### ISSUE TITLE
[NuGet.org Bug]: Dark mode README table issue

### ISSUE THREAD

**Issue by aarm1n** [NuGet/NuGetGallery#10065]
### Impact

It's more difficult to complete my work

### Describe the bug

When viewing a NuGet package using dark mode, every second table row in the README is unreadable because the background and text are the same color.

### Repro Steps

1. Use dark mode
2. Go to https://www.nuget.org/packages/RMN.Blazor.DragDrop
3. Find the table in the README

### Expected Behavior

![image](https://github.com/NuGet/NuGetGallery/assets/156656650/72b9213b-bebc-4b1a-9fef-fadab5a6be6c)

### Screenshots

![image](https://github.com/NuGet/NuGetGallery/assets/156656650/fa5f9390-3d01-4c57-85ca-d5ff31f400fd)

**Comment by erdembayar** [comment]
cc @martinrrm

**Comment by skofman1** [comment]
@mariaghiondea , @martinrrm , this issue is closed, but it still reproduces on nuget.org (https://www.nuget.org/packages/RMN.Blazor.DragDrop). Pending deployment? We should close issues only after deployment to production and verification of a successful fix.

**Comment by skofman1** [comment]
Fixed on prod
