### ISSUE TITLE
[NuGet.org Bug]: Interruption in restoring project dependencies

### ISSUE THREAD

**Issue by ravindra-aditya** [NuGet/NuGetGallery#10074]
### Impact

It's more difficult to complete my work

### Describe the bug

Constantly, getting feed interference issues whenever other services are interrupted or not working. 

**Error**: NU1301	Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.	

### Repro Steps

- Create an aspnetcore web api application and try to build, immediately the reported error is getting inferred. 

### Expected Behavior

if dotnet or related is having issue, why packages restore is having issue?

### Screenshots

![image](https://github.com/user-attachments/assets/bdde0095-4289-427c-aaed-e6a261b1cc3f)

**Comment by martincostello** [comment]
https://github.com/dotnet/aspnetcore/issues/56873#issuecomment-2236232378
