### ISSUE TITLE
De-emphasize Nuspec authors references to nuget.org

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/NuGetGallery#10070]
The documentation for `.nuspec` authors indicates that cross-referencing is done between `authors` and NuGet Gallery. See https://learn.microsoft.com/en-us/nuget/reference/nuspec#authors

> A comma-separated list of packages authors, **matching the profile names on nuget.org**. These are displayed in the NuGet Gallery on nuget.org **and are used to cross-reference packages by the same authors**.

I'd like to remove this verbiage entirely from the document, and focus instead on authors being a freeform metadata. Wanted to verify first whether any cross-referencing is done for other reasons I'm not aware of currently.

**Comment by erdembayar** [comment]
Could you please add screenshot? Not sure exactly which part you're referring.

**Comment by drewgillies** [comment]
@donnie-msft the document change is a good one, but I want to clarify that the message on the Package Details page is not from the authors entry in the nupec, but the copyright entry. 

For example, https://www.nuget.org/packages/Serilog/4.0.1-dev-02205 - this message is not from:
`<authors>Serilog Contributors</authors>`
but from
`<copyright>Copyright © 2013-24 Serilog Contributors</copyright>`

https://github.com/NuGet/NuGetGallery/blob/2341258cbd5dfd50cf40e48c116158b0e221bb40/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L1344

**Comment by donnie-msft** [comment]
Makes sense, thanks! So, is author not shown anywhere at all on nuget.org? Just to be clear, this has no impact on the docs change.

**Comment by donnie-msft** [comment]
> Could you please add screenshot? Not sure exactly which part you're referring.

@erdembayar the quote and the link with an anchor are provided. What specifically would you like to see?

**Comment by erdembayar** [comment]
> > Could you please add screenshot? Not sure exactly which part you're referring.
> 
> @erdembayar the quote and the link with an anchor are provided. What specifically would you like to see?

I wanted to see actual example and Drew already provided one.

**Comment by erdembayar** [comment]
@donnie-msft 
Should this issue be in the document repository?

**Comment by donnie-msft** [comment]
@erdembayar the docs issues were decommissioned in June. Where do you store them now? https://github.com/NuGet/docs.microsoft.com-nuget/ no longer supports issues.

**Comment by erdembayar** [comment]
> @erdembayar the docs issues were decommissioned in June. Where do you store them now? I assumed here since there is a Label "Area: Documentation". https://github.com/NuGet/docs.microsoft.com-nuget/ no longer supports issues.

1. I checked with team and I was told recommended new approach is `Encourage users to contribute the changes themselves` instead of creating just issue. Could be you able to create doc PR?
2. Alternative would be "Users should use the `Feedback` link at the top and bottom of each article."

So, we prefer not to track doc issue here.
