### ISSUE TITLE
[NuGet.org issue]: NuGet.org support unavailable

### ISSUE THREAD

**Issue by JKorf** [NuGet/NuGetGallery#10081]
### Impact

I'm unable to use NuGet.org

### Describe the bug

NuGet.org support is unavailable or unresponsive depending on the topic of the support request.

Specifically when information about the `Binance.Net` package is requested it seems the message is lost along the way.

Jokes aside; NuGet support is only reachable via email (or webform, but that's basically the same). Not receiving any answer on sent messages for over 2 weeks on why my package is unlisted doesn't seem right. 

### Repro Steps

1. Develop / maintain a NuGet package for 7 years and build up a user base
2. Report a package with a similar name to your own package for artificial download numbers on the NuGet gallery
3. Receive confirmation from NuGet support that the package has been unlisted after investigation
4. Realize your own package is now also unlisted

NuGet support will now no longer respond to any questions around the package. Note that requests unrelated to this are still possible.

### Expected Behavior

When a package is unlisted information should be given to the owner, and questions should be answered. Especially if this seems to be an error.

The package doesn't break any rules so I'd like to have it (and the account publishing it) restored.

**Comment by monwazchh** [comment]
Why was such a wonderful and useful library removed?

**Comment by Bradtus** [comment]
Can attest, his packages are legit and the best out there. Seems like NuGet flagged his package by mistake. Please escalate this so it can be investigated again.

**Comment by hat013579** [comment]
What is going on GitHub? We need these updates! Isnt there any support who can fix this? Or at least let us know what is happend. Thanks!

**Comment by JonDouglas** [comment]
Hello,

I personally looked into this situation, and it should be remediated appropriately. I apologize for the confusion that took place with the support team and the proper actions have been taken. Please reach out to myself or the @nuget X account if this hasn't been resolved appropriately.

https://www.nuget.org/packages/Binance.Net/8.0.9
