### ISSUE TITLE
[NuGet.org Bug]: MonitoringProcessor can hang in KV secret injection

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#10146]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I noticed this bug in DEV and in INT but, thankfully, not in PROD. 

The `SecretDictionary` type of ours is used by `Ng` for storing secrets. It uses our `ISecretInjectory.InjectAsync` but is a sync context. We can change this to be sync all the way down to avoid deadlocks. 

### Repro Steps

Let MonitoringProcessor restart. It does so every 24 hours. Sometimes, it will hang on secret injection.

### Expected Behavior

This job should not hang. We should avoid sync-over-async.

### Screenshots

<img width="853" alt="image" src="https://github.com/user-attachments/assets/ba8dbaa6-4aab-4d2b-b7e5-59c8b640a0ad">

**Comment by erdembayar** [comment]
@joelverhagen 
Could we close this PR since your PR is already merged?

**Comment by joelverhagen** [comment]
I still need to deploy it.
