### ISSUE TITLE
[NuGet.org Bug]: Intermitient certificate failures

### ISSUE THREAD

**Issue by glennawatson** [NuGet/NuGetGallery#10168]
### Impact

I'm unable to use NuGet.org

### Describe the bug

when using NuGet.org I am signing using Azure Trusted Signing the certificate.

I extract the certificate using normal tools, and upload the CER file

The upload validation fails saying there isn't a certificate of the SHA256 found. Even though the certificate uploaded now has a valid name listed against it (which it wasn't previously)
![image](https://github.com/user-attachments/assets/c020a600-19b2-44ba-ac98-42c88f0e2f41)

I check the SHA256 and it matches using the algorithm mentioned (I would provide a screenshot

I am used the cli sign with ATS support, signtool, and jsign

Also NuGet package explorer lists it as a valid certificate 
![image](https://github.com/user-attachments/assets/cdff6d7f-7c15-4c16-9135-c90733ab472f)

I wouldn't be shocked if there is some certificate issue that nuget.org doesn't like and its showing that generic error message?

This used to be a dotnetfoundation owned package (removed the ownership so I can test ATS for the foundation), and DNF has special rules around signing certificate lockouts so not sure if that has something to do with it?

the package name is `Splat`

### Repro Steps

1. Sign a package with ATS
2. Extract the package using certificate extraction tools
3. Upload the CER files
4. Upload the NuGet package.

### Expected Behavior

That when you upload the valid CER file, and have it listed that it

**Comment by glennawatson** [comment]
Whats worse, I'm finding some packages successfully being uploaded passing validation with the same certificate, and some not.

**Comment by glennawatson** [comment]
Adding details from here; 

https://github.com/NuGet/NuGetGallery/issues/10027#issuecomment-2324112239

Seems to happen only on packages that have ever been owned by the DotNetFoundation user 

Packages never owned by that user (and have the certificate) are able to be published.

**Comment by erdembayar** [comment]
We'll check internally first.

**Comment by erdembayar** [comment]
> This used to be a dotnetfoundation owned package (removed the ownership so I can test ATS for the foundation)

 Could you please provide us with more context details? What does ATS stand for? When and why was the DNF owner removed? Did you remove the DNF owner or did the DNF owner remove themselves?

**Comment by clairernovotny** [comment]
Hi @glennawatson,

We looked closer and don't see any issues that should be blocking this publish. Can you please resign the package (you can use the same version), upload the public certificate to one of the package owner accounts and then try publishing it again?

**Comment by glennawatson** [comment]
> Hi @glennawatson,
> 
> We looked closer and don't see any issues that should be blocking this publish. Can you please resign the package (you can use the same version), upload the public certificate to one of the package owner accounts and then try publishing it again?

Yeah that's what I been doing.

Having a issue where some of Splat is passing vertification (with the same certificate using the ATS sign tool) and the other half is not.

**Comment by glennawatson** [comment]
> > This used to be a dotnetfoundation owned package (removed the ownership so I can test ATS for the foundation)
> 
> Could you please provide us with more context details? What does ATS stand for? When and why was the DNF owner removed? Did you remove the DNF owner or did the DNF owner remove themselves?

ATS = azure trusted signing.

Claire has been involved in the discussions with that team so has some back story so might be worth chatting to her.

In terms of the DNF user, at the moment if you want to use your own certificate you have to remove the DNF user. At the moment there are special rules around the DNF owner and certificates. We been talking as a board and looking at relaxing those. Project committee has agreed upon a relaxed criteria for a BYO certificates (from a valid authority only). As per @JonDouglas request we will be making that request somewhere hear for public debate.

**Comment by glennawatson** [comment]
@clairernovotny sent you an email with some of the certificate details and further details.

**Comment by glennawatson** [comment]
Closed since there's a work around.
