### ISSUE TITLE
[NuGet.org Bug]: Wrong version in API V3

### ISSUE THREAD

**Issue by askovpen** [NuGet/NuGetGallery#10164]
### Impact

Other

### Describe the bug

in api v3 latest stable version 3.2.3
on [SqlKata](https://www.nuget.org/packages/SqlKata/) 2.4.0

### Repro Steps

https://api.nuget.org/v3-flatcontainer/sqlkata/index.json
```
{
    "versions": [
        "1.0.0-beta-1",
      ...
        "2.4.0",
        "3.0.0-beta",
        "3.2.3"
    ]
}
```

### Expected Behavior

need:
```
{
    "versions": [
        "1.0.0-beta-1",
      ...
        "2.4.0",
        "3.0.0-beta",
    ]
}
```

**Comment by askovpen** [comment]
How to get latest stable (not hidden) version with api v3?

**Comment by joelverhagen** [comment]
You use the package metadata resource and filter out the unlisted versions. This is what the version selection list in the Visual Studio package management UI does (roughly).

https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#get-package-metadata
(see `package.IsListed` in the sample).

You can sort them by `package.Identity.Version` to get the latest SemVer version.
