### ISSUE TITLE
[NuGet.org Bug]: Make "Validation" Faster #5183 (The closed issue in 2017 still exists

### ISSUE THREAD

**Issue by georgemesseha** [NuGet/NuGetGallery#10177]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Uploading nuget package takes forever. This is a serious blocker of our work. It doesn't have the same behavior all the time. This issue is old since 2017 with the number #5183. But actually it's still there.

### Repro Steps

Try to upload a nuget package at different times and check the time it takes to be published

### Expected Behavior

Uploading new nuget packages takes a reasonable time.

### Screenshots

![image](https://github.com/user-attachments/assets/a563c68a-c19d-42c9-ba0d-da1a6b716513)

**Comment by eventsourcer** [comment]
Happening for me as well.
"Package validation is taking longer than expected. This is not normal, but we are on it!"

**Comment by joelverhagen** [comment]
Hey folks, apologies for the publishing delay. We had an outage in our validation subsystem which lasted for several hours. The issue is now resolved. In the future, feel free to check for latest information on our status page:
https://status.nuget.org/

**Comment by eventsourcer** [comment]
thanks for resolving this @joelverhagen
