### ISSUE TITLE
Referencing packed images in readmes

### ISSUE THREAD

**Issue by eventsourcer** [NuGet/NuGetGallery#10182]
while packed package icon and readme is readable by nuget, I am wondering why not images as well.

Use cases: referencing images in readmes

If I can understand properly, referencing packed image doesn't seem to be from a trusted source/domain.

**Comment by erdembayar** [comment]
Dup of https://github.com/NuGet/NuGetGallery/issues/9959
Could you please upvote the above issue? We prioritize based on community engagement such as upvote and comment.
