### ISSUE TITLE
[Feature]: WebHooks 

### ISSUE THREAD

**Issue by itaibh** [NuGet/NuGetGallery#10181]
### Related Problem

I need to know when a package was uploaded, when it was published, if its validation gets delayed etc. automatically and without registering emails for some automation purposes. For that I'd need webhooks set up, either by placing a URL in the account settings to which a REST message (JSON) will be sent, with the package name, version, and status.

I understand I can do so by polling, but it's inefficient for both sides.

### The Elevator Pitch

I need to know when a package was uploaded, when it was published, if its validation gets delayed etc. automatically and without registering emails for some automation purposes. For that I'd need webhooks set up, either by placing a URL in the account settings to which a REST message (JSON) will be sent, with the package name, version, and status.

I understand I can do so by polling, but it's inefficient for both sides.

### Additional Context and Details

Example JSON:

```
{
    "package": {
        "name": "MyNuget",
        "version": "1.0.0",
        "status": "published",
        "time": "2024-09-11T13:23:15.000Z"
     }
}
```

**Comment by erdembayar** [comment]
Dup of https://github.com/NuGet/NuGetGallery/issues/1153
Could you please upvote above issue? We prioritize based on community engagement such as upvote and comment.
