### ISSUE TITLE
Allow for wildcard reservation of package names

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#103]
The RIA Services team would like to claim "RIAServices._" so that any RIAServices._ name is reserved for the RIA Services team.  We could create a convention where a name prefix can be claimed/reserved so that others cannot create a package.  Community contributions could still be named "RIAServicesFooBar," but "RIAServices.FooBar" would not be allowed because the product team owns "RIAServices." (with the dot)

**Comment by loic-sharma** [comment]
This is implemented by package ID prefix reservation: https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation
