### ISSUE TITLE
[NuGet.org Bug]: Github repository dependenc list should not include package's own repo

### ISSUE THREAD

**Issue by tonyqus** [NuGet/NuGetGallery#10310]
### Impact

It's more difficult to complete my work

### Describe the bug

I found a few times that a nuget package lists its own repo as the dependent Github repo. Since I saw it again today, I'd like to open an issue for this.

### Repro Steps

Nuget Url: https://www.nuget.org/packages/FileSignatures
Github Repo URL: https://github.com/neilharvey/FileSignatures/

### Expected Behavior

It should not list its own Github repo as a dependent repo.

### Screenshots

![image](https://github.com/user-attachments/assets/ba36071a-a55a-45db-b719-5489b9b0d4c1)

**Comment by joelverhagen** [comment]
This appears to be a duplicate of the issue you filed in the past:
https://github.com/NuGet/NuGetGallery/issues/9441
We'll keep the older one for tracking.

**Comment by tonyqus** [comment]
There is an easy fix for this

If(Source Repo or project url==dependent repo URL)
    exclude it from the dependent list.
