### ISSUE TITLE
Allow uploading 128 x 128 custom icon for package 

### ISSUE THREAD

**Issue by ghost** [NuGet/NuGetGallery#1074]
Ported from client work item here: https://nuget.codeplex.com/workitem/3276

The NuGet website shows images in a size of 128x128. The Visual Studio NuGet client shows images in 32x32. This results in ugly scaling issues, especially around aliased fonts. 

 It would be good if NuGet would:
1.Standardize the resolution of icons (medium = 32x32, large = 128x128)
2.Support specifying two icon URLs in the NuSpec file

dotnetjunky's comment:

This should be a feature on the NuGet gallery. Ideally, the gallery should have an option to upload image in 128x128 dimension and use it to show package icon.

**Comment by 304NotModified** [comment]
I like this idea. Yes, in sync with nuspec is nice,  but this is a practical approach (and maybe until the nuspec is extended)? 

So +1

**Comment by lindexi** [comment]
Good +1 

I want to upload 128 x 128 custom icon
