### ISSUE TITLE
Provide a way to "Contact Support" for multiple packages in one go

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#1129]
1. Consider an organization which has uploaded 50 + packages to nuget.org.
2. User A who is the owner of the packages leaves the organization.
3. Some one from the team need to "Contact support" to claim ownership on these packages.
4. Today, they need to do it individually for each package (and each version in a package).
5. This is an overhead from the user side and the support team side too (as there will be multiple requests in the place of one).

It would be good if "contact support" provides a way to list and multi select packages ( that the current user owns) and submit a single request.

**Comment by skofman1** [comment]
Contact support allows to send a message. In that message the user can specify whatever information he needs. So one message will be enough.
