### ISSUE TITLE
Provide a way to accept package ownership from ~/Accounts

### ISSUE THREAD

**Issue by pranavkm** [NuGet/NuGetGallery#1131]
Right now I can see the list of users that are pending approval for packages that I have ownership of. However the only way to accept ownership is through the confirmation email that we send. If this email is lost or forgotten, there's no indication in the gallery that a user has pending ownership requests.

It would be great if we could introduce a section in the Manage Packages tab that let you process these requests

**Comment by skofman1** [comment]
this was done. 
/cc: @scottbommarito
