### ISSUE TITLE
Site UI layout is broken in IE7 when the Alert bar is being displayed.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1150]
Right now, when a user navigates the site in IE7 while there is a message to display in the Alert bar, only some of the elements on screen automatically shift downward as the bar pops into view on page load.  

To reproduce this, follow these steps:
1.  Navigate to http://qa.nugettest.org/Users/Account/LogOn in IE7. (For the record, I'm doing this on English Windows Vista Ultimate x64, SP2)
2.  Observe that only some of the UI elements shift downward as the alert bar pops into view.

![ie7-2](https://f.cloud.github.com/assets/1505144/520435/37bc16b0-bf38-11e2-8002-f543fbcfd3cd.png)

Given this constraint, we ought to consider having the Alert bar be static in our site UI.

**Comment by maartenba** [comment]
Obsolete
