### ISSUE TITLE
Accessibility:  Turning off displaying images in the browser renders the navigation bar unreadable.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1174]
1.  In Internet Explorer, turn off displaying pictures (i.e. In Internet Options, go to the Advanced tab, and under Multimedia uncheck Show Pictures).
2.  Navigate to https://nuget.org/.  You may have to press Ctrl-F5 to load the page without hitting the browser cache.

Result:  The white text of the navigation bar links will render against a white background, rendering the site unreadable.
Expected:  We should look into a way to render a toolbar that doesn't depend on images.  This isn't a WCAG scenario, but it does affect compatibility with platform settings, making it potentially high-impact for users.

**Comment by johnataylor** [comment]
We have a new gallery design.
