### ISSUE TITLE
Accessibility:  Turning off images or using large fonts causes front-page hero text to spill over, breaking UI

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1175]
Scenario 1:

1. In Internet Explorer, turn off displaying pictures (i.e. In Internet Options, go to the Advanced tab, and under Multimedia uncheck Show Pictures).
2. Navigate to https://nuget.org/. You may have to press Ctrl-F5 to load the page without hitting the browser cache.

Result: The gray bar in which the hero text ("Jump Start Your Projects with NuGet ...") is shown is scaled only to the height of the image, which is minimal.  The text that normally appears in this section spills down into the user count bar underneath it, breaking layout and confusing users.

Scenario 2:

1. In Internet Explorer, set text size to 'Largest' (from the View menu, choose Text Size -> Largest).
2. Navigate to https://nuget.org/. 

Result: The same text will again spill out of the hero box into the user count bar underneath it, breaking layout.

Expected:  Our UI should be more adaptive to users' custom browser settings.  In this case, I'd expect the hero bar to resize to accommodate both the text and the screenshot, not just the latter.

**Comment by johnataylor** [comment]
We have a new gallery design.
