### ISSUE TITLE
Accessibility (WCAG level A) HTML 5 Validation error in meta tag on layout page

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1177]
1.  Go to http://validator.w3.org/ and validate the page http://nuget.org/

Result:  There will be a single HTML validation error, caused by our use of a non-standard value in the http-equiv attribute of the following meta element:

        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

Expected:  Since a well-formed page with a doctype will render in standards mode anyway, this entire element is superfluous.  We should get rid of it.

**Comment by johnataylor** [comment]
We have a new gallery design.
