### ISSUE TITLE
Accessibility (WCAG level A) HTML 5 validation error on Packages page because of the use of an hgroup element

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1178]
1.  Go to http://validator.w3.org/ and validate the page https://nuget.org/packages.

Result:  In addition to other validation errors which I've logged elsewhere, there is a validation error message triggered by our use of an hgroup element:

Error Line 49, Column 23: The hgroup element is obsolete. To mark up subheadings, consider either just putting the subheading into a p element after the h1-h6 element containing the main heading, or else putting the subheading directly within the h1-h6 element containing the main heading, but separated from the main heading by punctuation and/or within, for example, a span class="subheading" element with differentiated styling. To group headings and subheadings, alternative titles, or taglines, consider using the header or div elements. 

Expected:  I don't see a good reason why we can't take the last of these suggestions and have a span styled to be a block element within the header to achieve the desired visual and semantic effect.

**Comment by johnataylor** [comment]
We have a new gallery design.
