### ISSUE TITLE
Accessibility (WCAG level A) HTML 5 validation error on Packages page because form's action attribute is empty

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1179]
Go to http://validator.w3.org/ and validate the page https://nuget.org/packages.

Result: In addition to other validation errors which I've logged elsewhere, there is a validation error message triggered by the page's form tag having an empty action attribute. 
Expected:  We ought to be able to set it to "/packages" and achieve the desired result.

**Comment by johnataylor** [comment]
We have a new gallery design.
