### ISSUE TITLE
ASP.NET  Request Validation blocks valid search queries that contain angle brackets

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1191]
We've made some improvements to search to enable search terms that include punctuation, but users today can't search for expressions that contain angle brackets on the site because of ASP.NET's default restriction against them.

To repro:
1.  Navigate to nuget.org 
2.  Search for any of the following:
        &lt;system.web>
        <!DOCTYPE
        <?xml
        <?php

Result:  You'll be directed to the white screen of death (Oh no...).  A review of ELMAH shows that no error is logged there for this.
Expected:  Not having this impedes users of angle-bracket languages form searching for packages based on code snippets or samples, and deters owners from supplying them.  In all of the above cases, this is a shame, because each are frequently used as shorthand by people familiar with the technologies in question.  We only echo the search results back to the user in one place, and making sure it's properly encoded would seem to be a trivial task. 

Note that this is specific to the gallery; this doesn't repro in the NuGet client.

**Comment by robertmuehsig** [comment]
Was this reopened in error or is there anything still to do here?
