### ISSUE TITLE
Display the License for a package

### ISSUE THREAD

**Issue by analogrelay** [NuGet/NuGetGallery#1258]
We're working on a system to display the "friendly name" of a package license based on analyzing its metadata

[anurse]
Test Plan Notes:
NOTE: These all require that the latest worker has been deployed AND that data is arriving in the License tables and the Packages.LicenseNames/LicenseReportUrl columns.
- [ ] Deploy **without** new config setting (Feature.FriendlyLicenses)
- [ ] Verify that license report data only shows for Admins
- [ ] Verify that license report data is NULL in the OData feed
- [ ] Verify that the client does not display license report data
- [ ] Set web.config value "Feature.FriendlyLicenses" = true
- [ ] Verify that license report data shows
- [ ] Verify that owner can disable license report, and that they continue to see it (but other users do not see it)
- [ ] Verify that license report data is NULL in the OData feed when owner opts out
- [ ] Verify that license report data is not shown in client when owner opts out

**Comment by hickford** [comment]
This is important. People need to know what license software is, especially when they create new software that depends on it.

Other package managers show licence information in a clear, consistent and machine-readable format:

1. https://rubygems.org/gems/pony "LICENSE: MIT"
2. https://pypi.python.org/pypi/numpy "License: BSD"
3. https://www.npmjs.com/package/karma "MIT license"

The NuGet gallery doesn't show licenses clearly or consistentlys:

1. https://www.nuget.org/packages/EntityFramework/ (licence hidden behind link)
2. https://www.nuget.org/packages/angularjs/ (licence missing)

Please reopen this issue.
