### ISSUE TITLE
Statistics navigation/drilldown suggestion

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1308]
I found the navigation/drilldown for the existing statistics pages didn't work the way I expected (after coming back to the packages with fresh expectations after a while).

**Problem:**
You cannot drill down into the by-version statistics for a package from the package's overall statistics.

**Repro:**

1. Navigate to https://www.nuget.org/stats
1. Click on the downloads number for Newtonsoft.Json in the left-hand column (Downloaded Packages)
1. Click on a Version number in the table

**Expected:**
To be taken to the statistics page for that specific version

**Actual:**
Taken to the package details page for that version

**Note:**
You can get to the version-specific statistics page for package versions that make the Downloaded Package Versions list, but there's no drill down that gets you there for a version that isn't in that report (even though the page can render).

**Comment by johnataylor** [comment]
Site navigation issues are being fixed as part of the v3 gallery development.
