### ISSUE TITLE
Statistics:  Remove the OL numbers from the Downloaded Packages and Package Versions lists

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1364]
To repro:
1.  Navigate to https://qa.nugettest.org/stats
2.  Look at the download counts in the Downloaded Packages table

Result:  Because we're showing numeric rankings, the rankings in the adjacent table (Downloaded Package Versions) overlap with the download counts of the Downloaded Packages table, making both hard to read.
Expected:  Both lists are short enough that then rankings are unnecessary. (See "The magical number seven, plus or minus two" at http://www.psych.utoronto.ca/users/peterson/psy430s2001/Miller%20GA%20Magical%20Seven%20Psych%20Review%201955.pdf .)  We should remove them.

![oloverlap](https://f.cloud.github.com/assets/1505144/864331/3db7b8e4-f61f-11e2-969a-7a720fbf5b7a.png)

**Comment by johnataylor** [comment]
site visual issues are being fixed as part of the v3 gallery development
