### ISSUE TITLE
Statistics:  In extreme cases, the axis label "Downloads" is cut off on Downloads charts

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1365]
If the first column in any of the downloads charts shown in the Statistics section is large enough, it can cut off the word "Downloads", making it hard to read.

To reproduce:
1.  Navigate to https://qa.nugettest.org/stats.
2.  Look at the "NuGet Client Usage (Last 6 Weeks)" chart.

Result:  The "Downloads" caption is cut off. (See image below.)
Expected:  We should either print "Downloads" on the other side of the axis line or enforce a minimum gap between the axis line and the first bar to prevent this from happening in the future.

![downloadscutoff](https://f.cloud.github.com/assets/1505144/864428/1c9e05da-f621-11e2-8a08-80f681461cf2.png)

**Comment by johnataylor** [comment]
Site visual bugs are being fixed as part of the v3 gallery development.
