### ISSUE TITLE
Host icons in our blob storage

### ISSUE THREAD

**Issue by Haacked** [NuGet/NuGetGallery#14]
Rather than allowing embedded icons (which, while useful, is a much more complicated feature), let's download Icons from the IconUrl and use those in the feed and website (we will not rewrite the NuPkg), that way we can host the icons ourselves and support HTTPS.

We may still investigate embedding icons in packages, but for now the main priority is taking the bandwidth burden of hosting and SSL support off of the package author and on to us.

--
Previous version as filed by @Haacked 
--

**Allow including icon and license within package**

[Original Spec](http://nuget.codeplex.com/wikipage?title=Packages%20Containing%20Icon%20and%20License)

Icons:
* Icon_dialog.png (32x32)
* Icon_list.png (50x50)
* Icon_details.png (100x100)

License:
License.txt

Related Issue: [Automatically resize images](https://github.com/NuGet/NuGetGallery/issues/15)

**Comment by johnataylor** [comment]
We have a new gallery design and infrastructure that addresses this.
