### ISSUE TITLE
Allow multiple API Keys, but store them hashed

### ISSUE THREAD

**Issue by anurse** [NuGet/NuGetGallery#1404]
While investigating Auth I looked up info on some other services. One thing that stuck out for me was Google's "App-specific Passwords" model for allowing apps that do not support two-factor auth to authenticate with Google Accounts. I think we should adopt a similar model in NuGet moving forward.

So, an account should be able to have multiple API Keys, each with a name. New API Keys generated in this model would be hashed and thus **not recoverable**. When the user adds a new API Key, we send the plaintext (over SSL) once and then store the hashed value. This means that API Keys can never be retrieved again, only Revoked or Reset to a **new** random value. Using this model also encourages users to generate a new key whenever they need to set up a new build server or other automated pusher, which makes it easier to audit who pushes what. Any API Key attached to an account would be authorized to push packages on behalf of that user, and an audit log of which API Key was used to push a particular package would be recorded for use by Support in resolving issues (and possibly displayed to package owners at a future date).

**Comment by skofman1** [comment]
Feature in progress: https://github.com/NuGet/NuGetGallery/issues/3246
