### ISSUE TITLE
Remove offensive language from our source code

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1435]
There are a few examples of offensive or suspect language buried in our source code.  We should proactively clean up our source code now to avoid the chance that one of these terms could offend future contributors.

<table>
  <tr>
    <th>File</th><th>Line</th><th>Term</th><th>Context</th>
  </tr>
<tr><td>Facts\Services\PackageServiceFacts.cs</td><td>1079</td><td>damn</td><td>// Nothing to assert because it's too damn complicated to test the actual LINQ expression.</td></tr>
<tr><td>Website\PackageCurators\TagBasedPackageCurator.cs</td><td> 26</td><td>foobar</td><td>// Break the tags up so we can be sure we don't catch any partial matches (i.e. "foobar" when we're looking for "foo")</td></tr>
<tr><td>Website\Infrastructure\Lucene\LuceneSearchService.cs</td><td> 283</td><td>foo-bar</td><td>// 3) For ID search, split search terms such as Id:"Foo.Bar" and "Foo-Bar" into a phrase "Foo Bar" which will work better for analyzed field search</td></tr>
<tr><td>Website\Infrastructure\Lucene\LuceneSearchService.cs</td><td> 201</td><td>foo bar</td><td>// a) General search? [foo bar]</td></tr>
<tr><td>Website\Infrastructure\Lucene\LuceneSearchService.cs</td><td> 202</td><td>foo bar</td><td>// b) Id-targeted search? [id:Foo bar]</td></tr>
<tr><td>Website\Infrastructure\Lucene\LuceneSearchService.cs</td><td> 203</td><td>foo bar</td><td>// c)  Other Field-targeted search? [author:Foo bar]</td></tr>
<tr><td>Website\Infrastructure\Lucene\LuceneSearchService.cs</td><td>301</td><td>foo bar</td><td>// 3) For ID search, split search terms such as Id:"Foo.Bar" and "Foo-Bar" into a phrase "Foo Bar" which will work better for analyzed field search</td></tr>
<tr><td>Website\Infrastructure\Lucene\AnalysisHelper.cs</td><td>23</td><td>sucks</td><td>// This attribute way of getting token properties sucks, but it's the non-obsolete one.</td></tr>
<tr><td>Website\Services\PackageFileService.cs</td><td>78</td><td>sucks</td><td>// c) it sucks to hit the database just to look up the right case</td></tr>
<tr><td>Website\DataServices\SearchAdaptor.cs</td><td>128</td><td>hack</td><td>// HACK: The way the default paging works is WCF attempts to read up to the MaxPageSize elements. If it finds as many, it'll assume there</td></tr>
</table>

**Comment by NullVoxPopuli** [comment]
sounds like the code should just be improved, rather than nice-ifying the comments.

**Comment by NeLaurynas** [comment]
Here comes open source pussies with their codes of conducts AND DID YOU JUST ASSUME MY GENDER??? GITHUB IS SAFE SPACE!

Why do we, hardened enterprise developers with balls, comply with these... garbage?

**Comment by blowdart** [comment]
You realise this was from 2013, right? I'm locking this, because this just isn't useful or constructive in any way.
