### ISSUE TITLE
GetUpdates scrambled response when no versionConstraints and targetFrameworks are provided

### ISSUE THREAD

**Issue by shayke** [NuGet/NuGetGallery#1502]
I'm not sure if the versionsConstrains and targetFrameworks are mandatory parameters, but I see different responses:

OK:
https://www.nuget.org/api/v2/GetUpdates()?packageIds='jQuery|Newtonsoft.Json'&versions='1.0.0.0|5.0.4'&includePrerelease=true&includeAllVersions=true

Messed up response:
https://www.nuget.org/api/v2/GetUpdates()?packageIds='jQuery|Newtonsoft.Json'&versions='1.0.0.0|3.0.4'&includePrerelease=true&includeAllVersions=true

**Comment by maartenba** [comment]
Relates to #1502, #1886 and #1259 - found out this is a bug in `System.Data.Services` (also described at https://social.msdn.microsoft.com/Forums/en-US/6cc0ef87-80ec-4331-8b41-efb22d8f1c60/odata-provider-with-wcf-40-paging-operations-with-null-parameters?forum=adodotnetdataservices).

Created a pull request with the OData folks - https://github.com/OData/odata.net/pull/149

**Comment by maartenba** [comment]
Fixed.
