### ISSUE TITLE
Stats: Drill down from Install-Dependency and Update-Dependency into the dependent packages

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1507]
When viewing the [Package Downloads for a package version, grouped by Operation], you should be able to drill down into the Install-Dependency and Update-Dependency download numbers, into a page that shows which dependents (and their versions) were logged for those installations.

That would allow me to see a list (and a graph) of the packages/versions that were directly installed that caused the install-dependency/update-dependency.

**Comment by maartenba** [comment]
We no longer have this data in all cases
