### ISSUE TITLE
Skip the CDN for nuget.org/nuget.exe

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1512]
We need to skip the CDN when serving nuget.org/nuget.exe, serving it directly from blob storage.  This will allow the new version to be available immediately after pushing NuGet.CommandLine.

**Comment by xavierdecoster** [comment]
@deepakaravindr is this one still relevant?

**Comment by TimLovellSmith** [comment]
The was issue that there's no good way to tell CDN to refresh a certain URL and start serving latest content there, I expect that hasn't changed.
Have you considered doing anything to work around this from the client side like append a dummy query ?_=uniquifier to force bypassing CDN cache when getting nuget.exe?

**Comment by robertmuehsig** [comment]
Just scrolled through old issues: Is this still relevant with dist.nuget.org in place? 

I also noticed that https://nuget.org/nuget.exe will serve version 2.8.6 - is this by design?

**Comment by skofman1** [comment]
https://nuget.org/nuget.exe is no longer used. Closing the issue.
