### ISSUE TITLE
Exclude Restore from NuGet Client Version Usage Stats

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1520]
To get a more accurate picture of the NuGet client version usage, we should exclude Unknown and Restore operations from those stats.  I suspect (hope) that the reason 1.6 is so high on that list is because of nuget.exe-based package restores.

**Comment by maartenba** [comment]
@xavierdecoster is this still relevant?

**Comment by xavierdecoster** [comment]
Nope
