### ISSUE TITLE
Have a clean plain-text email format

### ISSUE THREAD

**Issue by membersuite** [NuGet/NuGetGallery#1539]
[Modified by @anurse]
Add a plain-text format without Markdown cruft to the email message. We may need to drop MarkdownMailer and do manual markdown processing followed by standard .Net SMTP calls.

Original Report:
I can't login, and when I try to get my password, I get the email but the link brings me to an error screen. The account is 'membersuite' - please help, can't login.

**Comment by skofman1** [comment]
Haven't had similar complaints in the last few years.
