### ISSUE TITLE
Captcha shouldn't be required for reporting your own package to gallery owners.

### ISSUE THREAD

**Issue by TimLovellSmith** [NuGet/NuGetGallery#1562]
Just noticed this oddity of our code.

**Comment by AlexBHarley** [comment]
Can this be closed? Not sure how to report my own package. Has this been removed?

**Comment by maartenba** [comment]
@xavierdecoster can you check if this is still relevant?

**Comment by xavierdecoster** [comment]
Seems this is already fixed. Thanks for bringing this issue under our attention!

FYI: this is the URL to report one of your own packages
`https://www.nuget.org/packages/{PackageId}/{PackageVersion}/ReportMyPackage`
