### ISSUE TITLE
404 error when clicking 'Cancel' on package upload while Javascript is disabled.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1583]
1.  Turn off JavaScript in the browser of your choice.  (In IE, It's Tools -> Internet Options, switch to the Security tab, select the Internet Zone, click the "Custom level" button and then select "Disable" under Scripting -> Active Scripting.)
2.  Navigate to https://qa.nugettest.org/packages/upload, 
3.  Choose a package using the file picker, 
4.  Click "Upload"
5.  On the Validate Upload page, click "Cancel"

Result:  You'll get a 404 error.
Expected:  I'd expect a user should be able to cancel without depending on JavaScript being turned on.

**Comment by skofman1** [comment]
JavaScript is a core part of how our site operates.
