### ISSUE TITLE
No easy way to supress Friendly License reports across all versions of a package

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1586]
Right now, there's no way to turn off friendly licenses for all versions of a package.  If there are a large number of versions, this can be a problem for package owners who have to manipulate this setting separately on dozens of package versions.

We should provide a way for folks to turn this setting on and off en masse more easily.

**Comment by skofman1** [comment]
@claycompton , @anurse how do we turn off friendly licence reports for a package? I'm trying to understand this issue.

**Comment by skofman1** [comment]
An option to suppress Friendly license reports must have been removed a while ago..
