### ISSUE TITLE
Invalid version numbers in nuspec trigger an unhandled exception (WSOD) on upload.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1640]
1. Create a .nupkg file by hand whose version number in the nuspec is invalid (for the purposes of this example, let's assume it's 0.0.0.0.0).
2. Attempt to upload it using the gallery UI.

RESULT:  You'll get an unhandled exception on upload.  Investigating error logs reveals the underlying error is an ArgumentExeption with the error message:

System.ArgumentException: '0.0.0.0.0' is not a valid version string. Parameter name: version

The full stack trace is available at https://qa.nugettest.org/Admin/Errors.axd/detail?id=2213.
EXPECTED:  We should never WSOD on customers, even in fringe scenarios like this. If we can treat invalid package uploads in the Gallery the same way we do for validation errors, that would be ideal.

**Comment by johnataylor** [comment]
We need much better validation.

**Comment by joelverhagen** [comment]
This no longer happens.

Web UI:
![image](https://user-images.githubusercontent.com/94054/32625577-72158f80-c541-11e7-8b55-8aedce909d6c.png)

Push from command line:
```
Pushing e2e.semver1stable.170503.225836.7811214.1.0.0.nupkg to 'https://dev.nugettest.org/api/v2/package'...
  PUT https://dev.nugettest.org/api/v2/package/
  BadRequest https://dev.nugettest.org/api/v2/package/ 623ms
Response status code does not indicate success: 400 (Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.).
```
