### ISSUE TITLE
Add Owner : check if already owner before adding.

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#165]
1. on /ManagePackageOwners there is not dup check.

Current Owners
 •aldion
 •aldionRemove
 •aldionRemove
 •aldionRemove

**Comment by xavierdecoster** [comment]
This is [being checked](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml#L68) since August 2013, time to close the issue :)
