### ISSUE TITLE
Unable to create SQL Server database

### ISSUE THREAD

**Issue by jeradrose** [NuGet/NuGetGallery#1656]
I am trying to set up the [Github NuGetGallery](https://github.com/NuGet/NuGetGallery) using the setup instruction on the repo page, and create a SQL Server database instead of EF LocalDB.

However, The `UpdateDatabase` command to create the database seems to only recognize LocalDB. Even after updating the web.config connection string to point to my local SQL Server Express database:

```
Data Source=.\SQLEXPRESS;Initial Catalog=NuGetGallery;Integrated Security=SSPI
```

It only connects to LocalDB. I verified this by using `-Verbose`, and it shows trying to connect to LocalDB, saying the database is up to date:

> PM> Update-Database -Verbose
> Using StartUp project 'NuGetGallery'.
> Using NuGet project 'NuGetGallery'.
> Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
> Target database is: 'NuGetGallery.EntitiesContext' (DataSource: (localdb)\v11.0, > > Provider: System.Data.SqlClient, Origin: Convention).
> No pending code-based migrations.
> Running Seed method.

I found a few articles (possibly for an older version of the NuGet Gallery) instructing to run the site and it will create the database if it doesn't exist. But when I try this, all I get are errors trying to execute procs that don't exist:

> Invalid object name 'dbo.Packages'.

And then when trying to log this error:

> Could not find stored procedure 'ELMAH_LogError'.

I tried changing the connection string back to using LocalDB just to make sure that worked, and it does -- I only get errors when trying to connect to the local SQL Server DB.

I also tried running this without the database even being created, thinking that the setup process included creating the database, and that the database existing made it think it was actually populated. But this resulted in the obvious error:

> Cannot open database "NuGetGallery" requested by the login. The login failed.
> 
> Login failed for user 'Jerad'.

I found [this wiki article](https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS) and tried following it, but the build command doesn't seem to produce the indicated `_PackagedWebsite` folder, possibly because the build results in a warning when trying to run the functional tests:

> warning : The referenced project '..\NuGetGallery.Frontend.FunctionalTests.Helpers\NuGetGallery.FunctionalTests.Helpers.csproj' does not exist. [C:\Users\Jerad\Documents\Visual Studio 2012\Projects\NuGetGallery-master\tests\NuGetGallery.FunctionalTests\NuGetGallery.FunctionalTests.csproj]

I'm assuming I'm doing something wrong, because I've searched online and through the closed issues here, and nobody seems to be having this problem. So my apologies in advance for what is likely a silly mistake on my part. But I've exhausted all of the options I can think of at this point.

**Comment by ekumachidi** [comment]
Hi Not sure of where to go to:
I get this error `A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)` when i run `Update-Database -verbose`.
I noticed this in the log `'DefaultConnection' (DataSource: .\SQLEXPRESS, Provider: System.Data.SqlClient, Origin: Convention)` but I am not using SQLEXPRS i have the enterprise verion installed

**Comment by robertmuehsig** [comment]
Can you access your MS SQL instance via the Visual Studio Data Tools or via SQL Management Studio?

**Comment by ekumachidi** [comment]
yes I can assess MS SQL via management studio.

I changed the connection string as follows: 
`<add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=eCommerce;Integrated Security = true"/>` to use localdb

Or 
`<add name="DefaultConnection" connectionString="Data Source=.;Initial Catalog=eCommerce;Integrated Security = true"/>` to use the default instance

When I run `Update-Database -verbose`

I notice this line in the console
`Target database is: 'DefaultConnection' (DataSource: .\SQLEXPRESS, Provider: System.Data.SqlClient, Origin: Convention).`

It means it still tries to use sqlserver express which is not in the connection string

And my installation is not `SQLSERVER_EXPRESS` it is the developer edition of 2014 and vs2017 RC
