### ISSUE TITLE
Validation of newly uploaded packages

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#167]
Smoke test newly uploaded packages to ensure packages meet basic standards.

This also increases overall package quality on the gallery and mitigates risks such as defined in http://nuget.codeplex.com/workitem/1686

Maybe add some recommendations as well? (e.g. your package seems to be larger than average, consider splitting your package into multiple ones with proper dependencies if individual components can be used without requiring the full package contents)

**Comment by johnataylor** [comment]
Great idea Xavier. Let's add more validation to the publish service. And we probably want a more sophisticated protocol between the publish service and the new gallery.

**Comment by csharpfritz** [comment]
+1  

I like this idea in the grand-scope of package owner usability.  We should be able to 'fail fast' if a package is malformed, corrupted, or just doesn't work... preventing it from getting into the public gallery.

I see this functionality as very similar to the "WACK" Windows App Certification Kit.

**Comment by yishaigalatzer** [comment]
Here is some other new stuff we found lately

1. Mismatching nuspec to package name
2. a nupkg inside the package with the same name as the package

**Comment by maartenba** [comment]
Linking #2634

**Comment by xavierdecoster** [comment]
Assigning to you @joelverhagen.

Feel free to close/link this issue in favor of to the validation work you are doing.

**Comment by joelverhagen** [comment]
Thanks @xavierdecoster. This will be handled by https://github.com/NuGet/Engineering/issues/705.
