### ISSUE TITLE
Build Error with SSIS Script Task (C#) and Microsoft.Net.Http

### ISSUE THREAD

**Issue by hannam1971** [NuGet/NuGetGallery#1702]
When using an Integrated Services (SSIS) Project in Visual Studio 2012, when a C# Script Task is added to the Project, and the Microsoft.Net.Http package is added through NuGet 2.7, and the script is Built, the following error occurs:

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.

Steps to reproduce problem:
1. Within Visual Studio 2012, create a new Project of type "Business Intelligence - Integration Services"
2. Add a "Script Task" to the Control Flow.
3. Go to edit the script.
4. Add the "Microsoft.Net.Http" package within NuGet Package Manager Console (PM> Install-Package Microsoft.Net.Http).
5. Click to Build the C# code, and error occurs.

NOTE: I first noticed this error with the Google.Apis,Auth NuGet package, but then after troubleshooting, found that it was because this package depends on Microsoft.Net.Http.  Also, this error does NOT occur if following the same steps in Visual Studio with a C# Console Application.

**Comment by unionthugface** [comment]
I would like this to be reopened.  The problem is that it inserts this code into the .csproj file:

```<Import Project="..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets')" />
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
  <PropertyGroup>
    <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
  </PropertyGroup>
  <Error Condition="!Exists('..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets'))" />
</Target>```

I do not believe SSIS can find '..\packages\ for some reason.  Is this still a Nuget problem?

**Comment by Kris824** [comment]
This issue has no solution?
