### ISSUE TITLE
Give Users Easy Recommendation of Open Source Compatible or Not

### ISSUE THREAD

**Issue by ericschultz** [NuGet/NuGetGallery#1705]
The gallery currently uses Sonatype to guess as to what license a package is under. We can use this information to help package users know whether the package they want to use is open source compatible or not.

The method of doing so might work as follows:

* Once Sonatype returns with it's prediction on the license, verify if that's an open source license.
* If it is an open source license, check whether it's dependencies are marked as open source compatible. If not, mark the package and not open source compatible.
* If all dependencies are open source compatible, the package is open source compatible as well. Otherwise, the package is not open source compatible.

This can be displayed in the UI in some fashion and ideally put into a curated feed providing people with packages we THINK are open source compatible.

**Comment by johnataylor** [comment]
This issue assumes the Sonatype license information mechanism is working robustly which is currently doesn't appear to be. Closing this as Won't Fix.
