### ISSUE TITLE
Word breaking for package Id doesn't work properly

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1722]
Create a package whose ID contains an unbroken group of over 90 non-whitespace chars in a row.
2. Upload this package.
3.  Navigate to the Contact Owners page

Result: Despite having implemented word-breaking in other parts of the application, there is no word breaking on this page, causing text to extend past the edge of most users' screens.
![contactowners](https://f.cloud.github.com/assets/1505144/1506043/dcb2b900-4906-11e3-82e7-8213d199dbe1.png)
Expected:  We should implement word-breaking consistently across the site's pages, including here.

**Comment by johnataylor** [comment]
we have a new gallery design.
