### ISSUE TITLE
WSOD when attempting to report abuse while Javascript is disabled.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1726]
1.  Disable JavaScript in the browser of your choice and navigate to the Report Abuse page of an existing package (e.g. https://qa.nugettest.org/packages/jQuery/2.0.3/ReportAbuse )
2.  Fill out the form, and then click Report.

Result:  You'll get a WSOD.  Examining the site logs reveals an System.InvalidOperationException that, oddly, appears to be ties to RECAPTCHA APIs.  The full stack trace can be seen at https://qa.nugettest.org/Admin/Errors.axd/detail?id=6313.
Expected:  I'd expect the flow of control to be the same regardless of whether JavaScript is enabled on the client.  In any case, we should be handling internal errors gracefully regardless of the reason.

**Comment by robertmuehsig** [comment]
Related: https://github.com/NuGet/NuGetGallery/issues/1803

I didn't could pass the captcha stuff without JS. Without JS it is super weird...
