### ISSUE TITLE
DB profiling : Refresh stats in HomePage every 2-5 minutes instead of 30 seconds

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#1736]
The queries made by Home Page refresh stats are one of the expensive queries made by Gallery (approx. 200 ms while the other queries take around 40-60 ms). It would be good to see if we can do some fine tuning here.

The javascript to refresh stats in home page runs every 30 seconds. Can it be less frequent ? Since the aggregate stats job runs only every five minutes, polling for stats every 30 seconds doesn’t add much value.

**Comment by johnataylor** [comment]
Understanding and addressing our database load has become a priority.
