### ISSUE TITLE
Always show prerelease packages when searching on the gallery

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1752]
The dropdown is stupid now.  There are bugs where we don't remember the user's choice.  And when I'm searching on the gallery, I don't care if it's prerelease or not because I cannot directly consume a package from the gallery.  When I go to consume the package in my project, I need to hit the Include Prerelease choice there.

Let's just ditch the dropdown on the gallery and ***always*** include prerelease on the website when browsing or searching packages.

**Comment by johnataylor** [comment]
We now show packages that only have pre-release versions. When you navigate to the package its very clear.
