### ISSUE TITLE
Redirected to "Do we Know You?" page if MSFT Account matches an unvalidated Nuget.org account.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1757]
1.  Create a brand new NuGet.org account on the qa.nugettest.org with an original e-mail address.  Don't validate it.
2.  Create a Microsoft Account with the same e-mail address.
3.  Log in to qa.nugettest.org with that Microsoft Account.

Result:  You'll be redirected to the "Do we know you?" page that is used for unidentified users.
Expected:  We ought to direct users to the "We found an existing account", just as we would if the account had already been validated.

**Comment by skofman1** [comment]
We changes the login flow. Closing.
