### ISSUE TITLE
Add a flag for marking packages as out of date

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#1764]
Porting from https://nuget.codeplex.com/workitem/3873

There are a lot of packages that are just not updated in time in Nuget. 

There is a system in use by ArchLinux's AUR (an user-generated software repository for that linux distribution) where logged in users can click a link called "Flag as out-of-date" in the package page. This is used to notify the owner of the package that the package there is out of date, and also to tell other people that the owner has been notified but the package has not been updated. Once the owner uploads a new package, the flag is cleared. 

It is a very simple, but very effective system. 

Nuget should support some way for users to report that, because it is very common not only for packages to be out of date, but some maintainers just forget to upload alpha/beta packages in time.

**Comment by nvivo** [comment]
Out of curiosity.  Was this closed because it was implemented or because it was discarded? Didn't see anything different on the website.

**Comment by johnataylor** [comment]
Discarded for now. We have a lot of old open issues and also a new gallery design that is quite developed.
