### ISSUE TITLE
Metadata validation:  THere's no validation error when uploading a package with an unsupported protocol in a URL field

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1805]
To repro:
1. Create a package using NPE.
2. Change its extension to zip and expand the package file
3. Edit the metadata to give the iconUrl field an unsupported protocol like "test://".
4. Zip the package with the new metadata and change the extension back to .nupkg
5. Attempt to upload the file through the gallery.

RESULT: There'll be no validation error at upload time. Instead, you'll get to the verify-upload page, but will be blocked from proceeding without any indication of the problem.
 EXPECTED: Like for other kinds of package validation that we've added in Iteration 6, this ought to generate a validation error when the user this to upload the package.

**Comment by johnataylor** [comment]
We need much better validation.
Perhaps we can collect all the validation gaps under a single validation issue?

**Comment by skofman1** [comment]
We are deprecating IconUrl per https://github.com/NuGet/Home/issues/352
