### ISSUE TITLE
Consider validating that the Owners field in package metadata matches the uploader's account.

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1806]
Right now, we don't do any validation of the Owners field in package metadata.  We should add this to match users' native expectation about the site.

To repro:
1.  Create a package using NPE with an author and owner of 'steveb' and "Steve Ballmer" respectively.  (This account doesn't exist.)
2.  While logged in as another user, upload the package.

Result:  The author value from package metadata will be kept as is, but the logged-in user will be the listed owner of the new package at the verify-upload stage of the process.  
Expected:  A discrepancy at this point between the logged-in user's name and the owner name in package metadata is a likely error; a likely cause is that the user is uploading a package from the wrong account.  We should try to flag this error so the user can correct it before uploading to save steps afterward.

**Comment by skofman1** [comment]
'owners' field was deprecated.
