### ISSUE TITLE
JavaScript error in IE7 and IE8 on Report Abuse page ("nodeName is null or not an object")

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1808]
1.  In either IE7 or IE8, go through the process of reporting abuse for an arbitrary package anonymously.

RESULT:  When you reach the Report Abuse page for the package of your choice, there will be a JavaScript error as per the title.
![jsie7](https://f.cloud.github.com/assets/1505144/1748267/6fe5e12c-64ad-11e3-90f6-acbd04440891.png)
Expected:  Regardless of cause, we shouldn't have end-user-visible javascript errors in any of the browsers we support.

**Comment by johnataylor** [comment]
this is the old gallery on and old browser. Closing
