### ISSUE TITLE
Scrub the WebMatrix feed for packages that depend on packages with powershell scripts

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1810]
The changes made in I6 for WebMatrix feed improvements are good, and block a vector for new packages that won't actually work in WM from entering the feed, but it should be pointed out that the repro scenario from #1311 still works verbatim.  As Xavier said at the time:

"Example: query for 'glimpse'.

"The Glimpse.Core package uses powershell and isn't shown.
"However, quite a few dependent plugin packages that don't use powershell are listed while useless."

We should now scrub the WebMatrix feed and drop packages that have grandfathered dependencies on packages that won't work in WM.

**Comment by maartenba** [comment]
Obsolete
