### ISSUE TITLE
Gallery needs to support "inferred portable platforms" that the NuGet client got in 2.7.2 with Xamarin Tools

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1815]
Xamarin tools update portable profiles' platform support.  The NuGet client was updated in 2.7.2 to respect these updates to the profiles and allow packages to be installed into projects where the packages didn't explicitly claim support.

We need to make sure that package consumers are able to get updates for packages when they are in this mode, which relies on the GetUpdates() call to the gallery that accepts the target framework.

We might not have a problem, but we need to verify it works and if not, address it.

**Comment by johnataylor** [comment]
We are tracking target framework issues elsewhere.
