### ISSUE TITLE
Deployment failure on Azure using External Repository feature

### ISSUE THREAD

**Issue by basnielander** [NuGet/NuGetGallery#1820]
Recently I tried to publish a NuGetGallery website on Azure using the "External Repository" feature. 
First I tried to publish the Gallery using the master branch, but that failed at installing the external libraries. After that I tried to publish the 'prod' branch. This deployment also fails, but after the external libraries are successfully installed. 

![nugetgallery deployment failure](https://f.cloud.github.com/assets/6238329/1800384/b1c08cd8-6bc3-11e3-8d49-37f06718224b.JPG)

The following errors are logged:

D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.Diagnostics, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.ServiceRuntime, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
Areas\Admin\Controllers\ConfigController.cs(9,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
Configuration\ConfigurationService.cs(11,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
Diagnostics\DiagnosticsNinjectModule.cs(10,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
Infrastructure\TableErrorLog.cs(8,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
App_Start\AppActivator.cs(14,30): error CS0234: The type or namespace name 'Diagnostics' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
App_Start\AppActivator.cs(15,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
Configuration\AppConfiguration.cs(10,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
App_Start\ContainerBindings.cs(10,30): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]
An error has occurred during web site deployment.
D:\Program Files (x86)\SiteExtensions\Kudu\1.25.21127.11\bin\scripts\starter.cmd build\DeployFrontend.cmd

Do I need to use another branch from the NuGetGallery or does something needs to be fixed?

**Comment by rholder613** [comment]
Still having the same trouble here!
