### ISSUE TITLE
While uploading package, the entry can be added to database, even if the upload to blob storage fails

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#1836]
While doing package upload, the package is uploaded to blob and then the changes to database is commited. Since this is not a single atomic action, failure in the former doesn't guarentee abortion of the latter. We need to add more checks around it.

**Comment by johnataylor** [comment]
This sounds like a Pri 1. Bug for packages upload from the command line. Can you confirm?

**Comment by maartenba** [comment]
Was this one fixed?

**Comment by skofman1** [comment]
This is still relevant: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/ApiController.cs#L328
@maartenba @qianjun22

**Comment by skofman1** [comment]
Was fixed.
