### ISSUE TITLE
No e-mail is sent to affected user when removing a user as a package's owner

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1844]
0.  If you don't already, create two user accounts on NuGet.  I'll call them A and B.
1.  Create a package, log in as A, and upload the package.
2.  Edit the package owners to include account B.
3.  Log out and log in as B.
4.  Remove A from the list of package owners.
5.  Watch A's email inbox.

Result:  There's no notice to user A that he is no longer an owner on the package.
Expected:  We should, as a matter of symmetry, have e-mail notification that a user was removed a package's list of owners.  Folks learn through e-mail that they've been added, after all.

**Comment by AlexBHarley** [comment]
When removing user A, should there be a link in the email to confirm they can be removed? At the moment there is no choice for the owner being removed, so my initial thought is no. I imagine this is just a courtesy email?

**Comment by maartenba** [comment]
It's indeed just a courtesy email at the moment.
