### ISSUE TITLE
Cannot log into my NuGet account, and my packages are not available

### ISSUE THREAD

**Issue by sitecorerick** [NuGet/NuGetGallery#1857]
When I attempt to log into NuGet, I get a white screen of death, 500 is mentioned in the URL. If I attempt to recover my password, I get a WSOD. If I attempt to install any of my known package from the Package Manager Console, I get a 500, and if I try to push a package from the command line, I get a 500. 

The issue is clearly associated with my user account.

**Comment by mynkow** [comment]
Same thing is happening right now with me

**Comment by mygithubaccnt** [comment]
I'm having this problem for half an hour

**Comment by NagaMurali** [comment]
Please check whether your visual studio have administrator rights
