### ISSUE TITLE
Aggregate Stats fail to show in IE8

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1873]
1.  In IE7 or IE8, navigate to http://staging.nuget.org/.

Result:  Aggregate stats will fail to load on the home screen.  The javascript error reported by the browser is:

    Message: Object doesn't support this property or method
    Line: 1
    Char: 118525
    Code: 0

    URI: http://qa.nugettest.org/Scripts/all?v=Q_cl3n35gNPU7v2UxyjaaeY6OwOcBiRHE8XsLMlsEQ1

Expected:  This should work as it does on other supported browsers.

**Comment by yishaigalatzer** [comment]
This falls below the things we want to fix.
