### ISSUE TITLE
Development Dependency status isn't shown on upload or package page; can't be edited

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1874]
In NuGet 2.8, we introduced a new optional tag in package metadata called "developmentDependency".  However, uploaded packages with developmentDependency set to true aren't shown as such on package pages, nor are authors shown this on package upload.

To repro:
1.  Create a package with <developmentDependency> set to true in its nuspec file.
2.  Upload the package on nuget.org.

Result:  There are two closely connected issues here:
a.  On the verify-upload page, the author isn't shown this value,m even though essentially all other package metadata is shown here, and
b.  On the package page, there's no mention that the package is a development dependency.

Expected:  We ought to show this information in both places; it's important for authors validating their packages and this field value has a definite effect on the package consumer's experience.

**Comment by johnataylor** [comment]
We should consider this for the new gallery.

**Comment by robertmuehsig** [comment]
Link to a related PR https://github.com/NuGet/NuGetGallery/pull/2242

**Comment by robertmuehsig** [comment]
With PR https://github.com/NuGet/NuGetGallery/pull/2834 this is already resolved:
a. On the verify-upload page, the author isn't shown this value,m even though essentially all other package metadata is shown here, and
