### ISSUE TITLE
Support e-mail address isn't resolved and shown in IE8

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1875]
1.  In either IE7 or IE8, navigate to http://staging.nuget.org/policies/Contact.

Result:  The support@nuget.org email address doesn't appear in these two browsers.  In IE8, the unhandled javascript error reads:

    Message: Object doesn't support this property or method
    Line: 1
    Char: 118525
    Code: 0
    URI: http://qa.nugettest.org/Scripts/all?v=Q_cl-3n35gNPU7v2UxyjaaeY6OwOcBiRHE8XsLMlsEQ1

Expected:  We should find another way to obfuscate our email address that can work across the range of browsers we support.

**Comment by johnataylor** [comment]
This is the old gallery on and old browser.
