### ISSUE TITLE
Branding/Content file cannot serve static files

### ISSUE THREAD

**Issue by joostdenijs** [NuGet/NuGetGallery#1888]
Need to add:

`<location path="Branding/Content">
        <system.web>
            <httpHandlers>
               <clear />
            </httpHandlers>
        </system.web>
        <system.webServer>
            <handlers>
                <clear />
                <add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
            </handlers>
        </system.webServer>
    </location>
`

to the main web.config at line 130.

**Comment by johnataylor** [comment]
We have a new gallery implementation where branding is more first class. closing this bug as we won't be enhancing this on the existing gallery.
