### ISSUE TITLE
Windows Azure SDK 2.2 is not enough to build

### ISSUE THREAD

**Issue by asbjornu** [NuGet/NuGetGallery#1951]
Having the [Windows Azure SDK v2.2](http://www.windowsazure.com/en-us/downloads/) installed was not enough to get the required `.targets` file for the `build.cmd` to work. After installing "Windows Azure Cross-platform Command Line Tools" and "Windows Azure SDK for .NET (VS 2012)" (the one for 2013 was already installed), the build started working. I'm pretty sure just installing the latter would be enough, but I haven't tested.

A side question is: Why is Windows Azure required to build and set up a **local** NuGet gallery? If the answer is "because there's only one solution and it contains everything", perhaps the `build.cmd` file could be parameterized or otherwise be adjusted to the fact that most local builds of the NuGet gallery won't need any Azure connectivity?

**Comment by derigel23** [comment]
The build is still not working with installed Azure SDK. See https://github.com/NuGet/NuGetGallery/issues/2348#issuecomment-82565100
