### ISSUE TITLE
Enable-LocalTestMe.ps1 failed - "Failed to create an SSL Certificate"

### ISSUE THREAD

**Issue by lukaskabrt** [NuGet/NuGetGallery#1976]
Enable-LocalTestMe.ps1 shows the following error on my machine (Windows 8.1, Czech regional settings)

    Generating a Self-Signed SSL Certificate for nuget.localtest.me
    Error: Invalid input parameter for -b option.

    Failed to create an SSL Certificate
    At C:\Users\Lukas\Source\Repos\NuGetGallery\tools\Enable-LocalTestMe.ps1:103 char:5
    +     throw "Failed to create an SSL Certificate"
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (Failed to create an SSL Certificate:String) [], RuntimeException
        + FullyQualifiedErrorId : Failed to create an SSL Certificate

**Comment by maartenba** [comment]
Has been fixed since long. Closing issue.
