### ISSUE TITLE
Search:  We aren't tokenizing user input

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1982]
1.  Navigate to the search service console.
2.  Search for "Razor3".

Result:  Only one search result is returned, and it is only peripherally relevant to someone searching for version 3 of Razor.
Expected:  We ought to tokenize user input, at least along letter/number boundaries, in order to provide roughly the same results the user would've gotten searching for "Razor 3" (with a space, sans quotes).

More generally, if people run together words in a package name -- which is likely if a person misremembers the internal spacing or punctuation of a package name -- search results are degraded.  "JQueryUI" doesn't match JQuery UI, for example.  As a stretch goal, we might want to try to tokenize search terms from users if they use camel casing.

**Comment by johnataylor** [comment]
We currently camel split and split on punctuation. We could also split on alpha/numeric boundaries

**Comment by skofman1** [comment]
was fixed
