### ISSUE TITLE
Search:  We don't catch near misses in user input

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1984]
1.  Navigate to the search service console.
2.  Search for "Modernizer", "JsonDotNet", or "Knockout.js" (all sans quotes).

Result:  In all three cases, you'll get low-relevance search results.  In all three cases, the conceptually best match doesn't appear in search results.
Expected:  At this point, typo correction is something users naturally expect from website search.  Users aren't going to reliably remember the exact names of packages they use infrequently, and not being able to catch common cases of this hampers users' ability to search the site.  We should have some capacity to point folks to the correctly-spelled package.

**Comment by johnataylor** [comment]
Spell correcting on id is difficult. Though we might be able to do something with ngrams in the search box

**Comment by maartenba** [comment]
Duplicates https://github.com/NuGet/NuGetGallery/issues/2789
