### ISSUE TITLE
Wrap the wait time out exception from AddDownloadFacts in to a custom exception

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#1988]
We have a time out of 5 seconds set to the DB write operation related to download stats. 
It would be good to wrap this in to a custom exception so that we can differentiate between wait timeouts happening while writing stats and other wait timeouts. This will help  in analyzing Elmah logs and  alerting appropriately.

**Comment by xavierdecoster** [comment]
@bhuvak Think this one becomes obsolete with https://github.com/NuGet/NuGetGallery/issues/2672

Feel free to reopen if that's not the case :)
