### ISSUE TITLE
Unable to find version '3.0.3-rel-4' of package 'NuGet.Services.Search.Client'.

### ISSUE THREAD

**Issue by akuryan** [NuGet/NuGetGallery#2004]
Whenever I try to build solution (nevertheless with build.cmd or with VS 2013) - an error is generated that Nuget is not able to NuGet.Services.Search.Client
The only way to fix it I found was to manually checkout https://github.com/NuGet/NuGet.Services.Search.git and add assembly to solution

**Comment by ashuthinks** [comment]
can anyone help me i'm getting below error for NuGet.Services.Platform.Client while build.
"A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "NuGet.Services.Search.Client (≥ 3.0.75-r-master)" or update the version field.	NuGet.Services.Search.Client"
