### ISSUE TITLE
Improve fault-tolerance for package restore

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#2035]
If the search service is down or a package is missing from the index, it cannot be restored.  To be more tolerant of this, we should:

1. Try to find the package in the search index.  If the search service is *down*, then
2. Test for the package/version existence in blob storage and if it exists, manufacture a response to allow the package url to be served

Note that we don't want to hit SQL server as a fallback when the search service is down as we'd likely just cause ourselves more problems.

**Comment by johnataylor** [comment]
This is address with the deployment of API v3. Closing this issues that tracks the design.
