### ISSUE TITLE
Download count on search results inconsistent with count on package page

### ISSUE THREAD

**Issue by domaindrivendev** [NuGet/NuGetGallery#2037]
Repro steps:

1. Search for package Swashbuckle
2. Note the listed download count for the package titled Swashbuckle.WebHost
3. Click the package link to get more details
4. Note the download count displayed on this page (off by a couple of hundred at time of writing)

This bug is particularly unfortunate because people often use the count on the search results page to compare similar packages by popularity and in this case the value is less than it should be.

Thanks

**Comment by johnataylor** [comment]
There was a bug with the replication stats feature. This should now be fixed. The search is always a few downloads behind. This could be up to 24 hours behind.
