### ISSUE TITLE
Search: click the tag Roslyn on Packages page gives RoslynHelper on top, but Roslyn in the middle of the page

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2058]
because RoslynHelper has one tag of Roselyn, whereas Roslyn has more than one tags. But we should consider moving up the ranking of Roslyn package a bit.

**Comment by johnataylor** [comment]
We have since flattened the negative impact of having more tags. You can have up to 15 tags and not receive any penalty.See code in NuGet.Indexing.CustomSimilarity
