### ISSUE TITLE
Enable-LocalTestMe.ps1 fails to create/find config

### ISSUE THREAD

**Issue by phatcher** [NuGet/NuGetGallery#2110]
I'm developing as a non-admin on Windows 8.1, and the script didn't work as it cannot find the admin's IISExpress config since it doesn't exist, i.e. admin wasn't used for development.

The solution is to first run IISExpress as the admin user so that it creates the applicationHost file, I think it just needs a documentation note in the README.md as this took me a while to figure out.

**Comment by maartenba** [comment]
Updated with https://github.com/NuGet/NuGetGallery/commit/e35ece8c542e50bcfd71d0c5ed528d1b8206389f.
