### ISSUE TITLE
Private local NuGetGallery in VirtualDir

### ISSUE THREAD

**Issue by MatzeG** [NuGet/NuGetGallery#2121]
Hello 

the hero.png points to root Directory /content/logos when I install it on a virtual directory. I expected http://xyz.local/VirtualDir/Content/logos

Matthias

**Comment by robertmuehsig** [comment]
Just looked through old issues:
I could reproduce it with nested VirtualDirs (with just one VirtualDir at least the image was fine)

![image](https://cloud.githubusercontent.com/assets/756703/15910712/7c8c64d8-2dcc-11e6-85a6-ac152b15c5b9.png)

![image](https://cloud.githubusercontent.com/assets/756703/15910727/915ce676-2dcc-11e6-8ba2-bf8f166a6066.png)

I also noticed that all links to /downloads will point just to "localhost/downloads".

Will take a look at it in the coming days...

**Comment by maartenba** [comment]
Thansk @robertmuehsig

**Comment by maartenba** [comment]
Fixed by @robertmuehsig
