### ISSUE TITLE
Add a DB migration to drop Elmah_Error table to speed up DB imports

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2134]
We noticed during our recent tier migration effort that Elmah_Error table ( with 150 K rows and taking up to 1 GB storage space) was contributing to a major time in the database import operation.
Since we don't use this table anymore, it would be good to drop this table. This will be helpful in increasing the import DB times while syncing to failover DC.

**Comment by maartenba** [comment]
Table has been emptied, keeping the table itself around.
