### ISSUE TITLE
[NuGetGallery] Update DC1 V2Gallery settings to match with DC0

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/NuGetGallery#2135]
Update prod-1 V2Gallery SqlServer to point to Legacy instead of Primary
Before doing the above, ImportDB running prod-1 work to be rescheduled to import to Legacy instead of Primary

Also, update prod-1 V2Gallery CDN Host to point to storage account of DC1. Currently, it is still pointing to CDN host of prod-0 V2Gallery

**Comment by bhuvak** [comment]
This is fixed.
