### ISSUE TITLE
Intermittent and temporary failures installing new packages

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#2149]
Here's a build log from FAKE where the following happens:
1. A new version of FAKE is produced and published to nuget.org
2. A subsequent build step executes: 'nuget.exe install FAKE' to get the latest version of FAKE
3. The command-line reports: "Unable to find version '2.15.6' of package 'FAKE'."

This means that nuget.exe was determining that version 2.15.6 is the latest version and then it tries to install it, but installing it fails.  We are internally inconsistent.

This is leading to nasty/hard-to-repro issues for @forki and they've been plaguing him for some time now.

**Comment by neurospeech** [comment]
Temporary solution: https://github.com/neurospeech/NuGetProxy
