### ISSUE TITLE
Inconsistency on feed - package versions missing

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#2158]
With the following request, NuGet 2.8.1 is not included:
http://www.nuget.org/api/v2/FindPackagesById()?id=%27Nuget.Core%27

That response includes a "next" link to this URL:
http://www.nuget.org/api/v2/FindPackagesById?id=%27Nuget.Core%27&amp;$skiptoken=%27Nuget.Core%27,%272.7.2%27

But that page has the same data as the first page, and NuGet 2.8.1 is still not there.

However, the following URL does include NuGet 2.8.1:
http://www.nuget.org/api/v2/FindPackagesById()?id=%27Nuget.Core%27&$orderby=Published%20desc

And the next link (with the skiptoken) seems to do its job.

So it looks like we have issues with skiptokens that we didn't realize we had.

**Comment by maartenba** [comment]
Obsolete
