### ISSUE TITLE
Cache package id/version lookups and use a fall-back

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#2165]
We should aggressively cache the package id/version lookups that are used for package restore.  We want to insulate the front-end from interruptions in the search service.

Additionally, if the search service fails to respond, we should fall back to looking the package up in the database.

Anything else we can do to make the package restore lookups resilient is good.

**Comment by maartenba** [comment]
Will be fixed with #2557

**Comment by maartenba** [comment]
Fixed with https://github.com/NuGet/NuGetGallery/issues/2821
