### ISSUE TITLE
404 for re-sending confirmation email

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2199]
Repro steps:
1. after registering a new user, send confirmation email
2. do nothing to the confirmation email for ~15 mins and wait for the token to expire
3. click the link in the email now, NuGet gallery would say "the token has expired" or something. There is a link saying "Please reconfirm your email." Click that.
4. Now the email address filed on the https://int.nugettest.org/account/ConfirmationRequired page will become null and the page will show as below

![nullemail](https://cloud.githubusercontent.com/assets/1087852/3206700/df706d4e-edcb-11e3-80a2-6c9d2cff1070.PNG)

5. click the Send confirmation email link again will gives a 404

**Comment by 304NotModified** [comment]
FYI: I got an error while doing this local

`user.UnconfirmedEmailAddress` and `user.EmailConfirmationToken` where `null`

![image](https://cloud.githubusercontent.com/assets/5808377/10405701/0ade24d0-6edb-11e5-8bd8-340330b763d9.png)

**Comment by maartenba** [comment]
@304NotModified should be relatively easy to fix I think. Want to take it?

**Comment by 304NotModified** [comment]
- Well I have to retest this, because I'm not sure if I did the same case: I didn't wait for the timeout, but clicked on the link twice.

Also, it's easy to fix the crash, but it's unclear what to do if the "user.EmailConfirmationToken / user.UnconfirmedEmailAddress " is `null`. Options:

1. Crash with a nice error
2. Don't show the button
3. Prevent that those become `null` (dunno how)

**Comment by maartenba** [comment]
3 would be the one to go with. I *think* they become null because the token is expired and its values are not passed into the view in that case.

**Comment by 304NotModified** [comment]
Well, 1 and 2 were the easy fixes ;)

But I will look at option 3 this week.

**Comment by 304NotModified** [comment]
I was not 100% sure that I had the same issue, I cannot reproduce the timeout, but I got the same error. So I created a new issue, and PR.
