### ISSUE TITLE
Non-HTTPS resources loaded at package page

### ISSUE THREAD

**Issue by ahmetalpbalkan** [NuGet/NuGetGallery#2202]
https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.Libraries

This is one example. Something loaded from external resource is non-HTTPs and causes this: 

![](http://cl.ly/image/31252f143343/Image%202014-06-09%20at%2010.13.58%20AM.png)

**Comment by johnataylor** [comment]
Thanks for the suggestion, the latest development follows this pattern.
