### ISSUE TITLE
Profile Picture on Profile Page?

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#2228]
Wouldn't it be nice if the profile page contains the user avatar as well? Somewhere in this yellow marked region or similar to the package detail page:
![image](https://cloud.githubusercontent.com/assets/756703/3337122/656f0274-f845-11e3-9a41-d2d7b5addc3d.png)

Most users have good enough images on gravatar to show a 128x128px version.

Related to this issue https://github.com/NuGet/NuGetGallery/issues/144

**Comment by hbrock** [comment]
I would like to work on this issue.

**Comment by robertmuehsig** [comment]
This would be awesome :+1:

**Comment by hbrock** [comment]
Is this what we are shooting for:
![image](https://cloud.githubusercontent.com/assets/1028907/9691020/d81a6240-530d-11e5-920c-703ce5639d8f.png)

**Comment by maartenba** [comment]
It is!

**Comment by hbrock** [comment]
I will make a pull request soon

**Comment by robertmuehsig** [comment]
At least for me: Yes!

Von meinem Windows Phone gesendet
________________________________
Von: Harrison Brock<mailto:notifications@github.com>
Gesendet: ‎04.‎09.‎2015 20:04
An: NuGet/NuGetGallery<mailto:NuGetGallery@noreply.github.com>
Cc: Robert Mühsig<mailto:robert.muehsig@codeinside.eu>
Betreff: Re: [NuGetGallery] Profile Picture on Profile Page? (#2228)


Is this what we are shooting for:
[image]<https://cloud.githubusercontent.com/assets/1028907/9691020/d81a6240-530d-11e5-920c-703ce5639d8f.png>

**Comment by hbrock** [comment]
It took me a few tries to push the code up correctly.

**Comment by maartenba** [comment]
Thanks, fixed with #2657 - deployment will happen in the next days.
