### ISSUE TITLE
ReplicateStatisticsToWarehouse job is failing

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2237]
%  

System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Dimension_Package' with unique index 'Dimension_Package_2'. The duplicate key value is (PowerProductivityStudio.server, 2014.2.2). Cannot insert the value NULL into column 'Dimension_Package_Id', table 'NuGetWarehouse.dbo.Fact_Download'; column does not allow nulls. INSERT fails. The statement has been terminated. The statement has been terminated. at System.Data.SqlClient.SqlCommand.<ExecuteDbDataReaderAsync>b__24(Task`1 result) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() ---

**Comment by johnataylor** [comment]
The replicate stats job is no longer idempotent and not reliably able to recover from failures such as a VM reboot. This is a serious regression but can be easily addressed by resorting the original replicate stats logic. However the performance of the original replicate stats can be improved by making use of some of the batching logic in the newer code.

**Comment by RanjiniM** [comment]
The issues in the job have been fixed and it is running now.
