### ISSUE TITLE
Lovely hidden file-writing bug

### ISSUE THREAD

**Issue by sunnokon** [NuGet/NuGetGallery#2252]
Sorry if this is a duplicate, but I'd be surprised considering the unique circumstances under which I came to it.

# The bug
When trying to save a newly edited package file (locally) the data will sometimes be corrupted and unable to be read/understood as a .nupkg file (easy to see using NuGet Package Explorer).

# What's happening
The SaveFileAsync implementation (of FileSystemFileStorageService) will directly copy the file stream to the file location regardless of whether there is an existing file.  This will leave extra data at the end if the original file is longer than the new contents.

# Solution
Delete the file before saving it if it already exists.  NOTE: CloudBlobFileStorageService does this already, but FileSystemFileStorageService does not.

# How I found it
## Feel free to ignore this
I run an internal-only version of the Gallery, and wanted to update to the latest version (so authors could edit their package metadata/etc.).  Our setup is not on the cloud - it's all local, and I have no plans to move it to the cloud, as it's easier to manage and keep internal-only with the current setup.

Anyway, I noticed that the edit functionality wasn't working locally, so I added a new job to the task manager so it would actually edit packages if it wasn't running with the background cloud operations.  The copy from Operations.Tasks.HandleQueuedPackageEditsTask was pretty straightforward (replacing the assumed Cloud blob storage with the currently injected IFileStorageService), but once I tested everything I found that the package I was using as a test dummy kept coming up with different errors when I tried to open it in NuGet Package Explorer.  These errors were things like:

* specified argument was out of the range of valid values. parameter name: zipfilename
* file contains corrupted data.
* unable to read beyond the end of the stream.

After a lot of digging around I realized what was up, and figured that the only reason this particular funness hadn't been discovered yet is because the only parts that use this particular functionality don't allow uploads of the same file twice (since you're not allowed to change a .nupkg directly.

**Comment by yishaigalatzer** [comment]
We would love to take a PR with your fix for this. Sorry for this being hanging around for so long

**Comment by sunnokon** [comment]
Sorry, I'm not familiar with the abbreviation 'PR' - do I need to do anything to help with the fix beyond the code that's already attached to this bug? No worries on how long it's been around - I honestly forgot about it because I implemented the fix in my local version so long ago.

**Comment by yishaigalatzer** [comment]
You can submit a pull request, which means we will review the code, provide feedback and finally merge into our source tree, and you become a nuget contributor :)

Let me know if you need guidance on how to do that.

**Comment by ryuyu** [comment]
This is now (finally) fixed with the merge of https://github.com/NuGet/NuGetGallery/pull/3113
