### ISSUE TITLE
Support Target Framework filtering in Search Service

### ISSUE THREAD

**Issue by anurse** [NuGet/NuGetGallery#2255]
The Search Service can easily support target framework filtering, but it's disabled right now. The main blocker is around Portable Framework compatibility (especially Xamarin).

The interface will be through a new query parameter on the Search Service:
* RequiredFrameworks=... - Comma-separated list of frameworks that *MUST* be supported by a package to be returned

In order to properly determine framework compatibility, we'll need to use NuGet.Core's code to check compatibility. However, that code depends on files on disk that specify the frameworks supported by specific portable profiles. To make things more complicated, Xamarin Studio augments these files, so we'd need to have Xamarin Studio installed on the machine that runs this code as well.

Since we don't want to require that data be present on the search service, we'll build a file containing the data we need and export it. The Search Service will load that file and use the same NuGet.Core code to determine compatibility.

Sub-tasks:
* [ ] [*Ready for Code Review*] Augment NuGet.Core with the ability to export/import Portable Profile Tables
* [ ] Build a Lucene Filter that can filter out documents that are not compatible with the requirements, using an imported Portable Profile Table
* [ ] Augment Search Service with the ability to load up the latest portable profile table (without restarting)
* [ ] Create a build procedure for producing the Portable Profile Tables and uploading them to Blob Storage

**Comment by bhuvak** [comment]
This is added to v3 search service.
