### ISSUE TITLE
ImportDatabaseToFailoverDC job failing due to DB size limit

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2276]
System.Exception: Error encountered during the service operation. Could not import package. Error SQL72014: .Net SqlClient Data Provider: Msg 40544, Level 17, State 1, Line 3 The database 'backup_2014aug05_2302z' has reached its size quota. Partition or delete data, drop indexes, or consult the documentation for possible resolutions. Error SQL72045: Script execution error. The executed script: PRINT N'Checking constraint: FK_PackageStatistics_Packages_PackageKey [dbo].[PackageStatistics]'; ALTER TABLE [dbo].[PackageStatistics] WITH CHECK CHECK CONSTRAINT [FK_PackageStatistics_Packages_PackageKey]; at NuGet.Services.Work.Jobs.ImportDatabaseJob.<Resume>d__b.MoveNext() in c:\TeamCity\App\buildAgent\work\4b555bca28d8be56\src\NuGet.Services.Work\Jobs\Db\ImportDatabaseJob.cs:line 197

**Comment by deepakaravindr** [comment]
This job is not used anymore. We are using SQL Azure Premium
