### ISSUE TITLE
Rebuild DB indexes in Gallery and Warehouse DB

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2277]
The index fragmentation for some of the indexes in Packages and PackageRegistration table is around 70%. 
We need to rebuild the indexes at some point of time.
Also lot of times queries around warehouse DB is timing out. We need to rebuild the indexes in Warehouse DB as well.

**Comment by johnataylor** [comment]
This is surely out of date?
Perhaps we need issues on monitoring the health of indexes and jobs that trigger index rebuilds. But this issue on actually rebuilding is neither of those.
