### ISSUE TITLE
EmitPackageRegistrationBlobs_1_DC0 and UpdateCatalog_0_DC0 work service job is not getting invoked

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2279]
The last time this job was queued was 7/29 and it is still in "Incomplete" state. 
Check out https://api-work-0.nuget.org/work/invocations/instances/EmitPackageRegistrationBlobs_1_DC0 for details.

**Comment by maartenba** [comment]
No longer exists. Closing.
