### ISSUE TITLE
ReplicatePackageStatisticsJob is swallowing exceptions and can silently fail without writing records to DB

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2288]
The output from the job is all positive and showing successful messages. But actually no records is being written to warehouse DB.

One scenario that can repro this issue is:
creating a blank warehouse DB, with tables, stored procedures and functions created. But the fixed dimensions are not populated.

**Comment by johnataylor** [comment]
This code has been updated.
