### ISSUE TITLE
spec: Unexpected token error with complex url.

### ISSUE THREAD

**Issue by obiwanjacobi** [NuGet/NuGetGallery#2304]
Have a spec file with this url for the icon:
<iconUrl>http://download-codeplex.sec.s-msft.com/Download?ProjectName=vstnet&DownloadId=34897</iconUrl>

When trying to create a package it says:
'=' is an unexpected token. The expected token is ';'. Line 10, position 92.

Pos:92 is the second! '=' char. (after '&' ?)

Hope it helps,
Marc Jacobi

**Comment by deepakaravindr** [comment]
Duplicate of https://github.com/NuGet/Home/issues/526
