### ISSUE TITLE
Search: Package shown or not shown on search results unexpected

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2310]
Note: How to interpret the search results

There are 3 types of tests, 
- CompareSearchResultsForReductions, this is to verify packages got removed from the search results are Not compatible with the project's targetframework. Expected compatibility is false. 

- CompareSearchResultsForAdditions, this is to verify packages got added to the search results are compatible with the project's targetframework. Expected compatibility is true. 

- CompareSearchResultsForVersionUpdates, this is to verify package's new versions are compatible with the project's targetframework. Expected compatibility is true. 

The results below are from automated runs. It will list out the questioning package ID and version, also tells about the project's targetframework and the supported target frameworks by the package. 
The test will pass/fail at comparing the expected and actual compatibility, the latter of which is obtained by calling NuGet.Core's version utility IsCompatible. (The bugs regarding to version utility itself is filed at codeplex).

**********************

NuGet.Services.Search.Comparer.SearchResultTest.CompareSearchResultsForAdditions(targetFramework: ".NETFramework,Version=v4.5", feed: Win8Express)
Package: winrtxamltoolkit, 1.4.4.1
Project targetframework is .NETFramework,Version=v4.5; Package targetframewors are .NETCore,Version=v4.5.
Expected compatibility: True; Actual: False

**Comment by johnataylor** [comment]
We have another bug tracking this.
