### ISSUE TITLE
Newer Azure SDK 2.4 does not seem to support nuget.localtest.me

### ISSUE THREAD

**Issue by zfields** [NuGet/NuGetGallery#2319]
`nuget.localtest.me` should be replaced with `localhost` in
NuGetGallery.csproj
NuGetGallery.Cloud\ServiceConfiguration.Local.cscfg

**Comment by ChrisSfanos** [comment]
Could you post the instructions you are referring to?  We want to make sure we are looking at the same thing you are - thanks!

**Comment by zfields** [comment]
I have no idea. I appreciate you taking the time to respond, but original post was five and half months ago...

**Comment by maartenba** [comment]
After spelunking through README and docs, I can confirm that:

* You _may_ replace `nuget.localtest.me`with `localhost`, if you want to develop locally without using SSL.
* You _must_ keep it if you want to develop locally using SSL. Some additional steps are required however: in an ADMIN powershell prompt, run the `.\tools\Enable-LocalTestMe.ps1` file. It allows non-admins to host websites at: `http(s)://nuget.localtest.me`, it configures an IIS Express site at that URL and creates a self-signed SSL certificate. For more information on `localtest.me`, check out [readme.localtest.me](http://readme.localtest.me).

Of course you can deviate from this too, but the above should work for a freshly-cloned gallery. I updated the README.md to reflect this. https://github.com/NuGet/NuGetGallery/commit/75026bd9fc9095c10263d9c008128827484932b9

**Comment by maartenba** [comment]
Did this help resolving the issue you saw?

**Comment by zfields** [comment]
Are those "additional steps" well documented in the README?

**Comment by maartenba** [comment]
Yes.

**Comment by zfields** [comment]
Then you have resolved my issue. :-) If it was there before, perhaps you could make it more obvious. Thanks man!

**Comment by maartenba** [comment]
Thank you for reporting! (and having a lot of patience :-))
