### ISSUE TITLE
Package statistics page graph package order

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#2322]
http://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version

I noticed in the graph on the package statistics page that 6.0.1-beta1 is displayed after 6.0.1. Shouldn't it be the other way around?

**Comment by yishaigalatzer** [comment]
They are ordered by download count as far as I can tell. Makes sense to me at least, am I missing something?

**Comment by JamesNK** [comment]
I am talking about the graph, not the table of numbers. I have noticed in the past that the graph sometimes is out of order, showing pre-release versions after the final version.

**Comment by yishaigalatzer** [comment]
I see what you mean. It is ordered at the moment, but we should take a look at the code and see if this was fixed already or if there is something else lurking there.

**Comment by johnataylor** [comment]
#1711

**Comment by JamesNK** [comment]
Screenshot of it happening for Newtonsoft.Json:

![image](https://cloud.githubusercontent.com/assets/303201/7403135/cc9a077c-ef26-11e4-89f4-8e1e3e28fa85.png)

**Comment by JamesNK** [comment]
This still happens - http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/Newtonsoft.Json?groupby=Version

**Comment by yishaigalatzer** [comment]
Reactivated. Maarten can you please fix before deploying the new statistics?

Sent from my Windows Phone
________________________________

**Comment by maartenba** [comment]
We've pushed an update for this now.
