### ISSUE TITLE
Build is broken by MVC4 Windows Update

### ISSUE THREAD

**Issue by VintageMud** [NuGet/NuGetGallery#2323]
The build is failing with the below error, and can be attributed to a [Windows Update](http://stackoverflow.com/questions/26393157/windows-update-caused-mvc3-and-mvc4-stop-working)

> "D:\12-Git\NuGetGallery\build.msbuild" (default target) (1) ->
> "D:\12-Git\NuGetGallery\packages\NuGet.Services.Build.3.0.6\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
> "D:\12-Git\NuGetGallery\NuGetGallery.sln" (Build target) (3) ->
> "D:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\NuGetGallery.Facts.csproj" (default target) (6) ->
> (RunFacts target) -> 
>   D:\12-Git\NuGetGallery\build\NuGetGallery.xunit.targets(14,9): error : NuGetGallery.AppConfigIsCorrectlyApplied.VerifyBindingRedirectToMvc4IsWorking: Assert.Equal() Failure [D:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\NuGetGallery.Facts.csproj]
> D:\12-Git\NuGetGallery\build\NuGetGallery.xunit.targets(14,9): error : Expected: 4.0.0.0 [D:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\NuGetGallery.Facts.csproj]
> D:\12-Git\NuGetGallery\build\NuGetGallery.xunit.targets(14,9): error : Actual:   4.0.0.1 [D:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\NuGetGallery.Facts.csproj]
>   D:\12-Git\NuGetGallery\build\NuGetGallery.xunit.targets(14,9): error :    at NuGetGallery.AppConfigIsCorrectlyApplied.VerifyBindingRedirectToMvc4IsWorking() in d:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\AppConfigIsCorrectlyApplied.cs:line 23 [D:\12-Git\NuGetGallery\tests\NuGetGallery.Facts\NuGetGallery.Facts.csproj]

**Comment by yishaigalatzer** [comment]
see http://blogs.msdn.com/b/webdev/archive/2014/10/16/microsoft-asp-net-mvc-security-update-broke-my-build.aspx
