### ISSUE TITLE
CodeAnalysis Build Failure - Unused Variable

### ISSUE THREAD

**Issue by VintageMud** [NuGet/NuGetGallery#2324]
The build is failing with the below error due to unused variable.

> "D:\12-Git\NuGetGallery\build.msbuild" (default target) (1) ->
> "D:\12-Git\NuGetGallery\packages\NuGet.Services.Build.3.0.6\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
> "D:\12-Git\NuGetGallery\NuGetGallery.sln" (Build target) (3) ->
> "D:\12-Git\NuGetGallery\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
> (RunCodeAnalysis target) -> 
>   d:\12-Git\NuGetGallery\src\NuGetGallery\DataServices\V2Feed.svc.cs(78): error CA1804: Microsoft.Performance : 'V2Feed.Search(string, string, bool)' declares a variable, 'result', of type 'List<V2FeedPackage>', which is never used or is only assigned to. Use this variable or remove it. [D:\12-Git\NuGetGallery\src\NuGetGallery\NuGetGallery.csproj]
>   MSBUILD : error : Code Analysis detected errors.  See Code Analysis results window or log file for details. [D:\12-Git\NuGetGallery\src\NuGetGallery\NuGetGallery.csproj]
>

**Comment by maartenba** [comment]
@RanjiniM I fixed this one last week, feel free to close the issue.
