### ISSUE TITLE
nuget.exe "pack" command dependency problem.

### ISSUE THREAD

**Issue by hikalkan** [NuGet/NuGetGallery#2327]
I have an issue. I will write a sample situation to explain the problem:

This is my sample command to create a nuget package named Abp:

"..\src\.nuget\NuGet.exe" "pack" "..\src\Abp\Abp.csproj" -Properties Configuration=Release -IncludeReferencedProjects -Symbols

It automatically finds packages.config and create dependencies of Abp package. In package.config, it depends on:

  &lt;package id=&quot;Castle.Core&quot; version=&quot;3.3.1&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Castle.LoggingFacility&quot; version=&quot;3.3.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Castle.Windsor&quot; version=&quot;3.3.0&quot; targetFramework=&quot;net451&quot; /&gt;
  &lt;package id=&quot;Microsoft.Bcl.Immutable&quot; version=&quot;1.0.34&quot; targetFramework=&quot;net451&quot; /&gt;
  
But it does not include dependency for Castle.Core and Castle.Windsor since they are depended also by Castle.LoggingFacility (See http://www.nuget.org/packages/Abp).
But it's a problem because of depended versions. Castle.LoggingFacility depends on Castle.Core 3.3.0 but Abp depends on 3.3.1.
When I install Abp to my project, it gets Castle.Core 3.3.0 instead of 3.3.1 required by Abp.

It should explicitly set all dependencies of Abp.

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#338. Please file VS client issues on https://github.com/NuGet/Home/issues
