### ISSUE TITLE
Deleting package from Search index doesn't work

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2328]
While updating index, package deletes from DB are not applied to the search index and the UpdateSearchIndexJob throws "ArgumentOutofRangeException"

The issue seems to be related to the commit : .
https://github.com/NuGet/NuGet.Services.Search/commit/bc77f5d2ffa62d9764f95b0d106ab93b15fa6b24#diff-8728326a7661b44a7f1a61a0e0be07a7.

The PackageFetcher ( @ https://github.com/NuGet/NuGet.Services.Search/blob/master/src/NuGet.Indexing/UpdateIndexTask.cs#L52) tries to retrieve the package record from DB using the package key. While this works fine for Adds and updates, deletes doesn't work as the record with the specific key will not be found in the DB anymore ( as the package is already deleted).

**Comment by johnataylor** [comment]
closing this issue here as its is covered by the consolidation issue.
