### ISSUE TITLE
[NuGet.Warehouse] Improve parsing in SQL methods like 'UserAgentClientMinorVersion'

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/NuGetGallery#2335]
[NuGet.Warehouse] Improve parsing in SQL methods like 'UserAgentClientMinorVersion'

**Comment by johnataylor** [comment]
Closing this because there is no know bug here. Maintaining this logic in TSQL means that if we want to extend it, we can easily re-apply it to the historical data with a simple TSQL statement.
