### ISSUE TITLE
Would be nice if you guys did things consistently 

### ISSUE THREAD

**Issue by ghost** [NuGet/NuGetGallery#2337]
instead of this splitbrained "NuWorld" repository for everything on github vs nuget repository on codecrap(plex) because:

>>> Unpacking source...
Cloning into bare repository '/usr/portage/distfiles/egit-src/nuget'...
remote: Counting objects: 57399, done.
remote: Compressing objects: 100% (13991/13991), done.
remote: Total 57399 (delta 47146), reused 52243 (delta 42917)
Receiving objects: 100% (57399/57399), 39.11 MiB | 238.00 KiB/s, done.
error: RPC failed; result=56, HTTP code = 200
Resolving deltas: 100% (47146/47146), done.
 * ERROR: dev-dotnet/nuget-9999::dotnet failed (unpack phase):
 *   git-2_initial_clone: can't fetch from https://git01.codeplex.com/nuget

AND FAIL.

RIP Nuget.

**Comment by ChrisSfanos** [comment]
Thanks - we've moved everything to a single source
