### ISSUE TITLE
BUG: NuGet package manager has difficulty with "unavailable" projects in multi-project solution.

### ISSUE THREAD

**Issue by zfields** [NuGet/NuGetGallery#2340]
MENU:
NuGet Package Manager >> Manage NuGet Packages for Solution...

BRIEF:
When a project is unloaded, it is not recognized by the "Installed packages" pane, however it is considered by the "Online" pane.

DETAIL:
If you remove a package using the "Manage" button on the "Installed packages", the NuGet package will not be removed from an unloaded project. When attempting to subsequently re-"Install" the same NuGet package. The NuGet Package Manager shows a green checkmark indicating the package is already installed for you project.

WORKAROUND:
Reload the "unavailable" project and navigate to the NuGet Package Manager "Installed packages" pane. Click the "Manage" button, remove the NuGet Package from the newly loaded project, then re-"Install" the desired package.

ANTICIPATED RESOLUTION:
1) Would like to see the "unavailable"/unloaded projects listed in the "Manage" option from the "Installed packages" pane.
2) "Install" should allow user to install the package on a project-by-project basis in a single solution.

**Comment by ChrisSfanos** [comment]
Thanks for the suggestion - this is something we could consider for a future version of the client

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#337. Please file VS client issues on https://github.com/NuGet/Home/issues
