### ISSUE TITLE
I18n (Internationalization and Localization) of NuGet Gallery.

### ISSUE THREAD

**Issue by CalvinRodo** [NuGet/NuGetGallery#2341]
I would like to be able to run a local copy of the NuGet Gallery in my org we are however a bilingual workplace and as such would have to provide a bilingual gallery, currently all the text is hard-coded in the views. A move should be made to make the text configurable. 

For user generated packages uni-lingual is fine though localization would be a nice to have feature there as well.

**Comment by ChrisSfanos** [comment]
For the current NuGet Gallery, it is English only.  For a future version of the Gallery, we can consider making the strings localizable

**Comment by skofman1** [comment]
This issue was open for 6 years without additional upvotes. Making the Gallery localized is not a high priority. Closing.
