### ISSUE TITLE
Incredibly slow package download speed

### ISSUE THREAD

**Issue by cnblogs-dudu** [NuGet/NuGetGallery#2343]
very very very slow!
![pc5gbkjcb](https://cloud.githubusercontent.com/assets/3196961/5517308/0929062c-8918-11e4-8f46-e1ca6aa7ca12.png)

**Comment by ChrisSfanos** [comment]
Thanks - the team is not seeing any slowness during package download.  Are you still seeing this?  If so, can you share more about your location?

**Comment by yishaigalatzer** [comment]
Feel free to reopen if you still see slowness and specify exactly what is slow.

**Comment by cnblogs-dudu** [comment]
@ChrisSfanos In Shanghai, China.

**Comment by yishaigalatzer** [comment]
Tell us some more. Connection speed, what packages are you installing how long does it take. Is it slow now?
