### ISSUE TITLE
Page cannot be displayed http://nuget.localtest.me

### ISSUE THREAD

**Issue by jianyunt** [NuGet/NuGetGallery#2344]
I followed guidelines NuGet, cloned the nugget, ran Enable-LocalTestMe.ps1, and built it from VS successfully. However when I launch http://nuget.localtest.me/ from VS or hit F5, I got an error below. 

My machine config: WS2012 R2 Standard Server,  2013 VS, and Azure 2.4.   It’s a clean installed VM.   How do I get around this?

Network Access Message: The page cannot be displayed  
Explanation: There is a problem with the page you are trying to reach and it cannot be displayed. 
...
Technical Information (for support personnel) 
•Error Code: 502 Proxy Error. Forefront TMG denied the specified Uniform Resource Locator (URL). (12202) 
•IP Address: ... 
•Date: 12/26/2014 11:20:14 PM [GMT] 
•Server: TK5-P.....
•Source: proxy

**Comment by ChrisSfanos** [comment]
This looks like a proxy/FW issue with your Forefront TMG
