### ISSUE TITLE
Questions about NugetGallery cloud configuration

### ISSUE THREAD

**Issue by kappos** [NuGet/NuGetGallery#2347]
Hi together,
I installed NugetGallery as a private repository. I configured that packages uploaded into Azure Blobstorage.
In that szenario i have the problem, that displaying stats not working.
So I reading the code and me understanding is that this is not really implemented and if i interpreting correctly, that there are many NuGet.Services.xx projects, that this job in futuere doing this stuff, is this correct?

**Comment by ChrisSfanos** [comment]
Thanks for posting - can you post this to StackOverflow - that will be the best spot to get an answer on this.  Thanks!
