### ISSUE TITLE
How build from master branch and setup on premise(local) nuget gallery

### ISSUE THREAD

**Issue by DoCode** [NuGet/NuGetGallery#2348]
Hi,
what are currently the minumum steps to build and setup a local gallery?
The current branch not build, nuget references, etc.
Many thanks

**Comment by phatcher** [comment]
Have a look at https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS, also I've recently added a pull request to implement #1297, see #2382 for details

**Comment by derigel23** [comment]
It's still not possible to build project from master branch by build.cmd
I get errors in NuGetGallery project - azure related dll are not resolved (Microsoft.WindowsAzure.ServiceRuntime  & etc). There is no hint path, no Azure targets import, nothing. Do you suppose that Azure SDK should register own dll in GAC?! It didn't.

**Comment by asbjornu** [comment]
@phatcher Azure isn't mentioned on [that tutorial page](https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS) and as I wrote in #1951, it's not very intuitive to have Azure dependencies in something that won't be hosted on Azure. Will #2383 remedy any of this?

**Comment by maartenba** [comment]
We need the Azure SDK dependency for deployments to Azure. Unfortunately, the project model requires some assemblies to be imported. Best is to install Azure SDK 2.4 or 2.5.

**Comment by derigel23** [comment]
I did (Azure SDK 2.4). But it doesn't help as I described in previous comment. Did I miss something?

**Comment by maartenba** [comment]
The Azure SDK should add itself to the GAC. I installed http://go.microsoft.com/fwlink/?LinkId=323510 earlier this week and got it running.

**Comment by DoCode** [comment]
the same with ef...
update-database on fresh install (vs2013) not working...

**Comment by derigel23** [comment]
Yep, with Microsoft.WindowsAzure.ServiceRuntime all fine now.
```
gacutil /l Microsoft.WindowsAzure.ServiceRuntime
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  Microsoft.WindowsAzure.ServiceRuntime, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  Microsoft.WindowsAzure.ServiceRuntime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  Microsoft.WindowsAzure.ServiceRuntime, Version=2.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL

Number of items = 3
```

Problem with ***Microsoft.WindowsAzure.Diagnostics*** assembly.
```
"c:\Projects\OriginalNuGetGallery\build.msbuild" (default target) (1) ->
"c:\Projects\OriginalNuGetGallery\packages\NuGet.Services.Build.3.0.6\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"c:\Projects\OriginalNuGetGallery\NuGetGallery.sln" (Build target) (3) ->
"c:\Projects\OriginalNuGetGallery\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
(ResolveAssemblyReferences target) -> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.Diagnostics, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [c:\Projects\OriginalNuGetGallery\src\NuGetGallery\NuGetGallery.csproj]


"c:\Projects\OriginalNuGetGallery\build.msbuild" (default target) (1) ->
"c:\Projects\OriginalNuGetGallery\packages\NuGet.Services.Build.3.0.6\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"c:\Projects\OriginalNuGetGallery\NuGetGallery.sln" (Build target) (3) ->
"c:\Projects\OriginalNuGetGallery\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
(CoreCompile target) ->  App_Start\AppActivator.cs(15,30): error CS0234: The type or namespace name 'Diagnostics' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?) [c:\Projects\OriginalNuGetGallery\src\NuGetGallery\NuGetGallery.csproj]
```
```
gacutil /l Microsoft.WindowsAzure.Diagnostics
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:

Number of items = 0
```

**Comment by derigel23** [comment]
More details - Microsoft.WindowsAzure.Diagnostics is somehow resolved when project is opened in VS. But not resolved when building from command line (it's resolved after first opening solution in VS, because necessary dll get to bin folder).
How do you build it on CI server?!

**Comment by maartenba** [comment]
Should be resolved from GAC or C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.4\ref\Microsoft.WindowsAzure.Diagnostics.dll

**Comment by derigel23** [comment]
Yep, second case is what I see in VS.
But SDK installer do not register Microsoft.WindowsAzure.Diagnostics in GAC.

**Comment by ChrisSfanos** [comment]
Maarten - please clarify the steps - thanks!

**Comment by maartenba** [comment]
On all my Windows 8.1 machines with VS2013 and Azure SDK 2.5 it "just works". Not reeally a help, I know, but can't reproduce what you are seeing above. The assembly is not in my GAC either, but the Azure tools for VS2013 seem to be able to resolve the correct path.

Just added a bunch of the steps to `README.md`. @derigel, which commit of the gallery have you downloaded for this? I am suspecting this is more an issue with the Azure SDK installer.

**Comment by derigel23** [comment]
I was trying on 465a222cf016185b38173fb43449429e8303d01f.
To finally build the project I was forced to add Microsoft.WindowsAzure.Diagnostics to the GAC manually.
