### ISSUE TITLE
Global Tools Deployment

### ISSUE THREAD

**Issue by laktak** [NuGet/NuGetGallery#2350]
Package managers like npm allow us to install tools with the -g switch (e.g. `npm i hjson -g`) so I can use it from the commandline (e.g. `hjson file.hjson`).

Would it be possible to add a similar functionality that can install an exe in my path to NuGet?

**Comment by dimsedane** [comment]
You could take a look at https://chocolatey.org/, which uses nuget to install applications.

**Comment by ChrisSfanos** [comment]
Other teams are working on this type of solution, but we don't have anything we can share - thanks!

Ex: https://github.com/oneget

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#334. Please file VS client issues on https://github.com/NuGet/Home/issues
