### ISSUE TITLE
HTTP 504 from NuGet servers when performing restore

### ISSUE THREAD

**Issue by cmoore-cimpress** [NuGet/NuGetGallery#2353]
Over the past two days (2/2/15 & 2/3/15) we've noticed that many operations against the NuGet Azure servers are failing.

e.g. the following request nearly always results in a 504 - Gateway Timeout:
```
GET https://az320820.vo.msecnd.net/packages/autofac.extras.dynamicproxy2.3.0.4.nupkg HTTP/1.0
NuGet-Operation: Restore
User-Agent: NuGet Command Line/2.8.50126.400 (Microsoft Windows NT 6.2.9200.0)
```

**Comment by ChrisSfanos** [comment]
Thanks for posting - we will analyze the failures to see if we can determine the cause.  We will look at client improvements to these types of failures where we can

**Comment by maartenba** [comment]
On a side note: we switched to a different CDN provider near the end of february. @cmoore-cimpress, are you still seeing this?

**Comment by johnataylor** [comment]
Thanks for reporting this. We are not seeing this currently.

**Comment by kgyokov** [comment]
I noticed a similar issue when trying to restore older versions of packages. For example, go to  https://www.nuget.org/packages/RazorEngine/3.2.0 and click "Download", which takes you to https://api.nuget.org/packages/razorengine.3.2.0.nupkg . That URL is currently giving us an HTTP 504 error. Same with https://api.nuget.org/packages/autofac.wcf.2.6.3.862.nupkg . 

Downloading the latest versions of the packages works fine.
