### ISSUE TITLE
URL to nuget.exe command line tool should be HTTPS not HTTP

### ISSUE THREAD

**Issue by delcypher** [NuGet/NuGetGallery#2355]
The [link to the ``nuget.exe`` command line executable on your website](https://docs.nuget.org/consume/installing-nuget) uses HTTP. It should be HTTPS seeing as the HTTPS URL works just fine.

**Comment by yishaigalatzer** [comment]
@maartenba can you please include this change when we push the 2.8.5 update?

**Comment by maartenba** [comment]
Fixed with https://github.com/NuGet/NuGetDocs/commit/c0c95edb8f14fef79ef8b1239bfbf39107ed186e (docs) and https://github.com/NuGet/NuGetGallery/commit/5e757678fd8a7a3d966b583003053c9f8922ff74 (enforcing https)
