### ISSUE TITLE
allowedVersions filter not working at solution level

### ISSUE THREAD

**Issue by mj1856** [NuGet/NuGetGallery#2356]
Add a single web project to a new solution in Visual Studio.  Add jQuery 1.11.2 to the project.

Since jQuery 2.x is not supported in IE8, we want to stick with jQuery 1.11, so I use the `allowedVersions` attribute in the project's packages.config - like this:

    <package id="jQuery" version="1.11.2" targetFramework="net451" allowedVersions="[1,2)" />

This works fine, and hides the 2.x packages from updates.  But *only* from the command-line and the project-level GUI.

If you open the Nuget GUI from the *solution* level, it still shows jQuery 2.x updates - even though it would not be applicable for any project in the solution.

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#333. Please file VS client issues on https://github.com/NuGet/Home/issues
