### ISSUE TITLE
URLs in email confirmation email differ

### ISSUE THREAD

**Issue by FransBouma** [NuGet/NuGetGallery#2357]
Hi,

If you register at nuget.org, you need to confirm your email address. Nuget sends you an email for that. Now, I'm an old fart from the old days where you read your email using 'mail' on a shell prompt so I read all my emails in plain text. When I got the confirmation email, I saw this: (url changed to protect the innocent)

https://www.nuget.org/account/confirm/SomeName/uiRHuje67GrebnZIJMFA2 &lt;https://www.nuget.org/account/confirm/SomeName/uiRHuj_e67Grebn_ZIJMFA2&gt; 

So I copied the first URL, and it failed with the message it's been expired. Puzzled, I clicked the resend confirmation email link. To my surprise I received a new email with the exact same URL. Of course it still failed. I thought I was going crazy (some might think I'd reached that point many years ago, but let's say I'm sane here), so I again requested an email, same url, same story. The reason I retried the URL was that I thought it might be a problem in the service.

After more than half an hour I realized there were two '_' in the second URL, the one inside the &lt;&gt; characters. Using *that* URL worked. 

Now, for the love of everything that's holy, **please**, make both URLs the same. Not everyone reads their email in HTML format, some of us like it when the email text they're seeing is the actual email text, stripped from all hiding HTML mess that caused and still causes so much problems in the world. 

Thank you.

**Comment by Niels-V** [comment]
Seems to be an issue with the Markdown mailer which uses the underscore as italic indicator. That means that either the MarkdownSharp property StrictBoldItalic should be set (which is not accessible from the MarkdownMailer), or the underscore need to be escaped.

**Comment by ChrisSfanos** [comment]
Thanks for reporting this - at this time, this doesn't meet our bar.

**Comment by FransBouma** [comment]
Wait, someone created a PR for you and you still refuse to fix it, even though the PR fixes it? Why? If it takes weeks to fix something, and you're nearing a deadline, sure, but the fix is right there!

**Comment by yishaigalatzer** [comment]
@FransBouma we missed the fact that you had a PR, reactivating.

**Comment by RanjiniM** [comment]
The PR has been merged into master now
