### ISSUE TITLE
Allow perm delete of packages 

### ISSUE THREAD

**Issue by FransBouma** [NuGet/NuGetGallery#2359]
Why is it impossible to perm-delete a package? Let me illustrate this by a real-world scenario that happened to me this afternoon:

I wanted to upload a package for a dll of one of our products. A customer of ours already had uploaded a package with the name of the package we want, with the same dll, for their own use. I asked the customer to take the package down as we want to have control over our own material on nuget and there was no need for their package. 

He couldn't delete it, only de-list it. So he used the reportabuse form. The package of the 3rd party was removed, at least it's unlisted, but it's still there: the id is still unavailable. This is silly, I can't upload the package now with the name of the dll, and I don't want to  pick another name as there's **nothing** it clashes with in the nuget gallery, plus if I pick a different name I'm stuck with it and I don't want that. 

So, why is it so hard to implement a perm-delete, even github has one. Isn't the owner of the package in charge of the package? It seems not the case. Sure if something is perm-deleted the users referencing it might have a bad 5 minutes, well, tough: they don't own the package, the owner does, and they can still reference it locally.

**Comment by davidfowl** [comment]
The solution to this sorta thing isn't to allow deletion, that would actually be bad (as anybody who got this package before and was working will suddenly get some new random package from a new owner?). The *real* solution is to introduce something like organizations to packages. In this particular case, the package would have been called RandomBob/Something instead of Frans/Something.

**Comment by FransBouma** [comment]
While in the theoretical case that could happen, it is also a problem today that if a 3rd party / fan uploads a package under name X, and the owner of the material decides to do it themselves, they're out of luck and have to pick a different package name, which kind of majorly sucks. 

I agree that an organizational structuring would be better, so it can't happen you get a different dll from a different supplier on the same ID, but unless that's added, perm delete is a solution to a **real** problem. 

Keeping it how it is today is simply unacceptable. I'm definitely not alone in this situation: there are many more packages uploaded by 3rd parties who don't own the material at all and making them hidden isn't a solution: the real owner of the material can't simply upload the material under their own name, even though they *own* the material.

Btw, what you describe can happen today as well, if the package changes ownership: then too another person can start pushing content to the id and subscribers then too would get content from a different source.

**Comment by yishaigalatzer** [comment]
We are going to enable deletes of packages at some point. But we actually haven't considered this scenario. I agree with @davidfowl that packages that are published should not be republished with the same name (well maybe until we introduce signing).

But at the same time we want to enable self serve delete for people that say accidentally published confidential information accidentally in their packages. We will get to this at some point. We want to have more self service things happening.

@FransBouma in regards to 
> Btw, what you describe can happen today as well, if the package changes ownership: then too another person can start pushing content to the id and subscribers then too would get content from a different source.

Customers will have to upgrade or install a package to get in that situation, for already deployed packages simply package restore will drop them into this predicament, which is a very bad thing.

**Comment by FransBouma** [comment]
> But at the same time we want to enable self serve delete for people that say accidentally published confidential information accidentally in their packages. We will get to this at some point. We want to have more self service things happening.

but do these users still have to go through your checks? Because what I don't understand is that it is apparently not me who owns the packages I put on your site: once they're there, you apparently control what happens to them, I don't control them as I can't do with them what I want, e.g. delete when I please. It's not you who carries the responsibility towards the users of my stuff, I do, so why can't I decide what I think is best for my users but instead I have to follow your rules while I still carry the responsibility towards my users? See my problem? 

It's worded in your last sentence:

> Customers will have to upgrade or install a package to get in that situation, for already deployed packages simply package restore will drop them into this predicament, which is a very bad thing.

Perhaps it's a good thing, you don't know that. In the situation I ran into, it *was a good thing*. See, you are now deciding for me what is best for my users, while they're not your users, they're my users, and I carry the responsibility, not you. You control the delivery system, if something breaks there, that's your responsibility. **What** is delivered over the delivery mechanism isn't your responsibility, it's mine, as the user has taken a dependency on *my* stuff, not yours. 

The problem is that nuget is made so important by Microsoft that I can't avoid nuget to deliver my stuff to my users, but at the same time I run into a walled garden where I am no longer in control about what I deliver to my users. 

Why is that so hard to understand?

**Comment by yishaigalatzer** [comment]
@FransBouma sorry you don't follow the need of customers to be able to get the same code the installed in their project (with same version) on every build.

>  What is delivered over the delivery mechanism isn't your responsibility
Well our users disagree with you. If dev A publishes a pacakage that I as a user depend on. And you asked him to delete and deploy another package with the same name, and same version. Then the end user has a serious problem.

So you have to understand that we are not going to make the addition of delete support lightly. But we are and I said it clearly, so I'm not getting the rant.

Today we have have support to unlist packages, and you can ask us in critical situations (like packages with sensitive information published accidentally) to delete packages right now. You can even take ownership from other users (because we are not the judge and the garden is not really walled, you have to talk to the other package owner for that), and unlist their packages and add yours after that.

**Comment by FransBouma** [comment]
> sorry you don't follow the need of customers to be able to get the same code the installed in their project (with same version) on every build.

I do but it's not about the location of the resource the customer takes the dependency on, but the resource itself, which e.g. can be obtained elsewhere if a particular package is deleted. I don't think it should be the case that whatever is put online on nuget has to stay there forever just because there might be someone somewhere who has a dependency on it and hasn't taking precautions when that dependency changes. Microsoft also changes things which people have dependencies on, it's not something one will do lightly, but the option should be there. Same as here on github: it's the choice of the repo owner whether the repo is deleted, not the choice of the people who pull code from the repo in their build system: the delete action isn't simple but still possible without asking Microsoft whether it can be deleted. 

> So you have to understand that we are not going to make the addition of delete support lightly. But we are and I said it clearly, so I'm not getting the rant.

You specifically referred to specific cases but it's IMHO not up to Microsoft whether a package is removed or not, but to the package owner. Microsoft doesn't own the package, the owner does: if the package owner wants to get rid of it, it should be possible to do so without hoping that Microsoft will play ball and help. I understand you will eventually add support for this, but when that is is highly unclear: it can be in 2020 for all we know. What I don't get is why nuget makes such a distinction for this, while e.g. github doesn't. I haven't read anyone ever complain about github's feature for repo owners to remove a repo when they want to. 

I understand that Microsoft can delete packages or whatever you call it today, but what I'm asking for is that the owner of the package can delete the packages instead of asking Microsoft to do it (which implies that there might be a 'no we won't delete it' answer, or a delay or other reasons why it's not deleted. Which is of course rather odd, considering the owner of the package should be the one deciding it, not Microsoft).

**Comment by yishaigalatzer** [comment]
@FransBouma so this is down to a schedule question. We will update here when we have one

**Comment by FransBouma** [comment]
Thanks :)

**Comment by johnataylor** [comment]
#1693

**Comment by maartenba** [comment]
Possible via a support request now. Note that deletes are "soft deletes" - the id and version remain reserved. (Hard deletes are possible in specific cases)
