### ISSUE TITLE
No support for aspnetcore50 platform

### ISSUE THREAD

**Issue by fitzchak** [NuGet/NuGetGallery#2361]
See this issue http://stackoverflow.com/questions/28423123/problems-with-ravendb-client-reference-in-asp-net-5-0-project-json

In short, when the user install the RavenDB.Client package, it assume support for aspnetcore50 which we don't have. 

1. How can we specify in the NuGet configuration that we don't have this support, so our NuGet users won't be confused by this error?
2. What it takes to support aspnetcore50?

**Comment by ChrisSfanos** [comment]
1. This is now supported - note that the next ASPNET release (currently it's in their dev branch), it will become DNXCore (dotnet cross-platform core).  You'll need at least NuGet 2.8.3.  You need a min client of NuGet 2.8.5 to support projects that contain DNXCore in their packages

2.  Visit the ASP.NET on GitHub (https://github.com/aspnet)
