### ISSUE TITLE
Nuget default exclusion problem

### ISSUE THREAD

**Issue by Sbopf** [NuGet/NuGetGallery#2362]
Hi

I have been investigating an issue I am having with nuget excluding a sub directory of a recursively included directory.

The include statement:
<file src="Content\**\*.*" target="Content\" />

The sub directory that is missing:
Content\LessFiles\Compiler\node\node_modules\less\bin

I didn't think default exclusion would apply to this situation but it is not publishing to the package. I have no exclude statements and everything else in the directory I am recursively including is being published. 

 I know this is not a critical issue but Any help is appreciated. (sorry in advance if I am overlooking something simple, but I could not find a solution)

Thanks

Sam

**Comment by ChrisSfanos** [comment]
We need a bit more details - can you share the whole .nuspec file so we can get a better idea of what you are attempting - thanks

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#332. Please file VS client issues on https://github.com/NuGet/Home/issues
