### ISSUE TITLE
Unable to reinstall Json.NET

### ISSUE THREAD

**Issue by sushils2k9** [NuGet/NuGetGallery#2364]
When trying to reinstall Json.NET after upgrading the .Net framework version, I get the following errors:

PM> Update-Package –reinstall "Json.NET"
Update-Package : Unable to find package 'Json.NET'.
At line:1 char:1
+ Update-Package –reinstall "Json.NET"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

Please advise. Thanks,
Sushil

**Comment by JamesNK** [comment]
Sup sushils2k9. You want:

    Update-Package –reinstall Newtonsoft.Json

May the JSON be with you.

**Comment by yishaigalatzer** [comment]
@JamesNK the JSON is strong with you
