### ISSUE TITLE
Private NuGet gallery and NuGet 3.0

### ISSUE THREAD

**Issue by ebbeflarup** [NuGet/NuGetGallery#2365]
Hello NuGet

I have a question regarding your choice to remove "All package sources"

We have a private NuGet gallery, and some of the packages deployed here have dependencies to packages on the public NuGet gallery. So now the issue is that we can't search across multiple package sources in the NuGet 3.0 UI, meaning that dependencies to the public NuGet gallery from our private NuGet gallry cannot be resolved. Do you have a fix for this that does not include removing external dependencies from our private packages? :)

**Comment by ggrnd0** [comment]
[6. Don’t depend directly on NuGet.org.](https://msdn.microsoft.com/en-us/magazine/jj851071.aspx)

So, just upload all your deps in private gallery. 
It is better way.

**Comment by rkeithhill** [comment]
We are in the same boat.  I'm not so sure, in a corporate environment, our lawyers would go for us hosting another company's package on our internal server.  Not everybody works in a small outfit/startup where "anything goes".  :-)

**Comment by rkeithhill** [comment]
Hmm, is there really no way to vote on issue here?  Say what you will about Codeplex.com but it's issue tracking system (and existence of a discussion forum) are far better than what's offered on GitHub.  GitHub has some catching up to do in this regard.

**Comment by ebbeflarup** [comment]
Sorry for the late reply.

ggrnd0, I see your point, but as rkeithhill, I'm not sure about the legal implications of this :)

**Comment by ChrisSfanos** [comment]
Thanks for posting this - this is a NuGet client bug and we will move this issue to that repo.

**Comment by yishaigalatzer** [comment]
You can currently restore packages across different sources, this is already supported. If you would like a feature to search across multiple sources, please file an issue request for that at https://github.com/nuget/home/issues
