### ISSUE TITLE
DirectoryNotFound

### ISSUE THREAD

**Issue by eyalkl** [NuGet/NuGetGallery#2370]
Hi,

Got this log message when installing: (what can i do please)?

19/02/2015 15:28:05 - Microsoft VSIX Installer
19/02/2015 15:28:05 - -------------------------------------------
19/02/2015 15:28:05 - Initializing Install...
19/02/2015 15:28:05 - Extension Details...
19/02/2015 15:28:05 - 	Identifier      : NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5
19/02/2015 15:28:05 - 	Name            : NuGet Package Manager
19/02/2015 15:28:05 - 	Author          : Microsoft Corporation
19/02/2015 15:28:05 - 	Version         : 2.8.50926.602
19/02/2015 15:28:05 - 	Description     : A collection of tools to automate the process of downloading, installing, upgrading, configuring, and removing packages from a VS Project.
19/02/2015 15:28:05 - 	Locale          : en-US
19/02/2015 15:28:05 - 	MoreInfoURL     : http://docs.nuget.org/
19/02/2015 15:28:05 - 	InstalledByMSI  : False
19/02/2015 15:28:05 - 	SupportedFrameworkVersionRange : [4.0,4.5]
19/02/2015 15:28:05 - 
19/02/2015 15:28:05 - 	SignedBy        : Microsoft Corporation
19/02/2015 15:28:05 - 	Certificate Info : [Subject]
  CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Issuer]
  CN=Microsoft Code Signing PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Serial Number]
  33000000CC776171D4B17BA1280001000000CC

[Not Before]
  22/04/2014 20:39:04

[Not After]
  22/07/2015 20:39:04

[Thumbprint]
  9DD77A79F7124D8DB128A526833CF3760FCB7794

19/02/2015 15:28:05 - 	Supported Products : 
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.Pro
19/02/2015 15:28:05 - 			Version : [10.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.Pro
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.IntegratedShell
19/02/2015 15:28:05 - 			Version : [10.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.IntegratedShell
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.VWDExpress
19/02/2015 15:28:05 - 			Version : [10.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.VWDExpress
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.VPDExpress
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.VSWinExpress
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 		Microsoft.VisualStudio.VSWinDesktopExpress
19/02/2015 15:28:05 - 			Version : [11.0]
19/02/2015 15:28:05 - 
19/02/2015 15:28:05 - 	References      : 
19/02/2015 15:28:05 - 
19/02/2015 15:28:05 - Searching for applicable products...
19/02/2015 15:28:05 - Found installed product - Microsoft Visual Studio Professional 2012
19/02/2015 15:28:05 - System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath)
   at VSIXInstaller.App.GetExtensionManager(SupportedVSSKU sku)
   at VSIXInstaller.App.GetExtensionManagerForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ChrisSfanos** [comment]
Version 2.8.5 will be available by 4/3 - we cannot repro this currently, so can you please try that version.  If it does repro, can you provide more specifics if you can

**Comment by deepakaravindr** [comment]
Moved issue to https://github.com/NuGet/Home/issues/331. Please file VS client issues on https://github.com/NuGet/Home/issues
