### ISSUE TITLE
How to remove the pull of nuget.org packages in to the feed listing?

### ISSUE THREAD

**Issue by bc3tech** [NuGet/NuGetGallery#2371]
I followed the install instructions and am seeing all the nuget.org packages when I go to Packages. this despite the "stats" bar below the header on the main page says "1 unique package". In addition, when I search for the package I *have* uploaded, it doesn't show up.

I also went to the GallerySettings table, after running the Update-Database script, and see nothing in there to customize as per the instructions.

Thanks

**Comment by irwinj** [comment]
Same issue here. I wonder if there is a step missing in the readme. I see the nuget.org packages via my custom gallery, and also when I query said gallery via Visual Studio.

**Comment by irwinj** [comment]
To work around this issue you will need to comment out the Gallery.ServiceDisccoveryUril key. As noted in the web.config, this overrides ALL other Lucene related settings and disables indexing jobs. With this key present you will always use a remote Lucene index and will therefore not be able to see the packages you uploaded via search. Hth!

**Comment by ChrisSfanos** [comment]
Thanks for posting - as this is a support request, please email support@nuget.org or post a question to StackOverflow - thanks!
