### ISSUE TITLE
Package readme is not automatically opening in VS 2015 CTP6

### ISSUE THREAD

**Issue by rkeithhill** [NuGet/NuGetGallery#2375]
I'm loading a package from an internal repo running NuGet.Server 2.8.3.  I see that packages I load from api.nuget.org are opening their readme's correctly.  Hopefully, there will be an update to NuGet.Server that allows it to do this correctly as well - on both VS 2013 and VS 2015.

**Comment by deepakaravindr** [comment]
@rkeithhill , Created https://github.com/NuGet/Home/issues/321 for tracking this.
Please file visual studio client issues in https://github.com/NuGet/Home/issues
