### ISSUE TITLE
Documentation: Start with the basics

### ISSUE THREAD

**Issue by dale-wilson** [NuGet/NuGetGallery#2377]
I've been programming for mumble-mumble  years.  I downloaded the latest visual studio and it has this thing called NuGet.   When check it out, it says:

NuGet is the package manager for the Microsoft development platform including .NET. The NuGet client tools provide the ability to produce and consume packages. The NuGet Gallery is the central package repository used by all package authors and consumers.

That's nice, but it leaves the open question:   WHAT IS A PACKAGE, and why would I want one?   (The term "package" has been severely overloaded over the years.)  Pretend you don't know what a package is in this case and look through the documentation until you can figure it out.   It took me about 10 pages to get a feel for what a package is and does.

**Comment by ChrisSfanos** [comment]
Please come up with some better content and then assign to Maarten (on nuget.org and v3.nuget.org)
