### ISSUE TITLE
Package statistics don't appear to be updating.

### ISSUE THREAD

**Issue by eswann** [NuGet/NuGetGallery#2380]
I've recently uploaded 2 new packages and neither have downloads/stats updating.  They should be incrementing some as I know they've been downloaded at least a few times.  Is this down?

**Comment by T-Alex** [comment]
I have the same problem, my last new 4 packages are without any statistic, but should be, this trouble appeared approximately 3-4 days ago, before this everything was ok.

**Comment by ButchersBoy** [comment]
Same here, none of [my packages](https://www.nuget.org/profiles/ButchersBoy) have moved for around four days.

**Comment by eswann** [comment]
Automapper's been sitting at 1,651,901 total downloads for ~5 days now.  So yeah that's proof that status aren't updating.

**Comment by eswann** [comment]
And as soon as I speak...looks like they have started updating again..... :)

**Comment by jmontanaepa** [comment]
I've just downloaded one of [my packages](http://www.nuget.org/packages/FakeXrmEasy) 2 times from 2 different computers and statistics are not being updated either... they are kept at 0 :(

**Comment by devmathews** [comment]
Been days now and the stats still haven't changed at all. They just remain static. There gotta be a prominent issue with the Package Statistics.

I even emailed NuGet reporting the issue but haven't got any replies yet.

**Comment by RanjiniM** [comment]
This issue is fixed now.
