### ISSUE TITLE
Visual Studio 2015 CTP 6: Show from all sources.

### ISSUE THREAD

**Issue by Zoltu** [NuGet/NuGetGallery#2384]
As a user, I want an easy way to identify what packages are installed from the GUI.

There does not appear to be a way to tell the new NuGet package manager GUI to show a list of all packages from all sources.  I have 4 package sources and in order to see what packages I have installed or search for a package I have to look through each collection separately.

**Comment by ggrnd0** [comment]
+1

**Comment by deepakaravindr** [comment]
Moved issue to NuGet/Home#335. Please file VS client issues on https://github.com/NuGet/Home/issues
