### ISSUE TITLE
Visual Studio 2015 CTP 6: Don't page packages.config listing.

### ISSUE THREAD

**Issue by Zoltu** [NuGet/NuGetGallery#2385]
The new package UI feels unresponsive due to the lazy evaluation of packages and not showing the list until they are evaluated.

Presumably, the packages.config file is local and can easily be read/parsed in one pass.  When viewing Installed packages however, I get a list with a short scrollbar that has items added to it as I scroll.  This is annoying because I don't know how long the list is and I can't skip to the end if I want to (the list is sorted alphabetically, so skipping to the end is not unreasonable).

It seems that the list box should be initially populated with every list item and each list item would initially have the package ID displayed and a spinner of some kind indicating that the meta-data is being fetched.  As the meta-data comes in, the list items could be populated.  Additionally, if there was a desire to not fetch everything then only the visible list items could be fetched and additional visible item fetching could only occur when the scrollbar is released.

This will preserve the lazy evaluation feature yet give me a responsive UI that doesn't take a prohibitively long time to scroll through.

**Comment by yishaigalatzer** [comment]
Thanks for the idea. We are going to take a look at design alternatives here. As a side note please open bugs for Nuget Client on github.com/nuget/home

**Comment by Zoltu** [comment]
I'll recreate the issue over there.
