### ISSUE TITLE
Visual Studio 2015 CTP 6: Cannot install some packages.

### ISSUE THREAD

**Issue by Zoltu** [NuGet/NuGetGallery#2386]
1. Launch VS 2015 CTP 6
1. Create a new class library project.
1. Manage NuGet Packages For Solution.
1. Install xunit
 1. Package source: api.nuget.org
 1. Filter: All
 1. Include prerelease: unchecked
 1. Search box: xunit
 1. Show preview window
 1. Action: Installe
 1. Version: Latest stable 2.0.0
 1. Dependency behavior: Lowest
 1. File conflict action: Propmpt

First signs of a problem appear with dependency resolution taking a long time.  Once the Preview window does come up it only shows `xunit.assert 2.0.0`.  The expectation is that `xunit`, `xunit.core` `xunit.extensibility.core` and `xunit.assert` should all be installed.

I believe the problem is likely the fact that xunit and xunit.core don't have a lib folder or add any references.  They do however contain build tools and have references that must be installed.

Is this an expected behavior change?  If so, what is the correct way to build packages like this?

**Comment by deepakaravindr** [comment]
@zoltu, Created https://github.com/NuGet/Home/issues/320 for tracking this.
Please file visual studio client issues in https://github.com/NuGet/Home/issues
