### ISSUE TITLE
Manually creating the SQL database standalone

### ISSUE THREAD

**Issue by thebrianlopez** [NuGet/NuGetGallery#2387]
I've successfully cloned and built the repo per documentation (thanks :)) however I'm wondering how would one create the SQL database from command line externally from Nuget Package Console.

Looking to get an on-premise CI build going from a private fork i'm working on. 

Thanks in advanced and keep up the great work team!

**Comment by ChrisSfanos** [comment]
Thanks for submitting this - this is a support request, so please email: support@nuget.org or open a question on StackOverflow
