### ISSUE TITLE
Commit url in footer points to git://, should use https:// instead

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/NuGetGallery#2392]
The link to the release commit in the footer looks like this:

```
Deployed from <a href="git://github.com/NuGet/NuGetGallery.git/commit/5e757678fd">5e757678fd</a>.
```

Note the git protocol instead of https, if I click on the link my browser doesn't know what to do with it, you should use https instead :)

**Comment by maartenba** [comment]
Updated it to replace this when building from GitHub.com. Keeping the `git://` if you have a private fork on other source repos.

Will be live with our next deployment. Thanks for the suggestion, @akoeplinger!
