### ISSUE TITLE
Version calculator page

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2393]
Would be nice to support something similar to http://semver.npmjs.com/

@DamianEdwards cool suggestion

**Comment by csharpfritz** [comment]
I like the idea, and I think it would be really cool to be able to click
the versions that I want to include and get the semver notation for that
collection.



Jeff

**Comment by maartenba** [comment]
Also http://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=%5E0.1.1

**Comment by skofman1** [comment]
there was no interest from users over the last 3 years. Closing.
