### ISSUE TITLE
Some packages show the wrong license

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2396]
e.g. https://www.nuget.org/packages/Telerik.DataAccess.Fluent.Sample/

**Comment by ericlaw1979** [comment]
More specifically, SonaType's license analyzer appears to mark some set of commercial licenses as "Public Domain", exposing dangerously misleading information in both the NuGet website sidebar and the clientside UI shown in Visual Studio.

**Comment by yishaigalatzer** [comment]
Thanks @ericlaw1979

**Comment by johnataylor** [comment]
#1837

**Comment by johnataylor** [comment]
Please also consider #1705

**Comment by 304NotModified** [comment]
+1

**Comment by skofman1** [comment]
@yishaigalatzer , did you mean that it shows "Unknown" ? https://www.nuget.org/packages/Telerik.DataAccess.Fluent.Sample/2015.1.225.1

**Comment by skofman1** [comment]
License URLs have been deprecated. https://github.com/NuGet/Announcements/issues/32
