### ISSUE TITLE
New version of package shouldn't be returned unless package can be downloaded

### ISSUE THREAD

**Issue by ashic** [NuGet/NuGetGallery#2398]
It seems that for a period of time after a package has been updated, a nuget install fails coz it can't download the package. It appears that NuGet installs that don't specify a version number, find the latest metadata, but can't download the package. This might be due to DNS updates, or some other reason. 

I'd expect any version info that's returned from the api to be downloadable. It really shouldn't show the "latest" version in the api unless I can actually install it.

**Comment by yishaigalatzer** [comment]
tracked by this item: https://github.com/NuGet/Home/issues/268

**Comment by maartenba** [comment]
Relates to https://github.com/fsharp/FAKE/issues/710
