### ISSUE TITLE
In the search results, packages with few downloads should not be ranked higher than canonical packages for a search term

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/NuGetGallery#2399]
- [Search for HttpClient](http://www.nuget.org/packages?q=httpclient) - The [second result](http://www.nuget.org/packages/Plasma.HttpClient/) has 34 downloads, while [the “real” package](http://www.nuget.org/packages/Microsoft.Net.Http/), with 5 million downloads, is 9th.  Of the first 8 results, the highest number of downloads for any of them is 1376.
- [Search for ReactiveUI](http://www.nuget.org/packages?q=reactiveui) - The [correct package](http://www.nuget.org/packages/reactiveui/), with 36K downloads, is listed after 2 packages with less than 500 downloads each.  The results are much worse if you search for "[Reactive UI](http://www.nuget.org/packages?q=reactive+UI)" - the right package isn't even on the first page of results.
- [Search for PCL Storage](http://www.nuget.org/packages?q=PCL+Storage) - An [outdated fork of PCL Storage](http://www.nuget.org/packages/PCLStorage-Append/0.2.2-pre) with 82 downloads shows up before [the real package](http://www.nuget.org/packages/PCLStorage/) which has 24,000 downloads.

Search relevancy is hard.  As @davkean [has pointed out](https://twitter.com/davkean/status/573720957266845696), we've invested a lot in this sort of thing in Bing.  In fact, doing a site:nuget.org search for these terms on Bing returns the right package as the first result for all of these cases.  Can we investigate if we can use Bing's relevancy in some form to produce better search results for NuGet?

Barring that, I'd suggest that packages with several orders of magnitude more downloads than the others in the results get a boost to their relevancy.

**Comment by yishaigalatzer** [comment]
@dsplaisted thanks for the suggestions. We are aware of these issues, and we will fix them. 

Aside: We are not planning to use bing for this, and we are boosting for downloads, but like you said search is hard and we need to find the time to do it over other things that have higher priority at the moment.
