### ISSUE TITLE
Results page uses super tiny font for "Last Published" and "Latest Version"

### ISSUE THREAD

**Issue by Eilon** [NuGet/NuGetGallery#2402]
See picture:

![image](https://cloud.githubusercontent.com/assets/202643/7108674/8b8c3c74-e142-11e4-9880-3134db326486.png)

**Comment by csharpfritz** [comment]
There's a new web UI coming, and we'll keep this in mind with the new
results page



Jeff

**Comment by Eilon** [comment]
<sub>thanks!</sub>

**Comment by maartenba** [comment]
Will be better in our next deployment.
