### ISSUE TITLE
How can I create a NuGet package for Windows Phone 8.1 from a PCL project?

### ISSUE THREAD

**Issue by JoshClose** [NuGet/NuGetGallery#2403]
My PCL project is setup with these targets:

.NET Framework 4
Silverlight 5
Windows 8
Windows Phone 8.1
Windows Phone Silverlight 8
I created the PCL target for my nuspec file using the [NuGet Package Explorer](https://npe.codeplex.com/).

My target looks like this: `lib\portable-net4+sl5+wp8+win8`.

If I create a Windows 8 test project, I can find the latest version of my library in NuGet. If I create a Windows Phone 8.1 project, this version does not show up.

What am I doing wrong here?

I am cross posting this with [StackOverflow](http://stackoverflow.com/questions/29619169/how-can-i-create-a-nuget-package-for-windows-phone-8-1-from-a-pcl-project) in case this is a bug.

**Comment by yishaigalatzer** [comment]
You are missing wpa81 (wpa and wpa81 are synonyms)

Stackoverflow answer is right, and also stackoverflow is the place to post.

Also note this repo is for website issues, all other issues should go to nuget/home repo

**Comment by JoshClose** [comment]
That worked. So essentially any of those single profiles are what is used for the PCL profile too? The documentation on this isn't the greatest. 

> Common Framework and Profile Targeting Examples
> The following provides examples of common targets.

That right there says it all. Why isn't there a real list of everything NuGet understands?

Sorry if this wasn't the correct place to post. I follow some links around and ended up in a place that said everything was moved to github. I went to post on the client library, but it said it should be posted here.

> Got bugs? File them here: https://github.com/NuGet/NuGetGallery/issues

https://github.com/NuGet/NuGet.Client

**Comment by JoshClose** [comment]
Also, thanks for replying and making things clear for me. :)

**Comment by yishaigalatzer** [comment]
Thanks Josh. We just made home repo public and not all links have been updated yet.

**Comment by maartenba** [comment]
Updated all README.md's in our projects to point to the correct URL.
