### ISSUE TITLE
Encouraging use of strong named assemblies?

### ISSUE THREAD

**Issue by picrap** [NuGet/NuGetGallery#2404]
This is a problem I often have, which is NuGet packages containing non-signed (with SNK) assemblies.
Since I have to work with signed assemblies, this excludes a lot of packages (and is very frustrating).
Wouldn't it be good to show warnings on uploads when uploaded libs are .NET assemblies with no strong naming? 
So this wouldn't forbid unsigned assemblie, but just make people aware of possible improvements.

**Comment by yishaigalatzer** [comment]
We don't plan to do that

**Comment by robertmuehsig** [comment]
Regarding the "possible improvements": There were several long Strong Naming discussions in the past and the majority (at least in the OSS world) is against Strong Naming in general. See:
https://github.com/octokit/octokit.net/issues/405
http://strongnamingconsideredharmful.com/
