### ISSUE TITLE
Resetting password on int.nugettest.org

### ISSUE THREAD

**Issue by tushargupta51** [NuGet/NuGetGallery#2408]
I am trying to reset password using the "lost password" button in int.nugettest.org. It's giving me this error (image attached)
![capture](https://cloud.githubusercontent.com/assets/803796/7190711/e402d9e2-e43c-11e4-90d3-591fadcedc89.PNG)

I can reset password on nuget.org but resetting that and using the same password to log into int.nugettest.org is not working. Is that even suppose to work? I tried on both IE and chrome.

Thanks

**Comment by tushargupta51** [comment]
@emgarten @RanjiniM Thanks for the quick action. To emphasize it more, it is currently a blocker for me. I want to push some packages to int.nugettest.org ASAP. But since I am not able to login, I cannot upload any packages. Is there any workaround?

**Comment by RanjiniM** [comment]
@tushargupta51, this issue should be fixed now. The fix was a config change and everything seems okay now.

**Comment by tushargupta51** [comment]
@RanjiniM Thanks, I can log in now :)
