### ISSUE TITLE
Package's project url was saved to V2 database with an extra / at the end

### ISSUE THREAD

**Issue by danliu** [NuGet/NuGetGallery#2409]
For example, Elmah package's project url was saved as http://elmah.googlecode.com/, whereas in the nuspec file it is http://elmah.googlecode.com.

This makes open-packagePage -passthru -whatif command returns "http://elmah.googlecode.com/" for V2.

V3 does not have this issue and above command resturns  http://elmah.googlecode.com.

**Comment by deepakaravindr** [comment]
this is won't fix since there is no end user impact and it's hard to fix all the existing data.
