### ISSUE TITLE
Delete Missing packages from database

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2411]
We have some packages in nuget.org which exist in database and hence show up in search, but the actual package doesn't exist in blob storage.
There are around 164 of such packages like this. We might have ended in this state either due to an error while upload ( where the entry got added in DB and uploading to azure storage failed ) or it might have been an issue while trying to delete the package ( where the entry got removed from storage and not from DB).

Doing a diff by select * [dbo].[Packages] and ListBlob().Count on storage would give the exact count

**Comment by RanjiniM** [comment]
On comparing DB and storage only 4 records from DB were missing nupkgs on storage and those are cleaned up from DB now.
