### ISSUE TITLE
Service discovery index.json for V2 Gallery DEV environment

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2412]
Currently we don't have service discovery index.json for DEV environment. We should create one and make it deploy through octopus.

**Comment by xavierdecoster** [comment]
We do have this for DEV, being auto-deployed and verified on the CI.

**Comment by RanjiniM** [comment]
Yep, but i believe it is pointing to PROD resources now. The following should be done
1. Update Dev-Index.json to point to Dev resources (Search Service for example)
2. Update Dev gallery to use Dev service discovery URI
3. Create a Dev Lucene container
4. Run all the jobs on Dev-jobs VM
5. Make search service use the new container

**Comment by johnataylor** [comment]
If this is fixed with your changes from yesterday can you comment and close.
