### ISSUE TITLE
Convert Worker Role jobs into job exes running on a VM

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2413]
Here are the jobs still running in Azure Worker Role. We should move them as exes into our VM. 

GenerateDownloadCountReport_DC0_Aug14
GenerateSearchRankings_DC0_Aug14
HandlePackageEdits
RebuildWarehouseIndexes
UpdateLicenseReports

**Comment by bhuvak** [comment]
Will be addressed by #2415
