### ISSUE TITLE
Background jobs consolidation

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2415]
Currently our background jobs need to be restarted manually for VM reboots and manually deployed after fixes. Make it automatic through Octopus deployments

**Comment by bhuvak** [comment]
I will be working on #2415 and #2413 as part of this. Changing the title to reflect it.

**Comment by bhuvak** [comment]
#2414

**Comment by johnataylor** [comment]
#2336 
#2332
