### ISSUE TITLE
E2E monitoring tests for v2 and v3 data integrity

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2417]
We should have a test that tests our v2 and v3 E2E and alerts on any failures

**Comment by johnataylor** [comment]
Moving this to the RTM milestone. Perhaps we can just close this as a dup. We have two or three issues tracking monitoring.

**Comment by skofman1** [comment]
E2E tests for V2V3 search service were added by @shishirx34
