### ISSUE TITLE
Package restore should not hit the database

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2428]
We had a bunch of DB wait time out errors that happened this morning and it turns out to be a timeout error in "FindPackageByIdAndVersion" while restoring a package.
Package restore should get all the required data from Search and should not hit the DB. Looks like a regression. This need to be fixed.

**Comment by maartenba** [comment]
Will be fixed with https://github.com/NuGet/NuGetGallery/issues/2557

**Comment by maartenba** [comment]
Fixed with https://github.com/NuGet/NuGetGallery/issues/2821
