### ISSUE TITLE
Streamline the process around incremental rollouts and staging enviromment

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2439]
Currently int.nugettest.org is being used both for internal testing and by external folks. This causes issues since int environment goes down at times. We need to see if we can setup a different environment to point external folks to. 
As a part of this, we also need to streamline the process around how we do incremental roll outs for server components ( roll them to staging environment and let them stay there for a while, analyze various alerts/metrics during this time and then promote to prod).

**Comment by maartenba** [comment]
Relates to https://github.com/NuGet/NuGetGallery/issues/2629
