### ISSUE TITLE
Automated WebDeploy packaging fails

### ISSUE THREAD

**Issue by PleasantD** [NuGet/NuGetGallery#2440]
We are using a build script to automate the building and packaging of the NuGet Gallery so we can deploy it internally. We were using a ~2 year old checkout of the project and recently needed to update.

I was able to point the main build script to the new location (as all of the build scripts have moved and changed significantly). 

We were then calling the "Package" target on the former Website project to package the website into the MSDeploy zip file. After pointing the script to the new project file location, nothing was happening.

It turns out that the Package target from `Microsoft.Web.Publishing.targets` is being clobbered by the Package target from `NuGet.Services.Build.targets`. Since MSBuild scripts are processed top-down, this makes it impossible to call the publishing Package target directly.

```
<MSBuild Projects="..\Source\src\NuGetGallery.csproj" Targets="Package"
				 Properties="PackageLocation=$(BaseDir)\Packages\NuGetGallery_WebDeploy.zip;
                 DeployOnBuild=False;
                 Configuration=$(ProjectConfiguration);
                 Platform=AnyCPU"/>
```

**Comment by yishaigalatzer** [comment]
Rename the target files? Unfortunately doesn't look like there is much we can do about it for now.

An alternative is to use Kudu or another solution other than web deploy.
