### ISSUE TITLE
Windows App Certification Kit Test Fails, binary is built in debug mode

### ISSUE THREAD

**Issue by ranjittgs** [NuGet/NuGetGallery#2443]
Hi,

Windows phone 8.1 App fails Windows App Certification Kit test (WACK Test).

It is producing below error in Debug configuration test,

The debug configuration test detected the following errors:
 1)The binary Phone.Controls.dll is built in debug mode.

Impact if not fixed:  Windows Phone Store doesn’t allow a debug version of an app. 

How to fix:  Please make sure the app isn't linking to any debug versions of a framework and it is built with the release configuration
And i got a solution like,
Universal Apps (And Silverlight 8.1 Apps) have a different certification requirement. You cannot publish assemblies built in debug mode.
You'll need to contact the NuGet authors of ICSharpCode and ImageTools and have them provide you with a version built in release mode.
How to proceed with this solution. I'm very help full if any solution provided.
Thanks and Regards,
Ranjit.

**Comment by johnataylor** [comment]
Please contact the relevant package owners regarding issues with specific packages.
Thanks.

**Comment by princetomy92** [comment]
The binary RestSharp.dll is built in debug mode. error during packaging......need help

**Comment by princetomy92** [comment]
Debug configuration test

FAILED
Debug configuration
Error Found: The debug configuration test detected the following errors:
The binary RestSharp.dll is built in debug mode.
Impact if not fixed: Windows Store doesn’t allow a debug version of an app.
How to fix: Please make sure the app isn’t linking to any debug versions of a framework and it is built with release configuration with optimization enabled. If this is a managed app please make sure you have installed the correct version of .NET framework.

**Comment by princetomy92** [comment]
Debug configuration test

FAILED
Debug configuration
Error Found: The debug configuration test detected the following errors:
The binary RestSharp.dll is built in debug mode.
Impact if not fixed: Windows Store doesn’t allow a debug version of an app.
How to fix: Please make sure the app isn’t linking to any debug versions of a framework and it is built with release configuration with optimization enabled. If this is a managed app please make sure you have installed the correct version of .NET framework.
