### ISSUE TITLE
Search auto complete service should not be case-sensitive

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2452]
Found that using the autocomplete search endpoint, the service is case-sensitive.

For example: autocompletion for 
microsoft.aspnet vs. Microsoft.AspNet
testpackage vs. TestPackage

returns different results.

Talked to Scott and this is related to the tokenization of the query string and the search indexes.

We should probably improve the logic by adding lower-cased tokens to the existing search indexes to allow better match.

Also consider performance improvement by allowing a single call to retrieve data for all active frameworks.

(Moving this issue from nuget/home)

**Comment by maartenba** [comment]
Was fixed with https://github.com/NuGet/NuGetGallery/issues/2758
