### ISSUE TITLE
If NuGet.org rejects a package with Error 500 it should show details

### ISSUE THREAD

**Issue by forki** [NuGet/NuGetGallery#2456]
This wouldhelp to solve https://github.com/NuGet/NuGetGallery/issues/2455

**Comment by yishaigalatzer** [comment]
A website should never reveal details about 500s. It is useful for us (site developers) but a vulnerability when shared with the world.

**Comment by forki** [comment]
Ok but it would still be nice to understand the issue of the package.

**Comment by johnataylor** [comment]
Yes absolutely, regarding #2455 we will be improving the validation and it should be returning 400.
But 500 is the wrong error code to return this information on that's all. The information on the 500 we'll get in our trace.
