### ISSUE TITLE
SSL error on https://preview-search.nuget.org/search/autocomplete

### ISSUE THREAD

**Issue by forki** [NuGet/NuGetGallery#2459]
If I ask http://preview.nuget.org/ver3-preview/index.json for the autocomplete service I get:

     { 
     "version": "3.0.0-preview.1",
     "resources": [
      {
       "@id": "https://preview-search.nuget.org/search/query",
       "@type": "SearchQueryService"
      },
      {
       "@id": "https://preview-search.nuget.org/search/autocomplete",
       "@type": "SearchAutocompleteService"
      },
      {
       "@id": "http://api-metrics.nuget.org/DownloadEvent",
       "@type": "MetricsService"
      },
      {
       "@id": "https://az320820.vo.msecnd.net/registrations-0/",
       "@type": "RegistrationsBaseUrl"
      },
      {
       "@id": "http://preview.nuget.org/ver3-ctp1/islatest/segment_index.json",
       "@type": "LatestVersionsList"
      },
      {
       "@id": "http://preview.nuget.org/ver3-ctp1/islateststable/segment_index.json",
       "@type": "LatestStableVersionsList"
      },
      {
       "@id": "http://preview.nuget.org/ver3-ctp1/allversions/segment_index.json",
       "@type": "AllVersionsList"
      },
      {
       "@id": "http://www.nuget.org/api/v2",
       "@type": "LegacyGallery"
      }
     ],
     "@context": {
      "@vocab": "http://schema.nuget.org/services#"
     }
    }

but 

* https://preview-search.nuget.org/search/autocomplete?q=fake&take=10000 doesn't work
* http://preview-search.nuget.org/search/autocomplete?q=fake&take=10000 works

**Comment by johnataylor** [comment]
Please use http://api.nuget.org/v3/index.json
We've been testing the RC release with this feed. We are not actively working on the preview feed.

**Comment by forki** [comment]
yep. thanks.
