### ISSUE TITLE
Nuget package element is not declared

### ISSUE THREAD

**Issue by ParagNaikade** [NuGet/NuGetGallery#2460]
When i open packages.config, visual studio gives the warning as " package element is not declared". I resolved the issue by adding xml schema to the global location where visual studio is installed.e.g.C:\Program Files (x86)\Microsoft Visual Studio 10.0\Xml\Schemas
 But is there any nuget package which automatically adds this schema to packages folder so that  the visual studio solution will refer to it and no warning will appear.

**Comment by emgarten** [comment]
This is the expected behavior currently.

**Comment by ParagNaikade** [comment]
You mean the warning  " package element is not declared" which is coming, is expected behaviour??
