### ISSUE TITLE
AutoCompleteService fails

### ISSUE THREAD

**Issue by forki** [NuGet/NuGetGallery#2463]
![image](https://cloud.githubusercontent.com/assets/57396/7491500/490dcfd8-f3ea-11e4-85b5-7658085a6372.png)

**Comment by forki** [comment]
I "discovered" the link from https://api.nuget.org/v3/index.json

**Comment by maartenba** [comment]
We're on it. An index is being rebuilt. /cc @bhuvak

**Comment by forki** [comment]
Thanks for fast response.

/cc @Krzysztof-Cieslak

**Comment by forki** [comment]
Do you know how long this takes?

**Comment by maartenba** [comment]
https://api-v3search-0.nuget.org/autocomplete is back

**Comment by forki** [comment]
thanks
