### ISSUE TITLE
Add process recycle to all the jobs based on frequency/ conditions

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/NuGetGallery#2467]
In addition look into 
1. Mutex for these jobs
2. For issues detected through heart beat, kill the job safely and restart

**Comment by johnataylor** [comment]
We should try heart beat via tracing instead of something more active. And then couple the monitoring of the heart beat to the tracing. i.e. look for a particular trace entry at a regular interval.

The first step to the timed kill is to integrate the Cancellation framework.

**Comment by RanjiniM** [comment]
1. Heartbeat monitor is deployed to INT and DC1 now
2. Email monitoring to monitor the Heartbeat logs and send emails is deployed to INT and DC1

**Comment by RanjiniM** [comment]
Pending
1. Cancellation Token
2. Killing the jobs every few hours and restarting
3. Hooking up the log monitoring and emailing through PagerDuty
