### ISSUE TITLE
Nuget console insists to install a error package

### ISSUE THREAD

**Issue by RIldefonso** [NuGet/NuGetGallery#2474]
Hi, people. 
 I tried to install Punch (https://www.nuget.org/packages/IdeaBlade.Cocktail/) using the NuGet console in my VS 2013 Ultimate update 4 and the install didn't work. It complained about the version of .Net, informing that the necessary version was not presente. I am using Win8.1 and updates are automatics... 

 Ok... I gave up to test this package (if it started wrong, it will be wrong ever...) but the NuGet console insists in install the package of DevForce that it could not install previously. 

 How can I disable the batch that start this installation every time I open NuGet console? 

 Thanks.

**Comment by emgarten** [comment]
You likely have an init.ps1 file in your packages folder that is triggering this. Try removing those and checking if this resolves your issue.
