### ISSUE TITLE
Search /find endpoint returns null ref exception 

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2480]
https://api-v3search-0.nuget.org/find?id=westwindwebsurge&version=0.86.0 --> Return null ref 
while the package is actually found in reg. blobs : https://api.nuget.org/v3/registration0/westwindwebsurge/0.86.0.json

It could be an issue in find endpoint or an issue in indexing job where the package is missing in the index. Need to look more in to it.

**Comment by bhuvak** [comment]
Similarly https://api.nuget.org/v3/registration0/diginari.helpers/1.0.3.json

**Comment by bhuvak** [comment]
This happens for unlisted packages. As part of #2419 , this should be fixed.

**Comment by maartenba** [comment]
Fixed in V2V3 search (not yet deployed)
