### ISSUE TITLE
Unable to add Pdb file for the Referenced projects

### ISSUE THREAD

**Issue by ashwindersingh** [NuGet/NuGetGallery#2481]
I have Project A which is depend on the Project B and Project C. I am trying to Create Nuget for the Project A, I want to include the dll and Pdb files from the Project B and Project C. I am running below command for creating nuget package with Pdb symbols.

nuget.exe pack ProjectA.csproj -IncludeReferencedProjects -Symbols.

But after running this command, I am getting the below error

NuGet.CommandLineException: Specifying both -IncludeReferencedProjects and -Symbols is not supported.
   at NuGet.Commands.PackCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)

I am able to Create the Nuget package with Symbols file for the Project A alone without including referenced projects, but when i am trying to add referenced projects (Project B, Project C), it is throwing me above error.

Is there any work around for adding the referenced projects Pdb files to the Nuget package, if not when will this bug will be resolved.

**Comment by yishaigalatzer** [comment]
You can create the nuspec manually. We don't plan to fix this issue, as the recommendation is to include a single dll per package and we don't plan to extend support for this area.
