### ISSUE TITLE
Find namespaces or using statesment

### ISSUE THREAD

**Issue by fenixbrood** [NuGet/NuGetGallery#2482]
I'm looking for a way to find witch namespaces are included in what package. As a primarily C#/XAML developer. I find my self looking for a package (or multiple) that extends objects or types. Sometimes i copy samples from the web and I don't have the right namespaces. and then i have to start Google/Bing for it. I'm looking for an easier way to find packages that i want without leaving the coding environment.
Same as namespaces/object may exist for other languages. I think it would be awesome to search inside the packages.

Sure I can download all packages thru the API and then traverse them all and create my own index and then create a website/API that handles all this.

So my suggestion is add functionality to search for files in a structured way

**Comment by csharpfritz** [comment]
This functionality is available in Visual Studio 2015 RC.  Type a reference
to an object and you will be presented with a lightbulb in the left gutter
that you can use to install a package and add that reference.

Also, we have been experimenting with the site:
http://packagesearch.azurewebsites.net/



Jeff

**Comment by fenixbrood** [comment]
Nice! Exactly What Im looking for!
