### ISSUE TITLE
Cannot edit package info on Nuget.org for aspnet5 packages

### ISSUE THREAD

**Issue by Shazwazza** [NuGet/NuGetGallery#2486]
For example I've tried to edit this package: https://www.nuget.org/packages/smidge for each one of it's releases  but each time I try this it ends up telling me:

"Your last edit to this package was not successfully applied. You can edit the package and submit the edit again to retry the edit."

I've tried a few times to re-edit but it's never successful.

**Comment by yishaigalatzer** [comment]
@bhuvak can you please take a look?

**Comment by Shazwazza** [comment]
I can confirm that editing works on non-aspnet5 packages that are not in pre-release (such as this one i just changed: https://www.nuget.org/packages/Examine/0.1.63 )

So the problem must either be something with aspnet5 packages or pre-release packages.

**Comment by Shazwazza** [comment]
... actually just tested a pre-release of non aspnet5 and it worked :)

**Comment by bhuvak** [comment]
@Shazwazza, we had an issue around package edit that we have fixed. Can you confirm if your edits are applied now ?

**Comment by RanjiniM** [comment]
The job issues are fixed and things seem fine now.

**Comment by Shazwazza** [comment]
Sorry for the delay! Yup, can confirm it is all working now. thanks!
