### ISSUE TITLE
Getting "could not instantiate http://SymbolSource.Processing.Tools .PdbSourceExtractor" when trying to publish Symbolsource

### ISSUE THREAD

**Issue by LianwMS** [NuGet/NuGetGallery#2487]
Run the nuget push as follows:

nuget push Microsoft.AspNet.OData.5.6.0-rc.symbols.nupkg -source http://nuget.gw.symbolsource.org/Public/NuGet -apiKey XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX

get the follows error:

Failed to process request. 'Package submission failed: Server was unable to process request. ---> ComponentActivator: could not instantiate SymbolSource.Processing.Tools.PdbSourceExtractor ---> Exception has been thrown by the target of aninvocation. ---> Value cannot be null. Parameter name: path1. See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information.'.
The remote server returned an error: (506) Package submission failed: Server was unable to process request. ---> ComponentActivator: could not instantiate SymbolSource.Processing.Tools.PdbSourceExtractor ---> Exception has been thrown by the target of an invocation. ---> Value cannot be null. Parameter name: path1. See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information
...

**Comment by yishaigalatzer** [comment]
We do not own symbol source. Please contact those fellas
