### ISSUE TITLE
error viewing specific profiles

### ISSUE THREAD

**Issue by adamralph** [NuGet/NuGetGallery#2494]
E.g. https://www.nuget.org/profiles/damianh

![image](https://cloud.githubusercontent.com/assets/677704/7765271/472fc59e-005c-11e5-8ad7-8ab99c1d02b2.png)

Other profiles are fine, e.g. https://www.nuget.org/profiles/adamralph

![image](https://cloud.githubusercontent.com/assets/677704/7765280/6542cbb2-005c-11e5-8dd4-4c4c215fc0fa.png)

**Comment by damianh** [comment]
I'm in stealth mode :ghost:

**Comment by yishaigalatzer** [comment]
Thanks for reporting this.

**Comment by bhuvak** [comment]
Seems to be exception with duplicate entries. Pasting the stack trace
System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NuGetGallery.PackageService.FindPackagesByOwner(User user, Boolean includeUnlisted)
   at NuGetGallery.UsersController.Profiles(String username, Int32 page, Boolean showAllPackages)

**Comment by bhuvak** [comment]
You should be able to view your profile now.

**Comment by adamralph** [comment]
:+1: looks good now!
