### ISSUE TITLE
SSDT & SSDT-BI Support

### ISSUE THREAD

**Issue by shawnburge** [NuGet/NuGetGallery#2498]
Howdy, all!

Would it be possible to add support for Database, SSRS, SSAS, and SSIS projects to NuGet?

For the Database project, you can deploy custom static code analysis assemblies to the project.

For the BI tools, it would be nice to manage templates, resources, etc., in a NuGet package that can be easily deployed to new and existing projects.

Thanks!!
Shawn

**Comment by xavierdecoster** [comment]
Closing as duplicate.
Tracking it here: https://github.com/NuGet/Home/issues/637
