### ISSUE TITLE
Add dashboard check for daily download numbers 

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2499]

**Comment by petehauge** [comment]
Agreed!  In particular, I'd like to see the trend over time of downloads so we can see how announcements, blogs, etc., affect the downloads.  Even if this was just a table of data and we can use Excel to build our own visualizations, that would be great.

**Comment by yishaigalatzer** [comment]
We don't plan to invest in the dashboard at this point.
