### ISSUE TITLE
Stats replicator job fails with error related to replication cursor

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2500]
The INSERT statement conflicted with the CHECK constraint "CK_CollectorCursor
he conflict occurred in database "NuGetWarehouse", table "dbo.CollectorCursor".
as been terminated.

ta.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
ta.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
ta.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
ta.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject
ean& dataReady)
ta.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
ta.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
ta.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
ta.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
reading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by maartenba** [comment]
Wil be deprecated once we have CDN based warehouse in place.

**Comment by maartenba** [comment]
Will be deprecated with https://github.com/NuGet/NuGetGallery/issues/2503
