### ISSUE TITLE
Cannot edit Package information.

### ISSUE THREAD

**Issue by enkimatt** [NuGet/NuGetGallery#2501]
I've attempted several times now to edit my Package to add a link back to my "Project Site" aka GitHub...
Every attempt to edit fails, it starts out saying  
  
>*An edit is pending for this package version. You are seeing the edited package description now.
These changes will be applied to the package file and become visible to everybody soon unless you first.*

And ended up displaying the following message.  
>*Your last edit to this package was not successfully applied. You can edit the package and submit the edit again to retry the edit.*

I have verified, several times that the link I provided is correct and working.  
Why won't my package information update?

Package in question:
https://www.nuget.org/packages/Rogue/1.0.2  
Link I am attempting to add under the 'Project Home Page URL'
http://github.com/enkimatt/rogue/

**Comment by bhuvak** [comment]
Your package edit should have been applied now. Let us know if you still hit any issues.

**Comment by rickyah** [comment]
I'm having the same issue with the package https://www.nuget.org/packages/ini-parser/
Is there any solution?

**Comment by bhuvak** [comment]
Related to #2521
