### ISSUE TITLE
Package statistics don't appear to be updating (again).

### ISSUE THREAD

**Issue by 9swampy** [NuGet/NuGetGallery#2503]
Reopening https://github.com/NuGet/NuGetGallery/issues/2380, https://github.com/NuGet/NuGetGallery/issues/2329 & https://github.com/NuGet/NuGetGallery/issues/2278, perhaps unrelated but same issue - none of my package statistics have been updated since 2015-04-22, interestingly a couple of days after all the above issues were "fixed and closed".

**Comment by emgarten** [comment]
Thanks for reporting this we are aware of the issue. We are currently prioritizing other site stability issues over the stats, but we plan to get these up to date again as soon as possible.

**Comment by VikingsFan** [comment]
@johnataylor May I know the frequency of the package’s download count update?
Is there any way to get real time download count data? 
https://www.nuget.org/api/v2 is not working as before(update about every 5 minutes) now.

**Comment by gimlichael** [comment]
I am confused .. the statistic was working again as late as beginning of last week .. somewhere after 16-18 july it was failing again. How can this keep happening?

**Comment by 9swampy** [comment]
FWIW my stats are still stuck on Apr 22. Patiently waiting but would be nice to see a resolution...

**Comment by MarcosMeli** [comment]
Same here: "Statistics last updated at 2015-04-22 21:15:57 UTC."

https://www.nuget.org/stats/packages/FileHelpers?groupby=Version

The new versions stats are not there, just the past 6 weeks before Apr 22

**Comment by maartenba** [comment]
Working on it, @xavierdecoster is typing like a madman to get this out :-)

**Comment by 304NotModified** [comment]
:+1:

**Comment by JamesNK** [comment]
Do it!

https://www.youtube.com/watch?v=nuHfVn_cfHU

**Comment by 9swampy** [comment]
Woohoo. Seems like we have stats again. Will monitor and see if they roll the update.

**Comment by maartenba** [comment]
@9swampy should be good now :-)

**Comment by geoffreymcgill** [comment]
Download statistics appears to be stalled again. 

<img width="632" alt="screenshot 2016-04-08 10 48 26" src="https://cloud.githubusercontent.com/assets/62210/14391131/816c66fe-fd77-11e5-8fdf-354eff67e8bc.png">

**Comment by xavierdecoster** [comment]
We are working on data point roll-ups to avoid capacity problems. Jobs are a little behind but updates should soon be visible.

**Comment by xavierdecoster** [comment]
@geoffreymcgill Just noticed it got updated

![image](https://cloud.githubusercontent.com/assets/880728/14393397/be1af616-fd7b-11e5-8bd1-7c32ce32c424.png)

**Comment by 304NotModified** [comment]
It looks stuck again?

**Comment by xavierdecoster** [comment]
As stated above, we are working on data roll-ups. Statistics updates may experience delays as we disable the jobs during the roll-up process.

**Comment by 304NotModified** [comment]
Any idea when its all is up to date? Can this get posted on status.nuget.org?

**Comment by gimlichael** [comment]
Seems to be stalled again :-(
