### ISSUE TITLE
Out of memory exceptions thrown by dashboard monitoring tasks

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2508]
From last week bunch of dashboard tasks are throwing out of memory exception.
It could be related to #2485. But the orphaned processes doesnt consume any memory though. 
We should look more in to it and optimize the monitoring jobs if required .Also the VM can be upgrades to D3.

**Comment by yishaigalatzer** [comment]
@ryuyu please research and come up with a recommendation here (should we kill the jobs, fix the OOM, anything else?)

**Comment by skofman1** [comment]
Closing this issue since the jobs are in the process of deprecation.
