### ISSUE TITLE
PackageRegistrations table should not allow the same id to exist more than once

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2509]
PackageRegistrations table should not allow the same id to exist more than once.

**Comment by maartenba** [comment]
Fixed with https://github.com/NuGet/NuGetGallery/commit/de6455d2b3b2c1817984826242ef3194b68f73f6

**Comment by bhuvak** [comment]
This deployment is planned for S1.

**Comment by maartenba** [comment]
Deployed.
