### ISSUE TITLE
Latest packages are not accessible for Msbuild auto restore.

### ISSUE THREAD

**Issue by javad-helloy** [NuGet/NuGetGallery#2511]
After the issues with Nuget today. I can not do CI due to an error I get trying to update a nuget package. The latest version of the package can not be found by nuget restore. Its like some data has rolled back to older data (check point). 

I have problems with:

New Relic for Windows Azure Web Sites (x86) 4.5.90 
and 
NewRelic.Agent.Api 4.6.29

**Comment by andyday** [comment]
I'm having the same issue with JWT 1.3.4...

**Comment by mynkow** [comment]
Today is a nightmare. I have more than 10 packages failing right now.

**Comment by Sinstraliz** [comment]
Same here it seems that the latest versions of the packages are failing.

**Comment by FeodorFitsner** [comment]
This package fails too (and this is not the latest but the one from May 2):

    nuget install WindowsAzure.ServiceBus -Version 2.6.6 -nocache

**Comment by mynkow** [comment]
So nuget.org is hosted on Azure and the trafficmanager is the load balancer. Is it Azure issue or nuget issue? I think it is Azure issue because I can download all failing packages from the website using the download button. => https://www.nuget.org/packages/WindowsAzure.ServiceBus/2.6.6

Or it is something else. Please someone explain to us what is going on so I know if I have to update all 20 servers manually. 10x

C:\>nslookup www.nuget.org
Server:  UnKnown
Address:  10.10.63.5

Non-authoritative answer:
Name:    nuget-prod-0-v2gallery.cloudapp.net
Address:  168.62.110.126
Aliases:  www.nuget.org
          nuget-prod-v2gallery.trafficmanager.net

**Comment by msneeden** [comment]
Installations via the Package Manager Console in VS appear to be succeeding, restores via API calls to NuGet.org do not appear to find the latest package.

**Comment by sdluxeon** [comment]
"Installations via the Package Manager Console in VS appear to be succeeding, restores via API calls to NuGet.org do not appear to find the latest package." <= Same here. The BUILD server is dead. RIP

**Comment by dtretyakov** [comment]
Same error. Does not work nuget restore for recently updated nuget packages and outdated packages in the VS "Manage Nuget Packages" window.
```
(RestorePackages target) -> 
  ...\.nuget\NuGet.targets(100,9): error : Unable to find version '2.1.4' of package 'jQuery'.
```

**Comment by maartenba** [comment]
This was caused by an issue on www.nuget.org. It should be resolved right now. Feel free to respond to this issue in case you are still seeing issues.

**Comment by maartenba** [comment]
This was caused by an issue on www.nuget.org. It should be resolved right now. Feel free to respond to this issue in case you are still seeing issues.

**Comment by mynkow** [comment]
It works for me

**Comment by FeodorFitsner** [comment]
Looks like it's started to work. Thanks, Maarten!

**Comment by mynkow** [comment]
NuGet.exe install packages.config -OutputDirectory packages

This command fails with the same error.
