### ISSUE TITLE
NuGet.exe install packages.config - Failing to install

### ISSUE THREAD

**Issue by mynkow** [NuGet/NuGetGallery#2517]
NuGet.exe install packages.config -OutputDirectory packages

This command fails with the same error as #2511

**Comment by mynkow** [comment]
Any updates?

**Comment by yishaigalatzer** [comment]
This should be fixed now. Please let us know if this doesn't work for you.

**Comment by mynkow** [comment]
It is working in Europe. In US it is still failing.

**Comment by yishaigalatzer** [comment]
Can you share your packages.config

**Comment by yishaigalatzer** [comment]
And your nuget.config

**Comment by bhuvak** [comment]
If you can provide the fiddler traces that would help. Also the nuget.config file ( if it has any proxy settings).

**Comment by mynkow** [comment]
It is working at the moment.

For the history:
packages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Cronus.DomainModeling" version="1.2.3" targetFramework="net45" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="Multithreading.Scheduler" version="1.0.1" targetFramework="net45" />
</packages>

nuget.config:
<?xml version="1.0" encoding="utf-8"?>
<configuration />

**Comment by mynkow** [comment]
It is failing again.

**Comment by mynkow** [comment]
https://ci.appveyor.com/project/Elders-OSS/cronus/build/1.0.247

Fix it pls

**Comment by xavierdecoster** [comment]
Please target `https://www.nuget.org/api/v2` instead of `https://nuget.org`.
