### ISSUE TITLE
[V3] The feed should return the original version

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/NuGetGallery#2518]
To be able to propertly fix NuGet/Home#595 the version string returned and accepted from any feed calls should be non-normalized (as specified in .nuspec)

**Comment by xavierdecoster** [comment]
@AndriySvyryd is this a V3 feed only issue? (title suggests it is) No changes needed to the v2 NuGetGallery? This also seems related to the v2-v3 search consolidation work @bhuvak is doing. Would love to get some more context :)

**Comment by AndriySvyryd** [comment]
This is basically about making the V3 feed use the same version strings as V2. This will allow the client to treat the packages in the same way independently from the originating feed.

**Comment by xavierdecoster** [comment]
If the versions returned by the v2 gallery are correct, then this is not a gallery issue and the issue should be fixed in the search service consolidation work @bhuvak is doing. @bhuvak can you confirm the consolidated service will return the versions in the format the v2 gallery returns them currently?

**Comment by yishaigalatzer** [comment]
@bhuvak @johnataylor @xavierdecoster @maartenba this is pretty critical to make it in shortly. We are making a fix in RTM client bits.

**Comment by emgarten** [comment]
This will not fix NuGet/Home#595  The nupkg file name on the server is normalized for both v2 and v3. The right fix for this is for the v3 client to rename the nupkg in the way the 2.8.6 client does already.

**Comment by AndriySvyryd** [comment]
@emgarten While this wouldn't fix NuGet/Home#595 it allows to make the fix that I linked in the comments there, it uses non-normalized versions for both V2 and V3 package sources.

**Comment by skofman1** [comment]
@emgarten is this still a thing? Can I close?

**Comment by emgarten** [comment]
No, this was solved on the client. V3 can only use the normalized version.
