### ISSUE TITLE
Unable to save my Package details.

### ISSUE THREAD

**Issue by pritambaldota** [NuGet/NuGetGallery#2521]
I have saved package details several times, after save it says it will be updated soon. After some time it shows message - **our last edit to this package was not successfully applied. You can edit the package and submit the edit again to retry the edit.**

My Package url is https://www.nuget.org/packages/PritamBaldota.JqueryCultureInfo/

Can you please check this.

**Comment by rickyah** [comment]
I'm having the same problem, there seems to be several issues with the same problem

My package: https://www.nuget.org/packages/ini-parser/

**Comment by bhuvak** [comment]
We are looking in to it.

**Comment by RanjiniM** [comment]
The job issues are fixed now. Things are working again.

**Comment by cmcknz77** [comment]
I'm having this exact issue but in a private gallery... No packages where authors attempt to update the package info are ever actually updated to 'live'... @RanjiniM Are you able to provide some pointers on how/when the package update job runs?

**Comment by skofman1** [comment]
@cmcknz77 , package edits are applied by this job: https://github.com/NuGet/NuGet.Jobs/tree/master/src/HandlePackageEdits

Do you have it deployed?
