### ISSUE TITLE
Show indexing status next to new package versions

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2522]
Here is a strawman suggestion to show package status for packages that have been uploaded but not yet indexed, in a way that doesn't require the user to go to a status page.

inspired by #2432 

![image](https://cloud.githubusercontent.com/assets/1238711/7925599/a95be294-087b-11e5-8ca5-bc89976c9b55.png)

**Comment by maartenba** [comment]
Related commit: https://github.com/NuGet/NuGetGallery/commit/1c658259a0887bd935089284a8624a997e0438e6

**Comment by maartenba** [comment]
Would it make sense to show the index status instead, e.g. "Not indexed yet - last index created X minutes ago"?

**Comment by yishaigalatzer** [comment]
That sounds good as well, we can make it a link to the page from 2432 where it shows the location in the queue somewhere in the title

**Comment by maartenba** [comment]
Proposed design:

![Uploading screenshot.png…]()

**Comment by yishaigalatzer** [comment]
I assume listed shows up only for package owner.

I also assume indexed is going to have a link (eventually) and will update through Ajax once indexing is done?

**Comment by maartenba** [comment]
Listed is only package owner indeed. Indexed could be a link if we have a status page showing indexing status.

**Comment by johnataylor** [comment]
Is there a less obvious visual clue to indicate that something hasn't yet been indexed? For example fade out the font or something.

Here is my concern: when we fix the really quite basic problems in search we should be aiming for index updates in seconds not minutes. At which point we just have all this pointless yes, yes, yes, down the right side of the list.

For the new gallery the whole thing is just inflated from the Lucene state (or extended state) anyhow so this isn't a behavior that we are carrying forward anyhow.

**Comment by maartenba** [comment]
It's only showing when there is (at least) one version that's not indexed. Packages that have everything in index will not even show this column, basically making the page look like it looks today.

**Comment by maartenba** [comment]
@johnataylor Made a modification to make it less intrusive in the list: added the word "pending" with a tooltip.

![untitled](https://cloud.githubusercontent.com/assets/485230/7964642/1b9f8e7a-0a19-11e5-827e-5abeec80ab16.png)

**Comment by maartenba** [comment]
Logged #2527 to make this issue obsolete in the longer run.

**Comment by maartenba** [comment]
Deployed.
