### ISSUE TITLE
Setup a telemetry for NuGet Gallery to capture performance and usage data

### ISSUE THREAD

**Issue by abdullin** [NuGet/NuGetGallery#2525]
Nuget services are in a challenging position. They are included by default into Visual Studio, referenced everywhere in .NET ecosystem on Microsoft (and would probably be further used in new Linux tooling).

After all: _NuGet is the package manager for the Microsoft development platform including .NET. ... The NuGet Gallery is the central package repository used by all package authors and consumers._ 

People pay for Visual Studio, MSDN subscriptions, they expect it all to work flawlessly. When something (that they already paid their bloody money for) prevents them from doing their work (and then going home to loved ones), they could be rightfully infuriated. Even if that something is in reality a small separate project, managed by a small team without a lot of resources.

In my experience, this situation could be improved a little bit by:

1. Being more public about the project challenges, limitations, everyday use patterns (regular blog posts by team members could do the trick, they could also be a great PR campaign to let people understand the situation).
2. Learning more about how nuget.org is actually used, how it behaves and then improve that! 

I would recommend to start addressing the second point by setting up a proper telemetry for the Nuget gallery (here is a [brief description of setup that works the best for .NET for me](https://abdullin.com/telemetry/)) and capture following data:

1. Number of requests against different APIs, their latency.
2. Queue depth for the indexing jobs
3. Processing delay distribution for indexing jobs
4. Number of exceptions being thrown across the system.

Once you have the information, you would be able to see the bottlenecks and issues more clearly. Besides, that would also make a great material for the blog post.

**Comment by yishaigalatzer** [comment]
@abdullin this is good feedback.

We are tracking most of this information already, and we are going to augment it with app insights this week.

Its probably not a bad idea to look at your other suggestions once we get through the next two waves (S1 & S2) and figure out what else we want to start tracking.

Thanks again for the input

**Comment by maartenba** [comment]
Linking #2478 (internal telemetry via AppInsights)

**Comment by yishaigalatzer** [comment]
Done. Augmented the telemertry with AppInsights. Thanks for the advice!
