### ISSUE TITLE
Elmah error when service degradation happens

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2529]
Today morning we had a fluctuation in DC0 search and looks like Gallery falled back to DC1 and there were errros in Elmah around it @ https://www.nuget.org/Admin/Errors.axd/detail?id=1656112.

right now it just shows as "Aggregate error". it would be good, if we show specific exception, so that we can do alerting on it if required.

**Comment by maartenba** [comment]
It *should* be more specific using quietlog, the AggregateException shows something else. Feel free to assign this to me for S2 during triage.

**Comment by maartenba** [comment]
Updated the code to log the degradations to AppInsights instead. After a next deployment, ELMAH will no longer have these errors and instead will show the actual error that caused the degradation.

**Comment by maartenba** [comment]
May need to add alerting on this one.
