### ISSUE TITLE
Need new Replication API

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2533]
NuGet needs a new efficient and reliable replication API:
1) ideally this should be exposed from static cloud storage directly
2) the protocol should support the ability for multiple clients to maintain their own read cursor position
3) the protocol should support adds, updates and deletes

In v3 the protocol is called the Catalog.

The gap is that we need a first class, easy to use, client library for dealing with this protocol.

**Comment by maartenba** [comment]
Node.js: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/tests/CatalogTests/Node/collect.js

**Comment by skofman1** [comment]
We have sample code on how to replicate nuget.org using catalog: https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages
Will created sample library if asked by users.
