### ISSUE TITLE
Accessing the blog tab of nuget.org - blog.nuget.org uses an invalid security certificate

### ISSUE THREAD

**Issue by jmp75** [NuGet/NuGetGallery#2535]
Was looking for information about a possible API to analyse package stats - came across links to blog .nuget.org via google

Firefox 38.0.5
Windows7

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

blog.nuget.org uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, github.com, *.github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com (Error code: ssl_error_bad_cert_domain)

**Comment by hickford** [comment]
I think `includeSubDomains` is too strong in the Strict-Transport-Security header.

https://github.com/NuGet/NuGetGallery/blob/96a15f5b19e23a46e60923204e29fb84eb8aaff2/src/NuGetGallery/Web.config#L247

**Comment by hickford** [comment]
I think this has also broken http://status.nuget.org/  . Chrome and Firefox will use https://status.nuget.org/ , which times out.

**Comment by vcsjones** [comment]
This is kind of a gnarly issue. Even if you remove the HSTS header, it'll still be broken for people that managed to capture HSTS header.

**Comment by maartenba** [comment]
Yeah agreed. We're changing this to no longer include `includeSubDomains`. Once deployed (will notify via this GitHub issue), you will have to manually clear HSTS settings in your browser.

Here's a how-to: http://classically.me/blogs/how-clear-hsts-settings-major-browsers

**Comment by hickford** [comment]
Gnarly yes but (reading the spec carefully) I think after removing `includeSubDomains` browsing to https://www.nuget.org/ will update the browser cache, so you can get to http://blog.nuget.org again

**Comment by vcsjones** [comment]
@hickford that is my understanding as well.

**Comment by maartenba** [comment]
Deployed, please visit www.nuget.org or clear HSTS in browser.

**Comment by vcsjones** [comment]
Confirmed, thanks.
