### ISSUE TITLE
Issues building NuGet from Home page instructions

### ISSUE THREAD

**Issue by stunney** [NuGet/NuGetGallery#2539]
My first hurdle was that I needed to add C:\Users\Stephen\Documents\GitHub\NuGet.Home\nupkgs as a local nuget repo so that NuGet.CommandLine.Cmd (beta 3.1.0) et al would install after all tests were completed.

I have gotten MUCH further in the compilation however now I am running into the following error 

C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft
.NuGet.targets(58,5): error MSB4062: The "Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets" task could not be load
ed from the assembly C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integr
ation\build\Microsoft.NuGet.Build.Tasks.dll. Could not load file or assembly 'Microsoft.NuGet.Build.Tasks, Version=14.0
.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exc
eption from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dep
endencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:
\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]
Build failed
At C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\pack.ps1:78 char:5
+           throw "Build failed"
+           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed

I opened "C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integr
ation\build\Microsoft.NuGet.Build.Tasks.dll" in depends.x64 2.2.6000 and it is showing that this DLL is x86 compiled and ALL of its dependencies on my machine are x64.

IESHIMS.DLL
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-0.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-0.DLL
API-MS-WIN-CORE-FILE-L2-1-0.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-1-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-1.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-0.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
KERNEL32.DLL
KERNELBASE.DLL
MSCOREE.DLL
NTDLL.DLL
ACLUI.DLL
ACTIVEDS.DLL
ADSLDPC.DLL
ADVAPI32.DLL
ADVPACK.DLL
API-MS-WIN-APPMODEL-IDENTITY-L1-1-0.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-APPMODEL-STATE-L1-1-0.DLL
API-MS-WIN-BASE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-BEM-L1-1-0.DLL
API-MS-WIN-CORE-BIPLMAPI-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-0.DLL
API-MS-WIN-CORE-COM-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-JOB-L2-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-PATH-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L2-1-0.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRYUSERSPECIFIC-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-TOOLHELP-L1-1-0.DLL
API-MS-WIN-CORE-URL-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-VERSIONANSI-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERRORPRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-PROPERTYSETPRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-REGISTRATION-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-0.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-NORMALIZ-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-OLE32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHELL32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-USER32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-VERSION-L1-1-0.DLL
API-MS-WIN-DX-D3DKMT-L1-1-0.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
API-MS-WIN-EVENTING-LEGACY-L1-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTLOG-LEGACY-L1-1-0.DLL
API-MS-WIN-MM-JOYSTICK-L1-1-0.DLL
API-MS-WIN-MM-MISC-L1-1-0.DLL
API-MS-WIN-MM-MISC-L2-1-0.DLL
API-MS-WIN-MM-MME-L1-1-0.DLL
API-MS-WIN-MM-TIME-L1-1-0.DLL
API-MS-WIN-NTUSER-DC-ACCESS-L1-1-0.DLL
API-MS-WIN-NTUSER-RECTANGLE-L1-1-0.DLL
API-MS-WIN-NTUSER-SYSPARAMS-L1-1-0.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-SECURITY-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
API-MS-WIN-SECURITY-AUDIT-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L2-1-0.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDLPARSECOND-L1-1-0.DLL
API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-0.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
API-MS-WIN-SHCORE-COMHELPERS-L1-1-0.DLL
API-MS-WIN-SHCORE-OBSOLETE-L1-1-0.DLL
API-MS-WIN-SHCORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-0.DLL
API-MS-WIN-SHCORE-STREAM-L1-1-0.DLL
API-MS-WIN-SHCORE-STREAM-WINRT-L1-1-0.DLL
API-MS-WIN-SHCORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-SHCORE-THREAD-L1-1-0.DLL
API-MS-WIN-SHCORE-UNICODEANSI-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLCOM-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLFOLDERS-L1-1-0.DLL
APPHELP.DLL
APPREPAPI.DLL
AUTHZ.DLL
AVRT.DLL
BCP47LANGS.DLL
BCRYPT.DLL
BCRYPTPRIMITIVES.DLL
BROWCLI.DLL
CABINET.DLL
CERTCA.DLL
CFGMGR32.DLL
CHARTV.DLL
COMBASE.DLL
COMCTL32.DLL
COMCTL32.DLL
COMDLG32.DLL
CREDUI.DLL
CRYPT32.DLL
CRYPTBASE.DLL
CRYPTSP.DLL
CRYPTUI.DLL
CSCAPI.DLL
D2D1.DLL
D3D11.DLL
DAVHLPR.DLL
DBGHELP.DLL
DCOMP.DLL
DEVMGR.DLL
DEVOBJ.DLL
DEVRTL.DLL
DFSCLI.DLL
DHCPCSVC.DLL
DHCPCSVC6.DLL
DNSAPI.DLL
DPAPI.DLL
DRVSTORE.DLL
DSPARSE.DLL
DSROLE.DLL
DUI70.DLL
DUSER.DLL
DWMAPI.DLL
DWRITE.DLL
DXGI.DLL
EAPPCFG.DLL
EAPPPRXY.DLL
EFSADU.DLL
EFSUTIL.DLL
ELSCORE.DLL
ESENT.DLL
EXT-MS-WIN-ADVAPI32-EVENTINGCONTROLLER-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-MSI-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-PSM-APP-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-REMOTE-L1-1-0.DLL
EXT-MS-WIN-COM-CLBCATQ-L1-1-0.DLL
EXT-MS-WIN-COM-OLE32-L1-1-0.DLL
EXT-MS-WIN-COM-PSMREGISTER-L1-1-0.DLL
EXT-MS-WIN-DOMAINJOIN-NETJOIN-L1-1-0.DLL
EXT-MS-WIN-FIREWALLAPI-WEBPROXY-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-CREATE-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-L1-1-0.DLL
EXT-MS-WIN-GDI-DEVCAPS-L1-1-0.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-0.DLL
EXT-MS-WIN-GDI-FONT-L1-1-0.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-0.DLL
EXT-MS-WIN-GDI-PATH-L1-1-0.DLL
EXT-MS-WIN-GDI-RENDER-L1-1-0.DLL
EXT-MS-WIN-GDI-RGN-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-CURRENT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MPR-MULTIPLEPROVIDERROUTER-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-DC-ACCESS-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-GUI-L1-1-0.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-0.DLL
EXT-MS-WIN-NTUSER-MISC-L1-1-0.DLL
EXT-MS-WIN-NTUSER-PRIVATE-L1-1-0.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYSPARAMS-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOWCLASS-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOWSTATION-L1-1-0.DLL
EXT-MS-WIN-OLE32-BINDCTX-L1-1-0.DLL
EXT-MS-WIN-OLE32-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-PROFILE-USERENV-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-L1-1-0.DLL
EXT-MS-WIN-SESSION-WINSTA-L1-1-0.DLL
EXT-MS-WIN-SESSION-WTSAPI32-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-CFGMGR32LOCAL-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-CFGMGR32REMOTE-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLFOLDERS-L1-1-0.DLL
EXT-MS-WIN-SXS-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-WLAN-ONEXUI-L1-1-0.DLL
FIREWALLAPI.DLL
FLTLIB.DLL
FMS.DLL
GDI32.DLL
GDIPLUS.DLL
HLINK.DLL
IEADVPACK.DLL
IEFRAME.DLL
IERTUTIL.DLL
IEUI.DLL
IMAGEHLP.DLL
IMGUTIL.DLL
IMM32.DLL
INETCOMM.DLL
IPHLPAPI.DLL
LINKINFO.DLL
LOGONCLI.DLL
MFC42U.DLL
MFPLAT.DLL
MLANG.DLL
MMDEVAPI.DLL
MPR.DLL
MPRAPI.DLL
MPRMSG.DLL
MRMCORER.DLL
MSASN1.DLL
MSCTF.DLL
MSFEEDS.DLL
MSHTML.DLL
MSI.DLL
MSILTCFG.DLL
MSIMG32.DLL
MSLS31.DLL
MSOERT2.DLL
MSRATING.DLL
MSVCRT.DLL
NCRYPT.DLL
NDFAPI.DLL
NETAPI32.DLL
NETUTILS.DLL
NEWDEV.DLL
NINPUT.DLL
NSI.DLL
NTASN1.DLL
NTDSAPI.DLL
NTSHRUI.DLL
OCCACHE.DLL
ODBC32.DLL
OLE32.DLL
OLEACC.DLL
OLEAUT32.DLL
OLEDLG.DLL
ONEX.DLL
PCACLI.DLL
PCWUM.DLL
POWRPROF.DLL
PRINTUI.DLL
PRNTVPT.DLL
PROFAPI.DLL
PROPSYS.DLL
PUIAPI.DLL
RASAPI32.DLL
RASDLG.DLL
RASMAN.DLL
REGAPI.DLL
RPCRT4.DLL
RSTRTMGR.DLL
RTUTILS.DLL
SAMCLI.DLL
SAMLIB.DLL
SCECLI.DLL
SECUR32.DLL
SENSAPI.DLL
SETUPAPI.DLL
SHCORE.DLL
SHDOCVW.DLL
SHELL32.DLL
SHLWAPI.DLL
SLC.DLL
SPFILEQ.DLL
SPINF.DLL
SPPC.DLL
SRVCLI.DLL
SSPICLI.DLL
TAPI32.DLL
TWINAPI.DLL
UIAUTOMATIONCORE.DLL
URLMON.DLL
USER32.DLL
USERENV.DLL
USP10.DLL
UXTHEME.DLL
VERSION.DLL
VIRTDISK.DLL
VPNIKEAPI.DLL
W32TOPL.DLL
WDI.DLL
WEBIO.DLL
WEBSERVICES.DLL
WEBSOCKET.DLL
WER.DLL
WERUI.DLL
WEVTAPI.DLL
WINBRAND.DLL
WINDOWSCODECS.DLL
WINHTTP.DLL
WININET.DLL
WINMM.DLL
WINMMBASE.DLL
WINNSI.DLL
WINSCARD.DLL
WINSPOOL.DRV
WINSTA.DLL
WINTRUST.DLL
WKSCLI.DLL
WLANAPI.DLL
WLDAP32.DLL
WMICLNT.DLL
WS2_32.DLL
WTSAPI32.DLL
XMLLITE.DLL

**Comment by yishaigalatzer** [comment]
This issue should move to home

**Comment by pranavkm** [comment]
The build script needs some fixing - I'll look into this.

**Comment by stunney** [comment]
Hey @pranavkm , any idea where I could start looking to try and fix this while you are on other tasks?

**Comment by yishaigalatzer** [comment]
Closing the bug, please follow up with a bug in the home repo if you still can't the build to work by Tuesday
