### ISSUE TITLE
Fix issues with lucene index fall back

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2547]
As part of backing up lucene index, we need to take care of segments getting too big need to be taken care of. Also we need to moving to premium storage ( so that transfer rate will be faster). 
When there is a fallback, we need to aware of it ( through AppInsights/Monitoring).

**Comment by maartenba** [comment]
Any pointers on how to reproduce this behaviour?

**Comment by johnataylor** [comment]
1) add lots of documents, enough to trigger merges for very large segments
2) you can probably add fewer documents if you play with the merge settings
3) calling optimize on the index can merge segments (its often not a good thing to do, but in the interests of investigating problems it might be a useful approach.)
