### ISSUE TITLE
Uninstall.ps1 is not invoked for solution-only packages

### ISSUE THREAD

**Issue by chris-burt** [NuGet/NuGetGallery#2549]
uninstall.ps1 should invoke on uninstall, but it does not for solution-only packages. This is an obstacle when steps are performed in Init.ps1 or Install.ps1 to change the state of the project.  Uninstall.ps1 is need to undo the changes made during install.

**Comment by yishaigalatzer** [comment]
We are removing support for solution level pacakges in Visual Studio 2015. Long term we are removing support for install.ps1 in new scenario, which reduces the importance of dealing with this issue even further

Aside: Please file nuget client bugs in the home repo.

**Comment by chris-burt** [comment]
Thank you for the quick feedback.
