### ISSUE TITLE
No submodule mapping found in .gitmodules for path.No Submodule present

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2551]
I'm getting this error while deploying NugetGallery git project on azure website.

But when I try following command and check I have not found any submodule

C:\NuGetGallery-master [master]> git ls-files --stage | grep 160000
160000 e35ece8c542e50bcfd71d0c5ed528d1b8206389f 0       mydemonugetgallery 
what should be cause ?
deployment failed error : Updating submodules.

No submodule mapping found in .gitmodules for path 'mydemonugetgallery'

D:\Program Files (x86)\Git\bin\git.exe submodule update --init --recursive

**Comment by maartenba** [comment]
Can you run `git rm --cached mydemonugetgallery`?
