### ISSUE TITLE
NuGet.Indexing code needs unit tests

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2552]
Now we have migrated some of the SQL logic into Lucene filters we should add unit tests for these cases:
1) Curated Feed and Latest Version filters
2) Query Parsing

**Comment by bhuvak** [comment]
we have some funcitonal tests in V2 search repo : https://github.com/NuGet/NuGet.Services.Search/tree/master/test
We need to migrate this sln to meta repo ( in a different folder) and add more tests to this.

**Comment by maartenba** [comment]
@joelverhagen I'm guessing this is part of consolidation work? If so, feel free to close this issue.

**Comment by maartenba** [comment]
@joelverhagen added a good series of tests - closing issue
