### ISSUE TITLE
pushing nugetGallery to windows azure website getting error: The OutputPath property is not set for project 'NuGetGallery.csproj'.  

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2553]
I took codebase from https://github.com/NuGet/NuGetGallery to push nugetgallery on my own azure website but failed.
I'm getting following error and deployment failed.

 D:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(609,5): error : The OutputPath property is not set for project 'NuGetGallery.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\home\site\repository\src\NuGetGallery\NuGetGallery.csproj]

But I have already set output configuration to "Release" then also getting this error why?

**Comment by sebastienros** [comment]
It is unclear if you are having issues uploading a package on your own gallery or you that you can't even deploy the gallery successfully. On the latter, based on the stacktrace you are tying to copy the source code repository to the website and compile there. If this is the case then I would suggest you build it locally and publish it using the Publish command from Visual Studio to your Azure Website.

**Comment by ashuthinks** [comment]
actually when I build nuget Gallery full solution it is giving me two errors below 
"C:\Users\Documents\GitHub\NuGetGallery\build.msbuild" (default target
) (1) ->
"C:\Users\Documents\GitHub\NuGetGallery\packages\NuGet.Services.Build.
3.0.8\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"C:\Users\Documents\GitHub\NuGetGallery\NuGetGallery.sln" (Build targe
t) (3) ->
"C:\Users\Documents\GitHub\NuGetGallery\src\NuGetGallery\NuGetGallery.
csproj" (default target) (4) ->
"C:\Users\Documents\GitHub\NuGetGallery\src\NuGet.Services.Search.Clie
nt\NuGet.Services.Search.Client.csproj" (default target) (6) ->
(BuildPackage target) ->
  C:\Users\Documents\GitHub\NuGetGallery\.nuget\NuGet.targets(109,9):
error : A stable release of a package should not have on a prerelease dependenc
y. Either modify the version spec of dependency "NuGet.Services.Platform.Client
 (≥ 3.0.29-r-master)" or update the version field. [C:\Users\\Documents
\GitHub\NuGetGallery\src\NuGet.Services.Search.Client\NuGet.Services.Search.Cli
ent.csproj]
  C:\Users\Documents\GitHub\NuGetGallery\.nuget\NuGet.targets(109,9):
error MSB3073: The command ""C:\Users\Documents\GitHub\NuGetGallery\pa
ckages\NuGet.Services.Build.3.0.8\tools\\nuget.exe" pack "C:\Users\Doc
uments\GitHub\NuGetGallery\src\NuGet.Services.Search.Client\NuGet.Services.Sear
ch.Client.csproj" -Properties "Configuration=Debug;Platform=AnyCPU" -NonInterac
tive -OutputDirectory "C:\Users\Documents\GitHub\NuGetGallery\src\NuGe
t.Services.Search.Client\bin\Debug" -symbols" exited with code 1. [C:\Users\fug
atash\Documents\GitHub\NuGetGallery\src\NuGet.Services.Search.Client\NuGet.Serv
ices.Search.Client.csproj]

**Comment by ashuthinks** [comment]
Hi I have changed the topic and comment please check and reply  thanks

**Comment by iecompattest** [comment]
test the test in the test I think I can testssdf I like to test test sdfsdfsdfadfa dsfadsf sa

**Comment by maartenba** [comment]
Closing for now.
