### ISSUE TITLE
The main link to package "Microsoft Azure Amqp master 0.0.0.723" does not work

### ISSUE THREAD

**Issue by tameraw** [NuGet/NuGetGallery#2554]
Steps:
1. Run a search for "amqp"
2. From the search results, click on the link "Microsoft Azure Amqp master", you will hit 404 error.
Here is what I noticed. The link "Microsoft Azure Amqp master" has the wrong address:
https://ms-nuget.cloudapp.net/packages/Microsoft.Azure.Amqp.master

But if you click on the icon right next to it, you get routed to the correct address:
https://ms-nuget.cloudapp.net/packages/Microsoft.Azure.Amqp.master/0.0.0.723

Please help fix.

thanks,
-Tamer Awad

**Comment by maartenba** [comment]
This looks like an issue with internal NuGet server. Please reach out on internal alias.
