### ISSUE TITLE
xml in bin folder problem

### ISSUE THREAD

**Issue by nasgarothvip** [NuGet/NuGetGallery#2556]
Nuget not copying xml files along with dll in bin folder. Dlls appears, xml file not. I need provide xml file along with my dlls so this is a real problem. Please fix or provide any real solution. Regards

**Comment by nasgarothvip** [comment]
No one has any idea ????

**Comment by davidfowl** [comment]
NuGet doesn't copy files to the output directory. If you need the xml files in the output directory then change the msbuild `Copy to Output Directory` to Copy if newer or Copy Always
