### ISSUE TITLE
Configure gallery to make use of storage secondary

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2560]

**Comment by maartenba** [comment]
client.LocationMode = LocationMode.PrimaryThenSecondary;

**Comment by maartenba** [comment]
@xavierdecoster Can you do a quick review on https://github.com/NuGet/NuGetGallery/commit/78c13ef831e0844a9ae3b6bc54f68344cba32f86?

**Comment by xavierdecoster** [comment]
@maartenba looks good to me
