### ISSUE TITLE
Site alert banner: decide on one format instead of making 3 requests every few minutes

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2563]

**Comment by xavierdecoster** [comment]
minutes? how about each page load... :)

**Comment by maartenba** [comment]
I thought we cached that thing? :dizzy_face:

**Comment by maartenba** [comment]
Added to dev branch, we now cache it as well. Standardized on ".md". https://github.com/NuGet/NuGetGallery/commit/e71853ce4b60ce23f6be16c72755ecbbb2c2940b
