### ISSUE TITLE
Emails should not be sent synchronously

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2565]
Ideally they are not even a gallery responsibility

**Comment by AlexBHarley** [comment]
Can we discuss "Ideally they are not even a gallery responsibility" more? What is the process in removing the email service from the gallery? Is it another repo in Nuget?

**Comment by csharpfritz** [comment]
Is there an architecture under consideration here?

Create an INotificationProvider in gallery and define an EmailNotificationProvider in an external library to perform the public gallery's specific tasks?

Insert a record into an Azure queue for another microservice  or webjob to process?

There are a number of options to address this. Is this a deliverable required before //build?

**Comment by maartenba** [comment]
This is one for the NuGet team I'm afraid ;-)

**Comment by xavierdecoster** [comment]
I'd prefer the Azure queue approach here to decouple the gallery from 'handling the message'.

The improved support request functionality ideally should also leverage this, as we have dependencies in there (e.g. PagerDuty) that not every gallery deployment needs/wants. In addition, it would help reduce the problem of support email that didn't go through the support request system.
