### ISSUE TITLE
Make worker jobs RTM ready

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2566]
We need to do the below things for worker jobs :  

1. Make the deployments go through octopus.
2. Deploy the latest bits in master.
3. Validate the E2E latency and fix issues around it.
4. Make the "Reg-1" container that has the bug fixes as the primary one pointed by index.json.
5. Add monitoring to track memory/CPU for jobs VM.

**Comment by maartenba** [comment]
@bhuvak is this one complete? Can it be closed?
