### ISSUE TITLE
QUESTION: Generic URL to latest pre-release package on NuGet?

### ISSUE THREAD

**Issue by anders9ustafsson** [NuGet/NuGetGallery#2567]
Sorry for posting a question among the issues, but I have gotten no response on StackOverflow. I hope to get luckier here.  

---

The latest **stable** version of a _NuGet_ package PACKAGE is easily located via the generic URL

> https://www.nuget.org/packages/PACKAGE/

Is there a generic URL analogue to the latest **pre-release** version of the same NuGet package?

**Comment by maartenba** [comment]
There is no such URL currently. You could use the API to query for the latest prerelease of a package though, for example:

`https://www.nuget.org/api/v2/FindPackagesById()?Id=%27GoogleAnalyticsTracker.Core%27&$filter=IsPrerelease&$orderby=Version%20desc&$top=1`

From this response, you can get the package URL.

**Comment by anders9ustafsson** [comment]
Many thanks for a great response, @maartenba !

**Comment by supergibbs** [comment]
Can this be reopened as a feature request for a generic URL for the latest pre-release?

`https://www.nuget.org/packages/PACKAGE/prerelease`

Use case is the NuGet badge for Bootstrap 4 Alpha:
https://github.com/twbs/bootstrap - Dynamically shows and links to the latest stable
https://github.com/twbs/bootstrap/tree/v4-dev - Dynamically shows the correct badge but link has to be maintained manually

**Comment by skofman1** [comment]
@supergibbs , can @maartenba 's suggestion work in your case?
You can get the latest prerelease package using this OData query: https://www.nuget.org/api/v2/FindPackagesById()?Id=%27bootstrap%27&$filter=IsPrerelease&$orderby=Version%20desc&$top=1

And construct the URL to the package yourself (https://www.nuget.org/packages/bootstrap/4.0.0-alpha6)

**Comment by supergibbs** [comment]
I don't see how I can do that in a markdown readme file. See the example in the bootstrap readme:

https://github.com/twbs/bootstrap/blob/v4-dev/README.md

**Comment by jevansaks** [comment]
I figured out from the linked PR that you can use "/absoluteLatest" on your nuget URL to get a link to the prerelease, like this: 

https://www.nuget.org/packages/Microsoft.UI.Xaml/absoluteLatest
