### ISSUE TITLE
Unable to register for a new account

### ISSUE THREAD

**Issue by nikhilogic** [NuGet/NuGetGallery#2568]
For the past several days when trying to register for new account I get the "oops something went wrong..." page. I am also unable to login with my existing account. I get the same page

**Comment by xavierdecoster** [comment]
Thanks for reporting! We just deployed an update to the gallery that should fix the issue.
If you still experience this problem when trying to authenticate or register for a new account, then feel free to reopen the bug.

**Comment by nikhilogic** [comment]
Thanks for looking at this. Unfortunately the Issue still exists
