### ISSUE TITLE
add unlisted packages to the dnx feed

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2571]
Currently the dnx feed contains a JSON array of listed versions of a package. We also need an array of unlisted versions of a package.

**Comment by anurse** [comment]
The preference would be to have two lists: `versions` and `unlistedVersions` (that way old versions of DNX can still process the old blobs, they just won't see unlisted versions)

**Comment by skofman1** [comment]
@joelverhagen  @emgarten , is this related to your discussions?

**Comment by joelverhagen** [comment]
The list already contains all versions (listed and unlisted). For example, take a look at this one:
https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json

I don't know the context or scenario of this issue, but in general this would give clients an extremely simple way of seeing if a version is listed or not (e.g. the badges.io case).

**Comment by joelverhagen** [comment]
badges.io tracking issue: https://github.com/NuGet/NuGetGallery/issues/3167
I think @maartenba unblocked them by hitting registration blobs instead.

**Comment by maartenba** [comment]
Still have a PR with them that doesn't get accepted... But yes, solved.
