### ISSUE TITLE
Unable to register for a new account or signin (Reopening #2568)

### ISSUE THREAD

**Issue by nikhilogic** [NuGet/NuGetGallery#2572]
https://github.com/NuGet/NuGetGallery/issues/2568

**Comment by xavierdecoster** [comment]
I cannot reproduce this issue. Can you please provide detailed steps to reproduce and any other information that helps proving and diagnosing the issue? Thanks!

**Comment by vidarkongsli** [comment]
I have the same problem. I have tried 
 - Log in using the microsoft account. The problem occurs when i have entered my desired user name and gravatar and click register
- Register "locally", providing username, password, etc.
- Retried after deleting all browser cookies
- Tried both in Chrome and firefox (both on Windows)

**Comment by xavierdecoster** [comment]
@vidarkongsli Can you provide me with a UTC timestamp of when you noticed this issue? This narrows the search in our logs.

I also have a few additional questions. Answering these will also help me trace the execution path.
* Do you already have a NuGet account (not linked to your MS account)? 
* Is the system recognizing your email address and suggesting you to link your existing NuGet account to the MS account you authenticated with?

**Comment by linvi** [comment]
I have the same issue. 

Do you already have a NuGet account (not linked to your MS account)?

*Yes*

Is the system recognizing your email address and suggesting you to link your existing NuGet account to the MS account you authenticated with?

*I cannot login with either the username or email. My account is not linked to a MS account.*

Can you provide me with a UTC timestamp of when you noticed this issue?

*Personally the error occurred at 4:21 pm UK Time.*

Linvi

**Comment by vidarkongsli** [comment]
@xavierdecoster 
- 16:54 UTC
- No
- No, it states that "It looks like we haven't seen the Microsoft account 'Vidar Kongsli' before."

**Comment by xavierdecoster** [comment]
Thanks for the details, will follow up as soon as we learn more.

**Comment by nikhilogic** [comment]
Thanks.
It looks like I am only having the issue with my user id "nikhilogic".
I tried creating a new account with some random characters and it seems to work.
Would someone be able to either reset or delete my user id from the Nuget?
Time of issue (UTC) : 12:14 AM, Wednesday, July 1, 2015

**Comment by xavierdecoster** [comment]
The following commit has been deployed and should fix this issue: https://github.com/NuGet/NuGetGallery/commit/0c6705128a159418649348cfe169c0f3710cac1a

Please give it another go and confirm/verify whether the issue has been resolved.
Thanks!

**Comment by linvi** [comment]
Worked for me thanks :)

**Comment by vidarkongsli** [comment]
Worked for me as well. Thx, guys.

**Comment by xavierdecoster** [comment]
Thanks for confirming!
