### ISSUE TITLE
Dependencies on .NET Framework

### ISSUE THREAD

**Issue by BlackMael** [NuGet/NuGetGallery#2574]
I did a quick search through issues so sorry if this has been mentioned but why are some packages not defining/stating their dependency on .specific NET framework versions?

For example...  I have a .NET 4.0 Web App and Microsoft.AspNet.Web.Optimization.WebForms v1.1.3 allows me to install it via powershell console. The gallery page does not state that the latest version is for .NET 4.5 but Nuget happily installs the version despite it not being able to add the reference into a .NET 4.0 project.

Similar issues with Microsoft.AspNet.Mvc

Also the updat-package isn't aware of the .NET dependency and will happily upgrade to the incompatible version.

It seems the UI dialog filters out the invalid packages.  But it would be nice is the project page in the gallery would also make it a little more obvious.

Note, I've got installed Package Manager Console Host Version 2.8.60318.734

Here is some -WhatIf output for my .NET 4.0 Web App...
PM> update-package -WhatIf Microsoft.AspNet.Mvc -ProjectName MyWebApp
Updating 'Microsoft.AspNet.Mvc' from version '4.0.40804.0' to '5.2.3' in project 'MyWebApp'.
Remove 'Microsoft.AspNet.Mvc 4.0.40804.0' from project MyWebApp.
Remove 'Microsoft.AspNet.WebPages 2.0.30506.0' from project MyWebApp.
Remove 'Microsoft.AspNet.Razor 2.0.30506.0' from project MyWebApp.
Add 'Microsoft.AspNet.Razor 3.2.3' to project MyWebApp.
Install 'Microsoft.AspNet.Razor 3.2.3'
Add 'Microsoft.AspNet.WebPages 3.2.3' to project MyWebApp.
Install 'Microsoft.AspNet.WebPages 3.2.3'
Add 'Microsoft.AspNet.Mvc 5.2.3' to project MyWebApp.
Install 'Microsoft.AspNet.Mvc 5.2.3'
Uninstall 'Microsoft.AspNet.Mvc 4.0.40804.0'.
Uninstall 'Microsoft.AspNet.WebPages 2.0.30506.0'.
Uninstall 'Microsoft.AspNet.Razor 2.0.30506.0'.

Note, without the -WhatIf it does happily upgrade the packages despite it not being valid.

**Comment by yishaigalatzer** [comment]
Move to home
