### ISSUE TITLE
Fix Project URL of NuGet.Server package

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2576]
The Project Site link from https://www.nuget.org/packages/NuGet.Server/ leads to http://nuget.codeplex.com/, which now has a message directing to this project, https://github.com/nuget/home. I think the link at nuget.org should be rather changed to go directly to a project which builds the NuGet.Server package. And for the life of me I cannot find NuGet.Server sources on github...

Please untangle the links.

moved from https://github.com/NuGet/Home/issues/877

**Comment by yishaigalatzer** [comment]
This is because the package was published before we made the final move.

Regardless we should fix this in a future release

**Comment by issafram** [comment]
It is pretty bad.  I can't find the code anywhere on their official repos.

I found this from @Haacked https://github.com/Haacked/NuGet/tree/861741bd780225a542c73a1d0904dd33b33a7a3d/src/Server

That also says that it is mirrored from a CodePlex repo though: https://git01.codeplex.com/nuget which doesn't work for me.


I am so confused.

**Comment by yishaigalatzer** [comment]
We will finish moving over to github in the next few weeks

**Comment by xavierdecoster** [comment]
This PR on NuGet2 repo fixes it in code: https://github.com/NuGet/NuGet2/pull/9

Shall I update the metadata of the packages on nuget.org? 
Only the latest version, or all of them?

Proposed change for all NuGet v2 packages (NuGet.Core, NuGet.Server, etc):
* projectUrl: https://github.com/NuGet/NuGet2
* authors: .NET Foundation (currently still points to Outercurve Foundation)

**Comment by xavierdecoster** [comment]
Just updated package metadata for the latest releases of the following NuGet v2 packages:
* NuGet.Core
* NuGet.Server
* NuGet.Commandline
* NuGet.VisualStudio
* NuGet.Build
