### ISSUE TITLE
Recent Packages on Gallery UI to reduce server roundtrip and usability

### ISSUE THREAD

**Issue by guibirow** [NuGet/NuGetGallery#2577]
Hello guys, 

I was on your site/blog and saw a post about the issues with servers.
I'd like to suggest an feature that was on my mind for a long time, I didn't find anything about where should I sent feature request, so I'm sending it here.

On "Manage Nuget Gallery" UI, Would be nice an option "Recent packages", it's very common to reuse the same package among all projects on solution, instead of searching the package every time, we could reuse the same package downloaded before, will be faster an easier for us and will release a lot of resources from your Search Servers, CDN and API.

I know that I can manage the packages from solution, but would be easier if this option was on UI, because we apply direct on the project, through solution we have more steps to perform this task.

Thanks

**Comment by maartenba** [comment]
Moved your item to https://github.com/NuGet/Home/issues/933.

**Comment by maartenba** [comment]
We currently cache this first page to reduce server load. However this may be a good suggestion for the client in general.
