### ISSUE TITLE
Broken packages pagination

### ISSUE THREAD

**Issue by nmchristov** [NuGet/NuGetGallery#2578]
Currently the pagination is broken on page 131
https://www.nuget.org/packages?page=131
on 131st page there are only 7 projects and there are no Previous/Next pointers.

**Comment by yishaigalatzer** [comment]
Did you seriously paged 131 pages :) ?

**Comment by yishaigalatzer** [comment]
@xavierdecoster lets take a look to see if there is something else lurking here

**Comment by nmchristov** [comment]
@yishaigalatzer - yes I did paged 131 pages. I am building an index (scraping) nuget projects and the scraper stops at page 131 thinking there are no more pages. More importantly, it seems like some special char is braking the view.

**Comment by yishaigalatzer** [comment]
That's not the way to scrape the API. @xavierdecoster an help you with how to do it

**Comment by nmchristov** [comment]
That would be awesome.

**Comment by yishaigalatzer** [comment]
This is a good start  - https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Feed2Catalog.cs#L98

Note that this is a rather heavy operation, and we would like to ask you not to run this frequently as it puts a higher than usual load on the site.

We do plan to provide a more static based replication mechanism in the next few months, so ping us again (or follow our blogs where we will probably announce it)

**Comment by nmchristov** [comment]
Hey @yishaigalatzer and thanks for taking the time. I don't see how GetPackages(...) is tied to a route. Can you please explain. Thanks.

**Comment by yishaigalatzer** [comment]
It uses the odata feed

**Comment by maartenba** [comment]
@nmchristov you can do the scraping in an easier way by using the OData feed. Check this blog page for an example: http://blog.nuget.org/20130520/Play-with-packages.html (note the URL to the feed is `https://nuget.org/api/v2` - the blog post has an older URL in it)

**Comment by maartenba** [comment]
Fix has been deployed.
