### ISSUE TITLE
Custom Nuget Package Issue with TFS

### ISSUE THREAD

**Issue by RajivDadwal** [NuGet/NuGetGallery#2581]
I have wrapped up my java script code in Nuget package for distribution.Other team members can use this code by installing the nuget package created by us. this package contains nested folder structure and bulk java script  files.

I have created this package by using Nuget Package Explorer. Hosted it locally and run the command from package console. "install-package <packagename>".

 It works very well but the issue comes on TFS. When someone install the package on TFS project, it throws weird error "Collection Was Modified; Enumeration Operation May Not Execute." Al tough the package in installed with this error.

This is embracing  because we did everything but in the end it fails if we can not distribute that. Alternatively i have used batch file for that.

I have already posted an issue on the following url:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/3c9e8980-8ddd-4479-9e81-6423c9556c40/install-nuget-package-error-collection-was-modified-enumeration-may-not-execute-in-tfs?forum=tfsworkitemtracking&prof=required

They suggesting me to contact with Nuget team.
Is this a good practice to wrap up thousands of java scripts files in a package?  
Please look into this, i hope will get some resolution here.......

**Comment by maartenba** [comment]
Moved to https://github.com/NuGet/Home/issues/932

**Comment by RajivDadwal** [comment]
Closed Without resolution..... 
Great......

**Comment by maartenba** [comment]
Closed after moving to https://github.com/NuGet/Home/issues/932, which is still open.

**Comment by RajivDadwal** [comment]
ok, Sorry for the comments. Hope will get the resolution here.
