### ISSUE TITLE
Investigate use of Autofac instead of NInject

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2584]
Investigate use of Autofac instead of NInject

**Comment by Daniel15** [comment]
What's the advantage of Autofac over Ninject?

**Comment by Daniel15** [comment]
What's the advantage of Autofac over Ninject?

What about something like Simple Injector (which is very fast), or the built-in dependency injection in ASP.NET 5 Beta?

**Comment by maartenba** [comment]
Memory. NInject is a bad citizen when it comes to memory management under high web loads, at least that is what we are seeing on our servers.

**Comment by maartenba** [comment]
Deployed
