### ISSUE TITLE
Upgrade SQL Azure db servers to v12

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2589]
Needs anticipation: replication must be disabled during the upgrade process.

**Comment by xavierdecoster** [comment]
From the portal: 
>  The duration of upgrade ranges from several hours to days depending on the size, edition and number of databases in the server. During this time all databases on this server will remain online but certain server and database management actions will be restricted.

https://azure.microsoft.com/en-us/documentation/articles/sql-database-v12-plan-prepare-upgrade/

**Comment by maartenba** [comment]
Upgraded environments:
* Dev
* Int
* Prod

We're on V12 now :)
