### ISSUE TITLE
Package stats not updating https://www.nuget.org/packages/opencover

### ISSUE THREAD

**Issue by sawilde** [NuGet/NuGetGallery#2590]
The package download stats don't appear to be working for https://www.nuget.org/packages/opencover

Also, is it possible to remove packages (pre-release) that have no downloads (I understand why you may want to keep those that have already had downloads)? My build server and github had a bit of a recursive trigger/build/deploy/tag/trigger... cycle.

**Comment by maartenba** [comment]
Download stats are something we are working on. They will definitely be back, just not in the next few hours :)

Regarding your other question, please reach out to support@nuget.org.
