### ISSUE TITLE
VS2015 : Updating from one feed fails for packages from different feed.

### ISSUE THREAD

**Issue by ralfverstappen** [NuGet/NuGetGallery#2593]
We have two nuget feeds.
The default NuGet Offical feed and our own locally hosted feed for our own packages.
We package our libraries and push them to our feed.
From VS2013 we run a command in the package manager console to update packages from only our own feed by specifying the source (Update-Package -Source 'NAME OF OUR SOURCE').
This will update only our own packages.
This worked fine in VS2013.
In VS2015 this doesn't work anymore. We get an error on packages that are not from our source:

Update-Package : Package 'EntityFramework' is not foundAt line:1 char:1
+ Update-Package -Source 'NAME OF OUR SOURCE'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Anybody know how to update only from one source using the package manager console?

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1181
