### ISSUE TITLE
2013 Release: 2.8.60610.756 (NuGet check for updates broken) vsix download required?

### ISSUE THREAD

**Issue by tombrown571** [NuGet/NuGetGallery#2594]
After installing 2.8.60610.756 (on top of VS 2013 Update 5) I get an error loading package manager in NuGetVSEventsPackage

This appears to prevent NuGet from checking for updates.

Its very similar to this issue http://nuwanlanka.com/?p=85#comment-163 
From this blog, the fix appears to be to re-run the vsix package from outside visual studio - only as you are in the process of moving to GitHub, I can't find a download link for the correct vsix package (and I'm not sure it will fix the issue until I try it)

From the Activity Log
1090 ERROR CreateInstance failed for package [NuGetVSEventsPackage] {98BF0691-D23C-4897-A241-9CF5BEFDCC4A} 80070002 VisualStudio 2015/07/23 13:11:27.910 
1091 ERROR End package load [NuGetVSEventsPackage] {98BF0691-D23C-4897-A241-9CF5BEFDCC4A} 80004005 - E_FAIL VisualStudio 2015/07/23 13:11:27.910

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1180
