### ISSUE TITLE
Timeouts when pushing packages

### ISSUE THREAD

**Issue by Daniel15** [NuGet/NuGetGallery#2597]
I'm seeing frequent "The operation has timed out" errors when pushing packages to the NuGet gallery:

```
PushRelease:
  tools\NuGet\nuget.exe push output\React.AspNet.1.5.3.nupkg -NonInteractive
  Pushing React.AspNet 1.5.3 to the NuGet gallery (https://www.nuget.org)...
  The operation has timed out
C:\Users\danlo\Documents\Visual Studio 2015\Projects\React.NET\build.proj(156,3
): error MSB3073: The command "tools\NuGet\nuget.exe push output\React.AspNet.1
.5.3.nupkg -NonInteractive" exited with code 1.
Done Building Project "C:\Users\danlo\Documents\Visual Studio 2015\Projects\Rea
ct.NET\build.proj" (Package;Push target(s)) -- FAILED.

Build FAILED.
```

Even though the upload times out, the package does appear to be correctly uploaded (in this case, I was uploading https://www.nuget.org/packages/React.AspNet/1.5.3). It looks like the API request just never actually returns a response to the client.

**Comment by maartenba** [comment]
This may be in the client as well. On a future push, can you see if this happens when you also pass -Timeout 1234 ?

Will have a look at the server in the meanwhile.

**Comment by maartenba** [comment]
Did adding the -Timeout switch help?

**Comment by Daniel15** [comment]
I haven't had a chance to try again as I haven't had any packages to push :)  I can test it with a dummy package to see if that works.

**Comment by Daniel15** [comment]
Looks like this was a transient server-side issue, pushing  is a lot quicker now and hasn't been timing out for me.
