### ISSUE TITLE
Error trying to log in with old Nuget account

### ISSUE THREAD

**Issue by Jaykul** [NuGet/NuGetGallery#2599]
I wish I could tell you more, all I get is the relatively useless error page

> Sorry, an error occurred while processing your request.
> Error: Oh no, we broke something!

This happens if I try to log in with the old credentials, or if I try to log in with the Microsoft Account (it finds my old account and asks me to log in).

**Comment by Jaykul** [comment]
Seems this is related to #2438 -- I used the password reset to change to a simpler password and was able to get in.

**Comment by maartenba** [comment]
Thanks, will tackle as part of #2438
