### ISSUE TITLE
Getting list of all packages and their dependencies

### ISSUE THREAD

**Issue by anvaka** [NuGet/NuGetGallery#2600]
Hello Friends!

We are building [3D visualizations](http://anvaka.github.io/pm/#/) of popular package managers and [would like](https://github.com/anvaka/pm/issues/6) to add NuGet to the family.

I was trying to find what is the best way to download all packages as well as their dependencies. Could you please help?

**Comment by maartenba** [comment]
For NuGet, you can use the catalog. It is an append-log tree structure which has one blob page per “Add package” or “Edit Package” action that happens in the Gallery. All metadata of the package can be accessed from here. We use this catalog ourselves to populate the search index and so on. 

The root level index page of the catalog can be seen @ http://api.nuget.org/v3/catalog0/index.json. This has links to the individual pages (the second level nodes in the tree). The pages in turn will have links to the individual Package blobs (the leaf nodes the tree). Each leaf node will indicate a specific version of a package. 

To traverse through the catalog, you read the index and go to the individual pages from there and then follow the link to individual packages. Each “Page” (second level) and “Package” (leaf level) has a time stamp to indicate when it was created. If you are doing continuous replication, you can maintain a time stamp marker on your end (something like “LastRead”). Whenever you replication job starts, it will get the “LastRead” marker and go to the “Pages” created after the “LastRead” time stamp and go to the individual Packages.  

Sample code you say? You can clone the repo @ https://github.com/NuGet/NuGet.Services.Metadata. The https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Catalog2Registration.cs is an example of a “CatalogReader” which reads from the catalog and creates registration blobs. It maintains a LastReader marker which is stored in “Curson.json”. On similar lines https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Catalog2Lucene.cs is another “CatalogReader” which continuously reads from catalog and updates our search index.

**Comment by anvaka** [comment]
Thanks! That worked: http://anvaka.github.io/pm/#/galaxy/nuget?l=1
