### ISSUE TITLE
Feature: Reference conditionally based on target architecture in .nuspec

### ISSUE THREAD

**Issue by sjoerd222888** [NuGet/NuGetGallery#2601]
According to https://docs.nuget.org/create/nuspec-reference it is currently possible to conditionally reference packages depending on the target framework.

```xml
<references> 
  <group targetFramework="net45"> 
    <reference file="a.dll" />
  </group> 
  <group targetFramework="netcore45"> 
    <reference file="b.dll" /> 
  </group>
  <group>
    <reference file="c.dll" />
  </group>
</references>
```

It would be nice if this would also be possible regarding target architecture. By this I mean something like that:

```xml
<references> 
  <group targetArchitecture="x64"> 
    <reference file="a_x64.dll" />
  </group> 
  <group targetArchitecture="x86"> 
    <reference file="a_x86.dll" /> 
  </group>
  <group>
    <reference file="b.dll" />
  </group>
</references>
```

This issue might be related with: http://nuget.codeplex.com/workitem/679 (has this issue already been moved to github)

**Comment by maartenba** [comment]
Moved this issue to https://github.com/NuGet/Home/issues/1077
