### ISSUE TITLE
nuget deleting packages

### ISSUE THREAD

**Issue by mgwalm** [NuGet/NuGetGallery#2604]
I have a common local repository for all my packages for all my projects.

however if I uninstall a PACKAGE FROM ONE PROJECT AND IT IS NO LONGER USED BY THAT PROJECT IT DELETES THE PACKAGE. EVEN THOUGH IM USING IT ON OTHER PROJECTS.

please don't delete the package if the repository is not within the project's folders.

**Comment by maartenba** [comment]
Moved to https://github.com/NuGet/Home/issues/1097
