### ISSUE TITLE
Use latest version as dependency

### ISSUE THREAD

**Issue by remster85** [NuGet/NuGetGallery#2605]
Here is my setup.

I have a project that contains the wcf configuration (endpoints mostly) about a service. Let’s call it config package.

I have a service project that references the config dependency via nuget.

My problem is everytime the config is updated, I need to open the service project and manage my nuget dependency and request an update. It’s time consuming!

Is there any way to tell the service to reference the latest version available if any ?
I would only need to rerun the service project build instead.

I found this article https://docs.nuget.org/create/versioning.

They mention using empty version in order to get the latest but visual studio is not able to understand :
=> Unable to parse version value ” from ‘packages.config’.

Any clue how to do it ?

Thanks

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1210
