### ISSUE TITLE
Installing NuGet Docs - Dead Link (Latest Unreleased NuGet Build)

### ISSUE THREAD

**Issue by scovetta** [NuGet/NuGetGallery#2607]
Starting from [http://docs.nuget.org/consume/installing-nuget](http://docs.nuget.org/consume/installing-nuget), the last section contains:
"If you want to run the very latest unreleased build of NuGet, you can [http://build.nuget.org/NuGet.Tools.vsix](install it from the Build Server)."

That link goes to a page that presumably, most people don't have access to:
"There are no projects to show, because you don't have permissions to view projects. Please contact your system administrator."

**Comment by maartenba** [comment]
@csharpfritz This can be updated when we have the dist site up.
