### ISSUE TITLE
after upgrade, cannot reach internal nuget server

### ISSUE THREAD

**Issue by RipCurrent** [NuGet/NuGetGallery#2608]
hi,
can anyone give me guidance on this issue:

installed vs2015 & got latest nuget 3.1(?). Also upgraded command line to nuget v2.8.60717.93

I can reach external nuget feeds and localhost nuget feed.
I can no longer reach internal corporate nuget feeds. 404 error

I downloaded source code from codeplex and ran command line tool in debug mode.
With fiddler, I can see the v3 api call to internal server "{url}\intercept.json " which returns 404 (also see iis log entry)
After the 404, it then tries the request using v2 and just "{url}" and errors out
Nothing in fiddler for this or in IIS log, as if it never tried it.

other users who upgraded to VS2015 ok (they don't have command line). can ideas on how I might get going again here?
:)
thanks!

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1178
