### ISSUE TITLE
Visualize long package names

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2609]
The names of our packages are so long that they get clipped to the point of not being distinguishable. If we can’t shorten the name, let’s have the full name be at the start of the description paragraph so the user can see it.

![1](https://cloud.githubusercontent.com/assets/485230/9119156/840b4f9c-3c75-11e5-9875-0e8f1db9f8b9.png)

**Comment by maartenba** [comment]
Currently when hovering the abbreviated title, the full package name is shown. @yishaigalatzer @bhuvak @johnataylor @xavierdecoster suggested UI improvement is welcome.

**Comment by hbrock** [comment]
I uploaded a package to test this:
![image](https://cloud.githubusercontent.com/assets/1028907/9697499/c88e14ac-535d-11e5-9667-441eb691780e.png)

Do we want the title to be on two lines like in the above image? Or to have a short title and display the full name in the description paragraph

**Comment by yishaigalatzer** [comment]
We can also just reduce the font size a bit? Two lines may be even more confusing. This is something to experiment with a few samples and pick a winner.

**Comment by hbrock** [comment]
@maartenba I went with what you said about making the first line the title of the package. Would we want something like this:

![image](https://cloud.githubusercontent.com/assets/1028907/9700958/f67788c6-53e4-11e5-9a9b-dc990e01d61d.png)

Or something else like changing the font size of the title?

**Comment by csharpfritz** [comment]
We're going to consult with our designers and post a solution here after that discussion.  Thanks for the suggestions!

**Comment by hbrock** [comment]
Your welcome.

**Comment by skofman1** [comment]
This was fixed by the redesign. The entire id is always shown.
