### ISSUE TITLE
Owners icons not rendered in IE

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2610]
Chrome renders the icons but in IE on Win8 and 10, they don’t load.

![3](https://cloud.githubusercontent.com/assets/485230/9119214/d13e012e-3c75-11e5-90f9-00bbdc0438e1.png)

**Comment by maartenba** [comment]
Caused by https://github.com/NuGet/NuGetGallery/issues/2613

**Comment by maartenba** [comment]
Can be fixed using something like [CamoDotNet](https://github.com/maartenba/CamoDotNet)

**Comment by maartenba** [comment]
Can I be unassigned from this one? :-)

**Comment by joelverhagen** [comment]
This is fixed. Owners icons (Gravatars) are all served over HTTPS. Icon URLs are covered by https://github.com/NuGet/NuGetGallery/issues/2613.
