### ISSUE TITLE
Alerting when service index can not be read for a number of times

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2611]
Add alerting when service index document can not be read for a number of times.

**Comment by skofman1** [comment]
Does this issue propose adding pingdom monitoring for api.nuget.org/v3/index.json ?

**Comment by maartenba** [comment]
When gallery can't read index.json, though this never happened since opening the issue...

**Comment by skofman1** [comment]
Gallery no longer depends on index.json. We have other types of monitoring to cover other cases.
