### ISSUE TITLE
Trying to contact Package Owner and it keeps asking for email confirmation

### ISSUE THREAD

**Issue by howardg** [NuGet/NuGetGallery#2612]
I have already confirmed twice now.  When I just registered and when it asked me the first time.  Any help would be appreciated.

Thank you.

**Comment by maartenba** [comment]
What is the username you registered?

**Comment by howardg** [comment]
Hi,

howardbg

Thank you.

**Comment by maartenba** [comment]
Your username should now be confirmed.

**Comment by howardg** [comment]
Thank you.
