### ISSUE TITLE
NuGet Package Manager (3.1) shows descriptions from old versions of the package

### ISSUE THREAD

**Issue by MarcosMeli** [NuGet/NuGetGallery#2618]
For example in this package:

https://www.nuget.org/packages/FileHelpers-Stable/

You can see:

![image](https://cloud.githubusercontent.com/assets/446796/9206955/2664b548-4041-11e5-8162-5aaa719d807e.png)

But if you search FileHelpers in the UI in visual studio 2015 (last version of NuGet installed) you get:

![image](https://cloud.githubusercontent.com/assets/446796/9206986/48955f78-4041-11e5-97b0-0d32c00fb775.png)

Wrong name, description, Download count, displayed, I updated the description from the old package and anyway it shows this way

**Comment by MarcosMeli** [comment]
Another issue with this package is that if I install version 2.9.9 (latest is 3.1)

It said that there is an update available but only gives the Unistall option

![image](https://cloud.githubusercontent.com/assets/446796/9207122/e9de54b6-4041-11e5-9b59-e0ed748c6adb.png)

**Comment by maartenba** [comment]
@johnataylor could this be a V3 API thing or client?

**Comment by MarcosMeli** [comment]
I don't if you reseted something, but now it shows a bit better, at least descriptions, anyway package tittle is different in nuget.org and in visual studio addon

Nuget shows: Deprecated FileHelpers
Visual Studio addon: FileHelpers-Stable   (it never shows the package tittle Deprecated FileHelpers)

![image](https://cloud.githubusercontent.com/assets/446796/9278557/f575d4dc-4287-11e5-8a34-0dfac28df179.png)


![image](https://cloud.githubusercontent.com/assets/446796/9278576/188607da-4288-11e5-848b-49dc59b24a64.png)

Thanks

**Comment by MarcosMeli** [comment]
Maybe if the package has a Tittle the GUI can show it with the package name between ()

Deprecated FileHelpers (FileHelpers-Stable)

If name and tittle are the same or no tittle so show the Package Name

Now the behavior is:

WebPage shows only the tittle in the search
GUI: Shows only the package name

**Comment by maartenba** [comment]
Are you still seeing this issue? @MarcosMeli

**Comment by MarcosMeli** [comment]
Yes @maartenba is still different in 3.4.1

It is an inconsistency between app and web pages for example

https://www.nuget.org/packages/FileHelpers-Stable/
Shows as tittle Deprecated FileHelpers 3.1.2

Also in search in the page if you search for FileHelpers
https://www.nuget.org/packages?q=filehelpers

If shows the title: Deprecated FileHelpers in the search result

But finally in the app it still shows the Package Id FileHelpers-Stable but not the tittle.

Thanks

**Comment by maartenba** [comment]
So it's basically the title showing in the package manager UI that is not what you expect it to be?

/cc @emgarten @yishaigalatzer

**Comment by MarcosMeli** [comment]
Exactly in the web pages the **package.Title** is showing but in the UI the **package.Id**

Thanks

**Comment by skofman1** [comment]
From what I see now the title is shown correctly:
![image](https://cloud.githubusercontent.com/assets/16807822/21615640/3482ee30-d193-11e6-9e91-c1679ea84c77.png)

Please reopen the issue if you think the problem persists.
