### ISSUE TITLE
Put sign up on a separate page from sign in.

### ISSUE THREAD

**Issue by jkodroff** [NuGet/NuGetGallery#2619]
Could you fine folks put the sign in form on a separate page from the sign up form?  It doesn't play nicely with 1Password, which makes it annoying to sign in.

**Comment by hbrock** [comment]
If this is something the community wants. I can separate log-in and sign-up to two pages.

**Comment by 304NotModified** [comment]
+1

**Comment by briandrennan** [comment]
@hbrock, sounds more like a symptom right? Is it possible to just have a page that clients can go through so services that handle authentication management can pass through, as opposed to sign-in/sign-up? I would think that having two pages could be confusing.

**Comment by 304NotModified** [comment]
Well I don't use 1Password, but I find the current page confusing.  Showing input boxes for sign in and sign up on one page is really uncommon.

**Comment by briandrennan** [comment]
I've seen it on multiple sites here recently. Not much of a web guy, but it seems to be a common trend these days to have registration and sign-in on the same page for sites that only require a few fields.

I wouldn't mind having a go at redesigning the pages if the verdict says there should be two.

**Comment by skofman1** [comment]
@jonwchu , something to consider?

**Comment by skofman1** [comment]
We removed 'Sign Up' page as part of the NuGet password deprecation:
![image](https://user-images.githubusercontent.com/16807822/44492459-790ba680-a619-11e8-9d43-3a05b5b6ae02.png)
