### ISSUE TITLE
Server infrastructure should incorporate bulk-rebuild optimizations

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2623]
_From @johnataylor on April 21, 2015 18:39_

We materialize significant quantities of metadata across blob storage and we have jobs to incrementally keep this up to date. We know from experience that significant optimizations can be applied for a bulk rebuild of a metadata set.

This is a tracking issue to formalize these optimizations into reusable jobs we can run on demand if teh occasion arises.

_Copied from original issue: NuGet/Home#468_

**Comment by skofman1** [comment]
We have similar functionality
