### ISSUE TITLE
Relative path in NuGet.Config is automatically changed to absolute path on build

### ISSUE THREAD

**Issue by theo-albers** [NuGet/NuGetGallery#2625]
NuGet 2.8.5 breaks previous behaviour with respect to relative path references in NuGet.Config. Before it was possible to have a relative path in NuGet.config. To proof it worked before, see http://stackoverflow.com/questions/12932906/how-do-you-set-a-relative-path-for-a-file-based-package-source-with-nuget. We utilize this feature to define a workspace with a local package folder to be shared across 10 related solutions. We keep our own packages in that shared folder. 

After the upgrade to NuGet 2.8.5 inside VS2013, but also when using VS2015, something automatically changes the NuGet.config file and changes the relative path to an absolute path. The original NuGet.config file in the .nuget folder of the solution looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>
</configuration>
```
When any developer opens the solution, the file will be automatically changed to:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="Itesso package source" value="C:\dev\src\Common\.nuget\..\..\build-output\packagesource" />
  </packageSources>
</configuration>
```
Via the pending changes window the NuGet.config file gets checked in by mistake, breaking the environment for other developers. This behavior also interferes with our TFS2012 build server setup, which no longer is able to find the packages for restore.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1200
