### ISSUE TITLE
Investigate monitoring consolidation - we have dashboard, Pingdom, AppInsights, status page…

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2627]
Investigate monitoring consolidation - we have dashboard, Pingdom, AppInsights, status page…

Perhaps consolidate in AppInsights?

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #199](https://github.com/NuGet/Engineering/issues/199) via [**ZenHub**](https://www.zenhub.com/)
