### ISSUE TITLE
NuGet.Server for V3

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2632]

**Comment by allenmoatallen** [comment]
@maartenba Has work started on NuGet.Server v3? I would like to be able to get my local .NET Core RC2 libraries off my machine.

**Comment by maartenba** [comment]
Not yet. You can use latest NuGet.Server and update NuGet.Core to the latest version. This should support new target frameworks

**Comment by allenmoatallen** [comment]
I was trying to figure out how the project was setup to create a local `nupkg` to reference from my project but not quite sure how the `build.cmd` works.

**Comment by manu-silicon** [comment]
Would it be possible to have an update on this front?

**Comment by skofman1** [comment]
We are not planning to add v3 support to NuGet.Server in the near future. The team is working on other issues in our backlog.

**Comment by manu-silicon** [comment]
Meaning that if we want to host a v3 API, we have to use the NuGet.Gallery for the time being?

**Comment by skofman1** [comment]
The Gallery does not support V3 protocol either.
There was a discussion about this here: https://github.com/NuGet/NuGetGallery/issues/2844

@yishaigalatzer said: Note that the V3 protocol is not required by any client and is purely optional.
Although it does provide some neat performance improvements, we are not able to prioritize this work high enough compared to other hot issues on the list.

**Comment by manu-silicon** [comment]
Naive question, but how is the new v3 feed implemented on nuget.org?

**Comment by yishaigalatzer** [comment]
It's done two ways
1. We have a set of jobs that write pre computed blobs
2. The search service can respond to v3 requests.
3. Lots of various monitoring tools to make sure there are no hiccups. That part is partly based on internal and 3rd party tools.
4. A deployment pipeline to get everything setup/updated/tested.

Both of the first items are available on github, but take a much more significant setup to deploy than the raw gallery.

If you'd like we can point you to the code, but our deployment and tools are not OSS and not really ready to be shared.

Sent from Nine<http://www.9folders.com/>
________________________________
