### ISSUE TITLE
Package validation - inventory of strange package identifiers

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2634]
@xavierdecoster mentioned a lot of strange package id's. See what is tolerable and what not, adjust package validation based on this inventory.

**Comment by maartenba** [comment]
Package ID and Package Version (and more specific: prerelease tag) should be legal URL parts.

**Comment by maartenba** [comment]
Validation currently comes from `NuGet.Core`'s `PackageIdValidator` and adheres to the following regex:

    private static readonly Regex _idRegex = new Regex("^\\w+([_.-]\\w+)*$", RegexOptions.IgnoreCase | RegexOptions.ExplicitCapture);

**Comment by xavierdecoster** [comment]
Observations I made when working on cdn stats importer job (these complicated cdn raw URL parsing into package id and version segments):
* package id in the form of a version string (e.g. https://www.nuget.org/packages/5.0.0.0/, http://www.nuget.org/packages/1/, https://www.nuget.org/packages/1.0.10/)
* package id can have non-ASCII characters (e.g. https://www.nuget.org/packages/%E6%96%B0%E5%8C%85/)
* package id containing a substring in the form of version string (e.g. https://www.nuget.org/packages/1.0YprimeID/)

**Comment by xavierdecoster** [comment]
Closing this one and referencing #167.
