### ISSUE TITLE
Project "Default" is not found

### ISSUE THREAD

**Issue by swiftie821** [NuGet/NuGetGallery#2635]
NuGet is not letting me install packages or change the current project in command line, keeps coming up with (on Get-Package -ListAvailable):

PM> Get-Package -ListAvailable
Get-Package : Project 'Default' is not found.
At line:1 char:12
+ Get-Package <<<<  -ListAvailable
    + CategoryInfo          : ObjectNotFound: (Default:String) [Get-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetPackageCommand

Using VS2015RC2 NuGet version: 4.6.00081

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1215
