### ISSUE TITLE
Add advanced search filters

### ISSUE THREAD

**Issue by VPashkov** [NuGet/NuGetGallery#2636]
When user searching for a package at nuget.org the results sorted by relevance. 
It would be nice to have an option to sort result by popularity and upload date.
For example chocolatey.org have that option. There is a "Sort By" dropdown on search results page with Relevance, Popularity, A-Z and Recent options.

**Comment by hbrock** [comment]
I would like to work on this issue if no one else is working in it.

**Comment by maartenba** [comment]
@hbrock Word of warning: it's not a trivial fix. It is for database-related gallery, but for NuGet.org it's not. We are calling into the search service - more specifically https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Indexing/GalleryServiceImpl.cs, which currently does not support sorting.

We are working on a transition to the V3 search service (the one VS2015 also uses - https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Indexing/ServiceImpl.cs), which would be a great prerequisite to have before venturing on supporting sorts in the gallery.

Both search service implementations currently do not have sorting built in. The Lucene framework does support sorting when running a query, so the best starting point would probably be in https://github.com/NuGet/NuGet.Services.Metadata.

**Comment by hbrock** [comment]
Maybe I should start with a smaller task first

**Comment by maartenba** [comment]
That would be most welcome!

**Comment by skofman1** [comment]
@SQL-MisterMagoo wrote in https://github.com/NuGet/NuGetGallery/issues/4124:

> Possible filters/sorts would be :
Dependencies
Last updated
Author
License
Download total
Downloads in last 90 days
Prerelease flag
Tags
Basically any information you have decided would be useful to show me on the package view would potentially be useful in a search

**Comment by anangaur** [comment]
Related developercommunity feature suggestion: https://developercommunity.visualstudio.com/content/idea/583267/nuget-browser-have-sort-by-download-count.html

**Comment by Jericho** [comment]
+1 for this feature. 

In my scenario I use the API to find packages with a name containing a certain keyword and a simple alphabetical sort would be perfect because it’s predictable and consistent. I don’t care about “relevance” because it’s not predictable and a package might change position in a subsequent search. Again, in my scenario predictability and consistency are more important than “relevance”.

**Comment by snickler** [comment]
I would love a sorting feature. I personally would love to see options for version sorting simply on the results, regardless of the Id. For instance, if I want to sort by latest version - I want to see all packages returned sorted by the latest version of that package.

Something - v3.0.1
Something.Extensions v3.0.0
Something.Interfaces v3.0.0
Blah.Unrelated v2.5

**Comment by joelverhagen** [comment]
Mentioned by @donnie-msft on https://github.com/NuGet/NuGetGallery/issues/7992:

> ### Is your feature request related to a problem? Please describe.
> NuGet Client request to allow sorting on the Browse tab will require Server changes as well.
> 
> ### Describe the solution you'd like
> What changes would be necessary on Server to handle such a feature? Perhaps it should be limited to a single source?
> 
> ### Additional context
> https://github.com/nuget/home/issues/2585

Mentioned by @loic-sharma  on https://github.com/NuGet/NuGetGallery/issues/7992#issuecomment-628225675:

> > What changes would be necessary on Server to handle such a feature?
> 
> Cost-wise, it seems this feature would be similar to the package type filter feature. We would need to update:
> 
> 1. The protocol to declare whether the server supports sort ordering
> 1. The search API to request different sort orders
> 1. The search index to support ordering on the desired fields
> 
> We should figure out the sortable fields we'd like as some are easier than others. For example, it was suggested [here](https://github.com/NuGet/Home/issues/2585#issuecomment-303529181) that we support sorting by number of dependents. This information isn't in search today and would need to be added. In case you're interested, you can find the search index definition [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/f253504776376eedf77c108c910154263f9f20e1/src/NuGet.Services.AzureSearch/Models/SearchDocument.cs#L20). I would suggest we start with easy things like sort by "relevance", "downloads", "newest package", and "latest updated".
> 
> > Perhaps it should be limited to a single source?
> 
> Could you explain this a little bit more?
> 
> How would the client handle two sources, one which supports ordering and another that does not?

Mentioned by @joelverhagen on https://github.com/NuGet/NuGetGallery/issues/7992#issuecomment-630374220

> This has been a long time ask from customers. The pre-existing issue is here: https://github.com/NuGet/NuGetGallery/issues/2636. It reads as specific to nuget.org but the implementation would have to go as deep as the search service and therefore be low hanging fruit for V3 API addition.
> 
> Let's merge this issue into the existing one and include the information mentioned here. It's clearer for users if there's a single issue to upvote and provide comments on. It's really one feature, which multiple stages/entry points.
> 
> When we implement it for nuget.org, we will consider both how it works on the website as well as how it is shaped in the V3 API (which PM UI would call).
> 
> Regarding the sorting, if you can detect that all sources support sorting (perhaps a new search `@type` in the service index), you can merge the results on client side, assuming the sort key is in the result set.

**Comment by michael-hawker** [comment]
+1 for having author/owner as additional search criterion. License could also be useful for folks.

**Comment by skofman1** [comment]
Closing since we release the feature. If there are ideas for additional improvements, please open a new issue.
