### ISSUE TITLE
VS Extension: slow packages list updates\listing

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2637]
Moved from: https://github.com/NuGet/Home/issues/1211

By: @centur

VS Extension is very chatty on the network and doesn't perform proper response caching, which results in very low overall performance when listing all packages or updates:

* For each package in the solution it'll lookup for index.json file which is a separate network call.
* The data that downloaded with each call to index.json doesn't seems to be cached on a client side, thus results in consequent calls to get exactly the same data.
* Each action like Upgrade single package or install existing package into another project, flushes entire state and triggers all packages to be updated again - thus same call to index.json
* Network responses (index.json) are not gzipped which causes even more traffic, slower experience

Overall, upgrading packages in a solution with 70 packages ( not the biggest one :) ever) can result in 4Mb of internet traffic per each package upgrade
Here is [a link to fiddler capture](https://dl.dropboxusercontent.com/u/4735273/Chatty%20Nuget%20v3.saz)  with calls that were triggered after single package upgrade.

Potential fixes: 
1. Enable gzip compression on server-side. As you're using Azure block blob - it might be needed to upload compressed BlockBlobs and set Content-Encoding metadata manually there
2. Enable caching header on the server side and respect it on a client side - server side seems easy as it's just a metadata on a blob, client probably needs to be updated.

Even 5-10 minutes cache can improve overall experience - I'm not sure that real-time information about package versions is needed. But it'll avoid long refreshes and excessive traffic when managing nuget packages in Visual Studio.

Test environment:
Nuget Extension ver: 3.1.60724.766
Microsoft Visual Studio Community 2015 Version 14.0.23107.0 D14REL
Microsoft .NET Framework Version 4.6.00079

**Comment by yishaigalatzer** [comment]
Thanks for this report, we are in the process of adjusting the caching headers. We started with some over aggressive caching, so we backed out, and we slowly plan to bring more caching in.

**Comment by valeriob** [comment]
Any update ?
The network traffic for a solution with 80 packages (common in web applications) is insane, both in size and in the number of server roundtrips... doing a "search for update available" project with 82 packages: 
150 server requests, a lot of them > than 100k  (11 MB in total ! O_o)
the time taken makes it impossible to use, since on every action you have to wait that procedure again, and you can't do batch updates from the ui..
I'm very sad about that because it smells a lot of N+1 problem :(


Request Count:   154
Unique Hosts:    5
Bytes Sent:      31.320		(headers:31.320; body:0)
Bytes Received:  11.187.272		(headers:62.489; body:11.124.783)

ACTUAL PERFORMANCE
--------------
Requests started at:		21:10:54.988
Responses completed at:	21:12:20.710
Sequence (clock) duration:	00:01:25.722
Aggregate Session duration:	00:02:42.596
DNS Lookup time:		215ms
TCP/IP Connect duration:	1.364ms
HTTPS Handshake duration:	1.938ms

RESPONSE CODES
--------------
HTTP/200: 	153
HTTP/302: 	1

RESPONSE BYTES (by Content-Type)
--------------
application/json: 11.118.041
       ~headers~: 62.489
       image/png: 6.558
       text/html: 184

**Comment by yishaigalatzer** [comment]
We plan on improving this in 3.3 release, I can't commit that it is going to fix all the problems, but we are going to make significant improvements.

1. Cache update available, so search doesn't go to the server, just filters the local list
2. Batch update multiple packages (multi select, update to the latest)
3. Some network optimization (less network calls, better caching of results for the update itself).

I do expect more improvements to the protocol, post 3.3

**Comment by valeriob** [comment]
I look forward to it ! :smile:  
May i ask what brought to design an api so chatty and heavy ? I mean, downloading 11Mb with 150 requests just for asking to the server "i've got those packakes, what can you do for me?"

**Comment by yishaigalatzer** [comment]
I have a story but I don't have a good answer, so I'd keep quite

**Comment by philipbjorge** [comment]
@yishaigalatzer -- Is there an ETA on the 3.3 release?

**Comment by yishaigalatzer** [comment]
3.3 was released in November

**Comment by yyjdelete** [comment]
@yishaigalatzer 
Still get `Cache-Control:no-store` with `PackageDisplayMetadataUriTemplate`, which will be load every time when click an different package in VS2015 Update2 RC or check for update.

[nuget v3](https://api.nuget.org/v3/registration1/system.linq/index.json)->`Cache-Control:no-store`
[dev.nugettest.org v3](https://az635243.vo.msecnd.net/v3/registration1/system.linq/index.json)->`Cache-Control:no-store`

---
While myget use an different Cache-Control.
[myget](https://www.myget.org/F/aspnetvnext/api/v3/registration1/system.linq/index.json)->`Cache-Control:private, max-age=60, s-maxage=0`

**Comment by yishaigalatzer** [comment]
We still have nostore by design at this point, because we are worried about sharded responses. A myget user is a lot closer to his feeds.

However you will see in 3.4 major perf improvements in the chattiness and local caching, we are not relying on caching headers to make any of these determinations

**Comment by philipbjorge** [comment]
Is there an ETA on 3.4?

**Comment by yishaigalatzer** [comment]
3.4 RC is out, 3.4 RTM will soon follow when Visual Studio update II is released

**Comment by philipbjorge** [comment]
Would I expect chattiness to be reduced when accessing the "Updates" tab of Nuget package manager?

**Comment by yishaigalatzer** [comment]
Yes! The new design works something like that:

1. We are still chatty in the background to find out what packages need updates (no much choice, but we do download smaller payloads to figure it out)
2. Once the number of updates have been figured out, we remember the packages that needs update, so now we know what packages to show (trivial I know :) )
3. We show the list of packages and metadata that was already cached, and we go out to get the missing metadata, so the UI shows up immediately, but some data might be missing
3.a We first go to local folders, like the packages folder or the global packages folder, and refresh the data as it becomes available
3.b We then go online, for the rest of the missing data and refresh it (e.g. download counts)

Overall switching between the tabs in 3.4 RTM is instantaneous. See this short video

 [WebApplication26 - Microsoft Visual Studio 3_9_2016 12_02_46 PM (2).mp4](https://files.zenhub.io/56e0822eaccbaf5368c5dbea)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by yyjdelete** [comment]
Seems it doesn't works for me as except(the video), it it be done after 3.4 RC?

After the number of updates is shown, metadata of packages is still loaded everytime when switch between packages. And when switch between `Installed`/`Updates`, the number of updates will disappeared and be checked again which will take an long time.

And there is only one `%appdata%\..\Local\NuGet\v3-cache\1ca707a4d90792ce8e42453d4e350886a0fdaa4d$ps_api.nuget.org_v3_index.json\service_index.dat` in `v3-cache`

**Comment by yishaigalatzer** [comment]
Yes, this is today's build which is obviously after rc.

**Comment by johncrim** [comment]
Any update on this issue? When will it be coming out?

(Thanks)

**Comment by maartenba** [comment]
You can try the latest VSIX/.exe from www.nuget.org/downloads

**Comment by maartenba** [comment]
Can this one be closed?

**Comment by johncrim** [comment]
The current version of NuGet is 3.4.4. Is this issue fixed there? Perf does seem improved, but I don't have real data to back that statement.

**Comment by yishaigalatzer** [comment]
Not the final word on perf, but yes this issue was definitely addressed on the server by gzipping and changing the page size. The client is also better on caching data (although not perfect).

We are planning on more investment in the protocol in future releases. So less round trips are required.

Maarten you can close this issue. We will file specific improvements to protocol when we have further designs in flight

**Comment by ronnyek** [comment]
Not to beat a dead horse, but we've got a pretty massive solution with one package being included in like 10 of those projects. I'm pushing for reducing the footprint of the solution, but in the meantime a nuget package upgrade for one specific package has been known to take the better part of an hour. 

We haven't changed anything on the server to my knowledge, but 3.4.4 client didn't seem to provide appreciable gains. It doesn't appear that we actually check in the packages themselves, but there is a packages folder and repositories.config seems to be checked in and not.

If its fine to be checking in the folder itself and the repositories.config, is there some sort of debug mode I can turn on to get a better idea of where the time is being spent? Ultimately this is probably costing us a GOOD amount.

**Comment by yishaigalatzer** [comment]
Ronney we are constantly improving individual scenarios when we can put our hands on a repro.

Feel free to share a repro with us on feedback@nuget.org and we can profile and see if we can come up with improvements.

You can try 3.5beta2 as it has some more perf improvements and we are doing more towards 3.5rtm

A few other things that may speed you up (things we know may be slow and we are working on improving)

1. Avoid checking in the packages folder
2. Try removing resharper if you use it. We know of some scenarios it slows down significantly, we hope to have a common fix between us and them by the next release.
3. Does your package include many content files? That is another area where things take longer to add/remove and we don't yet have a good way around it (although we got some ideas)

**Comment by aschekatihin** [comment]
I have somewhat similar issue but a bit different - when I open Manage NuGet Packages for Solution and start scrolling to the end of the list without waiting for Nuget to download its jsons - gallery fails to  recognize packages at all: 
http://prntscr.com/c3kgci

Then when unrecognized package clicked - extensions fails to refresh right area rendering it unuseful until reopened:
Recognized clicked: http://prntscr.com/c3kjb0
Unrecognized clicked: http://prntscr.com/c3kl6b

Have issue on 3.4.4 and 3.5.0 beta 2,   80 packages in the solution.

Ps: cache control still no-store:

GET /v3/registration1-gz/newtonsoft.json/index.json HTTP/1.1

HTTP/1.1 200 OK
Cache-Control: no-store

**Comment by yishaigalatzer** [comment]
@aschekatihin thanks for a detailed report, you did it on a closed issue, so I would appreciate if you can open a fresh one and we can triage it.

BTW the registraiton blobs are no-store by design. They rev whenever a package is published and hence we can't safely cache them even for a short time. On the surface it seems like we should be able to cache, but caching a package will break a package install that depends on the new version in the following scenario:

Package graph:
A 1.0 ->B 1.0

Steps:
Install B 1.0

A & B Updates to 1.1

Install A 1.1
