### ISSUE TITLE
Unable to download Microsoft.Net.Http

### ISSUE THREAD

**Issue by boomie123** [NuGet/NuGetGallery#2639]
On the web page https://www.nuget.org/packages/Microsoft.Net.Http/2.2.28
I click Download link: https://www.nuget.org/api/v2/package/Microsoft.Net.Http/2.2.28
Instead of package I get index.json file.

**Comment by RogerKratz** [comment]
There seems to be a lot of packages having the same issue. The same goes for eg
https://www.nuget.org/packages/MbCache/2.7.0

**Comment by maartenba** [comment]
This has been resolved. We recommend clearing NuGet cache (%LOCALAPPDATA%\NuGet\Cache).
