### ISSUE TITLE
Kendo UI package download returns 404

### ISSUE THREAD

**Issue by bitzblitz** [NuGet/NuGetGallery#2640]
I see a listing for the Telerik Kendo MVC package, but trying to get it produces a 404 error.

**Comment by maartenba** [comment]
Can you see which URL it tries to access?

**Comment by olivier-spinelli** [comment]
nuget.org/v3 api has been down recently (about half an hour) ago. Could you retry and update this issue accordingly?

**Comment by bitzblitz** [comment]
Looks like
https://www.nuget.org/packages/Telerik.KendoUI/
still gives a 404. The 0 downloads might indicate that it never worked.

**Comment by maartenba** [comment]
If I recall correctly, this package was removed from the feed. @johnataylor @bhuvak can you check why it's still in the index?

**Comment by olivier-spinelli** [comment]
Ok... So strange things seems to happen... 
Now that the v3 api is up (at least for me), I 'm in front of a rather strange behavior:
I uploaded https://www.nuget.org/packages/SimpleGitVersion.Core/ (version 0.1.1) BUT the VS2015 nuget browser displays the 0.1.0 version I uploafed earlier. And a Install-Package SimpleGitVersion.Core results in 0.1.0 installation.

**Comment by maartenba** [comment]
@olivier-spinelli that's related to #1161

**Comment by olivier-spinelli** [comment]
Thanks a lot got your quick response! Are there any workaround? What can I do ?

**Comment by olivier-spinelli** [comment]
Since It is far from clear to me to understand how I can fix this issue at my level (nothing is related to json in my packages), my current workaround is to publish the package on an internal feed... but this does not allow everyone to use these terrific packages ;-).

**Comment by maartenba** [comment]
@olivier-spinelli Just checking if your package is visible now as expected?

**Comment by bitzblitz** [comment]
Yup. KendoUICore is now and installable package. Thanks.

**Comment by stefanrahnev** [comment]
I'm on the Kendo UI team, being Product Manager of the product.

@maartenba, can the following url (https://www.nuget.org/packages/Telerik.KendoUI/) can be stopped from being indexed by Google any more, as it refers to a non-existing NuGet package?

If that's not possible presently, at least can we make the url to redirect to the following:
https://www.nuget.org/packages/KendoUICore/?

Thanks,

**Comment by maartenba** [comment]
Both yes, but not "right now". We are working on a feature to handle this but for now can't force this.
