### ISSUE TITLE
Escaped filename characters causing package installation failures

### ISSUE THREAD

**Issue by ProductionReady** [NuGet/NuGetGallery#2641]
I am trying to install either package https://www.nuget.org/packages/Harvest.Chosen/ or https://www.nuget.org/packages/chosen/ however I am receiving errors with Visual Studio 2015. Both packages contain a file "chosen-sprite@2x.png" but when installing, the package installation errors out and says it cannot file "c:\....\.nuget\packages\chosen\1.2.0\content\chosen-sprite%402x.png". I can manually create a file in the package directory with the name shown in the error and the package moves on, however this is not a valid strategy for deploying these packages with mine. Can you take a look?

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1261
