### ISSUE TITLE
nuget package install fails on VS2015E

### ISSUE THREAD

**Issue by mprevot** [NuGet/NuGetGallery#2642]
Attempting to resolve dependencies for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Resolved actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Install failed. Rolling back...
Package 'Yeppp.CLR.Bundle 1.0.1-prerelease' does not exist in project 'VideoProcessor'
Package 'Yeppp.CLR.Bundle 1.0.1-prerelease' does not exist in folder 'C:\Users\soleil\Documents\Visual Studio 2015\Projects\shutter_modeler\packages'
Install-Package : Could not install package 'Yeppp.CLR.Bundle 1.0.1-prerelease'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package Yeppp.CLR.Bundle -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1298
