### ISSUE TITLE
Catalog Index and Index Pages should create snapshots

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2643]
When blobs are changed snapshots should be created. Snapshots are a Blob Storage feature which created a timestamped copy of the blob.

We would also need a job to clean up snapshots older than a time period. The clean-up snapshot job should run after the current container copy job has run.

Combining the snapshots with our existing backup copy script should give us a much improved backup story.

**Comment by skofman1** [comment]
We went with daily container replication without snapshots.
