### ISSUE TITLE
Profile & Email notifications improvements

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#265]
From ET session #243 :

2.
Went to edit profile. Changed email address. Clicked "Save". Received an email to confirm new email address. Email address doesn't provide any information about the actual emails being changed. We should fix this later.

 3.
Without confirming the email change, I went back to edit profile. Blue info message shows that there's a pending email address change. Email field shows old email address. There's no way to cancel the change.

 4.
Same as #3. Went back to Edit Profile with a pending email change. Did not make any changes. Clicked "Save". A new email change confirmation email was sent. If no changes are made, we shouldn't resend the email. We should probably disable the Save button until a change is made. Thoughts?

7.Went to edit profile and unchecked "Receive Email Notifications". Clicked "Save". Received an email change notification email. That should not happen..

**Comment by robertmuehsig** [comment]
Maybe all mentioned issue here are already solved - with the current version it is possible to cancel the email address change and there are a couple of good hints what is going on:

![image](https://cloud.githubusercontent.com/assets/756703/21277852/9cd80e0c-c3d8-11e6-996b-e4b58e1de962.png)

Close this issue or is there anything left to do?
