### ISSUE TITLE
the package does not contain any assembly references or content files that are compatible with that framework

### ISSUE THREAD

**Issue by NVentimiglia** [NuGet/NuGetGallery#2654]
I am trying to install a nuget package and failing. Both the nuget package and the importing project are of the same type (PCL target 259). When I try to import the project, I get this error.

Could not install package 'WebSocket.Portable.Core 1.2.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

After emailing myself the issue, I tried to republishing the nuget package using the manager tool (vs 1.2.3) and that did not work. Here is my nuget package explorer.

![nugetmad](https://cloud.githubusercontent.com/assets/125889/9646406/22462534-5188-11e5-8611-d410065d700a.png)

Using VS 2015 and NuGet 3.1.6

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1325

**Comment by NVentimiglia** [comment]
The core problem seems to be that VisualStudio likes to add Silverlight support to PCL's automatically.
Is there any way to remove Silverlight support from the project manually ?

![nooneusessilverlight](https://cloud.githubusercontent.com/assets/125889/10256368/a8a21568-6905-11e5-86e0-1e2a0d55c46a.png)
