### ISSUE TITLE
Packages Downloaded Per Month shouldn't show current month

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2658]
Referring to:

http://nuget-preprod-0-v2gallery.cloudapp.net/stats

If "Packages Downloaded Per Month" shows the current month the graph takes a sudden sharp dip down for the first few days of the month. The trick is to delay the reporting of data until that time period is complete (here that period being the month.)

**Comment by maartenba** [comment]
@xavierdecoster should be a simple fix, but that does mean the stats are always on month old for that report (with no "month in progress")

**Comment by xavierdecoster** [comment]
Current production site (https://nuget.org/stats) does show the current month in progress (stats were frozen in April). 

It's indeed a simple fix, but as we now update stats way more often, people should also notice progress during the month (the blobs get updated multiple times a day).

So, do we show current month or not? :)

**Comment by csharpfritz** [comment]
If we drop the current month from the graph, people may wonder if we have calculated month-to-date statistics since the previous month.  What do we think of dropping the current month from the graph and adding a line item for "Packages Downloaded: Month to Date"?

**Comment by xavierdecoster** [comment]
What is the intended communication of this chart? Is there value in knowing the total downloads of a specific calendar month? February and August have different number of days, so what's the value in comparing their totals? Is there a reason the time intervals must be coupled to the Gregorian calendar? :) If monthly comparison is important, it may be more correct to compare average daily downloads between months.

If the intent is to show download trends and update the numbers as new data comes in, then we have a sliding time window (with or without fixed start date for the time axis). A column bar chart may not be the best fit. See also index lag trend line on the new status page. One could also go all the way and allow zooming in, selecting a time range, etc: http://bl.ocks.org/mbostock/1667367

If we want to show totals, it may make more sense to show totals for the last day, the last week, the last month, and optionally compare them with their previous period.

**Comment by maartenba** [comment]
* Updated gallery to read "Packages Downloaded - Month to Date" (not deployed yet)
* Updated job to generate stats for month to date (deployed)
