### ISSUE TITLE
Per Package Statistics do not agree with figure on main Statistics page

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2659]
For example, 

http://nuget-preprod-0-v2gallery.cloudapp.net/stats
shows newtonsoft.json has 1,357,032

http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/Newtonsoft.Json
shows newtonsoft.json has 1,356,603

If this is because of a delta that has occurred in the time taken to generate the reports one trick is to generate both data sets for a fix time in the past - for example up to midnight yesterday. The both numbers will naturally align without further work. Otherwise this can look like a bug.

Such a behavior is in contradiction to a desire to provide real-time results. However, it is better to provide self-consistent results and then present real-time data explicitly as such and somewhat independently of the reports. At the same time the reports should probably be clearer as to exactly what they represent (i.e. they could include the exact date range as a sub-title.)

**Comment by maartenba** [comment]
@xavierdecoster could this be the user agent family filtering?

**Comment by xavierdecoster** [comment]
@maartenba likely what @johnataylor says: Blob generation time difference

**Comment by xavierdecoster** [comment]
Updating for the sake of having all context on this issue: 
CDN does not guarantee that raw logs are delivered same day, nor does it guarantee that it is delivered ordered by timestamp of download events. This needs to be taken into account: as new data still comes in, a newly parsed log file may *insert* facts within the selected time range at any point in time. Totals and details stats need to use the same cursor on the technical timestamp of the facts, in addition to the filter on the date dimension (last six weeks range).

The main issue is that one job generating totals can move the cursor whilst the other job generating the details stats is reading the cursor position. These jobs' order of execution is not synced in anyway, and totals job may finish before details job has finished, again resulting in inconsistent results. 

I think the only way to guarantee 100% *stable* numbers is to merge both jobs into one, and forcing them to use the same cursor position on the technical Timestamp.

**Comment by xavierdecoster** [comment]
In addition: the gallery fetches blobs to show the stats.
There may be a rather large time difference between uploading the totals blob and the individual package details blobs, temporary resulting in inconsistent numbers. 
The cursor position may be a useful flag to determine when to refresh the stats shown by the gallery (this flag is updated after all blobs have been uploaded). However, I don't feel like this is a gallery responsibility. Perhaps this should be put behind a service that shields clients, including the gallery, from such logic?

**Comment by xavierdecoster** [comment]
Fixed.
