### ISSUE TITLE
Per Package statistics some Client version appear blank. 

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2660]
For example:

http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/Newtonsoft.Json?groupby=ClientVersion

the top client type appears blank. Shouldn't it at least say "unknown" if we don't know what it is?

**Comment by johnataylor** [comment]
In some other cases the unknown client version does actually appear as (unknown) for example:

http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/dotnetrdf?groupby=ClientName

**Comment by maartenba** [comment]
@xavierdecoster Do we have a dimension named "" ?

**Comment by xavierdecoster** [comment]
@maartenba no, there's no client dimension with clientname ''

This should say 'unknown' or 'other' or something.

**Comment by maartenba** [comment]
Deployed a fix - version was set to blank in these cases, changed it to read "(unknown)" now.
