### ISSUE TITLE
Dependent packages not being including

### ISSUE THREAD

**Issue by kabua** [NuGet/NuGetGallery#2661]
First, the idea of Nuget is great and we have been using it a lot over the past several months. However, we've had several issues with dependent packages not being picked up as a dependency. Most of the issues appears to be around the case where we include a dependent package for some external purpose or like in the current case, Assem1 is accessing internals of AssemBase. 

It appears that Nuget is analysising our project and doesn't realize that Assem1 is accessing AssemBase's internal classes. Thus when we go to deploy Assem1 it fails because AssemBase is missing.

We've tried the using -NoPackageAnalysis but this flag didn't work.

Please add a switch or something to be able to disable this functionally. Thank you.

P.S. We are currently on version: 2.8.60318.667

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1375
