### ISSUE TITLE
Index.json has an incorrect content type

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#2663]
https://api.nuget.org/v3/index.json when opened in the browser is downloaded instead of opened due to the file having a content type of binary/octet-stream.

![image](https://cloud.githubusercontent.com/assets/6381138/9695936/39e70f92-531c-11e5-830f-a29705fee784.png)

**Comment by xavierdecoster** [comment]
TeamCity sets the content type to json-ld. Did someone deploy manually? Redeploying from TC should fix it.

**Comment by maartenba** [comment]
Did an update to `application/ld+json`.

**Comment by emgarten** [comment]
This has regressed. Opening http://api.nuget.org/v3/index.json in firefox brings up the download dialog. The rest of the files do not.

**Comment by scottbommarito** [comment]
As Firefox user, can confirm it has regressed.

**Comment by ryuyu** [comment]
This appears to be related to the way Firefox handles various content types.
Opening https://api.nuget.org/v3/catalog0/index.json in Firefox works as expected and has a returned Content-Type of application/json
https://api.nuget.org/v3/index.json returns a Content-Type of application/ld+json (as indicated above by @maartenba ).

Is this a recent thing you are seeing? Did it work properly previous after @maartenba 's fix?

**Comment by emgarten** [comment]
I recall it working at some point. The content type should be consistent across all of the pages. application/ld+json is technically the most correct, but I believe it was decided to use application/json back when v3 was first created for simplicity.

**Comment by xavierdecoster** [comment]
This issue is talking about the service index at https://api.nuget.org/v3/index.json. It is that blob that has regressed? Wondering if someone forgot about this https://github.com/NuGet/NuGetGallery/issues/2663#issuecomment-137915439 :)

**Comment by maartenba** [comment]
Redeploy from TC, be done with it.

**Comment by ryuyu** [comment]
I think the issue here is actually that Firefox regressed. I checked the response when we hit the index.json, and it returns application/ld+json, as @maartenba mentions above. It's just that Firefox doesn't know what to do with that content type. If this worked before, I would actually say this is probalby a Firefox regression. In any case, content type of application/json seems to work correctly, so we can maybe redeploy with that content type to work around it?

**Comment by maartenba** [comment]
@emgarten is this a blocker? Looks like Firefox... https://github.com/NuGet/NuGetGallery/issues/2663#issuecomment-244433040

**Comment by emgarten** [comment]
IE and Edge do not handle it either, is there any reason to use application/ld+json or to make index.json a different content type from the rest?

**Comment by maartenba** [comment]
Historical I think. Anyone else opinions or are we good with application/json here?
