### ISSUE TITLE
Package Statistics not updating since ages

### ISSUE THREAD

**Issue by EmptyKeys** [NuGet/NuGetGallery#2665]
Package statistics are not updating at all for my packages. Is it turned on?

https://www.nuget.org/stats/packages/EmptyKeysUI?groupby=Version
https://www.nuget.org/stats/packages/EmptyKeysUI_MonoGame?groupby=Version

**Comment by maartenba** [comment]
It will be again soon - check http://nuget-preprod-0-v2gallery.cloudapp.net/ for a preview.
