### ISSUE TITLE
Dependency package statistics

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#2666]
Hi

I had a look at the test server's package stats and I noticed that they no longer differentiate install vs install-dependency, etc.

http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/Newtonsoft.Json?groupby=Operation

vs

https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Operation

**Comment by maartenba** [comment]
Adding @xavierdecoster

**Comment by xavierdecoster** [comment]
Thanks for reporting @JamesNK!

Found a bug in the new parser that strips off `-Dependency` from `Install-Dependency` in the custom CDN headers. A fix is on its way but unfortunately requires us to reparse history. Might take a day or two.
