### ISSUE TITLE
Dependent packages not showing in References and project.json in UWP. Is it a new behaviour?

### ISSUE THREAD

**Issue by mathikp** [NuGet/NuGetGallery#2667]
In UWP projects, when we installing a NuGet, the dependency packages of the NuGet is not showing in References node in Solution Explorer and also there is no entry in project.json file. Whether it is an issue or not?

**Comment by emgarten** [comment]
Would you provide some repro steps for this? 

Is the install failing and rolling back?

**Comment by mathikp** [comment]
I have add dependencies properly. List of dependencies are showing correctly in VS2015's NuGet Package Manager. And after installed its successfully restored to the .nuget/packages folder. But the issue is, the dependency NuGet packages are not showing in the References node in Solution Explorer and entry is not adding in project.json file after installed. Its not showing any error in installation log.

**Comment by emgarten** [comment]
Please provide steps that can be used to reproduce this issue.
Example: project type, package installed, steps used to install the package.

**Comment by mathikp** [comment]
1.Created 2 packages with "lib/netcore46" folder named A and B. In A's nuspec file I had added B as a dependency. I have configured the NuGet in Visual Studio 2015. 
2.Created Universal Windows blank app. Opened Tools->NuGet Pakckage Manager->Manage packages for this solution. 
3.Selected my package source and selected package A.
4.B is showed as dependency in the right pane of NuGet Package Manager.
5.Installed A. Its installed successfully. 
6.A is added to project.json and under References node in Solution Explorer. But B is not showing in Solution Explorer and not added in project.json.

But A and B are available in .nuget/packages location. Why?

**Comment by emgarten** [comment]
Dependencies are not added to project.json, only the top level package. In solution explorer you can find B by expanding A.

Btw, it doesn't affect your scenario but netcore46 is not a valid target framework. If you are trying to target UWP use uap10.0.

**Comment by ratishphilip** [comment]
I am facing a similar issue.
I have created a Class Library for Universal Windows App and want to publish it as a NuGet package.

My library has a dependency on Microsoft.Xaml.Behaviors.Uwp.Managed.

I created the spec file for the project using NuGet and mentioned the dependency as follows
&lt;dependencies&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;dependency id="Microsoft.Xaml.Behaviors.Uwp.Managed" version="1.0.3" /&gt;
&lt;/dependencies&gt;

Then I used the nuget pack command to create the .nupkg file.

When I am adding this .nupkg  file to another Universal app (using the Nuget Package manager), it correctly lists its dependency on Microsoft.Xaml.Behaviors.Uwp.Managed.

But when I install the .nupkg, the dependency is not installed along with it which creates a build issue.

How to resolve this issue and make nuget install the dependencies automatically.

I am using Visual Studio 2015 Update 1.

**Comment by davidfowl** [comment]
@ratishphilip The solution explorer only shows top level dependencies in uwp projects. That doesn't have any effect on the build.

**Comment by ratishphilip** [comment]
@davidfowl Thanks for the reply. I found out what the issue was. While creating the nuget package, the default configuration was set to **Release|AnyCPU**. I think *Microsoft.Xaml.Behaviors.Uwp.Managed* does not work with **AnyCPU** configuration. Setting the default configuration to **Release|x64** solved the issue. Now while installing the package, it shows that *Microsoft.Xaml.Behaviors.Uwp.Managed* is also being installed.

![nuget_dep](https://cloud.githubusercontent.com/assets/7021835/11693693/2c0634b8-9e5b-11e5-9294-abb44f3cc618.png)

However, it does not show up in the Project References in the Solution Explorer. It builds successfully though.
![nuget_dep2](https://cloud.githubusercontent.com/assets/7021835/11693744/6cfb83d8-9e5b-11e5-8355-e7c3ca1ce460.png)

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1834

**Comment by dhaneeshkp** [comment]
if added dependencies not showing in in reference  just follow the simple steps 
1)Right Click on solution go to manage NuGet package for solution  and select the installed corresponding package  and select the projects  and uninstall it
2)Same way select the project and reinstall it
it will work

**Comment by maartenba** [comment]
Please work in NuGet/Home#1834
