### ISSUE TITLE
Trying to upload while another upload is incomplete gives a blank page with "The page was not displayed because there was a conflict."

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#267]
1. Tab A go to https://preview.nuget.org/packages/upload
2. Tab B go to https://preview.nuget.org/packages/upload
3. Tab A, upload a package, don't verify/cancel
4. Tab B, Upload a package 

Blank page with text :

"The page was not displayed because there was a conflict."

Low pri but the blank page is not so nice, could just redirect to the first package to finish.

**Comment by robertmuehsig** [comment]
I think this is solved - at least I now receive a clear information, that a upload can be canceled or submitted or that I can upload a new package.

**Comment by scottbommarito** [comment]
Yeah, this is a prehistoric issue from 2011...the UI has changed a loooot since then and now properly handles uploading a different package before you finish an upload.
