### ISSUE TITLE
NuGetDocs Webhooks failing

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/NuGetGallery#2670]
The webhooks in the NuGetDocs repository are failing to publish to the NuGetGallery on a regular basis.

**Comment by maartenba** [comment]
@csharpfritz can you provide me with admin access on that repo? Can't look into it currently.

**Comment by xavierdecoster** [comment]
I've disabled two webhooks that didn't look correct. If I'm right, we can delete them.
Not sure why the other webhook is showing as failed on GitHub, as the azure portal shows deployment got triggered, and succeeded.

**Comment by maartenba** [comment]
Have updated the web hooks and verified they now work. @csharpfritz please keep an eye on it during the next docs updates - I expect it to be good now.

**Comment by maartenba** [comment]
Latest updates have always returned green web hook calls. Closing issue.
