### ISSUE TITLE
TFS2015 Build Agent

### ISSUE THREAD

**Issue by Laserdaniel** [NuGet/NuGetGallery#2673]
New install of TFS 2015 server
New install of VS 2015
Installed build agent for my machine and registered it

Build definition has restore NuGet package checked
![capture](https://cloud.githubusercontent.com/assets/7558052/9833179/fd05dd06-595b-11e5-9918-6d41afe0ccc4.PNG)

In testing the release I get the following error:
Starting task: Build solution $/shanuAngularWordGame/shanuAngularWordGame/shanuAngularWordGame.sln

******************************************************************************
Executing the powershell script: E:\agent\tasks\VSBuild\1.0.11\VSBuild.ps1
E:\agent\agent\worker\tools\NuGet.exe restore "E:\agent\_work\90e3fb71\shanuAngularWordGame\shanuAngularWordGame\shanuAngularWordGame.sln" -NonInteractive

Configuration system failed to initialize

Unexpected exit code 1 returned from tool NuGet.exe

Not understanding what is happening..

**Comment by Laserdaniel** [comment]
Unchecking the Restore NuGet Packages produces a successful build, I would really like to have that option checked.

**Comment by Laserdaniel** [comment]
I have VS2015 installed on my C Drive, but I have the agent on my E drive...

**Comment by Laserdaniel** [comment]
Agent on C Drive: same type of error

1 
2015-09-12T19:33:32.8246308Z Executing the powershell script: C:\agent\tasks\VSBuild\1.0.11\VSBuild.ps1

2 
2015-09-12T19:33:33.4346430Z C:\agent\agent\worker\tools\NuGet.exe restore "C:\agent\_work\90e3fb71\shanuAngularWordGame\shanuAngularWordGame\shanuAngularWordGame.sln" -NonInteractive

3 
2015-09-12T19:33:33.5746458Z ##[error]Configuration system failed to initialize

4 
2015-09-12T19:33:33.5746458Z ##[error]Unexpected exit code 1 returned from tool NuGet.exe

**Comment by Laserdaniel** [comment]
If I copy the packages folder into the Agent working directory and uncheck the Restore NuGet Packages check box, I get a successful build :(

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1382
