### ISSUE TITLE
ApiAuthorizeAttribute, RequiresAccountConfirmationAttribute not covered by unit tests

### ISSUE THREAD

**Issue by TerraVenil** [NuGet/NuGetGallery#2680]
Code refactoring
1. ApiAuthorizeAttribute.cs. Line 18. Should be removed due to already setting up inside AuthenticationManager when call method Challenge.
2. RequiresAccountConfirmationAttribute.cs. Changed exception to use nameof, added readonly to field _inOrderTo.
3. RequireSslAttributeFacts.cs. Removed dead code.
4. Changed GetCurrentUser to virtual due to mocking inside unit tests.

**Comment by maartenba** [comment]
https://github.com/NuGet/NuGetGallery/pull/2681

**Comment by maartenba** [comment]
These were added a while back.
