### ISSUE TITLE
Inconsistency on feed - package versions missing on V3 feed

### ISSUE THREAD

**Issue by petedavis** [NuGet/NuGetGallery#2683]
There is a package version that does not appear in the V3 feed. The issues is outlined in the issue MassTransit/Automatonymous#19

In summary the version appears in the V2 feed, but is missing in the V3 feed.

**Comment by maartenba** [comment]
@johnataylor @bhuvak Can you have a look at this one?

**Comment by maartenba** [comment]
@petedavis Can you let me know if this works correctly now?

**Comment by petedavis** [comment]
Thanks @maartenba it is now working. I was able to explicitly install the 3.0.5-beta version that was causing issues and the new version that has since been released using the v3 package source.
