### ISSUE TITLE
Move validation logic from method ValidateNuGetPackageMetadata

### ISSUE THREAD

**Issue by TerraVenil** [NuGet/NuGetGallery#2689]
Based on TODO inside ValidateNuGetPackageMetadata (PackageService class) we should move validation logic to data annotation attributes. As I understand we need move validation from method ValidateNuGetPackageMetadata to another NuGet.Core project to ManifestMetadata class using data annotation attributes. But as I can see ManifestTest tests ( and some business logic) coupled to Validate method because ManifestMetadata inherited from IValidatableObject not to data annotations. So if we want to save tests structure then we need move validation logic to Validate method. But if we do that than all if else statements migrates just to another place. But if we move all this validation logic using data annotations than we can reduce if else statement BUT brakes all tests inside ManifestTest!!!
Propositions:
1. Move validation logic to Validate method to save tests structure and add similar for a new validation rules.
2. Refactoring ValidateNuGetPackageMetadata using Validator.TryValidateObject
3. Move if else statements from Validate method to data annotation attributes ManifestMetadata class.
P.S. Also I found strange mismatch. 
<code>
if (nugetPackage.Id.Length > 128)
{
       throw new EntityException(Strings.NuGetPackagePropertyTooLong, "Id", "128");
}
</code>
but in NuGet.Core (PackageIdValidator.MaxPackageIdLength equal 100)
<code>
if (Id.Length > PackageIdValidator.MaxPackageIdLength)
            {
                yield return new ValidationResult(String.Format(CultureInfo.CurrentCulture, NuGetResources.Manifest_IdMaxLengthExceeded));
            }
</code>

**Comment by maartenba** [comment]
@yishaigalatzer @emgarten Yishai/Justin, what would be the real limit on package id length?

@TerraVenil looks like a solid approach - please wait for feedback on the length limit though

**Comment by yishaigalatzer** [comment]
I would move validation out of a filter type thing. We plan to make validation a complete step in push v3, and I don't see justification to spend time on it or do any refactoring in this area given that we are going to completely overhaul it.

**Comment by yishaigalatzer** [comment]
When it comes to package id length - it is debatable, the main concern would be max path. Where with the new data structure package id appears twice and so does the version.

So for example:

C:\users\username\.nuget\packages\{id}\versions\{id}.{version}.nupkg

Given that version can normally be 10.1.2-beta10253 (15 chars), didn't go extreme :)

And package id being 50 chars, doesn't leave much of space when the package is exploded.

Though that's not a hard limit perhaps we should limit the combo if the two x2 to 120chars.

I would scan current packages to see if any exceed already the limit.

**Comment by TerraVenil** [comment]
As I understand I can skip this issue due to re-implementation the whole validation process of ManifestMetadata that will be done in v3. Correct?

**Comment by yishaigalatzer** [comment]
I would not say that :) I'm saying we should not spend effort in refactoring here. 

We should probably change the length to 100 (given that nuget.core had that limitation before). It is going to end up being too long anyways :(
