### ISSUE TITLE
Problems with Packages.Config

### ISSUE THREAD

**Issue by kabua** [NuGet/NuGetGallery#2693]
Nuget states: ```"Found packages.config. Using packages listed as dependencies"``` However, the dependencies are missing from the corresponding nupkg file.

We have a framework that consists of 1 solution and it contains 4 projects. All of the projects contains direct and indirect dependencies. E.g. Some dependencies are required by the project and others are required when **using** the framework. To ensure that **everything** is included in the package we are using the -NoPackageAnalysis like so: 

In our build batch file we have following local variable defined
```
set packageArgs=-Properties Configuration=Release -NoPackageAnalysis -IncludeReferencedProjects -MinClientVersion 2.5 -verbosity %verbosityLevel%
```
and being used like so
```
..\..\_Solutions\BuildTools\nuget pack Test1\Test1.csproj -OutputDirectory Test1\bin\Release %packageArgs%
..\..\_Solutions\BuildTools\nuget pack Test2\Test2.csproj -OutputDirectory Test2\bin\Release %packageArgs%
etc...
```
For each project, the output states ```"Found packages.config. Using packages listed as dependencies"```.

However, when we inspect our nupkg files, we find that some packages contains all of our direct and indirect dependencies and other packages do not. If we rebuild, the packages that were built correctly are still correct and the broken packages are still broken but we can't figure out why some build correctly and the others do not.

IOWs, how do we tell nuget to include **all** the packages that are referenced by the project, regardless if they are being used or not? We thought that the -NoPackageAnalysis flag was suppose to do that but that doesn't seem to work in all cases.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1441
