### ISSUE TITLE
The trust relationship between the primary domain and the trusted domain failed.

### ISSUE THREAD

**Issue by solidcloudio** [NuGet/NuGetGallery#2695]
I can open up the NuGet Gallery we are hosting fine, but other users get an exception which is logged as: The trust relationship between the primary domain and the trusted domain failed.

I'm not sure how the security of the Gallery is supposed to work?  Are all users supposed to register?
Does it use AD authentication ?  What would cause this error ?

Full Stack:
Source File: c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\169d220e\fa00eaf3\App_Web_uej03oea.3.cs    Line: 0 

Stack Trace: 

[SystemException: The trust relationship between the primary domain and the trusted domain failed.
]
   System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed) +1085
   System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess) +52
   System.Security.Principal.WindowsPrincipal.IsInRole(String role) +176
   NuGetGallery.ListPackageItemViewModel.IsOwner(IPrincipal user) +109
   ASP._Page_Views_Shared__ListPackage_cshtml.Execute() in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\169d220e\fa00eaf3\App_Web_uej03oea.3.cs:0
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +126
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +125
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +147
   ASP._Page_Views_Shared_ListPackages_cshtml.Execute() in c:\inetpub\wwwroot\NuGetServer\Views\Shared\ListPackages.cshtml:46
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +126
   System.Web.WebPages.StartPage.ExecutePageHierarchy() +143
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +110
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +380
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by maartenba** [comment]
By default AD authentication is not enabled. However this can be a number of errors related to how the website is configured in IIS.

**Comment by solidcloudio** [comment]
I've tried removing, re-adding the app pool user, checked directory permissions..  Any hints ?

**Comment by maartenba** [comment]
It does seem Windows authentication is enabled somehow. Can you search for `<authentication mode="Windows" />` in your config files?

**Comment by solidcloudio** [comment]
Yes, that is present..  My web.config has:


    
    
    
    <add key="Auth.LocalUser.Enabled" value="true" />
    <add key="Auth.ApiKey.Enabled" value="true" />
    <add key="Auth.MicrosoftAccount.Enabled" value="false" />
    <add key="Auth.MicrosoftAccount.ClientId" value="" />
    <add key="Auth.MicrosoftAccount.ClientSecret" value="" />

 
    
    
    
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="PreserveLoginUrl" value="true" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="autoFormsAuthentication" value="false" />
    <add key="enableSimpleMembership" value="false" />


    
    <customErrors mode="Off" />
    <sessionState mode="Off" />

        <identity impersonate="true" />
  </system.web>

I commented out the Auth mode windows, still getting this trust error..  I've tried both a Domain Account that's an admin on the machine and the "NetworkService" account on the AppPool.

**Comment by maartenba** [comment]
Can you set that to `<authentication mode="Forms" />` ?

**Comment by solidcloudio** [comment]
OK, that seems to have worked.  Let me check that others can access the page.

**Comment by solidcloudio** [comment]
When users click Upload package they get:


The resource cannot be found. 
  Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

 Requested URL: /login.aspx

**Comment by maartenba** [comment]
It looks like it's falling back to default ASP.NET settings. Again a few potential causes - https://www.google.com/search?q=mvc+redirecting+to+login.aspx&ie=&oe=

Also try replacing the `<authentication>` element with this:

```
<authentication mode="Forms">
    <forms loginUrl="~/users/account/LogOn" />
</authentication>
```

**Comment by solidcloudio** [comment]
Strange, this stuff wasn't in the source code.  It must have been added to web.config by IIS.
So to recap...
Fresh deploy from source..  Site runs, but get error on Packages page.  I turn off custom errors to reveal "The trust relationship between the primary domain and the trusted domain failed."  At this point no authentication mode element is present.

If I add: <authentication mode="Forms">
    <forms loginUrl="~/users/account/LogOn" />
</authentication>

Seems to work ok now.

**Comment by maartenba** [comment]
Smells like IIS configuration.

**Comment by simorgh1** [comment]
We had the same issue and debugging showed that during showing package detailes for not authenticated users, the extended method IsAdministrator in PrincipalExtensions class tries to check IsInRole for **Admins** group which does not exists in the server as a local group and therefore it throws this Exception. 

Adding the **Admins** Local Group solves the issue. 
Would be nice to get ride of this local group defined in Constants.AdminRoleName or disable the check by configuration or define the group in web.config.

In General IsInRole("NotExistingRole/Group") throws the same Exception, that in fact could be something like role not found!
