### ISSUE TITLE
This package requires version '3.2' of NuGet, which this gallery does not currently support.

### ISSUE THREAD

**Issue by sandersaares** [NuGet/NuGetGallery#2697]
I would like to require the latest (3.2) NuGet client from users of my packages. However, trying to upload a package with minClientVersion="3.2" via the website appears to generate the error message in the title.

I can see 3.0.0.0 hardcoded as the max supported version in ApiController and PackagesController - likely the cause of this?

**Comment by xavierdecoster** [comment]
@sandersaares Thanks for reporting!
