### ISSUE TITLE
Dependency Versioning...

### ISSUE THREAD

**Issue by kabua** [NuGet/NuGetGallery#2699]
We are using Nuget for in-house development, thus we have public packages co-mingled with private packages. We need the ability to specify that we want the **latest version** up to a given breaking change. We have multiple versions of our internal software components that different teams are using. For example, some teams (or components) are using the older 1.* version while other teams have moved on to version 2.*. Both are activity been used and updated accordingly. 

For example: let's say we that Package A which has a dependency on Package B, thus our nuspec would look something like this for PackageA.nuspec:
```
<dependency Id="Package-B" version="[1.0,2.0)" />
```
Let's also say that team 1 is currently using version 1.3.4 for both Package A and Package B, and we just released/published  a new internal version of 1.3.7 of both Package A and Package B (since the are tightly related to each other). 

In the past, when team 1 upgraded Package A, Package B would automatically be upgraded as well. However, with the new version of Nuget this functionally is now missing! See: [Dependencies are no longer unnecessarily updated during package installation] (http://docs.nuget.org/create/versioning).

For the most part we like the new changes, however, there are times when we need the old functionality. Thus how can we add the ability to automatically upgraded to the latest version (while being constrained to a version range) on a per dependency basis?

The documentation states that if the version attribute *is not* specified than that means 'get the latest version'. Which is find to a point; however, we need to constraint the upper bounds. Thus the closest way, according to the documentation, would be to use ```version=(,2.0)``` but that doesn't state to use the latest version within that bounded range.

Suggested ideas:
* ```version="[lv,2.0)"``` where "lv" would mean "Latest version" (not the best idea)
*  Add a new attribute, something like: ```get-latest="true"``` or ```autoUpdate="true"``` 

Thus team 1 could specify
```
<dependency id="Newtonsoft.Json" version="[6.0.8,7.0)" />
<dependency Id="Package-B" version="[1.0,2.0)" autoUpdate="true"  />
```

and team 2 (R&D) could specify
```
<dependency id="Newtonsoft.Json" version="[6.0.8,7.0)"  autoUpdate="true" />
<dependency Id="Package-B" version="[2.0,3.0) autoUpdate="true" />
```

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1463
