### ISSUE TITLE
Ssl config of nuget.org isn't optimal

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#2700]
The ssl/tls configuration of nuget.org isn't optimal. 

It is easy to get an A grade by disabling RC4. Also there is no benefit by keeping RC4 enabled (see results) 

https://dev.ssllabs.com/ssltest/analyze.html?d=nuget.org&hideResults=on

Rc4 is broken: https://qualys.jive-mobile.com/#jive-document?content=%2Fapi%2Fcore%2Fv2%2Fposts%2F2099

**Comment by 304NotModified** [comment]
Related:

http://www.infoworld.com/article/2979527/security/google-mozilla-microsoft-browsers-dump-rc4-encryption.html

**Comment by blowdart** [comment]
I have no problem with disabling or rearranging ciphers. 

If you're going to disable RC4 there's a supported package for it you'll need to put on all VMs. https://technet.microsoft.com/library/security/2868725?f=255&MSPPError=-2147217396

**Comment by 304NotModified** [comment]
IMO there is no need to reorder the chipers. The current order looks good (security point of view). 

So disabled RC4 (chipers) is the only thing needed.

**Comment by maartenba** [comment]
@blowdart can this be disabled from registry as well? E.g. running this:

```

$preferredCipherSuites = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P256,TLS_DHE_DSS_WITH_AES_256_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_256_CBC_SHA,TLS_DHE_DSS_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA"
$rebootRequired = $false

# Disable SSL 2.0
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server" "Enabled" 0 "DWord") -Or $rebootRequired

# Disable SSL 3.0
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0") -Or $rebootRequired
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server" "Enabled" 0 "DWord") -Or $rebootRequired

# Enable TLS 1.1
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1") -Or $rebootRequired
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server" "DisabledByDefault" 0 "DWord") -Or $rebootRequired
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" "DisabledByDefault" 0 "DWord") -Or $rebootRequired

# Enable TSL 1.2
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2") -Or $rebootRequired
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server" "DisabledByDefault" 0 "DWord") -Or $rebootRequired
$rebootRequired = (UpdateRegistryPath "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client") -Or $rebootRequired
$rebootRequired = (UpdateRegistryKey "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client" "DisabledByDefault" 0 "DWord") -Or $rebootRequired

# Protocol versions done, set preferred cipher suites
$rebootRequired = (UpdateRegistryKey "HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002" "Functions" $preferredCipherSuites "String") -Or $rebootRequired
```

**Comment by blowdart** [comment]
That works too :)

**Comment by maartenba** [comment]
@yishaigalatzer are you okay if we limit the supported cyphers? if so will merge this into pre-prod so we can ensure the NuGet clients don't break

**Comment by yishaigalatzer** [comment]
Can you explain the impact or potential impact?

**Comment by maartenba** [comment]
The good thing: we'd no longer support cyphers that are considered unsafe. Potential impact could be people using the website on older machines/browsers (e.g. a Windows Server 2003 or XP with IE6) can no longer access it.

We'd still be supporting TLS 1.0 (it's one of the defaults in .NET 4.5 and older and I don't recall our client setting another value - https://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols(v=vs.110).aspx), which means we can safely remove SSL3 support.

**Comment by 304NotModified** [comment]
Winxp was already not supported as it uses ssl 3 and not tls? See report ssllabs. 

Impact in summary : none for up to date systems. See also report ssllabs (rc4 isn't used with the client tests)

**Comment by maartenba** [comment]
Just gave this a try on pre-production, seems we now have an A grade (ignore the cert mismatch as I tried on the raw cloudapp.net URL)

@yishaigalatzer this should also not have any effect on our clients (same settings on MyGet for over a year now with no issues reported), I think we are good to go with this one.

**Comment by 304NotModified** [comment]
This isn't fixed yet?

https://dev.ssllabs.com/ssltest/analyze.html?d=nuget.org&hideResults=on

![image](https://cloud.githubusercontent.com/assets/5808377/10787733/550bc55c-7d73-11e5-84fb-106ca5875377.png)


![image](https://cloud.githubusercontent.com/assets/5808377/10787725/4b8d83c6-7d73-11e5-9ac8-d51cf206288d.png)

**Comment by maartenba** [comment]
Will have another look at it.

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
Is see an A :)

**Comment by 304NotModified** [comment]
This is still not fixed:

Scan a few moments ago.

![image](https://cloud.githubusercontent.com/assets/5808377/10964281/7a120f62-83a6-11e5-8a32-0ba13c590dbe.png)

probably is this not configured well on all servers?

Please reopen.

**Comment by 304NotModified** [comment]
@maartenba bump

**Comment by maartenba** [comment]
On our next deploy. Patience :)

**Comment by 304NotModified** [comment]
I have patience, but it was really unclear if this was getting fixed. Is not in the new release plan AFAIK

**Comment by maartenba** [comment]
Check again :)

**Comment by gjkhw** [comment]
This still appears to be an issue.  As to impact, it is breaking for me in two scenarios of different severity:

1. On Safari on OS X 10.11 I cannot open any pages on nuget.org at all in the default configuration of the OS (Application Transport Security enabled).
2. On Xamarin Studio on OS X 10.11 I get repeated warnings about an insecure certificate from nuget.org, since I use many nugets from your otherwise very helpful server (thank you!).  I dismiss them and cringe a little inside.

I understand the root cause of what's going on.  A number of other users who haven't run this to completion are going to be confused.  It's also pretty annoying even if you understand the workarounds.

**Comment by maartenba** [comment]
We'll look into it, thanks

**Comment by 304NotModified** [comment]
@gjkhw what's the root cause? 

Os x should be able to connect, see https://dev.ssllabs.com/ssltest/analyze.html?d=nuget.org&hideResults=on

**Comment by gjkhw** [comment]
At the time that I added my comment, the result from the SSL Labs test site was a "B" grade.  It was failing due to the RC4 ciphers.  Shortly after I posted, the grade improved to an "A", and the the RC4 ciphers were no longer in the list.  Perhaps someone made a change on the nuget servers.  I'm not sure.

At this point in time, my iOS9 personal device is able to connect to nuget.org just fine.  I don't know if it ever had problems - I only thought to check it after I began looking at this issue.

My OS X 10.11 machine is still having the same user-visible issues with Safari and Xamarin Studio.  Here are some reports from some diagnostic tools that I tried.  I suspect that at this point the problem is on my local machine.  Perhaps my local list of trusted roots is wrong.  I have not tried to troubleshoot these errors.  I do think that these are different errors than the ones that I was seeing this morning, but I did not save any debug logs to compare with.

```
curl -v https://www.nuget.org
* Rebuilt URL to: https://www.nuget.org/
*   Trying 191.236.146.247...
* Connected to www.nuget.org (191.236.146.247) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
```

```
nscurl --ats-diagnostics https://www.nuget.org
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://www.nuget.org.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
Use '--verbose' to view the ATS dictionaries used and to display the error received in URLSession:task:didCompleteWithError:.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
2016-04-11 13:33:51.736 nscurl[1972:496041] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
...
```

If I come up with anything useful, I'll respond here, but for now I assume that the problems are all on my end.  Thanks for the help!

**Comment by maartenba** [comment]
Could be because of a temporary failover, will look into it.

**Comment by 304NotModified** [comment]
FYI chain issues has nothing to do with chipers (RC4 etc) .

**Comment by gjkhw** [comment]
Thank you.  My apologies for not providing accurate information in my first comment.  If I get to the bottom of the chain issue, I will report.  As I said, I believe the issue is local to my machine.
