### ISSUE TITLE
dist.nuget.org - Downloads Link Broken - Default File Handler

### ISSUE THREAD

**Issue by dmccaffery** [NuGet/NuGetGallery#2701]
As an FYI:

The application pool hosted at: https://dist.nuget.org does not seem to have a default document handler (or index.html is not registered as a default document). Attempting to browse to: https://dist.nuget.org directly results in an XML error. Also, the "Downloads" link for the header navigation is set to: "https://dist.nuget.org" instead of "https://dist.nuget.org/index.html", which will cause the same error to appear.

![screen shot 2015-09-25 at 3 20 04 pm](https://cloud.githubusercontent.com/assets/1803684/10113431/0f03c1a2-6399-11e5-8bff-81cfaf35d0a7.png)
![screen shot 2015-09-25 at 3 20 48 pm](https://cloud.githubusercontent.com/assets/1803684/10113432/0f5f71a0-6399-11e5-8e00-bf1fca605add.png)

**Comment by maartenba** [comment]
Link in the header has been fixed, default document is pending.

**Comment by maartenba** [comment]
We now have www.nuget.org/downloads as the official URL
