### ISSUE TITLE
Downloads miscount

### ISSUE THREAD

**Issue by dajuric** [NuGet/NuGetGallery#2702]
The downloads count shown in the summary and by the packages does not match. An image is enclosed.

![miscount](https://cloud.githubusercontent.com/assets/4395047/10116801/dab0fec6-6440-11e5-97c3-5319e05e0bf4.jpg)

**Comment by maartenba** [comment]
@dajuric we're investigating this one, thanks for reporting!

**Comment by maartenba** [comment]
This has been resolved.
