### ISSUE TITLE
Cannot install some packages in VS15 Community on Win10 (Both command and GUI)

### ISSUE THREAD

**Issue by heku** [NuGet/NuGetGallery#2703]
PM> install-package System.Data.SQLite -dependencyversion highestminor
Attempting to gather dependencies information for package 'System.Data.SQLite.1.0.98.1' with respect to project 'OralEval.Infrastructure.Repositories', targeting '.NETFramework,Version=v4.0'
Attempting to resolve dependencies for package 'System.Data.SQLite.1.0.98.1' with DependencyBehavior 'HighestMinor'
Resolving actions to install package 'System.Data.SQLite.1.0.98.1'
Resolved actions to install package 'System.Data.SQLite.1.0.98.1'
Adding package 'EntityFramework.6.1.3' to folder 'C:\Codes\OralEval\packages'
Added package 'EntityFramework.6.1.3' to folder 'C:\Codes\OralEval\packages'
'App.config' already exists. Skipping...
Added package 'EntityFramework.6.1.3' to 'packages.config'
Executing script file 'C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\init.ps1'
Executing script file 'C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\install.ps1'

**Unable to find type [NuGet.VisualStudio.IVsPackageInstallerServices].**

At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1004 char:5
+     $packageInstallerServices = $componentModel.GetService([NuGet.Vis ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (NuGet.VisualStu...stallerServices:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
You cannot call a method on a null-valued expression.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1006 char:5
+     $vsPackage = $packageInstallerServices.GetInstalledPackages() | ? ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:740 char:28
+     $toolsPath = Join-Path $installPath tools
+                            ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:74
+ ...  [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsPath EntityF ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
You cannot call a method on a null-valued expression.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:810 char:20
+         (Join-Path $runner.ToolsPath EntityFramework.PowerShell.dll),
+                    ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
Unable to find type [NuGet.VisualStudio.IVsPackageInstallerServices].
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1004 char:5
+     $packageInstallerServices = $componentModel.GetService([NuGet.Vis ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (NuGet.VisualStu...stallerServices:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
You cannot call a method on a null-valued expression.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1006 char:5
+     $vsPackage = $packageInstallerServices.GetInstalledPackages() | ? ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:740 char:28
+     $toolsPath = Join-Path $installPath tools
+                            ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:74
+ ...  [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsPath EntityF ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 
You cannot call a method on a null-valued expression.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Codes\OralEval\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:810 char:20
+         (Join-Path $runner.ToolsPath EntityFramework.PowerShell.dll),
+                    ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
 

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully installed 'EntityFramework 6.1.3' to OralEval.Infrastructure.Repositories
Install failed. Rolling back...
Package 'System.Data.SQLite.Core 1.0.98.1' does not exist in project 'OralEval.Infrastructure.Repositories'
Removed package 'EntityFramework 6.1.3' from 'packages.config'
Package 'System.Data.SQLite.Core 1.0.98.1' does not exist in folder 'C:\Codes\OralEval\packages'
Removing package 'EntityFramework 6.1.3' from folder 'C:\Codes\OralEval\packages'
Removed package 'EntityFramework 6.1.3' from folder 'C:\Codes\OralEval\packages'
install-package : Object reference not set to an instance of an object.
At line:1 char:1
+ install-package System.Data.SQLite -dependencyversion highestminor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1470
