### ISSUE TITLE
nuget install -ExcludeVersion not working with packages.config

### ISSUE THREAD

**Issue by vonlipwigmoist** [NuGet/NuGetGallery#2704]
with nuget version  3.2.0.10516 the following command does not work as expected:
nuget install packages.config -ExcludeVersion
The destination directory still contains the version number while the documentation states that it shouldn't.
If a packageId is given instead of a packages.config file it works as expected.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1473
