### ISSUE TITLE
Custom nuget gallery

### ISSUE THREAD

**Issue by rekna1** [NuGet/NuGetGallery#2705]
We have a custom nuget gallery. I tried to upgrade to the latest version. I followed installation instructions for a new gallery, but of course, we have existing packages and existing database.
After upgrading the site works, it shows packages and their version history, but when I click on a package version, I get 404 not found.

When trying to download a package with package manager explorer, I get an error : 
Error downloading 'name of the package'. The underlying connection is closed. An unexcepted error has occured when receiving. Elmah is not showing any errors.

One package succeeds... but the rest of them fail downloading.

**Comment by maartenba** [comment]
Have you run the "Update-Database" command to also upgrade the database schema?

**Comment by rekna1** [comment]
yes I did , i checked the database migration tables , it contains about 49 items while the original only contained 24...

**Comment by maartenba** [comment]
Can you confirm the following settings in Web.config are set to empty?

```
<add key="Gallery.ServiceDiscoveryUri" value="" /> 
<add key="Gallery.SearchServiceResourceType" value="" /> 
<add key="Gallery.AutocompleteServiceResourceType" value="" />
<add key="Gallery.AzureCdnHost" value="" />
```

**Comment by rekna1** [comment]
yes they are all empty

**Comment by maartenba** [comment]
Then I'd say try to attach a debugger to the `PackagesController`'s `PackageDetails` action and see what is causing this. Could be configuration, could be database schema.

**Comment by rekna1** [comment]
Can not find PackageDetails in PackagesController, also looked in github source there is no PackageDetails

**Comment by rekna1** [comment]
When debugging I can see a ArgumentNullException on PackageFileService.BuildFileName for the argument "version"

**Comment by maartenba** [comment]
This is the one - https://github.com/NuGet/NuGetGallery/blob/767112aa7ec1e02b8fca20b53913d48191eb1592/src/NuGetGallery/Controllers/PackagesController.cs#L263

**Comment by rekna1** [comment]
Also in DisplayPackage, I can see version = null

**Comment by rekna1** [comment]
When executing FindPackageByIdAndVersion, the follow query is executed and results in null:
`package = packageVersions.SingleOrDefault(
                    p => p.PackageRegistration.Id.Equals(id, StringComparison.OrdinalIgnoreCase) &&
                         (
                            String.Equals(p.NormalizedVersion, SemanticVersionExtensions.Normalize(version), StringComparison.OrdinalIgnoreCase)
                         ));`

**Comment by maartenba** [comment]
Looks like a database schema issue. Which was the version you had before the update? E.g. which commit?

**Comment by rekna1** [comment]
I don't know, but it was very old... I see several files dating from octobre 2012...

**Comment by rekna1** [comment]
In the above list of packageVersions all p.NormalizedVersion are null...
(have to go now, catch you later...)

**Comment by maartenba** [comment]
Looks like you need to update the NormalizedVersion column in your packages table.

**Comment by rekna1** [comment]
Problem seems to be solved. I had to do the following to get it working:
Script using linqpad to update NormalizedVersion and set it to semanticVersion.ToNormalizedString() for all packages (using Nuget.Core packages which contains SemanticVersion class)
Script to rename all packages for which Version and Normalized version are different, in packages folder. Package filename must use Normalized version instead of Version.
