### ISSUE TITLE
Doc issue: github-workflow

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#2706]
The  github-workflow docs seems out to date?

https://github.com/NuGet/NuGetGallery#the-git-workflow

There is not "iter-start". This should be "master"? (related #1811 and #2311)

 > 5. Merge your changes in to master

I don't get this. Are contributions only allowed by official NLog contributors?

**Comment by maartenba** [comment]
Updated README. https://github.com/NuGet/NuGetGallery/blob/master/README.md
