### ISSUE TITLE
Nuget Pack doesn't include resource files (single localized package approach)

### ISSUE THREAD

**Issue by richieeeeeeee** [NuGet/NuGetGallery#2708]
Hi,
I try to pack an NugGet package that contains all my localized resource files as described here:
https://docs.nuget.org/create/creating-localized-packages

Unfortunately, the resource DLLs are not included in the packed file. Whats wrong? Here is my nuspec (I removed some attributes like license):

```xml
<?xml version="1.0"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>$description$</description>
    <releaseNotes>See Redmine/SVN</releaseNotes>
  </metadata>
</package>
```
My output folder of VS 2013 bin\Debug:
```
en
   MyAssembly.resource.dll
es
   MyAssembly.resource.dll
MyAssembly.dll
```
However, the final package after calling "nuget pack MyAssembly.csproj" contains only the MyAssebly.dll, not the resource files.

What's wrong?

Thanks!

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1482
