### ISSUE TITLE
NuGet.config settings are not enforced between workspaces

### ISSUE THREAD

**Issue by theo-albers** [NuGet/NuGetGallery#2709]
We have a workspace like this:
- src
  - build
  - build-output
  - solution-folder-1
  - ...
  - solution-folder-n

We have release branches in TFS. We have local NuGet packages with a hard coded version number, so in release branch v1.0 we have NuGet package abc-1.0.0, but in release branch v2.0 we also have abc-1.0.0. The packages are different, content wise. This is the way it has worked well in the past.
With the latest NuGet version in VS2013, 2.8.60723.765, we have problems with workspace isolation. When I create two workspaces;
- c:\dev\src-v1.0 for our release 1.0, TFS workspace v1-0 
- c:\dev\src for our trunk version, TFS workspace trunk

NuGet will resolve NuGet packages from 1 workspace build-output folder. So when I build the trunk version, it uses the packages local to the trunk build-output folder. When I switch workspaces and open a solution in the v1-0 workspace, it will still use the packages local to trunk. It should have used the build-output folder of the v1-0 workspace. This problem persists even after closing VS or cleaning the package cache. 
We have a NuGet.config like this in each solution .nuget folder. 

~~~
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>

  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>

  <packageSources>
    <remove key="Itesso package source" />
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>

  <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>

</configuration>
~~~

When I open the settings dialog in VS I see it picks up the correct NuGet.config settings for the package source. The only way to eliminate the problem is to remove the trunk workspace from disk. It's very disturbing that we can't rely on package isolation per workspace.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1481
