### ISSUE TITLE
Inconsistent number style (group or thousand separators)

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#2710]
I'm not sure if this is dependent of someone's (browser) culture, but I'm seeing different number styles, which looks sloppy.

Current status
===
Home page has dots between thousands:
![image](https://cloud.githubusercontent.com/assets/5808377/10177524/df9f574a-66fa-11e5-8f95-e524d105a484.png)

---

Stats page has dots between thousands:
![image](https://cloud.githubusercontent.com/assets/5808377/10177385/2f876410-66fa-11e5-9884-58d33307a450.png)

---

Stats of a package has commas.
![image](https://cloud.githubusercontent.com/assets/5808377/10177393/46ceb4ca-66fa-11e5-94dd-1de3c54411a5.png)

---

Packages overview has commas:
![image](https://cloud.githubusercontent.com/assets/5808377/10177510/ceb2cdc2-66fa-11e5-86a5-93586c20dee0.png)

---

Version history of a package has **no** separator.. (difficult to read)

![image](https://cloud.githubusercontent.com/assets/5808377/10177412/6161e898-66fa-11e5-9b46-9c423a3575c9.png)

Resolution
----
Choose one format (preferred: browser or profile culture, please do use thousand separators), and use them everywhere! (maybe create a C# extension on int to prevent inconsistencies).

**Comment by maartenba** [comment]
Now that would be an awesome PR :-)

**Comment by 304NotModified** [comment]
If I have some spare time, I will try to create a PR. I cannot guarantee anything as I'm a bit over scheduled.

**Comment by maartenba** [comment]
Closing the issue, thanks for your work!
