### ISSUE TITLE
Nuget package Restore

### ISSUE THREAD

**Issue by saadsami119** [NuGet/NuGetGallery#2713]
We have deployed our custom package feed. Incidentally our package name is exactly same as package name on the NuGet gallery. Therefore during the packing restore process it downloads the package from the NuGet gallery assigning it the highest priority and doesn't download it from our local feed. How can we set the priority to first locate the packages in our local NuGet  feed.

**Comment by maartenba** [comment]
@saadsami119 you can do this by changing the order in your `NuGet.config`. Here's a very simple example that you can place next to your solution file:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <clear />
    <add key="YourOwnFeed" value="https://feed/url/goes/here" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

**Comment by juRiii** [comment]
what is the purpose of `<clear />`? what happens if i leave it out?

**Comment by maartenba** [comment]
It clears the existing list of package sources, allowing you to enter them again in a different order.

**Comment by juRiii** [comment]
what do you mean by `existing list of package sources`? the only config we know about, is `%appdata%\nuget`. are there any default sources, which are not visible in the config file?

**Comment by maartenba** [comment]
That is one, but you can also place an additional one next to your solution file so that the configuration becomes solution-specific - see http://blog.maartenballiauw.be/post/2014/03/11/NuGet-Configuration-File-inheritance-is-awesome.aspx

You can just remove the `<clear />` element and reorder the sources in your main NuGet.config as well.

**Comment by saadsami119** [comment]
Thanks for the help. We tried this solution as you provided but we still had the same problem. It was restoring the package from NuGet gallery. But when we deleted all the packages files inside the  %APPDATA%Local\NuGet\Cache folder and executed the restore script again and then it worked. It prioritized our custom feed first. Looked like it was restoring the package from the local cache.
