### ISSUE TITLE
Integrate package delete in NuGet gallery

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2714]
Integrate package delete in NuGet gallery. Goal is to first light this up for administrators.

## Scope
NuGet.org currently does not allow people to delete their packages. Our policy has always been to only permanently delete NuGet packages that really need it, such as packages that contain passwords, malicious/harmful code, legal reasons, etc. Users can unlist their packages, hiding the package in search results but keeping it available for download and packages depending on it. 

For the cases where a delete is needed (for the aforementioned reasons), we want functionality for the NuGet administrators to delete packages. Deletes can be “soft” deletes, where the package is rendered unavailable in search results and package install/restore scenarios but where the package details page shows that the package was deleted, and “hard” deletes where all traces of a package are removed in all different systems. 

Deletes must be traceable and should involve creating a backup of the current package state so that if needed, we can find who deleted a package and why, and optionally restore it to our systems.

## Goals
The following are the goals for package deletes: 
* Package deletes should be available from the gallery UI for administrators. We may surface this for users (self-service) later on. 
* Package deletes should be traceable (who, when, why and keep a backup of original package) 
* Package deletes should be available per package, and in bulk (for a given package registration delete all versions, delete a list of packages). 
* Deletes are stored in the main gallery database (with tracing) and replicated to other systems from there on. 

Additionally, we want to provide a GitHub-style “Danger Zone” warning that should inform the user about to delete the package that unlisting is still favored. This warning could include a note about the number of packages depending on it, the number of downloads ,…

### Hard delete vs. soft delete
Package deletes can be soft deletes and hard deletes. With both options, the package binary is rendered unavailable and the package is removed from any search results. 

Soft delete keeps the package registration and version combination unavailable, as if the package existed. No new package with the same identifier and version can be pushed to NuGet.org. Soft delete keeps a package details page available that provides a clear message to NuGet users as to why the package has been deleted.

Hard delete purges a package from all systems and removes its package registration + version combination. No traces of the delete are visible to end users: if a package has been deleted it no longer exists. After a hard delete, a new package with the same identifier and version can be pushed to NuGet.org, essentially overwriting a package.

## Flow through systems
When a delete happens in the gallery database, it must propagate to other systems like search, flat container and so on. 

A delete in the gallery database must be appended to the catalog so it can be recognized as a delete by the various jobs. 

* For example, a “PackageDelete” catalog entry could instruct the Lucene job to remove the package from the index, as seen [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/SearchIndexFromCatalogCollector.cs)
* For the registration blobs, a similar approach can be taken by adding the required logic [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Catalog/Registration/RegistrationMaker.cs)
* For DNX, the package binary can be removed and the index.json file updated to no longer contain a given package version.

Traceability should be linked to the support system that is currently being built, so that a delete can originate from a support request. This provides additional tracing on the reasoning why a package was deleted.

## Security
When a package is deleted, whether it is a soft or hard delete, it must never be visible in search results. The package binary must never be available for download once a package has been deleted. 

Technical design of package deletes should incorporate the guarantee that: 
* Deleted packages can never be downloaded 
* Deleted packages never show up in any of the NuGet clients 
* Deleted packages never show up in any of the statistics reports

**Comment by maartenba** [comment]
Loosely related -  #2359

**Comment by forki** [comment]
> Integrate package delete in NuGet gallery.

You should first make it available in API and then let gallery go through API.

(Sorry I shut up.)

**Comment by yishaigalatzer** [comment]
@forki unfortunately the gallery is the API at the moment, our goal is to separate the API from the gallery such that they are completely separate services. For now we want to make deletes a simple administrative process that works without several manual operations it takes today (which is why we are very reluctant to delete packages unless it's a security, privacy or rights infringements).

One step at a time

**Comment by SimonCropp** [comment]
Is this the right place to ask for package redirects?

**Comment by yishaigalatzer** [comment]
New issue? I don't even know what redirect means :)

**Comment by SimonCropp** [comment]
@yishaigalatzer https://github.com/NuGet/NuGetGallery/issues/2736
