### ISSUE TITLE
Question: deployment plans - GitHub milestones 

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#2717]
Hi, 

I really like the [deployment plans] (https://github.com/NuGet/NuGetGallery/wiki/Deployments). 

But why are those GitHub issues and not just GitHub milestones?

**Comment by maartenba** [comment]
Trying to figure out what works best. For now working with issues, may become GitHub releases one day.
Issues are easier to search + we can manage them in tools like Huboard.

**Comment by yishaigalatzer** [comment]
Closing, as this doesn't seem to be a bug. Feel free to continue the discussion
