### ISSUE TITLE
The 'IntegrationPackage' package did not load correctly after Installing Latest Build

### ISSUE THREAD

**Issue by rmegal** [NuGet/NuGetGallery#2718]
Running VS2015 Community Edition. I am getting the following error after updating to NuGet Package Manager for Visual Studio 3.2.60914.10516:

> The 'IntegrationPackage' package did not load correctly.

I can easily recreate the error by firing up VS2015 and opening any file. Or starting VS2015 and passing it a file to open in the editor.

I get the following error if I select `Tools/Options/Nuget Package Manager`:

> The 'NuGetPackage' package did not load correctly.

I tried to attach some screenshots and the ActivityLog but kept getting:

> Something went really wrong, and we can't process that file. Try again.

I will keep them around and try again later.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1519
