### ISSUE TITLE
Missing Package odp.net.managed

### ISSUE THREAD

**Issue by MikeOsborn** [NuGet/NuGetGallery#2721]
Searching for [odp.net.managed](http://www.nuget.org/packages?q=odp.net.managed) returns the following result:

[Oracle Data Provider for .NET (ODP.NET) Managed Driver By: stemann](http://www.nuget.org/packages/odp.net.managed/)

When you visit the link a "404 : Page Not Found" error is displayed.

**Comment by xavierdecoster** [comment]
Yep. Here's why: http://blog.nuget.org/20151007/Package-Content-and-Removals.html
