### ISSUE TITLE
NuGet Slow, becuase of UI refresh

### ISSUE THREAD

**Issue by reader-man** [NuGet/NuGetGallery#2722]
When you use nuget at the solution level to add/remove a package to multiple Projects, it takes a long time for a trivial functionality, i think one of the reasons is because its trying to show the changes in the Solution Explorer and maybe other UI controls, instead of using the new VS 2015 mechanism of having a watch on nodes and metadata instead of a sharing model, to disconnect the UI from the Model.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1536
