### ISSUE TITLE
EmailConfirmation Fails

### ISSUE THREAD

**Issue by Darknet** [NuGet/NuGetGallery#2726]
Hi everyone,

I've a problems with nuget gallery.

I change the value of Gallery.ConfirmEmailAddresses to false

But when i try to upload a package.

Before you can upload a package you must first confirm your email address.

where i can change this or where i can configure a email smtp.

thanks a lot.

P.D It's possible the integration with Active Directory??

**Comment by maartenba** [comment]
You can set the Gallery.SmtpUri option, for example:
smtp://user:password@smtpservername:25

**Comment by maartenba** [comment]
AD can be configured by enabling Windows Authentication in web.config.

**Comment by Darknet** [comment]
where i can set this, any document explain

i founfd one where indicate, that it's necessary to set information on database,

https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS

step "14"

but on Database in this table only appear on columns

Key
DownloadStatsLastAggregatedId
TotalDownloadCount
NextLicenseReport

thanks in advance

**Comment by maartenba** [comment]
Just add it to web.config under appsettings, like the other settings.

Regarding AD you will have to edit the authentication element in there.
