### ISSUE TITLE
Could not install package in VS 2015

### ISSUE THREAD

**Issue by mikasoukhov** [NuGet/NuGetGallery#2727]
Could not install package 'StockSharp 4.3.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain 
any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Works ok in VS 2013. In VS 2015 the package https://www.nuget.org/packages/StockSharp cannot be installed.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1542
