### ISSUE TITLE
Package redirects

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#2736]
In many cases people want to rename a package. ATM there is no easy way to do this, you basically have to release a broken version of the old package with some kind of message to move to the new package. It would be nice to have this handled in a more seamless way by nuget. 

If you are willing to hack many things in the nuget toolset then you can handle it yourself, but it is painful. Here is the work we had to do to move users to a new package https://github.com/Particular/NServiceBus/issues/2113

**Comment by yishaigalatzer** [comment]
That's something I've been wanting for a while for a few more scenarios. 

This issue should go to the home repo, as it is not a server issue.

Worth a good discussion to cover all the scenarios (both tooling and user scenarios).

Thanks!

**Comment by SimonCropp** [comment]
@yishaigalatzer is there an existing issue tracking it? or should i move this to the home repo?

**Comment by yishaigalatzer** [comment]
Move it. This is something I wanted as a nuget customer. But I don't believe it is tracked on github
________________________________

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1590
