### ISSUE TITLE
Global Package Management

### ISSUE THREAD

**Issue by briandrennan** [NuGet/NuGetGallery#2737]
Hi,

I see there's support for a single download repository on the hard drive in the NuGet docs, but there is no (good) way to let that location be the one referenced by the package manager when you're working on a project. Would like to see support for global package management on the local client, with support for networked drive and server paths so that teams can have locally shared repositories, removing a need for downloading the same packages multiple times. (I use Newtonsoft.Json quite a bit, and have it referenced in several projects).

The best way I've found to manage packages within a solution right now is <HintPath>$(SolutionDir)\.nugget\[packagename]</HintPath>.

**Comment by briandrennan** [comment]
By the way, I wouldn't mind working on this one myself if the community agrees it would be a good feature.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1604
