### ISSUE TITLE
Change content type to "binary/octet-stream" for packages

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2740]
To avoid IE/Edge automatically try to open/save it for zip.
1.	Update gallery + jobs: change content type to “binary/octet-stream”
2.	Build a onetime tool to change existing packages.

**Comment by maartenba** [comment]
Updated code + existing blobs.

**Comment by eric-miller-cdfw** [comment]
The media type "binary/octet-stream" is not valid according to the IANA registry. Where did you come up with this media type? What is wrong with "application/octet-stream"?

http://www.iana.org/assignments/media-types/media-types.xhtml
