### ISSUE TITLE
Commandline switch on nuget push to skip if already published

### ISSUE THREAD

**Issue by lukemcgregor** [NuGet/NuGetGallery#2743]
Currently if the package is already published the following occurs

> Pushing Pkg 1.0.0 to the NuGet gallery (https://www.nuget.org)...
> Failed to process request. 'A package with id 'Pkg' and version '1.0.0' already exists > and cannot be modified.'.
> The remote server returned an error: (409) Conflict..

And a non-zero return code is returned from nuget push

I would like to add another switch to pack so that the following occurs

`nuget push Pkg -SkipIfAlreadyPublished`

 > A package with id 'Pkg' and version '1.0.0' already exists, skipping...

A zero return code is returned.

This would allow for better integration with automated build tools which produce nuget packages.

**Comment by lukemcgregor** [comment]
To do this I want to edit https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/NuGet.CommandLine/Commands/PushCommand.cs But I cant work out how to build the project. 

Ive tried using home (http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment) But the nuget3 solution doesn't appear to build the CLI.

Building PackageManagement directly seems to fail as it refers to a bunch of nuget packages which dont exist yet.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1630
