### ISSUE TITLE
Search "version" by V3 does not return matched older versions

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2744]
Example:
V2v3:
http://int-0-v3.cloudapp.net//query?q=Version%3A%221.0.15%22+AND+Id%3A%22ContpaqiNubeNomiPAQEntity%22

http://int-0-v3.cloudapp.net//query?q=Version%3A%221.0.0%22+AND+Id%3A%22ContpaqiNubeNomiPAQEntity%22

While V2 could return correct result:
http://nuget-prod-0-v2searchwebsite.azurewebsites.net/search/query?q=Version%3A%221.0.0%22+AND+Id%3A%22ContpaqiNubeNomiPAQEntity%22

**Comment by johnataylor** [comment]
This is a raw Lucene query on the search endpoint (indicated by the fact that the URI is missing a luceneQuery=false and teh use of the word AND in the query)

Raw lucene queries are a debug hook in the service and something we can just do without. From here on we can just ignore the luceneQuery argument and always do a nuget query and never a Lucene query.

If we reintroduce this we should make it a separate endpoint so as to remove any confusion like this.
