### ISSUE TITLE
Search "tag" by V3 return 500 

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2745]
V2v3 return 500 when the tag expression is not accepted.
http://int-0-v3.cloudapp.net/query?q=Tags:"abc;"
other query: Tags:"abc"",Tags:""abc", Tags:":", Tags:","

V2 search return invalid query (400):
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=Tags:"abc;"

**Comment by joyhui** [comment]
For some charactor V2 works ok, while V3 return 500:
Tags:",", ":", "."

Example:
V2:
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=Tags%3A%22%3B%22&luceneQuery=false&take=2
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=Tags:%22.%22

V3: 
http://api-v3search-0.nuget.org/query?q=Tags:%22.%22

**Comment by joyhui** [comment]
I added "ValidateQuery" which return invalid query.. We may want to return default top 10 result.

**Comment by johnataylor** [comment]
This is a parsing problem when " are not closed. This is fixed now on the searchcloud branch.

**Comment by maartenba** [comment]
Tested and confirmed working.
