### ISSUE TITLE
V2-3 Search change the @id

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2746]
V2-3 Consolidate search change the @id to 
"@id":"caliburn.micro.start/index.json",
http://int-0-v3.cloudapp.net/query?q=Caliburn.Micro.Start

V3 search return:
"@id":"http://api.nuget.org/v3/registration1/caliburn.micro.start/3.0.0-beta1.json",
http://api-v3search-0.nuget.org/query?q=Caliburn.Micro.Start

**Comment by johnataylor** [comment]
This is actually correct. Both responses are logically identical because the new one includes an @base in the @context.
