### ISSUE TITLE
Update not working correctly for NuGet.exe (2.8.6) with -Safe option

### ISSUE THREAD

**Issue by fknx** [NuGet/NuGetGallery#2752]
Hello,

I am using the NuGet.exe (2.8.6) to update my packages with the `-Safe` option. According to the [docs](https://docs.nuget.org/consume/command-line-reference#update-command) the `-Safe` option will not update a package to a higher major or minor version.

When I update a prerelease package with version `6.44.1-C80673` using the `-Safe` option I would expect it to update to a package with version `6.44.1`, `6.44.2` and so on (or any prerelease version with a later version than with `6.44.1-C80673` but starting with `6.44`). Unfortunately this is not the case. Instead, the packages are updated to the latest prerelease version available (in my case `6.45.0-C80620`).

I suspect this is a bug of the `-Safe` option in correlation with prerelease packages.

(Note: I am not using the `-Prerelease` option).

Best regards,
Frederik

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1651
