### ISSUE TITLE
V2 search does not work when include feed

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2753]
Query:
V2v3: 
http://int-0-v3.cloudapp.net/search/query?q=&skip=0&take=30&sortBy=relevance&supportedFramework=MonoAndroid50&feed=microsoftdotnet

http://int-0-v3.cloudapp.net//search/query?q=Sql&&take=3&sortBy=relevance&supportedFramework=wpa81%7Cwin81&feed=windows8-packages

V2:
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=&skip=0&take=30&sortBy=relevance&supportedFramework=MonoAndroid50&feed=microsoftdotnet

It should return 30 results, while V2v3 query returns very few results.

**Comment by johnataylor** [comment]
Looks like we had a case-sensitive lookup of the id when we read the curatedFeeds.json and built the filters.

**Comment by maartenba** [comment]
Tested and confirmed working.
