### ISSUE TITLE
V2V3 internal server error when search Author:"a"

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2754]
When author is "a":
http://int-0-v3.cloudapp.net/search/query?q=Author:%22a%22
http://int-0-v3.cloudapp.net/search/query?q=Author:" ..."

Return 500.. we should return default top 10 results when query is invalid

**Comment by johnataylor** [comment]
I've replaced the query parsing logic completely and this is no longer getting lost in the translation. (It appears the code was assuming a Lucene Query object would round trip through a string which it doesn't always safely do. The new code makes no such assumption.)

**Comment by maartenba** [comment]
Confirmed the issue is fixed.
