### ISSUE TITLE
V2 query behavior is different: search Owners field

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2755]
V2V3:
http://int-0-v3.cloudapp.net//search/query?q=xa&&take=3&sortBy=relevance&luceneQuery=false
Return empty

http://int-0-v3.cloudapp.net//search/query?q=daxnet&&take=3&sortBy=relevance&prerelease=true&luceneQuery=false&X-ARR-LOG-ID=fa893b8c-56c2-4c93-9437-4d78e6cde579
return only one, which title contains "daxnet"

V2:
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=xa&&take=3&sortBy=relevance&luceneQuery=false
Return one data, whose owner field include this "xa"

http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=daxnet&&take=3&sortBy=relevance&prerelease=true&luceneQuery=false
Return three data, whose owner field include this "daxnet"

**Comment by johnataylor** [comment]
All sorts of problems with this: firstly the Owner fields were not being added to the index (they are in a rather too-clever ParallelIndex ... perhaps we won't keep this one long term).

(And the query parsing logic also a little messed up with extra layers of parsing.)

**Comment by maartenba** [comment]
@johnataylor @joyhui Is there anything left to do on this one? The "xa" indeed still returns 0, but when searching for a full author name (e.g. `maartenba`) the results look good.

**Comment by johnataylor** [comment]
I think this should be fixed in v2v3

**Comment by maartenba** [comment]
Yeah it looked like this. Thanks or confirming!
