### ISSUE TITLE
NuGet package source installation

### ISSUE THREAD

**Issue by dajuric** [NuGet/NuGetGallery#2756]
The provided package I created (I cannot upload the nupkg file here):
http://expirebox.com/download/059a5d4acd4c0f92ada91212c2f7b1f1.html

installs fine when used in .NET 4.x.
However, when added to DotNet5 project, it is added as an dependency, the source file is not copied and the readme file is not shown. 

![project](https://cloud.githubusercontent.com/assets/4395047/10806424/75c11ba0-7dd5-11e5-8e3f-2f76cf0b5296.jpg)

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1659
