### ISSUE TITLE
V3 --> V2V3 regression

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2759]
V2V3 and V3:
http://int-0-v3.cloudapp.net//query?q=signalrClient
http://api-v3search-0.nuget.org/query?q=signalrClient

http://int-0-v3.cloudapp.net//query?q=microsoft.net.c
http://api-v3search-0.nuget.org/query?q=microsoft.net.c

**Comment by johnataylor** [comment]
Not seeing a different here at the moment. However, I have just also done a fix on CamelCaseFilter that might help similar scenarios. Anyhow no repro here so closing.
