### ISSUE TITLE
V2 -> V2V3 regression

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2760]
V2:
http://nuget-prod-1-v2searchwebsite.azurewebsites.net/search/query?q=microsoft.office.tools&skip=0&take=30&sortBy=relevance&supportedFramework=net45&luceneQuery=false

It returns results. If remove "luceneQuery=false", no result returned.

V2v3:
http://int-0-v3.cloudapp.net//search/query?q=microsoft.office.tools&skip=0&take=30&sortBy=relevance&supportedFramework=net45&luceneQuery=false

**Comment by johnataylor** [comment]
This looks the same to me now. I've checked with the latest rev of the analyzers and they seem to be good. In the current code I wouldn't expect microsoft.office.tools to return anything because it gets translated into "microsoft office tools" (note the quotes) which doesn't match anything.
