### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by RiaanAspeling** [NuGet/NuGetGallery#2761]
I've compiled and used the latest NuGetGallery on a clean installed server. (Server 2012, IIS 8.5.9600.16384, SQLExpress 2008 R2) When accessing : 
http://localhost/admin
it redirects to : 
http://localhost/users/account/LogOn?ReturnUrl=%2Fadmin
which in turn redirects to : 
http://localhost/admin
and so on and so on, until a error too many redirects.

Anybody know about this issue?

**Comment by maartenba** [comment]
Looks like a configuration issue where the login isn't stored somehow. Did you configure anything special in Web.config under <authorization> ?
Does the loop also happen in, say another browser or after cleaning cookies?

**Comment by RiaanAspelingSage** [comment]
I found the problem. The user that was logged on and tried to access the admin page directly, was not an admin user. This is before the role was created or assigned. After doing so, there was no problem. The user was able to access the admin page.

I feel that when the URL is accessed directly and the user does not have the rights, the user should rather be notified than sent into a for-ever-loop-loop-loop...

**Comment by fabiostawinski** [comment]
It happens here time to time and I get a URL like, I fix restarting IIS:
/users/account/LogOn?ReturnUrl=%2Fusers%2Faccount%2FLogOn%3FReturnUrl%3D%252Fusers%252Faccount%252FLogOn%253FReturnUrl%253D%25252Fusers%25252Faccount%25252FLogOn%25253FReturnUrl%25253D%2525252Fusers%2525252Faccount%2525252FLogOn%2525253FReturnUrl%2525253D%252525252Fusers%252525252Faccount%252525252FLogOn%252525253FReturnUrl%252525253D%25252525252Fusers%25252525252Faccount%25252525252FLogOn%25252525253FReturnUrl%25252525253D%2525252525252Fusers%2525252525252Faccount%2525252525252FLogOn%2525252525253FReturnUrl%2525252525253D%252525252525252Fusers%252525252525252Faccount%252525252525252FLogOn%
