### ISSUE TITLE
unable to get packages what I have upload on my own Nuget Gallery azure website?

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2762]
I have created a new azure website and uploaded code of NugetGallery on that.

Everything working fine (register new user,upload packages etc)

But When I enter my website url into package manager - package source - I do not get any packages it is just loading.
Created new available package source -
name - mytest
source- http://mydemosite-nuget.azurewebsites.net/packages

then also not loaded all packages :( why so?

![untitled](https://cloud.githubusercontent.com/assets/3287696/10845455/fa8a68ec-7f2d-11e5-8c24-4fcddad85904.png)

**Comment by maartenba** [comment]
Try source: http://mydemosite-nuget.azurewebsites.net/api/v2

**Comment by ashuthinks** [comment]
thanka a lot
