### ISSUE TITLE
Cannot view package statistics per client

### ISSUE THREAD

**Issue by forki** [NuGet/NuGetGallery#2763]
Go to https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version
try to click "Client name" checkbox.

This used to work and show "package statistics per client" now it does nothing for me. Tested in chrome and edge.

**Comment by csharpfritz** [comment]
Looks like a JavaScript error.




On Fri, Oct 30, 2015 at 10:56 AM, Steffen Forkmann <notifications@github.com

**Comment by maartenba** [comment]
Indeed! Pushed a fix.
