### ISSUE TITLE
All Framework for shared dependency group is misleading

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2764]
Consider the following nuspec

```
<dependencies> 
   <group>
      <dependency id="RouteMagic" version="1.1.0" />
   </group>

   <group targetFramework="net40">
      <dependency id="jQuery" />
      <dependency id="WebActivator" />
   </group>

   <group targetFramework="sl30">
   </group>
</dependencies>
```

nuget.org will show that RouteMagic is available for All Frameworks, where in reality it is just a fallback so it will be installed in (3.5 and lower, and native).

Need to come up with a better message.

https://github.com/NuGet/Home/issues/1661

**Comment by maartenba** [comment]
So in this case only .NET 4 and SL should be displayed?

**Comment by skofman1** [comment]
We should discourage authors from publishing packages with dependencies that are not tfm specific. This will go into future work of "search by TFM": https://github.com/NuGet/Announcements/issues/5
There's no small fix to dependencies UI we can make to improve this.
