### ISSUE TITLE
Automatic import of props at top of project file is not always correct.

### ISSUE THREAD

**Issue by aodennison** [NuGet/NuGetGallery#2766]
(V 2.8.50926.663) Automatically inserting the include of "xxx.props" file at top of the csproj file does not work if the properties refer to certain MsBuild symbols. It causes MsBuild/VS to throw errors.

For example, the following fails with an unhelpful error about an invalid startIndex passed to Substring if it is included at the start of the project; presumably because TargetFrameworkVersion is not defined yet. It works fine if it is included at the end of the project.

build\Framework.Compilation.Symbols.props
    
	<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	    <PropertyGroup>
	        <DefineConstants>
				$(DefineConstants); TFV_$(TargetFrameworkVersion.Replace("v", "").Replace(".", "_"))
			</DefineConstants>
	        <DefineConstants Condition="$([System.Version]::Parse('$(TargetFrameworkVersion.Substring(1))').CompareTo($([System.Version]::Parse('4.6'))))   &gt;= 0">$(DefineConstants);NETFX_46</DefineConstants>
	    </PropertyGroup>
	</Project>

While the documentation [https://docs.nuget.org/release-notes/nuget-2.5]  does say: "The .props file is added at the top, whereas the .targets file is added to the bottom." The implications of this are not obvious. The lack of other documentation/examples make this difficult to debug.

Below is an example which does work as intended, but only if the included properties file is deliberately misnamed "Framework.Compilation.Symbols.targets" so that NuGet insert the include at the end of the csproj file. If it is is named "Framework.Compilation.Symbols.props" it fails.

The entire nuspec is here for completeness. The relevant line is:

	<file src="build\Framework.Compilation.Symbols.targets" target="build\Framework.Compilation.Symbols.targets" />

Framework.Compilation.Symbols.1.0.0-alpha.nuspec

	<?xml version="1.0" encoding="utf-8"?>
	<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
	    <metadata minClientVersion="2.8">
	        <id>Framework.Compilation.Symbols</id>
	        <version>1.0.0-alpha</version>
	        <authors>Andrew O. Dennison</authors>
	        <owners>Andrew O. Dennison</owners>
	        <projectUrl>http://stackoverflow.com/questions/3436526/detect-target-framework-version-at-compile-time/29001688?noredirect=1#comment53939916_29001688</projectUrl>
	        <requireLicenseAcceptance>false</requireLicenseAcceptance>
	        <developmentDependency>true</developmentDependency>
	        <description>Defines the cummulative (backwardly compatible) set of compile-time constants for conditionally compiling version dependent code. E.g. if the csproj Target framework specifies ".NET Framework 4", then NETFX_40, NET_35, NETFX_30 and NETFX_20 are defined.
	Also defines TFV_XXX, where XXX is the target framework. E.g. TFV_451</description>
	        <summary>Defines the .NET Framework version compile time symbols Microsoft forgot: E.g. NETFX_46,  NETFX_45 .. NETFX_20</summary>
	        <releaseNotes>1st release (alpha)</releaseNotes>
	        <copyright>Copyright © 2015 Andrew O. Dennison. All Rights Released.</copyright>
	        <tags>.NET csproj vbproj version-specific compile-time-constants</tags>
	    </metadata>
	    <files>
	        <file src="build\Framework.Compilation.Symbols.targets" target="build\Framework.Compilation.Symbols.targets" />
	    </files>
	</package>

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1669
