### ISSUE TITLE
unable to upload same package again - no overwriteflag is there for push command?

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2767]
I tried to push same named package again in simple word i want to override already uploaded package as new one has some changes but there is no overwrite flag in push commnad?

I tried to delete command and then push but still getting same error as package already exist .

please guide me.

nuget push * apikey -source -overwrite http://mydemosite.azurewebsites.net

**Comment by maartenba** [comment]
Overwriting is not supported. You can push a new package version (e.g. instead of 1.0.0 push 1.0.1)
