### ISSUE TITLE
Can't upload new version of package

### ISSUE THREAD

**Issue by larsbrinkhoff** [NuGet/NuGetGallery#2768]
I'm trying to upload a new version of my Cygwin package.  I go here:
https://www.nuget.org/packages/upload
and select my package file, and click upload.

However, the upload stops at around 30%.

Here's a copy of the nupkg file:
http://lars.nocrew.org/tmp/Cygwin.2.2.1.nupkg

**Comment by maartenba** [comment]
Can you give it another go? Or use nuget.exe push?

**Comment by larsbrinkhoff** [comment]
It finally went through with nuget.exe 2.7.3 -Timeout 3601.  I tried the webpage push many times from two different locations, without success.

Is there a problem with large files?  My packages is about 80M.

**Comment by maartenba** [comment]
That could be an issue, the -Timeout is something you definitely want to specify with uploading larger packages.
