### ISSUE TITLE
Gallery: NuGet Distribution URL should return friendly content

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2773]
We should return friendly content

![dist_nuget](https://cloud.githubusercontent.com/assets/4565352/10978062/bbc74f5a-83a9-11e5-82d1-11cc51e720c5.jpg)

**Comment by maartenba** [comment]
We have a CDN rule we have to apply at some point.

**Comment by maartenba** [comment]
We now have www.nuget.org/downloads as the official URL
