### ISSUE TITLE
entry.Name bug for ZIP archives

### ISSUE THREAD

**Issue by darek-msft** [NuGet/NuGetGallery#2774]
I believe you have a bug in the following code. It should be entry.FullName, not entry.Name.
File: Gallery\src\NuGetGallery.Core\Packaging\NupkgRewriter.cs

Same problem in: Gallery\src\NuGetGallery.Core\Packaging\Nupkg.cs

```
using (var newManifestStream = new MemoryStream())
            {
                manifest.Save(newManifestStream);
                using (var archive = new ZipArchive(readWriteStream, ZipArchiveMode.Update, leaveOpen: true))
                {
                    var manifestEntry = archive.Entries.SingleOrDefault(entry =>
                            entry.Name.IndexOf("/", StringComparison.OrdinalIgnoreCase) == -1
                            && entry.Name.EndsWith(".nuspec", StringComparison.OrdinalIgnoreCase)
                        );

                    using (var manifestOutputStream = manifestEntry.Open())
                    {
                        manifestOutputStream.SetLength(0);
                        newManifestStream.Position = 0;
                        newManifestStream.CopyTo(manifestOutputStream);
                    }
                }
            }
```

**Comment by maartenba** [comment]
We just want to check the file name (no need for full name here).

**Comment by darek-msft** [comment]
You have this line
entry.Name.IndexOf("/", StringComparison.OrdinalIgnoreCase) == -1
to ensure that you only look for .nuspec files in the top level directory.

But Name is only the file name with no full path. So this check will never be true and so if you have a nuspec file in a subfolder, it will fail due to multiple entries in SingleOrDefault().

**Comment by maartenba** [comment]
Right, got it. Let's get that fixed. `Nupkg` already has that fixed in `dev`.
