### ISSUE TITLE
user not getting invite email

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#2778]
I have added @alexeysuvorov as an owner to https://www.nuget.org/packages/MethodDecorator.Fody

but he has never got the email invite and cannot see the option to accept

**Comment by maartenba** [comment]
Have just resent the invite. If not available have @alexeysuvorov check https://www.nuget.org/packages/MethodDecorator.Fody/ManagePackageOwners and see if he's listed there
