### ISSUE TITLE
Grey on grey is hard to read

### ISSUE THREAD

**Issue by MikeyBurkman** [NuGet/NuGetGallery#2779]
The right hand navigation on the home page has lots of links, but the font colors are one shade of light grey on a background that's just a slightly lighter shade of grey. The lack of contract makes the links look disabled, and more importantly, they're difficult to read. (And I have decent eyesight.) Can we please make the font color for the navigation a bit darker?

**Comment by maartenba** [comment]
Which site are you referring to here?

**Comment by MikeyBurkman** [comment]
Ack, I'm sorry. This the documentation site for NuGet. http://docs.nuget.org/

**Comment by maartenba** [comment]
Would making it black be better?

/cc @yishaigalatzer @csharpfritz @joyhui @xavierdecoster

**Comment by MikeyBurkman** [comment]
Just really anything a few shades darker. Contrast is important, as is making it not look like a disabled link.

**Comment by maartenba** [comment]
@csharpfritz okay if we make it a bit darker?

Before:
![before](https://cloud.githubusercontent.com/assets/485230/11271017/a53af38e-8ec3-11e5-92b3-96c2e5919abb.png)

After:
![after](https://cloud.githubusercontent.com/assets/485230/11271022/abdf05f4-8ec3-11e5-8265-1b8f56788499.png)

**Comment by 304NotModified** [comment]
Also much better IMO.

**Comment by maartenba** [comment]
@csharpfritz @yishaigalatzer okay if we make it a bit darker? Seems like a good change?

**Comment by csharpfritz** [comment]
Yea.. I think that makes sense.  Isn't there a minimum contrast that we are supposed to support?

**Comment by yishaigalatzer** [comment]
There is. Need to ask our accessibility experts

**Comment by 304NotModified** [comment]
I'm curious how do you measure the minimal contrast.

**Comment by maartenba** [comment]
@csharpfritz @yishaigalatzer who to ask?

**Comment by maartenba** [comment]
Spoke with our designers, and `#515151` is the color to go with.

**Comment by 304NotModified** [comment]
Is that the current? Or in the mockup?

**Comment by maartenba** [comment]
The new color should be `#515151`- the one in the mockup is still too light. Note that this change also should be made to blog, docs, status page.

**Comment by xavierdecoster** [comment]
Changed to `#515151` on Docs side-nav, and on Blog archive page. Did not spot any issues on status page or dist.nuget.org/index.html, but let us know if you do. Thanks for reporting the issue!
