### ISSUE TITLE
Improve handling of Bad Request to external search service due to invalid query

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2781]
The following example request (a search for `"json` on the packages page) throws an HTTP 500 in the gallery: 
[`GET https://www.nuget.org/packages?q=%22json`](https://www.nuget.org/packages?q=%22json)

Under the hood, a call to external search service returns HTTP 400 Bad Request: 
[`GET https://nuget-prod-0-v2searchwebsite.azurewebsites.net/search/query?q=%22json&skip=0&take=20&sortBy=relevance&prerelease=true&luceneQuery=false`](https://nuget-prod-0-v2searchwebsite.azurewebsites.net/search/query?q=%22json&skip=0&take=20&sortBy=relevance&prerelease=true&luceneQuery=false)

The gallery throws because of the call to `HttpResponse.EnsureSuccessStatusCode()` [here](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs#L149) which is left unhandled.

**Comment by xavierdecoster** [comment]
@yishaigalatzer @csharpfritz What would be the preferred way to handle in this in the Gallery in terms of UX?

**Comment by yishaigalatzer** [comment]
Write a message that says the query was invalid (even nicer would be to get a proper user friendly error from search) and print out a sample search syntax

**Comment by maartenba** [comment]
Looks like #2745 which is being fixed /cc @joyhui

**Comment by yishaigalatzer** [comment]
Very much related but not the same. Gallery shouldn't 500 regardless of what search does

**Comment by xavierdecoster** [comment]
Ideally, the search service echos back the original query and the actually executed (perhaps auto-corrected) query.
It should also inform the client (a simple flag may do) whether the original query is a well-formed query or not.
This way, any client can determine if the results provided by the search query match the requested or an interpreted query, and it's up to the client to define client behavior around this.

There are numerous examples out there that seem to be following this pattern. 
Consider the following typo in the search term, and the way the client behaves, in the event the original query is well-formed, but interpreted:
![image](https://cloud.githubusercontent.com/assets/880728/11361916/cd1c23c0-9290-11e5-9c4b-5f48993a1360.png)

If the original query is not well-formed, the search service may choose to return 0 results and flag the original query is not well-formed.
Adding a link to the [search syntax documentation](http://docs.nuget.org/Consume/Search-Syntax) is a no-brainer, but the client needs a way to know when to display it.

Also, the user may need to be informed about the fact that the search service *corrected/interpreted* the search request.
The above approach seems to satisfy both needs, and leaves it entirely up to the search service when or when not to interpret the query or just reply it couldn't handle the query.

Of course, if connectiion failures or service failures happen and the client gets anything else but an HTTP 200, the client should still properly handle it.

**Comment by maartenba** [comment]
@xavierdecoster This one's fixed, right? (the 500, not the "spell check")

**Comment by xavierdecoster** [comment]
Yep, the 500 is fixed.
