### ISSUE TITLE
Webmatrix 2.8.1 Update?

### ISSUE THREAD

**Issue by herbertmilhomme** [NuGet/NuGetGallery#2782]
# Webmatrix: "An error occurred.

The 'Microsoft.Net.Http 2.2.29' package requires NuGet client version '2.8.1' or above, but the current NuGet version is '2.6.50319.301'.

NuGet.NuGetVersionNotSatisfiedException: The 'Microsoft.Net.Http 2.2.29' package requires NuGet client version '2.8.1' or above, but the current NuGet version is '2.6.50319.301'."
## NuGet 2.8.1 Release Notes:

"NuGet 2.8.1 was released on April 2, 2014.
Update of the NuGet WebMatrix Extension
This release updates the NuGet client found in WebMatrix to NuGet.Core 2.6.1 and brings with it features such as XDT transformations. More importantly, the 2.6.1 core update enables the WebMatrix client to install NuGet packages which contain more recent versions of the nuspec schema, which includes the ASP.NET NuGet packages.

For more information about the WebMatrix Extension update, see those specific release notes."
## NuGet.Core 2.6.1 Download Page:

"NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon.

The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore."

What a terrible experience. To be caught in a loop, and forced with no alternatives, or escape. You're practically forced to use NuGet, and there are no resources or instructions on how to perform the given task without it.
## NuGet How-To Page:

"How to download a package?
The short answer is don't, at least not manually. NuGet provides a faster better way to incorporate a library into your project."

How can i do anything when i'm stuck at a wall, and there are no resources available to something i know very little about. Any solutions, guides, assistance, or something? If a suggestion to switch tools and move to VisualStudio. Then that isn't much of an answer, nor is it of any help to the current problem and issue. I don't think learning and mastering a new tool should be necessary when one made for someone of my skill level is adequate enough. I just need to install a package. Nothing more, nothing else.

**Comment by imarkphillips** [comment]
same issue

**Comment by skofman1** [comment]
@xavierdecoster, can we close this?

**Comment by xavierdecoster** [comment]
Looks like an old issue we can close, as WebMatrix EOL has been announced, and the gallery retired: https://blogs.iis.net/webmatrix/webmatrix-product-support-ends-on-november-1st-2017
