### ISSUE TITLE
V3+V2 restore fails when server responds to FindPackagesById() with 204-No content

### ISSUE THREAD

**Issue by jesperll** [NuGet/NuGetGallery#2784]
I have a Visual Studio 2015 windows 10 app project with references to packages from both nuget.org(V3) and a local TeamCity server(V2). 
During package restore TeamServer is queried for all packages and responds 204 No content to the ones it doesn't know. This causes restore to fail.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1759
