### ISSUE TITLE
Test "CreatesNewCatalogFromCreatedAndEditedPackages" in NuGet.Services.Metadata repo fails

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#2785]
The root cause is the `DateTime.MinValue.ToUniversalTime().ToString("O")` has different results depending on the the host machine time zone.

In Pacific Standard Time, the result is: `0001-01-01T08:00:00.0000000Z`.
Expected: `0001-01-01T00:00:00.0000000Z`

Notice the hour place is off by eight hours.

`DateTime.MinValue` is `DateTimeKind.Unspecified` to `.ToUniversalTime()` [assumes `DateTimeKind.Local`](https://msdn.microsoft.com/en-us/library/system.datetime.touniversaltime(v=vs.110).aspx). Presumably this test has passed before because the build machine runs in UTC.

To fix this test failure, only one line is needed to be fixed. However, there are a lot of places where `DateTime.MinValue` is used in the project so it is hard to tell if there are more similar bugs. My proposal is to fix the one line now, and file a bug to investigate all of the other places after our functional test coverage has improved.

**Comment by maartenba** [comment]
Sounds good to me

**Comment by joelverhagen** [comment]
Fixed #2785
