### ISSUE TITLE
My packages are not showing the total downloads correctly?

### ISSUE THREAD

**Issue by netdragoon** [NuGet/NuGetGallery#2793]
I have two packages that are in trouble, they sometime appears the total number of downloads to zero, but there are already downloads for them , what is happening ?

Packages:

- https://www.nuget.org/packages/Canducci.MongoDB.Repository4.0/
- https://www.nuget.org/packages/Canducci.MongoDB.Repository4.5/

![example](https://cloud.githubusercontent.com/assets/15145509/11440932/0eef7eb4-94ee-11e5-8582-af566b09b1aa.png)

**Comment by maartenba** [comment]
Seems our package ID parser missed the "4.0" and "4.5" in the package id. We're correcting the issue so that the package ID is recognized correctly.

In the meanwhile, the package details contains the correct number.

**Comment by netdragoon** [comment]
And my observations , I realized that the count is falling in version 1.0.0 instead of falling on the version that was actually chosen 2.0.0 .

![1fato](https://cloud.githubusercontent.com/assets/15145509/11471330/c5e4dc9a-974b-11e5-9434-3bb95303431a.png)


I'm waiting for a solution proposed by you and I thank everyone for their efforts .

**Comment by maartenba** [comment]
Still updating, will post here when done.

**Comment by netdragoon** [comment]
Thank you for the great commitment .

**Comment by maartenba** [comment]
Stats have been updated.

**Comment by netdragoon** [comment]
Thank You...
