### ISSUE TITLE
Make the .zip download link an actual .zip

### ISSUE THREAD

**Issue by NickCraver** [NuGet/NuGetGallery#2794]
I'm not sure of all the use cases, but my main one for manually downloading a package is to open it and take a look, not to deploy locally for use somewhere (that's what the feed is for, IMO). A frustrating piece is the inaccurate download link:

<img width="740" alt="screen shot 2015-11-27 at 11 19 18 am" src="https://cloud.githubusercontent.com/assets/454813/11445258/c0ffbb46-94f8-11e5-8b1f-0734e7c5f54f.png">

See that download link?

> Or [Download Dapper-1.50.0-beta4.zip](https://www.nuget.org/api/v2/package/Dapper/1.50.0-beta4)

It doesn't download a .zip, it downloads a .nupkg, which isn't hooked up to tooling for most people. Can we actually make it a .zip? If there's some compelling reason *not* to, the link text should at least be fixed.

**Comment by johandanforth** [comment]
+1

**Comment by rstarkov** [comment]
Is that link added by an extension? I don't think NuGet has these download links at all (which is in itself a frustrating aspect of NuGet)

**Comment by NickCraver** [comment]
Well....crap. I honestly don't remember installing this extension over a year ago: [NuTake](https://chrome.google.com/webstore/detail/nutake/ibhhbcaipjilldjkhhblhgdedjgoecap/reviews). Thanks for the sanity check @rstarkov.

I'll close this out and open an issue to get these links added to the page itself, this should be a feature of nuget.org without an extension.

**Comment by akoeplinger** [comment]
@NickCraver there is already a link in the sidebar if you're logged in to nuget.org

**Comment by NickCraver** [comment]
@akoeplinger it's there regardless now (I think it was logged-in-only at some point), but I had grown accustomed to the other spot - closed this because I agree, this is taken care of in a way I was blind to, my fault.
