### ISSUE TITLE
404 : Page Not Found when creating new account on nuget.org

### ISSUE THREAD

**Issue by caioproiete** [NuGet/NuGetGallery#2795]
(apologies if this is not the right place to open this issue)

Hello,

I've created a new account on nuget.org and got a 404. The account got created as expected, though.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/177608/11448013/9deb0f9c-9526-11e5-84e2-37dba93684d9.png)

**Comment by maartenba** [comment]
It is the right place :-) Registration succeeded, so you can upload your packages.
We will look into the issue.

**Comment by maartenba** [comment]
Seems lots of sites are linking to `/users/account/register`. Adding the route and making sure we redirect properly. Will go live with next deployment.

**Comment by maartenba** [comment]
Deployed.

**Comment by caioproiete** [comment]
Awesome!
