### ISSUE TITLE
Leading 0 in Package Revision Number Fails to Restore in VSTS

### ISSUE THREAD

**Issue by joshlrogers** [NuGet/NuGetGallery#2797]
Starting today (12/1/2015) we are unable to restore packages during a build in VSTS that have a leading 0 in the revision number of the version.  Currently our private Nuget Packages are packaged and deployed in VSTS and have versions like 1.0.151201.01.  Starting today, we're assuming due to the recent release of the VS Update 1, it is stripping off the leading 0 of the revision number when trying to restore and thus not finding a package that maps. So for the example given it is trying to restore a package with the version 1.0.151201.1 rather than .01 and since this version doesn't exist it is failing the builds.

Our packages.config file do have the .01 in the version attribute
&lt;package id="mhd.ExternalMessaging.Contract" version="1.0.15334.05" targetFramework="net45" /&gt;

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1800
