### ISSUE TITLE
[Azure Search] Functional test V3 search at deployment time

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#2798]
- [x] Add functional tests that exercise the protocol
  - [x] V3 Search
    - [x] Paging (skip + take)
    - [x] Prerelease true/false
    - [x] semVerLevel
    - [x] All query fields

**Comment by maartenba** [comment]
@joelverhagen Can you remember which items were tackled and which not?

**Comment by skofman1** [comment]
@shishirx34 , you implemented some functional tests. Anything we can check off?

**Comment by shishirx34** [comment]
Ticked the last one, apart from that I don't think our integration tests verify anything new.

**Comment by joelverhagen** [comment]
Split out auto-complete functional tests: https://github.com/NuGet/NuGetGallery/issues/7232
Split out V2 search functional tests: https://github.com/NuGet/NuGetGallery/issues/7233

**Comment by skofman1** [comment]
@joelverhagen , can we close this one?

**Comment by joelverhagen** [comment]
@skofman1, we still need functional tests on the V3 search endpoint (`/query`) and I left this one to cover it.
