### ISSUE TITLE
Protocol documentation for NuGet v3 is missing

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2801]
from @niklaslundberg

I cannot find any documentation anywhere for the NuGet v3 protocol. I want to learn about endpoints that are known by both the server and the client, their purpose, their paths, HTTP methods, HTTP headers, query string parameters and so on. I can read the source code of course but then it's an implementation rather than a specification.

**Comment by aL3891** [comment]
i'm also interested in this :+1:

**Comment by SebastianLang** [comment]
+1

**Comment by jamesqo** [comment]
Would also like to see this, I'm interested in building a NuGet v3 library in a non-.NET language. ATM all a Google search turns up is [some design notes from 3 years ago](https://github.com/NuGet/NuGetGallery/wiki/API-v3-Specification).

**Comment by skofman1** [comment]
We created a new issue to track this: https://github.com/NuGet/NuGetGallery/issues/4103
