### ISSUE TITLE
Make command box more friendly

### ISSUE THREAD

**Issue by benwa** [NuGet/NuGetGallery#2803]
By changing the output to read more like

```html
<style>
.nuget-badge code::before {
    content: "PM> ";
}
</style>
<code>Install-Package adk-platform-tools</code>
```

We can get text selection that is nicer for copy & paste (even though users really shouldn't copy & paste into a terminal).
![before](https://cloud.githubusercontent.com/assets/1351571/11716412/b1dba598-9f17-11e5-9440-68ce5bec834f.PNG)
![after](https://cloud.githubusercontent.com/assets/1351571/11716413/b44c86a8-9f17-11e5-9e48-fee3e75a6465.PNG)

**Comment by maartenba** [comment]
Good one! Will go live with our next deployment.

**Comment by maartenba** [comment]
Deployed.
