### ISSUE TITLE
Tobii confirmation email not showing up (nor in spam), 404 on logout

### ISSUE THREAD

**Issue by JSalazar88** [NuGet/NuGetGallery#2804]
- No matter how many times I send the confirmation email, it does not show up in my webmail or outlook tobii acct (jsar@tobii.com)
- Sending a gmail to jsar@tobii.com works perfectly fine, so it's not the webmail's fault
- When logging out/in, I get a 404 page

**Comment by maartenba** [comment]
I've confirmed your email address manually, you can now use NuGet.org completely. A password reset email has been sent as well.

Please use support email in the future for this type of requests.
