### ISSUE TITLE
Prerelease version sorting incorrect when number of digits in label varies

### ISSUE THREAD

**Issue by martincostello** [NuGet/NuGetGallery#2806]
I've recently published a [new package](https://www.nuget.org/packages/MartinCostello.BrowserStack.Automate) to the NuGet gallery. I haven't reached v1.0.0 yet, and am publishing pre-release versions.

The first version published was ```1.0.0-beta5``` and the second was ```1.0.0-beta10```.

However, NuGet is treating ```beta5``` as a later version that ```beta10```, presumably because it's using some sort of lexical sort instead of a numerical sort.

It would be better if NuGet would consider numeric parts of prerelease labels as numbers so that they sort logically when the number of digits varies.

Otherwise the only way to get the correct behaviour would appear to pad the numbers with zeroes.

**Comment by maartenba** [comment]
There is nothing we can do here right now as this would mean breaking backward compatibility. The padding is required with the implementation of NuGet's versioning scheme.
