### ISSUE TITLE
Page referenced in http://docs.nuget.org/consume/NuGet-Config-Settings does not exist.

### ISSUE THREAD

**Issue by gituser227** [NuGet/NuGetGallery#2808]
The documentation page at http://docs.nuget.org/consume/NuGet-Config-Settings includes a link to http://docs.nuget.org/consume/..%5CWorkflows%5CUsing-NuGet-without-committing-packages, but that page does not exist.  The broken link on http://docs.nuget.org/consume/NuGet-Config-Settings is found in the Description for the "Source control integration" setting.

**Comment by maartenba** [comment]
Fixed.
