### ISSUE TITLE
The gallery should have a link to nuget feed urls

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2809]
When I got to a NuGet gallery based site, I should be able to know what is the download url to use. Look at what myget does for this :)

For example, as a user I have to guess what is the feed address for https://staging.nuget.org/

**Comment by maartenba** [comment]
Where would you like to see this? E.g. what would be a nice place to put this URL in the UI?

/cc @joyhui

**Comment by robertmuehsig** [comment]
You could put it in the footer. I think most people are just using the official one and don't bother which feed url their NuGet client uses. So the footer might be a good enough place, e.g.
![image](https://cloud.githubusercontent.com/assets/756703/12074643/23a0e770-b15f-11e5-9080-b7df9db09799.png)

**Comment by csharpfritz** [comment]
Can we add another section of text in the center above "Latest NuGet
Releases" using the same header text saying: "Use this NuGet Repository"
with text underneath pointing to the URLs for that repository?



Jeff

**Comment by maartenba** [comment]
Something like this?

![feeds](https://cloud.githubusercontent.com/assets/485230/12109238/78713b4c-b380-11e5-8f1c-f80b7bf7d7d7.png)

**Comment by csharpfritz** [comment]
Do you think we should end this new section with a link to the
configuration of package sources?  Perhaps this location:
http://docs.nuget.org/consume/package-manager-dialog#package-sources



Jeff

**Comment by maartenba** [comment]
Makes total sense! Want to draft the complete section?

**Comment by csharpfritz** [comment]
NuGet Feed Locations
NuGet delivers packages to your project from a feed URL that provides
interactions with the repository for your NuGet client.  For
NuGet.org, configure
your NuGet clients
<http://docs.nuget.org/consume/package-manager-dialog#package-sources> to
use one of the following repository URLs:

NuGet feed v3 (VS 2015 / NuGet v3.x)
<url>

NuGet feed v2 (VS 2013 and earlier / NuGet 2.x)
<url>



Jeff

**Comment by maartenba** [comment]
Linked PR. https://github.com/NuGet/NuGetGallery/pull/2847

**Comment by csharpfritz** [comment]
Looks good to me... :shipit:

**Comment by maartenba** [comment]
Deployed. May be a few minutes before it shows on www.nuget.org.
