### ISSUE TITLE
Looks like package statistics is showing wrong figures

### ISSUE THREAD

**Issue by jordimontana82** [NuGet/NuGetGallery#2811]
Hi,

I have 3 different packages in nuget:

FakeXrmEasy
FakeXrmEasy.2013
FakeXrmEasy.2015

Package statistics are 0 for the .2013 and .2015 packages, however, if I look at the statistics for package FakeXrmEasy below, it looks like it's mixing different packages into the one?

https://www.nuget.org/stats/packages/FakeXrmEasy?groupby=Version

**Comment by maartenba** [comment]
@jordimontana82 We've updated the package mapping in our datawarehouse (the 2013 / 2015 was incorrectly recognized as a version number - using something like `.VS2013` would solve this). It will take up to 24 hours before the correct numbers will show in the statistics.

**Comment by jordimontana82** [comment]
Great @maartenba !

Thanks for the supper fast reply :+1:
