### ISSUE TITLE
NuGet is not available in Belarus

### ISSUE THREAD

**Issue by drweb86** [NuGet/NuGetGallery#2818]
Both https://dist.nuget.org/index.html and nuget services are not available in my country. And i can open them from anonymizers

Could you please provide workaround steps

**Comment by maartenba** [comment]
@joyhui can you check with the CDN folks?

**Comment by drweb86** [comment]
# Tracert shows
C:\Users\drweb86>tracert dist.nuget.org
Трассировка маршрута к cs1.wpc.v0cdn.net [68.232.34.200]
с максимальным числом прыжков 30:
  1  Общий сбой.
Трассировка завершена.
# "My" IP
46.216.47.147. 
# ISP
BelTeleCom (it is known for massive NAT usage for its clients due to lack of ips)

**Comment by maartenba** [comment]
@joyhui can you check with the CDN folks?

**Comment by drweb86** [comment]
Hi guys,

As i see neigher dist.nuget.org nor its services are not available yet...
Probably i will be adding note to code about downloading libraries and all staff and putting them to some folder because commiting all that 200 mb binaries staff is not great.

**Comment by maartenba** [comment]
@drweb86 Any luck so far on reaching our services?

**Comment by drweb86** [comment]
Hi

The issue is still there. Anyway i found another workaround - to use a http://www.vpngate.net/en/ to access site from other one. 

Despite the frustration nuget is abandoning my ISP i understand efforts to prevent dos attacks, i even did one day similar thing on a forum to prevent spammers from china...

**Comment by maartenba** [comment]
We are definitely not intentionally blocking. Can you contact us on support at nuget org so we can work with you to see where the issue lies?

**Comment by drweb86** [comment]
Hi

I just sent letter there.

**Comment by joyhui** [comment]
Please include MTR trace too.

Guideline is here:
https://docs.nuget.org/consume/nuget-faq
capture MTR

**Comment by drweb86** [comment]
Hello

 

See logs below.

 

dist.nuget.org

 

|------------------------------------------------------------------------------------------|

|                                      WinMTR statistics                                   |

|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |

|------------------------------------------------|------|------|------|------|------|------|

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4385 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4384 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 4383 |    0 |    0 |    0 |    0 |    0 |

|________________________________________________|______|______|______|______|______|______|

   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

 

api.nuget.org

 

|------------------------------------------------------------------------------------------|

|                                      WinMTR statistics                                   |

|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |

|------------------------------------------------|------|------|------|------|------|------|

|                   No response from host -  100 | 3959 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3959 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3958 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|                   No response from host -  100 | 3957 |    0 |    0 |    0 |    0 |    0 |

|________________________________________________|______|______|______|______|______|______|

   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

 

tracert dist.nuget.org

 

Tracing route to cs1.wpc.v0cdn.net [68.232.34.200]

1         General failure.

 

For comparison

Tracert works fine with other sites.

MTR works fine with other sites.

 

Thanks.

**Comment by joyhui** [comment]
I created a ticket for Azure CDN service. They will do investigation and get back to us soon.

**Comment by maartenba** [comment]
Have they gotten back?

**Comment by drweb86** [comment]
Hi

I saw no response letters. Last letter was about contacting cloud service a month ago or something like that.

Dist.nuget.org is still unavailable for direct access, however it is available through anonymous vpn services.

**Comment by drweb86** [comment]
Sorry for bumping this up, but will it be possible to work with nuget this year?

**Comment by maartenba** [comment]
@drweb86 No worries, seems this slipped through the mazes :( Apologies for that!

The `General failure` from https://github.com/NuGet/NuGetGallery/issues/2818#issuecomment-165094276 is a bit strange. It looks like your PC may be blocking things or your local network is blocking things. However other tracerts work so let's see...

Are you seeing this on one network (e.g. work) or also on other networks (e.g. home)? Is there a firewall/proxy in your network?

We'd like to get some recent traces if possible. Can you provide us with a new:
* MTR + tracert towards api.nuget.org
* MTR + tracert towards www.nuget.org
* MTR + tracert towards www.microsoft.com

Feel free to send these over to support at NuGet dot org.

**Comment by drweb86** [comment]
@maartenba, i'm sorry.
I found the problem. It was windows firewall. It blocks nuget org for some reason while other "Microsoft and .Net" staff is available. So i will be reviewing its rules.

Actually i never thought that it will, but! No words. Thanks again. Now all works fine.

**Comment by maartenba** [comment]
No worries, happy to hear this is resolved.
