### ISSUE TITLE
NuGet.Server - Add symbols support

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2825]
Support symbols packages and make it a symbol server that can be used with VS.

**Comment by npodbielski** [comment]
So it is still open? Despite in example this [link](http://thinkbeforecoding.com/post/2012/02/26/NuRep-your-local-NuGetsymbolssource-repository) it is impossible to do with Nuget.Server?

**Comment by cristinamanum** [comment]
This was [done](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg). Closing.
