### ISSUE TITLE
NuGet 3.3 under VS2015 removes References XML from proj files

### ISSUE THREAD

**Issue by lukepuplett** [NuGet/NuGetGallery#2826]
Cross-posted with SO.

http://stackoverflow.com/questions/34400276/nuget-references-vs2015-and-vs2013-compatibility

Reinstalling packages removes the `<Reference ...>` XML elements from the .csproj files, but the references are visible as nodes in the Solution Explorer pane.

I'm not sure if this is intended behaviour. My colleagues think not, and indeed they have also ran `Update-Package ... -Reinstall` without seeing this behaviour, yet I think its just how it works nowadays. However, if it is how it works, will it break the project for 2013 users?

Maybe something is configured differently on my machine, maybe its not supposed to happen, in any case I have not checked in the changes and have gone back to VS 2013 for now.

Luke

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1866
