### ISSUE TITLE
Changes in dependency handling breaks nuget.exe v2 update

### ISSUE THREAD

**Issue by BeeWarloc** [NuGet/NuGetGallery#2827]
Hello, I'm the maintainer of the package "Pomona" on nuget.org.

I recently created created a new release, which is presented different than the previous versions:

https://www.nuget.org/packages/Pomona/0.27.0 (new)
https://www.nuget.org/packages/Pomona/0.26.2 (old)

The dependencies of the new package is part of the "Any 0.0" group, while the previous package does not have a dependency group.

The breaking problem appears when using nuget.exe 2.8.6 to upgrade this package, as it now removes all dependencies. Using nuget.exe 3, or upgrading in VS 2015 works as expected. Upgrading with nuget 2.8.6 using a local folder as source also works ok.

The packages have been built using nuget.exe 2.8.6 pack command, and the nuspec has not changed between versions.

Looking through recent commits I suspect https://github.com/NuGet/NuGetGallery/commit/60ce88812b1f335ce809294ad0d20bad9eddb536 might be related.

Hope this is useful, it could possibly affect other more widely used packages :cake:

**Comment by BeeWarloc** [comment]
This is the nuspec used:

https://github.com/okb/Pomona/blob/develop/app/Pomona/Pomona.nuspec

**Comment by BeeWarloc** [comment]
After a bit more investigation nuget3 update on solution does not work exactly as expected, as there seems to be another (possibly) unrelated change in behaviour.

https://github.com/NuGet/NuGetGallery/issues/2828

**Comment by BeeWarloc** [comment]
Thanks for the quick feedback.

As the v2 client has not changed recently I think it's safe to assume that the server has changed behavior?

**Comment by maartenba** [comment]
@BeeWarloc I did a manual correction on your package to test the above assumption in https://github.com/NuGet/NuGetGallery/issues/2827#issuecomment-166589627 - can you try the upgrade using 2.8.6 again and see if this odd behaviour is still there?

**Comment by fubar-coder** [comment]
I can confirm that this changes are fixing the problem that the dependencies could not be found in VS 2015 SP1.

**Comment by maartenba** [comment]
Awesome, thanks!

**Comment by maartenba** [comment]
Issue has been resolved. Thanks for helping out, @fubar-coder and @BeeWarloc !

**Comment by BeeWarloc** [comment]
Thanks, that's great!
