### ISSUE TITLE
Add functional tests for bad packages reaching the V3 jobs

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#2830]
In response to #2822.

In general, a bad nupkg (corrupted ZIP, bad nuspec, unexpected target framework, etc) should not interrupt the jobs. Ideally this is validated on upload so bad nupkgs don't make it into the system, but each component that cracks open the nupkg should be resilient to problems.

Functional tests should be added to feed2catalog and catalog2dnx that pass in bad nupkgs.
Functional tests should be added to catalog2registration and catalog2lucene that pass in bad target frameworks (as these values are derived from nupkg folder structure).

If a bad package is encountered, a visible signal should be raised. Maybe in the form of a Sev 2/3?

**Comment by maartenba** [comment]
Ideally job should continue running as well, not just crash out.

**Comment by csharpfritz** [comment]
We should consider moving a bad package to a dead-letter queue and sending a notification with a descriptive error message to the package owner and on-call support.  This way, processing can continue and the package owner could resubmit a fix

**Comment by skofman1** [comment]
@joelverhagen , still relevant?

**Comment by joelverhagen** [comment]
It's been open for a year and a half with no action. We should re-open this when a specific bug arises.
