### ISSUE TITLE
DevelopmentDependency is missing from Package

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#2836]
I tried to move most of the "features" from this closed PR https://github.com/NuGet/NuGetGallery/pull/2242 to new PRs and I already noticed that the developmentDependency is missing as an actual property on the PackageMetadata. @maartenba already said that this is currently on your radar (https://github.com/NuGet/NuGetGallery/pull/2834#issuecomment-167067726), which is fine, because on the VerifyPackageUpload page I can at least access the data via the NuSpecReader.

On the package detail page it seems I can't access the NuSpec directly and there is no DevelopmentDependency property - not even as read only property.

When I did the original PR I could do something like this:
https://github.com/robertmuehsig/NuGetGallery/commit/1ad1f4630726055734a0a592326faef1ab851809

It's not super important IMHO, but I wanted to log it somewhere.

This would also resolve this issue:
https://github.com/NuGet/NuGetGallery/issues/1874

**Comment by skofman1** [comment]
Per the work done in https://github.com/NuGet/NuGetGallery/issues/5666  we are now populate DevelopmentDependency in the DB, and it's already exposed on Package details page. If you think there are other places where this data should be exposed feel free to reopen this issue/ create a new one.

**Comment by robertmuehsig** [comment]
Just a couple of hours ago I updated my fork and discovered this - nice work!
