### ISSUE TITLE
registered new user successfully but getting error while uploading package API key is invalid

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2838]
Registered new user successfully but getting error while uploading package API key is invalid.

If I upload package from UI working perfectly fine. with the first registered user also it is working great,
but getting following error when create new user and use its API key.

Failed to process request. 'The specified API key is invalid or does not have permission to access the specified package.'.
The remote server returned an error: (403) Forbidden..

command is also correct works for first registered user
"nuget push *.nupkg NEWAPIKEY  -source http://mydemo-website.azurewebsites.net/"

Also checked tables Roles , UserRoles they are empty.

**Comment by maartenba** [comment]
Try:

"nuget push *.nupkg NEWAPIKEY -source http://mydemo-website.azurewebsites.net/api/v2/package"

**Comment by ashuthinks** [comment]
cool thanks :)
