### ISSUE TITLE
Reference group @id is sometimes a broken link in the catalog

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#2840]
For example, in the catalog entry for [LibGit2Sharp 0.21.0.176](https://api.nuget.org/v3/catalog0/data/2015.02.07.20.09.32/libgit2sharp.0.21.0.176.json), the link at `entry["references"]["group"]["@id"]` is broken.

The value is:
`https://api.nuget.org/v3/catalog0/data/2015.02.07.20.09.32/.json#gpref`

I think it should be:
`https://api.nuget.org/v3/catalog0/data/2015.02.07.20.09.32/libgit2sharp.0.21.0.176.json#gpref`

@johnataylor, I think this is in the XSLT that builds the catalog entry.

**Comment by maartenba** [comment]
@joelverhagen @johnataylor Has this one been fixed? Doing some spring cleaning to see what's to be done and has been done :)

**Comment by joelverhagen** [comment]
Yes, seems to be fixed.
