### ISSUE TITLE
The catalog page should have a link to the package

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2856]
Suggestion:

When we upload a package to the gallery we first drop it in the "flatcontainer" without updating the flatcontainer index.json, so it is not yet discoverable

Then we create the catalog page, and the catalog page should have a link to the nupkg.

**Comment by maartenba** [comment]
What is the intent of this? (e.g. is the client suddenly going to start consuming the catalog?)

/cc @joyhui @johnataylor
