### ISSUE TITLE
can not load NuGetGallery project

### ISSUE THREAD

**Issue by chucklu** [NuGet/NuGetGallery#2858]
I open the solution with vs2015 enterprise,and have installed update1

i can not load NuGetGallery  project ,
the info i get is,this project is incompatible with the current edition of visual studio 2015
NuGetGallery/src/NuGetGallery/NuGetGallery.csproj

so,I already have the latest version of vs,why I can not load the project?

**Comment by robertmuehsig** [comment]
Are you on the latest version of the master or dev branch?

**Comment by chucklu** [comment]
I am on branch master
the last commit is

commit 1226789b82f92f9465df1397f62f350a483aeece
Merge: 441b80d 9d76405
Author: Maarten Balliauw <maarten@balliauw.be>
Date:   Tue Jan 5 19:39:48 2016 +0100

    Merge pull request #2847 from NuGet/maballia-feedurls

    The gallery should have a link to nuget feed urls #2809

**Comment by maartenba** [comment]
That should loud just fine. Can you try the develop branch + follow the steps in README?
https://github.com/NuGet/NuGetGallery

**Comment by chucklu** [comment]
I'm not sure,I installed the nuget by the visual studio
https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d
I will try download this

**Comment by chucklu** [comment]
I have checked ,i alredy installed the NuGet
![image](https://cloud.githubusercontent.com/assets/3004057/12288153/9b088042-ba0c-11e5-8114-acc163012040.png)

**Comment by maartenba** [comment]
Off to the next step then :)

**Comment by chucklu** [comment]
https://azure.microsoft.com/en-us/downloads/
I download from .net-->vs2015
get this SQLCE.26SQLCEVSTools_4_0.exe

I installed this ,and still can not load the NuGetGallery project

**Comment by maartenba** [comment]
Does the Visual Studio output window show any additional info on why it can't load the project?

**Comment by chucklu** [comment]
I got this,weird.
what' this?
[Failure] Could not find file 'C:\Users\Administrator\AppData\Local\Temp\299ff8a621104979b8910239d6bc3ba7_VersionInfo.cs'.
[Failure] Could not find file 'C:\Users\Administrator\AppData\Local\Temp\a92df7d17f224a9e88dd5858e54265f0_VersionInfo.cs'.
[Failure] Could not find file 'C:\Users\Administrator\AppData\Local\Temp\007eec9bf5234a39923a5eaeefa470d9_VersionInfo.cs'.
[Failure] Could not find file 'C:\Users\Administrator\AppData\Local\Temp\c25ea79b7e314d5f9ea9397088311015_VersionInfo.cs'.
[Failure] Could not find file 'C:\Users\Administrator\AppData\Local\Temp\88354ebc94de496d9cbbc1d00dfc954e_VersionInfo.cs'.

**Comment by chucklu** [comment]
I also find the sln file was changed by the vs automatically
VisualStudioVersion was changed

 git diff NuGetGallery.sln
diff --git a/NuGetGallery.sln b/NuGetGallery.sln
index 26b68c3..60cd2fb 100644
--- a/NuGetGallery.sln
+++ b/NuGetGallery.sln
@@ -1,7 +1,7 @@
 <U+FEFF>
 Microsoft Visual Studio Solution File, Format Version 12.00
 # Visual Studio 14
-VisualStudioVersion = 14.0.23107.0
+VisualStudioVersion = 14.0.24720.0^M
 MinimumVisualStudioVersion = 10.0.40219.1
 Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = ".nuget", ".nuget", "{96E4A
        ProjectSection(SolutionItems) = preProject

**Comment by maartenba** [comment]
That's all unrelated. Did you run the build.cmd as described in the README before opening the solution?

**Comment by chucklu** [comment]
项目“D:\SourceCode\GitHub\NuGetGallery\packages\NuGet.Services.Build.3.0.9\tool
s\
NuGet.Services.FullBuild.msbuild”(2)正在节点 1 上生成“D:\SourceCode\GitHub\NuG
etGaller
y\NuGetGallery.sln”(3) (Build 个目标)。
D:\SourceCode\GitHub\NuGetGallery\NuGetGallery.sln(2,1): error MSB4025: 未能加载
项目文
件。根级别上的数据无效。 第 2 行，位置 1。

**Comment by maartenba** [comment]
Can you try the `develop` branch?

**Comment by chucklu** [comment]
according to the info above,the project file can not be loaded

**Comment by maartenba** [comment]
Can you try the `develop` branch?

**Comment by chucklu** [comment]
I am already switch to dev branch
$ git branch -vv
* develop fefe956 [origin/dev] Merge pull request #2853 from robertmuehsig/Foote
r-at-Bottom
  master  1226789 [origin/master] Merge pull request #2847 from NuGet/maballia-f
eedurls

$ git status
On branch develop
Your branch is up-to-date with 'origin/dev'.

**Comment by maartenba** [comment]
Ok, can you delete the older named "packages" and then retry the build.cmd?

**Comment by chucklu** [comment]
still got the same error MSB4025
try open the sln in VS2015
still the same info "this project is incompatible with the current edition of visual studio"

**Comment by chucklu** [comment]
another problem is NuGetGallery.Cloud project can not load either
the error info is "the application is not installed'

**Comment by maartenba** [comment]
That needs the Azure Tools 2.7.1 installed.

**Comment by chucklu** [comment]
I have installed the SQLCE.26SQLCEVSTools_4_0.exe from 
https://azure.microsoft.com/en-us/downloads/

**Comment by chucklu** [comment]
about the error MSB4025
I will try this 
https://therightjoin.wordpress.com/2014/07/04/msb4025-the-project-file-could-not-be-loaded-data-at-the-root-level-is-invalid-error-when-building-ssdt-project-in-teamcity/

**Comment by maartenba** [comment]
Which are only the SQL tools, you will need the Azure Tools 2.7.1 as well.

**Comment by chucklu** [comment]
https://azure.microsoft.com/en-us/downloads/
there are SDKs,Command-line tools,Migration Tools,Standalone Tools
how many tools should be installed?

**Comment by maartenba** [comment]
http://go.microsoft.com/fwlink/?linkid=616239&clcid=0x409

**Comment by chucklu** [comment]
followed this article
https://therightjoin.wordpress.com/2014/07/04/msb4025-the-project-file-could-not-be-loaded-data-at-the-root-level-is-invalid-error-when-building-ssdt-project-in-teamcity/
I got this error info,I will download the Azure Tools 2.7
D:\SourceCode\GitHub\NuGetGallery\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccp
roj(87,3): error MSB4019: 未找到导入的项目“C:\Program Files (x86)\MSBuild\Micro
soft\Vis
ualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.WindowsAzure.targets”。请确认
 <Im
port> 声明中的路径正确，且磁盘上存在该文件。

**Comment by chucklu** [comment]
I need install the web deployment first before I install Azure Tools 
Thank you very much and for your patience @maartenba 

I will try to build it ,after i install the Azure Tools

**Comment by maartenba** [comment]
Thanks, I'm guessing that is the only one missing still.

**Comment by chucklu** [comment]
ownloadManager Information: 0 : Increasing current install to 12
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '29806592'
DownloadManager Information: 0 : Number of bytes after possible decompression: '29806592'
DownloadManager Information: 0 : Moving downloaded file 'C:\Users\Administrator\AppData\Local\Temp\tmp17FC.tmp' to: C:\Users\Administrator\AppData\Local\Microsoft\Web Platform Installer\installers\AzureMobileAppsSDK_VS2015.2.0\7FED65435B174F1724963CACE614EC84504660F4\AzureMobileAppsSdkV2.0.msi
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Tools 2.7.1 for Microsoft Visual Studio 2015'. Skipping download.
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Tools 2.7.1 for Microsoft Visual Studio 2015'. Skipping download.
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure VS Tools - 2.7 for Visual Studio 2015'. Skipping download.
DownloadManager Information: 0 : Starting MSI install for msi 'C:\Users\Administrator\AppData\Local\Microsoft\Web Platform Installer\installers\AzureMobileAppsSDK_VS2015.2.0\7FED65435B174F1724963CACE614EC84504660F4\AzureMobileAppsSdkV2.0.msi', commandline: 'ACTION=INSTALL REBOOT=ReallySuppress'
DownloadManager Information: 0 : Product Microsoft Azure Tools 2.7.1 for Microsoft Visual Studio 2015 had a dependency fail. Increasing install product to 13
DownloadManager Information: 0 : Downloading file 'http://download.microsoft.com/download/D/E/B/DEB395C9-C875-47F3-96F7-55C9A8FCD869/Microsoft.Azure.HDInsightToolsForVS2015.msi' to: C:\Users\Administrator\AppData\Local\Temp\tmp3702.tmp
DownloadManager Information: 0 : Product Microsoft Azure Tools 2.7.1 for Microsoft Visual Studio 2015 had a dependency fail. Increasing install product to 14
DownloadManager Information: 0 : Product Microsoft Azure VS Tools - 2.7 for Visual Studio 2015 had a dependency fail. Increasing install product to 15
DownloadManager Information: 0 : Content-disposition header: attachment

**Comment by chucklu** [comment]
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Tools 2.7.1 for Microsoft Visual Studio 2015'. Skipping download.

whta's the Dependency ?

**Comment by chucklu** [comment]
try install again,make it

**Comment by chucklu** [comment]
another problem,
The referenced component 'Microsoft.WindowsAzure.Storage' could not be found.

**Comment by chucklu** [comment]
find the reference in NuGetGallery.Core.Facts is
 <Reference Include="Microsoft.WindowsAzure.Storage, Version=2.1.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\WindowsAzure.Storage.2.1.0.3\lib\net40\Microsoft.WindowsAzure.Storage.dll</HintPath>

I change the version to 4.3.0

**Comment by chucklu** [comment]
There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" 
                          and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". (TaskId:18)

**Comment by chucklu** [comment]
There was a conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". (TaskId:56)
2>      "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not. (TaskId:56)
2>      References which depend on "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll]. (TaskId:56)
2>          C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll (TaskId:56)
2>            Project file item includes which caused reference "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll". (TaskId:56)

**Comment by maartenba** [comment]
I'd try a fresh clone of the gallery, these errors are errors we've never seen before (also do you have .NET 4.5.2 installed?)

**Comment by chucklu** [comment]
yeah,when i installed vs2015
I think I have installed .net 4.6.1,include 4.5.2

**Comment by chucklu** [comment]
@maartenba hi，have you checked?

**Comment by maartenba** [comment]
No idea how to solve, it should work with the steps in README. Can you delete your copy and try a fresh pull from GitHub?

**Comment by chucklu** [comment]
ok,I will try anotherclone

**Comment by chucklu** [comment]
try again,reproduce the same error
```xml
<Reference Include="Microsoft.WindowsAzure.Storage, Version=2.1.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\WindowsAzure.Storage.2.1.0.3\lib\net40\Microsoft.WindowsAzure.Storage.dll</HintPath>
    </Reference>
```
actually,there is only WindowsAzure.Storage.4.3.0 under packages

**Comment by chucklu** [comment]
still have the error info

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	NuGetGallery.Operations	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1819	


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The project 'NuGetGallery' targets .NET Framework 4.5.2. To make sure that the role starts, this version of the .NET Framework must be installed on the virtual machine for this role. You can use a startup task to install the required version, if it is not already installed as part of the Microsoft Azure guest OS. For more details, see http://go.microsoft.com/fwlink/?LinkId=309796.	NuGetGallery.Cloud	NuGetGallery	1

**Comment by maartenba** [comment]
Can you try updating that reference? Or disable the NuGetGallery.Operations project as its not immediately needed?

**Comment by chucklu** [comment]
yeah,I replace the reference to the correct one

still have reference conflicts like I paste above
