### ISSUE TITLE
Download time for .NET Core runtimes & packages

### ISSUE THREAD

**Issue by jamesgibbs100** [NuGet/NuGetGallery#2864]
I'm experiencing a very slow download of runtimes and packages. Is there anything you are aware of at your end that would be effecting this.

Based in London

James

**Comment by maartenba** [comment]
@jamesgibbs100 If this is still happening, can you send us an MTR trace via NuGet support? (described on https://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org)
