### ISSUE TITLE
Sorted by recent installs

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#2865]
What is the logic is that NuGet uses to rank its unsearched results? I thought it was recent installs (nuget.org/packages says "Sorted by recent installs") which meant the number of `Install` hits in the last 6 weeks, but that doesn't appear to be the case.

For example [Microsoft.AspNet.WebPages](https://www.nuget.org/stats/packages/Microsoft.AspNet.WebPages?groupby=Operation) is ranked ahead of [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/stats/packages/Microsoft.AspNet.WebApi.Client?groupby=Operation) and [AutoMapper](https://www.nuget.org/stats/packages/AutoMapper?groupby=Operation) even though it has less installs.

Is this a bug, a delay in updating, or is there some different logic at work?

**Comment by maartenba** [comment]
@johnataylor

**Comment by JamesNK** [comment]
I attempted to take a look myself but there are so many layers and caching in NuGet now I have no idea where to find it.

**Comment by yishaigalatzer** [comment]
The importance of the exact order in the list is kinda negligible. I don't know that we want to spend time researching this. If there is anything of importance feel free to re-raise the issue. Otherwise I'm closing it for lack of interest to the public :)

**Comment by JamesNK** [comment]
WebGrease has half the number of installs than AutoMapper but is ranked much higher. Isn't that a bug?

**Comment by yishaigalatzer** [comment]
I'm saying the importance of the empty list is pretty much zero. I wish we never had it.

**Comment by csharpfritz** [comment]
There are other, more interesting initial lists of packages that we could explore in the future.
