### ISSUE TITLE
Search Service V2V3 Should support gzip results

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2867]
With [this](https://github.com/NuGet/NuGet.Client/pull/244) change to the client, we can now support properly gzip-ed results from the search service.

We should update the search service to minimize the payload for search results by both minifiying the json response and gzip-ing (and whatever else we can do to minimize the payload size without breaking the client).

The work is to build, test performance impact, test customer impact on gallery, V3.3 and V3.4 clients

**Comment by yishaigalatzer** [comment]
CC @joyhui @maartenba @johnataylor

**Comment by UFUKGOCMEN** [comment]
merhaba who started to made that in map box project, about istanbul to couple american city...

**Comment by maartenba** [comment]
V2V3 search is now gzipped + minified.
V2V3 registrations blobs are now minified.

What's left here?

/cc @xavierdecoster

**Comment by yishaigalatzer** [comment]
Test against 3.3 and 3.4, registration blobs are going to get further changes including gzipping

**Comment by maartenba** [comment]
I believe John has tested these. If not, please reopen.
