### ISSUE TITLE
NuGet package results order broken

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#2868]
Recreated from #2865

WebGrease is the 6th result with 3,214 installs in the last 6 weeks
AutoMapper is the 19th result with 6,209 installs
NLog is the 45th result with 6,397 installs
RestSharp is the 63rd result with 3,751 installs

When the 6th result has less installs than the 63rd result something is either broken or wrong.

**Comment by skofman1** [comment]
please reopen if this is still relevant.
