### ISSUE TITLE
Add AWS S3 support for file storage

### ISSUE THREAD

**Issue by fandango-babak** [NuGet/NuGetGallery#2871]
For users that want to deploy their private NuGet Gallery to AWS, they should be able to leverage S3 as their storage.

**Comment by maartenba** [comment]
Feel free to propose a pull request for this. We are very much tied to Azure right now and for our needs this will remain the case, but if a low impact change can add AWS support we will look into it.

**Comment by fandango-babak** [comment]
I have an S3 backed implementation of IFileStorageService working and am working on the statistics now.

**Comment by maartenba** [comment]
Sweet!

**Comment by JonCubed** [comment]
@fandango-babak how did you end up going with this? I'm looking for an option to use S3, if you need help finishing this off let me know

**Comment by fandango-babak** [comment]
We've been using it in production for months with great success. I will try to get a PR prepared as soon as I can.

**Comment by JonCubed** [comment]
@fandango-babak thanks would be very useful

**Comment by SeanFarrow** [comment]
@fandango-babak, Did you ever get a PR for this? I'm just about to deploy a private Gallery to AWS. If you need a hand with this, feel free to ask!

**Comment by fandango-babak** [comment]
I got it working in my fork but had to move on to other projects before I could prepare a PR. I’m still hoping to prepare a PR this month of next month.
Babak Naffas
Staff Engineer, Software Engineering
Fandango LLC / NBCUniversal
12200 W. Olympic Blvd. Suite 400
Los Angeles, CA  90064
E: babak.naffas@fandango.com<mailto:babak.naffas@fandango.com%0d>
T: (310) 954-0278 x274
F: (310) 954-0292

[cid:FBBC0296-0FE1-408C-AC45-24D538714EF0]

**Comment by SeanFarrow** [comment]
Any chance you could give us a pointer to your fork/specific branch?

**Comment by Texernie** [comment]
I know this is an old issue, but I'm sure many people keep looking for AWS S3 support. I know I am. I am preparing a PR for review of an implementation for this. I need to rework it following the Git workflow, but that shouldn't be too hard.
