### ISSUE TITLE
Problem with Authorised feeds

### ISSUE THREAD

**Issue by ProfessionalNihilist** [NuGet/NuGetGallery#2873]
Hello,

I'm trying to set up a private instance of the nuget gallery such that users must be authorised to view and download packages.

This scenario does not seem to be supported currently. 

Modifying the code to restrict the website was trivial, but I can't seem to get the API to behave. I have added the ``ApiAuthorize`` attribute to the ``GetPackage`` method. Attempting to install a package will cause visual studio to ask for login details, but it does not seem to be able to successfully authenticate. I added an API key for the feed to my nuget config file, but that does not seem to be working either.

Any ideas?

Thanks

**Comment by maartenba** [comment]
Visual Studio will send basic auth credentials for authorization - so you'll have to make sure the attribute(s) you are adding are supporting basic auth.

**Comment by ProfessionalNihilist** [comment]
That is useful to know. I suppose I was hoping nuget would add the API key in a header for the HTTP requests using the same mechanism it does to authorise pushing packages.

Maybe the client doesn't know to do that though? I'll do some investigation on Monday.

**Comment by maartenba** [comment]
It doesn't, basic auth is the way to go here (or integrated auth)
