### ISSUE TITLE
the issue about map work. do not try to bad work on any country"s map 

### ISSUE THREAD

**Issue by UFUKGOCMEN** [NuGet/NuGetGallery#2875]
if you are started to work on map please finish to dame work and do not put bad ugrement inside to project side...computing ugrement and all country's law include that dont forget about it...

**Comment by UFUKGOCMEN** [comment]
why am i told that stuff please go www.mapbox.com open id and look about it,thank you have a grate day

**Comment by blowdart** [comment]
Awww. Bot spam. Locked.
