### ISSUE TITLE
Page NOT found

### ISSUE THREAD

**Issue by alikarimilangroodi** [NuGet/NuGetGallery#2877]
fslexyacc installation for VS is impossible?

**Comment by maartenba** [comment]
Can you please elaborate? What error are you seeing?

**Comment by alikarimilangroodi** [comment]
Thank you very much for asking. 

The errors are getting less now.

I tried with too many versions. 

I am working with VS Community 2015. 

I don't know when that will bomb out?

**Comment by maartenba** [comment]
Can you describe "the errors"?

**Comment by alikarimilangroodi** [comment]
As I said, I had too many errors with different versions of VS.

Thank you again.

**Comment by maartenba** [comment]
Closing the issue for now. Please re-open with specific error messages / repro steps.

**Comment by alikarimilangroodi** [comment]
Thank you
