### ISSUE TITLE
nuget pack -IncludeReferencedProjects partly ignores .nuspec of referenced projects

### ISSUE THREAD

**Issue by tklingert** [NuGet/NuGetGallery#2879]
Hi,
it seems like nuget ignores the nuspec-definition of referenced projects up on building the dependency list of a package
e.g.:

> src/LibraryA/LibraryA.csproj  - (Version = 1.0.0.0, InformationalVersion = 1.0.0.0-alpha!d11f62)
> src/LibraryA/LibraryA.nuspec  - (version = 1.0.0.0-alpha)

> src/LibraryA/LibraryB.csproj   - (Version = 1.0.0.0, InformationalVersion = 1.0.0.0-alpha!d11f62)
> src/LibraryA/LibraryB.nuspec  - (version = 1.0.0.0-alpha)

> LibraryB references Library A:
> nuget pack -IncludeReferencedProjects ... LibraryB.csproj 

> The generated package should have dependency to 
> LibraryA >= 1.0.0.0-alpha

> but actually added is (nuget version 3.2.1.10581) 
> LibraryA => 1.0.0.0

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2083
