### ISSUE TITLE
Package statistics not updating for a package which contains 2016

### ISSUE THREAD

**Issue by jordimontana82** [NuGet/NuGetGallery#2880]
Hi,

It seems like package statistics aren't being updated for this package: 

https://www.nuget.org/packages/fakexrmeasy.2016

whereas it seems fine for others like:

https://www.nuget.org/packages/fakexrmeasy.2015
https://www.nuget.org/packages/fakexrmeasy.2013
https://www.nuget.org/packages/fakexrmeasy

**Comment by maartenba** [comment]
Fixed these in our warehouse - note that it may take up to 24 hours before this is reflected in the web UI.
