### ISSUE TITLE
Update-Database Throws "Get-Project : Project 'Default' is not found."

### ISSUE THREAD

**Issue by counsellorben** [NuGet/NuGetGallery#2884]
Using VS 2015 Update 1 and EntityFramework 6.1.3.

This happens in two solutions I have tested thus far.  Both are Azure Cloud Service projects, so I specify both -ProjectName and -StartupProjectName with the Update-Database command.

I also have tried specifying the connection string, but that makes no difference.

This error is critical, as it prevents me from updating the cloud service, since I will not be able to update my database as needed.

**Comment by maartenba** [comment]
@counsellorben Can you set the -verbose flag and post logs here?

**Comment by counsellorben** [comment]
@maartenba This morning, I restarted my development machine, updated some unrelated NuGet packages, rebuilt the solution, then tried the Update-Database command again.  Today, it worked without a problem.

Something in my development environment apparently was out of sync yesterday.  However, I do have the output from when I ran the command yesterday.  I substituted the # character for certain identifying info:
===============================================================
PM> update-database -ProjectName #.Data -StartupProjectName #.Website -verbose
Get-Project : Project 'Default' is not found.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:950 char:16
+     $project = Get-Project $name
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Get-Project], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetProjectCommand
 
Get-Project : Project 'Default' is not found.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:950 char:16
+     $project = Get-Project $name
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Get-Project], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetProjectCommand
 
Cannot determine a valid start-up project. Using project '' instead. Your configuration file and working directory may not be set as expected. Use the -StartUpProjectName parameter to set one explicitly. Use the -Verbose switch for more information.
Value does not fall within the expected range.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:977 char:5
+     $DTE.Solution.SolutionBuild.BuildProject($configuration, $project ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
 
Get-Project : Project 'Default' is not found.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:950 char:16
+     $project = Get-Project $name
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Get-Project], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetProjectCommand
 
Value does not fall within the expected range.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:977 char:5
+     $DTE.Solution.SolutionBuild.BuildProject($configuration, $project ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
 
Get-Package : Cannot validate argument on parameter 'ProjectName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\#\#\#\#\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:989 char:41
+     $package = Get-Package -ProjectName $project.FullName | ?{ $_.Id  ...
+                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Package], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,NuGet.PackageManagement.PowerShellCmdlets.GetPackageCommand
 
The EntityFramework package is not installed on project ''.
PM> 
===============================================================

Happily, it is working again, and I am able to proceed with my updates.

**Comment by maartenba** [comment]
May be because it was awaiting package restore and a VS restart.

**Comment by DavidTurton** [comment]
You also get this error message if the project doesn't build cleanly (Package Manager console does a build).  I got it on VS 2015 Update 3 with .NET Core 1.0.1 while executing "scaffold-dbcontext".

**Comment by soroshsabz** [comment]
ITNOA

Do not you think that is better get better message for this situation? even show some recommended actions to resolve this issue. like `Did you awaiting package restore and VS need to restart?`

`Get-Project : Project 'Default' is not found` is very unclear message for finding problem and resolve it.
