### ISSUE TITLE
net40/45 TFMs should show up as '.NETFramework', not 'Portable Class Library' when displaying targeted platforms

### ISSUE THREAD

**Issue by jamesqo** [NuGet/NuGetGallery#2891]
Was creating a library recently that targeted `.NETPortable` when I noticed this. Here is my `project.json`:

```json
{
    "frameworks": {
        "dotnet": {},
        ".NETPortable,Version=v4.0,Profile=Profile328": {}
    }
}
```

And here is how it shows up on the NuGet website:

https://www.nuget.org/packages/Shims.Xaml/1.10.0

As you can see, the TFM 'translation' is listed as

> Portable Class Library (Portable Class Library, Silverlight 5.0, Windows 8.0, WindowsPhone 8.0, WindowsPhoneApp 8.1)

instead of what it should be, which is

> Portable Class Library (.NETFramework 4.0, Silverlight 5.0, Windows 8.0, WindowsPhone 8.0, WindowsPhoneApp 8.1)

**Comment by maartenba** [comment]
@emgarten What would be the correct translation here?

**Comment by emgarten** [comment]
It should contain net40. It's also strange that it lists Portable Class Library in the framework list.

**Comment by maartenba** [comment]
Seems to be the NuGet.Frameworks 3.4.0-beta* we use in the gallery. It returns "portable40" as the first element of the framework short name, failing the translation back to full name.

@emgarten are portable40 and portable45 valid portable framework TFM?

Repro:
```
var framework = NuGetFramework.Parse(".NETPortable,Version=v4.0,Profile=Profile328");
var shortFolderName = framework .GetShortFolderName(); // <-- results in "portable40-net40+sl5+win8+wp8+wpa81"
```

**Comment by emgarten** [comment]
``portable40-net40+sl5+win8+wp8+wpa81`` is correct. NuGet doesn't use the portable generation version, but it can exist. How does it fail to translate this back into a full name? It looks like it chooses portable40 over net40 when writing it out on the gallery, does NuGetFrameworks do this also?

**Comment by maartenba** [comment]
In that case the fix I did in the gallery will solve this. Deployment after the weekend. Thanks for clarifying, Justin! Had no idea portable versions existed.
