### ISSUE TITLE
Nuget backend returns incorrect number of packages

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2895]
from @jianyunt 

Recently, when we use nuget API v2 and ODATA syntax to query the server, we get back the wrong number of packages. Specifically, the URL
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=320&$top=40 returns 39 packages instead of 40. This used to work before but now it is broken (we are not sure when this happened). Is this a known issue?

**Comment by yishaigalatzer** [comment]
We recently made a change to the gallery so this could be a regression.

At the same time, this is a very costly query, and we much appreciate if you stop using these if possible, and use an alternate V3 protocol for your queries (that relies directly on storage rather than database access).

If you can specify what exactly you are looking for we will be glad to help

**Comment by maartenba** [comment]
Fixed this regression - will be deployed next week.

**Comment by maartenba** [comment]
Deployed.
