### ISSUE TITLE
Unity 3d Supporting

### ISSUE THREAD

**Issue by archiZ** [NuGet/NuGetGallery#2897]
Dear developers! Huge request to add support **Unity3d**.
I want to publish assemblies for Unity3d (or Unity3d Editor) with your system.
At the moment **Unity3d** uses **net35-Unity Full v3.5**.
Thank you!

https://unity3d.com

**Comment by maartenba** [comment]
@emgarten @yishaigalatzer Is that a TFM we support in NuGet.Frameworks?

**Comment by emgarten** [comment]
``net35-Unity Full v3.5`` would be ``.NETFramework, Version=v3.5, Profile=Unity Full v3.5``

A profile can be anything though I would expect it to not have whitespace within it. There's no change needed from NuGet here as far as I know. Unity needs to use this target framework in the project files in way where NuGet will read it, and then packages can contain this same framework.

**Comment by archiZ** [comment]
The problem I have is that the Visual Studio 2015 misunderstands and install this package.
I created the structure of the package:
```
+lib/
 +net45/n45.dll
 +net35/n35.dll
 +net35-client/n35c.dll
 +net35-Unity Full v3.5/net35u.dll
 +other/other.dll
```
If I install it on **.Net 4.5** project: Added ref to assembly **n45.dll**. (OK)
If I install it on **.Net 3.5** project: Added ref to assembly **n35.dll**. (OK)
But if I install it on **.Net35-Unity Full v3.5** project: Added ref to assembly **net35u.dll** and **other.dll**. (**FAIL**)
It is expected that will added ref to **only net35u.dll** assembly.
It does not consider folder "**net35-Unity Full v3.5**" as valid target framework.
I think that the problem in the **space symbols**.

I can not affect Unity.
A Visual Studio supports this type of framework.
I think that NuGet must also be support this type :)
![clipboard01](https://cloud.githubusercontent.com/assets/6303937/13195131/f0ff7caa-d7ba-11e5-87b2-6a4637400b9a.jpg)

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2146
