### ISSUE TITLE
Cannot install packages in Node.js project - Project "Default" is not found

### ISSUE THREAD

**Issue by chojrak11** [NuGet/NuGetGallery#2898]
I have Visual Studio 2015 Update 1, with Node.js Tools for Visual Studio v1.1. Everything up to date.
I have a single Node.js project in a solution. The project was created from template "Blank Node.js Web Application." I cannot install any package through Package Management Console. I need for example AngularJS.Intellisense. No luck. The message is: 'Project "Default" is not found.'
In fact, the "Default Project" drop down in PMC is empty and I cannot select anything (the list is empty as well). How can I install this AngularJS.Intellisense package in my project?

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2145
