### ISSUE TITLE
Package icons should only be HTTP/HTTPS

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2899]
Package icons should only be HTTP/HTTPS. Right now we allow other URLs there as well. Restrict protocol type + scan existing packages.

Loosely relates to https://github.com/NuGet/NuGetGallery/issues/2613 and https://github.com/NuGet/NuGetGallery/issues/2610

**Comment by skofman1** [comment]
Going to solve this as part of : https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg

**Comment by skofman1** [comment]
Done.
