### ISSUE TITLE
White installation error

### ISSUE THREAD

**Issue by d054702741** [NuGet/NuGetGallery#2900]
Attempt to install White by the PM, with the following line: "PM> Install-Package TestStack.White"
I've got the following error:

Install-Package : Could not install package 'TestStack.White 0.13.3'. You are trying to install this package into a projec
t that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files tha
t are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  TestStack.White
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Please advise the way to resolve this problem.

Thanks
Daniel Maor
danielmaor@gmail.com

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2159
