### ISSUE TITLE
NuGet.exe push needs different URL to NuGet.exe list (with NuGet.Server)

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2903]
_From @piers7 on February 24, 2016 2:57_

When running an internal Nuget.Server, the [docs](https://docs.nuget.org/create/hosting-your-own-nuget-feeds#step-5:-deploy-and-run-your-brand-new-package-feed!) and start page tell you to put a URL in this form into Visual Studio package manager:

> http://yourserver/nuget

This works fine in Visual Studio (2013), and in the command line nuget.exe (3.3.0.212 - ie latest) if you **list** packages:

> nuget.exe list -source http://yourserver/**nuget**

When you come to **push** packages, however, you need to drop the /nuget off the end:

> nuget.exe list -source http://yourserver/

...otherwise you get either 405 Method Not Allowed or 413 Request Entity Too Large (see http://stackoverflow.com/questions/11264902/private-nuget-server-request-entity-too-large/17813278#17813278 and http://stackoverflow.com/a/16453216/26167 )

This means that the nuget server aliases defined in nuget.config can't be used during push operations, which is a pain.

Is this a client bug, or is it actually a Nuget.Server issue?

_Copied from original issue: NuGet/Home#2165_

**Comment by maartenba** [comment]
_From @yishaigalatzer on February 24, 2016 3:18_

This is definitely not a NuGet client issue. @maartenba can you see what it means to change it in the new nuget.server? (basically it would need to allow both URLs as push end point)

**Comment by piers7** [comment]
You've moved this to the wrong place surely. Shouldn't you have moved this to nuget.server? Or has that been folded in here? I'm confused.

**Comment by maartenba** [comment]
We track anything related to server components there, so correct place :)

**Comment by piers7** [comment]
This is also a pain in TeamCity / build scenarios - have to use a different URL for package restore as you do for pushing final packages. Prevents just sharing the URL across multiple build configurations etc... as a parameter (have to have one for restore, one for push).

**Comment by maartenba** [comment]
The current package supports these URLs for consuming packages:

* `/nuget`

The current package supports these URLs for pushing packages:

* `/`
* `/api/v2/package`

To have it listen on `/nuget` for pushes, a new route can be added. Find the `Routes.cs` file and update it to look like this: (where `$rootnamespace$` is your root namespace)

```
using System.Data.Services;
using System.ServiceModel.Activation;
using System.Web.Routing;
using NuGet.Server;
using NuGet.Server.DataServices;
using NuGet.Server.Publishing;
using RouteMagic;

[assembly: WebActivatorEx.PreApplicationStartMethod(typeof($rootnamespace$.NuGetRoutes), "Start")]

namespace $rootnamespace$ {
    public static class NuGetRoutes {
        public static void Start() {
			ServiceResolver.SetServiceResolver(new DefaultServiceResolver());

            MapRoutes(RouteTable.Routes);
        }

        private static void MapRoutes(RouteCollection routes) {
            // Route to create a new package(http://{root}/nuget)
            routes.MapDelegate("CreatePackageNuGet",
                               "nuget",
                               new { httpMethod = new HttpMethodConstraint("PUT") },
                               context => CreatePackageService().CreatePackage(context.HttpContext));

            // The default route is http://{root}/nuget/Packages
            var factory = new DataServiceHostFactory();
            var serviceRoute = new ServiceRoute("nuget", factory, typeof(Packages));
            serviceRoute.Defaults = new RouteValueDictionary { { "serviceType", "odata" } };
            serviceRoute.Constraints = new RouteValueDictionary { { "serviceType", "odata" } };
            routes.Add("nuget", serviceRoute);
        }

        private static IPackageService CreatePackageService()
        {
            return ServiceResolver.Resolve<IPackageService>();
        }
    }
}

```

I have added this route as a default in the new package which is available as a prerelease: https://www.nuget.org/packages/NuGet.Server/2.10.0-master-0006
