### ISSUE TITLE
OData $batch appears slower than it should be 

### ISSUE THREAD

**Issue by johnataylor** [NuGet/NuGetGallery#2905]
Executing an odata $batch of FindPackageById calls appears on a fast network appears to perform about the same speed as executing the discrete calls from the client sequentially.

However, executing the calls concurrently from the client and you get a big jump in performance - up to 3 times quicker. (Note the only additional work the client is doing is building and parsing the actual batch MIME packet.)

This indicates the core gallery code and SQL database is capable of significantly better performance with the batch and the gallery is serializing the work in the batch.

**Comment by skofman1** [comment]
We are deprecating OData: https://github.com/NuGet/Announcements/issues/37
