### ISSUE TITLE
Authentication issues in ASP.NET 5 projects

### ISSUE THREAD

**Issue by vvatkov** [NuGet/NuGetGallery#2907]
Hi guys,

We have hosted the NuGetGallery V2 with basic authentication in a public feed. Our authentication however does not work in ASP.NET 5 projects. It seems that we receive some requests with UserAgent "Microsoft_.NET_Development_Utility/1.0.0-rc1-16202(Windows6.3)" without Authorization header even though we response with WWW-Authenticate header. Is this a known issue?

Regards,
Veselin Ivanov
Telerik Team

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2194
