### ISSUE TITLE
Errors running build file

### ISSUE THREAD

**Issue by MarkBhoy** [NuGet/NuGetGallery#2911]
Hi All,

I followed the build and run gallery instructions in the README.md file to build nuget gallery.
Which returned the following errors: 

Skipping target "BclBuildEnsureBindingRedirects" because all output files are u
p-to-date with respect to the input files.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output fi
les are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\MSBuild\12.0\bin\Csc.exe /noconfig /nowarn:1701,1702 /
  nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NET
  Framework\v4.5.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Ref
  erence Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" /ref
  erence:"E:\svn\MVC Work\NuGetGallery-master\packages\Newtonsoft.Json.6.0.8\li
  b\net45\Newtonsoft.Json.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\
  packages\NuGet.Services.Platform.Client.3.0.29-r-master\lib\portable-net45+wp
  80+win\NuGet.Services.Platform.Client.dll" /reference:"C:\Program Files (x86)
  \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framewor
  k\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Prog
  ram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2
  \System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Mic
  rosoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Program File
  s (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.
  Net.Http.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\Micros
  oft.Net.Http.2.2.29\lib\net45\System.Net.Http.Extensions.dll" /reference:"E:\
  svn\MVC Work\NuGetGallery-master\packages\Microsoft.AspNet.WebApi.Client.5.2.
  3\lib\net45\System.Net.Http.Formatting.dll" /reference:"E:\svn\MVC Work\NuGet
  Gallery-master\packages\Microsoft.Net.Http.2.2.29\lib\net45\System.Net.Http.P
  rimitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
  oft\Framework\.NETFramework\v4.5.2\System.Net.Http.WebRequest.dll" /reference
  :"E:\svn\MVC Work\NuGetGallery-master\packages\Microsoft.AspNet.WebApi.Core.5
  .2.3\lib\net45\System.Web.Http.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll" /refe
  rence:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFr
  amework\v4.5.2\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collec
  tions.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collections.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NET
  Framework\v4.5.2\Facades\System.ComponentModel.Annotations.dll" /reference:"C
  :\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\
  v4.5.2\Facades\System.ComponentModel.dll" /reference:"C:\Program Files (x86)\
  Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.
  ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagno
  stics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\
  Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Debug.dll
  " /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
  \.NETFramework\v4.5.2\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Pr
  ogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5
  .2\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files (x86)
  \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System
  .Dynamic.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Globalization.dll" /
  reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.N
  ETFramework\v4.5.2\Facades\System.IO.dll" /reference:"C:\Program Files (x86)\
  Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.
  Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\F
  ramework\.NETFramework\v4.5.2\Facades\System.Linq.Expressions.dll" /reference
  :"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewo
  rk\v4.5.2\Facades\System.Linq.Parallel.dll" /reference:"C:\Program Files (x86
  )\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\Syste
  m.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.NetworkInformati
  on.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fra
  mework\.NETFramework\v4.5.2\Facades\System.Net.Primitives.dll" /reference:"C:
  \Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v
  4.5.2\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (x86)\Ref
  erence Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Obj
  ectModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microso
  ft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.dll" /reference:"
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework
  \v4.5.2\Facades\System.Reflection.Emit.dll" /reference:"C:\Program Files (x86
  )\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\Syste
  m.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflec
  tion.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assem
  blies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Exte
  nsions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft
  \Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Primitives.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NET
  Framework\v4.5.2\Facades\System.Resources.ResourceManager.dll" /reference:"C:
  \Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v
  4.5.2\Facades\System.Runtime.dll" /reference:"C:\Program Files (x86)\Referenc
  e Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.
  Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micro
  soft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framewor
  k\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.WindowsRuntime.
  dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framew
  ork\.NETFramework\v4.5.2\Facades\System.Runtime.Numerics.dll" /reference:"C:\
  Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4
  .5.2\Facades\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Fi
  les (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facad
  es\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files
  (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\S
  ystem.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Refer
  ence Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Secur
  ity.Principal.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Mi
  crosoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Duplex.dll
  " /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
  \.NETFramework\v4.5.2\Facades\System.ServiceModel.Http.dll" /reference:"C:\Pr
  ogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5
  .2\Facades\System.ServiceModel.NetTcp.dll" /reference:"C:\Program Files (x86)
  \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System
  .ServiceModel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference As
  semblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel
  .Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
  oft\Framework\.NETFramework\v4.5.2\Facades\System.Text.Encoding.dll" /referen
  ce:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFrame
  work\v4.5.2\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Progr
  am Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\
  Facades\System.Text.RegularExpressions.dll" /reference:"C:\Program Files (x86
  )\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\Syste
  m.Threading.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Tasks.dll" /ref
  erence:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETF
  ramework\v4.5.2\Facades\System.Threading.Tasks.Parallel.dll" /reference:"C:\P
  rogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.
  5.2\Facades\System.Threading.Timer.dll" /reference:"C:\Program Files (x86)\Re
  ference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xm
  l.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\M
  icrosoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.XDocument.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NET
  Framework\v4.5.2\Facades\System.Xml.XmlSerializer.dll" /debug+ /debug:full /f
  ilealign:512 /optimize- /out:obj\Debug\NuGet.Services.Search.Client.dll /subs
  ystemversion:6.00 /target:library /utf8output Client\BaseUrlHealthIndicatorSt
  ore.cs Client\IEndpointHealthIndicatorStore.cs Client\IHealthIndicatorLogger.
  cs Client\NullHealthIndicatorLogger.cs Client\RetryingHttpClientWrapper.cs Cl
  ient\SearchClient.cs Client\ServiceDiscovery.cs Client\ServiceDiscoveryClient
  .cs Correlation\CorrelatingHttpClientHandler.cs Correlation\WebApiCorrelation
  Handler.cs Models\SearchResults.cs Models\SortOrder.cs Properties\AssemblyInf
  o.cs "C:\Users\Mark\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyA
  ttributes.cs"
Client\SearchClient.cs(158,93): error CS1056: Unexpected character '$' [E:\svn\
MVC Work\NuGetGallery-master\src\NuGet.Services.Search.Client\NuGet.Services.Se
arch.Client.csproj]
Done Building Project "E:\svn\MVC Work\NuGetGallery-master\src\NuGet.Services.S
earch.Client\NuGet.Services.Search.Client.csproj" (default targets) -- FAILED.

Project "E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery\NuGetGallery.cspr
oj" (4) is building "E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\
NuGetGallery.Core.csproj" (6) on node 1 (default targets).
CoreResGen:
  No resources are out of date with respect to their source files. Skipping res
  ource generation.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output fi
les are up-to-date with respect to the input files.
GetGitMetadata:
  Extracted Git Metadata
   Branch = nobranch
   CommitId = HEAD
   RepositoryUrl =
CoreCompile:
  C:\Program Files (x86)\MSBuild\12.0\bin\Csc.exe /noconfig /nowarn:1701,1702 /
  nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /re
  ference:"E:\svn\MVC Work\NuGetGallery-master\packages\entityframework.6.1.3\l
  ib\net45\EntityFramework.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master
  \packages\entityframework.6.1.3\lib\net45\EntityFramework.SqlServer.dll" /ref
  erence:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETF
  ramework\v4.5.2\Microsoft.CSharp.dll" /reference:"E:\svn\MVC Work\NuGetGaller
  y-master\packages\Microsoft.Data.Edm.5.6.5-beta\lib\net40\Microsoft.Data.Edm.
  dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\Microsoft.Data.
  OData.5.6.5-beta\lib\net40\Microsoft.Data.OData.dll" /reference:"E:\svn\MVC W
  ork\NuGetGallery-master\packages\Microsoft.Data.Services.Client.5.6.5-beta\li
  b\net40\Microsoft.Data.Services.Client.dll" /reference:"E:\svn\MVC Work\NuGet
  Gallery-master\packages\Microsoft.Web.Xdt.2.1.1\lib\net40\Microsoft.Web.XmlTr
  ansform.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\Microso
  ft.WindowsAzure.ConfigurationManager.3.1.0\lib\net40\Microsoft.WindowsAzure.C
  onfiguration.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\Wi
  ndowsAzure.Storage.4.3.0\lib\net40\Microsoft.WindowsAzure.Storage.dll" /refer
  ence:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFra
  mework\v4.5.2\mscorlib.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\p
  ackages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll" /reference:"E:\s
  vn\MVC Work\NuGetGallery-master\packages\NuGet.Common.3.4.0-beta-632\lib\net4
  5\NuGet.Common.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\
  NuGet.Frameworks.3.4.0-beta-632\lib\net45\NuGet.Frameworks.dll" /reference:"E
  :\svn\MVC Work\NuGetGallery-master\packages\NuGet.Logging.3.4.0-beta-632\lib\
  net45\NuGet.Logging.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\pack
  ages\NuGet.Packaging.Core.3.4.0-beta-632\lib\net45\NuGet.Packaging.Core.dll"
  /reference:"E:\svn\MVC Work\NuGetGallery-master\packages\NuGet.Packaging.Core
  .Types.3.4.0-beta-632\lib\net45\NuGet.Packaging.Core.Types.dll" /reference:"E
  :\svn\MVC Work\NuGetGallery-master\packages\NuGet.Packaging.3.4.0-beta-632\li
  b\net45\NuGet.Packaging.dll" /reference:"E:\svn\MVC Work\NuGetGallery-master\
  packages\NuGet.Versioning.3.4.0-beta-632\lib\net45\NuGet.Versioning.dll" /ref
  erence:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETF
  ramework\v4.5.2\System.ComponentModel.DataAnnotations.dll" /reference:"C:\Pro
  gram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.
  2\System.Configuration.dll" /reference:"C:\Program Files (x86)\Reference Asse
  mblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:"
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework
  \v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)
  \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.dl
  l" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framewor
  k\.NETFramework\v4.5.2\System.Data.Services.Client.dll" /reference:"C:\Progra
  m Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\S
  ystem.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\
  Framework\.NETFramework\v4.5.2\System.IO.Compression.dll" /reference:"E:\svn\
  MVC Work\NuGetGallery-master\packages\System.Spatial.5.6.5-beta\lib\net40\Sys
  tem.Spatial.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.5.2\System.Web.dll" /reference:"C:\Program F
  iles (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Syst
  em.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft
  \Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /debug+ /debug:full /fil
  ealign:512 /optimize- /out:obj\Debug\NuGetGallery.Core.dll /subsystemversion:
  6.00 /resource:obj\Debug\NuGetGallery.Strings.resources /target:library /warn
  aserror+ /utf8output Auditing\AuditEntry.cs Auditing\AuditActor.cs Auditing\A
  uditingService.cs Auditing\AuditRecord.cs Auditing\CloudAuditingService.cs Au
  diting\PackageAuditRecord.cs Auditing\UserAuditRecord.cs CoreConstants.cs Cre
  dentialTypes.cs Completion.cs DisposableAction.cs Entities\Credential.cs Enti
  ties\CuratedFeed.cs Entities\CuratedPackage.cs Entities\PackageDelete.cs Enti
  ties\EmailMessage.cs Entities\EntitiesConfiguration.cs Entities\EntitiesConte
  xt.cs Entities\EntityException.cs Entities\Interception\ObjectMaterializedInt
  erception.cs Entities\Interception\ObjectMaterializedInterceptingDbContext.cs
   Entities\EntityRepository.cs Entities\GallerySetting.cs Entities\IEntitiesCo
  ntext.cs Entities\IEntity.cs Entities\Interception\IObjectMaterializedInterce
  ptor.cs Entities\IEntityRepository.cs Entities\Package.cs Entities\PackageAut
  hor.cs Entities\PackageDependency.cs Entities\PackageEdit.cs Entities\Package
  Framework.cs Entities\PackageHistory.cs Entities\PackageLicense.cs Entities\P
  ackageLicenseReport.cs Entities\PackageOwnerRequest.cs Entities\PackageRegist
  ration.cs Entities\ReadOnlyModeException.cs Entities\Role.cs Entities\User.cs
   PackageReaderCoreExtensions.cs Packaging\InvalidPackageException.cs Packagin
  g\ManifestEdit.cs Packaging\ManifestValidator.cs Packaging\NupkgRewriter.cs P
  ackaging\PackageIdValidator.cs Packaging\PackageMetadata.cs Packaging\Package
  StreamMetadata.cs Properties\AssemblyInfo.cs NuGetVersionExtensions.cs Stream
  Extensions.cs Strings.Designer.cs Unit.cs "E:\svn\MVC Work\NuGetGallery-maste
  r\packages\NuGet.Services.Build.3.0.13\tools\\CommonAssemblyInfo.cs" "C:\User
  s\Mark\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs"
   C:\Users\Mark\AppData\Local\Temp\cdd8916086af44219509bace1cc70a69_VersionInf
  o.cs
Auditing\AuditActor.cs(48,17): error CS1056: Unexpected character '$' [E:\svn\M
VC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
Auditing\AuditingService.cs(74,33): error CS1056: Unexpected character '$' [E:\
svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.csproj
]
Auditing\PackageAuditRecord.cs(38,20): error CS1056: Unexpected character '$' [
E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.csp
roj]
Packaging\PackageIdValidator.cs(33,45): error CS1056: Unexpected character '$'
[E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.cs
proj]
Done Building Project "E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Cor
e\NuGetGallery.Core.csproj" (default targets) -- FAILED.

Done Building Project "E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery\NuG
etGallery.csproj" (default targets) -- FAILED.

Done Building Project "E:\svn\MVC Work\NuGetGallery-master\NuGetGallery.sln" (B
uild target(s)) -- FAILED.

Done Building Project "E:\svn\MVC Work\NuGetGallery-master\packages\NuGet.Servi
ces.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default targets) -- F
AILED.

Done Building Project "E:\svn\MVC Work\NuGetGallery-master\build.msbuild" (defa
ult targets) -- FAILED.

Build FAILED.

"E:\svn\MVC Work\NuGetGallery-master\build.msbuild" (default target) (1) ->
"E:\svn\MVC Work\NuGetGallery-master\packages\NuGet.Services.Build.3.0.13\tools
\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"E:\svn\MVC Work\NuGetGallery-master\NuGetGallery.sln" (Build target) (3) ->
"E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery\NuGetGallery.csproj" (def
ault target) (4) ->
"E:\svn\MVC Work\NuGetGallery-master\src\NuGet.Services.Search.Client\NuGet.Ser
vices.Search.Client.csproj" (default target) (5) ->
(CoreCompile target) ->
  Client\SearchClient.cs(158,93): error CS1056: Unexpected character '$' [E:\sv
n\MVC Work\NuGetGallery-master\src\NuGet.Services.Search.Client\NuGet.Services.
Search.Client.csproj]

"E:\svn\MVC Work\NuGetGallery-master\build.msbuild" (default target) (1) ->
"E:\svn\MVC Work\NuGetGallery-master\packages\NuGet.Services.Build.3.0.13\tools
\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"E:\svn\MVC Work\NuGetGallery-master\NuGetGallery.sln" (Build target) (3) ->
"E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery\NuGetGallery.csproj" (def
ault target) (4) ->
"E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.cs
proj" (default target) (6) ->
  Auditing\AuditActor.cs(48,17): error CS1056: Unexpected character '$' [E:\svn
\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
  Auditing\AuditingService.cs(74,33): error CS1056: Unexpected character '$' [E
:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.cspr
oj]
  Auditing\PackageAuditRecord.cs(38,20): error CS1056: Unexpected character '$'
 [E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.c
sproj]
  Packaging\PackageIdValidator.cs(33,45): error CS1056: Unexpected character '$
' [E:\svn\MVC Work\NuGetGallery-master\src\NuGetGallery.Core\NuGetGallery.Core.
csproj]

    0 Warning(s)
    5 Error(s)

Help to resolve these errors would be appreciated.

Thanks
Mark

**Comment by maartenba** [comment]
Seems like C# 6 is not supported by your compiler. Which VS version do you have installed?

**Comment by jozefizso** [comment]
The `build.cmd` will use the latest msbuild.exe from VS2015 but the NuGet Gallery build scripts prefer to use older toolset. If the machine has VS2012/2013 installed, it will use the old .NET toolset which does not support string interpolations.

This can happen on AppVeyor builds too because their machines tend to have several Visual Studio versions installed.

I fixed this on my personal fork with forcing the toolset version to 14.0: https://github.com/goitsk/NuGetGallery/commit/b4a8c1490ce4318abd95fd2785c87bc2eb08cc5a

```
@msbuild build.msbuild /tv:14.0 /p:VisualStudioVersion=14.0 /p:ToolsVersion=14.0 %*
```

[NuGet.Services.Build](https://github.com/NuGet/NuGet.Services.Build) package prefers to use the "12.0" toolset in its build scripts: https://github.com/NuGet/NuGet.Services.Build/blob/17422ad170b0dd784a0f24c83ec8bf3bbfbb8cdd/tools/NuGet.Services.FullBuild.msbuild#L10-L13

**Comment by maartenba** [comment]
Fixed.
