### ISSUE TITLE
the v2 feed has started returning unlisted packges

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#2913]
For example it returns https://www.nuget.org/packages/log4net/1.2.11

**Comment by maartenba** [comment]
Investigating...

**Comment by maartenba** [comment]
A fix is now deployed that sets the published date correctly.
Can you confirm things are as expected now?

**Comment by SimonCropp** [comment]
this is fixed. awesome. i was fully expecting the answer to be "use the v3 feed"

**Comment by maartenba** [comment]
Happy to hear! Thanks @simoncropp
