### ISSUE TITLE
Search by owner misses some owned packages

### ISSUE THREAD

**Issue by mmdriley** [NuGet/NuGetGallery#2914]
Three packages [owned by `google-apis-packages`](https://www.nuget.org/profiles/google-apis-packages?showAllPackages=True) don't appear in the output of `nuget list owner:google-apis-packages`:

- [`Google.Apis.Iam.v1`](https://www.nuget.org/packages/Google.Apis.Iam.v1/)
- [`Google.Apis.Iam.v1alpha1`](https://www.nuget.org/packages/Google.Apis.Iam.v1alpha1/)
- [`Google.Apis.People.v1`](https://www.nuget.org/packages/Google.Apis.People.v1/)

Corrupt or out-of-date index, perhaps?

**Comment by maartenba** [comment]
Which API endpoint are you running this on? V2 or V3?

**Comment by mmdriley** [comment]
Nuget v3.3.0 seems to be hitting the v2 endpoint:

```
C:\Users\Matthew>nuget
NuGet Version: 3.3.0.212
...

C:\Users\Matthew>nuget list owner:google-apis-packages -verbosity detailed
GET https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='owner:google-apis-packages'&targetFramework=''&includePrerelease=false
...
```

The packages are also missing from [a search on nuget.org](https://www.nuget.org/packages?q=owner%3Agoogle-apis-packages).

**Comment by maartenba** [comment]
@mmdriley Seems like this is a stale index of package owners. We are looking into resolving this.

**Comment by maartenba** [comment]
Should be fixed now.
