### ISSUE TITLE
Capture System.IO.InvalidDataException in PackageArchiveReader..ctor

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2917]
Occasionally, an invalid zip archive is sent to `PUT https://www.nuget.org/api/v2/package/` (Api/PushPackageApi), resulting in the InvalidDataException.

We should handle the exception, log this properly, but avoid it from cluttering Application Insights for the gallery.

**Comment by skofman1** [comment]
@xavierdecoster , I added similar code in staging. Can I take this one?

**Comment by maartenba** [comment]
Is that this one? https://github.com/NuGet/NuGet.Staging/pull/15/files#diff-57f75ce5c7a8d9100d2ca92556881d37R81

Looks good to me!

**Comment by xavierdecoster** [comment]
@skofman1 the stage is yours :)
