### ISSUE TITLE
Package stats - Add unique downloader count

### ISSUE THREAD

**Issue by playtime222** [NuGet/NuGetGallery#2918]
I have recently added some new packages that were effectively for private use but to my surprise the stats show far more downloads than I believe I can account for.

If I could see that an indication of 'unique downloader count' - where this could be counted in a similar manner to 'unique users' on a web site - this would help determine whether it was more than just me attempting to use the package and steer some effort into bringing it up to a reasonable standard.

**Comment by maartenba** [comment]
No NuGet client sends anything to identify a user uniquely, making this an impossible task to add.

Note that there are a number of "bots" out there that copy packages, run analytics, provide notifications, ... which could explain the downloads you are seeing. Or just regular users, of course. If you want your packages only available to you and/or your team, you may want to setup a private NuGet server.

**Comment by playtime222** [comment]
The 'bots' explanation works for me. 
We do run a private server too but there were 'reasons' for these packages to be public.
Thanks.
