### ISSUE TITLE
Add a download rate metric to the package page

### ISSUE THREAD

**Issue by richorama** [NuGet/NuGetGallery#2924]
Add a metric in the left hand panel to show the averge number of downloads per day.

i.e. `rate = number of downloads / days since publish`

I suggest this is rounded to the nearest whole number.

If the number is less than one, I suggest `<1 download per day` is added.

This is a much more useful way of judging the popularity of a package than just the total number of downloads.

This is something I have pioneered on the http://nugot.net website.

![image](https://cloud.githubusercontent.com/assets/353138/13672910/ac35398e-e6ce-11e5-8ee2-ef5c8966dafe.png)

**Comment by maartenba** [comment]
A PR would be most welcome :)

**Comment by richorama** [comment]
Will do :¬)

**Comment by maartenba** [comment]
Thanks @richorama !

**Comment by maartenba** [comment]
Closing. Deployment still panding but should be in the next few days.
