### ISSUE TITLE
Update-Database Command issues

### ISSUE THREAD

**Issue by pravegali** [NuGet/NuGetGallery#2926]
HI, 

As per the wiki i have got the application setup on my machine. But, when I run the Update-Database command it fails saying more that one configuration found. So, I ran the command 
Update-Database -Verbose -ConfigurationTypeName MigrationsConfiguration

This time the all the tables were required. But, the table Packagestatistics was deleted as per another script. Why was it explicitly deleted. And also, the application is failing because of this. 

Thanks
Praveen Gali

**Comment by skofman1** [comment]
PackageStatistics code is obsolete and was removed from the gallery ~month ago. What kind of failures are you seeing?

**Comment by pravegali** [comment]
when i run the application locally, the class UpdateStatisticsJob.cs has a stored proc execution [dbo].[AggregateStatistics], that is failing.

**Comment by maartenba** [comment]
@xavierdecoster @skofman1 Can you check and remove the job if needed?

**Comment by xavierdecoster** [comment]
Tracking issue for removal of obsolete download stats aggregation code from the gallery: https://github.com/NuGet/NuGetGallery/issues/2932

We no longer track package downloads in the gallery db.
