### ISSUE TITLE
Neo4jClient v1.1.0.29 is not showing in https://api.nuget.org/v3/index.json feed

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#2927]
@drgraduss wrote:
I'm experiencing issue similar to #1145 and #1544 with Neo4jClient package.

Latest version 1.1.0.29 is not showing up in the VS2015 for nuget v3 feed.
Nuget v2 feed returns the latest version though.

Trying to install latest version from PackageManagerConsole gives me 1.1.0.28. Plus Teamcity nuget restore failing to find 1.1.0.29 version as well (uses Nuget v.3.3.0).

I can confirm that I can download package from https://api.nuget.org/packages/neo4jclient.1.1.0.29.nupkg

**Comment by xavierdecoster** [comment]
This package version is now available on the v3 feed. Closing this one as it only tracks a symptom of issues we already track separately.

**Comment by drgraduss** [comment]
@skofman1 @xavierdecoster thanks!
