### ISSUE TITLE
Catalog2Registration throw NullReferenceException

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#2929]
[mylog.txt](https://github.com/NuGet/NuGetGallery/files/168108/mylog.txt)

**Comment by skofman1** [comment]
![image](https://cloud.githubusercontent.com/assets/16807822/13688777/d8e668f4-e6d8-11e5-9f2e-4420341737ab.png)

Theory: The success rate for blob storage is between 60%-80%. According to logs, there is an often failure to load a registration blob, and same blob time after time. The job progress continues when the cursor is moved away from the failing blob. 
Next steps: better error messages for storage errors, retries for storage access

**Comment by maartenba** [comment]
Issue has been resolved. The success percentage may be related to 404's (and in turn to this: https://github.com/NuGet/Home/issues/2038)
