### ISSUE TITLE
Packages containing Unsupported0.0 should be rejected

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#2930]
The gallery should reject packages containing the target framework ``Unsupported0.0`` in the nuspec file. This can happen when nuget.exe does not understand a target framework but still creates the package.

Note that this is different than creating a package with a framework that the gallery doesn't understand. Here the framework isn't understood by the tooling creating it. The result is a package that cannot be used correctly and so it should not be allowed on the gallery.

**Comment by maartenba** [comment]
Do we have an example package?
