### ISSUE TITLE
Ability to search by target framework

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2936]
Customers would like to search by target framework and find packages compatible with their projects. This is to track an API and web UI that enables it (and not a client level filtering in the visual studio)

**Comment by maartenba** [comment]
What would be the timeline for this one?

**Comment by Mottor** [comment]
Hey people, the .NET Platform Standard is coming. It is time to make it possible to search by platform.

**Comment by cpsaez-Lendsum** [comment]
yes please, develop something in .NET Core right now is far to be as smooth  as 4.6

**Comment by skofman1** [comment]
This is vert similar to this one: https://github.com/NuGet/NuGetGallery/issues/3098
closing.
