### ISSUE TITLE
Visual Studio Not Finding Latest NuGet Package

### ISSUE THREAD

**Issue by daryllabar** [NuGet/NuGetGallery#2938]
On Saturday night, I published a new release to NuGet: [https://www.nuget.org/packages/XrmUnitTest.2015/1.1.4-alpha05](https://www.nuget.org/packages/XrmUnitTest.2015/1.1.4-alpha05) And now I'm trying to reference it from Visual Studio, but it's not finding the 1.1.4-Alpha05 release, only the 1.1.4-Alpha03.

![NuGet Feed](http://i.stack.imgur.com/Ti4KE.jpg)
![Visual Studio Version](http://i.stack.imgur.com/RemRH.jpg)

Even attempting to update manually doesn't work:
```
PM> Install-Package XrmUnitTest.2015 -Version 1.1.4-alpha05 -Pre
Attempting to gather dependencies information for package 'XrmUnitTest.2015.1.1.4-alpha05' with respect to project 'Defender.Xrm', targeting '.NETFramework,Version=v4.5.2'
Install-Package : Package 'XrmUnitTest.2015' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources 
are available.
At line:1 char:1
+ Install-Package XrmUnitTest.2015 -Version 1.1.4-alpha05 -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by maartenba** [comment]
This should be resolved soon. We are deploying a fix for an issue we've had. Keep an eye on http://status.nuget.org for status updates.

**Comment by daryllabar** [comment]
Thanks for the quick response @maartenba!
