### ISSUE TITLE
Rename package on nuget.org

### ISSUE THREAD

**Issue by nietras** [NuGet/NuGetGallery#2941]
Mistakes happen. And I for one made the mistake of naming a package `DotNetCross.Memory.Unsafe.dll` note this include `.dll`. I would like remove `.dll` of the package name, but there is no apparent way to do this on nuget.

Is this possible? Or could this feature be added?

Or do I have to delete the old package with `.dll` in the name and then upload new without?

**Comment by maartenba** [comment]
Please upload a new one without, and send us a support request asking for deletion of the old one.

**Comment by nietras** [comment]
I tried to upload without the `.dll` part but got the following message:

> The ID of your package, 'DotNetCross.Memory.Unsafe', is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again.

**Comment by maartenba** [comment]
Package removed, you should now be able to re-upload.
