### ISSUE TITLE
unable to get to https://api.nuget.org

### ISSUE THREAD

**Issue by jpence** [NuGet/NuGetGallery#2942]
error:   
The webpage cannot be found
 
  HTTP 400 
 
     
Most likely causes:
•There might be a typing error in the address.
•If you clicked on a link, it may be out of date.
 
   
What you can try:
 
    

  Retype the address.  

 
    

  Go back to the previous page.  
 
    

  Go to  and look for the information you want.  
 
    

More information  More information   

This error (HTTP 400 Bad Request) means that Internet Explorer was able to connect to the web server, but the webpage could not be found because of a problem with the address.

For more information about HTTP errors, see Help.

**Comment by skofman1** [comment]
The site is available from our location. What is you location? Can you capture an MTR trace (described here: http://docs.nuget.org/Consume/NuGet-FAQ) and send it back so that we can investigate?

**Comment by yishaigalatzer** [comment]
That's actually expected there is no resource at that level.

You can use `api.nuget.org/v3/index.json` to get the service index

**Comment by maartenba** [comment]
@jpence can you confirm  api.nuget.org/v3/index.json works for you?

**Comment by maartenba** [comment]
Closing for now - no feedback received
