### ISSUE TITLE
Packages with a lib/netcore subdirectory show up as .NETCore 0.0

### ISSUE THREAD

**Issue by jamesqo** [NuGet/NuGetGallery#2946]
When creating a package that has a `lib/netcore` subdirectory and uploading it to the Gallery, it will show up as `.NETCore 0.0`. [Here](https://www.nuget.org/packages/DotNetCross.Memory.Unsafe) is one such test case. Note that the version-less `dnxcore` on the other hand gets perfectly translated to `DNXCore 5.0`.

cc @maartenba @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Going forward you should use netstandard rather than netcore.

If you want it to show a version is should be netcore45

**Comment by maartenba** [comment]
Will be updated when we update the gallery with new client dependencies having these new tfm's.
