### ISSUE TITLE
NuGet.Server - Default to using the host header for request urls

### ISSUE THREAD

**Issue by MerickOWA** [NuGet/NuGetGallery#2951]
Ran into an issue which turned out to be relatively simple to fix, but seemed unnecessary work.

Running NuGet.Server in a NAT'ed network with a public IP which was different from the server's internal IP caused the atom feed to return its internal IP for all incoming requests and made it impossible to actually download the packages as user's couldn't access the server via the internal IP.

After digging into it, I realized that simply adding an appSetting for "aspnet:UseHostHeaderForRequestUrl" set to "true" resolved the issue easily enough.

It seems like it would be better to default this to true by default, or at the very least, add it to the web.config commented out with a description explaining it just to help others find this in the future.

**Comment by maartenba** [comment]
Thanks! We just published a new prerelease version which has this setting (commented in Web.config)

**Comment by DanTup** [comment]
I'm curious - why is this not the default? Under what circumstances would the IP work but the hostname in the host header fail?

**Comment by maartenba** [comment]
Not wanting to break the defaults that have been in NuGet.Server for ages.

**Comment by DanTup** [comment]
That's kinda my question; under what circumstances could it break - under what circumstances would the IP address work, but the hostname in the host header wouldn't? (I'm not suggesting it can't, I just can't think of a reason so I'm curious what I haven't thought of :-))

**Comment by maartenba** [comment]
Good question :-) My guess is when running behind reverse proxies, load balancers, ... `true` would make sense, but also can't think of a reason.  ASP.NET sets it default to false as well - https://msdn.microsoft.com/en-us/library/hh975440(v=vs.120).aspx so I guess there is a reason :-)

**Comment by DanTup** [comment]
Ah, I thought this was a NuGet Gallery setting, not ASPNET. Those docs seem to suggest it might use the hostname from the web server (eg. IIS) rather than host header (not necessarily the IP):

> If this value attribute is false [default], the Url property is dynamically built from the host, port, and path provided by the web server.
