### ISSUE TITLE
NuGet packages for Universal Windows not installing from private feed

### ISSUE THREAD

**Issue by mathikp** [NuGet/NuGetGallery#2954]
I have a private NuGet feed which has packages for various platforms. All the other platform's packages are working fine, can install those packages from Visual Studio. But packages targeting uap10.0 is cannot be installed in Universal Windows project in Visual Studio 2015. The same packages can be installed from local folder into the project. While installing from online feed, its shows below error.

_Failed to retrieve information from remote source 'http://feedlink'.
Response status code does not indicate success: 404 (Not Found)._

But the package is listing in Package Manager window and also in Package Manager Console while using Get-Package command. Please help.

**Comment by maartenba** [comment]
Which NuGet server are you using?

**Comment by mathikp** [comment]
I'm maintaining our own server for my company.

**Comment by maartenba** [comment]
Which server product are you using?

**Comment by mathikp** [comment]
We are using Azure.

**Comment by maartenba** [comment]
What software is installed to host NuGet packages? Is it a file share? NuGet.Server? NuGet gallery? ProGet? MyGet? Artifactory?

**Comment by mathikp** [comment]
We are using NuGet server.

**Comment by maartenba** [comment]
Which version of it are you using?

**Comment by mathikp** [comment]
The version is 3.0.

**Comment by maartenba** [comment]
The version of NuGet.Server? There is no 3.0 verion of it (we just released 2.10.1 yesterday)
We will need some info on the environment and server software used to be able to see what the problem could be...

**Comment by mathikp** [comment]
Sorry for the delay in response and for mentioned the version wrongly. We have tried version [2.10.1](https://www.nuget.org/packages/NuGet.Server/2.10.1) NuGet.Sever assembly in our project. Still the error is coming frequently. The package is getting installed only few times. Most of the time it fails.

**Comment by maartenba** [comment]
Do you happen to have more logs on the NuGet install? (in VS)
Which Nuget verson do you have instaleld in Visual Studio? Can you try vLatest from http://dist.nuget.org/index.html ?

**Comment by mathikp** [comment]
Installation Log: [NuGetLog.txt](https://github.com/NuGet/NuGetGallery/files/181900/NuGetLog.txt)
I'm using NuGet Package Manager 3.3.0.167 in my VS.
The package is installing fine while using nuget.exe. But the issue is with installing package inside VS with Package Manager or Package Manager Console.

**Comment by maartenba** [comment]
You may be missing the `/nuget` part of the URL, full URL to NuGet.Server should be http://server/nuget

**Comment by mathikp** [comment]
We are just checking the server site in staging for testing purpose. Actually all the packages are listing in the Package Manager. There is no issues with the url.

**Comment by maartenba** [comment]
May be a client issue then, moving

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2366

**Comment by mathikp** [comment]
Any other suggestions?
