### ISSUE TITLE
Get deleted packages or delta via API

### ISSUE THREAD

**Issue by larsbaunwall** [NuGet/NuGetGallery#2955]
Hi 

I am playing around a bit with Azure Search, and thought it would be awesome to see if I could build something cool on top of the data you have in the nuget-feed.

I have been exploring Nuget.Services.Metadata and tried using some of the techniques in the for fetching packages from the nuget feed for ingestion into Azure Search.

However, I've run into some challenges - mainly indexing performance and how to get deletes. Do you have any API's, where one can fetch deltas?

**Comment by maartenba** [comment]
You can use the catalog for this type of traversal. It is an append-log tree structure which has one blob page per “Add package” or “Edit Package” action that happens in the Gallery. All metadata of the package can be accessed from here. We use this catalog ourselves to populate the search index and so on. 

The root level index page of the catalog can be seen @ http://api.nuget.org/v3/catalog0/index.json. This has links to the individual pages (the second level nodes in the tree). The pages in turn will have links to the individual Package blobs (the leaf nodes the tree). Each leaf node will indicate a specific version of a package. 

To traverse through the catalog, you read the index and go to the individual pages from there and then follow the link to individual packages. Each “Page” (second level) and “Package” (leaf level) has a time stamp to indicate when it was created. If you are doing continuous replication, you can maintain a time stamp marker on your end (something like “LastRead”). Whenever you replication job starts, it will get the “LastRead” marker and go to the “Pages” created after the “LastRead” time stamp and go to the individual Packages.  

Sample code you say? You can clone the repo @ https://github.com/NuGet/NuGet.Services.Metadata. The https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Catalog2Registration.cs is an example of a “CatalogReader” which reads from the catalog and creates registration blobs. It maintains a LastReader marker which is stored in “Curson.json”. On similar lines https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Catalog2Lucene.cs is another “CatalogReader” which continuously reads from catalog and updates our search index.

Let me know if this works :)

**Comment by larsbaunwall** [comment]
Hi Maarten

Thank you so much for you answer :) Really appreciate it!

Actually, what you describe in your approach is exactly what I did, and so far it has worked out really good. However, I didn't see deletes in the page blobs - but maybe I just overlooked them?

I would very much like to do deletes in my continous indexing process too, so I don't have to do a full reindex every time...

Looking forward to hearing from you :)

**Comment by maartenba** [comment]
Deletes are in there, if you check the "searchcloud" branch (which will become our new master) you will find the @type for it: https://github.com/NuGet/NuGet.Services.Metadata/blob/searchcloud/src/Ng/SearchIndexFromCatalogCollector.cs#L108

Note deletes will only show up from somewhere after last summer

**Comment by larsbaunwall** [comment]
ahh - great!
thx!
