### ISSUE TITLE
Include package size in search and registrations

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2957]
Include package size in search and registrations, see https://github.com/NuGet/Home/issues/2375#issuecomment-200081479

Are there other fields we may want to add?

**Comment by maartenba** [comment]
(adding @yishaigalatzer as CC)

**Comment by jhaamit6666** [comment]
Owners of the package and link to [Package Statistics](https://www.nuget.org/stats/packages/NLog?groupby=Version&groupby=ClientName&groupby=ClientVersion&groupby=Operation) as marked in the snapshot. 
![1](https://cloud.githubusercontent.com/assets/16834561/13980256/933dcb82-f103-11e5-8790-8d67c6fcb76f.png)

**Comment by 304NotModified** [comment]
I would find "has strong name" (maybe including version) be useful. Strong naming is still needed these days and lead to unclear errors.

**Comment by jhaamit6666** [comment]
kindly close this issue if solution found or to be implemented or "won't fix".

**Comment by skofman1** [comment]
Having the size on Gallery as well will be useful.

**Comment by onovotny** [comment]
Any updates there? Agree that size would be useful

**Comment by skofman1** [comment]
@onovotny , the team is working on other areas in the moment, and since exposing the package size in 
 V3 is a lot of work, it is not work planned for the near future. 
However, exposing the package size on the Gallery is quite easy, and I created a separate issue for that: https://github.com/NuGet/NuGetGallery/issues/5471

**Comment by anangaur** [comment]
Closing this as a duplicate of https://github.com/NuGet/Home/issues/7957. There are bunch of metadata that needs to be shown on the VS PM UI.

**Comment by anangaur** [comment]
The Gallery already shows the size information (implemented as part of #5471).
