### ISSUE TITLE
Backpointers from a package to packages dependent on it

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#2958]
If we had information about all the packages dependent on a certain package we could do lots of nice scenarios with it:
1. Discovery - when a customer is considering which package to use, this information is valuable in deciding the package usability and reliability. It's more relevant then download count, because that doesn't reflect cases when a package was installed, and then uninstalled, without actually being used.
2. Package owner feedback - knowing who uses your package and for what purposes is important for a package owner, similarly to the case when you publish an article in a journal, and can see who quoted you. This will encourage people to publish more packages to NuGet.
3. npm has it.

**Comment by anangaur** [comment]
Linking https://github.com/NuGet/NuGetGallery/issues/4718.

**Comment by skofman1** [comment]
Closing this one since the new issue has pretty pictures :)
