### ISSUE TITLE
Unable to publish package. Error: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by rexhansen** [NuGet/NuGetGallery#2964]
Uploading a package to nuget.org using the command line tool fails with the error: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.  Also unable to upload using a browser or the Nuget Package Explorer app.  Browser will freeze, go blank, or return a similar error (depends on browser type).  In Nuget Package Explorer, the upload appears to never complete (progress bar spins). 

The package may be relatively large (~340MB), but I'm not aware of any package size limits on nuget.org.  Can you determine why the upload is failing? 

NuGet package shared here: https://esri.box.com/s/v9fcl5vvrgsoei6jsc0js389hnl1pavd

**Comment by yishaigalatzer** [comment]
We do limit package size on nuget.org to 250mb, and really ask package authors not to exceed 50mb.

We should check why this behaves this way rather than provide a good error message

**Comment by maartenba** [comment]
We indeed have a limit and large packages are usually bad.

Which NuGet.exe client are you using to do the push?
