### ISSUE TITLE
Documentation  not mentioning 2015 

### ISSUE THREAD

**Issue by vbjay** [NuGet/NuGetGallery#2965]
[Example](http://docs.nuget.org/Consume/Overview):NuGet User Interface in Visual Studio
NuGet runs in all versions and SKUs of Visual Studio 2010, Visual Studio 2012 and Visual Studio 2013. For Visual Studio 2012...

**Comment by maartenba** [comment]
@csharpfritz can you do a pass over the docs?

**Comment by csharpfritz** [comment]
Updated this page...  need to scan more of the docs for specific references to OS and application versions

**Comment by maartenba** [comment]
Thanks - is this somethin @harikm86 can start looking at as well?

**Comment by harikm86** [comment]
Jeff, I'm going to reassign this to myself and start tracking this.

**Comment by harikm86** [comment]
Did a search and fixed it in docs https://github.com/NuGet/NuGetDocs/commit/18461a22026d8d39b8497788d0cceae514851915
