### ISSUE TITLE
Private Nuget Gallery with protocol v3. Where is it?

### ISSUE THREAD

**Issue by ReverseBlade** [NuGet/NuGetGallery#2971]
Our team has been been running a private nuget gallery since last 2 - 3 years. 

We heard that nuget v3 offers better speed so we decided to install a recent nuget gallery from GitHub repo to try protocol v3. 

I have cloned the latest commit and set it up and make it running properly. However I have no clue how to make use of protocol v3 from visual studio side. The official nuget gallery runs something route like v3/index.json and making use of JSON-LD. However nothing the in the source code (beside tests) shows anything relevant with v3. Instead it uses the old v2 OData. 

Am I missing something or is nuget protocol v3 not publicly available for a private Nuget Gallery ?

**Comment by maartenba** [comment]
The V3 protocol is a set of services that isn't included in the NuGet Gallery repository.

**Comment by ReverseBlade** [comment]
Yes  I am well aware of it is not in the Nuget Gallery repository. If you read the issue it asks "Where is it"
And that you haven't respond. So from your answer I deduce that for us it is impossible to make use of v3 with our private galleries at the time being. Am I correct ?

**Comment by maartenba** [comment]
There's NuGet.Services.Metadata that contains a bunch of services (both web and back-end) that need to be run. We're planning on making NuGet.Server a V3 endpoint at some point but that is work in progress.

**Comment by stg609** [comment]
How is everything going? I get the latest nuget gallery, but still can't make a v3 api request.

**Comment by loic-sharma** [comment]
If you’d like to run NuGet.org’s services that power the V3 API, please follow this guide: https://github.com/NuGet/NuGetGallery/wiki/Hosting-nuget.org's-v3-services

You can also use BaGet to setup a NuGet V3 server: https://github.com/loic-sharma/BaGet
