### ISSUE TITLE
Do not query for Alert.md all the time

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2973]
Do not query for Alert.md all the time. Ideally remove it altogether (we have the status page for it) but keep support for the banner on dev and int.

**Comment by robertmuehsig** [comment]
Idea to remove the Alert.md completely:
Introduce a new Config-Entry - e.g. 
<add key="Gallery.WarningBanner" value="This is a development environment." />

If this key is present or has any value, just render it in the layout.cshtml - e.g.

      @if (!string.IsNullOrWhiteSpace(Config.Current.WarningBanner))
      {
        <div id="service-alert">@Config.Current.WarningBanner</div>
      }

When I understand your idea correctly this might work and we could remove the Alert.md, the ServiceAlert method in the ApiController and the JS that is using this Service.

What do you think?

**Comment by maartenba** [comment]
Sounds perfect!

**Comment by robertmuehsig** [comment]
Then I will give it a try :+1:

**Comment by robertmuehsig** [comment]
This seems to be already deployed, right? Close?
