### ISSUE TITLE
nuget feed returning an unlisted package for NServiceBus

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#2977]
Find-Package -Id nservicebus -AllVersions -IncludePrerelease -ExactMatch -Source https://api.nuget.org/v3/index.json

gives 

    {6.0.0-unstable0257, 5.2.14, 5.2.13, .

but `6.0.0-unstable0257` is unlisted https://www.nuget.org/packages/NServiceBus/6.0.0-unstable0257

i tried listing and unlisting. but it doesnt seem to work, or i am suffering from caching

**Comment by SimonCropp** [comment]
using VERSION 3.4.1.807

**Comment by SimonCropp** [comment]
pinged some others. does not happen on 3.3.0.167 or 2.8.50506.491. but someone else could replicate on  3.4.1.807

**Comment by SimonCropp** [comment]
and just to be clear i am happy for that unstable0257 version to be permanently removed if that is the easiest solution

**Comment by SimonCropp** [comment]
v2 feed does not have the problem 

    Find-Package -Id nservicebus -AllVersions -IncludePrerelease -ExactMatch -Source https://www.nuget.org/api/v2/

**Comment by maartenba** [comment]
I've removed the package for now. The fact that this happens on 3.4 and does not happen on 3.3.0.167 or 2.8.50506.491 makes me believe this is a client issue.

Did some testing on a test package, this seems to happen when some versions are listed and some are unlisted. For `MaartenTestIsLatest` there are 0.0.1 (listed) and 0.0.2 (unlisted) which shows both versions in VS:
```
PM> Find-Package -Id MaartenTestIsLatest -AllVersions -IncludePrerelease -ExactMatch -Source https://api.nuget.org/v3/index.json

Id                                  Versions                                 Description                                                                                               
--                                  --------                                 -----------                                                                                               
MaartenTestIsLatest                 {0.0.2, 0.0.1}                           My package description.   
```

In this case 0.0.2 is unlisted and shows in this find command.

Search URL requested by client:
`https://api-v2v3search-0.nuget.org/query?q=MaartenTestIsLatest&skip=0&take=26&prerelease=true`

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2494
