### ISSUE TITLE
.\build  bash: .build: command not found

### ISSUE THREAD

**Issue by if825** [NuGet/NuGetGallery#2980]
I try to perform 3th step 
$ .\build
bash: .build: command not found

**Comment by maartenba** [comment]
That would need PowerShell or regular command line instead. (or .\build.cmd)

**Comment by if825** [comment]
When I type .\build  or .\build.cmd I get 'msbuild' is not recognized as an internal or external command,operable program or batch file

**Comment by if825** [comment]
When I type .\build or .\build.cmd I get 'msbuild' is not recognized as an internal or external command,operable program or batch file.
I was trying PowerShell and command line as well

**Comment by maartenba** [comment]
You will need a Visual Studio command prompt (or add msbuild to %PATH%)
