### ISSUE TITLE
Add support for vector images in the Nuspec iconUrl reference

### ISSUE THREAD

**Issue by jordimontana82** [NuGet/NuGetGallery#2981]
Hi,

I was looking at the [Nuspec reference](https://docs.nuget.org/create/nuspec-reference), and it looks like the only supported format for iconUrl property is a PNG of 64x64 pixels only.

Would be nice to include support for SVG formats too, cause we could use that to display high definition logos (specially logos containing fonts or similar) while at the same time files served will be small.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2519
