### ISSUE TITLE
Support requests - when setting request to "unresolved" error occurs

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#2983]
https://www.nuget.org/Admin/SupportRequest/Save Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by xavierdecoster** [comment]
ah, good catch! it should not be in the dropdownlist for that dialog, as it is a 'virtual' state (new, in progress, waiting for customer, are all 'unresolved'). Will fix!

**Comment by skofman1** [comment]
Actually it happens when you try to save a support request with status "unresolved". Sorry for the poor description

**Comment by xavierdecoster** [comment]
That's what I understood, and that's what I replied too :)
