### ISSUE TITLE
Support dashboard is missing the email for some users

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#2984]
Some of the dashboard requests show up as from Anonymous and clicking the email button does not input an email address. 

I can see the original support email which does have the address so I know this info exists.

**Comment by maartenba** [comment]
@xavierdecoster

**Comment by xavierdecoster** [comment]
I know some of the support forms are submitted anonymously, so I'm surprised the email address pops up somewhere else. Will check.
