### ISSUE TITLE
Bad servername.cache.bin make server to not start

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2985]
_From @Tasteful on April 12, 2016 8:47_

I run out of discspace on my nuget-server and when I added a new package (without knowing about discspace) the servername.cache.bin was persisted in some bad state. After deleting some items on the disc I need manually delete servername.cache.bin to get the nuget-server to start again.

It should be good if nuget-server can recover itself if the cache-file is bad.

Using NuGet.Server.2.10.2 package as "nuget-server" and running that on Windows 2012r2.

_Copied from original issue: NuGet/Home#2526_

**Comment by maartenba** [comment]
Fixed in latest (prerelease) package of NuGet.Server - can you validate?
https://www.nuget.org/packages/NuGet.Server/2.10.3-master-0005

**Comment by Tasteful** [comment]
I have tested with a corrupt cache.bin-file and the site is now recovered as expected.

**Comment by neethasp** [comment]
I use Nuget v3.5.0-beta2 for packing nugets. Upon upgrading to NuGet.Server 2.11.2 to resolve this issue, it was found that the package fetching operation failed with error  "Method not found: '!!0[] System.Array.Empty()'". Could it be due the fact that my build server has .NET 4.5.2 installed which may not be compatible with NuGet.Server 2.11.2 (as per its specification in https://www.nuget.org/packages/NuGet.Server/2.11.2) ?

**Comment by maartenba** [comment]
You will need 4.6.1
