### ISSUE TITLE
NuGet.Server - default page instructions are for FLAT, not hierarchical 

### ISSUE THREAD

**Issue by shanselman** [NuGet/NuGetGallery#2986]
NuGet.Server v2.1 instructions on its default page when it starts up say:

> To add packages to the feed put package files (.nupkg files) in the folder C:\LocalNuGet

But since it's moved from flat to hierarchical, those instructions should be changed, right? 

Can you run nuget init source dest multiple times? Is THAT the recommended way to load files into the packages folder for NuGet.Server?

**Comment by maartenba** [comment]
Dropping files into the folder should work. NuGet.Server will pick them up on next app start (and with a file watcher) and put them in the hierarchical format.
