### ISSUE TITLE
NuGet.Server is case sensitive for Packages(Id='',Version='') endpoint

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#2988]
NuGet.Server is case sensitive for the `/Packages(Id='',Version='')` endpoint. It should be case-insensitive like nuget.org.

**Product**: NuGet.Server
**Version**: 2.10.2

Created a basic NuGet.Server instance by following [the instructions on the docs site](http://docs.nuget.org/create/hosting-your-own-nuget-feeds#step-2:-install-the-nuget.server-package). I then add a Newtonsoft.Json .nupkg to the packages folder.

I launch the website in VS and try things out:

`http://localhost:6134/nuget/Packages(Id='Newtonsoft.Json',Version='5.0.4')` - Succeeds.
`http://localhost:6134/nuget/Packages(Id='newtonsoft.json',Version='5.0.4')` - Fails with a 404.

`/FindPackagesById()` works just fine. I have not tried any other endpoints.

`http://localhost:6134/nuget/FindPackagesById()?id=%27Newtonsoft.Json%27` - Succeeds.
`http://localhost:6134/nuget/FindPackagesById()?id=%27newtonsoft.json%27` - Succeeds.

This effects nuget.exe 2.8.6 since seems to do a `/FindPackagesById()` (works) then `/Packages(Id='',Version='')` (fails) when installing.

**Comment by joelverhagen** [comment]
BTW, I am executing this in NuGet.exe to reproduce this.
```
nuget.exe install newtonsoft.json -source http://localhost:6134/nuget
```

Here's the Fiddler trace on 2.8.6, 3.3.0, and 3.4.3.343 (prerelease):
[NuGet.Server.saz.zip](https://github.com/NuGet/NuGetGallery/files/220059/NuGet.Server.saz.zip)

**Comment by maartenba** [comment]
Seems to only be (Id,Version) - other methods unaffected.

Fixed in latest (prerelease) package of NuGet.Server - can you validate?
https://www.nuget.org/packages/NuGet.Server/2.10.3-master-0005

(if confirmed I'l make it a stable release afterwards)

**Comment by joelverhagen** [comment]
> Fixed in latest (prerelease) package of NuGet.Server - can you validate?

Validated on https://www.nuget.org/packages/NuGet.Server/2.10.3. Works great. Thanks!
