### ISSUE TITLE
Make it possible to unsubscribe to a subset of the emails sent by the gallery

### ISSUE THREAD

**Issue by FransBouma** [NuGet/NuGetGallery#2991]
Every time I release a new build, I push 10 packages and I receive 10 emails and the company account also gets 10 emails that the packages are pushed. All great, except, I don't want these. Now, I can unsubscribe on the nuget gallery website, but that unsubscribes me for from all email, which is not what I want of course.

Please implement a way to unsubscribe/opt-out from these notification emails (and potentially other emails) so it's more flexible for the user to choose what email to receive from nuget. 

Thanks.

**Comment by xavierdecoster** [comment]
Our next deployment will have an opt-out option for package-push notification emails https://github.com/NuGet/NuGetGallery/pull/2989

**Comment by FransBouma** [comment]
great!

**Comment by xavierdecoster** [comment]
This is now live! 
![image](https://cloud.githubusercontent.com/assets/880728/14563499/8e71151a-0322-11e6-8c95-e6e12ab14a4e.png)
