### ISSUE TITLE
Possible issue with site certificate?

### ISSUE THREAD

**Issue by gjkhw** [NuGet/NuGetGallery#2993]
I was having some difficulty connecting to nuget.org from my local machine (noted here earlier: https://github.com/NuGet/NuGetGallery/issues/2700#issuecomment-208505703).

My account had been created with a default policy to require Online Certificate Status Protocol (OCSP) validation of certificates "if certificate indicates" per https://support.apple.com/kb/PH20126?viewlocale=en_US&locale=en_US .  A default OS X user account is created with the "Best attempt" policy.  Switching my account to "Best attempt" per Apple's recommendation resolves my connectivity issues.  

I suspect that you could make a change to support OSCP validation.  This is not my forte, so here's a long-winded explanation:

It's interesting that the error message when OSCP is required to validate the certificate is "untrusted CRL".  I noticed that the certificate that your site uses as a root for the nuget.org certificate is what appears to be an older version of the certificate called "Microsoft IT SSL SHA2".  Your version expires December 19, 2017.

The most recent certificate by that name appears to be available from Microsoft's PKI site here: https://www.microsoft.com/pki/mscorp/cps/ . That version has a later expiry date: May 7, 2018.

The newer version of the "Microsoft IT SSL SHA2" certificate validates properly when I change my local certificate settings back to requiring OSCP.

That leads me to think that you might want to re-sign nuget.org's certificate, assuming that you can do so with the newer "Microsoft IT SSL SHA2" certificate.

That's all just guesswork.  Still, I hope that it's useful.

**Comment by maartenba** [comment]
Very useful! Looking into it.
