### ISSUE TITLE
On building one NuGet.org CSS Layout

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#2994]
NuGet.org consists of several APIs & web apps and currently the "main" page NuGet.org looks a bit outdated - let's see if we could give the site a facelift.

Disclaimer: I don't know if the team is currently rebuilding the site or if a designer is now working on the site and I'm by far not a designer or an expert in CSS. 

I thought it would be nice to see if the existing - fresher looking - blog/docs/status/dist-NuGet.org sites could be combined to build one common css layout. so I made this repository: https://github.com/robertmuehsig/NuGetCss/tree/gh-pages

The repo contains the HTML from the blog/docs/status/dist frontpages and they share already one common nuget.css, but each site has it's own flavor and for example you can't use the smaller "boxes" from the distribution page inside the blog page, because each specialized css does affect the other one.
Also each specialized css file seems to contain a lot of duplicated styles, which is not ideal.

My idea would be to move the common parts to the nuget.css and see if those specialized stuff could be seen as small components, that can be combined different ways. 

The final goal would be to build a "styleguide" or html-component cookbook for the nuget.css - something like http://getbootstrap.com/components/#breadcrumbs 

This should lay the groundwork for a modern nuget.org.

Is this worth looking into or maybe you are already doing something like this? What do you think?

**Comment by maartenba** [comment]
Redesign is on our roadmap, but no definite date there... Ideally I'd like to go full bootstrap, but that's a personal opinion ☺ 

I wouldn't put the effort in right now, it is on our radar but there are more urgent things at the moment.

**Comment by robertmuehsig** [comment]
Sounds good to me. Would love to help when you are working on it.

**Comment by robertmuehsig** [comment]
After the pretty nice redesign this is obsolete - closing this myself ;)
