### ISSUE TITLE
NuGet.Server custom IPackageAuthenticationService fiasco

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2996]
_From @kkm000 on April 19, 2016 18:2_

We run a `NuGet.Server`-based server on our intranet. The server has a custom `IPackageAuthenticationService`, that authorizes package publishing through ASP.NET role (which is further defined through Active Directory group membership). I tried to upgrade the server to `NuGet.Server` v2.10.x (latest), and my attempt semi-failed.

Out current code uses `NuGet.Server`  v2.8.5, and this version uses Ninject to compose services, so all I had to do was

```c#
[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(SmartAction.NuGetServer.Initializers), "Start")]
namespace SmartAction.NuGetServer {
  public static class Initializers {
    public static void Start() {
      NinjectBootstrapper.Kernel.Rebind<IPackageAuthenticationService>().To<MyOwnFancyPackageAuthenticationService>();
    }
. . . 
```

The new version seems to have get ridden of Ninject in favor of semi-opaque `ServiceResolver`. Now, short of forking the Server's source, I found the following way to hack my authentication service in (sans locking entirely -- I am omitting locking for clarity)
```c#
public class MyServiceResolver : IServiceResolver {
  static DefaultServiceResolver default_resolver_ = new DefaultServiceResolver();
  IPackageService package_service_ = null;
  
  public object Resolve(Type type) {
    if (type == typeof(IPackageService)) {
      if (package_service_ == null) {
        var repo_service = (IServerPackageRepository)default_resolver_.Resolve(typeof(IServerPackageRepository));
        package_service_ = new PackageService(repo_service, new MyOwnFancyPackageAuthenticationService());
      }
      return package_service_;
    }
  }
}
```
and then call `ServiceResolver.SetServiceResolver()` with the instance of this thing on startup.

Am I doing it wrong? There is something uneasy about this code, as it is entirely based on the knowledge of the internal structure of the `DefaultServiceResolver`, and on other assumptions which may or may not be valid even after a minor Server package upgrade.

_Copied from original issue: NuGet/Home#2611_

**Comment by maartenba** [comment]
We decided to drop NInject as all we have for the default NuGet.Server is three services that need resolving. You could implement an IServiceResolver that makes use of NInject or any other container and indeed set it using SetServiceResolver.

**Comment by yishaigalatzer** [comment]
Note that Ninject was one of the main performance killers on nuget.org, and we moved to use autofac (or potentially others in the future).

**Comment by kkm000** [comment]
> all we have for the default NuGet.Server is three services that need resolving

This is not exactly true. There is at least four that **need** resolving, and only three that **are** resolved. I would not have to write the whole messy workaround otherwise. The default resolver does not resolve `IPackageAuthenticationService`; this `Service` is no longer a *service*. Rather, there is essentially one hard-coded implementation of this interface. I was able to replace it by hook and by crook, and I still cannot believe I did...

Here's a request: Is it possible to make `IPackageAuthenticationService` also resolvable through the same new `ServiceResolver`? (And, in parentheses, is using ASP.NET role or Windows authentication so unusual that no one but I is asking for it?)

**Comment by yishaigalatzer** [comment]
You can always send a pull request if you know exactly what you want. The goal should be that files delivered by the package are not altered by the end user (or mostly so), such that updated are smooth

**Comment by maartenba** [comment]
Just pushed an update that resolves the `IPackageAuthenticationService` as well. The NuGet.Server code indeed does not resolve it as it's only used by `PackageService` (which in our case is a singleton if you look at it from the resolver side).

You could create a custom `IServiceResolver` that instantiates all these per request (e.g. per OData call / package download/upload)
