### ISSUE TITLE
Unable to run Migration "201603151731262_AddIndexForPackageDeletes" on LocalDb

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#2997]
I just tried to update my dev-environment and needed to update the database and run "Update-Database -StartUpProjectName NuGetGallery -ConfigurationTypeName MigrationsConfiguration"

Sadly it failed, because the migration [201603151731262_AddIndexForPackageDeletes](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Migrations/201603151731262_AddIndexForPackageDeletes.cs#L9) contains a SQL statement which is only available on SQL Enterprise:

    Applying explicit migration: 201603151731262_AddIndexForPackageDeletes.
    System.Data.SqlClient.SqlException (0x80131904): Online index operations can only be performed in Enterprise edition of SQL Server.

Current SQL Migration Script:

    Sql("IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'nci_wi_Packages_Deleted' AND object_id = OBJECT_ID('Packages')) CREATE NONCLUSTERED INDEX [nci_wi_Packages_Deleted] ON [dbo].[Packages] ([Deleted], [Listed]) INCLUDE ([Description], [FlattenedDependencies], [IsPrerelease], [PackageRegistrationKey], [Tags], [Version]) WITH (ONLINE = ON)");

Working SQL Script:

    Sql("IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'nci_wi_Packages_Deleted' AND object_id = OBJECT_ID('Packages')) CREATE NONCLUSTERED INDEX [nci_wi_Packages_Deleted] ON [dbo].[Packages] ([Deleted], [Listed]) INCLUDE ([Description], [FlattenedDependencies], [IsPrerelease], [PackageRegistrationKey], [Tags], [Version]);

I guess you had a good reason for the "WITH (ONLINE = ON)"), but this leads to problems with non-enterprise environments.

**Comment by maartenba** [comment]
Feel free to PR 😏

**Comment by robertmuehsig** [comment]
Insert "I have no idea what I'm doing"-img here - PR submitted :+1:

**Comment by maartenba** [comment]
"WITH ONLINE=ON" basically is non-blocking when running on production, the other alternative will grab a lock and make things go bad on our production site :)

Thanks for the fix!

**Comment by robertmuehsig** [comment]
But when you run the same migration now on production things will go bad, right? Or is this already applied and therefor is not a problem anymore?

**Comment by maartenba** [comment]
Already applied and thus no more issue.
