### ISSUE TITLE
Documentation error for relative paths in config files

### ISSUE THREAD

**Issue by mark-zhou** [NuGet/NuGetGallery#3001]
On this page: http://docs.nuget.org/consume/nuget-config-settings

It states:

Note
Relative path is only relative to the solution folder.

That's not accurate. It's actually relative to the the location of Nuget.config. I tested with both command line tool (2.7 and 3.3) and VSIX extensions (VS 2013 and 2015), by placing solution and config on different directories. The actual behavior is more desirable because it allows us to check in one config file at the root of our source tree and redirect local repository to a shared location. But could you update the doc? Thanks.

**Comment by harikm86** [comment]
@skofman1  has a fix for this

**Comment by skofman1** [comment]
@mark-zhou , thanks for the feedback. Fixed.

**Comment by mark-zhou** [comment]
Wow. That was fast. Thanks!
