### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by holidaycottages** [NuGet/NuGetGallery#3007]
Hello,

Have followed all instructions, works fine locally, but when I upload to the server it just wants to redirect forever.

See example url below.

I have only changed in the config where the SQL DB lives.

/users/account/LogOn?ReturnUrl=%2Fusers%2Faccount%2FLogOn%3FReturnUrl%3D%252Fusers%252Faccount%252FLogOn%253FReturnUrl%253D%25252Fusers%25252Faccount%25252FLogOn%25253FReturnUrl%25253D%2525252Fusers%2525252Faccount%2525252FLogOn%2525253FReturnUrl%2525253D%252525252Fusers%252525252Faccount%252525252FLogOn%252525253FReturnUrl%252525253D%25252525252Fusers%25252525252Faccount%25252525252FLogOn%25252525253FReturnUrl%25252525253D%2525252525252Fusers%2525252525252Faccount%2525252525252FLogOn%2525252525253FReturnUrl%2525252525253D%252525252525252Fusers%252525252525252Faccount%252525252525252FLogOn%252525252525253FReturnUrl%252525252525253D%25252525252525252Fusers%25252525252525252Faccount%25252525252525252FLogOn%25252525252525253FReturnUrl%25252525252525253D%2525252525252525252Fusers%2525252525252525252Faccount%2525252525252525252FLogOn%2525252525252525253FReturnUrl%2525252525252525253D%252525252525252525252Fusers%252525252525252525252Faccount%252525252525252525252FLogOn%252525252525252525253FReturnUrl%252525252525252525253D%25252525252525252525252Fusers%25252525252525252525252Faccount%25252525252525252525252FLogOn%25252525252525252525253FReturnUrl%25252525252525252525253D%2525252525252525252525252Fusers%2525252525252525252525252Faccount%2525252525252525252525252FLogOn%2525252525252525252525253FReturnUrl%2525252525252525252525253D%252525252525252525252525252Fusers%252525252525252525252525252Faccount%252525252525252525252525252FLogOn%252525252525252525252525253FReturnUrl%252525252525252525252525253D%25252525252525252525252525252Fusers%25252525252525252525252525252Faccount%25252525252525252525252525252FLogOn%25252525252525252525252525253FReturnUrl%25252525252525252525252525253D%2525252525252525252525252525252Fusers%2525252525252525252525252525252Faccount%2525252525252525252525252525252FLogOn%2525252525252525252525252525253FReturnUrl%2525252525252525252525252525253D%252525252525252525252525252525252Fusers%252525252525252525252525252525252Faccount%252525252525252525252525252525252FLogOn%252525252525252525252525252525253FReturnUrl%252525252525252525252525252525253D%25252525252525252525252525252525252Fusers%25252525252525252525252525252525252Faccount%25252525252525252525252525252525252FLogOn%25252525252525252525252525252525253FReturnUrl%25252525252525252525252525252525253D%2525252525252525252525252525252525252Fusers%2525252525252525252525252525252525252Faccount%2525252525252525252525252525252525252FLogOn%2525252525252525252525252525252525253FReturnUrl%2525252525252525252525252525252525253D%252525252525252525252525252525252525252Fusers%252525252525252525252525252525252525252Faccount%252525252525252525252525252525252525252FLogOn%252525252525252525252525252525252525253FReturnUrl%252525252525252525252525252525252525253D%25252525252525252525252525252525252525252F

**Comment by maartenba** [comment]
Looks like a misconfiguration in IIS or another auth mechanism in place.

**Comment by skofman1** [comment]
Sometimes opening the browser in "Incognito" mode helps.

**Comment by holidaycottages** [comment]
@maartenba somehow basic auth got turned on! Cheers for the pointer!
