### ISSUE TITLE
Broken Link on Ecosystem: NuGet Command Line Reference

### ISSUE THREAD

**Issue by bluerv** [NuGet/NuGetGallery#3008]
On this page:

https://docs.nuget.org/Contribute/Ecosystem

In the section "NuGet Command Line tool"

There is a link "NuGet Command Line Reference" to "https://docs.nuget.org/Contribute/Command-Line-Reference"

That results in a 404.  Not sure where that moved to, so I cannot update it.

**Comment by harikm86** [comment]
Thanks for pointing it out. Fixed it in https://github.com/NuGet/NuGetDocs/commit/2eb9bfc011db26c1f396b381be4aed4852d41167
