### ISSUE TITLE
Can't upload xBehave package due to "title similar to ID of existing package"

### ISSUE THREAD

**Issue by adamralph** [NuGet/NuGetGallery#3012]
ref: https://twitter.com/adamralph/status/725372223586992129

![image](https://cloud.githubusercontent.com/assets/677704/14861573/25025e28-0cae-11e6-8610-0d718e53222c.png)

The title of this package has *always* been "xBehave.net". See the history at https://www.nuget.org/packages/Xbehave/

I guess some change has been put into the gallery which now bans me from uploading the package with this title. I can understand the motivation, but this shouldn't apply to packages *which have always had this title!*

In order to release the package, I hacked the nupkg locally to make the title "xBehave" but this really isn't acceptable. Note that this happened after I had already uploaded 2.1 of https://www.nuget.org/packages/Xbehave.Core so I had to take what ever measure necessary to upload 2.1 of https://www.nuget.org/packages/Xbehave/ which, unfortunately, meant changing the title. The gallery web UI also won't let me change the package title back to what it should be, giving a similar error message.

Note also, that in this case, the refusal is due to this incorrectly uploaded package (by me) which I immediately de-listed when I realised it has the wrong ID - https://www.nuget.org/packages/Xbehave.net - I would have deleted the package immediately, but the gallery won't let me do that.

**Comment by adamralph** [comment]
@rrelyea [says](https://github.com/NuGet/Home/issues/2670#issuecomment-216361295)

> We enforce a strict policy on this...in which the title of a package cannot match the ID of another package.
> You may either change it locally, or on the server for packages that already exist.
This change was made to address major security concerns of users about being confused between 2 packages...so we hope you understand why we won't allow a back door to do this.

The first problem with this is that this wasn't always the rule. By introducing it now, you've enforced the rule in retrospect for existing packages (like https://www.nuget.org/packages/Xbehave/) which can no longer upload new versions without changing their title.

However, the biggest problem is with this is that for any package which does not have the title as it's ID, and where that title is a valid string to use an ID, that package is at risk of someone uploading a new package with that title as it's ID which, again, will block the original package from ever being uploaded again without changing its title.

I'll give another example: https://www.nuget.org/packages/xunit/ - this package has always had "xUnit.net" as its title. All I have to do is upload a new package today with the ID "xUnit.net" and boom! The next deployment of https://www.nuget.org/packages/xunit/ will fail! /cc @bradwilson

**Comment by yishaigalatzer** [comment]
@adamralph yes, we have considered these issues, but we believe that this rule is right in most cases, and the overall behavior is correct. The previous behavior was sad and confusing to the community. I suggest changing back the title to be exactly like the ID in your case.

FYI we are considering another option to completely remove titles from the site and visual studio.

**Comment by adamralph** [comment]
> FYI we are considering another option to completely remove titles from the site and visual studio.

:+1: Ultimately, this is the correct solution.

IMHO the current banning of titles similar to other ID's is an awkward half-way house. The sooner we get the correct solution, the better.
