### ISSUE TITLE
Getting Unable to find package error

### ISSUE THREAD

**Issue by Ananthyogesh** [NuGet/NuGetGallery#3016]
![nugeterror](https://cloud.githubusercontent.com/assets/4208446/15007547/96e96042-11f7-11e6-9d74-55a593f8ae80.PNG)
I am trying to install package from nuget . Getting **Unable to find paackage error.**

**Package details: Install-Package EnterpriseLibrary.TransientFaultHandling**

**Comment by skofman1** [comment]
What is the NuGet feed you are using? Can you provide the list of package sources configured?

**Comment by wallymathieu** [comment]
I've experienced some problems with timeouts. While browsing the feed api directly I've gotten the following info:
https://gist.github.com/wallymathieu/99a941d11c4aa9ec1592d9b30eee6974

**Comment by yishaigalatzer** [comment]
This looks like a CDN issue in your area. Can you please let us know if the issue got resolved from your end?

**Comment by zhili1208** [comment]
@wallymathieu According to our CDN provider, the CDN issue is resolved, Can you confirm the issue is resolved from your side? thanks

**Comment by wallymathieu** [comment]
The CDN issue looks like it's resolved. 👍

**Comment by yishaigalatzer** [comment]
Thanks, and sorry about the trouble. We are in discussions for a better CDN solution
