### ISSUE TITLE
Packages in Gallery appear as not indexed

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3017]
We are seeing a strange behavior that some old packages in the Gallery appear as not indexed.

![1](https://cloud.githubusercontent.com/assets/16807822/15032198/4ed6a064-1213-11e6-9847-b9aefb01ed2b.jpg)

**Comment by skofman1** [comment]
Rollback mitigated the issue.

**Comment by yishaigalatzer** [comment]
@skofman1 would be cool to include the commit as well as the PR
