### ISSUE TITLE
https://www.nuget.org/downloads is not resolving anymore

### ISSUE THREAD

**Issue by harikm86** [NuGet/NuGetGallery#3018]
Navigate to https://www.nuget.org/downloads

Shows 404.

**Comment by skofman1** [comment]
This is because the version that contains this change was rolled back. Which also caused this issue: https://github.com/NuGet/NuGetGallery/issues/3017

**Comment by harikm86** [comment]
:(. Can we update just this specifically?

**Comment by yishaigalatzer** [comment]
We are rolling back shortly

**Comment by harikm86** [comment]
Thanks :)
