### ISSUE TITLE
Readme steps are not up to date, cannot build project

### ISSUE THREAD

**Issue by DamianBis** [NuGet/NuGetGallery#3019]
Trying to follow read me to build project and getting errors about versions not existing from Nuget

C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Common'.
C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Frameworks'.
C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging'.
C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core'.
C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core.Types'.
C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Versioning'.
C:\NuGetGallery-master\build.msbuild(57,9): error MSB3073: The command ""C:\NuGetGallery-master\\.nuget\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "" -NonInter
active" exited with code 1.
Done Building Project "C:\NuGetGallery-master\build.msbuild" (default targets) -- FAILED.

Build FAILED.

"C:\NuGetGallery-master\build.msbuild" (default target) (1) ->
(RestorePackages target) ->
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Common'.
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Frameworks'.
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging'.
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core'.
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core.Types'.
  C:\NuGetGallery-master\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Versioning'.
  C:\NuGetGallery-master\build.msbuild(57,9): error MSB3073: The command ""C:\NuGetGallery-master\\.nuget\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "" -NonInt
eractive" exited with code 1.

    0 Warning(s)
    7 Error(s)

**Comment by maartenba** [comment]
Seems these packages are gone from our nightlies feed and we should upgrade them.

**Comment by michalhainc** [comment]
I came accross the same situation

**Comment by yishaigalatzer** [comment]
@maartenba lets pin the packages we use, so it doesn't break the builds? Is our internal build broken as well?

**Comment by maartenba** [comment]
It is not, the dev branch should have newer (pinned) versions. Will look at this one next week.

**Comment by DamianBis** [comment]
Dev branch is the same

C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Common'.
C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Frameworks'.
C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging'.
C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core'.
C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core.Types'.
C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Versioning'.
C:\NuGetGallery-dev\build.msbuild(57,9): error MSB3073: The command ""C:\NuGetGallery-dev\\.nuget\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "" -NonInteractive
" exited with code 1.
Done Building Project "C:\NuGetGallery-dev\build.msbuild" (default targets) -- FAILED.


Build FAILED.

"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
(RestorePackages target) ->
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Common'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Frameworks'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Packaging.Core.Types'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error : Unable to find version '3.4.0-beta-632' of package 'NuGet.Versioning'.
  C:\NuGetGallery-dev\build.msbuild(57,9): error MSB3073: The command ""C:\NuGetGallery-dev\\.nuget\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "" -NonInteracti
ve" exited with code 1.

**Comment by maartenba** [comment]
Can you try the latest `dev` branch?

**Comment by AndyButland** [comment]
Just ran into this same issue - can confirm `dev` branch restores it's packages OK.

**Comment by maartenba** [comment]
Thanks @AndyButland - feel free to clone `dev` for now until we merge to master.

**Comment by DamianBis** [comment]
there are issues still with teh build

Client\SearchClient.cs(158,93): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj]
Done Building Project "C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj" (default targets) -- FAILED.

Project "C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (4) is building "C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj" (6) on node 1 (default targets).
CoreResGen:
  No resources are out of date with respect to their source files. Skipping resource generation.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
GetGitMetadata:
  Extracted Git Metadata
   Branch = nobranch
   CommitId = HEAD
   RepositoryUrl =
CoreCompile:
  C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:C:\NuGetGallery-dev\packages\entityframe
  work.6.1.3\lib\net45\EntityFramework.dll /reference:C:\NuGetGallery-dev\packages\entityframework.6.1.3\lib\net45\EntityFramework.SqlServer.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft
  \Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll" /reference:C:\NuGetGallery-dev\packages\Microsoft.Data.Edm.5.6.5-beta\lib\net40\Microsoft.Data.Edm.dll /reference:C:\NuGetGallery-dev\packages\Microsoft.D
  ata.OData.5.6.5-beta\lib\net40\Microsoft.Data.OData.dll /reference:C:\NuGetGallery-dev\packages\Microsoft.Data.Services.Client.5.6.5-beta\lib\net40\Microsoft.Data.Services.Client.dll /reference:C:\NuGetGaller
  y-dev\packages\Microsoft.Web.Xdt.2.1.1\lib\net40\Microsoft.Web.XmlTransform.dll /reference:C:\NuGetGallery-dev\packages\Microsoft.WindowsAzure.ConfigurationManager.3.1.0\lib\net40\Microsoft.WindowsAzure.Confi
  guration.dll /reference:C:\NuGetGallery-dev\packages\WindowsAzure.Storage.4.3.0\lib\net40\Microsoft.WindowsAzure.Storage.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFra
  mework\v4.5.2\mscorlib.dll" /reference:C:\NuGetGallery-dev\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Common.3.5.0-beta-1208\lib\net45\NuGet.Com
  mon.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Frameworks.3.5.0-beta-1208\lib\net45\NuGet.Frameworks.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Logging.3.5.0-beta-1160\lib\net45\NuGet.Logging.dl
  l /reference:C:\NuGetGallery-dev\packages\NuGet.Packaging.Core.3.5.0-beta-1208\lib\net45\NuGet.Packaging.Core.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Packaging.Core.Types.3.5.0-beta-1208\lib\net45\N
  uGet.Packaging.Core.Types.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Packaging.3.5.0-beta-1208\lib\net45\NuGet.Packaging.dll /reference:C:\NuGetGallery-dev\packages\NuGet.Versioning.3.5.0-beta-1208\lib
  \net45\NuGet.Versioning.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.ComponentModel.DataAnnotations.dll" /reference:"C:\Program Files (x86)\Refer
  ence Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Configuration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:
  "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewo
  rk\v4.5.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.Services.Client.dll" /reference:"C:\Program Files (x86)\Reference Assemb
  lies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.IO.Compression.dll" /reference:C:\NuGetGallery
  -dev\packages\System.Spatial.5.6.5-beta\lib\net40\System.Spatial.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Web.dll" /reference:"C:\Program Fil
  es (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /de
  bug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\NuGetGallery.Core.dll /subsystemversion:6.00 /resource:obj\Debug\NuGetGallery.Strings.resources /target:library /warnaserror+ /utf8output Auditing\Aud
  itEntry.cs Auditing\AuditActor.cs Auditing\AuditingService.cs Auditing\AuditRecord.cs Auditing\CloudAuditingService.cs Auditing\PackageAuditRecord.cs Auditing\UserAuditRecord.cs CoreConstants.cs CredentialTyp
  es.cs Completion.cs DisposableAction.cs Entities\Credential.cs Entities\CuratedFeed.cs Entities\CuratedPackage.cs Entities\PackageDelete.cs Entities\EmailMessage.cs Entities\EntitiesConfiguration.cs Entities\
  EntitiesContext.cs Entities\EntityException.cs Entities\Interception\ObjectMaterializedInterception.cs Entities\Interception\ObjectMaterializedInterceptingDbContext.cs Entities\EntityRepository.cs Entities\Ga
  llerySetting.cs Entities\IEntitiesContext.cs Entities\IEntity.cs Entities\Interception\IObjectMaterializedInterceptor.cs Entities\IEntityRepository.cs Entities\Package.cs Entities\PackageAuthor.cs Entities\Pa
  ckageDependency.cs Entities\PackageEdit.cs Entities\PackageFramework.cs Entities\PackageHistory.cs Entities\PackageLicense.cs Entities\PackageLicenseReport.cs Entities\PackageOwnerRequest.cs Entities\PackageR
  egistration.cs Entities\ReadOnlyModeException.cs Entities\Role.cs Entities\User.cs PackageReaderCoreExtensions.cs Packaging\InvalidPackageException.cs Packaging\ManifestEdit.cs Packaging\ManifestValidator.cs
  Packaging\NupkgRewriter.cs Packaging\PackageIdValidator.cs Packaging\PackageMetadata.cs Packaging\PackageStreamMetadata.cs Properties\AssemblyInfo.cs NuGetVersionExtensions.cs StreamExtensions.cs Strings.Desi
  gner.cs Unit.cs C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\\CommonAssemblyInfo.cs "C:\Users\damian.bisignano\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs" C:\Users
  \damian.bisignano\AppData\Local\Temp\a1b0708961d947208a73caeb224193c2_VersionInfo.cs
Auditing\AuditActor.cs(48,17): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
Auditing\AuditingService.cs(74,33): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
Auditing\PackageAuditRecord.cs(38,20): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
Packaging\PackageIdValidator.cs(38,45): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
Done Building Project "C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj" (default targets) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (default targets) -- FAILED.

Project "C:\NuGetGallery-dev\NuGetGallery.sln" (3) is building "C:\NuGetGallery-dev\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccproj" (11) on node 1 (default targets).
C:\NuGetGallery-dev\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccproj(87,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.Win
dowsAzure.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "C:\NuGetGallery-dev\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccproj" (default targets) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\NuGetGallery.sln" (Build target(s)) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default targets) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\build.msbuild" (default targets) -- FAILED.


Build FAILED.

"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
"C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj" (default target) (5) ->
(CoreCompile target) ->
  Client\SearchClient.cs(158,93): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj]


"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
"C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj" (default target) (6) ->
  Auditing\AuditActor.cs(48,17): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
  Auditing\AuditingService.cs(74,33): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
  Auditing\PackageAuditRecord.cs(38,20): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]
  Packaging\PackageIdValidator.cs(38,45): error CS1056: Unexpected character '$' [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj]


"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccproj" (default target) (11) ->
  C:\NuGetGallery-dev\src\NuGetGallery.Cloud\NuGetGallery.Cloud.ccproj(87,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.W
indowsAzure.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    6 Error(s)

**Comment by DamianBis** [comment]
if i DON'T specify version when running msbuild it errors out on the sln file


C:\NuGetGallery-dev>msbuild build.msbuild
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/05/2016 8:32:13 AM.
Project "C:\NuGetGallery-dev\build.msbuild" on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forc
ed to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
RestorePackages:
  Restoring packages ...
  "C:\NuGetGallery-dev\\.nuget\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "" -NonInteractive
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
Project "C:\NuGetGallery-dev\build.msbuild" (1) is building "C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (2) on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forc
ed to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
RestorePackages:
  Restoring packages ...
  "C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\\nuget.exe" restore -Source "https://www.nuget.org/api/v2;https://www.myget.org/F/nugetbuild/" "C:\NuGetGallery-dev\\NuGetGallery.sln" -NonInter
  active
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
Project "C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (2) is building "C:\NuGetGallery-dev\NuGetGallery.sln" (3) on node 1 (Build target(s)).
C:\NuGetGallery-dev\NuGetGallery.sln(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
Done Building Project "C:\NuGetGallery-dev\NuGetGallery.sln" (Build target(s)) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default targets) -- FAILED.

Done Building Project "C:\NuGetGallery-dev\build.msbuild" (default targets) -- FAILED.


Build FAILED.

"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
  C:\NuGetGallery-dev\NuGetGallery.sln(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:06.69

**Comment by DamianBis** [comment]
I've updated build.cmd in my PC to use the most up to date msbuild exe on my pc and am getting past teh $ errors now.


  Building solution configuration "Debug|Any CPU".
Project "C:\NuGetGallery-dev\NuGetGallery.sln" (3) is building "C:\NuGetGallery-dev\src\NuGetGallery\Nu
GetGallery.csproj" (4) on node 1 (default targets).
Project "C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (4) is building "C:\NuGetGallery-dev
\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj" (5) on node 1 (default targets).
C:\NuGetGallery-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(97,5): error
MSB4127: The "EnsureBindingRedirects" task could not be instantiated from the assembly "C:\NuGetGallery
-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll". Please verify the task a
ssembly has been built using the same version of the Microsoft.Build.Framework assembly as the one inst
alled on your computer and that your host application is not missing a binding redirect for Microsoft.B
uild.Framework. Unable to cast object of type 'Roxel.BuildTasks.EnsureBindingRedirects' to type 'Micros
oft.Build.Framework.ITask'. [C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search
.Client.csproj]
C:\NuGetGallery-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(97,5): error
MSB4060: The "EnsureBindingRedirects" task has been declared or used incorrectly, or failed during cons
truction. Check the spelling of the task name and the assembly name. [C:\NuGetGallery-dev\src\NuGet.Ser
vices.Search.Client\NuGet.Services.Search.Client.csproj]
Done Building Project "C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Clien
t.csproj" (default targets) -- FAILED.

[[content removed]]


CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\NuGetGallery.Core.Facts.dll" to "bin\Debug\NuGetGallery.Core.Facts.dll".
  NuGetGallery.Core.Facts -> C:\NuGetGallery-dev\tests\NuGetGallery.Core.Facts\bin\Debug\NuGetGallery.C
  ore.Facts.dll
  Copying file from "obj\Debug\NuGetGallery.Core.Facts.pdb" to "bin\Debug\NuGetGallery.Core.Facts.pdb".
C:\NuGetGallery-dev\build\NuGetGallery.xunit.targets(14,9): error MSB4127: The "xunit" task could not b
e instantiated from the assembly "C:\NuGetGallery-dev\build\..\packages\NuGet.Services.Build.3.0.13\too
ls\xunit.runner.msbuild.dll". Please verify the task assembly has been built using the same version of
the Microsoft.Build.Framework assembly as the one installed on your computer and that your host applica
tion is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Xu
nit.Runner.MSBuild.xunit' to type 'Microsoft.Build.Framework.ITask'. [C:\NuGetGallery-dev\tests\NuGetGa
llery.Core.Facts\NuGetGallery.Core.Facts.csproj]
C:\NuGetGallery-dev\build\NuGetGallery.xunit.targets(14,9): error MSB4060: The "xunit" task has been de
clared or used incorrectly, or failed during construction. Check the spelling of the task name and the
assembly name. [C:\NuGetGallery-dev\tests\NuGetGallery.Core.Facts\NuGetGallery.Core.Facts.csproj]

[[content removed]]



Build FAILED.

"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (defa
ult target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
"C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Core.csproj" (default target) (6) ->
(Package target) ->
  EXEC : warning : '$(MSBuildThisFileDirectory)\CommonAssemblyInfo.cs' was included in the project but
the path could not be resolved. Skipping... [C:\NuGetGallery-dev\src\NuGetGallery.Core\NuGetGallery.Cor
e.csproj]


"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (defa
ult target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\src\NuGetGallery\NuGetGallery.csproj" (default target) (4) ->
"C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Search.Client.csproj" (default tar
get) (5) ->
(BclBuildEnsureBindingRedirects target) ->
  C:\NuGetGallery-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(97,5): erro
r MSB4127: The "EnsureBindingRedirects" task could not be instantiated from the assembly "C:\NuGetGalle
ry-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll". Please verify the task
 assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one in
stalled on your computer and that your host application is not missing a binding redirect for Microsoft
.Build.Framework. Unable to cast object of type 'Roxel.BuildTasks.EnsureBindingRedirects' to type 'Micr
osoft.Build.Framework.ITask'. [C:\NuGetGallery-dev\src\NuGet.Services.Search.Client\NuGet.Services.Sear
ch.Client.csproj]
  C:\NuGetGallery-dev\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(97,5): erro
r MSB4060: The "EnsureBindingRedirects" task has been declared or used incorrectly, or failed during co
nstruction. Check the spelling of the task name and the assembly name. [C:\NuGetGallery-dev\src\NuGet.S
ervices.Search.Client\NuGet.Services.Search.Client.csproj]


"C:\NuGetGallery-dev\build.msbuild" (default target) (1) ->
"C:\NuGetGallery-dev\packages\NuGet.Services.Build.3.0.13\tools\NuGet.Services.FullBuild.msbuild" (defa
ult target) (2) ->
"C:\NuGetGallery-dev\NuGetGallery.sln" (Build target) (3) ->
"C:\NuGetGallery-dev\tests\NuGetGallery.Core.Facts\NuGetGallery.Core.Facts.csproj" (default target) (10
) ->
(RunFacts target) ->
  C:\NuGetGallery-dev\build\NuGetGallery.xunit.targets(14,9): error MSB4127: The "xunit" task could not
 be instantiated from the assembly "C:\NuGetGallery-dev\build\..\packages\NuGet.Services.Build.3.0.13\t
ools\xunit.runner.msbuild.dll". Please verify the task assembly has been built using the same version o
f the Microsoft.Build.Framework assembly as the one installed on your computer and that your host appli
cation is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type '
Xunit.Runner.MSBuild.xunit' to type 'Microsoft.Build.Framework.ITask'. [C:\NuGetGallery-dev\tests\NuGet
Gallery.Core.Facts\NuGetGallery.Core.Facts.csproj]
  C:\NuGetGallery-dev\build\NuGetGallery.xunit.targets(14,9): error MSB4060: The "xunit" task has been
declared or used incorrectly, or failed during construction. Check the spelling of the task name and th
e assembly name. [C:\NuGetGallery-dev\tests\NuGetGallery.Core.Facts\NuGetGallery.Core.Facts.csproj]

    1 Warning(s)
    4 Error(s)

Time Elapsed 00:00:12.34

**Comment by maartenba** [comment]
@DamianBis can you do a fresh clone from the `dev` branch and run `git clean -xdf` after?

**Comment by DamianBis** [comment]
I downloaded as a zip from GIT (dev branch) so shouldn't be an issue there

**Comment by DamianBis** [comment]
Fresh download as zip from dev branch and still getting the xunit errors and The "EnsureBindingRedirects" task has been declared or used incorrectly, or failed during cons

**Comment by yishaigalatzer** [comment]
Do you have visual studio 2015 installed?

**Comment by DamianBis** [comment]
Yes. 2015 Enterprise edition

**Comment by yishaigalatzer** [comment]
Yes, we do have a build break right now. @skofman1 is working on fixing it

**Comment by skofman1** [comment]
The issue I was looking at was fixed in dev (it's the original missing packages issue you wrote about). Regarding the build issue your are seeing @DamianBis , I wasn't able to repro it. Best thing I can offer is making sure you are using build 14.0, and to clean the packages folder on your machine.

**Comment by DamianBis** [comment]
I have just done a fresh clone from master this morning and it has completed building. thank you for your help.

**Comment by DamianBis** [comment]
Only issue now is that i'm getting an error that the nugetgallery.cloud.ccproj is incompatible

I've checked and i have version 2.9 of the SDK which is what is referenced in the project.
