### ISSUE TITLE
Update NuGet from command line

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/NuGetGallery#3023]
Hi,

I have installed NuGet to a particular folder from command line by using following command.
install "Packagename"  -Version "version"  -Source "source"  -o "output directory".The package has been installed successfully . Now i need to update the packages in this folder for this i have used the following command
Update "Pacakge name"  -Source "source"  -RepositoryPath "directory in which previous packages are installed". But am unable to update since iam not having any packages.config or solution file. it shows the following message.
No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe.

SO how can i update packages without packages.config or solution folder

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2781
