### ISSUE TITLE
Enable-LocalTestMe script needs updating

### ISSUE THREAD

**Issue by Brendan-McCoy** [NuGet/NuGetGallery#3024]
The Enable-LocalTestMe script needs to be updated to reflect the possibility of users only installing the most recent SDKs and whatnot.

With VS 2015+Azure SDK 2.9, makecert is installed to
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Microsoft Azure Data Lake Tools for Visual Studio 2015\2.0.6000.0\CppSDK\SDK\bin

However, the script scans and sees entries for Windows SDK (which has entries just from VS installing small components), and incorrectly assumes the presence of makecert.

Thus, the script believes C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\x64\makecert.exe
is the location of make cert.

In lieu of updating the script, anyone who has just freshly installed VS and the SDKs may run the following at 4.ii instead of just the bare script.

```
.\tools\Enable-LocalTestMe.ps1 -MakeCertPath "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Microsoft Azure Data Lake Tools for Visual Studio 2015\2.0.6000.0\CppSDK\SDK\bin\makecert.exe"
```

**Comment by maartenba** [comment]
The script could be updated to also check this path if the first one fails. PR would be awesome ;-)

**Comment by maartenba** [comment]
Thanks for the PR :)
