### ISSUE TITLE
Package autocomlete do not work for local repository or "nuget/package-ids?partialId" returns 404

### ISSUE THREAD

**Issue by Kamarey** [NuGet/NuGetGallery#3031]
When using Package Manager Console, say Install-Package, and than pressing tab, autocomplete of available packages stopped to work **for my local package repository only** .
In Fiddler I see this request, which returns 404:
http://localhost/NuGetServer/nuget/package-ids?partialId=&includePrerelease=False
(while http://localhost/NuGetServer/nuget works)

I tried moving the NuGetServer app to different servers, tried autocomplete from different dev machines, created NuGetServer app from scratch (with both 2.8.6 and 2.10.3 NuGet.Server packages). Nothing helped

The problem originally found in VS2015.
VS2013 works, but it gets 404 for this requests too. This works as it sends another request right after:
http://localhost/NuGetServer/nuget/Packages()?$orderby=DownloadCount%20desc,...
which return required data

Other functionality, like NuGet UI for project, is working and show all packages available in repository

I think it something that happened on my side. But have no idea what can it be as I tested different server and client machines. May be it's client configuration... How can I debug this problem?

Thanks

**Comment by maartenba** [comment]
The autocomplete endpoint is not available in NuGet.Server. @rrelyea I guess this fallback is not in the VS2015 client?

**Comment by Kamarey** [comment]
I understand this is a bug in client of VS 2015. Right?

**Comment by maartenba** [comment]
@rrelyea can you check if this is in client?

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#2896
