### ISSUE TITLE
Publishing packages doesn't expand them as did "nuget init -expand"

### ISSUE THREAD

**Issue by Kamarey** [NuGet/NuGetGallery#3033]
I'm using new repository folder structure (described [here](http://blog.nuget.org/20150922/Accelerate-Package-Source.html) ). I converted the old structure to a new one using the **nuget init** command with the **-Expand** switch

Publish package is working from nuget push and code (Nuget.Core).
The problem that the **-Expand** command extracted existing packages, while publish doesn't. I would like to use expanded files in some scenarios so interesting if there is an issue with Nuget.Server, which handles publish requests?

Thanks

**Comment by maartenba** [comment]
`NuGet.exe push <package> -Source <server URL>`

**Comment by Kamarey** [comment]
Sorry, but didn't understand you comment. I mean why do you think I didn't tried it before opened this issue? An if you closed this issue - this means it's solved?

**Comment by maartenba** [comment]
Are yoy pusing to the server URL or to the server's package path? (http(s) or the full path to the server)?

**Comment by Kamarey** [comment]
To URL, so it will pass the Nuget server app. The direct access to packages folder is closed

**Comment by maartenba** [comment]
Then the server should expand. What version of the server are you using?

**Comment by Kamarey** [comment]
NuGet.Server: 2.10.3

**Comment by Kamarey** [comment]
By the say, what is the purpose of that expansion? Can't find any documentation.

**Comment by maartenba** [comment]
Here's the why: http://blog.nuget.org/20160113/Accelerate-your-NuGet.Server.html

Note that the server only expands the .nuspec and package hash, not the actual files in the package (as the server doesn't expose those directly anyway)

Are you looking into expanding all files?

**Comment by Kamarey** [comment]
I expecting it to expand the lib folder as well as done by the **nuget init -expand**. .nuspec and package hash expanded without -expand option. NuGet.Server do it right. Sorry for being unclear. So the only thing differ nuget init -expand from NuGet.Server is lib folder (in my case). 
nuget.exe help [says](https://docs.nuget.org/consume/command-line-reference#init-command-options):
_Expand - If provided, all the files in the package(s) are added to destination package source._

**Comment by maartenba** [comment]
Got it :) NuGet.Server does not support this further expansion, it just needs the .nuspec and hash.

**Comment by Kamarey** [comment]
Ok, if it's by design - no problems.
Thanks
