### ISSUE TITLE
NuGet.Server taking a long time to expand all packages 

### ISSUE THREAD

**Issue by gusgorman** [NuGet/NuGetGallery#3034]
When we copy multiple .nupkg files to our NuGet,Server directory it often takes a very long time to unpack them all and create the directory structure. I have just copied 3 in.... 15 minutes later the last of the 3 is still sitting there.

**Comment by maartenba** [comment]
Try using `NuGet.exe push` to add packages, or use `nuget.exe init` to make the expansion happen upfront - check http://blog.nuget.org/20150922/Accelerate-Package-Source.html

**Comment by gusgorman** [comment]
Maximum apologies if I am being stupid but I don't understand the relevance of that link... we are using an http server not a network share.

**Comment by maartenba** [comment]
The mention of the "init" command :-) You could of course also run nuget help init to get that info.
