### ISSUE TITLE
Enable CORS for API v3

### ISSUE THREAD

**Issue by rappen** [NuGet/NuGetGallery#3037]
Currently it is not possible to use the ``@id`` property of the returned repo from e.g. this request:
https://api-v2v3search-0.nuget.org/query?q=id:Cinteros.Xrm.FetchXMLBuilder
The ``@id`` property is returned as:
https://api.nuget.org/v3/registration0/cinteros.xrm.fetchxmlbuilder/index.json
Pasting it in a browser works fine, but trying with an ajax request returns ``parsererror Unexpected token :`` (if trying as jsonp and crossDomain) or ``Access-Control-Allow-Origin`` error otherwise.

I believe this could be fixed by enabling CORS for the returned API urls.
(I appologize if my terminology is not 100%)
Ref: #3036

**Comment by maartenba** [comment]
Looks like all we have to do is set our Azure blob storage CORS rules + add these headers to search service.

Minimal header: ```Access-Control-Allow-Origin *```
My vote would be to also add: ```Access-Control-Allow-Origin *```

@yishaigalatzer would you be okay with adding this so that browsers can do cross-domain JavaScript requests to our V3 API?

**Comment by yishaigalatzer** [comment]
Looks fine , talk with @blowdart first

**Comment by rappen** [comment]
I like where this issue is heading :)
But I have absolutely no idea what your cycle looks like - are we talking this week or April 2018 or somewhere in between?

**Comment by maartenba** [comment]
No promises, but definitely before 2020 ;-) Kidding, should be fairly quick!

**Comment by maartenba** [comment]
And were live :-) Let us know how it goes!

**Comment by rappen** [comment]
Works sweet and smooth and just the way I like it!
Super, thanks guys! :+1:
