### ISSUE TITLE
NugetGallery.sln not build-able due to NuGet reference issues 

### ISSUE THREAD

**Issue by digitalray** [NuGet/NuGetGallery#3038]
When loading the NuGetGallery solution in Visual Studio 2015 U, the referenced NuGet libraries (NuGet.) are not found when doing a NuGet restore. The solution is not build-able and when trying to upgrade or change NuGet references an error is thrown in VS 2015.

Here is the restore error:
An error occurred while trying to restore packages: Unable to find version '3.4.0-beta-632' of package 'Nuget.Common'. https://api.nuget.org/v3/index.json

Here is the VS Output:
[Failure] Could not find file 'C:\Users\user\AppData\Local\Temp\ef4453b51dfc47c9acab151f63401305_VersionInfo.cs'.

Tried changing the NuGet server to the following with no luck:
https://www.nuget.org/api/v2

![nuget-issue](https://cloud.githubusercontent.com/assets/6512172/15368742/39254b22-1ce4-11e6-97c1-6ccd63d0a838.JPG)

**Comment by maartenba** [comment]
We have updated the dependencies, can you try a fresh clone?

**Comment by digitalray** [comment]
Just tried fresh clone. All of the packages were restored except for Nuget.Logging. Still getting an error on that one. 

An error occurred while trying to restore packages: Unable to find version '3.5.0-beta-1160' of package 'NuGet.Logging'. https://api.nuget.org/v3/index.json: Package 'NuGet.Logging.3.5.0-beta-1160' is not found on source 'https://api.nuget.org/v3/index.json'.

**Comment by maartenba** [comment]
Can you try once more? That one is on https://www.myget.org/F/nugetbuild/api/v3/index.json, it should be picked up by Visual Studio during build (make sure to use the latest NuGet from http://nuget.org/downloads)

**Comment by digitalray** [comment]
Thanks a lot for the quick fix. After adding https://www.myget.org/F/nugetbuild/api/v3/index.json to NuGet settings, I was able to restore NuGet.Logging.

**Comment by haingoctu** [comment]
I'm new to all this. Where do I put " https://www.myget.org/F/nugetbuild/api/v3/index.json" in Visual Studios?
