### ISSUE TITLE
Uploading large packages result in OutOfMemoryException

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3042]
_From @mocsharp on May 24, 2016 17:22_

Using latest (as of May 24,16) nightly build of nuget.exe, I was able to upload nuget packages over 300MB without timing out.  However, Nuget.Server now throws an OutOfMemory exception.  

Exception was thrown from StreamExtensions.cs > ToStreamFactory in the ZipPackage constructor, stream.ToStramFactory() call.

_Copied from original issue: NuGet/Home#2842_

**Comment by mocsharp** [comment]
Just some numbers. 
Uploading a 460MB (1.98GB unpacked) package:

From Task Manager:
1) initial memory usage: 25MB
2) Peak memory usage: 6.30GB

**Comment by maartenba** [comment]
Will look into this. Switching to `OptimizedZipPackage` should do the trick.

On a side note, large packages are a bad idea in general.

From the NuGet.org FAQ:

> **What is the maximum size of packages I can upload to NuGet.org?**
> 
> NuGet.org allows uploading packages up to 250MB. As a best practice, we recommend uploading smaller packages that are < 1 MB and using dependencies to link together packages. As a rule of thumb, packages contain only one assembly to avoid collissions.
> 
> NuGet's protocol for downloading packages is HTTP. The bigger the package, the higher the chance for failed installs. It is much easier to retry and download small packages than large ones.
> 
> It is possible to share dependencies between multiple packages, making the total download size for consumers of your NuGet packages smaller.
> 
> Dependencies are mostly static and never change. When fixing a bug in code, the dependencies may not have to be updated. If your dependencies ship in the same package you end up reshipping the large packages every time. By splitting NuGet packages into smaller chunks (dependencies), upgrades are much more fine-grained for the end user of the NuGet package.
>

**Comment by mocsharp** [comment]
@maartenba  I agree.  We are using it the wrong way... but still a good problem to solve.

**Comment by maartenba** [comment]
Published a new version that has a fix.
