### ISSUE TITLE
With custom NuGetGallery, download counts aren't updating

### ISSUE THREAD

**Issue by AndyButland** [NuGet/NuGetGallery#3046]
I've set up a custom installation of NuGetGallery, which is all working fine apart from the fact that the download statistics for all packages remain at zero.  They are zero in the `Packages` table too.  I've noted this issue #2972 which suggests them being zero there isn't surprising, and so perhaps this method has been removed?

If that's the case, could you advise how the download count should be being updated and stored now?  And any suggestion why it may not be updated on my custom installation?  Thanks.

**Comment by maartenba** [comment]
When we implemented our CDN-based statistics, we removed all code paths for tracking downloads in the standalone gallery. You could add a few lines of code [around here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/ApiController.cs#L143) that fetch the package, increment the download count and then write that to the database.

**Comment by robertmuehsig** [comment]
Is tracking downloads something that should work in the future for a custom installation of the NuGetGallery? If yes, than maybe the download-count column shouldn't be removed and we could introduce a config switch.

**Comment by AndyButland** [comment]
Thanks @maartenba - partly to share in case others need this, and partly as have a question still if you don't mind - I've set this up at the point you indicated:

```
await PackageService.IncrementDownloadCountAsync(id, version);
```

Which calls into this:

```
        public async Task IncrementDownloadCountAsync(string id, string version)
        {
            var package = FindPackageByIdAndVersion(id, version);
            package.DownloadCount++;
            await _packageRepository.CommitChangesAsync();

            var packageRegistration = FindPackageRegistrationById(id);
            packageRegistration.DownloadCount++;
            await _packageRegistrationRepository.CommitChangesAsync();
        }
```

That works nicely if I then browse to `/api/v2/package/<mypackage>`.  I see the database has been updated and see the stats on the website front-end.

However it doesn't look like this API end-point gets hit if I do an `Install-Package MyPackage` from the PM console in Visual Studio.  So I'm not getting download counts updating that way.  Could you advise if I'm missing something further please?

**Comment by maartenba** [comment]
A config switch makes sense, feel free to send a PR ☺  For install-package, that should come in this path as well (but make sure to clear your local NuGet cache or it will not be downloaded again)

**Comment by AndyButland** [comment]
Thanks - that's working for me now.  The clearing out the cache did it.  Happy to send a PR but as noted above saw you have an issue live for removing these database columns?

**Comment by maartenba** [comment]
We can close that issue :-)

**Comment by AndyButland** [comment]
PR here: https://github.com/NuGet/NuGetGallery/pull/3047

**Comment by maartenba** [comment]
Thanks! Will give it a go tomorrow (CET timezone here)
