### ISSUE TITLE
Nuget.Server 2.11.1 crash if try to use package that require NuGet 3.4

### ISSUE THREAD

**Issue by Tasteful** [NuGet/NuGetGallery#3054]
I added the https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.Reflection.Extensions/4.0.1-rc4-24131-00 in the packages folder and the below exception messages was logged. The package is not listed.
```
 type="System.InvalidOperationException" message="'System.Collections.Concurrent' already has a dependency defined for 'System.Runtime'." source="NuGet.Core" detail="System.InvalidOperationException: 'System.Collections.Concurrent' already has a dependency defined for 'System.Runtime'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest(Func`1 manifestStreamFactory)
   at NuGet.ZipPackage..ctor(Stream stream)
   at NuGet.Server.Publishing.PackageService.CreatePackage(HttpContextBase context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)"
```

**Comment by maartenba** [comment]
Can you confirm this is on NuGet.Server 2.11.1? The above call stack looks like it comes from NuGet.Server 2.10.

**Comment by Tasteful** [comment]
@maartenba Sorry, that stacktrace was from the 2.10 version and I also see that I referencing the wrong package, the one that causing problem when I retest is the https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.any.System.Runtime.Extensions/4.0.10-rc3-23915

And when adding that to the packages-folder the app is crashing with the following in EventViewer.
```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at MS.Internal.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(System.IO.Packaging.PackagePart)
   at MS.Internal.IO.Packaging.PartBasedPackageProperties..ctor(System.IO.Packaging.Package)
   at System.IO.Packaging.Package.get_PackageProperties()
   at NuGet.OptimizedZipPackage+<>c__DisplayClassa.<EnsurePackageFiles>b__9(System.IO.Packaging.PackagePart)
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at NuGet.OptimizedZipPackage.EnsurePackageFiles()
   at NuGet.OptimizedZipPackage.GetFilesBase()
   at NuGet.Server.PackageExtensions.IsSymbolsPackage(NuGet.IPackage)
   at NuGet.Server.Infrastructure.ServerPackageRepository.AddPackagesFromDropFolder()
   at NuGet.Server.Infrastructure.ServerPackageRepository.FileSystemChanged(System.Object, System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

Files in bin-folder
![image](https://cloud.githubusercontent.com/assets/357589/15700039/bb9b0d92-27d1-11e6-8a77-0115068a7fef.png)

**Comment by maartenba** [comment]
@Tasteful Any chance you can send us a copy of your server's folder? (excluding packages)

**Comment by Tasteful** [comment]
@maartenba We have built some own authentication so you will not be able to run that version. But I created a sample server [WebApplication3.zip](https://github.com/NuGet/NuGetGallery/files/292812/WebApplication3.zip)

In the above zip you have a folder that is named `failing-packages` that contains the package that got the server to crash, copy that into the `WebApplication3\Packages` folder.

The sample app was created with the following steps
1 Creating a empty web application
2 run "Install-Package NuGet.Server" in package manager console

**Comment by maartenba** [comment]
Thanks! That was yet another package :-) This now reproduces the error indeed.

I found that the package has an invalid XML element in one of the inner metadata files (`package\services\metadata\core-properties\cc34be8b80ad4443be7895d2b4c22d9f.psmdcp`):

```
<?xml version="1.0" encoding="UTF-8"?>
<coreProperties xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>Microsoft</dc:creator>
  <dc:description>Provides commonly-used classes for performing mathematical functions, conversions, string comparisons and querying environment information.

Commonly Used Types:
System.Math
System.Environment
System.Random
System.Progress<T>
System.Convert
System.Diagnostics.Stopwatch
System.Runtime.Versioning.FrameworkName
System.StringComparer
System.IO.Path
 
TFS ID: 1609112, GitHub SHA: https://github.com/dotnet/corefx/tree/c9598abc6f87cb4c7ef32513d6f4ff153b81debc 
When using NuGet 3.x this package requires at least version 3.4.</dc:description>
  <dc:identifier>System.Runtime.Extensions</dc:identifier>
  <version>4.1.0-rc4-24131-00</version>
  <keywords />
  <lastModifiedBy>NuGet.Packaging, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35;Microsoft Windows NT 6.3.9600.0;</lastModifiedBy>
</coreProperties>
```

The description here contains ```System.Progress<T>```, which can not be parsed as valid XML as there is no ```</T>```. Or in other words: the description element should be encoded so that it becomes ```System.Progress&lt;T&gt;``` instead.

For now, I'm afraid this package will not work with NuGet.Server as we use some NuGet.Core framework base classes to read the packages - and those expect this particular file to be valid.

The good news is: this issue has been resolved (https://github.com/NuGet/NuGet2/commit/cc9ec1ac8da24739775b061a5c2c12f29203cd67) and will ship in NuGet.Server once we ship a new NuGet.Core.

If you want to have this particular package on your server right now, you could use our pre-release NuGet.Core package and replace the NuGet.Core.dll on your server with the one from this package file:

[NuGet.Core.2.12.0-rtm-815.nupkg.zip](https://github.com/NuGet/NuGetGallery/files/292844/NuGet.Core.2.12.0-rtm-815.nupkg.zip)

**Comment by Tasteful** [comment]
@maartenba Thanks for investigation and the fix with the updated NuGet.Core, do you know why that package not is on https://www.myget.org/gallery/nugetbuild ?

**Comment by maartenba** [comment]
Will enquire internally.

**Comment by embix** [comment]
I encountered the infamous ParseCorePropertyPart related XmlException as well:

    <error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        <code/>
        <message xml:lang="de-DE">
            Fehler beim Verarbeiten dieser Anforderung.
        </message>
        <innererror>
            <message>
                Unbekanntes Stammelement im Core Properties-Teil. Zeile 2, Position 2.
            </message>
            <type>
                System.Xml.XmlException
            </type>
            <stacktrace>
                bei MS.Internal.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part) 
                bei MS.Internal.IO.Packaging.PartBasedPackageProperties..ctor(Package package) 
                bei System.IO.Packaging.Package.get_PackageProperties() 
                bei NuGet.OptimizedZipPackage.<>c__DisplayClassa.<EnsurePackageFiles>b__9(PackagePart part) 
                bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() 
                bei NuGet.OptimizedZipPackage.EnsurePackageFiles() 
                bei NuGet.OptimizedZipPackage.GetFilesBase() 
                bei NuGet.Server.PackageExtensions.IsSymbolsPackage(IPackage package) 
                bei NuGet.Server.Infrastructure.ServerPackageRepository.AddPackagesFromDropFolder() 
                bei NuGet.Server.Infrastructure.ServerPackageRepository.RebuildPackageStore() 
                bei NuGet.Server.Infrastructure.ServerPackageRepository.get_CachedPackages() 
                bei NuGet.Server.Infrastructure.ServerPackageRepository.GetPackages() 
                bei NuGet.Server.DataServices.PackageContext.get_Packages() 
                bei System.Data.Services.Providers.ReflectionServiceProvider.GetResourceContainerInstance(ResourceSet resourceContainer) 
                bei System.Data.Services.RequestUriProcessor.CreateFirstSegment(IDataService service, String identifier, Boolean checkRights, String queryPortion, Boolean isLastSegment, Boolean& crossReferencingUrl) 
                bei System.Data.Services.RequestUriProcessor.CreateSegments(String[] segments, IDataService service) 
                bei System.Data.Services.RequestUriProcessor.ProcessRequestUri(Uri absoluteRequestUri, IDataService service) 
                bei System.Data.Services.DataService`1.HandleRequest()
            </stacktrace>
        </innererror>
    </error>

I am _running NuGet.Server v2.11.2.0_ on our test environment with the same packages we use in production (NuGet.Server v2.8.60717.93). The following packages caused that error:

 - Argu.1.1.2.nupkg
 - FsPickler.1.4.0.nupkg
 - FsUnit.1.3.1.0.nupkg
 - FsUnit.1.4.0.0.nupkg
 - JetBrains.Platform.Standalone.Shell.102.0.20150724.141603.nupkg
 - XPlot.GoogleCharts.1.2.1.nupkg
 - XPlot.GoogleCharts.Deedle.1.2.1.nupkg
 - XPlot.Plotly.1.2.1.nupkg

BTW: Would be cool, if the error message contained the "broken" nugpkg. Or aggregate that kind of error and give all broken packages at once. Or put them in a legacypackages folder and don't cache them, so we can use the nuget server again. In fact, pushing such a fishy package could be considered a denial of service attack.
