### ISSUE TITLE
TitleConflictsWithExistingRegistrationId operates on unlisted packages

### ISSUE THREAD

**Issue by mganss** [NuGet/NuGetGallery#3055]
I have a package whose title is the same as the id of an unlisted package (also owned by me). When trying to push a new version of the listed package (from AppVeyor) I get:

> Error publishing package. NuGet server returned 400: The NuGet package is invalid. The error encountered was:'The title of your package, 'XmlSchemaClassGenerator', is similar to the ID of an existing package, which can cause confusion with our users. Please modify the title of your package and try uploading again.'. Correct the error and try again.

This is due to the check in `PackageNamingConflictValidator.TitleConflictsWithExistingRegistrationId`. I believe unlisted packages shouldn't be taken into account when performing this check because the policy regarding unlisted packages stated on the NuGet Gallery site is:

> Unlisting a package hides the package from search results and all NuGet commands

**Comment by maartenba** [comment]
Adding @yishaigalatzer @harikm86

**Comment by maartenba** [comment]
We've discussed this in the team and will not be changing this policy short-term. For now, you can add a prefix or suffix to the title and publish the package.

**Comment by mganss** [comment]
:ok: fair enough. One thing that puzzles me, though: I tried adding just an emoji character to the name and still got the error. Adding a "regular" character worked, though. I can't see anything in the code that would prevent the first case. The check just does `Trim()` and `ToLowerInvariant()` and then compares with string `==`.

**Comment by maartenba** [comment]
Good question, would have to check. What value did you attempt?

**Comment by mganss** [comment]
:sunglasses:

**Comment by maartenba** [comment]
Filtered out by the database :)

**Comment by mganss** [comment]
Ah, got it.
