### ISSUE TITLE
Issue submitting package created in a different timezone

### ISSUE THREAD

**Issue by lumaxis** [NuGet/NuGetGallery#3058]
Today, me and a colleague worked on a release together. I created the dll in the CEST timezone and sent it to him for submission. He is in the PDT and got the following message:
`"The package is invalid and cannot be uploaded. One or more files, such as 'x.dll' have a date in the future."`

Is there anything we can do about this or does he really have to wait 9 hours everytime until he can submit the package? Thanks!

**Comment by maartenba** [comment]
Can you send us a copy of the package?

**Comment by lumaxis** [comment]
Sure, you can load it from here: https://github.com/bitstadium/HockeySDK-Xamarin/releases/download/4.1.0-beta2/HockeySDK.Xamarin.4.1.0-beta2.nupkg

**Comment by maartenba** [comment]
Seems the package does have files with a date in the future. Here's an example from that package when opened with WinRAR:

![issue](https://cloud.githubusercontent.com/assets/485230/15745879/5ef602dc-28d4-11e6-9574-f0af64fbf036.png)

Which client are you using to create the package? On what OS?

**Comment by lumaxis** [comment]
Interesting 🤔 The package was created on a Mac using Cake 0.12.0 and Mono 4.4.0

**Comment by maartenba** [comment]
@yishaigalatzer @rrelyea do we know which client is generating these future dates?

**Comment by lumaxis** [comment]
Thanks in advance for looking into this! ☺️

**Comment by maartenba** [comment]
Can you try creating it with the latest prerelease NuGet.exe? www.nuget.org/downloads

**Comment by lumaxis** [comment]
Thanks! That looks like it might fix the problem.
Our build toolchain tries to automatically download a NuGet.exe version from `https://www.nuget.org/nuget.exe` which apparently returns version 2.8.6.
Do you know if there's another generic link that always provides the latest NuGet.exe?

**Comment by maartenba** [comment]
This should work:
`https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`

**Comment by lumaxis** [comment]
Perfect, thanks again!
