### ISSUE TITLE
PackageHash mismatch for NuGet.Server 2.11.1

### ISSUE THREAD

**Issue by shunter** [NuGet/NuGetGallery#3059]
The API call:  https://www.nuget.org/api/v2/Packages(Id='Nuget.Server',Version='2.11.1')  reports a PackageHash of:

`FGVE4n2sNYHlJ/ViIklxfnuj9OZy6rX4YpMfyaUOxDMX7k5CJxbpF5OHsll8arH57BEseRc3UXi+OuhYpQt7Hg==`

but the actual package downloaded from:

https://www.nuget.org/api/v2/package/NuGet.Server/2.11.1

has an actual SHA512 of:

`jXEMeQc1Gf9QbdBhSIhmYMfXTyLu9wYdpvmBewCTf6zVHCwI7FASG6UNx6iin7cxKp89HPuzRWjzRcy7ixbejA==`

I also note that the file size doesn't match either, API reports 53816 but the actual file is 53990.

**Comment by maartenba** [comment]
This is because the package has since been updated to add release notes. We've reflowed the package so that the hash matches again. Thanks for the ping!

**Comment by shunter** [comment]
I tested this again today and found that the API call PackageHash has changed to:

`yxNnRp9Wx5OTQo0BA0MDNXyTdD6p2sgmvpWukQDwqos+UsxrY1sPnZ7CkdgkhZJlWS88zrcNBUqm8JGY/8E1Kw==`

however it still does not match the actual file SHA512.  (the file SHA512 is still the same as what I posted above)
