### ISSUE TITLE
Split core of NuGet.Server into own project/package

### ISSUE THREAD

**Issue by andulv** [NuGet/NuGetGallery#3061]
I need to host multiple NuGet feeds in an existing OWin Web API application.

NuGet.Server provides the bulk of what I need to accomplish this, but the NuGet package includes WCF / IIS specific portions and also depends on lots of stuff that is not needed for core functionality.

For my own use, I have forked and split the NuGet.Server project in two:

- NuGet.Server.Base contains repository / query code, ODatPackage, etc. that is not WCF/IIS/Implementation specific
- NuGet.Server contains all the website specific stuff.

From consumers point of view, nothing has changed in NuGet.Server. It just pulls in NuGet.Server.Base.

And I have also added 
- NuGet.Server.WebAPI references NuGet.Server.Base and uses WebAPI OData v3 to expose one or more NuGet feeds as OData controllers.

See my fork here: [https://github.com/andulv/NuGet.Server](https://github.com/andulv/NuGet.Server)

I hope this scenario can be officially supported in some way. If you are interested, I can try to reapply the same/similar changes as Pull Requests.

**Comment by maartenba** [comment]
That is cool stuff, @andulv! I just went through your fork and it looks nice, although it is too big a change to just take in. However we're open to several smaller ones. Here are the PR's I am thinking of:

**1)** Split `NuGet.Server` into `NuGet.Server.Core` (your NuGet.Server.Base) + `NuGet.Server`. Make sure that we generate two NuGet packages from these. This would make sure that we have one package with the base code and a second package with all the web/runtime specifics. This would also fix https://github.com/NuGet/NuGetGallery/issues/2881 potentially.

Once that is tested and verified, we can go to a next PR:

**2)** Create a `NuGet.Server.V2` package, which would hold a Web API version exposing the feed as WebAPI OData v3. (note you may want to re-use some of the OData implementation, conventions etc. from https://github.com/NuGet/NuGetGallery/tree/master/src/NuGetGallery/OData and https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/ODataV2FeedController.cs - these is well-tested on www.NuGet.org and it would greatly help to have the two implementations be as similar as possible). This PR would also remove all of the WCF-based services and dependencies. This would introduce a third NuGet package in the NuGet server family.

The end result would be 3 NuGet packages for NuGet.Server:

* `NuGet.Server`, holding the `Web.config` and other hosting-specific items.

  * Depends on `NuGet.Server.Core` and `NuGet.Server.V2`

* `NuGet.Server.Core`, holding the core functionality of making sure we can work with packages etc.

  * Probably depends on `NuGet.Core`

* `NuGet.Server.V2`, holding the WebAPI OData specifics.

  * Depends on `NuGet.Server.Core` (and whatever is needed for the Web API stuff of course)

I know, quite the task 😄  We currently don't have this very high on our backlog right now, but looks like this may actually happen in the community instead. Thanks in advance and do let us know if you are up for it or want to discuss further.

(cc @yishaigalatzer for visibility)

**Comment by robertmuehsig** [comment]
Is there a connection between NuGet.Server and the NuGet Gallery or is the NuGet Server "just" a lightweight protocol endpoint, without all the UI stuff? 
And just a general question: Where is the code for the v3 API? Can this be selfhosted as well?

**Comment by maartenba** [comment]
NuGet.Server is indeed just a lightweight protocol layer. V3 is in NuGet.Services.Metadata, but we are not yet planning to create a lightweight version of it (needs some protocol love before we do so)

**Comment by andulv** [comment]
@maartenba I just submitted a pull request (Dev#11) for your first task. Please take a look and see if this is what you had in mind.

**Comment by skofman1** [comment]
@robertmuehsig  in the new Staging code there is some lightweight code that creates the V3 structure, that can be reused. However, this code only help you to create the structure, not to consume it.
Take a look here: https://github.com/NuGet/NuGet.Staging/blob/dev/src/NuGet.Services.V3Repository/V3Service.cs

**Comment by maartenba** [comment]
@andulv Thank you so much for the PR https://github.com/NuGet/NuGet.Server/pull/11 !

Guess we can start looking at replacing WCF now as well.

**Comment by andulv** [comment]
@maartenba I have made some progress over at: [andulv/NuGet.Server/tree/dev3061-2](https://github.com/andulv/NuGet.Server/tree/dev3061-2)

Status now is this:
- NuGet.Server.V2 is a library mostly based on code from NuGetGallery
- NuGet.Server.V2.OWinSampleHost is a console application that exposes services from NuGet.Server.V2
- Package search and download seems to be working (done light testing with nuget.exe)
- Supports hosting multiple NuGet feeds in same project
- Original NuGet.Server project is not yet modified.


Todo:
- Eliminate need for implementors to provide own ODataController and APIController. (But still keep it as an option)
- Web API MessageHandlers instead of (or as alternative to) ApiController for file operations? (Port MVC MessageHandlers from NuGet.Server?)
- Update NuGet.Server (IIS project) to use NuGet.Server.V2 (will probably wait with this one until everything else is OK. Maybe seperate PR?)

I will be leaving for a one-week vacation tomorrow. Will try to follow up when I am back.

**Comment by maartenba** [comment]
Just went through it, looks pretty awesome so far :) You may want to rebase on `dev` as I did a few changes after merging your previous PR.

Enjoy your vacation! (I'll be out the week after that)

**Comment by maartenba** [comment]
We merged in https://github.com/NuGet/NuGet.Server/pull/13.

An official release is pending a few other changes, but a pre-release package is available:

```Install-Package NuGet.Server -Version 2.14.0-dev-0003 -Source https://dotnet.myget.org/F/nuget-build/api/v2```

**Comment by joelverhagen** [comment]
Hey guys, it's been a long time coming, but we have release the Web API version of NuGet.Server as version `3.0.0-beta`. This also includes the two dependencies: NuGet.Server.Core and NuGet.Server.V2.
https://www.nuget.org/packages/NuGet.Server/3.0.0-beta
https://www.nuget.org/packages/NuGet.Server.V2/3.0.0-beta
https://www.nuget.org/packages/NuGet.Server.Core/3.0.0-beta

Note that this has feature parity with NuGet.Server 2.14.1 and therefore has SemVer 2.0.0 support 😃.

**Comment by joelverhagen** [comment]
NuGet.Server 3.0.0 and its dependencies have been published to NuGet.org:
https://www.nuget.org/packages/NuGet.Server/3.0.0
