### ISSUE TITLE
NuGet.Server: Default packagesPath is root path and not ~/Packages!

### ISSUE THREAD

**Issue by aureole82** [NuGet/NuGetGallery#3062]
After installing NuGet.Server (version="2.11.1") the web.config has been modified. It says:

    
    <add key="packagesPath" value="" />

But that's wrong! It points to the web application's root path.

By the way: It works with `<add key="packagesPath" value="~/Packages/Packages" />` but that's not what  it was intended for!

**Comment by maartenba** [comment]
Not sure I completely understand the issue. The packages path is resolved here: https://github.com/NuGet/NuGet.Server/blob/3c0edb60aad5a50e279ccd090eff08ebd946f919/src/NuGet.Server/Infrastructure/PackageUtility.cs#L43

When not specified, we fallback to `~/Packages` (https://github.com/NuGet/NuGet.Server/blob/3c0edb60aad5a50e279ccd090eff08ebd946f919/src/NuGet.Server/Infrastructure/PackageUtility.cs#L52)

If you want to override it, say, to write packages in `~/pkgs`, you could specify: `<add key="packagesPath" value="~/pkgs" />` which will store packages there (resolved here https://github.com/NuGet/NuGet.Server/blob/3c0edb60aad5a50e279ccd090eff08ebd946f919/src/NuGet.Server/Infrastructure/PackageUtility.cs#L57)

**Comment by aureole82** [comment]
I've update the following packages and the issue is gone:

    <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.1" targetFramework="net452" />
    <package id="Microsoft.Net.Compilers" version="1.2.2" targetFramework="net452" developmentDependency="true" />

But I don't believe there's a relation...

**Comment by maartenba** [comment]
Maybe the update triggered an app pool reload which in turn fixed it?
