### ISSUE TITLE
Use Serilog in Gallery

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3067]
1.       Serilog traces turn into Custom events in AI.
2.      Serilog properties turn into Custom Data properties in AI. 
3.      AI contains a filtering option, that allows to filter telemetry according to properties 
4.      Here are some tips how to write log messages, so we can take advantage of AI features, without explicitly taking dependency on AI in our business logic:

a.      Use the same Serilog properties throughout you code, so we can filter by them later

b.      For jobs, we can add a property for each job that will contain its name, and propagate in all the events, like so: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#track-custom-traceeventmetric
This will allow us to easily filter traces of a specific job, when all jobs traces are sent to the same AI app.

c. we should maybe build a glossary of terms we can reuse in log traces across our services, so we can search/filter on the same property names everywhere (e.g. avoid mixing Package, PackageId, Id, … and instead consolidate to use PackageId everywhere). This could reduce the long list of properties and make our queries more consistent (Consider a common set of strings in a common library instead of a 'documented glossary')

d. Some of these properties (such as MachineName, Version) are added automatically by one of the Enrichers (just check the code base for *Enricher class names ).
Data that is readily available can always be added using an Enricher too, so we don’t have to pass it along in every trace call ourselves. We just need to consider if it needs to be part of the message template or not.

**Comment by skofman1** [comment]
Related issue: In Gallery, IDiagnosticsService traces don't appear in AI.

**Comment by maartenba** [comment]
Related:
* https://github.com/NuGet/NuGetGallery/issues/3146

**Comment by skofman1** [comment]
Resolved for V3 jobs: https://github.com/NuGet/NuGet.Services.Metadata/pull/86

**Comment by skofman1** [comment]
Outdated.
