### ISSUE TITLE
NuGet.Server error processing dropped package when ignoreSymbolsPackages=false

### ISSUE THREAD

**Issue by andulv** [NuGet/NuGetGallery#3069]
**Reproduce**
- Set ignoreSymbolsPackages=false in config
- Start with empty package folder
- Add one or more .nupkg files to package folder root.
- Invoke the Search function in the dataservice (through 'nuget list' from a client, or similar)
- The search logs an error, and does not return the newly added packages.
- But it seems like the packages are processed correctly, and are available next time the request is performed

**Background**
Overview based on logic in ServerPackageRepositor.AddPackagesFromDropFolder()
- If IgnoreSymbolsPackages=true, package.IsSymbolsPackage() is invoked *before* the .nupkg is processed and deleted. This function has sideeffect of expanding the files in the package to temp folder, where they are kept as a cache.
- After the .nupkg has been deleted, a new ServerPackage is created based on the dropped package.
- However, the constructor of ServerPackage calls down to functions that accesses the extracted files. And if not already extracted to tempfolder, it will try to extract from the dropped .nupkg (which is now deleted)

**Comment by maartenba** [comment]
> The search logs an error, and does not return the newly added packages.

Which error are you referring to? Looks like changing:

```
                        // Copy to correct filesystem location
                        _expandedPackageRepository.AddPackage(package);
                        **_fileSystem.DeleteFile(packageFile);**

                        // Mark for addition to metadata store
                        serverPackages.Add(CreateServerPackage(package, EnableDelisting));
```

into 

```
                        // Copy to correct filesystem location
                        _expandedPackageRepository.AddPackage(package);

                        // Mark for addition to metadata store
                        serverPackages.Add(CreateServerPackage(package, EnableDelisting));
                        **_fileSystem.DeleteFile(packageFile);**
```

could solve the issue if I understand correctly?

**Comment by andulv** [comment]
The error is IOException (file not found) triggered by calling CreateServerPackage after the file has been deleted.

So I think your fix will solve the issue perfectly.

**Comment by maartenba** [comment]
Fixed in `dev`, a prerelease package is available on `https://www.myget.org/F/nugetbuild/api/v3/index.json`. ([NuGet.Server 2.11.3-dev-0002](https://www.myget.org/feed/nugetbuild/package/nuget/NuGet.Server/2.11.3-dev-0002))

**Comment by maartenba** [comment]
Closing for now, this will be part of the next release in a few weeks.
