### ISSUE TITLE
Unable to donwload source file from nuget source server (https://nuget.smbsrc.net)

### ISSUE THREAD

**Issue by northtyphoon** [NuGet/NuGetGallery#3071]
The following is an example. The server returned (404) Not Found.
https://nuget.smbsrc.net/src/LinkExtensions.cs/r3vl8vqKvXGxUOF8HRnjRZCjSzXQ3PURGx8--MFtcZo=/LinkExtensions.cs

The source location was retrieved from symbol pdb of System.Web.Mvc.

Tried a few other source files and got the same result. It used to work. Did the source file be moved?

**Comment by harikm86** [comment]
This service is not actually hosted by the NuGet team. I would recommend that you reach out to https://twitter.com/TripleEmcoder who owns the nuget.smbsrc.net service.
