### ISSUE TITLE
Contact support shows error page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3077]
When contacting support from this page: https://www.nuget.org/policies/Contact
with unconfirmed e-mail, an error page is shown.

**Comment by robertmuehsig** [comment]
You mean after this contact support form is submitted? 
![image](https://cloud.githubusercontent.com/assets/756703/16096649/3679c76e-334a-11e6-9856-f5c0f2be69f4.png)

Should a user with an unconfirmed e-mail be able to contact the support via this form?

**Comment by skofman1** [comment]
Exactly

**Comment by maartenba** [comment]
Fixed (see referenced commit)
