### ISSUE TITLE
Dev: ReflowPackageService build error

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#3080]
Hi

I tried something on the latest NuGet/Dev branch, but the build always fails with:

The type or namespace name 'ReflowPackageService' could not be found (are you missing a using directive or an assembly reference?)	
NuGetGallery	
D:\Code\GitHub\NuGetGallery\src\NuGetGallery\Controllers\PackagesController.cs	758	Active

![image](https://cloud.githubusercontent.com/assets/756703/16133773/e4b8820a-3419-11e6-8121-4e6bf6dfc0d0.png)

Known issue?

**Comment by maartenba** [comment]
That should compile, any chance you are missing a using statement?

**Comment by robertmuehsig** [comment]
Mhh... I reverted my changes and now it builds fine. Sorry for the issue here - my bad :smiley:
