### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by vikrantThakur** [NuGet/NuGetGallery#3081]
how to publish nuget.server on our local company server.

**Comment by maartenba** [comment]
@vikrantThakur you would have to deploy the web application you have created in Visual Studio, for example using a right-click on the project and selecting "publish"

**Comment by vikrantThakur** [comment]
thank you @maartenba , can you please provide the steps.

**Comment by maartenba** [comment]
This one is linked to Azure Web Apps but steps are roughly similar on IIS - you'd have to create a site for it in IIS, copy over the application and make sure permissions are set correctly.

https://www.suchan.cz/2014/10/how-to-deploy-your-own-nuget-server-on-azure-website-in-15-minutes/

We can't provide individual installation support though.
