### ISSUE TITLE
api-v2v3search-0 paging limit

### ISSUE THREAD

**Issue by MscrmTools** [NuGet/NuGetGallery#3082]
Hi,
This is not really an issue but more a help request.

When using the api-v2v3search-0 endpoint, only 20 results are returned.

Is there any way to get more results? result data does not seem to contain information to retrieve additional packages even if it tells how many packages match the query.

Thanks

**Comment by maartenba** [comment]
You can add the "skip" URL parameter, e.g. "skip=20" to ge the next page.

**Comment by MscrmTools** [comment]
Thank you very much!!
