### ISSUE TITLE
Support organizational accounts

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3084]
Discussion topic for spec - https://github.com/NuGet/Home/wiki/%5Bspec%5D-Support-organizational-accounts

**Comment by skofman1** [comment]
How about organizational hierarchy? For example, ASP.NET is under Microsoft organization. This will allow you to propagate rules (like ApiKey expiration) from an Organization to it's children, allow NuGet customers to get more details about an organization (like an organization details page) by seeing an organization graph, etc.

**Comment by robertmuehsig** [comment]
A hierarchy sounds interesting, but I would try to keep it simple. The hierarchy could introduce tons of challenges (Who "owns" what).
GitHub has a pretty simple but "good enough" org concept for most use cases.
Otherwise the spec seems pretty straight forward.

**Comment by harikm86** [comment]
Agreed with @robertmuehsig . The spec is a good MVP. Curious, @maartenba , did you take a look at existing publisher style account on App Stores?

**Comment by skofman1** [comment]
This feature has a new spec and is being tracked here: https://github.com/NuGet/NuGetGallery/issues/4627
