### ISSUE TITLE
Nuget.Server namespace missing

### ISSUE THREAD

**Issue by lgwapnitsky** [NuGet/NuGetGallery#3086]
Receiving the following in Visual studio 2013 & 2105 after a plain, vanilla installation of Nuget.Server:

The type or namespace name 'Server' does not exist in the namespace 'NuGet' (are you missing an assembly reference?)

The namespace is referenced, but I don't see it in assemblies, nor is it available to add.

Thank you,
Larry

**Comment by harikm86** [comment]
You need to re-target the project to 4.6 or above. We are looking into splitting up the packages and republishing this so you probably wont have to do this in the near future, but currently with the current stable version you have to re-target,

**Comment by harikm86** [comment]
https://github.com/NuGet/NuGetGallery/issues/3072
