### ISSUE TITLE
Documentation about target frameworks is outdated

### ISSUE THREAD

**Issue by ygoe** [NuGet/NuGetGallery#3091]
The page https://docs.nuget.org/create/targetframeworks is stuck at NuGet 3.3 but there's NuGet 3.4.x available for a while. I'm trying to understand the .NET Platform Standard and how to use it. That's really hard if the documentation only covers outdated technology.

**Comment by harikm86** [comment]
Thanks for letting us know. We will update this list soon. In the meantime the tfm you can use is netstandard with a suffix  of (1.0 etc..) in your folder name, e.g netstandard1.0. The up to date list of the available versions is given here https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by harikm86** [comment]
This issue was moved to NuGet/NuGetDocs#476
