### ISSUE TITLE
Package icon in search results doesn't match actual icon

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3093]
dima117a@gmail.com wrote:

The package has wrong icon in the package list (on the site and in the UI in Visual Studio).
Package icon https://habrastorage.org/files/99f/a59/fa7/99fa59fa760f4762a86fed46302b2d30.png
Icon in the package list https://habrastorage.org/files/c66/481/299/c664812990004f4b9a56edd5b2e81770.png

**Comment by maartenba** [comment]
Seems like the fallback icon is used in the second case, may be an SSL error in the browser?

**Comment by skofman1** [comment]
Saw no SSL errors. There wasn't even an attempt to load the icon from it's URI at https://raw.githubusercontent.com/bem/bem-identity/master/sign/_theme/sign_theme_spots.png

Checked the search results, and IconUrl is not part of the search results for this package. Do we need to rebuild the index?

**Comment by maartenba** [comment]
Try unlist / list cycle. Should update the index.

**Comment by dima117** [comment]
I executed the 'list/unlist' commands and the package icon is displayed correctly.
Thank you!
