### ISSUE TITLE
NuGet.Server CoreCLR support?

### ISSUE THREAD

**Issue by xied75** [NuGet/NuGetGallery#3094]
Dear Team,

Is there any plan to make the NuGet.Server to run on CoreCLR ( ASP.NET Core )?

Best

**Comment by harikmenon** [comment]
Nothing in the immediate roadmap. We plan to look into this sometime next year.

**Comment by emanb29** [comment]
It's about halfway through the year, has there been any update on potential plans for this?

**Comment by Baklap4** [comment]
Any updates?

**Comment by blakeja** [comment]
Updates?

**Comment by loic-sharma** [comment]
Here is a NuGet service implementation that runs on .NET Core: https://github.com/loic-sharma/BaGet
