### ISSUE TITLE
HandlePackageEdits job failing in prod

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3109]
You can see the error in the DB:

System.IO.FileLoadException: Could not load file or assembly 'NuGet.Core, Version=2.8.60318.667, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NuGet.Core, Version=2.8.60318.667, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at HandlePackageEdits.Job.<ApplyEdit>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at HandlePackageEdits.Job.ApplyEdit(PackageEdit edit)
   at HandlePackageEdits.Job.<Run>d__8.MoveNext() in c:\Users\bhuvak\Documents\GitHub\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 140

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by maartenba** [comment]
@skofman1 @shishirx34 Can this one be closed?

**Comment by shishirx34** [comment]
yes, I kept this until I deploy to INT and PROD. I will close it off.

**Comment by shishirx34** [comment]
@maartenba - It seems that using NugetGallery.Core's NupkgRewriter(which  https://github.com/NuGet/NuGet.Jobs/pull/60 does) adds empty tags for null items. For eg if licenseUrl, projectUrl, iconUrl is not specified. This could cause an issue in client side: https://github.com/NuGet/NuGetGallery/issues/3177 in which @emgarten says _"Those fields are not required, however the client does fail if they exist but do not contain a valid url."_ which in my understanding means, if I were to edit the nupkg using the above rewriter, it would add empty tags for non-existing elements, which can cause issues in client (see: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Core/Packaging/NupkgRewriter.cs#L73). 

I think we should only add element to metadata if it exists, either before the edit or after edit and non-existing elements shouldn't be added. Does that sound good to you? I can open another bug to fix and consume those changes for HandlePackageEdits, and hold on to push changes to prod for https://github.com/NuGet/NuGet.Jobs/pull/60. Is that reasonable?

**Comment by scottbommarito** [comment]
@shishirx34 I agree that we shouldn't add metadata elements to specs that don't have those elements. I don't know if you need to wait on pushing to prod, unless this additional issue will also make the `HandlePackageEdits` job useless.

**Comment by shishirx34** [comment]
@scottbommarito - The HandlePackageEdits job might essentially break Clients if it a package is edited for a that adds empty tags, hence I want to hear from @maartenba if that is a likely scenario.

**Comment by maartenba** [comment]
@shishirx34 sounds good, I think it makes total sense to not write those elements if they are empty anyway

**Comment by scottbommarito** [comment]
@shishirx34 Ah, I was uninformed on what the change was about--don't push it for sure if it introduces a regression.
