### ISSUE TITLE
Search service HTTP 500 errors

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3110]
The following URLs cause HTTP 500 errors:
- /autocomplete?q=:En&supportedFramework=netcoreapp1.0&take=100&prerelease=true
- /autocomplete?q=--prerelease%20Swashbuckle&take=1000
- /autocomplete?q=-&supportedFramework=netstandard1.3&take=100&prerelease=true
- /autocomplete?q=--&supportedFramework=netstandard1.3&take=100&prerelease=true

In general it seems like there are some search queries that cause HTTP 500.

**Comment by maartenba** [comment]
What would be the expected result for these? Filter out the weird characters at the start and return what we can find? Or just return empty result for these as they usually do not match anything out there?

**Comment by harikmenon** [comment]
I think returning empty results is fine in this case.

**Comment by maartenba** [comment]
@yishaigalatzer Should we filter out these weird characters? Can be done both on the web side before it hits Lucene, or in Lucene itself.

**Comment by skofman1** [comment]
Was resolved: https://github.com/NuGet/NuGetGallery/issues/3330
