### ISSUE TITLE
alert window xss

### ISSUE THREAD

**Issue by ibrahimuludag** [NuGet/NuGetGallery#3124]
When I search for xss, an alert window with content xss is displayed.

https://www.nuget.org/packages?q=xss

**Comment by robertmuehsig** [comment]
Wow. I think this is the package, which is not even a real package... 

![image](https://cloud.githubusercontent.com/assets/756703/16817994/bc7393de-4945-11e6-8814-fe17543f7bad.png)

The PackageId seems to be "upload", which is a pretty clever trick...
https://www.nuget.org/packages/Upload/

**Comment by maartenba** [comment]
Thanks guys,well get this fixed

**Comment by scottbommarito** [comment]
Just put up a PR to solve the issue. Fortunately it was only affecting strings shorter than 300 characters, so no elaborate script could have been run. However, regarding the package with an id of "upload", we should probably add some additional checks to the packageId to preventing certain ids that conflict with the route names from being published. This would include "upload-progress", "verify-upload", and "cancel-upload" as well.

**Comment by yishaigalatzer** [comment]
We should fix routing, or the url patterns rather than block package names

**Comment by maartenba** [comment]
Has been deployed, thanks again for reporting!
