### ISSUE TITLE
NuGet Build Error (3.0.624-r-master)

### ISSUE THREAD

**Issue by haingoctu** [NuGet/NuGetGallery#3125]
![nuget](https://cloud.githubusercontent.com/assets/14064416/16818935/2811e31c-4918-11e6-940d-18b3229d10e0.png)

I tried googling this problem, but I cannot find a resolution. Thank you.

**Comment by maartenba** [comment]
Can you give it another go? Builds fine on our CI system...

**Comment by haingoctu** [comment]
![image](https://cloud.githubusercontent.com/assets/14064416/16841695/68de9968-49a8-11e6-84bf-6b53dadd6946.png)

Still NoGo.

**Comment by maartenba** [comment]
Can you try the `dev` branch?

**Comment by haingoctu** [comment]
Same error with dev build. 
"git clone git@github.com:NuGet/NuGetGallery.git -b dev --single-branch"
"cd nugetgallery"
"./build.cmd"

then same set of errors

Can I provide you with any more information that may help you determine this problem?

**Comment by maartenba** [comment]
Can you edit the build.msbuild file and add `-Verbosity Detailed` switch to the restore command? That should give some info.

**Comment by haingoctu** [comment]
![image](https://cloud.githubusercontent.com/assets/14064416/16842595/0331490e-49ac-11e6-8418-a7fd0a8e0878.png)
![image](https://cloud.githubusercontent.com/assets/14064416/16842602/0c4b8d92-49ac-11e6-8d1c-a4a2fc621161.png)

**Comment by maartenba** [comment]
Looks like a connectivity issue ("Unable to connect to the remote server"). Make sure to check connectivity to both www.nuget.org and www.MyGet.org is okay

**Comment by haingoctu** [comment]
I'm able to go to nuget.org and myget.org. Is that what you mean when you say check connectivity?
However, I cannot ping nuget.org or myget.org. Do those sites intentionally dissalow pings?

**Comment by maartenba** [comment]
They do. In any case, the error seems restore related. Can you try putting latest Nuget.exe command line from www.nuget.org/downloads in the .nuget folder? This has better error reporting and should give more logs.

**Comment by haingoctu** [comment]
built with the latest nuget.exe  (win x86 commandline v3.4.4)
![image](https://cloud.githubusercontent.com/assets/14064416/16843702/5f13cef0-49b0-11e6-8c54-ef59ad062ca7.png)
![image](https://cloud.githubusercontent.com/assets/14064416/16843726/7a18a81a-49b0-11e6-9fa2-1026ca25e052.png)

**Comment by maartenba** [comment]
Ok let's try opening the solution in VS and running restore there?

**Comment by haingoctu** [comment]
![image](https://cloud.githubusercontent.com/assets/14064416/16844326/b8eab054-49b2-11e6-81ff-09593fa86d11.png)

**Comment by maartenba** [comment]
Seems https://www.myget.org or https://www.nuget.org are not working on your connection. Is there a proxy, antivirus, ...? Can you perhaps try on another machine/network?

**Comment by haingoctu** [comment]
It looks like myget.org is not working on this guest. I could've sworn it was working 20 minutes ago. I'm running the guest virtually and somethings seems to be blocking it because I can go to myget.org outside of the VM. I'll see if I can fix this and return back when I get some progress.

**Comment by haingoctu** [comment]
There might be a lot of hoops I have to jump through to make any changes to the network where I am. Can I alternatively get whatever this restore is attempting to get and put it locally in my machine and have the restore point to it?

**Comment by maartenba** [comment]
Can you run it at home or another PC?

**Comment by haingoctu** [comment]
I will attempt to run it outside of the VM environment since I can go to myget.org outside of the VM, but the end state is to get this running on the VM.

**Comment by maartenba** [comment]
Clsoing for now, but feel free to ask any questions you may have

**Comment by haingoctu** [comment]
maartenba, 

If I get it running on outside of the VM, can I use the successful build and transfer anything to the VM to get it working?

**Comment by maartenba** [comment]
That will work indeed

**Comment by haingoctu** [comment]
Based on the inability to connect to myget.org do you know what I will need to transfer over to the VM?

**Comment by maartenba** [comment]
The /packages folder should be enough

**Comment by haingoctu** [comment]
If I have to do everything over again, but all I need are some packages, is there a list of the packages I need so I can just download them? Otherwise, I will have to redownload visual, azure, and all the bells and whistles.

**Comment by maartenba** [comment]
Thety are all listed in the various packages.config files

**Comment by haingoctu** [comment]
I'm on to the deployment of the website now.

When I set up using IIS, is the physical path the root of the nugetgallery folder or some other folder inside it?

**Comment by maartenba** [comment]
You can specify the root
