### ISSUE TITLE
JobRunner does not handle job.Init failure properly

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3126]
I was looking at the `JobRunner` logic and noticed the following interesting code...

(in `JobRunner.JobSetup`)

```
if (!job.Init(jobArgsDictionary))
{
    // If the job could not be initialized successfully, STOP!
    Trace.TraceError("Exiting. The job could not be initialized successfully with the arguments passed");
}
```

In other words, if `job.Init` fails, `JobRunner` prints an error and does nothing else. This means that `JobRunner.JobLoop` will start anyway and potentially reek havoc. We should make it so that in the case of an initialization failure, `JobRunner` exits or perhaps waits and attempts `job.Init` again later.

**Comment by cristinamanum** [comment]
done
