### ISSUE TITLE
Move NuGet blog to Azure WebApps

### ISSUE THREAD

**Issue by harikmenon** [NuGet/NuGetGallery#3132]
We need to move NuGet blog to Azure WebApps to resolve the HTTPS issue, also the right thing to do in the long term.

**Comment by yishaigalatzer** [comment]
Let's first contact github support, if that doesn't work do the move

**Comment by harikmenon** [comment]
Agreedm @maartenba do you mind following up with GitHub on this? I don't have context on the previous conversation you had when we raised this issue. if you can forward me the threads I can do that as well.

**Comment by maartenba** [comment]
Did not have a thread with them, just looked at their docs and various search results out there. 

https://encrypted.google.com/search?hl=nl&q=github%20pages%20ssl
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it (SSL enabled only for their domain, no custom SSL)
https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8 (sign the petition :-))

**Comment by harikmenon** [comment]
I have opened a support request. Will update this thread once I hear back.

**Comment by harikmenon** [comment]
They got back to me and they said no :(. So, lets keep this one alive :)

**Comment by robertmuehsig** [comment]
Just looking through old issues here: This seems fixed or is obsolete @anangaur

**Comment by anangaur** [comment]
@robertmuehsig seems like it.. 
/cc: @skofman1

**Comment by skofman1** [comment]
We added https to out blog through CDN. This issue is no longer needed.
