### ISSUE TITLE
libphonenumber-csharp.unofficial 1.0.3

### ISSUE THREAD

**Issue by ashishgupta-kiwi** [NuGet/NuGetGallery#3133]
Hi
 we are using libphonenumber-csharp.unofficial 1.0.3  but this is not supported for **7042094906** phone number and Countryregion **"IN"**  

we are implementing  in windows phone below is my code

  public static bool ValidatePhoneNumber(string strphonenumber, string locale)
        
        {
            bool isValid = false;
            try
            {
                PhoneNumberUtil phoneUtil = PhoneNumberUtil.GetInstance();
                PhoneNumber swissNumberProto = phoneUtil.Parse(strphonenumber, locale);
              
                isValid = phoneUtil.IsValidNumber(swissNumberProto);
            }
            catch (Exception ex)
            {
            }
            return isValid;
        }
but it retrun false for 7042094906 number with locale IN please help me

**Comment by harikmenon** [comment]
Sorry, we dont support individual packages. please contact the owner directly for support using the Contact Owners link on the package details page here http://www.nuget.org/packages/libphonenumber-csharp.unofficial/
