### ISSUE TITLE
Push package not allowed via http, only https

### ISSUE THREAD

**Issue by nengberg** [NuGet/NuGetGallery#3135]
Hi,

I couldn't find a matching issue for this so I'll give it a shot.

When you are logged in on your account page and under the API Key tab you have an example how to push your package to the NuGet feed.

The example includes an address with http and not https which gives me an error when I'm trying to push:

```
Failed to process request. 'The requested resource can only be accessed via SSL.'.
The remote server returned an error: (403) Forbidden..
````

![image](https://cloud.githubusercontent.com/assets/2542686/16868826/0aa011ce-4a7a-11e6-9c4a-59f685a4f5fe.png)

After adjusting the protocol I'm allowed to push. Maybe the example code should be updated?

Best Regards
Niklas

**Comment by maartenba** [comment]
We'll get this fixed in our next deployment. Good find!
