### ISSUE TITLE
Catalog2Registration - Slow for packages with lots of versions

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3136]
For packages with lots of versions (RavenDB, FAKE, ...) the catalog2registration process is slow. Optimize it so registration entries are written much faster.

**Comment by skofman1** [comment]
@shishirx34 what's the status on this? Were the changes deployed to prod?

**Comment by shishirx34** [comment]
@skofman1  - From what I can gather, Maarten merged the above PR on Aug 1, and from our deployments I do not see there have been any deployments for Catalog2Registration on Prod. These changes seem to be deployed to Int and Dev. For Prod, the deployment seem to be partially done but never completed. 

We need to create a task to complete this deployment to Prod.

Should we be doing a regular Jobs deployment similar to Gallery?

**Comment by shishirx34** [comment]
@maartenba - I know its been a while, but, do you happen to remember the merged PR https://github.com/NuGet/NuGet.Services.Metadata/pull/80 which has been deployed to Dev and Int is safe to be deployed to Prod?

**Comment by maartenba** [comment]
It should be good :-)
