### ISSUE TITLE
Align package id validation with the client

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3142]
`nuget.exe pack` currently requires package id's to be <= 100 characters.
Allowed character set includes a dot, hyphen or ".NET word token" (`\w` in regex)

The gallery seems to be less restrictive currently (e.g. limits to 128 characters).
Also need to check on possible localization issues (Turkish i problem)

**Comment by shishirx34** [comment]
Note: To add package id validation to the HandlePackageEdit Jobs too.

**Comment by maartenba** [comment]
Note: Client has a `PackageIdValidator` which can be reused in the gallery (I think the gallery has its own, which can probably be removed)

**Comment by scottbommarito** [comment]
The only real difference between the Gallery's validation and the client's validation is the max character length difference, which is very easy to fix.

The Turkish i problem seems to be much more difficult. Basically it sounds like it would require us to [normalize](http://unicode.org/reports/tr15/#Norm_Forms) and [strip the diatrics](http://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net) of package ids when comparing to see if a package already exists.

I'll keep looking into this after lunch lol.

**Comment by emgarten** [comment]
> The only real difference between the Gallery's validation and the client's validation is the max character length difference, which is very easy to fix.

Use the client library. There should not be two copies of this code.

**Comment by scottbommarito** [comment]
@emgarten That's the plan now, but I need the number in NuGet.Client to be public before I can because we use the max package id length constant outside of the validation code.

**Comment by skofman1** [comment]
Lets revert this change since it has no value for customers.
