### ISSUE TITLE
SMTP email confirmation

### ISSUE THREAD

**Issue by haingoctu** [NuGet/NuGetGallery#3145]
I uncommented the `<add key="gallery.smtpuri"`... line and entered the valu of my smtp server, mail.mycompany.net so the line reads
`<add key="gallery.smtpuri" value=smtps://mail.mycompany.net" />`

however, I'm not getting an email. I tested that smturi 'mail.mycompany.net' in powershell and it's a GO:

`Send-MailMessage -From farts.mcgee@mycompany.net -To hai.tu@mycompany.net -Subject "test email" -Body "test e-mail body" -SmtpServer "mail.mycompany.net"`

Could it be because I'm lacking a port? Lacking authentication?

**Comment by maartenba** [comment]
Try  `smtp://`, the PowerShell example does not include any TLS/SSL security so let's see if the gallery can send it out that way :-) Note that the /admin dashboard also has error logs which may yield some additional info.

**Comment by haingoctu** [comment]
I did check out error logs in the admin dashboard but it wasn't tracking this issue. 

smtp:// is a go. Thank you.

**Comment by haingoctu** [comment]
If I wanted to, I may modify the registration process to have admins allow user's registeration instead of  this automatic system? 

I was thinking, since this is for the company, instead of the smtp, it would be sent to an admin email where the admin had to click the link to confirm.

**Comment by maartenba** [comment]
Sure, you can always make such changes in your own copy of the gallery
