### ISSUE TITLE
V3 jobs - Add job name to log

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3146]
We can't distinguish between logs from different jobs in AI since job name doesn't appear in traces. Should be part of serilog enrichers.

**Comment by xavierdecoster** [comment]
Perhaps a good place to fix this would be in the `LoggingSetup` class of `NuGet.Services.Logging` (make process name a mandatory enrichment): https://github.com/NuGet/NuGet.Staging/blob/dev/src/NuGet.Services.Logging/LoggingSetup.cs#L18

**Comment by skofman1** [comment]
The process name already appears.. the problem is that for V3 jobs all jobs have the same process name (ng.exe)

**Comment by skofman1** [comment]
Related issue in V3 jobs: when an exception is thrown it's not logged because the process exists shortly after the trace line.

**Comment by skofman1** [comment]
Fixed in this PR: https://github.com/NuGet/NuGet.Services.Metadata/pull/86
