### ISSUE TITLE
Pushing packages problem

### ISSUE THREAD

**Issue by haingoctu** [NuGet/NuGetGallery#3150]
I'm trying to push a package through the command line because uploading packages through the website works fine.

![untitled](https://cloud.githubusercontent.com/assets/14064416/17036107/dca69872-4f58-11e6-800b-bad068dd7554.png)

I attempted to browse the link mysite.com/NUGETGALLERY but i'm getting a 404.4

![image](https://cloud.githubusercontent.com/assets/14064416/17036118/e9f388a0-4f58-11e6-8176-8e2b381007bd.png)

**Comment by angrifel** [comment]
Hi @haingoctu. from your screenshot it looks like you are running in a local IIS. Usually , but no always, 405 errors are issued by the Request filtering module. 

Please check the settings for you IIS Server & Site. Open the feature IIS 'Request Filtering' and then go to the 'HTTP Verbs tab'. Make sure all verbs are allowed.

Let is know how it went.

**Comment by haingoctu** [comment]
In my IIS, should the physical path be pointing at the root of my whole git zip or at src (src\nugetgallery...) or something else?

**Comment by angrifel** [comment]
It should be pointing at src\nugetgallery. 
I suggest you take a look at the following page too

* [https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS](url)

it might be useful

**Comment by haingoctu** [comment]
Those instructions was a grind to walk through. I don't have experience doing this and I feel the instructions were very vague.

**Comment by haingoctu** [comment]
Pointing to src\nugetgallery for IIS paths worked. Thank you.
