### ISSUE TITLE
Pushing package through command line but unauthorized

### ISSUE THREAD

**Issue by haingoctu** [NuGet/NuGetGallery#3154]
I'm getting a 404.4 error server side. 
When I try to push with powershell, I get..

![image](https://cloud.githubusercontent.com/assets/14064416/17040375/4a61668a-4f6d-11e6-8df7-a56b88a5123d.png)

I attempt to enter my uesr and pass that I created. And I did register my api key using setapikey

**Comment by maartenba** [comment]
Cna you try capturing a Fiddler trace? (find "Fiddler" on https://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org) - this will help inspecting which result is sent back from your server. Do not share the resulting file on GitHub, as it will contain credential info.

Adding `-Verbosity Detailed` to the push command will also provide some extra logs.

It does look like an IIS issue again (perhaps Windows Integrated Auth is enabled in IIS?)

**Comment by haingoctu** [comment]
When you say IIS and windows integrated authentation perhaps being enabled , are you talking about the "Windows Authentication" here? It's disabled so that doesn't seem to be the problem.
![image](https://cloud.githubusercontent.com/assets/14064416/17059339/ac39e00a-4ff2-11e6-8367-6ed858a8b675.png)

I will check out Fiddler now. Thanks.

**Comment by haingoctu** [comment]
One more thing to add.

If I try to push a package on the same machine that is hosting this site, I get a different error.:

![image](https://cloud.githubusercontent.com/assets/14064416/17059737/9e728524-4ff4-11e6-933b-3887898b2efd.png)

**Comment by haingoctu** [comment]
What elements should I be posting for you from fiddler?

**Comment by maartenba** [comment]
The ones that occur on posting the package. Interested to hear the response code of that request.

**Comment by haingoctu** [comment]
There are a lot of different tabs and views. I'm still unsure.

![image](https://cloud.githubusercontent.com/assets/14064416/17061286/c3c0249c-4ffb-11e6-91b8-e8ff3e7f0a64.png)

**Comment by haingoctu** [comment]
Problem solved. WEBDAV is the culprit. It won't allow you to PUT.

https://betimdrenica.wordpress.com/2013/02/05/web-api-on-iis-8-0-405-method-not-allowed-for-put/

**Comment by maartenba** [comment]
Awesome :-) Good find!

**Comment by haingoctu** [comment]
Maartenba thanks for great support.
