### ISSUE TITLE
Pushing powershell module to NuGetGallery Trouble

### ISSUE THREAD

**Issue by haingoctu** [NuGet/NuGetGallery#3155]
So now my next objective is to use our private nuget gallery as a powershell cmdlet repo.  Attempted to push this module to my gallery.

![image](https://cloud.githubusercontent.com/assets/14064416/17066958/77e8276a-5017-11e6-8d5c-7d66261cbed2.png)

I performed these actions http://docs.myget.org/docs/how-to/publish-a-powershell-module-to-myget

I also did the invoke-webrequest from https://github.com/OneGet/oneget/issues/174

Fiddler's syntax view shows this  message:

`<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code /><m:message xml:lang="en-US">The requested resource does not support http method 'PUT'.</m:message></m:error>`

Header:
![image](https://cloud.githubusercontent.com/assets/14064416/17068744/c6f048c0-5020-11e6-80f7-71cf293f195a.png)

Googling this problem leads me to this, however, I think this fix is above my pay grade.

[((http://stackoverflow.com/questions/12765636/the-requested-resource-does-not-support-http-method-get))]

**Comment by maartenba** [comment]
Push should go to `/api/v/2/package` (don't see the `/package` suffix in the above logs)

**Comment by haingoctu** [comment]
Thanks.
