### ISSUE TITLE
Enable-LocalTestMe.ps1 looks up for makecert.exe even when it does not need to

### ISSUE THREAD

**Issue by angrifel** [NuGet/NuGetGallery#3157]
The current implementation of Enable-LocalTestMe.ps1 will lookup for makecert.exe when it is not provided in the command line. The lookup throws an error if makecert.exe is not found.

Makecert.exe is used to create a certificate when the script does not find a matching certificate for the site

The current implementation fails if the correct certificate is already present in the system and makecert is not found.

**Comment by maartenba** [comment]
I assume this relates to https://github.com/NuGet/NuGetGallery/pull/3158?

**Comment by maartenba** [comment]
Merged PR
