### ISSUE TITLE
Nuget Gallery setup either outdated or not newbie-friendly.

### ISSUE THREAD

**Issue by alexzxz** [NuGet/NuGetGallery#3162]
I'm currently stuck on **Step 4. Set up the website in IIS Express.**

Perhaps this setup is outdated since the Enable-LoclTestMe PS Script returns:
```
'hostnameport' is not a valid argument for this command. The syntax supplied for this command 
is not valid. Check help for the correct syntax. 
```
Checking the documentation on netsh, there is no hostnameport parameter, only ipport.

Does this file setup the website, since "http://nuget.localtest.me" is not returning anything.

**Comment by angrifel** [comment]
Could please provide details on how you invoked script?
Did you provide any arguments or no arguments at all?
Could you post a screenshot or a full dump of the script's output?

**Comment by alexzxz** [comment]
Here's a picture of the script running:
https://www.flickr.com/photos/49319171@N03/shares/o7T924

**Comment by scottbommarito** [comment]
Maybe try [adding "certstore=my"?](https://balofg.wordpress.com/2015/07/09/netsh-add-sslcert-by-hostname/)

The line is https://github.com/NuGet/NuGetGallery/blob/master/tools/Enable-LocalTestMe.ps1#L122 btw.

**Comment by alexzxz** [comment]
I don't think the "certstore=my" did anything. Also it might be "certstorename"

I'm using [this](https://msdn.microsoft.com/en-us/library/windows/desktop/cc307220(v=vs.85).aspx) as reference. 

My setup is Windows 7 Enterprise 2009 with Powershell 5.

**Comment by scottbommarito** [comment]
That page you linked is for Windows Vista and Windows Server 2008. I've been trying to find docs online for a much more recent version but I can't seem to find any.

Can you try running `Netsh http add sslcert help`?
Mine looks like `Usage: add sslcert hostnameport=<name:port> | ipport=<ipaddr:port> | ccs=<port>...` If your doesn't have a `hostnameport=` parameter you might need a newer version of Netsh to run the script.

**Comment by alexzxz** [comment]
Yep mine is definitely different. 

Usage: add sslcert [ipport=]<IP Address:port> 
             [certhash=]<string> 
             [appid=]<GUID> 
             [[certstorename=]<string> 
              [verifyclientcertrevocation=]enable|disable 
              [verifyrevocationwithcachedclientcertonly=]enable|disable 
              [usagecheck=]enable|disable 
              [revocationfreshnesstime=]<u-int> 
              [urlretrievaltimeout=]<u-int> 
              [sslctlidentifier=]<string> 
              [sslctlstorename=]<string> 
              [dsmapperusage=]enable|disable 
              [clientcertnegotiation=]enable|disable]       

Tried googling for a Netsh windows update, can't seem to find this. Is it part of some bundle/package?

**Comment by scottbommarito** [comment]
The easiest way would be to upgrade to Windows 10. I don't know if you can upgrade only Netsh though.

**Comment by angrifel** [comment]
hostnameport is part of a feature call Server Name Indication (SNI). SNI allows you to bind a certificate to a hostname and port rather than to an ip address port. SNI is supported on windows 8 and upwards.

upgrading seems to much to run the gallery so I would suggest you just run it using http or create a certificate yourself and bind it to your local ip address

**Comment by angrifel** [comment]
@scottbommarito I think a modification to the documentation should be made stating that Enable-LocalTestMe.ps1 is supported only on Windows 8 and up.

**Comment by angrifel** [comment]
@scottbommarito - or maybe degrade the functionality of Enable-LocalTestMe.ps1 to only create the HTTP site binding and avoid creating the HTTPs binding when targeting windows 7?

**Comment by scottbommarito** [comment]
@harikmenon @maartenba Any thoughts?

**Comment by harikmenon** [comment]
I actually did this 2 days ago and it worked for.

**Comment by scottbommarito** [comment]
@harikmenon You ran it on Windows 7?

**Comment by harikmenon** [comment]
nope 10 :)

**Comment by alexzxz** [comment]
Yeah, the reason I can't casually upgrade to Windows 10 is because this is a company computer, hence the Windows 7 Enterprise, lots of security restrictions. I'm pretty sure there's plenty of companies fine with Win 7 and don't see the need to upgrade.

**Comment by maartenba** [comment]
For @harikmenon @yishaigalatzer to decide. Not sure we want to spend a lot of time in making it work for Windows 7, given https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Windows%207%20Enterprise&Filter=FilterNO.

There are other alternatives around as well (http://docs.nuget.org/Contribute/Ecosystem) which can be used.

**Comment by harikmenon** [comment]
@qianjun22 I will Jun make the call here given our recent focus on security related and infrastructure work. This is probably not the highest priority work at this time.
