### ISSUE TITLE
Deleted (unlisted) package releases visible to public (e.g. via shields.io)

### ISSUE THREAD

**Issue by jochenwezel** [NuGet/NuGetGallery#3167]
Deleted (or let's say "unlisted") package releases are currently visible to the public (e.g. via shields.io).

Shields.io (and potentially others) appear to be consuming a nuget.org API which does not give listed/unlisted status (there are other APIs which do give this info).

@drewgil As you stated, further evaluation/digging needs to be done. 
### Test case / sample

At https://github.com/CompuMasterGmbH/cammIntegrationPortal there is a badge icon for NuGet.CIP.Core which shows a stable version v4.10.206.103. This functionality is provided by shields.io which provides the markup for the readme at github. I consider Shields.io to be just a „consumer“ of your APIs.

At https://www.nuget.org/packages/cammWM/ I have deleted (=unlisted) all packages except the pre-release ones.

**Comment by drewgil** [comment]
Note that this is purely about unlisted packages (not deleted ones). shields.io is consuming the v3 flatcontainer API from nuget.org, which presents all packages in a lightweight format and no additional metadata (specifically, no listing status). The fix may be for shields.io to call the registration blobs for listing status, or for there to be an addition to the flatcontainer response specifically for this. TBD, but likely the former. This issue can track progress if desired even if it's purely shields.io work.
@joelverhagen @maartenba @qianjun22

**Comment by jochenwezel** [comment]
>shields.io is consuming the v3 flatcontainer API from nuget.org
sounds as this API version should be changed to only report listed packages (and not unlisted packages) to 3rd parties

**Comment by maartenba** [comment]
Unlisted packages can still be installed, the only thing "unlisted" means is that the package version no longer shows in search. Going with registrations is the right way here (or adding another API)

**Comment by maartenba** [comment]
Just did a PR to shields.io to get this fixed.

**Comment by skofman1** [comment]
@maartenba, Can this issue be closed?

**Comment by maartenba** [comment]
Well https://github.com/badges/shields/pull/769 is still open... This one is more of a tracking issue :-)

**Comment by skofman1** [comment]
This: badges/shields#769 went live! (thanks @maartenba ) 🥇
