### ISSUE TITLE
Gallery should validate packages same as Client(?)

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#3177]
It looks like the client is doing some validations that the Gallery does not do when uploading the package. This causes issue when looking up 'Installed' package in VS2015 Nuget Package Management for solution. I am unsure if this is the desired behavior and its a bug on Nuget.Client, and the Nuget.Client should ignore these elements instead.

Steps:

1. I uploaded a package with following metadata to DEV
``` xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>DeltaX.RandomTest1</id>
        <version>2.0.0</version>
        <authors>shishirh</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Creating a random generator test package</description>
    </metadata>
</package>
```
2. Install the above Package after indexing from VS 2015 Nuget Package manager to my solution.

3. Go to `Installed` tab for the Nuget Package Manager it shows 'Error occurred'.
![image](https://cloud.githubusercontent.com/assets/1646506/17344056/9e1d5f4e-58b5-11e6-8b0b-68be092e5da4.png)

 The errors in output:
```
LicenseUrl cannot be empty.
IconUrl cannot be empty.
ProjectUrl cannot be empty.
```

Its possible that this could be the issue on VS2015 extension for Nuget package management.

**Comment by scottbommarito** [comment]
duplicate of https://github.com/NuGet/NuGetGallery/issues/3142

**Comment by scottbommarito** [comment]
jk that one is related to package id only, but I think there's another issue somewhere about this specifically

**Comment by skofman1** [comment]
@emgarten @rrelyea

**Comment by emgarten** [comment]
Those fields are not required, however the client does fail if they exist but do not contain a valid url. Did DEV modify the nuspec? I don't think the client would fail on the nuspec displayed in the issue here.

**Comment by scottbommarito** [comment]
@shishirx34 can you try installing the package that you uploaded before uploading to see if the upload process modified the nuspec?

**Comment by shishirx34** [comment]
@emgarten - I downloaded the uploaded package from the DEV, and it has the same nuspec as the one shown above. You can see it here: https://dev.nugettest.org/api/v2/package/DeltaX.RandomTest1/2.0.0

**Comment by emgarten** [comment]
Seems like a client bug then, this field isn't required. What version of NuGet are you using?

**Comment by shishirx34** [comment]
Nuget Package Manager 3.4.4
Package Manager Console Host Version 3.4.4.1321

**Comment by shishirx34** [comment]
@emgarten - do you want me to open the bug on client?

**Comment by emgarten** [comment]
@shishirx34 that would be great, thanks!

**Comment by shishirx34** [comment]
Closing this for the client bug opened.
