### ISSUE TITLE
How to display the proper downloads count for NuGet packages that hosted from private NuGet server ? 

### ISSUE THREAD

**Issue by mathikp** [NuGet/NuGetGallery#3181]
Hi Team,

We have hosted our NuGet packages in private NuGet server. its working fine for all the functionalities(install/uninstall/updates). But the downloads count  was not increased in every downloads or installation. We have configured the NuGet.Server nuget package to configure the nuget server. Is there any ways to manage the downloads count in our NuGet server ? 

![downloadscout](https://cloud.githubusercontent.com/assets/13851265/17397647/a73c35bc-5a56-11e6-89b2-1de7a5dee4bb.png)

Thanks in advance.

**Comment by maartenba** [comment]
NuGet.Server does not track download counts.

**Comment by mathikp** [comment]
Hi @maartenba ,

Thanks for the update. Can you suggest us how to manage the downloads count in our private NuGet server **or** How to setup a private NuGet server with track the downloads count ?
