### ISSUE TITLE
How to track the NuGet downloads count in private NuGet server ? 

### ISSUE THREAD

**Issue by mathikp** [NuGet/NuGetGallery#3182]
From the #3181 thread we came to know didnt able to track the downloads count from NuGet.Server web apps. How to manage the downloads count in our private NuGet repository ?

**Comment by maartenba** [comment]
@mathikp You can spin up a different NuGet server, for example the NuGet gallery, or look at any of the other options out there (https://docs.nuget.org/Contribute/Ecosystem).

**Comment by mathikp** [comment]
@maartenba thanks for the update. We got a documentation about the NuGet server projects by below link. 
https://docs.nuget.org/Create/Hosting-Your-Own-NuGet-Feeds#Step-2%3a-Install-the-NuGet.Server-Package

But we cant able to find the steps to publish the NuGet gallery projects. Can you help us to redirect that ?

**Comment by maartenba** [comment]
More info can be found in the README here: https://github.com/NuGet/NuGetGallery
