### ISSUE TITLE
Feed2Catalog fails when a package contains unicode characters

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3184]
We had a live site issue caused by uploading this package: https://dev.nugettest.org/packages/Z%CC%88%CC%8D%CC%90%CC%83%CC%8A%CD%8B%CC%81%CC%A1%CC%9C%CD%8DA%CC%BD%CD%A7%CD%97%CC%9C%CC%A3%CD%8D%CC%AC%CC%9E%CC%9D%CD%89L%CC%83%CC%8C%CD%A4%CC%B8%CC%96%CD%95%CC%A4%CC%A0%CC%B9%CC%98%CD%96G%CC%80%CD%AA%CD%93%CC%9D%CD%93%CC%B0O%CD%8C%CD%88/1.0.0

Feed2Catalog was failing with this error:
An Attribute with an incorrectly encoded URIRef was encountered, URIRef's must be encoded in Unicode Normal Form C
[Source XML]
rdf:about="https://api.nuget.org/v3/catalog0/data/2016.08.08.20.46.32/z̡̜͍̈̍̐̃̊͋́a̜̣͍̬̞̝͉̽ͧ͗l̸̖͕̤̠̹̘͖̃̌ͤg͓̝͓̰̀ͪo͈͌.1.0.0.json"

**Comment by skofman1** [comment]
Fix: https://github.com/NuGet/NuGet.Services.Metadata/pull/84

**Comment by harikmenon** [comment]
Curious, why did a change in the dev environment affect prod?

**Comment by scottbommarito** [comment]
@harikmenon I think she deleted the package from Prod and then uploaded it to Dev as an example.

**Comment by skofman1** [comment]
What @scottbommarito  said.
