### ISSUE TITLE
Status page shows uncorrelated results between North Central US and West US

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3185]
![image](https://cloud.githubusercontent.com/assets/16807822/17499839/1b8e35d8-5d85-11e6-84bb-74166be0b65a.png)

The index lag was identical for all environments.

**Comment by skofman1** [comment]
@maartenba ?

**Comment by maartenba** [comment]
Checked the blobs, seem this is a caching issue. Investigating further...
