### ISSUE TITLE
Download counts not incrementing

### ISSUE THREAD

**Issue by carnageX** [NuGet/NuGetGallery#3192]
I've setup a private instance of the NuGet Gallery on premises on our network, hosted by IIS.  I have it all setup and working (for the most part), but the Download counters for the packages are not incrementing at all.  

I've tried looking through the source, but am unsure where the increment even happens at.  Any insight would be helpful, thanks!

**Comment by maartenba** [comment]
They shou

**Comment by maartenba** [comment]
Oops, mobile... Can you see the downloadcount in the database being incremented on download?

**Comment by carnageX** [comment]
Nope, the DownloadCount field stays at 0.

**Comment by maartenba** [comment]
Can you check `Web.config` and make sure this one is in there? (set to `true`)

```
<add key="Feature.TrackPackageDownloadCountInLocalDatabase" value="true" />
```

**Comment by carnageX** [comment]
Nope, that's not in my config file.  The only feature config I have is:
<add key="Feature.FriendlyLicenses" value="" /> 

Should I add that and see if it works?

**Comment by maartenba** [comment]
Yes please :-)

**Comment by carnageX** [comment]
Sorry about the delay. 

Added the config option and it appears it still isn't incrementing.

**Comment by maartenba** [comment]
ApiController has a DownloadPackage method which should do this

**Comment by carnageX** [comment]
Is that GetPackage(string id, string version) - with the action attribute GetPackageApi ?  I don't see a "DownloadPackage" in ApiController, otherwise.

**Comment by maartenba** [comment]
If the method has a check for "TrackPackageDownloadCountInLocalDatabase" then yes

**Comment by carnageX** [comment]
Ah, it doesn't.  My version doesn't have the block: 
if (ConfigurationService.Features.TrackPackageDownloadCountInLocalDatabase)
{
        await PackageService.IncrementDownloadCountAsync(id, version);
}

Must be because I only downloaded the latest release (from August 2015) that's listed in the Release tab of the Github, rather than forking the current version?

**Comment by maartenba** [comment]
Yeah best fetch latest

**Comment by carnageX** [comment]
Ok...looks like the DownloadCount column is actually incrementing now so that's good.  

However, a new problem has arisen after upgrading...I kept my original database that I had (which had a few existing packages and a single user [me] in it).  Now when I go to download the package, either through the web portal or through VS's package explorer, I get a 404 response. 

It gets to the FileSystemFileStorageService class, and within the CreateDownloadFileActionResultAsync method it throws the 404 when it gets to the check if the file path exists.  It's like it's not actually creating the package for temp download on disk from the database.

**Comment by maartenba** [comment]
Can you make sure to update the database (EF migrations)

**Comment by carnageX** [comment]
Yeah, I already made sure to do that after changing the Web.Config to point to my DB.  Did it again just to make sure, and it does indeed say there's no pending migrations.

**Comment by maartenba** [comment]
Can you also verify Web.config is configured to point to disk (filesystem storage) instead of Azure? Other than that, you may want to just re-upload packages, not sure what version was under "releases" but it must be an old one...

**Comment by carnageX** [comment]
Hmm, may be related to permissions settings on the App_Data\Files directory now.  Tried to upload a new package to see if I could get it to work, and it errors out on the upload: 

Exception Details: System.UnauthorizedAccessException: Access to the path '~/App_Data/Files' is denied. 

ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. ASP.NET has a base process identity (typically {MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the configured application pool identity on IIS 7.5) that is used if the application is not impersonating. If the application is impersonating via <identity impersonate="true"/>, the identity will be the anonymous user (typically IUSR_MACHINENAME) or the authenticated request user. 



Which is weird, because it's using the same account it was before on my old/working version of the gallery on the server, which should already have it's file permissions set...

**Comment by maartenba** [comment]
Going to close the issue, but feel free to keep the discussion going.

Can you double-check permissions?

**Comment by carnageX** [comment]
Yeah I'm working with one of our web server guys now to look at permissions.  

Will the "Gallery.FileStorageDirectory" config item accept UNC paths?

**Comment by maartenba** [comment]
It will need a drive mapping I think, haven't tried it to be honest.

**Comment by carnageX** [comment]
So following up on this because I finally have another chance to work on it a bit more... Working with our web team, we finally found out that it was trying to write to a system directory (even if temporary?), which is: C:\Windows\System32\inetsrv\~ 

Turns out I didn't specify the Gallery.FileStorageDirectory configuration item; I set that to the UNC path of the app's App_Data\Files folder and uploads started to work just fine.

**Comment by maartenba** [comment]
Cool! Thanks for letting us know
