### ISSUE TITLE
Delete packages that are unlisted and have zero downloads.

### ISSUE THREAD

**Issue by PureKrome** [NuGet/NuGetGallery#3193]
Hi :wave: 

Sometimes packages get pushed up to nuget accidently. By accidentally, i mean with some bad meta data (for example) or bad files attached or that it should not have been pushed up at all (for whatever reasons). Or CI servers have an error and this error ends up bubbling up to the nuget package which is then auto pushed up.

Accidents happen, in all shapes and forms.

So - could we please allow us to delete a package if:
- It's unlisted 
- Has _zero_ downloads.

Like, right now the best we can do is hide it via unlisting. But it's still there to the public.

I totally get the concept that if 1-or-more downloads have occurred, then _someone_ could be requiring it (hello leftpad anyone?) .. but if -zero- people have downloaded it??

Or even better.... have a publish but hide for 'x' minutes (setting, per account or even nuget push command). .. so if the package was just pushed up ... and is in this 'auto-wait' hide state .. it's a safety precaution allowing us to delete it, if we have to?

Just some thoughts/requests.

**Comment by maartenba** [comment]
We are working on a feature that will prevent these accidental downloads, but it's still out for a bit. For now, your best bet is to contact support for the package in question and ask for removal.
