### ISSUE TITLE
Gallery fails requests due to AI exception

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3194]
Thrown exception:

> message is a required field for Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry
> 
> System.Web.HttpException:
>    at System.Web.CachedPathData.ValidatePath (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
>    at System.Web.HttpApplication+PipelineStepManager.ValidateHelper (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

**Comment by maartenba** [comment]
Where is it thrown? Under what circumstances?

**Comment by skofman1** [comment]
You can see a bunch of those in Gallery AI. Didn't investigate it yet.

**Comment by scottbommarito** [comment]
It seems to be happening on various `GET packages/someidhere/someversionhere`. It's quite rare, happening only seven times in the last week, or 1.7% of our total exceptions.

**Comment by maartenba** [comment]
Any stack traces of interest?

**Comment by skofman1** [comment]
Nope

**Comment by shishirx34** [comment]
It Looks like these are the URLs with space character in the end `%20` which throws these exceptions. 
Setting `relaxedUrlToFileSystemMapping="true"` for `httpRuntime` config should prevent requests from failing and not throw these exceptions.
