### ISSUE TITLE
EnsureNuGetPackageBuildImports Target Always Causes Errors

### ISSUE THREAD

**Issue by MelbourneDeveloper** [NuGet/NuGetGallery#3195]
There are many project types created by Visual Studio that add a "EnsureNuGetPackageBuildImports" target element to csproj files. In this case the element is defined in a Xamarin Forms project. It was newly minted in the last week or so from a standard VS template. The target looks something like this in the csproj file:

```
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Xamarin.Forms.2.3.0.107\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xamarin.Forms.2.3.0.107\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets'))" />
  </Target>
```

The element is usually benign until you move the project to a different location on the hard drive, or another developer tries to compile the code. When this happens, you get:

_This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\Xamarin.Forms.2.0.0.6482\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets._

This error message is very misleading and untrue. I've wasted countless hours in many projects trying to get Visual Studio to refresh the packages, but the error just keeps coming up even though there are no other compilation problems in the project. I don't know if the element is useful or not, but the various teams that create the templates need to either remove this element from the templates, or correct the element so that it doesn't cause errors. I can't even count how days I sat there scratching my head over this error until I finally found the error text in the csproj file. Yesterday, my colleague experienced it when she opened up an ASP MVC app. The whole point of NuGet is supposed to be that if the other person doesn't have the libraries, the libraries are silently downloaded and compilation ensues.

Other people can recreate this problem, and there are people reporting this problem all over the place. Here is my original MSDN thread on the topic:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/300b0549-58c9-4c50-bd64-7c82516495a9/nuget-error?forum=visualstudiogeneral&prof=required

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#3320
