### ISSUE TITLE
Nuget.server : Published date property is not preserved but promoted daily

### ISSUE THREAD

**Issue by igorWe** [NuGet/NuGetGallery#3197]
NuGet.Server v2.11.2.0 deployed and running, the publish date property for all packages seems to be promoted daily to a new date: e.g :
Yesterday: <d:Published m:type="Edm.DateTime">2016-08-15T17:35:22.3070716Z</d:Published>
Today: <d:Published m:type="Edm.DateTime">2016-08-16T12:23:22.3070716Z</d:Published>
etc.
while the update time seems to be preserved:
<updated>2016-07-25T08:53:15Z</updated>

**Comment by maartenba** [comment]
Strange... The published and last updated time use the same source:

```
                Published = package.Published.HasValue ? package.Published.Value.UtcDateTime : DateTime.UtcNow,
                LastUpdated = package.Published.HasValue ? package.Published.Value.UtcDateTime : DateTime.UtcNow,
```

Can you check your packages folder and look at the timestamp on the `.bin` file? Does it match the date you are seeing?

**Comment by igorWe** [comment]
Close, but no match either....
.bin TS:  2016-08-16 13:32
package: 2016-08-16T14:01:27.902389Z

**Comment by maartenba** [comment]
If you restart the application pool, does that also update the tiemstamp you are seeing on the feed?

**Comment by igorWe** [comment]
Yes, it does.

**Comment by igorWe** [comment]
Is this a proper behavior of the server ? I can't find it in the documentation.

**Comment by maartenba** [comment]
It is a proper behaviour, as the underlying repository from NuGet.Core reads the date from the file, and if not possible it will fall back to the current time.

**Comment by igorWe** [comment]
Does the .bin holds the derived data ? It can't the .nuspec.

**Comment by maartenba** [comment]
It looks like NuGet.Core's repository implementation does not read the correct value, hence we use the current time the first request is made.

**Comment by RobSwDev** [comment]
Why is this by design? Are there any workarounds we can use?

**Comment by pantonis** [comment]
@maartenba And what is the correct value?
