### ISSUE TITLE
Supported frameworks not always populated correctly

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3215]
For `Newtonsoft.Json` (for example), [this line of code](https://github.com/NuGet/NuGetGallery/blob/dbe578b69eefd03671977974d221d2ceb680df1e/src/NuGetGallery/Services/PackageService.cs#L81) seems to ignore all frameworks if one of them is null, instead of just skipping the null one and adding all others. So that means this data is not in the database...

![newtonsoftnono](https://cloud.githubusercontent.com/assets/485230/18000294/9b485e88-6b7d-11e6-86d5-35b438d32a3f.png)

Note that this [was by design](https://github.com/NuGet/NuGetGallery/blob/dbe578b69eefd03671977974d221d2ceb680df1e/tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs#L929), but it makes no sense.

Please fix (fairly trivial) and reflow all packages that have no supported frameworks data in the database.

**Comment by maartenba** [comment]
I just published a PR. Whoever takes this during my vacation, please validate and note that once deployed, **you will have to reflow all packages that have no supported frameworks data in the database** (there is logic for this in the gallery, will need a little custom coding to run it for all)

**Comment by shishirx34** [comment]
We can use this same issue to track the work needed to be done to reflow all packages that have no supported frameworks data in the database.

**Comment by maartenba** [comment]
@qianjun22 @shishirx34 @yishaigalatzer Can I plan a reflow of these packages?

Will have some impact on catalog, registrations and search as there are quite some packages that need updating; ~3.000 registrations if I recall correctly. End result is we will suffer some index lag for an hour or two, but supported frameworks will be populated correctly.

If we don't want the index lag, we could reflow without telling the catalog things changed (which seems like a good thing to do, as the catalog nor registrations contain this info) and just reindex once we reflowed. That will bring index lag to ~30 minutes. Thoughts?

**Comment by shishirx34** [comment]
I am fine with either approach. For the first one it would be best to run when we have the least load on our servers ensuring that it doesn't result in cascading index lag. To be safe I think it would be better to go with the second approach.

**Comment by maartenba** [comment]
One important functional question: currently, we do not write frameworks if there is an “Any” moniker for the package. Is that something we want to keep? (for example, Newtonsoft.Json 9.0.1 has an Any moniker and would not get any supported frameworks written). So:

* For this case, do we write an empty list of supported frameworks (as any are supported)
* Or do we write “any” to the output? (so that search can also output “any”)
* Or do we write all supported frameworks in the same way PackageArchiveReader sees them? (any, net45, …, the whole list)

**Comment by skofman1** [comment]
verified
