### ISSUE TITLE
NuGet.Server update to NuGet.Core 2.14.0

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#3219]
Update NuGet.Server to depend on NuGet.Core 2.14.0

This will provide SemVer 2.0.0 support until https://github.com/NuGet/NuGetGallery/issues/3123 is complete.

I've done some basic testing on this and was able to push and install packages with NuGet.Server after updating NuGet.Core on my own installation.

Related to: https://github.com/NuGet/Home/issues/1359

**Comment by justmara** [comment]
SemVer? Really? I just realized that my project based on Nuget.Server is completely broken. It was based on nuget 2.6 and i cannot be updated even to 2.8.* without refactoring because of api changes in NuGet.Server.Lucene.Web, and 2.10.* is a total internal redesign in MINOR version. Are you seriously talking about SemVer here?

**Comment by emgarten** [comment]
@justmara there are no breaking API changes for SemVer in 2.14.0, this issue is to update the package dependency.

2.6 -> 2.10.1 on the other hand looks like +2 years and 11 stable releases of changes.

**Comment by maartenba** [comment]
@emgarten keep us posted when 2.14.0 drops

**Comment by justmara** [comment]
@emgarten SemVer is not about numbers (years or stable releases) but about **Versioning** and **Compatibility**. And it strictly declares these three statements:
```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```
NuGet.Server fails both first two.

**Comment by maartenba** [comment]
@justmara That is a different discussion and you are absolutely right. We can't roll-back the current version that is out there, unfortunately, as that would also break projects out there.

**Comment by emgarten** [comment]
NuGet.Core 2.14.0 is available on nuget.org now. NuGet.Server should be updated to depend on it by default to avoid failures on netstandard/netcoreapp packages.

The current dependency on NuGet.Core 2.11.1 does not contain support for netstandard. This leads to NuGet.Server displaying ``unsupported`` as the dependency group TFM which causes the client to select the wrong group, or no dependencies at all.

In the past it has been very hard for users to track down the cause of this problem, so it would be great if we could avoid it by updating NuGet.Server to work out of the box.

//cc @yishaigalatzer @rrelyea

**Comment by joelverhagen** [comment]
This is completed in `dev` and `master` of NuGet.Server.
