### ISSUE TITLE
can not download caffe 3rd package using nuget. 

### ISSUE THREAD

**Issue by BaiYu0120** [NuGet/NuGetGallery#3220]
I can not download caffe 3rd package when compile caffe using VS2013 Nuget.What's the problem?

**Comment by shishirx34** [comment]
@emgarten @joelverhagen looks like client issue?

**Comment by emgarten** [comment]
@BaiYu0120 would you open an issue on https://github.com/nuget/home/issues containing the steps for how to reproduce this error, and also the errors you are seeing?
