### ISSUE TITLE
Command line "list outdated packages."

### ISSUE THREAD

**Issue by brianbegygr** [NuGet/NuGetGallery#3225]
This is a feature request for a command line "list outdated packages" feature.  This would be similar to what "lein ancient" provides for Clojure developers.  

NuGet command line offers an update command, but I'm looking for a read-only version.  Just show me a list of all packages that are out of date in a solution and let me decide.  This is something we could automate as part of our build process.

I'm open to just pulling the source and building this, but I'm looking for guidance on if this is something the team considered and explicitly rejected before I start.

**Comment by emgarten** [comment]
@brianbegygr this sounds like a good idea, would you log it on http://github.com/nuget/home/issues  nuget.exe issues are tracked there.

**Comment by maartenba** [comment]
Closing for now, do re-open at http://github.com/nuget/home/issues :-)
