### ISSUE TITLE
Package update after delete cache in NuGet.Server v2.11.2.0

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#3227]
https://github.com/NuGet/Home/issues/3407

From @mahen123 

Hello

I am using latest NuGet.Server v2.11.2.0 as a my local repository.It hosted at my local system.
My problem is that newly added package is not listed while refresh the link.
For example In my server Packages folder has 5 .nuget package.But when i add new one , It will not show after the link refresh.

It will show the new one after deleting "aatfsbuild.cache.bin" file from server packages.
Pleaese suggest the way to add new package without delete file.

http://localhost:57958/nuget/Packages

Thanks,
Mahen

**Comment by maartenba** [comment]
@mahen123 does it refresh when hitting http://localhost:57958/nuget/Packages?
How are you adding the new package, usign nuget.exe push or by copying it to the server?

**Comment by maartenba** [comment]
Related to https://github.com/NuGet/Home/issues/3340

**Comment by maartenba** [comment]
Can you try updating to this (prerelease!) version of NuGet.Server?
```Install-Package NuGet.Server -Version 2.11.3-dev-0012 -Source https://dotnet.myget.org/F/nuget-build/api/v2```
