### ISSUE TITLE
UpdateLicenseReports doesn't log to AI

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3231]
[Currently, the UpdateLicenseReports job logs to Azure blob storage (which is really ugly).](https://github.com/NuGet/NuGet.Jobs/blob/master/src/UpdateLicenseReports/Scripts/UpdateLicenseReports.cmd#L10) We should make it log to AI by supplying an instrumentation key.

**Comment by skofman1** [comment]
@scottbommarito , you fixed this, right?

**Comment by scottbommarito** [comment]
Yes.
