### ISSUE TITLE
AggregateCdnDownloadsInGallery fails when all package ids are not case-insensitive

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3232]
If two packages have an identical `Lower(Id)` in the DB, the `Stats.AggregateCdnDownloadsInGallery` job fails. The job should handle these cases gracefully and not crash.

For example, `Lower(iamapackage)` is equivalent to `Lower(İamapackage)`. If the job were to see both of these packages ids in the DB, it would crash.

**Comment by scottbommarito** [comment]
@xavierdecoster

**Comment by xavierdecoster** [comment]
Fixed by https://github.com/NuGet/NuGet.Jobs/issues/67
