### ISSUE TITLE
Add metrics to measure total time required to publish/register a package in gallery.

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#3239]
The needed work would be on catalog2Registration job. Maarten's suggested method below:

• Add a Microsoft.ApplicationInsights dependency to NuGet.Services.Metadata.Catalog
• Add a new class, something like:

```
public class EventTelemetryTracker
    {
        private readonly string _eventSourceName;
        private readonly bool _enabled;
        private readonly TelemetryClient _telemetryClient;

        public EventTelemetryTracker(string eventSourceName, bool enabled)
        {
            _eventSourceName = eventSourceName;
            _enabled = enabled;
            _telemetryClient = new TelemetryClient();
        }

        public void TrackEvent(string eventName, string subject, TimeSpan duration)
        {
            if (!_enabled)
            {
                return;
            }

            _telemetryClient.TrackEvent(new EventTelemetry
            {
                Name = _eventSourceName,
                Properties =
                {
                    { "Subject", eventName }
                },
                Metrics =
                {
                    { "DurationInMs", duration.TotalMilliseconds }
                }
            });
        }
    }
```

• In Catalog2Registration.cs, we want to pass a new instance of the above class to RegistrationCollector (and in my branch, to the RawJsonRegistrationCollector), and let it flow through function calls down to where we need it
• Wherever we want to track an event, call into the above class.

```
TrackEvent("Finished batch for registration", registrationId, stopwatch.TotalMilliseconds);
```

Or make it an IDisposable thing 

```
            using (telemetryTracker.Track("Write registration", "Newtonsoft.Json"))
            {
                // do work
            }
```

This should, I think, make it possible to inspect these values in AppInsights (and differentiate based on the passed in eventSourceName). My class above is far from optimized though (the way I track time may introduce some performance loss)

**Comment by scottbommarito** [comment]
(fixed the formatting for you)

**Comment by shishirx34** [comment]
Update: Putting the requirement and its possible that we could get a better way to do this.

Requirement:
- How long does it take to consume a package at the earliest after it has been published/uploaded in the gallery.

Methods:
Earlier I thought that we can get the required information just from Catalog2Registration, but @skofman1  pointed out that we won't be able to consume the package until it is available in the lucene index.

So the alternative:
1. We send a timestamp(event) to the AI when the package is published/uploaded from gallery.
2. We send a timestamp(event) to the AI when the `feed2Catalog` processes it
3. We send a timestamp(event) to the AI when the `catalog2Registration` processes the package.
4. We send a timestamp(event) to the AI when the `catalog2Dnx` processes the package.
5. We send a timestamp(event) to the AI when the `catalog2lucene` processes the package.

To get the required information, we can get the difference of 5 - 1, this would be the time took to upload and the package become available from search(this I believe is the index lag that we show on the status page).

We can get the difference of 3 - 1, this would be the time when you can technically consume the package if you know the Package ID and the Version.

2, 3, 4 represent additional data that we can use to measure the performance of other jobs for a package flowing through the pipeline.

@maartenba, @skofman1 @xavierdecoster @ryuyu @scottbommarito thoughts?

**Comment by scottbommarito** [comment]
Do you know if AI has an easy way to parse multiple AI `customEvents` in a single query? It seems like something they would have but I've never experimented with their language outside of simple queries.

I think we would need to make another AI instance for this to work as well, since the gallery and the jobs use separate ones and finding the difference of values across multiple AI instances is probably much harder. Also, if we integrated this data with the rest of our `customEvents` it could potentially clutter the data and make queries on our jobs slower than they already are.

**Comment by maartenba** [comment]
I like the fact that this would enable end to end measuring, as well as per-job measuring. If AI querying allows this sort of aggregation?

**Comment by shishirx34** [comment]
Yes I have done it in the past in my previous project. Aggregating `custom events` by correlating is possible. We can get required information using kusto query in AI's Analytics. The only thing we need to ensure is having a common ID to identify the event through different reportings. We can come up with a structure that we can persist across different jobs for events, not worried about it.

@scottbommarito - good point, we cannot aggregate data over the different instances of application insights. Might need a little investigation on how we can use multiple Application insight reporting from gallery and jobs. Otherwise I think just the reporting on the jobs alone would also be sufficient for our purposes.

**Comment by skofman1** [comment]
Looks good. Will give us good performance analysis of the pipeline. Regarding code, we can have a common library for tracking telemetry. This library can provide a general interface for telemetry tracking, and hide the fact that it's using AI.

**Comment by ryuyu** [comment]
It seems like a good plan to me.
The only thing to keep in mind is when during the step the timestamp will be.
The jobs running takes a nonzero amount of time, so if we send a timestamp at the start of an event, we will miss the processing time of the event itself.
Assuming that we only send at the end of a step, we will miss the time of the given step/transition between steps when computing the time.
I would assume that ideally, we would stamp start and end, but at that point, i would be concerned about the overhead of sending these as that will effectively double the number of AI points we send.

**Comment by maartenba** [comment]
Track start and end in code, send one event "processed X" with a few properties (start, end, duration) which we can use in queries?

**Comment by skofman1** [comment]
Is this completed? Can be closed?

**Comment by shishirx34** [comment]
This hasn't been addressed yet. Available to grab.
