### ISSUE TITLE
Get-Package command in Find-Package example

### ISSUE THREAD

**Issue by BartHamer** [NuGet/NuGetGallery#3241]
The Find-Package examples section contains the following:

```Get-Package jquery -AllVersions -ExactMatch```

which should be

```Find-Package jquery -AllVersions -ExactMatch```

**Comment by maartenba** [comment]
@karann-msft Looks like a docs issue, can you look into it?

**Comment by karann-msft** [comment]
@BartHamer can you provide the link to the doc.

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #3528](https://github.com/NuGet/Home/issues/3528) via [**ZenHub**](https://www.zenhub.com/)
