### ISSUE TITLE
Gallery: on password change wrong message appears

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3243]
Scenario:
1. Login
2. Click on "Password Login" => Change button
3. Change password and uncheck reset API key".
4. Click "Change"

After page reload this message is shown: 

![image](https://cloud.githubusercontent.com/assets/16807822/18530802/08bbe94e-7a88-11e6-8f1d-c82573e304a7.png)

Although checkbox "reset API key" was unchecked.

**Comment by maartenba** [comment]
Good catch. Fixed (did not do a PR for this simple change)
