### ISSUE TITLE
Statistics not working (again, again)

### ISSUE THREAD

**Issue by gimlichael** [NuGet/NuGetGallery#3247]
My pacakge, [Cuemon](https://www.nuget.org/packages/Cuemon), does not receive any increments in the package download of 4.0.2016.2600.

This is a recurring problem, that the statistics does not work, and I have at least 1 confirmed download, as I always test the package and statistics as a part of my publish.

What is wrong this time?

**Comment by xavierdecoster** [comment]
The back-end jobs processing statistics data is currently catching up and recovering from an infrastructure issue earlier this week. 
There's some delay in the data to become available, but it will catch up eventually.

**Comment by xavierdecoster** [comment]
I noticed an update today on the download count for this package, so data is catching up.
Closing the issue as the back-end is catching up.

**Comment by gimlichael** [comment]
What is wrong this time? No statistics for a long time :-(

**Comment by joelverhagen** [comment]
Sure, I'll investigate this.

**Comment by gimlichael** [comment]
Thank you; I hope for a permanent fix this time :-)

**Comment by joelverhagen** [comment]
FYI, there is currently a whole group of individuals observing this issue here:
https://github.com/NuGet/NuGetGallery/issues/3472

**Comment by joelverhagen** [comment]
Statistics pipeline issue is now resolved. Please re-open if you see another problem.
