### ISSUE TITLE
Nuget 2.8.5.207 can't install PowerShell modules

### ISSUE THREAD

**Issue by swernli** [NuGet/NuGetGallery#3249]
I'm working on the Docker PowerShell project (https://github.com/Microsoft/Docker-PowerShell) and we recently starting having issues with our automatic appveyor builds because of the new Nuget 2.8.5.207.  It seems that installing packages via PowerShell's `Install-Module` command fails if the client machine has the latest version, but succeeds with version 2.8.5.205.  This fails for 207 in our local testing as well, and happens regardless of which version produced the package.  This means that any new clients will be unable to use our module at all.  I tried dotnet packages, and those seem to work fine, so it has something to do with the way the PowerShell module packages get unpacked.

This is a major blocking issue for any PowerShell users who want to distribute modules via nupkgs.

**Comment by swernli** [comment]
@jterry75 @jstarks for FYI

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#3495
