### ISSUE TITLE
Int 1 Gallery has a UI glitch

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3250]
not sure what caused this but the "`latest nuget.exe - all downloads - documentation`" buttons are all missing as well, probably hidden behind the misplaced image

![gallery ui goofed up](https://cloud.githubusercontent.com/assets/18014088/18804072/2b2cd748-81ab-11e6-801d-465a7a139ff8.png)

**Comment by skofman1** [comment]
@xavierdecoster, can this be related to build? I looked at the release noted on http://nuget-int-1-v2gallery.cloudapp.net/ home page, and they seem ancient.

**Comment by maartenba** [comment]
Release notes are in storage AFAIK, may indeed have to be updated there.

**Comment by xavierdecoster** [comment]
What @maartenba says: the content of that page is fetched from blob storage.

**Comment by skofman1** [comment]
Fixed.
