### ISSUE TITLE
"File a doc bug" link broken.

### ISSUE THREAD

**Issue by davidmatson** [NuGet/NuGetGallery#3254]
The 404 page, for example:
http://docs.nuget.org/ndocs/consume-packages/support-for-native-projects

Points to the following link to file doc issues:
Maybe it was a bug
•File a bug so we can fix it. https://github.com/NuGet/NuGetDocs/issues

But it looks like issues have since been disabled in the NuGetDocs repository. The link redirects to pull requests, which isn't the right way to file doc bugs. Should this link instead point to the Issues page for the NuGetGallery repo?

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #3545](https://github.com/NuGet/Home/issues/3545) via [**ZenHub**](https://www.zenhub.com/)
