### ISSUE TITLE
Broken link from Creating Native Packages to Consuming Native Packages

### ISSUE THREAD

**Issue by davidmatson** [NuGet/NuGetGallery#3255]
This page:
http://docs.nuget.org/ndocs/create-packages/native-packages

Has the following content, with a broken link:
A native package contains native C++ code instead of managed code, allowing it to be used within C++ projects. (See Support for Native Projects in the Consume section.)
Links to:
http://docs.nuget.org/ndocs/consume-packages/support-for-native-projects

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #3548](https://github.com/NuGet/Home/issues/3548) via [**ZenHub**](https://www.zenhub.com/)
