### ISSUE TITLE
NuGet Gallery search results differ from VS Client

### ISSUE THREAD

**Issue by jonwchu** [NuGet/NuGetGallery#3262]
For certain search terms, the results returned when searching on the Gallery differs from the VS Client. 
For example, searching for "socketio" returns a different amount of results (3 on the Gallery, 2 on the Client). Other terms like "vkontakte," return different results ordering. 

Should there be consistency between these two platforms when a search term is used?

**Comment by skofman1** [comment]
Hi @jonwchu , 
Reproed the behavior you are seing:
Regarding "socketio" - you will see all 3 result if you check the "include prerelease" button in Package Manager: 
![image](https://cloud.githubusercontent.com/assets/16807822/19058040/31b0387c-8989-11e6-959f-6cf9c61e1088.png)

Same for the "vkontakte" search term.
