### ISSUE TITLE
.NET Standard and minClientVersion

### ISSUE THREAD

**Issue by yfakariya** [NuGet/NuGetGallery#3264]
Hi,
I found that if we created NuGet package containing .NET Standard package and we forgot specifying `minClientVersion="2.12"` in `<metadata>` element of `.nuspec` file, old (2.x) client showed confusing error message like "'PACKAGE NAME' already has a dependency defined for 'System.Collections'." I investigated corefx nupkgs and found that specifying `minClientVersion` could resolve this issue.

But I cannot find this specification in docs.nuget.org. I think this should be documented in the documents.

**Comment by skofman1** [comment]
@harikmenon?

**Comment by karann-msft** [comment]
we do talk about `minClientVersion ` in the [.nuspec Reference](https://docs.nuget.org/ndocs/schema/nuspec)

**Comment by yfakariya** [comment]
Sorry disturbing, I missed it.
