### ISSUE TITLE
NullReferenceException is thrown when calling 	/api/v2/curated-feeds/microsoftdotnet/Packages(Id=' ',Version='4.3.4')

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3267]
More details in Elmah: https://www.nuget.org/Admin/Errors.axd/detail?id=2327133

**Comment by shishirx34** [comment]
Findings: 
- This thrown from ODataV2CuratedFeedController/GetCore method. 
- Testing locally returns 404, because there aren't any curated feeds locally available.

Need to add a curated feed for microsoftdotnet locally to get this setup and investigate.
