### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception

### ISSUE THREAD

**Issue by JoyceShee** [NuGet/NuGetGallery#3269]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, you are posting in the correct issue tracker.
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), file a bug on [NuGet Home](https://github.com/nuget/home/issues).

## Frequently Asked Questions

* **I want to delete my package** - please contact support instead via the [NuGet.org website](https://www.nuget.org)
* **I am having connectivity issues** - include an MTR and/or Fiddler trace - steps to capture this are [in our FAQ])(http://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org)

## All set!

Remove this template content and create your issue.

**Comment by JoyceShee** [comment]
Kindly assist

**Comment by skofman1** [comment]
Can you please provide more details? What code are you running? Which version? Stack trace?
