### ISSUE TITLE
'Access to the path '~/App_Data/Files' is denied.' when uploading package - translates to c:\windows\system32\inetsrv\~\App_Data\Files

### ISSUE THREAD

**Issue by tehsuk** [NuGet/NuGetGallery#3271]
OS: Server 2012 R2
NuGet Gallery Version: as of https://github.com/NuGet/NuGetGallery/commit/bce4a86
Steps to reproduce:
- Build
- Deploy NugetGallery website to different server
- Configure as documented
- Create user
- make user login an admin
- login
- upload package

Error:
Access to the path '~/App_Data/Files' is denied.

The app pool for NuGet_Gallery is set to ApplicationPoolIdentity & I gave it full control permsisions over the site directory, verified /App_Data/Files effective permissions were full control.

I ran procmon and found that the site is trying to write to c:\windows\system32\inetsrv~\App_Data\Files, not finding the directory, and trying to create it.

I tried toggling the "Load User Profile" advanced app pool setting, Gallery still tries to write to that location.

I tried running the app pool as a windows user (non-admin), it still tries to write to that directory & not c:\users\$username.

**Comment by tehsuk** [comment]
Based on info in https://github.com/NuGet/NuGetGallery/issues/3192 it looks like you need to define the path to the files directory in Gallery.FileStorageDirectory in web.config.

ex:

    <add key="Gallery.FileStorageDirectory" value="D:\Nuget_Gallery\App_Data\Files" />

There looks to be code that tries to set this value properly (FileSystemFileStorageService.cs, ResolvePath, line 181) but for some reason it trips up in my server config (and the one I linked above).

**Comment by robertmuehsig** [comment]
I think this problem is resolved with this PR https://github.com/NuGet/NuGetGallery/pull/3332 (I had the same issue. Root of the problem was, that the relative path was not resolved.
