### ISSUE TITLE
NuGet.Server 404 error when navigating to Packages folder

### ISSUE THREAD

**Issue by JJoe2** [NuGet/NuGetGallery#3276]
Repro:
- Create an empty web application with the name "NuGet.Server", a natural name to choose
- Install the NuGet.Server package
- Build, package and deploy the website
- Navigate to the website, and click on the "here" link to navigate to the Packages folder

Actual result:
- 404 error

Expected result:
- This happens because the dll generated by the web application project has the same name as NuGet.Server.dll, an easy mistake to make.
- There should be some means to prevent this happening, e.g. the nuget package might refuse to install in a project whose name is NuGet.Server.csproj

**Comment by skofman1** [comment]
Thanks for sharing your feedback. Given there’s an easy work-around, this is not a priority requiring our immediate attention. If this is a common feedback we can reconsider, but you’re the first to report since the NuGet.Server package exists :)

**Comment by ajtowf** [comment]
omg just spent an hour on this, now I'm the second, "nuget.server" is definitely a natural name to choose!
