### ISSUE TITLE
InvalidOperationException: The object cannot be deleted because it was not found in the ObjectStateManager.

### ISSUE THREAD

**Issue by jjlucas76** [NuGet/NuGetGallery#3279]
galops.exe hqe -StorageAccount -ConnectionString does not handle the queued package edits task.
The InvalidOperationException message is written into the database LastError column of dbo.PackageEdits.
The issue seems related to this line of code:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Operations/Tasks/HandleQueuedPackageEditsTask.cs#L138
I have tested this from a remote machine into Azure and from a machine in Azure.
info output looks like this:
![image](https://cloud.githubusercontent.com/assets/11175133/19381141/3266975e-91f2-11e6-942b-6528c082c7be.png)

**Comment by skofman1** [comment]
@xavierdecoster is this code still maintained? 
NuGet.org uses this job to handle package edits: https://github.com/NuGet/NuGet.Jobs/tree/master/src/HandlePackageEdits

**Comment by xavierdecoster** [comment]
@skofman1 never used galops.exe :) The job you mention should handle this kind of stuff. Think a cleanup of NuGetGallery.Operations is due..

**Comment by skofman1** [comment]
Closing this issue since galops is no longer supported.
