### ISSUE TITLE
When adding an owner, allow entering a message

### ISSUE THREAD

**Issue by Haacked** [NuGet/NuGetGallery#328]
I have a lot of package owner requests with no context. Would be nice to allow an optional message when adding owners. :)

**Comment by robertmuehsig** [comment]
The "fixing" PR is now live at nuget.org (via this deployment https://github.com/NuGet/NuGetGallery/issues/3323) - I guess this one can be closed now. @shishirx34

**Comment by shishirx34** [comment]
@robertmuehsig thanks.
