### ISSUE TITLE
Provide better error message when accepting ownership but access denied

### ISSUE THREAD

**Issue by Haacked** [NuGet/NuGetGallery#329]
When another user attempts to add you as a package owner, you receive an email with a confirmation URL. But suppose you login with the wrong account (maybe you have more than one), the site returns a 403 error. This is the correct HTTP response, but the error message is unhelpful.

We should detect this specific condition and provide a more helpful page. I was thinking something like:

_You are attempting to claim ownership of package as user 'NotOwner', but the package ownership request was sent to user   'Username'._

It might seem odd to disclose the username, but consider that the only person who legitimately could have clicked on the link in the first place is both users. Make sense?

**Comment by skofman1** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/16807822/44486918-c253fa00-a609-11e8-99a8-a575b8796639.png)
