### ISSUE TITLE
Can latest Nuget.Server Nuget.Server 2.11.2.0 work with Visual Studio 2015 Update 3?

### ISSUE THREAD

**Issue by wpostma** [NuGet/NuGetGallery#3290]
It is known per issue 2844 that API V3 mode of nuget.server is not yet working.  But, I just want to serve packages from my dev server, to be used inside our office, and I want both command line nuget and dotnet restore operations, and visual studio 2015 ide nuget package search/browsing to work.

1. I followed the steps here, using Nuget.Server 2.11.2.0, inside empty .net 4.6 hosted inside iis
    https://docs.nuget.org/ndocs/hosting-packages/nuget.server
    http://www.hanselman.com/blog/HowToHostYourOwnNuGetServerAndPackageFeed.aspx

2. My code is here even including my web.config secret which has been changed locally, but it's exactly as built and deployed:  https://github.com/wpostma/temporaryrepo1

3. When I browse my server I see the RSS XML output at this url:
    http://dev-html5/NugetServer/nuget/Packages

output (reduced)

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<feed xml:base="http://dev-html5/NugetServer/nuget/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">Packages</title>
  <id>http://dev-html5/NugetServer/nuget/Packages</id>
  <updated>2016-10-18T17:35:09Z</updated>
  <link rel="self" title="Packages" href="Packages" />
     ... entry items are there, but snipped for brevity ...
</feed>

```

4. But when I add the package to visual studio 2015 in tools options package sources either as any of the below, I end up with errors when I try to use the visual studio Manage Nuget Packages feature to browse my custom nuget feed, which is configured inside Tools Options to one of these two options:

```
http://dev-html5.ramsoft.biz/NugetServer/nuget/Packages/
OR
http://dev-html5.ramsoft.biz/NugetServer/nuget/Packages/api/v2/
```

Errors visible in visual studio "Output from Package Manager" window:
```
[RamSoft Package Source] The V2 feed at 'http://dev-html5.ramsoft.biz/NugetServer/nuget/Packages/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=true&$skip=0&$top=26' returned an unexpected status code '400 Bad Request'.
[RamSoft Package Source] The V2 feed at 'http://dev-html5.ramsoft.biz/NugetServer/nuget/Packages/api/v2/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=true&$skip=0&$top=26' returned an unexpected status code '400 Bad Request'.
```

It seems to me similar to this bug !2443 which is marked fixed.

**Comment by maartenba** [comment]
Try `http://dev-html5.ramsoft.biz/NugetServer/nuget/` as the package source instead. The `/Packages` suffix is what Visual Studio will add internally.

**Comment by wpostma** [comment]
Oh dear. That was it! Thanks.
