### ISSUE TITLE
Footer overlapping content on package statistics page

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/NuGetGallery#3297]
When viewing the package statistics page grouped by version, the footer can overlap the content. This appears to happen when the version list is shorter than the checkbox column. 

I can currently see this in latest Chrome and Edge, at the following link: https://www.nuget.org/stats/packages/NUnit.xamarin?groupby=Version

![image](https://cloud.githubusercontent.com/assets/4837132/19539688/a5cda7c8-9652-11e6-88da-e52382831dfb.png)

**Comment by skofman1** [comment]
@xavierdecoster ?

**Comment by ChrisMaddock** [comment]
Thanks @xavierdecoster!
