### ISSUE TITLE
Package stats page lists the download as "unknown" for the "operation"

### ISSUE THREAD

**Issue by Eilon** [NuGet/NuGetGallery#3298]
E.g. on this page: http://www.nuget.org/stats/packages/Microsoft.AspNetCore.Mvc?groupby=Version&groupby=Operation

Almost every operation is listed as "unknown" - more than 99% of them. This could presumably be a problem with the clients sending the wrong operation data to the server, but I can't be certain. Even if it is a client problem, it'd be good to follow up with the owners of the "bad" clients and have them send better data.

Or... if the "operation" metadata just isn't important anymore, it might be good to remove that feature from the gallery because it isn't meaningful.

**Comment by shishirx34** [comment]
@harikmenon - thoughts?

**Comment by harikmenon** [comment]
Not the part of telemetry pipeline I have worked on. @xavierdecoster might know the answer since this probably comes from either the stats database or CDN logs.

**Comment by xavierdecoster** [comment]
This is indeed based on the CDN data, but the clients are sending the user agent strings.

@harikmenon I can look into it, but you should answer @Eilon 's question regarding importance of the "operation" metadata :)

**Comment by Eilon** [comment]
BTW I noticed this because we were trying to see how many were "installs" vs. "restores" though I suppose in the project.json world that isn't a super meaningful distinction - it's pretty much always a "restore" unless perhaps you're using VS's NuGet Package Manager window or console.

**Comment by harikmenon** [comment]
@xavierdecoster Yes operation metadata is important :)

**Comment by xavierdecoster** [comment]
Btw, looking at the cross-reference between client and operation metadata, there's a few suspects in there :) https://www.nuget.org/stats/packages/Microsoft.AspNetCore.Mvc?groupby=ClientName&groupby=Operation

I'll take a closer look at the raw data that reaches the CDN.

**Comment by xavierdecoster** [comment]
Looked at the data, and the following User-Agents are having *lots* of requests without the `NuGet-Operation` HTTP Header. 
The CDN is configured to look for this custom HTTP-header, and when available, [the data is parsed by the stats jobs](https://github.com/NuGet/NuGet.Jobs/blob/81fa007ca528a64d1a684878e9915f760a26c3c5/tests/Tests.Stats.ImportAzureCdnStatistics/CdnLogCustomFieldParserFacts.cs#L12) collecting the info from the CDN W3C logs.

Sample HTTP header:
```
NuGet-Operation: Install-Package
```

Here's the top 5 of clients and their 'unknown' operations in the last 6 weeks:

Client | Version | Requests with 'unknown' operation (last 6 weeks)
------ | --------- | ---------------------------------------
NuGet Cross-Platform Command Line | 3.5.0 | 141,374,548
NuGet Command Line | 3.3.0 | 55,494,422
NuGet Client V3 | 3.4.4 | 30,222,316
NuGet Command Line | 3.5.0 | 20,759,164
NuGet Client V3 | 3.5.0 | 9,769,401

Zooming in on this particular package registration (`Microsoft.AspNetCore.Mvc`), that gives the following top 5 in the last 6 weeks:

Client | Version | Requests with 'unknown' operation (last 6 weeks)
------ | --------- | ---------------------------------------
NuGet Cross-Platform Command Line | 3.5.0 | 186,593
NuGet Client V3 | 3.5.0 | 9,069
NuGet Cross-Platform Command Line | 3.6.0 | 6,174
NuGet Command Line | 3.5.0 | 6,019
DNX Utility | 1.0.0 | 3,854

@harikmenon @rrelyea I think there's some work to be done on the client-side to ensure this header is sent :)

Did a quick check: 
* [No occurences of `NuGet-Operation` in the NuGet.Client repo](https://github.com/NuGet/NuGet2/search?utf8=%E2%9C%93&q=NuGet-Operation)
* [No (more) occurences of NuGet.Core's `OperationHeaderName` constant](https://github.com/NuGet/NuGet.Client/search?utf8=%E2%9C%93&q=OperationHeaderName)

**Comment by xavierdecoster** [comment]
Closing the server issue as the data is not reaching the server.
Logged a client issue. Feel free to subscribe to https://github.com/NuGet/Home/issues/3708 to follow or start a client-side discussion.
