### ISSUE TITLE
Server exceptions

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#3307]
Between approximately 16:15 UTC and 17:16 UTC today, I was playing around with various feed queries.  The following query both succeeded and failed:

[https://www.nuget.org/api/v2/package-ids?partialId=xunit.runner.](https://www.nuget.org/api/v2/package-ids?partialId=xunit.runner.)

...but when it failed, it failed with the following error:

Server Error in '/' Application.

Runtime Error

Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.

**Comment by shishirx34** [comment]
Weirdly, I do not see successful or unsuccessful requests in Application insights to investigate this issue. I couldn't co relate any exceptions seen by elmah either during the given time frame. I will try to find if we can get some FREB logs, that I can investigate.
