### ISSUE TITLE
Remove galops.exe code

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3309]
The old jobs code in gallery is no longer used and can be removed.

@xavierdecoster , @yishaigalatzer , any objections?

**Comment by xavierdecoster** [comment]
@skofman1 by all means, would be good riddance :)

**Comment by joelverhagen** [comment]
This is helpful in my signing work. Less stuff to be concerned with signing on.

**Comment by joelverhagen** [comment]
Completed with https://github.com/NuGet/NuGetGallery/pull/3602.
