### ISSUE TITLE
Automate Process for generating new Lucene index

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3312]
Regeneration of the Lucene index regeneration consists of a few steps.
1. Generate the actual index.
2. Upload the index to a network location.
3. Validate the index is good/not corrupt.
4. Update applications to use new index.
5. Validate applications are in a good state and using new index.

Steps 1 and 2 should be relatively trivial.
Step 3-5 will likely require discussion.

This process should be flexible enough to allow us to either schedule it or allow manual kickoff, and robust enough to automatically fall back if any of the validation fails.

**Comment by skofman1** [comment]
@ryuyu , please add a OneNote page with detailed instructions about the process. Will be performed weekly. After that move to backlog.

**Comment by skofman1** [comment]
Status: Generation of new index and upload to blob storage are scripted. The script is on the VM, with some hard coded values. Script should submitted once hard coded are turned into params.
