### ISSUE TITLE
Package registrations missing from V3

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#3321]
This is reported at https://github.com/NuGet/Home/issues/1542 

@sanjeev8800 says:

```
Severity Code Description Project File Line Suppression State
Error Package 'StockSharp,4.3.17' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. 
Please verify all your online package sources are available (OR) package id, version are specified correctly. 0

Please anybody idea why this error occured.
```

It looks like we are missing the package registration for package "StockSharp.4.3.17".

Initial diagnosis seems that the package might have been missed from feed2Catalog for v3 api.

NOTE: I am able to view this package in VS 2015, however with the v3 feed, I see the error mentioned above. V2 feed however works fine.

**Comment by shishirx34** [comment]
@sanjeev8800 - To unblock you for the moment, you can use the v2 feed to install the package. Follow the following steps to add v2 feed to your VS environment.

1. Go to Tools -> Nuget package manager -> Manage Nuget packages for solution
1. On the top right corner you should see a settings icon, click it. 
1. Add a new package source here With Name:  "V2-Nuget.org" and Source:"https://nuget.org/api/v2". Click Update and Ok.
1. From Package source drop down select this new feed. 
1. Search and install "StockSharp" 4.3.17 version. This should allow you to install the package.

Let me know if that works for you?

**Comment by xavierdecoster** [comment]
I reflowed the package through our system and the package registration got created. I also tested installing the package from nuget.org V3 and it succeeded.

@sanjeev8800 Can you please retry installing the package using https://api.nuget.org/v3/index.json as the package source and confirm?

Leaving the issue open for @shishirx34 to investigate how this happened.

**Comment by skofman1** [comment]
Might be related to this issue: https://github.com/NuGet/NuGetGallery/issues/3365
Closing, since there is no repro we can investigate now.
