### ISSUE TITLE
Unable to deploy to Azure App Service using local git or web deploy

### ISSUE THREAD

**Issue by jahead** [NuGet/NuGetGallery#3326]
Deploying from a local git. 

I get " warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.Diagnostics".

Deploying via visual studio 2015 web deploy, I just get a runtime error.  

I've followed all the documentation at https://github.com/NuGet/NuGetGallery/tree/master/docs/Deploying/Websites
but that hasn't been updated in 2 years. Is Azure App Service not supported? 

Any help would be appreciated.

**Comment by skofman1** [comment]
Can you provide further information about the runtime error you saw? I tried to repro your experience, and was able to successfully deploy a web app using visual studio 2015 web deploy.

**Comment by jahead** [comment]
I'll try to get it up and running again tomorrow. 
But we are trying to get it working with Azure Storages and have already partitioned the sql server. 

The interesting thing is web deploy doesn't have the same issues with local git deploy situation. 

Anyway I'll get back to you asap.

**Comment by jahead** [comment]
Hey @skofman1 

So I did a complete tear down and re deploy of the galley, and it's as you said. Though as soon as I add the Gallery.StorageType AzureStorage and the resulting connection string to the app settings, I get a 500 runtime error. 

Then I went and recreated the storage account and then redeployed the Galley hard coding the storage account strings the web.config not the app.settings. and it worked. 

So I guess you can close this? I think it was a bad deploy from the local git deploy.

You guys looking for someone to update that doc?

Thanks,
Josh

**Comment by skofman1** [comment]
@jahead , would you like to help us update the instructions doc?

**Comment by jahead** [comment]
Yea, I'll update that. Should I make another issue? 
Sorry @skofman1, I think we are on different time zones, so my reply are always so delayed.

**Comment by skofman1** [comment]
No worries :)
I don't think you need to create a new issue. As far as I understand, sending a pull request for this file should do it: https://github.com/NuGet/NuGetGallery/blob/master/docs/Deploying/Websites/README.md
