### ISSUE TITLE
NuGet Gallery Publish-Module Fails with 404

### ISSUE THREAD

**Issue by cpolydorou** [NuGet/NuGetGallery#3328]
Hello,

I have cloned the NuGet Gallery repository and published it to an azure website and SQL server. Everything seems to be working fine, I have tested the admin menu and the user registration without any problems.

I have registered the repository in powershell using the URL https://mysite.com/api/v2 as source location and the https://mysite.com/api/v2/package as publish location.

When I try to publish a powershell module I get an error that says "Publish-PSArtifactUtility : Failed to publish module 'Module': 'Failed to process request. 'Not Found'. The remote server returned an error: (404) Not Found.."

The module gets uploaded to the repository and after a while it is available for download via the Find-Module cmdlet but the install-module fails with error "End of Central Directory record could not be found".

Any ideas?

Regards,

Christos

**Comment by skofman1** [comment]
@yishaigalatzer , who can help with this?

**Comment by yishaigalatzer** [comment]
Hey @cpolydorou 

Looks like you are trying to use the standard gallery as a powershell gallery? Did I get it right?

**Comment by yishaigalatzer** [comment]
I looped in a few folks from the PS Gallery team, and someone should jump on this thread soon with suggestions on private hosting for a PS Gallery.

**Comment by cpolydorou** [comment]
Hi yishaigalatzer, 

This is exactly what I'm trying to accomplish.

**Comment by yishaigalatzer** [comment]
The short (and not very helpful) answer is that this is not the right codebase to use for the powershell gallery.

The longer answer should come from the ps gallery folks. Hopefully soon, I'll ping them again now.

**Comment by bmanikm** [comment]
@cpolydorou Latest version of NuGet provider should resolve the "End of Central Directory record could not be found" error.

More details [here](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/) to install the latest versions of PowerShellGet and NuGet provider.

If you can still repro the Publish-Module error with latest version of PowerShellGet, try to push a nupkg to your gallery using http://nuget.org/NuGet.exe.
