### ISSUE TITLE
Changing database to MySQL gives migration erros

### ISSUE THREAD

**Issue by waqaskhan540** [NuGet/NuGetGallery#3329]
I have changed the backend database as MySQL but I am having errors in migrations, especially in those migrations where indexes are being created. Kindly post a detailed tutorial for migrating database to MySQL.

**Comment by skofman1** [comment]
NuGet Gallery project is the code used to host https://www.nuget.org. We use SQL server in our deployment, and have never worked on deploying it using MySQL.
If you plan to deploy the Gallery with MySQL we would appreciate an entry in our wiki for future users going through the same endeavor. Alternatively, we can recommend trying SQL express: https://www.microsoft.com/en-us/sql-server/sql-server-editions-express which is free.

**Comment by waqaskhan540** [comment]
Thanks for your response. I have managed to resolve most of the migration issues. Once I am done with that I would like to share it. Can you guide me how can I share that to nuget repository.

**Comment by WesleyKhoiVo** [comment]
Hi, Can we use MySQL now?

**Comment by WesleyKhoiVo** [comment]
Hi @waqaskhan540 can you share with details, using Nuget gallery with MySQL

**Comment by WesleyKhoiVo** [comment]
Hi @waqaskhan540 can you share with me the details using Nuget gallery with MySQL please?

**Comment by loic-sharma** [comment]
@WesleyKhoiVo NuGetGallery is used to run nuget.org. We have no plans at this time to support MySQL. I would consider alternative NuGet server implementations instead: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

For example, BaGet supports MySQL: https://loic-sharma.github.io/BaGet/configuration/#database-configuration

**Comment by WesleyKhoiVo** [comment]
Thanks Loic
