### ISSUE TITLE
Uploading newer unlisted package says : You successfully uploaded x. This is not the latest version of x available. 

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#333]
I uploaded TestDependsOnUnlisted 1.0.0.0 as listed and right away uploaded TestDependsOnUnlisted 2.0.0.0 as unlisted.

At the top (in blue) I get :

"You successfully uploaded TestDependsOnUnlisted 2.0.0.0. This is not the latest version of TestDependsOnUnlisted  available."

which is confusing.

It IS the latest version but maybe it's not available as in unlisted ? 
If that's the case right below it says : 

"This package is unlisted and hidden from package listings. You can see the package because you are one of its owners. To list the package again, change its listing setting. "

I'd remove "This is not the latest version of x" in this case.

**Comment by xavierdecoster** [comment]
Text currently reads: "You successfully uploaded {id} {version}"

About time we closed this issue :)
