### ISSUE TITLE
hosted nuget.server tips 502 (not found),what's that mean?

### ISSUE THREAD

**Issue by ColinZeb** [NuGet/NuGetGallery#3331]
#Custom Nuget.Server by hostself.
hostname:https://nuget.jingshonline.com/nuget
I'm using chinese language with vs 2015 up3.
error:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		响应状态代码不指示成功: 502 (Not Found)。			0	

![nuget](https://cloud.githubusercontent.com/assets/6287608/19990870/0bd01f7c-a26c-11e6-9a11-851db3000a6f.png)
NOTE: on other solution it's works fine

**Comment by skofman1** [comment]
Moved to client repository: https://github.com/NuGet/Home/issues/3879
