### ISSUE TITLE
Back Button on "Package"-Operations

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#3333]
I noticed that there a couple of "Package" related sites from where you currently can't easily jump back to the actual package page:

![image](https://cloud.githubusercontent.com/assets/756703/20023872/19c9da56-a2e3-11e6-95e9-73ffd34902f9.png)

My idea would be to provide a common "back" link to the NuGet details package page, e.g. something like that:

![image](https://cloud.githubusercontent.com/assets/756703/20023905/4259db88-a2e3-11e6-90f5-deed854488ab.png)

Nothing fancy, but should simplify the navigation. What do you think?

**Comment by shishirx34** [comment]
@harikmenon - thoughts?

**Comment by skofman1** [comment]
@jonwchu can you please take a look?

**Comment by jonwchu** [comment]
@robertmuehsig thanks for sending this feedback our way! I was wondering, is there any functionality for this that might differ from using the browser's back button? At least the pages that I could see, you can navigate using the back button, but just wanted to make sure it's the same with your scenario. Thanks!

**Comment by robertmuehsig** [comment]
The problem occures if you have a link to such a deep site. 

Sometimes I want to go from the VS NuGet Client to NuGet.org to get a better overview, but currently it only shows me this link:

![image](https://cloud.githubusercontent.com/assets/756703/20422291/c63b4046-ad69-11e6-950d-31f8f52c9ebf.png)

When I jump now to this link I have no way to get back to the actual "Package" site.

**Comment by jonwchu** [comment]
Ok, that makes sense that you'd need the link to the package page. Though it sounds like that this is more of an issue of needing a direct link in the Client to the package entry on the website than needing a back button on the website for these pages. 

I've moved this issue to the client repo: [NuGet/Home#3999](https://github.com/NuGet/Home/issues/3999)
