### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by mindfuucker** [NuGet/NuGetGallery#3337]
Hi,

On [this page](https://www.nuget.org/packages/System.Net.Primitives/4.3.0-preview1-24530-04), the notes for the release notes give a 404 on github.

**Comment by shishirx34** [comment]
This is not something that the Nuget team controls. Please contact the owner of the package to update the link to their release notes.

**Comment by shishirx34** [comment]
I just realized this is a Microsoft package. Let me follow up and see who owns it.

**Comment by shishirx34** [comment]
Following up with the .Net team to address this issue.

**Comment by shishirx34** [comment]
Please note dotnet team has an issue opened to address it. https://github.com/dotnet/corefx/issues/13493

Since there is nothing more actionable for us here. I will close this issue.

**Comment by karann-msft** [comment]
@mindfuucker the link to the release notes has been fixed.
