### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sellotape** [NuGet/NuGetGallery#3338]
On https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior, there is a link to "NuGet Configuration Settings" which points to https://docs.nuget.org/ndocs/consume-packages/ndocs/schema/nuget.config-file.md, which gives 404.

It should probably point to https://docs.nuget.org/ndocs/schema/nuget.config-file

**Comment by skofman1** [comment]
@harikmenon

**Comment by harikmenon** [comment]
@karann-msft can you take care of this is the current and new site?

**Comment by karann-msft** [comment]
@sellotape thanks for reporting. We have fixed the link.
