### ISSUE TITLE
Search results ranking for MSTest framework

### ISSUE THREAD

**Issue by AbhitejJohn** [NuGet/NuGetGallery#3339]
Searching for "MSTest" on nuget.org site brings up a bunch of search results none of them including "MSTest.TestFramework" in page-1. This package however shows up in page-2 although this has higher downloads and is tagged appropriately and is updated much more frequently.

Comparing this to (say) MSTest.**Unit**TestFramework which has 10,000 lower downloads and was updated a year ago but shows up much higher compared to the package in question.

What could be the issue here? Is this just a glitch in the ranking or is something wrong with the package?

**Comment by shishirx34** [comment]
@xavierdecoster - could you elaborate on the search ranking here.

Note: I see the MSTest.TestFramework on page-1 as the third result at the moment. https://www.nuget.org/packages?q=MSTest

**Comment by xavierdecoster** [comment]
@yishaigalatzer can you chime in with some pointers as to what could be causing this?

**Comment by AbhitejJohn** [comment]
@shishirx34 : Yes. I see it moved up to the first page now although am not sure if 3 is its current position. It would be really interesting to understand how packages are ranked though.

**Comment by yishaigalatzer** [comment]
A small difference in download count should have very small effect on location. The impact of download count is logarithmic in nature.

Update date is not yet taken into account.
