### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by badersur** [NuGet/NuGetGallery#3345]
Hello NuGet. I'm facing some security issues with your site.

1. I get "**Your connection is not private. This server could not prove that it is api.int.nugettest.org; its security certificate is from *.blob.core.windows.net. This may be caused by a misconfiguration or an attacker intercepting your connection.**" when I visit https://api.int.nugettest.org/v3-index/index.json on Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.10 (64-bit). And when I execute `curl -v https://api.int.nugettest.org/v3-index/index.json`, I get:

```
curl -v https://api.int.nugettest.org/v3-index/index.json
*   Trying 168.61.132.14...
* Connected to api.int.nugettest.org (168.61.132.14) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_CBC_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* SSL: certificate subject name (*.blob.core.windows.net) does not match target host name 'api.int.nugettest.org'
* Closing connection 0
curl: (51) SSL: certificate subject name (*.blob.core.windows.net) does not match target host name 'api.int.nugettest.org'
```

I'm using curl 7.50.1.

2. I can't visit https://api.nuget.org/v3/index.json over SSL, it works **sometimes**! but then it stops after few minutes.

Most of the time, I get this:

```
curl -v https://api.nuget.org/v3/index.json
*   Trying 68.232.34.200...
* Connected to api.nuget.org (68.232.34.200) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

and this recently:

```
curl -v https://api.nuget.org/v3/index.json
*   Trying 68.232.34.200...
* Connected to api.nuget.org (68.232.34.200) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* Operation timed out after 300100 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 300100 milliseconds with 0 out of 0 bytes received
```

When it works I get:

```
curl -v https://api.nuget.org/v3/index.json
*   Trying 68.232.34.200...
* Connected to api.nuget.org (68.232.34.200) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.vo.msecnd.net (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=*.vo.msecnd.net
* 	 start date: Fri, 21 Oct 2016 20:35:09 GMT
* 	 expire date: Sat, 21 Apr 2018 20:35:09 GMT
* 	 issuer: C=US,ST=Washington,L=Redmond,O=Microsoft Corporation,OU=Microsoft IT,CN=Microsoft IT SSL SHA2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /v3/index.json HTTP/1.1
> Host: api.nuget.org
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding
< Cache-Control: max-age=120, must-revalidate
< Content-MD5: rLbcy1wS6wjfkkxXz8wXgQ==
< Content-Type: application/ld+json
< Date: Thu, 10 Nov 2016 18:47:56 GMT
< Etag: 0x8D38F7C230CE7BB
< Last-Modified: Wed, 08 Jun 2016 09:06:11 GMT
< Server: ECAcc (omm/44AC)
< Vary: Accept-Encoding
< X-Cache: HIT
< X-CDN-Rewrite: Lowercase blobs in v3-flatcontainer
< x-ms-blob-type: BlockBlob
< x-ms-lease-status: unlocked
< x-ms-request-id: f17c110e-0001-0060-2482-3bcc86000000
< x-ms-version: 2009-09-19
< x-ms-write-protection: false
< Content-Length: 5929
< 
JSON RESPONSE...
* Connection #0 to host api.nuget.org left intact
```

I'm trying to learn ASP.NET Core but NuGet doesn't work for me, and when I do `dotnet restore` I get:

```
dotnet restore -v Debug --disable-parallel --infer-runtimes
trace: NuGet Command Line Version: 3.5.0.0
trace: Running non-parallel restore.
trace: Reading project file /home/badersur/GitHub/Eilon/ProjectKIssueList/src/Hubbup.Web/project.json.
log  : Restoring packages for /home/badersur/GitHub/Eilon/ProjectKIssueList/src/Hubbup.Web/project.json...
trace: Restoring packages for .NETCoreApp,Version=v1.0...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms.
trace: System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://api.nuget.org/v3/index.json.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.TimeoutException: The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms.
```

The full response can be found in [this file](https://github.com/NuGet/NuGetGallery/files/584324/nuget-1-projectk-infer.txt).

To make sure I'm not setting wrong data in project.json or NuGet.org, I've cloned [aspnet/live.asp.net][1] and [Eilon/ProjectKIssueList][2] and executed `dotnet restore -v Debug`, then `dotnet restore -v Debug --disable-parallel`, and `dotnet restore -v Debug --disable-parallel --infer-runtimes` but I got this error :(

I'm using dotnet 1.0.0-preview2-1-003155 downloaded from [dotnet/cli][3] for Ubuntu 16.10, and my NuGet.Config has:

```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

3. I can't download packages manually from your Gallery!

4. I followed your instructions on using Fiddler but I got nothing captured and I couldn't visit secure websites! Then, `dotnet restore` and `curl` complained about certificates :(

Please help and sorry for the long issue.

[1]: https://github.com/aspnet/live.asp.net
[2]: https://github.com/Eilon/ProjectKIssueList
[3]: https://github.com/dotnet/core/blob/master/release-notes/preview-download.md

**Comment by skofman1** [comment]
You can use http to access this:  http://api.int.nugettest.org/v3-index/index.json

**Comment by badersur** [comment]
@skofman1 I don't want to use the APIs over HTTP! I'm looking for any nuget feeds over SSL so sometimes I use this:

```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--<config>
    <add key="globalPackagesFolder" value="/home/badersur/.nuget/packages" />
  </config>

  <packageRestore>
    <add key="enabled" value="true" />
    <add key="automatic" value="true" />
  </packageRestore>-->

  <packageSources>
    <add key="globalPackagesFolder" value="/home/badersur/.nuget/packages" />

    <add key="AspNetCore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="AspNetCore-patch" value="https://dotnet.myget.org/F/aspnetcore-patch/api/v3/index.json" />
    <add key="AspNetCore-master" value="https://dotnet.myget.org/F/aspnetcore-master/api/v3/index.json" />
    <add key="AspNetCore-ci-dev" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />

    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-cli" value="https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json" />

    <add key="xunit" value="https://www.myget.org/F/xunit/api/v3/index.json" />

    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <!--<add key="api.nuget.org" value="https://www.nuget.org/api/v2" protocolVersion="2" />-->
  </packageSources>
</configuration>
```

After reporting the issue I used https://www.nuget.org/api/v2 to restore [aspnet/live.asp.net](https://github.com/aspnet/live.asp.net) packages and it worked but I would like to use v3 over SSL! And it's annoying for the API to work sometimes :(

I don't use nugettest, I was looking for any feeds then faced this issue so I'm just letting you know about  it.

Note: Most websites work over SSL except api.nuget.org and some microsoft related websites! I face similar issue when I try to download VS Code over SSL (it works sometimes), and I had an issue with https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js last week (I forgot the issue but it's working now)

**Comment by xavierdecoster** [comment]
@badersur does this happen as well when on a different network?

**Comment by badersur** [comment]
@xavierdecoster I don't have another network to test but I think yes it happen because I tried to download nuget packages using visual studio from another network and it was failing (well, I'm not sure whether it was a different network or this one).

I have full control over this network and I don't see any signing of misconfiguration. I tried to change the DNS IP on the router but it doesn't seem to help!

I've played a lot with the configurations of our router and my brothers are complaining that some game are not working any more.. But all sites are working with me and the API is sometimes working (So I'm pretty sure my settings are not the issue).

**Comment by xavierdecoster** [comment]
Can you try intercepting the HTTPS traffic with Fiddler and send the traces to us? Instructions can be found here: http://www.fiddlerbook.com/fiddler/help/httpsdecryption.asp

In addition, you could also capture an MTR. Instructions here: https://docs.nuget.org/ndocs/policies/nuget-faq#managing-packages-on-nuget-org

**Comment by badersur** [comment]
@xavierdecoster I'll try Fiddler again but MTR doesn't seem to have a Linux version to use... I don't have Windows nowadays.

**Comment by blowdart** [comment]
Folks is your HTTPS set up with SNI, or IP based? It might be that :)

**Comment by badersur** [comment]
I tried Fiddler and I got:

```
dotnet restore -v Debug
trace: NuGet Command Line Version: 3.5.0.0
trace: Running restore with 8 concurrent jobs.
trace: Reading project file /home/badersur/GitHub/Eilon/ProjectKIssueList/src/Hubbup.Web/project.json.
log  : Restoring packages for /home/badersur/GitHub/Eilon/ProjectKIssueList/src/Hubbup.Web/project.json...
trace: Restoring packages for .NETCoreApp,Version=v1.0...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Peer certificate cannot be authenticated with given CA certificates
trace: System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://api.nuget.org/v3/index.json.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
trace:    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
```

when restoring packages for [Eilon/ProjectKIssueList][1] and the [Fiddler session is here][2] (which I don't think is what you are looking for because dotnet and curl are complaining about certs).

Did someone manage to use Fiddler on Linux with dotnet?! I see instructions for adding Fiddler's cert to browsers but how to do this for command line tools?

[1]: https://github.com/Eilon/ProjectKIssueList
[2]: https://github.com/NuGet/NuGetGallery/files/587145/Fiddler.zip
