### ISSUE TITLE
Installing Microsoft.AspNet.Identity.EntityFramework

### ISSUE THREAD

**Issue by Artorias271** [NuGet/NuGetGallery#3348]
I'm having to manually reinstall several missing NuGet packages. I'm not sure what the -Pre flag does at the end of a command, but I tried the command as described [here](https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/3.0.0-rc1-final) and it threw an error when it got to System.Runtime:

![image](https://cloud.githubusercontent.com/assets/1584561/20246811/64c4096a-a97c-11e6-96a0-6d75648f9f80.png)

I managed to install this package by removing the -Pre flag at the end.  Does anyone know why this may have worked? I like to get as much info as I can when I run across problems, I usually get stuck on annoying bugs that end up having a very simple fix for quite some time, so I try to get as much info as I can to refer to so I can recall why a solution fixes a problem. Thanks!

**Comment by ryuyu** [comment]
Specifying the -Pre flag tells nuget that you are trying to install a prerelease package.
Removing the -Pre will default to the last stable release, which is probably why that is working.

The assembly that the prerelease version is trying to install is a facade assembly, and isn't supposed to be included as an explicit dependency. It looks like this might be an issue with this prerelease version of the package. The latest stable version of this package does not have the same dependencies, and thus installs correctly.

For more information about issues with installing packages that reference facades, you can see https://github.com/NuGet/Home/issues/2193 on the NuGet Client.

Do you need the latest version of the package specifically, or will the stable version be sufficient?

**Comment by Artorias271** [comment]
For now, everything seems to be working just fine. Thanks again for the explanation.

**Comment by ryuyu** [comment]
Thanks for letting us know everything is good. Please let us know if you run into this issue again in the future!
