### ISSUE TITLE
Allow package owner to remove themselves

### ISSUE THREAD

**Issue by adamralph** [NuGet/NuGetGallery#3356]
> This should only be allowed if you're not the last package owner.
> If you're the last package owner, you can simply unlist the package.

*This is a "re-opening" of https://github.com/NuGet/NuGetGallery/issues/179. That issue is marked up for grabs, but is closed. It's unlikely anyone will find a closed issue and grab it, which is why I'm re-opening.*

**Comment by shishirx34** [comment]
Assigning to @scottbommarito to validate this change deployed on int, since he merged the corresponding PR.

**Comment by scottbommarito** [comment]
Verified with @skofman1 yesterday, closed duplicate issue
