### ISSUE TITLE
Restrict adding assemblies in the Windows application while install the custom Xamarin NuGet package

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/NuGetGallery#3366]
I have created the custom Xamarin forms NuGet package with the below format.

![old lib folder of the package](https://cloud.githubusercontent.com/assets/16695209/20512579/3be2ff5c-b0a6-11e6-8eaf-251043b9d1f0.png)

The packages are installed and assemblies are added successfully for this package.

Then I have changed the lib folder format since I don't need the Windows and Windows phone, winRT assemblies in the project. So I have changed the lib folder format like as below,

![new lib folder of the package](https://cloud.githubusercontent.com/assets/16695209/20512534/e47798e0-b0a5-11e6-867d-75b20076b16d.png)

I got the below error while install the package in the project after change lib folder format.

**Could not install package 'Custompackage.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author**

The **Xamarin.Forms.2.3** package has been installed default while create the Xamarin project.

Why we get this error after change the format of the lib folder in the package?
Any standard format we need to maintain for this Xamarin forms packages?

Please help me on this.

Thanks,
Ganesan R.

**Comment by skofman1** [comment]
Moved to client repo: https://github.com/NuGet/Home/issues/3997
