### ISSUE TITLE
Package updated with different versions

### ISSUE THREAD

**Issue by jansater** [NuGet/NuGetGallery#3367]
Noticed a strange thing while updating my projects this morning. I have a package that belongs to several projects in my solution and while I was updating to the latest version (its my own package) I published an even newer version. The result was that the package manager in VS actually installed the older version on half my projects and the newer version on the rest. This could lead to very serious issues and should be fixed in my opinion...

I'm using vs 2015 and Package Manager Console Host Version 3.4.4.1321

**Comment by skofman1** [comment]
Moved to client repo: https://github.com/NuGet/Home/issues/3998
