### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ManyouRisms** [NuGet/NuGetGallery#3376]
https://docs.nuget.org/ndocs/schema/nuget.config-file

The description for the "automatic" parameter in packageRestore section has "should" misspelled as "shoudl".

**Comment by shishirx34** [comment]
@karann-msft

**Comment by karann-msft** [comment]
@ManyouRisms thanks for reporting. This has been fixed. We enable the community to contribute to the docs, simply click on the "Edit in Github" button at the top of page.
