### ISSUE TITLE
FakeXrmEasy.365 downloads count

### ISSUE THREAD

**Issue by jordimontana82** [NuGet/NuGetGallery#3378]
Hi!
I've pushed the FakeXrmEasy.365 a couple of days ago but it seems like the number of downloads is not updating, although I know for sure people is downloading it.

Could you have a look please?

**Comment by xavierdecoster** [comment]
We noticed some request logs got stuck in the stats processing pipeline. This may contain the download records for this package. We are working on reflowing these logs. Note that stats only update once a day on the gallery, so this may take a day (or two, if reflowing happened after today's regeneration of stats blobs). cc @skofman1

**Comment by skofman1** [comment]
Investigated ImportAzureCDNStatistics and opened a few issues:
https://github.com/NuGet/NuGetGallery/issues/3409
https://github.com/NuGet/NuGetGallery/issues/3408

**Comment by jordimontana82** [comment]
Thx a mill for looking into this!

**Comment by jordimontana82** [comment]
Thanks a mill for fixing this! :)
