### ISSUE TITLE
Intermittent "Unable to find version" errors when installing different packages and using a local installation of NuGet.Server (v2.10.3.0)

### ISSUE THREAD

**Issue by mizbrodin** [NuGet/NuGetGallery#3385]
It happens from time to time that we get an error like this:

"Unable to find version '1.2.0.33' of package 'MyPackageX"

when we try to install a package via command line using a feed hosted by our local installation of NuGet.Server (v2.10.3.0).

The issue verifies randomly (and not very frequently) for different packages. In all such cases the package is actually present in the feed and subsequent installation attempts (using exactly the same command and without applying any changes to the server/feed) complete successfully.

Investigating IIS logs and Windows Events didn't help as nothing strange seem to be happening with the system at the time when the problem occurs.

**Comment by joelverhagen** [comment]
Have you ever seen this issue on any other source (e.g. nuget.org or a MyGet source)?

What client are you using and what version? nuget.exe? Visual Studio? .NET CLI?

Can you reproduce it within a short period of time on your own machine? Having some Fiddler traces and verbose nuget.exe logs would be very helpful.

Can you reproduce this by putting nuget.exe restore in a loop and letting it run over and over (clearing caches and packages directory per iteration of course)?

**Comment by mizbrodin** [comment]
Hi Joel,

Thanks for looking into this.

We are using nuget.exe version 2.8.5 which is called from TeamCity. (We are not using a newer version of nuget.exe (3.x) because it's not compatible with the old version of TeamCity which we have.)

So far, the issue was noticed only with nuget.exe running from TeamCity. We can't activate verbose logging on TeamCity because we are using a standard TeamCity Build step (NuGet Installer) which doesn't provide us an option for verbose logging.

I will see if we can try to reproduce the problem by putting nuget.exe restore in a loop. It's not very easy to do during normal working hours because we are using this NuGet Server in production (by numerous developers and build servers), but I should be able to find suitable time to do run this experiment. I'll let you know about the results.

Kind Regards,
Max

**Comment by joelverhagen** [comment]
Thanks, I look forward to the results. 

> We can't activate verbose logging on TeamCity because we are using a standard TeamCity Build step (NuGet Installer) which doesn't provide us an option for verbose logging.

Could you use a custom build step and execute the `nuget.exe restore` yourself? The build logs should be able to demonstrate the exact command used. Then you can add `-Verbosity detailed` argument. It's worth a try we, when you do reproduce it, you have all the information you can get.

**Comment by joelverhagen** [comment]
Closing until we get more information. @mizbrodin, if you run into this error again and have some repro steps I can jump, please feel free to re-open this issue.
