### ISSUE TITLE
'boost_coroutine-vc140' version 1.62.0 is not available in https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by sergey-shandar** [NuGet/NuGetGallery#3391]
[boost_coroutine-vc140 1.62.0](https://www.nuget.org/packages/boost_coroutine-vc140/1.62.0) is not available in https://api.nuget.org/v3/index.json but it's available in https://www.nuget.org/api/v2.

The package has been uploaded on Oct 03 2016.

**Comment by shishirx34** [comment]
@joelverhagen - Need package reflow?

**Comment by joelverhagen** [comment]
Yup, this seems to be a bi-product of https://github.com/NuGet/NuGetGallery/issues/3365. I've reflowed the package. The artifacts looks correct for search, flat container, catalog, and registration blobs.

@sergey-shandar, could you verify that things look okay from your side now?

**Comment by sergey-shandar** [comment]
It works now, thanks.
