### ISSUE TITLE
Update package - version switch available only from 3.5

### ISSUE THREAD

**Issue by pawepaw** [NuGet/NuGetGallery#3393]
Hello,

I just found misleading that you added version parameter to update command but it's available only in 3.5 package which is RC now. In stable 3.4.4 release it's not included. Also if you can probably it'd be better to change it to "specifies target version of the package" because from what is written now you can understand that it'll only update packages that have some specific version now.

> version  When used with one package ID, specifies the version of the package to update.

https://github.com/NuGet/NuGetDocs/blob/master/NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md#update

Probably info (3.5+) would be enough. 

I would create PR but i have no access to PC now.

**Comment by skofman1** [comment]
Moved to Home repository where we track NuGet client related issues:
https://github.com/NuGet/Home/issues/4058
