### ISSUE TITLE
New Account Registration fails to send confirmation email

### ISSUE THREAD

**Issue by akrois** [NuGet/NuGetGallery#3394]
I have tried to create a new account with 2 different email addresses:

akrois@gmail.com
akrois24

akrois@gmail.com
avatar

akrois@ancestry.com
akrois24

In all of these cases, I have not received a confirmation email.  Without it, I can not complete the registration process.  This has been tested on Chrome, Safari and FireFox.

The last time it was tried, I received a nuget error page:

![screen shot 2016-12-02 at 2 31 59 pm](https://cloud.githubusercontent.com/assets/8987983/20851213/438572f0-b89c-11e6-9606-77776b52186c.png)

Please fix this, or provide a work-around so that I can create an account.  Thanks,

Andrew Krois

**Comment by skofman1** [comment]
Hello @akrois!
I couldn't find your user name in our system. Did you try to create a user in NuGet.org?
Please provide more information.

**Comment by akrois** [comment]
Yes, I tried several times using emails:

akrois@ancestry.com<mailto:akrois@ancestry.com> or
akrois@gmail.com<mailto:akrois@gmail.com>

and Usernames:

akrois22
akrois23
akrois24

In all cases I failed to receive a confirmation email so I could not complete the registration.

Andy

**Comment by skofman1** [comment]
@akrois, still can't find any record of a user with name that contains 'akrois'.
Please provide more details.
Did you use this page to register: https://www.nuget.org/users/account/LogOn ?
Did you get a success page after you entered your details?

**Comment by skofman1** [comment]
Also, you can contact us at support@nuget.org

**Comment by akrois** [comment]
The page I’m using to register is the following:

http://webdeploy.myfamilysouth.com/account/Register

After registering I get the following:

[cid:image001.png@01D24EF2.DF260A30]


This time I did receive a confirmation email and was able to confirm the account.

Andy
