### ISSUE TITLE
Block additional crawlers from going over NuGet Gallery DB 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#3407]
NuGet Gallery PROD DB currently experiences a high load in constant intervals due crawlers that replicate the packages table daily, using V2 OData endpoint.

The first stage in the effort to improve DB performance is to block additional crawlers from joining, while allowing the existing ones to continue operating. The suggestion is to allow only a subset of OData query formats.

**Comment by shishirx34** [comment]
Should this be moved to Engineering, @skofman1 ?

**Comment by skofman1** [comment]
Nope.. this is the place
