### ISSUE TITLE
ImportAzureCDNStatistics fails when the same package appears in different casings

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3408]
Package Metrics version 1.0.13 appears in the logs as Metrics and as metrics. Causing the code to fail with this message: 

`Violation of UNIQUE KEY constraint 'UQ__#A652089__A16B9C09D8BA3255'. Cannot insert duplicate key in object 'dbo.@packages'. The duplicate key value is (Metrics, 1.0.13).\r\nThe data for table-valued parameter \"@packages\" doesn't conform to the table type of the parameter. SQL Server error is: 3602, state: 30\r\nThe statement has been terminated.`

Line: https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/Warehouse.cs#L705

@xavierdecoster, will consolidating all package names to be lower case is the correct fix here?

**Comment by xavierdecoster** [comment]
@skofman1 perhaps. All queries on the (in-mem cached) data will also need to be case-insensitive then, as well as any query that works with that data.

**Comment by skofman1** [comment]
Seems like the querying on the in-mem cache is already case-insensitive: https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/Warehouse.cs#L685
