### ISSUE TITLE
[Statistics] Introduce Community Statistics Reports

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3417]
Thanks @emgarten, for bringing this up.

Look here: https://www.nuget.org/stats

![image](https://cloud.githubusercontent.com/assets/94054/21124070/86809376-c091-11e6-9c5c-909d2f234bdb.png)

It's not interesting that `System.*` packages are being downloaded a lot. They show up in templates so it does not help new cool packages catch on to crowd them out with BCL-ish packages.

We should filter out `System.*` packages by Microsoft or perhaps the closure of the `Microsoft.NETCore.App`.

**Comment by xavierdecoster** [comment]
This is a known issue, and a non-trivial fix to get it right, but thanks for bringing it up again!
Anyone can own a `System.*` or `Microsoft.*` package today. The thing is, the stats database only has the W3C logs as input, which does not contain ownership data, and today there is no link to correlate between stats data and gallery data when these stats report blobs are generated. 

We do have the concept of `PackageSets` in the stats db which is a manually maintained list of package sets we treat specially (e.g. we could leverage this to filter certain packages in this report view).

**Comment by skofman1** [comment]
Since a full solution is complex, lets update  `PackageSets` in the stats db with the packages above, like @xavierdecoster suggested.

**Comment by joelverhagen** [comment]
This point has been brought up on Twitter (https://twitter.com/CodeScottLe/status/887796340029247488).

As a first "easy" step, @jonwchu and I think we should try excluding anything owned the [microsoft](https://preview.nuget.org/profiles/microsoft) or [aspnet](https://preview.nuget.org/profiles/aspnet). 

If this remaining set is too small, we should remove the `NETStandard.Library` closure.

**Comment by joelverhagen** [comment]
Additional feedback from the community. @anangaur posted on https://github.com/NuGet/NuGetGallery/issues/4836:

> https://twitter.com/chrismckee/status/918275305835585536
> 
> On https://www.nuget.org/stats/packages, NuGet.org should show only the directly referenced packages that users add to their projects and not System.*, Microsoft.* that automatically get pulled in.

**Comment by anangaur** [comment]
IMO the right fix is to be able to distinguish between "Install" action vs. download which may be update/restore/install. And use the install count as the metric to list top packages. (Or even in search ranking). 

However, any quick fix as suggested above should be good too, in the interim.

**Comment by skofman1** [comment]
We can start with removing system.*  and runtime.native.*, and perhaps a few other prefixes.

**Comment by anangaur** [comment]
I think we do wither of the following:
1. Have a way to know the packages that are dependent package always (like many system.*) and exclude those.
2. Have a filter to exclude all microsoft packages (on by default)

Option 1 is ideal but i would bot like this to be manual effort as its prone to be inaccurate and would need constant revisit of the blacklisted packages. Implementing it the right way is non trivial as we do not collect/process enough data to make this decision.

So for the short term i would vote for just having a check box filter to exclude packages that belong to Microsoft(owner = any Microsoft team). This is on by default and can be unchecked to get the current list. I find this the a good option without ambiguity.

**Comment by loic-sharma** [comment]
The CDN Reports job has been deployed to PROD and has been verified. Gallery changes are still pending PROD deployment.
