### ISSUE TITLE
dist.nuget.org download urls are case sensitive and inconsistent across versions

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3426]
@AGBrown commented on [Fri Dec 16 2016](https://github.com/NuGet/Home/issues/4117)

## Details about Problem

NuGet product used: NuGet.exe

NuGet version: various

## Detailed repro steps so we can see the same problem

When downloading from `https://dist.nuget.org/win-x86-commandline/<version>/NuGet.exe`, the package naming is inconsistent with regard to case, but the web server is case sensitive. It is not possible therefore to write a simple script which can take a version parameter and insert it into the download url. For example, taking the most recent three versions and "latest" from https://dist.nuget.org/index.html

| version | Pascal case | Lowercase |
| --- | --- | --- |
| latest | ✘ [latest NuGet.exe](https://dist.nuget.org/win-x86-commandline/latest/NuGet.exe) | ✓ [latest nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) |
| v3.5.0 | ✓ [v3.5.0 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe) | ✘ [v3.5.0 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe) |
| v3.4.4 | ✓ [v3.4.4 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe) | ✘ [v3.4.4 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe) |
| v3.3.0 | ✘ [v3.3.0 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.3.0/NuGet.exe) | ✓ [v3.3.0 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe) |

## Suggestion for Fix

1. make the web server handler for nuget.exe download links case insensitive
1. if that is not possible then:
     - Future uploads to dist.nuget.org should be automated to ensure consistency
     - Both the lower and pascal case versions of all existing and future nuget.exe versions should be uploaded - standardising to lowercase will simply break things for half the nuget world and vice versa

And on a slightly flippant ending: it's lowercase in the text on the page at https://dist.nuget.org/index.html; the case varies in the download links; the case is pascal case in the page's title; and it is lowercase in the logo for nuget. I don't think there are [enough standards here](http://xkcd.com/927/). Maybe we should adopt nUgET?

---

@emgarten commented on [Fri Dec 16 2016](https://github.com/NuGet/Home/issues/4117#issuecomment-267670378)

@AGBrown Thanks for pointing this out and the table of version casings. We'll investigate to see how this could be improved/fixed on dist.

//cc @skofman1 @joelverhagen 

---

@joelverhagen commented on [Fri Dec 16 2016](https://github.com/NuGet/Home/issues/4117#issuecomment-267679435)

dist.nuget.org is living directly on Azure blob storage which has case-sensitive URLs. Thanks for the report @AGBrown. I'm going to move this to the server-side bug tracker so the server team has better visibility.

**Comment by joelverhagen** [comment]
Things we should investigate:

1. Redirects / rules in CDN configuration to allow "nuget.exe" to point to "NuGet.exe".
1. In not 1, upload both "nuget.exe" and "NuGet.exe" as suggested.
1. Moving dist.nuget.org to be a web app (downside is compute...)

**Comment by skofman1** [comment]
@rrelyea, we should decide on consistent filename for future uploads?

**Comment by emgarten** [comment]
I believe we were trying to be consistent with the original casings used.
1. nuget.org/nuget.exe  (lowercase)
1. NuGet.Commandline package: tools/NuGet.exe 

Dist should always be lowercase. But the package needs to keep the mixed casing for ``NuGet.exe update -self`` with mono.

It looks like for 3.4.4 and 3.5.0 the exe just wasn't renamed to lowercase when it was copied out of the package.

**Comment by joelverhagen** [comment]
CDN rules should fix this. I'm investigating right now. Until the rule exists, we should provide both casing I think. No harm and provides ergonomic URL creation.

**Comment by joelverhagen** [comment]
All of the broken links up there should be working now. I'll work on the CDN rule so we don't have to have copies of the blobs (future-proof) and oTHeR casings work as well.

**Comment by joelverhagen** [comment]
Fixed in prod.
