### ISSUE TITLE
HTTP Error 404.0 - Not Found

### ISSUE THREAD

**Issue by filippobottega** [NuGet/NuGetGallery#3430]
Hello,
  I'm trying to use Nuget.Server using Visual Studio 2015. I get some errors.

Repro:

    Create an empty web application with the name "MyNuget"
    Install the NuGet.Server package
    Build and run website from Visual Studio F5 (Debug)
    Navigate to the website, and click on the "here" link to navigate to the Packages folder

Actual result:

    404 error

```
Requested URL	   http://localhost:43672/nuget/Packages
Physical Path	   <..>\MyNuget\nuget\Packages
```

but the real path is <..>\MyNuget\bin\Packages

Repro:

```
nuget.exe push MyPackage.nupkg VSTS -Source http://localhost:43672/api/v2/package
Pushing MyPackage.nupkg to 'http://localhost:43672/api/v2/package'...
  PUT http://localhost:43672/api/v2/package/
  Created http://localhost:43672/api/v2/package/ 530ms
Your package was pushed.
```

The package was created under folder <..>\MyNuget\Packages

Repro:

`nuget.exe list -Source http://localhost:43672/api/v2/package`

Error:

`Errore del server remoto: (404) Non trovato.`

How can I create a local nuget server that works?

Best regards,
  Filippo.

**Comment by joelverhagen** [comment]
Could you provide some more details about this step?
> ```
> Build, package and run website from Visual Studio
> ```

In particular, how are you packaging and running the website? If you F5 (Debug) the website in Visual Studio, do you encounter the same problem?

**Comment by filippobottega** [comment]
Hello Joel,
  thank you for your support.

  I have changed:

`Build, package and run website from Visual Studio`

  with the correct step: 

`Build and run website from Visual Studio F5 (Debug)`

  I have attached my solution for testing purpose.

[NugetServer.zip.002.zip](https://github.com/NuGet/NuGetGallery/files/663172/NugetServer.zip.002.zip)
[NugetServer.zip.003.zip](https://github.com/NuGet/NuGetGallery/files/663173/NugetServer.zip.003.zip)
[NugetServer.zip.001.zip](https://github.com/NuGet/NuGetGallery/files/663174/NugetServer.zip.001.zip)

  (Before decompressing, please remove the last zip extension from the file name of each attached files)

  Best regards,
    Filippo.

**Comment by joelverhagen** [comment]
Oh, I see the problem. This is a VB.NET project. NuGet.Server only support .NET Framework 4.6 and later C# projects.

The NuGet.Server project contains a `Routes.cs.pp` (templated C# file) that is added to your project upon installation. This file is what bootstraps NuGet.Server by initializing services and binding routes. Easiest solution is to switch to a C# project. Alternatively, you can rewrite the Routes.cs file in your project as VB.NET (but performing the same logic).

**Comment by joelverhagen** [comment]
To satisfy my own curiosity, I took some time to figure out what the VB.NET implementation of `Routes.vb` would be. Give this a try, changing namespace names where necessary. Note that this **is not** an officially supported NuGet.Server scenario. To "stay on the rails" you should switch to a C# project.

```vb
Imports System.Data.Services
Imports System.ServiceModel.Activation
Imports System.Web.Routing
Imports NuGet.Server
Imports NuGet.Server.DataServices
Imports NuGet.Server.Publishing
Imports RouteMagic

<Assembly: WebActivatorEx.PreApplicationStartMethod(GetType(MyNuget.NuGetRoutes), "Start")>

Public Module NuGetRoutes
    Public Sub Start()
        ServiceResolver.SetServiceResolver(New DefaultServiceResolver)

        MapRoutes(RouteTable.Routes)
    End Sub

    Private Sub MapRoutes(routes As RouteCollection)
        ' Route to create a New package(http://{root}/nuget)
        routes.MapDelegate("CreatePackageNuGet",
                           "nuget",
                           New With {.httpMethod = New HttpMethodConstraint("PUT")},
                           Sub(context)
                               CreatePackageService().CreatePackage(context.HttpContext)
                           End Sub)

        ' The default route is http://{root}/nuget/Packages
        Dim factory = New DataServiceHostFactory()
        Dim serviceRoute = New ServiceRoute("nuget", factory, GetType(Packages))
        serviceRoute.Defaults = New RouteValueDictionary From {{"serviceType", "odata"}}
        serviceRoute.Constraints = New RouteValueDictionary From {{"serviceType", "odata"}}
        routes.Add("nuget", serviceRoute)
    End Sub

    Private Function CreatePackageService() As IPackageService
        Return ServiceResolver.Resolve(Of IPackageService)()
    End Function
End Module
```

**Comment by filippobottega** [comment]
![D'ho!](https://sophosnews.files.wordpress.com/2009/01/the-simpsons-d-oh-mini-posters-71133.jpg)

Thank you!
