### ISSUE TITLE
NuGet manager UI not able to search packages incrementally

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3439]
@jainaashish commented on [Fri Dec 30 2016](https://github.com/NuGet/Home/issues/4173)

I tried searching for package `QGEditors.WinForms` through NuGet manager UI, and typed `QGEditor` but it didn't show any search results for that. But when I typed `QGEditors `then it showed this package.

**Comment by joelverhagen** [comment]
This is a server side issue. 

Returns results: https://www.nuget.org/packages?q=QGEditors
Does not return results: https://www.nuget.org/packages?q=QGEditor

**Comment by joelverhagen** [comment]
The ask here is essentially for n-gram searching. We have this on the autocomplete endpoint but not on package search. Not sure if this is feasible, a good idea, etc. Needs evaluation.

**Comment by skofman1** [comment]
duplicate: https://github.com/NuGet/NuGetGallery/issues/2789
