### ISSUE TITLE
NuGet dist iste is down

### ISSUE THREAD

**Issue by rupaks** [NuGet/NuGetGallery#3444]
Hi Team,

Trying to download NuGet.exe from NuGet site(https://dist.nuget.org/index.html). But looks like site is down.

Please have a look.

Regards,
Rupak

**Comment by cristinamanum** [comment]
Hi rupaks, 
I just tried and the site is up. Please try it again and reply if still does not work for you.
Regards,
Cristina

**Comment by joelverhagen** [comment]
Yes, as @cristinamanum mentioned, dist seems fine from our end. Could you provide a Fiddler trace of your interactions with dist we can diagnose the issue?

Thanks!

**Comment by joelverhagen** [comment]
@rupaks, please feel free to re-open this if you are still having issues interacting with dist.nuget.org.
