### ISSUE TITLE
Unlisted package page should not allow downloading or provide the snippet to install it

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#3452]
Today, if a package is unlisted by the owner, they do not show up in nuget.org search. However, search engines and other nuget package indexes may continue to point to provide a link to the package page when you search for the package. Once on the page, you can either download the nupkg or install it using the PMC using the conveniently provided snippet.

By unlisting a package, the intent of the author is to stop more users from taking a dependency on it without breaking existing users. To that effect, I believe the download link and the PMC install snippet should be removed for unlisted packages.

**Comment by skofman1** [comment]
@anangaur ?

**Comment by scottbommarito** [comment]
Unlisting is meant to prevent discovery. I think hiding the download link or install snippet on unlisted packages is only going to create customer frustration because they've already found it.

**Comment by anangaur** [comment]
Don't have very strong opinion here but I tend to agree with @karann-msft here. The package, though found states that its unlisted and should not be used but then we provide methods/ways to use it. Kind of conflicting info IMO.

**Comment by karann-msft** [comment]
this could become a part of the deprecate feature :)
https://github.com/NuGet/Home/issues/2867

**Comment by anangaur** [comment]
@karann-msft Thats right. Its already part of my proposal.

**Comment by karann-msft** [comment]
closing as dupe of NuGet/Home#2867
