### ISSUE TITLE
ID and title validation does not exclude soft-deleted packages on NuGet.org

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3456]
## Steps

On NuGet gallery:

1. Add a package with ID A and title B.
1. Delete the package.
1. Try to push a package with ID B and title B.

## Expected

You should be able to push the new package.

## Actual

The package is reject with the following warning:

```
The ID of your package, 'B', is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again.
```

/cc @rohit21agrawal

**Comment by scottbommarito** [comment]
Clarification: the package was deleted with the id and version still reserved.
