### ISSUE TITLE
VSTS internal feed package uninstall error on VS2015:The array must contain at least one element.

### ISSUE THREAD

**Issue by liushuanggang** [NuGet/NuGetGallery#3459]
**symptom:**
The error display : "The array must contain at least one element" when update/uninstall the package on a project connected to VSTS.

The visual studio Enterprise 2015 version is 14.0.25431.01 Update 3.
The NuGet Packager Manager version is 3.5.0.1996

**Steps:**
1. Published a simple NuGet package containing 4 .cs files on VSTS.
2. Create a simple project and add into VSTS.
3. Install the package published in step 1.
4. Uninstall the package and get the above error massages.

These steps working fine in the NuGet Packager Manager version is 3.5.0.1848

Only when I check in entire project with the installed package, the uninstall process could successful.

**Comment by cristinamanum** [comment]
Hi @liushuanggang,

Could you please add to the repro the published nuget package used?

Thanks,
Cristina

**Comment by cristinamanum** [comment]
Moved the issue to NuGetHome as it is not a Gallery issue.
https://github.com/NuGet/Home/issues/4244
