### ISSUE TITLE
Picture not in sync with text in the dependency resolution docs

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/NuGetGallery#3460]
The last picture (about the error situation) doesn't match the explanation:

[Cousing dependencies](https://docs.nuget.org/ndocs/consume-packages/dependency-resolution#cousin-dependencies)

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #4237](https://github.com/NuGet/Home/issues/4237) via [**ZenHub**](https://www.zenhub.com/)
