### ISSUE TITLE
NuGet.Server: FileFormatException

### ISSUE THREAD

**Issue by UweKeim** [NuGet/NuGetGallery#3461]
"Out of nothing", we see errors when pushing to our local NuGet Server (installed from [nugetserver.net](http://nugetserver.net), setup version 2.8.5.1).

The push command looks like:

    NuGet.exe Push MyPackage.1.0.0.1.nupkg" -ApiKey "…" -source "http://my-server.com:81"

(NuGet version on the client is 3.5.0.1996)

The output on the client looks like:

```
Pushing MyPackage.1.0.0.1.nupkg to 'http://my-server.com:81'...
  PUT http://my-server.com:81/api/v2/package/
  InternalServerError http://my-server.com:81/api/v2/package/ 413ms
  PUT http://my-server.com:81/api/v2/package/
  InternalServerError http://my-server.com:81/api/v2/package/ 409ms
  PUT http://my-server.com:81/api/v2/package/
  InternalServerError http://my-server.com:81/api/v2/package/ 397ms
Der Antwortstatuscode gibt keinen Erfolg an: 500 (Internal Server Error).
```

The error message on the server is:

> Archive file cannot be size 0.

In German:

> Archive dürfen nicht die Größe Null besitzen.

Stack trace on the server:

```
2017-01-09 16:09:38.966 +01:00 [Error] Archive dürfen nicht die Größe Null besitzen.
System.IO.FileFormatException: Archive file cannot be size 0.
   bei MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   bei System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   bei System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   bei NuGet.ZipPackage.EnsureManifest()
   bei NuGet.ZipPackage..ctor(Stream stream)
   bei NuGet.Server.PackageService.CreatePackage(HttpContextBase context)
   bei NuGet.Server.NuGetRoutes.<MapRoutes>b__1(RequestContext context)
   bei RouteMagic.HttpHandlers.DelegateHttpHandler.ProcessRequest(HttpContext context)
   bei System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

This thing worked two weeks ago like a charm and now fails with the above error.

What I've done to resolve:

- I've purchased and installed the latest NuGet.Server from [nugetserver.net](http://nugetserver.net/) as version v2.8.60318.667.
- I've monitored with Fiddler to verify that the PUT request actually contains a valid package.
- I've given full ACL access to the Packages folder on the server.
- I've monitored with Process Monitor on the server to confirm that data arrives.

Still, the error message persists.

The only strange thing I found with Process Monitor is:

> Result: PATH_NOT_FOUND
> Path: C:\Program Files (x86)\NuGet Server\server\api\v2\package

Which seems strange, since I've expected the "api/v2/package" to be a virtual path, not a file system path. Although I don't know whether this is related to the error.

I can only imagine some recent Windows Update on our Windows 2012 R2 Server broke the NuGet Server functionality.

**My question:**

Can anyone give me some hints on how to approach to fix this issue?

**Comment by joelverhagen** [comment]
Hey @UweKeim, thanks for taking the time to report this.

The NuGet.Server version you mentioned seems to correlate to package version [2.8.5](https://www.nuget.org/packages/NuGet.Server/2.8.5). Have you tried installing this package to an empty .NET Framework 4.5 web project and just hitting F5 (debug) in Visual Studio?

Could you try this an see if you are running into the same problem?

**Comment by AndreasLamp** [comment]
Hey @joelverhagen ,

i run into the same Problem, creating a test project with nuget.server version 2.8.5 and 2.11.3 works.

Best regards

Andreas

**Comment by joelverhagen** [comment]
Interesting. So upgrading to 2.11.3 resolves your issue? Could you use that as a work-around until we fully understand what is going on here?

To help understand the 2.8.5 problem, could you provide a .zip file wit:

1. The NuGet.Server 2.8.5 test project
1. The package (.nupkg) that you are trying to push.
1. The nuget.exe client you are using.
1. A text file or script containing the exact nuget.exe command you are running to reproduce the issue.
1. A Fiddler trace of the failed push HTTP requests.

Thanks!

**Comment by UweKeim** [comment]
My personal workaround is the following:

- The NuGet Server I'm trying to push to is in our local network (LAN)
- I created an UNC share on that server that points to the "Packages" folder of the NuGet Server.
- I'm _not_ doing a push at all.
- Instead I'm doing a simple file copy of my local NuGet package to that "Packages" share on the server.

Probably my workaround may have some drawbacks, but it works perfectly in my scenario.

**Comment by AndreasLamp** [comment]
Hello @joelverhagen ,

here some Information:

NuGet.exe push Rehm.Core.WCF.Contracts.1.1.20.6569.nupkg -Source http://server/ API-REHMCORE

[package.zip](https://github.com/NuGet/NuGetGallery/files/703642/package.zip)
[nuget.zip](https://github.com/NuGet/NuGetGallery/files/703643/nuget.zip)
[nuget_push.zip](https://github.com/NuGet/NuGetGallery/files/703646/nuget_push.zip)

**Comment by joelverhagen** [comment]
Unfortunately, I am unable to reproduce the issue. The NuGet.Server instance you are hitting is hosted in IIS, right? Could you take a look at Event Viewer on the hosting machine and look for some indication of the exception that occurred?

For example, I make the `/api/v2/package` endpoint throw a simple exception and I see this in my Windows Event Viewer:

```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 1/13/2017 10:49:58 AM 
Event time (UTC): 1/13/2017 6:49:58 PM 
Event ID: 714236cc6de34ac085dfae630fd2a0d2 
Event sequence: 31 
Event occurrence: 10 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/2/ROOT-2-131288068306596339 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: D:\trash\2017-01-13\nugetgallery3461\WebApplication1\WebApplication1\ 
    Machine name: JVER-D-1 
 
Process information: 
    Process ID: 26100 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\NuGetServer 
 
Exception information: 
    Exception type: Exception 
    Exception message: foo!
   at WebApplication1.NuGetRoutes.<>c.<MapRoutes>b__1_0(RequestContext context) in D:\trash\2017-01-13\nugetgallery3461\WebApplication1\WebApplication1\DataServices\Routes.cs:line 26
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: http://jver-d-1/api/v2/package/ 
    Request path: /api/v2/package/ 
    User host address: D:\trash\2017-01-13\nugetgallery3461\WebApplication1\WebApplication1\ 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\NuGetServer 
 
Thread information: 
    Thread ID: 13 
    Thread account name: IIS APPPOOL\NuGetServer 
    Is impersonating: False 
    Stack trace:    at WebApplication1.NuGetRoutes.<>c.<MapRoutes>b__1_0(RequestContext context) in D:\trash\2017-01-13\nugetgallery3461\WebApplication1\WebApplication1\DataServices\Routes.cs:line 26
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 
 
Custom event details: 
```

**Comment by UweKeim** [comment]
For me, the nuget server is not hosted in IIS. 

I'm using the standalone version from nugetserver.net

**Comment by joelverhagen** [comment]
@UweKeim, I am not familiar with the nugetserver.net product. Could you reach out to them? I think this is an issue with how NuGet.Server is being hosted.

**Comment by AndreasLamp** [comment]
Hello @joelverhagen ,

after long testing and finally installing an iis and hosting the nuget.server on it, the problem is gone.

The nugetserver.net product using the cassini (https://cassinidev.codeplex.com/) web server. When i create a project with CassiniDev (https://www.nuget.org/packages/CassiniDev/) and nuget.server, the error occures. I think the FileFormatException is a problem of cassini.

Best regards and thank you very much for your effort

Andreas

**Comment by UweKeim** [comment]
I've contacted the nugetserver.net vendor via their [contact form](http://inedo.com/contact) some weeks/months ago.

Unfortunately the never replied :-(

**Comment by sburky** [comment]
I have a similary problem ...
I use NuRep Project(https://bitbucket.org/galaktor/nurep)  wich  is a NuGet repository that also serves symbols and sources. It use Nuget.Server vs 2.0.1 and nuget.Core vs 2.8.5
it works fine on my environment.

I try to upgrade this projet with nuget.Server 2.8.13 and nuget.Core vs 2.14.0 and  I have a curious edge effect.

in this simple code 

         `           var request = context.Request;
            var stream = request.Files.Count > 0 ? request.Files[0].InputStream : request.InputStream;
            var package = new ZipPackage(stream);

            var symbolFiles = package.GetFiles("lib").Where(f => Path.GetExtension(f.Path) == ".pdb").ToList();

            foreach (var symbolFile in symbolFiles)
                ProcessSymbolFile(symbolFile, package);

            stream.Position = 0;

            if (IsSymbolPackage(package, symbolFiles))
                symbolPackageService.CreatePackage(context);
            else
                packageService.CreatePackage(context);`

with the latest versions, when i execute the line ` var package = new ZipPackage(stream);` the contentLength of the underlaying httpContext is reseting (and in my sense the multipart-encode stream) ... 

and i have the error mentioned below ... "
