### ISSUE TITLE
Query/concern about the download count for my package.

### ISSUE THREAD

**Issue by GregTrevellick** [NuGet/NuGetGallery#3471]
_**NOTE**: I originally emailed support about this, and subsequently received an email from Justin Emgarten (juste@microsoft.com) on 14 January 2017 at 02:07 saying "Please file an issue on: https://github.com/nuget/nugetgallery/issues"._

**ISSUE:**
I have a query/concern about the download count for my package, as follows:

     Package:  https://www.nuget.org/packages/OpenInApp.Common/

The download stats for this package are as follows (as of 16:15 GMT 14th January 2017)

Version                                                        Downloads   Last updated
OpenInApp.Common 1.0.36 (this version)  0                  Tuesday, January 10, 2017
OpenInApp.Common 1.0.27                       0                   Sunday, January 8, 2017
OpenInApp.Common 1.0.22                       0                   Saturday, January 7, 2017
OpenInApp.Common 1.0.0                        47                  Wednesday, January 4, 2017

As you can see the stats are zero for all versions except v1.0.0.

I am sure the other version have had downloads, and in fact I did a direct "save as" from the nuget website for version 1.0.36 earlier this week.

This is the first package I've uploaded, so I may be doing something wrong as a "newbie" in the package definitions for 1.0.22 / 1.0.27 / 1.0.36.

Thanks, Greg

**Comment by 304NotModified** [comment]
See below the page

https://status.nuget.org

**Comment by 304NotModified** [comment]
AFAIK this a recurring issue and hasn't a high prior.

**Comment by skofman1** [comment]
@GregTrevellick , as was reported on our status page, our statistics pipeline currently degraded. Further details are provided here: https://github.com/NuGet/NuGetGallery/issues/3472
We treat this as a top priority, and activly working on a fix.

**Comment by cristinamanum** [comment]
Hi @GregTrevellick,

We deployed the fix for the statistics pipeline.  All the versions of  OpenInApp.Common  have downloads count > 0.
I will close this issue but feel free to reopen if you have any concerns.

Regards,
Cristina

**Comment by 304NotModified** [comment]
I see still packages with 0 downloads while I know multiple users has installed it. 

https://www.nuget.org/packages/NLog.web.aspnetcore
https://www.nuget.org/packages/NLog.web

**Comment by GregTrevellick** [comment]
Thanks Julian 😀

**Comment by shishirx34** [comment]
@304NotModified - I see your packages were uploaded on January 18. Our system is catching up with a backlog of CDN logs chronologically and currently processing data for the last week. It will still be another day until it catches up completely up to date. We will keep you posted.

**Comment by 304NotModified** [comment]
Thanks for the update!

**Comment by GregTrevellick** [comment]
Thanks 😀

**Comment by cristinamanum** [comment]
Hi @304NotModified  - the above two packages have downloads numbers for 4.3.0 version.
