### ISSUE TITLE
Install command on package description page

### ISSUE THREAD

**Issue by am11** [NuGet/NuGetGallery#3473]
On npmjs.org, the details page shows the command to install the package:

![image](https://cloud.githubusercontent.com/assets/3840695/21967742/23c2b786-db95-11e6-9f5c-af66064c3fe8.png)

On nuget.org, the details page also shows us the install command like this:

---
![image](https://cloud.githubusercontent.com/assets/3840695/21967774/ce6f88b2-db95-11e6-8a49-17e683a1917f.png)
---

However, the command:

```powershell
Install-Package System.Net.Http 
```

only works in Visual Studio's Package Manager Console.

It would be great to have a more general command in instruction, which works across the board, instead of or in addition to the existing one:

```cmd
nuget install System.Net.Http
```

or

```cmd
nuget install System.Net.Http -source https://api.nuget.org/v3/index.json
```

**Comment by skofman1** [comment]
@jonwchu ?

**Comment by skofman1** [comment]
We have improved the command UI to show commands for multiple tools:
![image](https://user-images.githubusercontent.com/16807822/44496765-d3613300-a62a-11e8-98a0-b0fbaf6b2daf.png)

Does this solve the issue? Closing for now.

**Comment by am11** [comment]
Thanks, the new experience is much pleasant 👍
