### ISSUE TITLE
ZeroMQ/4.1.0.22 can't be installed

### ISSUE THREAD

**Issue by liluhao1982** [NuGet/NuGetGallery#3475]
Hi team,
Would you please if the package below still exist?
https://www.nuget.org/packages/ZeroMQ/4.1.0.22
I can't download/install it on Windows by Package Manager Consolve: Install-Package ZeroMQ or https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.22

**Comment by chenriksson** [comment]
Hi @liluhao1982 

The package does exist, and I've verified that I can download it from both the Package Manager Console and https://www.nuget.org/packages/ZeroMQ/4.1.0.22.

Can you try again? Do you get an error message?

**Comment by chenriksson** [comment]
ping @liluhao1982. Will wait another day for response before closing.

**Comment by liluhao1982** [comment]
Thanks all, it works, you can close this ticket now.





At 2017-01-20 02:58:39, "Christy Henriksson" <notifications@github.com> wrote:


ping @liluhao1982. Will wait another day for response before closing.
