### ISSUE TITLE
Copy button lost after refreshing account page 

### ISSUE THREAD

**Issue by v-atian** [NuGet/NuGetGallery#3487]
**Repro steps:**
1. Login https://dev.nugettest.org with my own accout "NuGet_Test"
2. Create some API keys like key1, key2 ....
3. Refresh the page.

**Excepted:**
User can copy the key vaule.

**Actual:** 
Copy button lost after refreshing account page.
![apikey](https://cloud.githubusercontent.com/assets/12235523/22240768/7035d3e6-e257-11e6-8079-059cf0c1eaa2.png)

**Comment by skofman1** [comment]
This is by design. A user gains access to the API key only once, after creation. We have a warning banner on top of the new key that points this out.
