### ISSUE TITLE
Certificate is missing SAN for nuget.org

### ISSUE THREAD

**Issue by j3parker** [NuGet/NuGetGallery#3491]
The certificate has `CN=*.nuget.org` but is missing a SAN for the root (`nuget.org`) which is leading to certificiate validation issues.

(`net::ERR_CERT_COMMON_NAME_INVALID` in Chrome.)

Possibly related to #3490

**Comment by joelverhagen** [comment]
@j3parker, thanks for the report. We have reverted the certificate change. Could you try accessing https://nuget.org/ again?

**Comment by j3parker** [comment]
The certificate is now valid (`CN = nuget.org` with a Subject Alternative Name including `*.nuget.org`) but `nuget.org` is doing a very slow 301 to `www.nuget.org`, oddly.

**Comment by joelverhagen** [comment]
Slowness is likely related to app warm-up time. Please let us know if the slowness persists.

**Comment by j3parker** [comment]
Thanks!
