### ISSUE TITLE
Add functional test (P0 level) that tests that https://nuget.org/ redirects to www.nuget.org

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3492]
This will catch future certificate issues when the certificate includes `*.nuget.org` but not `nuget.org`.

Related to https://github.com/NuGet/NuGetGallery/issues/3491.

**Comment by skofman1** [comment]
This wouldn't have helped us in the SSL issue (https://github.com/NuGet/NuGetGallery/issues/3491), since functional tests run on staging slot. 
I added a test to pingdom to cover this case.

**Comment by joelverhagen** [comment]
Real time monitoring -- even better.
