### ISSUE TITLE
Re-injecting the dead-letter files through Stats.ImportAzureCdnStatistics could lead to duplicate data.

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3495]
@cristinamanum commented on [Fri Jan 13 2017](https://github.com/NuGet/Engineering/issues/169)

The stats imports have the following method that inserts data:

```
public async Task ProcessLogFileAsync(
  ILeasedLogFile logFile, 
  PackageStatisticsParser packageStatisticsParser, 
  bool aggregatesOnly = false)
{
  //...
  try
  {
    var logFileName = logFile.Blob.Name;
    var cdnStatistics = await ParseLogEntries(logFile, packageStatisticsParser, logFileName);
    var hasPackageStatistics = cdnStatistics.PackageStatistics.Any();
    var hasToolStatistics = cdnStatistics.ToolStatistics.Any();

    // replicate data to the statistics database
    if (hasPackageStatistics)
    {
      // some code
      **await _warehouse.InsertDownloadFactsAsync(downloadFacts, logFileName**);
      //more code
    }
                
    if (hasToolStatistics)
    {
      // some code
      **await _warehouse.InsertDownloadFactsAsync(downloadFacts, logFileName);**
      //more code
    }
```

If the first Insert download succeed and the second fails the file is added to the dead letter.
If the file is moved in raw storage at reprocessing the first insert will insert same data again .

---

@skofman1 commented on [Thu Jan 19 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-273973559)

@xavierdecoster ?

---

@xavierdecoster commented on [Fri Jan 20 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-274117366)

Looks like we may need a `UNIQUE INDEX` on this table? 
(which will slow down inserts, and increase storage requirements)

---

@xavierdecoster commented on [Fri Jan 20 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-274118521)

Also: the above piece of code is targeting two different tables.
First one is targeting the Fact_Download table, the other one is targeting the Fact_Dist_Download table. They do not insert in the same tables.

See:
* https://github.com/NuGet/NuGet.Jobs/blob/81fa007ca528a64d1a684878e9915f760a26c3c5/src/Stats.ImportAzureCdnStatistics/LogFileProcessor.cs#L79
* https://github.com/NuGet/NuGet.Jobs/blob/81fa007ca528a64d1a684878e9915f760a26c3c5/src/Stats.ImportAzureCdnStatistics/LogFileProcessor.cs#L122

---

@skofman1 commented on [Fri Jan 20 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-274120079)

@xavierdecoster , @cristinamanum , can we close this?

---

@cristinamanum commented on [Fri Jan 20 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-274123059)

I think that an issue still exists. From my understanding - Let's assume that 
1. the first ingest is fine ( Fact_Download and Fact_Download_.. _ProjectType are updated )
2. The  insert for  Fact_Dist_Download  fails (throws) 
Result => file is in dead letter. 

3. The file form dead letter is moved back to the raw storage.
4. It will be processed again and the data from (Fact_Download and Fact_Download_.. _ProjectType ) will be re-ingested.

Maybe we can have the data ingested in one transaction?

---

@xavierdecoster commented on [Fri Jan 20 2017](https://github.com/NuGet/Engineering/issues/169#issuecomment-274134370)

You are right @cristinamanum !
We should update that method to accept a transaction and have both invocations within the same transaction.

**Comment by cristinamanum** [comment]
Another idea that was discussed regarding how to approach this is to use the file LogFileName in the FactDownload and Dist_FactDownload. If the file that is currently processing has already entries in these tables a new insert will not be attempted.
This assumes that: 1. No partial inserts will be done. 2. The data from these tables is not altered by other process/job. (for example a file inserted does not have the LogFileName altered later).

**Comment by xavierdecoster** [comment]
The job handles two pipelines really: one for package download stats, another for tool downloads from dist.nuget.org.

I believe we should be able to gracefully handle errors in either one of these processing pipelines independently. In other words, partial inserts should be possible, albeit within that pipeline's transaction.
So I'm leaning towards not sharing the transaction, and checking the `Fact_Download` (resp. `Fact_Dist_Download`) table for records linked to the currently processed LogFileName.

Thoughts on this approach @cristinamanum ?

**Comment by cristinamanum** [comment]
Reading more the CollectCDNLogs job, my understanding is that two files with the same name to be processed is a supported scenario from the CollectCDNLogsJob point of view. For example in line : 176 in Job.cs  - var isReprocessing = await azureClient.CheckIfBlobExistsAsync(cloudBlobContainer, rawLogFile.FileName); 
and also my understanding after a file is renamed a file with same name can still be created on the ftp server. 
If this is correct it will mean that ImportStats job cannot rely on the assumption that all the files that will come to be processed will have distinct names. It also will mean that the jobs consuming the stats data cannot assume that the file names are different.

**Comment by xavierdecoster** [comment]
> ... my understanding after a file is renamed a file with same name can still be created on the ftp server.

@cristinamanum That should never happen. EdgeCast is dropping the files onto our FTP, and will handles the file names and numerical increments there-in. When a file is dropped onto the FTP that is corrupt, or fails to be delivered to our FTP, they don't retry, they send us an email notification about the failure.

When a file failed to deliver to the FTP server, and we recover it ourselves and copy it to the FTP server, it's still going to be the first successful delivery to the FTP server.

Our own procedure to reprocess a file in the case of failure does not involve the FTP server at all. We copy our deadlettered blobs to the to-be-processed container in blob storage instead.
