### ISSUE TITLE
CollectAzureCdnLogs logs are going to customEvents instead of traces in Application Insights

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3497]
@joelverhagen commented on [Thu Jan 26 2017](https://github.com/NuGet/Engineering/issues/197)

This made it hard to detect that the job was blocked on the same exception over and over.

**Comment by skofman1** [comment]
Is it a local issue (particular exception), general issue (no exception at all, ever), or no AI logs at all (ever)?

**Comment by joelverhagen** [comment]
No AI logs at all (ever) as far as I can tell.

**Comment by cristinamanum** [comment]
The Kusto query will give results.
customEvents
| where timestamp >= ago(30d) 
| extend traceSource = tostring(parsejson(customDimensions)["TraceSource"] )
| where traceSource contains "collectazurecdnlogs"
| project timestamp , traceSource
| order by timestamp desc

**Comment by joelverhagen** [comment]
Ah, is the key difference **customEvents**. I've always been looking in traces! What do the two buckets mean and how are they different?

**Comment by scottbommarito** [comment]
I thought we removed `customEvents`. I was under the impression that `NuGet.Services.Logging` now only logged to `traces`. @skofman1 ?

**Comment by joelverhagen** [comment]
CollectAzureCdnLogs version is 3.0.612 (very old?)

**Comment by skofman1** [comment]
Old job would explain this. Deployment is planned for next week. Closing.

**Comment by joelverhagen** [comment]
Spoke to @skofman1 offline, we agreed to take this through the pipeline so we can verify traces are going to the right place.

**Comment by joelverhagen** [comment]
This will deploy next week.

**Comment by joelverhagen** [comment]
Verified on DEV and INT with:
```
traces
| where cloud_RoleName == 'Stats.CollectAzureCdnLogs'
| count 
```
