### ISSUE TITLE
api calls resulting in 404 shouldn't redirect to error page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3499]
Should just return 404.

**Comment by joelverhagen** [comment]
Which APIs are returning the error page?
https://www.nuget.org/api/v2/Packages(Id='Package.Does.Not.Exist',Version='0.1.2')

**Comment by skofman1** [comment]
Tried the URL you provided @joelverhagen , and couldn't repro. Closing.
