### ISSUE TITLE
Error page on the gallery seems like it's missing styling

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3505]
https://www.nuget.org/Error.html

![image](https://cloud.githubusercontent.com/assets/94054/22385794/0bdfb4be-e489-11e6-8247-1cd29d3171f6.png)

![image](https://cloud.githubusercontent.com/assets/94054/22385775/f7f60fc0-e488-11e6-95af-6ad5a2929265.png)

**Comment by chenriksson** [comment]
We believe this is fixed
