### ISSUE TITLE
Functional tests should not default to INT configuration values

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3516]
Currently, `EnvironmentSettings.cs` has all of its values defaulting to INT. This means if you just want to run the functional tests against your own local gallery, you have to fiddle with a bunch of environment variables. We can change the defaults to point to `localhost` instead.

**Comment by joelverhagen** [comment]
https://github.com/NuGet/NuGetGallery/blob/master/tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs

**Comment by chenriksson** [comment]
@scottbommarito fixed this
