### ISSUE TITLE
Verify Public merged PRs in Gallery

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3518]
Adding required badges:
https://github.com/NuGet/NuGetGallery/pull/3415
https://github.com/NuGet/NuGetGallery/pull/3418

Check that the badges show up on the pages.

Optimizing png images
https://github.com/NuGet/NuGetGallery/pull/3429

**Comment by shishirx34** [comment]
Verified #3415 and #3418
