### ISSUE TITLE
Access custom private NuGet gallery based on dynamic Feed URL

### ISSUE THREAD

**Issue by MathanKumarHJ** [NuGet/NuGetGallery#3520]
I need to provide **private NuGet patch** for the customers. We have more number of customers. We are in the position to provide different NuGet Patch to all needed customers. Now, I have followed below approach for provide NuGet patch

- provided **each NuGet feed** link for each customer and maintain separate NuGet package folder for each customer. But, we have maintained **each Web application** for each customer. This is very complex and it’s not possible achieve for more customers.

- This is my code block

**Web.Config**

```
 <appSettings>
<add key="requireApiKey" value="true" />
<add key="apiKey" value="" />
<add key="packagesPath" value="~/NugetPackages/customer1" />
<add key="enableSimpleMembership" value="false" />
<add key="" />
</appSettings>
```
I want to know other possibilities for to achieve this. My query is

_For Example_

- My Feed link is - http://mydomain/packages/c1 and http://mydomain/packages/c2 etc…
- C1 feed link is want to show only NuGet package which is in customer1 package folder
- C2 feed link iswant to show only NuGet package which is in customer2 package folder

But We need to maintain one web application for achieve these.

Is this possible or not? Could you please share your ideas?

Thanks in Advance

Mathan

**Comment by joelverhagen** [comment]
Hey @MathanKumarHJ, thanks for reaching out about this. It's funny you bring this up. We actually have a sample of how to do this in our `dev` branch of NuGet.Server. The latest release (2.11.3) of NuGet.Server is implemented using WCF. The `dev` branch, which is not yet release as a package on NuGet.org, is implemented using Web API. This allows easier custom multi-feed behavior.

Take a look at this sample in the NuGet.Server repository:
https://github.com/NuGet/NuGet.Server/blob/6fe33292fe93399accfe9e8afefd1acb450a2f0c/samples/NuGet.Server.V2.Samples.OwinHost/Program.cs#L73-L89

If you want to give this a try, your best bet it to produce a private build of NuGet.Server, `dev` branch.

**Comment by maartenba** [comment]
There are also many options available in the NuGet Ecosystem - check https://docs.microsoft.com/en-us/nuget/policies/ecosystem

**Comment by NagarajMasub** [comment]
Hi @joelverhagen ,

I have also wanted the same feature mentioned in this question. you have mentioned using that dev branch source we can achieve this. any procedures available to know how to set different packages path in that sample. 
and one more doubt is it possible to create multiple feed link using the same application. or any restrictions available..?
