### ISSUE TITLE
Cannot register - HttpAntiForgeryException - Error 400

### ISSUE THREAD

**Issue by anthes** [NuGet/NuGetGallery#3521]
I am trying to install Nugetgallery in a development environment.
I follow all instructions step by step.
I start the site in Visual Studio and try to register an account on my nugetgallery local istance.
I insert all data in the form and this is the error:
```
Error: Invalid Request
We can't process your request because your browser sent an invalid request. This is likely because you have disabled Cookies in your browser. Please enable cookies in your browser settings and try your request again.
```
This is my configuration:
IIS 10
Windows 7 x64
Visual Studio 2013
Nugetgallery tagged version NuGetGallery-2017.01.17
SSL totally disabled in my configuration

I see the code and it seems that the problem is in this filter: AntiForgeryErrorFilter, infact the Exception that is raised is HttpAntiForgeryException
I have understood that this filter generate a cookie, but in my development environment this cookie is not generated.

**Comment by skofman1** [comment]
Have you tried setting this parameter to false:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L248

**Comment by anthes** [comment]
Alleluia. Solved.
Now I try to enable SSL but the script "Enable-LocalTestMe.ps1" is breaked so it cannot generate certificate.

**Comment by skofman1** [comment]
what is the error you are getting?

**Comment by anthes** [comment]
The error is here:
# Set the Certificate
Invoke-Netsh http add sslcert hostnameport="$(Get-SiteHttpsHost)" certhash="$($siteCert.Thumbprint)" certstorename=Root appid="{$([Guid]::NewGuid().ToString())}"

It says that "hostnameport" is not accepted like parameter, I changed it to "ipport" and it works.
I think that is better to fix it in "Enable-LocalTestMe.ps1" script

**Comment by skofman1** [comment]
Seems that it;s a OS version issue: https://msdn.microsoft.com/en-us/library/windows/desktop/cc307220(v=vs.85).aspx

What OS are you using?

**Comment by anthes** [comment]
I'm using Windows 7 x64
In the page above the hostnameport parameter isn't exist.

**Comment by skofman1** [comment]
The link (https://msdn.microsoft.com/en-us/library/windows/desktop/cc307220(v=vs.85).aspx) describes the command line parameters that sslcert supported on Windows 7. Those don't include hostnameport. This is the reason Enable-LocalTestMe.ps1 doesn't work for you as is.

**Comment by anthes** [comment]
Thx Svetlana. I hope you can fix it. Like sofware developer I try my software always with a configuration older.
I use virtual machine to test my software in all operating systems before I release it.
I think that is a agood practice.

**Comment by skofman1** [comment]
@anthes , thanks for your feedback. We would welcome a PR that will allow Enable-LocalTestMe.ps1 to run on both Win7 and newer OS.
