### ISSUE TITLE
Cannot download Nuget package from server in Azure

### ISSUE THREAD

**Issue by LukeHenners** [NuGet/NuGetGallery#3522]
Hi,

I am hosting a Nuget server in Azure, I have managed to push a package successfully:

> http://x/nuget/Packages

Has the entry, I have added the server as a package source inside visual studio and it's also listed there - however when I attempt to install the package through the package manager I get the following in the output window:

```
Attempting to gather dependency information for package 'package.2.0.0' with respect to project 'project', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'package.2.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'package.2.0.0'
Resolved actions to install package 'package.2.0.0'
  GET http://x/api/v2/package/project/2.0.0
  NotFound http://x/api/v2/package/project/2.0.0 69ms
Install failed. Rolling back...
```

I have no idea why it can't be seen, I assume there are some settings I am missing or something I have to do with Azure web apps but I can't pinpoint it...

**Comment by joelverhagen** [comment]
Hey @LukeHenners, thanks for reaching out about this issue. Could you provide some steps on how you hosted NuGet.Server in Azure? More details the better! 

What version of NuGet.Server are you using?

Also, could you provide a Fiddler trace of the different (both successful and unsuccessful) operations you can perform against this source?

If you are concerned about privacy, please feel free to send information to support@nuget.org. Note that file attachments are sometimes rejects so it is easiest to host files on a third-party file sharing site (like Dropbox, OneDrive, or Google Drive) and then include the link in the email.

**Comment by LukeHenners** [comment]
Thanks for reply @joelverhagen!

I am using Nuget server 2.11.3.0, it seems to in fact be an issue with the .nupkg I have generated and am publishing to the server not the server itself, which is weird.

I published the normal entity framework package up to the server and then attempted to download this it worked fine, the nupkg that I have generated (FooCompany.Product.Assembly) has been pushed and is in the exact same location, in the exact same format but for some reason I can't download it as mentioned in initial post as it "can't find it".

I have just used the standard publish to IIS with a publishing profile - it makes me think that something is wrong with the package but I can't understand what...

**Comment by joelverhagen** [comment]
I would love to get a clear picture of what's going on here. It really surprises me that the package itself is the problem here. Do other packages work just fine? Could you try pushing a "known good" package to your NuGet.Server instance (e.g. [NuGet.Core 2.14.0](https://www.nuget.org/packages/NuGet.Core/2.14.0))?
