### ISSUE TITLE
Indexing seems stuck for SkiaSharp.* packages

### ISSUE THREAD

**Issue by mattleibow** [NuGet/NuGetGallery#3537]
There appears to be an issue with the indexing of these packages:
http://www.nuget.org/packages/SkiaSharp
http://www.nuget.org/packages/SkiaSharp.Svg

I uploaded it a few hours ago, and it is still going. Is there an issue somewhere?

**Comment by shishirx34** [comment]
Hi @mattleibow, 

Yes we are aware of the issue. We have posted an update on https://status.nuget.org/

We are having a live site issue, and it will be a little while before it gets resolved. I will keep you posted once your package gets indexed. 

Please note, your package, while not indexed in v3 feed it should still be available to be consumed by v2 feed: https://nuget.org/api/v2

Thank you for your patience.

**Comment by shishirx34** [comment]
Hi @mattleibow - Your packages are indexed. Please let us know if you still see any issues.

**Comment by mattleibow** [comment]
Thanks for the feedback and resolution!
