### ISSUE TITLE
makecert has been deprecated

### ISSUE THREAD

**Issue by zorthgo** [NuGet/NuGetGallery#3538]
I am trying to install a copy of NugetGallery by following the instructions on the README.md file. But when I get to step 4.ii and try to run the `.\tools\Enable-LocalTestMe.ps1` script it throws an error message saying that it can't find makecert.exe. The issue seams to be that makecert has been deprecated and is no long there. Is there a new updated instructions set somewhere else in the repo that doesn't make use of makecert? Thanks! :)

**Comment by skofman1** [comment]
@zorthgo , did @anthes unblock you?
We will add fixing the script to our backlog.

**Comment by blowdart** [comment]
Powershell can do it; 

New-SelfSignedCertificate -DnsName test.contoso.com -CertStoreLocation cert:\LocalMachine\My

**Comment by agr** [comment]
`.\tools\Enable-LocalTestMe.ps1` script has a parameter `-MakeCertPath` which allows to specify your path to `makecert.exe`. So in my case I run:

    .\tools\Enable-LocalTestMe.ps1 -MakeCertPath "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\makecert.exe"

And it works for me. No need to edit anything.

**Comment by loic-sharma** [comment]
`tools\Enable-LocalTestMe.ps1` has been replaced with `tools\Setup-DevEnvironment.ps1`. This uses the same PowerShell command that blowdart mentioned instead of makecert.
