### ISSUE TITLE
List of dependencies is not correctly ordered

### ISSUE THREAD

**Issue by lucaritossa** [NuGet/NuGetGallery#3550]
Is this a by-design behaviour?

For example: 
*  open [AutoMapper](https://www.nuget.org/packages/AutoMapper/) nuget gallery package
*  on "Dependencies" section you can see that "Microsoft.CSharp" is not before "NETStandard.Library

![image](https://cloud.githubusercontent.com/assets/12578097/22828428/8d2aa6fe-ef9d-11e6-911e-2582b4ec04ce.png)

I reported similar [issue](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/166) to [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) project.
It seems that it depends on the order the dependencies have been specified on nuspec file.
This is the Automapper nuspec file:  

![image](https://cloud.githubusercontent.com/assets/12578097/22828643/b977b052-ef9e-11e6-80fd-d2f4f209f0df.png)

**IMO the best result should be an alphabetically order**

**Comment by skofman1** [comment]
Thanks for reporting!

**Comment by robertmuehsig** [comment]
Recap: The Dependencies should be ordered alphabetically, right? 
Does this also apply for the "groups", e.g. 

   <group targetFramework="FrameworkB">
      <depedency... />
   </group>
   <group targetFramework="FrameworkA">
      <depedency... />
   </group>

FrameworkA (with its dependencies) should be displayed before FrameworkB, even if it is declared in the other way in the nuspec file, correct?

**Comment by skofman1** [comment]
@robertmuehsig , that would make sense

**Comment by robertmuehsig** [comment]
The NuGet Client (v 4.0.0) should order it the same way, right?

Currently it is also unordered:
![image](https://cloud.githubusercontent.com/assets/756703/24351111/d1533408-12e4-11e7-8392-40cf57239827.png)

**Comment by skofman1** [comment]
Thanks @robertmuehsig , created an issue for the client 🌷
