### ISSUE TITLE
dist.nuget.org download links overlap the border

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#3554]
nuget.exe download links on dist.nuget.org go outside of the box in Firefox

![capture](https://cloud.githubusercontent.com/assets/6381138/22840493/9afec88e-ef82-11e6-8fba-664e2fe35792.PNG)

This page should be updated to a format that supports a long list of versions for each of these components since we will continue to add to this list.

**Comment by skofman1** [comment]
was fixed
