### ISSUE TITLE
Update catalog2registration to support SemVer 2.0.0

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3560]
To support [SemVer2 Protocol](https://github.com/NuGet/Home/wiki/Semver-2.0.0-Protocol) on the registration blobs, we should expose a new endpoint RegistrationsBaseUrl/Versioned, with a client version greater than or equal to 3.5.0.

**Comment by joelverhagen** [comment]
Please include unit testing (Xunit) in this work, which might be expensive considering the infra might not be there at all.
