### ISSUE TITLE
Catalog2Registration is slow on updating packages with multiple versions

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3566]
Need to investigate why, and come up with improvements.

**Comment by skofman1** [comment]
@dtivel , FYI

**Comment by dtivel** [comment]
There's not a lot we can do here.

For each package registration consists of an index, zero or more pages, and package details leaves.  Whenever a new version is added, Catalog2Registration must reload the index and all pages in the registration graph so it can update all entries with a new commit ID and timestamp.  The package details leaves are not reloaded.

Ideas include:

* Optimize RDF document loading/creation.
* Increase registration page size.
* Break the pattern today that all package registration entries must have the same commit ID and timestamp.  Instead, only update the commit ID and timestamp for updated/new pages.

**Comment by skofman1** [comment]
Closing as @joelverhagen  rewrote the job and fixed the issues.
