### ISSUE TITLE
Package should store which source it is installed from

### ISSUE THREAD

**Issue by petterek** [NuGet/NuGetGallery#3573]
I think it would be a good idea to add an attribute to the <package > tag, to indicate which source it was installed from. 

 <package id="NUnit" version="3.6.0" targetFramework="net461" src="nuget.org" />

When installing a package using the "Manage packages for soulution" in vs studio, then nuget will use the src from the tag, and not from the src selected in the DropDown 

nuget fails to install a package when the "wrong" packagesource is selected, with an "package not found"

**Comment by petterek** [comment]
I don't think this issue is about this.. 
This occure in mycase because I have 5 different package sources hosting different kind of packages. 

Might be my us case is "out of scope" but I also belive that adding a src attribute to the package tag could be useful. For information to the user as well when looking at the packages file

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #4666](https://github.com/NuGet/Home/issues/4666) via [**ZenHub**](https://www.zenhub.com/)
