### ISSUE TITLE
Multiple feeds in single application using NuGet Server

### ISSUE THREAD

**Issue by NagarajMasub** [NuGet/NuGetGallery#3575]
Hi Guys,

I have to create multiple NuGet feeds in single applications like proget and myget feeds. currently, am using NuGet.Server for my feed. am having separate applications for each feed. now I need a number of feeds so it leads to implementing a number of sub-applications. is there is any other options available in NuGet server?

I have found the similar requirement in this question
https://github.com/NuGet/NuGetGallery/issues/3520

as per @joelverhagen  comment in that question. I have downloaded and checked the source. as per my knowledge, only 3 feeds/application can be possible in that source. if I am wrong please correct me.

1. How many feeds can be created in that NuGet Server development source
2. is there is any document available to use that development source for multiple feeds..?

Thanks in advance

**Comment by joelverhagen** [comment]
The sample provided in the `dev` branch has three mentioned, but you could certainly add more by following the same pattern. We have not done any testing to what the practical limit there is in a single process. Could you describe your specific scenario so we can better help you?

**Comment by NagarajMasub** [comment]
Hi @joelverhagen 

We have nearly 8 lack customers, we are trying to provide customer specific feeds. 
so one feed link will show that specific customer's packages alone. like these, we need to provide for multiple customers.
I can see in MyGet and ProGet servers provide the option to create N number of feeds. likewise, any option is available.
Or we can use any other way to achieve this in our NuGet Server itself.?

**Comment by joelverhagen** [comment]
If you consume the `NuGet.Server.V2` package produced by the `dev` build of the NuGet.Server repository (of which you'll have to build locally), it should be possible to achieve this. NuGet.Server provide basic tools to achieve this but not a ready-made "N number of feeds" implementation.

**Comment by NagarajMasub** [comment]
@joelverhagen  ok thanks, as per your suggestion we are going to modify the NuGet.Server source to achieve N number of feeds.
Is there is any document for this multiple feeds workflow..? or how to define packagesPath and feed links for this multiple feeds.

**Comment by joelverhagen** [comment]
Nope, no such documents. The best offering is the sample project in the `dev` branch.
