### ISSUE TITLE
NuGet and .Net Foundation logos missing from NuGet.org downloads page

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#3577]
![2017-02-16](https://cloud.githubusercontent.com/assets/10507120/23035849/6bde84ba-f435-11e6-91f2-a455b49e29c2.png)

Observed on chrome, edge and internet explorer.

**Comment by dtivel** [comment]
Looks like https://docs.nuget.org/images/logo.png is broken.

**Comment by skofman1** [comment]
@ryuyu , this is probably related to the site move.

**Comment by ryuyu** [comment]
Deployed fixes to point to local copies of the images.
