### ISSUE TITLE
[Perf] NuGet APIs seems to be slow in NZ

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#3595]
**From Twitter:**
![image](https://cloud.githubusercontent.com/assets/14800916/23315206/165c8050-fa7a-11e6-8cd3-243bf1664141.png)

**Sample to try:**
If you clone https://github.com/exceptionless/foundatio and try and get a package list in nz vm should probably reproduce

**Comment by joelverhagen** [comment]
We have not heard back from the customer. Please re-open if the issue re-appears.

**Comment by niemyjski** [comment]
Sorry, I was on an extended vacation, I was unable to update my packages or get available updates for almost all of trip throughout the north and South Island of New Zealand, the connections ranged from terrible to ok (10mb/5mb). On the 10/5mb connection it took a good 5 minutes it seemed before I could get my list of package updates.
