### ISSUE TITLE
Registration page of some packages has incorrect "listed" attribute.

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3612]
Some packages are listed in V2 but have a registration page that suggests they are unlisted and vice versa.

It seems to me like Catalog2Registration either skipped or incorrectly updated these when they were listed or unlisted.

They all appear in the search index and flat container correctly.

The issue has occurred more recently than the last search index rebuild so it is likely an issue with just Catalog2Registration itself.

[Here is a report containing every package with this issue.](https://github.com/NuGet/NuGetGallery/files/815506/registration.page.of.some.packages.has.incorrect.listed.attribute.zip)

**Comment by skofman1** [comment]
One of the issues: https://github.com/NuGet/NuGetGallery/issues/3709

**Comment by skofman1** [comment]
Another issue: https://github.com/NuGet/NuGetGallery/issues/3716

**Comment by skofman1** [comment]
All affected packages were reflowed.
