### ISSUE TITLE
Some packages are missing a registration1 page

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3613]
Some of these packages have a page in registration0, but some do not.

Most of these packages are also missing their flat-container nupkg.

All packages are also found in search except for a couple older packages that are all unlisted. This suggests the issue is in Catalog2Registration itself because Catalog2Lucene and often Catalog2Dnx are running correctly.

[Here is a zip containing reports of all packages with this issue.](https://github.com/NuGet/NuGetGallery/files/815524/some.packages.are.missing.a.registration1.page.zip)

**Comment by loic-sharma** [comment]
Replaced by #3991
