### ISSUE TITLE
Some packages are missing a flat-container nupkg

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3614]
Most of these packages are also missing their registration1 page.

All packages are found in search except for a couple older packages that are all unlisted. This suggests the issue is in Catalog2Dnx itself because Catalog2Lucene and often Catalog2Registration are running correctly.

[Here is a zip containing reports of all packages with this issue.](https://github.com/NuGet/NuGetGallery/files/815543/Some.packages.are.missing.a.flat-container.nupkg.zip)

**Comment by loic-sharma** [comment]
Replaced by #3991
