### ISSUE TITLE
Some packages do not appear in the v2 Packages feed (Packages(Id='...',Version='...'))

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3615]
- https://www.nuget.org/packages/OKHOSTING.Core/1.0.28
- https://www.nuget.org/packages/Protogame/0.0.0-SHAd17c35164b4f4445175753be35a2892ed0b5d77e

For example, https://www.nuget.org/api/v2/Packages(Id='Protogame',Version='0.0.0-SHAd17c35164b4f4445175753be35a2892ed0b5d77e')

OKHOSTING.CORE is in V3 correctly.
Protogame is missing from V3 entirely.

[Here is a report containing both packages.](https://github.com/NuGet/NuGetGallery/files/815566/Some.packages.do.not.appear.in.the.v2.Packages.feed.zip)

**Comment by skofman1** [comment]
Both packages appear in V2 search results.
package https://www.nuget.org/packages/Protogame/0.0.0-SHAd17c35164b4f4445175753be35a2892ed0b5d77e didn't appear in V3, however, there are no logs to investigate. Reflowed the package.
