### ISSUE TITLE
Some packages are missing their V2 nupkg

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3616]
- https://www.nuget.org/packages/GSF.Web.Security/2.1.161-beta
- https://www.nuget.org/packages/XOMNI.SDK.Private/4.0.0-alpha20

Packages are also missing from V3 entirely.
We may not even have the .nupkg for these packages anywhere!

[Here is a zip containing a report of both packages with this issue.](https://github.com/NuGet/NuGetGallery/files/815564/Some.packages.are.missing.their.V2.nupkg.zip)

**Comment by skofman1** [comment]
This behavior was possible because we saved the package in the DB before uploading to blob storage. We fixed the issue since (can't find the issue #), so this behavior can't happend anymore.
