### ISSUE TITLE
[Statistics] Reduce DB size by removing unused data - project type

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3623]
This data is not used in any functionality today. We only track it because we have the data available at w3c-log parsing time, and it is *only available for requests originating by v2 clients that send the `NuGet-ProjectGuids` header*. (see https://github.com/NuGet/Home/issues/3708)

We could reconsider storing this data when revisiting the design of the NuGet statistics feature.

> **Note**
> 
> Even when we no longer import these datapoints into the stats database, we still have all the data in the w3c-logs we upload to blob storage.
>
> However, its value may be questionable, as we do not get consistent data from all clients, and there's no data provided by the v3 protocol.

### Impact on database

A database size reduction could be achieved totalling **1,002.38 MB** (or 0.98 GB)!

Removing these indices will also improve performance of insert/delete operations against the `[dbo].[Fact_Download]` and `[dbo].[Fact_Dist_Download]` tables.

In addition, we generate less churn on the data by avoiding clean-up operations.

The following database objects would become obsolete:

* Table `[dbo].[Fact_Download_Dimension_ProjectType]` (size = 548.49 MB)
* Table `[dbo].[Dimension_ProjectType]` (size = 0.39 MB)
* Stored procedure `[dbo].[EnsureProjectTypeDimensionsExist]`
* Clustered index `[dbo].[Fact_Download_Dimension_ProjectType].[PK_Fact_Download_ProjectType]` (size = 235.88 MB)
* Non-clustered index `[dbo].[Fact_Download_Dimension_ProjectType].[Fact_Download_Dimension_ProjectType_NCI_ProjectType]` (size = 217.54 MB)
* Non-clustered index `[dbo].[Dimension_ProjectType].[Dimension_Project_NCI_ProjectTypes]` (size = 40 KB)
* Clustered index `[dbo].[Dimension_ProjectType].[PK_Dimension_Project]` (size = 40 KB)

### Impact on jobs

The `Stats.ImportAzureCdnStatistics` job would no longer need to deal with project-type data.

We could:

* avoid the need to check whether a Project-Type already exists, and if not, create it during import;
* avoid the need to retain already imported Project-Type dimensions into in-memory cache;
* reduce complexity of import by no more linking Project-Type identifiers to the download facts in a linked table (many-to-many relationship).

**Comment by skofman1** [comment]
We decided to go in a different direction to reduce DB size. Will reopen if needed.

**Comment by xavierdecoster** [comment]
Reopening to restart the discussion on this one (and already have a PR ready :)). This may be a good time to finally do this: see https://github.com/NuGet/Engineering/issues/467
