### ISSUE TITLE
[Statistics] Reduce DB size by removing unused data - original UserAgent-strings

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3624]
This data is not used in any functionality today. We only track it because we have the data available at w3c-log parsing time, and it *could* be useful from operational point of view. So far, we only used this once to correct a few parsing errors in the early days of this parser - to avoid having to deal with reimporting a huge set of data. *It is questionable in terms of cost-effectiveness, as well as usefulness (as we only retain 6 weeks of data, parsing errors will heal itself over time).*

We could still store it elsewhere for operational purposes (e.g. in Azure table storage). Or we could reconsider storing this data when revisiting the design of the NuGet statistics feature.

> **Note**
> 
> Even when we no longer import these datapoints into the stats database, we still have all the data in the w3c-logs we upload to blob storage.

### Impact on database

A database size reduction could be achieved totalling **55,672.16 MB** (or 54.37 GB)!

Removing these indices will also improve performance of insert/delete operations against the `[dbo].[Fact_Download]` and `[dbo].[Fact_Dist_Download]` tables.

In addition, we generate less churn on the data by avoiding clean-up operations.

The following database objects would become obsolete:

* Table `[dbo].[Fact_UserAgent]` (size = 29.65 MB)
* Table column `[dbo].[Fact_Download].[Fact_UserAgent_Id]` (size = 2,585.75 MB)
* Table column `[dbo].[Fact_Dist_Download].[Fact_UserAgent_Id]` (size = 23.63 MB)
* Stored procedure `[dbo].[CleanupFactUserAgent]`
* Stored procedure `[dbo].[EnsureUserAgentFactExists]`
* Stored procedure `[dbo].[PatchClientDimensionForUserAgent]`
* SQL Type `[dbo].[UserAgentFactTableType]`
* Non-clustered index `[dbo].[Fact_Download].[Fact_Download_NCI_UserAgent]` (size = 52,560.89 MB)
* Non-clustered index `[dbo].[Fact_Dist_Download].[Fact_Dist_Download_NCI_UserAgent]` (size = 472.24 MB)

The following database objects would decrease in size:

* Non-clustered index `[dbo].[Fact_Dist_Download].[Fact_Dist_Download_NCI_Client]` would no longer need to include the `Fact_UserAgent_Id` column, or would perhaps also be obsolete.
* Non-clustered index `[dbo].[Fact_Download].[Fact_Download_NCI_Client]` would no longer need to include the `Fact_UserAgent_Id` column, or would perhaps also be obsolete.

### Impact on jobs

The `Stats.ImportAzureCdnStatistics` job would still need to parse the original user agent strings, however, it would no longer need to store the original data, which would improve import speed, throughput, and overall performance of the job.

We could:

* avoid the need to check whether a UserAgent string already exists, and if not, create it during import;
* avoid the need to retain already imported UserAgent facts into in-memory cache;
* reduce complexity of import by no more linking original UserAgent-string identifiers to the download facts.

The `Stats.RefreshClientDimension` job would become obsolete. This job is the ad-hoc executable to patch a client dimension when a parsing error in user agent strings needs to be fixed.

**Comment by skofman1** [comment]
We decided to go in a different direction to reduce DB size. Will reopen if needed.
