### ISSUE TITLE
[Statistics] Reduce DB size by removing unused data - Platform dimension 

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3626]
This data is not used in any functionality today. We only track it because we have the data available at w3c-log parsing time. *It is questionable in terms of cost-effectiveness.*

We could still store it elsewhere (e.g. in Azure table storage). Or we could reconsider storing this data when revisiting the design of the NuGet statistics feature.

> **Note**
> 
> Even when we no longer import these datapoints into the stats database, we still have all the data in the w3c-logs we upload to blob storage.

### Impact on database

A database size reduction could be achieved totalling **5,172.03 MB** (or 5.05 GB)!

Removing these indices will also improve performance of insert/delete operations against the `[dbo].[Fact_Download]` and `[dbo].[Fact_Dist_Download]` tables.

In addition, we generate less churn on the data by avoiding clean-up operations.

The following database objects would become obsolete:

* Table `[dbo].[Dimension_Platform]` (size = 0.39 MB)
* Table column `[dbo].[Fact_Download].[Dimension_Platform_Id]` (size = 2,585.75 MB)
* Table column `[dbo].[Fact_Dist_Download].[Dimension_Platform_Id]` (size = 2,585.75 MB)
* Stored procedure `[dbo].[EnsurePlatformDimensionExists]`
* Stored procedure `[dbo].[CleanupPlatformDimension]`
* SQL Type `[dbo].[PlatformDimensionTableType]`
* Clustered index `[dbo].[Dimension_Platform].[PK_Dimension_Platform]` (size = 56 KB)
* Non-clustered index `[dbo].[Dimension_Platform].[IX_Dimension_Platform_UniqueIndex]` (size = 88 KB)

### Impact on jobs

The `Stats.ImportAzureCdnStatistics` job would no longer need to store the Platform dimension data, which would improve import speed, throughput, and overall performance of the job.

We could:

* avoid the need to check whether an Platform already exists, and if not, create it during import;
* avoid the need to retain already imported Platform dimensions into in-memory cache;
* reduce complexity of import by no more linking Platform dimension identifiers to the download facts.

**Comment by skofman1** [comment]
We decided to go in a different direction to reduce DB size. Will reopen if needed.

**Comment by shishirx34** [comment]
not much gain here.. decided to not drop this information.
