### ISSUE TITLE
Cannot Hide Package

### ISSUE THREAD

**Issue by mjhillman** [NuGet/NuGetGallery#3637]
I am trying to delete/hide the package "HITS Data Access Layer" but when I uncheck the check box and click Save, the package still shows up in the Package List.  I have done this in the past the the package was moved to the "Unlisted Packages" list, but not this time.

![image](https://cloud.githubusercontent.com/assets/18598702/23752763/a6954402-04a4-11e7-84fd-65c17a2a9069.png)

Thanks.
Mike

**Comment by skofman1** [comment]
@mjhillman, I checked the two package above (HITS_DAL, HITS.DAL), and for each of them, there is a "listed" package version. 
A package will appear in "Packages" list even if it has a single listed version. If you unlist all versions, the package will appear in "Unlisted packages".
