### ISSUE TITLE
Add validation to reject package versions with leading zeros in numeric identifiers (semver v2.0.0)

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3648]
Currently, no `.` characters are allowed in (pre)release labels in the version string, so this is a non-issue currently. However, when introducing semver v2.0.0 support, we should reject packages that use leading zeros in numeric identifiers of release labels.

Example of invalid semver2 version string: `1.0.0-alpha.001`
Example of valid semver2 version string (possible today, no numeric identifier parts in release label): `1.0.0-alpha-001`

**Comment by joelverhagen** [comment]
How is this different than https://github.com/NuGet/NuGetGallery/issues/3648?

The mentioned version is already not parsable as a version range:
http://nugettoolsdev.azurewebsites.net/4.0.0-rtm-2265/parse-version-range?versionRange=%5B1.0.0-alpha.001%2C+%29

**Comment by xavierdecoster** [comment]
You refer to this very same issue? 

It may very well be that it is not parsable, but this issue tracks the very fact that gallery doesn't even try to parse/validate it.

**Comment by joelverhagen** [comment]
> You refer to this very same issue?

😆 oops! Very confusing. Sorry.

I meant https://github.com/NuGet/NuGetGallery/issues/3482.

> It may very well be that it is not parsable, but this issue tracks the very fact that gallery doesn't even try to parse/validate it.

Okay, perhaps we're saying the same thing. I don't understand what work there would be to complete this issue on top of the work required to complete https://github.com/NuGet/NuGetGallery/issues/3482.

**Comment by xavierdecoster** [comment]
One is for dependency version ranges (#3482), the other (#3648) is for the actual package versions :)

**Comment by joelverhagen** [comment]
Clear. Thanks!

**Comment by xavierdecoster** [comment]
This is implicitly fixed by the upgrade to latests `NuGet.Versioning` and the validation fix https://github.com/NuGet/NuGetGallery/issues/3645. No additional work needed, besides testing, which is tracked by functional test issue https://github.com/NuGet/NuGetGallery/issues/3731.
