### ISSUE TITLE
Consider increasing frequency that auxiliary data is generated

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3654]
Today, it is every 24 hours. 

With auxiliary data reload time of 1 hour and index reload of 10 minutes, worst case scenario is a customer waiting 25 hours and 10 minutes to see their own appear on a package (either new package ID or ownership changes).

We should consider increasing the frequency that this data is generated.

**Comment by joelverhagen** [comment]
Related: https://github.com/NuGet/NuGetGallery/issues/3364

This issue tracks increasing the frequency. https://github.com/NuGet/NuGetGallery/issues/3364 tracks handling the case where new IDs should have their own defaulted to the original owner.

**Comment by mishra14** [comment]
Agree, I don't think making user wait for 24+ hours just to see the owner change is fair. Further we don't let the user know that they should expect 24+ hours of delay, it's easy for them to get confused if their change made it through.

**Comment by skofman1** [comment]
@joelverhagen , still relevant?

**Comment by joelverhagen** [comment]
Not relevant. Ownership changes are immediate - 30 minutes depending on job time and come critieria
