### ISSUE TITLE
Package metadata appears in Gallery DB, but package is not in storage

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3661]
Package: https://www.nuget.org/packages/EscolaDeVoce.Services/3.2.0

**Comment by joelverhagen** [comment]
This is easily reproducible locally using the API push endpoint, even with file system store.

**Comment by joelverhagen** [comment]
Code fix is in PR. Open questions:

1. How many packages in PROD were effected?
1. What should be done with effected packages?

**Comment by scottbommarito** [comment]
I confirmed with my validation PowerShell script that the only broken package from this issue is the one you identified.

**Comment by joelverhagen** [comment]
Thanks @scottbommarito!
