### ISSUE TITLE
Support unicode for author names with special characters during publish

### ISSUE THREAD

**Issue by hanssens** [NuGet/NuGetGallery#3663]
It would be great if the website could properly display unicode names, such as mine:

![nuget_gallery___hanssens_net_extensions_2_0_0-beta](https://cloud.githubusercontent.com/assets/493382/23989200/e7c8ec7a-0a31-11e7-95a7-0fa7b492d20e.png)

In my case, `Juliën` has an umlaut. 

I have encountered this automatically not rendering correctly after doing a publish. Both a new package or an update. Although I can change it it on the NuGet.org website, through the package details, it would be awesome if I didn't have to do this manually.

**Comment by skofman1** [comment]
@hanssens , which page are you referring to? 
I'm looking at: https://www.nuget.org/packages/Hanssens.Net.Extensions/

and your name appears correctly: 
![image](https://cloud.githubusercontent.com/assets/16807822/24122900/e4f54a42-0d7a-11e7-942d-e158d60269d4.png)

**Comment by hanssens** [comment]
@skofman1 that is because I manually changed it in the "My Packages".

**Comment by skofman1** [comment]
@hanssens , how are you creating the package? Using nuget.exe? If so, which version?

**Comment by skofman1** [comment]
@hanssens ?
