### ISSUE TITLE
[Validation.Callback.Vcs] Deployment warning in Octopus

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3665]
The warning we get is: The script file "content\Deploy.ps1" contained within the package will not be executed because it is contained within a child folder. As of Octopus Deploy 2.4, scripts in sub folders will not be executed.

Although the service is deployed correctly. 
The root cause is that deploy.ps1 is placed in to places during packaging:
1. root folder
2. content/deploy.ps1

**Comment by scottbommarito** [comment]
I'm pretty sure that the fix for this is to [pack the `nuspec` files directly instead of the `csproj` files](https://github.com/NuGet/NuGet.Jobs/blob/e2ea7a5f05e0c70978c2f1bb5b6562cc08bfce79/build.ps1#L96).

**Comment by agr** [comment]
The easiest fix would be not to reference the file from `.csproj`

**Comment by agr** [comment]
Actually, adding `Deploy.ps1` using `None` node instead of `Content` should keep it in the project (and thus available in VS), but should prevent `nuget.exe` from copying it to the `content` sub-directory inside .nupkg.
