### ISSUE TITLE
Store SemVerLevel for newly pushed/uploaded packages to gallery

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3675]
When new packages are pushed/uploaded to the gallery, we should store the SemVerLevel in the gallery database.

Add new column “SemVerLevelId” of type int, hard-code the value for now, and have the ability to expand with another table later on when needed.

This requires minimal storage, provides optimal speed, and still allows us to be flexible in the event we need to support additional semver-levels.

```sql
ALTER TABLE [dbo].[Packages] ADD [SemVerLevelKey] [int]
```

**Comment by joelverhagen** [comment]
Verified in prod by reflowing existing SemVer 2.0.0 package (semVerA).
