### ISSUE TITLE
NuGetGallery P1 functional test "PackagesPageTest" is flaky

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3676]
It compares the download count on search service with download count on the gallery and assumes they match. This is not necessarily true.

**Comment by skofman1** [comment]
We didn't see any failures with this test since the issue was opened. Closing.

**Comment by chenriksson** [comment]
Reopening - failed again on 8/23, and passed on retry.

https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=39051&_a=summary&view=logs
