### ISSUE TITLE
Create all registration hives (original + gz + SemVer 2.0.0) using lightning

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3683]
This task includes validation.

**Comment by maartenba** [comment]
What is the difference in API for the semverlevel 2 blobs? And what happens to v1 blobs?

**Comment by joelverhagen** [comment]
> What is the difference in API for the semverlevel 2 blobs?

Same shape of JSON. The only difference is that SemVer 2.0.0 versions are included.

> And what happens to v1 blobs?

V1 blobs will still be available both SemVer 2.0.0 compatible and SemVer 2.0.0 incompatible clients.

Today, we have two registration hives:
1. https://api.nuget.org/v3/registration1/
    - All packages.
    - `@type`: `RegistrationsBaseUrl`, `RegistrationsBaseUrl/3.0.0-rc`, etc.
1. https://api.nuget.org/v3/registration1-gz/
    - All packages. Gzipped.
    - `@type`: `RegistrationsBaseUrl/3.4.0`

After the migration, the available hives will be:
1. https://api.nuget.org/v3/registration2/
    - All non-SemVer 2.0.0 packages.
    - `@type`: `RegistrationsBaseUrl`, `RegistrationsBaseUrl/3.0.0-rc`, etc.
1. https://api.nuget.org/v3/registration2-gz/
    - All non-SemVer 2.0.0 packages. Gzipped.
    - `@type`: `RegistrationsBaseUrl/3.4.0`
1. https://api.nuget.org/v3/registration2-gz-semver2/
    - All packages (both SemVer 1.0.0 and SemVer 2.0.0 packages). Gzipped.
    - `@type`: `RegistrationsBaseUrl/Versioned` and `clientVersion` of `4.3.0`.

**Comment by joelverhagen** [comment]
Plan:

(note that this plan includes work tracked by https://github.com/NuGet/NuGetGallery/issues/3684).

**ALL ENVIRONMENTS**

1. Manually run lightning to produce `registration2-*` and `secondary-registration2-*`.
1. Manually run nssm on catalog2registration so we can keep these new hives up to date.
1. Manually run db2lucene to produce `lucene2` and `secondary-lucene2`
1. Manually run nssm on catalog2lucene to build a `lucene2` and `secondary-lucene2`
1. Switch search service to point at `registration2` and `lucene2` instead of `registration1` and `lucene1`.
    - Two deployments are required so both the production and staging slot are not using `lucene1`.
1. Switch index.json to point to the new `registration2` hives.
1. Monitor access of the `registration1` and `lucene1` blob resources to ensure access is limited to the jobs keeping them up to date.

**Comment by joelverhagen** [comment]
Slight change in plan: we should use `"clientVersion": "4.3.0-alpha"` for the SemVer 2.0.0 registration hive so prerelease clients can test integration.

**Comment by joelverhagen** [comment]
The new hives are deployed to PROD and are referenced in search service and v3/index.json. I will close this issue once we have enabled and validated SemVer 2.0.0 package upload.
