### ISSUE TITLE
NuGet.Server returns 404 error 

### ISSUE THREAD

**Issue by rammaram06** [NuGet/NuGetGallery#3687]
I try to build a nuget server using instructions from this link,
[https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server](url)

I used latest version of nuget.server 2.11.3, I was able to build it and push packages to the repo. But when i clicked on the **Click here to view your packages.** I'm getting a "404 - File or directory not found." error. Could you pls let me know If there is any additional steps apart from the steps mentioned in above link. I tried building it in my personal laptop, work laptop but same error. I'm using VS2015 professinal.

**Comment by joelverhagen** [comment]
Could you provide a Fiddler trace of your session? Including both pushing of packages as well as clicking the the "Click here to view your packages" .

Also, how are you starting the server?

Could you provide detailed steps (ideally including File > New Project) of how you reproduce this issue?

**Comment by joelverhagen** [comment]
Please re-open the issue if you are still blocked. I hope to hear from you so we can resolve this issue!

**Comment by dumians** [comment]
that it is still happend also on update old nuget server packages
