### ISSUE TITLE
Retire WebMatrix-specific curated-feed

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3696]
The gallery still hosts a curated feed specific to WebMatrix.
URL: https://www.nuget.org/api/v2/curated-feed/webmatrix

**Do we still need it now that WebMatrix is nearing EOL?**
[Formal support ends on November 1st, 2017](https://blogs.iis.net/webmatrix/webmatrix-product-support-ends-on-november-1st-2017).

I'd propose to also work out a retirement plan for this particular curated-feed on nuget.org, and remove it from the gallery when EOL.

The reason for the curated-feed can be found in the [`WebMatrixPackageCurator.ShouldCuratePackage`](https://github.com/NuGet/NuGetGallery/blob/27869a9f2bd453d87c061b2ad491314d9f273eea/src/NuGetGallery/PackageCurators/WebMatrixPackageCurator.cs#L44) method (mostly because of no PowerShell or T4 support in WebMatrix client).

Would be good to remove this code and relieve nuget.org of this duty :)

**Comment by karann-msft** [comment]
@xavierdecoster do we have telemetry on the usage of this feed?

**Comment by anangaur** [comment]
Is there any other existing curated feed? May be time to retire all of them :)

**Comment by xavierdecoster** [comment]
@karann-msft you should be able to get those from AppInsights by checking request telemetry containing `api/v2/curated-feeds/` in the url

@anangaur the list of curated feeds is stored in the gallery database. I remember there being a `windows8` curated feed, and likely some others.

**Comment by xavierdecoster** [comment]
List of curated feeds:
* windows8-packages
* webmatrix
* dotnetframework
* microsoftdotnet

**Comment by joelverhagen** [comment]
This is already done as a part of another work item.
