### ISSUE TITLE
Support IsLatest and IsAbsoluteLatest with respect to SemVer 2.0.0 in gallery DB

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3708]

**Comment by joelverhagen** [comment]
@xavierdecoster, there seems to still be a bug here:
https://dev.nugettest.org/api/v2/FindPackagesById()?id=%27jver.semver2.package.dots%27&semVerLevel=2.0.0

```xml
  <d:Id>jver.semver2.package.dots</d:Id>
  <d:Version>1.0.0-a.1</d:Version>
  ...
  <d:IsLatestVersion m:type="Edm.Boolean">false</d:IsLatestVersion>
  <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">false</d:IsAbsoluteLatestVersion>
```

This should have "is absolute latest" as true.

Available versions: https://dev.nugettest.org/packages/jver.semver2.package.dots

**Comment by joelverhagen** [comment]
DB result is wrong too:
https://dev.nugettest.org/api/v2/Packages()?$filter=Id%20eq%20%27jver.semver2.package.dots%27%20and%201%20eq%201&semVerLevel=2.0.0

**Comment by xavierdecoster** [comment]
Can you retry the scenario with a brand new package registration? The data issue may be separate and self-inflicted due to EF migration rollback earlier this week.

**Comment by xavierdecoster** [comment]
Or push a new version first to fix the database.
