### ISSUE TITLE
Can't create database with SQL Express 2014

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3713]
NuGetGallery's web.config refers local db as:

    Data Source=(localdb)\v11.0

which does not work with SQL Express 2014 (running `Update-Database` produces "Login failed for user zzz") and needs to be updated to:

    Data Source=(localdb)\mssqllocaldb

(both instances in file). Without the change it fails to connect. Updating the file though will likely break the compatibility with SQL Express 2012.

**Comment by skofman1** [comment]
Does SQL Express 2014 bundled in VS 2015? 
If so, please send a PR, and lets update the web.config.

**Comment by dtivel** [comment]
#3027.  @scottbommarito
