### ISSUE TITLE
Feed2Catalog doesn't appear to block if package download fails.

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3721]
Per Application Insights trace logs the Feed2Catalog job was failing consistently on a nonexistent package.

    Unable to download: http://int.nugettest.org/api/v2/package/DuplicatePushesAreRejectedAndNotDeleted.636263222102712356/1.0.0. Http status: NotFound

This was a test package created by a [functional test](https://github.com/NuGet/NuGetGallery/pull/3706/files#diff-69bb66e7a5bbce2aa8f3c4b9f832ec22R31).  The package did not exist intentionally.

However, the rest of the pipeline appeared to ignore this failure and continue.

**Comment by skofman1** [comment]
This is a desired behavior.
