### ISSUE TITLE
Front page V3 feed compatibility should mention NuGet 4.x/VS 2017

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3729]
https://www.nuget.org/

![image](https://cloud.githubusercontent.com/assets/94054/24520559/c39fe92c-153d-11e7-9e4c-fd79f68bb398.png)

**Comment by skofman1** [comment]
@anangaur , can you please fix?

**Comment by anangaur** [comment]
It should _say_ 

NuGet feed v3 (VS 2015 _and later_ / NuGet v3.x _and above_): https://api.nuget.org/v3/index.json

**Comment by anangaur** [comment]
We should also add the release details of 4.1 once we make 4.1 as default nuget.exe (i.e. its ReleasedAndBlessed). 
![image](https://cloud.githubusercontent.com/assets/14800916/25715328/042e8c9a-30b0-11e7-8b9d-d18711cbeaff.png)
