### ISSUE TITLE
SemVer 2.0.0 test plan

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3731]
This is a summary work item. The intention here that these are manual validations done to increase confidence in SemVer 2.0.0 work. The validations should be done against INT.

# Manual tests

## Client-ish

1. [ ] Search and browse in VS UI for SemVer 2.0.0 packages
1. [ ] Update and install SemVer 2.0.0 packages in VS UI

## Server-ish

1. [ ] Make sure download counts go up on a package with just SemVer 2.0.0 versions
1. [ ] Make sure download counts go up on a package with a mix of SemVer 1.0.0/2.0.0
1. [ ] Interactive upload should reject upload of version with build metadata in dependency range
1. [ ] Delete and edit in gallery
    1. [ ] SemVer 2.0.0 due to build metadata, e.g. `1.0.0+git`
    1. [ ] SemVer 2.0.0 due to dots in prerelease, e.g. `1.0.0-alpha.1`

# Automated tests

(covered by https://github.com/NuGet/NuGetGallery/issues/3762 and child items)

**Comment by xavierdecoster** [comment]
Specific tests for 2.x clients: 

* [ ] Verify package versions containing a `.` in the prerelease label don't flow through to these clients
