### ISSUE TITLE
Catalog entries can get skipped by catalog2registration when there are transient failures

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3733]
From PR https://github.com/NuGet/NuGet.Services.Metadata/pull/150:

> Suppose you have a page with:
> ```
> ID   Version   Commit Timestamp
> --   -------   ----------------
> B    1.0.0     10:00 PM
> A    1.0.0     10:00 PM
> A    1.0.1     10:05 PM
> ```
> 
> Also suppose you have the cursor set to 9:55 PM. This means all of the items in the page need to be processed. You will have two batches processed by `RegistrationCollector`:
> 
> ```
> Batch 1: B 1.0.0
>  - Commit Timestamp: 10:00 PM
> 
> Batch 2: A 1.0.0, A 1.0.1
>  - Commit Timestamp: 10:00 PM
> ```
> 
> Suppose batch 1 is processed successfully. The [`CommitCollector` will update the cursor](https://github.com/NuGet/NuGet.Services.Metadata/blob/cb1e7afa4d345a8a6d46ff3edd874bd8a7579e8f/src/Catalog/CommitCollector.cs#L60) to 10:00 PM (the commit timestamp of batch 1) then start processing batch 2.
> 
> Now suppose the processing of batch 2 fails such that neither A 1.0.0 nor A 1.0.1 are completed.
> 
> The job will crash due to the failure then start up again. Since the cursor is now at 10:00 PM, the set of items in the page considered will be:
> 
> ```
> ID   Version   Commit Timestamp
> --   -------   ----------------
> A    1.0.1     10:05 PM
> ```
> 
> This means A 1.0.0 is skipped. Remember that the cursor means "everything strictly after this timestamp needs to be processed".

**Comment by skofman1** [comment]
reopen for tracking
