### ISSUE TITLE
Cannot send email using the 465 smtp port

### ISSUE THREAD

**Issue by edwardmeng** [NuGet/NuGetGallery#3734]
According to the document of microsoft, the System.Net.Mail cannot send email message through 465 port(https://blogs.msdn.microsoft.com/webdav_101/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465/).
But we want to use the tencent exmail account which have to use 465 port, so the mail sender component should be replaced another third part solution instead of System.Net.Mail.

**Comment by skofman1** [comment]
@edwardmeng , can you please provide more details? What is the error you are seeing? 

From what I see here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/538ac4b8-23a3-4367-8e73-c2b1573dc80d/send-email-smtp-465?forum=csharpgeneral

It should be possible to configure System.Net.Mail with port 465.

**Comment by edwardmeng** [comment]
The email setting in web.config as following:
`<add key="Gallery.SmtpUri" value="smtps://myaccount:password@smtp.gaiaworks.cn:465" />`
And debugged in source code, it can be parsed correctly. But there are lots of error log message in ELMAH, which said "System.Net.Mail.SmtpException: The operation has timed out."
There is the same issue in [exceptionless](https://github.com/exceptionless/Exceptionless/issues/290) that I have reported, and then I have submitted a pull request to replace the implementation of mail sender with MailKit. It works correctly, and I can receive the email message now.
If possible, I can try to fix it and submit a pull request too.

**Comment by edwardmeng** [comment]
#https://github.com/NuGet/NuGetGallery/issues/3734

**Comment by edwardmeng** [comment]
https://github.com/NuGet/NuGetGallery/issues/3734

**Comment by edwardmeng** [comment]
exceptionless/Exceptionless##290

**Comment by edwardmeng** [comment]
#exceptionless/Exceptionless#290

**Comment by edwardmeng** [comment]
exceptionless/Exceptionless#290

**Comment by edwardmeng** [comment]
@skofman1 , in the post you provded, the implicit SSL can be implemented with System.Web.Mail which has been obsoleted. And there is a reply redirected to stackoverflow http://stackoverflow.com/questions/1011245/how-can-i-send-emails-through-ssl-smtp-with-the-net-framework
Which means, it can only be implemented with third part solution, such as MailKit, Aegis Implicit Mail, Stunnel.

**Comment by skofman1** [comment]
@edwardmeng , I checked internally, and unfortunately MailKit isn't approved by Microsoft to be used in our products, and requires a review process. The team is working on multiple features, and we don't have the capacity to initiate this process now.
My recommendation is to branch our code, and perform any changes you require.

**Comment by andrew-lenvi** [comment]
Microsoft now officially recommends that we use MailKit for new development work:  
https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-7.0#remarks

**Comment by joelverhagen** [comment]
If you'd like to use MailKit or another external emailing service, I recommend changing NuGetGallery to have asynchronous email sending enabled:
https://github.com/NuGet/NuGetGallery/blob/a4b3c64acb65ca68eb67ac6b51242356aa5e4da7/src/NuGetGallery/Web.config#L131

This uses two other settings to publish a Service Bus message per sent email:
https://github.com/NuGet/NuGetGallery/blob/a4b3c64acb65ca68eb67ac6b51242356aa5e4da7/src/NuGetGallery/Web.config#L57-L58

You will need to write your own background job to consume the Service Bus messages and submit to MailKit. This is generally what nuget.org does in production, but the consumer of the Service Bus topic is closed source code since it integrates with an internal Microsoft email service.
