### ISSUE TITLE
Mark semVerLevelKey=2 for packages on NuGet.org that are already SemVer 2.0.0

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3737]
These break old clients. Once the [`SemVerLevelKey` migration](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Migrations/201703221228170_AddSemVerLevelKeyColumn.cs) has been run in production, we should perform a data fix on these packages.

## SemVer 2.0.0 package versions

ID                           | Normalized Version        | Value
---------------------------- | ------------------------- | -----
prototest                    | 1.2.0                     | 1.2.0+git.unspecified
protobuild                   | 16.1119.5842              | 16.1119.5842+git.unspecified
protobuild.testinstall       | 16.1120.60313             | 16.1120.60313+git.unspecified
semvera                      | 1.0.0                     | 1.0.0+metadata
astarpathfinder              | 1.0.0                     | 1.0.0+git.unspecified
protobuild                   | 16.1119.145207            | 16.1119.145207+git.unspecified
protogame                    | 6.0.1                     | 6.0.1+git.unspecified
protobuild                   | 16.1117.224729            | 16.1117.224729+git.unspecified
ndesk.options.redpoint       | 0.2.1                     | 0.2.1+git.unspecified
ffmpeg.nuget                 | 1.0.0                     | 1.0.0+git.unspecified
protogame                    | 6.0.0                     | 6.0.0+git.unspecified
protobuild                   | 16.1119.13506             | 16.1119.13506+git.unspecified
prototest                    | 1.1.0                     | 1.1.0+git.unspecified
protoinject                  | 1.0.0                     | 1.0.0+git.unspecified
prototest                    | 1.1.3                     | 1.1.3+git.unspecified
semvernumeric                | 1.0.0                     | 1.0.0+-

## SemVer 2.0.0 version range minimums

ID                           | Normalized Version        | Value
---------------------------- | ------------------------- | -----
snowflake.framework          | 0.2.0-pre-alpha-build1038 | 0.2.0-pre-alpha.1038
snowflake.framework.utility  | 0.2.0-pre-alpha-build1038 | 0.2.0-pre-alpha.1038
snowflake.framework.services | 0.2.0-pre-alpha-build1038 | 0.2.0-pre-alpha.1038

## SemVer 2.0.0 version range maximums

(none)

**Comment by joelverhagen** [comment]
These packages should also be reflowed once update **feed2catalog**, **catalog2registration**, **catalog2dnx**, and **catalog2lucene** have been deployed.

**Comment by joelverhagen** [comment]
It looks like API push did not block SemVer 2.0.0 until: https://github.com/NuGet/NuGetGallery/commit/0b7007b8b08dc6f7b781be0e0438ce10d448d719

Which was deployed on March 1st, I think.

**Comment by xavierdecoster** [comment]
This requires the db schema change (part of deployment https://github.com/NuGet/NuGetGallery/issues/3718) to be in place first.
