### ISSUE TITLE
Get rid of registration0 job

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3744]
Search service should point to the same registration base URL as index.json. Today registration1 and registration0 are both in the same storage account so it does not provide anything to the disaster recovery story,

index.json points to:
- https://api.nuget.org/v3/registration1/
- https://api.nuget.org/v3/registration1-gz/

search services points to:
- https://api.nuget.org/v3/registration0/

**Comment by joelverhagen** [comment]
1. Wait for https://github.com/NuGet/NuGetGallery/issues/3748 to be completed.
1. Verify blob access for registration0 is limited to the catalog2registration job.
    - Note that callers may have hard-coded registration0. We should wait 3 days after all links to it are removed before moving on.
1. Stop the catalog2registration job for registration0 on the prod VM.
1. Disable deployment of catalog2registration job for registration0.
1. Stop catalog2registration job for registration0 on the prod VM.
1. Remove the job cmd file from NuGet.Services.Metadata for this job.
1. Remove the unused configuration from Octopus.

**Comment by scottbommarito** [comment]
How will callers of registration0 know that the container has been deprecated? It could be very confusing for those who have hardcoded it if they start finding discrepancies between what they see in registration and what exists on nuget.org.

Do we want to consider putting a redirect on the CDN to a "registration0 has been deprecated" page? Do we want it to redirect to registration1?

**Comment by skofman1** [comment]
Do we have the same situation on dev&int?

**Comment by joelverhagen** [comment]
@scottbommarito:

> How will callers of registration0 know that the container has been deprecated? It could be very confusing for those who have hardcoded it if they start finding discrepancies between what they see in registration and what exists on nuget.org.

This is breaking contract. `v3/index.json` is the source of truth on registration base URLs. That being said our client does cache the index.json for 40 minutes. We will wait 3 days for callers to pick up on the new index.json. If someone hard-coded the registration0 location, they will encounter stale data after we stop the registration0 job and encounter 404's when we remove registration0 (not planned).

> Do we want to consider putting a redirect on the CDN to a "registration0 has been deprecated" page? Do we want it to redirect to registration1?

I don't think this is worth the effort. Clients should be following index.json. We can re-evaluate this if we observe a high level of traffic on registration0 after we switch the search service over.

@skofman1:

> Do we have the same situation on dev&int?

Yes. We will prove the process there first.

**Comment by joelverhagen** [comment]
Access to `registration0` on PROD is limited to jobs and around external 6735 hits over a course of 24 hours (May 1, 2017, UTC). `registration1` have over 16,000,000 hits over the same 24 hours.

The set of external hits to `registration0` have the following characteristics:

1. None have the NuGet client user agent.
1. 6730 have user agents that suggest 3rd party scripting:
    1. 3397 - no user agent
    1. 3261 - `python-requests`
    1. 82 - `RestSharp`
1. The 5 hits are browser or bingbot hits.
1. There are only 8 distinct IPs with pattern `X.X.X.0`, suggesting a low number of organizations involved.

For this reason, I think we can safely deprecate `registration0`. That is, we can stop updating it with new packages.

**Comment by skofman1** [comment]
Agreed.

**Comment by joelverhagen** [comment]
I have disabled the `registration0` job. The remaining work is:

- [ ] Remove the registration0 service from the PROD jobs machine.
- [ ] Remove the job cmd file from NuGet.Services.Metadata for this job.
- [ ] Remove the unused configuration from Octopus.
