### ISSUE TITLE
Move as much configuration as possible from Octopus to VSTS

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3747]
Today, Search Service and Gallery store some configuration in VSTS and some in Octopus.

We should align on VSTS since this provides easy versioning and, most importantly, a flow for code review.

We should also move jobs to have a NuGetDeployment build as well (like Search and Gallery already have).

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #367](https://github.com/NuGet/Engineering/issues/367) via [**ZenHub**](https://www.zenhub.com/)
