### ISSUE TITLE
absoluteLatest endpoint on view needs to be updated

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3751]
When we enable the semver2 is latest column, the call to FindAbsoluateLatestPackageById will need to be updated to check the semver2 islatest column. See [this commit](https://github.com/NuGet/NuGetGallery/commit/2c584e72c96ed230155ee9c5fcb4ab88209b8cd2#diff-124d0e9b5a728caf5579132427fb26a0R174) for more context.

**Comment by joelverhagen** [comment]
https://dev.nugettest.org/packages/jver.semver2.package.dots/absoluteLatest
