### ISSUE TITLE
Nuget takes highest prelease

### ISSUE THREAD

**Issue by v703612** [NuGet/NuGetGallery#3760]
Hello,

We are currently doing some testing of nuget to use nuget command line in our deploy system. We would like to use the latest version of nuget but there we encountered that when you are having prereleases that it is always taking the lowest(first) prerelease and we would need the latest prerelease. Is this possible?

kr,

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #4999](https://github.com/NuGet/Home/issues/4999) via [**ZenHub**](https://www.zenhub.com/)
