### ISSUE TITLE
[SR-1150] show the latest version in the table that lists your packages

### ISSUE THREAD

**Issue by alpaix** [NuGet/NuGetGallery#3765]
> Created by anavarro9731 on 2017-04-04T12:44:04.66.

> Please show the latest version in the table that lists your packages, and ideally find a way to show the whole package name. It is really annoying when you have a bunch of packages that start with the same text and you have to hover each one to find the right one.

**Comment by skofman1** [comment]
@anavarro9731 , can please attach a screenshot?

**Comment by anavarro9731** [comment]
![ambiguousnugetpkgname](https://cloud.githubusercontent.com/assets/549572/25155881/55297e3e-248f-11e7-90c2-0033a0bcc6ce.PNG)

sure.

**Comment by skofman1** [comment]
@jonwchu

**Comment by xavierdecoster** [comment]
`Latest Version` is now shown on today's `Manage Packages` view, and the `Package` and `Package ID` columns in the old screenshot above have merged so there is a bit more room for longer package id's. However, we still truncate at some point, which I believe is hard to avoid in the current design. Hovering the `Package ID` reveals the URL though, and the column is now sorted alphabetically.

@skofman1

**Comment by xavierdecoster** [comment]
Closing this issue as per the issue title, the latest version is shown on this view now.
There's another issue tracking refactoring the Manage Packages view: https://github.com/NuGet/NuGetGallery/issues/5616
