### ISSUE TITLE
Gallery UI redesign - design & plan

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3782]

**Comment by joelverhagen** [comment]
Closed since this issue is now broken into more granular issues.
https://github.com/NuGet/NuGetGallery/issues/3926
https://github.com/NuGet/NuGetGallery/issues/3927
https://github.com/NuGet/NuGetGallery/issues/3928
https://github.com/NuGet/NuGetGallery/issues/3929
