### ISSUE TITLE
Idea: "Manage My Package" Package Table Alignment

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#3783]
I'm just playing with an idea, because I noticed that the "Manage My Package" site looks a bit unstructure, because each table might have a different size (depending on the actual content).

This is the actual site now:

![image](https://cloud.githubusercontent.com/assets/756703/25022883/f3d4150e-2097-11e7-99d8-b7a5b9822330.png)

And with "width: 100%" for the table and some text-align: left for the "last" column it could look like this:

![image](https://cloud.githubusercontent.com/assets/756703/25022875/ead9c9b2-2097-11e7-91f4-2312b25e19fb.png)

I just changes it in the browser but I'm pretty sure those changes could be made in a very "careful" way, so that the only affected site is the "my package" site. 

What do you think?

**Comment by robertmuehsig** [comment]
(the large download number is a fake - I just needed a larger number to see how it will fit in the layout)

**Comment by robertmuehsig** [comment]
The package detail page wouldn't look bad with the 100% change - if this is something you are interested I would see where this "sexy-table" is used 

![image](https://cloud.githubusercontent.com/assets/756703/25023162/13f2df68-2099-11e7-915e-02b9f8622304.png)

**Comment by skofman1** [comment]
Thanks for the great idea @robertmuehsig! Change to "Manage My Package" is welcome, and looks great. Regarding package details page, we will be rebuilding it in one of the upcoming sprints, so no need to invest work there :)
