### ISSUE TITLE
 unable to install "DevExpress.Mvvm.v16.2" in wpf application ehich have framework4.5

### ISSUE THREAD

**Issue by yogeshgautam1** [NuGet/NuGetGallery#3784]
PM> Install-Package DevExpress.Mvvm.v16.2
Installing 'DevExpress.Mvvm.v16.2 1.2.0'.
Successfully installed 'DevExpress.Mvvm.v16.2 1.2.0'.
Adding 'DevExpress.Mvvm.v16.2 1.2.0' to Magicube.
Uninstalling 'DevExpress.Mvvm.v16.2 1.2.0'.
Successfully uninstalled 'DevExpress.Mvvm.v16.2 1.2.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'DevExpress.Mvvm.v16.2 1.2.0'. You are trying to install this package into a pr
oject that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  DevExpress.Mvvm.v16.2
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by skofman1** [comment]
@yogeshgautam1 , the package support only net461 and above:
![image](https://cloud.githubusercontent.com/assets/16807822/25363076/018eee08-290d-11e7-9b15-21a2210949b7.png)

**Comment by yogeshgautam1** [comment]
Yes.you are right. I got it earlier,
