### ISSUE TITLE
Error querying NuGet.org V2 API (Search endpoint)

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3790]
In our NuGet client, we are querying the NuGet.org V2 API. For a specific request, the server seems to load a while, then returns "An error has occurred."

Repro steps:
* Hit [https://www.nuget.org/api/v2/Search()?searchTerm=%27newtonsoft.json%27&includePrerelease=true&$filter=IsLatestVersion%20or%20IsPrerelease&$orderby=Id&$top=27&$skip=0](https://www.nuget.org/api/v2/Search()?searchTerm=%27newtonsoft.json%27&includePrerelease=true&$filter=IsLatestVersion%20or%20IsPrerelease&$orderby=Id&$top=27&$skip=0)
* Witness slow load
* Witness `<m:message xml:lang="en-US">An error has occurred.</m:message>`

This used to work fine in the past, please advice.

**Comment by maartenba** [comment]
Any news on this one? Really annoying some of our users :-)

**Comment by cristinamanum** [comment]
Fix deployed in dev.

**Comment by skofman1** [comment]
This will be deployed to prod Wednesday next week
