### ISSUE TITLE
Inconsistencies between package listings on nuget.org and VS package manager UI result in confusing package identity

### ISSUE THREAD

**Issue by diverdan92** [NuGet/NuGetGallery#3791]
In nuget.org, the package name is listed in search:
![image](https://cloud.githubusercontent.com/assets/6608201/25094130/91b99514-234a-11e7-9e08-a10a737d3fae.png)

In Visual Studio, the package ID is listed in search:
![image](https://cloud.githubusercontent.com/assets/6608201/25094121/822e939c-234a-11e7-844d-6a3b8be7a42e.png)

When quickly glancing at/searching for packages, the inconsistencies may make you second guess the package you are consuming. In nuget.org, you have to view the package details to view the real package ID. 

Many packages have a 1:1 correlation, but for packages that do not, this can result in unnecessary confusion.

**Comment by anangaur** [comment]
This is now implemented and live on NuGet.org
