### ISSUE TITLE
report abuse form changes

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#3792]
1.	Request form changes – change the dropdown option to say The package violates a Copyright I own instead of License. 
2.	At the bottom of this form, add the line “You can also send us an email at admin@nuget.org"
3.	Required Statements should only show up when the  "The package violates a Copyright I own" option is selected

**Comment by skofman1** [comment]
Posting the e-mail publicly will allow spammers to use it..

**Comment by anangaur** [comment]
As per discussion with legal, this seems to be a requirement for DMCA requirements.
