### ISSUE TITLE
Search Service 404's make search AI noisy.

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3793]
request to the search service that 404 should not be logged as failed requests.

**Comment by loic-sharma** [comment]
This will be done in three steps:

- [ ] [Add changes to the common repository](https://github.com/NuGet/ServerCommon/pull/43)
- [ ] Update Gallery to use new AI processor
- [ ] Add processor to Search Service

**Comment by skofman1** [comment]
I still see some 404s in the search service marked as failed requests. Was this item completed?
