### ISSUE TITLE
How I can host API v3?

### ISSUE THREAD

**Issue by grzegorz-ogrodowski** [NuGet/NuGetGallery#3800]
Hi,

I've installed this repo on my IIS, but this is API V2.
How I can host V3?

Cheers,

**Comment by skofman1** [comment]
Hi @grzegorz-ogrodowski ,

V3 protocol is based on client/server communication using json. On NuGet.org, this protocol is implemented using static blobs, which allows us to provide a scalable and reliable service. 
The Gallery web service is not accessed at any point in the communication between client and server using V3 protocol, hence it's not enough to deploy the Gallery to support V3. 
V3 protocol has not been official documented at this point in time, and doesn't provide any additional functionality on top of V2 protocol. 
That said, if you are still interested in hosting V3, we have a pipeline of jobs that reads from the Gallery and creates a V3 index. The code is open source, and I can point you to it.
