### ISSUE TITLE
In the JSON response from api.nuget.org, "upper" version info property SHOULD NOT include the version of unlisted package, or not?

### ISSUE THREAD

**Issue by jsakamoto** [NuGet/NuGetGallery#3802]
### What you were trying to do.

Update the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" from version v.10.0.14393.1 to latest version.

### What you expected to happen.

The version of the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" update to v.10.0.15063.0.

### What actually happened.

The version of the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" updated to v.10.1.14393.0.

That version is unlisted package version.  
See also: https://www.nuget.org/packages/Selenium.WebDriver.MicrosoftWebDriver/10.1.14393

### Steps to reproduce the problem.

1. Create or open any .NET project with Visual Studio 2017. 
2. Execute "Install-Package Selenium.WebDriver.MicrosoftWebDriver" command at Package Manager Console. 
3. After it, the correct latest version "10.0.15063" was installed. (This is correct behavior) 
4. Next step, execute "Update-Package Selenium.WebDriver.MicrosoftWebDriver" command. 
5. Then, the command update the package to UNLISTED version "10.1.14393" !

### Appendix Information

I guess, this problem happens due to the JSON response from api.nuget.org.

The JSON reponse contains "upper" proprty, but it looks like include unlisted package versions.

![image](https://cloud.githubusercontent.com/assets/95908/25183534/d08fa9a4-2552-11e7-8f4e-204207486981.png)

Is it by design and it should not change? or should fix it?

**Comment by skofman1** [comment]
@joelverhagen , @emgarten , is this a client or server issue?

**Comment by emgarten** [comment]
Looks like a client issue if the unlisted package is being installed. The upper and lower bounds are correct.

**Comment by joelverhagen** [comment]
I confirmed this behavior in NuGet 4.2.0.2451 with a packages.config project. A PackageReference project does not reproduce the problem. The issue occurs for both V2 and V3 NuGet.org source URL.

As @emgarten, this seems to be a client issue.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #5069](https://github.com/NuGet/Home/issues/5069) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsakamoto** [comment]
Thank you for reply, all.

> The upper and lower bounds are correct.

OK, I understand, I agree.

I reported this issue to Visual Studio Developer Community: https://developercommunity.visualstudio.com/content/problem/46121/update-package-command-at-package-manager-console.html

Thanks.
