### ISSUE TITLE
Package Download Count isn't incrementing in self-host NuGetGallery

### ISSUE THREAD

**Issue by zmingxie** [NuGet/NuGetGallery#3803]
Hi there,

I have NuGetGallery (v2017.03.22) setup locally. For some reasons, the package download count is not incrementing. I've confirmed the package was pulled from my local Nuget feed instead of Nuget.org.

Could you advise where I can investigate further?

**Comment by joelverhagen** [comment]
The easiest way to enable this is by using the `TrackPackageDownloadCountInLocalDatabase` feature. By default this is disabled, meaning download counts will not be incremented.

If you go into the NuGetGallery web.config file, search for the following line:
```
    <add key="Feature.TrackPackageDownloadCountInLocalDatabase" value="false" />
```

Change that `false` to `true` and you should be good to go. When the user downloads the package (either in the browser or using a NuGet client) the download count will be incremented. You can easily test it using the download link on the package page:
![image](https://cloud.githubusercontent.com/assets/94054/25247908/2592fac8-25c1-11e7-907a-b509953bc42b.png)

Please note that this feature is not used on NuGet.org. We rely on a background job analyzing CDN logs to determine the download count.

**Comment by scottbommarito** [comment]
@joelverhagen Do you think it would make more sense if `Feature.TrackPackageDownloadCountInLocalDatabase` defaulted to `true`? Most users are not going to be running a statistics pipeline.

**Comment by joelverhagen** [comment]
@scottbommarito, I think we should keep default behavior of NuGetGallery to be as close to nuget.org as possible. This feature would not work at all on NuGet.org or on any package source that also supports V3 protocol. People should have to think about the correctness of generating stats this way before opting in.

**Comment by zmingxie** [comment]
Thanks for the info.

Closing this ticket now.
