### ISSUE TITLE
Suggestion: add bookmarks/favorites on the nuget.org

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/NuGetGallery#3808]
It'd very helpful if people could bookmark packages on nuget.org site. 
Like we could do on https://www.npmjs.com/ for example.

**Comment by robertmuehsig** [comment]
I guess this issue is more or less the same as this (very) old one https://github.com/NuGet/NuGetGallery/issues/440

**Comment by evil-shrike** [comment]
yeah, exactly, I was searching for "favorite" not "favourite" :(

**Comment by skofman1** [comment]
Thanks for the feedback @evil-shrike . Closing this issue as duplicate of: https://github.com/NuGet/NuGetGallery/issues/440
