### ISSUE TITLE
Ambiguous or Erroneous Instructions

### ISSUE THREAD

**Issue by brentarias** [NuGet/NuGetGallery#3809]
In the article "[Installing and reinstalling packages with package restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)" it has a heading "Allow NuGet to download missing packages" where it ambiguously explains that for package restore, enabled=disabled.  That is, to enable package restore - it must be disabled.  It gives the following nuget.config XML to clarify:

    <configuration>
        <packageRestore>
          
        <add key="enabled" value="False" />
        </packageRestore>
    </configuration>

This leaves me wondering if there is simply an error in the document.  If not, perhaps it should explicitly say something like "this disables the pre-nuget v2.7 behavior, and thereby activates the post-nuget v2.7 restore behavior."  As is, I can't tell if the article is advocating for the option being set to "enabled=true" or "enabled=false."

This exact same problem occurs in the next heading as well entitled "Automatically check for missing packages during build in Visual Studio."  In this case the article is stating that true==false.  Note the XML sample it gives:

    <configuration>
        <packageRestore>
        
        <add key="automatic" value="False" />
        </packageRestore>
    </configuration>

Is the article suggesting I should change this from setting from "False" to "True", or is it suggesting that by disabling the automatic check...I am actually enabling it?

**Comment by anangaur** [comment]
Thanks @brentarias for pointing this out. We will fix this to make it clear and unambiguous. @karann-msft can you take a look.

**Comment by kraigb** [comment]
@brentarias This is updated; see https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#enabling-and-disabling-package-restore.

**Comment by karann-msft** [comment]
Closing the issue since this has been fixed.
