### ISSUE TITLE
error occurred in visual studio 2015 nuget package manager.

### ISSUE THREAD

**Issue by yunlang** [NuGet/NuGetGallery#3810]
I downloaded the nuget source, registered it as a website, and started working.
I have tried to run Nuget Package Manager to search for it in Visual Studio 2015, but I have not been able to search it and I have encountered an error. There is only a warning phrase.
There is no way to find out where it is not.
How do I fix it?

**Comment by yunlang** [comment]
just only "error occurred"

**Comment by skofman1** [comment]
@yunlang , can you please provide more details:
1. Are you running NuGet Gallery or NuGet.Server
2. What's the feed you provided to VS?
3. Are you able to access your website and use it without VS?

**Comment by yunlang** [comment]
1. Yes
2. install-package : An error occurred while retrieving package metadata for '{we dll}' from source '{we dll name}'.

+ install-package {we dll name}
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
3. Yes

**Comment by yunlang** [comment]
1. Yes
2. The V2 feed at 'https://{we URL}/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net452'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '404 Not Found'.
3. Yes

**Comment by yunlang** [comment]
Resolved this issue.

**Comment by Bloodcoder** [comment]
@yunlang , @skofman1 , 
How was this resolved?

**Comment by yunlang** [comment]
@Bloodcoder 
I just modified the format of the string (XML) that connects Nugget correctly.
