### ISSUE TITLE
[Search] Improve sampling configuration for AI 

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#3817]
The sampling logic that AI is using for the search service appears to be throttling and dropping events that should otherwise be reported.

**Comment by skofman1** [comment]
We would like to continue sampling requests. Shouldn't sample traces, exceptions. Traces currently log every request. This is redundant. Should be removed.

**Comment by loic-sharma** [comment]
Pull request [here](https://github.com/NuGet/NuGet.Services.Metadata/pull/183).
