### ISSUE TITLE
Harden JSON parsing logic when calling external search service

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3826]
If for some reason the external search service returns malformed JSON, the gallery should fallback to the database if possible.

Related to https://github.com/NuGet/NuGetGallery/issues/3825

**Comment by shishirx34** [comment]
The JSON malformed issue has been fixed in search service to not return such data and gallery is monitored by ELMAH error monitoring, we shouldn't get any malformed data from search service. Closing this issue in favor of seeing a real case scenario that warrants this fix.
