### ISSUE TITLE
Investigate how it is possible that search service returned search results missing the Version property

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3827]
The search service should shield consumers from missing data in the Lucene index.

Related to #3826 and #3825

**Comment by joelverhagen** [comment]
Was really curious about this so I looked at the two Lucene indexes. I think there is a bug in `db2lucene` where the `OriginalVersion` is not set in the generated documents.

Query: `*:* -OriginalVersion:[* TO *]` (find all documents with no `OriginalVersion` property).

v3-lucene1-v2v3-20170110: 1 result, which is a non-package document
v3-lucene1-v2v3-20170425: 1,075,425 results

**Comment by joelverhagen** [comment]
Looks like we need better test coverage in `db2lucene`. Also, search service should blow up if it doesn't see the required properties.

**Comment by scottbommarito** [comment]
This has been fixed with @ryuyu's and is now successfully deployed with today's index rebuild.
