### ISSUE TITLE
Link to "master" in the footer points to a 410 page on GitHub

### ISSUE THREAD

**Issue by aevitas** [NuGet/NuGetGallery#3828]
When clicking the link to `master` in the page footer, one would expect the link to point to the master branch of this repository. However, it points to https://github.com/NuGet/NuGetGallery/branches/master

Which appears to be retired by GitHub. As far as I can tell, the repository URI is obtained from the AssemblyInfo, which is declared:

`[assembly: AssemblyMetadata("RepositoryUrl", "https://www.github.com/NuGet/NuGetGallery")]`

This now also represents the URI to the master branch of the repository, as selecting "master" on the [branches page for the repository](https://github.com/NuGet/NuGetGallery/branches) points to the same resource as the `RepositoryUrl` specified in the metadata.

Fixing this should be trivial, it appears that the "branches/{branch}" combination [in ApplicationVersion line 51](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Infrastructure/ApplicationVersionHelper.cs#L51) should simply be changed to

`BranchUri = repositoryBase;`

For the link in the footer to be working properly again.

I'd be happy to provide the above change in a PR if this is even deemed an issue.

**Comment by skofman1** [comment]
@aevitas , thanks for letting us know!
Seems like the fix in the line you provided (https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Infrastructure/ApplicationVersionHelper.cs#L51)
should be to change from "branches" to "tree": https://github.com/NuGet/NuGetGallery/tree/master

A PR will be most welcome 👍
