### ISSUE TITLE
Register account form have weird tab order

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3837]
The Register form on the [Log on](https://www.nuget.org/users/account/LogOn) page have weird tab order:
When you place a cursor into Username field and press Tab, cursor moves to the Password field as expected, then if you press tab again it moves *somewhere*, and after that, pressing tab one more time cursor gets to the Email field. 
Email field should be one Tab away from password, not two.

**Comment by skofman1** [comment]
We have a long list of accessibility issue to tackle next sprint. Closing for now as duplicate.
