### ISSUE TITLE
Strengthen Search Service Around Required Fields

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#3840]
We had an issue where the Lucene `DocumentCreator` allowed documents to be created without the `verbatimVersion` field. There should be a unit test to covers this. Also, the Search Service should return a 500 error when it encounters malformed Lucene Documents.

Related to issue #3827

**Comment by skofman1** [comment]
@loic-sharma , can you please provide more details about this issue? What is the expected behavior of search service when an index is invalid?

**Comment by loic-sharma** [comment]
Sure! Updated the issue
