### ISSUE TITLE
Search results do not show right results and are different for VS and gallery

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#3843]
For example: 
1. Search for "Xaml Behaviors" and the results the top result being a package that has very less download counts (popularity?)
![image](https://cloud.githubusercontent.com/assets/14800916/25539725/60951ca4-2bfd-11e7-8eac-40b06cf50cad.png)

2. Search for "aspnetcore". Top results show either a package with great download number but the term only in the tag (is it considered same as name/id for match?) OR contains packages that have very low download counts. In VS the result is very different.
NuGet gallery:
![image](https://cloud.githubusercontent.com/assets/14800916/25539895/fe94f802-2bfd-11e7-930d-9924475e804c.png)

In VS we get different set of search result for the same term:
![image](https://cloud.githubusercontent.com/assets/14800916/25539997/4b98cb6a-2bfe-11e7-9590-1a967905ccbe.png)

**Comment by benaadams** [comment]
Not quite sure what its sorting by; isn't even a priority of release date as later ones (MS.ANC.Xxx) are more recent

**Comment by khellang** [comment]
The screenshot says "Sorted by relevance", whatever that means 😂

**Comment by skofman1** [comment]
You should check "include prerelease" in VS and you will get the same results:
![image](https://cloud.githubusercontent.com/assets/16807822/25540742/00baaebc-2c01-11e7-937a-dc54eb95f9a6.png)

**Comment by skofman1** [comment]
Regarding the bad sorting of results, it's related to this issue: https://github.com/NuGet/NuGetGallery/issues/3778

Can I close this issue?

**Comment by anangaur** [comment]
@skofman1 missed that. May be we should have a checkbox for pre-release on gallery too?

**Comment by skofman1** [comment]
If that's what the clients want..
