### ISSUE TITLE
Improve ImportAzureCdnLogs packagetranslations.json process

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3844]
We need a better process behind adding to `packagetranslations.json`.

Currently, if a customer notes that their package is not getting any downloads, and we notice it follows the invalid pattern (ending with `[.][0-9]*`), we simply add it to the list without any validation and roll it out with the next deployment.

There should be a defined process/playbook for adding these translations and testing them. It could even be an automated process. Additionally, it would be ideal if this change did not require a deployment.

Example PR: https://github.com/NuGet/NuGet.Jobs/pull/139

@xavierdecoster

**Comment by joelverhagen** [comment]
Data-driven unit tests to run against the JSON file would be good too.

**Comment by joelverhagen** [comment]
Not only are package IDs ending in numbers a problem, but also versions that have SemVer 2.0.0 versions in their prerelease label:
https://gist.github.com/joelverhagen/d54fe499b4b0f20c360c10e7e71d919e

**Comment by scottbommarito** [comment]
@joelverhagen how did you get this list?

**Comment by cristinamanum** [comment]
added logic to mitigate this issue. some corner cases exist.
