### ISSUE TITLE
Update Gallery/Search Service functional tests scripts

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3850]
The current scripts for running functional tests are `bat` files that do not use our common build functions and are very outdated.

We should update them. This will provide them more stability and functionality.

**Comment by xavierdecoster** [comment]
In addition, the gallery functional tests seem to have a rather strong dependency on VS2015 (hardcoded paths to msbuild, to mstest.exe, even WebTest Framework that no longer exists in VS2017?)
