### ISSUE TITLE
NuGet.Server 2.11.3 not always honoring packages drop folder

### ISSUE THREAD

**Issue by ABrehm264** [NuGet/NuGetGallery#3852]
Howdy,

I'm sorry if this is already an issue somewhere, but my Github issue search fu isn't working too well. And the one that I did find, is super old and stuff https://github.com/NuGet/Home/issues/3340

I'm currently hosting NuGet.Server v2.11.3, and I'm trying to deploy using the copy/paste to the ~/Packages drop folder method and it seems to not work most of the time.

I haven't been able to spend much time on it, but it seems that the file watching functionality only works when both the site is running, a certain URL ({URL}/nuget/Packages?) on the site has been hit, a file is dropped into the packages folder, and the stars are aligned just right.

Therefore, I have some things that I'm hoping you all could address:
1.) Is it possible to make it so that the file watcher will process everything in the drop folder on web site start up? It doesn't have to do it immediately, but if it could start up, do nuget server start things, perform the current task, and then in the background process the new non-sorted package files.
2.) I was thinking that in the meantime, I could facilitate the packages drop folder by either:
2.1) Splitting up the packages folder that NuGet uses from the thing that everyone else uses to drop NuGet files, and then using a batch job to run the ".\nuget.exe init c:\shared\packagesDropFolder c:\wwwroot\nugetServer\packages" command every 15 minutes or something to "sync the packages"
2.2) Write a script that's pings the /nuget/packages url on the NuGet server to make it so that it's trying to update it's packages every so often.
3) Do you have any other ways that I could accomplish my goal? unfortunately, switching to the apikey isn't currently an option since I have a whole bunch of deploy stuffs that are set up for the  for nuget package file copy method.

Thanks,
Alex

**Comment by joelverhagen** [comment]
Hey @ABrehm264, thanks for taking the time to report this issue.

> I haven't been able to spend much time on it, but it seems that the file watching functionality only works when both the site is running, a certain URL ({URL}/nuget/Packages?) on the site has been hit, a file is dropped into the packages folder, and the stars are aligned just right.

This is expected. The file watcher is initialized after the first NuGet operation is performed against the server. This, for example, is hitting the `/nuget/Packages` endpoint in your browser or using a NuGet client to interact with the server. If this behavior seems to be inconsistent for you, could you provide detailed repro steps (ideally including creating the website project from scratch)?

> 1.) Is it possible to make it so that the file watcher will process everything in the drop folder on web site start up? It doesn't have to do it immediately, but if it could start up, do nuget server start things, perform the current task, and then in the background process the new non-sorted package files.

This should be easy to do in your own project that is consuming the NuGet.Server code. Try putting this in the `Start()` method of `Routes.cs`:

```csharp
// Fire and forget.
Task.Run(() =>
{
    var packages = new NuGet.Server.DataServices.Packages();
    var warmUpSearch = packages.Search(
        searchTerm: string.Empty,
        targetFramework: string.Empty,
        includePrerelease: true,
        includeDelisted: false).ToList();
});
```

> 2.1) Splitting up the packages folder that NuGet uses from the thing that everyone else uses to drop NuGet files, and then using a batch job to run the ".\nuget.exe init c:\shared\packagesDropFolder c:\wwwroot\nugetServer\packages" command every 15 minutes or something to "sync the packages"

This seems reasonable. The benefit of this is it allows you to control operations performed on the `~/packages` folder. A simpler approach would be making `~/packages` into a UNC share that users could drop stuff into themselves. However this means you could mistakenly delete all of the packages on the server if you are not careful.

Another option would be to set up a `System.Timers.Timer` in your web server process (also in `Routes.cs`) that copies the packages from this external folder into the drop folder. Then you could avoid the complexity of that external batch job.

**Comment by ABrehm264** [comment]
Hi, thanks for the response.

My site doesn't have a route.cs. Is that a MVC thing?

Per the instructions here https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server, I thought I was supposed to set up an empty Asp.Net web site.

![screen shot 2017-05-02 at 12 41 51 pm](https://cloud.githubusercontent.com/assets/12091031/25628580/bd9910ec-2f34-11e7-903d-db7cbdad4cc9.png)
![screen shot 2017-05-02 at 12 42 09 pm](https://cloud.githubusercontent.com/assets/12091031/25628592/c56c7e94-2f34-11e7-91f7-ad9dfdf87c77.png)

I'm sorry I'm a noob at making websites :(

**Comment by ABrehm264** [comment]
Looks like that worked, thank you so much.

Thanks,
Alex

**Comment by joelverhagen** [comment]
Glad to help!
