### ISSUE TITLE
Use constants in search service for Lucene field names

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3858]
@ryuyu has already done great work in the catalog2lucene and db2lucene to use constant for lucene field names. We should use these constant in the search service as well, which consumes the Lucene index.

We should also consider moving away from the `IDictionary<string, string>` of properties toward a C# class with string properties. This would be a great improvement to the maintenance of db2lucene and catalog2lucene.

**Comment by skofman1** [comment]
We have a new search service...
