### ISSUE TITLE
NuGet.org gallery doesn't support packages with minClientVersion = 4.0.0

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3866]
@natemcmaster commented on [Wed May 03 2017](https://github.com/NuGet/Home/issues/5156)

**Repro**
1. Create a package with
```xml
<metadata minClientVersion="4.0.0">
```
2. Attempt to push package via NuGet.exe or upload on the nuget.org manually.

**Error**
The push fails with this error
> This package requires version '4.0.0' of NuGet, which this gallery does not currently support. Please contact us if you have questions.

**Comment by joelverhagen** [comment]
We should raise the priority of this. There is no good reason to be blocking these pushes. NuGet 4.1.0 is live right now!
