### ISSUE TITLE
Can't upload SemVer 2.0.0 package with build metadata

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3868]
On dev environment.

1. Create a package with a version that has package metadata, e.g. `1.0.0+git`.
1. Upload it to the gallery. I used the interactive web UI flow but push has the same error.

![image](https://cloud.githubusercontent.com/assets/94054/25673298/ab01f54a-2feb-11e7-91e1-63513fb67de5.png)

![image](https://cloud.githubusercontent.com/assets/94054/25673312/bc12064a-2feb-11e7-9803-b7e6d61de78f.png)

**Comment by xavierdecoster** [comment]
Works on my machine :)

Will retry this on DEV once proper semver2 branch has been deployed there.

**Comment by xavierdecoster** [comment]
Confirmed this now works on DEV (uploaded `SemVer2MetadataTestPackage` package with version `1.0.0+metadata`).
