### ISSUE TITLE
[Question] SignIn/Register issues Local IIS instance

### ISSUE THREAD

**Issue by Seeker1437** [NuGet/NuGetGallery#3882]
Please read the following information before posting the issue.

Error when attempting to sign in or register on locally hosted IIS instance:

https://puu.sh/vFmaZ/d0459fb1e3.png

It is not logging errors in t\he DB, or I just don't know how to get the error. I think it's DB related, but I can't tell, I don't get error anywhere I can find them. Debugging the site in VisualStudio, everything is perfect. D:

I was able to register a user when running from VS, is there something I need to do to get it access to errors?

**Comment by skofman1** [comment]
@Seeker1437 , check ApplicationInsights for errors: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-visual-studio

**Comment by Seeker1437** [comment]
Thank you for your reply!

The Application Insights works for debugging in VisualStudio as expected, however, all of the errors or issues I am having are on the production server. Would it still be where you referred me?

**Comment by skofman1** [comment]
@Seeker1437 , you can configure the gallery to use AI in production as well (that's what we do). You can set the instrumentation key here: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L46

**Comment by Seeker1437** [comment]
Thank you!

It helped me discover the cause of my issue. I thought it was something more complicated!

It was file access permissions.

**Comment by Seeker1437** [comment]
I guess the last thing I have is email. I have set up the smtpurl setting but it does not work.

`smtps://support%40example.com:XXXXXXX@example.com:465`

when I try to use it I just continually get "Operation Timed Out"

**Comment by skofman1** [comment]
@Seeker1437 , port 465 is not supported by System.Net.Mail. Take a look at this issue: https://github.com/NuGet/NuGetGallery/issues/3734
