### ISSUE TITLE
Show confirmation email delivery failure in UI

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3883]
We have been receiving a lot of support requests lately about not having received confirmation emails.

It would be useful if we implemented a feature that told users whether or not their confirmation email was successfully delivered.

This could include the following states:
- successfully delivered (check your spam folders)
- bounced (recipient rejected the delivery)
- blocked (refused to deliver email)

**Comment by skofman1** [comment]
Since MSA/AAD is used we no longer have confirmation e-mail on sign-in. This is not needed.
