### ISSUE TITLE
Remove custom feed parsing code in NuGet.Services.Metadata.Catalog and reuse V2FeedParser from Client

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3884]
Now that [V2FeedPackageInfo](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedPackageInfo.cs) supports `Created` and `LastEdited` we should reuse it in `NuGet.Services.Metadata.Catalog` rather than using our own implementation.

**Comment by skofman1** [comment]
We will be disconnecting V3 from V2 feed in the upcoming sprints, so this won't be needed.
