### ISSUE TITLE
Sudden significant reduction of downloads statistics on Nuget.org

### ISSUE THREAD

**Issue by mariuszgromada** [NuGet/NuGetGallery#3888]
Today I observed significant decrease of number of total downloads for my package
https://www.nuget.org/packages/MathParser.org-mXparser/

Yesterday (2017-05-04) it was: 3714
Today (2017-05-05) it is: 3119

I am consonantly tracking statistics and I am sure about this change - also I have my own log.

Best regards

**Comment by ryuyu** [comment]
Hey.

Thanks for reporting this. We have identified the issue and are working on resolving it soon. There was a bug introduced that is causing us to not properly aggregate downloads from versions that had 4 parts. The individual statistics are still there, and we will get the aggregates corrected soon.

You can follow the work at https://github.com/NuGet/NuGet.Jobs/pull/144

**Comment by mariuszgromada** [comment]
Thanks!

**Comment by gep13** [comment]
@mariuszgromada the issue that is was seeing with download counts has now been resolved. It is also now working for you?

**Comment by mariuszgromada** [comment]
@gep13 Yes, it works! Thanks!
