### ISSUE TITLE
Problem with download counts

### ISSUE THREAD

**Issue by gep13** [NuGet/NuGetGallery#3891]
There seems to be an issue with download counts.

Take for example this package:

https://www.nuget.org/packages/Cake.FileHelpers/

It says that the total downloads is 95,199:

![image](https://cloud.githubusercontent.com/assets/1271146/25770740/b283ca7c-3235-11e7-92c0-686e48735366.png)

However, if you look further down on the same page, the individual package version downloads takes the total to 180115:

![image](https://cloud.githubusercontent.com/assets/1271146/25770746/c7b04128-3235-11e7-9c12-23b369e623e8.png)

I noticed this when I checked this page:

https://www.nuget.org/profiles/cake-contrib

Earlier this month, we tweeted to say that there were more than 500000 downloads associated with the cake-contrib user, and now there is only just over 400000.

Any ideas on what is going on here?  Thanks!

**Comment by gep13** [comment]
The stats have updated, but they are unfortunately still wrong:

![image](https://cloud.githubusercontent.com/assets/1271146/25774499/c607d604-3287-11e7-9e6e-23c669b06c16.png)

![image](https://cloud.githubusercontent.com/assets/1271146/25774503/cf0acf0e-3287-11e7-899f-20b3b55dbcb3.png)

**Comment by anangaur** [comment]
Thanks for reporting this. We have identified the issue and are actively working on resolving it. 
You can follow the work at https://github.com/NuGet/NuGet.Jobs/pull/144

**Comment by gep13** [comment]
@anangaur that is great news! Thanks for quick reply!

**Comment by skofman1** [comment]
@gep13 , thanks for reporting. We are aware of the issue and working on a fix. You can see more details here: https://github.com/NuGet/NuGetGallery/issues/3888
