### ISSUE TITLE
www.nuget.org homepage should mention VS2017

### ISSUE THREAD

**Issue by jawn** [NuGet/NuGetGallery#3894]
Steps:
Go to www.nuget.org

Expected result:
- Latest NuGet Releases mentions that Visual Studio 2017 includes NuGet 4.0. 
- NuGet Feed Locations mentions VS2017

Actual result:
- Latest NuGet Releases only mentions VS2015
- NuGet Feed Locations:  most recent version mentioned is VS2015

**Comment by xavierdecoster** [comment]
Thanks @jawn for reporting! A PR is pending to address this: https://github.com/NuGet/NuGetGallery/pull/3875
