### ISSUE TITLE
Update Semver2 package details message with final nuget client version

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#3897]
Tracking issue to verify client version for semver2 support in messaging.
Relates to https://github.com/NuGet/NuGetGallery/pull/3893

**Comment by xavierdecoster** [comment]
@skofman1 is the final client version known? Currently used `4.3.0`. Has this changed, or will this change?

**Comment by xavierdecoster** [comment]
🔔 @rrelyea?

**Comment by anangaur** [comment]
We should go out with the following message:

This package is only available for download with Visual Studio 2017 (version 15.3) and above or with NuGet client 4.3.0 and above.
Reach out to support if you have more questions.
