### ISSUE TITLE
Improve message for e-mail change confirmation - link works only if you are logged in to nuget.org

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3901]
1. Open the nuget.org in a private window in a browser and apply for a new account.
2. Once new account created, close the private browser window;
3. Find the email confirmation message and copy the link from there.
3. Open new private window and paste the link there.
4. Notice that you are redirected to the nuget.org home page.

It seem you have to be logged on for the email confirmation link to work. If it is a requirement, then we need a clear error message saying that you have to log in for the confirmation link to work, silently redirecting to the home page is bad.
If it is not required to be logged in for the confirmation link to work, it has to be properly processed for the case when a person is not logged in.

**Comment by scottbommarito** [comment]
It is required--it prevents any tomfoolery with our email confirmation process. 

I agree that we need a clear error message, however.

**Comment by skofman1** [comment]
@anangaur ?

**Comment by anangaur** [comment]
We should ask for login again if the user is not logged in.

**Comment by skofman1** [comment]
@agr , please check if this is still the behavior

**Comment by skofman1** [comment]
The behavior changes:
![image](https://user-images.githubusercontent.com/16807822/44552064-dff29380-a6dd-11e8-83c8-1058e63eed55.png)
