### ISSUE TITLE
$filter=IsLatestVersion and semVerLevel=2.0.0 yields no results

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3905]
The client does the following query when using the Browse tab is VS:
```http
GET https://dev.nugettest.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net46'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0 HTTP/1.1
Accept: application/atom+xml, application/xml
user-agent: NuGet Client V3/4.3.0 (Microsoft Windows NT 10.0.14393.0, VS Enterprise/15.0)
X-NuGet-Client-Version: 4.3.0
Accept-Language: en-US
Host: dev.nugettest.org
Accept-Encoding: gzip, deflate
```

This yields no results. I think perhaps its a bug with the introduction of `IsLatestSemVer2` and `IsLatestStableSemVer2`.

This results in an empty "browse" tab when using SemVer 2.0.0:
![image](https://cloud.githubusercontent.com/assets/94054/25864811/a45f214a-34a5-11e7-87d1-ae1344adb611.png)

**Comment by chenriksson** [comment]
Also affects `nuget.exe list`

> D:\tools\NuGetClients\v4.3-beta1\NuGet.exe list -Source http://api.dev.nugettest.org/v3-index/index.json semver -Verbosity detailed

NuGet Version: 4.3.0.0
  GET https://dev.nugettest.org/api/v2/$metadata
  OK https://dev.nugettest.org/api/v2/$metadata 84ms
  GET https://dev.nugettest.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='semver'&targetFramework=
''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
  OK https://dev.nugettest.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='semver'&targetFramework='
'&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 118ms
No packages found.

**Comment by xavierdecoster** [comment]
This may be a data related issue caused by https://github.com/NuGet/NuGetGallery/issues/3908 yet to be deployed to DEV.

**Comment by xavierdecoster** [comment]
For some reason, the external search service returns these packages with `SemVerLevelKey = null` (whilst the value should be `2`).

**Comment by xavierdecoster** [comment]
There's something odd with this client query: 

https://dev.nugettest.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net46'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0

It's filtering on `IsLatestVersion` (not `IsLatestVersionSemVer2`), whilst simultaneously requesting `semVerLevel=2.0.0`, for a search term `semver`. That means, for it to return any results, there must be packages matching the term `semver` that are non-prerelease, and non-SemVer2.

Do you have an example package for which this is the case?

**Comment by xavierdecoster** [comment]
The filter is applied on [line 124 of the `QueryResult` class](https://github.com/NuGet/NuGetGallery/blob/7eed4f25888e8fb88794d4e2a2942d6fed115c7d/src/NuGetGallery/WebApi/QueryResult.cs#L124). 

The OData filter is checking on `IsLatestVersion=true`, and filtering out any package versions not matching that filter.

`IsLatestVersionSemVer2` and `IsLatestStableVersionSemVer2` are not exposed on the OData feed, so we need to do some more OData query hijacking to make this work...

**Comment by chenriksson** [comment]
@xavierdecoster I noticed packages with both semver1 and semver2 in the name, so was querying based on that to test filtering.

**Comment by xavierdecoster** [comment]
yep, working on it, need to apply an additional hijack when applying the OData filter

**Comment by xavierdecoster** [comment]
Looks resolved to me in latest DEV deployment. Can you please confirm? @joelverhagen @chenriksson

**Comment by chenriksson** [comment]
@xavierdecoster nuget list scenario works now; 4.3 client shows semver2 packages
