### ISSUE TITLE
SemVer 2.0: when clicking package with metadata in search results 404 is returned

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3906]
Repro:
1. Uploaded package https://dev.nugettest.org/packages/NuGetGallery.Core?NormalizedVersion=10.0.2-skofman.1.1.1.1
2. Search for NuGetGallery in search window (web site)
3. Click on the package result. The URL is: https://dev.nugettest.org/packages/NuGetGallery.Core/10.0.2-skofman.1.1.1.1%2bbla22

**Comment by xavierdecoster** [comment]
@skofman1 When you say `Search for NuGetGallery in search window`, what do you mean? In client? In browser? All URLs should use normalized version, so trying to pinpoint what gallery page is not doing that.

**Comment by skofman1** [comment]
updated the issue. Meant the website

**Comment by xavierdecoster** [comment]
Was no longer able to repro. Looks resolved on DEV. https://dev.nugettest.org/packages?q=NuGetGallery.Core
