### ISSUE TITLE
SemVer 2.0 - When unlisting package with metadata 404 page shown after ok click

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3907]
Repro:
1. Go to package page https://dev.nugettest.org/packages/NuGetGallery.Core/10.0.2-skofman.1.1.1.1 
2. Click "Delete package", and uncheck the "listed" checkbox. Click ok.
3. You get a 404: https://dev.nugettest.org/packages/NuGetGallery.Core/10.0.2-skofman.1.1.1.1%2bbla22

**Comment by xavierdecoster** [comment]
Confirmed this no longer repros on DEV.
