### ISSUE TITLE
SemVer 2.0: when uploading a package with metadata that already exists a wrong message appears

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3910]
1. Upload package with version 10.0.2-skofman.1.1.1.1+bla22
2. Try to upload package with version 10.0.2-skofman.1.1.1.1+bla33
3. The message that appears: 
![image](https://cloud.githubusercontent.com/assets/16807822/25865699/982288ba-34a8-11e7-8b1f-a4d6fc886f78.png)

4. The message showed should clearly explain that two packages that differ only by version metadata can't be uploaded.

**Comment by xavierdecoster** [comment]
![image](https://cloud.githubusercontent.com/assets/880728/26239651/282d122c-3c7e-11e7-94fa-ea946d7eae39.png)
