### ISSUE TITLE
User profile page does not show SemVer 2.0.0 packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3911]
I have a bunch of SemVer 2.0.0 packages on the DEV environment:
https://dev.nugettest.org/profiles/jver?showAllPackages=True

It seems like only some are showing. These are missing:
```
jver.bugbash.dots
jver.bugbash.dotsmetadata
jver.bugbash.metadata
jver.bugbash.dependency
```

**Comment by xavierdecoster** [comment]
Confirmed these are now showing in your user profile on DEV.
