### ISSUE TITLE
Weird flow when uploading semver2 package through Gallery

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3912]
The issue reproduces with the following package: https://dev.nugettest.org/packages/TestNugetPackage2
1. Create a new semver2 package, say v.0.0.4.0-alpha.3;
2. Upload it through the dev.nugettest.org web site;
3. After submitting the verification form, notice that you are redirected to https://dev.nugettest.org/packages/TestNugetPackage2?NormalizedVersion=0.0.4-alpha.3 and the page displays information about the last "stable" version.

URL seems to be malformed and information on the page does not match the URL.

**Comment by xavierdecoster** [comment]
No longer repros in DEV
