### ISSUE TITLE
Semver2 package with prerelease number and without number show wrong details page in Gallery

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#3913]
On uploading a package with Semver2 having prerelease number and with prerelease without number, UI shows details for the one with prerelease having number in it for the package with URL having without number.
It looks like NormalizedVersion query parameter is not being processed correctly to display details page.
1. Uploaded package: `DeltaX.RandomTest2` version: `3.4.0-alpha.1`
2. Uploaded package: `DeltaX.RandomTest2` version: `3.4.0-alpha`
3. On second upload the URL presented is: https://dev.nugettest.org/packages/DeltaX.RandomTest2?NormalizedVersion=3.4.0-alpha
However, the details page show the details for the package with version: 3.4.0-alpha.1 instead of 3.4.0-alpha

**Comment by xavierdecoster** [comment]
Was not able to repro anymore on DEV. Please do give it another shot during bug bash :)

**Comment by shishirx34** [comment]
Hey @xavierdecoster, I think this still repros on DEV atleast for the packages above. 
1. Go to url: https://dev.nugettest.org/packages/DeltaX.RandomTest2?NormalizedVersion=3.4.0-alpha
2. Notice the details given on the page are for version `3.4.0-alpha.1`. I'd assume it to show for `3.4.0-alpha`

Do I need to re-upload these packages(similar packages) for `NormalizedVersion` parameter to correctly show the details page?

**Comment by xavierdecoster** [comment]
That URL (https://dev.nugettest.org/packages/DeltaX.RandomTest2?NormalizedVersion=3.4.0-alpha) no longer should be generated on the gallery UI, that was a bug.

Where you able to repro by uploading similar packages to DEV?

**Comment by xavierdecoster** [comment]
@shishirx34 Can you please try a repro (not just clicking the URL, but really replaying the scenario)? I believe this issue is resolved.
