### ISSUE TITLE
FindPackagesById does not observe semVerLevel=2.0.0

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3914]
It always just shows the SemVer 2.0.0 versions:
https://dev.nugettest.org/api/v2/FindPackagesById()?id=%27jver.bugbash.dots%27&semVerLevel=1.0.0

This package is indeed SemVer 2.0.0.
https://dev.nugettest.org/packages/jver.bugbash.dots/1.0.0-alpha.1

**Comment by xavierdecoster** [comment]
For some reason, the external search service returns these packages with `SemVerLevelKey = null` (whilst the value should be `2` for these packages, having them excluded from search results when `semVerLevel=1.0.0`).

**Comment by xavierdecoster** [comment]
Just confirmed that for this package the `SemVerLevelKey = 2` in the DEV database, so sounds like a bug in search service? @ryuyu

**Comment by ryuyu** [comment]
Does the gallery expect that v2 search result returns a SemVerLevelKey field? We don't currently do this, which, if the gallery does expect, would reflect this behaviour.

On the other hand, this query
http://nuget-dev-0-v2v3search.cloudapp.net/search/query?q=packageid:jver.bugbash.dots&prerelease=true&semVerLevel=1.0.0
returns an empty result, whereas 
http://nuget-dev-0-v2v3search.cloudapp.net/search/query?q=packageid:jver.bugbash.dots&prerelease=true&semVerLevel=2.0.0
returns a single package

**Comment by xavierdecoster** [comment]
Seems resolved on DEV now:

https://dev.nugettest.org/api/v2/FindPackagesById()?id=%27jver.bugbash.dots%27&semVerLevel=1.0.0
https://dev.nugettest.org/api/v2/FindPackagesById()?id=%27jver.bugbash.dots%27&semVerLevel=2.0.0
