### ISSUE TITLE
Investigate E2E test failures where the client could not connect to the search service

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3924]
E2E Test Run 6070 – 1 Failed Test: NewlyPushedIsAvailableInV3
ErrorMessage: 
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.WebException : Unable to connect to the remote server
-------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.79.43.186:8080
```

E2E Test Run 6072 – 1 Failed Test: UnlistedPackageIsHiddenFromSearch
ErrorMessage:
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.WebException : Unable to connect to the remote server
-------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.79.43.186:80
```

Different test failure, same error message.

Both of these came from search service.
Concerning this flakiness in E2E tests, we have two options:

1.	Call this “network flakiness”, add retries to the request in question, call it a day.
2.	Determine the cause of this connection failed.

**Comment by skofman1** [comment]
@joelverhagen , did you see a repro of this? Are the E2E tests flaky?

**Comment by joelverhagen** [comment]
I haven't seen a repro of this. This run was against DEV so perhaps the machine was in a bad state.

**Comment by skofman1** [comment]
Closing since this didn't repro. Will reopen as needed
