### ISSUE TITLE
NuGet 2.x no longer installs Json.NET on VS2010

### ISSUE THREAD

**Issue by rboy1** [NuGet/NuGetGallery#3935]
I have VS2010 and can't upgrade. So I'm limited to NuGet 2.8.3.
However NuGet 2.8.3 no longer installs Json.NET 10.x, the author says it's a NuGet issue and nothing he can do about the package. 

Can NuGet 3.x be made compatible with VS2010 or alteast find a patch to why 2.8.3 won't install Json.NET 10.x

Please refer to:
https://github.com/JamesNK/Newtonsoft.Json/issues/1265

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #5210](https://github.com/NuGet/Home/issues/5210) via [**ZenHub**](https://www.zenhub.com/)
