### ISSUE TITLE
Deployment 2017.05.24

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3949]
# Deployment 2017.05.24

**Status**: Planned

**Planned production date**: 05/24/2017

**Focus**: 

**Services to Deploy**: 

Branch                       |Service                       | INT                                | PROD
-------                        | -------                        | ---                                 | ----
NuGet.Services.Metadata                       |catalog2lucene  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata                      | Search Service           | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata                       |catalog2registration  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata                       |catalog2dnx              | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata                       |feed2catalog             | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGetGallery                       | V2 Gallery                  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>

**Related blog posts/docs**:
- None

**Deployed commit**: 
- NuGet.Services.Metadata: a2d60c6a7d
- NuGetGallery: f8c924628e
- NuGet.Shims: cfd317e2e2

## Deployment Process
**Search Service**:
- [ ] Deploy catalog2lucene, search
- [ ] Update catalog2lucene, search octopus variables to use v3-lucene2-v2v3*
- [ ] Rebuild lucene index
- [ ] Re-deploy catalog2lucene, search

**Gallery**:
- [ ] Update DB schema
- [ ] Deploy services
- [ ] Update [deployments overview](https://github.com/NuGet/NuGetGallery/wiki/Deployments)
- [ ] Deploy secondary region

**Test Plan**: 
- [ ] Run all functional tests
- [ ] Smoke testing

## Changes
- Gallery
  - Technical
    - SQL: Added the index recommended by Azure portal perf advisor:  #3950. The index is already created in PROD (manually), so applying the migration should only mark the migration itself as applied and not do anything with the DB.

  - Functional
    - Accessibility: Fix: "Example glob patterns" button and "close" button are not accessible using keyboard #3968
    - Accessibility: Scoped API keys UI - disabled elements are accessible using tab #3963

**Comment by chenriksson** [comment]
Sources changes this sprint:
- https://github.com/NuGet/NuGetGallery/pull/3997 (plus shims)
- https://github.com/NuGet/NuGet.Jobs/pull/150
- https://github.com/NuGet/NuGet.Services.Metadata/pull/191
