### ISSUE TITLE
Intermittent connectivity issues from AppVeyor build environment

### ISSUE THREAD

**Issue by FeodorFitsner** [NuGet/NuGetGallery#3961]
Hi guys,

Starting from last Thursday, May 11 we started seeing a lot of timeouts while restoring NuGet packages on build worker VMs in our primary environment. The environment is located in Rackspace DFW3 data center, San Antonio, TX. We are not experiencing the issues on VMs running in Google Compute Engine cloud. 

Could it be that requests from our environment are being throttled/dropped somehow (it uses a single outgoing IP address)? Could it be related to [recent issues in NuGet's CDN provider](https://status.verizondigitalmedia.com/#network-status)? Do you see dropped requests on your side coming from our IP?

Any help with this ongoing issue is highly appreciated!

**Comment by FeodorFitsner** [comment]
WinMTR report for that location:

```
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             148.62.16.3 -    0 |  109 |  109 |    0 |   17 |  226 |    2 |
|    aggr172b-1-core10.dfw3.rackspace.net -    0 |  109 |  109 |    0 |    1 |    7 |    1 |
|   core10-corea.corea.dfw3.rackspace.net -    0 |  109 |  109 |    2 |    3 |    8 |    3 |
|           be31.dcpe2.dfw1.rackspace.net -    0 |  109 |  109 |    2 |    3 |    7 |    6 |
|           be1-mspe4.dfw30.rackspace.net -    0 |  109 |  109 |    4 |    4 |    9 |    4 |
|      de-cix.dfw.verizondigitalmedia.com -    0 |  109 |  109 |    4 |    6 |   28 |    6 |
|                          152.195.72.129 -    0 |  109 |  109 |    4 |    8 |   54 |    6 |
|                            72.21.81.200 -    0 |  109 |  109 |    3 |    4 |   10 |    4 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

**Comment by skofman1** [comment]
@ryuyu , take a look.
@FeodorFitsner, is the issue still in progress?

**Comment by FeodorFitsner** [comment]
Thanks for looking into that! Yes, it's still happening.

**Comment by gep13** [comment]
@FeodorFitsner @skofman1 has this issue been fixed?  Looks like builds that were failing for me, and now passing again.

**Comment by pascalberger** [comment]
Still failing for me (eg. https://ci.appveyor.com/project/cakecontrib/cake-prca-website/build/1.0.163)

**Comment by gep13** [comment]
@pascalberger yip, seems to still be failing for me as well.  Had one build pass, which then it failed again 😢

**Comment by skofman1** [comment]
@FeodorFitsner , @gep13 , @pascalberger , sorry to hear this wasn't resolved yet. We are communicating with our CDN provider, and will update you on the progress. 
I assume you are all using AppVeyor hosted in  San Antonio, TX, Correct?

**Comment by FeodorFitsner** [comment]
Yes, it's Rackspace DFW3 data center in San Antonio, TX.

**Comment by gep13** [comment]
>@skofman1 said...
I assume you are all using AppVeyor hosted in San Antonio, TX, Correct?

Yes, that is correct.  Both @pascalberger and myself are running builds on AppVeyor.

**Comment by gep13** [comment]
@skofman1 just to let you know, our builds now seems to be running correctly 👍

**Comment by ryuyu** [comment]
Hey! Glad to hear everything is working ok.
Just for some extra information here, we heard back from our CDN provider. According to them, they were seeing a few latency spikes in the path inside of rackspace network:

4. be41.corea.dfw1.rackspace.net 0.0% 210 2.8 2.6 2.5 3.9 0.1 
5. po1.corea-core9.core9.dfw3.rackspace.net 0.0% 210 4.7 4.7 4.6 9.0 0.3 
6. core9-aggr172a-1.dfw3.rackspace.net 0.0% 209 4.3 36.7 4.1 261.4 66.0 <<<<<< 

As far as we can tell, it appears to have been an intermittent network issue with rackspace.

Please let us know and reopen the issue if you see more problems like this going forward.

Thanks!

**Comment by FeodorFitsner** [comment]
Yeah, it's working again! 😄 Thank you very much guys for fixing that!

**Comment by skofman1** [comment]
@FeodorFitsner , glad to hear everything works for you! Please note that no fix was performed on our side, and the issue originated in the rackspace network.

**Comment by FeodorFitsner** [comment]
@skofman1 so there was a fix on their side?

**Comment by skofman1** [comment]
@FeodorFitsner , I assume this is the case, since there was no action on our end.

**Comment by FeodorFitsner** [comment]
OK, thanks!

**Comment by FeodorFitsner** [comment]
Hi guys,

We are experiencing connectivity issues to api.nuget.org from AppVeyor environment again. Could you please take a look? There was service [disruption on nuget CDN provider](https://status.verizondigitalmedia.com/#network-status) - maybe this affecting the connectivity.

**Comment by gep13** [comment]
@FeodorFitsner I was just wondering why this build was failing..

https://ci.appveyor.com/project/cakebuild/cake-eijwj/build/1.0.1775#L18

**Comment by brienRosenquist** [comment]
I am also experiencing the same issue...packet loss when connecting out to https://api.nuget.org.  I setup a continuous ping from one of our servers and can see there are timeouts occurring.  I setup a side by side ping test out to google 8.8.8.8 and did not see any timeouts.  The following traceroute was executed multiple times and I am seeing a timeout occurring at 72.21.81.200 which belongs to Edgecast:

PS C:\Users\Rack> tracert api.nuget.org

Tracing route to cs9.wpc.v0cdn.net [72.21.81.200]
over a maximum of 30 hops:

  1     2 ms     2 ms     1 ms  72.32.186.2
  2     2 ms     2 ms     2 ms  aggr107a-core3.dfw1.rackspace.net [72.3.129.76]
  3     3 ms     2 ms     3 ms  Po1.core3.CoreA.dfw1.rackspace.net [72.32.111.0]
  4     3 ms     3 ms     3 ms  be31.dcpe2.dfw1.rackspace.net [74.205.108.120]
  5     5 ms     5 ms     4 ms  10.25.1.103
  6     4 ms     6 ms     5 ms  ae-22.a01.dllstx04.us.bb.gin.ntt.net [129.250.207.117]
  7     4 ms     4 ms     4 ms  ae-0.edgecast-networks.dllstx04.us.bb.gin.ntt.net [128.242.179.166]
  8     3 ms     3 ms     *     72.21.81.200
  9     3 ms     3 ms     3 ms  72.21.81.200

**Comment by FeodorFitsner** [comment]
@brienRosenquist are you guys Rackspace customers too?

**Comment by brienRosenquist** [comment]
@FeodorFitsner Yep.

**Comment by brienRosenquist** [comment]
why was this just closed?
