### ISSUE TITLE
Focus on nav links is ugly

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3964]
![image](https://cloud.githubusercontent.com/assets/94054/26074433/adc20642-3966-11e7-99f0-55c06409d09f.png)

At this instant I am clicking the "Packages" tab.

The orange is very visible (good) but looks ugly for every nav click. Other sites seem to do this properly so the focus border is only visible when you are tabbing across controls.
https://www.microsoft.com/net

/cc @ryuyu 

Only dev branch is affected.

**Comment by skofman1** [comment]
Was fixed
