### ISSUE TITLE
NuGetGallery Self Hosted Local Environment Backup/Restore Oh no, we broke something!

### ISSUE THREAD

**Issue by shyamhd** [NuGet/NuGetGallery#3969]
We have NuGetGallery Self Hosted in our Local Environment. I have took backup of current running NuGetGallery database and restored on other server. However, Once I click on any page like packages, try to sign in, I am getting below error 
```
Sorry, an error occurred while processing your request.
Error: Oh no, we broke something!

You might be here because:

There is an error on our server and the server is "givin' her all she's got, captain."
The system is down, the system is down, the system is down.
Our name is smalls.
We have logged the error and we will look into it, and make sure it doesn’t happen again
```
So, I am not able to access NuGetGallery.
Can you please help me.

Regards,
Shyam

**Comment by skofman1** [comment]
@shyamhd , you should check the logs for errors. NuGetGallery supports both Elmah and ApplicationInsights for logging. To check the Elmah logs you can access the Admin section of NuGet Gallery. To see error in ApplicationInsight, set the InstrumentationKey here: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L46

**Comment by shyamhd** [comment]
@skofman1 thank you for reply.
I have found error log in ApplicationInsights
The error is due to `login failed for user`. Because of I have to SQL Server instances on same sever cause this issue.
