### ISSUE TITLE
Unable to access api.nuget.org from specific network

### ISSUE THREAD

**Issue by satripat** [NuGet/NuGetGallery#3971]
Connections to https://api.nuget.org/v3/index.json appear to be refused by the nuget.org. it seems our IP addresses are blocked.  due to this development activities are getting impacted. can you help in fixing it?

**Comment by skofman1** [comment]
Hi @satripat , can you provide additional information regarding the issue? 
1. What is the error you are seeing? 
2. What is your location? 
3. Please provide us with an MTR log according to the instructions here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#managing-packages-on-nugetorg
4. What is your IP?

To avoid placing this information publicly, please send an e-mail with the details to support@nuget.org

**Comment by satripat** [comment]
Hi @skofman1 , 

i have sent an email to support@nuget.org with the details you requested. please help us fixing this issue. 

thank you.

**Comment by anangaur** [comment]
Another similar issue reported on twitter: https://twitter.com/ganesanarun21/status/864685044610211840

**Comment by satripat** [comment]
This issue is fixed. Thank you for your help. :+1:

**Comment by satripat** [comment]
hello team, this issue is back again. could you please look  into it?

thank you.

**Comment by ZweHlaingPhyo** [comment]
I have similar issue for unable access api.nuget.org. Please fix it,i will sent an email to [support@nuget.org](mailto:support@nuget.org) with the details information.

**Comment by ZweHlaingPhyo** [comment]
> I have similar issue for unable access api.nuget.org. Please help to fixing it,i will sent an email to [support@nuget.org](mailto:support@nuget.org) with the details information. Thanks.
