### ISSUE TITLE
api/v2/curated-feeds/whatever responds with HTTP 200

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3989]
For some reason, the requests like

    https://www.nuget.org/api/v2/curated-feeds/almost-anything

respond with HTTP 200 instead of 404. We probably need to look into that.

**Comment by skofman1** [comment]
@emgarten , is this by design?

**Comment by emgarten** [comment]
> is this by design?

Not that I know of. The client uses curated feeds in the same way as other feeds. It is possible an older version of VS shipped with a curated feed that was removed and the gallery wanted to avoid breaking someone, but that is just a guess.

**Comment by skofman1** [comment]
Since this behavior isn't impacting customers in a negative way, and changing it is a risk, closing this issue.
