### ISSUE TITLE
Incorrect comparer implementation causes infinite loop

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4003]
`RetryingHttpClientWrapper.cs` contains the `WeightedRandomComparer` class that implements `IComparer<int>` in a way that involves rolling random numbers. This implementation does not pass basic sanity check for the comparer: `Compare(a,b) == -Compare(b,a)`. Specifically, for the case when array of zeroes is attempted to be sorted it causes the sort implementation to loop infinitely.
Specifically in case of Gallery, if both instances of search service are considered down, eventually, each request that involves the subsequent request to the search service would create a thread with an infinite loop inside of it. So after few dozens of such requests we'd have Gallery machines completely unresponsive.

**Comment by agr** [comment]
Found the paper offering efficient solution for the problem: http://utopia.duth.gr/~pefraimi/research/data/2007EncOfAlg.pdf

**Comment by agr** [comment]
Even worse, the instance of the `WeightedRandomComparer` is declared static, created once and exists for the life time of the process. It does not contain any synchronization logic inside and uses the object of `Random` class which is [not thread safe](https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx#ThreadSafety).

**Comment by skofman1** [comment]
We will move to traffic manager: https://github.com/NuGet/NuGetGallery/issues/5700
