### ISSUE TITLE
Package metadata to unlist the package by default

### ISSUE THREAD

**Issue by AArnott** [NuGet/NuGetGallery#401]
Some packages are there merely to serve as common dependencies for several other packages, and aren't useful to be listed for public consumption (because there is no public API in those packages, for example).  

It would be great if there were a .nuspec xml element, like `<DependencyOnly>true</>` or `<Unlisted>true</>` that would hide it from the public listen to avoid cluttering up the packages list.

See discussion here: http://nuget.codeplex.com/discussions/291138

**Comment by StephenCleary** [comment]
Is there a possibility of getting this in? Nuspec metadata works much better than a command line option in my case (AppVeyor).
