### ISSUE TITLE
Support URLs as entire "release notes" contents

### ISSUE THREAD

**Issue by mgravell** [NuGet/NuGetGallery#4023]
Release notes are a bit awkward in the app, and updating them *in the package* is usually a bad idea as it is hard (impossible) to fix the release notes. Additionally, in the csproj or nuspec is a horrible place to try to store cumulative notes. And the formatting is poor.

As such, a lot of people just use a URL. There exists  #2280 to improve the formatting (which would allow this indirectly, by using `[see here](https://some.com/url)` as the notes), but as a really quick win that doesn't get bogged down in lots of questions like "which variant of markdown?", pragmatic option:

If the release notes are a http[s] URL and *just* a http[s] URL: linkify it in the gallery.

I would be happy to submit a PR if it helps (thought it best to discuss first).

**Comment by Drawaes** [comment]
I use a csproj include based on the version number I tag it in during the build...
https://github.com/Drawaes/CondenserDotNet/tree/master/releasenotes
Granted I don't have a lot in them at the moment but I could.

If you look at my appveyor build it checks if there was a release tag that triggered the build and if so changes the include.

**Comment by NickCraver** [comment]
Related: see https://github.com/NuGet/Home/issues/1734 which was merged into https://github.com/NuGet/Home/issues/1203

I think making it recognize and auto-link URLs seems like a *very* cheap Gallery-only win though. Perfection shouldn't be the blocker to incremental, easy, substantial improvements here.

**Comment by Drawaes** [comment]
I tend to agree, what is the goal here though? To scrap the data from the URL and pull it into nuget? If so that leads to a load of potential problems. Why not make it MD ?

**Comment by NickCraver** [comment]
Nope - literally to make it clickable, that's it. I think it should be makrdown, etc., but a very easy win would be to just make it a link.

**Comment by Drawaes** [comment]
In that case, I withdraw my comments and it give it a thumbs up

**Comment by skofman1** [comment]
Thanks for the feedback @mgravell , @NickCraver , @Drawaes . We are currently working on improvments in this area and will take your feedback into account.

//cc @chenriksson , @jonwchu

**Comment by skofman1** [comment]
@mgravell , our preview site includes the change you requested:
https://github.com/NuGet/NuGetGallery/issues/4492 
https://github.com/NuGet/NuGetGallery/pull/4505

Feel free to reopen this issue if the added feature doesn't cover your ask.
