### ISSUE TITLE
SEC_ERROR_OCSP_INVALID_SIGNING_CERT SSL Problem

### ISSUE THREAD

**Issue by r-ising** [NuGet/NuGetGallery#4024]
Browser: Firefox 53
OS: macOS 10.12.5

Hello,

https://www.nuget.org is not working on my mac with firefox 53.

I get an OCSP error like this:
SEC_ERROR_OCSP_INVALID_SIGNING_CERT

Can you fix it please?

Thanks

**Comment by hjred** [comment]
Hi there,

having the same problem with Firefox 53.0.3 on Windows 10 (1703).
Trying to browse nuget.org aborts with "secure connection failed".
Invalid OCSP signing cert in OSCP answer.
Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT

Thanks for looking into this

**Comment by hjred** [comment]
It's working again at the moment

**Comment by xavierdecoster** [comment]
[This looks like a broader issue not only affecting nuget.org](https://blogs.msdn.microsoft.com/vsoservice/?p=14225). 

I just verified this on my machine with latest Firefox and it did not reproduce the issue. @r-ising could you please confirm the issue is resolved for you as well?

**Comment by hjred** [comment]
Yeah, codeplex.com was down for me too and is also working at the moment again.

Based on the information i found, whenever OCSP stapling is used on the server side (which is the case, indicated by the error), there should be a flag called "Must staple" set in the certificate (which has to be enabled at certificate creation).
The nuget cert doesn't have this flag set according to ssllabs test but the server has enabled support.
This kind of configuration could cause problems in some situations like invalid responses.

**Comment by skofman1** [comment]
Based on the information we recieved, the root cause was an expired OCSP signing certificate that was cached. The caching expired, and the issue is now resolved.
