### ISSUE TITLE
More improvement my package list readability.

### ISSUE THREAD

**Issue by kekyo** [NuGet/NuGetGallery#4025]
## Cannot read my package's id...

![image](https://cloud.githubusercontent.com/assets/6181948/26568961/5924e81a-4542-11e7-96b8-af512b15d053.png)

* I want to improvement nuget.org my package list UI, for example applying responsive web design.

**Comment by skofman1** [comment]
Thanks for the feedback @kekyo ! We are currently working on redesigning the site, and will take your feedback into account.
//CC @jonwchu

**Comment by joelverhagen** [comment]
We have redesigned this page using Bootstrap. It should be a lot more readable on a variety of screen sizes.
https://preview.nuget.org/

**Comment by kekyo** [comment]
@joelverhagen It's nice!! thanks!

![image](https://user-images.githubusercontent.com/6181948/27962614-6a6e41fe-636d-11e7-9fad-e42fcb4bb08d.png)
