### ISSUE TITLE
status.nuget.org status coloring scheme needs fix

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4033]
If there is an issue impacting any of our online service, the status page should reflect the same status color (yellow/red) till the issue is fixed. We should have the latest message pinned at the top and a link to rest of the messages at the bottom.

**Comment by scottbommarito** [comment]
This is a duplicate of https://github.com/NuGet/Engineering/issues/230. I will update the other issue's name to better reflect what it's describing.
