### ISSUE TITLE
All regular expressions must have a MatchTimeout property set or be removed

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4038]
Regex matching should be time limited, otherwise it opens up the possibility to craft the input data in a way that would cause the server to consume too much resources while checking the match.

See the [docs](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.matchtimeout%28v=vs.110%29.aspx).

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #1278](https://github.com/NuGet/Engineering/issues/1278) via [**ZenHub**](https://www.zenhub.com/)
