### ISSUE TITLE
Average download shown incorrectly when its 1.x 

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4039]
From a tweet: https://twitter.com/plecaillon/status/870322417251602432 
 
![image](https://cloud.githubusercontent.com/assets/14800916/26705813/734fe18e-46ed-11e7-9cee-716c226ca86b.png)

Its 63 days since first publish of the package: https://www.nuget.org/packages/Evolve 
![image](https://cloud.githubusercontent.com/assets/14800916/26705823/817fd7dc-46ed-11e7-91c5-bf6bca0d5499.png)

 It should be 79/63 = ~1 download per day. 

Fix https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L43

```
Model.DownloadsPerDay <= 1 ? "<1" : Model.DownloadsPerDay.ToNuGetNumberString() 
```
should be (??)
```
Model.DownloadsPerDay < 1 ? "<1" : Model.DownloadsPerDay.ToNuGetNumberString()
```

**Comment by xavierdecoster** [comment]
Verified in PROD, this now shows `1` instead of `<1`.
https://www.nuget.org/packages/Evolve
