### ISSUE TITLE
 Package Manager Console requires PowerShell 2.0

### ISSUE THREAD

**Issue by Michael-McD** [NuGet/NuGetGallery#4043]
After a clean install of VS 2017 Pro on a Windows Server 2016 Std. Edition.

Step 1: open the Package Manager Console

Result: Error message:
`Error: The Package Manager Console requires PowerShell 2.0 runtime, which is not detected on this machine. Please install the PowerShell 2.0 from http://support.microsoft.com/kb/968929 and restart Visual Studio.`

**Comment by blowdart** [comment]
Related - https://github.com/NuGet/Home/issues/5294

**Comment by skofman1** [comment]
Closing since this is not NuGet.org related
