### ISSUE TITLE
Statistics last updated for 2017-06-Su? - The Date format is bugged

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#4053]
This is a kind of date format I cannot handle ;)

![image](https://cloud.githubusercontent.com/assets/5808377/26765069/90a17c28-4974-11e7-9b0f-01438e950c3e.png)

For example : https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version

**Comment by skofman1** [comment]
Thanks for reporting @304NotModified ! Will start investigation ASAP.

**Comment by scottbommarito** [comment]
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Views/Statistics/_PivotTable.cshtml#L14

is probably where the bug is

**Comment by scottbommarito** [comment]
I believe the `dd` should be `D` or `DD`
