### ISSUE TITLE
What is the correct handling approach for Symbols packages?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/NuGetGallery#4056]
If I pack with -Symbols, then two packages are created, one with symbols and one without.

For an internal only nuget server I would think I would want both but Nuget.Server only allows this when `allowOverrideExistingPackageOnPush` is set to true. 

However, enabling that means that someone can overwrite an existing non-symbols package - and that is something that should not happen. 

Whats the proper setting combination or SOP to allow both (but at worst just the symbols) to be published to Nuget.Server, without the chance of overwriting an existing published package of the same name + version?

**Comment by skofman1** [comment]
@StingyJack , can you please provide more details on what is your user scenario?
In general, if you would like to host symbol packages on NuGet.Server, and also avoid overriding existing packages, you should run a secondary NuGet.Server instance, especially for this kind of packages.
Having said that, NuGet.Server is not a symbols server since it doesn't support symbols server protocols. So more details will help provide a better answer.

**Comment by StingyJack** [comment]
i mean packages made with the '-symbols' switch. nuget pack emits both, but nuget.server doesnt seem to consider this as far as i can tell

**Comment by skofman1** [comment]
symbols packages that are created by nuget.exe are not meant to be hosted on NuGet.Server, they are meant to be hosted on a symbols server to allow using them during debugging.

You can get more details in our documentation: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages#publishing-a-symbol-package

If you are interested in hosting your own symbol server, found this blog by @xavierdecoster : http://www.xavierdecoster.com/setting-up-your-own-symbolsource-server-step-by-step

**Comment by StingyJack** [comment]
Sorry to bother again, but I cant tell if the symbols server you are talking about the same as the symsrv+local folder or if it is something specific to NuGet.

**Comment by skofman1** [comment]
@StingyJack , in general, a symbol server has no understanding of the concept of a "NuGet Package" (*.nupkg) or a "NuGet Symbols Package" (*.symbols.nupkg). Symbols servers 'understand' only DLLs and PDBs. You can see the documentation here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms680693(v=vs.85).aspx

There are symbol servers that understand the concept of "NuGet Symbols Package" (*.symbols.nupkg). Meaning, you can push a symbols.nupkg to the server, it will extract the *.pdb files and index them. When you configure VisualStudio to use this symbol server, at debug time it will use a protocol to find and download those symbols. 
Instructions on how to build such a  symbol server are provided here:
http://www.xavierdecoster.com/setting-up-your-own-symbolsource-server-step-by-step

Also, VSTS recently built a symbol server that support packages:
https://blogs.msdn.microsoft.com/devops/2017/11/15/vsts-is-now-a-symbol-server/

**Comment by StingyJack** [comment]
Right but I can still publish my pdb's to the [symsrv](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681417(v=vs.85).aspx) based symbols repo, and VS wont have a cow about finding them when its using a nuget package?

**Comment by skofman1** [comment]
@StingyJack , when installing a NuGet package to a project, during build the DLLs (and other files) in the package are placed in the output directory of the project. Hence, the debugger should be able to find symbols for them on your symsrv as it would for any other DLL.
