### ISSUE TITLE
Can't upload packages using NuGet owner's API Key

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#4069]
@mythz commented on [Tue Jun 06 2017](https://github.com/NuGet/Home/issues/5353)

I'm getting a 409 Error Response when trying to upload NuGet packages from the command-line using my `mythz` API Key. 

NuGet Version: 3.4.4.1321

This is the .bat script I used to upgrade:

```
SET NUGET=C:\src\ServiceStack\src\.nuget\nuget
%NUGET% setApiKey {mythz API key}

%NUGET% push ServiceStack.OrmLite.Firebird.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
%NUGET% push ServiceStack.OrmLite.Oracle.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
%NUGET% push ServiceStack.OrmLite.Oracle.Signed.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
%NUGET% push ServiceStack.OrmLite.VistaDb.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
```

This is the error response from the command-line:

```
C:\TeamCity\buildAgent\work\e4249c2d6a4e9e8d\deploy>C:\src\ServiceStack\src\.nuget\nuget push ServiceStack.OrmLite.Firebird.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
Pushing ServiceStack.OrmLite.Firebird.4.5.10.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 464ms
Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.Firebird' is not available.).

C:\TeamCity\buildAgent\work\e4249c2d6a4e9e8d\deploy>C:\src\ServiceStack\src\.nuget\nuget push ServiceStack.OrmLite.Oracle.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
Pushing ServiceStack.OrmLite.Oracle.4.5.10.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 448ms
Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.Oracle' is not available.).

C:\TeamCity\buildAgent\work\e4249c2d6a4e9e8d\deploy>C:\src\ServiceStack\src\.nuget\nuget push ServiceStack.OrmLite.Oracle.Signed.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
Pushing ServiceStack.OrmLite.Oracle.Signed.4.5.10.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 427ms
Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.Oracle.Signed' is not available.).

C:\TeamCity\buildAgent\work\e4249c2d6a4e9e8d\deploy>C:\src\ServiceStack\src\.nuget\nuget push ServiceStack.OrmLite.VistaDb.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package
Pushing ServiceStack.OrmLite.VistaDb.4.5.10.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 720ms
Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.VistaDb' is not available.).
```

What's different about these packages is that they're the only ones that aren't "dual-owned" by both **servicestack** and **mythz** accounts which I believe is related to the underlying issue. But I'm definitely using the **mythz** API key to upload these packages owned by **mythz** and I was later able to upload these packages manually through the nuget.org website under the **mythz** account - it just doesn't work when trying to upload them using **mythz** API Key.

**Comment by shishirx34** [comment]
@mythz - Do you mind reaching out to us on support@nuget.org. I need to get some more information from you to debug this issue. Please specify this issue and my github handle @shishirx34 in the email so that it would be redirected to me.

The error you see should be shown only if the API Key specified doesn't have access/permissions to push to the given package ID. Are you absolutely certain that the API key you used wasn't that of other user(servicestack) maybe?

Could you try following things:
1. If possible, could you please try using the [latest nuget.exe](https://dist.nuget.org/index.html), we have some improved error message logging with latest versions, I believe with the older versions of nuget.exe you'd see 409(conflict) instead of 403(no permissions). 
2. Try running from command line the push command with API key, ensuring you have copied the correct API key.
```
nuget.exe push <Nupkg> -Source https://www.nuget.org/api/v2/package -ApiKey <mythz's API key>
```

**Comment by mythz** [comment]
>  Are you absolutely certain that the API key you used wasn't that of other user(servicestack) maybe?

Yes I am 100% absolutely, positively, definitely sure I used the API key for the **mythz** user in the .bat script. I ran this script several times and checked the API Key several times before resorting to manually uploading the packages by hand. 

> If possible, could you please try using the latest nuget.exe,

I did use the latest NuGet.exe that I got from the **latest nuget.exe** link on the https://www.nuget.org home page, which for some reason is reporting **3.4.4.1321** version number listed in the issue I submitted. We publish our official releases are on NuGet and we just released so we wont be able to publish a new release until our next release in 4-6 weeks. Is there another command I can use to test permissions without uploading a new package?

**Comment by shishirx34** [comment]
You could try getting the v4.1.0 version directly with the url [here](https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe). 

Please put this exe directly into your nuget folder where you are consuming it. 'C:\src\ServiceStack\src\.nuget\nuget`

Run following command to check the version
```
C:\src\ServiceStack\src\.nuget\nuget
```
Should be 4.1.0

We can try one thing to gauge the permissions. Try uploading the same **existing package** with your API key.
Run:
```
nuget.exe push ServiceStack.OrmLite.Firebird.4.5.10.nupkg -Source https://www.nuget.org/api/v2/package -ApiKey <mythz's API key>
```

If you see error like: 
```
Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.Firebird' is not available.)
```
Then the API key used definitely does not have the permission to push to this package.

If you see error like:
```
Response status code does not indicate success: 409 (A package with ID 'ServiceStack.OrmLite.Firebird' and version '4.5.10' already exists and cannot be modified.)
```
Then the API key does have permission but the package already exists, and the next time you upload a newer version then this API key should just work.

In the former case, you can try to create a new API key. Follow the steps [here](http://blog.nuget.org/20170202/introducing-scoped-api-keys.html#create-scoped-api-keys). Once done you can try to push again with the same existing package with this new API key you created and test if you see the second error above.

Let me know.

**Comment by mythz** [comment]
This is the result from running the above command:

```
Pushing ServiceStack.OrmLite.Firebird.4.5.10.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 595ms
```
**Response status code does not indicate success: 409 (A package with ID 'ServiceStack.OrmLite.Firebird' and version '4.5.10' already exists and cannot be modified.).**

So it sounds like it will work in future when I use the update **nuget.exe** version, thanks.

**Comment by shishirx34** [comment]
Thanks @mythz for verifying this. Please feel free to open this issue in future if you face the same issue again.

**Comment by mythz** [comment]
FYI I tried it again and can confirm id doesn't work when setting the API Key with:

```
nuget setApiKey 34ca0303-aa1e-4b39-85ff-eeaebbdec600
```

Which resulted in all 4 packages failing with:

```
Pushing ServiceStack.OrmLite.Firebird.4.5.12.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 858ms
```
**Response status code does not indicate success: 409 (The package ID 'ServiceStack.OrmLite.Firebird' is not available.).**

But it worked when I added the ` -ApiKey <mythz's API key>` param. I'm using:

```
NuGet Version: 4.1.0.2450
```

**Comment by skofman1** [comment]
@mythz , you shouldn't leak your API key. Other users might use it to push packages in your name! @shishirx34 , please expire this credential.

**Comment by mythz** [comment]
@skofman1 ahh crap I thought I wrote <mythz API Key>, can my new key be set to never expire please

**Comment by shishirx34** [comment]
@mythz - did you delete your old key? Please reach out to us at support@nuget.org for discussing how we can help you out with your API key.

**Comment by mythz** [comment]
@shishirx34 thx I've deleted old API key and sent request to `support@nuget.org` to set my new key to never expire.

**Comment by shishirx34** [comment]
@mythz - I have responded to your request in the mail thread. Getting back to the issue at hand. Could you tell us how you are running the command for `nuget setApiKey` and `nuget push <pkg>`. 

1. Which directory are you running the command from?
2. Where is your <pkg> located?
3. Are both the commands being run from the same working directory?
4. Do you use the same machine to push to other packages, which are shared with `servicestack`. Is the API key for `servicestack` also configured on the same machine?

When you use `nuget setApiKey <api key>` command, we save this API key in the global `NuGet.Config` placed in `%AppData%` folder, unless a config file is specified somewhere. I suspect that its possible that the setApiKey is not writing to the correct config file in your case and `nuget push` command picking it up from some other place, which has incorrect API key configured.

**Comment by mythz** [comment]
@shishirx34 thx for sorting my new API key out.

> Which directory are you running the command from?

It's from one of my TeamCity artifact output folders. I am using the same CI Server with a different key which is likely the issue, can't tell which API Key is in `%AppData%\NuGet\NuGet.Config` since it seems to be encrypted and Base64 encoded. So it looks like the issue is as you say `nuget setApiKey <api key>` doesn't save it in NuGet.config from which the `nuget.exe` is later reading from, although I would've thought that `nuget setApiKey <api key>` would've sets an Environment variable for the shell that `nuget.exe` uses.

**Comment by shishirx34** [comment]
Issue moved to [NuGet/Home #5468](https://github.com/NuGet/Home/issues/5468) via [**ZenHub**](https://www.zenhub.com/)
