### ISSUE TITLE
NuGet gallery UI should show target frameworks the package

### ISSUE THREAD

**Issue by AArnott** [NuGet/NuGetGallery#4077]
Neither nuget.org nor preview.nuget.org show the target frameworks of a package. Consider a package that targets net40 and net45, but expresses no package dependencies. The gallery shows _no hint_ as to what projects the package might install into.

Even when dependencies are expressed, that's only a rough estimate, and can under express the compatibility of this package. For example, a package might take a dependency on NetStandard.Library when targeting netstandard1.5 but have no dependency for net40, and the gallery will only show netstandard1.5 on the page even though net40 is also a target. 

It seems like a super basic and critical trait of a package to be able to see on the gallery. Can it be added?

see also: https://github.com/NuGet/NuGetGallery/issues/2805

**Comment by bladeoflight16** [comment]
I don't know what others think about this, but for me, I can make do without a full list of every possible compatible runtime as long as package's *explicit* targets are listed. For example, if it contains builds for .NET Standard 2.0 and .NET 4.5.2 and the UI shows that, I can figure out that the .NET Framework 4.7.0 will work just fine with at least one of those. The main thing I'm looking to determine is, "Is there *any* target framework in the package that is compatible with my project's currently targeted framework?"

**Comment by joelverhagen** [comment]
We've shipped a Frameworks tab on the package details page. This shows all package asset frameworks (frameworks directly expressed by assets in the package) and calculated frameworks (implicit support via TFM mappings). This was tracked by https://github.com/NuGet/NuGetGallery/issues/4843 and is now resolved. Go try it out if you haven't already 😃.
https://www.nuget.org/packages/Newtonsoft.Json/13.0.2-beta1#supportedframeworks-body-tab

The ability to filter package search by TFM or by supported framework is tracked by https://github.com/NuGet/NuGetGallery/issues/3098.

If you feel that what you're describing is now implemented yet, please feel free to open a new issue with details!

Thanks!
