### ISSUE TITLE
[Secure push] Admin tools - when clicking SecurePush table header user is not checked

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4079]
Repro: 
1. Search for user name
2. Click on SecurePush table header

Expected: user row checkbox checked. 

![image](https://user-images.githubusercontent.com/16807822/26951892-e44f70f6-4c57-11e7-834e-04f4ff4c9894.png)

**Comment by chenriksson** [comment]
Closing; has been fixed in PR #4061
