### ISSUE TITLE
When adding an owner with propagating secure push, the warning is in a JavaScript alert

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4081]
This is kind of hard to read. I think we should get some designer resources on this modal to decide how to more prettily handle modal interactions in the web UI. JavaScript `alert()` is the easiest but also the ugliest.

![image](https://user-images.githubusercontent.com/94054/26952937-7bb3f1fc-4c5c-11e7-8215-53e08c54b6ae.png)

Could we get a multi-step UI in the web page or perhaps an HTML-rendered modal?

/cc @chenriksson

**Comment by chenriksson** [comment]
Fixed in PR #4061. Will provide screenshot there.
