### ISSUE TITLE
Inifinite redirect loop on log in after logging out from page requiring authentication

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4082]
Prerequisites: 2 sets of credentials: cred1 and cred2. 'cred1' should have a package uploaded, 'cred2' MUST NOT be an owner of the package.
Steps:
1. Log in as 'cred1';
2. Go to 'manage package' for the owned package (cred2 must not have access to that page);
3. Click the 'sign out';
4. Sign in as 'cred2';
5. Browser complains about incorrect redirect.
    * Firefox shows this:
    > The page isn’t redirecting properly
    >Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

There probably shouldn't be 'returnUrl' part in the sign out link at least for the pages that require authorization.
In any way we shouldn't issue invalid redirects.

**Comment by agr** [comment]
Found simpler repro:

Log in as any non-admin account to dev.

Try opening the following link:

https://dev.nugettest.org/packages/TestNugetPackage3/ManagePackageOwners

Result is the same as above.

**Comment by skofman1** [comment]
@agr, please see if it still repros

**Comment by skofman1** [comment]
@agr, 🔔

**Comment by skofman1** [comment]
> Found simpler repro:
> 
> Log in as any non-admin account to dev.
> 
> Try opening the following link:
> 
> https://dev.nugettest.org/packages/TestNugetPackage3/ManagePackageOwners
> 
> Result is the same as above.

Tried to repro. Getting a 404.
