### ISSUE TITLE
Response status code does not indicate success: 400 (Your account requires client version '4.1.0' or higher to be able to push packages)

### ISSUE THREAD

**Issue by ferventcoder** [NuGet/NuGetGallery#4083]
Just curious why I suddenly started seeing this recently. Did I miss a blog post about this change?

**Comment by ferventcoder** [comment]
Other folks have hit this as well - https://github.com/appveyor/ci/issues/1590 and http://help.appveyor.com/discussions/problems/5665-nuget-version

**Comment by ferventcoder** [comment]
More importantly, how do I adjust my account?

**Comment by anangaur** [comment]
@ferventcoder, Can you reach to support@nuget.org and we will help you out immediately.

**Comment by ferventcoder** [comment]
Was just going to say that I did. Good edit. :)

**Comment by FeodorFitsner** [comment]
Got something?

**Comment by ferventcoder** [comment]
The information I received is that I was a co-owner of a package that fell under a Microsoft-owned technology. This means my account was subject to a stricter security policy while I was still a maintainer/owner. I asked for my account to no longer maintain that package and the restriction to be lifted.

**Comment by ferventcoder** [comment]
For anyone that runs into this, reach out to support at nuget dot org, it could be any of numerous things and they will be able to tell you what it is.

**Comment by ferventcoder** [comment]
https://github.com/NuGet/NuGetGallery/issues/4315 is a duplicate of this. Since there is more discussion there, closing this.
