### ISSUE TITLE
[Redesign] Last Updated Timestamp is wrong

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4084]
On the `feature-redesign` branch, upload a package and view its Package Details page. The last updated time will be `in 6 hours`. It seems that the timestamp inserted into the database is wrong.

**Comment by ctolkien** [comment]
Confirming that the time display is out by 10 hours and we are UTC+10

**Comment by skofman1** [comment]
@joelverhagen , was this fixed?

**Comment by joelverhagen** [comment]
Fixed.
