### ISSUE TITLE
Release Notes should treat links as links

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4126]
Publishers often put a link (with or without text) in the Release Notes section. We should make these links clickable so easy navigation.

**Comment by skofman1** [comment]
@joelverhagen , wasn't this something you worked on?

**Comment by anangaur** [comment]
I think this is fixed now. Let dig out the issue # and close it

**Comment by anangaur** [comment]
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4492 and fixed.
