### ISSUE TITLE
Updated setup instructions?

### ISSUE THREAD

**Issue by thnk2wn** [NuGet/NuGetGallery#413]
So far I've run into some issues getting NuGet gallery fully running on our web server:

https://github.com/NuGet/NuGetGallery/issues/409
https://github.com/NuGet/NuGetGallery/issues/412

Is there updated documentation somewhere with instructions on setting this up? Preferably instructions that don't assume you are just trying to make it run on your local dev box?

The instructions at http://docs.nuget.org/docs/contribute/setting-up-a-local-gallery still refer to the older Orchard setup and I don't see setup info here in the readme markdown or elsewhere in the codebase. I can keep reverse-engineering and playing around with different configurations but I do not want to spin my wheels too long.

Any info / tips are much appreciated. I found a few resources online but nothing very comprehensive that addresses the issues so far. Thanks again.

http://www.codecapers.com/post/How-to-Set-Up-a-Local-NuGet-Gallery.aspx
http://anthonymastrean.com/post/11405529860/getting-a-nuget-gallery-running

**Comment by maartenba** [comment]
Closing as it's quite an old one and docs have had a few updates
