### ISSUE TITLE
[Redesign] Text cut off on the chart on the statistics page in Edge

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4140]
https://preview-dev.nugettest.org/stats no high contrast, full screen, logged out

![image](https://user-images.githubusercontent.com/102933/27155852-65be83a0-510f-11e7-99a9-29123fa7caba.png)

**Comment by joelverhagen** [comment]
Another example:
![image](https://user-images.githubusercontent.com/94054/28042209-2f03ff62-6581-11e7-9d81-0a175c33578d.png)
