### ISSUE TITLE
Package stats page is empty in Edge

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4144]
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage/1.0.0?groupby=Version
not logged in, no high contrast.

Error produced in browser console on page load:
```
HTML1300: Navigation occurred.
1.0.0
Current window: preview-dev.nugettest.org/stats/packages/BaseTestPackage/1.0.0
SCRIPT5007: Unable to get property 'length' of undefined or null reference
stats.min.js (1,131692)
```

**Comment by ryuyu** [comment]
Same root cause as https://github.com/NuGet/NuGetGallery/issues/4174
