### ISSUE TITLE
Inconsistent number alignment in stats tables

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4146]
Tested in Edge, but likely an issue in all browsers:
https://preview-dev.nugettest.org/stats page has all numbers in tables right aligned, on other pages 
(https://preview-dev.nugettest.org/stats/packages/BaseTestPackage?groupby=ClientName, https://preview-dev.nugettest.org/stats/packages, and others) numbers are left aligned in tables.
Generally, all numbers in tables should be right aligned.

**Comment by ryuyu** [comment]
We discussed this a bit and decided that it looked better this way currently. Right aligning leads to a lot of empty space between columns in some cases. We can revisit if you feel strongly.
