### ISSUE TITLE
[Redesign] iOS Safari Copy to Clipboard doesn't seem to be working

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#4148]
http://preview-dev.nugettest.org/packages/Newtonsoft.Json/10.0.2

Clicking on copy, shows "Copied" message. However, it doesn't seem to be in clipboard, when I try to paste the message in iCloud Notes.

**Comment by joelverhagen** [comment]
I'm going to "won't fix" this for now until there is some customer input.
https://stackoverflow.com/a/34046084
