### ISSUE TITLE
Vertical scroll bar on right side is too close to content

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4149]
![image](https://user-images.githubusercontent.com/94054/27156341-9352c9a0-5111-11e7-946c-24f591a80d85.png)

**Comment by scottbommarito** [comment]
I was only able to reproduce this on IE, and only on very small screen sizes. This seems more like a bug with IE 11 than something we should actively try to fix.

**Comment by joelverhagen** [comment]
Seems fine.
