### ISSUE TITLE
[Redesign] Spinning loading indicator does not spin in Edge

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4150]
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage?groupby=ClientName
No high contrast, logged out.
Try clicking the checkboxes, notice that loading indicator appears, but does not move

**Comment by ryuyu** [comment]
Apparently, Edge doesn't support animations on SVGs.
See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8487752/

**Comment by ryuyu** [comment]
Addressed with [Redesign]Fix loading Spinner in Edge/IE #4398
