### ISSUE TITLE
No horizontal scroll bars in Edge when window is narrowest

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4155]
https://preview-dev.nugettest.org/errors/404
no high contrast, make window as narrow as possible:

![image](https://user-images.githubusercontent.com/102933/27156651-d7c53ea0-5112-11e7-9718-5765d927a22f.png)

Notice text is cut, no scroll bars on screen.

But, it kind of works on other pages:
https://preview-dev.nugettest.org/packages

![image](https://user-images.githubusercontent.com/102933/27156677-0464642c-5113-11e7-99f7-4a4279331d01.png)

Notice, horizontal scroll bar is present, vertical is not

**Comment by scottbommarito** [comment]
After doing some investigations, this seems like a bug in Edge and not something we can easily or reasonably fix.
