### ISSUE TITLE
Sometimes the download number is a link, sometimes not

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4157]
![image](https://user-images.githubusercontent.com/94054/27156657-e295c4b2-5112-11e7-9803-ab69a8ba4f48.png)

![image](https://user-images.githubusercontent.com/94054/27156700-24eebcb0-5113-11e7-9fb1-e8886cfbc6f5.png)

We should be consistent.

**Comment by ryuyu** [comment]
Discussed offline with Joel. We decided this discrepancy is ok.
