### ISSUE TITLE
[Redesign] Stats data truncated on Windows Phone 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#4168]
On this page  https://preview-dev.nugettest.org/stats/packages/Newtonsoft.Json?groupby=Version
The information above the graph ins truncated. (Instead of "Downloads for 15 latest packages ... ") the text is truncated.

**Comment by ryuyu** [comment]
Duplicate root cause as https://github.com/NuGet/NuGetGallery/issues/4190
