### ISSUE TITLE
[Redesign] Stats Label is Truncated on OS X Chrome

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4170]
[This page](https://preview-dev.nugettest.org/stats/packages/BaseTestPackage?groupby=ClientName) clips the "N" in the label "NuGet.Core-based Dow.."

<img width="1079" alt="screen shot 2017-06-14 at 3 20 56 pm" src="https://user-images.githubusercontent.com/737941/27157147-1f627bf4-5115-11e7-9189-1ab6bdc5b69c.png">

**Comment by ryuyu** [comment]
Addressed by #4340
