### ISSUE TITLE
[Redesign] Package statistics - show/hide is extremely slow

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4172]
Killed the page..
![image](https://user-images.githubusercontent.com/16807822/27157271-ac5424a4-5115-11e7-832a-c4f000c79563.png)

**Comment by 304NotModified** [comment]
Another option is to drop the slow KnockOut with a modern lib:

https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html
