### ISSUE TITLE
[Redesign] Statistics overview page Version Downloads graph with small window cuts off data

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4176]
![image](https://user-images.githubusercontent.com/18014088/27157487-8f27fcf6-5116-11e7-88b6-0dd97997d483.png)

Note that the "Version" and "Downloads" columns are cut off.

**Comment by ryuyu** [comment]
Addressed by [Redesign]Add Column content overflow #4399
