### ISSUE TITLE
Package stats chart labels are unreadable in high contrast in Edge

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4181]
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage?groupby=ClientName
![image](https://user-images.githubusercontent.com/102933/27157546-f3ff5624-5116-11e7-9d2c-11d72d3def12.png)

No axis labels.

When I select all, it becomes visible:
![image](https://user-images.githubusercontent.com/102933/27157569-15bfa9d0-5117-11e7-90ca-6606b28f0182.png)

**Comment by scottbommarito** [comment]
This also reproduces in Firefox.

**Comment by ryuyu** [comment]
Being addressed with https://github.com/NuGet/NuGetGallery/pull/4333
