### ISSUE TITLE
Inconsistent links in legal pages

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4193]
https://preview-dev.nugettest.org/policies/Terms
https://preview-dev.nugettest.org/policies/Privacy

At the top of the page there is a clickable link to a nuget.org web site, but all emails mentioned on all pages are not clickable. We probably should make them either all clickable or all non-clickable

![image](https://user-images.githubusercontent.com/102933/27158421-ba2841ae-511b-11e7-8591-92c2ef113790.png)

**Comment by scottbommarito** [comment]
@jonwchu is planning to fix the text of these pages when he does a pass over them

**Comment by joelverhagen** [comment]
Fixed by Jon's PR.
