### ISSUE TITLE
Inconsistent reference to a site in legal pages

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4194]
https://preview-dev.nugettest.org/policies/Terms
https://preview-dev.nugettest.org/policies/Privacy

Both are missing `www`, one uses `http` instead of `https`:

![image](https://user-images.githubusercontent.com/102933/27158588-6fdf0a00-511c-11e7-844c-042d018b928a.png) 
![image](https://user-images.githubusercontent.com/102933/27158598-7efbbe52-511c-11e7-84e2-8d72a0d3928a.png)

**Comment by scottbommarito** [comment]
@jonwchu is planning to fix the text of these pages when he does a pass over them

**Comment by joelverhagen** [comment]
Addressed by https://github.com/NuGet/NuGetGallery/pull/4339.
