### ISSUE TITLE
Some packages are listed in the gallery but not in registration

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4201]
MvcExtensions.Unity 2.00.0.484 is listed in the [gallery](https://www.nuget.org/packages/MvcExtensions.Unity/2.0.0.484) but not listed in [registration2-gz](https://api.nuget.org/v3/registration2-gz/mvcextensions.unity/2.0.0.484.json).

Twilio 2.0.2 is listed in the [gallery](https://www.nuget.org/packages/Twilio/2.0.2) but not listed in [registration2-gz](https://api.nuget.org/v3/registration2-gz/twilio/2.0.2.json).

**Comment by skofman1** [comment]
MvcExtensions.Unity 2.00.0.484 issue was caused by https://github.com/NuGet/NuGetGallery/issues/3709 
Probaby missed the reflow before, reflowed it now.
