### ISSUE TITLE
Support AAD authentication on NuGet.org

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4205]
Based on current Microsoft ID recommendations:

> It is highly recommended that all new services from Microsoft integrated with both Azure AD (work/school accounts) and MSA (personal accounts).

Right now, AAD only is used when admins log in.

**Comment by skofman1** [comment]
Sounds the same as the planned 2FA work.
@shishirx34 , can we close as duplicate?

**Comment by shishirx34** [comment]
Yes duplicate of 2FA work.

**Comment by joelverhagen** [comment]
What the duplicate issue?

**Comment by shishirx34** [comment]
https://github.com/NuGet/NuGetGallery/issues/3252
