### ISSUE TITLE
SemVer 2.0 - improve messaging for SemVer 2.0 upload and packages page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4215]
Exact messages will be provided by @anangaur 
Edit: Proving the details:

**Problem**
SemVer 2.0 packages will not be visible from legacy clients (i.e clients before NuGet 4.3 release). In order to make sure that publishers are aware that they are about to publish a SemVer 2 package, they should be warned appropriately so that this is a conscious decision and not an inadvertent one. 

Read more on [Identifying SemVer v2.0.0 Packages](https://github.com/NuGet/Home/wiki/SemVer2-support-for-nuget.org-%28server-side%29#identifying-semver-v200-packages)

One of the concerns is that a build metadata (e.g. 2.1.0**+buildmetadata**) also constitutes a Semver 2 version though this build metadata does not form the identity of the package. 

**Solution**
The idea here is to warn enough at the client (https://github.com/NuGet/Home/issues/5493) and on the NuGet.org server (this issue) when there is an intent or when the package is published.

Following is the list of cases and NuGet should identify to determine a SemVer 2 package and corresponding warning messages NuGet should output:
**Case 1:** Package has prerelease SemVer 2 versioning
**Warning1:** 
Title: This package has a SemVer2 package version
Message: This package will only be available to download with SemVer2 compatible NuGet clients, such as Visual Studio 2017 (version 15.3) and above or NuGet client 4.3 and above. [Read more](https://go.microsoft.com/fwlink/?linkid=852248)

**Case 2:** Package has a non-semver2 version, but is considered semver2 due to a dependency declaration
**Warning2**
Title: This package is considered a SemVer2 package as it has dependency on SemVer2 package(s)
Message: This package will only be available to download with SemVer2 compatible NuGet clients, such as Visual Studio 2017 (version 15.3) and above or NuGet client 4.3 and above. [Read more](https://go.microsoft.com/fwlink/?linkid=852248)

**Case 3:** Package has dependecy declared as SemVer 1 but the available dependency matching default dependency resolution Lowest itself is SemVer 2 (due to build metadata)
**Warning2** as described above.

NuGet Server should warn for the above scenarios during:
1. Package upload - Verify step
2. Package page

**Comment by xavierdecoster** [comment]
Proposal: the message should be _in your face_ right next to the submit button on the VerifyPackage page.
Awaiting the final message, here's a suggestion.

When a package has a semver2 version itself:

![image](https://user-images.githubusercontent.com/880728/27324607-0e381024-55a6-11e7-8e88-30e6fddd8b8e.png)

When a package has a non-semver2 version, but is considered semver2 due to a dependency declaration:

![image](https://user-images.githubusercontent.com/880728/27324881-e26ed62a-55a6-11e7-8326-615b04f24acb.png)

**Comment by anangaur** [comment]
Provided the scenarios we should warn for and the error messages.

**Comment by xavierdecoster** [comment]
I do want to point out that none of the server APIs are considering the package to be SemVer 2.0.0 in Case 3. 

These packages are not considered to be SemVer 2.0.0 and e.g. **NOT HIDDEN on V2 OData endpoints**, as all we check is the package's nuspec manifest. 

We also don't want to go to the database on every read operation to check whether the matching dependency happens to be SemVer 2.0.0 or not at that point in time.

This is one of the edge cases described in the [non-goals](https://github.com/NuGet/Home/wiki/SemVer2-support-for-nuget.org-%28server-side%29#non-goals) (paragraph 2) that may lead to (gracefully handled) restore failures on non-SemVer2 compatible clients.

**Comment by xavierdecoster** [comment]
Updated screenshots (including fwlink).

**Case 1**

![image](https://user-images.githubusercontent.com/880728/27575541-86bd7cf4-5b1a-11e7-8c4d-84ba1978f8fe.png)

**Case 2**

![image](https://user-images.githubusercontent.com/880728/27575635-b10a65c6-5b1a-11e7-88f1-24d242da6621.png)

**Comment by anangaur** [comment]
@xavierdecoster: What does 'gracefully handled' mean? 
I am guessing the restore will fail as it would not be able to find the dependency package version (SemVer2 due to build metadata). So user goes to this package version on NuGet.org to find out it is SemVer 2 package and hence needs the latest client?

Also if the publisher releases a newer non SemVer 2 version of the package, then the restore would continue with warning. Right?

**Comment by xavierdecoster** [comment]
Gracefully handled indeed means: it _won't crash_, and be treated as a _package not found_ causing restore failure.

Once a newer non SemVer2 version is made available, restore will just work (given the newer version does not violate the upper-bound of the dependency version range of course).

**Comment by anangaur** [comment]
Pending documentation the message link points to: https://github.com/NuGet/docs.microsoft.com-nuget/issues/376
