### ISSUE TITLE
Deployment 2017.05.07

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4257]
# Deployment 2017.05.07 (originally 6/28/2017)

**Status**: Planned

**Planned production date**: 7/5/2017

**Focus**: Force HTTPS for Gallery and Search service

**Services to Deploy**:

**Prerequisites**:
* merge force HTTPS changes in
  - [ ] NuGetDeployment;
  - [ ] Gallery;
  - [ ] Search service;

Repo |Service | INT | PROD-usnc | PROD-ussc
--- | --- | --- | --- | ---
NuGetGallery | V2 Gallery | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Search Service | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Catalog2DNX | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Catalog2Lucene | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Catalog2Registration | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Feed2Catalog | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | ImportAzureCdnStatistics | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>

**Related blog posts/docs**:
- None

**Deployed commit**: 
Search (NuGet.Services.Metadata):
- Search HTTPS redirect - https://github.com/NuGet/NuGetGallery/issues/3975

NuGetGallery:
- Gallery HTTPS redirect - https://github.com/NuGet/NuGetGallery/issues/3795
- DisplayPackage ArgNull fix - https://github.com/NuGet/NuGetGallery/issues/4204
- Improve SemVer2 upload message - https://github.com/NuGet/NuGetGallery/issues/4215
- Warn on SemVer2 upload - https://github.com/NuGet/NuGetGallery/pull/4239
- Add GoogleAnalytics events - https://github.com/NuGet/NuGetGallery/issues/4122
- Profile page fix for IsLatest issue - https://github.com/NuGet/NuGetGallery/issues/4281

NuGet.Jobs:
- ImportCDNStats user agent fix - https://github.com/NuGet/NuGetGallery/issues/3807

NuGet.Services.Metadata:
- Redundant calls to storage - https://github.com/NuGet/NuGetGallery/issues/4208

**Comment by agr** [comment]
I had merged the force HTTPS changes in all repos into dev (master in case of `NuGetDeployment`). And did a dev deployment to verify that nothing broke as a result.

As a side effect, any PROD deployment of Gallery (Search might work, but I'm not sure about that) that does NOT contain force HTTPS will fail (Health probe settings changed, old code won't work with the current health probe settings as present in NuGetDeployment master).

**Comment by chenriksson** [comment]
INT deployment is complete. Reassigning to @scottbommarito for next week's PROD deployment.
