### ISSUE TITLE
"Contact Owners" email doesn't include version

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4258]
The email sent by https://www.nuget.org/packages/{id}/{version}/ContactOwners does not include the version.

It says
```
User <user> sends the following message to the owners of Package <id>.
```

I think it should say
```
User <user> sends the following message to the owners of Package <id> <version>.
```

This is because the user chose to report a specific version of the package, so we should expose this information to the owners.

For example, if a user found a specific bug in version x of a package, they might write "This version has a bug with ...", which is not enough information for the owner to find the issue.

**Comment by robertmuehsig** [comment]
Is this "up-for-grabs"?

**Comment by skofman1** [comment]
It is now 😄

**Comment by martynas1266** [comment]
It looks like a fairly easy issue. Could I give a try on this one?

**Comment by scottbommarito** [comment]
Go ahead--that's what Up for Grabs is for!

**Comment by dvkudr** [comment]
It seems that _martynas1266_ is not going to fix it.
Could I pick this one up?

**Comment by scottbommarito** [comment]
@dvkudr yup!
