### ISSUE TITLE
Update gallery landing page to reflect VS 2017

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4276]
The landing page for NuGet.org does not contain any information for VS 2017 clients -

![capture](https://user-images.githubusercontent.com/10507120/27495609-752a4e1a-5807-11e7-87d0-e39bbb4bf8f2.PNG)

We should add some information for VS 2017 users. Otherwise, it seems that NuGet has not had any new releases since June 2016 and nothing for VS 2017. Maybe we should add the same text as on the downloads page -

```
NuGet 4.x is included in the Visual Studio 2017 installation. Latest NuGet releases are delivered as part of Visual Studio updates.

Batteries are included!
```

**Comment by anangaur** [comment]
@jonwchu Can you look at this one along with NuGet.org refresh text review?

**Comment by skofman1** [comment]
Closing since the redesign changed home page
