### ISSUE TITLE
Problems downloading big packages?

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#4277]
Please see https://github.com/Microsoft/visualfsharp/issues/3253
The package I just had problems with was: `StrawberryPerl64.5.22.2.1`
Basically it seems like the NuGet server sends 504 responses on this package, or even stops responding from time to time...

**Comment by cartermp** [comment]
This issue can prevent people from successfully contributing to the F# compiler and tools.  Not sure what the solution here is, but it would be great to get it looked at.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #5491](https://github.com/NuGet/Home/issues/5491) via [**ZenHub**](https://www.zenhub.com/)
