### ISSUE TITLE
No search filter present in UI

### ISSUE THREAD

**Issue by LarryEllis** [NuGet/NuGetGallery#4278]
I've seen a posting complaining that there are no sort options.   I also do not see a search filter, which was there on previous releases.  So what you see below:

![image](https://user-images.githubusercontent.com/1085235/27510241-4093a93c-58d2-11e7-8b80-64e40944166e.png)

is completely missing in my current build, which shows only:
![image](https://user-images.githubusercontent.com/1085235/27510253-62bc4578-58d2-11e7-9f78-f7d5f7061926.png)

Is this normal?

**Comment by skofman1** [comment]
@LarryEllis , sorting and "Include prerelease" options are not available on the Gallery. You can see https://www.nuget.org/ 

We have issues tracking adding those features: https://github.com/NuGet/NuGetGallery/issues/3845
https://github.com/NuGet/NuGetGallery/issues/2405
