### ISSUE TITLE
Manage Package Owners : add user "a" : "An unexpected error occurred!" pop-up.

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#428]
1. go to the Manage Owners page for any package you own.
2. in the Username box, type a, click Add

I get a pop-up (yuck!) with "An unexpected error occurred!".

**Comment by robertmuehsig** [comment]
Close? At least the error is not reproducible anymore.

**Comment by shishirx34** [comment]
Very old. I think safe to close. Thanks @robertmuehsig
