### ISSUE TITLE
File upload date is UTC

### ISSUE THREAD

**Issue by LarryEllis** [NuGet/NuGetGallery#4280]
The date that renders on the package details is based on UTC.   Should this be converted in the UI to local time, or is there a way to do so?

I have not been able to find a timezone configuration, if one is needed.

**Comment by skofman1** [comment]
@joelverhagen , does this repro on the redesigned page?

**Comment by joelverhagen** [comment]
Potentially related: https://github.com/NuGet/NuGetGallery/issues/4084

**Comment by joelverhagen** [comment]
Are you looking at https://www.nuget.org for this? If so, all of the timestamp we store internally should be UTC. It's a view or display concern of what timezone it should be converted to for human readability. In our website redesign (currently in progress), these timestamps are converted to browser local time using moment.js. 

Could you take a look at our preview site and let me know if it looks better for you?
https://preview.nuget.org/packages/Newtonsoft.Json/

Also, could you provide a screenshot or specific example of this?

**Comment by joelverhagen** [comment]
This is resolved in the redesign. 

The server sends down timestamps in UTC. Then the client (browser) converts these UTC timestamps to relative times (11 hours ago) with respect to the browser's local time.

**Comment by ctolkien** [comment]
![image](https://user-images.githubusercontent.com/515955/28394404-3696d98c-6d30-11e7-9745-72791ee43a61.png)

With the current preview build - this is not correct. I just pushed a new package live and it's out by 10 hours (which is our UTC offset).

**Comment by joelverhagen** [comment]
I'll take another look -- thanks for the heads up!

**Comment by joelverhagen** [comment]
Resolved but not yet deployed.
