### ISSUE TITLE
Add ReadMe and RepoUrl to nupkg from HandlePackageEdits

### ISSUE THREAD

**Issue by laurenshen** [NuGet/NuGetGallery#4301]
- Support packing ReadMe.md into nupkg
- Support editing/adding repositoryUrl to nuspec

**Comment by maartenba** [comment]
Regarding README, I that an official spec? If so I'd like to learn what it is and how it will work. If not official, same questions actually :-) Would be nice as an addition to MyGet, too.

**Comment by maartenba** [comment]
And others in the ecosystem of course.

**Comment by anangaur** [comment]
This is an intern project and irrespective of whether its official or not, I agree, we can have the spec in the public domain. 
/cc @jonwchu

**Comment by maartenba** [comment]
Any news on a spec? Seeing commits and PR's related to this.

**Comment by anangaur** [comment]
https://github.com/NuGet/Home/wiki/Package-README.md-support

**Comment by maartenba** [comment]
Thanks!

**Comment by chenriksson** [comment]
Changes to nuspec / nupkg out of scope for this iteration. Initial README.md support scoped as Gallery experience with upload/edit support.
