### ISSUE TITLE
New lines in package description

### ISSUE THREAD

**Issue by kubakista** [NuGet/NuGetGallery#4313]
Hello,

I am trying to add simple new lines into package description, but it seems like that hitting "enter" causes new paragraph instead of new lines.

It happens only in description, release notes are fine.

I took a screenshot from "Editing" page and from package page for comparison.

<img width="1690" alt="nuget" src="https://user-images.githubusercontent.com/1637770/27771253-a0534c54-5f4b-11e7-8ce4-39551b91f437.png">

**Comment by skofman1** [comment]
@jver, is this something that will happened in the new design as well?

**Comment by joelverhagen** [comment]
I did not explicitly fix it. We can put it in the redesign backlog to consider at the end or punt to an unrelated epic.

**Comment by joelverhagen** [comment]
I have fixed this on the website redesign. The change should be available on https://preview.nuget.org later this week.
