### ISSUE TITLE
Edit Profile : Have a way to cancel email change

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#432]
1. I went to my profile page. https://preview.nuget.org/account/Edit
2. change my email.
3. go back to the page.

It looks  like this :

"
Edit Profile

You recently requested to change your email address to aldion@<mydomain>.ca. This change will take effect when you confirm the address. Check your inbox (or spam folder) for an email with a confirmation link.

Email
aldion@<mydomain>.com
"

not too harmful but there is no way to cancel (get rid of that message) if I don't own that email address unless I change to another address that I own (putting the old one back is ignored), confirm it, then switch back to the old one.

**Comment by hbrock** [comment]
Should this be closed because of ##2230?

**Comment by maartenba** [comment]
Yes! Good catch!
