### ISSUE TITLE
Antiforgery Token verification fails on http

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#4322]
Currently, it would appear that the antiforgery token verification fails when accessing via http, and not https, resulting in erroneous 400's.

This appears to be caused by the token not being added to the cookie that is sent in the request.
The response for the page request sends the token cookie, but it appears to have a "secure" tag on it, causing the browser to not send it when submitting the requests over http.

**Comment by skofman1** [comment]
we enforced HTTPs on nuget.org. What's the impact here?
If the issue is with local debugging/private deployment changing this config: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L253
will resolve it.
