### ISSUE TITLE
Choosing package list view trash icon leads to failure path

### ISSUE THREAD

**Issue by iancooper** [NuGet/NuGetGallery#4323]
## To Recreate

* Go to the Manage My Packages page. 
* Click on the Trash Icon.
* Attempt to unlist package (unselect check box and click save)

## Observered behaviour

* Oops error page

## Expected behaviour

* For my part I believed that clicking this trash icon would unlist the whole package (not just versions of the package). In fact, I think it tries to unlist just the current package.
* EIther way, it should not error

## Additional Information
* Sometimes you want to remove a whole package i.e. all versions. There is no easy way to do this, and there ought to be.

**Comment by skofman1** [comment]
Thanks for reporting! Working on it.
