### ISSUE TITLE
[Redesign] Drag and drop package to upload field does not work

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4360]
Steps:
1. Log in
1. Go to package upload page
1. Drag and drop a .nupkg from your desktop onto the upload field

Old site worked:

![image](https://user-images.githubusercontent.com/94054/28035871-02aeebae-656b-11e7-906a-3eb5412da6ff.png)

New site in Chrome treats the drag and drop as a file download.

**Comment by ryuyu** [comment]
Being addressed with https://github.com/NuGet/NuGetGallery/pull/4366
