### ISSUE TITLE
Heavily weight download count in search results

### ISSUE THREAD

**Issue by davkean** [NuGet/NuGetGallery#4368]
This has frustrated me greatly for years, NuGet.org (and Managed NuGet Packages search) should heavily weight download count. Searching for https://www.nuget.org/packages?q=Benchmark, returns 10 packages with a combined download count of 13,826 before you even see https://www.nuget.org/packages/BenchmarkDotNet/ with >170,000 downloads.

It even lists https://www.nuget.org/packages/BenchmarkDotNet.TestDriven before it (with 95 downloads) , even though they have the same name but with ".TestDriven" in the name.

I would expect results similar to a search engine, if I try [Google](https://www.google.com.au/webhp#q=site:nuget.org+benchmark), it lists BenchmarkIt, following immediately by BenchmarkDotNet.

**Comment by skofman1** [comment]
Hi @davkean , NuGet.org search results are heavily based on popularity. Unfortunately, the current popularity calculation is based on partial information, and is essential incorrect: https://github.com/NuGet/NuGetGallery/issues/3778

We are investigating how to fix this issue and provide accurate search results. You can track the attached issue for updates.
