### ISSUE TITLE
Unable to unlist my packages due to an error "Sorry, an error occurred while processing your request."

### ISSUE THREAD

**Issue by nick301** [NuGet/NuGetGallery#4374]
Dear Team, 
I have created some Nuget Packages and these packages is no longer required, hence wanted to unlist/delete my package. But, in doing so, I get an error that **_"Sorry, an error occurred while processing your request.
Error: Oh no, we broke something!"_**

Hence, please help me deleting the package. For reference, I have attached the screenshot of the error.

Thanks and regards,
Nishant Kumar
![errorwhiledeleting](https://user-images.githubusercontent.com/30075842/28102768-1bde1c96-66ef-11e7-884a-57137c9abeec.png)

**Comment by anangaur** [comment]
Is this consistent? Roughly what time did you try this operation and which time-zone? Btw which packages do you wish to unlist?

**Comment by nick301** [comment]
Hi,
Yes. This error is consistent. Following are the details:
1. Package name : People.API
2. Time of the attempt to delete the package :  11-Jul-2017(tried several times, but time is not remembered) and 12-07-2017 at 11:27am (India Time) 

I wish to unlist two of my packages, namely People.API and People.API.Homologation. 

Regards,
Nishant Kumar

**Comment by anangaur** [comment]
Thanks @nick301 for the additional information. We will take a look at the possible causes/issues here and get back. Do give us a day's time. Hope this the unlisting of the packages is not so urgent?

**Comment by nick301** [comment]
Thanks @anangaur . Really appreciate the help. If the unlisting of the package can be done by tomorrow, then it will be best.

**Comment by anangaur** [comment]
@nick301 Thanks for the patience. The "People.API" package has been unlisted as requested.

**Comment by nick301** [comment]
Hi @anangaur. Thanks for unlisting the People.API. 
Requesting you to do the same for other package named **People.API.Homologation** also, which I mentioned in my earlier comments.
Thanks in advance.

**Comment by anangaur** [comment]
Done.
