### ISSUE TITLE
Add Bitbucket to Repository URL autocomplete

### ISSUE THREAD

**Issue by fayrose** [NuGet/NuGetGallery#4386]
Currently, if one enters a Github repository link in the repository URL field upon upload, it will autocomplete the ReadMe Url field to point to that repo's raw ReadMe file. Can we add bitbucket to this as well?

In async-file-upload.js, add the following to filleReadMeUrl:

var bitbucketRegex = /^(http(s)?:\/\/)?([a-zA-Z0-9]+\.)?bitbucket\.org\/([a-zA-Z0-9])+\/([a-zA-Z0-9])+(\/)?$/;

...

...else if (bitbucketRegex.text(repositoryUrl)) {
			return repositoryUrl + "raw/default/README.md";
}...

**Comment by skofman1** [comment]
Per https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg we will no longer allow uploading documentation from Gallery UI. Closing.
