### ISSUE TITLE
Support Azure Blob Storage for storing packings

### ISSUE THREAD

**Issue by kieronlanning** [NuGet/NuGetGallery#4388]
To support hosting in the Azure platform more simply, support storing Azure Blob Storage as a package source, not just the local disk.

**Comment by maartenba** [comment]
This can be configured from [Web.config](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L28)

**Comment by kieronlanning** [comment]
@maartenba Ah! I didn't realise. I mailed NuGet support yesterday and they suggested adding it as an issue. I'll investigate and close. Thanks.
