### ISSUE TITLE
Download stats are not updating as of 2017-06-12

### ISSUE THREAD

**Issue by rianjs** [NuGet/NuGetGallery#4389]
My [package download totals](https://www.nuget.org/packages/Ical.Net/) were:
* July 11: 55,605
* July 12: 55,615

And they haven't moved since. I suspect something went wrong between July 11 and July 12, because I haven't had a day with just 10 downloads since before I started keeping track six months ago.

This is the ~second time in the last month that stats updates have died.

**Comment by loic-sharma** [comment]
It seems like your stats have been updated now. Feel free to reopen the issue if you encounter more problems!
