### ISSUE TITLE
Got 504 time out error while using cloud foundry to push a dotnet app with dotnet buildpack

### ISSUE THREAD

**Issue by DavinZhang** [NuGet/NuGetGallery#4401]
**This is the buildpack version I am using. 1.0.13**
_zhang.yepeng-bl@public01-boshcli:~/myapps/dotnet$ cf buildpacks
Getting buildpacks...
buildpack                                     position   enabled   locked   filename
liberty-for-java                              1          true      false    buildpack_liberty-for-java_v3.9-20170419-1403-offline.zip
sdk-for-nodejs                                2          true      false    buildpack_sdk-for-nodejs_v3.12-20170505-0656.zip
dotnet-core                                   3          true      false    buildpack_dotnet-core_v1.0.13-20170330-1023.zip_

**below is the error log when I pushed the app using "cf push $my_app_name"**

_log : Restoring packages for /tmp/app/src/dotnetCloudantWebstarter/project.json...
STG/0  log : Response status code does not indicate success: 504 (Gateway Timeout).
STG/0  log : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg'.
STG/0  log : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg'.
STG/0  log : Response status code does not indicate success: 504 (Gateway Timeout).
STG/0  error: Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg'.
STG/0  error: Response status code does not indicate success: 504 (Gateway Timeout).
STG/0  error: Unable to load package 'System.Private.DataContractSerialization'.
STG/0  FAILED: Restoring dependencies with Dotnet CLI failed, command failed, exit status 1
STG/0  FAILED: command failed, exit status 1
STG/0  Failed to compile droplet
STG/0  Exit status 223
STG/0  Staging failed: Exited with status 223
STG/0  Destroying container
API/0  Failed to stage application: staging failed
STG/0  Successfully destroyed container_

**It appears to be the nuget source is not accessible
so I use curl -I https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg"to test whether I can access this from my personal computer, but failed with 504**
_# Davin @ zhangyepengdeMacBook-Pro in ~ [14:41:38] 
$ curl -I https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg
HTTP/1.1 504 Gateway Timeout
Content-Type: text/html
Content-Length: 357
Date: Sat, 15 Jul 2017 07:09:46 GMT
Server: ECLF (hhp/9A8C)_

**and I changed the build pack version using cf push $my_app_name -b https://github.com/cloudfoundry/dotnet-core-buildpack.git
this buildpack's version is 1.0.22 which didn't work and showed the same error**
     _zhang.yepeng-bl@public01-boshcli:~/myapps/dotnet$ cf push davindotnettest -b https://github.com/cloudfoundry/dotnet-core-buildpack.git
       Decompressing 100% 8083 ms
       Expanding 100% 7641 ms
       log  : Restoring packages for /tmp/app/src/dotnetCloudantWebstarter/project.json...
       log  : Failed to download package from ''.https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg
       log  : Response status code does not indicate success: 504 (Gateway Timeout).
       log  : Failed to download package from ''.https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg
       log  : Response status code does not indicate success: 504 (Gateway Timeout).
       error: Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.private.datacontractserialization/4.1.1/system.private.datacontractserialization.4.1.1.nupkg'.
       error: Response status code does not indicate success: 504 (Gateway Timeout).
       error: Unable to load package 'System.Private.DataContractSerialization'.
       FAILED: command failed, exit status 1
       FAILED: Restoring dependencies with Dotnet CLI failed, command failed, exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container
FAILED
Error restarting application: BuildpackCompileFailed_

Any idea？？TIA

**Comment by doublnt** [comment]
I have the same issue when i restore package

**Comment by doublnt** [comment]
It works now

**Comment by DavinZhang** [comment]
@doublnt   yeah, Now it works too. but it repeatedly to be like this these two days

**Comment by cristinamanum** [comment]
@DavinZhang if the issue reproduces again please send us the information mentioned at [Why can't I download/upload packages to nuget.org?](https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#managing-packages-in-nuget.org)  . It will help us diagnose the problem.

**Comment by skofman1** [comment]
@doublnt , @DavinZhang , does the issue still reproduce? Please reopen it if needed.
