### ISSUE TITLE
Secure Push Policy Breaks End-To-End Tests

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4404]
If the account that is used for end-to-end tests has the secure push policy, the [`GalleryClient`](https://github.com/NuGet/NuGet.Services.EndToEnd/blob/dev/src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs)'s `PushAsync` method will throw the following exception:

    System.Net.Http.HttpRequestException: Response status code does not indicate success: 400
    (Your account requires client version '4.1.0' or higher to be able to push packages.
    Please contact support@nuget.org to get more details.).

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #613](https://github.com/NuGet/Engineering/issues/613) via [**ZenHub**](https://www.zenhub.com/)
