### ISSUE TITLE
[Redesign] Package edit - submit-button enabled only by focus change

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#4418]
I noticed that the submit button on package edit page is only enabled when I change something *and* change the focus to the next control. It would be better if the trigger would be a keydown event, because it might confuse people like me ;)

Repo:
1. Edit a package
1. Click in the package title input
1. Change the title
1. Try to click on submit

Browser: Chrome 58 on macos.

**Comment by joelverhagen** [comment]
Thanks for the tip, @robertmuehsig! Always happy to see your feedback and contributions 😄.

**Comment by joelverhagen** [comment]
Resolved. Not yet deployed.
