### ISSUE TITLE
[Redesign] Packages page is not mobile friendly.

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/NuGetGallery#4419]
The new NuGet.org looks great - big improvement!

The site seems to be mostly mobile friendly, with the exception of the package index page (/packages) which looks like this. I assume this is just an oversight.

**Comment by ChrisMaddock** [comment]
![](http://i.imgur.com/yHBTswB.jpg)

I've tried this in both Chrome and Safari on iOS 10.

**Comment by joelverhagen** [comment]
Resolved and deployed to https://preview.nuget.org/.

**Comment by ChrisMaddock** [comment]
Great - thanks!
