### ISSUE TITLE
[Redesign] Consider reducing whitespace on the search results page

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4421]
https://twitter.com/Nick_Craver/status/887709596281909249

From @NickCraver 

> I like the new @nuget layout, but not the copious amounts of whitespace. Here are search results with that toned down (vs. current):

Suggestion:

![image](https://user-images.githubusercontent.com/94054/28379589-0fda2afa-6c69-11e7-8b5e-54ce5881e572.png)

**Comment by joelverhagen** [comment]
Another optimization here is making sure the heading of the package title/ID has the same top baseline as the image. Right now, it looks like the heading is a little lower than the image.

**Comment by NickCraver** [comment]
There's a related alignment issue:
Note that the results are slightly wider than the rest of the page due to the negative margins in `.row` here:
```css
.row {
    margin-right: -15px;
    margin-left: -15px;
}
```

**Comment by joelverhagen** [comment]
Improved. Not yet deployed. Will keep an eye on further feedback.
