### ISSUE TITLE
[Redesign] Horizontal rule at the top of the packages page is narrower than the others

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4425]
https://twitter.com/Nick_Craver/status/887709801731457024

From @NickCraver 

> @nuget also: the width differs between top and results, see how the gray bars get wider after the header?

**Comment by NickCraver** [comment]
See for cause: https://github.com/NuGet/NuGetGallery/issues/4421#issuecomment-316456204

**Comment by joelverhagen** [comment]
Resolved. Not yet deployed.
