### ISSUE TITLE
V3 jobs should be hardened to index.json changes

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4430]
We have a couple instances in which direct links to V3 resources are passed as arguments to jobs.

For example, Catalog2Lucene takes in a direct link to the cursor of one of our Catalog2Registration containers.

These jobs should fetch these V3 resources from `index.json`, so that if the containers change, the jobs automatically pull in the correct cursor values.

For example, when we moved from registration1 to registration2 (because of semver2), the V3 monitoring job failed some packages because it was using registration1's cursor while checking registration2.

**Comment by joelverhagen** [comment]
This should be optional integration. There are cases when you want to run the job before something is mentioned in the index.json.

**Comment by skofman1** [comment]
>
