### ISSUE TITLE
[Redesign] Manage packages page is too long (unusable) for people with many packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4431]
Feedback from @onovotny offline:

1. When you have many packages, the "Manage Packages" page it way too long. Part of this is due to the fact that each item in the list takes up a lot of vertical real estate. 
1. The order right now seems random or at least useless.

**Comment by joelverhagen** [comment]
Spoke to @jonwchu and @ryuyu about this and we have three suggestions.

1. Sort alphabetically by package ID or title.
1. Provide a "live search" box at the top of the page to limit the items under the listed and unlisted sections. This would be partial matching on ID and title.
1. Reduce the whitespace, per https://github.com/NuGet/NuGetGallery/issues/4421.

Thoughts, @onovotny?

**Comment by onovotny** [comment]
The above things are all a great start. I would say though that the No. 1 thing is to bring back a "list" view though. 

Consider this: the view that's there for other users is a "marketing/info" view. It shows the title, description, etc. As an author, you can skip the marketing and just show me the details. Give me the "Excel view" if you will.

**Comment by joelverhagen** [comment]
I see. Perhaps another middle ground would be not showing tags or description on the manage packages page? Those seem pretty uninteresting to the package author.

**Comment by onovotny** [comment]
TBH, the single-line list is already about 2 browser pages. Anything more than that is even more space.

**Comment by NickCraver** [comment]
I'm with @onovotny here, I don't have that many packages and a PDF print (for common comparison) went from 2 pages to 8 pages. Please bring back the list view. Anything more is just too verbose and adds little. 

@joelverhagen Your point about the tags is correct, but it's also true for all other metadata. I don't need to see all the information about my packages on the main view, they're *my* packages, I'm familiar with them already. I *just want to manage the package*. Making me scroll a bunch to do the only thing I want to do is a real regression here.

I'd like to add to this: the package ID has been removed here, we're now only showing the title. I definitely want to manage by the package ID. That's the key for everything in the stack. Downloads was also useful. The latest version showing in the new UI is an improvement IMO, I'd like to see this column in a list UI.

If bringing back the list view, request: please commify the numbers. It's one of the very few places where we're lacking commas. The total download count at the top of the current UI isn't comma-ed either. It's also wrong but I recall seeing an issue for that. Also please allow sorting of the list, I have no explanation for what the current sort is in the old or new site. What is that order? Please default to alphabetical. I also suggest rendering a small version of the package logo in the list view. There's room and this would make things a bit easier for many use cases (especially when many packages are involved in a single "product").

...should I make an issue with all these laid out as bullets? I'm just laying out everything I see here to get it down.

**Comment by joelverhagen** [comment]
> ...should I make an issue with all these laid out as bullets? I'm just laying out everything I see here to get it down.

This format is fine 😄.

To summarize, it sounds like we should make a condensed table with:

- Small logo
- Package ID (I am thinking of excluding title here, as ID makes more send on the owner views)
- Comma separated downloads (total for the ID)
- Latest version
- Controls
  - Edit
  - Manage Owners
  - Delete (Unlist)

Also commify the total download count at the top of the page.

> What is that order?

I think it is using the clustered index of the underlying table. I'm pretty sure we're not specifying the order at all. 😨 

Thanks for all the rapid feedback, guys. I'll work with the team to come up with a mock-up and have something out soon.

**Comment by joelverhagen** [comment]
@onovotny @NickCraver, thoughts?

![image](https://user-images.githubusercontent.com/94054/28548454-f4e77d96-7088-11e7-8a99-f82d2bea3aa9.png)

**Comment by NickCraver** [comment]
I love the look! I'm concerned about many-author packages, but if that's allowed to wrap a line I think we're good. 

This is yet another huge improvement, I absolutely love seeing the speed at which you're making revisions across the board here.

**Comment by onovotny** [comment]
Agree with @NickCraver, that looks much better!

**Comment by joelverhagen** [comment]
We should relabel the "authors" column to "owners". This is the actual name of the field and aligns with the display package page. /cc @ryuyu

**Comment by joelverhagen** [comment]
Also, the download count numbers should be comma-seperated (e.g. 2,235 vs 2235).

**Comment by joelverhagen** [comment]
Also, ID should be capitalized in the table heading.

**Comment by joelverhagen** [comment]
Aside from the three polish comments mentioned above, this page is now **live** on https://preview.nuget.org/! Thanks again for the feedback!
