### ISSUE TITLE
[Redesign] Small feedbacks from Twitter and offline

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4432]
From https://twitter.com/shanselman/status/887795754021957633, offline with @unniravindranathan and @jonwchu, etc.

- [x] stats page
  - [x] "Client Version" -> NuGet Client Version"
  - [x] reverse order of client versions
- [x] footer
  - [x] headings to h3
  - [x] first row 1em
  - [x] second row is .85em
- [x] packages list
  - [x] package title height 0.9
  - [x] bold downloads: weight 500
  - [x] 5px at the top of package-details, not 10
- [x] jumbotron
  - [x] too much top padding: 5px
  - [x] check mobile too
    - [x] note there are two settings for padding-top (based on screen width)
- [x] inconsistent pagination padding
  - [x] https://twitter.com/chad_ramos/status/887804942903382017
  - [x] clear the float?

**Comment by NickCraver** [comment]
Just a small tip: you can format with "- [ ] Item" for checkboxes in issues, ideal use case! Like this:

- [x] Item 1
- [ ] Item 2
  - [x] Subitem A
  - [ ] Subitem B

**Comment by joelverhagen** [comment]
Fixed and deployed to https://preview.nuget.org/.
