### ISSUE TITLE
[Redesign] Account page form data floats to top

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#4440]
The Account page in new redesign shows the data floating to the top against the title. It should be centered.

![image](https://user-images.githubusercontent.com/1646506/28434033-d3f9e6d0-6d42-11e7-9be9-115277a2252e.png)

![image](https://user-images.githubusercontent.com/1646506/28434050-dc8151e4-6d42-11e7-8c16-3fd1ea4d217f.png)

**Comment by joelverhagen** [comment]
Fixed and deployed to https://preview.nuget.org/.
