### ISSUE TITLE
[Redesign] Packages list total is missing commas

### ISSUE THREAD

**Issue by NickCraver** [NuGet/NuGetGallery#4444]
The top of [the /packages route](https://preview.nuget.org/packages) is missing a comma:

<img width="689" alt="screen shot 2017-07-20 at 20 02 20" src="https://user-images.githubusercontent.com/454813/28443784-5f9941fc-6d86-11e7-82e0-e6db461bc447.png">

Since all of these are getting love, logging it here.

/cc @joelverhagen

**Comment by NickCraver** [comment]
Hmm, note it **does** have a comma on search results, only the default view does not.

**Comment by joelverhagen** [comment]
Fixed and deployed to https://preview.nuget.org/.
