### ISSUE TITLE
JsonApiController not validating anti forgery tokens

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4452]
ManagePackageOwners.cshtml is sending a __RequestVerificationToken header for ajax posts to GetAddPackageOwnerConfirmation and AddPackageOwner, but it doesn't look like we have the validate attribute in JsonApiController.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #618](https://github.com/NuGet/Engineering/issues/618) via [**ZenHub**](https://www.zenhub.com/)
