### ISSUE TITLE
Published date/time is incorrect (probably showing UTC date)

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/NuGetGallery#4459]
The last updated date/time is incorrect. I *just* published a package, yet it says 2 hours ago. I think it doesn't translate the storage date/time to the client date/time.

![image](https://user-images.githubusercontent.com/1246444/28531309-c8625382-7096-11e7-980d-f65684e42327.png)

**Comment by joelverhagen** [comment]
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4280. Will soon be addressed by https://github.com/NuGet/NuGetGallery/pull/4457. Thanks!
