### ISSUE TITLE
[Redesign] Long package names overflow into the right column

### ISSUE THREAD

**Issue by xt0rted** [NuGet/NuGetGallery#4470]
The issue can be seen with the [Microsoft.WindowsAzure.ConfigurationManager](https://preview.nuget.org/packages/Microsoft.WindowsAzure.ConfigurationManager/) package and looks like so.

![image](https://user-images.githubusercontent.com/831974/28642302-f5d5fe1a-721f-11e7-9757-e3689651bdc7.png)

**Comment by joelverhagen** [comment]
Great catch! Working on the fix now 😄.

**Comment by joelverhagen** [comment]
Fixed and deployed to https://preview.nuget.org/.
