### ISSUE TITLE
Search Service does not actually log index reopen exceptions

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4473]
The search service only [logs the message "Search index reopen failed with an exception"](https://github.com/NuGet/NuGet.Services.Metadata/blob/e4cc26618201b228dd1b8378f1a892e65d3e0dd9/src/NuGet.Services.BasicSearch/Startup.cs#L219) on exceptions thrown during index reloads

**Comment by loic-sharma** [comment]
Same with [InitializeSearcherManager](https://github.com/NuGet/NuGet.Services.Metadata/blob/e4cc26618201b228dd1b8378f1a892e65d3e0dd9/src/NuGet.Services.BasicSearch/Startup.cs#L249)

**Comment by skofman1** [comment]
This should be high pri since it blocks investigation into index load issues.
