### ISSUE TITLE
Enhanced package upload workflow

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#4478]
Status: **Implemented**

The NuGet package upload workflow is being enhanced as we introduce package validation. Let's use this issue to discuss the spec. 

[Enhanced package upload workflow](https://github.com/NuGet/Home/wiki/Enhanced-package-upload-workflow)

**Comment by anangaur** [comment]
How does the CLI experience look like? Should the CLI experience on push give out the URL of the package to monitor?

**Comment by karann-msft** [comment]
The CLI says push succeeded. It doesn't say anything about publishing. It also gives out the URL. 

```
Pushing myAwesomeLib.1.0.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 15028ms
Your package was pushed.
```

**Comment by anangaur** [comment]
I think it should give out the URL of the package.

**Comment by skofman1** [comment]
@karann-msft , @anangaur , can we close?

**Comment by karann-msft** [comment]
created this issue to track CLI feedback - https://github.com/NuGet/Home/issues/6333

Closing this issue.
