### ISSUE TITLE
DEV and INT service indexes should not mention vo.msecnd.net

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4485]
Steps.

1. Navigate to the service index for each environment:
    - PROD: https://api.nuget.org/v3/index.json
    - INT: http://api.int.nugettest.org/v3-index/index.json
    - DEV: http://api.dev.nugettest.org/v3-index/index.json
1. Search for "vo.msecnd.net".

On PROD, no such domains exist since all resources are behind "nuget.org" subdomains.

ON INT and PROD, this is not so. We should have consistency here. In every way possible, DEV and INT should mirror PROD, including in DNS configuration.

**Comment by joelverhagen** [comment]
Note that we do not have an SSL cert for "*.int.nugettest.org" or "*.dev.nugettest.org" right now. We would either need to rename the domains to "api-int.nugettest.org" etc or add these patterns to the CDN SSL cert.

**Comment by skofman1** [comment]
This was done.
