### ISSUE TITLE
[Redesign] Revisit font sizes on the redesign site

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4491]
There was a lot of feedback on the font sizes on the preview site. Major points of feedback:

1. [x] ID size on the search results - too big
1. [x] Footer text - too small

**Comment by anangaur** [comment]
Smaller font size for the Package Ids and separator line removed:
![image](https://user-images.githubusercontent.com/14800916/29131487-e2a2623a-7ce1-11e7-9b41-f1a16434dc2e.png)
