### ISSUE TITLE
Deploy three jobs from NuGet.Jobs so acceptable version of Newtonsoft.Json is used

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4496]
Newtonsoft.Json was updated in three projects from the NuGet.Jobs repository:

1. SnapshotAzureBlob
1. CopyAzureContainer
1. NuGetCDNRedirect

These need to be deployed during the regular sprint deployment.

**Comment by joelverhagen** [comment]
Related engineering issue: https://github.com/NuGet/Engineering/issues/648
PR: https://github.com/NuGet/NuGet.Jobs/pull/188

**Comment by shishirx34** [comment]
I am not aware of the deployments of `SnapshotAzureBlob` and `CopyAzureContainer` jobs deployments, don't see any references in OneNote either. Putting these deployments on hold for next week when @cristinamanum would be able to elaborate/deploy.

**Comment by joelverhagen** [comment]
Spoke to @cristinamanum, SnapshotAzureBlob is an ops tool (no deployment) and the other two were deployed.
