### ISSUE TITLE
Provide capability to filter on .NET Core & .NET Framework when searching

### ISSUE THREAD

**Issue by tomkerkhove** [NuGet/NuGetGallery#4502]
Provide capability to filter on .NET Core & .NET Framework when searching since I'm only interested in one of both for certain scenarios

![screenshot_1](https://user-images.githubusercontent.com/4345663/28909829-6952f7b6-782a-11e7-834e-e81cd25a46a7.png)

**Comment by skofman1** [comment]
This is duplicate of: https://github.com/NuGet/NuGetGallery/issues/3098
