### ISSUE TITLE
Average Download stats calculated incorrectly.

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#4513]
@forki noticed the following

![e87bbe56-448b-11e7-9a17-1f3b403c872d.png](https://cloud.githubusercontent.com/assets/57396/26553432/e87bbe56-448b-11e7-9a17-1f3b403c872d.png)

in https://github.com/NuGet/NuGetGallery/issues/3973

Out of curiosity I did a bit of math and excel work and it seems that the average number is calculated like this:

`TotalDownloads(P) / DaysSinceMinVersion(P)`

instead of

`TotalDownloads(P) / DaysSinceFirstVersion(P)`

Now average download stats on FAKE are broken because we accidentally released 

`FAKE                                     1.0.0-alpha-10 | 42 | Samstag, 27. Mai 2017
-- | -- | --`

which is about 70 days old instead of 

`FAKE                                     1.46.1 | 527 | Montag, 21. Februar 2011
-- | -- | --`

which is actually the oldest release and 2357 days old.

This leads to an average daily download count of around `427` instead of `14371`:

![image](https://user-images.githubusercontent.com/1866463/28994703-119dae42-79d5-11e7-8191-05c59a1b6091.png)

![image](https://user-images.githubusercontent.com/1866463/28994707-1f91a918-79d5-11e7-8081-02f1718eab86.png)

I completely agree with https://github.com/NuGet/NuGetGallery/issues/3973 that additional stats about a more recent time-frame are actually more useful than a total number. But if we report it - it should be at least correct.

**Comment by matthid** [comment]
One more thing. It's not fixed in the new Preview:
![image](https://user-images.githubusercontent.com/1866463/28994781-985ca310-79d6-11e7-8a3a-7b5a1c8023d1.png)

**Comment by xavierdecoster** [comment]
@joelverhagen https://github.com/NuGet/NuGetGallery/pull/2943 is the original PR that added the feature, and https://github.com/NuGet/NuGetGallery/pull/4040 is the recent change we did. The recent change ensured that the label shows `<1` when the average was below 1. That change was a UI fix and is unrelated to this issue, as the average already was calculated.

**Comment by xavierdecoster** [comment]
Found an older [commit](https://github.com/NuGet/NuGetGallery/commit/12e96a03ea8e7596949732fb806cc3ae3d93472d) that updated the calculation to use the last entry in the package history ordered by version descending. 
This effectively considers the **lowest** version number, irrespective of the order in which packages were pushed to the server.

This indeed should be updated to consider the **oldest** package version instead.
