### ISSUE TITLE
MSBuild task user agent string update

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#4518]
Restore has been updated to use different user agent strings, nuget.org stats should include the following:

* `NuGet .NET Core MSBuild Task`
* `NuGet Desktop MSBuild Task`

//cc @xavierdecoster

**Comment by xavierdecoster** [comment]
@emgarten looking at the diff here https://github.com/NuGet/NuGet.Client/pull/1614/files, shouldn't this become:

* `NuGet .NET Core MSBuild Task`
* `NuGet Desktop MSBuild Task`

**Comment by emgarten** [comment]
@xavierdecoster yes, thank you! I've updated the original description.
