### ISSUE TITLE
Add HSTS and SSL redirect to all *.nugettest.org and *.nuget.org domains

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4519]
Remaining:

- [x] apidev.nugettest.org
- [x] apiint.nugettest.org
- [x] packages.nuget.org (https://github.com/NuGet/NuGetGallery/issues/4515)
- [x] blog.nuget.org
- [x] dist.nuget.org
- [x] api.nuget.org

**Comment by loic-sharma** [comment]
CDN has a rule that applies HSTS header on all responses, and another rule that redirects blog/dist HTTP requests to HTTPS. Also,

**Comment by loic-sharma** [comment]
Added rule to `api.nuget.org`. Will verify once rule is applied.
