### ISSUE TITLE
Investigate Usefulness of ApiController's Team Endpoint

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4522]
The [Team](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/ApiController.cs#L616) endpoint seems to be unused. Investigate if it is still needed, and if it isn't, delete it.

**Comment by scottbommarito** [comment]
Found it.

https://www.nuget.org/api/v2/team

Not sure if it has any real purpose, however. The list isn't regularly updated and we frequently find that it's missing people. Anybody who wants to know the GitHub usernames of our team members should go to our GitHub org and check there.

**Comment by skofman1** [comment]
Is it used? Please check AI.
