### ISSUE TITLE
Better leverage h2 via http headers

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4524]
For the new preview site have a look at the waterfall (note i am using chrome for the below)

![image](https://user-images.githubusercontent.com/122666/29100366-788371fc-7cee-11e7-8f17-73e1ee1affed.png)

Note that despite using h2 there is no Multiplexing. The reason for this is that the response headers contain no [rel=preload headers](https://caniuse.com/#feat=link-rel-preload)

you may also want to look into `dns-prefetch` and `preconnect` headers https://www.keycdn.com/blog/resource-hints/

**Comment by joelverhagen** [comment]
Great feedback, @SimonCropp, this will require some learning and investigation on our side. Thanks for the heads up! I'll leave this open until we can look into this.

**Comment by SimonCropp** [comment]
@joelverhagen TBH i am still learning as well :)

BTW check out the http headers (using chrome) on this page https://docs.particular.net/

```
<https://cdnjs.cloudflare.com>; rel=dns-prefetch, <https://cdnjs.cloudflare.com>; rel=preconnect; crossorigin, </content/js/documentation_v5.js>; rel=preload; as=script, </content/images/menu/transports-icon.svg>; rel=preload; as=image, </content/images/menu/servicepulse-icon.svg>; rel=preload; as=image, </content/images/menu/serviceinsight-icon.svg>; rel=preload; as=image, </content/images/menu/servicecontrol-icon.svg>; rel=preload; as=image, </content/images/menu/samples-icon.svg>; rel=preload; as=image, </content/images/menu/persistence-icon.svg>; rel=preload; as=image, </content/images/menu/nservicebus-icon.svg>; rel=preload; as=image, </content/images/particular_v1.svg>; rel=preload; as=image, </content/images/logo_v1.svg>; rel=preload; as=image, </content/css/style_v6.css>; rel=preload; as=style, <https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css>; rel=preload; as=style, <https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff2>; rel=preload; as=font; crossorigin, <https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js>; rel=preload; as=script, <https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js>; rel=preload; as=script, <https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js>; rel=preload; as=script
```

we optimise the headers based on browser support for the various headers

**Comment by SimonCropp** [comment]
been a year, and this was only a suggestion. so closing
