### ISSUE TITLE
enable gzip

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4526]
am i missing something or is gzip not enabled?

this is the new site i am looking at

**Comment by SimonCropp** [comment]
yeah it seems despite the browser requesting it the response is not gzipped

![image](https://user-images.githubusercontent.com/122666/29101100-765f4702-7cf3-11e7-8c9f-44aba482b995.png)

**Comment by joelverhagen** [comment]
This should be investigated for sure, but my initial guess is that "binary" data types are not gzipped by server side. I think SVG is lumped into that erroneously because it is an image.

**Comment by SimonCropp** [comment]
```
%windir%\system32\inetsrv\appcmd set config  -section:system.webServer/httpCompression /+"dynamicTypes.[mimeType='image/svg+xml',enabled='True']" /commit:apphost >> "%TEMP%\StartupLog.txt" 2>&1
```
