### ISSUE TITLE
use unabiguous dates 

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4529]
https://preview.nuget.org/stats

![image](https://user-images.githubusercontent.com/122666/29101739-ac6ff9aa-7cf7-11e7-8d3f-8ff11933a35b.png)

eg `yyyy/mm/dd`

**Comment by joelverhagen** [comment]
In general, we intentionally use the user's locale to determine the date format, via our [`DateTimeExtensions`](https://github.com/NuGet/NuGetGallery/blob/dd19a210482572805da9d9bd19081d9a002310b1/src/NuGetGallery/Extensions/DateTimeExtensions.cs). In this particular case, however, we are using `MM/dd/yy` for all cultures, which is wrong.

The fix here is to use date format `d` instead of `MM/dd/yy`.

**Comment by SimonCropp** [comment]
But wont that use the servers datetime settings, not mine?

**Comment by joelverhagen** [comment]
MVC sets the culture based off of:
```
accept-language: en-US,en;q=0.8
```

**Comment by SimonCropp** [comment]
i dont think that is working

![image](https://user-images.githubusercontent.com/122666/29146795-8aa08b82-7da6-11e7-812c-60e7e7b6069d.png)

![image](https://user-images.githubusercontent.com/122666/29146801-96137c18-7da6-11e7-9038-15f0a6230f0e.png)

**Comment by joelverhagen** [comment]
Could you provide what your `Accept-Language` header value is? If it's `en-US`, you will see the standard Month/Day/Year format. Sorry if I miscommunicated before -- our intention is that the date format used matches the user's culture (which is not necessarily `yyyy/MM/dd`).

**Comment by SimonCropp** [comment]
`accept-language:en`

![image](https://user-images.githubusercontent.com/122666/29147135-9450025a-7da8-11e7-96af-1d22b3464f9c.png)

**Comment by SimonCropp** [comment]
> this is expected behavior then

sorry to qualify: "it is a bug"?

**Comment by cdrnet** [comment]
That doesn't seem to be working though. My Accept-Languages header is set to `en-GB,en;q=0.8,de-CH;q=0.5,de;q=0.3` and I still get served with `MM/dd/yyyy`, while I'd have expected `dd/MM/yyyy`.

**Comment by joelverhagen** [comment]
> _Update: ah, likely just not deployed yet - ignore this comment_

Yeah, I should have mentioned that! I will probably be deploying this change to the preview site today.

**Comment by joelverhagen** [comment]
@cdrnet, the change is now available on https://preview.nuget.org.

@SimonCropp, thanks for all the input here. Can we consider this case closed?

**Comment by cdrnet** [comment]
Works perfectly, thanks!

**Comment by SimonCropp** [comment]
![works](https://user-images.githubusercontent.com/122666/29197946-40ca01ae-7e83-11e7-8166-75ee0d965114.png)
