### ISSUE TITLE
[Redesign] NuGet downloads page needs the facelift

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4535]
https://dist.nuget.org/index.html  has the old look and feel. We should rev this page up too.

**Comment by jonwchu** [comment]
Downloads page was moved inside of the nuget.org domain (https://preview.nuget.org/downloads).

**Comment by joelverhagen** [comment]
Yes, @jonwchu, hit the nail on the head. Once we have deployed the redesign, we will make https://dist.nuget.org/index.html to https://www.nuget.org/downloads.

**Comment by anangaur** [comment]
Thanks for the info. Closing it
