### ISSUE TITLE
cache and calculate stats on home page

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4541]
on the home page this url gets the stats https://preview.nuget.org/stats/totals

however it is not cached

it would be better to cache it for some period and instead include a "rate of increase". so in the result include "downloads are increasing at x per hour". then an approximation of the current value can be calculated from the cached information without the need to re-get the stats.

**Comment by skofman1** [comment]
@SimonCropp , the download counts data is cached on the server side:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/StatisticsController.cs#L50

Since this calculation is updated only once in 24 hours, there is no need for an approximation.

**Comment by SimonCropp** [comment]
they are not cached 
![image](https://user-images.githubusercontent.com/122666/30628669-fc32049e-9e1a-11e7-86a7-9ebd4f790b2e.png)
