### ISSUE TITLE
request for blocker stats

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4542]
A question i have been wanting answered for a while now is "how many developers run ad blockers or anti trackers".  I think the nuget gallery would be a really good site to get an approximation of that number. Specifically i am more interested in .net/Microsoft developers so nuget gallery makes even more sense.

Now i know this is outside the scope of what the nuget team is trying to achieve, so i am asking very much form a "as a favour" perspective. Although it might make an interesting blog post for http://blog.nuget.org/ 

And i know you are very busy with the new preview site and work related to net core/standard, so i understand if this does not get prioritised for a while. And i also completely understand if you close this as "not worth the effort".

If u do decide to do this, there are a variety of ways to achieve this. for example one of the results of googling "test if an ad blockers is being used" is http://www.detectadblock.com/

**Comment by alxrz** [comment]
we ran a test a while ago when we were doing ads on stackoverflow (and paying for impressions which were affected by ad blockers). Experiment was that we put a pixel on home page and were measuring if ad blocker is enabled. Results are still somewhere in analytics - though if i'm not mistaken ratio was 32-35% of visitors.

Though there's a limitation we didn't consider- when user activity tracking and analytics is blocked. In this case an experiment should include backend tracking or requests sent to backend with results.

**Comment by anangaur** [comment]
@SimonCropp While I understand that you are keen to get this data, but IMO this is not a NuGet issue. As you rightly mentioned this would be outside the scope of NuGet work.
