### ISSUE TITLE
Resetting Password on Account with Unconfirmed Email Causes 500

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4548]
The [`ForgotPassword`](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/UsersController.cs#L177) route will result in a 500 if the account's email is unconfirmed. This is due to the `ForgotPassword` route not catching the `InvalidOperationException` that AuthenticationService's [`GeneratePasswordResetToken`](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Authentication/AuthenticationService.cs#L391) throws if the user's email address is unconfirmed.

**Comment by joelverhagen** [comment]
I will assess whether this regressed with the UI redesign.

**Comment by loic-sharma** [comment]
I did a quick git blame, it seems that this was always an issue.
