### ISSUE TITLE
NuGetGallery should support multiple Azure storage accounts

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4554]
Currently NuGetGallery usages the same storage account for many different purposes. 

- [x] table: "ElmahErrors" (exceptions from elmah)
- [x] blob container: "nuget-cdnstats"
  - [x] Totals stats
  - [x] Stats reports
  - [ ] download counts
- [x] blob container: "auditing" (auditing)
- [x] blob container: "content" (static content)
- [x] blob container: "downloads" (nuget.exe)
- [x] blob container: "packages" (uploaded packages, after submit)
- [x] blob container: "package-backups" (deleted packages)
- [x] blob container: "uploads" (uploaded packages, before submit)

**Comment by scottbommarito** [comment]
I think we can get rid of `downloads` by redirecting to dist instead.

https://github.com/NuGet/NuGetGallery/issues/4558
