### ISSUE TITLE
Redirect www.nuget.org/nuget.exe endpoint to dist

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4558]
Currently this points to a very old version of `nuget.exe` (2.8.6) hosted in a blob storage that is not used otherwise. We should either
- deprecate the endpoint if it has no use
- redirect it to `dist`

**Comment by scottbommarito** [comment]
The endpoint still has a lot of usage (13k in the last day). We should immediately redirect it to version 2.8.6 on dist and then consider migrating it to the latest version.

**Comment by anangaur** [comment]
Linking https://github.com/NuGet/NuGetGallery/issues/4559
