### ISSUE TITLE
"Remember me" option

### ISSUE THREAD

**Issue by weitzhandler** [NuGet/NuGetGallery#4566]
When signing in to NuGet, please remember my last sign-in state or show a "Remember me" checkbox on the sign-in page.
Currently the sign-in lasts only per session, which is a bit annoying.

The new design is gorgeous! Thank y'all!

**Comment by skofman1** [comment]
The sign in experience changed since we deprecated NuGet password logins in favor of MSA/AAD. If you are experiencing issues with the current sign-in, please open a new issue.

**Comment by weitzhandler** [comment]
I still experience this annoying issue to this day.
Please reopen this.
