### ISSUE TITLE
Package statistics graph contains wrong values

### ISSUE THREAD

**Issue by justdmitry** [NuGet/NuGetGallery#4571]
Graph with package download counts ([like this](https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version)) is displaying wrong values.

Version with download count "3 649 326" shows bar with height of 3, with " 700 877" downloads - bar with height of 700.

It seems that graph parses values until first space.

Here is screenshot:
![statistics-bug](https://user-images.githubusercontent.com/3540597/29405767-92deccb8-8347-11e7-825b-3a45bb37d2c6.png)

**Comment by joelverhagen** [comment]
@justdmitry, thanks for reporting this. Could you send us the "Accept-Language" header your browser is sending to NuGet.org? This can be found in Chrome developer tools, Network tab under Request Headers.

**Comment by agr** [comment]
I'd guess it's `ru-RU`.

**Comment by justdmitry** [comment]
Yes, it's ru-RU: `Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3`
