### ISSUE TITLE
Upload Page points to http://www.nuget.org instead of https://...

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#4573]
I noticed a small "bug". On the upload page you show the URL without https which might confuse people.

![image](https://user-images.githubusercontent.com/756703/29433694-8e9f77a2-83a0-11e7-901e-8b40ca6cad64.png)

The part seems to be in your configuration:

https://github.com/NuGet/NuGetGallery/blob/e72e08ab541b0b47fafc7f6e1139644258b52004/src/NuGetGallery/Views/Packages/UploadPackage.cshtml#L14

I'm not sure if this is a typo in your configuration or if this is more like an internal URL. I could imagine that the SSL handling is managed by a proxy and behind that proxy you are using HTTP and thats why this internal config entry points to http://www.nuget.org

**Comment by skofman1** [comment]
Thanks for reporting @robertmuehsig ! It's a config issue
