### ISSUE TITLE
Please put focus on the search input control when nuget.org loads

### ISSUE THREAD

**Issue by guardrex** [NuGet/NuGetGallery#4575]
I frequently show up to nuget.org with a package name on my clipboard to paste. *PLEASE* set the focus to the `search` **\<input>** element on the homepage so that when the page loads we can just paste (Ctrl-v) and hit Enter to get our package search results.

**Comment by anangaur** [comment]
Makes sense. Similar to https://github.com/NuGet/NuGetGallery/issues/4458
Today the focus goes to the search bar the moment you start typing. 
@joelverhagen can this be also enabled for Ctrl key (so that Ctrl+v can work) without hampering the accessibility requirements?

**Comment by guardrex** [comment]
I see what u mean. Thing is tho ... about 99% of the time, I'm coming in with clipboard contents to paste. It's a package that I've snipped from an online source or from a project file.

The search element just needs an `autofocus` attribute. There shouldn't be a prob with accessibility, e.g., see: http://webaim.org/blog/future-web-accessibility-html5-input-extensions/. It wouldn't be implemented here in a way that would break or confuse a screen reader. The primary purpose of the nuget.org homepage *IS* to search for packages, so setting the focus on the search box makes *perfect sense*.

Thanks for considering this (and my mouse thanks you! :smile:)

**Comment by guardrex** [comment]
This is a bit of a dupe of #4458, but imo that's *doesn't fix the problem*. :cry:

**Comment by robertmuehsig** [comment]
Whats the problem with autofocus? Worked quite well in the older portal.

**Comment by joelverhagen** [comment]
Perhaps we can `autofocus` just on the front page. Would that improve the situation for you, @guardrex? By default autofocusing the search bar on all pages could be frustrating for pages that have forms.

**Comment by guardrex** [comment]
I agree. I suspected your partial there was in use in other places; otherwise, you wouldn't have used a partial at all. I'll close and let u cats take over. Thanks for taking this into consideration.

**Comment by joelverhagen** [comment]
@guardrex, mind if I leave this open? I think it's a good idea to `autofocus` the main page. We can use this issue to track that work. Concerning the partial view, we can add a parameter to enable/disable `autofocus` I think (or perhaps do it based off of page URL).

**Comment by guardrex** [comment]
Sure.

> do it based off of page URL

Can be unstable, of course, depending on how its implemented, which is why I think a lot of devs base it either on detecting the controller that fires or by, as you say, a parameter like `ViewBag.IsHome`. My gut feel'in: Probably most reliable (and simple) to go the parameter way.

**Comment by agr** [comment]
FYI, if you are using Chrome, you can set up "Nuget package search" there like this:
![image](https://user-images.githubusercontent.com/102933/29475472-be803a00-8414-11e7-9984-56a8c2f367f6.png)
Then while in address bar you just press `n`, then space, then paste your package name and press enter, and you'll get directly to search results page. No need to visit nuget.org home page.
![image](https://user-images.githubusercontent.com/102933/29475513-ec782940-8414-11e7-8952-29353c3a8f23.png)
