### ISSUE TITLE
Package delete from the package details page does not work

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4577]
Seems to be a regression from the redesign.

![image](https://user-images.githubusercontent.com/94054/29466476-dcd15958-83f1-11e7-96b9-2eb40e7d2105.png)

Works just fine from the admin panel.

**Comment by skofman1** [comment]
Perhaps a missed merge: https://github.com/NuGet/NuGetGallery/pull/4341/files
