### ISSUE TITLE
Package Indexing - System.Security.Cryptography.OpenSsl

### ISSUE THREAD

**Issue by yaakov-h** [NuGet/NuGetGallery#4582]
Hi,

[System.Security.Cryptography.OpenSsl v4.4.0](https://www.nuget.org/packages/System.Security.Cryptography.OpenSsl/4.4.0) has the following warning:

> **This package has not been indexed yet.** It will appear in search results and will be available for install/restore after indexing is completed.

According to the versions table below, it was uploaded 9 days ago.

What's making it take so long to be indexed?

This is messing with my workflow as Paket can resolve the package, but cannot download it. I've had to manually download it for now from the Gallery website as a workaround.

**Comment by joelverhagen** [comment]
Thanks for reporting this issue, @yaakov-h. I have reflowed the package. It should now be available.
