### ISSUE TITLE
Very slow feed response times

### ISSUE THREAD

**Issue by OliverRC** [NuGet/NuGetGallery#4584]
There has been a long running issue on the performance of updating nuget packages. 
https://github.com/NuGet/Home/issues/1909#issuecomment-316933090

This comment highlights some very slow response times from nuget.org. With the feed being queried 100's of times 6.5s + response times making updating packages extremely slow.

`https://api.nuget.org/v3/registration2-gz/runtime.fedora.24-x64.runtime.native.system.security.cryptography/index.json 5095ms OK https://api.nuget.org/v3/registration2-gz/microsoft.bcl/index.json 6591ms OK https://api.nuget.org/v3/registration2-gz/runtime.debian.8-x64.runtime.native.system.security.cryptography/index.json 6511ms OK https://api.nuget.org/v3/registration2-gz/runtime.opensuse.42.1-x64.runtime.native.system.security.cryptography/index.json 5146ms OK https://api.nuget.org/v3/registration2-gz/runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography/index.json 6108ms OK https://api.nuget.org/v3/registration2-gz/runtime.rhel.7-x64.runtime.native.system.security.cryptography/index.json 5558ms OK https://api.nuget.org/v3/registration2-gz/runtime.osx.10.10-x64.runtime.native.system.security.cryptography/index.json 6390ms OK https://api.nuget.org/v3/registration2-gz/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography/index.json 5732ms OK https://api.nuget.org/v3/registration2-gz/runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography/index.json 5238ms OK https://api.nuget.org/v3/registration2-gz/microsoft.framework.configuration/index.json 5097ms OK https://api.nuget.org/v3/registration2-gz/runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography/index.json 5449ms OK https://api.nuget.org/v3/registration2-gz/validation/index.json 4312ms OK https://api.nuget.org/v3/registration2-gz/microsoft.framework.configurationmodel.interfaces/index.json 4928ms OK https://api.nuget.org/v3/registration2-gz/system.xml.xpath/index.json 4709ms`

**Comment by skofman1** [comment]
Hi @OliverRC , can you provide additional information regarding your network and geo-location so we can investigate the network slowness?
You can find the instructions on how to capture an MTR log on our FAQ page: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq under "Why can't I download packages from or upload packages to nuget.org?"
Please send the MTR log to support @ nuget.org

**Comment by skofman1** [comment]
We can't investigate this issue without further information. Closing for now.
