### ISSUE TITLE
Analyze performance of "Status" column in Packages table (to replace Deleted)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4585]

**Comment by joelverhagen** [comment]
Top 8 queries before change:
[AA-before-change.txt](https://github.com/NuGet/NuGetGallery/files/1265195/AA-before-change.txt)
Top 8 queries after change:
[BB-after-change.txt](https://github.com/NuGet/NuGetGallery/files/1265194/BB-after-change.txt)

Results (times are in microseconds)

. | 1  | 2  | 3  | 4  | 6  | 7  | 9  | 10
-- | -- | -- | -- | -- | -- | -- | -- | --
Old | 135600 | 421450 | 13695700 | 2913150 | 213750 | 248400 | 2884100 | 247500
New | 136450 | 451950 | 13399700 | 2892050 | 206650 | 252200 | 2892700 | 249150

**Comment by joelverhagen** [comment]
This is how I timed the SQL queries.

```
declare @i integer = 0
declare @itrs integer = 20

while @i < @itrs
begin
declare @t0 datetime = GETDATE()

-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- Query here

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

declare @t1 datetime = GETDATE()

SELECT DATEDIFF(microsecond,@t0,@t1) AS [Measurement,10,New]

set @i = @i + 1

end
```

**Comment by agr** [comment]
`DATETIME` type resolution is ~3ms, so it's kind of pointless to try to calculate microsecond intervals using it :)
