### ISSUE TITLE
Enable a tab for third-party clients on package details page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4589]
Proposal:

![thirdpartyclientsonpackagedetailspage](https://user-images.githubusercontent.com/14800916/29630745-0bf3a8c2-87f2-11e7-8862-1b605fbfdfed.PNG)

**Comment by pmbanka** [comment]
I like this design - the additional information is clearly visible and hard to miss. There is just one element which bothers me with it - the warning icon.

I think that the warning icon is usually associated with actions that are potentially dangerous - like e.g. deleting unsaved files. In this case, the displayed command is not a potentially dangerous action - in fact, it is the most commonly executed command in the context of a specific NuGet client.

There is a downside of displaying unnecessary warnings, [described very well here](https://ux.stackexchange.com/q/44609) - it makes users accustomed to skipping them and not paying attention, which can lead to serious consequences.

I believe it would be better from UX perspective if the warning icon was replaced with an information sign - something like this ⓘ 

Another thing is the background colour. Warnings are usually associated with yellow, while information is associated with blue or green, so changing just the icon might lead to a confusing design (mixed signals). In case of changing the icon, I would suggest experimenting with other background colours as well.

**Comment by pmbanka** [comment]
Thinking about it a little more, I have some comments about the wording of the message as well.

With the current wording, it is quite easy to think that Paket simply does not work with NuGet server, because "is not supported" in context of programming usually means "it will not work on this environment|machine|etc" or "is not implemented". 

What do you think about something like this?

> The NuGet Team does not provide support for {Client1} client. Contact its maintainers for support.

**Comment by agr** [comment]
There might not be need in any icon at all: assuming that the banner is invisible when either of first two tabs is selected and appears only when the Paket tab is selected, the act of appearing might be enough attention drawing. CSS animation for making it visible might draw even more attention to it.

Also I'd suggest not to make hyperlinks that span whole sentences, having only the 'maintainers' as hyperlink should be enough.

**Comment by anangaur** [comment]
I would rather go with existing mechanism of warning than coming up with new mechanism or animation. I think the proposed text changes are fine.

**Comment by anangaur** [comment]
I think for other clients too we should have link to help page to understand more on the install mechanism. Obviously first we need to have the doc page ready for that 🙂
