### ISSUE TITLE
Package upload fails without error.

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#4592]
Customer reported issue: 

> Hello,
Whenever I try to upload an update (NabtoClientNative.4.1.4.nupkg), nothing happens after the progress bar reaches 100% - no text, no redirect, not anything. I can just try to upload again. The new update does not appear anywhere so it must have failed for some reason. I have tried in Chrome and Safari on a Mac and in Edge on Windows 10, exact same behavior. Any idea about what is going on?
Thanks!
Ulrik

**Comment by skofman1** [comment]
couldn't find traces to investigate. Closing.
