### ISSUE TITLE
Clicking the "Contact owner" link on dev web site causes HTTPS certificate mismatch errors in the browser

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4594]
Repro: go to https://dev.nugettest.org/packages/TestNugetPackage2/
Click on the [Contact owners](https://dev.nugettest.org/packages/TestNugetPackage2/ContactOwners) link.
(I wasn't logged on when I did this, if it matters)

You get redirected to the Trafficmanager [URL](https://devnugettest.trafficmanager.net/users/account/LogOn?ReturnUrl=%2Fpackages%2FTestNugetPackage2%2FContactOwners) which browser to go crazy about mismatching HTTPS certificate.

**Comment by agr** [comment]
Also, all the links on the contact owner page lead to trafficmanager.com instead of dev.nugettest.org

**Comment by xavierdecoster** [comment]
This should now be fixed on the DEV environment.

The fix involved configuring a `set-header` outbound policy on APIM that overrides the response HTTP `Location` header.
