### ISSUE TITLE
tag search not list any package

### ISSUE THREAD

**Issue by liurongwei** [NuGet/NuGetGallery#4596]
upload a package to nuge with tag aaa, in the package detail page ,click the tag 'aaa', no package can be listed .

maybe this a bug .

**Comment by agr** [comment]
Search index update is not instantaneous, did you try searching for the tag some time after uploading a package? Mind sharing the specific package and tag having that issue?

**Comment by liurongwei** [comment]
I got the problem , does it need a job to maintain the edit state to package table . I search the problem with 

> An edit is pending for this package version. You are seeing the edited package description now.
                            These changes will be applied to the package file and become visible to everybody soon unless you

and It need a job the save the edits to the packages table .

so I clone the https://github.com/NuGet/NuGet.Jobs.git project . and try to run the project 'HandlePackageEdits' , and still got a trouble .

I deploy the nugetgallery locally ,not in the windows azure . I found that the job can only handle the cloud storage with a class 'CloudStorageAccount', and how I can make it work , thanks .

**Comment by agr** [comment]
Oh, so you are talking about issues with local setup, not with nuget.org, right?

HandlePackageEdits job is pretty much unrelated here: what it does is that given the requested updates to the package metadata it retrieves the `.nupkg`, updates the `.nuspec` inside and repackages the `.nupkg`, then updates the DB to reflect the change. It's pretty much unrelated to the search.

My search-related knowledge is limited, but from what I understand, for search to work, you have to have [BasicSearch](https://github.com/NuGet/NuGet.Services.Metadata/tree/master/src/NuGet.Services.BasicSearch) running, and for the search index to receive changes from the Gallery, you'd also need `feed2catalog` and `catalog2lucene` jobs running (sources for both are [here](https://github.com/NuGet/NuGet.Services.Metadata/tree/master/src/Ng/Jobs)), but I'm not sure if any of those are capable of working outside of Azure.

**Comment by agr** [comment]
Hey, I have an update on the issue. I was wrong regarding the search service (sorry, I'm the new guy here): Gallery has integrated search service, so the search should work without any additional setup or services. Tag search also should work with it (edits would still require HandlePackageEdits job to be running though, but it's unrelated to the new package upload, unless tags were added during the package upload and are not present in the `.nuspec`).

If it does not work, first thing to try is rebuilding the Lucene index: on an admin page there is a "Lucene Index Maintenance" link that has the "Rebuild Now" button which will do the job.

Please let me know if it helped.

**Comment by liurongwei** [comment]
have updated to v20170901, another issue came up . package cann't display when a new package was uploaded , rebuild lucene index still cann't ,except restart the website.

**Comment by agr** [comment]
I see you have opened another issue regarding it, thank you. Do you have tag search working?

**Comment by skofman1** [comment]
Closing. Feel free to reopen if the issue wasn't resolved.
