### ISSUE TITLE
Always show supported frameworks for packages

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4598]
Today NuGet.org shows the frameworks only if there are dependencies in the packages.
Twitter thread: https://twitter.com/imperugo/status/899901309788225540

**Comment by cdrnet** [comment]
Even so, what is shown there can actually misleading, since this is about dependency groups, not about supported frameworks (which can be different).

**Comment by anangaur** [comment]
Agree. We should look at adding this functionality along with "Context aware search" feature that aims to add more such metadata around to package details page. May be both sets of information are required. We need to think through the right way to surface the info without confusing the users.

cc: @karann-msft can you link this to the proposed feature?

**Comment by joelverhagen** [comment]
We've shipped a Frameworks tab on the package details page. This shows all package asset frameworks (frameworks directly expressed by assets in the package) and calculated frameworks (implicit support via TFM mappings). This was tracked by https://github.com/NuGet/NuGetGallery/issues/4843 and is now resolved. Go try it out if you haven't already 😃.
https://www.nuget.org/packages/Newtonsoft.Json/13.0.2-beta1#supportedframeworks-body-tab

The ability to filter package search by TFM or by supported framework is tracked by https://github.com/NuGet/NuGetGallery/issues/3098.

If you feel that what you're describing is now implemented yet, please feel free to open a new issue with details!

Thanks!
