### ISSUE TITLE
Many packages do not have IsLatestSemVer2 / IsLatestStableSemVer2 set

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4600]
Observe the following two OData queries:
https://www.nuget.org/api/v2/Packages/$count?$filter=IsAbsoluteLatestVersion
https://www.nuget.org/api/v2/Packages/$count?$filter=IsAbsoluteLatestVersion&semVerLevel=2.0.0

Presumably, the result of the second should be greater than or equal to the result of the first since the first excludes SemVer 2.0.0 packages. However, the result of the second is much less than the first.

I dug into this a bit and it seems like many packages have not `IsLatestSemVer2` or `IsLatestStableSemVer2` for any package with that ID. This should not be the case.

To find the affected IDs, sorted by download count:

```sql
SELECT DISTINCT pr.Id, pr.DownloadCount
FROM dbo.PackageRegistrations pr
WHERE pr.Id IN (
	SELECT DISTINCT pr.Id
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE p.Listed = 1
) AND pr.Id NOT IN (
	SELECT DISTINCT pr.Id
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE p.IsLatestSemVer2 = 1
) ORDER BY pr.DownloadCount DESC
```

To observe the issue on a specific package:
```sql
SELECT pr.Id as ID, p.[Version], p.Listed, p.IsLatestSemVer2, p.IsLatestStableSemVer2, p.IsLatest, p.IsLatestStable
FROM dbo.Packages p
INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE pr.Id = 'Knapcode.Procommand'
```

ID | Version | Listed | IsLatestSemVer2 | IsLatestStableSemVer2 | IsLatest | IsLatestStable
-- | -- | -- | -- | -- | -- | --
Knapcode.Procommand | 0.1.0 | 1 | 0 | 0 | 0 | 0
Knapcode.Procommand | 0.2.0 | 1 | 0 | 0 | 0 | 0
Knapcode.Procommand | 0.3.0 | 1 | 0 | 0 | 1 | 1

/cc @xavierdecoster 

We can fix individual packages by reflowing one of the version, but that is not a scalable solution for the 67282 effected packages.

**Comment by joelverhagen** [comment]
Since this issue is only effecting IDs that have no SemVer 2.0.0 versions, we can perform a data fix in SQL by simply copying the value of `IsLatest` to `IsLatestSemVer2` and `IsLatestStable` to `IsLatestStableSemVer2`.

**Comment by joelverhagen** [comment]
The following script can be used:

```sql
-- Determine if any SemVer 2.0.0 packages have this issue. If there are any, manually reflow them.
SELECT DISTINCT pr.Id
FROM dbo.PackageRegistrations pr
WHERE pr.Id IN (
	SELECT DISTINCT pr.Id
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE p.Listed = 1
) AND pr.Id NOT IN (
	SELECT DISTINCT pr.Id
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE p.IsLatestSemVer2 = 1
) AND pr.Id IN (
	SELECT DISTINCT pr.Id
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE p.SemVerLevelKey = 2
)

-- Determine if any packages have inconsistent IsLatest columns. If there are any, manually reflow them.
SELECT PackageRegistrationKey, pr.Id, IsLatestCount, IsLatestStableCount, IsLatestSemVer2Count, IsLatestStableSemVer2Count
FROM
(
	SELECT ISNULL(ISNULL(pr.[Key], q3.PackageRegistrationKey), q4.PackageRegistrationKey) AS PackageRegistrationKey,
		IsLatestCount, IsLatestStableCount, IsLatestSemVer2Count, IsLatestStableSemVer2Count
	FROM
	(
		[dbo].[PackageRegistrations] pr
		INNER JOIN
		(
			SELECT PackageRegistrationKey, COUNT(*) AS IsLatestCount
			FROM [dbo].[Packages]
			WHERE IsLatest=1
			GROUP BY PackageRegistrationKey
			HAVING COUNT(*) > 1
		) AS q1
		ON pr.[Key] = q1.PackageRegistrationKey
		FULL OUTER JOIN
		(
			SELECT PackageRegistrationKey, COUNT(*) AS IsLatestStableCount
			FROM [dbo].[Packages]
			WHERE IsLatestStable=1
			GROUP BY PackageRegistrationKey
			HAVING COUNT(*) > 1
		) AS q2
		ON pr.[Key] = q2.PackageRegistrationKey
		FULL OUTER JOIN
		(
			SELECT PackageRegistrationKey, COUNT(*) AS IsLatestSemVer2Count
			FROM [dbo].[Packages]
			WHERE IsLatestSemVer2=1
			GROUP BY PackageRegistrationKey
			HAVING COUNT(*) > 1
		) AS q3
		ON pr.[Key] = q3.PackageRegistrationKey
		FULL OUTER JOIN
		(
			SELECT PackageRegistrationKey, COUNT(*) AS IsLatestStableSemVer2Count
			FROM [dbo].[Packages]
			WHERE IsLatestStableSemVer2=1
			GROUP BY PackageRegistrationKey
			HAVING COUNT(*) > 1
		) AS q4
		ON pr.[Key] = q4.PackageRegistrationKey
	)
) AS qq
JOIN [dbo].[PackageRegistrations] pr
ON pr.[Key] = qq.PackageRegistrationKey
ORDER BY pr.Id

DECLARE @BatchSize INT = 1000;

-- Preview the records that will be updated.
SELECT pr.Id, p.NormalizedVersion, p.Listed, p.IsLatestSemVer2, p.IsLatestStableSemVer2, p.IsLatest, p.IsLatestStable
FROM dbo.Packages p
INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.[Key] IN (
	SELECT p.[Key]
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE
		(p.IsLatest = 1 OR p.IsLatestStable = 1) AND
		pr.Id IN (
		SELECT TOP (@BatchSize) *
		FROM (
			SELECT DISTINCT pr.Id
			FROM dbo.PackageRegistrations pr
			WHERE pr.Id IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.Listed = 1
			) AND pr.Id NOT IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.IsLatestSemVer2 = 1
			) AND pr.Id NOT IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.SemVerLevelKey = 2
			)
		) A
	)
);

-- Update the records. Repeat this statement until all data is fixed and at a rate that does not impact customers.
BEGIN TRANSACTION;

UPDATE dbo.Packages
SET IsLatestSemVer2 = IsLatest, IsLatestStableSemVer2 = IsLatestStable
WHERE [Key] IN (
	SELECT p.[Key]
	FROM dbo.Packages p
	INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
	WHERE
		(p.IsLatest = 1 OR p.IsLatestStable = 1) AND
		pr.Id IN (
		SELECT TOP (@BatchSize) *
		FROM (
			SELECT DISTINCT pr.Id
			FROM dbo.PackageRegistrations pr
			WHERE pr.Id IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.Listed = 1
			) AND pr.Id NOT IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.IsLatestSemVer2 = 1
			) AND pr.Id NOT IN (
				SELECT DISTINCT pr.Id
				FROM dbo.Packages p
				INNER JOIN dbo.PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
				WHERE p.SemVerLevelKey = 2
			)
		) A
	)
);

COMMIT;
```

**Comment by agr** [comment]
The issue is that `IsLatestSemVer2` and `IsLatestStableSemVer2` are not set for some packages, which have `IsLatest` and `IsLatestStable` set, yet the update query checks only for `IsLatestSemVer2` being not set. It's OK if in _all_ cases both `IsLatestSemVer2` and `IsLatestStableSemVer2` are not set (I haven't seen the data, so I don't know).

Otherwise, looks good.

**Comment by joelverhagen** [comment]
> The issue is that `IsLatestSemVer2` and `IsLatestStableSemVer2` are not set for some packages, which have `IsLatest` and `IsLatestStable` set, yet the update query checks only for `IsLatestSemVer2` being not set. It's OK if in _all_ cases both `IsLatestSemVer2` and `IsLatestStableSemVer2` are not set (I haven't seen the data, so I don't know).

The query under the following comment...
```sql
-- Determine if any packages have inconsistent IsLatest columns. If there are any, manually reflow them.
```
... covers this case. Application code is doing the right thing so we'll never get more instances of messed up SemVer 2.0.0 columns.

**Comment by cristinamanum** [comment]
What is the correct state of a package in regard with IsLatestSemVer2 , IsLatestStableSemVer2 , IsLatestStable  , IsLatest?

**Comment by joelverhagen** [comment]
> What is the correct state of a package in regard with IsLatestSemVer2 , IsLatestStableSemVer2 , IsLatestStable , IsLatest?

If the package's ID has no SemVer 2.0.0 packages, the values of `IsLatestSemVer2` and `IsLatest` are the same, as with the pair `IsLatestStableSemVer2` and `IsLatestStable.

`IsLatest` is true for the highest listed version, stable _or_ prerelease.
`IsLatestStable` is true for the highest listed version, disregarding prerelease versions.

**Comment by cristinamanum** [comment]
Why a package that does not have any SemVer 2 packages should have IsLatestSemVer2 = 1?

**Comment by joelverhagen** [comment]
`IsLatestSemVer2` and `IsLatestStableSemVer2` are simply the booleans used by SemVer 2.0.0 compatible client.s SemVer 1.0.0 packages are compatible with SemVer 2.0.0 clients, so these columns must be populated.

**Comment by cristinamanum** [comment]
IsLatestSemVer2 does not mean "the latest SemVer2 package" it means "the latest SemVer 2.0.0 compatible package" note that SemVer 1.0.0 is a subset of SemVer 2.0.0 so a SemVer 1.0.0 package is SemVer 2.0.0 compatible

**Comment by xavierdecoster** [comment]
> Why a package that does not have any SemVer 2 packages should have IsLatestSemVer2 = 1?

Looking at the meaning of `IsLatestVersion` and `IsAbsoluteLatestVersion` when projecting the SQL database entities to OData feed entities:

```csharp
// We do not expose the internal IsLatestSemVer2 and IsLatestStableSemVer2 properties; 
// instead the existing IsAbsoluteLatestVersion and IsLatestVersion properties will be 
// updated based on the semver-level supported by the caller.
IsLatestVersion = semVerLevelKey == SemVerLevelKey.SemVer2 
                            ? p.IsLatestStableSemVer2 : p.IsLatestStable,

// To maintain parity with v1 behavior of the feed, 
// IsLatestVersion would only be used for stable versions.
IsAbsoluteLatestVersion = semVerLevelKey == SemVerLevelKey.SemVer2 
                            ? p.IsLatestSemVer2 : p.IsLatest,
```
[Source](https://github.com/NuGet/NuGetGallery/blob/e5982240f7f165effdab864064f73275798f81a8/src/NuGetGallery/OData/PackageExtensions.cs#L93-L98)

> What is the correct state of a package in regard with IsLatestSemVer2 , IsLatestStableSemVer2 , IsLatestStable , IsLatest?

The `IsLatestSemVer2` and `IsLatestStableSemVer2` properties themselves are **not** exposed to clients AFAIK.

However, for any given package that has `IsLatestStable = true`, and has *no newer, non-prerelease SemVer2 versions* ([SemVer2 versions are identified as described in the spec](https://github.com/NuGet/Home/wiki/SemVer2-support-for-nuget.org-%28server-side%29#identifying-semver-v200-packages)), the `IsLatestStableSemVer2` property should be set to `true`. (unless you want the code to iterate over the package versions twice)

For any given package that has `IsLatest = true`, and has *no newer SemVer2 versions (pre-release or non-prerelease)*, the `IsLatestSemVer2` property should be set to `true`.
