### ISSUE TITLE
Pushing to the gallery prints a warning with the wrong URL

### ISSUE THREAD

**Issue by pranavkm** [NuGet/NuGetGallery#4603]
```
Pushing Test.1.2.3.nupkg to the NuGet gallery (https://www.nuget.org)...
  PUT https://www.nuget.org/api/v2/package/
WARNING: Your API key expires in 0.999246530690972 days. Visit https://127.0.0.1/account to regenerate your API key.
  Created https://www.nuget.org/api/v2/package/ 10465ms
```

Also, would be nice if the expiration time was pretty printed.

**Comment by xavierdecoster** [comment]
Very likely. Did a high-level check just now of the code path that generates this warning, and this change is affecting it: https://github.com/NuGet/NuGetGallery/pull/4612/files#diff-3a73a77c6ab652df243e040f87bd23b1L214

**Comment by skofman1** [comment]
We should definitely fix the expiration time and introduce test coverage.

**Comment by xavierdecoster** [comment]
@skofman1 logged separate issue to track pretty-printing the expiration time: https://github.com/NuGet/NuGetGallery/issues/4620

**Comment by xavierdecoster** [comment]
Verified this is fixed in DEV.

**Comment by xavierdecoster** [comment]
Fixed.
