### ISSUE TITLE
Download count looks wrong on "Manage packages" page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4607]
https://twitter.com/trailmax/status/903051635592765449

![image](https://user-images.githubusercontent.com/14800916/29979486-770c2f30-8efa-11e7-94d4-2f2149615f5e.png)

**Comment by joelverhagen** [comment]
This should be `TotalDownloadCount`:
https://github.com/NuGet/NuGetGallery/blob/e72e08ab541b0b47fafc7f6e1139644258b52004/src/NuGetGallery/Views/Users/_UserPackagesList.cshtml#L5
