### ISSUE TITLE
Verify Packages shows no dependencies after redesign work

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4614]
From #SR-1707:

Before the site was updated to the new version, when uploading a package it showed the dependencies of the package on the verification page. That was very helpful because occasionally I would see that the package I was uploading did not have the correct version for a dependency, and that gave me a chance to cancel the upload and fix it. Now it just says "none specified" for dependencies on the verification page (which is not even true most of the time). To me it seems like taking away that information on the upload verification is not as good as it was before the website update when that information was available. I do like the new look of the site but I don't like the functionality as much as before.

Repro:
- Go to: https://www.nuget.org/packages/cloudscribe.SimpleContent.Web/2.0.1
- Notice that Display Package lists dependencies
- Download, modify ID and test upload of same package
- Notice that Verify Package lists no dependencies

# Display Package:
![image](https://user-images.githubusercontent.com/15364949/30076241-199324b8-922d-11e7-888b-ff96f07d37cb.png)

# Upload/Verify Package:
![image](https://user-images.githubusercontent.com/15364949/30076208-0ade4e34-922d-11e7-9a06-6a5031a08b5e.png)

**Comment by SabotageAndi** [comment]
Any timeframe when this is fixed and deployed on nuget.org?

**Comment by skofman1** [comment]
This is part of our sprint plan, hence it will be deployed at the end of the month.
