### ISSUE TITLE
Package SleetLib displays newer prerelease version notice incorrectly

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#4619]
The package page for SleetLib contains a notice saying a newer prerelease version is available, however there is no newer version (no unlisted versions).  

The current stable package is the latest.
See: https://api.nuget.org/v3/flatcontainer/sleetlib/index.json

The parent package has the same latest version but does not display this notice. Both contain SemVer 2.0.0 metadata.
https://www.nuget.org/packages/Sleetlib

![image](https://user-images.githubusercontent.com/6381138/30095635-ad0c83e6-9288-11e7-8fd1-55721cdcea86.png)

**Comment by skofman1** [comment]
Seems like an issue with SemVer 2.0 sorting.

**Comment by skofman1** [comment]
@xavierdecoster , ideas?
