### ISSUE TITLE
Status page returns 500 when you POST to a page that does not exist

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4621]
Found from AI, server side.

404 is properly returned when you do a GET.

**Comment by loic-sharma** [comment]
This issue is also tracked by https://github.com/NuGet/Engineering/issues/709. We should close one of these issues.

**Comment by joelverhagen** [comment]
Let's use the other one. It's older and has more data. Closing as duplicate of https://github.com/NuGet/Engineering/issues/709.
