### ISSUE TITLE
Some end-to-end tests do not poll package availability before moving on

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4626]
Consider:
https://github.com/NuGet/NuGet.Services.EndToEnd/blob/240e0d1c8e2006f317f2ce02d052b1efa4ad6aa2/src/NuGet.Services.EndToEnd/AutoCompleteResultTests.cs#L42

This should wait for the package to be available in the search service before hitting the autocomplete endpoint.

Right now if this tests is run in isolation it compares two empty arrays (since neither result set contains the expected data) and therefore passes prematurely.

**Comment by shishirx34** [comment]
@joelverhagen - I created this task https://github.com/NuGet/Engineering/issues/747 earlier. I think we can close this one.

**Comment by joelverhagen** [comment]
D'oh! Forgot to check there. Sorry.
