### ISSUE TITLE
Organizations on NuGet.org

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4627]
We need a **light-weight** 'Organizations' concept on NuGet.org to support companies and groups owning packages and to enable 2-FA for these accounts.

Spec for this feature available here: https://github.com/NuGet/Home/wiki/Organizations-on-NuGet.org

**Comment by gfraiteur** [comment]
That would be a good feature for us at PostSharp, since we are currently sharing one account with several team members. If Nuget is already married to GitHub, it would be nice to reuse their organization system. No idea if this is feasible.

**Comment by anangaur** [comment]
@gfraiteur We do not have integration with Github. May be once we have Github integration, we should have a way to migrate the Organization from there. Keeping in sync may be an issue but something to think in future. 
For now we are working on providing a way to migrate away from shared account approach.

**Comment by hkusulja** [comment]
I am part of 3 PRO company which is Microsoft partner and developing lot for free / open source NuGets. So I am also interested in this feature. Is there any ETA for this to be in production nuget.org? tx

**Comment by anangaur** [comment]
@hkusulja Implementation of the feature in progress right now.

**Comment by anangaur** [comment]
The feature is live: https://blog.nuget.org/20180417/organizations-on-nuget-org.html 
Keeping the issue open to get feedback.

**Comment by anangaur** [comment]
Organizations - member add should be able to lookup via email address, not just nuget.org username [#5815](https://github.com/NuGet/NuGetGallery/issues/5815)

**Comment by anangaur** [comment]
Publish notification emails should include the person publishing for organizational accounts [#5807](https://github.com/NuGet/NuGetGallery/issues/5807)

**Comment by tomkerkhove** [comment]
Great feature, are there plans to invite people based on email address? This can be for people who either have an account (covered by #5815) or new users.

**Comment by tomkerkhove** [comment]
@Kralizek That's already there, you can simply go to `https://www.nuget.org/profiles/{org-name}`

**Comment by Kralizek** [comment]
@tomkerkhove yes but it's pretty scarce... compare https://www.nuget.org/profiles/emg with https://github.com/emgdev

I'd like to
* Set an organization name that does not affect the url (in this case Educations Media Group)
* Set link(s) to the organization's relevant site(s)

**Comment by anangaur** [comment]
@Kralizek What you ask are general improvements we can do to the profile pages irrespective of whether the account is a user or org account. Some of the asks are captured here:
https://github.com/NuGet/NuGetGallery/issues/2346

**Comment by luis-cortina** [comment]
Not sure if this is the correct place to ask for this. Is it possible to a Reader user type? Why wasn't considered in the beginning? 
Just wanting to share some packages with my team but don't want them being able to do any of thadmin stuff.

Thanks,

Luis

**Comment by anangaur** [comment]
What would the reader user type do? Anybody can look at the packages belonging to a user account - individual or organization. Typically the only use case of an account or author is to be able to publish packages. Rest of the details are public anyway.

**Comment by anangaur** [comment]
If possible can you create another issue for this discussion as this one is closed? Just tag me :)

**Comment by luis-cortina** [comment]
So organizational packages are visible to anyone? I had the wrong idea then, I though organizational packages were only visible to the members of the org. If that's the case then you're correct, no point in having a Reader User type.

**Comment by anangaur** [comment]
That’s right. To a package consumer there is no difference in an organization or individual account. All packages on NuGet.org are public.
