### ISSUE TITLE
Command line download URL for latest nuget.exe is still pointing to 4.1.0

### ISSUE THREAD

**Issue by alulyazan** [NuGet/NuGetGallery#4634]
In the downloads page, under the "Windows x86 Commandline" section, the latest link is still pointing to 4.1.0 instead of 4.3.0. Shouldn't it point to 4.3.0 by now?

I had issues restoring .netstandard 2.0 packages to a .csproj targeting 4.6.1, but forcing our scripts to use 4.3.0 fixes that.

**Comment by rrelyea** [comment]
By design. Please see the "updating process" that we use each time we release a new nuget.exe: https://github.com/NuGet/Home/issues/4851
