### ISSUE TITLE
Headings wrap across multiple lines which is ugly

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4635]
![image](https://user-images.githubusercontent.com/94054/30232750-90e03756-94a6-11e7-83a1-41acc3b8beef.png)

**Comment by skofman1** [comment]
Looks good now since we stopped showing metadata in versions:
![image](https://user-images.githubusercontent.com/16807822/44555959-67470380-a6ec-11e8-9b48-1791f8136b2c.png)
Please reopen if you think it's still relevant.
