### ISSUE TITLE
Rebrand NuGet.org gallery as part of move to Microsoft

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#4640]
Updates to gallery as part of the move

**Comment by skofman1** [comment]
We are missing ToU update.

**Comment by skofman1** [comment]
PR: https://github.com/NuGet/NuGetGallery/pull/4670

**Comment by cristinamanum** [comment]
[TOU.zip](https://github.com/NuGet/NuGetGallery/files/1319092/TOU.zip)

**Comment by cristinamanum** [comment]
The TOU was manually deployed to dev storage. Attached is the copy.
