### ISSUE TITLE
Investigate global indexing perf hit caused by China indexing

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4641]
By introducing V3 indexing to China blob storage, and adding a dependency on this indexing to our global indexing pipeline, we have hurt perf significantly. We should investigate how we can correct this.

**Comment by cristinamanum** [comment]
Experiment Notes:
[https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Issues.one%7C609EE7E4-8366-4FAB-85DE-FA0ECD809891%2FInvestigations%20for%20the%20performance%20difference%20of%20the%20v3%20china%20pipeline%7C27225281-CC97-43FB-B794-E694471415C6%2F%29
onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Issues.one#Investigations%20for%20the%20performance%20difference%20of%20the%20v3%20china%20pipeline%20vs%20north%20America%20pipeline&section-id={609EE7E4-8366-4FAB-85DE-FA0ECD809891}&page-id={27225281-CC97-43FB-B794-E694471415C6}&object-id={635C1162-6391-49BC-8C2E-EB5697420598}&12](url)
