### ISSUE TITLE
How to format Package Release notes

### ISSUE THREAD

**Issue by shahabhijeet** [NuGet/NuGetGallery#4642]
I want to point out three issues:
1) What xml property to use in the .csproj in order for the Release notes to be visible on nuget.org package page, currently there are two properties < ReleaseNotes > and < PackageReleaseNotes >
2) Currently even if I use <![CDATA[ to format my release notes, they end up on nuget page with an in correct format
e.g.
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/Microsoft.Rest.ClientRuntime.Azure.csproj#L11
they end up like below
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure/
version 3.3.10

3) Why don't I see my release notes in VS UI when I try to either install the nuget package or simply browsing various nuget packages.

Do we need two properties for ReleaseNotes?
Also why we cannot have a way to format our release notes, so that it's easy for customers to know what is in the package.

**Comment by scottbommarito** [comment]
Issue moved to [NuGet/Home #5873](https://github.com/NuGet/Home/issues/5873) via [**ZenHub**](https://www.zenhub.com/)

**Comment by scottbommarito** [comment]
Moved because it is a client issue and not a server issue.
