### ISSUE TITLE
Set up SQL Server user for the orchestrator job (limited permissions)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4656]
- SELECT and UPDATE on dbo.Packages
- SELECT on dbo.PackageRegistrations
- SELECT, INSERT, UPDATE to dbo.ValidationSets and dbo.Validations

**Comment by joelverhagen** [comment]
This new credential needs to be mentioned in the secret rotation process.

**Comment by agr** [comment]
Column level permissions might be nice for the Packages table to limit the ability to write there to the ValidationStatus column.

**Comment by joelverhagen** [comment]
We decided against this and will use the existing "read + write" credential.
