### ISSUE TITLE
Minimum dependencies to removed packages and minimum pre-release packages.

### ISSUE THREAD

**Issue by Thorium** [NuGet/NuGetGallery#4663]
I don't know which Nuget-repository is correct for this bug, but at least this one has the issues tab.

I own a package called [Owin.Comperession](https://www.nuget.org/packages/Owin.Compression/). It has a following dependency:
`Owin (>= 1.0.0-prerelease && <= 1.0.0)`

And everything worked fine and everyone was happy. Until one day, the Owin-team unlisted the prerelease-version of the package from NuGet. Now my users started to get build errors.

1.0 is still there. Do you consider all pre-release versions are better than release versions?

A repository to reproduce the issue is here:
https://github.com/jomonson/OwinCompressionDependencyIssue

**Comment by joelverhagen** [comment]
Thanks for reporting this issue @Thorium. The available versions on nuget.org are 0.5.0, 0.7.0, 0.11.0, 0.12.0, 0.14.0, and 1.0.0. The 1.0.0 version of Owin is the only version that satisfies the version range in your Owin.Compression package. I am not familiar with a 1.0.0-prerelease version of the Owin package. Perhaps it was on some CI or secondary source like MyGet?

Concerning the build failure, I was only able to reproduce a build warning in Visual Studio 2017:
```
warning NU1603: Owin.Compression 1.0.16 depends on Owin (>= 1.0.0-prerelease && <= 1.0.0) but Owin 1.0.0-prerelease was not found. An approximate best match of Owin 1.0.0 was resolved.
```

This warning is just saying that 1.0.0-prerelease was not found so 1.0.0 was used instead. NuGet prefers the lowest version in the dependency version range. Is it possible you have warnings as errors enabled?

As a side note, you can test version range compatibility using this tool:
http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/version-satisfies?versionRange=%5B1.0.0-prerelease%2C1.0.0%5D&version=1.0.0

**Comment by Thorium** [comment]
My customer says Owin.Compression 1.0.16 gives warning but 1.0.15 error, and it's the same dependency.

I have not used CI or MyGet or any other sources than NuGet.org

Why the warning? So should I release a new package for every removed minimum dependency, saying "no changes" in the release notes?

**Comment by joelverhagen** [comment]
> My customer says Owin.Compression 1.0.16 gives warning but 1.0.15 error, and it's the same dependency.

I am not sure why this is happening and have been unable to reproduce the error. Do you have steps?

> So should I release a new package for every removed minimum dependency, saying "no changes" in the release notes?

Yes, that's quite reasonable.

**Comment by Thorium** [comment]
>> So should I release a new package for every removed minimum dependency, saying "no changes" in the release notes?

> Yes, that's quite reasonable

Ok... How do people get notifications of minimum dependency packages not being available anymore?

**Comment by joelverhagen** [comment]
We do not have a notification mechanism for package deletion since package deletions are a very rare case. Our package deletion policy is here:
https://docs.microsoft.com/en-us/nuget/policies/deleting-packages

Given that 1.0.0 was published in 2012, I don't have any records of whether 1.0.0-prerelease ever existed at all on NuGet.org.

**Comment by forki** [comment]
1.0.0 prerelease probably never existed but that's not the question here.

The range is >= 1.0.0-prerelease && <= 1.0.0 and there is a 1.0 of owin. 1.0 is clearly higher than any prerelease and definitely smaller or equal to 1.0. So this version clearly matches this range. Why is it even showing a warning (or crashes)?

**Comment by joelverhagen** [comment]
All great questions! Let's move this issue over to the NuGet client repository (https://github.com/NuGet/Home/issues) so that the client guys can give all the details. Thanks for all the helpful information!

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/Home #5882](https://github.com/NuGet/Home/issues/5882) via [**ZenHub**](https://www.zenhub.com/)

**Comment by joelverhagen** [comment]
Please feel free to re-open if you feel this is an issue with NuGet.org itself 👍.

**Comment by forki** [comment]
Yes it's probably more a client issue. Thanks

Am 13.09.2017 05:37 schrieb "Joel Verhagen" <notifications@github.com>:

**Comment by Thorium** [comment]
That is better repository for this issue, thanks!
