### ISSUE TITLE
Remove Gallery blocking IPs feature

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4666]
This is an old and unused feature: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Public/Blocked.html

**Comment by joelverhagen** [comment]
Resolved with https://github.com/NuGet/NuGetGallery/commit/f08ce16bb524666add5a961f84574562af7ae763#diff-3705f05c9224ca5ded26fd7021b93e03.
