### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by didrikjonaker** [NuGet/NuGetGallery#4673]
How do I change my user name on nuget profile?

**Comment by skofman1** [comment]
Hi @didrikjonaker ,  
We do not support changing usernames directly. However, you can use a workaround:
1. Create a new account with your new username. If you want to reuse your current email address, I suggest you change the email address of your current NuGet.org account to another email address before creating a new account. 
2. Assign packages to the new account: from your package's page, you can "Manage Owners" and add the new account as a package owner. Once confirmed, remove the old account name as a package owner.
