### ISSUE TITLE
cannot convert from 'System.Text.RegularExpressions.RegexOptions' to 'int'

### ISSUE THREAD

**Issue by vivekkatakam** [NuGet/NuGetGallery#4674]
I am getting this error when building from MSBuild:
cannot convert from 'System.Text.RegularExpressions.RegexOptions' to 'int'

Error CS1503: Argument 3: cannot convert from 'System.Text.RegularExpressions.RegexOptions' to 'int' 

I have installed  System.Text.RegularExpressions and StringUtils packages from Nuget. I am using .net 4.5

Can you please suggest how to resolve the above errors.

**Comment by skofman1** [comment]
@vivekkatakam , which project are you building? NuGetGallery?

**Comment by skofman1** [comment]
@vivekkatakam, we don't provide support for Selenium Framework. I recommend that you contact their maintainers.
