### ISSUE TITLE
Consider adding an "auto delete" feature to handle failed validations

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4678]
Validation orchestrator should have a feature that means failed validations result in package deletion.

**Comment by skofman1** [comment]
We should allow package authors to re-upload a package that failed certain kinds of validation, like signature validation.

**Comment by rido-min** [comment]
Packages failing validation should not appear in `PackageRegistrations` or `Packages` tables. So "auto delete" or "re-upload" gestures are not required. Just allow submitting again.

Related to #6014 #6008, #6009 and #6010

**Comment by onovotny** [comment]
When is this hitting prod?

**Comment by scottbommarito** [comment]
@onovotny - It's live now!
