### ISSUE TITLE
Invalid version range in v3 registration blob causes client to ignore all versions

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#4684]
https://api.nuget.org/v3/registration3-gz-semver2/microsoft.visualstudio.services.gallery.webapi/index.json contains an invalid version range of `[15.106.0.preview]` which causes the client to fail when finding the package for packages.config installs. 

The result is the error: 
`Unable to resolve dependency 'Microsoft.VisualStudio.Services.Gallery.WebApi'.`

The client could handle this better by only skipping the invalid package version, however I think this should also be handled better on the server side. Invalid packages that cannot be used should not appear in the feed, and invalid data should not appear in the feed even if it is in the nuspec file.

**Comment by shishirx34** [comment]
Closing this as dupe https://github.com/NuGet/NuGetGallery/issues/3482 since it has more information.
