### ISSUE TITLE
Edit packages experience is broken if tried for a SemVer v2.0.0 package

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4697]
Steps:
1. Go to a package you own
2. Remove the version from the URL, if present - To make sure you are editing from the package page and not for specific version of the package
3. Edit a field eg. Copyright
4. Submit

Issue 1: The "Submit" button is not clickable unless you click outside on the page to remove focus from the textbox
**Issue 2 (Main issue):** On submit, this takes to a version selector page that does not have a submit button.

**Comment by skofman1** [comment]
@anangaur , couldn't repro. Lets go over it together.

**Comment by anangaur** [comment]
Updated the title to reflect that this happens for SemVer 2.0.0 packages

**Comment by anangaur** [comment]
Related https://github.com/NuGet/NuGetGallery/issues/4756

**Comment by xavierdecoster** [comment]
@anangaur Can you try and repro on int.nugettest.org? 

I could not repro on INT, but that environment has the #4756 fix. 
Looks like it also fixed this one?

**Comment by anangaur** [comment]
Looks like fixed on INT :)
