### ISSUE TITLE
Change the text on NuGet API keys page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4715]
Existing page says:

![image](https://user-images.githubusercontent.com/14800916/30672368-e09a7e7c-9e20-11e7-80db-a20ac19d54ff.png)

**Proposed text:**

An API key is a token that can identify you to NuGet Gallery. The [NuGet command-line](https://www.nuget.org/downloads) utility allows you to [submit a NuGet package to the gallery](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#push) using your API key to authenticate. 

Always keep your API keys a secret! If one of your keys is accidentally revealed, you can always generate a new one at any time. You can also remove existing API keys if necessary.

**Note:** We recommend using NuGet.exe v4.1.0 or above to push packages.

**Comment by skofman1** [comment]
PR: https://github.com/NuGet/NuGetGallery/pull/4768

**Comment by skofman1** [comment]
Reopening to change text again: https://github.com/NuGet/docs.microsoft.com-nuget/pull/503/files
