### ISSUE TITLE
Update enum ReportPackageReason, and problem description text on the form

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#4716]
Update [ReportPackageReason.cs ](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/ViewModels/ReportPackageReason.cs)

    public enum ReportPackageReason

    {

        [Description("Other")]

        Other,

        [Description("The package has a bug/failed to install")]

        HasABugOrFailedToInstall,

        [Description("The package contains malicious code")]

        ContainsMaliciousCode,

        [Description("The package is infringing my copyright or trademark")]

        ViolatesALicenseIOwn,

        [Description("The package contains private/confidential data")]

        ContainsPrivateAndConfidentialData,

        [Description("The package was not intended to be published publicly on nuget.org")]

        ReleasedInPublicByAccident,

    }

Here is the updated Details text when the user has selected "The package is infringing my copyright or trademark" as a reason.

Please provide a detailed description of the problem. If you are reporting trademark infringement, include the name of your trademark, registration number and country where registered.

![image](https://user-images.githubusercontent.com/16904420/31631128-8ef2ce7e-b26d-11e7-8084-b22b389ef45b.png)

**Comment by karann-msft** [comment]
There is a bug. @ryuyu why am I seeing the highlighted text for owner support request? I remember working on this with you where this should show up only for report abuse and when the reason selected is copyright/TM infringement.

![image](https://user-images.githubusercontent.com/16904420/32674265-6681ff52-c607-11e7-908d-6269348d8a29.png)

I got to that page by clicking on contact support on the delete page.

**Comment by skofman1** [comment]
This should be hotfixed
