### ISSUE TITLE
We should not show any details about the deleted package on the details page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4717]
Deleted packages are rarest of rare cases on NuGet.org and should be never done. However, showing the details of the deleted package and ways to install the package is unnecessary and confusing. We should not show all these details.

E.g:
https://www.nuget.org/packages/Microsoft.Azure.Management.Monitor/0.17.0-preview
![image](https://user-images.githubusercontent.com/14800916/30709156-1c20a1a2-9eb6-11e7-8f88-728972e140c0.png)

**Comment by scottbommarito** [comment]
I will note that only SOFT-deleted packages show this information. HARD-deleted packages are completely invisible.

**Comment by anangaur** [comment]
I think none of them should show for a normal user because the package doesn't exist. I am okay with the page being shown.
