### ISSUE TITLE
Consider making CachingSecretReader resilient to KeyVault downtime

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4725]
Currently, [CachingSecretReader](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.KeyVault/CachingSecretReader.cs) does not do any error processing for a KeyVault call. So if KV goes down and the KeyVault methods throw exceptions, we would be unable to get even the old values due to exceptions thrown, effectively rendering the process that uses the secrets provided inoperable.

Since secrets don't change that often, we probably should try to keep old secrets available for use in case KV does not respond.

**Comment by skofman1** [comment]
had no issue with this
