### ISSUE TITLE
Documentation.md should be populated from package during push

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4730]

**Comment by tmenier** [comment]
Is there a blog post or something explaining this documentation feature? I wasn't able to find anything. It just sort of appeared one day and I can't even find any examples of anyone using it. Granted, it seems pretty self-explanatory, but a quick explanation of its intent would be helpful. There are lots of options for hosting documentation and I'm not sure if this is meant as an alternative to those or supplemental or what. 

Just having a "should I be using this?" moment. :)

Thanks!

**Comment by skofman1** [comment]
@tmenier , this feature was announced in September. You can see the details here: https://github.com/NuGet/Announcements/issues/9

**Comment by lyndaidaii** [comment]
Close this ticket since this issue is tracked by Self-contained package readme https://github.com/NuGet/NuGetGallery/issues/6908
