### ISSUE TITLE
Package ownership requests and organization membership requests should use POST when linked from site

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4736]
@joelverhagen on https://github.com/NuGet/NuGetGallery/pull/4722:

>If we are doing work in this area to move the package ownership request experience to the web UI, we should at the same time:
>
>1. Remove the token from the URL
>1. Change the accept/reject endpoint to POST
>1. Make the email link to either link to the manage packages page
>       - Alternatively, link to a GET version of the accept/reject endpoints which require an additional click.

**Comment by skofman1** [comment]
@joelverhagen , this was fixed, right?

**Comment by joelverhagen** [comment]
Yes. Fixed.
