### ISSUE TITLE
Curated feeds don't filter out deleted packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4750]
It is unclear whether there is user impact since package deletes are rare and curated feeds don't have many packages.

The code should still filter out deleted.

**Comment by scottbommarito** [comment]
A couple clarifying questions:

1 - These are SOFT-deleted packages that are shown, correct?
2 - There is no threat of these packages being downloaded, right? Their metadata is shown but they are not downloadable?

**Comment by joelverhagen** [comment]
Correct on both counts.

Hard deleted packages cannot be seen, by definition. They are gone.

Soft deleted packages have their package content removed so the content URL in the V2 feed would simply 404.
