### ISSUE TITLE
ReadMe input persists on cancelling an upload

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4751]
Repro steps:

1. Start uploading a package on Upload page
2. Cancel the upload

**Expected**: The page gets reset to its original

**Actual**: The ReadMe input persists:

![image](https://user-images.githubusercontent.com/14800916/30876787-7a520cb2-a2ac-11e7-88d9-1ecae057bd9d.png)

**Comment by anangaur** [comment]
Linking https://github.com/NuGet/NuGetGallery/issues/4729

**Comment by chenriksson** [comment]
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4707. Will be fixed in next deployment.
