### ISSUE TITLE
Incorrect messaging while confirming a co-ownership request

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4754]
Steps:
1. Accept a co-ownership request by clicking the mail you get when somebody adds you as a co-owner of a package

**Expected:** The message should say: "Ownership Confirmed". 

**Actual:** It says "Email confirmed"
![image](https://user-images.githubusercontent.com/14800916/30883748-0b9c222e-a2c2-11e7-84ff-7a70e3300946.png)

**Comment by scottbommarito** [comment]
This was already fixed with https://github.com/NuGet/NuGetGallery/commit/0ec72a27fc6e7f4276f46a218da2dc5a4eb7a405
