### ISSUE TITLE
[api] [nuget.org] api/v2/FindPackagesById()/$count endpoint is broken

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4760]
_From @evil-shrike on September 27, 2017 13:12_

Previously url `api/v2/FindPackagesById()/$count` worked - for example:
https://www.nuget.org/api/v2/FindPackagesById()/$count?includePrerelease=false&$top=160&id=%27Rx-Linq%27&includeAllVersions=false
Now it returns 404 Not Found.
I couldn't find any announcements about such API breaking changes. 
We use Artifactory extensively as out internal nuget server, it also is used as proxy for nuget.org (for CI builds). Now we're getting errors.

_Copied from original issue: NuGet/Home#5947_

**Comment by joelverhagen** [comment]
Hey @evil-shrike, when was the last time you saw this endpoint work? I have dug back in the source code and found that it probably regressed with this commit https://github.com/NuGet/NuGetGallery/commit/3f92c55e42f2905dd415a8bb765fe4adef714c5a (circa February, 2016).

Either way, I have reproduced the issue and I am working on a fix.

**Comment by evil-shrike** [comment]
@joelverhagen I can only say that on 2017-08-18 (18th of Aug) it started failing. Not sure about what was before that time.

**Comment by joelverhagen** [comment]
I am looking at our server logs and it seems like Artifactory 5.2.1 and newer are using this non-existent `FindPackagesById()/$count` endpoint. As far as I can tell, this is a regression on the NuGet.org side. Thanks for letting us know,

**Comment by joelverhagen** [comment]
@evil-shrike, this issue is now resolved on www.nuget.org.
