### ISSUE TITLE
NuGet.Server won't work with Azure Active Directory

### ISSUE THREAD

**Issue by zairhenrique** [NuGet/NuGetGallery#4771]
Dear,

This issue is about https://github.com/NuGet/NuGet.Server which refers this repo to open issues.

I've tried NuGet.Server locally and on Azure App Service without problems, but, when I enable Azure Active Directory on my App Service for authentication/authorization, page opens without problems after log in, but when trying to pull or push from command line, I am being prompted for my username and password, and using the same from AAD is not working correctly.

Is there any reason it is not working?

Thanks for the attention.

Regards,

**Comment by skofman1** [comment]
Hi @zairhenrique , when pushing from command line (using nuget.exe), you need to authenticate with an api key.

**Comment by rafaelsc** [comment]
Duplicated? https://github.com/NuGet/Home/issues/708

**Comment by andrzejmartyna** [comment]
> Hi @zairhenrique , when pushing from command line (using nuget.exe), you need to authenticate with an api key.
Hi, @skofman1 
These are two things.
Before you are able to pass api key it is AAD in place that protects Nuget.Server.
