### ISSUE TITLE
UploadPackage.cshtml's ValidationSummary not showing VerifyPackage errors

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4787]
Regression from redesign.

#4763 logs exceptions as traces, so we can see what happened.

This issue is to fix the validation summary so the user sees validation errors again. I think the summary is working for upload, but not verify.

**Comment by scottbommarito** [comment]
@chenriksson does this issue suggest that ANY issue with the verify package form doesn't show up?

Is there a quick repro for this that would help me fix this quickly?

**Comment by chenriksson** [comment]
Repro:
1. Upload package with Id {X} and Title {Y} as User {A}
2. Upload package with Id {Y} as User {B}
  - During the Verify step, make sure the package Title is also set to {Y}
3. Submit the upload

Expected:
User should see validation error "The ID of your package, '{Y}', is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again." (see issue #809)

Actual:
User just sees error "An unexpected error occurred. Contact support for assistance."

**Comment by scottbommarito** [comment]
Upon investigation, VerifyPackage errors are shown--the scenario you've given me is a specific error case that we are not catching and returning a message for.

**Comment by chenriksson** [comment]
Deployed on 2017.11.30 - please verify in PROD!

**Comment by skofman1** [comment]
@scottbommarito , please verify and close

**Comment by scottbommarito** [comment]
Verified in prod.
