### ISSUE TITLE
Get rid of obsolete notifications on package details view

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#4788]
To reduce the number of potential notification messages shown on the package details page, two notification messages will be removed.

* pending edits message
* v4.1.0 min client requirement for push message

Those are the 2 top notifications on the below screenshot:

![screenshot](https://user-images.githubusercontent.com/880728/31988627-0c03fd76-b970-11e7-9f1f-33ba8cc9ad3d.png)

**Comment by xavierdecoster** [comment]
@anangaur there's also a "Last-Edit-Failed" notification still. I guess that should also be removed?

> Your last edit to this package was not successfully applied.  You can edit the package and submit the edit again to retry the edit.

**Comment by anangaur** [comment]
I am assuming when the edit fails users would would know that immediately? If not, then I am assuming this shows when the job to edit fails and in that case we should show the notification unless we send a mail to the user for this case.

**Comment by xavierdecoster** [comment]
Didn't find any email notification sending code in the `HandlePackageEdits` job, so my guess is that this notification in the UI is currently the only indicator of edit failure.

As the job is to be retired anyway, my vote is to keep the notification in the gallery around until all pending edits have been processed once we disabled edits. A subsequent deployment can then retire the gallery UI notification.

**Comment by anangaur** [comment]
@xavierdecoster Does this notification show while the edits are in progress (through Jobs)? Or only when its processed and failed for some reason? I thought its the later.

**Comment by xavierdecoster** [comment]
The `Pending-Edits` notification was shown while the edits were in progress. This one is removed by this PR.
The `Edit-Failed` notification was shown after failure, and is still there (not removed as part of this PR). Reason: when deploying this, notifications may still be pending and fail (rare situation). The `Edit-Failed` notification can then be removed in subsequent deployment (once Edit feature has been retired completely).
