### ISSUE TITLE
nugget servers block few geniune Public IPs

### ISSUE THREAD

**Issue by aloysiustany** [NuGet/NuGetGallery#4801]
I am from Honeywell. We are facing issues reaching https://api.nuget.org/v3/index.json. Our IT team tells that nugget servers block few Honeywell Public IPs. Please could help in whitelisting few subnets. 
Please IM/email me for subnet details.
aloysius.fernandez@honeywell.com

**Comment by rrelyea** [comment]
How should @aloysiustany ask for this support?

**Comment by skofman1** [comment]
Hi @aloysiustany , the investigation with our CDN provider showed that the requests from Honeywell India don't reach our CDN, and an error in a local web proxy. I added you to the relevant support request thread.
