### ISSUE TITLE
Upload fails due to model binding error

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4804]
On DEV environment, you can't upload a package due to an error in the page-edit-readme model binding. Works in INT/PROD.

The issue is that bindModel is getting passed an empty string, where as it should be passed null on the first callback. This breaks in readme model binding which relies on an observable property on the model to detect tab selection.

Also seen by @cristinamanum

**Comment by xavierdecoster** [comment]
Can you try again? DEV APIM config updated.

**Comment by chenriksson** [comment]
Looks good... thanks!

To clarify what the issue was... the upload initially does an ajax request to cancel the previous upload. The response that came back was missing the "Content-Type: application/json" header which caused jquery to treat the empty response as text. As a result, we ended up model binding an empty string which broke in page-edit-readme where we store an observable off the model.

Cancel behavior is still strange - we're relying on a parser error to trigger the page-edit error handler and clear the page. I'll open a separate issue for this.
