### ISSUE TITLE
Hard delete of package doesn't delete package owner requests

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4807]
Repo:
- Create package
- Add new owner to the package
- Hard delete the package through the Admin panel
- Go to Account->Manage Packages

You'll see 500 server error due to NullReferenceException in OwnerRequestsListItemViewModel. The cause is that the PackageOwnerRequest still exists in the DB, but the PackageRegistration was deleted.

**Comment by chenriksson** [comment]
It looks like hard deletes also don't delete from the PackageRegistrationOwners table, but this doesn't block any UI or cause exceptions.

**Comment by scottbommarito** [comment]
Hard deletes should delete from the `PackageRegistrationOwners` table according to this

https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Services/PackageDeleteService.cs#L25

**Comment by scottbommarito** [comment]
I checked locally and it does in fact delete from the `PackageRegistrationOwners` table--I think if it didn't, the commit would fail.

**Comment by chenriksson** [comment]
Closing - should be fixed with #4898
