### ISSUE TITLE
Confusing info for prerelease package

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4814]
Go to: https://www.nuget.org/packages/EntityFramework/6.2.0-beta1

I find the following confusing:
![image](https://user-images.githubusercontent.com/14800916/31326436-118b8116-ac7c-11e7-9169-7e8bc2a16210.png)

What does this even mean? It says "There is a newer prerelease version of this package available. 
See the version list below for details." but as far I can see this is the latest version.

**Comment by xavierdecoster** [comment]
There are in fact newer pre-release versions available. However, they are unlisted. The fix is to not take unlisted package versions into consideration when determining whether this message should be shown.
