### ISSUE TITLE
[Epic]  Package Signing

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#4819]

**Comment by robertmuehsig** [comment]
@dtivel @anangaur Obsolete issue?

**Comment by dtivel** [comment]
There are still 9 issues remaining to be completed in this epic.

**Comment by robertmuehsig** [comment]
Oh sorry. Is there a way to see those "attached" issues or is this just a naming convention via GitHub issues?

**Comment by dtivel** [comment]
You can see the links with the [ZenHub extension].  I'm not sure if you can see the links without ZenHub.

Most of the remaining issues are in a private repo; however, [this issue](https://github.com/nuget/nugetgallery/issues/5345) is in NuGetGallery and hasn't been closed yet.
