### ISSUE TITLE
Unable to access api.nuget.org from specific network

### ISSUE THREAD

**Issue by satripat** [NuGet/NuGetGallery#4827]
Connections to https://api.nuget.org/v3/index.json appear to be refused by the nuget.org. it seems our IP addresses are blocked. due to this development activities are getting impacted. can you help in fixing it?

Issue is same as https://github.com/NuGet/NuGetGallery/issues/3971 .

**Comment by skofman1** [comment]
@satripat , we need additional information  to start investigation:
1. What's your location and which network are you using?
2. When did the incident start?
3. An MTR log. Details here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#managing-packages-in-nuget.org

Please send the info to support at nuget.org

**Comment by satripat** [comment]
@skofman1 i have sent requested data to support at nuget.org. thank you.

**Comment by skofman1** [comment]
@satripat , I'm closing this issue, and we will continue investigation on support requests channel.

**Comment by GuillermoGuevara** [comment]
@skofman1 hi! I hope you are very well, i have the same issue, i am from Mexico, there are something that i can do to resolve this issue in my local network, some configuration or something like that? Or is necessary that you help me out to resolve it

**Comment by skofman1** [comment]
Hi @GuillermoGuevara, please follow the instructions provided above. We need detailed information about your location and network request in order to help. Please send this to support@nuget.org for your privacy.

**Comment by desarrollott** [comment]
Hi! @skofman1, i have this issue using mac osx, and winMtr is for windows, you can tell me about an alternative  for mac osx

**Comment by skofman1** [comment]
@desarrollott , if WinMtr is not available please send a traceroute:
http://support.hostgator.com/articles/how-do-i-run-a-traceroute-on-a-mac
