### ISSUE TITLE
VS Feedback - problem with nuget.server?

### ISSUE THREAD

**Issue by rrelyea** [NuGet/NuGetGallery#4835]
This developer community issue appears to be complaining about changes in behavior for nuget.server? (but i'm not sure)

Internal VSTS issue 488874 + externally visible: https://developercommunity.visualstudio.com/content/problem/106046/vs2017-1533-nuget-400-bad-request.html

The customer says it was solved and shows some nuget.server source code.  Can you please take a look?

**Comment by joelverhagen** [comment]
I haven't heard back in over a week from the customer. 

If you are still encountering this issue, please feel free to comment and we can re-open the issue and investigate the root cause. Thanks!
