### ISSUE TITLE
Show directly referenced top 100 packages on stats page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4836]
https://twitter.com/chrismckee/status/918275305835585536

On https://www.nuget.org/stats/packages, NuGet.org should show only the directly referenced packages that users add to their projects and not System.*, Microsoft.* that automatically get pulled in.

**Comment by xavierdecoster** [comment]
Looks like duplicate of https://github.com/NuGet/NuGetGallery/issues/3417
