### ISSUE TITLE
How to setup a project for NuGet`s 

### ISSUE THREAD

**Issue by ShalokShalom** [NuGet/NuGetGallery#4837]
This page lacks information about how to setup projects and that this is necessary in order to use Nugets. 

![screenshot_20171011_135611](https://user-images.githubusercontent.com/6344099/31439377-38f7c1a8-ae8c-11e7-8171-fef001d37c54.png)

**Comment by skofman1** [comment]
@ShalokShalom, thanks for your feedback! What specific information would you like to see on this page? There are links to documentation  on NuGet's home page: https://www.nuget.org/

**Comment by ShalokShalom** [comment]
Hi there, thanks a lot 

Casual package managers work out of the box, this one here requires something that is new to me - while it seems to be in use in Java and others as well. 

The basic question is still: 
Why setup a project, in order to install a compiler?
And what is such a project?

I still ask myself, why [this page](https://www.nuget.org/packages/FSharp.Compiler.Tools/) shows us 3 methods to download, while not a single one works (for me) and there is still not even `nuget install` count, which throws another error: 

4 installation methods. Zero solutions. 

It might be, that this makes sense for people which are used to it, while for someone new like me, it appears just confusing, overwhelming and messy. 

> There are links to documentation on NuGet's home page: https://www.nuget.org/

The thing is that I found the fsharp package page with the help of a search engine. 

These docs are anyway less helpful for somebody on Linux [since it is very strongly focused on Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/use-a-package).

Count the number of people who reach such a nuget site by Google and simply guess how much of them are new to the concept of compilers, who do not work with projects. 

You can then scale up this number to all these years, since when this setup is running.
I guess you might see that this current technique fails to serve millions a successful installation.

So, a huge number of persons get directly to the specific package pages, without any documentation.
My suggestion is something like: 

[Are you new? ](link-to-the-project-page)

Since, as it seems, there is currently no such thing: 
https://msdn.microsoft.com/library/898dd854-c98d-430c-ba1b-a913ce3c73d7#

And then here, seems like a complete other topic:
https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-in-visual-studio/configuring-projects

Well, lets find it on Google: 

![screenshot_20171013_020307](https://user-images.githubusercontent.com/6344099/31524646-5f4ac406-afbb-11e7-900d-39abde578f10.png)
![screenshot_20171013_020313](https://user-images.githubusercontent.com/6344099/31524661-70837484-afbb-11e7-89ec-3a827936eb53.png)

Well, maybe on page 2:
![screenshot_20171013_020327](https://user-images.githubusercontent.com/6344099/31524672-7d40cb54-afbb-11e7-8b09-b533a866ed6b.png)
![screenshot_20171013_020336](https://user-images.githubusercontent.com/6344099/31524678-81da73cc-afbb-11e7-88cf-fda9402c396e.png)

So, let sum it: 3 Methods at least, to download and install a binary. Zero of them are working _just like that_. 
Then, about 3 different specifications on the term "Projects" in the Microsoft ecosystem. 

Zero documentation on the homepage about an essential feature, which even can block the installation of such a fundamental software like a language compiler. 

Oh, I found another solution: Method 4, NuGet, which is - whyever - not listed on these package pages, among the other three...

Lets see:

![screenshot_20171013_022220](https://user-images.githubusercontent.com/6344099/31524983-5aed0c82-afbd-11e7-9de3-b45512d03786.png)

Which is a very similar issue to that one here: https://github.com/fsharp/fsharp/issues/784

Thanks a lot for your support

**Comment by skofman1** [comment]
@ShalokShalom , thanks for the detailed explanation. We will take this into account when updating our documentation. Seem like a lot of the feedback is related to the specific package. You can contact the owner using "Contact Owners" link on the package page, and recommend to them adding detailed installation instructions on the package page.

**Comment by ShalokShalom** [comment]
I have already done that. They dont think this is an issue at all.. -.-
