### ISSUE TITLE
build.ps1 should set version metadata

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4838]
@chenriksson commented on [Mon Mar 20 2017](https://github.com/NuGet/NuGet.Jobs/issues/122)

NuGet.Jobs/build.ps1
* Should set version metadata in AssemblyInfo.cs, same as done in NuGetGallery
* Should pack from nuspec instead of csproj for each job

*Note that NuGet.Services.Metadata/build.ps1 also needs updating.*

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #867](https://github.com/NuGet/Engineering/issues/867) via [**ZenHub**](https://www.zenhub.com/)
