### ISSUE TITLE
Gallery should show which frameworks a package is compatible with

### ISSUE THREAD

**Issue by terrajobst** [NuGet/NuGetGallery#4843]
The NuGet web site (and client UI) doesn't *really* show which frameworks a package is compatible with. Instead, it renders the dependency groups. If there are no dependency groups, it doesn't show any frameworks:

![image](https://user-images.githubusercontent.com/5169960/31554645-04ba4bdc-aff3-11e7-9dc2-cba00c2562e5.png)

And if there are some, it quickly looks super busy, even in packages with few dependencies (check out [JSON.NET](https://www.nuget.org/packages/Newtonsoft.Json/)). And for meta packages it's basically not working at all (check out [NETStandard.Library](https://www.nuget.org/packages/NETStandard.Library)).

If think we want to render the lowest version of a framework that the package is compatible with. We probably also want to hide or at least deemphasize legacy frameworks:

![image](https://user-images.githubusercontent.com/5169960/31554441-6fae0cd6-aff2-11e7-939e-5206cf1699b3.png)

If my package only targets .NET Standard, I should still see the list of frameworks I’m effectively compatible with (i.e. the list above). Ideally, the list of frameworks would remain the same between packages but we’d indicate unsupported ones. For instance, let’s say the package only targets .NET Framework 2.0, this is what I would expect to see:

![image](https://user-images.githubusercontent.com/5169960/31554451-7534c4ce-aff2-11e7-96c8-116496f55a84.png)

Logically, I think we want to have a list of frameworks on the server for which we do hit testing with each package. Adding new frameworks should update the display for all packages.

## .NET Standard

We probably want to treat .NET Standard specially, at least by displaying it first. If a package has .NET Framework assets, it might be consumable via the .NET Standard 2.0 compatibility mode. It seems we should think if and how we could render that information. Maybe like this?

![image](https://user-images.githubusercontent.com/5169960/31555337-8544e7a6-aff5-11e7-8924-1217fa9a91ca.png)

**Comment by jbogard** [comment]
What would this look like for packages that multi-target different versions of the same TFN? JSON.NET for example has separate versions for:
 - net20
 - net35
 - net40
 - net45
 - netstandard1.0
 - netstandard1.3
 - PCL junk drawer

Would it just show ".NET Framework 2.0 (or higher)"? A few of my packages also include additional features depending on what .NET Standard version you're on, so I'll multi-target accordingly.

**Comment by adamralph** [comment]
https://github.com/NuGet/NuGetGallery/issues/2787, https://github.com/NuGet/NuGetGallery/issues/2805, https://github.com/NuGet/NuGetGallery/issues/4077, https://github.com/NuGet/NuGetGallery/issues/4598, ...

**Comment by terrajobst** [comment]
@adamralph

Fair point. So far, I've not seen any concrete proposals for a design, though.

**Comment by terrajobst** [comment]
@jbogard 

Yeah, I was thinking about that too. I'm wondering if that might be too much information for the person just trying to find what would work. Another option might be icons in front of the framework name that indicates how that platform is supported (indirectly by .NET Standard, or explicitly). Multi targeting across multiple versions could be a toggle in the UI (like `[x] Show lowest versions only`).

**Comment by anangaur** [comment]
https://github.com/NuGet/Home/issues/5725

**Comment by jamesmontemagno** [comment]
Can we make things filterable in the search too?!?!? Would be amazing :)

**Comment by DmitriySokhach** [comment]
Can we have it implemented like on fuget.org please?
![image](https://user-images.githubusercontent.com/2741620/40832850-9c97fa40-658c-11e8-8594-9c820a50ee4b.png)

**Comment by drewgillies** [comment]
Spec: https://github.com/NuGet/Home/blob/dev/accepted/2021/NuGet.orgTFMs.md

**Comment by JonDouglas** [comment]
@adelarsq This is out of scope right now as this work has already been merged and will be released shortly. I encourage you to create a separate issue regarding the feature request.

**Comment by adelarsq** [comment]
@JonDouglas Nice! Thanks for the reply. I will create a new request for this.

**Comment by JonDouglas** [comment]
https://devblogs.microsoft.com/nuget/introducing-compatible-frameworks-on-nuget-org/

🚢🚢🚢 (Thanks to @dannyjdev & team!)
