### ISSUE TITLE
Why are nuget web requests so slow?

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4859]
_From @SimonCropp on April 22, 2017 7:43_

eg 

 * OK https://api.nuget.org/v3/registration1-gz/vandelay.fody/index.json 74412ms

_Copied from original issue: NuGet/Home#5112_

**Comment by mishra14** [comment]
_From @emgarten on April 22, 2017 19:42_

//cc @karann-msft @rrelyea who are investigating similar scenarios

**Comment by mishra14** [comment]
_From @karann-msft on April 26, 2017 16:53_

+@skofman1 to do a server side investigation....

**Comment by ryuyu** [comment]
We are going to need an MTR log to look into this any further. Can we request one of these from users having issues? I am unable to replicate locally.

**Comment by bchavez** [comment]
Great. I was just about to post an issue about this too.

Check this NuGet page out:
https://www.nuget.org/packages/FAKE/

![chrome_707](https://user-images.githubusercontent.com/478118/31697389-16147110-b36c-11e7-8f89-4a2d54edf4e0.png)

NuGet takes 27 seconds to load the F# FAKE page.

Used: https://tools.pingdom.com/

**Comment by SimonCropp** [comment]
Jsut to be clear my initial issue was with the nuget api. Will changes in the web ui of the nuget gallery also fix the nuget api?

**Comment by skofman1** [comment]
@bchavez , please open a separate issue, since as Simon wrote, this issue is regarding API slowness, and your issue is regarding web page slowness. From a quick look at https://www.nuget.org/packages/FAKE/ seems the slowness is related to the fact the package has hundreds/thousands of versions.

**Comment by SimonCropp** [comment]
sorry why was this closed?

**Comment by skofman1** [comment]
@SimonCropp , connectivity issues are usually related to an individual network issue, and we handle those via the support requests channel. Please send the information requested by @ryuyu to support at nuget.org so we can start an investigation.
