### ISSUE TITLE
Status page should show times in user local time

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#4865]
![image](https://user-images.githubusercontent.com/16807822/31746448-5544de3c-b41c-11e7-9eb9-1aa9015819c9.png)

**Comment by skofman1** [comment]
@scottbommarito , is this is still the behavior?

**Comment by scottbommarito** [comment]
I did not fix this behavior, it was nontrivial and I prioritized other things.

**Comment by scottbommarito** [comment]
Note: it is nontrivial because the times are generated server-side, where there is no information about the client's timezone. The fix would involve adding JS that localizes the times.
