### ISSUE TITLE
Build tool to reflow hard-deleted packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4876]
## Overview 

Below are all cases where the flat container and registration disagree on whether a package exists. There both cases where the package does and doesn't exist in the gallery.

I reflowed all of the non-deleted ones so those problems are gone. Remaining:

- 158 deleted (these ones need their "deleted" reflowed)
- 1 deleted but still in packages container (this one needs its package manually deleted)
   - k2.framework.sso.base-signature 1.0.0

## Solution

Write an admin tool which takes a list of ID/Versions as input. The tool should validate that each of the ID/Versions does not exist in the gallery (that is, they are not available or soft-deleted).

Then, the tool should write out a minimal audit record for each ID/version so that feed2catalog picks up on it.

## Data

**F** (false) means it's not there. **T** (true) means it's there.

ID | Version | Gallery | Packages Container | Flat Container | Registration | Search
-- | -- | -- | -- | -- | -- | --
actiprosoftware.shared.wpf | 12.2.570 | F | F | F | T | F
actiprosoftware.shared.wpf | 14.2.610 | F | F | F | T | F
actiprosoftware.syntaxeditor.wpf | 12.2.570 | F | F | F | T | F
actiprosoftware.syntaxeditor.wpf | 14.2.610 | F | F | F | T | F
actiprosoftware.text.wpf | 12.2.570 | F | F | F | T | F
actiprosoftware.text.wpf | 14.2.610 | F | F | F | T | F
apsis.nuget.7z | 0.0.1 | F | F | F | T | F
apsis.nuget.axalis.ax1.enterprise | 1.0.0 | F | F | F | T | F
apsis.nuget.ckeditor.net | 3.6.2 | F | F | F | T | F
apsis.nuget.diffiehellman | 0.0.0 | F | F | F | T | F
apsis.nuget.edtftpnet | 2.1.0 | F | F | F | T | F
apsis.nuget.edtftpnetpro | 8.3.0 | F | F | F | T | F
apsis.nuget.enterpriselibrary | 3.1.0 | F | F | F | T | F
apsis.nuget.enterpriselibrary.caching | 3.1.0 | F | F | F | T | F
apsis.nuget.evopdf | 3.0.0 | F | F | F | T | F
apsis.nuget.exceldatareader | 2.0.1 | F | F | F | T | F
apsis.nuget.fusioncharts | 3.2.2 | F | F | F | T | F
apsis.nuget.hibernatingrhinos.profiler.appender | 4.0.0 | F | F | F | T | F
apsis.nuget.icsharpcode.sharpziplib | 0.85.5 | F | F | F | T | F
apsis.nuget.linqtotwitter | 2.0.11 | F | F | F | T | F
apsis.nuget.lumenworks.framework.io | 3.7.1 | F | F | F | T | F
apsis.nuget.microsoft.office.interop.outlook | 14.0.4760 | F | F | F | T | F
apsis.nuget.org.mentalis.security | 1.0.13 | F | F | F | T | F
apsis.nuget.pagedlist.mvc | 0.0.1 | F | F | F | T | F
apsis.nuget.rss.net | 0.86.3381 | F | F | F | T | F
apsis.nuget.splcrypto | 1.0.0 | F | F | F | T | F
apsis.nuget.syncfusion | 8.302.0 | F | F | F | T | F
apsis.nuget.tnvalidate | 1.0.0 | F | F | F | T | F
apsis.nuget.twitterizer | 2.3.1 | F | F | F | T | F
backstretch.jquery | 2.0.4 | F | F | F | T | F
backstretch.jquery | 2.0.4.1 | F | F | F | T | F
bau.xunit | 0.0.0-placeholder | F | F | F | T | F
bau.xunit | 0.0.0-placeholder01 | F | F | F | T | F
bitnetclientlibraries.client | 0.1.36-alpha | F | F | F | T | F
bitnetclientlibraries.sdk | 0.1.36-alpha | F | F | F | T | F
bitnetclientlibraries.sdk.sample | 0.1.36-alpha | F | F | F | T | F
bitnetclientlibraries.sdk.sample | 0.1.37-alpha | F | F | F | T | F
bitnetclientlibraries.sdk.sample | 0.1.38-alpha | F | F | F | T | F
branch-xamarin-sdk | 1.0.0 | F | F | F | T | F
cfl_linker | 1.0.0 | F | F | F | T | F
distributorfx.automatedorders.services | 1.0.5536.21942 | F | F | F | T | F
distributorfx.automatedorders.services | 1.0.5578.14565 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.1 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.10 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.11 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.12 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.13 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.14 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.15 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.16 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.17 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.18 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.19 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.2 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.20 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.21 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.22 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.23 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.24 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.25 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.26 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.27 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.28 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.29 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.3 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.30 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.31 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.32 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.33 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.34 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.35 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.36 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.37 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.38 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.39 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.4 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.40 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.41 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.42 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.43 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.44 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.45 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.46 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.47 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.48 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.49 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.5 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.50 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.51 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.6 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.7 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.8 | F | F | F | T | F
dsmall.dynamicscrm.plugins.common | 1.0.0.9 | F | F | F | T | F
fibnoccisample | 1.0.0 | F | F | F | T | F
ficdaworkflowcommon | 1.0.0 | F | F | F | T | F
finsa.odp.net.core.unofficial | 5.0.0 | F | F | F | T | F
finsa.odp.net.unofficial | 5.0.0 | F | F | F | T | F
flexewebcommerce | 1.1.1 | F | F | F | T | F
fujitsu.gpmo.core.webservice.common | 1.0.4 | F | F | F | T | F
gryffindor | 1.0.0 | F | F | F | T | F
hungvq.kendoui | 15.4.20 | F | F | F | T | F
hungvq.kendoui | 15.4.20.1 | F | F | F | T | F
hungvq.kendoui | 15.5.4 | F | F | F | T | F
joshnugget | 1.0.0 | F | F | F | T | F
k2.framework.sso.base-signature | 1.0.0 | F | T | F | T | F
kendouiprofessional | 2014.2.716 | F | F | F | T | F
microsoft.upn.sanapp | 5.0.0 | F | F | F | T | F
mongodb.embedded.v3 | 3.0.0 | F | F | F | T | F
mongodb.embedded.v3 | 3.0.1 | F | F | F | T | F
mongodb.embedded.v3 | 3.0.2 | F | F | F | T | F
mongodb.embedded.v3 | 3.0.3 | F | F | F | T | F
mypackage123.1 | 1.0.0 | F | F | F | T | F
networksocket | 1.2.0 | F | F | F | T | F
nuget.platform | 1.0.0 | F | F | F | T | F
odp.net.entityframework | 6.121.1-beta | F | F | F | T | F
odp.net.managed | 112.3.50 | F | F | F | T | F
odp.net.managed | 112.3.60 | F | F | F | T | F
odp.net.managed | 121.1.0 | F | F | F | T | F
odp.net.managed | 121.1.1 | F | F | F | T | F
pdfwebapilibrary.dll | 0.0.1 | F | F | F | T | F
pdfwebapilibrary.dll | 0.0.2 | F | F | F | T | F
pdfwebapilibrary.dll | 0.0.3 | F | F | F | T | F
pdfwebapilibrary.dll | 0.0.4 | F | F | F | T | F
pmml4net | 0.1.0 | F | F | F | T | F
pmml4net | 0.1.1 | F | F | F | T | F
pmml4net | 0.1.3 | F | F | F | T | F
psns.common.mvc.skin | 1.1.0 | F | F | F | T | F
psns.common.mvc.skin | 1.1.0.1 | F | F | F | T | F
receipts.money | 0.2.0 | F | F | F | T | F
receipts.money | 0.2.1 | F | F | F | T | F
sanpackage | 1.0.0 | F | F | F | T | F
sanpackage | 1.0.1 | F | F | F | T | F
sd.tools.ormprofiler.interceptor.net45 | 1.5.14 | F | F | F | T | F
sflib | 1.0.0 | F | F | F | T | F
socrates.core | 2015.50.306.1 | F | F | F | T | F
techis.cloud.configuration | 1.0.0 | F | F | F | T | F
telerik.kendoui | 2015.1.429 | F | F | F | T | F
telerik.kendoui | 2015.1.429.1 | F | F | F | T | F
telerik.windows.controls | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.chart | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.charting | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.datavisualization | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.docking | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.gridview | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.input | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.navigation | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.controls.navigation | 2014.3.1402.46 | F | F | F | T | F
telerik.windows.data | 2014.3.1402.45 | F | F | F | T | F
telerik.windows.data | 2014.3.1402.46 | F | F | F | T | F
telerik.windows.persistenceframework | 2014.3.1402.45 | F | F | F | T | F
terrainenginedb | 1.0.0 | F | F | F | T | F
tsc.terrainengine.database | 1.4.0 | F | F | F | T | F
tsc.terrainengine.database | 1.4.1 | F | F | F | T | F
unblockapp.csharp | 1.0.0 | F | F | F | T | F
upnnewpackage | 1.0.0 | F | F | F | T | F
win8rdmos | 1.0.1 | F | F | F | T | F
yzwlib | 1.0.0 | F | F | F | T | F

**Comment by joelverhagen** [comment]
Search service is in sync with gallery because of `db2lucene`.

**Comment by joelverhagen** [comment]
The oldest non-deleted package that is on this list is chrome.TypeScript.DefinitelyTyped 3.1.6 was published on `2016-01-15 08:04:02Z`. I don't think this is an on-going issue.

I will reflow the non-deleted packages.

**Comment by joelverhagen** [comment]
I've reflowed all of the non-deleted packages.

**Comment by joelverhagen** [comment]
Spoke to @scottbommarito and @skofman1. Let's build an admin tool for this (Gallery admin UI). Description of tools requirements are above.

**Comment by scottbommarito** [comment]
A package that is correct in V2 and V3 but needs a deletion record is
```
SolidFire.Core 0.9.0.20
```

**Comment by joelverhagen** [comment]
I have reflowed all 158 deletes.
