### ISSUE TITLE
Ability to search tags with search that contains "-" (hyphen)

### ISSUE THREAD

**Issue by shahabhijeet** [NuGet/NuGetGallery#4878]
Currently if I search on nuget.org with a text "2017-01-01" it will tokenize and search text "2017" or "01"
Would be great if you can support "-" hyphen in the search string.
Also the same thing should work if I search from Visual Studio

**Comment by joelverhagen** [comment]
@joelverhagen wrote on https://github.com/NuGet/NuGetGallery/issues/7642:

Right now tags use the default analyzer in Azure Search which is the "Standard" analyzer. This tokenizes in some reasonable places (like spaces) but it some not-so-great places like hyphens. Underscores are not tokenized. This is rather inconsistent.

My hypothesis is that tags should be treated in a case insensitive manner but should not be tokenized on hyphens or underscores. Dots and other symbols are debatable.

Query [Tags:"Storage_2019-04-01"](https://www.nuget.org/packages?q=Tags%3A%22Storage_2019-04-01%22) may not be working as expected. Perhaps we could reach out to the package authors to understand their specific expectations for a sanity check.

Some data:
- 107,623 package IDs have tags on their latest version
- 590 / 107623 = 0.5% of these have an underscore (`_`) in their tags
- 11306 / 107623 = 10.5% of these have a hyphen (`-`) in their tags
- 20195 / 107623 = 18.8% of these have a dot (`.`) in their tags

Another note is that PowerShell gallery uses hyphens in their tags extensively (when cmdlet names are a tag) so this behavior is bad for that too.

**Comment by khalidabuhakmeh** [comment]
Tags should be normalized but not tokenized. For example:

```
Tags:dotnet-tool
```

**Comment by loic-sharma** [comment]
@khalidabuhakmeh Your change is live for all NuGet customers! Our telemetry indicates this change has not regressed our search metrics in the past week, so I'll go ahead and close this issue now.

Thanks for your contribution! 🎉
