### ISSUE TITLE
DownloadPackageApiV2.webtest is broken on NuGet.Jobs

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#4879]
This [test](https://github.com/NuGet/NuGet.Jobs/blob/master/src/LoadTests/DownloadPackageApiV2.webtest) is failing. The `ExpectedResponseUrl` should be updated to whatever `https://dev.nugettest.org/api/v2/package/Newtonsoft.Json/6.0.1-beta1` redirects to now.

**Comment by skofman1** [comment]
@xavierdecoster , I see that this is your code. Can you explain the purpose of this test?
