### ISSUE TITLE
Stats exist for package versions that do not exist

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4880]
Prior to https://github.com/NuGet/NuGet.Jobs/pull/221, we counted all HTTP status codes as valid downloads. 404s were properly excluded. This means that HTTP redirects and intermittent HTTP 500s are counted as downloads. HTTP to HTTPS redirect exacerbates this since redirects are more common now.

Consider Newtonsoft.Json:
https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version
![image](https://user-images.githubusercontent.com/94054/31845716-b82c7828-b5b8-11e7-86da-79e14ffcf827.png)

123.0.0 is not a real version. Try this query against stats DB for all downloads of invalid versions by date.

```sql
SELECT PackageId, PackageVersion, dd.[Date], SUM(DownloadCount)
FROM dbo.Fact_Download fd
INNER JOIN dbo.Dimension_Package dp ON fd.Dimension_Package_Id = dp.Id
INNER JOIN dbo.Dimension_Date dd ON fd.Dimension_Date_Id = dd.Id
WHERE PackageId = 'Newtonsoft.Json' AND PackageVersion IN ('0.0.1', '1.0.0', '3.5.0', '4.5.0', '4.5.4.1', '4.5.5.14908', '4.5.9.15308', '4.5.11.15520', '5.0.0', '6.0.0', '6.0.2.16931', '7.0.0', '7.0.0.1', '7.0.1.1', '7.0.1.18622', '7.0.2', '8.0.0', '8.0.2.120', '9.0.0', '9.0.1.19813', '9.0.2', '9.0.3', '10.0.0', '10.0.0.2', '10.0.0.3', '123.0.0')
GROUP BY PackageId, PackageVersion, dd.[Date]
```

(the list of versions is from gallery stats report above)

PackageId | PackageVersion | Date | Download Count
-- | -- | -- | --
newtonsoft.json | 4.5.0 | NULL | 17
newtonsoft.json | 6.0.0 | NULL | 43
newtonsoft.json | 7.0.0 | NULL | 2
newtonsoft.json | 8.0.0 | NULL | 11
newtonsoft.json | 9.0.0 | NULL | 7
newtonsoft.json | 7.0.0 | 4/11/2017 | 1
newtonsoft.json | 8.0.0 | 4/11/2017 | 1
newtonsoft.json | 10.0.0 | 5/30/2017 | 1
newtonsoft.json | 1.0.0 | 6/1/2017 | 1
newtonsoft.json | 6.0.0 | 8/17/2017 | 1
newtonsoft.json | 7.0.0 | 9/5/2017 | 1
newtonsoft.json | 8.0.0 | 9/5/2017 | 2
newtonsoft.json | 7.0.0 | 9/7/2017 | 1
newtonsoft.json | 10.0.0 | 9/8/2017 | 37
newtonsoft.json | 10.0.0.2 | 9/8/2017 | 16
newtonsoft.json | 4.5.0 | 9/8/2017 | 74
newtonsoft.json | 6.0.0 | 9/8/2017 | 32
newtonsoft.json | 7.0.0 | 9/8/2017 | 4
newtonsoft.json | 7.0.1.1 | 9/8/2017 | 3
newtonsoft.json | 8.0.2.120 | 9/8/2017 | 13
newtonsoft.json | 9.0.0 | 9/8/2017 | 10
newtonsoft.json | 4.5.0 | 9/9/2017 | 19
newtonsoft.json | 7.0.0 | 9/9/2017 | 5
newtonsoft.json | 8.0.0 | 9/9/2017 | 16
newtonsoft.json | 8.0.2.120 | 9/9/2017 | 1
newtonsoft.json | 9.0.0 | 9/9/2017 | 1
newtonsoft.json | 4.5.0 | 9/10/2017 | 77
newtonsoft.json | 6.0.0 | 9/10/2017 | 3
newtonsoft.json | 7.0.0 | 9/10/2017 | 3
newtonsoft.json | 0.0.1 | 9/11/2017 | 1
newtonsoft.json | 10.0.0 | 9/11/2017 | 79
newtonsoft.json | 10.0.0.2 | 9/11/2017 | 2
newtonsoft.json | 4.5.0 | 9/11/2017 | 42
newtonsoft.json | 4.5.4.1 | 9/11/2017 | 1
newtonsoft.json | 4.5.5.14908 | 9/11/2017 | 23
newtonsoft.json | 6.0.0 | 9/11/2017 | 23
newtonsoft.json | 7.0.0 | 9/11/2017 | 50
newtonsoft.json | 8.0.0 | 9/11/2017 | 4
newtonsoft.json | 8.0.2.120 | 9/11/2017 | 1
newtonsoft.json | 9.0.0 | 9/11/2017 | 17
newtonsoft.json | 9.0.3 | 9/11/2017 | 1
newtonsoft.json | 10.0.0 | 9/12/2017 | 68
newtonsoft.json | 10.0.0.2 | 9/12/2017 | 1
newtonsoft.json | 4.5.0 | 9/12/2017 | 84
newtonsoft.json | 6.0.0 | 9/12/2017 | 56
newtonsoft.json | 7.0.0 | 9/12/2017 | 60
newtonsoft.json | 8.0.0 | 9/12/2017 | 5
newtonsoft.json | 9.0.0 | 9/12/2017 | 40
newtonsoft.json | 9.0.3 | 9/12/2017 | 1
newtonsoft.json | 10.0.0 | 9/13/2017 | 22
newtonsoft.json | 10.0.0.2 | 9/13/2017 | 2
newtonsoft.json | 4.5.0 | 9/13/2017 | 131
newtonsoft.json | 6.0.0 | 9/13/2017 | 33
newtonsoft.json | 7.0.0 | 9/13/2017 | 18
newtonsoft.json | 8.0.0 | 9/13/2017 | 5
newtonsoft.json | 9.0.0 | 9/13/2017 | 99
newtonsoft.json | 1.0.0 | 9/14/2017 | 3
newtonsoft.json | 10.0.0 | 9/14/2017 | 50
newtonsoft.json | 10.0.0.2 | 9/14/2017 | 1
newtonsoft.json | 4.5.0 | 9/14/2017 | 54
newtonsoft.json | 4.5.11.15520 | 9/14/2017 | 2
newtonsoft.json | 6.0.0 | 9/14/2017 | 87
newtonsoft.json | 7.0.0 | 9/14/2017 | 23
newtonsoft.json | 8.0.0 | 9/14/2017 | 1
newtonsoft.json | 9.0.0 | 9/14/2017 | 64
newtonsoft.json | 1.0.0 | 9/15/2017 | 6
newtonsoft.json | 10.0.0 | 9/15/2017 | 134
newtonsoft.json | 10.0.0.2 | 9/15/2017 | 1
newtonsoft.json | 4.5.0 | 9/15/2017 | 85
newtonsoft.json | 6.0.0 | 9/15/2017 | 64
newtonsoft.json | 7.0.0 | 9/15/2017 | 15
newtonsoft.json | 8.0.0 | 9/15/2017 | 3
newtonsoft.json | 9.0.0 | 9/15/2017 | 20
newtonsoft.json | 10.0.0 | 9/16/2017 | 52
newtonsoft.json | 10.0.0.2 | 9/16/2017 | 2
newtonsoft.json | 4.5.0 | 9/16/2017 | 5
newtonsoft.json | 7.0.0 | 9/16/2017 | 20
newtonsoft.json | 8.0.0 | 9/16/2017 | 2
newtonsoft.json | 10.0.0 | 9/17/2017 | 12
newtonsoft.json | 10.0.0 | 9/18/2017 | 29
newtonsoft.json | 10.0.0.2 | 9/18/2017 | 1
newtonsoft.json | 4.5.0 | 9/18/2017 | 37
newtonsoft.json | 6.0.0 | 9/18/2017 | 25
newtonsoft.json | 7.0.0 | 9/18/2017 | 53
newtonsoft.json | 7.0.1.1 | 9/18/2017 | 2
newtonsoft.json | 8.0.0 | 9/18/2017 | 1
newtonsoft.json | 9.0.0 | 9/18/2017 | 18
newtonsoft.json | 10.0.0 | 9/19/2017 | 22
newtonsoft.json | 10.0.0.2 | 9/19/2017 | 41
newtonsoft.json | 4.5.0 | 9/19/2017 | 82
newtonsoft.json | 6.0.0 | 9/19/2017 | 60
newtonsoft.json | 7.0.0 | 9/19/2017 | 73
newtonsoft.json | 8.0.0 | 9/19/2017 | 3
newtonsoft.json | 9.0.0 | 9/19/2017 | 16
newtonsoft.json | 9.0.1.19813 | 9/19/2017 | 2
newtonsoft.json | 10.0.0 | 9/20/2017 | 20
newtonsoft.json | 4.5.0 | 9/20/2017 | 20
newtonsoft.json | 6.0.0 | 9/20/2017 | 66
newtonsoft.json | 7.0.0 | 9/20/2017 | 102
newtonsoft.json | 8.0.0 | 9/20/2017 | 4
newtonsoft.json | 9.0.0 | 9/20/2017 | 68
newtonsoft.json | 10.0.0 | 9/21/2017 | 36
newtonsoft.json | 4.5.0 | 9/21/2017 | 6
newtonsoft.json | 5.0.0 | 9/21/2017 | 1
newtonsoft.json | 6.0.0 | 9/21/2017 | 59
newtonsoft.json | 7.0.0 | 9/21/2017 | 129
newtonsoft.json | 7.0.0.1 | 9/21/2017 | 2
newtonsoft.json | 8.0.0 | 9/21/2017 | 1
newtonsoft.json | 8.0.2.120 | 9/21/2017 | 1
newtonsoft.json | 9.0.0 | 9/21/2017 | 12
newtonsoft.json | 10.0.0 | 9/22/2017 | 51
newtonsoft.json | 10.0.0.3 | 9/22/2017 | 5
newtonsoft.json | 3.5.0 | 9/22/2017 | 1
newtonsoft.json | 4.5.0 | 9/22/2017 | 39
newtonsoft.json | 6.0.0 | 9/22/2017 | 34
newtonsoft.json | 7.0.0 | 9/22/2017 | 60
newtonsoft.json | 7.0.0.1 | 9/22/2017 | 1
newtonsoft.json | 9.0.0 | 9/22/2017 | 1
newtonsoft.json | 9.0.1.19813 | 9/22/2017 | 1
newtonsoft.json | 10.0.0 | 9/23/2017 | 35
newtonsoft.json | 10.0.0.3 | 9/23/2017 | 3
newtonsoft.json | 6.0.0 | 9/23/2017 | 19
newtonsoft.json | 7.0.0 | 9/23/2017 | 30
newtonsoft.json | 10.0.0 | 9/24/2017 | 6
newtonsoft.json | 6.0.0 | 9/24/2017 | 30
newtonsoft.json | 10.0.0 | 9/25/2017 | 6
newtonsoft.json | 3.5.0 | 9/25/2017 | 2
newtonsoft.json | 4.5.0 | 9/25/2017 | 112
newtonsoft.json | 6.0.0 | 9/25/2017 | 62
newtonsoft.json | 7.0.0 | 9/25/2017 | 20
newtonsoft.json | 8.0.0 | 9/25/2017 | 24
newtonsoft.json | 9.0.0 | 9/25/2017 | 1
newtonsoft.json | 10.0.0 | 9/26/2017 | 37
newtonsoft.json | 4.5.0 | 9/26/2017 | 60
newtonsoft.json | 6.0.0 | 9/26/2017 | 96
newtonsoft.json | 6.0.2.16931 | 9/26/2017 | 1
newtonsoft.json | 7.0.0 | 9/26/2017 | 11
newtonsoft.json | 8.0.0 | 9/26/2017 | 1
newtonsoft.json | 9.0.0 | 9/26/2017 | 2
newtonsoft.json | 10.0.0 | 9/27/2017 | 29
newtonsoft.json | 4.5.0 | 9/27/2017 | 37
newtonsoft.json | 6.0.0 | 9/27/2017 | 38
newtonsoft.json | 7.0.0 | 9/27/2017 | 1
newtonsoft.json | 8.0.0 | 9/27/2017 | 15
newtonsoft.json | 9.0.0 | 9/27/2017 | 3
newtonsoft.json | 10.0.0 | 9/28/2017 | 6
newtonsoft.json | 4.5.0 | 9/28/2017 | 56
newtonsoft.json | 6.0.0 | 9/28/2017 | 13
newtonsoft.json | 7.0.0 | 9/28/2017 | 2
newtonsoft.json | 8.0.0 | 9/28/2017 | 4
newtonsoft.json | 9.0.0 | 9/28/2017 | 9
newtonsoft.json | 9.0.1.19813 | 9/28/2017 | 2
newtonsoft.json | 10.0.0 | 9/29/2017 | 1
newtonsoft.json | 4.5.0 | 9/29/2017 | 43
newtonsoft.json | 6.0.0 | 9/29/2017 | 72
newtonsoft.json | 7.0.0 | 9/29/2017 | 10
newtonsoft.json | 8.0.0 | 9/29/2017 | 3
newtonsoft.json | 9.0.0 | 9/29/2017 | 26
newtonsoft.json | 1.0.0 | 9/30/2017 | 1
newtonsoft.json | 10.0.0 | 9/30/2017 | 4
newtonsoft.json | 4.5.0 | 9/30/2017 | 17
newtonsoft.json | 6.0.0 | 9/30/2017 | 23
newtonsoft.json | 9.0.0 | 9/30/2017 | 1
newtonsoft.json | 6.0.0 | 10/1/2017 | 5
newtonsoft.json | 6.0.0 | 10/2/2017 | 1
newtonsoft.json | 10.0.0 | 10/3/2017 | 12
newtonsoft.json | 10.0.0 | 10/4/2017 | 1
newtonsoft.json | 4.5.0 | 10/4/2017 | 1
newtonsoft.json | 9.0.0 | 10/5/2017 | 11
newtonsoft.json | 4.5.0 | 10/6/2017 | 16
newtonsoft.json | 6.0.0 | 10/6/2017 | 7
newtonsoft.json | 6.0.0 | 10/7/2017 | 3
newtonsoft.json | 6.0.0 | 10/8/2017 | 2
newtonsoft.json | 8.0.0 | 10/8/2017 | 14
newtonsoft.json | 1.0.0 | 10/9/2017 | 67
newtonsoft.json | 10.0.0 | 10/9/2017 | 18
newtonsoft.json | 4.5.0 | 10/9/2017 | 8
newtonsoft.json | 6.0.0 | 10/9/2017 | 51
newtonsoft.json | 7.0.0 | 10/9/2017 | 1
newtonsoft.json | 7.0.1.18622 | 10/9/2017 | 2
newtonsoft.json | 8.0.0 | 10/9/2017 | 10
newtonsoft.json | 8.0.2.120 | 10/9/2017 | 21
newtonsoft.json | 9.0.0 | 10/9/2017 | 1
newtonsoft.json | 1.0.0 | 10/10/2017 | 2
newtonsoft.json | 10.0.0 | 10/10/2017 | 8
newtonsoft.json | 4.5.0 | 10/10/2017 | 82
newtonsoft.json | 6.0.0 | 10/10/2017 | 44
newtonsoft.json | 7.0.0 | 10/10/2017 | 36
newtonsoft.json | 8.0.0 | 10/10/2017 | 26
newtonsoft.json | 9.0.0 | 10/10/2017 | 3
newtonsoft.json | 1.0.0 | 10/11/2017 | 1
newtonsoft.json | 10.0.0 | 10/11/2017 | 45
newtonsoft.json | 123.0.0 | 10/11/2017 | 1
newtonsoft.json | 4.5.0 | 10/11/2017 | 16
newtonsoft.json | 6.0.0 | 10/11/2017 | 47
newtonsoft.json | 7.0.0 | 10/11/2017 | 20
newtonsoft.json | 8.0.0 | 10/11/2017 | 5
newtonsoft.json | 9.0.0 | 10/11/2017 | 4
newtonsoft.json | 1.0.0 | 10/12/2017 | 4
newtonsoft.json | 4.5.0 | 10/12/2017 | 10
newtonsoft.json | 6.0.0 | 10/12/2017 | 108
newtonsoft.json | 7.0.0 | 10/12/2017 | 1
newtonsoft.json | 8.0.0 | 10/12/2017 | 3
newtonsoft.json | 9.0.0 | 10/12/2017 | 6
newtonsoft.json | 9.0.1.19813 | 10/12/2017 | 3
newtonsoft.json | 9.0.2 | 10/12/2017 | 1
newtonsoft.json | 1.0.0 | 10/13/2017 | 3
newtonsoft.json | 10.0.0 | 10/13/2017 | 11
newtonsoft.json | 4.5.0 | 10/13/2017 | 1
newtonsoft.json | 6.0.0 | 10/13/2017 | 23
newtonsoft.json | 7.0.0 | 10/13/2017 | 10
newtonsoft.json | 8.0.0 | 10/13/2017 | 3
newtonsoft.json | 9.0.0 | 10/13/2017 | 18
newtonsoft.json | 10.0.0 | 10/14/2017 | 1
newtonsoft.json | 4.5.0 | 10/14/2017 | 8
newtonsoft.json | 6.0.0 | 10/14/2017 | 18
newtonsoft.json | 1.0.0 | 10/16/2017 | 13
newtonsoft.json | 10.0.0 | 10/16/2017 | 1
newtonsoft.json | 4.5.0 | 10/16/2017 | 14
newtonsoft.json | 4.5.9.15308 | 10/16/2017 | 3
newtonsoft.json | 6.0.0 | 10/16/2017 | 52
newtonsoft.json | 7.0.0 | 10/16/2017 | 6
newtonsoft.json | 7.0.1.1 | 10/16/2017 | 2
newtonsoft.json | 7.0.2 | 10/16/2017 | 2
newtonsoft.json | 8.0.0 | 10/16/2017 | 1
newtonsoft.json | 9.0.0 | 10/16/2017 | 63
newtonsoft.json | 9.0.1.19813 | 10/16/2017 | 7
newtonsoft.json | 1.0.0 | 10/17/2017 | 8
newtonsoft.json | 10.0.0 | 10/17/2017 | 7
newtonsoft.json | 4.5.0 | 10/17/2017 | 24
newtonsoft.json | 6.0.0 | 10/17/2017 | 51
newtonsoft.json | 7.0.0 | 10/17/2017 | 2
newtonsoft.json | 8.0.0 | 10/17/2017 | 1
newtonsoft.json | 9.0.0 | 10/17/2017 | 48
newtonsoft.json | 9.0.1.19813 | 10/17/2017 | 9
newtonsoft.json | 1.0.0 | 10/18/2017 | 2
newtonsoft.json | 10.0.0 | 10/18/2017 | 15
newtonsoft.json | 10.0.0.3 | 10/18/2017 | 1
newtonsoft.json | 4.5.0 | 10/18/2017 | 13
newtonsoft.json | 6.0.0 | 10/18/2017 | 31
newtonsoft.json | 7.0.0 | 10/18/2017 | 11
newtonsoft.json | 8.0.0 | 10/18/2017 | 4
newtonsoft.json | 9.0.0 | 10/18/2017 | 57
newtonsoft.json | 1.0.0 | 10/19/2017 | 3
newtonsoft.json | 10.0.0 | 10/19/2017 | 9
newtonsoft.json | 4.5.0 | 10/19/2017 | 31
newtonsoft.json | 6.0.0 | 10/19/2017 | 29
newtonsoft.json | 7.0.0 | 10/19/2017 | 20
newtonsoft.json | 9.0.0 | 10/19/2017 | 85

**Comment by skofman1** [comment]
@joelverhagen , with fix NuGet/NuGet.Jobs#221, the wrong versions will disappear in 6 weeks, correct?

**Comment by joelverhagen** [comment]
Are you talking about the roll-up? The roll-up batches download facts by package ID and version, so if there's a bad version, it will live forever, as far as I know.

**Comment by skofman1** [comment]
https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=Version shows last weeks of data. Meaning wrong data will be no longer visible. The DB rollups will continue to contain bad versions, and affect the sums, but won't be visible to users, right?

**Comment by joelverhagen** [comment]
Correct. The total counts (the ID level) will be wrong by this sum.
