### ISSUE TITLE
[Organizations] For co-owners, show the user who last pushed/edited each version

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4887]
![image](https://user-images.githubusercontent.com/18014088/31960539-f5a33f42-b8ac-11e7-8f69-89799e26bcb4.png)

If the user that pushed the package was doing so on behalf of an org, it should show the org's name for other co-owners instead of the actual user unless they are in the same org.

**Comment by anangaur** [comment]
We should include the publisher in the emails that we send out - https://github.com/NuGet/NuGetGallery/issues/5807
