### ISSUE TITLE
[Organizations] Encourage users to consolidate ownership into organizations

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4890]
Prompting should be done using the existing "confirm" page.

1 - If a user owns a package and adds an organization that they are a part of as an owner of the package, they should be prompted if they would like remove themselves as an owner.

2 - If a user adds a co-owner to a package that is a member of an organization that owns the package, they should be warned that the user already owns the package through an organization.

**Comment by scottbommarito** [comment]
@anangaur do we still want this?

**Comment by anangaur** [comment]
P2. Not needed now.
