### ISSUE TITLE
Not receiving confirmation email

### ISSUE THREAD

**Issue by zakaluka** [NuGet/NuGetGallery#4897]
Hello,

I am trying to get the website to send a confirmation email, but am not receiving it.  My username on Nuget is zakaluka.

Thank you.

**Comment by scottbommarito** [comment]
Hey @zakaluka,

Sorry for taking so long to respond. Our email service was unable to send the confirmation email, so it added your address to a bounce list. I have removed it from the list, so you should be able to log into the account again and resend the confirmation email.

If you have trouble receiving the email again, it'll be easier for us to help you if you email support@nuget.org with your problem.

Thanks!
