### ISSUE TITLE
API key expiry notification mail sends incorrect URL

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4900]
Currently the following mail gets sent:

--------
Hi <user>,
We wanted to inform you that the following API key(s) on NuGet Gallery will expire soon:
• \<API key name> – expires in \<duration> day(s).
Visit https://www.nuget.org/account to generate a new API key(s) so that you can continue pushing packages using them.

Best regards,
NuGet Gallery

--------

Note the URL is https://www.nuget.org/account. 

It should be: https://www.nuget.org/account/ApiKeys

**Comment by ryuyu** [comment]
There is a branch where the message that the gallery sends back in the header is fixed (https://github.com/NuGet/NuGetGallery/tree/ryuyu-fix-apikeyexpirymessage). However, i believe this will need a corresponding fix in the job that sends out the api key expiry emails.

**Comment by scottbommarito** [comment]
@ryuyu the change to the job is just configuration--it's set in octopus

**Comment by scottbommarito** [comment]
I have updated the configuration.

**Comment by chenriksson** [comment]
@loic-sharma and I verified the header URL in PROD. Will check with Scott if CredentialExpiration job w/ config change was deployed.

**Comment by loic-sharma** [comment]
Scott confirmed that the job was deployed with the config changes.
