### ISSUE TITLE
Integrate external authentication using SAML

### ISSUE THREAD

**Issue by ushabala123** [NuGet/NuGetGallery#4903]
Hi,
We are creating a gallery of our own using nuget gallery source.We would like to integrate external authentication into the gallery using SAML. Can someone please help/guide us how to integrate into the nuget gallery?

Regards
Usha

**Comment by skofman1** [comment]
Hi @ushabala123 , nuget.org doesn't support external authentication providers (this feature request is tracked here: https://github.com/NuGet/NuGetGallery/issues/3811)

That said, you could implement an additional Authenticator based on the existing examples:
https://github.com/NuGet/NuGetGallery/blob/27869a9f2bd453d87c061b2ad491314d9f273eea/src/NuGetGallery/Authentication/Providers/LocalUser/LocalUserAuthenticator.cs

Let me know if you have additional questions.
