### ISSUE TITLE
Very slow V2 request

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#4921]
This seems like a very slow request currently (over 20 seconds to respond):

`https://www.nuget.org/api/v2/Search()?searchTerm=%27test%27&targetFramework=%27%27&includePrerelease=true&$filter=IsLatestVersion%20or%20IsPrerelease&$orderby=Id&$top=101&$skip=0`

**Comment by maartenba** [comment]
Any chance someone could look into this? Looks like a missing index or something.

**Comment by skofman1** [comment]
I'm looking into this. Will update when I have more details. Is it something that was working fine before?

**Comment by maartenba** [comment]
Yeah used to work fine about 2 weeks ago.

**Comment by skofman1** [comment]
@maartenba , from querying our logs, I see that similar queries had bad performance for at least 3 months. 
Performance of OData queries was negatively impacted by introduction of SemVer 2.0.0 support back in June: https://github.com/nuget/nugetgallery/issues/3557 . New DB columns were added that made all OData queries less performant.
From our investigation, there is no missing index we can add to resolve this. 
We encourage all our users to migrate their queries to V3 search service. The documentation work of the API is in progress (thanks for reviewing the PR!)

**Comment by maartenba** [comment]
Is there a way to rewrite this specific query to make it faster on V2?

**Comment by skofman1** [comment]
If you remove orderby=id it becomes significantly faster, however, I don't know if this suits your needs.

**Comment by maartenba** [comment]
that should be possible to do. Thanks, @skofman1 !
