### ISSUE TITLE
Sporadic 500 (Internal Server Error) while restoring some packages

### ISSUE THREAD

**Issue by FeodorFitsner** [NuGet/NuGetGallery#4933]
Hello,

On AppVeyor we currently experiencing sporadic `500 (Internal Server Error)` while restoring some packages. For example using v3 feed:

```
NU1000: Unable to find version '1.1.6002.26530' of package 'SocketMessaging'.
 https://api.nuget.org/v3/index.json: Error downloading 'SocketMessaging.1.1.6002.26530' from 'https://api.nuget.org/v3-flatcontainer/socketmessaging/1.1.6002.26530/socketmessaging.1.1.6002.26530.nupkg'.

Response status code does not indicate success: 500 (Internal Server Error).
```

NuGet v2 feed:

```
  InternalServerError https://www.nuget.org/api/v2/package/Markdig/0.10.3 409ms
WARNING: Error downloading 'Markdig.0.10.3' from 'https://www.nuget.org/api/v2/package/Markdig/0.10.3'.
Response status code does not indicate success: 500 (Internal Server Error).
```
nuget.exe is 4.3.0

Considering `500` response which is server-side it feels like some of NuGet.org servers is erroring.

Could you please take a look?

Please let me know if you need more data to investigate that. CC @skofman1, @anangaur, @rrelyea, @IlyaFinkelshteyn

**Comment by loic-sharma** [comment]
Hello,

Our CDN is currently encountering issues in several regions, including Dallas, Texas. Please refer to [this page](https://status.verizondigitalmedia.com/) for the list of all affected regions. I've went ahead and updated nuget.org's status page to reflect our degraded status. Thank you for reporting this issue!

**Comment by FeodorFitsner** [comment]
Thanks for the update!

**Comment by loic-sharma** [comment]
This should be resolved now - could you confirm @FeodorFitsner? Thanks!

**Comment by IlyaFinkelshteyn** [comment]
Confirmed (on behalf of @FeodorFitsner). Our customers (as well as our monitoring) did not complain about last 12 hours.
