### ISSUE TITLE
Add unit test to check for pending schema changes

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4934]
Suggested by @joelverhagen to keep migrations and schema changes in sync

Should be possible to programmatically create migration and check. See:
- https://github.com/aspnet/EntityFrameworkCore/blob/dev/test/ef.Tests/SimpleProjectTest.cs
- https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/ef/Commands/MigrationsAddCommand.cs

**Comment by skofman1** [comment]
@chenriksson , which DB do we want to test this on?

**Comment by chenriksson** [comment]
@skofman1 This isn't testing migrations against a DB instance. The test would check if EF would detect schema changes if a new migration were added... comparing the source code against the latest EF migration snapshot.

Will keep, but put at P3

**Comment by joelverhagen** [comment]
Done on gallery DB, support requests DB, and validation DB.
