### ISSUE TITLE
Wrong symbol used for copyright on gallery home

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4938]
The copy right symbol used on nuget gallery home footer seems to be a `c` and not a `©` - 

![image](https://user-images.githubusercontent.com/10507120/32250024-24508778-be48-11e7-8de6-3b455df000b4.png)

**Comment by mishra14** [comment]
cc: @loic-sharma @joelverhagen

**Comment by joelverhagen** [comment]
@mishra14 nice catch! 

/cc @ryuyu

**Comment by skofman1** [comment]
This was fixed: 
![image](https://user-images.githubusercontent.com/16807822/32671727-5b918b8a-c5fd-11e7-94d4-8534a516dbce.png)
