### ISSUE TITLE
Confirmation email refuses to verify account, support email doesn't work

### ISSUE THREAD

**Issue by mvkra** [NuGet/NuGetGallery#4939]
I want to reactivate my Nuget username (mvkra). When I first signed up for the account the verification email didn't verify my account and therefore could never get the account working. In addition when trying to "Reset the Password" later on it states I need to confirm the account. I could just make a new account but would prefer to keep the username.

I have also tried emailing support@nuget.org but there's a DNS error when sending the email via Gmail (NXDOMAIN 19730281 DNS type 'a' lookup) so I suspect there's a problem with your support email as well.

**Comment by loic-sharma** [comment]
Hello,

Our email address support@nuget.org is currently encountering issues. Please use our alternate email address nuget@microsoft.com until we resolve this issue.

Best regards,
Loic

**Comment by mvkra** [comment]
All good now. Closing

**Comment by jnicolau** [comment]
Same problem here and contact form not working. The problem isn't fixed yet.
