### ISSUE TITLE
VSTO VS2017 hosted build of unit test project with project reference to a Web UI project - nuget restore fails with error NU1105

### ISSUE THREAD

**Issue by IainmXray** [NuGet/NuGetGallery#4944]
I have already raised this issue via Microsoft support ticket and have been asked by them to raise a ticket here as have suggested that it is a Nuget issue.

Nuget resolve is working locally but failing on the VSTO hosted VS2017 build server with the following error:

2017-10-31T16:04:14.5903315Z d:\a\1\s\Link.Ui.UnitTest\Link.Ui.UnitTest.csproj : error NU1105: Unable to find project information for 'd:\a\1\s\Link.Ui\Link.Ui.csproj'. The project file may be invalid or missing targets required for restore.

I am attaching the source code used in the build
[Link.Ui.zip](https://github.com/NuGet/NuGetGallery/files/1438277/Link.Ui.zip)

[logs_436.zip](https://github.com/NuGet/NuGetGallery/files/1438254/logs_436.zip)

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #6157](https://github.com/NuGet/Home/issues/6157) via [**ZenHub**](https://www.zenhub.com/)
