### ISSUE TITLE
 Documentation: Show more displayed even if no more lines

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4948]
Can we determine if 'show more' is unnecessary?

**Comment by joelverhagen** [comment]
![image](https://user-images.githubusercontent.com/94054/32398777-92b6a59a-c0ae-11e7-9be9-2a931bff4276.png)

https://www.nuget.org/packages/Knapcode.TorSharp

I have never added documentation to this package.

**Comment by anangaur** [comment]
IMO,
1. The "Documentation" should not be shown if it does not exist for a package. 
2. If documentation exists, the "Show more" should appear only if there is something to show more :)

**Comment by magol** [comment]
How do i add documentation under this section?

**Comment by joelverhagen** [comment]
@magol, if you are the owner of the package, you can click on the "Edit package" link:

![image](https://user-images.githubusercontent.com/94054/33533197-61e6fde4-d854-11e7-9dae-2bc253639d55.png)

On this edit page, scroll down to the **Import Documentation** heading:

![image](https://user-images.githubusercontent.com/94054/33533215-77ac5dcc-d854-11e7-87b7-2014bbc186e1.png)

**Comment by skofman1** [comment]
Split into two issues: 1. Hide the "Documentation" section - https://github.com/NuGet/NuGetGallery/issues/5184
2. This issue to fix the "show more"

**Comment by lyndaidaii** [comment]
close it since it will be handled by new design of display package
