### ISSUE TITLE
https://api.nuget.org/v3/index.json is not accessible 

### ISSUE THREAD

**Issue by nisar-med** [NuGet/NuGetGallery#4957]
HI,

https://api.nuget.org/v3/index.json is not accessible on my computer which is not behind any firewall or proxy. I can access other sites normally including www.nuget.org which is very strange. 

I have tried accessing on one of my servers on amazon and it works fine there.

Thanks
Nisar

**Comment by anangaur** [comment]
Can you try to provide more info to support@nuget.org by following the steps here: https://aka.ms/NuGet-connectivity
