### ISSUE TITLE
delete page is outdated

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#4960]
When a package owner clicks on "Delete package", the page displays information which is not aligned to NuGet.org policy. Moreover, it is difficult to maintain this page. Instead, it should point to our docs.

**Comment by joelverhagen** [comment]
@karann-msft, can you verify this on INT?

**Comment by karann-msft** [comment]
There is a bug. @ryuyu why am I seeing the highlighted text for owner support request? I remember working on this with you where this should show up only for report abuse and when the reason selected is copyright/TM infringement.

![image](https://user-images.githubusercontent.com/16904420/32674265-6681ff52-c607-11e7-908d-6269348d8a29.png)
