### ISSUE TITLE
Support for forced logout.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#4966]
Add support for force logout.
One scenario that could use this feature is account deletion. An account that was deleted the deleted user would need to be signed out and require a sign it.

**Comment by skofman1** [comment]
@chenriksson , you will be implementing this as part of Organization migration, correct? Do you have a separate issue to track or should I assign this one to you?

**Comment by chenriksson** [comment]
@cristinamanum can take, since she's more familiar with account deletion scenario.

This should be easy to do, just redirect to AuthenticationController::LogOff with no returnUrl so it goes to the homepage. i.e., `RedirectToAction("Logoff", "Authentication")`

**Comment by skofman1** [comment]
Account deletion feature was release without this. Not needed for now.
