### ISSUE TITLE
Add search modifier "AND"

### ISSUE THREAD

**Issue by jespersh** [NuGet/NuGetGallery#4969]
Ideally I'd like to search for the terms: windows AND service AND install AND uninstall
Doing this however returns: 9,572 packages returned for windows AND service AND install AND uninstall 

Example: https://www.nuget.org/packages?q=windows+AND+service+AND+install+AND+uninstall

Thanks! - this could be a duplicate, however searching for the word "AND" on issues...

**Comment by skofman1** [comment]
Thanks for the feedback @jespersh ! We already have an issue tracking this suggestion: https://github.com/NuGet/NuGetGallery/issues/3306
Feel free to upvote!
