### ISSUE TITLE
Gallery accepts packages containing floating version ranges in dependencies

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4973]
The following packages have floating versions in their dependency version ranges:

ID | Version
-- | --
Scissorhands.Helpers | 1.0.0-alpha-17
Scissorhands.Helpers | 1.0.0-alpha-16
PInvokeCompiler | 1.0.0-rc1
JWT | 2.3.1

These should be rejected on upload and V3 registrations should strip the floating-ness, as client does:

https://github.com/NuGet/NuGet.Client/blob/bdd8626c0e5c6ee0b505ea8a1274c5fe941fb6d1/src/NuGet.Core/NuGet.Protocol/DependencyInfo/RegistrationUtility.cs#L26

/cc @emgarten

**Comment by scottbommarito** [comment]
Is this all packages with floating version ranges or just a few you've found?

**Comment by joelverhagen** [comment]
All.

**Comment by joelverhagen** [comment]
Note that `pack` strips off the floating-ness as well.
https://github.com/NuGet/Home/issues/5150

**Comment by skofman1** [comment]
What is the impact of this?

**Comment by joelverhagen** [comment]
Unofficial clients unaware of this restriction could incorrectly support floating versions in package dependencies.

**Comment by joelverhagen** [comment]
Latest set, as of now:

```
JWT 2.3.1
LibTestCM1 3.0.0
PInvokeCompiler 1.0.0-rc1
Scissorhands.Helpers 1.0.0-alpha-16
Scissorhands.Helpers 1.0.0-alpha-17
```
