### ISSUE TITLE
Password reset for accounts created with MSA login is broken

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4984]
Reported through a support request.

Repro steps:
1. Get a Microsoft Account;
2. Create new account on nuget.org with that MSA;
3. Go to Account settings -> Password Login -> Enable Password login;
4. Click the link in the email;
5. Enter new password;
6. Observe the error:
![image](https://user-images.githubusercontent.com/102933/32680438-8141d020-c61f-11e7-9604-720d00a5ea2f.png)

**Comment by shishirx34** [comment]
It looks like the user tried to enable password login before he/she confirmed their account.

Please have the user click on the account confirmation link first and then again request link for 'Enabling password login'. The correct link will be sent by gallery and then the user should be able to set the password successfully.

I will send out a PR to fix the 'Account' view to not show password login until the account is confirmed, which should prevent users from hitting this issue again.
