### ISSUE TITLE
Failed to load a file or assembly Newtonsoft.Json, Version=9.0.0.0

### ISSUE THREAD

**Issue by marjezhang** [NuGet/NuGetGallery#4987]
I had Install the version 3.0 Nuget.Server package into my simple asp.net mvc project, but ,It couldn't Run,There are issues about the Version is not match like the pic saids
![image](https://user-images.githubusercontent.com/12440254/32690661-05121a3e-c735-11e7-8cf0-821d518dc0f8.png)

but it is ok when i install the version 2.14 Nuget.server pacakage.

**Comment by skofman1** [comment]
@marjezhang , I tried to repro, but couldn't.
Please provide additional information:
1. VisualStudio version used
2. Type of Asp.Net project you created
3. .NET framework of the project
