### ISSUE TITLE
nuget.org

### ISSUE THREAD

**Issue by biourja-ajain** [NuGet/NuGetGallery#4989]
I am unable to open the page where (manage nuget pachages). its just showing error occured, 
I need to browse some packages and install it in my system
actually the error occured when i mistakenly deleted the nuget.config file from users/ appdata/local/nuget

can you please help me in this- i am using VS2017

**Comment by biourja-ajain** [comment]
![capture](https://user-images.githubusercontent.com/33622024/32720751-79afa536-c88a-11e7-8214-eb7f2abded79.JPG)

**Comment by biourja-ajain** [comment]
its urgent can you please reply ASAP

**Comment by scottbommarito** [comment]
Sorry for the late response. This looks like a client issue to me--this is the repository for issues with the server. Moving to NuGet/Home.

**Comment by scottbommarito** [comment]
Issue moved to [NuGet/Home #6195](https://github.com/NuGet/Home/issues/6195) via [**ZenHub**](https://www.zenhub.com/)
