### ISSUE TITLE
Enable users to change profile pictures/avatars on NuGet.org

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4992]
Based on user feedback.

**Comment by skofman1** [comment]
@anangaur we use gravatar for profile pictures:
![image](https://user-images.githubusercontent.com/16807822/33591088-2f047e4e-d938-11e7-8ade-d1942fe52457.png)

What is the suggestion here?

**Comment by anangaur** [comment]
Let users upload their profile pic instead of gravatar.

**Comment by skofman1** [comment]
@anangaur , why is gravatar not sufficient? Can you point to the user feedback?

**Comment by anangaur** [comment]
@skofman1 I should have mentioned the source while opening it (note to self). I remember a couple of instances when users have asked for this. One example is the following (look at the final comment):
https://stackoverflow.com/questions/9620546/how-can-i-change-the-profile-icon-on-nuget-org

**Comment by skofman1** [comment]
From the stackoverflow discussion I get to the conclusion that we need better instructions on how to set the icon, and not to change the feature.

**Comment by anangaur** [comment]
I think it is generally easier to upload a pic now-a-days. But I do not see this as a blocker. At best a P2. You may close this issue for now. I will reopen it when I hear again from customers (and record it).

**Comment by RevZero** [comment]
I find it very inconvenient that you MUST have a gravatar account to set your profile picture. I never encountered any other website where it wasn't possible to just upload (mostly drag and drop nowadays) a profile picture. Personally, I do not know anyone who uses gravatar.
