### ISSUE TITLE
Fix the spaces on "Manage owners" page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4993]
![image](https://user-images.githubusercontent.com/14800916/32742983-e00e1bd0-c85f-11e7-923b-4a416a97e4fd.png)

**Comment by skofman1** [comment]
@anangaur , Can we close this since you created this issue: https://github.com/NuGet/NuGetGallery/issues/5226

**Comment by anangaur** [comment]
@skofman1 Sure. I unassigned my self from https://github.com/NuGet/NuGetGallery/issues/5226 as now it needs to be implemented :)
