### ISSUE TITLE
Particular package page in gallery very slow to load

### ISSUE THREAD

**Issue by hickford** [NuGet/NuGetGallery#4998]
Hi. I noticed the page https://www.nuget.org/packages/Paket/ takes around 30 seconds to load. This is several times slower than other pages. 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FPaket

> In our test, your server responded in 27.3 seconds. There are many factors that can slow down your server response time. Please read our recommendations to learn how you can monitor and measure where your server is spending the most time.

Could it be relevant that the particular package has an extensive version history (2000+ versions)?

**Comment by hickford** [comment]
For comparison https://www.nuget.org/packages/Newtonsoft.Json

> In our test, your server responded in 1.1 seconds.

**Comment by skofman1** [comment]
@hickford , package pages for packages with many versions  take a long time to load. We have an issue tracking this: https://github.com/NuGet/NuGetGallery/issues/4862 and will be working on a fix soon.
