### ISSUE TITLE
Consider upgrading to latest XUnit and enabling XUnit.Analyzers

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5008]
I tried upgrading Gallery to xunit 2.3.1 to see if it would fix a test discovery issue (it didn't). It does look like there are some fixes for Win10 creators update, but not sure if this will be necessary.

If we upgrade, we should consider enabling XUnit.Analyzers which is now added by default with the XUnit package (you can exclude it by only adding XUnit.Core and XUnit.Assert). When enabled, the analyzers provide build warnings to encourage best xunit practices... which we have a number of.

**Comment by skofman1** [comment]
We need to update to latest XUnit anyhow, otherwise there's a problem with latest VS: https://github.com/NuGet/NuGetGallery/pull/5106

**Comment by skofman1** [comment]
Done.
