### ISSUE TITLE
Is there any way to transform Views/_ViewImports.cshtml on instaling nuget package for asp.net project

### ISSUE THREAD

**Issue by WeihanLi** [NuGet/NuGetGallery#5014]
Is there any way to transform Views/_ViewImports.cshtml on instaling nuget package for asp.net project?

I wanna transform the file like transform web.config or app.config, but I don't know how.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #6207](https://github.com/NuGet/Home/issues/6207) via [**ZenHub**](https://www.zenhub.com/)
