### ISSUE TITLE
Consolidate ExtensionMethods.cs and HtmlExtensions.cs in NuGetGallery

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5015]
Right now, there are a lot of extension methods on `HtmlHelper<TModel>` in both ExtensionMethods.cs and HtmlExtensions.cs. I think all of these should be in HtmlExtensions.cs.

**Comment by skofman1** [comment]
@joelverhagen , I would like to reduce the number of "Refactoring" issues we have, since it's hard to assign time for such issues. 
Please perform the refactoring in the near future or close the issue.

**Comment by skofman1** [comment]
ping?
