### ISSUE TITLE
Update delete account workflow to consider organizations

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5016]
Per discussion with @cristinamanum 

Delete account should:
- Also list packages for user's organizations (intended to show ownerships they are giving up)
- Incorporate organizations into orphaned package calculation:
  - Package is also orphaned if org is last owner and account is last org member
- Also list user's organizations that they will be removed from
- Show green/red for orphaned organizations
  - Organization is orphaned if account is last org member
  - Also warn/show if account is last org admin

Note that both this and #4894 require updating PackagesService.FindPackagesByOwner to return organization packages.

**Comment by chenriksson** [comment]
Closing, as this can't be verified until an organization is onboarded.

I've noted this scenario in the bug bash / test plan that I'm starting to put together.

**Comment by skofman1** [comment]
@chenriksson , was the work done? Can I delete an organization?

**Comment by chenriksson** [comment]
@skofman1 No, the work wasn't done. For now we've just blocked deletion of an organization, and we would need to revert it back to a user in order to support delete.

**Comment by scottbommarito** [comment]
Note: we have not yet implemented the ability to convert an organization back into a user AFAIK
