### ISSUE TITLE
Downloading Nuget.exe from dist.nuget.org blocked

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#5018]
@georgecheyne commented on [Thu Nov 16 2017](https://github.com/NuGet/Home/issues/6191)

Hi, 

I'm not certain if this is the right issue tracker maybe it should be in the one for the website?

Anyway the url:

https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

to download nuget.exe is being blocked in my company.  Apparently dist.nuget.org has been marked as suspicious as per this site:

https://sitereview.bluecoat.com/sitereview.jsp#/?search=https%3A%2F%2Fdist.nuget.org

This means our security systems block us from downloading it.

I thought you might want to fill out the form about getting the suspicious status removed.

Thanks,

George

---

@nkolev92 commented on [Thu Nov 16 2017](https://github.com/NuGet/Home/issues/6191#issuecomment-345024269)

@joelverhagen Any ideas?

**Comment by scottbommarito** [comment]
I requested a review for them and told them to contact support@nuget.org when they finish their review.
