### ISSUE TITLE
Should site admins be able to upload packages to existing IDs or reserved namespaces?

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5019]
Currently, admins can (for all packages):
- Edit packages
- Manage package owners
- Unlist packages

It makes sense that, given that admins can do anything on a package, and even make themselves an owner of a package if necessary, that admins might as well also have the ability to:
- Upload a new version of an existing package
- Upload a new package ID to a reserved namespace

Although it seems unlikely, it could potentially be necessary for an admin to perform this functionality, and it seems unnecessary to require them to add themself as an owner to do so.

With the introduction of the `PermissionsService`, this has become extremely easy to implement.

**Comment by skofman1** [comment]
This is against out ToU:

> The Services allow you to store or share Your Content or receive material from others. We don't claim ownership of Your Content. Your Content remains Your Content and you are responsible for it.
