### ISSUE TITLE
in visual studio (or by manually) impossible to download nuget

### ISSUE THREAD

**Issue by fbregeon-ir** [NuGet/NuGetGallery#5024]
Hello,

for 2 days, in visual studio (or by manually) impossible to download nuget.

For example if you try to download directly this nuget : 
https://www.nuget.org/api/v2/package/Xamarin.Forms/2.5.0.91635

or run 

Install-Package Xamarin.Forms -Version 2.5.0.91635

Maybe site does not responding or very slow.

Regards.

**Comment by scottbommarito** [comment]
Hello,

Sorry that you're experiencing issues.

Can you please follow the instructions at https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible and email support@nuget.org with your findings?

**Comment by skofman1** [comment]
@fbregeon-ir , is this issue still on-going?

**Comment by fbregeon-ir** [comment]
Now it's working fine. Thx.
So i close.
