### ISSUE TITLE
Nuget Support does not work with Visual Studio for Mac

### ISSUE THREAD

**Issue by emgarten** [NuGet/NuGetGallery#5041]
_From @petersuwara on November 20, 2017 15:31_

## Details about Problem

Piotrs-MacBook-Pro:ContosoUniversity piotrsuwara$ dotnet add package Microsoft.VisualStudio.Web.CodeGeneration
  Writing /var/folders/c9/z9kxysr57hb5m7npd1lgtm400000gn/T/tmpfn7AP0.tmp
info : Adding PackageReference for package 'Microsoft.VisualStudio.Web.CodeGeneration' into project '/Users/piotrsuwara/Development/ContosoUniversity/ContosoUniversity/ContosoUniversity.csproj'.
log  : Restoring packages for /Users/piotrsuwara/Development/ContosoUniversity/ContosoUniversity/ContosoUniversity.csproj...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't connect to server

NuGet product used (VS UI | Package Manager Console):

NuGet version (4.3.0.5):

dotnet.exe --version (2.0.0):

VS version (if appropriate): 7

OS version (i.e. win10 v1607 (14393.321)): OS X High Sierra

Worked before? If so, with which NuGet version: No has not worked

## Detailed repro steps so we can see the same problem

Try adding any NuGet package. api.nuget.org is not reachable.

1.
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

_Copied from original issue: NuGet/Home#6204_

**Comment by emgarten** [comment]
_From @petersuwara on November 20, 2017 16:19_

If I VPN to a USA IP Address I can access api.nuget.org.

Go figure...

**Comment by emgarten** [comment]
_From @petersuwara on November 20, 2017 16:19_

How on earth are you managing the hosting if it only runs via US IP ? What about the rest of the world ?

**Comment by skofman1** [comment]
@petersuwara , api.nuget.org is available globally. 
To help us investigate the connectivity issue you encountered please follow he instructions here: https://aka.ms/nuget-connectivity and send the collected logs to support at nuget.org

**Comment by petersuwara** [comment]
@skofman1 Fiddler crashes with an exception and MTF is windows only. Any other suggestions ?

With IPVANISH - Connecting to Seattle through the VPN I get the PING results to api.nuget.org as follows ->
Piotrs-MacBook-Pro:Desktop piotrsuwara$ ping api.nuget.org
PING cs9.wpc.v0cdn.net (72.21.81.200): 56 data bytes
64 bytes from 72.21.81.200: icmp_seq=0 ttl=58 time=248.818 ms
Request timeout for icmp_seq 1
64 bytes from 72.21.81.200: icmp_seq=2 ttl=58 time=367.600 ms
64 bytes from 72.21.81.200: icmp_seq=3 ttl=58 time=390.804 ms
64 bytes from 72.21.81.200: icmp_seq=4 ttl=58 time=301.826 ms
64 bytes from 72.21.81.200: icmp_seq=5 ttl=58 time=260.289 ms
64 bytes from 72.21.81.200: icmp_seq=6 ttl=58 time=366.208 ms
64 bytes from 72.21.81.200: icmp_seq=7 ttl=58 time=382.776 ms
^C
--- cs9.wpc.v0cdn.net ping statistics ---
8 packets transmitted, 7 packets received, 12.5% packet loss
round-trip min/avg/max/stddev = 248.818/331.189/390.804/55.345 ms

From the WIFI here without VPN, ping results are the following ->
Piotrs-MacBook-Pro:Desktop piotrsuwara$ ping api.nuget.org
PING cs9.wpc.v0cdn.net (117.18.232.200): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
^C
--- cs9.wpc.v0cdn.net ping statistics ---
9 packets transmitted, 0 packets received, 100.0% packet loss

Route info through netstat with VPN (Reaches destination) ->
traceroute to cs9.wpc.v0cdn.net (72.21.81.200), 64 hops max, 72 byte packets
 1  172.21.24.1 (172.21.24.1)  225.364 ms  246.565 ms  323.374 ms
 2  205.185.218.17 (205.185.218.17)  305.615 ms  225.262 ms  225.231 ms
 3  ae9.r1.sj.hwng.net (209.197.0.57)  241.951 ms  245.279 ms  242.815 ms
 4  ae2.r2.la.hwng.net (209.197.0.65)  285.852 ms  424.358 ms  317.713 ms
 5  ae1.r2.la.hwng.net (209.197.4.7)  873.087 ms  532.475 ms  478.238 ms
 6  edgecast-networks.as15133.any2ix.coresite.com (206.72.210.112)  921.923 ms  595.048 ms  325.226 ms
 7  152.195.76.129 (152.195.76.129)  409.632 ms  312.399 ms  255.043 ms
 8  72.21.81.200 (72.21.81.200)  256.327 ms  445.025 ms  254.654 ms

Route info through netstat without VPN (Gets lost in Singapore) ->
traceroute to cs9.wpc.v0cdn.net (117.18.232.200), 64 hops max, 72 byte packets
 1  192.168.3.2 (192.168.3.2)  22.328 ms  107.297 ms  2.313 ms
 2  static.vnpt.vn (123.29.12.199)  11.283 ms  16.133 ms  3.817 ms
 3  static.vnpt.vn (113.171.44.225)  20.511 ms  42.165 ms  30.483 ms
 4  static.vnpt.vn (123.29.10.93)  39.437 ms  24.426 ms  28.503 ms
 5  static.vnpt.vn (113.171.56.222)  29.662 ms  23.433 ms  29.165 ms
 6  ix-ae-10-0.tcore1.hk2-hong-kong.as6453.net (180.87.112.237)  71.660 ms  56.111 ms  51.327 ms
 7  if-ae-7-2.thar1.hk2-hong-kong.as6453.net (180.87.112.142)  89.404 ms  100.969 ms  107.732 ms
 8  if-ae-2-2.tcore2.hk2-hong-kong.as6453.net (116.0.82.63)  124.654 ms  113.357 ms  113.267 ms
 9  if-ae-32-2.tcore2.svw-singapore.as6453.net (180.87.15.80)  103.825 ms  137.523 ms  82.316 ms
10  if-ae-20-2.tcore1.svq-singapore.as6453.net (180.87.96.21)  95.182 ms  96.834 ms  127.691 ms
11  if-ae-7-2.thar1.svq-singapore.as6453.net (180.87.98.9)  100.659 ms  84.676 ms  95.236 ms
12  ae-6.r00.sngpsi05.sg.bb.gin.ntt.net (129.250.8.241)  113.228 ms  119.829 ms  140.101 ms
13  xe-0-3-0-32.r00.sngpsi05.sg.ce.gin.ntt.net (116.51.26.70)  117.234 ms  121.675 ms  101.537 ms
14  * * *
15  * *

Better get your CTO on the phone to your DNS providers. They need a serious arse whipping. :)

**Comment by skofman1** [comment]
@petersuwara, thanks for the info! What is your location?

**Comment by petersuwara** [comment]
Vung Tau, Vietnam. Hotel Ky Hoa.

**Comment by cristinamanum** [comment]
Hi @petersuwara, we are working with our CDN provider to understand the issue.  Could you please provide the source IP addresses for both the VPN and non-VPN connection?

**Comment by petersuwara** [comment]
Working IP address : 172.21.22.1 Local / 205.185.218.17 Visible
Not Working IP address : 192.168.3.2 Local Router / 113.161.128.70 Visible

**Comment by petersuwara** [comment]
Any update on this, I'll be in Thailand today so can confirm if that works/doesn't also.

**Comment by cristinamanum** [comment]
Hi @petersuwara, 
The CDN support team is asking for:
1. The output that you get when run:
http://db16.wpc.azureedge.net/002DCC/nc/headers.html?url=http://DB16.wpc.azureedge.net/crossdomain.xml&req=GET
2. MTR logs.  Below are couple of links for helping in getting mtr from mac.
https://manager.mswebnetwork.net/knowledgebase/17/How-to-perform-an-MTR-test-on-a-Mac.html 
https://support.appliedi.net/kb/a1038/how-to-perform-an-mtr-test-on-a-mac.aspx

Would it be possible to provide this info?

**Comment by petersuwara** [comment]
I am now no longer in that location, I am working from Phuket, Thailand. The connection here seems fine.

**Comment by cristinamanum** [comment]
Please let us know if the issue will manifest again.

**Comment by cristinamanum** [comment]
HI @petersuwara , I will close the issue. If the problem will reproduce again please reopen it.

Thanks,
Cristina
