### ISSUE TITLE
PugTrace 0.7.0 and PugTrace.SqlServer 0.7.0 are broken

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5044]
```
nuget.exe install PugTrace -Version 0.7.0 -Source https://www.nuget.org/api/v2
nuget.exe install PugTrace.SqlServer -Version 0.7.0 -Source https://www.nuget.org/api/v2
```

```
Offset to Central Directory cannot be held in an Int64.
```

**Comment by skofman1** [comment]
The zip file itself is broken. We should:
1. See if our archives have the "non-broken" package
2. If not, reach out to the user and notify him about this. Suggest re-uploading the package. 
3. Hard-delete the package.

**Comment by ryuyu** [comment]
We do not appear to have any back ups of this package.

**Comment by joelverhagen** [comment]
Let's wait a couple of days for feedback from customer.
