### ISSUE TITLE
Package page shouldn't show both "Listed" and "Validation Status" for package owners

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5048]
This UI is confusing, because "Listed" can be "yes" and "Validation status" can be "Validating"

Suggestion: We should have a single column with values: "Validating/Valid/Invalid/Listed/Unlisted"

**Comment by skofman1** [comment]
@anangaur , @karann-msft how do you think we can improve the UI here?

**Comment by anangaur** [comment]
IMO, there should just one column - **Status** with the following values:
* Validating
* Listed
* Unlisted
* Failed validation

@karann-msft What is the user action when the package fails validation? Can the author resubmit the same package version?

**Comment by anangaur** [comment]
@rido-min what happens when a package is uploaded with invalid signature (any of the reasons)? IMO that chack should be a synchronous check unlike the virus scanning check that may take some time.

**Comment by rido-min** [comment]
@anangaur any package that does not satisfy the requirements should be rejected. The plan has been to do the check in the async pipeline, although the user perception should be almost instantaneous.

**Comment by anangaur** [comment]
@rido-min Agree. So will the author see a rejection of the package then and there i.e. on the upload workflow? Without navigating to the package page? If yes then all is good :)
It would be weird that for package signing validation, author is navigated to the package page and then the validation fails thereby confusing the author whether to upload the same version again or a new version needs to be uploaded?

**Comment by karann-msft** [comment]
where is the spec for this?
