### ISSUE TITLE
Unable to push packages to NuGet.org?

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5065]
This is a placeholder issue to discuss any issue(s) due to the [recent protocol changes](https://github.com/NuGet/Announcements/issues/10) that was announced early October. We also reached out to all active users on the required changes via mail so that everybody had enough time to react to this `breaking change`. (Also see the [twitter announcement](https://twitter.com/adgrv/status/926140980893442048) early November).

### NuGet client requirements: 

NuGet.org will only accept **push** requests from `nuget.exe` version **4.1.0 and above** or from clients that implement **X-NuGet-Protocol-Version: 4.1.0** and identifies so to NuGet.org through the corresponding header (as explained [here](https://github.com/NuGet/Announcements/issues/10)).

List of known clients that can push packages to NuGet.org:
 
| Client | Requirement | 
| :------------- |:-------------| 
| `nuget.exe` |  [version 4.1.0 or above](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) |
| `dotnet.exe` | [version 2.0.0 or above](https://www.microsoft.com/net/download/windows) |
| VS Team Services | NuGet tasks already use 4.1.0 by default. [Use NuGet installer task to get latest compatible version](https://blogs.msdn.microsoft.com/devops/2017/09/29/using-the-latest-nuget-in-your-build/) |
| MyGet | Already uses the right protocol |
| AppVeyor | NuGet push task uses the right protocol |
| NuGet Package Explorer | [version 3.24 or above](https://www.microsoft.com/store/productId/9WZDNCRDMDM3) |
| Custom client | Should implement the [NuGet.org protocol 4.1.0](https://docs.microsoft.com/en-us/nuget/api/nuget-protocols) |

**Comment by santoshCRM** [comment]
Does anyone get solution for this issue.

**Comment by anangaur** [comment]
@santoshCRM could you let us know the scenario/tool you are using? If it’s any of the above , can you try the right version as specified above.

**Comment by anangaur** [comment]
Closing this issue as it's been a couple of weeks since the announcement.
