### ISSUE TITLE
API to push markdown documentation to NuGet.org

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [NuGet/NuGetGallery#5067]
[Related SO post](https://stackoverflow.com/questions/47497923/push-markdown-documentation-to-nuget-org). I wonder if API to edit existing package and upload `.md` file exists. It would be nice if we can automate it, for example as after push step.

**Comment by skofman1** [comment]
Referencing the discussion issue: https://github.com/NuGet/NuGetGallery/issues/2280

**Comment by skofman1** [comment]
Update on this topic:
We are starting work on allowing to upload markdown documentation as part of the package: https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg

The discussion issue for this feature is here: NuGet/Home#6873
Closing this one as duplicate.

**Comment by ffMathy** [comment]
And how can I specify this documentation via a `CsProj` file in a similar manner to how other properties can be specified there?
