### ISSUE TITLE
Include link to package in email sent to package owners

### ISSUE THREAD

**Issue by Eilon** [NuGet/NuGetGallery#5087]
When someone contacts the author of a package, an email is sent from NuGet.org to the package owners. The email looks something like this:

> ![image](https://user-images.githubusercontent.com/202643/33400880-4f3b6900-d50c-11e7-80db-6406b89c23da.png)

It would be super useful to include a link to the package on the NuGet.org gallery in the email because that's my next step 100% of the time to investigate the issue. (And, unfortunately NuGet.org search doesn't always lead me directly to the package I'm looking for, but that's a discussion for another day.)

I'd like something like this:

> ![image](https://user-images.githubusercontent.com/202643/33400861-40d69ea2-d50c-11e7-81a0-4bb9f035f50c.png)

**Comment by anangaur** [comment]
Should be easy fix but helpful. We did similar enhancements recently to the “Add owner” mails.
/cc: @skofman1

**Comment by Eilon** [comment]
Thanks!
