### ISSUE TITLE
Move to a new version of anglicangeek.markdownmailer

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5102]
Gallery references the old unlisted version from 2011. There is a newer version (which is not unlisted) from 2013. We should use that one: https://www.nuget.org/packages/MarkdownMailer/

**Comment by drewgillies** [comment]
@joelverhagen @skofman1 It appears this newer version has been removed. Shall we close this issue?

**Comment by joelverhagen** [comment]
Yes, I think we'd only update if we had a compelling reason. I don't recall a compelling reason since this issue was filed.
