### ISSUE TITLE
How to install a Nuget.Job, such as HandlePackageEdits? Does it need Azure to be done?

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5110]
@nhathongly commented on [Fri Jun 09 2017](https://github.com/NuGet/NuGet.Jobs/issues/160)

---

@agr commented on [Fri Jun 09 2017](https://github.com/NuGet/NuGet.Jobs/issues/160#issuecomment-307542657)

Under each runnable project there is a `Scripts` directory with, containing a batch script used to run it, which should give you an idea about how to start it.

Example: [HandlePackageEdits.cmd](https://github.com/NuGet/NuGet.Jobs/blob/master/src/HandlePackageEdits/Scripts/HandlePackageEdits.cmd) needs following arguments to run:
* `-VaultName "<Azure KeyVault Vault name>"`
* `-ClientId "<Azure KeyVault ClientID>"`
* `-CertificateThumbprint "<Azure KeyVault Certificate thumprint>"`
* `-LogsAzureStorageConnectionString "<Azure Blob Storage connection string>"`
* `-PackageDatabase "<SQL Server connection string>"`
* `-SourceStorage "<Azure Blob Storage connection string>"`
* `-BackupStorage "<Azure Blob Storage connection string>"`
* `-InstrumentationKey "Azure Application Insights instrumentation key"`
* `-Sleep <time in seconds>`

Not all of them are required, but you'd need to check the [source code](https://github.com/NuGet/NuGet.Jobs/blob/master/src/HandlePackageEdits/HandlePackageEdits.Job.cs) to figure out which one are optional (I'd guess KeyVault settings are optional as well as `InstrumentationKey ` and `Sleep`)

Generally, any job requires whole bunch of command line arguments that are used to pass environment-specific information into the job:
* KeyVault settings;
* AI instrumentation keys;
* Azure Storage connection strings;
* Service URLs;
* DB connection string;
* etc.

The job by itself can run on any computer, but usually no service abstractions are implemented, so, for example, it requires a `SourceStorage` command line argument to be set to a valid Azure Blob Storage connection string.

**Comment by joelverhagen** [comment]
Moved from https://github.com/NuGet/NuGet.Jobs/issues. This repository (NuGetGallery) is meant for all server-side issues.

**Comment by skofman1** [comment]
Closing the issue since the question was answered.
