### ISSUE TITLE
Issue of managing NuGet package

### ISSUE THREAD

**Issue by Samuel98005** [NuGet/NuGetGallery#5117]
Hi,

I have an issue of managing NuGet package. Basically I tried to resolve this issue with a new Visual Studio installation after uninstalling the existing one. This happens in both Visual Studio 2015 Professional and Enterprise edition in Windows Server 2012. 

The error message I have encountered: "Solution is not saved. Please save your solution before managing NuGet packages."
 
Could someone please help on this?

Kind regards,
Samuel

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #6255](https://github.com/NuGet/Home/issues/6255) via [**ZenHub**](https://www.zenhub.com/)
