### ISSUE TITLE
Duplicate metadata elements in nuspec causes serialization of JSON metadata fields as arrays

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5119]
Consider the following nuspec.

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>chenriks-350mb-limit-test</id>
    <version>2.2.0</version>
    <title>chenriks-350mb-limit-test</title>
    <description>chenriks-350mb-limit-test</description>
    <authors>Microsoft</authors>
    <owners>Microsoft, CNTKTeam</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl></licenseUrl>
    <projectUrl></projectUrl>
    <iconUrl></iconUrl>
    <description></description>
    <summary></summary>
    <releaseNotes></releaseNotes>
    <copyright>© Microsoft Corporation. All rights reserved</copyright>
    <tags></tags>
  </metadata>
</package>
```

`<description>` is duplicated

Now consider the generated registration JSON:

```
"@id": "https://az635243.vo.msecnd.net/v3-catalog0/data/2017.12.01.20.50.51/chenriks-350mb-limit-test.2.2.0.json",
"@type": "PackageDetails",
"authors": "Microsoft",
"description": [
    "chenriks-350mb-limit-test",
    ""
],
"iconUrl": "",
"id": "chenriks-350mb-limit-test",
"language": "",
"licenseUrl": "",
"listed": false,
"minClientVersion": "",
"packageContent": "https://apidev.nugettest.org/v3-flatcontainer/chenriks-350mb-limit-test/2.2.0/chenriks-350mb-limit-test.2.2.0.nupkg",
"projectUrl": "",
"published": "1900-01-01T00:00:00+00:00",
"requireLicenseAcceptance": false,
"summary": "",
"tags": [
    ""
],
"title": "chenriks-350mb-limit-test",
"version": "2.2.0"
```

`"description"` is serialized as an array instead of a `string`

This is incorrect and causes our monitoring to fail.

The gallery should reject this package and our V3 jobs should either ignore the duplicated field or skip the package.

**Comment by xavierdecoster** [comment]
The gallery makes use of client APIs such as `NuspecReader` and `PackageArchiveReader.GetNuSpec()`. I suspect those APIs need fixing and become more strict, in order for the gallery and jobs to handle these situations. Thoughts? @scottbommarito

**Comment by joelverhagen** [comment]
This only happens when there are duplicate elements _and_ all but one of elements have whitespace (or empty, or missing) text content. If there are two or more elements with the same element name and non-empty text content, the upload flow reject the package.

**Comment by scottbommarito** [comment]
So should `NuspecReader`/`PackageArchiveReader.GetNuSpec()` ignore whitespace/empty elements?
