### ISSUE TITLE
Performance: Manage Packages view

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5120]
Opened to address server-side performance mentioned in PR #5060 

Potential optimizations:
1.  Packages.cshtml does a lot of UrlHelper.Action calls for Delete DeletePackage and ManagePackageOwners (for each version). With >1500 versions, this accounts for 65.8% inclusive (RouteCollection.GetVirtualPath is expensive).

Fix: Consider single virtual path lookup for DeletePackage, ManagePackageOwners, and Edit package action links then replace route values manually without route configuration lookup.

![image](https://user-images.githubusercontent.com/15364949/33627396-3ff56720-d9b2-11e7-9323-f92f3c3bcbca.png)

2. Packages.cshtml also has a lot of action links for package owner profiles. We should consider the same approach for these.

![image](https://user-images.githubusercontent.com/15364949/33629693-d6238e82-d9b9-11e7-9cee-511b519ec836.png)

**Comment by chenriksson** [comment]
Branch: chenriks-perf-managepackages
Improvement: -32.8% (server) latency (warm)

Before:
- 6.41s (cold)
- 2.96s
- 2.90s
- 2.93s
- Avg (warm) = 2.93

After:
- 4.82s (cold)
- 1.94s
- 2.00s
- 1.98s
- Avg (warm) = 1.97s

**Comment by chenriksson** [comment]
After rebase latest dev, and including Url.Package template.
Improvement: -60.2% (server) latency (warm)

Before:
* 1.63s
* 1.67s
* 1.68s
* Avg (warm) = 1.66s

After:
* 645ms
* 653ms
* 684ms
* Avg (warm) = 660.7ms

**Comment by chenriksson** [comment]
The initial (cold) load of 'Manage Packages' has additional overhead due to EF reflection:

![image](https://user-images.githubusercontent.com/15364949/33694402-bdd7905a-daac-11e7-9c93-61ff3933a6ea.png)

**Comment by xavierdecoster** [comment]
@chenriksson this is in deployed to dev state, is there a way you could verify and label it as such?

**Comment by chenriksson** [comment]
Closing - will verify as part of #5173
