### ISSUE TITLE
Lots of duplicate catalog entries

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5134]
Thanks for the heads up @emgarten.

Since we enabled blocking async validation on PROD, the number of catalog items produced has gone up. This can be illustrated in two ways. The first way, is simply the number of catalog items per hour. This however is not conclusive since maybe we are just more popular 😄.

![image](https://user-images.githubusercontent.com/94054/33691646-064a6f24-da9e-11e7-9ee4-3db8af71e420.png)

Another way is finding the number of packages where that package's first commit timestamp is different than its last commit timestamp. Presumably, if a package is not edited, it only needs a single commit timestamp so the first and last commit timestamp is the same.

![image](https://user-images.githubusercontent.com/94054/33691781-b838384c-da9e-11e7-9fae-27bea036dd12.png)

The orange line "TRUE" is when the first and last commit timestamp is different. The X axis is based off of the first commit timestamp. "FALSE" is when the first and last commit timestamp are the same.

As you can see at 7 PM UTC, December 5, we started getting way more "edit" cases.

I think our Created and LastEdited cursor are picking up the same packages.

**Since async validation means packages are always edited, we can eliminate the created cursor and query.** I am pretty sure this is right but more investigation is needed.

**Comment by skofman1** [comment]
This is a duplicate and was fixed: https://github.com/NuGet/NuGetGallery/issues/6120
