### ISSUE TITLE
Push is not working when WebDAV is installed

### ISSUE THREAD

**Issue by azzlack** [NuGet/NuGetGallery#514]
When WebDAV is installed on the hosting server, it intercepts the PUT and DELETE verbs for all requests.

One solution is to uninstall WebDAV from the server, but the other is to insert the following code to system.webServer\modules:

<code>&lt;remove name="WebDAVModule" /&gt;</code>

**Comment by softboy99** [comment]
on my server , there is no webdav installed at all, but still get the error
