### ISSUE TITLE
Signing out of NuGet.org does not sign me out of MSA login

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5150]
Related to the current MSA/AAD/2FA work:

1. Sign in to NuGet.org using MSA account1
2. Sign out
3. Try to sign in to NuGet.org (hoping to sign in using another MSA account2)
4. You get signed in automatically with account1. You are never completely signed out.

Expected: 
1. Signing out should sign me out of NuGet.org account
2. On clicking 'Sign in' it should prompt me the MSA sign in screen.
3. If I enter the same account1 email address, the sign in should happen automatically as I was already signed in to MSA
4. If I use another MSA account2, I should be prompted for password and 2FA (if req) just like normal MSA sign in process.

**Comment by joelverhagen** [comment]
Note that a couple of customers have successfully worked around the problem by using an InPrivate/Incognito browser window.

**Comment by joelverhagen** [comment]
Using Firefox seems to be another workaround.

**Comment by anangaur** [comment]
Don’t see a label for regression.

**Comment by skofman1** [comment]
we don't have one.. it's Priority 1 so will fix ASAP

**Comment by KirillOsenkov** [comment]
We've encountered the same issue (@kzu) and found a workaround.

If you have signed in using Account 1, go to some website (*.visualstudio.com) where you're signed in using the same account, then sign out of there. Go back to nuget.org, sign out of there. Then, when signing back on nuget.org it will offer the account picker again.

**Comment by shishirx34** [comment]
@KirillOsenkov - The issue is fixed and now in production. Please try out the login scenario to confirm. Thank you for your patience.

**Comment by KirillOsenkov** [comment]
Confirmed, works great now! Thanks.
