### ISSUE TITLE
Edit page error handling is broken

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5155]
Issue 1: Edit page doesn't show errors
Issue 2: When accessing Edit page for a package that doesn't exist 500 is returned. 
Issue 3: When accessing Edit page for a package that is not yours, 500 is returned.

**Comment by scottbommarito** [comment]
We should find a way to unit/functional test this so it doesn't happen again--it would be very bad if somebody didn't know what was wrong with their package on upload/edit.
