### ISSUE TITLE
Private Gallery logon after migaration

### ISSUE THREAD

**Issue by MatzeG** [NuGet/NuGetGallery#5161]
Hello 

i´m using a private GalleryServer based on your development. I´ve tryed to migrate from a Version 08/2013 to the current version. After the mirgration I can´t logon - i had to use the Forgot Password process. Is this normal or must I set a special entry in the web.config?

Thx for Help
Matthias

**Comment by skofman1** [comment]
Hi @MatzeG ! 
A long time passed since 2013.. I'm not sure what caused the login issue, but can assume that it's related to password hashing algorithms changing. Glad to hear that you were able to resolve the issue using the password reset process.
