### ISSUE TITLE
Consider reuse of routeUrlTemplates in UrlExtensions

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5162]
Per discussion with @scottbommarito in #5138, there's some refactoring that we could do in UrlExtensions for code reuse and possibly performance.

Options:
- Shared helper between Url.Package and Url.PackageRegistrationTemplate (and similar APIs)
- Static cache of RouteUrlTemplate, and use of it by Url.Package (and simliar APIs)

**Comment by skofman1** [comment]
@chenriksson , is this something we are planning to implement in the near future? If not, lets close. I'm trying to reduce the number of issues we have that focus on code refactoring.

**Comment by chenriksson** [comment]
Closing due to priority of refactoring
