### ISSUE TITLE
[Dev] JS Exception when loading APIKeys page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5170]
The erro from AI:
Cannot read property 'PackageIds' of undefined /account/ApiKeys
Error in: page-api-keys.min.js

![image](https://user-images.githubusercontent.com/16807822/33856673-b3f169ba-de7d-11e7-96d4-b7ce23cb95a9.png)

**Comment by chenriksson** [comment]
@skofman1 Having trouble reproducing... if you get a repro, can you show it to me?

**Comment by skofman1** [comment]
Try this: 
1. Regenerate an api key
2. Click edit 
3. Click cancel

**Comment by skofman1** [comment]
couldn't repro. Probably fixed.
