### ISSUE TITLE
Validation is taking more than 3 hours

### ISSUE THREAD

**Issue by andreminelli** [NuGet/NuGetGallery#5198]
The 'Takenet.MessagingHub.Client.InfoEntertainmentExtensions' package has been published 3 hours ago and is still 'validating'.
There is no active alert on status.nuget.org. Can you please check what is going on?

**Comment by christophwille** [comment]
Same here - https://www.nuget.org/packages/ICSharpCode.Decompiler/our 3447 patch release is now stuck validating for almost three hours.

**Comment by skofman1** [comment]
Hi,

We are currently experiencing an incident with our package validation pipeline. Newly pushed packages are taking several hours to become publicly available. You can get updates on our status page: https://status.nuget.org

Apologies for the inconvenience.

**Comment by skofman1** [comment]
Closing since this is duplicate of: https://github.com/NuGet/NuGetGallery/issues/5199
