### ISSUE TITLE
I get an email saying my nuget package is published but hours later it is not

### ISSUE THREAD

**Issue by bradphelan** [NuGet/NuGetGallery#5199]
I pushed my nuget package and received an email confirming that it is published. However many hours later it is still not published and the [nuget url](https://www.nuget.org/packages/ReactiveCompositeCollections/1.3.3-ci.2) gives a 404

![image](https://user-images.githubusercontent.com/17650/34110041-bec80802-e405-11e7-9209-62c39b926af6.png)

![image](https://user-images.githubusercontent.com/17650/34110100-ea869f9e-e405-11e7-85c4-f566aa5eff2d.png)

[ReactiveCompositeCollections.1.3.3-ci.2.zip](https://github.com/NuGet/NuGetGallery/files/1568185/ReactiveCompositeCollections.1.3.3-ci.2.zip)

Zip file of the archive is added.

**Comment by skofman1** [comment]
Hi,

We are currently experiencing an incident with our package validation pipeline. Newly pushed packages are taking several hours to become publicly available. You can get updates on our status page: https://status.nuget.org

Apologies for the inconvenience.

**Comment by bradphelan** [comment]
OK.  Thank you for the information.

**Comment by skofman1** [comment]
This was resolved.

**Comment by gep13** [comment]
@skofman1 are you certain that this issue was resolved?  We pushed a new package at 08:34 today, and almost 1 hour later, we are still not seeing the package on NuGet.org.  We also haven't received any emails about the package being pushed.  Should we be worried?  Thanks.  The NuGet.org status pages suggests that the validation stage should take no more than 10 minutes.

**Comment by gep13** [comment]
I have just logged into our account, and I am at least seeing this:

![image](https://user-images.githubusercontent.com/1271146/34199914-26cd42a2-e567-11e7-9940-4494432475ea.png)

Which suggests it can take up to 1 hour, which is different to what is stated on the Status page.

Any ideas on why an email about the new package being pushed wasn't delivered?  Or will this only happen after the validation step is completed?

**Comment by skofman1** [comment]
@gep13 , we experienced an issue with our validation pipeline. This is now resolved, and your packages should be available for download.
We deployed new functionality a few weeks ago and are still working through issues.
Regarding the e-mail - it will be sent after the validation is completed.

**Comment by cdmdotnet** [comment]
This seems to be happening again today.
