### ISSUE TITLE
Let users accept non infringement of trademark while registering a username with NuGet.org

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5205]

**Comment by skofman1** [comment]
@anangaur , is this a requirement? If so, please provide more details.

**Comment by anangaur** [comment]
@skofman1 Placeholder to define the spec. Will soon add the details.

**Comment by skofman1** [comment]
soon? :)

**Comment by anangaur** [comment]
We should do what marketplace already does :)
