### ISSUE TITLE
Unable to push pakcaages in staging.nuget.org site using command line 

### ISSUE THREAD

**Issue by joo92** [NuGet/NuGetGallery#5211]
1.Set API Key for [https://int.nugettest.org/](url) site.
`>nuget setAPIKey XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX -source https://apiint.nugettest.org/v3/index.json`

2.Push package in [https://int.nugettest.org/](url) site.
`>nuget push *.nupkg -source https://apiint.nugettest.org/v3/index.json`

I get Forbidden Error like below.

` PUT https://int.nugettest.org/api/v2/package/
ARNING: Your API key expires in 1 days. Visit https://int.nugettest.org
to regenerate your API key.
 Forbidden https://int.nugettest.org/api/v2/package/ 41570ms
Response status code does not indicate success: 403 (The specified API key invalid, has expired, or does not have permission to access the specified.`

Can you please suggest solution to upload packages in   [https://int.nugettest.org/](url) site for testing purpose.

**Comment by chenriksson** [comment]
@joo92 The message suggests that your API key will expire soon, but also that there is some reason that your API key does not have permission for that push operation.

Please log into https://int.nugettest.org and go to the 'API Keys' page under the upper right (username) menu. Look for your API key, and check the following:
- Expiration
- Does it have push scope enabled? (highlighted below)
- Does the glob pattern match the id of the package being pushed?

![image](https://user-images.githubusercontent.com/15364949/34220080-1ff5c750-e568-11e7-88b1-b33c0d700705.png)

If you still can't determine why the API key is not working, I suggest sending an email to support@nuget.org with a description of your problem, and your username on the https://int.nugettest.org site.
