### ISSUE TITLE
package pushed to nuget.org not showing up (2 hrs later)

### ISSUE THREAD

**Issue by fluffynuts** [NuGet/NuGetGallery#5212]
I pushed version 1.0.98 of [NExpect](https://nuget.org/packages/nexpect) around 2 hours ago
![image](https://user-images.githubusercontent.com/4669340/34201461-3c648eb6-e57d-11e7-80bd-2645d7156330.png)
And I still don't see it at the package page (not even with the warning that it's being indexed):
![image](https://user-images.githubusercontent.com/4669340/34201501-591e781e-e57d-11e7-9923-716091749152.png)

Please investigate.

**Comment by geoffreymcgill** [comment]
We too are experiencing the same delay in indexing. Pushed two new packages and currently at 3 hrs since package upload was completed.

**Comment by scottbommarito** [comment]
We're investigating this now. Thanks for the heads up.

**Comment by gep13** [comment]
I posted here on this closed issue:

https://github.com/NuGet/NuGetGallery/issues/5199#issuecomment-353009694

Since I was having the same problem.  We have been waiting almost 6 hours now 😢

**Comment by skofman1** [comment]
@fluffynuts , we experienced an issue with our validation pipeline. This is now resolved, and your packages should be available for download. 
We deployed new functionality a few weeks ago and are still working through issues.
