### ISSUE TITLE
Cannot edit release notes etc after uploading new version of package

### ISSUE THREAD

**Issue by ameed** [NuGet/NuGetGallery#5213]
I have tried with both chrome and IE, still I do not get to edit release notes, summary, project url, description etc, when uploading new verion of my package

![cannot update release notes for new version](https://user-images.githubusercontent.com/343796/34211188-9b608cec-e598-11e7-9401-bca2bc05d14f.PNG)

**Comment by chenriksson** [comment]
@ameed This is a recent change which you can read more about on our [Package Immutability](https://github.com/NuGet/Home/wiki/Package-Immutability) wiki.

You should see the following informational banner, but it appears we have a bug where it's not shown on the initial upload. It will appear if you navigate away and return to finish the upload.

![image](https://user-images.githubusercontent.com/15364949/34220342-2934dfc6-e569-11e7-839d-34e07e9e1e88.png)

I opened issue #5214 to track this.
