### ISSUE TITLE
Package immutability banner not displayed on initial upload

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5214]
The 'Please verify the package metadata below` banner should display on initial upload. Here's what I see instead:

![image](https://user-images.githubusercontent.com/15364949/34220716-69052fa6-e56a-11e7-877e-7a2753503e88.png)

If I navigate away and return, then it displays:

![image](https://user-images.githubusercontent.com/15364949/34220703-5d75ab52-e56a-11e7-9487-ed13b036920f.png)

**Comment by skofman1** [comment]
Can't repro... closing.
