### ISSUE TITLE
Show dotnet install command for template packages

### ISSUE THREAD

**Issue by nojaf** [NuGet/NuGetGallery#5216]
It would be nice if the site shows the `dotnet new -i PackageName` when the nuget package is a dotnet cli template, for example [Giraffe](https://www.nuget.org/packages/giraffe-template/).

![image](https://user-images.githubusercontent.com/2621499/34246832-7d9912ea-e630-11e7-8121-eb7f024bc3d7.png)

**Comment by joelverhagen** [comment]
@am11 this change is deployed to nuget.org. Thanks again for your contribution.

**Comment by am11** [comment]
Thanks for the production deployment! :)

Just tried out this template and noticed that CLI does not list the installed version of templates, so I have opened an issue: https://github.com/dotnet/cli/issues/12805.
