### ISSUE TITLE
Verification email is never sent, Contact form also not working

### ISSUE THREAD

**Issue by jnicolau** [NuGet/NuGetGallery#5218]
I've tried to verify my email but never received any verification email, even after hitting resend button many times. And I've also checked that it hasn't been sent to the Spam folder.
I've also used the Support email address and Contact from requesting for help and got no answer, plus I've clicked the "Send me a copy" and it didn't send anything.
Can somebody help me?

Regards

**Comment by shishirx34** [comment]
The issue has been resolved.
