### ISSUE TITLE
ReadCursor and ReadWriteCursor should be interfaces, not abstract classes

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5221]
E.g. [ReadCursor](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Cursor/ReadCursor.cs) and [ReadWriteCursor](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Cursor/ReadWriteCursor.cs)

**Comment by skofman1** [comment]
Is there an impact for the current code? 
We can change this code if needed in the future, no reason to track this.
