### ISSUE TITLE
Update copyright year in NuGet gallery footer

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#5233]
The year in the footer should be updated to 2018!

![image](https://user-images.githubusercontent.com/10507120/34582208-097c4422-f148-11e7-9871-823e63feac13.png)

**Comment by mishra14** [comment]
cc: @joelverhagen

**Comment by joelverhagen** [comment]
Since this lives in config, current code can't auto-update the year. We should consider a token replacement. For example, config has `&copy; Microsoft {year}` and the app code replaces `{year}` with `DateTime.UtcNow.Year`.
