### ISSUE TITLE
Cake user agent currently not recognized by the NuGet gallery stats 

### ISSUE THREAD

**Issue by devlead** [NuGet/NuGetGallery#5238]
Since Cake [v0.24.0](https://github.com/cake-build/cake/releases/tag/v0.24.0) in process NuGet handling now has a "Cake NuGet Client" user agent, so those downloads now incorrectly falls under _"unknown"_ client.
 
I've submitted pull request NuGet/NuGet.Warehouse#6 to address this.

**Comment by skofman1** [comment]
Thanks for the contribution!
However the PR is in the wrong place :)
Please modify:
https://github.com/NuGet/NuGet.Jobs/blob/9e793e057e77e19b6abd8563b51424bd5c650b3e/src/Stats.ImportAzureCdnStatistics/knownclients.yaml
https://github.com/NuGet/NuGet.Jobs/blob/9e793e057e77e19b6abd8563b51424bd5c650b3e/tests/Tests.Stats.ImportAzureCdnStatistics/UserAgentParserFacts.cs

**Comment by devlead** [comment]
Cool, will do.

**Comment by devlead** [comment]
@skofman1 PR NuGet/NuGet.Jobs#297 submitted.

**Comment by devlead** [comment]
PR now merged. 👍

**Comment by skofman1** [comment]
@devlead , we will close the issue once the fix is deployed.

**Comment by loic-sharma** [comment]
This is now deployed to PROD. We should be able to verify tomorrow by seeing `Cake NuGet Client` tomorrow on packages' download statistics (like [Newtonsoft's](https://www.nuget.org/stats/packages/newtonsoft.json?groupby=ClientName))!

**Comment by loic-sharma** [comment]
Verified that the package `Cake.Npm` has downloads from the client `Cake NuGet Client` (using [this page](https://www.nuget.org/stats/packages/Cake.Npm?groupby=ClientName)).
