### ISSUE TITLE
Nuget.org is unable to install the packages at my machine.

### ISSUE THREAD

**Issue by AkankshaVyas** [NuGet/NuGetGallery#5253]
Hello,
I'm working on VS 2015 with Windows 10. I'm not able to install any packages from package manager console or from any source in VS either. the url https://api.nuget.org/v3/index.json is not returning anything. Kindly check my endpoint asap.

Thanks
Akanksha Vyas

**Comment by skofman1** [comment]
@AkankshaVyas , the issue you are experiencing is likely a connectivity problem with our CDN. There are instructions here on how to troubleshoot this: 
https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible
Please collect the data and send to us at support@nuget.org
