### ISSUE TITLE
Package release notes invalid?

### ISSUE THREAD

**Issue by SteveWilkes** [NuGet/NuGetGallery#5268]
Hullo,

I've just added a new version of [a package of mine](https://www.nuget.org/packages/AgileObjects.AgileMapper/0.19.0) and while uploading, if the release notes contained this line:

\- Adding mapping extension methods - obj.Map().ToANew<Target>(), obj.Map().Over(otherObj), etc

...the upload page rejected the package, saying its manifest was invalid. Once I changed that line to:

\- Adding mapping extension methods

...it worked.

Why was the original version of that line unacceptable?

Thanks in advance,

Steve

**Comment by shishirx34** [comment]
Hi @SteveWilkes - do you mind sending the package that failed to upload to support@nuget.org, so that we can investigate this issue. I wasn't able to repro it with your package and modifying the release notes with the above said text. Please mention this issue in the email and refer it for me so that it can be routed appropriately.

**Comment by shishirx34** [comment]
Also, just to double check, did you use NuGet Gallery to upload the package or the CLI/nuget.exe?

**Comment by SteveWilkes** [comment]
Hi @shishirx34 ,

This was using the NuGet gallery, but would you believe it - I just updated the package release notes (and file name and version number) and tried again it worked fine. I'll email the original package over anyway, just in case.

Cheers,

Steve

**Comment by SteveWilkes** [comment]
I've tried emailing the package as a .nupkg and as a .zip - both emails have been returned as blocked.

**Comment by shishirx34** [comment]
Is there anyway you can upload this to onedrive or dropbox and send us a link on support@nuget.org?

**Comment by SteveWilkes** [comment]
It's on Dropbox [here](https://www.dropbox.com/s/k9o9g7wb38c9jf5/AgileObjects.AgileMapper.0.19.0.nupkg?dl=0).
