### ISSUE TITLE
NuGet.Server - The type or namespace name 'NuGet' could not be found

### ISSUE THREAD

**Issue by muus84** [NuGet/NuGetGallery#5279]
We are currently using NuGet.Server in version 2.11.2. After upgrading to 3.0.2.0 and compiling I'm getting a compiler error for line 3. 

 CS0246: The type or namespace name 'NuGet' could not be found (are you missing a using directive or an assembly reference?)

`
1:  <%@ Page Language="C#" %>
2:  <%@ Import Namespace="NuGet.Server" %>
**3:  <%@ Import Namespace="NuGet.Server.App_Start" %>**
4:  <%@ Import Namespace="NuGet.Server.Infrastructure" %>
5:  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

`

I already tried to create a new project/solution with target framework 4.6 and above.

**Comment by joelverhagen** [comment]
While you're editing a C# (.cs) file in your project, what do you have the `NuGetODataConfig` available to you? That type is in `NuGet.Server.App_Start` namespace.

If not, could you provide your .csproj here? It should have a reference like this:
```xml
    <Reference Include="NuGet.Server, Version=3.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\NuGet.Server.3.0.2\lib\net46\NuGet.Server.dll</HintPath>
    </Reference>
```

This is the assembly that is bringing in that namespace.
