### ISSUE TITLE
AAD / Sign in flow change

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5281]
see Sign-In Flow change in [OneNote](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Security.one%7CD36A0B17-E33C-43DE-B487-A40CAFAAA9E4%2FMicrosoft%20Logins%20%28MSA%5C%29%20and%20Nuget%20Gallery%7C4DD50740-0935-4235-8ADC-9F9A9CF013F1%2F%29)

Work includes:
- create new page for rejecting some logins

**Comment by skofman1** [comment]
will be tested as part of https://github.com/NuGet/NuGetGallery/issues/5399
