### ISSUE TITLE
Copy command button size on the package page does not match the command line height

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#5294]
4K display running at 150% scale in display properties results in the following:

https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/

![image](https://user-images.githubusercontent.com/102933/35172237-a3bf2426-fd1b-11e7-9237-becd48a6f99b.png)

or on Paket tab:

![image](https://user-images.githubusercontent.com/102933/35172277-d61e7a3e-fd1b-11e7-80b7-808579bbb41b.png)

Happens in Chrome and Chromium based browsers (fine in Edge and Firefox).

**Comment by skofman1** [comment]
@agr, please check if this still repros
