### ISSUE TITLE
VSIX user agent string update

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#5296]
The user agent for NuGet VS VSIX has changed and needs to be recognized by the stats pipeline.
See client issue https://github.com/NuGet/Home/issues/5853 (PR https://github.com/NuGet/NuGet.Client/pull/1967)

**Comment by xavierdecoster** [comment]
What's the priority/desired ETA for this? cc @skofman1 @nkolev92 @emgarten

**Comment by skofman1** [comment]
This is high priority. On-call can take it this week.
