### ISSUE TITLE
[BugBash] Package list table does not fit its borders

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#5303]
On the [my packages page](https://dev.nugettest.org/account/Packages):
![image](https://user-images.githubusercontent.com/102933/35238156-8bdba846-ff61-11e7-8b61-8a4eb213e909.png)

Either table width should be compacted, or border widened, so there is no overlap

**Comment by chenriksson** [comment]
Removing `Organizations` epic, as this is more of a version formatting issue. Moving to backlog.
