### ISSUE TITLE
Base lines of organization icon and the organization name are not aligned

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#5305]
On the [My packages page](https://dev.nugettest.org/account/Packages) in the "Owners" column organization icon is few pixels above the other text base line:

![image](https://user-images.githubusercontent.com/102933/35238416-399e344e-ff62-11e7-8e12-40e7ab50bc5f.png)

**Comment by chenriksson** [comment]
Closing as duplicate of #5298
