### ISSUE TITLE
change default https port (443)

### ISSUE THREAD

**Issue by georgiuk** [NuGet/NuGetGallery#531]
Hello,
we are trying to set nuget gallery. is there a way to change the default https port (443)  to 446?

Thank you

**Comment by xiaoxstz** [comment]
> Hello again, I have a hardcoded answer that seems to work in RequireRemoteHttpsAttribute.cs I added the port
> 
> string url = "https://" + filterContext.HttpContext.Request.Url.Host + ":446" + filterContext.HttpContext.Request.RawUrl;
> 
> maybe this cuold be a web.config property (like sslport)

However, RequireRemoteHttpsAttribute.cs disappears since 2013.
* `NuGetGallery/RequireRemoteHttpsAttribute.cs` was renamed to `Fiters/RequireSslAttribute.cs`
* `Fiters/RequireSslAttribute.cs` was deleted since 2017

**Comment by xiaoxstz** [comment]
See #9331
