### ISSUE TITLE
[BugBash] Layout and functionality issues with Manage packages page for Organizations

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#5310]
Couple of things:
1. The drop down box should be placed a little higher on par with "My packages"
2. The filter should be applicable to all packages on the page not just 'listed' 'unlisted' sections
3. 'My Reserved namespaces' section seems misplaced on this page, perhaps it should be moved to accounts page based on @anangaur's feedback. @diverdan92 - for visibility.
4. 'My reserved namespaces' section doesn't show the reserved namespaces for the organization(I was a collaborator)
4. The 'Pending ownership request' doesn't show incoming requests for the organization account to the collaborators.

**Comment by scottbommarito** [comment]
Regarding number 5: this is intentional, because collaborators cannot accept incoming requests for the organization account.

Note that it does not show incoming requests for the organization account to admins, which it probably should.

**Comment by chenriksson** [comment]
Work remaining to populate organization data and allow filtering for namespaces and owner requests sections.
