### ISSUE TITLE
Owner dropdown appears upload UI when package ID already exists

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5312]
![image](https://user-images.githubusercontent.com/94054/35239833-6d915fb6-ff66-11e7-9612-5446599184a3.png)

This makes no sense since the owner set is already fixed.

**Comment by scottbommarito** [comment]
@anangaur This is more of an experience bug than a code bug. What do you suggest we show for owner in this scenario? Should we show the dropdown at all?

**Comment by anangaur** [comment]
No dropdown. Just a list of owners should be fine. Not showing the owners here is fine too.
