### ISSUE TITLE
[Organizations] After beginning an upload, the "Owners" dropdown in the Verify form always shows current user

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#5316]
Logged in as "sharma.loic", a collaborator on Microsoft organization and site admin. Uploaded a new version of "Microsoft.AspNet.WebApi.Core", which only the Microsoft organization owns. The "Owner" field on the upload verification page incorrectly showed "sharma.loic" in text (it should've been "Microsoft"). Submitting the form fails. Reloading the page or manually changing the owner value to "Microsoft" allows the form to be submitted.

**Comment by scottbommarito** [comment]
Changed title to reflect problem better.
