### ISSUE TITLE
[BugBash] Email confirmation sent for the API keys created for an org is exactly the same as the one sent for personal key

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#5321]
> API key 'Microsoft.CSharp-only' was added to your account and can now be used. If you did not request this change, please reply to this email to contact support.

Wording should be different for the org API keys.

**Comment by agr** [comment]
Is copy sent to org email, too?

**Comment by scottbommarito** [comment]
So technically, org API keys are tied to your account, not the org, so this description makes sense. Something else to consider is that no other information about the API keys is described in the email either: e.g. the allowed actions, the allowed packages. I think it would be nice to display all this information.

**Comment by agr** [comment]
So org API keys are not visible to collaborators, right?

**Comment by chenriksson** [comment]
Collaborators can create API keys for their org too, but can't use the 'push new' scope.

**Comment by chenriksson** [comment]
Closing, as this will be part of #5277
