### ISSUE TITLE
NuGet gallery UI should use breadcrums for account/organization settings/profile/API-keys

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5331]
As discussed with @chenriksson , @joelverhagen. Details TBD.

**Comment by chenriksson** [comment]
@anangaur Maybe as part of this issue we can also revisit whether the temp message should span the full width (12 columns) instead of the page width? Sounds like page width was the decision from site redesign.

**Comment by chenriksson** [comment]
opened #5347 for that

**Comment by skofman1** [comment]
This was done: https://github.com/NuGet/NuGetGallery/issues/5723
