### ISSUE TITLE
Allow packages that failed signing validation to be re-submitted by the customer

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5345]
Today, when a package fails validation the user must publish a new version of the package to fix the issue. For example, suppose they use an untrusted timestamping server for signing. This can be fixed pretty easily by the customer so it makes sense to allow them to republish that same package version after they resign the package.

This needs some design, but it general it makes sense I think.

/cc @karann-msft

**Comment by skofman1** [comment]
was done
