### ISSUE TITLE
Nuget 404 on custom nuget server

### ISSUE THREAD

**Issue by kj1981** [NuGet/NuGetGallery#5350]
I have created a nuget server on my dev server but everytime I try to push the package from my local machine using the following command it errors out with 404 not found.

nuget.exe push MyProject.1.0.0.nupkg nugetkey -Source http://devserver.com/CustomNuget/nuget

I am running NuGet.Server v3.0.2.0

Have tried everything from giving permissions, running under app pool account, increasing max request length, giving folder permissons etc.

Also if I deploy it to my local and do push as below then there is no issue and works fine:

nuget.exe push MyProject.1.0.0.nupkg nugetkey -Source http://localhost/CustomNuget/nuget
-------------
Updated
-------------
Another thing is:
When I browse to my nuget server at  http://devserver.com/CustomNuget/ I get the following:

In the package manager settings, add the following URL to the list of Package Sources:
http://devserver.com/CustomNuget/nuget

Use the command below to push packages to this feed using the NuGet command line tool (nuget.exe).
nuget.exe push {package file} {apikey} -Source http://devserver.com/CustomNuget/nuget

But when I try browsing to 
 http://devserver.com/CustomNuget/nuget I get 404 error in my browser

And then if I try to use 

nuget.exe push MyProject.1.0.0.nupkg nugetkey -Source http://localhost/CustomNuget/
(removing nuget at the end)
I get 405 method not allowed error

**Comment by cfmayer** [comment]
I use a publish source of `http://<server>/<virtual dir>/api/v2/package`. Then for the  NuGet.config: `<add  key="<source name>" value="http://<server>/<virtual dir>/api/v2" protocolVersion="2" />`

**Comment by kj1981** [comment]
I added under app settings as below in my devserver nuget config file
<add key="NugetKey" value="http://devserver.iso.com/CustomNuget/api/v2" protocolVersion="2" />

Now when I try to browse my web server it gives me error:

Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: Unrecognized attribute 'protocolVersion'. Note that attribute names are case-sensitive.

**Comment by cfmayer** [comment]
Did you add that to the web.config? If so, remove it. It belongs in the NuGet.config so your projects know where to find the packages you've uploaded to the custom NuGet site.

**Comment by kj1981** [comment]
I have done the changes as you suggested and I get the same error.

Pushing MyProject.1.0.0.nupkg to 'http://devserver.com/CustomNuget/nuget'...
  PUT http://devserver.com/CustomNuget/nuget
  NotFound http://devserver.iso.com/CustomNuget/nuget/ 112ms
Response status code does not indicate success: 404 (Not Found).

**Comment by Nokecy** [comment]
@kj1981  Is the apiKey set up

**Comment by valeriob** [comment]
Same problem here, it works on iis express, but not when published to IIS : 
![image](https://user-images.githubusercontent.com/1522516/41102754-e520f016-6a67-11e8-9e0c-01a728ca7340.png)

**Comment by gbirchmeier** [comment]
I'm seeing this error too.

It's strange: we have some builders that do it, but some that don't.  I'm trying to figure out what the difference is.

**Comment by valeriob** [comment]
Yep, if i publish the web app it does 404 on http://localhost:8080/nuget/Packages
If then i copy the *.dll from the NuGet.Server\bin to the same running folder, it works...

**Comment by gbirchmeier** [comment]
I have a hypothesis, thanks to [this StackOverflow answer](https://stackoverflow.com/a/41680587/650475).

**Hypothesis:** I suspect that my web server is configured to disallow uploads greater than a certain file size.  I'm not sure what the http response to Nuget actually is, but Nuget wrongly reports back to the user that it's a 404.

**Supporting evidence:** We have many builders that release Nuget packages to our server.  Only one fails to upload, and it's the biggest one.  It's quite a bit larger than the rest, which fits the hypothesis perfectly.

I strongly believe that this is the root cause.  Due to certain colleagues being on vacation at the moment, I cannot alter the server today, so it will be some time before I can confirm this hypothesis.  But I hope to do so as soon as possible.

**Comment by valeriob** [comment]
Thanks @gbirchmeier !
Btw it fails also on a simple get on http://localhost:8080/nuget/Packages

**Comment by rogatec** [comment]
Is there a current solution?
I run also into this error after updating NuGet.Server to 3.1.2. The root url of my NugetServer works, but the url path to `http://localhost:58330/nuget/Packages` fails with an 404 error.

**Comment by valeriob** [comment]
@rogatec you have to update the publish bin folder with the dll from the bin folder.

**Comment by rogatec** [comment]
Actually what fixed my problem was, that I by mistake created the nuget.server project as a vb.net application. I fixed it to C#, afterwards everything worked fine (no copy/paste of dlls).

**Comment by valeriob** [comment]
Why closed ? i do not see a commit that fixes the publishing issue :(

**Comment by MadCoder253** [comment]
If anyone sees this issue. I fixed my problem by making sure a file in the "/Packages" folder has "Copy to Output Directory" = "Copy if newer". This makes sure the "/Packages" folder is created on the remote site. Otherwise, you will end up with a missing folder, causing a 404 error.

NOTE: I just marked "Readme.txt" to get outputted during the build/publish.

**Comment by manuelxmarquez** [comment]
I also struggled with this issue for a few hours trying all the suggestions. I also tried copying the DLLs like above but it didn't work... until I copied the Debug DLLs and it did. Figuring there was probably a compiler condition I searched and found App_Start\NuGetODataConfig.cs

`// The consuming project executes this logic with its own copy of this class. This is done with a .pp file that is
// added and transformed upon package install.
#if DEBUG
[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(NuGet.Server.App_Start.NuGetODataConfig), "Start")]
#endif`

Removing the if solved it for me and I could deploy the publish output. Hope that helps someone else looking for a solution!

**Comment by adityapewekar** [comment]
Hello Guys, I am facing the same issue i.e. 404 Not Found while trying to upload package on local server
I tried almost all the available feedbacks. Following are the few

1. Copy Dll from Project bin folder to the folder where website is deployed locally on IIS
2. [assembly: WebActivatorEx.PreApplicationStartMethod(typeof(NuGet.Server ... is not in If Else condition
3. Re publish the code by changing Packages folder properties to Output Directory" = "Copy if newer"
4. Added PUT verb on IIS request filtering
5. Tried the nuget.exe push on different URL's like http://localhost/nuget, http://localhost/nuget/packages, http://localhost/packages, http://localhost/api/v2/packages
6. Updated the <requestLimits maxAllowedContentLength="31457280"/> on web config
7. api key is setup

https://nicolaiarocci.com/how-to-build-and-deploy-a-private-nuget-server-on-iis-or-azure/
Above is the link i followed as instruction

I created an empty web application using C# on 4.6 framework and added nuget.server 3.4.1 from package console and hosted the site over IIS. I am able to view the home screen but when navigated to http://localhost:6000/nuget am getting 404 Not Found.
When am executing below command from cmd even though am getting the 404 not found error.
Command : 
nuget.exe push {package file} {apikey} -Source http://localhost/nuget

Am I missing any thing ?
