### ISSUE TITLE
Clean up invalid ownership requests

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#5354]
There are some pending ownership requests for packages that a user is already an owner of. For such requests, clicking on confirm or reject should delete the request apart from showing the message that you are already an owner of the 'Foo.Bar' package.
Additionally, we could have a job running that would would check for invalid ownership requests (that may be invalid for several reasons i.e. if any of the three entities are no longer around - the requester, the approver, the package)

cc: @shishirx34 @scottbommarito

**Comment by skofman1** [comment]
@karann-msft , is this still needed?

**Comment by karann-msft** [comment]
@skofman1 - you tell me :) 

I don't have that issue with Microsoft account but can you check the db to ensure other users are not stuck in the same bucket? @shishirx34 had helped resolve this first time around looking into the db.

**Comment by skofman1** [comment]
I found 4 instances of this, last one in 2016. I think it's safe to close this issue.
