### ISSUE TITLE
[ASK]: Show some sign of unofficial packages for reserved namespace packages

### ISSUE THREAD

**Issue by jainaashish** [NuGet/NuGetGallery#5359]
This ask has come from a customer support request where he suggested to reserve namespace like System for specific account or organization, which we already have in place for new packages. But he was confused with some existing packages.

So, the proposal is, to show some kind of indication on existing packages, which has these reserved namespace which aren't owned by those official accounts. Some differentiating factor which clearly tells consumer that this package is from the official account or entity but still doesn't down vote or show any negativity for that package.

**Comment by skofman1** [comment]
When we designed the reserved namespaces feature, we explicitly decided not to show any "negative" icons on packages described in the case above.
