### ISSUE TITLE
Automate and Improve status page when the service degrades

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5369]
When a service degrades and the status is updated to reflect the same, the status page reverts to normal (Green) in some time (~4 hours?) even if the degraded service is back again. This causes lot of confusion to people. 

We should also automate update of status messages for degrades like package validation,  CDN issues, service unavailability etc.

Ideally if our monitoring systems are able to find out an issue with the service, the following should happen:
1. A GitHub issue should be filed for the service degrade
1. Status page messaging should reflect the corresponding service degrade. It should link to the above mentioned issue.
2. When all is well, the Github issue should be closed (auto/manual) and that should trigger the degrade message to be marked as operational again.

**Comment by skofman1** [comment]
this was done.

**Comment by renemadsen** [comment]
> this was done.

Does it work like this now?

Having 1 package, which have been stuck in validating for 1 hour now and there is nothing to see on https://status.nuget.org/

**Comment by skofman1** [comment]
@renemadsen , we had an outage in the validation pipeline this morning. Your package should already be published. Please let me know if it wasn't.
Here are the updates that appeared on status page:
![image](https://user-images.githubusercontent.com/16807822/92638158-b853d100-f28e-11ea-98e6-a4143fa9a4bd.png)
