### ISSUE TITLE
Deletion in private gallery

### ISSUE THREAD

**Issue by georgiuk** [NuGet/NuGetGallery#537]
Hello,
we try to use nuget gallery in private and controlled server. Is there an easy call that can be used to delete permanently a package?I mean also in the default nuget gallery, you delete packages upon request. This is something we want to do in our private gallery.  What is the procedure/script/call to do that? should we write an sql script that takes all out all the references of the package? For which tables? Any directions would be very appreciative. 

Thank you
Kostas

**Comment by michaelsync** [comment]
@anurse The link for NuGet Operations is dead. Do you have the update?

**Comment by anurse** [comment]
The new repo is here https://github.com/NuGet/NuGet.Operations, though the commands have likely changed. I'm no longer with the team though, so things may be been moved or adjusted since I last used it :)
