### ISSUE TITLE
Notify package owner in case publishing is taking longer than expected

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#5371]
Today, when NuGet.org is experiencing a delay in publishing packages, we don't notify the package owner. Ask - automatically send an email to owners of packages that are affected by the delay i.e. they don't get published in 'x' minutes.

**Comment by skofman1** [comment]
@karann-msft , we invested in improving performance of indexing, so the need for this is reduced significantly. Also, if the package validation is delayed an e-mail will be sent. Please reopen if you disagree.
