### ISSUE TITLE
Having problem working with packages.nuget.org/api/v2

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/NuGetGallery#5377]
(Bug created from support request query)
 I'm developing a .NET service which checks nuget packages through the nuget api: packages.nuget.org/api/v2.
The service sometimes crush with the error: 
System.InvalidOperationException: An error occurred while loading packages from 'https://packages.nuget.org/api/v2': The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. (see in Event_Viewer_Error.png attachment).

I've read about the problem and most of the pages points to a certificate problem.
I tried to enter the https://packages.nuget.org/api/v2 address with the browser several times. The weird thing is that sometimes the pages loads and sometimes I get a privacy error. (see in Browser_Error.png attachment).
![image](https://user-images.githubusercontent.com/1857490/35655311-1d45ed14-06a6-11e8-9099-55691a7c6142.png)
![image](https://user-images.githubusercontent.com/1857490/35655313-2216b576-06a6-11e8-865b-2f1f176764ef.png)

**Comment by skofman1** [comment]
please reopen if this is still an issue.
