### ISSUE TITLE
Add telemetry which would illustrate spikes in push, unlist, relist

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5378]
We have had a variety of incidents in prod where one or a few package authors execute a massive volume of queries resulting in a big lag in V3 -- due to slow China blob storage queries. (this may be mitigated by APIM)

Additionally, other parts of our system (such as the asynchronous validation pipeline) can be sensitive to big spikes in package pushes.

I think we need a dashboard in Geneva which has the following data points:

1. packages pushed (custom metric from gallery?)
1. packages moving to available state (custom metric from orchestrator)
1. unlisted packages (custom metric from gallery?)
1. relisted packages (custom metric from gallery?)
1. reflow (custom metric from gallery?) -- not strictly necessary but we have in the past done a lot of reflows at once

Items 2 - 4 all cause catalog leaves to be produced and therefore have the potential for causing index lags.

This would be a good place to start when diagnosing cursor/index lags or slow validations.

**Comment by joelverhagen** [comment]
It looks like we already have the `PackagePush` custom event in the gallery. Unfortunately I don't think custom events show up in AI -> geneva continuous export...

**Comment by loic-sharma** [comment]
We should consider adding distributed tracing to our services (like [this](http://opentracing.io/) with [this](https://zipkin.io/)). Today, we rely on logs to determine the breakdown of performance of actions like package pushes. This won't scale as we continue adding more services and validations.
