### ISSUE TITLE
Add request throttling to nuget.org service APIs

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#5394]
The NuGet.org service API needs some configurable and enforceable upper limits on acceptable API usage. 

Initial planned throttling limits are based on the maximum load we've seen on these endpoints to date.

# V1 OData API

Throttling Type: **based on IP**

Api | Throttling Values | Main use case
-- | -- | --
**GET** `/api/v1/Packages` | 1000 / minute | Query NuGet package metadata via v1 OData `Packages` collection
**GET** `/api/v1/Packages/$count` | 100 / minute | Query NuGet package count via v1 OData `Packages` collection
**GET** `/api/v1/Search()?searchTerm=&targetFramework=&includePrerelease=` | 3000 / minute | Search for NuGet packages via v1 Search endpoint

# V2 OData API

Throttling Type: **based on IP**

Api | Throttling Values | Main use case
-- | -- | --
**GET** `/api/v2/Packages` | 20000 / minute | Query NuGet package metadata via v2 OData `Packages` collection
**GET** `/api/v2/Packages/$count` | 100 / minute | Query NuGet package count via v2 OData `Packages` collection
**GET** `/api/v2/Search()?searchTerm=&targetFramework=&includePrerelease=` | 3000 / minute | Search for NuGet packages via v2 Search endpoint
**PUT** `/api/v2/package` | 100 / minute | Upload a new NuGet package (version) via v2 push endpoint
**DELETE** `/api/v2/package/{id}/{version}` | 100 / minute | Unlist a NuGet package (version) via v2 endpoint

**Comment by anangaur** [comment]
@xavierdecoster , Can you also add the following details:

1. Error code and message o the author submitting packages more than the threshold?
2. Add a documentation plan - IMO this should go into a page in the API section as "Throttling limits"
3. Add some text to recommend on using V3 APIs.
