### ISSUE TITLE
NuGet V3 API service index moving to 3.0.0!

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5403]
For over two years, the NuGet V3 API’s service index has had the schema version of **3.0.0-beta.1**. During that period, there were no breaking changes made to the service index schema. Because of this, we will be changing the schema version declared in the document to be **3.0.0**. The NuGet team has verified that the official NuGet client and client APIs (e.g. [NuGet.Protocol](https://www.nuget.org/packages/NuGet.Protocol) package) properly handle this version change. To test your client implementation against the new version string, you can try NuGet’s staging environment service index: https://apiint.nugettest.org/v3/index.json.

The schema of the service index is defined here in our API documentation:
https://docs.microsoft.com/en-us/nuget/api/service-index

As mentioned in the document, non-breaking changes to the schema can be introduced and will be signaled by a minor version change in the existing document (no change of URL). For example, the version change could change to 3.1.0. These changes of course will be announced through this Announcements repository in advance.

Any future breaking changes will not be made to the existing V3 service index. They would be introduced in a different service index URL.

Third-party server implementations are encouraged to update their service indexes to move from **3.0.0-beta.1** to **3.0.0**.

As always, the URL for nuget.org’s production V3 service index is here:
https://api.nuget.org/v3/index.json

**Comment by joelverhagen** [comment]
Adding folks from the ecosystem for visibility:

* Paket @forki @isaacabraham 
* MyGet @maartenba
* Octopus Deploy @PaulStovell
* ProGet @apapadimoulis
* NuGet Package Explorer @304NotModified
* Chocolatey (?) @ferventcoder 
* JetBrains TeamCity @ekoshkin
* AppVeyor @FeodorFitsner

**Comment by maartenba** [comment]
Is there a date this will happen? We can align the change on our end.

**Comment by joelverhagen** [comment]
@maartenba, we are planning on deploying this change on February 19, 2018, unless some red flags come up from the community (in this thread or elsewhere).

**Comment by maartenba** [comment]
Splendid, thanks!

**Comment by joelverhagen** [comment]
@maartenba , @loic-sharma just mentioned to me that February 19 is a holiday. Let's do it the next day, February 20 (a Tuesday).

**Comment by maartenba** [comment]
Sounds good!

**Comment by joelverhagen** [comment]
Due to how noisy this week has been for our operations, I would like to post-pone this deployment for next Monday (February 26, 2018).

/cc @maartenba

**Comment by maartenba** [comment]
Too late :-D We went live with this Monday, so far all good.

**Comment by joelverhagen** [comment]
Sorry about that, we've had a noisy week. This is a low priority change in the grand scheme of things so other things pushed it out of the way. 

... thanks for being our canary? 🥇 😄

**Comment by maartenba** [comment]
Tweet!

**Comment by joelverhagen** [comment]
This is now deployed to PROD.
