### ISSUE TITLE
Outgoing URLs are wrong when running NuGet.Server behind reverse proxy

### ISSUE THREAD

**Issue by apeneve** [NuGet/NuGetGallery#5418]
We are running NuGet.Server on a local server on HTTP, port 81. The public address is HTTPS, and the traffic is routed in to the local address. Problem is all outgoing URLs  are generated with HTTP, port 81, not HTTPS 443.
I looked into enabling the aspnet:UseHostHeaderForRequestUrl app settings key by setting it to true, but it does not affect protocol or port.

I also tried to pass these headers along from the Apache reverse proxy we are using, to no effect:
X-Forwarded-Proto: https
X-Forwarded-Port: 443
X-Forwarded-For: [client IP]
X-Forwarded-Host: [our public host name]
X-Forwarded-Server: [our public host name]

Is it possible to configure NuGet.Server to work behind a proxy or load balancer like this, or do I have to look into rewriting the response?

**Comment by apeneve** [comment]
Solved this by adding an outbound URL rewrite rule in IIS that replaces all local URLs with external ones. A little messy, but it seems to do the trick.

**Comment by AgrawalAshishS** [comment]
@apeneve can you please share re-write rules you have applied? I have added following

**Comment by apeneve** [comment]
@AgrawalAshishS I added a much simpler rule:
```
    <rewrite xdt:Transform="Insert">
      <outboundRules>
        <rule name="All port 81 instances" patternSyntax="ExactMatch">
          <match pattern="http://local.host:81" />
          <action type="Rewrite" value="https://public.host" />
        </rule>
      </outboundRules>
    </rewrite>
```

No need to mess around with specific tags and such.

**Comment by AgrawalAshishS** [comment]
For some reason it breaks /api/v2/Packages feed and other related filters.
I had this resolved by setting sub_filter in nginx config.

**Comment by antibarbie** [comment]
So basically it was 5 years ago, and this is still NOT FIXED, no way to properly serve nugets behind a reverse proxy ?

I tried to add this code on application Owin startup, with no success (even forcing scheme as https is ignored) :

`````
            app.Use((context, next) =>
            {
                if (context.Request.Headers["X-Forwarded-Proto"] == "https")
                {
                    context.Request.Scheme = "https";
                }
                return next();
            });
``````
and if you reverse proxy is something like haproxy, you juste cannot use "sub_filter"...

**Comment by china-live** [comment]
> <rewrite>
>       <outboundRules>
>         <rule name="All port 81 instances" patternSyntax="ExactMatch">
>           <match pattern="http://local.host:81" />
>           <action type="Rewrite" value="https://public.host" />
>         </rule>
>       </outboundRules>
>     </rewrite>

This method is effective, thank you

**Comment by china-live** [comment]
2024/09/19 Mark，Fortunately, the following methods are effective。Thank you @apeneve 
` <rewrite>
      <outboundRules>
        <rule name="All port 81 instances" patternSyntax="ExactMatch">
          <match pattern="http://local.host:81" />
          <action type="Rewrite" value="https://public.host" />
        </rule>
      </outboundRules>
    </rewrite>`

**Comment by TWhidden** [comment]
This was a helpful thread. 

To further assist - you must have the IIS rewrite module installed.  Without it, the above configuration will give you a 500 error. 

[https://www.iis.net/downloads/microsoft/url-rewrite](https://www.iis.net/downloads/microsoft/url-rewrite)

Thanks for the hint on the rewrite. Annoying, but this is an easy work around.
