### ISSUE TITLE
V2 API next link doesn't contain SemVerLevel

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#5433]
While analyzing https://github.com/NuGet/NuGetGallery/issues/5431 we also noticed that the `next` link from a request doesn't contain the required parameters which could lead to problems in pagination.

Example:
Request `https://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='NLog'`
Response:
[request_semver.xml.txt](https://github.com/NuGet/NuGetGallery/files/1714929/request_semver.xml.txt)
`<link rel="next" href="https://www.nuget.org/api/v2/FindPackagesById()?id=%27NLog%27&amp;$skip=100" />` <- Missing `semVerLevel=2.0.0`

Response Headers:
[request_semver.txt](https://github.com/NuGet/NuGetGallery/files/1714930/request_semver.txt)

**Comment by skofman1** [comment]
Thanks for reporting! We will fix this.
