### ISSUE TITLE
[Question] How to get all tags for package using NuGet v3 API

### ISSUE THREAD

**Issue by zhili1208** [NuGet/NuGetGallery#5438]
@jamesqo
moved from https://github.com/NuGet/Home/issues/6554

It looks like sometimes the tags displayed on the nuget.org website are not reflected in the metadata returned by the catalog API. Example: [this](https://www.nuget.org/packages/adam.jsgenerator/) has a `javascript` tag, but there is no `tags` attribute here: https://api.nuget.org/v3/catalog0/data/2015.02.01.06.22.45/adam.jsgenerator.1.1.0.json How can I reliably get the tags associated with a package?

**Comment by joelverhagen** [comment]
@jamesqo, this seems to have been an old bug. The package itself does not have any tags so in this base the gallery was incorrect. I have reflowed the package so the gallery is now correct.

In general, these two sets of data should match. I have filed https://github.com/NuGet/NuGetGallery/issues/5439 to investigate how our monitoring did not catch this.

Concerning how to reliable get tags, I would recommend querying the registration (package metadata) resource for a specific package ID and version. This is easy if you know the package ID (and optionally version) in advance. Documentation for the package metadata resource is here:
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource

If you are already reading the catalog, this is always a good way to get package tags... but the catalog is not indexed by package ID so you have to process the whole thing to find data about a specific package.

**Comment by joelverhagen** [comment]
@jamesqo, please feel free to re-open this issue if you have follow-up questions.
