### ISSUE TITLE
[BugBash] Email missing from message on account link

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5441]
see scenario 1, per @joelverhagen 

The email on the link page is empty

**Comment by shishirx34** [comment]
Needs investigation.

**Comment by scottbommarito** [comment]
Not high pri because it doesn't not block the flow because the email address is still persisted in the form.

**Comment by scottbommarito** [comment]
Note: this only appears after submitting the form with incorrect data--the first load is successful.
