### ISSUE TITLE
[BugBash] Can reset password and replace AAD with MSA

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5445]
Scenario 7, per @anangaur 

1. linked my account to AAD
2. Now I cannot link it to MSA which...
...
5. Replaces my AAD with MSA

**Comment by scottbommarito** [comment]
AFAIK this is intentional unless you are 
a) in an organization
b) an admin

**Comment by anangaur** [comment]
I am fine with condition a) but not b). 

I think we always wanted to do this but due to lack of time, we chose to just block changing the auth from AAD to MSA. This is the behavior from the "Account settings" page. Should be the same for this user flow too.
