### ISSUE TITLE
[BugBash] Link/transform prompt UI issues

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5447]
- Scenario 8, per @anangaur (Issue 2)

  The title and warning text have to be inverted as per UX feedback...

- Scenario 8, per @anangaur (Issue 3)

  The dialog seems very narrow...

- Scenario 8, per @skofman1 

  There's too much space around "Sign in with Microsoft" button

**Comment by anangaur** [comment]
The warning icon should also move from title to warning section as per UX feedback.
