### ISSUE TITLE
[BugBash] Incorrect sign in state when registering after MSA sign in

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5448]
Scenario 1, per @loic-sharma 

Went to "Sign in" page, selected...

**Comment by shishirx34** [comment]
We, @scottbommarito and I, tried repro'ing this issue, but couldn't.

**Comment by scottbommarito** [comment]
Were not able to repro this--will ask @loic-sharma offline.

**Comment by scottbommarito** [comment]
Was not able to repro with @loic-sharma's help--keeping this issue open in case it ever happens again.

**Comment by shishirx34** [comment]
I think we should close this issue if there is a no repro, and reopen this issue when, if we ever see this issue.
