### ISSUE TITLE
[BugBash] Password reset sent page title misleading

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5449]
Scenario 1, per @loic-sharma 

Also, if I go to "Account Settings">"Password Login">"Enable Password Login", the title of the page...

![image](https://user-images.githubusercontent.com/15364949/40146025-dfc160e8-5918-11e8-9609-1979273fa1b0.png)

**Comment by shishirx34** [comment]
I think it is a valid issue, however, not related to AAD changes. Will add this to the backlog.

**Comment by skofman1** [comment]
"Enable password login" section is gone. Closing.
