### ISSUE TITLE
[BugBash] Org transform confirmation return url not preserved on admin AAD sign in

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5453]
Scenario 10, per @chenriksson

note, returnUrl w/ confirmation token is not preserved...

**Comment by scottbommarito** [comment]
For some reason, the return url (which is originally a relative url) is transformed into an absolute url, which causes the `SafeRedirectResult` to reject and redirect to the homepage. Looking into why this is occurring now.
