### ISSUE TITLE
[BugBash] Could add admin without AAD credential as collaborator

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5457]
Scenario 12, per @skofman1 (issue 1)

I was able to add a collaborator who is an admin that...

**Comment by scottbommarito** [comment]
Wasn't able to reproduce. Furthermore, I noticed all of the members in @skofman1's org did happen to have the AAD credential. Will ask @skofman1 for help repro'ing and then will close if not reproduceable.
