### ISSUE TITLE
[BugBash] Change email save changes page URL

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5459]
Scenario 12, per @skofman1 (issue 3)

Scenario1:
1. Go to page...
2. Edit e-mail to a token value...

Also Scenario 12, per @skofman1 (issue 4)

Scenario 2:
1. Got o page...
2. Add a member as collaborator...

**Comment by scottbommarito** [comment]
Was not able to reproduce, even with @skofman1's help. Whatever caused this seems to be ok now.
