### ISSUE TITLE
[BugBash] Manage Packages page slow for account with 60K packages

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5461]
Scenario 15, per @skofman1 

I got an account with 60,000 packages. "Manage Packages" page doesn't load.

**Comment by chenriksson** [comment]
Call to User.IsInRole is 11.9% incl, which is excessive for checking if the current user is an admin. I believe this is when performing permissions checks.

![image](https://user-images.githubusercontent.com/15364949/36167913-50315960-10ac-11e8-9e20-3eb676b8ea1c.png)

**Comment by chenriksson** [comment]
Microsoft (PROD) has almost as many package versions as NuGetStagingTest (DEV) has... so I think we should keep this in sprint. Roughly 42K versus 59K versions.

**Comment by chenriksson** [comment]
Plans for optimizations:
1. Improve server query by ordering in DB and only selecting latest versions. For packages that don't have IsLatest set (concurrency issue), we will do minimal work which could be:
    - exclude entirely
    - display registration details only (not latest version)
2. Add paging if serialization and client side performance is still bad. If we do this, we should add a search option for filtering by packageId.

//cc @joelverhagen  @ryuyu

**Comment by chenriksson** [comment]
We should still consider paging for scenarios with many registrations (i.e., test accounts), but that's already tracked by #5059... marking this code complete.

**Comment by skofman1** [comment]
@chenriksson , will your fix help with profile page? For example: https://www.nuget.org/profiles/awscpp
The page loads very slowly despite the number of packages being low and having paging.

**Comment by chenriksson** [comment]
@skofman1 No -- `PackagesService.FindPackagesByAnyMatchingOwner` was only used by "Manage Packages" and the Delete Account workflows. We could do the same w/ profiles if we're ok with the caveat there... being that we may not pull the latest if there's no IsLatest set due to the concurrency issue.

**Comment by skofman1** [comment]
Created a separate issue to track: https://github.com/NuGet/NuGetGallery/issues/5593
If this is a simple fix, we should definitely go for it.

**Comment by chenriksson** [comment]
@anangaur Did 'Manage Packages' performance improve for you after this latest deployment? If so, the priority for adding paging should be lower.

Microsoft has 3923 registrations and 43217 versions, so it should have helped a fair amount.
