### ISSUE TITLE
[BugBash] Manage Organizations UI issues

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5464]
Scenario 22, per @anangaur 

The above 3 issues...

**Comment by skofman1** [comment]
@chenriksson , can you please add more details here?

**Comment by chenriksson** [comment]
From the OneNote:

![image](https://user-images.githubusercontent.com/15364949/37529406-4995704a-28f4-11e8-874c-7b9a14fcf4c7.png)

Looks like @anangaur wanted to put the icon next to the Org name instead of a different column, and remove the Org link. Not sure if this is covered by the UI work that was discussed.

We should also look at consistency across site for this change... Manage Packages has the icon in a separate column too:
![image](https://user-images.githubusercontent.com/15364949/37529612-dad4b926-28f4-11e8-83bc-6089c063a726.png)

**Comment by scottbommarito** [comment]
Another note--due to how we use bootstrap in these tables, making major changes to the column spacing is not entirely possible. We could use CSS directly in the tables to make the spacing changes but that's much more complex than bootstrap.
