### ISSUE TITLE
Logon/Register functional test failures

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5465]
Are the logon and register tests failing due to the latest AAD work?

From build 22852:
>2018-02-12T10:24:10.7766382Z Failed                >NuGetGallery.FunctionalTests.WebUITests.AccountManagement.LogonTest
>2018-02-12T10:24:37.5390844Z Failed                >NuGetGallery.FunctionalTests.WebUITests.AccountManagement.RegisterNewUserTest
>2018-02-12T10:24:42.9358873Z Passed                >NuGetGallery.FunctionalTests.WebUITests.BasicPages.BrandingValidationTest
>2018-02-12T10:24:44.5677967Z Passed                >NuGetGallery.FunctionalTests.WebUITests.BasicPages.HomePageValidationTest
>2018-02-12T10:24:48.1556182Z Error                 >NuGetGallery.FunctionalTests.WebUITests.UploadAndDownload.UploadPackageFromUI
>2018-02-12T10:24:48.3431232Z 2/5 test(s) Passed, 2 Failed, 1 Error

**Comment by shishirx34** [comment]
Tests are passing.
