### ISSUE TITLE
catalog2dnx no-op can miss index.json update

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5473]
The no-op in catalog2dnx has the following rule.

If the source .nupkg and destination .nupkg have the same `Content-MD5` header, skip the catalog leaf.

Also, if the no-op does not pass and catalog2dnx determines the package should be added, it performs the following steps in sequence:

1. Upload .nuspec
1. Upload .nupkg
1. Update index.json

Suppose the update of the index.json fails. The next time catalog2dnx attempts to add the package, the no-op will occur and the index.json will never be updated.

**Comment by skofman1** [comment]
@joelverhagen , what's the priority on this? As far as I remember, the client doesn't use the flat container index.json

**Comment by joelverhagen** [comment]
> As far as I remember, the client doesn't use the flat container index.json

It does!!!
https://github.com/NuGet/NuGet.Client/blob/8b627e1ed95fd814a18d950d7af06b172224e52d/src/NuGet.Core/NuGet.Protocol/RemoteRepositories/HttpFileSystemBasedFindPackageByIdResource.cs#L347

Priority is high-ish given we have no monitoring on this problem.

**Comment by skofman1** [comment]
Seems like a reasonable fix will be to update always try to update the index.json even if the nupkg no-ops.

**Comment by joelverhagen** [comment]
> Seems like a reasonable fix will be to update always try to update the index.json even if the nupkg no-ops.

To do the index.json update you have to download the index.json. You can skip the write if the version is already there. But yeah, pretty much.

**Comment by skofman1** [comment]
We should be able to see in the logs if this already happened.

**Comment by joelverhagen** [comment]
After fixing this we need to reflow:

- [ ] paulovich.caju 0.0.2
