### ISSUE TITLE
Transform Organization flow should link to the Email Confirmation flow if the user to transform has not yet confirmed their account

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5477]
Currently, the transform to organization flow rejects accounts that have not yet been confirmed. It does not, however, link to the email confirmation page that allows you to resend the confirmation email in case it was never received. As a result, because the account settings page is blocked for users that have a discontinued login, unconfirmed users may find themselves stuck without the ability to transform into an organization and without the ability to confirm their email.

We should link to the email confirmation page in the transform to organization flow in case the user needs to resend their confirmation email.

**Comment by skofman1** [comment]
@scottbommarito , can we not block the account (or show transform) for unconfirmed users?

**Comment by scottbommarito** [comment]
We could potentially make transform allow unconfirmed accounts--it probably already would work fine but we'd need to confirm it does. This scenario is really uncommon as it is, however, so I don't think we should put too much effort into it.
