### ISSUE TITLE
504 Gateway Timeout in Los Angeles

### ISSUE THREAD

**Issue by ctaggart** [NuGet/NuGetGallery#5481]
This leads to a 504 Gateway Timeout error in the Los Angeles area.
https://api.nuget.org/v3-flatcontainer/fsharp.core/index.json

The status page at https://status.nuget.org/
has a link to the Verizon CDN status:
https://status.verizondigitalmedia.com/#network-status

![image](https://user-images.githubusercontent.com/80104/36233652-06f0801e-11b5-11e8-8d8b-9da789a8c28e.png)

Is there any way to workaround CDN outages like this?

**Comment by skofman1** [comment]
@ctaggart , unfortunately no good workaround. Perhaps a proxy to connect you to a different CDN POP. 
Closing the issue since the incident was resolved.
