### ISSUE TITLE
About page is missing some former members of the NuGet team

### ISSUE THREAD

**Issue by ferventcoder** [NuGet/NuGetGallery#5495]
Non-softie former member of NuGet team from 2010-2011ish. It would be nice to see myself in the right section of https://www.nuget.org/policies/About. @drusellers @bsimser are two others I know of who came on from the Nu team originally.

cc @maartenba @xavierdecoster

**Comment by maartenba** [comment]
Not sure why I was cc'ed here :-) /cc @anangaur

**Comment by ferventcoder** [comment]
Verification? :-)

**Comment by bsimser** [comment]
Verified. I am me.

**Comment by drusellers** [comment]
I can verify that I am me. ;p

**Comment by ferventcoder** [comment]
Yep, wiseguys. This is the right crew ;)

**Comment by maartenba** [comment]
Verified :-)

**Comment by xavierdecoster** [comment]
![giphy](https://user-images.githubusercontent.com/880728/36440048-a3002e54-1666-11e8-89f2-8a3c462ebe29.gif)

**Comment by skofman1** [comment]
@scottbommarito , don't forget @PatoBeltran !!!

**Comment by scottbommarito** [comment]
The missing former members should now appear on the site!
