### ISSUE TITLE
0 downloads reported for a package (latest version)

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5498]
From twitter:
https://twitter.com/bradwilson/status/964540973526147072
![image](https://user-images.githubusercontent.com/14800916/36323499-f556a3e0-1305-11e8-98bd-8576dc5c3182.png)

**Comment by skofman1** [comment]
Probably a bug in Statistics version parsing code.

**Comment by scottbommarito** [comment]
This is the first `xunit` package with a version containing a `.` in the prerelease part--@skofman1 is probably right.

**Comment by anangaur** [comment]
But the version in question is a stable version.

**Comment by anangaur** [comment]
Never mind. Got it :)

**Comment by scottbommarito** [comment]
@anangaur [2.3.1](https://www.nuget.org/packages/xunit/2.3.1) has over 800k downloads, I assume he's referring to [2.4.0-beta.1.build3958](https://www.nuget.org/packages/xunit/2.4.0-beta.1.build3958) which has 0 and was uploaded 5 days ago.

**Comment by scottbommarito** [comment]
@skofman1 and I looked into this. It is being parsed incorrectly as expected. We are working on a fix right now.

The current download count can be viewed at https://www.nuget.org/stats/packages/xunit.2?groupby=Version

**Comment by anangaur** [comment]
Another issue with package name at https://www.nuget.org/stats/packages/xunit.2?groupby=Version

Why is the name of the package xunit2? The link is also broken:
![image](https://user-images.githubusercontent.com/14800916/36326422-d8c485f8-130f-11e8-9df1-0a6f0a984be5.png)

**Comment by scottbommarito** [comment]
@anangaur To clarify, when we receive the download logs from our CDN, it can be sometimes ambiguous what package was downloaded. This was a case in which we determined what package was downloaded incorrectly. We thought the package was `xunit.2` version `4.0.0-beta.1.build3958` and not `xunit` version `2.4.0-beta.1.build3958`. 

`xunit.2` version `4.0.0-beta.1.build3958` doesn't actually exist--but the stats pipeline isn't aware of this and the gallery just shows the stats data on this page.

**Comment by anangaur** [comment]
How can we fix this? Can you file another issue for this?

**Comment by skofman1** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/16807822/36811247-f7f40d2e-1c81-11e8-88ad-77511ce00309.png)
