### ISSUE TITLE
Organizations: Allow collaborators to leave an organization

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5501]
Currently we only allow org admins to manage members. We should allow collaborators to delete their own membership / leave an organization.

/cc @anangaur @scottbommarito @shishirx34

**Comment by anangaur** [comment]
Wasn't aware of this :) Should have tested this out in the bugbash. The desired flow is this:

1. Admins can add new members - newer admins or collaborators
2. For Admins, there would be a confirmation before the Admin gets added.
3. The newly added members (Admins/Collaborators) would get a mail notifying the addition to an organization. 
4. [P2] This mail should contain a link to "leave the organization" 
5. Members (Admins/Collaborators) can leave any organization they do not want to be part of. 
6. The option to leave an organization, edit/view should be there on the list organizations page. I get the icons.
