### ISSUE TITLE
Should I put .mdb or .pdb files up on NuGet?

### ISSUE THREAD

**Issue by define-private-public** [NuGet/NuGetGallery#5504]
I'm a little confused by this.  At the moment, I've got two instances of MonoDevelop configured.  One where it's generating `.pdb` files, and the other one where it's making `.mdb` files.  When packing & submitting my library, is there one that I should be giving preference to?  IIRC, they are different.

I currently develop on a Linux system, but my library is compatible with Windows & OS X.  Here's the .nuspec file too:
https://gitlab.com/define-private-public/SharpCamera/blob/develop/SharpCamera/SharpCamera.nuspec

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #6585](https://github.com/NuGet/Home/issues/6585) via [**ZenHub**](https://www.zenhub.com/)
