### ISSUE TITLE
How to retrieve total download count for a package

### ISSUE THREAD

**Issue by jamesqo** [NuGet/NuGetGallery#5506]
I would like to retrieve the total number of times a package has been downloaded for my app. I looked through the gallery source code to try to ascertain how to do this, and it comes down to [this method](https://github.com/NuGet/NuGetGallery/blob/e5982240f7f165effdab864064f73275798f81a8/src/NuGetGallery/Services/CloudDownloadCountService.cs#L58) which looks like it calls into some private CDN service with a connection string I'm unable to see. Is it possible to get this metric other than by scraping the webpage?

**Comment by skofman1** [comment]
@jamesqo , you can get the total downloads count using our APIs. 
You can query our search service for the package, and the response will contain the downloads count: 
https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource

**Comment by jamesqo** [comment]
@skofman1 Thanks for the solution. It does seem a bit flaky though, can I be sure the package will always show up if I query for its ID? Will it always be the first result or is there a chance of it being behind others?

**Comment by skofman1** [comment]
You can use the search syntax to get the specific package by id:
https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax
