### ISSUE TITLE
Packages stuck in "validating" status for several hours

### ISSUE THREAD

**Issue by tmenier** [NuGet/NuGetGallery#5530]
On 2/19 I uploaded a package. 3+ hours later it was still in "validating" status. I contacted support, the package was listed shortly thereafter, and the next day I got a reply confirming there had been an incident of some sort and it was resolved. Today I uploaded a package and am seeing exactly the same behavior. 2+ hours on and it's still in "validating" status.

The package in question is Flurl.Http.

Is there another incident or is this the new normal?

**Comment by skofman1** [comment]
@tmenier , sorry for the slow response, missed this issue previously. We had several incidents around the validation pipeline in the last month. More details in the blog here: https://blog.nuget.org/20180201/NuGet-package-publishing-workflow-behind-the-scenes.html

I see that Flurl.Http is available, so closing this issue.
