### ISSUE TITLE
Allow releases to be tagged as security-related

### ISSUE THREAD

**Issue by landaire** [NuGet/NuGetGallery#5539]
## Summary

When uploading a new release to NuGet.org, the package author should be able to choose to indicate whether the new version contains security fixes and which versions are affected.

## Details

Tracking vulnerable NuGet packages is currently not an easy task. A lot of projects do not issue CVEs and if they do, they do not correlate the CVEs to their NuGet package. NuGet should support at a gallery layer indicating whether a package version should be avoided due to known vulnerabilities.

This proposal would have 3 main changes:

1. Add new UI elements on the package upload page to indicate a security release and affected versions
2. Change the "Version History" page to indicate previous versions that may contain vulnerabilities
3. Add additional info to the API response to include a flag on versions which contain vulnerabilities and which package version they should upgrade to

## Implementation

Here are some examples of UI changes that may occur:

![2018-02-23 11_29_36-nuget gallery _ upload package](https://user-images.githubusercontent.com/1313522/36613426-560e2ce8-188e-11e8-860a-5c67f88eb099.png)

![2018-02-23 11_35_11-nuget gallery _ ca04cb92478e4bb2a064705f9797b92b 1 0 15](https://user-images.githubusercontent.com/1313522/36613435-5adfa2ba-188e-11e8-85c1-2bb34056bf06.png)

**Comment by skofman1** [comment]
@anangaur

**Comment by anangaur** [comment]
I think this is tied to package deprecation feature where authors can deprecate certain packages  and provide reasons and recommended package+versions: https://github.com/NuGet/Home/issues/2867

**Comment by anangaur** [comment]
Closing this one. Pls use https://github.com/NuGet/Home/issues/2867 for any discussion related to deprecation, flagging vulnerable packages etc.
