### ISSUE TITLE
NuGet Gallery should support LDAP for on-premise deployments

### ISSUE THREAD

**Issue by matthewskelton** [NuGet/NuGetGallery#554]
For those who use NuGet Gallery on-premise (rather than just nuget.org), it'd be a big win for the Gallery to support LDAP for authentication rather than (or in addition to) the NuGet Gallery database authentication store.

**Comment by digitalray** [comment]
+ for LDAP/Active Directory ntlm authentication...Hosting a private gallery, chances are you’re on an Active Directory and don't want to have users login 2 times to get to NuGet Gallery. You want to add them in a AD group which will give them access.
