### ISSUE TITLE
[Log-in flow] Gallery returns 400 on double login

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5558]
Repro steps:
1. login with user id and password
2. Click "back" until you get to login page again
3. enter used id and password again
4. Result: 400 page

**Comment by shishirx34** [comment]
This happens due to a mismatch during the validation of `ValidateAntiforgeryToken` attribute on the `POST` to the `SignIn` page. 

Exception: `The provided anti-forgery token was meant for a different claims-based user than the current user.`

This is working as expected.
