### ISSUE TITLE
Alternative DNS need APIM

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5562]
packages.nuget.org -> PROD
staging.nuget.org -> INT

/cc @xavierdecoster

**Comment by joelverhagen** [comment]
There may be others. Worth asking DNS folks for enumeration.

**Comment by skofman1** [comment]
@joelverhagen , you can get the list of DNS here: https://prod.msftdomains.com/Dns/Records

The redirection now is this:
packages.nuget.org goes to nuget.org A record. For more details see this issue: https://github.com/NuGet/Engineering/issues/1246

Regarding staging.nuget.org - the MSA login is currently broken for it. @shishirx34 , is this something we can fix? If it's not, we should stop supporting this URL, and document it's move to int.nugettest.org

**Comment by scottbommarito** [comment]
@skofman1 we can easily set up MSA to work with staging.nuget.org as well, their portal allows us to add the link

**Comment by shishirx34** [comment]
no, we can't support it, we should migrate to int.nugettest.org, single url. It will be a lot more work to support multiple urls for MSA with APIM involved.

**Comment by skofman1** [comment]
Created an issue to track this: https://github.com/NuGet/NuGetGallery/issues/5627

Closing this issue since work items are tracked by other issues.

**Comment by skofman1** [comment]
APIM can be configured with wildcard domain: https://docs.microsoft.com/en-us/azure/api-management/configure-custom-domain
We should check if we can map feed.nuget.org, packages.nuget.org, preview.nuget.org to APIM instead of the A record.

**Comment by skofman1** [comment]
@cristinamanum , what is the work left here?

**Comment by skofman1** [comment]
No work left here.
