### ISSUE TITLE
[NuGet.Server.V2] NuGetPrivateODataController: Push/Delete not work

### ISSUE THREAD

**Issue by DoCode** [NuGet/NuGetGallery#5587]
Does anyone try to run the sample in the `NuGet.Server.V2` repository?

When I enabled the authentication for uploading and deleting packages here:  
https://github.com/NuGet/NuGet.Server/blob/master/samples/NuGet.Server.V2.Samples.OwinHost/Controllers/NuGetPrivateODataController.cs#L18-L19

The HTTP stack return always HTTP 406 here:  
https://github.com/NuGet/NuGet.Server/blob/master/samples/NuGet.Server.V2.Samples.OwinHost/BasicAuthentication.cs#L39

And then the user will never be prompted for username and password.

I don't see the trees in the forest...
Please, can anyone help me!?

**Comment by skofman1** [comment]
@DoCode , apologies for the slow response. 
Have you been able to resolve the issue?

**Comment by DoCode** [comment]
@skofman1 hehe. One month later... 😉
But yes. I resolved this issue. But currently I can not remember what the solution was. 😅 It's 2:45am in Germany and I should sleep now... I look tomorrow and come back here, ok?

**Comment by skofman1** [comment]
@DoCode , apologies again 😃 
It will be great if you share your solution for everyone who will get into the same situation in the future!

**Comment by scherenhaenden** [comment]
Hi Ppl! 

im facing the same problem here.. at least i think. Did you solved or know what to do?

**Comment by DoCode** [comment]
Hi @scherenhaenden, yes I fixed this, but currently, I have NO time to look what the issue in the sample was...
I am completely overcommitted...

**Comment by dcbazscott** [comment]
I had the 406 error as well, but I wasn't working with security at the time. After a lot of research I discovered that having a # in any file within your package will cause the zip operation to fail and result in a 406 response. I had font files with # in their name. I had to remove them from my package but then it worked. I hope this helps.

**Comment by vmik** [comment]
Faced with the same issue. Push/delete operation returns 406 in case you're not authorized.
