### ISSUE TITLE
Setting the sort order of the package list should change the url

### ISSUE THREAD

**Issue by zippy1981** [NuGet/NuGetGallery#559]
If this wasn't an MVC app I'd say make the form get not post. However, perhaps it should be something like

http://nuget.org/packages/by-date
http://nuget.org/packages/by-name
http://nuget.org/packages/by-popularity\

As a work around, you can manually send get variables to the url and it does sort. e.g http://nuget.org/packages?q=&sortOrder=package-download-count

**Comment by johnataylor** [comment]
Our new API v3 takes a different approach.
