### ISSUE TITLE
NuGet.Server Package Source filtered by tags

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/NuGetGallery#5591]
@Glober777 commented on [Fri Mar 09 2018](https://github.com/NuGet/Home/issues/6656)

Hi,

I'm hosting NuGet.Server in my network for managing PowerShell script\module based packages. All works relatively well, with the exception of the fact that both Find-Module and Find-Script return the same set of packages. Looking at how things are configured by default for PowerShell Gallery, I see that it references a slightly different source URL that returns a list of packages filtered by package tag (Scripts are tagged with 'PSScript' tag):
```posh
PS > Get-PSRepository PSGallery | fl *


Name                      : PSGallery
SourceLocation            : https://www.powershellgallery.com/api/v2/
Trusted                   : False
Registered                : True
InstallationPolicy        : Untrusted
PackageManagementProvider : NuGet
PublishLocation           : https://www.powershellgallery.com/api/v2/package/
ScriptSourceLocation      : https://www.powershellgallery.com/api/v2/items/psscript/
ScriptPublishLocation     : https://www.powershellgallery.com/api/v2/package/
ProviderOptions           : {}
```

Is there a way to build such a URL that would work for NuGet.Server?

Thanks!

---

@PatoBeltran commented on [Fri Mar 09 2018](https://github.com/NuGet/Home/issues/6656#issuecomment-371967929)

This seem to be a issue more appropriate for the Nuget.Server team. I will redirect it to them and close this.

**Comment by skofman1** [comment]
Hi @Glober777, NuGet.Server doesn't support filtering search results by tag, however, it's search includes tags, so the results might be a little noisy but will include the packages you are looking for. The query format will be: 
http://localhost:54534/nuget/Search()?searchTerm='PSScript'
