### ISSUE TITLE
Profile page is slow for accounts with many packages

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5593]
Examples: 
https://www.nuget.org/profiles/microsoft
https://www.nuget.org/profiles/awscpp

Since we have paging on this page, there's no reason for such poor perf.

**Comment by chenriksson** [comment]
Verified while deployed to INT staging, against old bits in INT0. Scenario is profile page for microsoft (1165 package registrations).

Baseline: 3.99, 4.36, 4.10, 4.44 => AVG=4.22
Latest: 1.19, 1.51, 1.16, 1.14 => AVG = 1.25 (-70.38%)

**Comment by chenriksson** [comment]
Verified PROD0 vs PROD-USSC (baseline) before USSC deployment.

Scenario: profiles/microsoft (3510 reg, 41021 ver)
- Baseline: 17.12, 16.48, 18.32, 17.37 => 17.32
- Latest: 4.98, 4.31, 3.22, 2.74 => 3.81 (-78%)

Scenario: profiles/awscpp (354 reg, 40096 ver)
- Baseline: 14.71, 14.60, 15.51, 13.66 => 14.62
- Latest: 1.59, 1.24, 1.30, 1.38 => 1.38 (-91%)
