### ISSUE TITLE
update docs link

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#5604]
Update docs link on nuget.org to point to https://docs.microsoft.com/en-us/nuget/what-is-nuget

![image](https://user-images.githubusercontent.com/16904420/37376388-44057a22-26e1-11e8-8797-d37571dd56e1.png)

**Comment by loic-sharma** [comment]
Some feedback after talking to @karann-msft: the goal of this change was to make the table of content easily accessible. However, this new "home" documentation page is a wall of text that is a little much on the eyes. We should find the right balance between the two.

**Comment by karann-msft** [comment]
I agree. At present this is the best page we have that doesn't assume if you are a package author or a consumer while giving you access to a ToC. I know we have a work item to make this page less text-heavy and concise.
