### ISSUE TITLE
Consider expiring org-scoped api keys when member leaves

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5610]
Should we delete API keys scoped at the organization if the user leaves that organization?

/cc @anangaur @scottbommarito

**Comment by anangaur** [comment]
Expired or deleted - won’t it mean the same? You can can’t use these keys anymore.

**Comment by scottbommarito** [comment]
They still appear in the UI.
Removing the keys would make them disappear from the UI.

**Comment by anangaur** [comment]
Agree we should not magically remove. Expire is the best option then :)

**Comment by skofman1** [comment]
Agree with @anangaur , we never delete Api Keys in the code, only expire.

**Comment by scottbommarito** [comment]
I don't think this is necessary, or I think it should require that a certain amount of time has passed (1-7 days) before we delete the keys. The gallery is smart enough to not allow users to use API keys to perform actions that they no longer have permissions to do. If a user is accidentally removed from an organization and immediately added back, they will lose all of their keys even though there is no harm for them to keep them. We should verify that there are no UI bugs with having API keys with scopes that you no longer have permission to have but I don't think we should expire them automatically.

**Comment by scottbommarito** [comment]
Closing because no security issue.
