### ISSUE TITLE
Incident nuget v3 feed?

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#5614]
GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/index.json?semVerLevel=2.0.0

Returns 502 consistently for me at the moment
```
Content-Length →349
Content-Type →text/html
Date →Wed, 14 Mar 2018 18:06:15 GMT
Server →ECLF (frc/8F0E)
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>502 - Bad Gateway</title>
    </head>
    <body>
        <h1>502 - Bad Gateway</h1>
    </body>
</html>
```

GET https://api.nuget.org/v3-flatcontainer/fsharp.core/index.json?semVerLevel=2.0.0 works:
```
{
    "versions": [
        "2.0.0",
        "3.0.2",
        "3.1.2",
        "3.1.2.1",
        "3.1.2.5",
        "4.0.0",
        "4.0.0.1",
        "4.0.1.5",
        "4.0.1.7-alpha",
        "4.1.0",
        "4.1.0.2",
        "4.1.2",
        "4.1.12",
        "4.1.17",
        "4.1.18",
        "4.2.1",
        "4.2.2",
        "4.2.3",
        "4.3.0",
        "4.3.1",
        "4.3.2",
        "4.3.3",
        "4.3.4"
    ]
}
```

**Comment by shishirx34** [comment]
@matthid - what is the location that you are experience the 502 from? Is this on your machine or a remote machine or a VM? Is the second available endpoint also from the same location(machine)?

@scottbommarito - possible CDN issue?

**Comment by joelverhagen** [comment]
As a side note @matthid, the flat container resource does not support the `semVerLevel` query parameter. It returns all versions, no matter the SemVer version.

**Comment by matthid** [comment]
@shishirx34 This is from my home internet provider Stuttgart, Germany and from my home desktop PC.

> Is the second available endpoint also from the same location(machine)?

I don't understand the second question. If you mean if I make the requests from the same PC then the answer is yes. I do both requests via Postman (after some stuff has failed on me)

**Comment by matthid** [comment]
> As a side note @matthid, the flat container resource does not support the semVerLevel query parameter. It returns all versions, no matter the SemVer version.

Thanks, good to know. Just to be sure: It doesn't change the 502.

**Comment by scottbommarito** [comment]
Both links you posted work as expected for me. I think this is likely a connectivity issue with our CDN.

Please follow the documentation at https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible and contact support (support@nuget.org) with more information.

**Comment by matthid** [comment]
> Please follow the documentation at https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible and contact support (support@nuget.org) with more information.

Do you not have some red blinking lights somewhere? :(

**Comment by matthid** [comment]
I'm just using v2 for now and hope this sorts itself out. As this clearly is a server side issue I'm not sure what additional info I can provide.

**Comment by forki** [comment]
It's 5xx error. Please look into your logs.

**Comment by matthid** [comment]
![image](https://user-images.githubusercontent.com/1866463/37424377-91a04d9a-27c0-11e8-9e60-10f36b43022f.png)

Whatever that means. 
Now I can no longer reproduce with Postman but paket still registers a 504 result:
```
-> Request 'https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/index.json?semVerLevel=2.0.0' finished with error
-> RequestFailedException: Request to 'https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/index.json?semVerLevel=2.0.0' failed with: 504 GatewayTimeout - <?xml version="1.0" encoding="iso-8859-1"?>
   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
            "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
   <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>504 - Gateway Timeout</title>
        </head>
        <body>
                <h1>504 - Gateway Timeout</h1>
        </body>
   </html>
```

**Comment by anangaur** [comment]
@matthid @forki 
We have been seeing the intermittent issues regarding 502s and 504s while restoring packages from folks in Germany. We are working with our CDN partners towards resolving the issue. We will be posting latest updates to the [NuGet status](https://status.nuget.org) page. 
Reopening the issue till the matter is resolved.

**Comment by skofman1** [comment]
This is resolved (for a while..). Will reopen if reoccurs.
