### ISSUE TITLE
During UI upload, two DB commits happen if user provided readme

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5625]
This means the package will be Available for a short period before being set to Validating.

**Comment by loic-sharma** [comment]
Great find

**Comment by joelverhagen** [comment]
This actually means in rare cases packages could make their way into V3 before being validated 😨.

**Comment by joelverhagen** [comment]
> This actually means in rare cases packages could make their way into V3 before being validated 😨.

Actually, not true, since the package content won't be there.
