### ISSUE TITLE
Deprecate staging.nuget.org

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5627]
MSA/AAD login won't work for this environment. Use https://int.nugettest.org

**Comment by joelverhagen** [comment]
What should staging.nuget.org do? Redirect to int.nugettest.org?

**Comment by skofman1** [comment]
@anangaur , can we announce this? How long after announcement can we  move forward with the deprecation?

**Comment by shishirx34** [comment]
we should do a permanent redirect to int.nugettest.org for this url. The AAD reply URL can't be configured with multiple domains(its configured for nugettest.org so nuget.org is not an option)

**Comment by joelverhagen** [comment]
Yup. This can be easily be done in the `web.config`. In fact we already have examples in there for other domain names.

**Comment by shishirx34** [comment]
@anangaur yes.

**Comment by skofman1** [comment]
After further review, it became clear that redirecting staging.nuget.org to int.nugettest,org will involve uploading prod ssl cert to int, which will be insecure. We decided to deprecate the dns and update docs.

**Comment by skofman1** [comment]
staging.nuget.org is deprecared. https://int.nugettest.org should be used.
