### ISSUE TITLE
-allversions (get-package) doesn't work in v1 feed

### ISSUE THREAD

**Issue by aldion** [NuGet/NuGetGallery#563]
Example using V2 :

PM> get-package -ListAvailable -AllVersions -filter 32feet.NET -source https://nuget.org/api/v2/

Id                             Version  
32feet.NET                     3.3
32feet.NET                     3.3.0.2
32feet.NET                     3.4.0.0
32feet.NET                     3.5.0.0

---

Example using V1, it returns a huge list of no so relevant packages, with only the latest version :

PM> get-package -ListAvailable -AllVersions -filter 32feet.NET -source https://nuget.org/api/v1/

Id                             Version  
32feet.NET                     3.5.0.0
ABCpdf                         8.1.1.6
ABCpdf.ABCGecko                8.1.1.6
ActionListWinForms             1.1.1.0
Activiz.NET.x64                5.8.0
Activiz.NET.x86                5.8.0
AE.Net.Mail                    1.6.0.0
.....

**Comment by pvandervelde** [comment]
And still an issue for the V3 feed

    get-package -ListAvailable -Filter packageid:nBuildKit.MsBuild -AllVersions

    Id                             Version              Description/Release Notes                                                                                                                                      
    --                             -------              -------------------------                                                                                                                                      
    nBuildKit.MsBuild              0.5.7                Provides build scripts and build tasks that can be used to execute the build of a .NET project.
