### ISSUE TITLE
[Organizations] Add UI to explain admin vs. collaborator

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5630]
Explain the roles of Admin and Collaborator. Put tooltip on the Administrator and Collaborator dropdown.
	
• A collaborator can manage the organization's packages i.e. upload packages as well as create API keys to upload packages.
• An administrator can manage organization's packages. In addition, an administrator can also add/remove members from the organization, edit organization settings, accept or request package ownerships.

**Comment by scottbommarito** [comment]
We discussed this should not be a tooltip--it should be text on the page.
