### ISSUE TITLE
Fetching package fails due to invalid certificate

### ISSUE THREAD

**Issue by EkiH** [NuGet/NuGetGallery#5641]
It seems that the V2 API sometimes returns the package location as https://nuget-prod-v2gallery.trafficmanager.net/api/v2/. This causes the request to fail as the certificate is valid for *.nuget.org and not the nuget-prod-v2gallery.trafficmanager.net domain. The problem seems intermittent. We noticed this problem last Friday on multiple different locations, on virtual machines in Azure North Europe and on local machines in Helsinki, Finland.

I've attached a Fiddler trace inside a zip as an example.
[nuget_org_invalid_certificate.zip](https://github.com/NuGet/NuGetGallery/files/1828524/nuget_org_invalid_certificate.zip)

**Comment by joelverhagen** [comment]
It looks like we have a bug in how we handle `packages.nuget.org` requests. In the meantime, could you use https://www.nuget.org/api/v2/ instead?

**Comment by skofman1** [comment]
@EkiH , thanks for reporting! We fixed this issue and it should no longer repro.
