### ISSUE TITLE
Gallery feedback survey does not route back

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#5644]
Taking the following survey ends up on a research.net page and there is no good way to come back to gallery except having to type the gallery url -

![image](https://user-images.githubusercontent.com/10507120/37675925-c3d64662-2c33-11e8-8ea1-6ffdbaeb2bbf.png)

Low priority but feels like bad UX.

**Comment by joelverhagen** [comment]
Spoke offline. Probably will remove the link since this survey is very old and potentially not even observed...

**Comment by karann-msft** [comment]
It is possible to update the exit page of the survey to point back to NuGet if we wanted to do that.

**Comment by anangaur** [comment]
I am okay to remove this for now. We can bring this back later.

**Comment by cristinamanum** [comment]
verified and closed
