### ISSUE TITLE
How to get the list of owners of a given package on nuget.org

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5647]
@Jericho commented on [Wed Mar 14 2018](https://github.com/NuGet/Home/issues/6679)

How can I get the list of owners of a given package hosted in nuget.org? What I'm looking for is the information circled in red in this screenshot:

![sshot-14](https://user-images.githubusercontent.com/112710/37443249-5c16cc6e-27e1-11e8-8111-888309c05edc.png)

When I query nuget with the following code, the `Owners` property is always null. So I'm wondering if there is an alternative?
```
var providers = new List<Lazy<INuGetResourceProvider>>();
providers.AddRange(NuGet.Protocol.Core.Types.Repository.Provider.GetCoreV3());
var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
var sourceRepository = new SourceRepository(packageSource, providers);
var nugetPackageMetadataClient = sourceRepository.GetResource<PackageMetadataResource>();
var packageMetadataResult = await _nugetPackageMetadataClient.GetMetadataAsync("Cake.Email", true, true, new Logger(), CancellationToken.None);
var mostRecentPackage = packageMetadataResult
    .OrderByDescending(p => p.Published)
    .First();
var owners = mostRecentPackage.Owners;
```

---

@rohit21agrawal commented on [Fri Mar 16 2018](https://github.com/NuGet/Home/issues/6679#issuecomment-373788398)

@joelverhagen does the v3 feed not send the owners metadata?

---

@Jericho commented on [Tue Mar 20 2018](https://github.com/NuGet/Home/issues/6679#issuecomment-374722505)

@joelverhagen can you help me figure out why the `Owners` property is always `null` and/or suggest an alternative to get the owners of a given package hosted on nuget.org?

---

@joelverhagen commented on [Tue Mar 20 2018](https://github.com/NuGet/Home/issues/6679#issuecomment-374738058)

Hey @Jericho, today there is no official way on NuGet.org to fetch the current list of owners on a package. This is a known shortcoming of our API and (in my own personal opinion) should be improved in the future. I will move this issue to the NuGetGallery repository to track this feature request.

**Comment by gep13** [comment]
@shishirx34 can you confirm what `Priority - 3` means?  Just wondering where this feature lands in amongst the others.  Thanks.

**Comment by loic-sharma** [comment]
Our priorities are roughly:

* Priority 1 means:  will be fixed within a month
* Priority 2 means: will be fixed within a few months
* Priority 3 means: will be fixed in the near future

Also, there are two ways you can determine a package's owners:

1. Use the unofficial owners.json API
2. Use the package's repository signature

# The unofficial `owners.json` API

> :warning: This API is unofficial and undocumented. The NuGet team may change it at any time.

There's an unofficial API that lists all packages and their owners: https://nugetprod0.blob.core.windows.net/ng-search-data/owners.json.

The schema is:

```
[
  [
    "PackageName",
    ["Owner1", "Owner2"]
  ],
  [
    "Newtonsoft.Json",
    ["jamesnk"]
  ],
  ...
]
```

You should be able to download this JSON blob and figure out the owners of all packages using it. This is what the NuGet search service uses to figure who owns what packages.

# Repository Signatures

In the near future, packages on nuget.org will be [repository signed](https://github.com/NuGet/Home/wiki/Repository-Signatures). You can use a package's repository signature to determine its owners through the signature's [metadata](https://github.com/NuGet/Home/wiki/Repository-Signatures#signature-metadata). To do so, you will need to use [this code](https://github.com/NuGet/NuGet.Client/blob/783986dd2a604061949a8a525f159a02384810af/src/NuGet.Core/NuGet.Packaging/Signing/Signatures/RepositoryPrimarySignature.cs#L20) inside of the [NuGet.Packaging](https://www.nuget.org/packages/NuGet.Packaging) NuGet package. Let me know if you need help doing that.

**Comment by dlebee** [comment]
This would be awesome or make the owners.json a rest api we can search from! :)

**Comment by loic-sharma** [comment]
Hello you should be able to use the [NuGet client SDK](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#search-packages). For example, to find the owners of the package `Newtonsoft.Json` on nuget.org:

```
ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
PackageSearchResource resource = await repository.GetResourceAsync<PackageSearchResource>();
SearchFilter searchFilter = new SearchFilter(includePrerelease: true);

IEnumerable<IPackageSearchMetadata> results = await resource.SearchAsync(
    "packageId:Newtonsoft.Json",
    searchFilter,
    skip: 0,
    take: 1,
    logger,
    cancellationToken);

foreach (IPackageSearchMetadata result in results)
{
    Console.WriteLine($"Found package {result.Identity.Id} with owners: {result.Owners}");
}
```

See:

Search API documentation: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result
Search SDK documentation: https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#search-packages

**Comment by joelverhagen** [comment]
This change has been implemented in PROD. For example:
![image](https://user-images.githubusercontent.com/94054/128918295-451c1ed7-aa13-472d-a4b6-81a34aa47390.png)

**Comment by Jericho** [comment]
@joelverhagen Thank you for keeping us in the loop. I confirm that I get ownership info when I search for packages like so:

```csharp
var logger = NullLogger.Instance;

var providers = new List<Lazy<INuGetResourceProvider>>();
providers.AddRange(NuGet.Protocol.Core.Types.Repository.Provider.GetCoreV3());  // Add v3 API support
var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
var nugetRepository = new SourceRepository(packageSource, providers);

// Search for multiple packages
var searchTerm = "Cake";
var take = 1000;
var skip = 0;
var filters = new SearchFilter(false)
{
	IncludeDelisted = false,
	OrderBy = SearchOrderBy.Id
};
var nugetSearchClient = nugetRepository.GetResource<PackageSearchResource>();
var searchResult = nugetSearchClient.SearchAsync(searchTerm, filters, skip, take, logger, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
Debug.Assert(searchResult.First().Owners != null, "The ownership information is missing when searching for multiple packages");
```

This is great!

However, I still do not get ownership information when I retrieve a specific package metadata using code similar to the sample I provided back in 2018.

```csharp
var logger = NullLogger.Instance;

var providers = new List<Lazy<INuGetResourceProvider>>();
providers.AddRange(NuGet.Protocol.Core.Types.Repository.Provider.GetCoreV3());  // Add v3 API support
var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
var nugetRepository = new SourceRepository(packageSource, providers);

// Retrieve the metadata for a single package
var name = "Cake.Email";
var nugetPackageMetadataClient = nugetRepository.GetResourceAsync<PackageMetadataResource>().GetAwaiter().GetResult();
var packageMetadata = nugetPackageMetadataClient.GetMetadataAsync(name, true, false, new SourceCacheContext(), logger, CancellationToken.None).GetAwaiter().GetResult();
var mostRecentPackage = packageMetadata.OrderByDescending(p => p.Published).First();
Debug.Assert(mostRecentPackage.Owners != null, "The ownership information is missing when retrieving a specific package's metadata");
```

**Comment by joelverhagen** [comment]
@Jericho - apologies on the miscommunication of the scope here. The technologies used to enable our various server-side endpoint on NuGet.org vary. For the search results (first sample) we have compute (Azure App Services + Azure Search) so making this change was quick and low risk. The data was already in the search index and we simply populated it in the search JSON.

For the registration "package metadata" endpoint (second sample), it is much harder for us to surface the owners since the backing technology is static, pre-rendered JSON blobs in blob storage. In other words there are literally millions of JSON files on Azure Blob Storage to cover all of the package IDs and versions on NuGet.org. This is not feasible for us to rollout right now unless there is an urgent business/product need for it.

If you'd like ownership information about a specific package ID, I recommend using the first sample with `var searchTerm = "packageid:Cake"` for an exact match on package ID.

**Comment by Vampire2008** [comment]
Hello!
Sorry for necroposting, but how to get owners of unlisted packages?
I need to check about 1000 packages. I alredy know that one package was take our PackageId before configuring reserved prefix and it was unlisted.
Search API don't search on unlisted packages.
