### ISSUE TITLE
semver2 version's metadata should be displayed in a separate column

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/NuGetGallery#5651]
displaying the metadata with the version in the same column as version gets ugly when the metadata gets long. My suggestion is to have a separate column for version metadata if it is a semver2 version.

**Comment by skofman1** [comment]
@rohit21agrawal , can you provide a screenshot of a page where the metadata doesn't look good?

**Comment by skofman1** [comment]
@rohit21agrawal , 🔔

**Comment by rohit21agrawal** [comment]
@loic-sharma helped me push a package to int.nugettest.org, and this is how one of our package looks: 

![28137688](https://user-images.githubusercontent.com/1857490/38398612-c3f33f38-38f9-11e8-85e9-90c6e2c91e53.PNG)

**Comment by rohit21agrawal** [comment]
@loic-sharma I am also curious why does it say 57 total downloads when it is still validating and was uploaded a minute ago.

**Comment by skofman1** [comment]
Looks like we need to limit the size of the column and add ellipsis overflow.

**Comment by anangaur** [comment]
We already have some ellipsis for long usernames, package IDs at multiple places. I remember @scottbommarito and I discussing this and he implemented for org's pages. We should do same here as well. 

We would need to do show the main version string in a better way and somehow make the metadata less explicit. 

![image](https://user-images.githubusercontent.com/14800916/39854606-429fcbdc-53dd-11e8-951e-5e8bdbb261e3.png)

**Comment by skofman1** [comment]
@anangaur , could you provide a UI recommendation  on how to make the metadata less explicit? We will fix the UI accordingly.

**Comment by skofman1** [comment]
Decision: we should remove build metadata from the table. Build metadata can be seen on top of the page. 
Idea: consider showing build metadata only when the owner is logged in (and hide publicly).
