### ISSUE TITLE
Hide confirm account link for org collaborators

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5654]
Per @anangaur 
> Looks like collaborators can not confirm and that’s good but it should not 404. Can you add it to the list of items to be fixed this sprint before go live?

![orgconfirmationbug](https://user-images.githubusercontent.com/15364949/37721543-0d85043e-2ce7-11e8-9432-58ebded411a3.jpg)

**Comment by scottbommarito** [comment]
Asked @anangaur for clarification on what he expects to happen.
404 is how all our confirmations on the site act when the user doesn’t have permission to accept them.
Should we just not show the link to confirmation?
