### ISSUE TITLE
Package metadata API returns an empty string instead of an object in repository value

### ISSUE THREAD

**Issue by zhili1208** [NuGet/NuGetGallery#5671]
Moved From https://github.com/NuGet/Home/issues/6725
@geneh

## Details about Problem

Projects that contain repository field in nuspec have incorrect value in https://api.nuget.org/v3/catalog0/data/ API: `"repository": ""`.

Example 1:
https://api.nuget.org/v3-flatcontainer/castle.core/4.2.1/castle.core.nuspec contains 
`<repository type="git" url="https://github.com/castleproject/Core"/>` 
but https://api.nuget.org/v3/catalog0/data/2017.10.10.15.15.58/castle.core.4.2.1.json (catalogEntry in https://api.nuget.org/v3/registration3/castle.core/4.2.1.json) doesn't: `"repository": "",`

Example2:
https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.1/newtonsoft.json.nuspec:
`<repository type="git" url="https://github.com/JamesNK/Newtonsoft.Json"/>`
https://api.nuget.org/v3/catalog0/data/2018.02.17.23.26.12/newtonsoft.json.11.0.1.json (catalogEntry in https://api.nuget.org/v3/registration3/newtonsoft.json/11.0.1.json):
`"repository": "",`

Documentation:
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-manifest-nuspec

https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-leaf

**Comment by skofman1** [comment]
@geneh, we never added support for repository URL in V3 API. Currently this information is not exposed anywhere or NuGet.org or in Visual Studio Package Manager. 
Can you share what is your usage scenario for this repository URL?

**Comment by geneh** [comment]
@skofman1, we are crawling different package managers including NuGet using https://github.com/clearlydefined/crawler. For NuGet, we need every package's nuspec data in JSON format. Converting XML to JSON works fine but it would be better to get it from an API in JSON format directly. The rest of the data in catalog API seems to be the there but this particular field's value is missing.

**Comment by skofman1** [comment]
@geneh , in general, there is (and will be) data that is available in the nuspec that is not available in V3 API. Repository URL is one such example, package type (https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#setting-a-package-type) is another example. 
We add data to V3 APIs based on the usage of this data in first party clients (like nuget.exe, VS package manager). Hence parity shouldn't be assumed.

**Comment by geneh** [comment]
Understood, thanks!
