### ISSUE TITLE
 RetryingHttpClientWrapper - HealthIndicatorStore should not be increased on 404

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#5683]
RetryingHttpClientWrapper  the CreateRequestQueue does  _endpointHealthIndicatorStore.IncreaseHealth(endpoint) on 404.
This should not happen.

**Comment by skofman1** [comment]
@cristinamanum , since we are planning to replace this code (https://github.com/NuGet/NuGetGallery/issues/5700) can I close this issue?
