### ISSUE TITLE
NuGet.Services.Configuration should support [TypeConverter]

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5688]
Today it uses `TypeConverter.GetConverter` which, as far as I know, only uses the default set of type converters.

**Comment by joelverhagen** [comment]
Line that probably needs to change:
https://github.com/NuGet/ServerCommon/blob/29ecd52296efbd4de9f2b66ecee45bcb30b1919f/src/NuGet.Services.Configuration/ConfigurationUtility.cs#L20

**Comment by skofman1** [comment]
@joelverhagen , is there a functional need here? Let's either modify the code or close the issue.
