### ISSUE TITLE
[Organizations] Link empty Manage Organizations page to the Transform flow

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5691]
A user who would like to transform their account into an organization cannot do so without knowing the endpoint directly. There should be a visible link on the Manage Organizations page to do so.

**Comment by scottbommarito** [comment]
@anangaur should the Manage Organizations page when a user has organizations have any indication that if a user would like to transform into an organization they need to leave all their organizations?

**Comment by anangaur** [comment]
Not required.
