### ISSUE TITLE
Resilient search service fail over in Gallery

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5700]
We currently use [RetryingHttpClientWrapper](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGet.Services.Search.Client/Client/RetryingHttpClientWrapper.cs)  to load balance Search service instances and failover. This code has several known issues: https://github.com/NuGet/NuGetGallery/issues/4003

The proposal is to instead of fixing the code to use Azure Traffic Manager.

**Comment by maartenba** [comment]
To give some history: the original intent was to load balance. Then it changed, to fire all requests to all backends, and get back the first response.

**Comment by skofman1** [comment]
Marten, so the only reason for the current design was request perf?

**Comment by maartenba** [comment]
I believe so, yes. And the ability to fall back on another server in case needed (so sort of load balancing).
The advantage though was that both back-ends are kept warm because they all get requests.
