### ISSUE TITLE
Can't fix account login for old MSFT account

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#5707]
_From @eschneider999 on March 28, 2018 11:54_

Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)

If this link worked......
(http://github.com/nuget/nugetgallery/issues)

_Copied from original issue: NuGet/Home#6749_

**Comment by skofman1** [comment]
@eschneider999 , can you provide additional details?

**Comment by eschneider999** [comment]
I think I fix the issue, I just unchecked that checkbox. I was just a bit confused. 

On April 2, 2018 12:58:18 PM CDT, Svetlana Kofman <notifications@github.com> wrote:
> @eschneider999 , can you provide additional details?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NuGet/NuGetGallery/issues/5707#issuecomment-377994435

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shishirx34** [comment]
@eschneider999 - Feel free to reach out to us if you see this issue again.
