### ISSUE TITLE
Package missing from flat container index.json

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5720]
https://www.nuget.org/packages/Paulovich.Caju/0.0.2

Version 0.0.2 is not in here:
https://api.nuget.org/v3-flatcontainer/paulovich.caju/index.json

**Comment by loic-sharma** [comment]
How did you find this? Is this package in the catalog?

**Comment by joelverhagen** [comment]
> How did you find this

Custom tool.

> is this package in the catalog?

Yes.

https://api.nuget.org/v3/catalog0/data/2018.03.08.17.37.38/paulovich.caju.0.0.2.json
https://api.nuget.org/v3/catalog0/data/2018.03.08.17.37.51/paulovich.caju.0.0.2.json
https://api.nuget.org/v3/catalog0/data/2018.03.08.17.43.38/paulovich.caju.0.0.2.json
https://api.nuget.org/v3/catalog0/data/2018.03.31.17.10.04/paulovich.caju.0.0.2.json

**Comment by joelverhagen** [comment]
China is fine. Global is not.

**Comment by joelverhagen** [comment]
From AI logs, it's unclear what happened. There is no exception or error message before seeing this line for the first time:

```
Ng.exe Information: 0 : No changes detected: paulovich.caju/0.0.2
```

My best guess is that catalog2dnx crashed after uploading the .nupkg and failed to emit and AI traces concerning the crash. This is supported by the fact that the process ID changed right around this time.

**Comment by joelverhagen** [comment]
Could be related to https://github.com/NuGet/NuGetGallery/issues/5473.

**Comment by joelverhagen** [comment]
This is now fixed in PROD.
