### ISSUE TITLE
Warning icons on menu and account settings are unclear

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5722]
It should be very clear to users what the warning icon next to their profile means. Currently, users have to follow a trail of icons that eventually lead to some tool-tips that are not well explained.

Users should also be guided on exactly how to fix the issue with their account by the tool-tips and other information displayed.

**Comment by anangaur** [comment]
We should expand the tooltip inside the **Password login** section. Same for the **Login Account** section.

In the password login, replace the checkbox with a button so that it aligns with the warning text.

**Comment by shishirx34** [comment]
- [ ] Remove warning icon upon removing Password login
