### ISSUE TITLE
Improve breadcrumbs across site

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5723]
The pages accessible from the package details page (e.g. edit, manage package owners, etc) should have a breadcrumb to the package details page.

@anangaur any idea on how these should look? The profile icon we use for the profile page breadcrumbs doesn't suit these pages.

**Comment by anangaur** [comment]
Why not?

\<profile-icon>\Packages\\<package>\Edit

**Comment by scottbommarito** [comment]
![image](https://user-images.githubusercontent.com/18014088/38332845-cb8d5fec-380b-11e8-8cec-d60c1a1560a5.png)
