### ISSUE TITLE
[Organizations] Add new organization page improvements

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5725]
- needs learn more link
- org name should appear in test profile link (do this for register flow as well?)
- explain gravatar for org email
- "the username is not available" should appear lower

**Comment by scottbommarito** [comment]
@anangaur what link should this page use for its learn more link?

**Comment by anangaur** [comment]
https://go.microsoft.com/fwlink/?linkid=870439

**Comment by anangaur** [comment]
![image](https://user-images.githubusercontent.com/14800916/38215239-f96c8172-367b-11e8-9e66-f86796ddcc55.png)

Font should be smaller.
