### ISSUE TITLE
JavaScript files should use strict mode

### ISSUE THREAD

**Issue by rebro-msft** [NuGet/NuGetGallery#5752]
### Problem
ModernCop (a static analysis tool for JavaScript files) has flagged the following files for not using strict mode.  

### Ask
Please set strict mode on these files and resolve any functionality that it may break.

### Files
src\NuGetGallery\Scripts
src\NuGetGallery\Scripts\gallery\async-file-upload.js           
src\NuGetGallery\Scripts\gallery\page-edit-readme.js            
src\NuGetGallery\Scripts\gallery\common.js       
src\NuGetGallery\Scripts\gallery\stats-dimensions.js    
src\NuGetGallery\Scripts\gallery\stats-perpackagestatsgraphs.js 
src\NuGetGallery\Scripts\supportrequests.js
src\NuGetGallery\Scripts\statsgraphs.js
src\NuGetGallery\Scripts\stats.js
src\NuGetGallery\Scripts\nugetgallery.js

### Message
Strict mode was set for this file but was enabled at global scope (which can lead to unexpected behaviors if this file is concatenated as part of a post-processing step). Consider using the JavaScript module pattern to wrap all code contained in the file within a function expression. Enable strict mode as the first statement of the containing function.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #1313](https://github.com/NuGet/Engineering/issues/1313) via [**ZenHub**](https://www.zenhub.com/)
