### ISSUE TITLE
Update signature processor to persist repository signature information into DB

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5754]
- Add repository signature record
- Add timestamp associated with repository signature
- Persist repository certificate chain in storage

**Comment by joelverhagen** [comment]
The only thing we are missing on https://github.com/NuGet/NuGet.Jobs/pull/401 is the real signing certificate information to include in the example.

This essentially depends on the same data as https://github.com/nuget/engineering/issues/1189 to finish.

**Comment by skofman1** [comment]
work left: verify in PROD

**Comment by loic-sharma** [comment]
This was disabled and will be redeployed to PROD on Monday. I will verify then.
