### ISSUE TITLE
HTTP 500 is thrown when documentation markdown is > 8000 characters

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5777]
1. Go to a package you own
1. Edit package
1. Provide a URL to a GitHub markdown document that is longer than 8000
    - example: https://raw.githubusercontent.com/adam-p/markdown-here/master/README.md
1. Submit

![image](https://user-images.githubusercontent.com/94054/38510898-38f5b6ba-3bdb-11e8-8888-7aa2fe82753e.png)

**Comment by chenriksson** [comment]
@joelverhagen Customer reported this issue... if you have suggestion for upper limit, maybe comment on the other thread?

see: https://github.com/NuGet/NuGetGallery/issues/5682

**Comment by skofman1** [comment]
![image](https://user-images.githubusercontent.com/16807822/44814543-e081a300-ab91-11e8-885b-6cffb7c00070.png)

Returns 400 now.
