### ISSUE TITLE
UI fixes for Organizations/Breadcrumbs

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5783]
1. Fix the margins and padding on manage organization page:
![image](https://user-images.githubusercontent.com/14800916/38525034-a2330c34-3c05-11e8-96d5-bc7a034c200f.png)

2. On Organizations page:
   * Fix the top/bottom margins as shown
   * Remove Add new button
    * Add "Add new" Linked button
![image](https://user-images.githubusercontent.com/14800916/38525190-3bcfe678-3c06-11e8-8e77-ae1a6f6e2b6c.png)

3. On create new org page
  * Align the organization oneliner to left
  * Push the info text for each text box up
  * Equal margins above and below the \</hr>

![image](https://user-images.githubusercontent.com/14800916/38530183-f5831dee-3c1d-11e8-8942-4b8bff717fa2.png)

... Growing list :)

**Comment by scottbommarito** [comment]
will work on this now

(please file new UI problems in another issue)

**Comment by anangaur** [comment]
Sure
