### ISSUE TITLE
"Organizations" should not be plural when there is only 1

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5789]
When logged in as a user that is a member of an organization, go to the profile page.

For example, for me on DEV environment:
https://dev.nugettest.org/profiles/jver

![2f200963](https://user-images.githubusercontent.com/94054/38576859-28cf9dda-3cb4-11e8-8542-fe7802af4478.PNG)

Two things:

1. "1 organizations" should be "1 organization"
1. The link should not include the space before the number. Right now there is a dangling underline on the link.

**Comment by scottbommarito** [comment]
Note: this applies to the "administrators | collaborators" text on the profile page for an organization as well
