### ISSUE TITLE
.Net Core templates Dependencies section

### ISSUE THREAD

**Issue by MNie** [NuGet/NuGetGallery#5792]
I wondering if there is a possibility to create some section for .net core templates, where we could list all dependencies of a concrete template. Right now it is doable via dependencies element in NuSpec, so all dependencies could be listed correctly. But it has some problems for example when installing a template:

@mlorbetske

> ...As far as the hang goes, it turns out (at least on Windows, I haven't tried this on my mac yet) that this isn't actually a hang. Because of the way that the template is authored (where the libraries used by the template are referenced in the template package itself) the installation process ends up looking through all of the types in all of the DLLs that are restored by the dependencies to see if there are any components that are required for making the template - this process takes a long time (multiple minutes) but does eventually complete, discovering the contained templates and no "components".

So if a template doesn't contain a dependency section it is downloaded almost immediately. But because of that dependencies section could looks like this:

![image](https://user-images.githubusercontent.com/7689103/38489381-8333b2da-3be6-11e8-9706-0bd14e73a331.png)

So the final question is, Is it possible to create some section on nuget.org which would depend only on a specific element in a NuSpec file?

[Related issue](https://github.com/dotnet/templating/issues/1506)

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #6815](https://github.com/NuGet/Home/issues/6815) via [**ZenHub**](https://www.zenhub.com/)
