### ISSUE TITLE
Nuget.Server Packages link does not redirect - 404.0

### ISSUE THREAD

**Issue by sneedbc** [NuGet/NuGetGallery#5794]
I am creating a new Nuget.Server website. After I get a new website setup and installing nuget.server, I run the page. When clicking on the packages folder, I get a 404 error.

The page does not seem to be redirecting correctly. Here is some information on what I have set up. I can't get it to run locally or after deploying to IIS.

Visual Studio 2017
C#
Nuget.server 3.1.2
Project is named EcsNuget

What things can I check to get this running. Been looking at this for hours today. Thank you.

**Comment by skofman1** [comment]
@sneedbc , did you follow the instructions here: https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server ?

**Comment by sneedbc** [comment]
Thank you. I had followed an old set of directions. I think I found several directions that all appeared to be the same. My issue was that I created an empty Website instead of an empty Web Application. Thank you for the help!
