### ISSUE TITLE
Login procedure thinks there is server issue when wrong MS account is selected

### ISSUE THREAD

**Issue by gorangrubic** [NuGet/NuGetGallery#5804]
I have two Microsoft accounts for historical reasons. When starting new session with huget.org, if I select wrong one it gives me "500 Internal server error" page - instead message: "you clicked on wrong account dummy!"

And if it's not due cookies left in my browser, it seems it actually logs me in even Microsoft account is not the one I used to open Nuget profile. Maybe it is anticipated / supported feature, but anyway: I get error page without real reason. 

So, not big deal. I'm just compassionate with the login procedure that believes server got issue due its fault but in reality the mistake is mine :)

**Comment by shishirx34** [comment]
@gorangrubic - thank you for reporting, we would like to make sure we show the proper error message. Do you mind sharing your nuget username to investigate the issue. We are consolidating our logins, and trying to have a single MSA per nuget account. Are your two microsoft accounts linked to the same nuget account?

**Comment by gorangrubic** [comment]
The profile:
https://www.nuget.org/profiles/goran.grubic

goran.grubic@gmail.com is proper MS account (I mean, the one I used to open the profile)
and
goran.grubic@koplas.co.rs is the "bad guy" in the story.

If it's linked? I have no idea, frankly. With all that accounts for so many services I have no idea what was used for what - but I can tell that the gmail.com one was the one used when was opening the profile. How and if Nuget later connected these two I really have no idea. Maybe, it asked me to connect (you would know better if there was such pop-up) them and I clicked while thinking on who knows what - but anyway I made no decision to do that, on self-aware way :) (hhaha how many words for simple: no)

**Comment by shishirx34** [comment]
I looked into this and yes your gmail account is linked to the nuget profile. The other one is not linked to any account. So upon selection of the second account during "Signin with Microsoft", you should have ideally seen a "Registration" page for registering a new Nuget profile for that account(koplas.co.rs). 

From the logs I see a few timeout/transient issues with database from three days ago which possibly threw 500 for you. Can you try logging in again with the second MS account on nuget and see, if you see a page for registering("Link microsoft account")? You don't need to register/link, just that you see the page is enough.

**Comment by gorangrubic** [comment]
Yep, now it works properly. 
You know what is strange, that after 500 I was logged in actually. But, now definitely works as it should be. Case closed (if you ask me :) )

![image](https://user-images.githubusercontent.com/20734509/39063299-e9887e52-44ca-11e8-8d72-c4a9a78b9c4a.png)

**Comment by skofman1** [comment]
@shishirx34 , is there any work for us here or can the issue be closed?
