### ISSUE TITLE
api.nuget.org IP is blacklisted in Russia :(

### ISSUE THREAD

**Issue by Sagrer** [NuGet/NuGetGallery#5806]
Hi.
Today i encountered an issue, similar to #3445
But now one of api.nuget.org IPs is blacklisted by Russian government.
I mean IP 93.184.221.200
I can't give a link to blacklist record (the site use AJAX), but this IP can be checked manually here: http://blocklist.rkn.gov.ru/
It is actually blocked :(.
I think that there is no any hope that this IP will be unbanned.
May be you can just avoid using this IP?

**Comment by agr** [comment]
Could you please follow the "Capture MTR" steps here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible
and send us the results so we better understand what got blocked.

Could you also please run the following command in powershell and show us the output:

    Invoke-WebRequest 'http://72.21.81.200/v3/index.json' -Headers @{Host='api.nuget.org'}

Meanwhile, I would suggest to setting up your computer to use a non-Russian DNS server (like 1.1.1.1, 8.8.8.8 or any other), instructions on how to change it should be easily searchable. This might get `api.nuget.org` (and others) host name to resolve to a different IP address (we're using CDN, so it should resolve to a different IP depending on your location as perceived by CDN, changing DNS might spoof your location).

**Comment by PastorGL** [comment]
I can confirm (from Russia too, 8.8.8.8 user).

WinMTR output:
```
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             192.168.1.1 -    0 |  150 |  150 |    0 |    0 |    1 |    0 |
|                           217.14.207.27 -    0 |  150 |  150 |    0 |    0 |    5 |    0 |
|                  izhevsk21.mark-itt.net -    0 |  150 |  150 |    1 |    2 |  124 |    1 |
|                 izhevsk207.mark-itt.net -    0 |  150 |  150 |    1 |    6 |  170 |    1 |
|                          198.51.100.101 -    0 |  150 |  150 |   36 |   37 |   49 |   37 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   30 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

PS output:
```
C:\Users\x> Invoke-WebRequest 'http://72.21.81.200/v3/index.json' -Headers @{Host='api.nuget.org'}
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:1
+ Invoke-WebRequest 'http://72.21.81.200/v3/index.json' -Headers @{Host ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

Roscomnadzor (Russian state Internet censorship agency) went completely crazy in an attempt to block Telegram and blocked a range of /15 and /12 subnets. So, this is an example of collateral damage.

**Comment by agr** [comment]
Thanks, we are investigating the issue with our CDN provider.

**Comment by Sergey-Terekhin** [comment]
Confirm
MTR output:
|------------------------------------------------------------------------------------------|

|                                      WinMTR statistics                                   |

|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |

|------------------------------------------------|------|------|------|------|------|------|

|                         router.asus.com -    0 |  116 |  116 |    0 |    0 |    0 |    0 |

|                              10.187.0.1 -    0 |  116 |  116 |    1 |    2 |   83 |    1 |

|                          213.85.208.250 -    0 |  116 |  116 |    1 |    4 |  162 |    3 |

|                            95.167.38.37 -    0 |  116 |  116 |    3 |    4 |   26 |    3 |

|                          213.59.212.235 -    0 |  116 |  116 |    2 |    2 |   12 |    2 |

|          rostelecom.demarc.cogentco.com -    0 |  116 |  116 |   44 |   45 |   65 |   45 |

|hu0-1-0-4.rcr22.fra06.atlas.cogentco.com -    0 |  116 |  116 |   42 |   42 |   43 |   42 |

|  telecomitalia.fra06.atlas.cogentco.com -    0 |  116 |  116 |   45 |   45 |   51 |   45 |

|           racc.franco33.fra.seabone.net -    0 |  116 |  116 |   44 |   46 |   94 |   47 |

|                          195.22.211.203 -    0 |  116 |  116 |   45 |   46 |   97 |   48 |

|                         152.195.101.129 -    0 |  116 |  116 |   42 |   46 |   91 |   43 |

|                          93.184.221.200 -    0 |  116 |  116 |   45 |   45 |   46 |   45 |

|________________________________________________|______|______|______|______|______|______|

   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by xakep139** [comment]
Link on RKN record with blocked IP 93.184.221.200: https://reestr.rublacklist.net/rec/342748/

**Comment by EugeneKosmin** [comment]
The same problem, [my ISP and area](https://www.whoismyisp.org/ip/90.188.114.120)

<html><body bgcolor="white">
<center><h2>WinMTR statistics</h2></center>
<p align="center"> <table border="1" align="center">
<tr><td>Host</td> <td>%</td> <td>Sent</td> <td>Recv</td> <td>Best</td> <td>Avrg</td> <td>Wrst</td> <td>Last</td></tr>
<tr><td>10.183.112.65</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>   2</td> <td>   2</td> <td>   5</td> <td>   2</td></tr>
<tr><td>192.168.0.9</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>   0</td> <td>   1</td> <td>  37</td> <td>   0</td></tr>
<tr><td>192.168.0.1</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>   1</td> <td>  13</td> <td> 699</td> <td>   1</td></tr>
<tr><td>tmsk-bras3.sib.ip.rostelecom.ru</td> <td>   1</td> <td> 272</td> <td> 271</td> <td>   2</td> <td>  17</td> <td> 341</td> <td>   4</td></tr>
<tr><td>ae5.tmsk-rgr5.sib.ip.rostelecom.ru</td> <td>   1</td> <td> 272</td> <td> 271</td> <td>   9</td> <td>  22</td> <td> 362</td> <td>  10</td></tr>
<tr><td>213.59.209.180</td> <td>   1</td> <td> 272</td> <td> 271</td> <td>   7</td> <td>  23</td> <td> 394</td> <td>   7</td></tr>
<tr><td>hu0-1-0-4.rcr22.fra06.atlas.cogentco.com</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>  89</td> <td> 110</td> <td> 705</td> <td>  95</td></tr>
<tr><td>telecomitalia.fra06.atlas.cogentco.com</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>  89</td> <td> 109</td> <td> 706</td> <td>  94</td></tr>
<tr><td>racc.franco33.fra.seabone.net</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>  88</td> <td> 110</td> <td> 705</td> <td>  90</td></tr>
<tr><td>edgecast.franco31.fra.seabone.net</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>  90</td> <td> 110</td> <td> 704</td> <td>  90</td></tr>
<tr><td>152.195.100.129</td> <td>   0</td> <td> 275</td> <td> 275</td> <td>  86</td> <td> 109</td> <td> 703</td> <td>  94</td></tr>
<tr><td>93.184.221.200</td> <td>   1</td> <td> 272</td> <td> 271</td> <td>  88</td> <td>  97</td> <td> 179</td> <td>  93</td></tr>
</table></body></html>

**Comment by chipitsine** [comment]
there's special nuget endpoint for China. can you please implement same for Russia ?

**Comment by egorpavlikhin** [comment]
Put this in hosts file as a workaround
72.21.81.200 api.nuget.org

**Comment by SagePtr** [comment]
Can you post full list of domains hosted by 93.184.221.200 ? Because not only nuget broken, but other microsoft services like ajax.aspnetcdn.com

**Comment by avgoncharov** [comment]
Hi!
In my case all IPs returns 404 - Not Found.

**Comment by EugeneKosmin** [comment]
> In my case all IPs returns 404 - Not Found.

@egorpavlikhin's workaround works fine for me. Thanks a lot, BTW!

Try this URL https://api.nuget.org/v3/index.json it must return XML file.

**Comment by egorpavlikhin** [comment]
Put it in drivers\etc\hosts file. If you visit the IPs from browser they will all return 404. 404 means it's working.

**Comment by proff** [comment]
93.184.221.200 is unbanned

**Comment by DimaBelov** [comment]
still not working

**Comment by codedokode** [comment]
Please don't do anything. Russian government blocks Russia from accessing millions of IP addresses trying to catch Telegram Messenger, and this is dubious even by Russian laws. You should not be wasting a second of your time trying to fix what they are breaking.

Instead, russian users can use VPN to access repositories or host their application on foreign servers that have no problems with connectivity.

**Comment by proff** [comment]
@DimaBelov your provider not is not updated blacklist yet

**Comment by Wereuser** [comment]
1. Ensure that your NuGet package source use URL https://api.nuget.org/v3/index.json (https://www.nuget.org/api/v2/ is working only for getting packge list, not for update them)
2. Insert into host file new entry "72.21.81.200 api.nuget.org" 
3. Profit!

**Comment by dvdobrovolskiy** [comment]
Confirm
api.nuget.org blocked

**Comment by Vertigo093i** [comment]
It is still somewhat blocked. Officially, the subject IP address was already removed from the registry. But it can take awhile for all providers to update their blocking rules. Even a single provider can not update all its routers at the same time (as it is for me).

**Comment by dvdobrovolskiy** [comment]
I believe so. Even that my provider is state scale monster - Rostelekom
api.nuget.org resolves to 152.199.20.1, I can even ping it. But Http/s traffic blocked

**Comment by Vertigo093i** [comment]
@dvdobrovoskiy, that's different from the subject IP. Your's one should have not been blocked by RKN. As I remember that one resembles to the IP address for China?
And for me all problems have been gone during the last hour.

**Comment by dvdobrovolskiy** [comment]
Not in the list, yes. But totally blocked. Saddest story. Country-wise. Not wise at all though.

**Comment by agr** [comment]
Azure had some connectivity issues couple of hours ago: https://azure.microsoft.com/en-us/status/history/ but they are mitigated now. @dvdobrovolskiy, you might have been impacted by it.
Clear DNS cache maybe (run `ipconfig /flushdns` in command line)?
Right now `api.nuget.org` should resolve to `93.184.221.201`.

May I get some fresh info on availability of `api.nuget.org`? And MTR logs if https://api.nuget.org/v3/index.json is not available.

Thanks.

**Comment by dvdobrovolskiy** [comment]
Confirm resolves to 93.184.221.201 and no block

tracert api.nuget.org

Tracing route to cs9.wpc.v0cdn.net [93.184.221.201]
over a maximum of 30 hops:

  1     1 ms    <1 ms     1 ms  192.168.1.1
  2     1 ms     1 ms     1 ms  31.163.64.1
  3     1 ms     1 ms     1 ms  87.226.151.158
  4     3 ms     3 ms     3 ms  87.226.146.132
  5    63 ms    63 ms    62 ms  ae41.stkm-cr1.intl.ip.rostelecom.ru [217.107.67.25]
  6    87 ms    83 ms    86 ms  5.104.69.12
  7    85 ms    85 ms    81 ms  93.184.221.201

Trace complete.

**Comment by PavelKhrapkin** [comment]
Restored!

**Comment by agr** [comment]
I suppose, we can consider the issue resolved.

**Comment by Shiko1st** [comment]
tracert is ok, browser opens index.json quickly, but in VS not working

**Comment by proff** [comment]
new ip is banned today
https://reestr.rublacklist.net/rec/347170/
you should again add entry to hosts file:
72.21.81.200 api.nuget.org

**Comment by proff** [comment]
@agr i think you shouldn't close issue while telegram works fine in Russia (instead of many other sites/services)

**Comment by dvdobrovolskiy** [comment]
Year, ajax.aspnetcdn.com blocked.

**Comment by vad3x** [comment]
https://reestr.rublacklist.net/rec/349558/

**Comment by roxan200** [comment]
Thank you! You help us with fascist government! The Workaround works great, but Whether this will work for a long time?

**Comment by petriashev** [comment]
not works once again...

**Comment by agr** [comment]
Please send [MTR](https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible) logs from locations where it does not work.

**Comment by petriashev** [comment]
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                                 RT-N56U -    0 |  134 |  134 |    1 |    5 |   22 |   13 |
|                          78.107.125.197 -    0 |  134 |  134 |    2 |    7 |   28 |    3 |
|      plehan9-bng1-local.msk.corbina.net -    0 |  134 |  134 |    2 |    8 |   29 |    2 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   27 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by petriashev** [comment]
it works, thanks

**Comment by dvdobrovolskiy** [comment]
It is temporary I believe. MS`s IPs send to ban on regular basis

**Comment by demonix** [comment]
dist.niget.org (152.199.20.1) is also blocked in Russia.
https://reestr.rublacklist.net/rec/350082/

**Comment by dvdobrovolskiy** [comment]
Add fresh VPN ban (Rostelekom through DPI). Donno what to change. Title or the state

**Comment by SagePtr** [comment]
> Donno what to change. Title or the state
Country =(

**Comment by loic-sharma** [comment]
`api.nuget.org` should now resolve to an unblocked IP address. Work is underway to move `blog.nuget.org`, `dist.nuget.org`, as well as some other lesser known endpoints. We will update this thread as we continue to make progress.

**Comment by loic-sharma** [comment]
`blog.nuget.org` and `dist.nuget.org` should now resolve to an unblocked IP address. Could you confirm @demonix this? Thanks!

**Comment by dvdobrovolskiy** [comment]
Unblocked.

**Comment by proff** [comment]
Temporary works

You can complain to the Interior Ministry for violation of Articles 13.18 of the administrative code and 286 of the criminal code (Roscomnadzor must block only telegram)
sample: https://docs.google.com/document/d/1NAO-Sdch-LFKa3GzFyitTk-tkQ34g5LhE6EL1QonLGI/edit
Ministry of Internal Affairs site: https://мвд.рф/request_main

**Comment by dvdobrovolskiy** [comment]
Document looks like cops should care / they don`t

**Comment by loic-sharma** [comment]
Great! Thanks @dvdobrovolskiy 😃 

This issue should now be resolved. If anyone has any connectivity issues, feel free to reply on this thread and we will reopen it.

**Comment by dvdobrovolskiy** [comment]
Solved till new ip blocked. I suggest you ignore next claim about blocked ip and suggest proper proxy/vpn with obfuscation etc

**Comment by efimomax** [comment]
Today (04 May) this IP ([191.236.146.247]) of nugget.org was blocked.

**Comment by dvdobrovolskiy** [comment]
just ignore this as our government regulator ignores common sense

**Comment by cristinamanum** [comment]
Hi @efimomax, could you add some details of your scenario?
