### ISSUE TITLE
Gallery seems to reuse the same instance of MailSender between multiple threads

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#5816]
https://github.com/NuGet/NuGetGallery/blob/67373eb24d14207969ecb80f0c9c20a8cc17f7fd/src/NuGetGallery/App_Start/DefaultDependenciesModule.cs#L268-L309

Here we create a `Lazy<IMailSender>` object (one per process) and pass `c => mailSenderThunk.Value` as a factory for generating `InstancePerLifetimeScope` objects. `mailSenderThunk.Value` on first evaluation will run the big chunk of code that creates `MailSender` and subsequent calls will reuse the instance it created.
This should only be done if we are sure that `MailSender` is thread-safe.

**Comment by skofman1** [comment]
To see logs in AI:
exceptions
| where outerMessage == "An asynchronous call is already in progress. It must be completed or canceled before you can call this method." and timestamp > ago(90d)

**Comment by cristinamanum** [comment]
Verified by checking the AI logs for the mentioned exception.
