### ISSUE TITLE
Ellipsis on package page make long versions unreadable

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5825]
Example: https://www.nuget.org/packages/Xamarin.Forms/

![image](https://user-images.githubusercontent.com/16807822/39004556-79d0cd26-43b2-11e8-9e97-e14ee32afb49.png)

We should make the version text longer, and add tool tip with the full value.

**Comment by joelverhagen** [comment]
This is merged to dev branch but has not been verified in any environment except my devbox.
