### ISSUE TITLE
Automatically delete empty accounts on owner request

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5831]
There are multiple request for account deletion by users that have no packages. The deletion should be automatic in those cases.

**Comment by anangaur** [comment]
Are these accounts that never had packages or accounts that had packages but were moved out?

**Comment by skofman1** [comment]
Is there a difference? The account name should remain reserved anyhow.

**Comment by anangaur** [comment]
Got it. I think for an unconfirmed account or an account that never had any packages, we should release the name too.
