### ISSUE TITLE
[Bug] Tags have newlines in them -> aren't being parsed correctly

### ISSUE THREAD

**Issue by jamesqo** [NuGet/NuGetGallery#5836]
I noticed this bug when the following output came up in my ML program:

```
'js 6.874810193669337,syncfusion 18.175989010608006,syncfusion\r\nessentialjs2\r\nej2\r\njavascript\r\nui\r\ncontrols\r\ncomponents\r\ngrid\r\nchart\r\nschedule 9.345568356508377,ui 9.489914442338158'
```

Above, `syncfusion\r\nessentialjs2\r\nej2\r\njavascript\r\nui\r\ncontrols\r\ncomponents\r\ngrid\r\nchart\r\nschedule` is actually a single tag value. Obviously, the author actually wanted to create multiple tags, one for `syncfusion`, one for `essentialjs2`, etc. Here's the package corresponding to this tag: https://www.nuget.org/packages/Syncfusion.EJ2/.

**Comment by scottbommarito** [comment]
The docs are pretty clear that it should be a space-delimited list (https://docs.microsoft.com/en-us/nuget/reference/nuspec) and not newline-delimited. I agree that we should probably support both but this isn't really a bug on our side and more of a misuse of the protocol.

**Comment by scottbommarito** [comment]
There are a couple problems with changing the protocol.

Some people may have intentionally put newlines in their tags without intending them to be split into separate tags, so this change in protocol would break them. I think this is unlikely but still something worth considering.

But more importantly, a lot of our V3 resources (including the catalog itself) actually store the tags as a `JArray`, e.g. the tags are split up already. Changing the delimiter would require regenerating these blobs, which is very difficult to do.
