### ISSUE TITLE
On the package pages on nuget.org is not working the counter of total downloads

### ISSUE THREAD

**Issue by Taritsyn** [NuGet/NuGetGallery#584]
In the last 2 days on the package pages on nuget.org is not working the counter of total downloads. It's also worth noting that the counter of downloads a specific version of a package is working properly.

**Comment by Taritsyn** [comment]
Today on [my profile page](https://www.nuget.org/profiles/taritsyn) are greatly decreased “Downloads taritsyn's of packages” rate (morning it was equal to 1,058,927, and now it equal to 702,416).

**Comment by maartenba** [comment]
Keep an eye on our blog, we'll detail the reasons there in the coming hours.

**Comment by maartenba** [comment]
FYI download counts have been updated and back to normal.

**Comment by Taritsyn** [comment]
Thank you!

**Comment by Taritsyn** [comment]
Again, counters are frozen.

**Comment by maartenba** [comment]
For which package?

**Comment by Taritsyn** [comment]
All my packages - http://www.nuget.org/profiles/taritsyn?showAllPackages=True

**Comment by Taritsyn** [comment]
Hello!

Starting from 10 January again stopped counters. Today a values of counters began to decrease.

**Comment by xavierdecoster** [comment]
As posted on https://status.nuget.org, there's currently an issue with stats collection for all packages. We are working on a fix.

You can track progress here: https://github.com/NuGet/NuGetGallery/issues/3472

**Comment by Taritsyn** [comment]
It is happening again.

**Comment by xavierdecoster** [comment]
@Taritsyn check status.nuget.org notice. We're performing some maintenance on the stats pipeline. Should be updating soon again.

**Comment by Taritsyn** [comment]
@xavierdecoster Thanks for information.
