### ISSUE TITLE
Cannot push anymore - possible rate limit

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#5845]
I tried to release several packages to NuGet in my release process. However, it suddenly failed with

```
-> WebException: The underlying connection was closed: An unexpected error occurred on a send.
-> IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
-> SocketException: An existing connection was forcibly closed by the remote host
```

And I'm unable to continue because it seems like I was blocked somehow? Is there a rate limit in place for pushing packages. If yes what are the steps to resolve this?

**Comment by chenriksson** [comment]
@matthid We've added rate limiting, but the limits are very high at the moment and shouldn't cause this.

Where are you uploading from? Can you provide us with an MTR trace so that we can investigate with our CDN?
https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible

**Comment by forki** [comment]
How high? IIRC the current deployment is over 50 packages right now

**Comment by matthid** [comment]
Today I could do the full release twice and if worked both times. So I'm not sure what happened at the time. It looked like some firewall block (and not an actual rate limit).

However it would be really nice if you guys would not break our workflow with future rate limits ;)

**Comment by scottbommarito** [comment]
@matthid - The new rate limits are posted at https://github.com/NuGet/Announcements/issues/24.

**Comment by matthid** [comment]
@scottbommarito Yes 250/hour is probably reasonable and shouldn't hit us too hard. If it hits us we will probably open issues ;)
