### ISSUE TITLE
A few packages are listed in registration but unlisted in gallery

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5865]
https://www.nuget.org/packages/Catel.Mvc/3.8.1312131405-beta
https://www.nuget.org/packages/Catel.Mvc/3.9.0.1406111340-beta
https://www.nuget.org/packages/Microsoft.DocAsCode.Build.JavaScriptReference/2.17.3
https://www.nuget.org/packages/MassTransit.AzureServiceBus/4.0.0.1322-develop
https://www.nuget.org/packages/Leadtools.Codecs.Dwg.dll.Native/20.0.0.1

All of these are unlisted in the gallery but listed in registration. Oddly, they are unlisted in search... not sure how that diverged.

**Comment by scottbommarito** [comment]
I'm not sure what caused these packages to fail but the only one that was pushed recently (within the last six months or so) was `Leadtools.Codecs.Dwg.dll.Native`, which had been scanned by the V3 monitoring pipeline and  determined that it needed to be skipped (and validated later) but for some reason but never was. It seems like the V3 monitoring job still has the potential to miss packages.

**Comment by joelverhagen** [comment]
It looks like the `Leadtools.Codecs.Dwg.dll.Native` is now corrected... perhaps it was reflowed? Seems like we should just reflow all of them.

**Comment by joelverhagen** [comment]
There are a bunch more mismatches:

```
reactiveui-core/5.2.0
reactiveui-winforms/5.2.0
reactiveui-events/5.99.2-beta
reactiveui-androidsupport/6.3.0
reactiveui-androidsupport/7.1.0
reactiveui-events/6.0.2.1
reactiveui-androidsupport/6.2.1.1
reactiveui-androidsupport/6.0.6
reactiveui-androidsupport/6.3.1
reactiveui-blend/6.4.0
reactiveui-androidsupport/8.0.0-alpha0062
reactiveui-events/5.5.1
reactiveui-core/6.4.0.1
```

**Comment by scottbommarito** [comment]
@joelverhagen my bad, I believe I did reflow `Leadtools` when I was investigating it.

**Comment by joelverhagen** [comment]
I think this problem is related to how `feed2catalog` is implemented. It uses a cursor against `LastEdited` which assumes that the timestamps put in the last edited column are always increasing. This is not guaranteed by SQL (at least how we are performing the commits).

Until we fix this bug or switch technologies (queue?), we should probably reflow them.

Feel free to perform additional investigations.

**Comment by scottbommarito** [comment]
@joelverhagen - We have a SQL trigger that updates the `LastEdited` field to be the SQL server's current time. Does that guarantees that the timestamps are always increasing? (My guess is probably not, lol.) It seems plausible that this is the cause, however.

Also, regarding the packages being correctly unlisted in search--that's because rebuilding the index updates it with the current state from the database. So even if a package was skipped initially, the next rebuild (which was done about a week ago) will "unskip" it.

**Comment by joelverhagen** [comment]
> Does that guarantees that the timestamps are always increasing?

From my reading and simulations it seems like there is no guarantee that each `INSERT`/`UPDATE` (and associated trigger) completes in the same order that `GETUTCDATE()` is invoked. 

Also, there is a problem where `feed2catalog` is exclusive in its lower bound, i.e. `LastEdited > {cursor}` which means that if two `LastEdited` values have the same timestamp then we can skip things. This last part has been known for ages: https://github.com/NuGet/NuGetGallery/issues/2841.

My simulation is here:
https://gist.github.com/joelverhagen/ac9d81f3645b048078162fa2fa112c28#file-program-cs

It uses `>=` instead of `>` and still has problems.

**Comment by shishirx34** [comment]
what is the fix here?

**Comment by joelverhagen** [comment]
> what is the fix here?

Reflow.

> have these packages been reflowed?

AFAIK, no.

**Comment by skofman1** [comment]
were reflowed.
