### ISSUE TITLE
Should not be showing any NUGet packages that is not applicable to the project (windows store app)

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#587]
Migrated from CodePlex:
http://nuget.codeplex.com/workitem/2554

Currently when you add nu-get package to a windows store JS app - if you go to online and all you see several packages that cannot be used in the project (.net packages which requires full .net framework). I understand that this is not a filtered list but I still do not get why we need to display any un-applicable packages.

**Comment by skofman1** [comment]
A similar suggestion is tracked here: https://github.com/NuGet/NuGetGallery/issues/3098
