### ISSUE TITLE
How to enable login option while configuring NuGet feed in visual studio?

### ISSUE THREAD

**Issue by Nivitha-Gopalakrishnan** [NuGet/NuGetGallery#5901]
Hi,

We are using custom public feed in our company. We have used NuGet.Server for this.
Now we need to enable authentication for our feeds.
We have more customers nearly 9 L,  so we need to enable customer based authentication.
 
We have customer username and password in our database, so once they configured our feed, they need to prompt to login , they need to login using our site's username and password.
 
We have to validate this and then allow them. Is this option is available in the NuGet.Server.
 
Please suggest me any option?

**Comment by loic-sharma** [comment]
NuGet.Server only authenticates package uploads and deletions. If you would like authentication for other operations such as package downloads, I would recommend looking at VSTS or MyGet.
