### ISSUE TITLE
Signing owner selection box on Manage Packages page can cause table to overflow

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5909]
![image.png](https://images.zenhubusercontent.com/58054e1495e42b6c5baa9ebb/10f07f47-fbbe-4097-ab30-4bdf22d712dc)

**Comment by xavierdecoster** [comment]
@scottbommarito haven't been able to repro this one yet. Got more info on how to reproduce this one? Also, in what browser is this?

**Comment by scottbommarito** [comment]
@xavierdecoster - can you show me what it looks like for you? should show very easily if you have enough owners for the "signing owner" column to appear. You may also need to upload some packages with long names, long version strings, many owners, etc. This was done on Chrome.

**Comment by joelverhagen** [comment]
I verified this on DEV environment.
