### ISSUE TITLE
Packages stuck in Validating state

### ISSUE THREAD

**Issue by NicolasDorier** [NuGet/NuGetGallery#5911]
My packages

https://www.nuget.org/packages/NBitpayClient/ and https://www.nuget.org/packages/NBXplorer.Client/ are stuck in validating state for hours.

![image](https://user-images.githubusercontent.com/3020646/39919183-d0a1effc-554d-11e8-930b-367841eadb91.png)

**Comment by skofman1** [comment]
@NicolasDorier , apologies for the slow response. On May 11th we had a live site issue and package validation was taking longer then expected. This was resolved on the same day.
