### ISSUE TITLE
[Debugging] Add option to disable email confirmation

### ISSUE THREAD

**Issue by jamesqo** [NuGet/NuGetGallery#5916]
While debugging https://github.com/NuGet/NuGetGallery/issues/5751, I needed to create a new account on the local server in order to upload packages. Registering brought up a prompt to confirm my email address, but it didn't actually send me an email. I had to comment out all of the `RequiresAccountConfirmation` attributes, some `user.Confirmed` checks, etc. You guys should consider adding an option to disable confirmation to make debugging easier.

**Comment by loic-sharma** [comment]
Emails that the Gallery sends are stored on disk by default. The [readme](https://github.com/NuGet/NuGetGallery/blob/master/README.md#build-and-run-the-gallery-in-arbitrary-number-easy-steps) has a little explanation on this:

> When working with the gallery, e-mail messages are saved to the file system (under ~/App_Data). You can use an SMTP server instead by editing src\NuGetGallery\Web.Config and adding a Gallery.SmtpUri setting. Its value should be an SMTP connection string, such as: smtp://user:password@smtpservername:25. You can also turn off e-email confirmations by changing the value of Gallery.ConfirmEmailAddresses to false in the src\NugetGallery\Web.Config file.

You should be able to open the email on disk and click the confirmation link to confirm your account. Does that make sense?

**Comment by shishirx34** [comment]
In web.config turn off this setting:
```
    <add key="Gallery.ConfirmEmailAddresses" value="true" />
```

**Comment by scottbommarito** [comment]
Closing because the option already exists as @shishirx34 mentioned.

**Comment by jamesqo** [comment]
@shishirx34 Thanks!
