### ISSUE TITLE
Deployment 2018-05-14

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#5917]
# Deployment 2018-05-14

**Status**: Planned

**Planned production date**:  2018-05-14

**Hotfixes**:

**Services to Deploy**:

Repo | Service | Commit | INT | PROD (primary) | PROD (secondary)
--- | --- | --- | --- | --- | ---
NuGet.Gallery | Gallery (real) | e2318e49d1... | <ul><li>[X] </li></ul> | <ul><li>[X] </li></ul> | <ul><li>[X] </li></ul> |
NuGet.Jobs | ProcessSignature| 1e2980059e9b... | <ul><li>[X] </li></ul> | <ul><li>[X] </li></ul> | 
NuGet.Jobs | Orchestrator | ac0e8b6 ... | <ul><li>[X] </li></ul> | <ul><li>[x] </li></ul> | 

**Related blog posts/docs**:
- N/A

**Gallery**
*Functional*

*Technical*

**Comment by chenriksson** [comment]
Published Gallery release:
https://github.com/NuGet/NuGetGallery/releases/tag/v2018.05.08
