### ISSUE TITLE
Can push one package from command line but not another

### ISSUE THREAD

**Issue by sam-wheat** [NuGet/NuGetGallery#5918]
[Can publish this](https://www.nuget.org/packages/AdaptiveClient/)

[Cant publish this](https://www.nuget.org/packages/AdaptiveClient.EntityFramework/0.30.0)

Publishing to same source: https://api.nuget.org/v3/index.json
Copy/paste apikey from same file.
 
Error message: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

Checked ownership as [described here](https://docs.microsoft.com/en-us/nuget/create-packages/publish-a-package#managing-package-owners-on-nugetorg).

I can log into nuget.org and upload the package.

Very sorry for this trivial question but the truth is...…… I'm stuck.

**Comment by skofman1** [comment]
@sam-wheat , apologies for the slow response. 
A possible issue can be the scopes of your API key. A key can be scoped to a subset of operations/packages.
For example: an API key can be allowed to only push new versions of a package, but not new packages. It can be scoped to push only packages the begin with prefix Adaptive*.
You can check the scope of your API key on page:  https://www.nuget.org/account/apikeys
