### ISSUE TITLE
How to enable login option while configuring my Nuget feed in visual studio.

### ISSUE THREAD

**Issue by karthikanandan** [NuGet/NuGetGallery#5919]
Hi @joelverhagen 

I want to enable the login option for Nuget feed in visual studio.

If a user configures my feed in visual studio. I want to enable login option. The login popup contains email and password (I have a database for user details). After successfully user login then allows the user to use the packages (Multiple user can use our feed).

I have configured our own NuGet feed using **NuGet Server**. I have used the **latest version (3.1.2)**
https://github.com/NuGet/NuGet.Server/releases

**How to achieve this?** 
**Is this option is available in the NuGet.Server ?**

Thanks in Advance.

**Comment by karthikanandan** [comment]
Hi Team,
Can you please update on this?
Thanks,

**Comment by loic-sharma** [comment]
NuGet.Server supports API key authentication for pushing packages and unlisting packages. NuGet.Server does not support authentication for package downloads. If you would like the latter, I would recommend looking at MyGet or VSTS. For a full list of hosting providers, please refer to this documentation: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

**Comment by karthikanandan** [comment]
Hi @loic-sharma 

Thanks for the update.
