### ISSUE TITLE
Allow package reupload with same version upon validation failure

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5933]
### Scenario:
* I upload a signed package with invalid signature. 
* The validation fails.
### Expected:
I should be able to re-upload the package with same version once i sign it with valid signature.
### Actual:
I am forced to upload a new version of the package.

/cc: @rido-min

**Comment by anangaur** [comment]
For packages that fail due to malware scan failure, the package should be locked for any update and hence prevent the owner to submit new packages. This could be a manual operation too.

**Comment by loic-sharma** [comment]
https://github.com/NuGet/NuGetGallery/issues/5345
