### ISSUE TITLE
Cannnot connect to https://api.nuget.org/v3/index.json from visual studio and web  browser

### ISSUE THREAD

**Issue by chanwut-k** [NuGet/NuGetGallery#5953]
Hi Support team,

We have the issue on accessing https://api.nuget.org/v3/index.json. It has been working fine until 21 May 2018.  Our server can access Internet or other websites without any problems

We have tried multiple ways to resolve this but still no luck. We can confirm that this is not DNS problem as we can resolve the URL to 117.18.232.200 which is correct.   However, when we tried to access this via web browser or using telnet command with 443 port, it is not working. I have read through the several discussion and this seemed to be happened with others earlier (https://github.com/NuGet/NuGetGallery/issues/3971). 

Our ISP is as below.

https://www.whoismyisp.org/ip/111.223.52.3

Can you please help us on this?

**Comment by shishirx34** [comment]
@chanwut-k 

Can you provide additional information regarding the issue?

1. What is the error you are seeing? 504 gateway issue?
2. What is your location?
3. Please provide us with an MTR log according to the instructions here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#managing-packages-on-nugetorg
4. What is your IP?

To avoid placing this information publicly, please send an e-mail with the details to support@nuget.org

I will close this issue, and we can handle it as a support request.
