### ISSUE TITLE
Validation:  add telemetry for duration of each validation

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#5956]
Individual validators/processors in the validation pipeline should log an AI custom metric for validation/processing duration.

**Comment by loic-sharma** [comment]
To clarify, the Orchestrator already reports validation/processing duration of each individual validator/processor. However, the Orchestrator polls on a minutely basis and its duration metric could be off by up to a minute.

**Comment by joelverhagen** [comment]
This is not needed with Queue back + current orchestrator-based telemetry.
