### ISSUE TITLE
[NuGet Symbol Server] BCDR

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#5979]
BCDR for the Symbol server support

**Comment by loic-sharma** [comment]
Should update the [Service Bus is down](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28BCDR.one%7CC35745F2-77AA-40A8-8D7A-15DFE4EF416C%2FService%20Bus%20is%20down%7CFADBEC6F-7CD0-40F3-A244-4E3E6ED4AD04%2F%29
onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/BCDR.one#Service%20Bus%20is%20down&section-id={C35745F2-77AA-40A8-8D7A-15DFE4EF416C}&page-id={FADBEC6F-7CD0-40F3-A244-4E3E6ED4AD04}&object-id={325435AE-83EB-0B89-327D-1636EBFF14ED}&B) page
