### ISSUE TITLE
Logging for Nuget.Server?

### ISSUE THREAD

**Issue by benorgil** [NuGet/NuGetGallery#5995]
How do I get Nuget.Server to write error logs or any logs?

For example when i try pushing a problem package i see this:

```
Pushing my.packge.1.2.3.nupkg to 'http://localhost:63701/nuget'...
  PUT http://localhost:63701/nuget/
  NotAcceptable http://localhost:63701/nuget/ 513ms
Response status code does not indicate success: 406 (Not Acceptable).
```

I have two problems:
* The message itself is not very helpful, I can confirm the package works when using it in my projects. Can I get more verbose info?
* I need Nuget.Server to write these errors to a log I can scrap/export

**Comment by chenriksson** [comment]
@ryuyu Can you have a look?

**Comment by ryuyu** [comment]
It doesn't look like there is any logging to enable in NuGet.Server at the time.
This is a great suggestion though, and we'll look into adding optional logging.

I was digging through the NuGet.Server code in the mean time, and it looks like we don't explicitly return 406 anywhere. You may want to check your IIS logs to see if the request is even getting to the NuGet.Server instance, and not being rejected by IIS.

You can find the log location for IIS express from the applicationhost.config ($(solutionDirectory)\.vs\config\applicationhost.config for VS) (https://stackoverflow.com/questions/5798264/iisexpress-log-file-location)

You can find instructiosn for locating IIS logs (not IISExpress) at https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/sitedefaults/logfile/

If you need more help, please let me know.
