### ISSUE TITLE
Allow NuGet account to signup with work and school accounts

### ISSUE THREAD

**Issue by jozefizso** [NuGet/NuGetGallery#5997]
I'm forced to upgrade NuGet account to use Microsoft Account.

Microsoft Account does not allow me to use me e-mail address, because it is "work or school account".

NuGet must allow accounts to use work and school accounts.

PS: I cannot create custom `@outlook.com` address because no matter what I enter, I always get validation error that account name is not available.

**Comment by shishirx34** [comment]
@jozefizso - could you please elaborate on this request? NuGet.org does support AAD(work or school) accounts. If you are having trouble linking an existing NuGet profile with an existing work/school 
 MSFT account. Please send us a request on support@nuget.org with your NuGet username and the email address of the work/school account you are trying to link. What is the error you are getting?

**Comment by skofman1** [comment]
Please reopen if this is still an issue.
