### ISSUE TITLE
Deployment 2018-06-06

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5998]
# Deployment 2018-06-06

**Status**: Planned

**Planned production date**:  2018-06-06

**Hotfixes**:

**Services to Deploy**:
- NuGet Gallery service
- V3 Pipeline
- Jobs

Repo | Service | Commit | INT | PROD | Prod Asia
--- | --- | --- | --- | --- | ---
NuGetGallery | NuGet Gallery | 4cc7184| <ul><li> [x] </li></ul> | <ul><li>[ ] </li></ul>
Services.Metadata | Catalog2Lucene | 53dc4fb  | <ul><li> [x] </li></ul> | <ul><li>[x] </li></ul>| <ul><li>[X] </li></ul>
Services.Metadata | Catalog2Registration | 53dc4fb  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Catalog2Dnx |53dc4fb   | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Feed2Catalog |53dc4fb   | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> 
NuGet.Jobs | Gallery.Maintenance** |135fe02  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Gallery.CredentialExpiration** |135fe02  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | ArchivePackages** |135fe02  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Stats.ImportCdnStatistics** |135fe02  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Stats.AggregateCdnDownloads** |135fe02 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Stats.CreateCdnWarehouseReports** |135fe02  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>

**SQL AAD authentication updates - please work with @chenriks on this

**Related blog posts/docs**:
- N/A

**Gallery**
- Remove 2FA for AAD restrictions (https://github.com/NuGet/NuGetGallery/pull/6017)
- Recaptcha updates (Need to generate keys for INT/PROD) (https://github.com/NuGet/NuGetGallery/pull/6006)

**Services Metadata/V3 pipeline**
- V3: fix incorrect telemetry (https://github.com/NuGet/NuGet.Services.Metadata/pull/308)
- V3: rename telemetry names. (https://github.com/NuGet/NuGet.Services.Metadata/pull/307)
- V3: increase default connection limit (https://github.com/NuGet/NuGet.Services.Metadata/pull/303) 

**V3 jobs**

*Technical*
- Retention policy for local log files (https://github.com/NuGet/NuGetGallery/issues/3147)
- SQL AAD authentication from Jobs (https://github.com/NuGet/Engineering/issues/1277)

**Comment by shishirx34** [comment]
@dtivel - as per this RI: https://github.com/NuGet/NuGet.Services.Metadata/pull/312 only your changes are going in. Can you verify this deployment item to make sure which v3 jobs need to be deployed here.

**Comment by dtivel** [comment]
For my commits, Feed2Catalog, Catalog2Dnx, Catalog2Registration, and Catalog2Lucene all need to be deployed.
