### ISSUE TITLE
Manual download link returning 403 response

### ISSUE THREAD

**Issue by rocklan** [NuGet/NuGetGallery#6002]
I've downloaded, compiled and installed NuGetGallery on a server, everything is working great except for one small issue: when I click on the "Manual Download" link for a package the server returns a 403 Forbidden response. On my machine it works fine :) Any ideas what might be causing this?

**Comment by loic-sharma** [comment]
What is your [`Gallery.StorageType`](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L27) config on your server?

**Comment by rocklan** [comment]
It's set to FileSystem - I've just realised that the two packages that I was trying to download didn't actually exist on the filesystem - they were in the DB though. I must have screwed something up, I've tried a different package and it's working fine :) Thanks muchly for your help.
