### ISSUE TITLE
Register certificates should not require 2FA for AAD based accounts.

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6005]
2FA setting is managed by AAD tenant admins and hence should not be enforced for registering certificates for AAD based account.

**Comment by dtivel** [comment]
@anangaur, does this only apply to registering/removing certificates or also to changing a package's required signer?

CC @shishirx34

**Comment by anangaur** [comment]
I forgot about the second part. Thanks @dtivel. We should make this change at all places where we have this restriction today.

**Comment by dotMorten** [comment]
Awesome! Works for me!
