### ISSUE TITLE
[Package Signing] Fail fast on cert mismatch upon upload/push – make the SHA1 hash check synchronous upon upload/push

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6008]
a.	When the package cert does not match with registered/required (for MSFT) certs
b.	When no cert is registered and signed package is pushed
*For a & b, if it’s an upload, show the error message upon upload even before submit

**Comment by joelverhagen** [comment]
Duplicate of https://github.com/NuGet/NuGetGallery/issues/6181.
