### ISSUE TITLE
SqlAggregateStatsService is missing download count

### ISSUE THREAD

**Issue by jamesharling** [NuGet/NuGetGallery#6026]
The `SqlAggregateStatsService` implementation of `IAggregateStatsService` does not populate the `AggregateStats.Downloads` property.

**Comment by chenriksson** [comment]
@loic-sharma Can you have a look?

**Comment by jamesharling** [comment]
Fixed with merge #6028, commit https://github.com/NuGet/NuGetGallery/commit/8f29dbfe5eed944ed379940ed3436910a055dc46
