### ISSUE TITLE
MS login is faling

### ISSUE THREAD

**Issue by jocutajar** [NuGet/NuGetGallery#6033]
Every MS live.com login brings me to a 500 error on nuget.org.

# Steps:
* https://www.nuget.org
* log in using the nuget account
* follow popup to sign in with Microsoft
* successful login at MS

# Result:
https://www.nuget.org/Errors/500?aspxerrorpath=/users/account/authenticate/return
Oops!
Error 500 - Internal Server Error

# Expected:
Login upgrade and access to nuget.org

# Impact
Since I cannot use nuget.org with the old account anymore, I'm effectively denied access to manage my packages.

**Comment by jocutajar** [comment]
Why cookies? After allowing some cookies to persist over site change, I was able to proceed. It's not cool to depend on cookies.

**Comment by shishirx34** [comment]
Can you elaborate on what issues you were seeing and give the repro steps. Please mention the NuGet account username and login emails used, you can send us the request to support@nuget.org if you don't prefer to share the details here. 

Can you clarify, what was it you had to do to allow cookies persistence?
>  After allowing some cookies to persist over site change, I was able to proceed.

**Comment by chenriksson** [comment]
@jocutajar Feel free to reopen if you have further details for @shishirx34
