### ISSUE TITLE
Consider removing the build metadata from the version list

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#6037]
Please consider removing the semver2 build metadata from the versions on the package metadata page - 

![image](https://user-images.githubusercontent.com/10507120/41121289-cec438c0-6a4c-11e8-9c67-2aadac4b7804.png)

The build metadata is a good add on and should be displayed on the page, but it has 2 issues - 
1. It can be noisy and given that it makes no difference in package lookup, it should only be displayed at one place on the page.
2. having it in the version list can confuse people who may not be familiar with semver2 rules.

**Comment by skofman1** [comment]
This is a duplicate: https://github.com/NuGet/NuGetGallery/issues/5651
