### ISSUE TITLE
Sign-In Assistance modal throws for unconfirmed users

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6060]
On the sign-in assistance modal, a `NullReferenceException` is thrown if the username is for an account whose email is unconfirmed.

You can find these kind of exceptions on Application Insights with this query:

```
exceptions
| where problemId == "System.NullReferenceException at NuGetGallery.AuthenticationController.FormatEmailAddressForAssistance"
```

/cc @shishirx34

**Comment by shishirx34** [comment]
Will fix it.

**Comment by scottbommarito** [comment]
What should the sign-in assistance modal show for accounts whose email is unconfirmed?

**Comment by shishirx34** [comment]
the formatted unconfirmed email address, see the fix.
