### ISSUE TITLE
Action links in emails lack the verb for the suggested action

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#6061]
https://github.com/NuGet/NuGetGallery/blob/f262ce11b5de6c30885568cb5bd8e28434cc87ee/src/NuGetGallery/Services/MessageService.cs#L245-L252

Message seem to lack the action that is expected from the reader. Like "Please, follow the link" or something like that.

**Comment by agr** [comment]
More examples:

https://github.com/NuGet/NuGetGallery/blob/f262ce11b5de6c30885568cb5bd8e28434cc87ee/src/NuGetGallery/Services/MessageService.cs#L352-L358

https://github.com/NuGet/NuGetGallery/blob/f262ce11b5de6c30885568cb5bd8e28434cc87ee/src/NuGetGallery/Services/MessageService.cs#L385-L390

**Comment by scottbommarito** [comment]
I think it's implied that the reader is meant to click the link.

```
To do x:
[url](url)
```

Potentially it may be better if we change this to
```
[Do x](url)
```

e.g.
```
[Decline this request](decline url)
```
