### ISSUE TITLE
[Reg cert] Admin should have permissions to manage certificates for an org

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6071]
Admins should have all the permissions for an org. Currently an admin does not have perm to manage an org's certificates.

**Comment by xavierdecoster** [comment]
@anangaur @skofman1 are you referring to _site admins_ that should have permission to manage certificates for an org? Org admins should already have that permission.

Should site admins have permission to manage an _account_? Or only _certificates_? 
In code, there's currently no distinction between these.

Depending on the answer to the above question, the solution will be different.

Code path that checks for permissions to manage certificates:
```
private bool CanManageCertificates(User currentUser, User account)
{
  var wasAADLoginOrMultiFactorAuthenticated = User.WasMultiFactorAuthenticated() || User.WasAzureActiveDirectoryAccountUsedForSignin();
  return wasAADLoginOrMultiFactorAuthenticated
    && ActionsRequiringPermissions.ManageAccount.CheckPermissions(currentUser, account) == PermissionsCheckResult.Allowed;
}
```

Current permissions requirement for _ManageAccount_:
```
/// <summary>
/// The action of managing a user or organization account. This includes confirming an account,
/// changing the email address, changing email subscriptions, modifying sign-in credentials, etc.
/// </summary>
public static ActionRequiringAccountPermissions ManageAccount =
    new ActionRequiringAccountPermissions(
        accountPermissionsRequirement: RequireOwnerOrOrganizationAdmin);
```

Proposed change, if site admins should have permission to manage an _account_:
```
/// <summary>
/// The action of managing a user or organization account. This includes confirming an account,
/// changing the email address, changing email subscriptions, modifying sign-in credentials, etc.
/// </summary>
public static ActionRequiringAccountPermissions ManageAccount =
    new ActionRequiringAccountPermissions(
        accountPermissionsRequirement: RequireOwnerOrSiteAdminOrOrganizationAdmin);
```

Proposed change if site admins should _only_ have permission to manage an account's _certificates_:
```
private bool CanManageCertificates(User currentUser, User account)
{
  var wasAADLoginOrMultiFactorAuthenticated = User.WasMultiFactorAuthenticated() || User.WasAzureActiveDirectoryAccountUsedForSignin();
  return wasAADLoginOrMultiFactorAuthenticated
    && (currentUser.IsAdministrator || ActionsRequiringPermissions.ManageAccount.CheckPermissions(currentUser, account) == PermissionsCheckResult.Allowed);
}
```

**Comment by anangaur** [comment]
account would be better. I thought site admins could already manage the members of the org but not certs.

**Comment by scottbommarito** [comment]
Upon discussion with @joelverhagen @anangaur @chenriksson - this should no longer be needed. The driving force between this feature has been resolved by https://github.com/NuGet/NuGetGallery/pull/6150.

**Comment by anangaur** [comment]
Not required, for now.
