### ISSUE TITLE
Upload Progress bugs

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6085]
There seems to be two bugs in the upload flow:

1. The "upload-progress" endpoint is polled even after the package has finished upload and the user is verifying the metadata
2. The upload bar will be stuck at 0 if the file upload request takes a long time to reach the server. This happens because if the "upload-progress" endpoint is polled 3 times before the upload starts, the UI will stop polling.

**Comment by skofman1** [comment]
@loic-sharma , please see how many users encountered this, and from that we will derive the priority.

**Comment by mbranscomb** [comment]
I encountered this when uploading several packages today. Visually I just saw the gray bar, and only later realized it is a progress bar. 

e.g.
![2435de4c-8034-11e8-9b9c-466cdaf4602c](https://user-images.githubusercontent.com/3381768/42337095-82224f08-803a-11e8-8053-ef7fd6a1df80.png)

With one package the bar also appeared to start at approx 30% and go backwards. But that could just be how I perceived it.

**Comment by loic-sharma** [comment]
@skofman1 It appears that roughly ~200 uploads a day hit this bug.

```
requests
| where name == "GET Packages/UploadPackageProgress" 
| where resultCode == "404"
| summarize count() by bin(timestamp, 1d)
| extend affectedUsers = count_ / 3
| project timestamp, affectedUsers
| render timechart  
```
