### ISSUE TITLE
Deployment 2018-06-27

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6087]
# Deployment 2018-06-27

**Status**: Planned

**Planned production date**:  2018-06-27

**Hotfixes**:
- N/A

**Services to Deploy**:
-V3 jobs:  Feed2Catalog, Catalog2Dnx, Catalog2Registration, Catalog2Lucene
-V2 jobs: Stats.CollectAzureCdnLogs

Repo | Service | Commit | Build | INT | PROD | Asia
--- | --- | --- | --- | --- | --- | ---
Services.Metadata | Catalog2Lucene | 3d999df86b12c | 33888 | <ul><li> [x] </li></ul> | <ul><li>[x] </li></ul>| <ul><li>[x] </li></ul>
Services.Metadata | Catalog2Registration | 3d999df86b12c| 33888  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Catalog2Dnx | 3d999df86b12c | 33888 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Feed2Catalog | 3d999df86b12c | 33888  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A
NuGet.Jobs| Stats.CollectAzureCdnLogs | 4ebdd67030dac89103 | 33909 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A
NuGet.Jobs| Orchestrator | 4ebdd67030dac89103| 33904 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A

**Comment by cristinamanum** [comment]
Deployment completed
