### ISSUE TITLE
Gallery:  cannot upload package via drag-and-drop in Edge

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#6090]
[async-file-upload.js uses `FormData.set(…)`](https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Scripts/gallery/async-file-upload.js#L55), which is [not yet supported in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?page=1&q=formdata).

Analytics query:
```
exceptions
| where timestamp > ago(30d)
| where type == "Object doesn't support property or method 'set'"
    and assembly == "https://www.nuget.org/Scripts/gallery/async-file-upload.js"
```

**Comment by skofman1** [comment]
This is a duplicate: https://github.com/NuGet/NuGetGallery/issues/5735
