### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by JDGHHou** [NuGet/NuGetGallery#6102]
It didn't recognize my password. I changed it. It still won't let me login. I get an OOPS 500 server error when I try.

Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, you are posting in the correct issue tracker.
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), file a bug on [NuGet Home](https://github.com/nuget/home/issues).

## Frequently Asked Questions

* **I want to delete my package** - please contact support instead via the [NuGet.org website](https://www.nuget.org)
* **I am having connectivity issues** - include an MTR and/or Fiddler trace - steps to capture this are [in our FAQ])(http://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org)

## All set!

Remove this template content and create your issue.

**Comment by shishirx34** [comment]
@JDGHHou - can you tell us your NuGet Username.

**Comment by shishirx34** [comment]
@JDGHHou - Is this still an issue for you?

**Comment by JDGHHou** [comment]
I ended up having to change my password. However it claims that it's using
Microsoft account login but I know my Microsoft account login password and
it wasn't that. so it looks like you've got an account that looks like a
Microsoft login account but really isn't and is really some other system
it's very confusing.

**Comment by shishirx34** [comment]
Can you clarify which password? Your Microsoft account password, or nuget.org login password? Also, what is your username on nuget? It will help us figure out why you saw a 500 page and fix the issue.

**Comment by JDGHHou** [comment]
Thanks for your help. Yes, I am using the Microsoft Account login option.
My Microsoft account username is johndunn@alumni.utexas.net

**Comment by JDGHHou** [comment]
by the way it wouldn't let me log in using my nuget login. The nuget login
screen claims that it is deprecated and that I couldn't use it.

**Comment by shishirx34** [comment]
Yes the NuGet login is deprecated, logging in with a MSFT account will remove the password login, if one is associated to your account. 

I am still a bit confused with regards to your following statement:

>However it claims that it's using
Microsoft account login but I know my Microsoft account login password and
it wasn't that. so it looks like you've got an account that looks like a
Microsoft login account but really isn't and is really some other system..

What do you mean by "...it's using Microsoft account.."? What is it's, NuGet?

Can you answer following questions?
1. Are you still seeing 500 when you try to login?
2. Launch https://nuget.org in incognito/private mode in the browser and click on `Sign In` => `Sign in with Microsoft`, Is your login successful after entering above email/password?

**Comment by shishirx34** [comment]
Please reopen if you still see this issue.
