### ISSUE TITLE
Please let me connect to a different username on Gravatar

### ISSUE THREAD

**Issue by Happypig375** [NuGet/NuGetGallery#6106]
I am unable to connect to my account over on Gravatar. As a result, my NuGet profile pic looks like :hankey: :cry:
![image](https://user-images.githubusercontent.com/19922066/41976235-31447fde-7a4f-11e8-8e5e-c6b406edcbf5.png)
 
As I do not know what email this username (Happypig375) is connected to on Gravatar, I tried every email but failed. Is there a way to connect to a Gravatar account which username is different from the one on NuGet as I want to create a new one?

**Comment by skofman1** [comment]
@Happypig375 , we get the image from Gravatar based on the e-mail address. You can see the e-mail address on the account page (https://www.nuget.org/account) under "Email Address" section. Next step will be to login to gravatar.com with this e-mail and make sure the picture is amazing 😄

**Comment by Happypig375** [comment]
Wow! That is great news! Hope it is not fake news :wink:

I'll wait a bit and hope my avatar replaces this abomination.

**Comment by Happypig375** [comment]
Wow! Thanks! My avatar suddenly looks like 🌈 now 😆
