### ISSUE TITLE
What's the difference of Nuget.Server and Nuget.ServerV2 project of the source code?

### ISSUE THREAD

**Issue by softboy99** [NuGet/NuGetGallery#6123]
What should i use? compile your source code. Always 405 error. when search on the internet, some is pointed to v2, some is pointed to v3. Is this is the latest version code of Nuget.Server?

**Comment by loic-sharma** [comment]
I recommend this guide to setup your own feed: https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server

To answer your questions:

1.  For most scenarios, you should use [NuGet.Server](https://www.nuget.org/packages/NuGet.Server/3.1.2). This is a configurable app that supports NuGet v2 APIs.
2. "NuGet.Server.V2" implements the NuGet protocols, but nothing more. You can use this package if you would like to heavily customize how your NuGet feed works.
3. "NuGet.Server" only supports NuGet's v2 APIs. If you would like to host a NuGet feed that supports v3, I recommend that you use BaGet instead: https://github.com/loic-sharma/BaGet
