### ISSUE TITLE
[Organizations] Add member by email address

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6133]
@loic-sharma commented on [Mon Jul 02 2018](https://github.com/NuGet/Engineering/issues/1510)

If you navigate to your organization and add a member, the input field reads "Add existing NuGet.org user". It's not clear that this field accepts only usernames but NOT email addresses. We should either:

1. Allow adding Organization members by email addresses
2. Change the input field to read something along the lines of "Add existing NuGet.org user by username"
3. Detect when an email address is inputted, and if so, show an error message that you must search by username

I think option 1 would be the best experience all around.

**Comment by anangaur** [comment]
@loic-sharma 

Option 1 was originally proposed but was taken back later as there was privacy concern. We do not divulge email addresses of NuGet users.

**Comment by loic-sharma** [comment]
I see. Do you have a preference between option 2 and 3?

**Comment by scottbommarito** [comment]
After discussion with @anangaur, we are planning to do both 2 and 3.
