### ISSUE TITLE
Owner info missing for a package

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6136]
Search for: "Microsoft.ML.LightGBM"

![image](https://user-images.githubusercontent.com/14800916/42234800-948f5442-7eaa-11e8-8158-926840ed0a31.png)

**Comment by skofman1** [comment]
@anangaur , owner information is updated once every 24 hours in search. Meaning, new packages will have an empty owner field for a while.
What is the proposed fix? Increase update frequency? Remove the "by: " text?
