### ISSUE TITLE
How can a package in validating status have downloads?

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6141]
https://twitter.com/dotMorten/status/1014906387594276864

![image](https://user-images.githubusercontent.com/14800916/42337540-f7cb995c-803b-11e8-98f7-39224f6e6fdc.png)

**Comment by loic-sharma** [comment]
This could be possible under the following scenario: a user uploads a package, deletes it, and then reuploads it. After the first package becomes available, our ingestion pipeline downloads the package a few times to index different parts of the package. When statistics are processed, the downloads from that first upload can be given to the second upload, even if the second upload hasn't finished validation yet.

... Or we could have a bug. Could we ask the customer what package was affected?

**Comment by anangaur** [comment]
You are there on the thread now :)

Btw, if nuget.org downloads the package as part of validation process, they should excluded from the download counts.

**Comment by loic-sharma** [comment]
The validation process does download packages, but those downloads are not included in the download counts.

**Comment by anangaur** [comment]
So then this is a bug if the package was not deleted and re-uploaded.

**Comment by skofman1** [comment]
@chenriksson will investigate.

**Comment by chenriksson** [comment]
Checked package auditing, SQL auditing, and Gallery/Stats DBs:
- Original INSERT had DownloadCount=0
- No other UPDATE/INSERT for this package/version
- Data for BULK INSERTs (AggregateCdnDownloadsInGallery) not included in SQL auditing, but Stats DB has no reference of this package/version
- Package has original datetime for Created/Updated

Based on this, it sounds like DownloadCount=2 wasn't persisted in the DB. I'm now wondering if there was a runtime issue.

**Comment by chenriksson** [comment]
Package: { Id = 1709001 , Created = 2018-07-05 16:42:05.907 }
Earliest Fact_Download:
- Timestamp: 2018-07-05 17:59:56.710
- LogFileName: wpc_DB16_20180705_0062.log.gz

@joelverhagen There's no data in Fact_Download before the package creation date, so I don't think it's caused by the stats data issue that we discussed.

**Comment by chenriksson** [comment]
Per discussion, it doesn't sound like this meets the bar for stats bugs to fix. If customers report more issues like this we can consider any of the following:
- Gallery AI to detect occurrence of this issue (Downloads > 0 when validating)
- Gallery override to always show '0' if package is validating
- Stats AI to help investigation (packages per bulk copy / would be lots of data)
