### ISSUE TITLE
Large package size should be rejected with 413 - Payload too large

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#6143]
I believe IIS rejects with 500 right now.

**Comment by singku** [comment]
It's happens when using nuget.exe, so here is the original issue. https://github.com/NuGet/Home/issues/7091.

The questions is, will this size limit be updated to higher value?

**Comment by skofman1** [comment]
@singku , 250MB is currently a hard limit on package size on nuget.org and is necessary to deliever a good e2e experience. We will consider raising it in the future as the requirements of customers change.
For now, we recommend spliting your package into two packages. We will respond with detailed instructions on NuGet/Home#7091.

**Comment by singku** [comment]
@skofman1 Thank you. Will follow the instructions to split if it's applicable in our case.
