### ISSUE TITLE
Condition References

### ISSUE THREAD

**Issue by eschneider999** [NuGet/NuGetGallery#6149]
If I have optional references, what is the best way to achieve this? 

In my case it's a database vendor library. If they choose Oracle, Sql Server, My Sql, there would be a specific vendor lib needed. 

Currently I add all and allow the developer to remove the unneeded verdors, but with the new Package reference you can't remove specific libs?

I thought about adding a content folder and adding them to it, then dynamically referencing them in code. But it seems the package reference doesn't support content/project folders?

I would rather not add create packages for all the database vendors? Is there A way to create a skeleton package that combines other packages?

**Comment by shishirx34** [comment]
Issue moved to [NuGet/Home #7102](https://github.com/NuGet/Home/issues/7102) via [**ZenHub**](https://www.zenhub.com/)
