### ISSUE TITLE
Fix the 'Learn more' link for discontinued nuget.prg based auth

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6155]
Currently when somebody signs in using the NuGet.org authentication, we state the following in the blocking dialog:
**NuGet.org authentication has been discontinued. [Learn more](https://blog.nuget.org/20180227/Deprecating-NuGet-org-authentication.html).**

The **Learn more** link goes to an old blog post. It should point to the following post, instead: https://blog.nuget.org/20180515/NuGet.org-will-only-support-MSA-AAD-starting-June.html

**Comment by zhhyu** [comment]
The Learn more link has been redirected to the correct page now.
