### ISSUE TITLE
After installing nuget server, I do not see well-formatted OData over ATOM feed of packages

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/NuGetGallery#6162]
@csimone86 commented on [Mon Jul 09 2018](https://github.com/NuGet/Home/issues/7099)

I am creating a free private nuget server with visual studio. I am following exactly the indicated steps on [nuget server site](http://nugetserver.net/) (those one on the right).

I think I have done everything, and nothing should miss and nothing should have been done in a different way.

But when I run my site, and I click on "here" (step 5) I do not see a well-formatted page like [this one](http://nugetserver.net/gfx/OData-over-ATOM-package-feed.png)...

But I see just the XML.

I am using Chrome.

What's wrong?

Thank you

**Comment by agr** [comment]
As far as I understand, we are not affiliated with nugetserver.net in any way. I'd wait for others to chime in though.

**Comment by skofman1** [comment]
If you are trying to run a NuGet.Server, please follow the official instructions here: https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server

Closing the issue. If the instructions don't work for you feel free to reopen.
