### ISSUE TITLE
please automatically update dependencies in .nuspec file when update package reference by Nuget Manager

### ISSUE THREAD

**Issue by softboy99** [NuGet/NuGetGallery#6164]
please automatically update dependencies in .nuspec file when update package reference by Nuget Manager,Otherwise, when forget to update the dependencies in .nuspec file manually, after package builded and published, it will cause the MSBuild runtime error for loading the old version dependency when this package being used.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #7123](https://github.com/NuGet/Home/issues/7123) via [**ZenHub**](https://www.zenhub.com/)
