### ISSUE TITLE
Deployment 2018-07-16

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#6166]
# Deployment 2018-07-16

**Status**: Planned

**Planned production date**:  2018-07-19

**Hotfixes**:
- https://github.com/NuGet/NuGetGallery/issues/6191: 500 error due to SecurityPolicies regression (https://github.com/NuGet/NuGetGallery/commit/e1a55f020302000d475940115127bba3ea80caa0)

**Services to Deploy**:
 - NuGetGallery
 - Orchestrator
 - V3 jobs: 
   - Feed2Catalog
   - Catalog2Dnx
   - Catalog2Registration

Repo | Service | Commit | Build | INT | PROD | Asia
--- | --- | --- | --- | --- | --- | ---
NuGetGallery | NuGetGallery | e1a55f0 | 35558 | <ul><li> [x] </li></ul> | <ul><li>[x] </li></ul>| N/A
Services.Metadata | Catalog2Registration | 522605c | 35211 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Catalog2Dnx | 522605c | 35211 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
Services.Metadata | Feed2Catalog | 522605c | 35211 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A
Services.Metadata | Catalog2Lucene | 522605c | 35211 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Orchestrator | TBD | TBD  | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A

**Gallery needs DB Migration before deployment
**Orchestrator - ValidationDB needs a Migration before deployment

**Comment by loic-sharma** [comment]
The PROD deployment of the gallery has been rolled back.
