### ISSUE TITLE
[NuGet Symbol Server] Topics for the validation jobs

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6171]
Resource | Dev | INT | PROD 
--- | --- | --- | ---
Orchestrator Topic| <ul><li> [x] </li></ul> |  <ul><li> [x] </li></ul> |  <ul><li> [ ] </li></ul> 
Symbol Validator Topic| <ul><li> [X] </li></ul> | <ul><li> [x] </li></ul> |  <ul><li> [ ] </li></ul> 
Symbol Ingestor Topic| <ul><li> [X] </li></ul> | <ul><li> [x] </li></ul> |  <ul><li> [ ] </li></ul> 

The resources are on the same service bus as the other service bus resources.

**Comment by shishirx34** [comment]
https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Specs.one%7C910181C5-8695-4A1C-9792-A56DBB86F1C3%2FConfigurations%7C60011C0D-2759-4C35-A59A-0D102D41BE15%2F%29
onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Specs.one#Configurations&section-id={910181C5-8695-4A1C-9792-A56DBB86F1C3}&page-id={60011C0D-2759-4C35-A59A-0D102D41BE15}&end

**Comment by shishirx34** [comment]
Configurations and how to run in onenote.

**Comment by shishirx34** [comment]
Need to add topics for INT and PROD.

**Comment by shishirx34** [comment]
Tracking PROD work together in the single issue which can be expanded further. Closing this issue.
