### ISSUE TITLE
How to change organization name

### ISSUE THREAD

**Issue by FObermaier** [NuGet/NuGetGallery#6188]
According to #5692 and #5693 user/organization names should not contain spaces.

Unfortunatly -however- the organization I'm maintaining is older than these 2 issues and it has two spaces in it.: [`nettopologysuite - team`](https://www.nuget.org/profiles/nettopologysuite%20-%20team).
 
What can we do to fix that. The issue arises because there are some packages around (e.g. [NetTopologySuite.IO.PostGis](https://www.nuget.org/packages/NetTopologySuite.IO.PostGis/) that are based on our code and we'd like to maintain but they don't belong to our organization. We are not owners of these packages .    

With the current username the transferation/addition of ownership fails with an internal server error.

**Comment by shishirx34** [comment]
As a one off scenario this naming issue has been fixed. https://www.nuget.org/profiles/nettopologysuite-team 

@FObermaier - please verify that you are unblocked.
