### ISSUE TITLE
Packages page showing 500 error

### ISSUE THREAD

**Issue by anantgarg** [NuGet/NuGetGallery#6194]
When visiting the Packages page, it shows me a 500 error:

![image](https://user-images.githubusercontent.com/168350/42996823-5a29cb1c-8c32-11e8-837c-e52c7dfb4e4b.png)

**Comment by rstaib** [comment]
Is there any Update?

**Comment by loic-sharma** [comment]
Apologies for the inconvenience, this should now be mitigated. Please let us know if you run into any additional issues.

**Comment by rstaib** [comment]
Thank you for the quick response and fix of course. I have tested it and could not find any issues anymore.

**Comment by loic-sharma** [comment]
Thanks for confirming! Feel free to open a new GitHub issue if you run into anything else.
