### ISSUE TITLE
An error occurred while processing your request. We really messed up this time...

### ISSUE THREAD

**Issue by ghuntley** [NuGet/NuGetGallery#6196]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Logging in to access the support portal results in <a href="https://t.co/cug9besQwL">pic.twitter.com/cug9besQwL</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/1021214066528870400?ref_src=twsrc%5Etfw">July 23, 2018</a></blockquote>

![image](https://user-images.githubusercontent.com/127353/43053511-7123cbe8-8e70-11e8-8aa2-e160cba5799b.png)

**Comment by loic-sharma** [comment]
Nothing is jumping out at me from the logs and I'm having difficulties reproducing this. From what I can tell, these are the steps that should reproduce this issue:

1. Log out from nuget.org
2. Go to https://www.nuget.org/packages/Splat/4.1.0/ReportMyPackage
3. After logging in, you are redirected to an error page

Is this correct?
