### ISSUE TITLE
[NuGet Symbol Server] Use the ValidatingType on the Orchestrator side to filter symbols by the packages.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6197]
Review the Orchestrator services and update them to use the ValidatingType in APIs that query the Validation DB and when symbols will be ingested could return data for both symbols and packages

There are at least two types that need to have the APIs reviewed:
src\Validation.Common.Job\Storage\ValidatorStateService.cs ( method IsRevalidationRequestAsync )
\src\NuGet.Services.Validation.Orchestrator\ValidationStorageService.cs

**Comment by shishirx34** [comment]
Not sure this one either why has to be done for MVP.
