### ISSUE TITLE
"Cancel" buttons on Account page are doing nothing

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#6200]
I noticed that all those nice looking "cancel" buttons on the account page are doing nothing:

![image](https://user-images.githubusercontent.com/756703/43103715-575c1ac6-8ecf-11e8-9c94-10c277e9c35d.png)

They are implemented as "a-tags" and styled as buttons inside each form like this:

```
      <div class="col-sm-6">
                        <a href="#" role="button" class="btn btn-default form-control" id="cancel-change-password">
                            Cancel
                        </a>
                    </div>
```

I didn't find any Javascript event binded to those element ids either.

When a user now clicks the cancel button nothing happens or the browser will just scroll up because of the "#" in the href.

Question is: What would be the desired behavior when I click on "cancel"?
I would assume that input fields are "cleared" and the "form box" should be collapsed like this:

![image](https://user-images.githubusercontent.com/756703/43103929-f7385366-8ecf-11e8-9661-5f40f68147f0.png)

What do you think? If you think this should be fixed I would be happy to assist with a PR :)

**Comment by skofman1** [comment]
@robertmuehsig , thanks for reporting! @scottbommarito  if fixing this bug along with a few accessibility issues.
