### ISSUE TITLE
Verify package fails and cannot submit new package

### ISSUE THREAD

**Issue by chrno1209** [NuGet/NuGetGallery#6218]
Reproduce steps:
1. Install a local development environment with file system storage
2. Try to upload a package
3. Submit package after uploading sucessfully

Expected: submit package successfully
Actual: get this error message:
The process cannot access the file 'D:\NuGetGallery-master\src\NuGetGallery\App_Data\Files\uploads\1.nupkg' because it is being used by another process

Checking in the code, in PackagesController.VerifyPackage, we  need to dispose uploadFile stream before deleting that file.

**Comment by skofman1** [comment]
Hi @chrno1209 , this issue was already fixed on our dev branch: https://github.com/NuGet/NuGetGallery/issues/6175
