### ISSUE TITLE
Nuget push to feeds taking long with EC2 Windows + ALB

### ISSUE THREAD

**Issue by rohitagarwal11** [NuGet/NuGetGallery#6221]
Hi Team, 

We are facing while pushing nuget packages from AWS EC2 windows instance over ALB to our proget application feed.

The case appears it takes too long to push the package like 500sec which generally takes 30 seconds max.

We tested the below cases:
1. Same working fine with linux slaves in AWS.
2. Same working fine with linux slave in on prem linux slaves
3. Same working well with windows on-prem slaves

Can someone help in this case?.

**Comment by skofman1** [comment]
@rohit21agrawal , are you publishing packages to nuget.org?

**Comment by rohit21agrawal** [comment]
@skofman1 this was a different rohit agarwal
