### ISSUE TITLE
[NuGet Symbol Server] Deployment - Symbol validatior job 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6226]
Deployment of the Symbols validator job.

**Comment by shishirx34** [comment]
Couldn't be verified in INT because the gallery hasn't been deployed with latest changes.

**Comment by shishirx34** [comment]
Will close this issue for now and reopen if need be.

**Comment by shishirx34** [comment]
AI log seems fine, couldn't verify with sending message. Will close this.
