### ISSUE TITLE
[NuGet Symbol Server] Deployment Symbol Ingestion job

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6227]
Deployment of Symbol Ingestion job.

**Comment by shishirx34** [comment]
@ryuyu - It looks like this job hasn't been working in INT. Need to fix it see the exceptions in AI. Missing certificates.

traces
| where cloud_RoleName == "NuGet.Jobs.Validation.SymbolsIngester" and timestamp > ago(10m)

**Comment by cristinamanum** [comment]
Dev and Int are verified. 

Let the task open for Prod and remove the MVP label,
