### ISSUE TITLE
style error in Firefox

### ISSUE THREAD

**Issue by JaylanChen** [NuGet/NuGetGallery#6254]
**There is no problem when opening the page.**

![default](https://user-images.githubusercontent.com/7055008/43570236-63cc6154-966c-11e8-9378-a1c54e87d360.png)

**When I click ' Show more'**

![default](https://user-images.githubusercontent.com/7055008/43570000-d8a3bbb8-966b-11e8-9f0f-99d286e102a0.png)

**When I click ' Show less', It can't be restored.**

![default](https://user-images.githubusercontent.com/7055008/43570804-d4e39eb0-966d-11e8-8bac-fd31d90dbf87.png)

Version: Firefox Quantum 61.0.1

**Comment by scottbommarito** [comment]
Hey @JaylanChen,

Can you tell me what package you're seeing this issue for? I have a feeling we've seen this before but I would like to confirm it's the same issue.

**Comment by JaylanChen** [comment]
Hey @scottbommarito 

When I use firefox, no matter which package, there will be an error.
such as [https://www.nuget.org/packages/Newtonsoft.Json/](https://www.nuget.org/packages/Newtonsoft.Json/)

![default](https://user-images.githubusercontent.com/7055008/43671690-4cab98ee-97d1-11e8-97e0-525b788c30dc.png)

**Comment by skofman1** [comment]
@JaylanChen , we tried to repro on Firefox Quantum 61.0.2 and couldn't repro. Please try updating your browser and let us know if it's still broken for you.

**Comment by JaylanChen** [comment]
@skofman1, I tried it again, it still here.

![default](https://user-images.githubusercontent.com/7055008/44969760-35059380-af81-11e8-8033-47b1cefdfd64.png)

When I remove the class ‘show’ of the element with the id of 'hidden-versions', it is normal.

test package url: https://www.nuget.org/packages/Newtonsoft.Json/

![default](https://user-images.githubusercontent.com/7055008/44969986-24a1e880-af82-11e8-9ba7-5cf7302d4eed.png)
![default](https://user-images.githubusercontent.com/7055008/44970009-384d4f00-af82-11e8-81a7-5ea00396a12a.png)

**Comment by ryuyu** [comment]
The block you are editing is added by the helper method at https://github.com/NuGet/NuGetGallery/blob/1b9875706fb5fda0313de0e7c235603946ef3856/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L89

Collapsed:
![image](https://user-images.githubusercontent.com/11051729/45119091-3f559800-b10f-11e8-8d46-c8c72a196bb2.png)

Expanded:
![image](https://user-images.githubusercontent.com/11051729/45119109-4aa8c380-b10f-11e8-8401-9c7c81c282e3.png)

You will notice that in neither screenshot here is the "show" class added to the line you are indicating.
Do you perhaps have an extension or something installed that is modifying this on the client side?

Note that I was able to reproduce the issue by adding the "show" class where you indicated.

**Comment by JaylanChen** [comment]
@ryuyu I'm sorry. The bug caused by a Firefox third-party extension.
