### ISSUE TITLE
Invalid cast exception in Header.cshtml

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6268]
timestamp [UTC] | 2018-08-05T04:57:59.8314587Z
-- | --
problemId | System.InvalidCastException at ASP._Page_Views_Shared_Gallery_Header_cshtml.Execute
type | System.InvalidCastException
assembly | App_Web_ci3hlftv, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
method | ASP._Page_Views_Shared_Gallery_Header_cshtml.Execute
outerType | System.InvalidCastException
outerMessage | Unable to cast object of type 'System.Boolean' to type 'System.String'.
outerAssembly | App_Web_ci3hlftv, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
outerMethod | ASP._Page_Views_Shared_Gallery_Header_cshtml.Execute
innermostType | System.InvalidCastException
innermostMessage | Unable to cast object of type 'System.Boolean' to type 'System.String'.

```
exceptions
| where problemId == "System.InvalidCastException at ASP._Page_Views_Shared_Gallery_Header_cshtml.Execute"
```

The code sets it as a boolean.

```csharp
TempData["ShowPasswordDeprecationWarning"] = true;
```

But it is read as a string.

```csharp
Convert.ToBoolean((string)TempData["ShowPasswordDeprecationWarning"])
```

I think this works most of the time because TempData is serialized as a string... not sure though. This exception could perhaps happen if `TempData` is read in the same request as it is set. 

From this line:
https://github.com/NuGet/NuGetGallery/blob/7f6ba8371c2aad0e6633c82fdb85c163eb58ed27/src/NuGetGallery/Views/Shared/Gallery/Header.cshtml#L4

**Comment by joelverhagen** [comment]
There are two instances of this in the last 24 hours.

**Comment by joelverhagen** [comment]
This problem also coincides with two exceptions found by this query:

```
exceptions
| where problemId == "System.ArgumentNullException at NuGetGallery.Authentication.AuthenticationService.Challenge"
```

**Comment by shishirx34** [comment]
`TempData` is serialized as `string` in the `cookie` and then `deserialized` during page rendering. Not sure why the `CastException` might happen, I don't think we ever `set` and `read` that value in the same request. The second exception might need investigation.

**Comment by joelverhagen** [comment]
Both exceptions have happens in the past two days. It seems that when exception A happens, exception B happens very soon after (perhaps even the same request).

**Comment by shishirx34** [comment]
Not sure how this happens, the tempdata object is supposed to be serialized, last happened two weeks ago. I think its simply better to use `.tostring()` and avoid the explicit cast altogether.
