### ISSUE TITLE
Delete local account nuget or unlink account with MSA.

### ISSUE THREAD

**Issue by serveryang** [NuGet/NuGetGallery#6271]
I have two local accounts. One is linked with MSA, but i want to unlink it or delete it, then i can bind another local account to MSA.

**Comment by ryuyu** [comment]
Please log in to the account you want to delete (MSA linked account) and submit a request to delete the account from https://www.nuget.org/account/delete
This will walk you through the process of transferring package ownerships and other cleanup.
Once you have deleted the account, you can link the MSA account to your other account.

Please note that if you delete an account, you will not be able to create an account with the same username as the deleted account.

**Comment by serveryang** [comment]
Thanks.
