### ISSUE TITLE
[Gallery] Consider showing the created timestamp on display package page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6301]
@loic-sharma commented on [Fri Aug 10 2018](https://github.com/NuGet/Engineering/issues/1633)

Repository signing a package causes its last updated timestamp to be updated to the current time. This will make outdated packages appear "recent". We could instead display the package's created date on the gallery.

---

@loic-sharma commented on [Mon Aug 13 2018](https://github.com/NuGet/Engineering/issues/1633#issuecomment-412577843)

/cc @anangaur

**Comment by anangaur** [comment]
The package metadata shouldn’t change with repo signing. It’s a regression.

**Comment by skofman1** [comment]
@anangaur , we checked, and it won't change.
However, we noticed that the text and data displayed can be improved:
Package are no longer editable, so "Last Updated" is not the correct text. My recommendation is "Created" or "Published"
![image](https://user-images.githubusercontent.com/16807822/44045331-12fa7288-9edd-11e8-8c5b-1aa8e4420a2c.png)

**Comment by anangaur** [comment]
Last updated still holds true from customers’ perspective. Repo signing update is an internal detail and should have no bearing in any customer scenario

**Comment by skofman1** [comment]
Repo signing won't change the timestamp. We checked.
