### ISSUE TITLE
Sign Search service dependencies

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6305]
@skofman1 commented on [Mon Jul 30 2018](https://github.com/NuGet/Engineering/issues/1577)

AppLocked started monitoring cloud services:
https://lens.msftcloudes.com/v2/#/dashboard/CodeIntegrityViolationDashboard?_g=(ws:b9ef86d0-4d61-4d97-9f69-1c709f5a1e63)&params=(filters:!((k:ServiceOid,v:'BBFD56CE-3FF1-4DFC-B51A-BBFE6A907563')))

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #1644](https://github.com/NuGet/Engineering/issues/1644) via [**ZenHub**](https://www.zenhub.com/)
