### ISSUE TITLE
Orchestrator completion of messages for packages that are not in the DB is dependent on configuration and not the service bus's dequeue count

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6313]
The orchestrator completes messages for packages that do not exist in the DB after a certain number of dequeues. This number of dequeues is set by the job's configuration.

The service bus itself has a configuration that specifies how many times a message can be dequeued before it is deadlettered.

If the service bus's configured max dequeue count is less than the orchestrator's max dequeues configuration, the orchestrator will dequeue a message for a package that doesn't exist and unintentionally deadletter it when it expects to receive it again.

The orchestrator should depend on the service bus's configuration instead.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #1682](https://github.com/NuGet/Engineering/issues/1682) via [**ZenHub**](https://www.zenhub.com/)
