### ISSUE TITLE
owner does not see the signature flag next to a signed package

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#6346]
see this package https://www.nuget.org/packages/VSIXBootstrapper/1.0.31

that version is signed but the owner can't see the visual indicator like we used to be able to:

![image](https://user-images.githubusercontent.com/16904420/44736374-e5682900-aaa3-11e8-9a5e-28d82ea40179.png)

**Comment by skofman1** [comment]
Icon will show up once all packages are revalidated.

**Comment by loic-sharma** [comment]
Fixed by repository signing. Verified that https://www.nuget.org/packages/VSIXBootstrapper/1.0.31 has the signature flag as expected.
