### ISSUE TITLE
Broken links on Terms page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6354]
Url: https://www.nuget.org/policies/terms
Broken link:  https://go.microsoft.com/fwlink/?linkid=141397

**Comment by karann-msft** [comment]
@skofman1 the Export Laws section in the terms need to be updated:

> Export Laws
> You must comply with all domestic and international export laws and regulations that apply to Your Content and/or Services, which include restrictions on destinations, end users, and end use. For further information on geographic and export restrictions, visit http://www.microsoft.com/exporting.
