### ISSUE TITLE
Nuget server Issue

### ISSUE THREAD

**Issue by hemkumarthiruvarangam** [NuGet/NuGetGallery#6373]
We are using Nuget Server v2.6.40619.9041 hosted in windows server. when we try to search for the packages from the Nuget feed with the browser we are able to search the content, While trying from Visual Studio 15 we are getting the below error.
[SharedComponents] The V2 feed at 'http://XXX/nuget/Packages/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net452'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '400 Bad Request'.

Could you please help to solve this issue.

Thanks
Hem

**Comment by skofman1** [comment]
@hemkumarthiruvarangam , apologies for the slow response. You can use fiddler to see the request Visual Studio sends to your service and see why that URL is not working. Please let me known if you need additional help.
