### ISSUE TITLE
Forgot Password form fails without clear message if two accounts have the same email address

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6387]
![image](https://user-images.githubusercontent.com/18014088/45114001-b6376480-b100-11e8-9c6d-567ad94e180e.png)

If two accounts have the same email address, the form gives an unclear message.

Ideally, no two accounts should have the same email address, but this message makes the issue harder to debug.

**Comment by skofman1** [comment]
@scottbommarito , if two accounts can have the same e-mail address we have a serious problem. This seems like a theoretical/local debugging scenario. Reopen if you disagree.
