### ISSUE TITLE
Deployment for Week of 9/10

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6388]
# Gallery
:warning: Run validation context's migrations! See [NuGet/ServerCommon#190](https://github.com/NuGet/ServerCommon/pull/190)

- [ ] DEV
    - [ ] USNC
    - [ ] USSC
- [x] INT
    - [x] USNC
    - [x] USSC
- [x] PROD
    - [x] USNC
    - [x] USSC

# Search Service
- [ ] DEV
    - [ ] USNC
    - [ ] USSC
    - [ ] EA
    - [ ] SEA
- [x] INT
    - [x] USNC
    - [x] USSC
- [x] PROD
    - [x] USNC
    - [x] USSC
    - [x] EA
    - [x] SEA

# Stats.ImportAzureCdnStatistics
- [x] DEV
- [x] INT
- [x] PROD

# Status Aggregator
- [x] DEV
- [x] INT
- [x] PROD

# Status Page
- [x] DEV
    - [x] USNC
    - [x] USSC
- [x] INT
    - [x] USNC
    - [x] USSC
- [x] PROD
    - [x] USNC
    - [x] USSC

**Comment by ryuyu** [comment]
Adding the following:
 - [ ] Feed2Catalog
 - [ ] Catalog2Dnx
 - [ ] Catalog2Registration
 - [ ] MonitoringProcessor

**Comment by cristinamanum** [comment]
The Stats.ImportAzureCdnStatistics was deployed for the build 41009, commit a5e602c .
