### ISSUE TITLE
Status traffic manager should fail if page is inaccessible

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6397]
Right now, the status traffic manager is tied to the json endpoint, which fails if the json file that powers the page is degraded. Unfortunately, by only monitoring the json endpoint, we are not failing over if the status page itself is inaccessible. We should create an endpoint that fails if the json is degraded or if the page is degraded.

**Comment by joelverhagen** [comment]
We should verify the case when both endpoints are unhealthy: make sure that the users still hit one of the degraded pages (probably by performance).

**Comment by joelverhagen** [comment]
Let's just monitoring the front page, the page that users hit.
