### ISSUE TITLE
Curated feeds owned by organizations cannot be managed

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6413]
When we added the organizations feature, we forgot to add curated feed management to the permissions service.

We should add curated feeds to the permissions service.

https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Controllers/CuratedFeedsController.cs#L36
https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Controllers/CuratedPackagesController.cs#L39
https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Controllers/CuratedPackagesController.cs#L67
https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Controllers/CuratedPackagesController.cs#L99
https://github.com/NuGet/NuGetGallery/blob/166d4c21134c11f0800aa7e0f0026a53cc583d48/src/NuGetGallery/Controllers/CuratedPackagesController.cs#L130

**Comment by skofman1** [comment]
We are removing curated feeds management, so this won't be necessary. //cc @joelverhagen
