### ISSUE TITLE
Error 404 when pushing package to server. Possibly configuration problem

### ISSUE THREAD

**Issue by IgorJanos** [NuGet/NuGetGallery#6416]
Hello,

I'm having problems getting Nuget Server to work correctly. For a long time I've been using a 2.10 Nuget server without any problems. Recently I wanted to update to a newer server version. I've managed to build the server web site without any problems - just like with the older 2.10 version. However I'm unable to push packages to the new server machine. The push request always fails with error 404.
(The package has only few KB, this is not the "package too big" problem).

The operating system is a clean Windows Server 2016 with IIS 10. I have set up an integrated .net4 application pool, configured api key, set up permissions for packages folder and adjusted maximum request sizes to allow for bigger packages - with no luck. I have tried deploying the original older 2.10 web application (copied the same binaries and configs) to the new 2016 server machine - also with no luck.

I am quite sure this is just a configuration problem, but I'm running out of ideas what might be wrong.
Can anyone hint me where to look? Perhaps some error log indicating the problem.

Many thanks,

Igor

**Comment by skofman1** [comment]
Hi @IgorJanos , sorry for the slow response. Can you share your configuration?
