### ISSUE TITLE
Non compliant package didn't fail validation 

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#6434]
https://www.nuget.org/packages/Microsoft.Graph.Calls/1.0.0.12

See author field

**Comment by loic-sharma** [comment]
Verified by creating a package with a project URL, a license URL, the copyright `© Microsoft Corporation. All rights reserved.`, and the author `Microsoft Communications Platform`. I subscriped to the `MicrosoftTeamSubscription` policy and uploaded this package to INT and verified that I got the following message:

>  The package is not compliant with metadata requirements for Microsoft packages on NuGet.org. Go to https://aka.ms/Microsoft-NuGet-Compliance for more information. Policy violations: The package metadata is missing required author 'Microsoft'.
