### ISSUE TITLE
[Azure Search] Implement NuGet search query parsing and mapping to Lucene query

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6456]
See related issues:
* Exact match fields: https://github.com/NuGet/NuGetGallery/issues/6920
* Id analyzer: https://github.com/NuGet/NuGetGallery/issues/6922
* Description analyzer: https://github.com/NuGet/NuGetGallery/issues/6921

**Comment by joelverhagen** [comment]
This is as far as I got:

https://github.com/NuGet/NuGet.Services.Metadata/tree/jver-pq

**Comment by loic-sharma** [comment]
* Exact matches using [`KeywordAnalyzer`](https://lucene.apache.org/core/4_10_3/analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html), update index
  * [ ] Add exact match packageId [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/azuresearch/src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs#L44)
  * [ ] Add exact match owners [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/azuresearch/src/NuGet.Services.AzureSearch/Models/SearchDocument.cs#L32)
  * [ ] Add normalized version [here](https://github.com/NuGet/NuGet.Services.Metadata/blob/azuresearch/src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs#L39)
