### ISSUE TITLE
[Azure Search] Add request duration monitoring for search service

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6463]
* [ ] Update the deployment template [NuGetDeployment#958](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/958?_a=files)
* [ ] Update Ev2 deployment to shutdown the staging slot after VIP swap
* [ ] Add a [OneNote page](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Monitoring.one%7C848EB03A-2183-4FA1-8EA1-E7FE0325BBA5%2FAzure%20App%20Service%7CEB41251B-AC41-4AB7-86DB-70130740170B%2F%29onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Monitoring.one#Azure%20App%20Service&section-id={848EB03A-2183-4FA1-8EA1-E7FE0325BBA5}&page-id={EB41251B-AC41-4AB7-86DB-70130740170B}&end) for installing Geneva on Azure App Service 
* [ ] Go to Geneva office hours and ask (contact George Johnston geojohn):
  * Can we use the machine name for the identity? Yes we can
  * Can we distinguish between production/staging slots?
  * Why is Request Duration Time always 0 on App Service?
* [x] Add `By-Environment-Region-Role-RoleInstance` and  `By-Environment-Region-Role` pre-aggregate for all needed metrics
  * [x] `\ASP.NET\Request Excution Time`
  * [x] `\.NET CLR Exceptions (w3wp)\# of Exceps Thrown / sec`
  * [x] `ASP.NET Applications (__Total__)\Error Total/Sec`
  * [x] `ASP.NET Applications\Errors Unhandled During Execution/sec` :warning: Missing today
* [ ] DEV
  * [x] Create Geneva config
  * [ ] Deploy latest service
  * [x] Export AI to Geneva
  * [ ] Add Geneva Monitors
* [ ] INT
* [ ] PROD

Options:

1. AI alerts??? I've seen automatic ones from this before
1. Export AI to Geneva.

https://stackoverflow.microsoft.com/questions/153648/perfcounter-broken-on-azure-app-service-using-geneva

**Comment by loic-sharma** [comment]
typeperf.exe maybe can run this on console

**Comment by loic-sharma** [comment]
# App Insights Perf Counters

Azure App Service Web App perf counters documentation: https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#performance-counters-for-applications-running-in-azure-web-apps
List of supported perf counters as (kudu wiki): https://github.com/projectkudu/kudu/wiki/Perf-Counters-exposed-as-environment-variables
Full list of supported perf counters (code): https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/PerformanceCollector/Perf.Shared/Implementation/WebAppPerformanceCollector/CounterFactory.cs#L16

# Geneva Derived Events

Send metric using a derived event: https://genevamondocs.azurewebsites.net/collect/advanced/logstometrics.html#setmdmmeasuremetric

**Comment by loic-sharma** [comment]
https://icm.ad.msft.net/imp/v3/incidents/details/132054792/home
