### ISSUE TITLE
Better Gallery Search for 127,000+ Packages

### ISSUE THREAD

**Issue by residentx10** [NuGet/NuGetGallery#6474]
Can you put a better search/advance search interface on this tool? I need to see the all packages overall faster somehow. I can't spend time navigating 20 packages per pages.

**Comment by skofman1** [comment]
Hi @residentx10 , we have an issue here tracking search results improvements: https://github.com/NuGet/NuGetGallery/issues/4124

Can you share your specific scenario and requirements?
