### ISSUE TITLE
Cannot login with microsoft account

### ISSUE THREAD

**Issue by SebastianJust** [NuGet/NuGetGallery#6488]
Hello,

I cannot login with my microsoft account. It says error 500.

**Comment by brendonthiede** [comment]
It says "We are currently degraded." here: https://status.nuget.org/
I have ARM templates that rely on nuget.org to install extensions, and I ran the deployment from our build server at least a dozen times before it worked in one environment, and then it failed in the next.  I'm not even sure if I can configure an alternate source.

**Comment by SebastianJust** [comment]
It's kind of a big issue, I think.

**Comment by brendonthiede** [comment]
For me at least, things seem to be back to normal now

**Comment by SebastianJust** [comment]
For me it's still an issue

**Comment by skofman1** [comment]
@SebastianJust , apologies for the slow response. Is this still an issue?
