### ISSUE TITLE
[Orchestrator] Fix parallel package validation concurrency issues

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6515]
# Problem
There are two known concurrency problems:

1. If the same package is uploaded multiple times, it is possible that multiple validation sets will be created. This will cause the Orchestrator to validate the same package multiple times in parallel. Only one of these validation sets' package will be made available, all other validation sets will dead-letter (the package's copy will fail as the destination's access condition will fail).
2. If the Orchestrator has message duplication for a single validation set, only one of these messages will be able to make the package available. All other messages will dead-letter (the package's copy will fail as the destination's access condition will fail).

The second issue seems to be happening more frequently due to the revalidation job.

# Solution

The proposed solution is to "cancel" a validation if the destination blob changes after the validation began:

1. Whenever the Orchestrator receives a message for a package whose validation set's [`PackageETag`](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Validation/Entities/PackageValidationSet.cs#L63) indicates the package shouldn't be available (ie the `PackageETag` is `null` or `*`), the Orchestrator will check the package's state according to the Gallery DB. If the package is available, the validation set's package will be deleted and the Orchestrator's message will be consumed.
2. Whenever the Orchestrator decides that a validation's package should be made available, the Orchestrator will first check that the validation set's `PackageETag` matches the packages container's ETag. If these ETags don't match, the validation set's package will be deleted and the Orchestrator message will be consumed.

/cc @agr @joelverhagen

**Comment by cristinamanum** [comment]
Packages that dead letter from this issue
NTK.GPU/2.0.0-rc1     
NTK.GPU/2.0.0-rc3 
CNTK.GPU/2.5.0-rc0.dev20180310 
CNTK.GPU/2.5.0  
CNTK.GPU/2.5.0-rc0.dev20180227 
CNTK.GPU/2.5.0-rc0.dev20180312 
CNTK.GPU/2.3.1 
CNTK.GPU/2.3.0 
CNTK.GPU/2.6.0-rc0.dev20180323 
CNTK.GPU/2.6.0-rc0.dev20180326  
CNTK.GPU/2.2.0 
CNTK.GPU/2.6.0-rc0.dev20180429 
CNTK.GPU/2.5.0-rc0.dev20180317 
CNTK.GPU/2.6.0-rc0.dev20180331 
CNTK.GPU/2.5.0-rc0.dev20180316 
CNTK.GPU/2.6.0-rc0.dev20180413 
CNTK.GPU/2.5.0-rc0.dev20180303 
CyberjusticeLab.Kernel.ServiceContracts/3.3.0-beta0001 
CyberjusticeLab.Kernel.ServiceClient/3.3.0-beta0001
CyberjusticeLab.Kernel.Federation/3.3.0-beta0001
runtime.debian.8-x64.Microsoft.NETCore.TestHost/1.0.0-rc2-24027 
runtime.debian.8-x64.Microsoft.NETCore.TestHost/1.1.9 
Microsoft.Owin.Security.Facebook.es/4.0.0-preview1 
Microsoft.Owin.Security.Facebook.es/2.0.0-rc1 
SAEA.MessageSocket/2.2.0
![image](https://user-images.githubusercontent.com/16580006/46841755-b7525600-cd7e-11e8-981f-cf53430a1ff2.png)

**Comment by cristinamanum** [comment]
AI trace:
Before calling FetchAttributesAsync(), the source blob 'validation-sets/***/***.nupkg' does not exist.

**Comment by loic-sharma** [comment]
The `catalog2packagefixup` job has been run on DEV, INT, and PROD. The next step is to verify that Orchestrator messages deadletter less often.

**Comment by joelverhagen** [comment]
All of these happened between:

```
| where timestamp > todatetime("2018-10-29")
| where timestamp < todatetime("2018-11-01")
```

## System.TimeoutException

developerforce.force 0.2.0
- ValidationSetId: 1f70cb4d-8494-4c60-8add-9e326e968965
- Exception CallGuid: 651b3094-ab40-4e62-b87b-c167ddd62031
- NO OBSERVED MESSAGE DUPLICATION

rainbow 1.3.0-beta01
- ValidationSetId: fffc1c40-7352-4809-a04b-f7d919590ff0
- Exception CallGuid: 116351de-7f78-4db8-8deb-c621b001c6ca
- HAD MESSAGE DUPLICATION

microsoft.teamfoundation.publishtestresults 16.142.0-preview
- ValidationSetId: 77325c46-8822-4240-ac72-ad652106779c	
- Exception CallGuid: f5795a9f-25f3-4abe-94a9-51a2a9463aec
- HAD MESSAGE DUPLICATION

## Microsoft.ServiceBus.Messaging.MessageLockLostException

intellitect.testtools.console 1.0.0-ci-20181030-214503
- Exception CallGuid: 83444f25-ea8a-4d91-860e-bc08c674bcf9
- ValidationSetId: 41256545-ccc4-4940-bb30-d9179c7bdf21
- HAD MESSAGE DUPLICATION

## No exception

This is a very funky case I have contact Service Bus discussion alias about.

orc.controls 3.1.0-alpha0070
- ValidationSetId: 63ce26f8-a2bc-48d8-aadd-38542334b6e2
- All CallGuid:
  - 041f73d3-a879-4f81-a13e-e4dfd4018903
  - 047e5dbb-7585-4248-b561-79e8e27c0bec
  - 199618fb-ea37-406d-b0d2-cc70bdca483f
  - 1baddd89-b5d8-499f-b9a2-cef046fd383b
  - 232b4538-1671-4603-b3e2-a4c01009db19
  - 2aeb3e1b-40f2-48a0-872c-14d6d7f2aaac
  - 2dcd6282-4292-472a-9097-23005256b376
  - 6848d660-5435-44c5-89c2-bf025022ef46
  - 8d49e023-12f0-4b56-a819-07dd69a40a16
  - 9a146ede-0b15-4ae5-96a3-bd0ffc257485
  - 9b2a3910-5926-4eff-b3f3-e5e28c4013f8
  - 9fa8d414-5ff9-49cf-aacb-0ec8edc0e912
  - a990a1af-cf5c-41f9-8b05-eb90b9139517
  - ab381b58-a65d-4d09-b5e2-ebc28cdfc956
  - b4f8bf9d-4e60-4caf-9c66-c074fffeea1f
  - c98ecc45-883b-4253-8edc-31cfb8b6b8ec
  - ccf9fa69-d216-402a-ab9d-9100ea1971bd
  - dc403b3b-0a61-4d8b-9551-8935b501bbaf
  - dfca139b-aa62-4770-99b4-a4e6340ff0cf
  - e189cda5-6192-471e-8511-ee3141cb6d94
  - ec46aefb-d531-4cfd-bf0f-1668aea39b9c
  - f2bd37ab-422e-496e-9607-8e7a12085df8
  - f2fc9a1f-2d99-4b69-a2ab-2de2ebdc2c3b
  - f4f88b36-024a-4154-9974-c04d2baa02e8
- NO OBSERVED MESSAGE DUPLICATION

sharpbotcore 1.0.0-alpha10
- ValidationSetId: e049e86f-9f71-4988-bc85-86f233da93f7
- All CallGuid:
  - 0cf83a1d-7173-410a-8bca-2c7a926a183c
  - 0db4e51f-2144-4fdb-ba2a-90c3fad1629f
  - 1968f131-138a-4468-b045-1bc5738fb66a
  - 252f08a3-656a-4864-b323-c9fad026c908
  - 2a6e7647-db03-4aa8-9004-f16bed05be65
  - 2ed66dd5-b7d7-4992-a199-5462b16d3880
  - 3fee780c-7270-4545-a5b4-776c036f5175
  - 411ea5eb-0080-41b2-bb6d-bbe60af3aeac
  - 41820a95-0c72-458c-a370-0aa057018a11
  - 44993bc6-4d60-46be-8c85-8e622a280171
  - 47486f0d-1cfc-44f6-86ff-e72e4b47c57c
  - 56050641-1037-4d5e-ab7a-a3bfe784de5a
  - 768bdc31-bb96-42d8-be5e-562083954ac5
  - 7ee69f96-4d75-4333-b9c2-349a8e305f32
  - 864b571f-43ab-452d-b714-8de13365e94b
  - 87a70454-fb9d-4f0a-8e3b-a5233f2a9aa2
  - 96a3b622-7de9-4137-821a-23367d3e072b
  - 9d30a4c0-0097-4df4-b9fb-5dec7db502bc
  - 9fbb0e5c-1b9d-46c0-b94d-b11b74496320
  - a4d17410-12bf-4c78-bb64-3a80d8f9f9bd
  - ab8f9c3c-6301-4638-9bc6-7681cd7b9753
  - b88268aa-479e-4356-994b-ee490ebee7d2
  - bb77c116-4e60-4d77-b680-de91a3dca766
  - c9345308-b4e4-42fc-81ad-fdd3c6769e29
  - cd417331-fb52-455e-9d97-28a724f8d0ae
  - cd59717a-556c-4ff8-9935-569b6200d608
  - d86bc351-d752-4df6-9fd4-9000137637a8
  - e0d621e1-e30b-4756-b707-f7863153a77d
  - e6157478-942e-4aca-ae0d-d6c9314574ef
- HAD MESSAGE DUPLICATION

**Comment by joelverhagen** [comment]
This happened 34 times in my on-call week (Friday evening to Friday evening).
