### ISSUE TITLE
[Deployment] Week of 10/8/2018

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6521]
# Deployment 2018-10-08

**Status**: Planned

**Planned production date**:  2018-10-10

Repo | Service | Commit | Build | INT | PROD|PROD USSC | Asia
--- | --- | --- | --- | --- | --- | --- | ---
Services.Metadata | EndpointMonitoring | [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd) | 41836| <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A | N/A
Services.Metadata | feed2catalog | [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd)| 41836-2 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A | N/A
Services.Metadata | catalog2dnx| [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd) | 41836 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A | <ul><li>[x] </li></ul>
Services.Metadata | catalog2registration | [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd)| 41836| <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | N/A | <ul><li>[x] </li></ul>
Services.Metadata | catalog2lucene | [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd)| 41836-2 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>  | <ul><li>[x] </li></ul>
Services.Metadata | Search service | [2ab0c43](https://github.com/NuGet/NuGet.Services.Metadata/commit/2ab0c43d219b23337e6397b4d379cbc92920a9dd) | 2093751 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Internal.Jobs | ScanAndSign submitter(aka Jobs - Validation - ESRP submitter) | 3b234f3 | 41989 | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> |  N/A | N/A

Includes: https://github.com/NuGet/NuGet.Services.Metadata/pull/363
-	83d5a388 Migrate projects to use PackageReference
-	8b0224cc Add configuration to enable signature validation

**Comment by cristinamanum** [comment]
Search service build 
https://devdiv.visualstudio.com/DevDiv/AI%20and%20ML%20Tools/_build/results?buildId=2093751&view=logs
Warm : 4.0.2093751-master
