### ISSUE TITLE
[Licenses] E2E tests for valid combinations of license settings

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#6535]
All valid combinations of licenseUrl/licenseExpression/licenseFile settings should be covered by E2E tests.

**Comment by agr** [comment]
Test should verify among other things that license URLs generated by catalog2registration and catalog2lucene point to the right location in Gallery.

**Comment by zhhyu** [comment]
1. Need to add E2E tests for Lucene pipeline;
2. Update configuration file.
