### ISSUE TITLE
api.nuget.org IP Blocked in DoD

### ISSUE THREAD

**Issue by mjhixson** [NuGet/NuGetGallery#6550]
The current api.nuget.org IP (72.21.81.200) is being blocked by DISA on US DoD networks.  We requested it be unblocked, but the request was denied due to "evidence of malicious activity on the site".  Any information on this or a possible alternate IP we can use to pull down packages?

**Comment by cristinamanum** [comment]
We are working with our CDN provider to find solutions for this issue.

**Comment by mjhixson** [comment]
Great, thank you!

**Comment by cristinamanum** [comment]
Hi  @mjhixson, our CDN provider is asking for additional details. Can you provide more details for the reason of this IP being blocked? What is the evidence of malicious activity on this site?

**Comment by mjhixson** [comment]
Unfortunately that is all the info we were given in response to our request to have it unblocked.  I will try and get more info, but they usually aren't very forthcoming with specific details.

**Comment by mjhixson** [comment]
Just to follow up, I was unable to get any more information on the evidence they have with regards to the malicious activity.  They consider that info classified and won't divulge it.

**Comment by cristinamanum** [comment]
Hi @mjhixson, we are still working with our CDN provider to find best solution of solving this issue. 
Would you mind sending an email to support@nuget.org with this issue? It will help us track better the issue. 
Is there any way for us to reach your support team? We hope that we can work together to understand the impact and find the best solution.

**Comment by mjhixson** [comment]
I have followed up with an email as requested.  I also provided some additional contact info in that email that may be able to provide assistance.

**Comment by cristinamanum** [comment]
Issue was resolved.
