### ISSUE TITLE
NuGet client version report ignore 'NuGet VS VSIX' user agents

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6551]
This report has skewed results because 4.6.0+ VSIX downloads are not included.

![image](https://user-images.githubusercontent.com/94054/46818095-3de24580-cd35-11e8-85fa-ea379f9adba5.png)
https://www.nuget.org/stats

Today, user agents starting with `NuGet VS VSIX/` are categorized in the stats DB with an empty string category.

ClientName | Major | Minor | Patch | ClientVersion | ClientCategory
-- | -- | -- | -- | -- | --
NuGet VS VSIX | 5 | 0 | 0 | 5.0.0 |  
NuGet VS VSIX | 4 | 9 | 0 | 4.9.0 |  
NuGet VS VSIX | 4 | 8 | 1 | 4.8.1 |  
NuGet VS VSIX | 4 | 8 | 0 | 4.8.0 |  
NuGet VS VSIX | 4 | 7 | 1 | 4.7.1 |  
NuGet VS VSIX | 4 | 7 | 0 | 4.7.0 |  
NuGet VS VSIX | 4 | 6 | 2 | 4.6.2 |  
NuGet VS VSIX | 4 | 6 | 1 | 4.6.1 |  
NuGet VS VSIX | 4 | 6 | 0 | 4.6.0 |  

Note that for Newtonsoft.Json, this client name is the 3rd most popular:
https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=ClientName

We are excluding this from the client version report:
https://github.com/NuGet/NuGet.Jobs/blob/7cf33fcf128330b407bd5b2f2242d260fa0c2963/src/Stats.Warehouse/Programmability/Stored%20Procedures/dbo.DownloadReportNuGetClientVersion.sql#L25

I think the fix here is to put the proper client category of "NuGet". Since PR https://github.com/NuGet/NuGet.Client/pull/1967 (fixing issue https://github.com/NuGet/Home/issues/5853), the VSIX has used this new user agent.

We should fix this so the client version report is not skewed.

**Comment by xavierdecoster** [comment]
Verified in PROD:

```
ClientName	Major	Minor	Patch	ClientVersion	ClientCategory
NuGet VS VSIX	5	0	0	5.0.0		NuGet
NuGet VS VSIX	4	9	3	4.9.3		NuGet
NuGet VS VSIX	4	9	2	4.9.2		NuGet
NuGet VS VSIX	4	9	1	4.9.1		NuGet
NuGet VS VSIX	4	9	0	4.9.0		NuGet
NuGet VS VSIX	4	8	1	4.8.1		NuGet
NuGet VS VSIX	4	8	0	4.8.0		NuGet
NuGet VS VSIX	4	7	1	4.7.1		NuGet
NuGet VS VSIX	4	7	0	4.7.0		NuGet
NuGet VS VSIX	4	6	2	4.6.2		NuGet
NuGet VS VSIX	4	6	1	4.6.1		NuGet
NuGet VS VSIX	4	6	0	4.6.0		NuGet
```
