### ISSUE TITLE
Cannot list account packages

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/NuGetGallery#6556]
Packages are listed for other frameworks fine 
e.g. for psake we have https://www.nuget.org/packages/psake
but when I try the same for [expand](https://www.nuget.org/profiles/expand) it fails
https://www.nuget.org/packages/expand

**Comment by skofman1** [comment]
@apobekiaris , 
 https://www.nuget.org/packages/psake points to a package called 'psake'
since there's no package called 'expand' a similar link will not work.
