### ISSUE TITLE
Suggestion: Improve documentation around Gallery.FileStorageDirectory

### ISSUE THREAD

**Issue by stevenaw** [NuGet/NuGetGallery#6557]
I've recently been trying to setup my own gallery using FileStorage. We had a requirement to store the `*.nupkg` files separate from the application itself (outside off App_Data). It took me a little bit, but I eventually figured out that the app setting `Gallery.FileStorageDirectory` controls this. I'm wondering if it would be possible to improve documentation of this?

I'm not sure what that would look like. I notice most settings already exist in the web.config file, but this one isn't. Maybe it could be added (but commented out, with a desccription)?

**Comment by loic-sharma** [comment]
That seems like a good idea! It seems we should make `Gallery.FileStorageDirectory`'s default value of  `~/App_Data/Files` explicit in the web.config file. If you have the time, feel free to send us a pull request and we'll take look.

**Comment by stevenaw** [comment]
Sure! I can start on this now

**Comment by shishirx34** [comment]
@stevenaw - your change has been merged. Thank you for your contribution.
