### ISSUE TITLE
Nit Fixes for symbols upload

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#6559]
- [x] Currently you will replace the symbols upon reuploading the symbols package. may be warn the users of the action they are taking
- [x] specify .snupkg in the upload box(to differentiate with symbols.nupkg, may be check that extension server side?)
- [x] Delete symbols page, default the drop down
- [x] remove title/other metadata from upload page?

**Comment by shishirx34** [comment]
@diverdan92 - thoughts on the feedback on UI from the team during the demo meeting?

**Comment by diverdan92** [comment]
@shishirx34 
We should warn about replacing symbols - agree.
For the 2nd feedback - we are reusing the same upload box for both, right? We should say both are supported.
Not sure what the third one means? Default the reason drop down?
Sure - probably doesn't matter since it isn't visible anywhere.

**Comment by shishirx34** [comment]
Oh no, not for second we do not support uploading a `<id>.symbols.nupkg` only `.nupkg` or `.snupkg` in gallery.
the third one was for delete page we have a drop down enabled to actually delete the symbols.

**Comment by diverdan92** [comment]
I see. Yes - we should specify .nupkg or .snupkg to make sure there is no confusion about symbols.nupkg.
And I see - yes we can default to actually delete the symbols if they try and delete.
