### ISSUE TITLE
Gallery Deployment 2018-10-22

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#6567]
# Deployment 2018-10-22

**Planned production date**:  2018-10-2

Repo | Service | INT | PROD|Prod-USSC
--- | --- | --- | ---|----
NuGetGallery | NuGetGallery | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>

Build: ~~**2125882-master**~~ master-2143260
- Deployment=~~57c8f4c6~~ abb2acca
- Gallery=~~410c949c~~ e1ac2b5
- Shims=b71398b

**Comment by shishirx34** [comment]
I will be redeploying the changes with Hotfix from @zhhyu  and @agr
