### ISSUE TITLE
Windows Server hangs after opening http://serveraddress/nuget/Packages

### ISSUE THREAD

**Issue by PiterGoCompany** [NuGet/NuGetGallery#6568]
I have very strange problem with Nuget.Server (3.1.2.0) which is deployed on Windows Server 2016. Every time when someone is opening address http://myserveraddress/nuget/Packages (in the web browser or Visual Studio Packages Manager) server hangs.  Resource Monitor on the serwer doesn't show any unusual vales but it's hard to connect with Remove Desktop. After connecting (tens of seconds) it's hard to do anything. Problem disappears after restarting W3SVC service. I've 66 packages (18 MB, ~1300 file and ~530 folders).

**Comment by agr** [comment]
Random thoughts: such hangs may happen when there are issues with the disk. Can you run error checking on all disks on your server to make sure there are no errors? It's also might be worth checking the system event log for other issues that might affect the performance.

**Comment by PiterGoCompany** [comment]
@agr event log was clean and disks are OK. Problem has disappeared after moving nuget server to the default IIS 'wwwroot' folder.

**Comment by agr** [comment]
Could you please provide some details about your initial setup, so we could try to reproduce the behavior?

**Comment by PiterGoCompany** [comment]
Nuget.Server and Packages folders were on one of our server (Windows Server 2016) drives in the same parent folder (eg. d:\WebApplications). IUSR, IIS_IUSRS and DefaultAppPool users had full access to the folders. There were no problems with the same configuration on my local machine (Windows 10) and our old server (Windows Server 2008).
