### ISSUE TITLE
[Orchestrator] Cleaning a cancelled validation set's package may cause deadlettering

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6572]
The Orchestrator cancels a validation set if the destination blob has been modified since the validation set was created (this behavior was introduced by: https://github.com/NuGet/NuGet.Jobs/pull/587). This cancelled validation set's package is deleted.

# Problem

Say a validation set that has passed all validations and has two messages inflight due to message duplication:

1. Message 1 copies validation set's package to public destination
2. Message 1 throws an exception after the copy (say sending the "package validated" email throws)
3. Message 2 attempts to copy the validation set's package to the public destination
  3a. The Orchestrator checks if the validation set's package has an MD5 hash on its blob properties (if there is a hash, the Ocherstrator no-op the copy if the destination blob's MD5 hash matches). Let's say that this blob is missing the MD5 hash, so the Orchestrator attempts the copy
  3b. Orchestrator builds Blob Storage access conditions to ensure the destination package has not been modified since the validation set was created
  3c. Orchestrator attempts to copy using the access conditions from step 3b
  3d. The copy fails as the access conditions aren't met
4. Message 2 handles the exception from Azure Blob Storage and marks the current message for cancellation
5. Message 2 deletes the validation set's package
6. Message 2 is consumed
7. Message 1 wakes up and attempts to copy the validation set's package to the public destination. The validation set's package no longer exists (it was deleted by step 5), so this message deadletters.

Could we fix this by just not deleting a cancelled validation set's package? Nope:

1. Same as before
2. Same as before
3. Same as before
4. Same as before
5. Message 2 is consumed (without deleting the validation set's package)
6. Message 1 wakes up and attempts to copy the validation set's package to the public destination
  6a. The blob is missing the MD5 hash (see 3a in previous example), so the Orchestrator attempts the copy
  6b. Orchestrator builds Blob Storage access conditions to ensure the hdestination package has not been modified since the validation set was created
  6c. Orchestrator attempts to copy using the access conditions from step 6b
  6d. The copy fails as the access conditions aren't met (the destination blob was modified by step 1)
7. Message 1 handles the exception from Azure Blob Storage and marks the current message for cancellation
8. Message 1 is consumed (without deleting the validation set's package).

⚠️ In this scenario, the public package has been modified **but the database hasn't been updated**! Also, both messages have been consumed without deadlettering!

# Possible solutions

We could:

* Every time we make a validation set's package available, we could first ensure it has a MD5 hash. This allows the Orchestrator to detect that the validation set's package has already been made available, and will report the copy as successful even though the destination's ETag has changed after the validation set was created. This could be done as part of: https://github.com/NuGet/NuGetGallery/issues/6285
* Consider making a service that attempts to clean up deadlettered validations. It can revalidate the package, and if the revalidation passes, consume the dead lettered message.
* TODO: Think of more solutions?

**Comment by loic-sharma** [comment]
FYI, if anyone runs into this problem today they should queue up a revalidation of the affected package. If the revalidation passes, the deadlettered message should be consumed.

**Comment by loic-sharma** [comment]
Definitely add monitoring for hash of feed, v2, v3

**Comment by skofman1** [comment]
This is not a problem today.
