### ISSUE TITLE
Make the signing rosette/ribbon viewable to any user

### ISSUE THREAD

**Issue by blowdart** [NuGet/NuGetGallery#6574]
Currently the rosette/ribbon that indicates an author signed package is only viewable by the package author.

It should be viewable to everyone, even anonymous users.

**Comment by loic-sharma** [comment]
/cc @rido-min @dtivel 

AFAIK, this was done to avoid potential controversies around authors that cannot acquire a trusted codesigning certificate.

**Comment by skofman1** [comment]
@rido-min , @dtivel , ping
