### ISSUE TITLE
Next page URL on NuGet.Server 2.x does not contain semVerLevel=2.0.0

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6585]
From https://github.com/NuGet/Home/issues/6625#issuecomment-431113226:

> @joelverhagen could it be that paging is causing the problem? Even though the initial request has the `semVerLevel` query parm, the URL in the `link rel="next" href` element at the end of the feed *does not*.
> 
> ```XML
> <link rel="next" href="http://example.com/nuget/FindPackagesById?id='MyPackage'&amp;$skiptoken='MyPackage','1.2.3-8-g6b82829'" />
> ```
> 
> Perhaps the first page will contain SemVer 2.0.0 versioned package, but not subsequent pages? That would also explain why the `semVerLevel` query parm worked in [this issue](https://github.com/NuGet/NuGetGallery/issues/5528) as it was a dummy package and there were not multiple pages in the feed.

When using NuGet.Server 2.14.2, the next URL on `FindPackagesById()` (probably the other endpoints too) does not have the `semVerLevel=2.0.0` query parameter even if the initial page was requested with it.

This issue does not affect NuGet.Server 3.1.2.

**Comment by skofman1** [comment]
I recommend customers that encounter this issue to migrate to NuGet.Server 3.1.2. 
If this poses a problem, please reach out to us and we will reevaluate.

**Comment by Rajkumar-Uppala** [comment]
Hello there,
Currently i am using VS 2017 Version 15.9.3 and Nuget Package manager 4.6.0

When i am trying to use the 'PackageReference' feature, I am experiencing an issue as below when trying to restore NuGet Packages.

Failed to retrieve information about 'cnLogger' from remote source 'http://londbcntfs/nuget/FindPackagesById()?id='cnLogger'&semVerLevel=2.0.0'.
Response status code does not indicate success: 404 (Not Found).

But if we restore them via old style (packages.config), we are able to retrieve them.

Please let me know if i can provide you any other details to validate this.

Could you please guide me, what might went wrong .

Thanks ,
Rajkumar.

**Comment by skofman1** [comment]
@Rajkumar-Uppala , which version of NuGet.Server are you using to host http://londbcntfs ?
