### ISSUE TITLE
Certain strange requests result in HTTP 500

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6601]
This can trigger "failed request" alert that we have set up in Application Insights.

Examples:
```
https://www.nuget.org/api/v2/lazy/>=1.0.5 <1.1
https://www.nuget.org/api/v2/mysql/*
https://www.nuget.org/api/v2/mysql-pool/*
https://www.nuget.org/api/v2/comb/*
https://www.nuget.org/api/v2/express/*
https://www.nuget.org/api/v2/hive-cache/*
https://www.nuget.org/api/v2/mysql/*
https://www.nuget.org/api/v2/comb/>=0.0.2
https://www.nuget.org/api/v2/hive-cache/*
https://www.nuget.org/api/v2/mysql/*
```

All of these result in HTTP 500 by redirecting to the 500 error page, e.g.
```
https://www.nuget.org/Errors/500?aspxerrorpath=/api/v2/lazy/%3E=1.0.5%20%3C1.1
```

These should probably be 404s.

**Comment by joelverhagen** [comment]
The fix caused https://github.com/NuGet/NuGetGallery/issues/6655. Re-opening.

Next time this is fixed, we should add a functional test that verifies reason phrases come through for API push.

**Comment by agr** [comment]
Some additional investigation as we were getting similar 500s (not from OData).
Example of the request that causes 500:
https://www.nuget.org/.nuGetV3/feed.json:properties

when `customErrors` are off we get a proper 400 for it:

> A potentially dangerous Request.Path value was detected from the client (:).

We have a bit overzealous `customErrors` settings:

https://github.com/NuGet/NuGetGallery/blob/7a0ed71f4c1f608b01d0947132123197b9bea839/src/NuGetGallery/Web.config#L323-L328

Which grab all errors and transform them into 500s.

**Comment by agr** [comment]
Some details on what exactly happens in different cases:

(ran against localhost with `customErrors mode="On"`)

| Method returns/throws | Class | Result observed from outside |
|-|-|-|
| `return new HttpStatusCodeWithBodyResult(400);` | `ApiController` | 400 |
| `throw new HttpException(400)` | `ApiController` | 500 |
| `throw new HttpResponseException(400)` | `ApiController` | 500 |
| `return new HttpStatusCodeWithBodyResult(500);` | `ApiController` | 500 |
| `throw new HttpException(500)` | `ApiController` | 500 |
| `throw new HttpResponseException(500)` | `ApiController` | 500 |
| `return new HttpStatusCodeWithBodyResult(400);` | `PagesController` | 400 |
| `throw new HttpException(400)` | `PagesController` | 302 => `Errors/500` |
| `throw new HttpResponseException(400)` | `PagesController` | 500 |
| `return new HttpStatusCodeWithBodyResult(500);` | `PagesController` | 500 |
| `throw new HttpException(500)` | `PagesController` | 500 |
| `throw new HttpResponseException(500)` | `PagesController` | 500 |

**Comment by agr** [comment]
against dev.nugettest.org:

```
fail400 => BadRequest https://dev.nugettest.org/fail400
ex400 => 302 /Errors/500?aspxerrorpath=/ex400
aspex400 => InternalServerError https://dev.nugettest.org/aspex400
fail500 => InternalServerError https://dev.nugettest.org/fail500
ex500 => InternalServerError https://dev.nugettest.org/ex500
aspex500 => InternalServerError https://dev.nugettest.org/aspex500
api/fail400 => BadRequest https://dev.nugettest.org/api/fail400
api/ex400 => InternalServerError https://dev.nugettest.org/api/ex400
api/aspex400 => InternalServerError https://dev.nugettest.org/api/aspex400
api/fail500 => InternalServerError https://dev.nugettest.org/api/fail500
api/ex500 => InternalServerError https://dev.nugettest.org/api/ex500
api/aspex500 => InternalServerError https://dev.nugettest.org/api/aspex500
```

**Comment by loic-sharma** [comment]
(From https://github.com/NuGet/Engineering/issues/2323). It seems Artifactory is causing an elevated amount of internal errors. The URL patterns are things like:

* https://www.nuget.org/.nuGetV3/feed.json:properties
* https://www.nuget.org/System.Reflection.DispatchProxy.4.4.0.nupkg:properties
