### ISSUE TITLE
Inconsistent "package indexing" messaging between regular and symbols packages

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#6609]
![image](https://user-images.githubusercontent.com/102933/47751642-98ddcd00-dc4f-11e8-9e0a-09d1277cfb33.png)
Top message has bold test, while bottom does not. Should it be consistent?

**Comment by shishirx34** [comment]
@diverdan92 - thoughts?

**Comment by diverdan92** [comment]
Let's make **The symbols for this package have not been indexed yet.** bold as well.
