### ISSUE TITLE
The Revalidate Symbols link should not be visible with packages without symbols

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6620]
https://dev.nugettest.org/packages/jver.bugbash.dependency/

This package has no symbols.

![image](https://user-images.githubusercontent.com/94054/47887151-23166480-ddfb-11e8-9b17-ada24b1b13d3.png)

**Comment by shishirx34** [comment]
https://github.com/NuGet/NuGetGallery/issues/6615 sorry @joelverhagen
