### ISSUE TITLE
Preview of new nuget package. Incorrect display of multiline description and release note

### ISSUE THREAD

**Issue by dmitry-lipetsk** [NuGet/NuGetGallery#6622]
Preview page displays a multiline text (description and release note of new package) in single line.

The page of published package displays a multiline text without problems.

It is creates some inconvenience.

See screenshots.
![2018_11_04--nuget-01-preview_page](https://user-images.githubusercontent.com/4594554/47965093-92869100-e053-11e8-8756-72e9c2b750ce.PNG)
![2018_11_04--nuget-02-package_page](https://user-images.githubusercontent.com/4594554/47965094-92869100-e053-11e8-8d56-674c19f5b190.PNG)

**Comment by skofman1** [comment]
Thanks for reporting!

**Comment by khellang** [comment]
Woulnd't `white-space: pre-wrap;` fix this?

**Comment by scottbommarito** [comment]
@khellang - Yup! Didn't realize this existed. You're welcome to make the fix yourself--otherwise, one of us will get around to it eventually.

**Comment by joelverhagen** [comment]
Reopening until we deploy to PROD.

**Comment by joelverhagen** [comment]
@robertmuehsig, this fix is deployed to nuget.org. Thanks!

**Comment by dmitry-lipetsk** [comment]
Fix looks fine. Thank you!
