### ISSUE TITLE
Message duplication causes orchestrator messages dead-letter 

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6624]
Orchestrator has logic that clones messages and re-enqueues them so that we can try a message more than the maximum attempts set on the subscription (20). In short, orchestrator does this:

1. Gets a message.
1. Process the message.
1. If the validation set is not done, re-enqueue
1. Complete the message.

If the "complete the message" step fails, that means there are now two messages for the one validation set. When the validation set finally completes, one message "wins" by copying the package from to the public container. The other message "loses" because it can't copy the package from the validation set location to the public container because the first message deleted the validation set copy.

This causes dead-lettering.

This issue is a continuation of https://github.com/NuGet/NuGetGallery/issues/6515.

In my on-call week I had 34+ dead-letter messages.

**Comment by loic-sharma** [comment]
```
traces
| where cloud_RoleName == "NuGet.Services.Validation.Orchestrator" 
| extend CallGuid = tostring(customDimensions.CallGuid)
| summarize max(timestamp), min(timestamp) by CallGuid
| extend Duration = (max_timestamp  - min_timestamp)/1s
| join (
  exceptions
  | where cloud_RoleName == "NuGet.Services.Validation.Orchestrator" 
  | where outerMessage contains "The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue."
  | extend CallGuid = tostring(customDimensions.CallGuid)
  | project CallGuid
) on CallGuid
| join (
  traces
  | where cloud_RoleName == "NuGet.Services.Validation.Orchestrator"
  | extend CallGuid = tostring(customDimensions.CallGuid)
  | extend ValidationSetId = tostring(customDimensions.ValidationSetId)
  | where ValidationSetId <> ""
  | summarize any(ValidationSetId) by CallGuid 
  | extend ValidationSetId = any_ValidationSetId
  | project ValidationSetId, CallGuid
) on CallGuid
| join (
  traces
  | where cloud_RoleName == "NuGet.Services.Validation.Orchestrator" 
  | where message contains "Before calling FetchAttributesAsync(), the source blob 'validation-sets/"
  | extend ValidationSetId = tostring(customDimensions.ValidationSetId)
  | summarize count() by ValidationSetId
  | extend CopyFailures = count_
) on ValidationSetId 
| project ValidationSetId, CallGuid, Duration, CopyFailures
```

**Comment by loic-sharma** [comment]
There is a concern that the solution could make a validation set "stuck". Say a package takes 30 minutes to download, no matter what. If all 20 deliveries of the messages hit the 30 minute download, all deliveries will not send a follow-up message, and the validation set will be "stuck". In other words, the solution would make a validation set "stuck" if all deliveries of a message exceed the lock duration.

I crunched some numbers on PROD. In the last week:

1. 911 validation sets had 1 message take longer than 1 minute to process
2. 21 validation sets had 2 messages take longer than 1 minute to process
3. 0 validation sets had 3 or more messages take longer than 1 minute to process

From the data, there is no concern for validation sets getting "stuck" after the change. Here is the query I ran:

```
traces
| where cloud_RoleName == "NuGet.Services.Validation.Orchestrator" 
| extend CallGuid = tostring(customDimensions.CallGuid)
| extend ValidationSetId = tostring(customDimensions.ValidationSetId)
| where CallGuid <> ""
| summarize max(timestamp), min(timestamp), max(ValidationSetId) by CallGuid
| extend DurationSeconds = (max_timestamp  - min_timestamp)/1s
| where DurationSeconds >= 60
| extend ValidationSetId = max_ValidationSetId 
| project ValidationSetId, DurationSeconds, CallGuid
| summarize count() by ValidationSetId
| order by count_ desc
```

Only 2 validation sets in the past week

**Comment by loic-sharma** [comment]
Orchestrator does not seem to set `ServicePointManager.DefaultConnectionLimit`

**Comment by loic-sharma** [comment]
* [ ] Improve message duration + lock expiration telemetry: https://github.com/NuGet/ServerCommon/pull/230, https://github.com/NuGet/NuGet.Jobs/pull/678
* [ ] Increase the connection limit in the Orchestrator: https://github.com/NuGet/NuGet.Jobs/pull/677
* [ ] Improve the package backup telemetry

**Comment by loic-sharma** [comment]
@agr should we keep this open until we’ve verified there’s no more dead lettering? I would wait a few days and maybe run functional tests on PROD.
