### ISSUE TITLE
NuGet.Server "hangs" on importing NuGet package

### ISSUE THREAD

**Issue by Birgos** [NuGet/NuGetGallery#6628]
Hello!

### My Setup
NuGet.Server v3.1.2.0 on Windows Server 2012 R2

### Problem
When I try to add the package https://www.nuget.org/packages/H3/3.2.0-alpha to my local gallery (via the import folder) the gallery stops working. It seems that the gallery can't import the nuget package.

I tried:
1. Restarting the app pool of the iis
2. Restarting the whole iis service
3. Deleting the cache file (multiple times, even at step 1 and 2)

### Workaround
After repacking the original nuget package (extract and create a new one, but with the following changes), the nuget.server imports my new package without any problems:

1. I didn't put the file .signature.p7s into my new package
2. I edited the nuspec files an deleted some of the empty lines at the description property

## Question

1. Is there an option to enable logging at the nuget.server so I can find out, why the package can not be imported?
2. What is the problem with that nuget package? Is the signature file problematic?

I would appreciate any kind of help with that issue. Thanks in advance!

**Comment by skofman1** [comment]
Hi @Birgos !
When you add package NuGet.Server to a project, it drops a file into your solution. It's called NuGetODataConfig.cs
Uncommenting two lines in that file will enable logging:
https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/App_Start/NuGetODataConfig.cs#L35
