### ISSUE TITLE
Cannot access my nuget.org account since i've closed my linked microsoft account

### ISSUE THREAD

**Issue by shayhatsor** [NuGet/NuGetGallery#6633]
i got the following email from admin@nuget.org:
> We received a Microsoft account close notification for the account linked with your NuGet account : https://www.nuget.org/profiles/shayhatsor. Your NuGet account https://www.nuget.org/profiles/shayhatsor will be deleted in the next 72 hours. Please consider transferring your owned packages to a different NuGet account using Manage package owners flow. Otherwise the packages owned by the account https://www.nuget.org/profiles/shayhatsor will remain available without a listed owner.

i have tried to login to my nuget.org account, but was unsuccessful. also tried to recover the password which didn't work either. also recreated the closed account, thinking it might give me access to the nuget.org account, but that didn't work either.
please help me move my owned packages to a new account. or remove the link to the microsoft account so i can register a microsoft account again, in order to get access. i wasn't expecting that my nuget.org account will be affected by removing a linked account.
thanks.

**Comment by loic-sharma** [comment]
I've sent @shayhatsor instructions on how to proceed. We will delete your old account after the packages have been transferred to your new account.

**Comment by shayhatsor** [comment]
thanks @loic-sharma for the quick resolution of my issue !

**Comment by loic-sharma** [comment]
Hey @shayhatsor, we're doing an internal investigation on this. You mentioned this:

>  tried to recover the password which didn't work either.

The recover password flow should work. Could you explain what happened when you tried to recover the password?

**Comment by shayhatsor** [comment]
yes, when i tried to recover the password for the nuget.org account
'shayhatsor'
i got the following email sent to *shayhatsor.mail@gmail.com
<http://gmail.com> *which is the email i used originally to register:
>
> Hi there,
>
> We heard you were looking for Microsoft logins associated with your
> account on NuGet Gallery.
>
> Our records indicate the associated Microsoft login(s): Shay Hatsor
> shayhatsor.mail@gmail.com.
>
> Thanks,
>
> The NuGet Gallery Team
>
which basically says that there's no way for me to get a new password other
than using the linked shayhatsor.mail@gmail.com Microsoft account, which
was closed.
if you have any other questions, please let me know.
shay.

**Comment by shayhatsor** [comment]
yes, when i tried to recover the password for the nuget.org account
`shayhatsor`
i got the following email sent to *shayhatsor@gmail.com* which is the email i used originally to register:
>
> Hi there,
>
> We heard you were looking for Microsoft logins associated with your
> account on NuGet Gallery.
>
> Our records indicate the associated Microsoft login(s): Shay Hatsor
> shayhatsor.mail@gmail.com.
>
> Thanks,
>
> The NuGet Gallery Team
>
which basically says that there's no way for me to get a new password other
than using the linked shayhatsor.mail@gmail.com Microsoft account, which
was closed.
