### ISSUE TITLE
Display package page does a query per version -- for latest symbols package

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6650]
`DisplayPackageViewModel` has a line where it calls `package.LatestSymbolPackage()`. `DisplayPackageViewModel` is initialized per package version when viewing the display package page. `package.LatestSymbolPackage()` does a SQL query.

This is the average number of SQL queries per display package page view:

![image](https://user-images.githubusercontent.com/94054/48296230-f1c81500-e448-11e8-950f-2df2ae8ad5cf.png)

```
dependencies
| where timestamp > ago(30d)
| where type == "SQL"
| where operation_Name == "GET packages/DisplayPackage" 
| summarize sum(itemCount) / dcount(operation_Id) by bin(timestamp, 6h)
| render timechart 
```

Clearly around October 24, we deployed this bug.

**We should have a unit test that the number of queries to render a page with 3 versions does not grow when there are 4 versions.**

/cc @ryuyu @loic-sharma

**Comment by joelverhagen** [comment]
Request duration is also impacted:

![image](https://user-images.githubusercontent.com/94054/48296266-79ae1f00-e449-11e8-922e-6880880763a7.png)

```
requests
| where timestamp > ago(30d)
| where operation_Name == "GET packages/DisplayPackage" 
| summarize avg(duration) by bin(timestamp, 6h)
| render timechart 
```

**Comment by shishirx34** [comment]
![image](https://user-images.githubusercontent.com/1646506/48584728-6a165680-e8df-11e8-9ebf-0e3c2b0c0920.png)

![image](https://user-images.githubusercontent.com/1646506/48584771-8914e880-e8df-11e8-817a-2aaafd3ffd28.png)
