### ISSUE TITLE
Sign in error "Using application 'NuGet.Org' is currently not supported for your organization X because it is in an unmanaged state."

### ISSUE THREAD

**Issue by andyb1979** [NuGet/NuGetGallery#6660]
When signing in to NuGet.org with my Microsoft account MyName@MyCompany.com I am presented with this error 

> Using application 'NuGet.Org' is currently not supported for your organization MyCompany.com because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of MyCompany.com before the application NuGet.Org can be provisioned. Request ID: 4875b829-901a-45bf-94a1-69c415f3ae3c,Timestamp: 11/13/2018 07:58:18 Trace ID: 1331961f-08a0-4437-a834-6f3e8ab96800 Correlation ID: 990d603e-b959-4f2e-80fa-789a83fad6e4 Timestamp: 2018-11-13 07:58:18Z

This is a recent error and I have been able to sign in successfully in the past.

**Comment by chenriksson** [comment]
@andyb1979 Sorry for the delay. I replied to your support email and will keep you updated there. Closing this public issue.

**Comment by msevestre** [comment]
@andyb1979 @chenriksson 

I am having the exact same issue today. Can you let me know how to proceed to solve the issue ?

**Comment by andyb1979** [comment]
It was not resolved for me ... I had to contact nuget support who told me
to create a new account and they would grant this second account admin
access. I have not done this step yet.

**Comment by msevestre** [comment]
@andyb1979 Thanks! I have send numerous emails to nuget support but no feedback whatsoever.
@chenriksson Do you think you could get in touch with me so that I can finally log back in?

**Comment by andyb1979** [comment]
... or fix the error ! Either would be useful

**Comment by chenriksson** [comment]
@msevestre Could you send a support email to nuget@microsoft.com and we'll try to help you. So far, we're not sure if we can correct this error on the NuGet.org side, but are reaching out to AAD to see if there's a good resolution.

/cc @shishirx34 @agr

**Comment by msevestre** [comment]
@chenriksson Done: Thanks for your feedback. Let me know if you need more info

**Comment by valentinacupac** [comment]
I am also facing this issue today, I have sent an email to nuget@microsoft.com so I hope it will be resolved...

**Comment by markpiller** [comment]
I am having exactly the same issue now. I was able to sign in using the same email just last week. Why is it so hard to provide basic instructions for how to claim ownership of the domain???
