### ISSUE TITLE
nuget.org should reject .symbols.nupkg

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#6662]
Today, if a user pushes a legacy symbol package (foo.symbols.nupkg) to nuget.org it gets published as a regular nuget package. We should reject it on the basis of the extension if there are no distinguishing elements in the nuspec.

**Comment by cristinamanum** [comment]
With this we will block the "symbols" to used as last segment in a package name. I do not see a reason for doing it. If the goal is to block packages with certain content (pdbs, .. ) it will be different issue and decision.

**Comment by skofman1** [comment]
@cristinamanum , @karann-msft , what is the decision here? Should this issue be closed?

**Comment by karann-msft** [comment]
@cristinamanum, the goal is to block a symbol package from being accidentally published as a nupkg. If the extension of a package is `.symbols.nupkg` it is obvious that this is an old style symbol package that nuget.org does not support.

**Comment by skofman1** [comment]
Closing this one since we can't distinguish between nupkg and symbols.nupkg
