### ISSUE TITLE
Tracking possible symbols delete perf degradation

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#6668]
Address the possible perf issue(we do not know what kind of issue it could be) on symbols delete page: https://github.com/NuGet/NuGetGallery/pull/6667 

The issue is on symbols delete page it is possible that we could make high number of dependency calls(db queries) based on the number of queries. The perf impact is unknown at the moment, hence this tracking issue.

**Comment by cristinamanum** [comment]
The fix was merged- closing the issue.
