### ISSUE TITLE
Documentation preview when adding new package does not work

### ISSUE THREAD

**Issue by ssougnez** [NuGet/NuGetGallery#6671]
Hi,

I'm currently adding a new NuGet package via NuGet.org and I'm having issue previewing my documentation. Indeed, when I type something in the textarea then click on "Preview", the textarea disappear but what I wrote in it does not appear on the page.

So I type something:

![01](https://user-images.githubusercontent.com/10199821/48551215-33d3d980-e8d5-11e8-86a8-d8b2907f9f5b.png)

Then I click "Preview":

![02](https://user-images.githubusercontent.com/10199821/48551224-3b937e00-e8d5-11e8-96d0-cefaa29153f0.png)

And nothing appears. I also tried to edit an existing package with a documentation already written and I'm having the same issue.

**Comment by loic-sharma** [comment]
It looks like `displayReadMePreview`'s `$("#readme-preview-contents").html(response)` should be changed to something like `$("#readme-preview-contents").html(response[0].PlainTextMessage);`. I'm looking into why the response changed.

**Comment by ssougnez** [comment]
I confirm that it now works as expected.

Thanks a lot ;-)
