### ISSUE TITLE
Nuget.exe 4.8.1 reads path incorrectly with space (generates "Could not find part of the path c:\path\  \packages\AngeSharp.0.9.9.2" etc.)

### ISSUE THREAD

**Issue by jeanluc33** [NuGet/NuGetGallery#6696]
I experienced this issue when MSBuild, using the Nuget.targets, downloaded Nuget 4.8.1 as specified int he Nuget.targets file (url: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe ).  When I deleted the 4.8.1 executable and hard coded https://dist.nuget.org/win-x86-commandline/v4.7.1/nuget.exe in Nuget.targets, the error was resolved.

Therefore, I believe an issue was introduced in Nuget 4.8.1 about reading package location paths.  The path is being concatenated incorrectly, introducing a space that is causing the error.

Example MSBuild errors with 4.8.1:
C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\AngleSharp.0.9.9.2'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.AspNet.Razor.3.2.6'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.AspNet.Mvc.5.2.6'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Castle.Core.4.3.1'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): The command ""C:\B\4\57\src\dev\Solution1\.nuget\NuGet.exe" install "C:\B\4\57\src\dev\Solution1\Solution1\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\B\4\57\src\dev\Solution1\ "" exited with code 1.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.ApplicationInsights.Agent.Intercept.1.2.0'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\WebGrease.1.5.2'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Respond.1.2.0'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\popper.js.1.14.3'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Owin.1.0'.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #7550](https://github.com/NuGet/Home/issues/7550) via [**ZenHub**](https://www.zenhub.com/)
