### ISSUE TITLE
Auto-link HTML in Package Description

### ISSUE THREAD

**Issue by Haacked** [NuGet/NuGetGallery#67]

**Comment by MarcosMeli** [comment]
Would be great for everyone !! :+1:

**Comment by 304NotModified** [comment]
Related #2280

**Comment by 304NotModified** [comment]
Is a PR accepted on this one?

**Comment by 304NotModified** [comment]
Bump

**Comment by maartenba** [comment]
Will be part of Support formatting in description #2280 (when we tackle it)

**Comment by 304NotModified** [comment]
Lol doesn't look like formating will ever be implemented.

**Comment by 304NotModified** [comment]
Same for this one. 5 years old and even no response if a PR is accepted.
