### ISSUE TITLE
[Feature Request] Button "Download package with depedencies"

### ISSUE THREAD

**Issue by Torgrimm** [NuGet/NuGetGallery#6700]
Hello,

It would be helpful, if there would be a button to download a package along with all dependencies in a single step.

Background:
We're developing in a LAN disconnected from Internet. On separate machines, we're downloading the required packages from nuget.org using the browser and pushing them in development LAN to our packet source server, afterwards. Especially with .net core there are a lot downloads required...

**Comment by loic-sharma** [comment]
What package source server are you using? Most implementations provide some sort of mirroring feature that help you do this.

**Comment by Torgrimm** [comment]
Hello Loic Sharma
we're using the package server of TFS 2017 on premise. I don't believe a mirroring will help us, though - as there is no direct connection possible between TFS and NuGet. The TFS is disconnected from Internet.

**Comment by agr** [comment]
You can try running
```
nuget install <package-id> -source https://api.nuget.org/v3/index.json
```
in an empty directory. It will download the package and all of its dependencies and save them in respective subdirectories (as nupkgs and unpacked, so it does quite a bit more than you need).

Then if you need nupkgs in current directory you can do something like this in powershell:
```Powershell
dir -Recurse -Include *.nupkg | ForEach-Object {copy $_ .}
```
