### ISSUE TITLE
[Deployment] Week of 11/29/2018

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#6713]
# Deployment 2018-11-29

**Planned production date**:  2018-12-03

Repo | Service | Commit | Build | INT | PROD|Prod Asia
--- | --- | --- | --- | --- | --- | ---
NuGet.Services.Metadata | Catalog2Dnx | https://github.com/NuGet/NuGet.Services.Metadata/commit/37b26ada86a09ce26f02c218bf4322ac1f9e6482 | [#2239802](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2239802) | <ul><li>[X] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Services.Metadata | Catalog2Registration | https://github.com/NuGet/NuGet.Services.Metadata/commit/37b26ada86a09ce26f02c218bf4322ac1f9e6482 | [#2239802](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2239802) | <ul><li>[X] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul>
NuGet.Jobs | Orchestrator | https://github.com/NuGet/NuGet.Jobs/commit/47326c56f822f18e09bf203fda7770372754bd23 | [#2243583](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2243583) | <ul><li>[X] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>NA</li></ul>
NuGet.Jobs | CollectAzureCdnLogs | https://github.com/NuGet/NuGet.Jobs/commit/47326c56f822f18e09bf203fda7770372754bd23 | [#2243582](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2243582) | <ul><li>[X] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>NA</li></ul>

Includes:

Title | PR | Commit
--- | --- | ---
Improve signing time of NuGet.Services.Metadata | https://github.com/NuGet/NuGet.Services.Metadata/pull/399 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/6ef2a1affd57a4325292a5026b27ddfb58cb7bb5
V3: extract parallelized commit processing into common utility class | https://github.com/NuGet/NuGet.Services.Metadata/pull/401 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/b87f57b24963aa261b592ccda807edd85a0c2098
Copy NuGet.Protocol.Catalog from Samples repository | https://github.com/NuGet/NuGet.Services.Metadata/pull/405 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/791f129c6f2ddddc26adf27a33823335229ed099
V3: simplify catalog commit processing parallelization | https://github.com/NuGet/NuGet.Services.Metadata/pull/407 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/3688478b04b2c7bc532408d77c047e98ffc052da
Test: move tests from NgTests project to CatalogTests project | https://github.com/NuGet/NuGet.Services.Metadata/pull/409 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/903e08a7bd1ede67c0438fffc73f5c8ef8fdd2c7
V3: fix potential NullReferenceException | https://github.com/NuGet/NuGet.Services.Metadata/pull/408 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/9e08ae36352a30e0a2b9ba5fb451828ac17a08ac
MonitoringProcessor: fix incomplete package delete identification | https://github.com/NuGet/NuGet.Services.Metadata/pull/411 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/18d1d32d4b6417690008d6ec1eeeb6822b0a89db
Catalog2Dnx: parallelize commit processing | https://github.com/NuGet/NuGet.Services.Metadata/pull/412 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/ae0d22f66487c9359441a48959ca86c7722f43ea
V3: fix missing initialization of IsDelete | https://github.com/NuGet/NuGet.Services.Metadata/pull/413 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/49ed10635279537de7383bf505f1748e106776ff
V3 Monitoring - Improve logging when queue message processing fails | https://github.com/NuGet/NuGet.Services.Metadata/pull/410 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/a1a4bf448bd4888e4d6643f9736f2ea44799d43c
Refactoring: moved FeedHelpers.GetCatalogPropertiesAsync | https://github.com/NuGet/NuGet.Services.Metadata/pull/414 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/11d3d81e0c844d310acbb406090de3e3b516bdac
Monitoring: undo IsDelete change | https://github.com/NuGet/NuGet.Services.Metadata/pull/421 | https://github.com/NuGet/NuGet.Services.Metadata/pull/418/commits/bea889f414a447c1e5cbbcce953fc33e60da0f26
CollectAzureCdnLogs should properly handle files ending in .tmp | NuGet/NuGet.Jobs#673 | NuGet/NuGet.Jobs@ced7785
Recognize "NuGet VS VSIX" as valid NuGet client | NuGet/NuGet.Jobs#681 | NuGet/NuGet.Jobs@c1801e1
Convert CollectCdnLogs jobs to JsonConfig | NuGet/NuGet.Jobs#685 | NuGet/NuGet.Jobs@497d470
Repository sign packages owned by users with "malformed" usernames | NuGet/NuGet.Jobs#686 | NuGet/NuGet.Jobs@9008706
Add configuration argument | NuGet/NuGet.Jobs#689 | NuGet/NuGet.Jobs@f85cafb
Remove legacy validation code (VCS-based) | NuGet/NuGet.Jobs#605 | NuGet/NuGet.Jobs@8a3b27d

**Comment by agr** [comment]
Catalog2dnx is in INT, running E2E tests

**Comment by agr** [comment]
Deployed both to INT, E2E tests succeeded.

**Comment by agr** [comment]
Stats pipeline in INT seem to have died. Do not promote ColelctAzureCdnLogs job to PROD.

**Comment by scottbommarito** [comment]
`ImportAzureCdnStatistics` is failing, not `CollectAzureCdnLogs`:

```
The SELECT permission was denied on the object 'Dimension_Time', database 'nuget-int-statistics', schema 'dbo'.
--
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlConnection.OnError","level":0,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlInternalConnection.OnError","level":1,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning","level":2,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.TdsParser.TryRun","level":3,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlDataReader.TryConsumeMetaData","level":4,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlDataReader.get_MetaData","level":5,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlCommand.FinishExecuteReader","level":6,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader","level":7,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlCommand.InternalEndExecuteReader","level":8,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal","level":9,"line":0
"assembly":"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync","level":10,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic","level":11,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":12,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":13,"line":0
"assembly":"Stats.ImportAzureCdnStatistics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Stats.ImportAzureCdnStatistics.Warehouse+<RetrieveTimeDimensions>d__29.MoveNext","level":14,"line":774,"fileName":"E:\\A\\_work\\53\\s\\src\\Stats.ImportAzureCdnStatistics\\Warehouse.cs"
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":15,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":16,"line":0
"assembly":"Stats.ImportAzureCdnStatistics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Stats.ImportAzureCdnStatistics.Warehouse+<GetDimension>d__23`1.MoveNext","level":17,"line":587,"fileName":"E:\\A\\_work\\53\\s\\src\\Stats.ImportAzureCdnStatistics\\Warehouse.cs"
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":18,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":19,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd","level":20,"line":0
"assembly":"Stats.ImportAzureCdnStatistics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Stats.ImportAzureCdnStatistics.Warehouse+<CreateAsync>d__15.MoveNext","level":21,"line":103,"fileName":"E:\\A\\_work\\53\\s\\src\\Stats.ImportAzureCdnStatistics\\Warehouse.cs"
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":22,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":23,"line":0
"assembly":"Stats.ImportAzureCdnStatistics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Stats.ImportAzureCdnStatistics.LogFileProcessor+<ProcessPackageStatisticsInLogFileAsync>d__6.MoveNext","level":24,"line":110,"fileName":"E:\\A\\_work\\53\\s\\src\\Stats.ImportAzureCdnStatistics\\LogFileProcessor.cs"
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":25,"line":0
"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":26,"line":0
"assembly":"Stats.ImportAzureCdnStatistics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Stats.ImportAzureCdnStatistics.LogFileProcessor+<ProcessLogFileAsync>d__4.MoveNext","level":27,"line":54,"fileName":"E:\\A\\_work\\53\\s\\src\\Stats.ImportAzureCdnStatistics\\LogFileProcessor.cs"
```

**Comment by chenriksson** [comment]
@scottbommarito @agr - @xavierdecoster mentioned this to me, so I'm planning to investigate. If anyone already knows the cause, please keep me in the loop.

**Comment by chenriksson** [comment]
SQL auditing revealed the permissions changes. I've emailed the fix to @agr for review, since he's on-call.
