### ISSUE TITLE
Cant connect to Nuget

### ISSUE THREAD

**Issue by Yantup** [NuGet/NuGetGallery#6718]
Hello, since mid day i havent been able to download any nuget package, cant sreach them in the VS 2017, or check for updates, cant access through console. Tried to ping the site via CMD / ping nuget.org and get the conection timeout. However i can access the website via browser navigation,  i also have tried to download via webbrowser and it always die here:
az320820.vo.msecnd.net
VS gave me a hint on this url and i cant get there via Web browser  or VS 2017:
api.nuget.org/v3/index.json

I dont have firewall or proxy, until last night everything was running normal(retake work after mid day), im using  Win10 Home.

This is the nuget info:

Name             : Package Manager Host
Version          : 4.8.1.5435
InstanceId       : 649399b5-4a1e-41aa-a9e9-76a15eeebe22
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : es-CO
CurrentUICulture : es-ES
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

Im only using the nuget.org source.
Im from Colombia.
.Net Framework installed version:
4.7.2
4.0.0.0
3.5.30729.5003
3.0.30729.4926
2.0.50727.4927

i ran 2 tests for Fiddler and winMTR:
[IssueN.zip](https://github.com/NuGet/NuGetGallery/files/2635311/IssueN.zip)

**Comment by cristinamanum** [comment]
Hello @Yantup, sorry for the delay. Do you still experience the issue above?

**Comment by Yantup** [comment]
The problem lasted a few more days, after the 3rd day i coulndt connect for intervals, sometimes there was no issue, sometimes no connection was allowed. Since yesterady everything seams to be fine.

**Comment by cristinamanum** [comment]
Thank you for the update. We added a test that will notify us for availability issues in Bogota. I will close the issue. Please reopen if it manifests again.
