### ISSUE TITLE
unlisted package description/workarounds

### ISSUE THREAD

**Issue by deepakverma** [NuGet/NuGetGallery#672]
there have been couple of posts I have seen where folks are looking for nuget packages that are now unlisted and don't have an idea on how to proceed
would propose:
1. there should be an option for the owner to specify details on why the package was unlisted and any pointers to  the new package or workarounds.
2. If owner still wants to display it in the search results so that customers can know about the details.

**Comment by flytzen** [comment]
This is definitely needed. It's less about deprecating a *version*, more about deprecating a whole package. 
See, for example, Microsoft.WindowsAzure.Management.* which has been replaced by Microsoft.Azure.Management.*. Yet, there is so much documentation out there pointing to the old packages that they sort of need to stay around. Also, I think, there may still be a few bits of functionality that are only available in the old version; so would be sensible to deprecate them to encourage everyone who can to move to the new set of packages.

**Comment by anangaur** [comment]
Closing this in favor of https://github.com/NuGet/Home/issues/2867 that has the discussion going.
