### ISSUE TITLE
Symbols package publishing fails?

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#6729]
One customer reports this issue:

> The following error is displayed for some symbols package:
> "Symbols package publishing failed. The associated symbols package could not be published due to the following reason(s): The uploaded symbols package contains one or more pdbs that are not portable. Once you've fixed the issue with your symbols package, you can re-upload it."

> These pdbs are generated for a .NET library written in C#.
> I've generated the .snupkg using "nuget pack MyPackage.nuspec -Symbols -SymbolPackageFormat snupkg". The code and pdbs were built using VS 2017 v15.9.3 and the .nupkg and .snupkg created using nuget v4.9.1.5694.
> The project's build > advanced build settings specifies "Debugging information" as Portable.
> Should this work for code targeting .NET Framework rather than .NET Core?

**Comment by shishirx34** [comment]
@cristinamanum - thoughts?

**Comment by shishirx34** [comment]
The package had a windows pdb which was why it failed validation. The customer has reported that he was able to resolve the issue.
