### ISSUE TITLE
The place for enhancement requests, and the feature to follow/unfollow a package?

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#6733]
Nuget should provide a place for customers to keep enhancement requests. Current issue tracker may not be the correct place. 
Nuget.org should also provide the feature so that customers could follow/unfollow a package. Customers could keep track of a package and have a favorites list.
The visual studio feedback area may be a similar feature.

**Comment by skofman1** [comment]
The place for feature requests is GitHub. There's a link on "Contact US" page here: https://www.nuget.org/policies/Contact

Regarding getting updates on "favorites list" - there's an issue tracking: https://github.com/NuGet/NuGetGallery/issues/2992
