### ISSUE TITLE
Edge and Firefox try to download license files with content type "text/markdown"

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#6735]
If package has an embedded license file ".md" extension, it gets saved to flatcontainer with "text/markdown" content type. When both Edge and Firefox browsers are pointed to those files, they prompt to save it instead of displaying it. Chrome displays those.
Need to have consistent behavior.
Making everything to be `text/plain` works, but we lose the type information for blobs (we still have an indication in DB though, so not a big deal for Gallery).

**Comment by skofman1** [comment]
Since we are changing UI to open the md files ourselves, no need to "hack" content types.
