### ISSUE TITLE
Unable to resolve dependencies between Microsoft.Azure.KeyVault 3.0.2 & Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider 2.1.0

### ISSUE THREAD

**Issue by prdpsvs** [NuGet/NuGetGallery#6736]
Is there a way to resolve this dependency?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'Microsoft.Azure.KeyVault 3.0.2' is not compatible with 'Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider 2.1.0 constraint: Microsoft.Azure.KeyVault (>= 2.0.6 && < 3.0.0)'.

**Comment by skofman1** [comment]
@prdpsvs , there's no way to resolve incompatible dependencies. To resolve this you will need to use Microsoft.Azure.KeyVault 3.0.0. 

For additional questions please contact owners of package Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider directly: 
https://www.nuget.org/packages/Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider/2.2.0-beta/ContactOwners 

As we don't provide support for individual packages.
