### ISSUE TITLE
NuGet Server creates large numbers of temp files in C:\Windows\Temp\nuget on build server

### ISSUE THREAD

**Issue by llyons** [NuGet/NuGetGallery#6740]
I have searched a number of locations on the net to find solutions but have not found any.

We have a build server that also doubles as a nuget private server.

When we have builds that pull nuget packages from this server,  it creates a large number of file/folders in  C:\windows\temp\nuget

these folders are named similar to whats below

jvlm0lgn.v10\lib\net451\   (Files)
gmxfxu44.llh\lib\net451\    (Files)
1lspx2v4.fpk\lib\net451\    (Files)

it looks like the files are a set of dll's that are part of a nuget package.

My big question is how do we move this temp folder location to another drive?   

We cant keep filling up the C: drive on the build server since it fills up quickly

**Comment by llyons** [comment]
It looks like the stamped dll version of nuget.server.dll is  3.0.0.0 or 3.0.0-preview.

where do we find the newer version and any upgrade instructions?

With the new version are these files cleaned up as they are unpacked or does the new update provide an option for where to unpack these?

**Comment by llyons** [comment]
I figured out how to rebuild the server with the latest version of nuget.server.  However we are getting a permission error on a cache.bin file.   C:\projects\packages is the defined in the web.config <add key="packagesPath" value="c:\projects\packages" />.   The site's app pool runs under network service which has permissions in that folder and for that file.  

Any ideas what I might be missing?

Error:

Message: Access to the path 'c:\projects\packages\corp-build01.cache.bin' is denied.

StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at NuGet.PhysicalFileSystem.CreateFile(String path)
   at NuGet.Server.Core.Infrastructure.ServerPackageCache.Persist()
   at NuGet.Server.Core.Infrastructure.ServerPackageCache.PersistIfDirty()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by skofman1** [comment]
@llyons , it's hard to debug remotely 😃 I would check if the file is marked "readonly"/used by another process. Try to delete it and see if that works?

**Comment by llyons** [comment]
ok I didnt know I could delete it but I will give that a try.

Is there any difference in how the packages are stored in the package folder between 3.0.0.0 (what we had) and 3.1.2.0?  

Is the cache.bin new with 3.1.2?

Was there any upgrade instructions that might spell out what needed to be done to move from 3.0.0.0 and 3.1.2.0?

Sorry if I am not giving enough info.  I do realize it makes it difficult to debug and understand.

**Comment by llyons** [comment]
Also,  where are the log files that the nuget server writes out too?  We are having a 404 error when trying to push a package with the new server.  This error shows as...


WARNING: No API Key was provided and no API Key could be found for 'http://machine.domain.local:8001/'. To save an API Key for a source use the 'setApiKey' command.
Pushing ContentManagement.WebAPI.ApiClient.1.0.12.nupkg to 'http://machine.domain.olh.local:8001/'...
  PUT http://machine.domain.local:8001/api/v2/package/
  NotFound http://machine.domain.local:8001/api/v2/package/ 18ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---

**Comment by joelverhagen** [comment]
> ok I didnt know I could delete it but I will give that a try.

Yes, it's just a cache of all of the package metadata on disk. If you delete it, NuGet.Server will rebuild it.

> Is there any difference in how the packages are stored in the package folder between 3.0.0.0 (what we had) and 3.1.2.0?

The packages should be stored the same way, but it's possible that the cache file changed format.

> Is the cache.bin new with 3.1.2?

No, it should have existed since 3.0.0-beta (and even in 2.x for a while).

> Was there any upgrade instructions that might spell out what needed to be done to move from 3.0.0.0 and 3.1.2.0?

Aside from update the package, you should be fine. If you have deleted the cache file no other steps should need to be taken.

> Also, where are the log files that the nuget server writes out too? We are having a 404 error when trying to push a package with the new server. This error shows as...

You can try enabling server-side logs like this:
https://github.com/NuGet/NuGet.Server/blob/fe2231b0373b9ecc3333a51695f8ec8864fc1368/src/NuGet.Server/App_Start/NuGetODataConfig.cs.pp#L25-L26

**Comment by skofman1** [comment]
> WARNING: No API Key was provided and no API Key could

You should provide an API Key to authenticate against the server. Here's the CLI reference: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-push

You can get/set the API Key in the web.config: https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Web.config#L17

**Comment by llyons** [comment]
i am deliberately not using an API key.  That should not be the issue right?

**Comment by llyons** [comment]
Thanks Joel,    Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'TextWriterTraceListener' could not be found (are you missing a using directive or an assembly reference?).

Trace is not recognized.  Is there another reference that needs to be included?

**Comment by joelverhagen** [comment]
@llyons, you need this at the top of your file:

```csharp
using System.Diagnostics;
```

**Comment by llyons** [comment]
yep thanks and system.web.hosting;

**Comment by llyons** [comment]
still getting this error.  we are able to pull from the nuget server but the push is failing.

we are doing a  

nuget.exe pack ContentManagement.WebAPI.ApiClient.csproj -IncludeReferencedProjects

then we are doing

nuget.exe push ContentManagement.WebAPI.ApiClient.1.0.11.nupkg -s http://machine.domain.local:8001/

error:


System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---

**Comment by joelverhagen** [comment]
Try pushing to `http://machine.domain.local:8001/nuget`.

If there is no path on the domain that you are pushing to, nuget.exe [assumes](https://github.com/NuGet/NuGet.Client/blob/548df8ffb2b9cc76ef769778a1e31f8dd6e34a5a/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L29) the path is `/api/v2/package` so I think it's actually pushing to `http://machine.domain.local:8001/api/v2/package` which is not supported.

**Comment by llyons** [comment]
that did it.  Thanks.

**Comment by llyons** [comment]
Thanks Joel.   I have one last question.    After adding the logging, I see this kind of message for almost every nuget package we publish.

**Comment by llyons** [comment]
Thanks Joel,  You and Skoffman1 have been very helpful.
