### ISSUE TITLE
Latest package count includes unlisted packages

### ISSUE THREAD

**Issue by SteveWilkes** [NuGet/NuGetGallery#6741]
The latest package download count on the Display Package view does not filter out unlisted packages. This can cause the latest package download count to differ from that of the latest listed package. It can be seen on [the AgileMapper](https://www.nuget.org/packages/AgileObjects.AgileMapper) page at the time of writing.

I will create a PR to fix this shortly.

**Comment by SeanKilleen** [comment]
Looking at this via the `up-for-grabs` tag and it seems as though it is fixed, verified & merged. Looks like this can be closed?

**Comment by SteveWilkes** [comment]
Yep! Closing :)

**Comment by chenriksson** [comment]
Reopening for tracking. Will close once this reaches production environment. /cc @SteveWilkes

**Comment by samedder** [comment]
I believe this is back, you can test this with https://www.nuget.org/stats/packages/Microsoft.ServiceFabric?groupby=Version
