### ISSUE TITLE
symbols.nuget.org does not returns my pdb

### ISSUE THREAD

**Issue by NicolasDorier** [NuGet/NuGetGallery#6744]
I am attempting to debug inside the sources of this package https://www.nuget.org/packages/NBitcoin/4.1.1.73

As you see, I can download the `snpukg` just fine.

I set up this in my visual studio

![image](https://user-images.githubusercontent.com/3020646/49698422-da767600-fc06-11e8-9b7c-531474c42040.png)

However, the debugger seems unable to fetch the pdb:
```
SYMSRV:  BYINDEX: 0x18
         C:\Users\NICOLA~1\AppData\Local\Temp\SymbolCache*https://symbols.nuget.org/download/symbols
         NBitcoin.pdb
         EBC3EBD8CBB84B69BC92B3B14E7F76741


SYMSRV:  UNC: C:\Users\NICOLA~1\AppData\Local\Temp\SymbolCache\NBitcoin.pdb\EBC3EBD8CBB84B69BC92B3B14E7F76741\NBitcoin.pdb - path not found


SYMSRV:  UNC: C:\Users\NICOLA~1\AppData\Local\Temp\SymbolCache\NBitcoin.pdb\EBC3EBD8CBB84B69BC92B3B14E7F76741\NBitcoin.pd_ - path not found


SYMSRV:  UNC: C:\Users\NICOLA~1\AppData\Local\Temp\SymbolCache\NBitcoin.pdb\EBC3EBD8CBB84B69BC92B3B14E7F76741\file.ptr - path not found


SYMSRV:  HTTPGET: /download/symbols/NBitcoin.pdb/EBC3EBD8CBB84B69BC92B3B14E7F76741/NBitcoin.pdb


SYMSRV:  HttpQueryInfo: 80190193 - HTTP_STATUS_FORBIDDEN


SYMSRV:  RESULT: 0x80190193


https://symbols.nuget.org/download/symbols: Symbols not found on symbol server.
```
Why is that?

I am using dotnet core with sdk 2.1.500.

I can download the `snupkg`, extract the pdb and load it manually and debug into successfully. But the `symbols.nuget.org` does not index my snupkg.

**Comment by cristinamanum** [comment]
Hi @NicolasDorier, the symbols are available in the symbol server. The issue that I suspect happens is that you use a version of Visual Studio older than Visual Studio 2017 version 15.9. 
I just tried in a simple console app and I was able to correctly fetch the symbols. 

![image](https://user-images.githubusercontent.com/16580006/49768327-d55e0900-fc90-11e8-995d-3e172a112cda.png)

**Comment by NicolasDorier** [comment]
My apologize, indeed I run 15.8.3. Closing, will reopen if I have issue.

**Comment by NicolasDorier** [comment]
I updated and it works!

I am quite surprised though, Visual Studio Code just worked fine without update, while I needed to update Visual Studio.
