### ISSUE TITLE
Update projects to .NET Framework 4.7.2

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6746]
The latest client targets .NET Framework 4.7.2. We will need to update the following items to support the latest client code:

* [ ] Build machines. Either:
   1. Install .NET Framework 4.7.2. This currently requires an OS update. Or, ...
   2. Move to MicroBuild for Continuous Integration Builds
* [ ] Verify that jobs machine can run .NET Framework 4.7.2 apps
* [ ] Update the Process Signature job to target .NET Framework 4.7.2. See https://github.com/NuGet/NuGet.Jobs/issues/695

If the gallery cannot use the .NET Standard 1.6 libraries, also:

* [ ] Verify that Azure Cloud Services can run .NET Framework 4.7.2 apps
* [ ] Update the Gallery to target .NET Framework 4.7.2

**Comment by loic-sharma** [comment]
This issue blocks https://github.com/NuGet/Engineering/issues/1891

**Comment by chenriksson** [comment]
Our build machines (nuget.vs) already have release 461814 (4.7.2) installed.

Existing jobs VMs only have release 394802 (4.6.1), but VMs created with the new job deployment template have 461814 (4.7.2) by default.

Our CloudServices are configured for 4.6.1 (e.g., NuGetDeployment `src\Gallery\NuGetGallery.Cloud\NuGetGalleryContent`), but could easily be updated per https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-dotnet-install-dotnet.

Based on this, I think we should do this work once we finish migration of jobs off Octopus.

**Comment by agr** [comment]
We will need this for the self-contained icons: client library that will be able to parse new icon elements in .nuspec files is going to be targeting 4.7.2, for us to take that dependency we'd have to upgrade to 4.7.2 as well.
