### ISSUE TITLE
Ensure revalidation of packages (12/16 incident)

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#6763]
The following packages need additional attention to revalidate properly:

- https://www.nuget.org/Admin/Validation/Search?q=CG.Bus.Abstractions+2019.3.2
- https://www.nuget.org/Admin/Validation/Search?q=Bencodex+0.1.0
- https://www.nuget.org/Admin/Validation/Search?q=Machete.HL7+1.0.244-develop
- https://www.nuget.org/Admin/Validation/Search?q=BlinkdotNet+1.0.20181216.1
- https://www.nuget.org/Admin/Validation/Search?q=Lopla.Draw+0.0.10-alpha
- https://www.nuget.org/Admin/Validation/Search?q=HotChocolate.Abstractions+0.7.0-preview.13

This special snowflake could use some verification that validation failure is expected: https://www.nuget.org/packages/Flurl.Http.Signed/2.4.0/

**Comment by loic-sharma** [comment]
View [this page](https://www.nuget.org/Admin/Validation/Search?q=Geonorge.FeedReader+1.0.0%0D%0AHotChocolate.Abstractions+0.7.0-preview.13%0D%0ALopla.Darw+0.0.10-alpha%0D%0ABlinkdotNet+1.0.20181216.1%0D%0AMachete.HL7+1.0.244-develop%0D%0ABencodex+0.1.0%0D%0ACG.Bus.Abstractions+2019.3.2) to see the latest status of the affected validations.

Gallery DB query:

```
SELECT p.[Key], pr.[Id], p.[NormalizedVersion]
FROM [dbo].[Packages] p
INNER JOIN [PackageRegistrations] pr
ON p.[PackageRegistrationKey] = pr.[Key]
WHERE PackageStatusKey = 2
ORDER BY [Created] ASC
```

**Comment by loic-sharma** [comment]
All of these packages have passed validation and are now being indexed.
