### ISSUE TITLE
Package stats haven’t updated in about two days

### ISSUE THREAD

**Issue by rianjs** [NuGet/NuGetGallery#6764]
See previous issues I’ve reported:
https://github.com/NuGet/NuGetGallery/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+author%3Arianjs+

It’s happening again.

**Comment by chenriksson** [comment]
@rianjs Thanks for the report! We'll look into this now.

**Comment by chenriksson** [comment]
Working on a hotfix that should resolve the current issue, and help with future mitigations.

**Comment by chenriksson** [comment]
Mitigated by manually regenerating outdated reports. Expecting to promote hotfix to PROD tomorrow.

**Comment by chenriksson** [comment]
Changes deployed to PROD, and appears to be caught up now. Closing, but feel free to reopen if you continue to see issues, /cc @rianjs

**Comment by WiredUK** [comment]
@chenriksson My package appears to have crawled to a halt with regards to downloads. Should I open an issue or not?
For info, my package is https://www.nuget.org/packages/graphity and was getting 10-15 downloads a day, then all of a sudden it's 2 downloads every few days.
