### ISSUE TITLE
NuGet Gallery Setup issues

### ISSUE THREAD

**Issue by nishaatr** [NuGet/NuGetGallery#6769]
I am trying to setup private instance of latest NuGet Gallery in our company. Locally on my machine it works fine after running Setup-DevEnvironment.ps1 and using local MSSQL. After I publish to our NuGet host (Windows Server 2012 R2) using File System publish method and external MSSQL, it works fine but having issues downloading packages. I manually setup IIS website with http://some-server-nuget02 URL and SSL disabled. I ran Update-Databases.ps1 after I publish and before running the IIS website. The server is running fine except that I cannot download packages and get this error:

```
The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)) 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[COMException (0x80070006): The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))]

[HttpException (0x80004005): An error occurred while communicating with the remote host. The error code is 0x80070006.]
   System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) +270
   System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[] bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes) +97
   System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal) +796
   System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders) +1399
   System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context, RequestNotificationStatus& status
```)
```
I am using shared data folder:

`<add key="Gallery.FileStorageDirectory" value="\\\\<server>\folder1\folder2\folder3\NuGetLibrary"/>`

If I use local storage on the machine then download works just fine. The shared folder has correct permissions for the system user I am using and this is proven by the fact that I can upload and the packages are copied to the shared folder.

Any ideas what is causing this error and how i can fix it?

Also, when I publish using VS2017 from my development machine, I am publishing to a shared folder on the NuGet host VM e.g. \\\\some-server-NUGET02\nugetlibrary. And then when setting up the IIS server, I have to use the same shared folder \\\\some-server-NUGET02\nugetlibrary in Physical path:. If I use the local folder (to which the shared folder is pointing to i.e. D:\Websites\nugetlibrary), the site does not start. Looks like the publish path has to match the Physical path: in IIS Basic Settings. Is this true and how can I configure Physical path: to be D:\Websites\nugetlibrary? Note: this is not causing any issues - I prefer to use D:\Websites\nugetlibrary as opposed to \\\\some-server-NUGET02\nugetlibrary. 

One more thing. After I upload packages, the packages count in the main front page is not reflected and also the packages don't appear in the Packages tab or search. I ran Lucene index but that does not help. However, after restarting the server, the count is fine. I see the same issue when running NuGet Gallery locally on my machine. Is this a known issue or am I missing something?

**Comment by nishaatr** [comment]
One more issue. I don't see the NuGet icon in Chrome or IE in the tab:
![image](https://user-images.githubusercontent.com/12186256/50150532-259f2180-02b6-11e9-8f39-499848234dd1.png)

**Comment by nishaatr** [comment]
Looks like http://some-server-nuget02/favicon.ico is available but for some reason its not showing up in the tab.

**Comment by nishaatr** [comment]
Managed to fix fav icon by changing link to "~/public/favicon.ico" in Layout.cshtml

**Comment by nishaatr** [comment]
Managed to fix Gallery.FileStorageDirectory issue. Had to grant 'Everyone=Read' rights on the network share folder. Looks like either NuGet is using a different user to fetch packages, and/or same user with reduced file rights. Would have preferred not to grant Everyone read rights but will do for now. 

So I still have the issue where package stats and package itself are not listed in Packages view and search after upload. Can you help with this?

**Comment by nishaatr** [comment]
The package stats and Packages view is now showing correct info after a few mins.  Is there a way to reflect uploaded packages state immediately?

**Comment by skofman1** [comment]
>  Is there a way to reflect uploaded packages state immediately?

Can you clarify the question?

**Comment by nishaatr** [comment]
After I upload a package, the package stats on the front page are not reflected immediately. I see this behavior also when browsing packages in the Packages section. It is as if the package has not been uploaded. NuGet seems to take time to reflect its current state. That said when I type '*' in the search box, the uploaded package is listed. 
Another thing I have noticed is that the 'packages downloads' stat is always 0:
![image](https://user-images.githubusercontent.com/12186256/50279305-37610000-0441-11e9-81ab-7b93b8cedeeb.png)
I set "Feature.TrackPackageDownloadCountInLocalDatabase" to true but that hasn't helped.

**Comment by nishaatr** [comment]
I have encountered another issue. I upload around 5 new packages usign 'nuget.exe push' and now the Packages view is only showing those packages:
![image](https://user-images.githubusercontent.com/12186256/50298518-3e0a6a00-0477-11e9-8120-27d421b3db99.png)
And the front is showing the actual total package count:
![image](https://user-images.githubusercontent.com/12186256/50298550-51b5d080-0477-11e9-851c-82d7c9584131.png)

Even if I search with '*', I only see 5 packages. If I search for specific packages that are not listed I cannot them. On the data shared folder the packages are all present. So something has gone awry!

**Comment by nishaatr** [comment]
Actually, I just remembered that I might have done a publish after the first batch of uploads. Do you think this might be the cause of missing packages? How can this be resolved without starting from scratch?
Also, is it ok to republish a new build or is there another procedure?

**Comment by nishaatr** [comment]
Sorry...ignore my previous comment. I restarted website and after a few mins, the packages are back. I can also see a couple SQL errors in Error Logs during package restore operation. I am hoping it was a glitch and will monitor in the coming days.

**Comment by skofman1** [comment]
@nishaatr , seems like you were able to resolve all the issues. Reopen this issue if not.
