### ISSUE TITLE
Package is stuck in validation for hours

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#6770]
_From @XtroTheArctic on December 17, 2018 2:43_

Package is stuck in validation for hours :(

https://www.nuget.org/packages/Atesh.BindableProperties

_Copied from original issue: NuGet/Home#7641_

**Comment by loic-sharma** [comment]
Hello @XtroTheArctic, there was an issue with our package publishing pipeline that caused delays two days ago. This should be fixed now!
