### ISSUE TITLE
Hosted Internal Nuget Repo and trying to register account after setting up email settings but never received an email and getting 500 error

### ISSUE THREAD

**Issue by gboll1819** [NuGet/NuGetGallery#6771]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, you are posting in the correct issue tracker.
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), file a bug on [NuGet Home](https://github.com/nuget/home/issues).

## Frequently Asked Questions

* **I want to delete my package** - please contact support instead via the [NuGet.org website](https://www.nuget.org)
* **I am having connectivity issues** - include an MTR and/or Fiddler trace - steps to capture this are [in our FAQ])(http://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org)

## All set!

Remove this template content and create your issue.

**Comment by skofman1** [comment]
@gboll1819 , can you share your configuration? 
By default you shouldn't confirm e-mails for new accounts:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L140

**Comment by gboll1819** [comment]
> @gboll1819 , can you share your configuration?
> By default you shouldn't confirm e-mails for new accounts:
> https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L140

I tried to Host Nuget Internal gallery by downloading the code from git hub and changed the connection strings by adding my local database. For some reason the gallery settings table doesnt have many columns except key and next license report columns. So i did manually added other columns like SMTP Port, SMTP User Name and opened user table and added my self as admin. Now i tried to register from nuget internal website but it doesnt register and throwing error 500.

**Comment by skofman1** [comment]
@gboll1819 , the settings table in the DB is not used. Configuration is done using web.config.
