### ISSUE TITLE
[Support] Add transform to org FAQ link in discontinuation flow.

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6777]
Problem 1 - 
login discontinuation flow - login errors are not visible enough.

Problem 2 - 
Password accounts that want to transform to organization don't have clear documentation/UI flow. The user needs to know to go to https://nuget.org/account/transform but it's not documented and there is no UI link.

@anangaur

**Comment by anangaur** [comment]
Does this alleviate Problem # 2?
![image](https://user-images.githubusercontent.com/14800916/50317601-511a3b80-0471-11e9-9383-fc1c6008bb7e.png)

**Comment by shishirx34** [comment]
the problem 2 is for accounts that do not have MSA/AAD linked, old password accounts. after they get a blocking dialog to link to microsoft, they could directly go to the route `/account/transform` which will allow these accounts to transform to organization without linking it to MSA/AAD.

**Comment by shishirx34** [comment]
Or we could reintroduce the link for transforming to organization in the blocking dialog page.

**Comment by anangaur** [comment]
The 1st step is to link MSA/AAD. May be - once this gets linked we pop up "Do you want to transform to an Organization?"

**Comment by shishirx34** [comment]
yeah but the linking to MSA/AAD is an unnecessary option. It takes away users' personal MSA/AAD account to link it and then have to create a new/temp MSA account to do all management. Its a pain.

**Comment by anangaur** [comment]
I agree. Let me think 🤔 over it. We did consider to provide both options initially but wanted to make it less confusing. May be we can achieve both now.

**Comment by skofman1** [comment]
@anangaur , @shishirx34 , any conclusions?

**Comment by shishirx34** [comment]
@anangaur - thoughts here?

**Comment by shishirx34** [comment]
had offline conversation with @anangaur - we came up to agreement that we could modify the pop up dialog and link to FAQ for transforming account to an organization. This issue can track that behavior. The wording is TBD.
