### ISSUE TITLE
Nuget package missing .target file in build folder

### ISSUE THREAD

**Issue by pc-hansen** [NuGet/NuGetGallery#6779]
I have build a nuget package at published it to a nuget.server site. But when I try to use the package form the server the .targets file from build folder is not in the file. But if I use the package from a local folder it works as it should. How do I get it to work ?

If i look in the package in the folder on the server it looks ok

**Comment by loic-sharma** [comment]
This sounds like a NuGet client issue. Does the .targets file work if you push a similar package to nuget.org? Can you provide us a package that reproduces this issue? Thanks!

**Comment by pc-hansen** [comment]
I just found the error. It was the cache that was not cleaned correctly so the package was and old cached version. It all works now.



Med venlig hilsen
Peter Chr. Hansen

Chefudvikler

[cid:FB7368CC-0181-4834-B0AA-1764689A78E7]

FutureLink Development ApS – CVR 33 77 19 16 | FutureLink Solutions ApS – CVR 36 40 11 84 | Blokken 13 | DK-3460 Birkerød | T. +45 70 22 98 00 | M. +45 28 88 13 04 |  www.futurelink.dk<http://futurelink.dk/> | pch@futurelink.dk<mailto:pch@futurelink.dk>


[FB]<https://www.facebook.com/futurelinkdk/?fref=ts>[LinkdIn]<https://www.linkedin.com/company-beta/143325/>


[cid:0668A47F-5F3C-47C7-A693-A00F6A53AC92]



IMPORTANT NOTICE & CONFIDENTIALITY NOTICE:
This e-mail message may contain information which is legally privileged and/or confidential. If you are not the intended recipient, you are notified that any unauthorised disclosure, copying, distribution or use of this information is strictly prohibited. If you have received this e-mail in error, please notify the sender and delete the material from any computer. FutureLink has taken every reasonable precaution to minimise the risk of software viruses, and as such we cannot accept liability for any damage you may sustain as a result of such viruses.

Fra: Loïc Sharma <notifications@github.com>
Sendt: 27. december 2018 22:46
Til: NuGet/NuGetGallery <NuGetGallery@noreply.github.com>
Cc: Peter Hansen <pch@futurelink.dk>; Author <author@noreply.github.com>
Emne: Re: [NuGet/NuGetGallery] Nuget package missing .target file in build folder (#6779)


This sounds like a NuGet client issue. Does the .targets file work if you push a similar package to nuget.org? Can you provide us a package that reproduces this issue? Thanks!

**Comment by loic-sharma** [comment]
Great! Please let us know if you have any additional questions.
