### ISSUE TITLE
Unknown Command "POST"

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/NuGetGallery#6781]
Hi Everyone,

The POST command is not working fine as you mentioned in the help link. I have used the command like below, But I have faced the below issue. 

**Command:**

nuget.exe POST https://www.nuget.org
/api/v2/package/{ID}/{Version} X-NuGet-ApiKey: {KEY}

**Issue:**

![image](https://user-images.githubusercontent.com/16695209/50580734-726b2680-0e78-11e9-8acb-0a0d480e8662.png)

Could you please check this and provide the solution to relist the NuGet packages in nuget.org.?

Thanks,
Ganesan R.

**Comment by skofman1** [comment]
Please refer to documentation here for a full list of supported commands: 
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference

If you are trying to publish a package the correct command will be "push".

**Comment by GanesanRengasamy** [comment]
Hi @skofman1,

I am trying to relist the NuGet packages which are already published and unlisted. Is there any option to achieve this without manual work. 

Thanks,
Ganesan R.

**Comment by skofman1** [comment]
@GanesanRengasamy , nuget.exe doesn't have a relist command (there's an open issue on this here https://github.com/NuGet/Home/issues/6329). Until this is implemented you can nuget.org API endpoint directly:  `POST https://www.nuget.org/api/v2/package/{ID}/{VERSION}`

You can see the discussion on this here: https://github.com/NuGet/NuGetGallery/issues/5191

**Comment by GanesanRengasamy** [comment]
Hi @skofman1,

I have already tried the POST command and I have faced the issue which is reported in my first comment. I think I am using the POST command wrongly to relist the packages. Could you please confirm me will i use the nuget.exe for this POST command or any other way to use this.

Thanks,
Ganesan R.

**Comment by skofman1** [comment]
You shouldn't use NuGet.exe, but make an http POST request. You can use powershell for example to do this with Invoke-WebRequest command https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6

**Comment by GanesanRengasamy** [comment]
Hi @skofman1,

I have tried the POST command in powershell like below, I have faced the 401 Unauthorized issue could you please suggest me how can I achieve this?

![image](https://user-images.githubusercontent.com/16695209/50683311-a3458a00-1037-11e9-8df2-f08a78fda5e2.png)

**Comment by GanesanRengasamy** [comment]
Hi @skofman1 

Could you please suggest me on this?

**Comment by skofman1** [comment]
@GanesanRengasamy , sorry for the partial response..
To use the relist API you will need to provide it with an API Key. You can create an API Key here: https://www.nuget.org/account/apikeys 
Make sure to give it permissions for "Unlist Package".

Please add to the request the following header:
Name: X-NuGet-ApiKey
Value: your API Key
