### ISSUE TITLE
[Suggestion]dotnet new command endpoint should not return unlisted packages

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#6783]
Customer Feedback:
> command dotnet new --install "Burcin.Templates.CSharp" pulls the alphabetical latest package in the list (in this case 1.0.442 which is an **unlisted** package ) regardless of package listing status. Since you don't allow hard-delete, it should not return **unlisted** packages to dotnet new` command

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #7711](https://github.com/NuGet/Home/issues/7711) via [**ZenHub**](https://www.zenhub.com/)
