### ISSUE TITLE
Empty versions list for some packages

### ISSUE THREAD

**Issue by controlflow** [NuGet/NuGetGallery#6798]
I noticed some packages have their versions list empty, while package page itself shows latest prerelease package version and allows to download it, for example:

https://www.nuget.org/packages/RavenDB.Client.FSharp/

NuGet package search API also returns empty results set for such packages.
Can you please clarify if this is a gallery bug or not. Thanks!

**Comment by skofman1** [comment]
@controlflow , this is by desing. When you see an empty versions list it means all the versions of this package were unlisted. Unlisting a package version hides it from search results. The only way to get to a package page like https://www.nuget.org/packages/RavenDB.Client.FSharp/ is by knowing the URL/package name (not from search results).
