### ISSUE TITLE
Owner icon is broken image

### ISSUE THREAD

**Issue by clovett** [NuGet/NuGetGallery#6799]
[This link](https://www.nuget.org/packages/DgmlImage/) shows me as "Owner" but the icon next to my name is a broken image:
![image](https://user-images.githubusercontent.com/3336415/50787712-09b2ee00-126c-11e9-9863-2d8f8612eb5c.png)

My [profile page](https://www.nuget.org/profiles/clovett) has an image of a cicada:
![image](https://user-images.githubusercontent.com/3336415/50787609-b9d42700-126b-11e9-8951-fc148a091433.png)

and I even see this same image on this issue page.  But it seems that the package gallery is having a hard time finding it for some reason?

**Comment by agr** [comment]
Looks OK for me:

![image](https://user-images.githubusercontent.com/102933/50928359-4ec35580-140f-11e9-8e0a-d33502568f98.png)

This image is loaded from gravatar web site, it might happen they had some issues at the time you were checking.

Does it still does not show for you? Does direct link load for you: https://secure.gravatar.com/avatar/aa2b9adbfaf11a4a8c1c03fffd83588b?s=64&r=g&d=retro ?

**Comment by clovett** [comment]
you're right it is working for me again now, weird.
