### ISSUE TITLE
Error in several v3 api catalog index or pages

### ISSUE THREAD

**Issue by zivkan** [NuGet/NuGetGallery#6827]
I was writing something that uses the V3 catalog API according to [the docs](https://docs.microsoft.com/nuget/api/catalog-resource) and found two types of problems.

1. A few pages have an issue where both the index and the page header list the commit id as all zeros. I can't think of any reason why someone would want to use commit id, since it doesn't enable any feature that timestamp can't provide. But according to the docs it should have the value of the commit that matches the timestamp, so it's objectively wrong.

2. The index has the wrong number of commits, the wrong commit timestamp and the wrong commit id for a few pages. It's like the page was updated correctly (header matches items in list), but the index page was not updated.

My program reads the catalog multiple times, so I cache the pages on disk. To detect when new packages are added (or packages deleted), I compare the package count, commit timestamp and commit id in the catalog index item to the cache page's header. The bugs above cause my program to re-download several pages every execution.

Below is the list of pages my program detected with issues:

Page # | Property | index | page header | page item with highest timestamp
------- | -------- | ------ | --------- | --------
|page0.json|Count|540|540|540|
||time stamp|2015-02-01T06:30:11.7477681Z|2015-02-01T06:30:11.7477681Z|2015-02-01T06:30:11.7477681Z
||commit id|00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000|19a4aedc-5139-4df5-81a3-b40aeabb3f3c
|page26.json|Count|540|540|540
||time stamp|2015-02-01T10:59:39.9767757Z|2015-02-01T10:59:39.9767757Z|2015-02-01T10:59:39.9767757Z
||commit id|00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000|325245e3-cf80-4b1a-919d-c0702edc1878
|page28.json|Count|540|540|540
||time stamp|2015-02-01T11:23:46.8866726Z|2015-02-01T11:23:46.8866726Z|2015-02-01T11:23:46.8866726Z
||commit id|00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000|ae14c85a-3b76-46b5-9766-b35683acf3f7
|page30.json|Count|540|540|540
||time stamp|2015-02-01T11:50:04.0835313Z|2015-02-01T11:50:04.0835313Z|2015-02-01T11:50:04.0835313Z
||commit id|00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000|403b4583-702a-4eb3-b263-6c0d2967538f
|page29.json|Count|540|540|540
||time stamp|2015-02-01T11:36:32.0153363Z|2015-02-01T11:36:32.0153363Z|2015-02-01T11:36:32.0153363Z
||commit id|00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000|65c10ceb-a0f1-4eba-b99c-18e5f6c9ff6b
|page1313.json|Count|550|552|552
||time stamp|2016-01-15T16:18:09.8452301Z|2016-01-15T16:18:13.8407352Z|2016-01-15T16:18:13.8407352Z
||commit id|c652a5a3-a0ad-4986-bcf3-229aa33af5b0|3c10fced-9fd1-4ecc-a9a9-ecba436a454b|3c10fced-9fd1-4ecc-a9a9-ecba436a454b
|page1300.json|Count|549|550|550
||time stamp|2016-01-13T22:11:37.7649356Z|2016-01-13T22:11:49.1579762Z|2016-01-13T22:11:49.1579762Z
||commit id|7c51a2eb-dc87-40a8-831b-83469b2526d7|dae05307-06a5-4954-aeaf-567b88c6b266|dae05307-06a5-4954-aeaf-567b88c6b266
|page1309.json|Count|548|550|550
||time stamp|2016-01-15T04:02:48.8858301Z|2016-01-15T04:02:56.9796327Z|2016-01-15T04:02:56.9796327Z
||commit id|02842ef9-7e5c-4df5-9dad-fa09bf7675da|ac9f13d7-bd08-4df5-b562-994a9ff0df18|ac9f13d7-bd08-4df5-b562-994a9ff0df18
page1367.json|Count|550|551|551
||time stamp|2016-02-11T10:00:49.8705942Z|2016-02-11T10:00:55.9548404Z|2016-02-11T10:00:55.9548404Z
||commit id|a6fb5dc0-ab0d-4d6d-9f66-65f1c7b0e188|b4376f7c-98f0-4a69-96df-975b8d083379|b4376f7c-98f0-4a69-96df-975b8d083379
|page1436.json|Count|548|549|549
||time stamp|2016-03-12T07:06:56.3828123Z|2016-03-12T07:07:06.3777682Z|2016-03-12T07:07:06.3777682Z
||commit id|bb0c5083-a8cd-4bba-b49e-d877b58bf853|12a57072-5065-44be-b872-24564369aff1|12a57072-5065-44be-b872-24564369aff1

**Comment by skofman1** [comment]
@joelverhagen ?

**Comment by joelverhagen** [comment]
Yeah, this is a bug. It all from early 2016 so I don't think the bug exists anymore. IMO this priority is relatively low since our sample catalog reader and our internal Collector infrastructure has no problem with this.

It could pose problems to custom implementations as @zivkan mentioned. And it clearly goes against our docs.

I think we should do a manual fix-up of the catalog JSON blobs. This on its own is actually a little complex because it would require stopping feed2catalog for a short time.

**Comment by agr** [comment]
There are issues with leaves as well: for example, see `releaseNotes` [here](https://api.nuget.org/v3/catalog0/data/2018.03.11.05.06.09/fluentconsoleapplication.0.1.0.json) and that's not the only kind of issues with leaves.

**Comment by joelverhagen** [comment]
Another problem is **multiple versions in the dependency range**.

Handling:
- [Pick first](https://github.com/NuGet/NuGet.Services.Metadata/blob/0c69b9dd47e01125c22f72c1e27cf3cdafc65233/src/NuGet.Protocol.Catalog/Serialization/PackageDependencyRangeConverter.cs#L19-L26)

Example:
- https://api.nuget.org/v3/catalog0/data/2016.02.21.10.24.50/dingu.generic.repo.ef7.1.0.0.json

**Comment by joelverhagen** [comment]
I fixed these data problems.

Here is the tool I wrote to detect and report all of the problems. The tool reports no more problems.
https://gist.github.com/joelverhagen/b50c44dcb6d1cbd5b6031773449630cd

I opened a new item to track catalog leaf data bugs: https://github.com/NuGet/NuGetGallery/issues/9744
