### ISSUE TITLE
 problems with push packages to nuget gallery (500 + 409)

### ISSUE THREAD

**Issue by nixon89** [NuGet/NuGetGallery#6833]
Hello. I have self-hosted nuget gallery on IIS and there are some problems with push packages to nuget gallery
On IIS enabled Failed Request Tracing module to cath errors.
I have valid API-key with correct rights for push nuget-packages to nuget gallery/
## Details about problem
To reproduce problem, i generate test package with script:
$id = kalinin-na-test-package
$myversion iterate from 1 to 99.
```
.\new-testpackage.ps1 -Id "$id" -Version "0.0.$myversion" -Title "test" -Description "desc"
```
In result i have 99 `.nupkg` files with id `kalinin-na-test-package`. 
For example `kalinin-na-test-package.0.0.18.nupkg`
Then i push packages from `nuget.exe` or from `nuget publish step in teamcity` (in reality - nuget publish step use nuget.exe too):
$myapikey = 'my-valid-apikey'
```
nuget.exe push .\*.nupkg -apikey $myapikey -Source http://nuget.mysite -Verbosity detailed
```
And in result i have error:
```
Starting: C:\buildAgent\tools\NuGet.CommandLine.4.9.2\tools\NuGet.exe push C:\buildAgent\work\30a63b1383db36e2\kalinin-na-test-package.0.0.1.nupkg ******* -Verbosity detailed -Source http://nuget.mysite
in directory: C:\buildAgent\work\30a63b1383db36e2
NuGet Version: 4.9.2.5706
Pushing kalinin-na-test-package.0.0.1.nupkg to 'http://nuget.mysite'...
  PUT http://nuget.mysite/api/v2/package/
  InternalServerError http://nuget.mysite/api/v2/package/ 186ms
  PUT http://nuget.mysite/api/v2/package/
  Conflict http://nuget.mysite/api/v2/package/ 33ms
Response status code does not indicate success: 409 (A package with ID 'kalinin-na-test-package' and version '0.0.1' already exists and cannot be modified.).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (A package with ID 'kalinin-na-test-package' and version '0.0.1' already exists and cannot be modified.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__23_0(HttpResponseMessage response)
	   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()
```
### There are two interesting moments:
1. `InternalServerError http://nuget.mysite/api/v2/package/ 186ms`
2. `System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (A package with ID 'kalinin-na-test-package' and version '0.0.1' already exists and cannot be modified.)` 

### 1st error
About 1st error code (Internal Server Error) (looks like 500, right?) in Failed Request Tracing module in IIS i find report:
```
Warning 
-MODULE_SET_RESPONSE_ERROR_STATUS 
ModuleName
ManagedPipelineHandler 
Notification
EXECUTE_REQUEST_HANDLER 
HttpStatus
500 
HttpReason
The parameter 'to' cannot be an empty string. Parameter name: to 
HttpSubStatus
0 
ErrorCode
The operation completed successfully.
 (0x0) 
ConfigExceptionInfo
 ManagedPipelineHandler 
```
In this case, very interesting `The parameter 'to' cannot be an empty string. Parameter name: to `
What is parameter `to`? I don't know and don't set this parameter whem push my packages.

### 2nd error
About 2nd error code (409):
I check in web nuget gallery and in database and in file storage directory, and yes, package with ID 'kalinin-na-test-package' and version '0.0.1' already exists. But before push i check it to, and this package don't exists anywhere (only on my laptop in local directory).
Question: why nuget.exe try to push package again in gallery? Looks like it think, that Internal Server Error is bad request and try again to push package, but in reality package was pushed to gallery after first attempt.

I completly delete this package from my nuget gallery, and try to push againt from **all clients** dicribed in `NuGet product used` section below, and that behavior repeats again and again.

## NuGet product used
Nuget Gallery
nuget-4.1.0.exe
nuget-4.3.0.exe
nuget-4.4.1.exe
nuget-4.5.1.exe
nuget-4.6.2.exe
nuget-4.7.1.exe
nuget-4.8.1.exe
nuget-4.9.2.exe
Nuget Publish step in Teamcity ( https://confluence.jetbrains.com/display/TCD10/NuGet+Publish )

**Comment by nixon89** [comment]
FYI:
before this error catched, i configure sending emails in my gallery. 
String with my email setting in Web.config looks like:
`<add key="Gallery.SmtpUri" value="smtp://nugetgallery:mypassword@smtp.mysite:25" />`
Email messages sends very well to users. This means that the setting should work correctly. (I think)
PS: There is comment in webconfig
`<!-- SmtpUri is expected to be of the format: smtps://username:password@host:port. Note that if username contains an "@", you need to URI Encode it! -->`
My password dont contains an "@" or another special characters

In my case **500** error HttpReason contains:
`The parameter 'to' cannot be an empty string. Parameter name: to `
Maybe configuring email settings is the reason of 500 error? But emails send correctly. Very strange

**Comment by nixon89** [comment]
I disable `Gallery.SmtpUri` setting in gallery webconfig and check again. And result same: 500 + 409 error

**Comment by nixon89** [comment]
I think i find a bug in gallery.
#### How push nuget packages works fine:
1. user `my-test-user` and correct API key from this user
2. in webconfig **enable** email setting like `<add key="Gallery.SmtpUri" value="smtp://nugetgallery:mypassword@smtp.mysite:25" />`
3. in web interface **enabled** `Account settings -> Email Notifications -> Notify when a package is published to Kontur NuGet Gallery'
4. `nuget.exe push .\*.nupkg -apikey $myapikey -Source http://nuget.mysite -Verbosity detailed`
5. packages push correct and email delivered to `my-test-user`'s email

#### How push nuget packages return 500 + 409 errors:
1. user `my-test-user` and correct API key from this user
2. in webconfig **enable** email setting like `<add key="Gallery.SmtpUri" value="smtp://nugetgallery:mypassword@smtp.mysite:25" />`
3. in web interface **disabled** `Account settings -> Email Notifications -> Notify when a package is published to Kontur NuGet Gallery'
4. `nuget.exe push .\*.nupkg -apikey $myapikey -Source http://nuget.mysite -Verbosity detailed`
5. 500 + 409 error like in first message of this issue and email dont sent to `my-test-user`'s email

I checked each scenario three times, and I'm sure the problem is exactly in setting up notifications in the web interface.

**Comment by scottbommarito** [comment]
Hey @nixon89,

This looks identical to a bug we had a couple months ago.
https://github.com/NuGet/NuGetGallery/issues/6632

Have you updated your self-hosted gallery recently?
I would sync with current master and see if it fixes your issue.

**Comment by nixon89** [comment]
@scottbommarito hello, thnx for link to #6632 
My gallery installation based on Commits near Oct 17, 2018
In the near future I will try to update my gallery installation and check if it fixes or no

**Comment by skofman1** [comment]
@nixon, please let us know if you still experience the issue after getting the latest version of Gallery. 
Closing for now.

**Comment by nixon89** [comment]
@scottbommarito @skofman1 hello. I finaly install actual version of nuget gallery from master (7a0ed71f4c1f608b01d0947132123197b9bea839) in my development environment, and problem is gone. Thank you very much
