### ISSUE TITLE
Search returns results in no discernable order

### ISSUE THREAD

**Issue by davkean** [NuGet/NuGetGallery#6835]
I cannot figure out the order in which gallery returns search results. If I search for "FxCop", it's returning old packages that haven't been updated in 4 years and have very little downloads ahead of a package that has over 1 million downloads and was last updated 2 weeks ago.

![image](https://user-images.githubusercontent.com/1103906/51583193-83f99880-1f23-11e9-8ce4-223a4706e022.png)

Google and Bing both return results I expect:

https://www.google.com.au/search?source=hp&ei=re1HXOCMOcqP9QOHvaXwBA&q=FxCop+site%3Anuget.org&btnK=Google+Search&oq=FxCop+site%3Anuget.org
https://www.bing.com/search?q=FxCop+site%3Anuget.org&qs=n&form=QBLH&sp=-1&pq=fxcop+site%3A&sc=0-11&sk=&cvid=D4C623BA1F304A9C954F019ED3874526

**Comment by davkean** [comment]
Note, we since delisted those packages so while this doesn't repro _now_, the bug/results are still broken.

**Comment by skofman1** [comment]
@davkean , thanks for reporting! We are working on rebuilding our search service (https://github.com/NuGet/NuGetGallery/issues/6371) and will improve search results as part of this work. 
We are using the issue [here](https://github.com/NuGet/NuGetGallery/issues/4124) to collect examples of search terms that are not getting correct results. I copied your feedback there. Feel free to update it with more examples you find!
