### ISSUE TITLE
[Investigate] Last 6 weeks statistics week start

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#6838]
Related to #6836.

I've noticed the discrepancy between the statistics shown on Gallery stats page and the data we have in statistics DB.

In `Dimension_Date` table in stats DB we have weeks starting on Sundays:
![image](https://user-images.githubusercontent.com/102933/51632124-63214b00-1f03-11e9-9347-891d9f4831e0.png)

And this table is used to produce weekly reports (queries [group by](https://github.com/NuGet/NuGet.Jobs/blob/5877dfb713bcfd8fe610133c9835995771eefe66/src/Stats.Warehouse/Programmability/Stored%20Procedures/dbo.DownloadReportLast6Weeks.sql#L31-L47) `WeekOfYear` column).

The [statistics page](https://www.nuget.org/stats) seem to use Monday as the first day of the week:
![image](https://user-images.githubusercontent.com/102933/51632275-bc897a00-1f03-11e9-976d-75298634cd0e.png)

But at the same time it displays data produced by the queries that group by `WeekOfYear`, so there is likely some misrepresentation.

Need to confirm that and figure out how to address it properly.

**Comment by skofman1** [comment]
@agr, what's the status here?

**Comment by agr** [comment]
The issue was fixed and deployed to DEV/INT/PROD.
Fix was incomplete, and follow-up fix is tracked by https://github.com/NuGet/Engineering/issues/2133.
