### ISSUE TITLE
[Repository signing] Update index.json to show all nuget.org packages are signed

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6841]
* [x] DEV China monitor https://icm.ad.msft.net/imp/v3/incidents/details/114417773/home
* [x] INT monitor https://icm.ad.msft.net/imp/v3/incidents/details/114419297/home

Also:
* [x] Update docs [#1391](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1391)
* [x] Find out how to see restore failures from client telemetry
* [X] 2.1.6xx and 2.2.2xx will GA with VS 16.0 on April 2nd ~~Find when dotnet.exe will be released with latest bits~~
* [x] Deploy monitoring [#887](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetMonitoring/pullrequest/887?_a=overview)
* [ ] Deploy the service index
  * [x] Prepare a deployment of  the current service index for rollback. Use https://github.com/NuGet/NuGet.Services.Index/commit/8a798306cb629fc901f3f668b9f9db0635c70341
  * [x] Deploy the monitor
  * [x] Deploy the new service index to PROD ([#55425](https://nuget.visualstudio.com/NuGetBuild/_build%2Fresults?buildId=55425&_a=summary))
  * [ ] ~~After an hour, rollback the PROD deployment~~
  * [x] Check the client's telemetry, look for restore failures
  * [ ] ~~If nothing suspicious, redeploy the service index~~
  * [ ] Deploy the new service index to PROD China ([#55459](https://nuget.visualstudio.com/NuGetBuild/_build%2Fresults?buildId=55459&_a=summary))
* [ ] Clean up the 4.9.0 repository signing resource
  * [ ] Wait until blob storage logs indicate that no one is loading the 4.9.0 resource
  * [ ] Delete the 4.9.0 resource by hand

# Client Telemetry

[Failed solution restores](https://aka.ms/kwe?cluster=ddteldata.kusto.windows.net&database=ClientTools&q=H4sIAAAAAAAAA3XOT0vDQBAF8LvgdxhySqC0ePJUQUQllyL%2BOYnINPvaLGRny%2BwkVfHDu66HqtDzvPebd8%2F76wliaTXewuj05JP2PRR06SaWDu4BOkEffUAyDrsn6%2BiCeBvrc9f8ihdkxQG0XFI1pYWMW9hCcysqvGyiBjYfpTp02tSKQYWH79KGh4TD8U7jDmoe6Tlz88LN8wQbU%2FVSntywH%2BCKl8YQWP0HKPBbfXx6Q%2Bv3n6mtm9FVzyIYWveX6OIoVpfo2kudxdfj4ozO%2BuYfpRAHJcuxrme1L4HArStkAQAA):

```
RawEventsNuGet 
| where AdvancedServerTimestampUtc > ago(7d) 
| where EventName == "vs/nuget/restoreinformation"
| where IsInternal == false
| where Properties["vs.nuget.status"] == "Failed"
| summarize max(AdvancedServerTimestampUtc) by EventId, ChannelId
| summarize count() by bin(max_AdvancedServerTimestampUtc, 1h), ChannelId
| render timechart
```

[Failed project restores](https://aka.ms/kwe?cluster=ddteldata.kusto.windows.net&database=ClientTools&q=H4sIAAAAAAAAA3WPQUsDMRBG7wX%2Fw7inXSitnjy1UKRIL0XUnkRkmoy7Kc1kmcxmVfzxhnioCj3Pe49vHnBcJ2KN2%2BGO9GLyBWNHQrCyCdmQfSRJJE%2FOU1T0%2FU4NLAHbUN%2FY5kSXxBY9wWIBVYpzHlrSeS%2FhQEYlu0HI8VsQj%2BoCVyf1XkJPoo7icxZnRZyNKOy4NcFSrF7gMkd%2FKbtIsjo6jOVQjJhMAeLgPYr7JPD4Xp9%2FooH9x8%2FqjZ3CbYfMdNzYvwkTBta6oHvHdS6%2Bni9O4frKN%2F9aQmxJQDNnOhT9BgK78HNuAQAA)

```
RawEventsNuGet
| where AdvancedServerTimestampUtc > ago(7d)
| where EventName == "vs/nuget/projectrestoreinformation"
| where Properties["vs.nuget.warningcodes"] != ""
| where UserAlias != "nugetsvc"
| summarize max(AdvancedServerTimestampUtc) by EventId, ChannelId
| summarize count() by bin(max_AdvancedServerTimestampUtc, 10m), ChannelId
| render timechart
```

[Project restore warning codes](https://aka.ms/kwe?cluster=ddteldata.kusto.windows.net&database=ClientTools&q=H4sIAAAAAAAAA42QwUrDQBCG74LvMObSBEJ7Eg8SoQfxVkQtHkRkshmTle5umJ1sovjwris1Uih4G5j5vp9%2F7nC8DmTFb4YbktOTTxg7YoJ1E9Aqau6JA%2FGDNuQFTb8VBVeArcsvmmK%2BTooNGoKqgiz4lR1aklXP7o2UcGQdk7avjg2Kdjab0Vt2PbFo8k8RXCZwOSJbbVvlGvLZM5xF6R9k64nXO40%2BLRLhg0oHNAnZBh5%2FeA8ViPPCcc7%2FEZQa%2BcEYZP1BYHDKj%2F%2BhgPr9N%2BgbNIGmHmO673da8v2qhMXl4sCs3GAlT4Za2zwGvRwPKuG8K8q5yF6cnBzrEkONrDpk%2BQJBP4FOzwEAAA%3D%3D)

```
RawEventsNuGet
| where AdvancedServerTimestampUtc > ago(7d)
| where EventName == "vs/nuget/projectrestoreinformation"
| where Properties["vs.nuget.warningcodes"] != ""
| where UserAlias != "nugetsvc"
| extend Warnings = tostring(Properties["vs.nuget.warningcodes"])
| summarize max(AdvancedServerTimestampUtc) by Warnings
| mvexpand split(Warnings, ';')
| summarize count() by bin(max_AdvancedServerTimestampUtc, 5h), tostring(Warnings)
| render barchart
```

Filter with `todatetime('2019-04-09T21:00:00.000Z')`

**Comment by loic-sharma** [comment]
Blocked by https://github.com/NuGet/Home/issues/7748

**Comment by loic-sharma** [comment]
Research on possible solutions on [this OneNote](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Specs.one%7C910181C5-8695-4A1C-9792-A56DBB86F1C3%2FService%20Index%20User%20Agent%20Sniffing%7C60A2909A-F498-4776-BE0F-3754AF949925%2F%29onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Specs.one#Service%20Index%20User%20Agent%20Sniffing&section-id={910181C5-8695-4A1C-9792-A56DBB86F1C3}&page-id={60A2909A-F498-4776-BE0F-3754AF949925}&end).

**Comment by skofman1** [comment]
@loic-sharma , related issue:
The URLs for repository signature information look like this: https://api.nuget.org/**v3-index**/repository-signatures/4.7.0/index.json

They should be aligned to other resources to use URL rewrite rules:
https://api.nuget.org/**v3/index**/repository-signatures/4.7.0/index.json

**Comment by loic-sharma** [comment]
# Rollback instructions

1. :warning: *Optional*: Disable the `Run end-to-end tests on the staged service index` task for [`NuGet.Service.Index`](https://nuget.visualstudio.com/NuGetBuild/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=108&view=Tab_Tasks) deployment
1. Change the variables of [`NuGet.Services.Index`](https://nuget.visualstudio.com/NuGetBuild/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=108&view=Tab_Variables)'s deployment
    1. Update `Azure.StorageAccount.Key` to the value of `Prod-NuGetGalleryStorage-Key` from the NuGet Prod Key Vault
1. Queue a new deployment of [`NuGet.Services.Index`](https://nuget.visualstudio.com/NuGetBuild/_build?definitionId=108), set the value of `Environment
` to PROD
