### ISSUE TITLE
External URLs on package details page should open in a new tab upon click

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6846]
This is a proposal and my hypothesis is that external URLs should be a new tab upon click. External links include:
* ProjectUrl
* License and LicenseUrl
* Source code
Release notes and other links on the package details page.

**Comment by loic-sharma** [comment]
Could you explain your hypothesis further? NPM, Ruby Gems, Packagist, and Pypi all open external links in the current tab.

**Comment by anangaur** [comment]
My hypothesis was that generally folks would want to keep the details page open and go to the new tab for external links for additional info. I discussed more with UX on this and its seems having links open inline is a better idea as an individual can always choose to open in a new through browser/click options. Hence closing this issue as `Won't Fix`
