### ISSUE TITLE
Default into 2FA upon new user sign up

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6858]
Once a new user sign's up using MSA, 2FA should be enabled. Users can disable if they wanted to.

**Comment by skofman1** [comment]
We need to make sure the users gets a visible notification in UI that 2FA is applied on his account.

**Comment by skofman1** [comment]
@anangaur , we didn't discuss details of the experience, so moving this task back to backlog.

**Comment by dannyjdev** [comment]
Closing this issue since it was completed by this task https://github.com/NuGet/NuGetGallery/pull/9035.
