### ISSUE TITLE
Gallery Deployment 1/31/2019

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6868]
Need to deploy the commit created by https://github.com/NuGet/NuGetGallery/pull/6859

[Build ](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2384620 )
[Commit](https://github.com/NuGet/NuGetGallery/commit/9f578da47bbb8d6c83112512e3ec5c6a715629b6)
- [ ] INT
    - [x] Apply migrations
    - [x] Deploy USNC
    - [ ] Verify USSC deployment succeeds
- [ ] PROD
    - [x] Apply migrations
    - [x] Deploy USNC
    - [ ] Verify USSC deployment succeeds

**Comment by cristinamanum** [comment]
[Build ](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2382914 )
[Commit](https://github.com/NuGet/NuGetGallery/commit/9f578da47bbb8d6c83112512e3ec5c6a715629b6)
