### ISSUE TITLE
How to add binding redirects in web config through NuGet packages installation

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/NuGetGallery#6873]
Hi Everyone, 

I have prepared the sample MVC4 NuGet package for my dll with the dependent of the following NuGet packages compression.base, officeChart.base. I have installed my custom MVC4 NuGet pacakge in ASP.NET MVC project with framework version 4.5.2. After installation completed all dependent assembly entries are placed under the binding redirect tag of the webconfig file. But, I didn't add this entry in my NuGet packages and I don't aware regarding how this entries are added after install my NuGet packages. 

`<dependentAssembly>
        <assemblyIdentity name="Compression.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4451.0.4" />
</dependentAssembly>
<dependentAssembly>
        <assemblyIdentity name="OfficeChart.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4451.0.4" />
 </dependentAssembly>`

Could you please update the details regarding how this entries are placed in the web config file while install the NuGet packages. 

Also, Could you please suggest me how can I overwrite this entries from my side through NuGet packages installation like below 

`<dependentAssembly>
        <assemblyIdentity name="Compression.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4400.0.4" />
</dependentAssembly>
<dependentAssembly>
        <assemblyIdentity name="OfficeChart.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4400.0.4" />
 </dependentAssembly>`

Could you please suggest me regarding this?

Thanks,

Ganesan R.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Home #7763](https://github.com/NuGet/Home/issues/7763) via [**ZenHub**](https://www.zenhub.com/)
