### ISSUE TITLE
SmartCosmos-SDK-Net package download stats

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#6883]
Is this some kind of bug? Or abuse? How did smartcosmos-sdk-net become 2nd in a very short time?

![image](https://user-images.githubusercontent.com/5808377/52527841-a5060b80-2ccf-11e9-866e-5139f8efc29e.png)

(last updated: 2 years ago)

https://www.nuget.org/packages/smartcosmos-sdk-net/

**Comment by 304NotModified** [comment]
![image](https://user-images.githubusercontent.com/5808377/52635324-df3afd00-2ec9-11e9-9f81-cd5c0a7ab9cd.png)

**Comment by chenriksson** [comment]
@304NotModified We are looking into this issue. Thank you for reporting!

**Comment by chenriksson** [comment]
The issue has been addressed, but could take up to a day for changes to propagate.

**Comment by shishirx34** [comment]
fix deployed
