### ISSUE TITLE
embedded license file causes validation error that the text file wasn't UTF8 encoded

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#6884]
see https://github.com/NuGet/Home/issues/7733 for more details. Package attached.
[MyPackageEsriIncTest.1.0.4.nupkg.zip](https://github.com/NuGet/NuGetGallery/files/2849069/MyPackageEsriIncTest.1.0.4.nupkg.zip)

**Comment by skofman1** [comment]
@karann-msft , from the original issue (NuGet/Home#7733) seems that the recommendation is to add client side validation. What is the suggested work form server?

**Comment by karann-msft** [comment]
I was hoping if the server can confirm that the file was indeed not UTF8 encoded and the should have been accepted.

**Comment by skofman1** [comment]
In the original issue it was stated that the file contained a non-UTF-8 character. 
@agr , do you think we can improve the error message and show the location of the "bad" char?

**Comment by agr** [comment]
The file indeed has a bad character in line 295. We might be able to produce a nicer error message, for that specific case (a text file with one stray character) specifying the line number, but for files that are actually binary that message might be nonsensical (binary files don't have a concept of line). Unless we want to implement some algo that would distinguish between those two cases.

**Comment by karann-msft** [comment]
Ok, now that we know that the file indeed has a bad character, the more important this here is for the client to do the same check as the gallery and warn if the file has such issues which would make it unacceptable to the gallery.

**Comment by skofman1** [comment]
@karann-msft , can I close the issue?

**Comment by karann-msft** [comment]
Closing issue since the gallery was right in rejecting the file as it did have a non UTF8 character.
