### ISSUE TITLE
[Azure Search] Balance score weights for all searchable fields.

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6904]

**Comment by loic-sharma** [comment]
@shishirx34 Has updated the scoring profile, it seems scoring isn't properly reflecting profile expected behavior. Fix bug, then this issue can be closed for now.

**Comment by loic-sharma** [comment]
Current scoring profile in code has `FreshnessScoringFunction` that should be reevaluated

**Comment by loic-sharma** [comment]
* [ ] Merge dev->master https://github.com/NuGet/NuGet.Services.Metadata/pull/532
* [ ] Update configs [NuGetDeployment#923](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/923?_a=files)
* [ ] Rebuild index https://github.com/NuGet/Engineering/issues/2470
