### ISSUE TITLE
Self-contained package readme

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6908]
Specs:
https://github.com/NuGet/Engineering/wiki/Packaging-Icon,-License-and-Documentation-within-the-nupkg
https://github.com/NuGet/Engineering/wiki/Packaging-Documentation-within-the-nupkg

Updated one:
https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg

**Comment by agr** [comment]
Features is release. Bugs are expected and shouldn't be a part of an epic.
