### ISSUE TITLE
Problem configuring AzureStorage

### ISSUE THREAD

**Issue by bvduijn** [NuGet/NuGetGallery#6913]
Hi

I've cloned this project and plan to Run it on Azure app services. As described in the manual I created a storage account (V2) and copied the storage connectionstring and updated the web.config.

When browsing the deployed site I get an error 500. If I change back the Gallery.Storagetype to Filesystem the site starts perfectly. Chinging it to AzureStorage makes it fail. In the logging I can see these messages

Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-02-21T07:47:42.6949793Z","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"avebenugetgallery.azurewebsites.net","ai.cloud.roleInstance":"RD0003FF558D08","ai.cloud.role":"AvebeNuGetGallery"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"saopwebapiweu01/content","id":"UxmGqnqtX3s=","data":"https://saopwebapiweu01.blob.core.windows.net:443/content/Login-Discontinuation-Configuration.md","duration":"00:00:00.3320000","resultCode":"404","success":false,"type":"Azure blob","target":"saopwebapiweu01.blob.core.windows.net","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'System.Net.WebException' in Microsoft.WindowsAzure.Storage.dll
'w3wp.exe' (CLR v4.0.30319: /LM/W3SVC/101618433/ROOT-3-131952088373306219): Loaded 'D:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Mobile\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Mobile.dll'. Cannot find or open the PDB file.
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
'iexplore.exe' (Script): Loaded 'Script Code (Windows Internet Explorer)'. 
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
ContentService Error: 0 : [C:\Git\chocolatey\VSProjects\NuGetGallery\src\NuGetGallery\Services\ContentService.cs:133 in RefreshContentFromFile] Requested Content File Not Found: Login-Discontinuation-Configuration.md
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2019-02-21T07:47:43.3087657Z","tags":{"ai.internal.sdkVersion":"sd:2.2.0-220","ai.internal.nodeName":"avebenugetgallery.azurewebsites.net","ai.cloud.roleInstance":"RD0003FF558D08","ai.cloud.role":"AvebeNuGetGallery"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"[C:\\Git\\chocolatey\\VSProjects\\NuGetGallery\\src\\NuGetGallery\\Services\\ContentService.cs:133 in RefreshContentFromFile] Requested Content File Not Found: Login-Discontinuation-Configuration.md","severityLevel":"Error","properties":{"EventId":"0","DeveloperMode":"true"}}}}
ContentService Stop: 3 : [C:\Git\chocolatey\VSProjects\NuGetGallery\src\NuGetGallery\Services\ContentService.cs:124 in RefreshContentFromFile] Finished Downloading Content Item: Login-Discontinuation-Configuration.md. Duration 711.13ms
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2019-02-21T07:47:43.3228085Z","tags":{"ai.internal.sdkVersion":"sd:2.2.0-220","ai.internal.nodeName":"avebenugetgallery.azurewebsites.net","ai.cloud.roleInstance":"RD0003FF558D08","ai.cloud.role":"AvebeNuGetGallery"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"[C:\\Git\\chocolatey\\VSProjects\\NuGetGallery\\src\\NuGetGallery\\Services\\ContentService.cs:124 in RefreshContentFromFile] Finished Downloading Content Item: Login-Discontinuation-Configuration.md. Duration 711.13ms","severityLevel":"Verbose","properties":{"EventId":"3","DeveloperMode":"true"}}}}
ContentService Start: 4 : [C:\Git\chocolatey\VSProjects\NuGetGallery\src\NuGetGallery\Services\ContentService.cs:124 in RefreshContentFromFile] Starting Downloading Content Item: Login-Discontinuation-Configuration.json
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2019-02-21T07:47:43.3228085Z","tags":{"ai.internal.sdkVersion":"sd:2.2.0-220","ai.internal.nodeName":"avebenugetgallery.azurewebsites.net","ai.cloud.roleInstance":"RD0003FF558D08","ai.cloud.role":"AvebeNuGetGallery"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"[C:\\Git\\chocolatey\\VSProjects\\NuGetGallery\\src\\NuGetGallery\\Services\\ContentService.cs:124 in RefreshContentFromFile] Starting Downloading Content Item: Login-Discontinuation-Configuration.json","severityLevel":"Verbose","properties":{"EventId":"4","DeveloperMode":"true"}}}}
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2019-02-21T07:47:43.3228085Z","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"avebenugetgallery.azurewebsites.net","ai.cloud.roleInstance":"RD0003FF558D08","ai.cloud.role":"AvebeNuGetGallery"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"saopwebapiweu01/content","id":"MPQIHA166rA=","data":"https://saopwebapiweu01.blob.core.windows.net:443/content/Login-Discontinuation-Configuration.json","duration":"00:00:00.1260000","resultCode":"404","success":false,"type":"Azure blob","target":"saopwebapiweu01.blob.core.windows.net","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'System.Net.WebException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll

All the values of Gallery.AzureStorage…...ConnectionString are like DefaultEndpointsProtocol=https;AccountName=<name>;AccountKey=<key>;EndpointSuffix=core.windows.net;

Any idea how to resolve this ?

**Comment by loic-sharma** [comment]
You will need to create a container named "content" in your storage account that contains all of the files in this directory: https://github.com/NuGet/NuGetGallery/tree/master/src/NuGetGallery/App_Data/Files/Content

By the way, do you need to run the NuGet gallery? There are other server implementations, like [BaGet](https://github.com/loic-sharma/BaGet) or [Sleet](https://github.com/emgarten/Sleet) that are easier to setup and support Azure. For a full list of NuGet server implementations, see: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

**Comment by bvduijn** [comment]
Thanks! This step is not really obvious in the installation steps.
