### ISSUE TITLE
Add list of dependent packages

### ISSUE THREAD

**Issue by peetw** [NuGet/NuGetGallery#6914]
As it currently stands, only the dependencies for a given package are listed in the Gallery (see [here](https://i.imgur.com/TNHrpUt.png) f.ex.).

It would be really useful if the list of packages that depend on that package (i.e. the dependent packages) were also listed, similar to the npm gallery (see [here](https://www.npmjs.com/package/react) f.ex.).

**Comment by skofman1** [comment]
Hi @peetw ,
Completely agree. We have this feature high on our backlog. Please see issue here: https://github.com/NuGet/NuGetGallery/issues/4718

Closing this one as duplicate.
