### ISSUE TITLE
Can't upload new package, after switch to MS

### ISSUE THREAD

**Issue by adolya** [NuGet/NuGetGallery#6919]
Hi
After switching from Nuget user to Microsoft account can't upload package.
The package ID 'Nlog.RabbitMQ.Target' is not available.

**Comment by joelverhagen** [comment]
It looks like Nlog.RabbitMQ.Target is owned by the username "adolya". Could you log in using your Microsoft account and verify that the username in the top navbar is "adolya"? Perhaps a new account was created with a new username?

Try taking a look at our account management FAQ. This answers some common nuget.org account and Microsoft account questions:
https://docs.microsoft.com/en-us/nuget/faqs/nuget-faq#nugetorg-account-management

**Comment by adolya** [comment]
Yes, after linking MS account, it displays artdolya username...
But I was still able to login using old username

**Comment by joelverhagen** [comment]
Okay, it looks like during the process of logging in with your Microsoft account, you created a new nuget.org user. From what I understand, you would like to keep you "adolya" username owning the "Nlog.RabbitMQ.Target" package but also enable Microsoft log in for this "adolya" account.

Our team received an account deletion request for your "artdolya" username. I have deleted this account. This should allow you to associate your Microsoft account with your "adolya" username.

Please let me know if you have any further questions.

**Comment by adolya** [comment]
Thanks, now it was linked correctly
