### ISSUE TITLE
Clean the old search code

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6928]
Clean the old search code

**Comment by skofman1** [comment]
When cleaning up, we need to take into account the current implementation of status endpoint. It pings index,json and triggers failover to read-only mode if the file is unreachable:
https://github.com/NuGet/Engineering/issues/2094

The "unintended" side-effect of this code is that when primary blob storage is down, we failover to secondary, which is actually the correct and desired behavior. 
We need to maintain this behavior even after we cleanup the dependency on index.json: when primary blob storage is down we should failover.
