### ISSUE TITLE
Improve the docs/experience for deleting packages

### ISSUE THREAD

**Issue by rrelyea** [NuGet/NuGetGallery#6935]
- Our FAQ has no mention of deleting packages. It is a common request... we should likely list it. (likely with a link to the policy page mentioned next)

- Our delete package policy page doesn't mention that sometime packages are deletable if recent, etc...:
Perhaps something like this in the exceptions section:
"If your package was published very recently, and has very few downloads, packages may be able to be deleted. Submit a support request through [NuGet Gallery](http://www.nuget.org) to start the process."

- The "submit a support request through nuget.org" isn't very helpful... nuget.org has a contact link, but no "support request" link. We should make the suggestion in the previous step be easier to follow.

@karann-msft @anangaur

**Comment by karann-msft** [comment]
> * Our FAQ has no mention of deleting packages. It is a common request... we should likely list it. (likely with a link to the policy page mentioned next)

I have PR out for that

> * Our delete package policy page doesn't mention that sometime packages are deletable if recent, etc...:
  Perhaps something like this in the exceptions section:
  "If your package was published very recently, and has very few downloads, packages may be able to be deleted. Submit a support request through [NuGet Gallery](http://www.nuget.org) to start the process."

That's by design.

> * The "submit a support request through nuget.org" isn't very helpful... nuget.org has a contact link, but no "support request" link. We should make the suggestion in the previous step be easier to follow.

where do we suggest that? docs? nuget.org?

**Comment by karann-msft** [comment]
@rrelyea the docs update is now live. 
https://docs.microsoft.com/en-us/nuget/faqs/nuget-faq#managing-packages-on-nugetorg
https://docs.microsoft.com/en-us/nuget/policies/deleting-packages#exceptions

Looks good?

**Comment by skofman1** [comment]
@karann-msft , can I close?

**Comment by karann-msft** [comment]
@skofman1 - if you ask me, sure! But I didn't open the issue :)
