### ISSUE TITLE
Add Indicator & Info about Signed Packages

### ISSUE THREAD

**Issue by dansiegel** [NuGet/NuGetGallery#6945]
## Description

Similar to what I believe the intent of #4800 was... The NuGet Gallery should show and offer filters packages that are Authenticode Signed. This has the effect of conveying to package consumers that they can trust that the packages they are consuming have not been tampered with and that they are in fact published by the legitimate package author.

Package Consumers should ultimately be able to see the public certificate info just as you currently can on MyGet.org

![screen shot 2019-02-27 at 3 53 04 pm](https://user-images.githubusercontent.com/3860573/53531342-dc363400-3aa7-11e9-9807-5106ee01d6d0.png)

Second I would say just showing that a package is signed is already technically there, but it is only available to the Package Author when they are logged in and viewing their own packages.

![screen shot 2019-02-27 at 3 55 51 pm](https://user-images.githubusercontent.com/3860573/53531547-46e76f80-3aa8-11e9-965b-225b0a259844.png)

**Comment by skofman1** [comment]
// cc @rido-min @anangaur

**Comment by skofman1** [comment]
@dansiegel , we already have a similar issue here: https://github.com/NuGet/NuGetGallery/issues/6882
I'm closing this one as duplicate.
