### ISSUE TITLE
False negative in version validation for dependencies. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#6950]
Originally reported https://github.com/NuGet/Home/issues/6434#issuecomment-468244868 & https://github.com/NuGet/Home/issues/6434#issuecomment-388085545. 

Repro:

Create a project like the following. 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>TestPackageVersion</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="[10.0.3, 11.0.0-0)" />
  </ItemGroup>

</Project>
```

Pack it, and everything gets packed correctly. 

Try to upload and get  `The package manifest contains an invalid Version: '11.0.0-0'`

I could repro the same problem on INT. 

I'm not sure if it's a regression, but this is definitely a valid version (the official client builds it). 

Remove the .zip from the nupkg to get a repro nupkg. 
[ClassLibrary61.1.0.0.nupkg.zip](https://github.com/NuGet/NuGetGallery/files/2916396/ClassLibrary61.1.0.0.nupkg.zip)

@shishirx34 as I think you are on-call. 

//cc @skofman1 @rrelyea 
I think this is high pri and should be fixed very soon. 

fyi @loic-sharma

**Comment by nkolev92** [comment]
Found https://github.com/NuGet/NuGetGallery/blob/5276638fccf406a30f126bf8845dccc75045f0f4/src/NuGetGallery.Core/Packaging/ManifestValidator.cs#L173-L191 and https://github.com/NuGet/NuGetGallery/issues/3226. 

This is a problem because it doesn't allow people to exclude all the prerelease versions of a certain major like in the linked issue.

**Comment by airbreather** [comment]
Duplicate of #6948?

**Comment by nkolev92** [comment]
Yeah, didn't see the linked issue in the original thread. 

I will close this one.
