### ISSUE TITLE
Copyright in Status page footer has © symbol as &#169;

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6983]
Status:

![image](https://user-images.githubusercontent.com/18014088/54152449-78423280-43fa-11e9-92af-2c1ffcd6bcf0.png)

NuGet.org (which shows the symbol correctly):

![image](https://user-images.githubusercontent.com/18014088/54152568-c5be9f80-43fa-11e9-8169-f4f0b0947ecb.png)

**Comment by shishirx34** [comment]
Also it seems the copyright year is two years old.

**Comment by scottbommarito** [comment]
Failed to fix this with the new deployment--for some reason, the `&#169;` isn't being encoded when deployed...will need to fix the config.

**Comment by scottbommarito** [comment]
Verified on USNC. Waiting for USSC.
