### ISSUE TITLE
Zalgo package causes MonitoringProcessor to hang

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6985]
Whenever the MonitoringProcessor job encounters [the package with an ID of `z̡̜͍̈̍̐̃̊͋́a̜̣͍̬̞̝͉̽ͧ͗l̸̖͕̤̠̹̘͖̃̌ͤg͓̝͓̰̀ͪo͈͌`](https://az636225.vo.msecnd.net/v3-catalog0/data/2019.03.02.01.37.44/z%CC%A1%CC%9C%CD%8D%CC%88%CC%8D%CC%90%CC%83%CC%8A%CD%8B%CC%81a%CC%9C%CC%A3%CD%8D%CC%AC%CC%9E%CC%9D%CD%89%CC%BD%CD%A7%CD%97l%CC%B8%CC%96%CD%95%CC%A4%CC%A0%CC%B9%CC%98%CD%96%CC%83%CC%8C%CD%A4g%CD%93%CC%9D%CD%93%CC%B0%CC%80%CD%AAo%CD%88%CD%8C.1.0.0.json) it gets stuck and stops processing packages until it is restarted.

**Comment by scottbommarito** [comment]
Reproduced the hang locally but was unable to figure out the cause of the issue.

**Comment by skofman1** [comment]
Issue moved to [NuGet/Engineering #2319](https://github.com/NuGet/Engineering/issues/2319) via [**ZenHub**](https://www.zenhub.com/)
