### ISSUE TITLE
In place update to 3.2 causes website failure

### ISSUE THREAD

**Issue by chiefengineer** [NuGet/NuGetGallery#6987]
"Could not load file or assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)" is the bug received.
One would think that by simply accepting the presented updates and re-executing the app, this would Just Work. Not so in this case.
What do I need to change?

**Comment by agr** [comment]
Could you please clarify what project you are trying to build?

**Comment by chiefengineer** [comment]
NuGet.Server. You know, the one where one starts out with an empty MVC
project, adds the NuGet.Server package and then executes yielding a
functioning local NuGet server (after setting the web.config appropriately,
of course). One should be able to update based on NuGet's available
"Updates", which I have. The latest was to update from NuGet.SErver 3.1.2
to 3.2. Doing so in place caused the aforementioned bug.
It *is* possible to get a 3.2 version up and running but the steps are:
1. Start with an empty MVC project - UNTOUCHED by any updates. This will be
an empty MVC project as supplied out of VS 2017 15.9.9 as-is.
2. Fetch and apply the NuGet.Server 3.2 package.
3. *Then* apply all other updates as offered by NuGet.

Following the above gets you a running server. Just updating NuGet.Server
in place after applying all the other NuGet-suggested updates as they occur
gets you the failure as mentioned above.

"Bang the Button - It Just Works!"

**Comment by agr** [comment]
Could you please provide the reproduction steps? I am failing to reproduce the issue on my side. I found some upgrade issues (#6988 and #6989) while trying to reproduce, but those seem to be unrelated to your issue.
Also, please, provide the following information (before upgrade):
* Your `packages.config` file;
* Your `web.config` file (withough any secrets, of course);

In your case, it seems, binding redirects update does not happen in web.config.
