### ISSUE TITLE
Implement a resource to help users find the reverse dependencies of their packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7011]
Reverse dependencies, a.k.a dependents...

In other words, allow people to see what depends on their package. Purposes:

- Another metric of popularity, a la PageRank
- Impact of deletion/deprecation of a package
- Curiosity and ego points 🐱 
- Learning how to use a library. Example, if the docs of a good library are not great, you can see how other popular libraries are using it for inspiration.

This could be cool to include in the gallery like what [fuget.org does](https://www.fuget.org/packages/Newtonsoft.Json/dependents).

**Comment by skofman1** [comment]
duplicate: https://github.com/NuGet/NuGetGallery/issues/4718
