### ISSUE TITLE
[Azure Search] Define a ranking for the "empty search query" that doesn't over-value System.* packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7027]

**Comment by joelverhagen** [comment]
Today it comes from 2.x installs and restores. Just download count will look like this:
https://www.nuget.org/stats/packages

Which is not that interesting...

**Comment by joelverhagen** [comment]
Two options here:

1. Take the existing rankings.json and use that. This gets weird after the end of the list.
1. Take the total download count list and introduce an exclude list (System.*, etc).

I am leaning towards option 2 since it will require less maintenance.

In short, we are not looking at this as a hugely important decision as long as the behavior delta between old and new search is not disruptive to our customers.

**Comment by joelverhagen** [comment]
Maybe include this implemention inside the auxiliary2azuresearch job tracked by https://github.com/nuget/nugetgallery/issues/6447.

**Comment by loic-sharma** [comment]
Exclude list idea:

1. Add new field
1. Exclude list in ng-search-data blob, downloaded by db2azuresearch for now. Required index rebuild
1. Do we need a new scoring profile? Only if results are weird

**Comment by joelverhagen** [comment]
The only things this blocks are:

1. Service index pointing to Azure Search
1. Moving 100% of gallery search queries to Azure Search

In other words, we can make the randomized A/B test go to the legacy search all the time for empty search results.
