### ISSUE TITLE
Deleted users are locked out from site until their session token expires

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7033]
1. Log into account A.
2. Delete account A **without logging out**
    - Have a site admin delete you
    - Delete the account from the DB
3. Attempt to browse the gallery.

Any request that loads the current user (`GetCurrentUser`) will throw at https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/ExtensionMethods.cs#L481

**Comment by AraHaan** [comment]
hmm when they delete their account, why not automatically invalidate their session token.

**Comment by scottbommarito** [comment]
https://github.com/NuGet/NuGetGallery/pull/7469
