### ISSUE TITLE
Github documentation markdown is not rendering tables correctly

### ISSUE THREAD

**Issue by Scottj1s** [NuGet/NuGetGallery#7035]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by joelverhagen** [comment]
Thanks for reporting this issue, @Scottj1s. We are working on improving the publishing flow of Markdown readmes in packages (currently referred to as "documentation").

@karann-msft, @zhhyu, what's the plan for Markdown tables in the next iteration of this feature?

**Comment by karann-msft** [comment]
we do have a goal to support md tables.
@Scottj1s  - this work is tracked as part of [Packaging Icon, License and Documentation within the nupkg #29](https://github.com/NuGet/Announcements/issues/29)

**Comment by zhhyu** [comment]
Yes, we will support tables in the new Readme feature and support more Markdown formats soon. Thanks for your suggestion!

**Comment by lyndaidaii** [comment]
I support tables on Nuget.org, Please let us know if you have any further suggestions.
