### ISSUE TITLE
The downloads page should include VS 2019

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#7036]
Now that VS 2019 is released, the downloads page should include a link to it :) 

//cc @rrelyea @skofman1 @anangaur @karann-msft

**Comment by karann-msft** [comment]
my recommendation
![image](https://user-images.githubusercontent.com/16904420/55432548-fef4b600-5547-11e9-8634-22f969c4e6f5.png)

**Comment by nkolev92** [comment]
Maybe we should have links to both 2017 and 2019?

**Comment by karann-msft** [comment]
We only point to VS download page. That page only provides download link for 2019. I don't see why we should be in the business of maintaining download links for old versions of VS.

**Comment by skofman1** [comment]
@karann-msft , we accept contributions ;)

**Comment by nkolev92** [comment]
We kind of have links to download the VS 2015 related NuGet installations already. 

Either way I'm fine :)

**Comment by karann-msft** [comment]
@skofman1 One Microsoft!

**Comment by joelverhagen** [comment]
Done.
https://www.nuget.org/downloads
