### ISSUE TITLE
Local Gallery occasionally throws System.MissingMethodException and needs to be restarted

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7044]
Not sure if this affects PROD or anything, but occasionally when making requests to my local gallery, it throws the following exception and needs to be restarted before it will handle any more requests. Seems to be related to [this line](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/App_Start/DefaultDependenciesModule.cs#L741).

```
System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.String, System.Action`1<System.Net.Http.HttpClient>)'.'
```

**Comment by cristinamanum** [comment]
I could not repo it.
