### ISSUE TITLE
How to interrogate NuGet for the globalPackagesFolder

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/NuGetGallery#7049]
Specifically, I am interfacing from a .NET context. I am taking a dependency on a Git package, which I need to invoke from the command line. But to do that I need to know where that dependency potentially landed. I'm assuming in a ``packages/``, but which ``globalPackagesFolder`` specifically?

For package references, I'm assuming I can do that through at least [NuGet.Common](http://nuget.org/packages/NuGet.Common/4.9.4)?

Thanks!

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/Home #7974](https://github.com/NuGet/Home/issues/7974) via [**ZenHub**](https://www.zenhub.com/)
