### ISSUE TITLE
Microsoft.WindowsAzure.MobileServices not changing the UpdatedAt value present in the EntityData of Microsoft.Azure.Mobile.Server on enableSoftDelete: true.

### ISSUE THREAD

**Issue by vishwajitshep0815** [NuGet/NuGetGallery#7054]
I am facing an issue while using Microsoft.WindowsAzure.MobileServices in my Xamarin.Forms application on below operations.
1) When I delete a record through the mobile app for a table it performs soft delete and the record gets updated in the SQL Server Table(Hosted on Azure Cloud). But in this scenario, the soft-deleted record does not get it's "UpdatedAt" column value changed. So, when the same record is present on different devices, it is not being deleted from there local storage as the MobileServices is not able to compare the changes in the "UpdatedAt" column because we are using incremental sync for multiple devices. This is hindering the syncing process on multiple devices for my application.

Following are the package details that I have in my project:
1) Microsoft.Azure.Mobile.Client.SQLiteStore: 4.1.1
2) Xamarin.Forms: 3.1.0.583944

Further, there is no exception thrown in the sync code written for the mobile sync which using the following steps:
var table = ApplicationSession.CurrentMobileContext.MobileService.GetSyncTable<T>();
await table.PullAsync(tabName, table.CreateQuery(), pushOtherTables: false, 
                    cancellationToken: CancellationToken.None,
                    pullOptions:new PullOptions{ MaxPageSize =100 }
                    );
On the server side, we have implemented soft delete using the following steps in the controllers:
protected override void Initialize(HttpControllerContext controllerContext)
{
            base.Initialize(controllerContext);
            //string databaseName = controllerContext.Request.Headers.GetValues("x-dbname").SingleOrDefault();
            //Change 6 Feb 2019
            string databaseName = ContextHelper.ConnRequestHandler(controllerContext);
            string connectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString.Replace("dbName", databaseName);
            ProjectContext context = new ProjectContext(connectionString);
            DomainManager = new EntityDomainManager<WBSNodeImage>(context, Request, enableSoftDelete: true);
 }
We also tried implementing hard delete by setting the "enableSoftDelete" false. This also does not seem to work.
For the workaround, we have added a trigger from backend service to change the "UpdatedAt" values which do not seem to be a proper way to handle the situation as the Microsoft.WindowsAzure.MobileServices should internal handle this on it own. 
If anyone can provide an update or solution for the same as soon as possible that would be really great.

**Comment by zhhyu** [comment]
Hello, we do not support individual NuGet packages. Please contact the package owner directly using the "Contact Owners" link on the package details page. Or you can contact the "WindowsAzure.MobileServices" team through their GitHub repository.
Thanks!

**Comment by Phony-typescript** [comment]
@zhhyu https://docutils-repulsive449.github.io/rWwymcQuyp0u0bI/
