### ISSUE TITLE
How to get relevant results when searching nuget packages ? 

### ISSUE THREAD

**Issue by Anthony-Breneliere** [NuGet/NuGetGallery#7081]
When I execute the command:

`nuget list microsoft dependencyinjection`, 

I expect to have the exact package name and version I need:
Microsoft.Extensions.DependencyInjection 2.20
and nothing else.

But instead I have a thousand of packages that just have microsoft in their description.

The only reliable way I found to get my package is using a Google search:
https://www.google.com/search?q=nuget+microsoft+dependencyinjection

**Comment by skofman1** [comment]
Hi @Anthony-Breneliere , thanks for reporting. I have added the example you provided to the issue where we gather all problematic search examples: https://github.com/NuGet/NuGetGallery/issues/4124 
The team currently works on improving search relevancy and rankings. Stay tuned for updates!

**Comment by Anthony-Breneliere** [comment]
Thank you, but the issue I mentioned was about the nuget list command and #4124 issue is about the search in nuget.org. The result does not seem the same, even if nuger.org results are not relevent neither.
