### ISSUE TITLE
Cookier Banner does not behavior on the NuGet blog

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#7082]
@unniravindranathan commented on [Mon Oct 09 2017](https://github.com/NuGet/Home/issues/6004)

a) The banner should only show up in the right locales (not in the US).
b) There is no way to dismiss
c) Navigating to an article and coming back to the blog gets rid of the banner (wrong behavior).

---

@emgarten commented on [Thu Nov 09 2017](https://github.com/NuGet/Home/issues/6004#issuecomment-343270613)

Should this be logged on the gallery instead? Home is primarily for the client.

**Comment by nkolev92** [comment]
This is an old issue, not sure if it's still a problem.

**Comment by skofman1** [comment]
We are compliant. Closing.
