### ISSUE TITLE
v2 Search()? API broken when $filter, $orderby, $skip or $top is missing

### ISSUE THREAD

**Issue by matthid** [NuGet/NuGetGallery#7085]
Previously [this function](https://github.com/fsharp/FAKE/blob/952cd476c89f0fd5086c45718f43e987685cb1a4/src/app/Fake.DotNet.NuGet/NuGetVersion.fs#L50-L54) worked. Recently, our tests working with the NuGet gallery started turning red.

While testing around a bit I noticed that the following still works:
`www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='log4net'&targetFramework=''&includePrerelease=false`

As soon as you leave out any of `$filter`, `$orderby`, `$skip`, `$top` or `searchTerm` you receive:

```json
{
    "statusCode": 404,
    "message": "Resource not found"
}
```

Therefore the following fails (which is what we have shipped/used in the function above):
`www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm='log4net'&includePrerelease=false`

And the following works again (and could be a workaround or the fix if this break was intended):
`www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='log4net'`

**Comment by skofman1** [comment]
@matthid , we introduced a throttling rule that has a bug. We rolled it back so your scenario should work again.

**Comment by skofman1** [comment]
@matthid , a question: why do you use V2 API for search? Is there an advantage for using it and not V3 API? Documentation for V3 search is available here: https://docs.microsoft.com/en-gb/nuget/api/search-query-service-resource

A query similar to V2:
`www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm='log4net'&includePrerelease=false`

Will be in V3:
`https://api-v2v3search-0.nuget.org/query?q=log4net&prerelease=false`

**Comment by matthid** [comment]
> @matthid , a question: why do you use V2 API for search? Is there an advantage for using it and not V3 API?

Not really. We shouldn't even use the search API for this particular function/use case. It was probably contributed and never modified because it "worked"

Anyway, thanks for the quick fix. Feel free to close.

**Comment by loic-sharma** [comment]
> Not really. We shouldn't even use the search API for this particular function/use case. It was probably contributed and never modified because it "worked"

Would FAKE be open to move to the NuGet's V3 APIs? These APIs scale better and are significantly more performant in countries like China. You can find  documentation for the V3 APIs [here](https://docs.microsoft.com/en-us/nuget/api/overview), but we'd be happy to help the FAKE team with any questions!

**Comment by loic-sharma** [comment]
* [Get latest version](https://github.com/fsharp/FAKE/blob/952cd476c89f0fd5086c45718f43e987685cb1a4/src/app/Fake.DotNet.NuGet/NuGetVersion.fs#L50-L54) - This can be implemented using V3's [enumerate package versions API](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#enumerate-package-versions). Example: https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
* [Get metadata](https://github.com/fsharp/FAKE/blob/952cd476c89f0fd5086c45718f43e987685cb1a4/src/app/Fake.DotNet.NuGet/NuGet.fs#L763) - This can be implemented using V3's [package metadata API](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource). Example: https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json

Please let us know if you need more info!

**Comment by matthid** [comment]
> Would FAKE be open to move to NuGet's V3 APIs?

Sure. it boils down to someone tracking all usages and replacing them. I'd accept such PRs.
In this particular instance, I tried myself by using the official NuGet packages: https://github.com/fsharp/FAKE/pull/2294
