### ISSUE TITLE
It takes such a long time to gather dependency information in VS when install/update packages. 

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#7089]
I always find that it takes a very long time to gather dependency information when install or update the packages. Is that possible to optimize this in a faster way?

**Comment by loic-sharma** [comment]
This should be opened on https://github.com/nuget/home, but I would recommend talking to the client team 😄

**Comment by zhhyu** [comment]
Is that time cost due to the recursive dependency finding? If so, is that a better idea that we provide more redundant info on our server side?

**Comment by skofman1** [comment]
@zhhyu , you should open the issue on  https://github.com/nuget/home. Client team is working on perf improvements.
