### ISSUE TITLE
Remember tab selection in package details page

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/NuGetGallery#7097]
Now that https://github.com/NuGet/NuGetGallery/issues/5670 landed it would be nice if the gallery UI would remember the selected tab instead of always reverting back to `Package Manager`.

I never use the default tab since I prefer the `PackageReference` option so I always need to switch to that tab before I can copy the string.

**Comment by scottbommarito** [comment]
@khellang has proposed a great fix. I have assigned myself so I can be in charge of pushing it through our deployment process.
