### ISSUE TITLE
[UI] PackageReference instructions should handle dev dependency

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7103]
The display package page now had a tab for `PackageReference` installation instructions. These instructions should include `PrivateAssets` for dev dependencies.

See https://twitter.com/MagickNET/status/1121369830056169472

/cc @rrelyea @khellang @xavierdecoster

**Comment by khellang** [comment]
This is already tracked by https://github.com/NuGet/NuGetGallery/issues/5666, no? 🤔

**Comment by loic-sharma** [comment]
Ah yup you're right!
