### ISSUE TITLE
Clarification on NuGet PUT throttle limit

### ISSUE THREAD

**Issue by sstevenkang** [NuGet/NuGetGallery#7105]
Hi, according to NuGet.org's documetation [here](https://docs.microsoft.com/en-us/nuget/api/rate-limits), the PUT API throttle limit is 350/hour per API key.  However, my team noticed that this is not the case.  We started quota reached response after pushing 167 NuGet packages in 15 minutes or so.   Could you clarify in the docs what the limit is with right granularity?

**Comment by xavierdecoster** [comment]
I checked our APIM config for this route. The documented limit is correct.

We're using the [`quota-by-key`](https://docs.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies#SetUsageQuotaByKey) policy where `counter-key` is the API-key being used. When the call limit is reached, the caller receives a `403 Forbidden` response status code. Was that the HTTP status code returned? More information (such as time and source region of requests) would be potentially useful to dig into some logs.

**Comment by sstevenkang** [comment]
We received the following message back:  `403 (Quota Exceeded)`.    We are using a legacy API key.  Maybe that has to do with it?  We are making the request from pacific northwest--not sure which Azure region it maps too.

**Comment by xavierdecoster** [comment]
@sstevenkang do you have a timestamp for when this happened?

**Comment by sstevenkang** [comment]
We don't have the exact timestamp.  However, the NuGet push failure occurred right after successfully pushing `AWSSDK.TranscribeService.3.3.103.1.nupkg`.  According to NuGet, the push occurred around `2019-4-24 19:21:58Z`.  I suspect the failure occurred in the next 10 min or so.

**Comment by xavierdecoster** [comment]
I can see that `AWSSDK.TranscribeService.3.3.103.1.nupkg` indeed got created at `2019-04-24 19:21:58.610Z` by the `awsdotnet` user. The user successfully pushed `269` new packages that day.

Looking at the batch of packages being pushed, it would appear that the push operation that encountered failures started around `2019-04-24 19:16:24.610Z` (first successful package pushed).
The one above was the last successful package pushed in this batch. In total, `164 packages` were pushed successfully in a timespan of `05m34s`. No symbols packages were pushed for these packages.
No additional _successful_ package push operations happened by this user in the hour before `2019-04-24 19:21:58.610Z`. I cannot derive _failed_ request information from the db by this user. 

Unfortunately, I couldn't find any information in the logs to learn more about the cause of failure. We're looking into enhancing our logs so we have more information to investigate this if it happens again.
