### ISSUE TITLE
Packages search doesn't find partial strings

### ISSUE THREAD

**Issue by AccuPhoenix01** [NuGet/NuGetGallery#7107]
Looking for Nuget packages is hard because I need to know the full or exact name of a package. Partial string search seems to be broken as to how I’d expect it to work.

Steps to reproduce (in VS):
1. Open VS project
2. Right click on Packages in left sidebar
3. Choose “Add Packages”
4. In Search area of Add Packages window, look for:
“mpart” …. looking for mParticle, does not return anything
“mparticle” … will return mParticle packages
“appsf” … looking for AppsFlyer, does not return anything
“appsflyer” … will return packages

Expected result: Entering any partial string of package name will match.
Such as “mpart” WILL return all 3 of the mParticle packages.

This applies to both Web and Visual Studio plug in.

**Comment by joelverhagen** [comment]
We're currently working on improving the matching and ranking in our search experience and are tracking all of the customer-reported issues here:
https://github.com/NuGet/NuGetGallery/issues/4124

Thanks for adding your voice to the mix and the helpful examples!
