### ISSUE TITLE
Separate the release and pre-release package feed?

### ISSUE THREAD

**Issue by AnthonyMastrean** [NuGet/NuGetGallery#7125]
I see some [recent activity](https://github.com/NuGet/NuGetGallery/pulls?q=is%3Apr+rss+feed+is%3Aclosed) to add Atom/RSS feeds to the packages page, and that's great! However, I want to use the feed as a notification to read release notes and schedule package updates. So, I really don't want to see the (sometimes) firehose of pre-release packages.

Could you separate the release and pre-release package feeds?

**Comment by joelverhagen** [comment]
You should be able to add `?prerel=false` to the Atom feed URL. For example,

https://www.nuget.org/packages/SlowCheetah.Xdt/atom.xml?prerel=false

**Comment by AnthonyMastrean** [comment]
Whoa, thanks! I went searching and didn't see this option mentioned anywhere.

**Comment by joelverhagen** [comment]
@AnthonyMastrean, yeah, it's a bit of a hidden feature. So we can attempt to make this more discoverable, where did you look to find this option?

**Comment by AnthonyMastrean** [comment]
I searched the issues on this site and looked at the package page source (a trick I learned to find hidden GitHub atom feeds, actually).
