### ISSUE TITLE
[Azure Search] Add ID prefix matching for search

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#7128]
Visual Studio Package Manager UI searches when you pause typing in the search box. Thus, intermediate searches should be pretty good too.

Target queries | Expected results
------------- | -----------------
newton, new, n | Newtonsoft.Json
s | System.*, AWSSDK.S3, Serilog, Swashbuckle
mi, micro | Microsoft.Extensions.\*, Micorsoft.AspNetCore.\*,Microsoft.AspNet.\*,Micrsoft.Owin,Microsoft.\*
en, e, enti, ent | EntityFramework, Microsft.EntityFrameworkCore
m | Moq, System.Memory, Microsoft.*
log4 | log4net
a | AutoMapper, Antlr, AWSSDK.*, Autofac
swash, swa | Swashbuckle.AspNet.Core.Swagger, Swashbuckle, Swashbuckle.*

**Comment by loic-sharma** [comment]
Likely uses same analyzer as from https://github.com/nuget/nugetgallery/issues/7129

**Comment by loic-sharma** [comment]
7% of nuget.org queries had no results ([LINK](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2gallery%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2gallery/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0XNsQ6CQBAE0J6v2FBBY2gtsFBbDVF%252FYD02cAl3S3b3gho%252F3sNC25nJG5fUOJzIxDst3rCMJATmA6lhmGEHOHC1bfr6V0YMBG0L5V54UZIrobixw4FKyCN6GMUeznwhTZMptGCs2Y9D5b5vx6xH9Rx1c2PD6cAp2io264mmEFD8i8CteVXD%252FfnX8kAyTwKzJzeiGBQfD6B6dcQAAAA%253D))

**Comment by loic-sharma** [comment]
### Add prefix matching to tokenized terms

If the query is `foo.bar` will result in Azure Search text like `foo.bar (+foo +bar)^3 +tokenizedPackageId:foo* +tokenizedPackageId:bar* packageId:foo.bar^1000`

Implementation: [dev..loshar-dot-split](https://github.com/NuGet/NuGet.Services.Metadata/compare/dev...loshar-dot-split?expand=1)

Curated Search Queries
======================
Curated control:   0.853337353833429
Curated treatment: 0.80452962531863

Client curated control:   0.762780387461513
Client curated treatment: 0.785477065558459

Feedback control:   0.734464808559348
Feedback treatment: 0.745347293704655

<details>
    <summary>Results</summary>

Curated Search Queries
======================
Control:   0.853337353833429
Treatment: 0.80452962531863

Biggest Winners (10)
--------------------
system.windows.forms                 => +0.0013
mysql                                => +0.0012
CefSharp                             => +0.0008
identityserver                       => +0.0006
Microsoft.Extensions.Hosting         => +0.0005
Microsoft.AspNet.WebPages            => +0.0005
Microsoft.EntityFrameworkCore.Sqlite => +0.0004
system.web.http                      => +0.0004
System.Web.Http                      => +0.0003
powershell                           => +0.0003

Biggest Losers (10)
-------------------
windowsazureofficial                             => -0.0074
Microsoft.VisualStudio.Web.CodeGeneration.Design => -0.0025
System.Net.Http.Formatting                       => -0.0025
json.net                                         => -0.0024
Microsoft.EntityFrameworkCore.SqlServer          => -0.0023
excel                                            => -0.0022
Owner:"Autofac" Autofac*                         => -0.0020
accord.net                                       => -0.0019
Microsoft.EntityFrameworkCore.Tools              => -0.0014
unit testing                                     => -0.0014

Lowest Treatment Scores (10)
----------------------------
windowsazureofficial     => 0
json.net                 => 0
unit testing             => 0
system.web.mvc           => 0
System.Web.Mvc           => 0
Owner:"Autofac" Autofac* => 0
Appeon                   => 0
email                    => 0
System.Web               => 0
XLSX                     => 0

Client Curated Search Queries
=============================
Control:   0.762780387461513
Treatment: 0.785477065558459

Biggest Winners (10)
--------------------
mi     => +0.0044
enti   => +0.0037
mic    => +0.0037
swa    => +0.0028
entit  => +0.0028
Mic    => +0.0028
micros => +0.0026
Mi     => +0.0026
sele   => +0.0022
micr   => +0.0020

Biggest Losers (10)
-------------------
Microsoft.EntityFrameworkCore.SqlServer => -0.0028
Microsoft.CodeAnalysis.FxCopAnalyzers   => -0.0026
Microsoft.AspNetCore.Mvc.NewtonsoftJson => -0.0015
Microsoft.EntityFrameworkCore.Tools     => -0.0013
System.Net.Http.Formatting              => -0.0012
json.net                                => -0.0012
excel                                   => -0.0010
swagger                                 => -0.0010
ef                                      => -0.0009
log                                     => -0.0008

Lowest Treatment Scores (10)
----------------------------
micro      => 0
m          => 0
e          => 0
n          => 0
Micro      => 0
ent        => 0
System.Web => 0
a          => 0
M          => 0
N          => 0

Feedback
========
Control:   0.734464808559348
Treatment: 0.745347293704655

Biggest Winners (10)
--------------------
appsf                           => +0.0117
mpart                           => +0.0085
microsoft.visualstudio.services => +0.0037
Azure                           => +0.0024
Azure Storage Blobs             => +0.0024
brot                            => +0.0024
Build.Extensions                => +0.0024
clrheap                         => +0.0024
eventgri                        => +0.0024
fluentassertion                 => +0.0024

Biggest Losers (10)
-------------------
Microsoft.Extensions          => -0.0142
MS, .net core                 => -0.0108
aad                           => -0.0024
ADAL                          => -0.0024
Approximate Nearest Neighbors => -0.0024
azure active directory        => -0.0024
blob storage                  => -0.0024
cache                         => -0.0024
ef                            => -0.0024
Ef                            => -0.0024

Lowest Treatment Scores (10)
----------------------------
Azure Keyvault => 0
Azure.         => 0
log file       => 0
log database   => 0
logging        => 0
log            => 0
html parser    => 0
ef core        => 0
qrcode         => 0
pdf            => 0
</details>

**Comment by loic-sharma** [comment]
Experiments based off the "Add optional prefix matching to the last raw term" ([dev..loshar-prefix-v5](https://github.com/NuGet/NuGet.Services.Metadata/compare/dev...loshar-prefix-v5?expand=1))

# Boost prefix matches if the last raw term is shorter than 4 characters

...

**Comment by loic-sharma** [comment]
### Prefix match last term on full package id if term contains id separators

The query `foo.bar` results in Azure Search text like `foo.bar (+foo +bar)^3 packageId:foo.bar*^20 packageId:foo.bar^1000`

Implementation: [dev..loshar-prefix-v10](https://github.com/NuGet/NuGet.Services.Metadata/compare/dev...loshar-prefix-v10?expand=1)

Data set | Control NDCG score | Treatment NDCG score | Result
-- | -- | -- | --
nuget.org curated queries | 0.8526 | 0.0.8550 | ❌
client curated queries | 0.7627 | 0.0.7624 | ✔
feedback queries | 0.7316 | 0.7468 | ✔

<details>
    <summary>Results</summary>

Curated Search Queries
======================
Control:   0.8526305050062
Treatment: 0.854993844736601

Biggest Winners (10)
--------------------
system.windows.forms                => +0.0007
System.Web.Http                     => +0.0006
System.ServiceModel                 => +0.0006
Microsoft.AspNet.WebPages           => +0.0003
Microsoft.IdentityModel             => +0.0002
system.web.http                     => +0.0002
R.NET.Community                     => +0.0002
Microsoft.AspNet.WebHooks.Receivers => +0.0002
xamarin.forms                       => +0.0002
socket.io                           => +0.0001

Biggest Losers (5)
------------------
Microsoft.AspNet.WebApi.Client           => -0.0006
AspNetCore.HealthChecks                  => -0.0003
MySql.Data                               => -0.0002
Microsoft.Practices.Unity                => -0.0001
Microsoft.EntityFrameworkCore.Relational => 0

Lowest Treatment Scores (10)
----------------------------
system.web.mvc      => 0
System.Web.Mvc      => 0
System.Web          => 0
Tags:"seq-app"      => 0
Tags:"excel-to-pdf" => 0
socket              => 0
httpcontext         => 0
qrcode              => 0
QRCode              => 0
Tags:"pdfviewer"    => 0

Client Curated Search Queries
=============================
Control:   0.762687841979449
Treatment: 0.762420737963763

Biggest Winners (8)
-------------------
System.Web.Http               => +0.0005
system.data                   => +0.0002
system.web.http               => +0.0001
Microsoft.AspNetCore.Identity => +0.0001
System.Data                   => +0.0001
xamarin.forms                 => +0.0001
Microsoft.Extensions.Http     => +0.0001
Microsoft.AspNetCore.Http     => 0

Biggest Losers (5)
------------------
Microsoft.AspNet.WebApi.Client => -0.0006
Microsoft.Asp                  => -0.0003
microsoft.asp                  => -0.0002
MySql.Data                     => -0.0002
Microsoft.AspNet               => -0.0001

Lowest Treatment Scores (10)
----------------------------
mi    => 0
micro => 0
m     => 0
en    => 0
e     => 0
mic   => 0
enti  => 0
n     => 0
Micro => 0
ent   => 0

Feedback
========
Control:   0.731618985150309
Treatment: 0.7467828806495

Biggest Winners (10)
--------------------
microsoft.visualstudio.services     => +0.0057
microsoft.bot.con                   => +0.0024
Microsoft.Bot.Con                   => +0.0024
mysql                               => +0.0024
serilog                             => +0.0014
Microsoft.Toolkit.Wpf               => +0.0010
Azure.Storage                       => +0.0009
markdown                            => +0.0009
Microsoft.Azure.functions.extension => +0.0009
Microsoft.Extensions.Depen          => +0.0009

Biggest Losers (2)
------------------
sqlite          => -0.0024
microsoft.azure => -0.0020

Lowest Treatment Scores (10)
----------------------------
Azure identity   => 0
Build.Extensions => 0
uwp pdf          => 0
bench            => 0
common helpers   => 0
KeyVault         => 0
aspnetcore       => 0
appsf            => 0
eventgri         => 0
WebView          => 0
</details>

**Comment by loic-sharma** [comment]
### Prefix match last term on tokenized package id if term less than X characters

The query `foo.bar` results in Azure Search text like `foo tokenizedPackageId:foo*^20`

Implementation: [dev..loshar-prefix-v10](https://github.com/NuGet/NuGet.Services.Metadata/compare/dev...loshar-prefix-v9?expand=1)

Data set | Control NDCG score | Treatment NDCG score | Result
-- | -- | -- | --
nuget.org curated queries | 0.8526 | 0.8538 | ❌
client curated queries | 0.7627 | 0.8038 | ✔
feedback queries | 0.7316 | 0.7159 | ✔

<details>
    <summary>Results</summary>

Curated Search Queries
======================
Control:   0.8526305050062
Treatment: 0.8537901780685

Biggest Winners (5)
-------------------
aws => +0.0007
xml => +0.0004
RTF => +0.0001
svg => +0.0001
dbf => 0

Biggest Losers (3)
------------------
ZPL => -0.0001
git => -0.0001
wpf => 0

Lowest Treatment Scores (10)
----------------------------
system.web.mvc       => 0
System.Web.Mvc       => 0
system.windows.forms => 0
system.web.http      => 0
System.Web           => 0
Tags:"seq-app"       => 0
Tags:"excel-to-pdf"  => 0
socket               => 0
httpcontext          => 0
qrcode               => 0

Client Curated Search Queries
=============================
Control:   0.762687841979449
Treatment: 0.8038345932575

Biggest Winners (10)
--------------------
m   => +0.0057
mic => +0.0052
mi  => +0.0044
Mic => +0.0039
ent => +0.0033
M   => +0.0029
swa => +0.0028
Mi  => +0.0026
e   => +0.0022
n   => +0.0016

Biggest Losers (4)
------------------
ef  => -0.0009
net => -0.0004
nu  => -0.0003
web => 0

Lowest Treatment Scores (10)
----------------------------
micro      => 0
enti       => 0
Micro      => 0
entit      => 0
System.Web => 0
micr       => 0
micros     => 0
boot       => 0
c          => 0
microso    => 0

Feedback
========
Control:   0.731618985150309
Treatment: 0.715891729366499

Biggest Winners (7)
-------------------
logging         => +0.0024
sqlite          => +0.0024
Android support => +0.0014
Azure PCL       => +0.0004
svg             => +0.0004
uwp             => +0.0002
cef             => +0.0001

Biggest Losers (10)
-------------------
ef            => -0.0024
Ef            => -0.0024
extended xml  => -0.0024
mysql         => -0.0024
rx            => -0.0024
ORM           => -0.0018
unit test     => -0.0010
my sample lib => -0.0009
log           => -0.0006
Log           => -0.0006

Lowest Treatment Scores (10)
----------------------------
markdown                                    => 0
Azure Keyvault                              => 0
Microsoft.Extensions.Hosting.WindowsService => 0
Microsoft.Azure.functions.extension         => 0
audit                                       => 0
my sample lib                               => 0
microsoft.bot.con                           => 0
ServerHost                                  => 0
NFC                                         => 0
azure f#                                    => 0
</details>

**Comment by loic-sharma** [comment]
Currently V8 ([dev..loshar-prefix-v8](https://github.com/NuGet/NuGet.Services.Metadata/compare/dev...loshar-prefix-v8?expand=1)) is the most promising prototype. I will polish the prototype, fix unit tests, and A/B test the change when I come back from vacation.

**Comment by loic-sharma** [comment]
A/B test at 1% @ 1/16/2020 1:30PM PST

**Comment by loic-sharma** [comment]
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3422395
Release: ...

* [ ] DEV
* [ ] INT
* [ ] PROD
