### ISSUE TITLE
Completely eliminate package title from the nuget.org UI

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7149]
This was made less prominent in the nuget.org UI during the UI redesign. I think it's time to remove it so that we can align with the official VS experience. The VS client has had title hidden for 2 major releases now (i.e. multiple years).

This inconsistency is confusing to users (as seen on at least one VS feedback item).

Current package details page:

![image](https://user-images.githubusercontent.com/94054/57414615-b87d2180-71ad-11e9-819a-6893a48e119c.png)

Current search results:

![image](https://user-images.githubusercontent.com/94054/57414632-c92d9780-71ad-11e9-967b-a334c6f85562.png)

Note that we eliminated the title-ID validation ages ago and our typosquatting check does not cover title.

**Comment by joelverhagen** [comment]
Thoughts? @anangaur @karann-msft

**Comment by karann-msft** [comment]
how is the title surfaced in the search APIs? Where does it show up in VS PM UI today?
I would like to drive consistency in the gallery and client behavior.

**Comment by joelverhagen** [comment]
> Where does it show up in VS PM UI today?

Doesn't show up at all. See Newtonsoft.Json which has a title even on the latest version:

![image](https://user-images.githubusercontent.com/94054/57548594-3a885a00-7316-11e9-85c8-067b53f81995.png)

> how is the title surfaced in the search APIs?

It shows up in the response but is not used by client.

![image](https://user-images.githubusercontent.com/94054/57548651-5ab81900-7316-11e9-8678-6d536a4191d9.png)

**Comment by karann-msft** [comment]
I want to make sure the direction we went with for the VS PM UI is the right one and we don't need to worry about it when we do a UI refresh.

Can we quickly look at the data:
* how many packages have the title property?
* of those, how many have Title = Id?
* Where Title != Id, is Title a substring of Id or vice-versa? (a variation of the bucket above)
* Finally, if Title is completely different from Id, let's see a few examples that may look interesting.

My gut says, most packages would fall in one of the first 3 categories, and if that is the case, I agree with the proposal.

**Comment by joelverhagen** [comment]
Total latest packages:

```sql
SELECT COUNT(*)
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1
```

153,426

> how many packages have the title property?

```sql
SELECT COUNT(*)
FROM Packages
WHERE IsLatestSemVer2 = 1 AND Title IS NOT NULL AND LEN(TRIM(Title)) > 0
```

78,409

> of those, how many have Title = Id?

```sql
SELECT COUNT(*)
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1 AND p.Title IS NOT NULL AND LEN(TRIM(p.Title)) > 0 AND TRIM(pr.Id) = TRIM(p.Title)
```

40,583

> Where Title != Id

```sql
SELECT COUNT(*)
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1 AND p.Title IS NOT NULL AND LEN(TRIM(p.Title)) > 0 AND TRIM(pr.Id) != TRIM(p.Title)
```

37,826

> Title a substring of Id

```sql
SELECT COUNT(*)
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1 AND p.Title IS NOT NULL AND LEN(TRIM(p.Title)) > 0 AND TRIM(pr.Id) != TRIM(p.Title) AND pr.Id LIKE CONCAT('%', p.Title, '%')
```

3,013

> or vice-versa

```sql
SELECT COUNT(*)
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1 AND p.Title IS NOT NULL AND LEN(TRIM(p.Title)) > 0 AND TRIM(pr.Id) != TRIM(p.Title) AND p.Title LIKE CONCAT('%', pr.Id, '%')
```

3,063

> Finally, if Title is completely different from Id, let's see a few examples that may look interesting.

I assume when you say "completely different" you mean one is not the substring of another.

```sql
SELECT TOP 20 pr.Id, p.Title
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.IsLatestSemVer2 = 1 AND p.Title IS NOT NULL AND LEN(TRIM(p.Title)) > 0 AND TRIM(pr.Id) != TRIM(p.Title) AND pr.Id NOT LIKE CONCAT('%', p.Title, '%') AND p.Title NOT LIKE CONCAT('%', pr.Id, '%')
ORDER BY pr.DownloadCount DESC
```

Id | Title
-- | --
Newtonsoft.Json | Json.NET
Microsoft.AspNet.WebApi.Client | Microsoft ASP.NET Web API 2.2 Client Libraries
Microsoft.AspNet.Razor | Microsoft ASP.NET Razor
Microsoft.AspNet.Mvc | Microsoft ASP.NET MVC
Microsoft.AspNet.WebPages | Microsoft ASP.NET Web Pages
Microsoft.AspNet.WebApi.Core | Microsoft ASP.NET Web API 2.2 Core Libraries
Microsoft.AspNet.WebApi.WebHost | Microsoft ASP.NET Web API 2.2 Web Host
WindowsAzure.Storage | Windows Azure Storage
Microsoft.AspNet.WebApi | Microsoft ASP.NET Web API 2.2
Microsoft.Data.OData | ODataLib
Microsoft.Data.Edm | EdmLib
Microsoft.ApplicationInsights | Application Insights API
Microsoft.AspNet.Web.Optimization | Microsoft ASP.NET Web Optimization Framework
Microsoft.Net.Http | Microsoft HTTP Client Libraries
xunit.extensibility.core | xUnit.net [Extensibility: Core]
xunit.abstractions | xUnit.net [Abstractions]
xunit.core | xUnit.net [Core Unit Testing Framework]
xunit.assert | xUnit.net [Assertion Library]
xunit.extensibility.execution | xUnit.net [Extensibility: Execution]
jQuery.Validation | jQuery Validation

**Comment by karann-msft** [comment]
I feel it is safe to remove the Title from the package details page.
@anangaur, thoughts?

**Comment by skofman1** [comment]
@anangaur , Ping!

**Comment by anangaur** [comment]
@karann-msft, Can you do a quick pulse with customers if they care for it? And if so, for what? I remember folks needed it to state a rationale text for a short package ID. However, I believe having `Title` is confusing and can be overcome with a better package naming.

**Comment by karann-msft** [comment]
https://twitter.com/karann9/status/1140766290501521408

**Comment by karann-msft** [comment]
the results are in, only 1 user said they use the title "as a more humanised version of the Id" whereas the remaining 104 used it as follows:

![image](https://user-images.githubusercontent.com/16904420/60623870-9b716300-9d98-11e9-933f-447d419cc497.png)

![image](https://user-images.githubusercontent.com/16904420/60623888-b217ba00-9d98-11e9-8f67-38a5e05c0338.png)

With that, I have high confidence we can kill title from nuget.org
