### ISSUE TITLE
[Azure Search] Add page to gallery than can be used from compare new and old search results

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7152]
This is the initial work related to https://github.com/nuget/nugetgallery/issues/7057.

The page will show both new and old search results.

It will have a "smile" and "frowny" button.

It will have a text area that allows custom feed back. The user can optionally provide their email so we can reach back to them. Logged in users have the email field auto-filled in.

**Comment by karann-msft** [comment]
Can we look at a quick mock before we make too much engineering investment?

**Comment by joelverhagen** [comment]
Yes.
