### ISSUE TITLE
Version component of package details page URL is case sensitive

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7154]
Compare the version selected between these two URLs:

https://www.nuget.org/packages/NUnit/3.0.0-rc-3
https://www.nuget.org/packages/NUnit/3.0.0-RC-3

Both should show `3.0.0-rc-3` selected.

This line is the problem.
https://github.com/NuGet/NuGetGallery/blob/9501b3539f893e6011a89120fd5a9b65a8420d86/src/NuGetGallery/Controllers/PackagesController.cs#L723

It is operating on a materialized list and uses a function that can't be mapped to SQL. Both are indicators that the string comparison is done in app code (case sensitive) not SQL Server (case insensitive in our collation).

**Comment by scottbommarito** [comment]
Looked into this. The work that introduced this bug intended to make this comparison in app code. The fix is to make the app code comparison case-insensitive.
