### ISSUE TITLE
[Azure Search] Implement randomized A/B test for new search service

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7166]
Very simple approach.

1. Randomly return a cookie to the user: `previewSearch = true | false`
    - Get the randomness percentage from JSON content file
1. With this cookie as `true`, use the preview search instead
    - Need a cookie so pagination isn't totally crazy and a single user has a consistent experience
1. Add feature flag to turn this off if things go bad.

This should happen once we have decently acceptable results.

Consider putting a Usabilla button on the treatment page.

**Comment by scottbommarito** [comment]
Note: will need to add new cookie to cookie compliance list.

**Comment by joelverhagen** [comment]
We should have an opt-out button and ask for feedback as they are opting out.

**Comment by joelverhagen** [comment]
If the Azure Search query takes too long or fails, fall back to control.

**Comment by joelverhagen** [comment]
I've prototyped something simple but would like to start the onboarding process with the internal A/B testing system before shipping something we cook ourselves.
