### ISSUE TITLE
How to locally access an Azure Search service?

### ISSUE THREAD

**Issue by MisinformedDNA** [NuGet/NuGetGallery#7170]
When I run the code locally, the search code is accessing Lucene and returning zero results. Is there a way to access NuGet's search service? Or a custom Azure Search service?

**Comment by joelverhagen** [comment]
Do you want to run your own search service indexing your own packages? Or just run search queries from your own NuGetGallery against the packages on nuget.org?

If you mean the latter, look up the URLs with the type `SearchGalleryQueryService/3.0.0-rc` in the service index (https://api.nuget.org/v3/index.json) and put them in the follow two configs values in the NuGetGallery web.config:
https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Web.config

Gallery.SearchServiceUriPrimary
Gallery.SearchServiceUriSecondary

Note that this is only in dev branch not master. We recently changed how the config works.
