### ISSUE TITLE
Consider add "noindex" to search results pages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7187]
A page like this is not a great Google result:
https://www.nuget.org/packages?q=json

Consider adding noindex here.

**Comment by skofman1** [comment]
@joelverhagen , can you provide additional details on the implications of not fixing doing this change?

**Comment by joelverhagen** [comment]
This was suggested by the SEO/telemetry office hours because the user experience is not great. The user searched for X on Google. They get a list of results. Then ends up in another list of results for X or even X'. For example:

![image](https://user-images.githubusercontent.com/94054/58899577-2dab1c00-86b2-11e9-86bb-f7af216cf20a.png)

They suggested the either they use nuget.org search to get the search results or they use Google/Bing to do directly to packages.
