### ISSUE TITLE
re-uploading another snukpg corrupts the debugging symbols

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#7188]
situation:

-  a package with snupkg is upload to nuget.org - everything file
- accidentally another snupkg is uploaded for the same version (valid snupkg, but wrong version)

currently:

- error: Symbols package publishing failed.

![image](https://user-images.githubusercontent.com/5808377/58581161-2ff31d80-824f-11e9-9510-ace96ad2ca01.png)

expected:

- the already correct Symbols package  are kept

**Comment by cristinamanum** [comment]
The already correct symbols should not be affected. The message is because the current publishing failed. @304NotModified if you can provide the package id and version i can investigate in more detail.

**Comment by 304NotModified** [comment]
Its https://www.nuget.org/packages/NLog.Web.AspNetCore

I fixed it by re uploading the original snupkg

**Comment by 304NotModified** [comment]
I had twice this email today:

---

The symbol package NLog.Web.AspNetCore 4.8.2 failed validation because of the following reason(s):

The uploaded symbols package contains one or more pdbs that are not portable.
Your symbol package was not published on NuGet Gallery and is not available for consumption.

You can reupload your symbol package once you've fixed the issue with it.


Privacy Statement
Microsoft Corporation
One Microsoft Way
Redmond, WA 98052 USA

**Comment by 304NotModified** [comment]
And it was triggered by appveyor, see also 

https://github.com/appveyor/ci/issues/2753#issuecomment-497060942

**Comment by 304NotModified** [comment]
I see this one is still broken: https://www.nuget.org/packages/NLog.Extensions.Logging/1.5.0-rc1

**Comment by cristinamanum** [comment]
I investigated the package https://www.nuget.org/packages/NLog.Extensions.Logging/1.5.0-rc1. The symbols are not corrupted. They are still on the symbol server and available to be used with the https://www.nuget.org/packages/NLog.Extensions.Logging/1.5.0-rc1 package version. 
When a new version of the symbols package is published, if the publishing fails an email is sent to the publisher. Also, package details on the  the nuget.org will show the latest publishing action status. What is not mentioned is that if publishing fails and symbols were already published, the existent symbols are not corrupted. 
We could improve this experience by adding more information and changing the error to warning/information.

**Comment by 304NotModified** [comment]
Thanks for investigating. 

Unfortunately, the "Download Symbols" is also gone, so it looks like the symbols are gone.

**Comment by 304NotModified** [comment]
I think the warning/error should not be visible if nothing gets broken

**Comment by cristinamanum** [comment]
The symbols are not gone. One way to see this is by trying to debug an app using the NLog.Extensions.Logging version 1.5.0-rc1.

![image](https://user-images.githubusercontent.com/16580006/58818939-ece4d180-85e3-11e9-871e-3dabfe6166bd.png)

The issue is that in the Package details page it is used the latest publish symbol status/information. I created a new general issue for tracking https://github.com/NuGet/NuGetGallery/issues/7222.
