### ISSUE TITLE
Deleting a user does not remove their ownership from package registrations without packages

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7197]
When deleting a package, if you choose to hard-delete the package, you are given an option to either remove the registration (if the registration has no other versions) or leave it.

![image](https://user-images.githubusercontent.com/18014088/58665337-7b580b00-82e5-11e9-8c91-14cf6a2d18cb.png)

If you leave the registration and then delete the user, the user will still own the registration, even though the user has `IsDeleted` true.

**Comment by cristinamanum** [comment]
Data was cleaned.
