### ISSUE TITLE
Introduce GitHub Usage for NuGet packages

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7200]
Today, users depend on a package's download counts to understand its popularity. However, this isn't always sufficient. For example, some System.* packages' downloads are high even though they are not referenced directly very often. To alleviate this, we will add to the "Display Package" page a list of the top GitHub repositories that depend on the package.

**Comment by sandyarmstrong** [comment]
(I tried to comment on the blog but it seemed to get swallowed up)

This is great! If I could make one suggestion: change the wording in the "info" sidebar from "Dependent repositories (223+)" to "Github Usage: 223+ repositories".

Even for native speakers, I feel pretty confident that a lot of people are going to read "Dependent repositories" and think it means how many dependencies the nuget package has, which is exactly the opposite of what you want to communicate, and may scare people away.

Sticking with "Github usage" is more consistent with the other new section on the page, too.

**Comment by vilinski** [comment]
Interesting feature. Maybe it will be interesting one day. But now very popular F# libs having no github usages, which is definitely not true. And e.g. Paket, maybe the most popular one, has no GitHub section at all. Correct your heuristics :)

**Comment by loic-sharma** [comment]
Thanks for the feedback @vilinski! At this time, we only index C# repositories. Adding support for F# projects is a low hanging fruit, I've opened an issue to track that here: https://github.com/NuGet/NuGetGallery/issues/7370

**Comment by kzu** [comment]
As of today, this feature isn't even working [on the package](https://www.nuget.org/packages/Microsoft.Extensions.Logging) showcased in [the article announcing the feature](https://devblogs.microsoft.com/nuget/surfacing-github-usage-for-packages-on-nuget-org/):

![image](https://user-images.githubusercontent.com/169707/104480764-afa83a00-55a3-11eb-9ad9-be54cfa9ce63.png)

**Comment by skofman1** [comment]
@kzu , the UX was updated, you can find GitHub usage in the 'Used By' section:
![image](https://user-images.githubusercontent.com/16807822/104493243-a316e800-5589-11eb-94fc-98a636575f05.png)

**Comment by kzu** [comment]
You mean *nothing* uses this? https://www.nuget.org/packages/Microsoft.Extensions.Logging

I'm not seeing any such sections in that page...

**Comment by skofman1** [comment]
Here's a screenshot of the page you linked:
![image](https://user-images.githubusercontent.com/16807822/104556907-35080a80-55f5-11eb-904e-3aabee2bea4d.png)

**Comment by kzu** [comment]
Ahhh, so it's under Used by, all the way to the bottom! Quite hard to discover if you've been in nuget.org for a while.

I'd suggest adding a second collapsible level under Used By, so that both NuGet Packages and GitHub Repositories become collapsible too and therefore easy to spot when first expanding Used By.

Thanks
