### ISSUE TITLE
Deployment week 6/3

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7216]
1. [x] Merge NuGetGallery dev to master **Commit** [5b7c5050](https://github.com/NuGet/NuGetGallery/commit/5b7c505086fae24912f3b0d3df58ffb5a9d1e8b8)
1. Run Validation DB migrations Release [344478](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344478)
    - [x] DEV
    - [x] INT
    - [x] PROD
1. Deploy Gallery **Build** [2734180](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2734180)  **Release** [344493](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344493)
    - [x] DEV USNC 
    - [x] DEV USSC 
    - [x] [FunctionalTestsAfterDBIntMigrationAndBeforeIntDeployment](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=56939)
    - [x] INT USNC 
    - [x] INT USSC
    - [x] FunctionalTestsAfterDBProdMigrationAndBeforeProdDeployment
    - [x] PROD USNC 
    - [ ] PROD USSC
1. [x] Merge NuGet.Jobs dev to master **Commit** [a787d82](https://github.com/NuGet/NuGet.Jobs/commit/a787d82ef60fc9090449a1c2011b281921870a5b) **Build** [2734176](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2734176)
1. [x] Merge NuGet.Internal.Jobs dev to master (Merge not needed it is only master.) Commit [cdfo754c](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGet.Internal.Jobs/commit/cdf0754c3ace39661ac6c16663c7930ea5d94080?refName=refs%2Fheads%2Fmaster)  **Build** [2725754](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2725754)
1. Deploy Validation.Orchestrator (NuGet.Jobs) **Release** [344526](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344526)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy Validation.SymbolsOrchestrator (NuGet.Jobs) **Release** [344523](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344523)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy NuGet.Jobs.Validation.SymbolsIngester (NuGet.Internal.Jobs ) **Release** [342236](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=342236)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy Validation.PackageSigning.ProcessSignature (NuGet.Jobs) **Release** [344521](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344521)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy Validation.PackageSigning.RevalidateCertificate (NuGet.Jobs) **Release** [344524](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344524)
    - [x] DEV
    - [x] INT
    - [x] PROD
1. Deploy Validation.PackageSigning.ValidateCertificate (NuGet.Jobs) **Release** [344527](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344527)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy Validation.Symbols.Job (NuGet.Jobs) **Release** [344518](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=344518)
    - [x] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC 
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC
1. Deploy ScanAndSign job **Release** [342239](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=342239)
    - [X] DEV USNC 
    - [x] DEV USSC
    - [x] INT USNC
    - [x] INT USSC
    - [x] PROD USNC 
    - [x] PROD USSC

**Repo**: NuGet.Services.Metadata, **Commit** [eae9098
](https://github.com/NuGet/NuGet.Services.Metadata/commit/eae909807621f85e9fa98f300b678c6c323d62fd) **Build**  [2737336](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2737336)
 1. Job: Catalog2Monitoring **Release** [345390](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=345390)
    - [x] DEV
    - [x] INT
    - [x] PROD

## NuGet.Jobs changes
Added logging of exceptions that manage to escape to ServiceBus SDK code for easier incident investigation (https://github.com/NuGet/Engineering/issues/1931).

**Comment by shishirx34** [comment]
All jobs deployments are done. Waiting on Gallery.
