### ISSUE TITLE
package provides  in nuspec/nuget pkgs. 

### ISSUE THREAD

**Issue by necrose99** [NuGet/NuGetGallery#7217]
while this is a nicety for chocolatey ...  which consumes nuget... 
I could see Other uses..  ie MSI/msix , install , Nuget to dynamically update sub packages. 
ie vendor  powershell modules  (ie VMware/Azure /Google etc.)  , then have nuget periodically update.. 

package Say Anaconda , (https://www.anaconda.com/distribution/) 
_insted of depends_ , **Package provides** Depend Python 3.7 , 
provides xyz , 100 other python modules , of which could be referenced against new installs , 
 and can document all the bundled in depends.. it will install. 

**package C**: now wants python,  _anaconda checks off the box , as python is installed by_ Anaconda..  while useful for chocolatey/nuget  for sure , i'm sure other bundlers could use to make self updating MSI , ie update registry of etc.. , so even if needing repair , the new map file will now use nuget to verify updates have not corrupted etc. 
**package D**:  wants Python & py modules : setuptools-git , etc to support a git gui client.. 
as they are tracked... , those  now , wont need to be installed less , they are required to upgrade. 

APP B needs =or less than <  5.2 can add to its folders.. else , can reduce adding more deps ...
via a larger MSI bundle.  , however making an added install of pkg dep to an app folder if required else will just use the depends provided by a bundler or things.. ie Anaconda , has over 100 pkgs included... 

Linux also has known Package Provides DEP A, B or C buddled in.. , also keeps it managed as to not clobber deps the main package provided and or handles upgrades  cleanly .. ie ELK services, needs Kibinana > or = to X but not lower than W.... 

any rate , I'm not sure were to put a feature suggestions.. but 
adding a provides these depends field could be of use.. 
As for documenting packages provided insted of depends ... i've seen zilch for documentation.. 

welcome to move to the suggestions box ...

**Comment by loic-sharma** [comment]
I'm not sure I fully understand your suggestion. A NuGet package can depend on another NuGet package (see [this documentation](https://docs.microsoft.com/en-us/nuget/what-is-nuget#managing-dependencies)). How is that different from a package "provides"? Are there other package managers that support package "provides" today that you could point us to? Thanks!

**Comment by joelverhagen** [comment]
Hello, we haven't heard back on this issue in quite a while. I will close it now. If you have further, specific questions, please consider opening a new issue. Thanks!

**Comment by necrose99** [comment]
I had mentioned a package such as anaconda 
It also installs python3.8 or 3.9 , at present..

Additional package provided... python3.9 
(Simular to Linux in style. ) ie dpkg/rpm.. 

Any other python depending packages can use the anaconda provided install of python3... 
And won't need to install python3 again...

Ie some Linux packages might provide a fork bundle of mpeg etc ie with liberto snes9x.. Google Chrome mpeg/etc provided over systems mpeg , ie libereto-mpeg...

Anaconda depending on python3,  however its installer also provides it... 

Ie one could add a tag that anaconda package also provides python3 via its bundled installer..

Windows visual studio,  anaconda,  chocolatey.org....
The redundancy of python3 installs runs deep....
