### ISSUE TITLE
[Symbols Improvement] Unclear UI workflow on new symbols publish failure 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#7222]
When new symbols package is uploaded and the upload fails it is not clear what happened with the old correct published symbols. 

The current behavior:
1. The user has the error message that the symbols failed to be published. 
2. The Download Symbols button is not available anymore. 

While this is fine for new symbol packages, if previous symbols were already published it is not clear if the old symbols are still available. 
The old symbols are still available but the UI could lead the user to the conclusion that they are not. 

More details see issue:
https://github.com/NuGet/NuGetGallery/issues/7188

**Comment by 304NotModified** [comment]
Also, "Download Symbols" is then unavailable.

**Comment by shishirx34** [comment]
@304NotModified - I am simplifying this issue with appropriate message and making the download button available, see the screenshot below. Does this help in removing any confusion you might have with regards to this flow of symbols upload?

![image](https://user-images.githubusercontent.com/1646506/59068522-2da14c80-8869-11e9-94dc-b724ead432ee.png)

**Comment by shishirx34** [comment]
Note: this message and download button will also be available when the newer uploaded symbols package are being indexed and validated.

**Comment by 304NotModified** [comment]
> - I am simplifying this issue with appropriate message and making the download button available, see the screenshot below. Does this help in removing any confusion you might have with regards to this flow of symbols upload?

That's a real improvement! Would it be possible to only show the warning to the (logged in) owners of the package?

**Comment by 304NotModified** [comment]
Another option would be to remove the warning and just show the last datetime when the symbols are updated.

**Comment by shishirx34** [comment]
@304NotModified - I think its fair to show this message only to the logged in owners of the package and not everyone.

Owners:
![image](https://user-images.githubusercontent.com/1646506/59069739-f03ebe00-886c-11e9-978d-636516799616.png)

Everyone else (note: download symbols is visible):
![image](https://user-images.githubusercontent.com/1646506/59069752-fdf44380-886c-11e9-9519-9ed27ad010dd.png)

**Comment by 304NotModified** [comment]
Great!
