### ISSUE TITLE
[Azure Search] Monitor search index lag

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7226]
This is meant to replace the /search/diag commit timestamp monitoring. Once idea is to sort index by commit timestamp and get the latest value. 

Two things to do in parallel
- [x] Query on commit timstamp. this has a gap for PackageDelete catalog leaves since no document in the index will have a record of this leaf, but this is probably okay.
- [x] Reach out the Azure search team about monitoring ingestion lag

**Comment by joelverhagen** [comment]
Done at Sev 3.
