### ISSUE TITLE
[Azure Search] Add V3 monitoring check to verify that all packages make it into search index

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7227]
We can't use this for fast reaction to pipeline outage but will give us a completeness guarantee never before implemented for search.

**Comment by joelverhagen** [comment]
Let's check out implementation with @scottbommarito early on so we don't waste effort on the wrong idea.

First implementation can just check the presence of the package in the search index.

**Comment by scottbommarito** [comment]
It should be pretty easy to implement these validations.
1. Create `SearchEndpoint` in [this namespace](https://github.com/NuGet/NuGet.Services.Metadata/tree/master/src/NuGet.Services.Metadata.Catalog.Monitoring/Validation/Test/Endpoint)
    - `SearchEndpoint` will need to be able to get the current cursor value of the search index. Currently, for registration and flat-container, [we just have the URL of the cursor in config.](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.Metadata.Catalog.Monitoring/Validation/Test/Endpoint/EndpointConfiguration.cs)
2. Cache the [`PackageSearchResource`](https://github.com/NuGet/NuGet.Client/blob/8058f199bdcce2fddaf35a19474b9ab69f4b4a34/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs) (or [`RawSearchResourceV3`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/RawSearchResourceV3.cs) if you decide to use it instead) in [`ValidationContext`](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.Metadata.Catalog.Monitoring/Validation/Test/ValidationContext.cs#L91)
3. Create implementations of [`Validator<SearchEndpoint>`](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.Metadata.Catalog.Monitoring/Validation/Test/Validator.cs#L102) that use the search resource chosen above.

Depending on what you want to validate, you may want to wait on [@xavierdecoster's work to pull in the package's metadata from the DB](https://github.com/NuGet/NuGet.Services.Metadata/pull/537). If you're just checking for the package's presence, you can probably proceed without it.

**Comment by joelverhagen** [comment]
Moved to later.
