### ISSUE TITLE
Refactor ApplicationInsightsHelper classes in statistics jobs

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7234]
We have several `internal static` classes named `ApplicationInsightsHelper` in our stats jobs.

https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.RollUpDownloadFacts/ApplicationInsightsHelper.cs
https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/ApplicationInsightsHelper.cs
https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.CreateAzureCdnWarehouseReports/ApplicationInsightsHelper.cs

These classes don't match our typical logging pattern and should be refactored to align with it. For example, any exceptions logged should be logged through `ILogger`.

**Comment by skofman1** [comment]
While I agree with the issue, this will never get prioritized since it's refactoring.
