### ISSUE TITLE
Document Sendgrid SMTP on Azure

### ISSUE THREAD

**Issue by corinja** [NuGet/NuGetGallery#7246]
Apologies if this is inappropriate, but I can't find detailed documentation on how to deploy a NuGetGallery on Azure using Sendgrid as the email service provider.

Apparently Sendgrid SMTP URIs need to be in the form:

`smtpTLS://CREDENTIAL-USERNAME:PASSWORD@smtp.sendgrid.net:587`

But this format seems to cause an exception when I set Gallery.SmtpUri value like this.

The existing documentation in README.md states that

>  "SMTP connection string, such as: smtp://user:password@smtpservername:25"

 should be used, but this does not seem to work for Sendgrid Azure service. Also, Sendgrid recommend using API Key, but the Gallery.SmtpUri does not support this.

Can someone provide guidance on correct usage for Sendgrid Azure service for email?

**Comment by skofman1** [comment]
@corinja , apologies for the slow reply. We have missed this issue.
What is the exception you are seeing and what is the stack trace? What is the config value you used (provide the string with obfuscation of sensitive data)?

**Comment by agr** [comment]
For using SMTP over SSL one should specify `smpts` as the schema in URL in the value for `Gallery.SmtpUri`. Another caveat is that if your login/password contains URL-unfriendly characters (such as `@`, `%`, etc.), they have to be URL encoded.

E.g. if your username is `u$ername` password is `p@ssw0rd`, then URL should look like:

```
smtps://u%24ername:p%40ssw0rd@smtp.sendgrid.net:587/
```
