### ISSUE TITLE
It's hard to tell which gallery region is emitting an ApplicationInsights event

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7250]
Right now cloud role name is "NuGetGallery" and cloud role instance is a specific instance. However, if you want to know USNC vs USSC vs staging slot vs production slot, it's hard to tell.

**Comment by scottbommarito** [comment]
As a mitigation, I was using the URL to identify region:
```
requests
| sort by timestamp desc 
| extend trimmedUrl = trim("http(s)*://", url)
| extend domain = substring(trimmedUrl, 0, indexof(trimmedUrl, '/')) 
| summarize count(itemCount) by bin(timestamp, 1m), domain
```
...but this is obviously not ideal.
