### ISSUE TITLE
MonitoringProcessor can overwrite status blobs

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7254]
`MonitoringProcessor` doesn't use ETags, so if the same package is being validated by two threads or separate instances at the same time, there is a chance that they could save at the same time and one run could overwrite the other.

This is possible with both a single instance handling multiple queue messages for the same package as well as with multiple instances handling these messages.

**Comment by skofman1** [comment]
@scottbommarito , is this fixed?

**Comment by scottbommarito** [comment]
Yes!
