### ISSUE TITLE
Stats are broken (part 6)

### ISSUE THREAD

**Issue by rianjs** [NuGet/NuGetGallery#7258]
Previous incidents:
1) https://github.com/NuGet/NuGetGallery/issues/4389
1) https://github.com/NuGet/NuGetGallery/issues/4572
1) https://github.com/NuGet/NuGetGallery/issues/6051
1) https://github.com/NuGet/NuGetGallery/issues/6764
1) https://github.com/NuGet/NuGetGallery/issues/7053

The latest issue is that the counts are wrong again. I began to suspect something last Thursday. Here's the breakdown:

Date | Count | Growth | 7d mean |  
-- | -- | -- | -- | --
2019-06-04 | 691,767 | 1,525 | 1,842 |  
2019-06-05 | 695,453 | 3,686 | 1,934 |  
2019-06-06 | 704,091 | 8,638 | 2,808 | 699,043
2019-06-07 | 701,557 | -2,534 | 2,135 |  
2019-06-08 | 702,320 | 763 | 1,905 |  
2019-06-09 | 704,590 | 2,270 | 2,102 |  
2019-06-10 | 704,900 | 310 | 2,094 |  
2019-06-11 | 705,250 | 350 | 1,926 |  

* That 699K value in its own column was the download count 12 hours after the 704K.
* 8.6K downloads in a 24 hour period would be the biggest day by a wide, wide margin. So it's unlikely, unless there were some downloads being dropped on the floor, and suddenly rediscovered by a cleanup job or whatever.
* The package is ical.net -- not that it matters: https://www.nuget.org/packages/Ical.Net/

I don't want be rude, but these issues have gone back to 2017. I find these errors with the world's least sophisticated spreadsheet. These should be trivially easy to catch with tooling. Automated monitoring and alerting should be very easy to build for this.

**Comment by skofman1** [comment]
Closing this one since we are tracking fixes on https://github.com/NuGet/NuGetGallery/issues/7053
