### ISSUE TITLE
have ability to go to github.nuget.io

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#7274]
After we went live with the new blog, there is no way to see the old one. Some reasons to want to see the old is to check if the migration brought it over correctly, etc. i.e. essentially to be able to compare.

**Comment by joelverhagen** [comment]
You can resolve the DNS of `nuget.github.io` then set a hosts file entry for the resolved IP address and blog.nuget.org.

**Comment by joelverhagen** [comment]
Worked with @karann-msft offline to apply this workaround.
