### ISSUE TITLE
[Deprecation] Deprecation message has no reasonable length restriction

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7280]
I put a deprecation message that has 1,702,389 characters.

**Comment by scottbommarito** [comment]
Probably going to limit this to 4,000 characters, like how other similar fields are restricted (https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Helpers/PackageHelper.cs#L75).

**Comment by joelverhagen** [comment]
Consider a number based on expected command line experience

**Comment by joelverhagen** [comment]
Lower is better for starters. It's easy to increase the limit later.
