### ISSUE TITLE
Revoke NuGet.org API keys published to GitHub using token scanning

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#7282]
Leverage [GitHub’s token scanning partnership program](https://developer.github.com/partnerships/token-scanning/) such that whenever you commit or push a change to GitHub in a public repository and an NuGet.org API key is found, it is sent to NuGet.org for validation. If it’s valid, we should revoke it and notify the user of this action.

**Comment by anangaur** [comment]
Here is the link to GitHub’s [token-scanning service](https://developer.github.com/partnerships/token-scanning/). We need to expose an endpoint that we can share with them upon enrollment. Rest of the process is elaborated on the page:
![image](https://user-images.githubusercontent.com/14800916/59797111-ca191500-9293-11e9-996c-e0ebb3bfc33b.png)

**Comment by anangaur** [comment]
@karann-msft I am assuming this is the `Epic` that tracks the automation as well? If so, can this be marked so?

**Comment by joelverhagen** [comment]
This is done.
