### ISSUE TITLE
[Azure Search] Add embedded icon URLs to Azure Search from DB (package entity)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7283]

**Comment by scottbommarito** [comment]
In `catalog2azuresearch`:

- If `iconFile` property exists in catalog, set `iconUrl` to `/v3-flatcontainer/{id}/{version}/icon`
- Else, fallback to existing behavior

In `db2azuresearch`:

- If `HasEmbeddedIcon` is true for `Package`, set `iconUrl` to `/v3-flatcontainer/{id}/{version}/icon`
- Else, fallback to existing behavior

**Comment by scottbommarito** [comment]
@joelverhagen @loic-sharma @agr - could you handle deploying/verifying this while I'm on vacation next week?

**Comment by joelverhagen** [comment]
@scottbommarito, yeah we will be running Db2AzureSearch for building the index for the next A/B test.
