### ISSUE TITLE
Statistics bar is covered by the chart title

### ISSUE THREAD

**Issue by WenceyWang** [NuGet/NuGetGallery#7286]
![image](https://user-images.githubusercontent.com/7100226/59837263-87cd0200-937f-11e9-86a4-7ea55c73c4cf.png)

The page located at [https://www.nuget.org/stats/packages/FoggyConsole?groupby=Version](https://www.nuget.org/stats/packages/FoggyConsole?groupby=Version)

The title of this chart is
```
<foreignObject x="1.71em" y="-10" width="840px" height="2em" font-weight="bold"><body><p style="text-align:center">Downloads for 15 Latest Package Versions (Last 6 weeks)</p></body></foreignObject>
```

and the style of `body` is
```
body {
  font-family: 'Segoe UI', "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 16px;
  line-height: 1.42857143;
  color: #000;
  background-color: #fff;
}
```
and the result:
![image](https://user-images.githubusercontent.com/7100226/59837846-8223ec00-9380-11e9-919c-8c7a6850998d.png)

**Comment by joelverhagen** [comment]
Thanks for reporting this @WenceyWang! 

Looks to be that the background color meant for the root `<body>` element is leaking into this element. Should be easy to fix with an explicit `background-color: transparent`.

**Comment by joelverhagen** [comment]
Fixed on PROD. Thanks again for reporting the issue!
