### ISSUE TITLE
[GitHub Usage] Add exclude list

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7298]
Allow a configurable list of repositories that should be excluded from the GitHub indexing job's output.

**Comment by loic-sharma** [comment]
Once this work is done, please make sure to close the corresponding alerts. Here are the active ones as of 8/16:

* https://portal.microsofticm.com/imp/v3/incidents/details/252718749/home
* https://portal.microsofticm.com/imp/v3/incidents/details/254086679/home
* https://portal.microsofticm.com/imp/v3/incidents/details/255456233/home

**Comment by RiadGahlouz** [comment]
Merged: https://github.com/NuGet/NuGet.Jobs/pull/1005
