### ISSUE TITLE
Package metadata validation uses bunch of hardcoded numbers

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#7303]
Check here:
https://github.com/NuGet/NuGetGallery/blob/e3ae678fd8bc9f1065a17ccfb0ab3be82328bf55/src/NuGetGallery.Services/PackageManagement/PackageHelper.cs#L78-L97

Besides the very first line, everything else is a bunch of hardcoded numbers. Those need to get turned to constants and have tests written to cover them.

**Comment by agr** [comment]
https://github.com/NuGet/NuGetGallery/tree/dev-7303 starts the change.

**Comment by skofman1** [comment]
This is a refactoring issue and will never get prioritized. Feel free to send a PR and fix this.
