### ISSUE TITLE
[Deprecation UI] blue frame around deprecation status 

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7305]
When clicking on the expander the blue frame appears

![image](https://user-images.githubusercontent.com/16807822/60363196-b0fd1c00-9997-11e9-8d5a-0dfe27c710e0.png)

**Comment by scottbommarito** [comment]
Only needed to add `outline: none`.

**Comment by scottbommarito** [comment]
Can't verify on PROD due to feature flag.
