### ISSUE TITLE
Wrong Package Name

### ISSUE THREAD

**Issue by SoftCircuits** [NuGet/NuGetGallery#7308]
I uploaded the package HtmlMonkey. I later decided that I should have named it BlackBeltCoder.HtmlMonkey in order to be consistent across all my packages. So I uploaded the package as BlackBeltCoder.HtmlMonkey.

Obviously, now nuget considers these two separate packages and I've kind of messed things up.

If there is a way to rename HtmlMonkey to BlackBeltCoder.HtmlMonkey, I would really like to do that and delete the existing BlackBeltCoder.HtmlMonkey, which is hidden and has no downloads.

Otherwise, is there any way to delete HtmlMonkey? Its only been up several days and I doubt anyone's really using it.

Any other suggestions to get me out of this mess?

**Comment by loic-sharma** [comment]
Hello! Please login to nuget.org, navigate to your package's page (https://www.nuget.org/packages/HtmlMonkey/), and select the "Contact support" link on the sidebar. We'll get you sorted out once we've verified you own these packages! :)

I'll close this issue off for now, but feel free to reply or create a new issue if you have any additional questions.
