### ISSUE TITLE
nuget SxS search takes very long to return results

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#7312]
1. go to nuget.org and login
2. go to to the SxS page
3. search for a term "aspnet"

Expected:
1. search results are displayed in less than a second

Actual:
1. search results take up to 10 seconds to be displayed.

This seems to happen when the new search has not been used for an extended period of time.

**Comment by joelverhagen** [comment]
I looked at the slow queries and they seem unrelated Azure Search. The durations are long-ish (800ms to 2000ms due to warm up) but there's 9+ seconds unaccounted for in the traces except for an "end" log from the cookie compliance stack. Will add additional tracing if the problem persists.
