### ISSUE TITLE
stats: Community Packages shows non-Community Packages

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#7314]
### Describe the bug

The Community Packages shows non-Community Packages, see screenshot

url: https://www.nuget.org/stats/packages

### To Reproduce
1. go to https://www.nuget.org/stats/packages

### Expected behavior
Not showing Microsoft packages when "Show all packages" isn't checked. Currently 16 microsoft.* packages are shown

### Screenshots

![image](https://user-images.githubusercontent.com/5808377/60547011-ef3f6600-9d1e-11e9-8184-c94af1b141e0.png)

related: https://github.com/NuGet/NuGetGallery/pull/4955

**Comment by loic-sharma** [comment]
Thanks for reporting this! We have a blocklist of non-community packages that we haven't updated in a long time.

**Comment by loic-sharma** [comment]
I've verified that the statistics page reflects the latest changes.

**Comment by 304NotModified** [comment]
thanks!
