### ISSUE TITLE
Cannot edit invalid pre-filled e-mail address on Register Microsoft account screen

### ISSUE THREAD

**Issue by tombogle** [NuGet/NuGetGallery#7324]
### Description
Attempting to log in using Microsoft account. After entering credentials, it goes to https://www.nuget.org/account/register, where it asks me to provide a username. The email field is already filled in and is not editable, but since it is my Microsoft account name and is not a valid e-mail address, I'm stuck. Attempting to go forward gives the error message: This doesn't appear to be a valid email address.

### To Reproduce
1. Go to this URL: https://www.nuget.org/users/account/LogOn?returnUrl=%2F
2. Click Sign in with Microsoft button
3. Enter Skype id (I've also tried logging out of skype.com, and coming back to nuget using the e-mail address associated with the Skype/Microsoft account - same results.)
4. When prompted, I enter my password. That opens this URL: https://www.nuget.org/users/account/authenticate/return?ReturnUrl=%2f&error=&errorDescription=
5. As shown in the screen shot, there is no way to edit the e-mail address. When I click Register there, I get the error: This doesn't appear to be a valid email address.

### Expected behavior
I either need nuget to correctly get the e-mail address associated with my Skype/Microsoft account or have it allow me to edit the e-mail address field manually.

### Screenshots
![image](https://user-images.githubusercontent.com/4229598/60890390-2df68400-a229-11e9-9448-123f5460e769.png)

**Comment by shishirx34** [comment]
Hi @tombogle - it looks like the email address claim for your account doesn't actually return an email id but your skype id(?). Can you verify you have an email address linked to your Microsoft account(https://account.microsoft.com/profile/)? Perhaps, would it be possible for you to update your microsoft account(https://account.microsoft.com/profile/) and add email address as login mechanism?

**Comment by agr** [comment]
OK, I managed to reproduce the issue and work around it.
Workaround:
1. Go to https://account.microsoft.com
2. Click on your profile picture in the top right corner and select "Sign out";
  * In my case, clicking that profile icon opened the account card that had my Skype name specified there, so I expect it would be the same for you;
3. Page reloads and your profile picture gets replaced with the generic "Sign in" icon;
4. Click the "sign in" icon;
5. Make sure you use your email (and not your Skype name) in the login process;
6. You should get back to your account page and clicking on the profile picture in the top right corner will open a card where it would have your email specified.
7. Go to https://www.nuget.org, click the "Sign in" button, followed by "Sign in with Microsoft";
8. Below the log in prompt you should see a "We found an account you can use here" message (with your email specified below your name):
  * ![image](https://user-images.githubusercontent.com/102933/60933225-388b3a80-a276-11e9-9111-2ec6a30de420.png)
9. Click it.
10. You should get to the "Register Microsoft account" page that will have your proper email specified.

**Comment by shishirx34** [comment]
@tombogle - does the workaround specified by @agr above work for you? I would like to get you unblocked and then look into the appropriate fix here.

**Comment by shishirx34** [comment]
The issue has been fixed and is live in production.
