### ISSUE TITLE
[Azure Search] Investigate and improve and/or problem in matching

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7333]
Right now if multiple terms in a search query match, the "boost" doesn't seem very extreme as if it is as relevant as only one term matching.

Azure Search people can help here.

**Comment by loic-sharma** [comment]
Findings from analyzing the data:

* The majority of searches are a single term
* According to browser events, the number of 2- or 3-term searches isn't negligible, however...
* ... 2-term searches are much more common than 3 term queries

**Using legacy search service telemetry**: [LINK](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2v3search%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2v3search/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA02NPwvCMBDFdz%252FFI4sJCLo61EXEVcFNRE492kCTtpcrWvHDGzuoww33%252FvyecNdz0jR54V6xMNSH%252FFNosQKVjV0ubu5rRgqMooDZbg6Y56YMBtnlh3K8YRRQQJuk4mNpW5LE515qm88dzX4M7EgyR1mSOR1NZ07uh8hqWDd91H8MidBwrjmWWtnU1l7tODXDFFPnPvXUh0Din4zrp20dLsMPlgOS6SxoPV8rEsXkDQnNjQL6AAAA)

Number of terms in query | Frequency
------------------ | --------------
1 | 98.74% (13.4M)
2 | 0.95% (129K)
3 | 0.19% (25K)
4 | 0.07% (9.8K)
5 | 0.02% (3.1K)

**Using gallery browser telemetry**: [LINK](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2gallery%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2gallery/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA02NsQrCQBBEe8F%252FWNLkDkRsLWKhtoKgvayXJTnw7uLuhhjx401iEcth5r1xrWgKJ1L2TpaLD3Q1MYH6QKIYGtgBVslsN6Wd24iBoCgg23PqhPhCyK4%252BY0XZOKKXUizh2RL3UIAmGeyxMm76Og7qKD5FWf%252B4K3Gwf5wO%252BZDaqP8sMmN%252Fe1CstDbSPLyayb%252BCHHJrJ17aEJD9m8CNuLFw72fbuODBTwyNJ1cjKyy%252B0p2we%252F8AAAA%253D)

Number of terms in query | Frequency
------------------ | --------------
1 | 85.5% (360K)
2 | 10.1% (42.7K)
3 | 3.09% (13K)
4 | 0.88% (3.7K)
5 | 0.24% (999)
