### ISSUE TITLE
[GitHub Usage] Add telemetry to the GitHubIndexer Job

### ISSUE THREAD

**Issue by mogah** [NuGet/NuGetGallery#7359]
Add the following metrics for telemetry.

per repo:
	totalDuration
	findDuration --> numberOfFiles
	checkoutDuration --> numberOfFiles
 
totalSearchDuration --> totalReposCount
	
Example telem: https://github.com/NuGet/NuGet.Jobs/blob/master/src/Monitoring.RebootSearchInstance/TelemetryService.cs

**Comment by loic-sharma** [comment]
Verify with [these artifacts](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2916211) and [these configs](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2916244).

**Comment by loic-sharma** [comment]
This work is done and its deployment will be tracked by: https://github.com/nuget/nugetgallery/issues/7214
