### ISSUE TITLE
Deployment for week of 7/29/2019

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7372]
# Gallery

- [x] INT
    - [x] USNC
    - [x] USSC
- [x] PROD
    - [x] USNC
    - [x] USSC

# (Legacy) Search Service

- [x] INT
    - [x] USNC
    - [x] USSC
    - [x] EA
    - [x] SEA
- [x] PROD
    - [x] USNC
    - [x] USSC
    - [x] EA
    - [x] SEA

# StatusAggregator

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=400673

- [x] INT
    - [x] USNC
    - [x] USSC
- [x] PROD
    - [x] USNC
    - [x] USSC

# Availability Tests

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=401083

- [x] INT
- [x] PROD

**Comment by zhhyu** [comment]
All the deployments have finished successfully.
