### ISSUE TITLE
[Azure Search] Improve field weights (including boosting tags)

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7381]
Pull request: https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/1080?_a=overview

Try to improve the following queries:

* aad -> microsoft.identitymodel.clients.activedirectory
* excel -> EPPlus
* mail -> SendGrid, Mailkit
* ml.net ->Microsoft.ML
* orm -> Dapper
* rx -> System.Reactive
* mysql -> MySqlConnector
* pdf -> itextsharp
* postgres -> Npgsql 
* Material -> MahApps.Metro
* wpf -> MahApps.Metro 
* logging -> NLog, log4net, serilog

**Comment by loic-sharma** [comment]
Modifying the tag field's weight had a stronger effect than expected: results seemed better generally, but this wasn't a clear win. Adding a field weight of `2` resulted in the following for the target queries:
 
"aad" - microsoft.identitymodel.clients.activedirectory went up from 2nd to 1sxt
"excel" - EPPlus went up from 8th to 5th
"mail" - Sendgrid went up from 7th to 4th
"ml.net" -> Microsoft.ML went to the 4th result
"orm" -> Dapper went from 4th to 1st
"mysql" -> MysqlConnector went from 11th to 8th

**Comment by loic-sharma** [comment]
Tag field weight | Offline Score
------------------|---------------
0 (Control) | 0.82024

**Comment by loic-sharma** [comment]
Final scoring profile:

* Exact id weight: 4.75
* Tokenized id weight: 3
* Tags weight: 4
* Downloads score boost: 16,500

Search Scorer output:

```
Curated Search Queries
======================
Control:   0.823311284680628
Treatment: 0.852353941306183

Biggest Winners (20)
--------------------
websocket                     => +0.0081
Microsoft.AspNetCore.App      => +0.0029
excel                         => +0.0025
pdf                           => +0.0022
Microsoft.EntityFrameworkCore => +0.0016
aws                           => +0.0016
postgres                      => +0.0013
mysql                         => +0.0012
microsoft                     => +0.0011
XLSX                          => +0.0009
sftp                          => +0.0008
entityframework               => +0.0008
EntityFramework               => +0.0007
kafka                         => +0.0007
RDLC                          => +0.0007
System.Net.Http.Formatting    => +0.0006
identityserver                => +0.0006
email                         => +0.0006
log                           => +0.0006
commandline                   => +0.0006

Biggest Losers (20)
-------------------
Tags:"seq-app"               => -0.0018
google.apis                  => -0.0014
automapper                   => -0.0009
signalr                      => -0.0009
Microsoft.ReportViewer       => -0.0009
powershell                   => -0.0008
itext                        => -0.0008
entityframeworkcore          => -0.0007
blazor                       => -0.0006
NPOI                         => -0.0005
Microsoft.AspNet.WebPages    => -0.0004
mysql.data                   => -0.0004
barcode                      => -0.0004
AutoMapper                   => -0.0003
Tags:"html-to-image"         => -0.0003
log4net                      => -0.0003
itext7                       => -0.0003
Microsoft.Extensions.Logging => -0.0003
syncfusion.ej2.blazor        => -0.0003
FluentValidation             => -0.0003

Feedback
========
Control:   0.690217380337595
Treatment: 0.715881457788619

Biggest Winners (20)
--------------------
netcore          => +0.0163
MS, .net core    => +0.0091
aws              => +0.0030
Postgres         => +0.0030
sqlite           => +0.0030
Youtrack         => +0.0030
boletonet        => +0.0025
ORM              => +0.0025
unit test        => +0.0025
aad              => +0.0023
ef               => +0.0023
Ef               => +0.0023
mocking          => +0.0022
CacheManager     => +0.0018
entity framework => +0.0018
EntityFramework  => +0.0018
ldap             => +0.0018
logging          => +0.0018
Loggly           => +0.0018
oragon           => +0.0018

Biggest Losers (20)
-------------------
multi line        => -0.0030
mysql             => -0.0026
common mark       => -0.0023
entity            => -0.0023
Entity framework  => -0.0023
dotnetnuke        => -0.0018
FluentAssertion   => -0.0018
identity server   => -0.0018
IdentityServer    => -0.0018
itext             => -0.0018
miniprofiler.mvc  => -0.0018
my sample lib     => -0.0018
mysql data entity => -0.0018
postgresql        => -0.0018
twitch            => -0.0018
Umbraco           => -0.0018
XPlat             => -0.0018
uwp pdf           => -0.0012
microsoft         => -0.0008
Microsoft.        => -0.0008
```

**Comment by loic-sharma** [comment]
Experimenting with multi term boost with the following configs:

Exact id weight: 4.75
Tokenized id weight: 3
Tags weight: 4
Downloads score boost: 16,500

Multi term boost | Curated Search Score | Feedback score
------------------ | ------------------------ | -----------------
3 | 0.8524 | 0.7159
5 | 0.8524 | 0.7086

**Comment by joelverhagen** [comment]
Releases:
- Db2AzureSearch: [505646](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=505646)
- Auxiliary2AzureSearch: [506851](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=506851)
- Catalog2AzureSearch: [506850](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=506850)
- Owners2AzureSearch: [506852](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=506852)

**Comment by joelverhagen** [comment]
This will be finished by https://github.com/NuGet/Engineering/issues/2877.

**Comment by 304NotModified** [comment]
Is this fixed? The link is dead

**Comment by loic-sharma** [comment]
Hi, this was shipped back in December. I left a little more context on the search relevancy issue here: https://github.com/NuGet/NuGetGallery/issues/4124#issuecomment-582182709
