### ISSUE TITLE
Deployment for week of August 5, 2019

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7394]
## Orchestrator

Merge PR: https://github.com/NuGet/NuGet.Jobs/pull/788
MergePR: https://github.com/NuGet/NuGet.Jobs/pull/793
Release: [416771](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=416771)

- [x] INT
  - [x] USNC
  - [x] USSC
- [x] PROD
  - [x] USNC
  - [x] USSC

## Symbols Orchestrator

Merge PR: https://github.com/NuGet/NuGet.Jobs/pull/788
Merge PR: https://github.com/NuGet/NuGet.Jobs/pull/793
Release: [416774](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=416774)

- [x] INT
  - [x] USNC
  - [x] USSC
- [x] PROD
  - [x] USNC
  - [x] USSC

## NuGet.Licenses

https://github.com/NuGet/NuGet.Licenses/commit/6301156bc3c3b599ac335ef382a704d9134749db
Release: [416930](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=416930)

- [x] DEV
- [x] PROD

## Stats.CreateAzureCdnWarehouseReports

https://github.com/NuGet/NuGet.Jobs/commit/1b6f4a0bf6605fb676cccca6a839cabdb5c17f2a
Release: [416773](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=416773&environmentId=2002961)
- [x] INT
- [x] PROD

## NuGetDSR Job

https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGet.Internal.Jobs/commit/2de7219af79d0b570a344a9177ca13541c43b842?refName=refs%2Fheads%2Fmaster
Release: [416676](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=416676)

- [x] DEV
- [x] INT
- [x] PROD

**Comment by shishirx34** [comment]
complete.
