### ISSUE TITLE
[Azure Search] Split traffic for hijack by percentage

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7400]
### Updates

9/24/2019 @ 1:10 PM PST - Raised to 100%
9/24/2019 @ 1:05 PM PST - Updated autoscale configs to scale up if CPU% > 30, down if CPU% < 15, to a maximum of 15 instances
9/23/2019 @ 1:55 PM PST - Raised to 75%
9/23/2019 @ 10:21 PM PST - Raised to 40%
9/20/2019 @ 11:40 PM - Updated autoscale configs to scale up if CPU% > 15, and down if CPU% < 5
9/19/2019 @ 1:10 PM PST - Raised to 20%
9/18/2019 @ 8:45 AM PST - Raised to 5%
9/18/2019 @ 3:48 PM PST - Enabled OData hijack feature flag
9/18/2019 @ 2:00 PM PST - Enabled OData hijack to Azure Search at 1%

### Application Insights query 

Use [this query](https://ms.portal.azure.com#@33e01921-4d64-4f8c-a055-5bdaffd5e33d/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2gallery%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2gallery/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA6WUT0sDMRDF7wW%252Fw7Ag7EJh1ZtoPYoHQQv1JCJpdmpjd5M4maCVfngnXVu7%252BIctHvaSmffLm5dka2QIqEjPr8yz0gsYQYUebYVWGwwHgxW8zpEQeOkRRiPIriaT2wy%252BClY1baFsOeVLRFq2HfjGggJWC3wcC9orCvgYqc4rxaq4z8apF24VCYSRQvZwn6Xu7GFHvgb21790xCZcR40Wx%252FtBOrIOMETvHTFWl6n%252F1dGiP%252FW7toP25J5R80Si7s%252FcEXVg2kXLN7beY%252BitpAW155t%252Fnt75BZwcgfo6Tlk4PirA0beMpZJlqfBjVttqd9zt8q7xdvXsYFCW6YM7q13ToGVgBzOzGRPc7PMWA6Fcl8BhCNPlZk3i8M5YTojOZV%252BJw6ZRZN6xBeVFkk2Nzdk0glGNH8LxvBjK0PQkb2UlG8jjIJgmjCKGP7ydnh5CFUmxcbanxTUOfjXpkSRoNjWGfEMeyj69bad66%252Fsv44fJ7UzJNtW%252Fc2VXuTitMV8HbGZ5iFpjCOmfwRSxKKDcN%252FztFIMPhpWnzcAEAAA%253D/timespan/P1D) to verify the hijack traffic split:

```
let searchHijack = dependencies
| where type == "HTTP" 
| where name == "/search/query" 
| extend take_Q = parse_url(data)["Query Parameters"]["take"]
| extend query_Q = parse_url(data)["Query Parameters"]["q"]
| extend isLuceneQuery_Q = parse_url(data)["Query Parameters"]["isLuceneQuery"]
| extend supportedFramework_Q = parse_url(data)["Query Parameters"]["supportedFramework"]
| extend projectType_Q = parse_url(data)["Query Parameters"]["projectType"]
| extend countOnly_Q = parse_url(data)["Query Parameters"]["countOnly"]
| where (take_Q <> 20 and take_Q <> 10) or isLuceneQuery_Q <> "" or supportedFramework_Q <> "" or projectType_Q <> "" or countOnly_Q  <> "";
//
// Uncomment to find count of search requests, by search endpoint
//searchHijack | summarize count() by bin(timestamp, 1h), target | render barchart 
//
// Uncomment to find 99% duration of search requests, by search endpoint 
// searchHijack | summarize percentiles(duration, 99) by bin(timestamp, 1h), target | render timechart  
//
// Uncomment to find % of failed search requests, by search endpoint
//searchHijack | summarize todouble(countif(success == true)) / count() by bin(timestamp, 1h), target | render timechart
```

### Background 
We need a knob to increase/decrease hijack percentage

* [x] Update AB test config
  * [x] DEV
  * [x] INT
  * [x] PROD
* [x] Add feature flag
  * [x] DEV
  * [x] INT
  * [x] PROD
* [x] Enable flag and run functional test
  * [X] DEV: Skipped
  * [x] INT: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=60856
* Increase preview hijack to 100% and run functional test
  * [X] DEV
  * [x] INT: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=60871
* Disable flag and reduce preview hijack to 100%
  * [x] INT
* [x] AI query to verify the % of search requests that are in the test

# Reference

To bucket, use client IP address and hash with SHA 256. Do chi-square test to ensure distribution. Test this on DEV Gallery, this needs to work on Gallery's Azure Web Role behind APIM.

* `X-Forwarded-For` header - this should have client IP address
    * See: https://stackoverflow.com/questions/38288378/how-do-i-extract-an-ip-address-in-the-azure-api-management-policy
    * Enabling the header? https://docs.microsoft.com/en-us/azure/api-management/policies/set-header-to-enable-backend-to-construct-urls
    * Some more info: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers
* Get IP address like [AuditActor](https://github.com/NuGet/NuGetGallery/blob/673503eaf6261f64f40ef2ec38bfc364b61137b4/src/NuGetGallery.Core/Auditing/AuditActor.cs#L66)
  * One note: `context.Request.UserHostAddress` is same as `context.Request.ServerVariables["REMOTE_ADDR"];`, no need to check both
* Hijack forking
    * https://github.com/NuGet/NuGetGallery/pull/6947/files
    * https://github.com/NuGet/NuGetGallery/pull/7145/files
* Binning
    * https://crypto.stackexchange.com/questions/17990/sha256-output-to-0-99-number-range
    * mod100(SHA256(x))
* IP distribution: https://jarvis-west.dc.ad.msft.net/73167EF0

**Comment by loic-sharma** [comment]
Hijack is on at 1% as of 9/18/2019 @ 2:00 PM PST

**Comment by loic-sharma** [comment]
In last 8 hours, +12M hijacked queries were served through legacy search, and +49K were served through Azure Search. We are well below the desired 1%. I will increase the traffic flowing to Azure Search.

**Comment by loic-sharma** [comment]
Routing 20% of hijacked traffic to Azure Search has regressed perfomrance: hijacked queries are taking ~375ms at P95, ~866ms at P99. There have been no failures in the last hour. I will continue monitoring.

**Comment by loic-sharma** [comment]
Azure Search has been hovering at ~1s at P99, with very few failures.

**Comment by loic-sharma** [comment]
Request durations at P99 since we increased hijacked traffic to Azure Search to 20%:

![Request duration (azs autoscale)](https://user-images.githubusercontent.com/737941/65446701-c2fd2800-dde9-11e9-9f43-18c8f9ed05d3.png)

Azure Search App Service autoscale history:

![autoscale history](https://user-images.githubusercontent.com/737941/65446692-bed10a80-dde9-11e9-9fd8-a78e95b2b674.png)

**Comment by loic-sharma** [comment]
Our configuration is now at 100% hijacked traffic to Azure Search. However, I'm still seeing 4% traffic going to legacy search. Will investigate...

**Comment by joelverhagen** [comment]
> Should check _abTestService.IsPreviewSearchEnabled(GetCurrentUser());

Probably not. I think the most "correct" is to check both and return true if both are true. Not worth the effort at this point though.

**Comment by loic-sharma** [comment]
The last 4% of traffic will be handled by: https://github.com/nuget/nugetgallery/issues/7586
