### ISSUE TITLE
LGPL 2.1 license text file rejected as not UTF-8

### ISSUE THREAD

**Issue by carlreinke** [NuGet/NuGetGallery#7405]
### Describe the bug
The [LGPL 2.1 license text file](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) contains form feed characters.  NuGet Gallery rejects this file as not UTF-8.

### To Reproduce
1. Create a package that includes the LGPL 2.1 license file.
2. Attempt to upload the package.
3. "The license file must be plain text using UTF-8 encoding."

### Expected behavior
The license file is not rejected.

**Comment by skofman1** [comment]
Thanks for reporting. Fix is in progress.

**Comment by agr** [comment]
The fix is available on nuget.org.
