### ISSUE TITLE
On-prem hosted NuGet Gallery - Push symbol packages and its feed for Visual Studio

### ISSUE THREAD

**Issue by varbedi** [NuGet/NuGetGallery#7413]
Hi,

My company is looking to host its own NuGet Gallery and would like to have both the main package and symbols package feeds available using it.

So, I have downloaded the source code for it and tried to push both the main package and symbols package, but pushing the symbols package fails.

Looking at the source code for NuGet Gallery, I can see that it only allows symbol packages which have PackageType set to 'SymbolsPackage' in metadata which I believe is only available in 'snupkg' symbol packages.

I also looked at how NuGet client works and if I understand correctly, the source need to implement V3 API which has the 'index.json' file. Is there any documentation for I can achieve the same for the on-prem hosted NuGet Gallery and what will be the URL to use in Visual Studio for symbols packages?

If not, can you please recommend the other best possible solutions?

Thanks

**Comment by loic-sharma** [comment]
> Looking at the source code for NuGet Gallery, I can see that it only allows symbol packages which have PackageType set to 'SymbolsPackage' in metadata which I believe is only available in 'snupkg' symbol packages.

Yup, NuGet.org only accepts the new symbols package format (.snupkg): https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-server

>  Is there any documentation for I can achieve the same for the on-prem hosted NuGet Gallery and what will be the URL to use in Visual Studio for symbols packages

This is not possible using the NuGetGallery code base.

> If not, can you please recommend the other best possible solutions?

I would recommend using [BaGet](https://github.com/loic-sharma/BaGet) or [Sleet](https://github.com/emgarten/Sleet) to setup a NuGet server that accepts symbols. Note that these are third-party solutions.

> I also looked at how NuGet client works and if I understand correctly, the source need to implement V3 API which has the 'index.json' file. 

Yup, to do this yourself you will need:

1. The [service index](https://docs.microsoft.com/en-us/nuget/api/service-index) V3 API - This is the `index.json` file, used to discover other endpoints.
2. The [push symbol packages](https://docs.microsoft.com/en-us/nuget/api/symbol-package-publish-resource) V3 API - This is the endpoint used to upload symbol packages
3. You will need to add the symbol server APIs. Here are some useful references:
    * https://github.com/dotnet/symstore/blob/master/docs/specs/Simple_Symbol_Query_Protocol.md
    * https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md
    * https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md
    * https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md
    * https://github.com/dotnet/symstore/tree/master/src/NugetSymbolServer
