### ISSUE TITLE
[Feature Request] Subscribe to New Release Email Notification

### ISSUE THREAD

**Issue by adriancs2** [NuGet/NuGetGallery#7419]
I'm working on a **package A** which depends on **package B**.
Whenever package B published a new release, my package A will broke and get expired.
Therefore, I need to check the new release of package B periodically,
so that my DLL will always compiled/bind with the latest package B.
But the problem is, the release of package B is unpredictable.
Sometime, package B releases twice a month....
Sometime, it releases once in 3-6 months....
It keeps me busy coming back for checking any new releases.
So, I'm thinking that, it would be good if there is a "New Release Email Notification" feature for me to subscribe, so that I won't have to come back frequently to check for the "New Release".

**Comment by skofman1** [comment]
@adriancs2 , thanks for the suggestion! We already have an issue tracking this idea:  https://github.com/NuGet/NuGetGallery/issues/6823
Feel free to upvote the issue.
