### ISSUE TITLE
Dispose DI container every job loop of JsonConfigurationJob

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7441]
Today, every time `JsonConfigurationJob.Init` is called, a new DI container is created replacing the reference to the previous one in `_serviceProvider`:
https://github.com/NuGet/NuGet.Jobs/blob/1b6f4a0bf6605fb676cccca6a839cabdb5c17f2a/src/NuGet.Jobs.Common/JsonConfigurationJob.cs#L66

This is a pit to fall in because DI containers can contain `IDisposable` instances (in particular singletons) and if we never dispose the previous container then the `IDisposable` instances inside of it will never be disposed, leading to leaks.

In short, a DI container is considered to "own" instances and `IDisposable` instances handed out by the DI container are typically the container's job to dispose -- especially singletons.

The `AutofacServiceProvider` container from Autofac.Extensions.DependencyInjection 4.2.0 does not implement `IDisposable` but the Autofac `IContainer` inside of it does. We should:

1. [x] Update to Autofac.Extensions.DependencyInjection version 4.3.0 or later
    - See https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#id3. We need this to make `AutofacServiceProvider` disposable
1. [x] Dispose the previous instance, if non-null. It will be non-null after the first job loop.

After this is done we can safely put `IDisposable` things in the DI container.

**Comment by loic-sharma** [comment]
Another suggestion: we could share the DI container but create a new scope on each iteration of the job loop. This would have the added benefit of making DI singletons truly a singleton for the lifetime of the process, which may minimize expensive object initializations.

This approach would be a larger change than disposing the container on each job loop, but it would be "cleaner". Also, it'll bring us closer to [`GenericHost`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)s! 😉

**Comment by agr** [comment]
Autofac.Extensions.DependencyInjection was updated by https://github.com/NuGet/NuGet.Jobs/pull/830
