### ISSUE TITLE
Homepage messes after sign-in with nuget.org account

### ISSUE THREAD

**Issue by csyszf** [NuGet/NuGetGallery#7444]
# Describe the bug
After signing in with a nuget.org account, the home page was frozen and mess.
Seems like a popup with the title "Sign-in with Microsoft account" did not show up on top of the homepage.

### To Reproduce
1. On nuget.org
2. Signing in with nuget.org account
3. See error

### Expected behavior
Maybe a popup about "Sign-in with Microsoft account" should show up.

### Screenshots
![Screen Shot 2019-08-12 at 11 02 14 AM](https://user-images.githubusercontent.com/13304483/62844085-5d4d5480-bcf1-11e9-9333-544024afa1a1.png)

**Comment by csyszf** [comment]
I can successfully link to MS account by calling `window.location.href = '/users/account/AuthenticateExternal?ReturnUrl=%2F'` manually

**Comment by ryuyu** [comment]
Hey Thanks for reporting this @csyszf 

This looks like it is a similar issue with https://github.com/NuGet/NuGetGallery/issues/7415

We fixed this with https://github.com/NuGet/NuGetGallery/pull/7421 and are working on getting this out.

Hopefully this will be fixed soon!

**Comment by skofman1** [comment]
Thanks for reporting! Closing as duplicate.
