### ISSUE TITLE
How to delete a nuget.org account?

### ISSUE THREAD

**Issue by dehghani-mehdi** [NuGet/NuGetGallery#7474]
I sent an email to support@nuget.org, but seems like there is no ones there!
I can not wait forever for it. if you can not handle support request, improve your site's options.

**Comment by skofman1** [comment]
Hi @dehghani-mehdi , we haven't received your support mail. Perhaps you used a different name when sending it?
In any case, in order to delete your nuget.org account please follow instructions here:
https://docs.microsoft.com/en-gb/nuget/nuget-org/nuget-org-faq#how-to-delete-my-nugetorg-account
