### ISSUE TITLE
NuGet continual prompt for credentials due to resource blocked on V3

### ISSUE THREAD

**Issue by bluedragonknight** [NuGet/NuGetGallery#7487]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.2.0

dotnet.exe --version (if appropriate): 3.0.100-preview-010184

VS version (if appropriate): 16.2.3

OS version (i.e. win10 v1607 (14393.321)): Win10 17134.984

Worked before? If so, with which NuGet version: worked just yesterday now doesn't

## Detailed repro steps so we can see the same problem

1. right click on project -> nuget package manager

2.

...

## Other suggested things

Api source: https://api.nuget.org/v3/index.json

When looking at the metadata pulled from api.nuget.org that visual studio uses only one site is being flag as malware/security risk: https://azuresearch-usnc.nuget.org/query.  What is the vetting process for the meta that is added or verifying that all site are in good standing for enterprise use?  This just started prompting for credentials today was working for the past few months.

**Comment by joelverhagen** [comment]
Hey @bluedragonknight, please feel free to comment if you are still running into problems. For now, I am closing this issue until we hear back from you.
