### ISSUE TITLE
Stats have been broken for 72 hours

### ISSUE THREAD

**Issue by rianjs** [NuGet/NuGetGallery#7500]
In the ongoing saga of broken stats, we’re now in a spot where package download counts haven’t updated since Saturday. 

https://docs.google.com/spreadsheets/d/1aPisoc9KQDlggyfuFjo8AePuKkQD5tVonZpdmCzU1SE

**Comment by zhhyu** [comment]
Yeah, the statistic page shows some sad results.

**Comment by liuliang-wt** [comment]
same problem

**Comment by loic-sharma** [comment]
Hello, we've mitigated the issue and we are now processing downloads from the last few days. Thank you for your patience.

**Comment by loic-sharma** [comment]
Closing this issue now. Please let us know if you have any additional issues!
