### ISSUE TITLE
Investigate using AppInsights directly instead of System.Diagnostics.Trace in DiagnosticsService

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#7512]
Related to ongoing efforts to upgrade Application Insights to v2.10 in the gallery, and unblock heartbeat efforts which require v2.10 dependency in ServerCommon.

**Comment by loic-sharma** [comment]
I verified that the content object service's traces (which depend on the `DiagnosticsService`) flow to Application Insights
