### ISSUE TITLE
Implement WCAG 2.1

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7534]
There are new accessibility standards that we need to abide by. We need to analyze our site to determine if there are any issues with our analysis of them.

Note that I have not included the following standards, which do not apply to us:
- MAS 2.1.4: Character Key Shortcuts
    - we don't have any such shortcuts, except those that are implemented by the browser by default
- MAS 2.5.1: Pointer Gestures
    - we don't have any pointer gestures
- MAS 2.5.4: Motion Actuation
    - we don't have any motion controls

**Comment by skofman1** [comment]
done
