### ISSUE TITLE
Http 500 stats page

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#7543]
https://www.nuget.org/stats is serving a http 500 error. 

> Oops!
>
> Error 500 - Internal Server Error
>
> An error occurred while processing your request. We really messed up this time...

**Comment by scottbommarito** [comment]
Thanks for filing this, I'm already looking into it. Appears to be an integer overflow. Working on a hotfix but it will likely take some time before it's deployed, unfortunately.

**Comment by loic-sharma** [comment]
We've mitigated this issue by temporarily removing the graph that caused this issue. We are still working on the hotfix to re-enable this graph. Please let us know if you find any additional issues!

**Comment by 304NotModified** [comment]
I can confirm the page is now up :)
