### ISSUE TITLE
[Deployment] Week of 2019-09-16

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7549]
### Regular Deployments

- [x] INT
  - [x] Scan and sign job ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449756))
  - [x] Gallery ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=447118))
  - [x] Legacy search ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=446128))
  - [x] Azure search ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=446894))
  - [x] Validation.SymbolsOrchestrator: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448837)
    - For https://github.com/NuGet/NuGetGallery/issues/7489
  - [x] Validation.PackageSigning.ValidateCertificate: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448847)
    - For https://github.com/NuGet/NuGetGallery/issues/7482
  - [x] Validation.PackageSigning.ProcessSignature: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448848)
    - For https://github.com/NuGet/NuGetGallery/issues/7482
- [x] PROD
  - [x] Scan and sign job ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449756))
  - [x] Gallery ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=447118))
  - [x] Legacy search ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=446128))
  - [x] Azure search ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=446894))
  - [x] Validation.SymbolsOrchestrator: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448837)
  - [x] Validation.PackageSigning.ValidateCertificate: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448847)
  - [x] Validation.PackageSigning.ProcessSignature: [Release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448848)

### AME Deployments

The following deployments are to complete the AME migration. For each deployment, the on-call engineer should create a new release using the latest artifacts and configs. The on-call engineer should verify that the newly deployed code is able to access the database. If the deployment is **bolded**, this is considered a "Level 1" job for the AME migration. These deployments were originally from https://github.com/nuget/engineering/issues/2642. If you have any questions, please contact @zhhyu.

- [x] INT
    - [x] **Db2Catalog** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=446176)) ⚠️ PENDING VERIFICATION ⚠️ 
    - [x] **NuGet.Jobs.SymbolsDeleter** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=445020)) ⚠️ PENDING VERIFICATION ⚠️ 
    - [x] **Catalog2AzureSearch** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448976))
    - [x] Validation.PackageSigning.RevalidateCertificate ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448977))
    - [x] MonitoringProcessor ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448979))
    - [x] Db2Monitoring ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448983))
    - [x] ArchivePackages ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448990))
    - [x]  Owners2AzureSearch ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448991))
    - [x] Search.GenerateAuxiliaryData ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448992))
    - [x] Stats.AggregateCdnDownloadsInGallery ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448993))
    - [x] Stats.ImportAzureCdnStatistics ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448999))
    - [x] Stats.RolUpDownloadFacts ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449000))
    - [x] Gallery.AccountDeleter ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449001))
- [x] PROD
    - [x] **Db2Catalog** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=451988))
    - [x] **NuGet.Jobs.SymbolsDeleter** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=453121))
    - [x] **Catalog2AzureSearch** ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448976))
    - [x] Validation.PackageSigning.RevalidateCertificate ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448977))
    - [x] MonitoringProcessor ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448979))
    - [x] Db2Monitoring ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448983))
    - [x] ArchivePackages ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448990))
    - [x]  Owners2AzureSearch ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448991))
    - [x] Search.GenerateAuxiliaryData ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448992))
    - [x] Stats.AggregateCdnDownloadsInGallery ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448993))
    - [x] Stats.ImportAzureCdnStatistics ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=448999))
    - [x] Stats.RolUpDownloadFacts ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449000))
    - [x] Gallery.AccountDeleter ([release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=449001))

### Changes
- Scan and sign
    - Add queue-back to scan and sign submitter (https://github.com/NuGet/NuGetGallery/issues/7483)
- Gallery
    - Make the readme show more link not jump to the top of the page (https://github.com/NuGet/NuGetGallery/issues/7519)
    - [SDL] Replace HttpWebRequest with HttpClient (https://github.com/NuGet/NuGetGallery/issues/7504)
    - Add site admin check for tenant (https://github.com/NuGet/NuGetGallery/issues/7511)
    - Make package ownership accept / reject require POST (https://github.com/NuGet/NuGetGallery/issues/7515)
    - Fix timezone issues (https://github.com/NuGet/NuGetGallery/issues/7521)
    - Update to latest ServerCommon to react to method rename (https://github.com/NuGet/NuGetGallery/issues/7520)
    - Add organization membership and transform actions use POST (https://github.com/NuGet/NuGetGallery/issues/7522)
    - Use AppInsights instead of System.Diagnostics.Tracing in DiagnosticsService (https://github.com/NuGet/NuGetGallery/issues/7513)
    - Add abbr tags to hidden column headers in display package version history table (https://github.com/NuGet/NuGetGallery/issues/7510)
    - [SDL] Gallery.Core uses the SHA512 for copy checks. (https://github.com/NuGet/NuGetGallery/issues/7530)
    - Minor icon fixes (https://github.com/NuGet/NuGetGallery/issues/7539)
    - Mitigate "Internal Server Error" on package uploads (https://github.com/NuGet/NuGetGallery/issues/7540)
    - Build&Sign config for GalleryTools (https://github.com/NuGet/NuGetGallery/issues/7541)
- Legacy search
    - [SDL] Use HttpClient instead of HttpWebRequest ([#647](https://github.com/NuGet/NuGet.Services.Metadata/pull/647))
- Azure Search
    - Mega-boost the package with ID matching a query containing symbols ([#652](https://github.com/NuGet/NuGet.Services.Metadata/pull/652))

**Comment by loic-sharma** [comment]
There's also the queue-back deployments: https://github.com/nuget/nugetgallery/issues/7509
