### ISSUE TITLE
[UX] Unlisting package redirects to package details page

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7567]
### Is your feature request related to a problem? Please describe.
When I unlist a package on nuget.org, I am redirected to my package's display package page. This makes it difficult to bulk unlist/relist packages (see https://github.com/NuGet/NuGetGallery/issues/6959).

### Describe the solution you'd like
Don't redirect to the Package Details page, instead, stay on the Manage Package page.

/cc @anangaur

**Comment by skofman1** [comment]
Related issue: https://github.com/NuGet/NuGetGallery/issues/7495
