### ISSUE TITLE
Document guidance on deprecation/unlisting best practices

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7573]
@rrelyea and @nkolev92 approached me today about what the best action would be for a specific scenario: whether the author should unlist, deprecate, or do both to a package.

I think it would be helpful to write some documentation on best practices for this scenario. It should answer the following questions:
1. When should an author unlist a package?
2. When should an author deprecate a package?
3. What are the differences between unlisting and deprecating?

cc: @anangaur @karann-msft @chgill-MSFT

**Comment by anangaur** [comment]
Why is this not sufficient? What would you add to this existing doc? A PR would be welcome 😄 

https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

![image](https://user-images.githubusercontent.com/14800916/66519312-eee00500-ea9b-11e9-948b-d7afe3774c2f.png)

**Comment by scottbommarito** [comment]
I think this issue predates the docs. What you've written in the docs covers this pretty well!
