### ISSUE TITLE
Latest package not found

### ISSUE THREAD

**Issue by Looooooka** [NuGet/NuGetGallery#7576]
Trying to install the latest version of Microsoft.AspnetCore.Identity and failing because nugetpackage manager is just not finding it.
The search results are not listing the 3.0.0 version even though if y
https://azuresearch-usnc.nuget.org/query?q=Microsoft.AspNetCore.Identity&skip=0&take=26&prerelease=false&semVerLevel=2.0.0 

Trying to install Authentication.Abstractions yields the same result:

Restoring packages for ****.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.abstractions/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.abstractions/index.json 621ms
NU1102: Unable to find package Microsoft.AspNetCore.Authentication.Abstractions with version (>= 3.0.0)
  - Found 16 version(s) in nuget.org [ Nearest version: 2.2.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
Package restore failed. Rolling back package changes for 'MC2MonetaWeb.StoreManagers.Standard'.

**Comment by loic-sharma** [comment]
Would you mind sharing a minimal .csproj that reproduces this issue?

**Comment by Looooooka** [comment]
Upgrading a net core 2 app to a net core 3 app I can see changes have been made to the SigninManager class from the Microsoft.AspNetCore.Identity assembly. You can see the new SDK is referencing Microsoft.AspNetCore.Identity 3.0.0.0
:

#region Assembly Microsoft.AspNetCore.Identity, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0\ref\netcoreapp3.0\Microsoft.AspNetCore.Identity.dll
#endregion

Looking at the definition I can see the constructor has changed:

`namespace Microsoft.AspNetCore.Identity
{
 
    public class SignInManager<TUser> where TUser : class
    {
        public SignInManager(UserManager<TUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<TUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<TUser>> logger, IAuthenticationSchemeProvider schemes, IUserConfirmation<TUser> confirmation);

}
`}``
however! you cannot add a reference to this version of Microsoft.AspNetCore.Identity to any class because as you noticed the latest version is 2.2.0
And it's constructor is different

`#region Assembly Microsoft.AspNetCore.Identity, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.identity\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Identity.dll
#endregion

namespace Microsoft.AspNetCore.Identity
{
    public class SignInManager<TUser> where TUser : class
    {
        public SignInManager(UserManager<TUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<TUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<TUser>> logger, IAuthenticationSchemeProvider schemes);
}
}
`
So the only way around this is to create the SignInManager inside the dotnetcore 3 app...until somehow Microsoft.AspNetCore.Identity 3.0.0.0 appears on nuget. And it clearly should be there already seeing as how the SDK for net core was released and is in fact referencing this missing version

**Comment by Looooooka** [comment]
Oh dotnet info from my machine:



dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by skofman1** [comment]
@Looooooka , this doesn't sound like a nuget.org issue but an ASP .NET Core issue. @natemcmaster , any idea?

**Comment by pranavkm** [comment]
@Looooooka  the packages you are looking were removed as part of the ASP.NET Core 3.0 release. See aspnet/Announcements#325. 

To resolve your issue, you'll need to replace your `PackageReference`(s) with a `FrameworkReference` to `Microsoft.AspNetCore.App` Please follow our migration guide to update your project to .NET Core 3.0: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30
