### ISSUE TITLE
Package download stats not updating

### ISSUE THREAD

**Issue by devlead** [NuGet/NuGetGallery#7592]
### Describe the bug

2 days ago we released Cake version 0.35.0, normally it should at least be a couple of thousands of downloads, it's still 0.

### To Reproduce

https://www.nuget.org/packages/Cake.Tool/0.35.0
https://www.nuget.org/packages/Cake.CoreCLR/0.35.0
https://www.nuget.org/packages/Cake/0.35.0

### Expected behavior

Download count to increase each day.

### Screenshots
![image](https://user-images.githubusercontent.com/1647294/65917169-0dc50400-e3d7-11e9-8bdb-c0ed1bb2e1b7.png)
![image](https://user-images.githubusercontent.com/1647294/65917004-bb83e300-e3d6-11e9-85b5-fe15e387906c.png)
![image](https://user-images.githubusercontent.com/1647294/65917094-ea9a5480-e3d6-11e9-8db5-85357e39b3b1.png)

**Comment by zhhyu** [comment]
Work on it now.

**Comment by nkolev92** [comment]
Related report, https://github.com/NuGet/Home/issues/8658.

**Comment by proudmonkey** [comment]
@nkolev92 Thank you for directing me to the right place. Just to add more, It seems like this is not only limited to project templates. I've uploaded a new version of a package [here](https://www.nuget.org/packages/AutoWrapper.Core) and seems like the download isn't incrementing too.

Thanks,
Vince

**Comment by gustavnavar** [comment]
The same happens to me. 

These 3 projects have no stats updates for the last 3 or 4 days:
https://www.nuget.org/packages/GridBlazor/
https://www.nuget.org/packages/GridMvcCore/
https://www.nuget.org/packages/GridShared/

**Comment by zhhyu** [comment]
The mitigation is running now, please wait for a while because of the time to populate the data. Thanks for the patience!

**Comment by proudmonkey** [comment]
@zhhyu it seems to work now. Many thanks! :)

**Comment by gurmitteotia** [comment]
This week no stats have been updated for this library: https://www.nuget.org/packages/Guflow/ as well.

**Comment by zhhyu** [comment]
The statistics should be back now. Sorry for the inconvenience, and we are working towards improving our statistics pipeline. Thanks!

**Comment by devlead** [comment]
@zhhyu can confirm there's now thousands instead of zero downloads. 👍
