### ISSUE TITLE
NuGetGallery (and other service builds) do not lock down the sources properly

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#7593]
### Describe the bug

NuGetGallery builds do not lock down the sources. 

https://github.com/NuGet/NuGetGallery/blob/dev/NuGet.config
should be: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositorypath" value=".\packages" />
  </config>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <clear/>
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
    <add key="nugetbuild" value="https://dotnet.myget.org/F/nuget-build/api/v3/index.json" />
    <add key="dotnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <disabledPackageSources>
	    <clear />
  </disabledPackageSources>
</configuration>
```

Note the clear tags in disabledPackageSources and package sources. 

//cc @loic-sharma @joelverhagen 

### To Reproduce
Run restore :)

### Expected behavior
Don't use machine specific sources. 

### Screenshots
N/A

### Additional context
Encountered this while investigating the issues with builds in the NuGet Deployment repo. 
I can fix the gallery one with a PR, but I can't easily change all the public/private repos as I simply don't know them all :)

**Comment by joelverhagen** [comment]
![image](https://user-images.githubusercontent.com/94054/65918279-23faa200-e38e-11e9-9795-6b6ce45fb5df.png)

Just kidding, just kidding.

**Comment by loic-sharma** [comment]
Thanks for reporting this! This was fixed as part of the secure sources effort. See: https://github.com/NuGet/Engineering/blob/main/Server.Specs/SecurePackageSources.md
