### ISSUE TITLE
Certificate error on https://nuget.smbsrc.net

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/NuGetGallery#7598]
@xuzhg commented on [Mon Sep 30 2019](https://github.com/NuGet/Home/issues/8647)

It's failed to upload the symbols to the symbols sever, the error message:

![image](https://user-images.githubusercontent.com/9426627/65919348-e4818500-e390-11e9-87df-4ac052329dcc.png)

I tried the nuget.exe 5.2.0 version. It's same error message. 

How can we upload the symbols server again?

---

@donnie-msft commented on [Tue Oct 01 2019](https://github.com/NuGet/Home/issues/8647#issuecomment-537340606)

@xuzhg thanks for letting us know, moving to NuGet Gallery

**Comment by zhhyu** [comment]
Please Checkout NuGet symbol server: https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by loic-sharma** [comment]
Hello! Thank you for reporting this issue @xuzhg. NuGet.org doesn't manage the symbol source service, so I've opened this issue on their GitHub project: https://github.com/SymbolSource/SymbolSource/issues/19

As an alternative, I suggest moving to [the new symbol package format (.snupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) as @zhhyu  mentioned. This new symbol format can be hosted on nuget.org without depending on the third-party Symbol Source service.

Please let us know if you have any additional questions!
