### ISSUE TITLE
Extensibility: How to load a custom storage implementation

### ISSUE THREAD

**Issue by babakontheweb** [NuGet/NuGetGallery#7601]
### Is your feature request related to a problem? Please describe.
There are a number of open issues for users trying to deploy NuGet Gallery on AWS with S3 storage. The hardest part of keeping custom implementations up to date with primary repo is that we would need to add to enum StorageType (in this case, adding AwsS3 as a value).

### Describe the solution you'd like
My proposal is to replace the enum with a static class of constants by the same name. This would allow others to define their own constant values for different storage types while keeping the primary code base intact.

**Comment by zhhyu** [comment]
Thank you for your suggestions!

**Comment by joelverhagen** [comment]
I've merged this into our `dev` branch. I will close the issue next time we merge to `master`.

**Comment by babakontheweb** [comment]
@joelverhagen I have a follow up question. I'm trying to refactor my AWS/S3 related implementations of `IFileReference` and `IFileStorageService` into a standalone Nuget package. Is there a package I can reference to be able to reference these interfaces instead of having to add them to a fork of this repo?

**Comment by joelverhagen** [comment]
>  Is there a package I can reference to be able to reference these interfaces instead of having to add them to a fork of this repo?

So you want to have something like "babakontheweb.NuGetGallery.S3" package that gets loaded by gallery for it's storage implementation? How would you reference this package? That would itself require modifications to NuGetGallery.csproj right?

We have a "shims" infrastructure that is used for loading DLLs at runtime via MEF. nuget.org uses this for private implementations of `IAuditingService` and `ICookieComplianceService`. With some refactoring you could perhaps use this infrastructure to load `IFileStorageService` from there as well. See:
https://github.com/NuGet/NuGetGallery/blob/5c21a41506ea6e088eb4742b8b58047e5b94b819/src/NuGetGallery/App_Start/DefaultDependenciesModule.cs#L1232-L1280

**Comment by joelverhagen** [comment]
@babakontheweb, this is merged to master. I would close this issue but it seems like you have more questions related to extensibility of NuGetGallery. I will leave this issue open for a couple more days regarding my response https://github.com/NuGet/NuGetGallery/issues/7601#issuecomment-539725169.

**Comment by loic-sharma** [comment]
@babakontheweb Out of curiosity, have you looked at alternative NuGet server implementations? There's a few that support AWS S3. Were they missing features you needed?

**Comment by babakontheweb** [comment]
Thank you @loic-sharma and @joelverhagen I will review your comments but we can consider this issue closed.
