### ISSUE TITLE
iconUrl warning appears for packages with no icon at all

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7605]
### Describe the bug

For a package with no `<iconUrl>`, I get an `<iconUrl>` warning.

### To Reproduce

1. Make a package with no `<iconUrl>`.
2. Drop it in the gallery upload UI.

### Expected behavior
No warning.

### Screenshots

![image](https://user-images.githubusercontent.com/94054/66249103-a616fd80-e6e3-11e9-8d9b-b853e2bcbacf.png)

![image](https://user-images.githubusercontent.com/94054/66249107-b333ec80-e6e3-11e9-992e-4d3468426416.png)

/cc @agr

**Comment by loic-sharma** [comment]
A customer has reported this issue on Twitter: https://twitter.com/peymanr34/status/1180636214954795008
