### ISSUE TITLE
Simultaneously pushing and unlisting a package may result in incorrect latest

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7607]
Consider the following:

1. Package is uploaded and unlisted at the same time.
2. Package is added to the database by upload flow.
3. Package is unlisted by unlist flow.
4. After being unlisted, package's IsLatest is updated incorrectly by upload flow, which still thinks package is listed.

Ideally, the unlist flow should not be able to execute until upload flow is completed. Perhaps the upload flow is committing to DB multiple times?

See https://github.com/nuget/nugetgallery/issues/7536 for more information

**Comment by joelverhagen** [comment]
This does not apply anymore. The current listed state is used when the package is first published post validation. The unlist performed prior to validation does not result in a full unlist operation (e.g. no catalog leaf).
