### ISSUE TITLE
Unlisted packages listed after cacheRebuildFrequencyInMinutes

### ISSUE THREAD

**Issue by Adrianucho** [NuGet/NuGetGallery#7616]
Hi, community,

I'm having problems with my **Nuget.Server v3.4.1**. It is deployed as an Azure App Service.
My web.config is configured with next keys:

```
<add key="requireApiKey" value="true" />
<add key="apiKey" value="xxx" />
<add key="packagesPath" value="" />
<add key="cacheFileName" value="" />
<add key="allowOverrideExistingPackageOnPush" value="false" />
<add key="ignoreSymbolsPackages" value="false" />
<add key="enableDelisting" value="true" />
<add key="enableFrameworkFiltering" value="false" />
<add key="enableFileSystemMonitoring" value="true" />
<add key="allowRemoteCacheManagement" value="true" />
<add key="initialCacheRebuildAfterSeconds" value="1" />
<add key="cacheRebuildFrequencyInMinutes" value="3" />
```
When I call to:

_nuget delete My.Package 1.0.0 xxx -Source https://mynugetserver.azurewebsites.net/nuget -NonInteractive -Verbosity detailed_

Response is OK and _https://mynugetserver.azurewebsites.net/nuget/Packages_ shows My.Package as unlisted but, **after 3 minutes** (just the time configured in `cacheRebuildFrequencyInMinutes` web.config key), **package is listed again**.

Am I missing some configuration or it is a bug?

Thanks in advance,
Adrián

**Comment by joelverhagen** [comment]
This is unexpected. I just tried 3.4.1 on an Azure Web App and could not reproduce the issue. NuGet.Server marks a packed as unlisted by marking the .nupkg on the file system as hidden. If you see that the unlisted, my guess is that the code is failing to mark the file as hidden and then the next time the cache is rebuilt it sees the .nupkg is NOT hidden and therefore believes the file is listed.

The code is here:
https://github.com/NuGet/NuGet.Server/blob/3d8f707e725d428d55694f28d423534849c2576c/src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs#L48-L66

Could you use the Kudu "Advanced Tools" option in Azure Portal to check if the .nupkg in question is hidden? 

![image](https://user-images.githubusercontent.com/94054/67120401-1589f400-f19e-11e9-9f9d-a32841e5c918.png)

1. Use the Debug console > CMD tool in Kudu.
1. By default the packages are stored at: `site\wwwroot\Packages` (D:\home\site\wwwroot\packages for me).
1. Use `attrib *` to look at the file system attributes on all the files related to your unlisted package.

The .nuspec and .sha512 file should be not be hidden. The .nupkg should be hidden.

For example:
![image](https://user-images.githubusercontent.com/94054/67123221-87fdd280-f1a4-11e9-967d-df9af7364250.png)

If it is not hidden, then I would recommend enabling application logging and looking through the logs. In particular, this one:
https://github.com/NuGet/NuGet.Server/blob/3d8f707e725d428d55694f28d423534849c2576c/src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs#L59-L64

**Comment by Adrianucho** [comment]
Thanks for your answer. But I couldn't find out the problem. nupkg is hidden, but version is listed, as shown in the attached images:

![nuGetDeleteAndList](https://user-images.githubusercontent.com/56387109/67269713-80497100-f4b7-11e9-845d-7e9a862fd9f0.PNG)

![nuGetPackageManager](https://user-images.githubusercontent.com/56387109/67269734-87707f00-f4b7-11e9-867e-a14cf8cc8b80.PNG)

![kuduAttrib](https://user-images.githubusercontent.com/56387109/67269726-84758e80-f4b7-11e9-967f-476c9b43fb0c.PNG)

**Comment by joelverhagen** [comment]
Did application logs indicate anything suspicious? 

Also, have you made any modifications to the web app that has NuGet.Server? Or did you just install the package to an empty web project then push reply?

**Comment by Adrianucho** [comment]
No, I have reviewed my logs and there is anything suspicious. I have just created an empty web project, then installed Nuget.Server, filled the web.config with the required properties and then published directly from VisualStudio.

**Comment by joelverhagen** [comment]
Another thing to check is the `/nuget/Packages()` endpoint with something like: `/nuget/Packages?$select=Id,NormalizedVersion,Listed`. Is it showing that version as `<d:Listed m:type="Edm.Boolean">true</d:Listed>`?

**Comment by joelverhagen** [comment]
Okay, I made this branch in the NuGet.Server repo:
https://github.com/NuGet/NuGet.Server/tree/jver-trace

It's basically 3.4.1 source code with my tracing change. Could you clone it and deploy the NuGet.Server project to your web app? You will need to modify the web.config to match whatever you have in your existing project. Make sure not to clear existing files upon deployment otherwise your packages will disappear!

If you have start-up issues, I would try manually deleting the `bin` directory and re-deploying.

**Comment by joelverhagen** [comment]
Hey I have not heard back from you so I am closing the issue. If you give this debugging branch a try and find out some more information, I'm happy to help.
