### ISSUE TITLE
[Azure Search] Remap legacy DNS to point to Azure Search Service

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7628]
There is still large amounts of traffic going to legacy search ([App Insights query](https://ms.portal.azure.com#@33e01921-4d64-4f8c-a055-5bdaffd5e33d/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2v3search%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2v3search/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22TwW7bMAxA7wX6D5xPCZA2liVb0oBsKNZg6KWHdjsPlESlRmo5tRV0Hfbxk5KmnbGdLJHme6JMD%252FS0pzGO52e%252F4fmBBoLYdimA3Q4%252BAW76GXPz92TAjqANMCu%252Brr%252FBciQc7MPStbgpFjCJJezw8hac7nAfe9t3u0eKVCT6cnni74dH%252BGD7ELENIxQT2Oen1Q7tFjfUuo%252Fran1ZwHIJ6%252BAuYn9BwUE8NUI%252FY967GwcriP0YhzZsZnY%252Fxr67Tu2Fse3DeHlNu8f%252BJW3jzbHH17o72qQ8rM7PAFrvZwfOCgqUdV1roYRgjWikRmaxaoQWjVfMM1VAP8Dp5YpzpxpF5KUR0jm0xjKukAmJdWl5vozv97dfikXWwNSkGlM54SVL9UIrrZtKMzRaYKk8GT8xWUGqQc0FRyGMNElRa46yKqlOSns03b%252Bbpi5Pwvm64VIaErxGLcmRkyJ1W2mvp125SnNvVNnwCgWzxnhb85o0OjK1rQ6u9dVfpqmL1SKdzBOXzAtOWutKSM604krJRk1dxL2ubL6uhosKS%252BN441NMMlmWTInsus%252By1F7Yhv455Fl6tZ5Wh%252Be%252FH%252FcquLvj5N%252FmiV5BmhGLcXbMJiIkbB72OeTacd91OLS%252FCGy%252FD3E2B%252FMCpg2zt59lAbzs5ov%252F4k%252FRIzHz%252BsHRkBkH3A9wNNocH9IJcyIPPQ4Rtm1wq8S3W3LwBx%252Br866rAwAA)). Things to do:

* Understand CORS policy? Talk to Barry
* Consider updating the DNS to point legacy search to azure search. See: https://github.com/nuget/engineering/issues/2841

Raw query:

```
requests
| where timestamp > ago(1d)
| where name in ("GET /search/diag", "GET /search/query", "GET /query", "GET /autocomplete")
//| where url !contains "/search/query?q=packageid:E2E." // End-to-end tests
| extend dId = tostring(customDimensions.DeploymentId)
| extend Region =
  iff(dId == "a755594844164679a1ca264946f81f18" or dId == "233d868eef7b47ddacbc138a147a50c3", "USNC",
     iff(dId == "86b2d4f718ee498996291ab94a08febf" or dId == "c4e86a9343a44b7ba14593a720e5c13c", "USSC",
       iff(dId == "fe4df56377be435a97eded74a7529f98" or dId == "d293fb80632a41cbbfc535e9adeb5c2c", "EA",
         iff(dId == "15493afe371f43e99924731983887688" or dId == "e3f92c47a56342a0bd36f3f971700184", "SEA", "Unknown")
       )
     )
  )
| extend RegionAndRequestName = strcat(Region, " ", name) 
| summarize count() by bin(timestamp, 30m), RegionAndRequestName, Region, name
| order by count_ desc
| render barchart kind=stacked 
```

This investigation needs to be done before we can delete legacy search resources.

**Comment by joelverhagen** [comment]
Two known internal partners:

1. Application Insights - internal issue [devdiv 1009585](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1009585)
1. Component governance - internal issue [mseng 1640389](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1640389)

**Comment by joelverhagen** [comment]
This is blocked by https://github.com/NuGet/Engineering/issues/2835.

**Comment by joelverhagen** [comment]
Both IIS logs and Application Insights corroborate the fact that SEA and EA traffic is extremely low. I will proceed with shutting these down.

**Comment by joelverhagen** [comment]
CORS is no longer supported. This may be a problem for Azure Portal:
[Legacy CORS](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fapi-v2v3search-0.nuget.org%2Fquery&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)
[Azure Search CORS](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fazuresearch-usnc.nuget.org%2Fquery&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

**Comment by loic-sharma** [comment]
Talked offline to Joel:

1. Use IIS logs to find common referrers
1. See Joel's notes [here](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Specs%20%28in%20progress%5C%29.one%7C910181C5-8695-4A1C-9792-A56DBB86F1C3%2FShutdown%20old%20search%7C21522B6A-A4D2-4A8A-A7E0-1A0E4111FCA8%2F%29onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Specs%20(in%20progress).one#Shutdown%20old%20search&section-id={910181C5-8695-4A1C-9792-A56DBB86F1C3}&page-id={21522B6A-A4D2-4A8A-A7E0-1A0E4111FCA8}&end)
1. Reach out to Azure Site Extensions and App Insights to confirm domains for CORS policy
1.

**Comment by joelverhagen** [comment]
If we can convince Barry that we can keep a cors policy for all domains we can probably save a lot of time with emails and analysis

**Comment by joelverhagen** [comment]
CORS for all domains is deployed to all environments. The remapping can commence.

**Comment by joelverhagen** [comment]
This is done on both PROD USNC and PROD USSC.
