### ISSUE TITLE
[Azure Search] Update side-by-side page's messaging when the page is disabled

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7638]
Old search is now the current search service. New search is now the preview search service.

**Comment by joelverhagen** [comment]
Let's make this a graceful 404 page with clear message "this page is closed right now, keep an eye on twitter". For now we will 404 it since it's very confusing.

**Comment by karann-msft** [comment]
I would say just redirect to the blog post that says the new search is live.

**Comment by joelverhagen** [comment]
@karann-msft I think I blind redirect on a page that once worked is confusing. I am thinking something like this:

![image](https://user-images.githubusercontent.com/94054/67226878-def4e900-f3ea-11e9-93f7-bab606471d84.png)

Landing on a blog post when a user had a specific action in mind I think would be disorienting. A message like this is disappointing perhaps to the user but it's at least obvious what is going on.
