### ISSUE TITLE
Implement job to fetch vulnerabilities from GitHub

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7648]

**Comment by skofman1** [comment]
Work left: deploy to all environments, verify data integrity

**Comment by scottbommarito** [comment]
We will need to add GitHub PATs to the KeyVaults of all environments before deploying. These PATs should be created with @nugetlurker. The DEV PAT should be recreated with @nugetlurker as well, as it is currently using a PAT associated with my GitHub account.

See:
https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment?path=%2Fsrc%2FJobs%2FNuGet.Jobs.Cloud%2FJobs%2FGitHubVulnerabilities2Db%2FDEV%2Fnorthcentralus%2Fappsettings.json&version=GBmaster
https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment?path=%2Fsrc%2FJobs%2FNuGet.Jobs.Cloud%2FJobs%2FGitHubVulnerabilities2Db%2FINT%2Fnorthcentralus%2Fappsettings.json&version=GBmaster
https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment?path=%2Fsrc%2FJobs%2FNuGet.Jobs.Cloud%2FJobs%2FGitHubVulnerabilities2Db%2FPROD%2Fnorthcentralus%2Fappsettings.json&version=GBmaster

**Comment by skofman1** [comment]
Deployed to dev and running. We put the deployment to prod on hold to avoid reflowing. Should be deployed after V3 pipeline is ready.

**Comment by drewgillies** [comment]
Closing this as data quality work has been completed and tested on PROD.
