### ISSUE TITLE
Newly pushed packages that are vulnerable should be marked vulnerable on upload/push

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7649]

**Comment by scottbommarito** [comment]
Verified that DB is not affected without job running.

Needs to be re-verified once job is running and emitting vulnerabilities.

**Comment by drewgillies** [comment]
Having consulted GitHub engineering, this is a highly unlikely scenario and verification can be addressed if we have a specific case to pursue.

**Comment by drewgillies** [comment]
I've reviewed code per discussions and I think this is good to close. Verification in PROD will need to take place when this situation occurs for a customer.

**Comment by drewgillies** [comment]
For peace of mind I ran some test scenarios (both for adding a package within a vulnerable range and adding one just outside it) and this works fine. FYI @skofman1
