### ISSUE TITLE
Add E2E test for vulnerability

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7654]
- Create a dummy "Vulnerability" record and "VulnerablePackageVersionRange" that applies to all versions of "E2E.Vulnerable".
- Create an E2E test that checks that the package was marked vulnerable in registration as expected.
- Update other E2E tests to verify that the package being fetched does not have vulnerability metadata.

**Comment by drewgillies** [comment]
We'll leave this as covered by the verification job. Closing.
