### ISSUE TITLE
Because the old accounts are disabled, I cannot access my profile

### ISSUE THREAD

**Issue by deylin** [NuGet/NuGetGallery#7659]

**Comment by loic-sharma** [comment]
Hello, please follow this guide to regain access to your account: https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-account-management

If you run into any issues, feel free to shoot support@nuget.org an email!

**Comment by deylin** [comment]
Dear Loïc,

Thank you for your response!
I followed the instructions, but when I enter my email address 'barry.deboer@deylin.com', I get 'Could not find anyone with that username or email':
[cid:image001.jpg@01D58E70.93F0F0A0]

Is the account disabled?

Regards Barry de Boer


Van: Loïc Sharma <notifications@github.com>
Verzonden: dinsdag 29 oktober 2019 15:35
Aan: NuGet/NuGetGallery <NuGetGallery@noreply.github.com>
CC: Barry de Boer <b.deboer@destin-it.com>; Author <author@noreply.github.com>
Onderwerp: Re: [NuGet/NuGetGallery] Because the old accounts are disabled, I cannot access my profile at https://nuget.org/profiles/deylin (#7659)


Hello, please follow this guide to regain access to your account: https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-account-management

If you run into any issues, feel free to shoot support@nuget.org<mailto:support@nuget.org> an email!

-

**Comment by loic-sharma** [comment]
Do you know the name of the NuGet account? What was the email address you used to login? If you'd like to keep your details private, please email this information to support@nuget.org.

**Comment by loic-sharma** [comment]
Hello, please open a new GitHub issue if you run into any more problems!
