### ISSUE TITLE
The uploaded symbols package contains one or more pdbs that are not portable. 

### ISSUE THREAD

**Issue by bezysoftware** [NuGet/NuGetGallery#7668]
I am not able to upload a generated snupkg to Nuget.org. During indexing it always reports this error "The uploaded symbols package contains one or more pdbs that are not portable."

TargetFramework: netstandard2.0
Visual Studio: 16.3.4
DebugType: portable

This is how I pack: `dotnet pack .\Firebase.csproj --include-symbols -p:SymbolPackageFormat=snupkg -p:configuration=Release`

Here's the full csproj (which specifies `DebugType` as `portable`: https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Firebase.csproj
Package on nuget: https://www.nuget.org/packages/FirebaseDatabase.net/

**Comment by bezysoftware** [comment]
I quickly went over the sources for checking the type of PDB - https://github.com/NuGet/NuGet.Jobs/blob/44cf1f870bcbc07a6e9936603e02e6d1b3373e46/src/Validation.Symbols/SymbolsValidatorService.cs#L274 checks that the file starts with BSJB. I double checked my generated PDB and it *does* start with those, so it should pass as a portable PDB. Here's the (zipped) PDB if you want to take a look:
[Firebase.zip](https://github.com/NuGet/NuGetGallery/files/3797267/Firebase.zip)

**Comment by loic-sharma** [comment]
Could you also share the .snupkg file you would like to push to nuget.org?

**Comment by loic-sharma** [comment]
It looks like your `DebugType` is set to `pdbonly` here: https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Firebase.csproj#L31

Also, could you share the .snupkg file you would like to publish to NuGet.org?

**Comment by bezysoftware** [comment]
There you go:
[FirebaseDatabase.net.4.0.3.snupkg.zip](https://github.com/NuGet/NuGetGallery/files/3798977/FirebaseDatabase.net.4.0.3.snupkg.zip)

You are right about the DebugType in the repo - I changed the options locally on my machine and generate the snupkg locally. I assumed changing the DebugType doesn't affect the result binary, only the form of the PDB. Was this assumption wrong, and the binaries depend on the DebugType?

**Comment by loic-sharma** [comment]
>  I assumed changing the DebugType doesn't affect the resulting binary, only the form of the PDB. Was this assumption wrong, and the binaries depend on the DebugType

Yup, the `DebugType` must be set to `portable` if you wish to use NuGet.org's symbol server. Please let us know if you need more help!

**Comment by loic-sharma** [comment]
Hi, please let us know if you have any additional questions! I'll close this off for now.
