### ISSUE TITLE
NuGet.org gallery doesn't support packages with minClientVersion = 5.0.0

### ISSUE THREAD

**Issue by yukiwongky** [NuGet/NuGetGallery#7674]
### Describe the bug
Cannot push to nuget.org gallery when the minClientVersion is 5.0.0

### To Reproduce
1. Create a package with 
```
<metadata minClientVersion="5.0.0">
```
2. Attempt to push package via NuGet.exe or upload on the nuget.org manually.

### Expected behavior
Able to push package to nuget.org gallery with no error.

### Error
```
##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 400 (This package requires version '5.0' of NuGet, which this gallery does not currently support. Please contact us if you have questions.).
```

**Comment by skofman1** [comment]
Hi, Thanks for reporting!
It will take us a couple of weeks to deploy a change, so a work around would be to use a minClientVersion 4.1 or lower in your package.
To better understand your scenario, why do you use minClientVersion 5.0.0 in your package? Is there a breaking change in your usage of NuGet your are communicating to package users?

**Comment by yukiwongky** [comment]
@skofman1 we've reverted our `minClientVersion` for now. We want to have the **BuildTransitive** feature introduced in [NuGet 5.0 RTM](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-rtm#summary-whats-new-in-50).

**Comment by loic-sharma** [comment]
Verified on INT:

* Uploaded a package that requires NuGet 5.0.0: https://int.nugettest.org/packages/My50MinClientPackage/1.0.0
* Uploaded a package that requires NuGet 6.0.0, received ` This package requires version '6.0.0' of NuGet, which this gallery does not currently support` error message
