### ISSUE TITLE
"Dependent repositories" is not great wording

### ISSUE THREAD

**Issue by sandyarmstrong** [NuGet/NuGetGallery#7677]
If I could make one suggestion: change the wording in the "info" sidebar from "Dependent repositories (223+)" to "Github Usage: 223+ repositories".

Even for native speakers, I feel pretty confident that a lot of people are going to read "Dependent repositories" and think it means how many dependencies the nuget package has, which is exactly the opposite of what you want to communicate, and may scare people away.

Sticking with "Github usage" is more consistent with the other new section on the page, too.

**Comment by loic-sharma** [comment]
Hi, thank you for the suggestion! I agree that "dependents" can be easily confused as "dependencies". 

We had a hard time finding the right text for the "Info" sidebar, and `Dependent repositories (123+)` was our best compromise. Believe it or not, we considered several texts similar to `GitHub Usage: 123+ repositories`, but we decided against them as we felt they didn't fit well the rest of the Info section. On the other hand, `Dependent repositories (123+)` felt a little more natural as it parallels text like `Download package (12.34 KB)` and `123 download per day (avg)`.

Going forward, we're considering replacing this compromise with a redesign of the package display page. We'd like one of the core pillars to be "Who uses this package", which would include both GitHub repositories as well as other NuGet packages hosted on NuGet.org. This is still in the early stages though, so I don't have anything to share with you at this time.

Do please let us know if you have any feedback! :)
