### ISSUE TITLE
Acct Mgmt:Increase the session time-out period in the server

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#768]
This is an issue reported in Jabbr.
Seems like the session time out period for NuGet gallery web site is very low and users have to login after every ~20 mins of inactivity.

We need to see if this can be increased and the security implications around it.

**Comment by nealmcb** [comment]
I'm glad to see this was taken care of.  For convenience, the relevant item of #1109 seems to be:
  -Stay signed on forever by default [DONE]

For the record, I'd like to know, though, if there is an option to have a session timeout for inactivity, and if the user can customize the time out period.
