### ISSUE TITLE
[readme] "Show more" button is present with no text shown

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7695]
Package: https://www.nuget.org/packages/AjaxControlToolkit/18.1.1#
Expected behavior: we show a proper short text

**Comment by karann-msft** [comment]
As part of this work, we should kill the "Documentation" subheading and just show the md content fully expanded like this:
![image](https://user-images.githubusercontent.com/16904420/68702601-f765a880-053d-11ea-9e6d-5986ce2593b2.png)

**Comment by karann-msft** [comment]
More issues around this - check out the behavior of clicking "show more" on this page https://www.nuget.org/packages/Microsoft.Azure.KeyVault/3.0.4

**Comment by shibaev** [comment]
We found the same issue with https://www.nuget.org/packages/BitMiracle.Docotic.Pdf/ package. Depending on the "Documentation" contents and browser's window width, the short version might be shown or not on page load.

Currently, we found a hack to avoid this issue in desktop browsers. Look at the attached markup in [docotic-pdf-nuget-doc.zip](https://github.com/NuGet/NuGetGallery/files/5601223/docotic-pdf-nuget-doc.zip). Pay attention to the line 8 with ` character. 
Without this character, the "Documentation" is fully collapsed by default. With the ` character, the "Documentation" is properly shown in desktop browsers (Chrome, Firefox, Edge, IE) when the width of browser's window is greater than 612px (on my 1920x1080 display).

However, the hack does not help on mobile devices or when the desktop browser's window is narrow.

It's looks that the JS component for collapsible content on nuget.org is buggy.

**Comment by skofman1** [comment]
@shibaev , thanks for providing a repro! We are currently working on revamping our "Documentation" section and hope to take a look at this as part of it!

**Comment by shibaev** [comment]
@skofman1, you are welcome! Looking forward for the fixed "Documentation" section.

**Comment by chgill-MSFT** [comment]
Closing this since the new nuget.org details design doesn't require an expander 🙂

https://devblogs.microsoft.com/nuget/introducing-the-new-nuget-org-package-details-page/
