### ISSUE TITLE
Package "gfi.ch.common.client" appears in registration but it is deleted

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7696]
Package ID: gfi.ch.common.client

I think this is because of this bug: https://github.com/NuGet/NuGetGallery/issues/7680

Gallery (404):
https://www.nuget.org/packages/gfi.ch.common.client

Registration (200, just version 0.0.9):
https://api.nuget.org/v3/registration4-gz-semver2/gfi.ch.common.client/index.json

The index.txt from lightning probably had something like that:

<details>
<pre>
Element@28557. Gfi.ch.Common.Client
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.1.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.2.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.18.51.22/gfi.ch.common.client.0.0.9.1.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.3.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.4.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.5.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.1.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.2.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.3.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.4.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.5.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.6.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.7.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.8.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.6.9.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.7.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.7.5.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.0.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.1.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.2.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.3.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.4.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.5.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.6.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.7.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.20.15.30/gfi.ch.common.client.0.0.8.8.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.22.50.03/gfi.ch.common.client.0.0.9.0.json
Element@28697. Gfi.Ch.Common.Client
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.11.55/gfi.ch.common.client.0.0.3.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.13.27/gfi.ch.common.client.0.0.4.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.13.27/gfi.ch.common.client.0.0.5.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.13.27/gfi.ch.common.client.0.0.6.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.13.27/gfi.ch.common.client.0.0.6.1.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.13.27/gfi.ch.common.client.0.0.6.2.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.3.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.4.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.5.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.6.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.7.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.8.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.6.9.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.7.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.7.5.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.8.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.15.09/gfi.ch.common.client.0.0.8.1.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.2.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.3.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.4.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.5.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.6.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.7.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.8.8.json
https://api.nuget.org/v3/catalog0/data/2016.04.05.19.05.17/gfi.ch.common.client.0.0.9.json
https://api.nuget.org/v3/catalog0/data/2017.07.27.23.16.50/gfi.ch.common.client.0.0.9.1.json
</pre>
</details>

**Comment by joelverhagen** [comment]
We can probably just reflow the hard delete.

**Comment by scottbommarito** [comment]
I think we should run the monitoring pipeline over registration4 for the sake of catching any other issues as well.

**Comment by joelverhagen** [comment]
Reset Db2Monitoring maybe? Would that overload the queue?

**Comment by scottbommarito** [comment]
Resetting Db2Monitoring wouldn't help--it only revalidates packages that are in the DB but not V3. We would have to reset the cursor of Catalog2Monitoring and then revalidate everything.

**Comment by joelverhagen** [comment]
Closing for now. We'll revisit if there are many more problems.

**Comment by scottbommarito** [comment]
(I reflowed the hard-delete and the package is no longer present in registration.)
