### ISSUE TITLE
Setup instructions cannot create database(s)

### ISSUE THREAD

**Issue by festivegoose** [NuGet/NuGetGallery#7699]
When I clone the project and go through the setup instructions, specifically running `.\tools\Setup-DevEnvironment.ps1` I get errors on the database creation steps:

```
[BEGIN] Running Migrations
Updating Nuget Gallery database...
ERROR: Method not found: 'System.Data.Entity.ModelConfiguration.Configuration.IndexConfiguration System.Data.Entity.ModelConfiguration.EntityTypeConfiguration`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)'.
Updating Nuget Gallery Support request database...
ERROR: Method not found: 'System.Data.Common.DbConnection System.Data.Entity.Core.Common.DbProviderServices.CloneDbConnection(System.Data.Common.DbConnection)'.
Update Complete!
[DONE] Running Migrations
```

### To Reproduce
1. Clone project
2. Run `.\build`
3. Run `.\tools\Setup-DevEnvironment.ps1`

### Expected behavior
Expect database creation to occur so that project can run successfully.

**Comment by scottbommarito** [comment]
Hey @festivegoose, I looked into the issue you're running into. It seems like, in that script (that we don't run very often), [we hardcoded a version of EntityFramework](https://github.com/NuGet/NuGetGallery/blob/master/tools/Update-Databases.ps1#L8) we were on for a long time. Recently we've updated our EF version a couple times, and are using a feature that was introduced in EF 6.2.0.

If you change the version that's hardcoded there to a version of EF that's 6.2 or higher, the script should work as expected. We're planning on upgrading to EF 6.4 soon (when it releases) so we'll update the script officially when it does.

**Comment by festivegoose** [comment]
That worked @scottbommarito , thanks a bunch!

**Comment by scottbommarito** [comment]
Glad that worked for you, @festivegoose!

I'm going to reopen this, though, so we'll remember to update the script when we stabilize the version.

**Comment by joelverhagen** [comment]
Turns out the latest versions of EntityFramework 6, starting in 6.3 time, no longer have `migrate.exe`. They now have `ef6.exe`. The script will need to be changed to use this new tool, which doesn't seem to have docs yet:
https://github.com/aspnet/EntityFramework.Docs/issues/1740

**Comment by joelverhagen** [comment]
I've updated the script to:

1. Automatically discovery the current version
2. Use `ef6.exe` instead of `migrate.exe`, the latter of which no longer exists in the package.
