### ISSUE TITLE
The package does not pass validation

### ISSUE THREAD

**Issue by zhenlei520** [NuGet/NuGetGallery#7759]
### Describe the bug
The project has been published many times and is stuck in the Validating step. I don't know why. This is just a small class library

### To Reproduce
1. The source address

https://github.com/zhenlei520/System.Extension.Core/tree/release/features-2.0

2. Release package details

https://www.nuget.org/packages/EInfrastructure.Core.ServiceDiscovery.Consul.AspNetCore/
https://www.nuget.org/packages/EInfrastructure.Core.Config.IdentificationExtensions/

![image](https://user-images.githubusercontent.com/9740886/70515068-ac0bdd80-1b6f-11ea-848a-fd67fec02f46.png)
![image](https://user-images.githubusercontent.com/9740886/70515110-bd54ea00-1b6f-11ea-96d6-310e90e17f19.png)

**Comment by agr** [comment]
Hi, sorry about the delay. NuGet.org had issues with the publishing pipeline that were resolved later that day and your packages were published.
