### ISSUE TITLE
Show license from README.md file

### ISSUE THREAD

**Issue by NN---** [NuGet/NuGetGallery#7760]
### Is your feature request related to a problem? Please describe.
There is a package where NuGet doesn't show license https://www.nuget.org/packages/DNS/.
[README.md](https://github.com/kapetan/dns/blob/master/README.md#license) has the license inside.

### Describe the solution you'd like
Show license in NuGet gallery

### Additional context
![image](https://user-images.githubusercontent.com/580536/70518186-97fdb700-1b42-11ea-8ea8-773ea6f177e2.png)
![image](https://user-images.githubusercontent.com/580536/70518204-a0ee8880-1b42-11ea-8968-ddf97dc3f525.png)

**Comment by agr** [comment]
Hi, nuget.org supports packages that specify the [license](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) in its metadata. Please, have the package updated to either include an SPDX expression or to have the license file as specified in the documentation.

**Comment by NN---** [comment]
Ok.
GitHub shows license tab when you have LICENSE file.
