### ISSUE TITLE
A/B test prefix matching on nuget.org

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7764]
⚠️ Do not copy this issue! This used a special A/B test process. For correct instructions, follow this process in the OneNote: [Rebuild the Azure Search Index](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Operations.one%7CC674B49C-4CB7-4793-8890-A1E46E33FEB9%2FRebuild%20the%20Azure%20Search%20Index%7CC705999F-85D9-4A93-8CFB-161C393C56FE%2F%29).

1. Determine the live instance of the Azure Search jobs
    - [ ] "a"
    - [x] "b"
    - [ ] "c"
1. ~~Determine the new instance to be used~~
    - [ ] "a"
    - [x] "b"
    - [ ] "c"
1. Update the job and service configuration
    - [ ] ~~NuGetDeployment PR:~~
    - [ ] ~~Infrastructure build:~~
    - [ ] ~~NuGet.Jobs Config build:~~
    - [x] AzureSearchService build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3385062
1. ~~Deploy Azure Search infrastructure to provision the resources and secrets~~
1. ~~Deploy Db2AzureSearch to initialize the new indexes~~
1. ~~Deploy alternative instances of the Azure Search jobs~~
1. ~~Monitor the new Catalog2AzureSearch cursors~~
1. ~~Deploy V3 monitoring to start monitoring the new indexes. If you are not rebuilding for an A/B test all this really will do is add an additional cursor to wait on.~~
1. Deploy AzureSearchService
    - ⚠️ The Azure Search Service must be deployed after all other jobs.
    - Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=552548
    - DEV
       - [x] USNC
       - [x] USSC
       - [x] EA
       - [x] SEA
    - INT
       - [x] USNC
       - [x] USSC
    - PROD
       - [ ] USNC
       - [ ] USSC
       - [ ] EA
       - [ ] SEA
1. ~~Change the default Instance name for job release pipelines~~
1. Wait a week.
1. ~~Clean up~~
   - ~~Stop monitoring the old cursors~~
   - ~~Stop monitoring the old indexes by deploying V3 monitoring~~
   - ~~Stop old job instances~~
   - ~~Update the [Secret Rotation excel](https://microsoft.sharepoint.com/teams/NuGet/Team/Engineering/NuGet_Secret_Rototation_Status.xlsx?web=1) to make sure new secrets are there and old secrets are gone~~

**Comment by loic-sharma** [comment]
```
where timestamp > todatetime('2020-01-17T00:00:00Z')
```

**Comment by loic-sharma** [comment]
## A/B test results

KPI | Control | Treatment | Result
-- | -- | -- | --
Bounce % | 33.388% | 33.271% | ✔
Clicks on first page % | 95.702% | 96.231% | ✔
Avg. click index on first page | 1.574 | 1.532 | ✔

**Comment by loic-sharma** [comment]
Reopening as I will need to zero out gallery’s ab test config and disable flight. I will do this Tuesday next week

**Comment by loic-sharma** [comment]
AB test is now disabled
