### ISSUE TITLE
Gallery feedback button shifts all the content to the right

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#7774]
1. Go to https://dev.nugettest.org
2. Click on the feedback button.

Notice the content shifts right as the feedback dialog appears.
At the same time the feedback button gets partially obscured by the scrollbar:
![image](https://user-images.githubusercontent.com/102933/70952086-1b734880-201a-11ea-964e-57f42fb9430a.png)

**Comment by joelverhagen** [comment]
This is known and should only occur while the modal is open. Same behavior on other Usabilla enabled sites (e.g. our blog site). Agreed that it is not ideal but I don't consider it a ship blocker. I have not investigated how much we can even do about it. I think we would need to leverage a Usabilla extension point for this.
