### ISSUE TITLE
A new version of a package shows previous icon

### ISSUE THREAD

**Issue by gsscoder** [NuGet/NuGetGallery#7792]
I've recently pushed a release with a new icon, but I still se the previous one on NuGet.org.

**package link**:
https://www.nuget.org/packages/CSharpx/1.2.3-rc2

**github of the project**:
https://github.com/gsscoder/csharpx

I had to use deprecated `PackageIconUrl` because, it's seem impossible to point a file with `PackageIcon`.

Thanks in advance.

**Comment by agr** [comment]
Apologies for the late response. I see that you figured out how to ship your icon with the package. I just had the icon updated on the older versions that had package URL specified.

Do you think our icon packaging documentation is lacking some details that prevented you to make it work in the first place? Any improvement suggestions?

**Comment by gsscoder** [comment]
@agr, no need to apologize! Instead thanks for excellent web app.

It was my fault... I didn't create a **NuGet** package for years and forgot how to pin the icon locally. Using URL is not properly updated, but this is not a problem since `IconPackageUrl` is deprecated.

I can't say about documentation, I solved using **Visual Studio** UI and than inspecting how it modified `csproj`.
Anyway is better to point out the need of `PackageIcon` and `ItemGroup` tags.

Thank you
