### ISSUE TITLE
No documentation on publishing "Documentation" content/URL from the API

### ISSUE THREAD

**Issue by lissyx** [NuGet/NuGetGallery#7800]
### Describe the bug
Ability to upload README content from the API is missing from the documentation ?

### To Reproduce
I can manually upload a version-specific documentation :
1. Go to the "Manage" page of a package
2. Unfold the "Documentation" part
3. Put raw content or a Github link, or upload from a local file

### Expected behavior
We should be able to upload at the same time we publish a package. I suspect (hope?) it's possible, but searching  the following documentations yielded nothing:
 - https://docs.microsoft.com/nuget/api/package-publish-resource
 - https://docs.microsoft.com/nuget/api/registration-base-url-resource
 - https://docs.microsoft.com/nuget/api/nuget-protocols

I also tried by spying quickly to what is being done when manually uploading  with Devtools, but I could not yield anything really actionable API-wise.

### Additional context
We are building and publishing from CI, so manually uploading is really not an option. I have seen there is expected work to make the NuGet self-contained including the README/documentation part, but so far this work has not yet started.

So, is it possible or not to perform this documentation upload step from the API ?

I'm quite a newbie in regards of the NuGet world, so it's possible I am missing something obvious here. Please direct me to the proper resources if they exists !

**Comment by loic-sharma** [comment]
Hi, thanks for opening this issue! You're right that today there's no supported API to upload a README. We realize that uploading a readme after uploading a package isn't the best experience, so we're working on a spec to package the documentation directly into the NuGet package itself: https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg

Please let us know if you have any feedback on the spec! 😊

**Comment by lissyx** [comment]
Right, this is the pending work I was referring to. At least I know I'm not insane, thanks. Let's close this, and honestly I know nothing about nuget nor the ecosystem around to be able to give feedback. I'll wait for it to be usable 😊
