### ISSUE TITLE
ID Prefix Reservation

### ISSUE THREAD

**Issue by SoftCircuits** [NuGet/NuGetGallery#7816]
I have twice now followed the instructions for reserving an ID prefix to a name that matches the prefix of all 14 of my packages. It is also a name that I hold a federal trademark on. The second time, I also sent an email to an address I had for NuGet saying that it was my second attempt and that I had heard nothing back from the first attempt.

In both cases, I never heard anything back and my ID prefix is still not reserved.

Is this a process that for some reason is normal to take several months? Or is it possible that the request was silently rejected for some reason? What should be my expectations for sending such an email into the void?

**Comment by loic-sharma** [comment]
Sorry about that, it looks like your ID prefix email may have slipped through the cracks during the holidays! We'll take a look and get back to you soon

/cc @karann-msft

**Comment by SoftCircuits** [comment]
I would appreciate it.

**Comment by loic-sharma** [comment]
Closing this for now. Feel free to reach out again if needed!

**Comment by SoftCircuits** [comment]
I appreciate the info. Still waiting though. I have no idea how long this should take before I see a response of some type.

**Comment by loic-sharma** [comment]
@karann-msft handles these requests and acknowledged that he saw the email. I believe he is still working through requests from the holidays. Feel free to ping here if you don't receive a reply within a few days.

**Comment by karann-msft** [comment]
@SoftCircuits - for future reference, this repo is not meant for following up on support requests. Email support@nuget.org for any questions on support requests. We process requests in the order in which it was received. We will get to your request as soon as possible. I appreciate your patience.

**Comment by SoftCircuits** [comment]
> @SoftCircuits - for future reference, this repo is not meant for following up on support requests. Email [support@nuget.org](mailto:support@nuget.org) for any questions on support requests. We process requests in the order in which it was received. We will get to your request as soon as possible. I appreciate your patience.

Understood. But after sending several emails to that address and still not hearing anything back after about six weeks, I thought I'd try something else.

**Comment by karann-msft** [comment]
for some reason, your emails are being marked as spam which is why there has been a delay in the response.

**Comment by SoftCircuits** [comment]
@karann-msft Well, **that** is frustrating. If you happen to notice why, please let me know. At any rate, it looks like my request has now been processed. Thanks.
