### ISSUE TITLE
Search:The search bar can provide a gesture to add search filters

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#782]
We have enabled search using "id", "author" "description" "title" and "tags".
But it is not very discoverable to the end user.
It would be good to provide a drop down arrow with the search bar to add search filters. Take a look at the "test explorer" windows's search ( Visual studi -->Test --> Window -->Test explorer" ) for example. Attaching a screen shot for the same.
![SearchFilter](https://f.cloud.github.com/assets/2625465/141330/ea41eada-7244-11e2-8cbc-907658d32118.PNG)

**Comment by robertmuehsig** [comment]
This is a pretty old issue, but why not give it a try in the fresh look. 
I'm not sure if this is the solution for this issue, it is more like in #1210 suggested - a small hint how the search syntax works on NuGet.org and everywhere else:

![image](https://user-images.githubusercontent.com/756703/29477921-bbfca268-846a-11e7-9187-42ffaed4c402.png)

Simple idea: If you enter a search term, but you get 0 package results the small hint appears and points to: https://docs.microsoft.com/nuget/consume-packages/finding-and-choosing-packages#search-syntax

This is more or less like the github search experience if you enter nothing and just press search:

![image](https://user-images.githubusercontent.com/756703/29478014-21afd882-846b-11e7-93c4-0e146e880c9b.png)

It is not super fancy, but should be accessible from all kinds of clients (mobile / tablet / screenreader etc.)

I also played with the top-message, but currently I can't inject HTML (the HTML will be html encoded)  to generate the link and maybe this isn't the right place at all.

![image](https://user-images.githubusercontent.com/756703/29478086-82e99d90-846b-11e7-8f35-1684946759b6.png)


What do you think?

**Comment by robertmuehsig** [comment]
Any comments @skofman1 @joelverhagen ?

**Comment by skofman1** [comment]
@robertmuehsig , I like this idea! @anangaur , thoughts?

**Comment by joelverhagen** [comment]
Great idea. This is just linking to existing docs, so it seems perfect!

**Comment by anangaur** [comment]
Yepp.. Lets get going.. 👍
