### ISSUE TITLE
NuGet Package restore failed for project,Unable to find version

### ISSUE THREAD

**Issue by vikassangal** [NuGet/NuGetGallery#7820]
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Tests\WebTests: Unable to find version '12.2.7221' of package 'Progress.Sitefinity.Ecommerce'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Progress.Sitefinity.Ecommerce.12.2.7221' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Progress.Sitefinity.Ecommerce.12.2.7221' is not found on source 'https://api.nuget.org/v3/index.json'.

**Comment by skofman1** [comment]
@vikassangal , package 'Progress.Sitefinity.Ecommerce' is not hosted on nuget.org and never was.
