### ISSUE TITLE
Not able to add package from file

### ISSUE THREAD

**Issue by rajputvishwas** [NuGet/NuGetGallery#7833]
### Describe the bug
I am trying very basic demo explained at https://softchris.github.io/pages/dotnet-core.html#download-and-use-a-package-from-the-nuget-repository
As explained in the demo, I am trying to add Newtonsoft.Json package to my project. I am behind the proxy and not able to download the package from https://api.nuget.org/v3/index.json. However, I have downloaded the package manually and attempting to add it to project. 

Get-PackageSource

Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
nuget.org                        NuGet            False      https://api.nuget.org/v3/index.json
**NewtonSoft.Json**                  NuGet            True       **D:\mypoc\ignite\demo1\library\newtonsoft.json.12.0.3.nupkg**
PSGallery                        PowerShellGet    False      https://www.powershellgallery.com/api/v2

### To Reproduce

Project structure:
02/04/2020  12:27 PM    <DIR>          .
02/04/2020  12:27 PM    <DIR>          ..
02/04/2020  11:53 AM    <DIR>          bin
02/04/2020  12:21 PM               135 library.csproj
02/04/2020  11:57 AM         2,596,051 newtonsoft.json.12.0.3.nupkg
02/04/2020  11:53 AM    <DIR>          obj
02/04/2020  11:54 AM               183 Thing.cs
               3 File(s)      2,596,369 bytes
               4 Dir(s)  294,733,180,928 bytes free

 dotnet add library package Newtonsoft.Json

### Expected behavior
It should add the package

### Screenshots
![image](https://user-images.githubusercontent.com/15668995/73727543-b43f5e00-4757-11ea-8652-66f7159da4f6.png)

**Comment by skofman1** [comment]
@rajputvishwas , the command you are using - `Get-PackageSource` is used for PowerShell packages. Those are used for sharing PowertShell resources.
To configure dotnet to use your local folder to find packages you have a few options:
1. Update `nuget.config` file manually: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file
2. Use nuget.exe tool as described here: https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds
