### ISSUE TITLE
Incorrect error message when PDB does not match DLL

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7844]
### Describe the bug

A user wants to update their .snupkg associated with an already pushed package:
https://www.nuget.org/packages/tusdotnet/2.2.2

There is an existing .snupkg that was accepted but subsequent attempts fail with this error:

> The uploaded symbols package contains one or more pdbs that are not portable.

However upon closer investigation, the failure is not because the PDBs are portable but because the PEReader saw that the PDB and DLL do not match.

I think the error is here:
https://github.com/NuGet/NuGet.Jobs/blob/dbd927c309005b63b82c1017ff6bfcfec96434cf/src/Validation.Symbols/SymbolsValidatorService.cs#L251

This should use the error message `ValidationIssue.SymbolErrorCode_MatchingAssemblyNotFound`.

### To Reproduce

Upload a snupkg with a portable PDB that matches in name but does not match according to `PEReader.TryOpenAssociatedPortablePdb`.

### Expected behavior

The validation should fail with a more helpful error message.

### Screenshots

![image](https://user-images.githubusercontent.com/94054/74369714-b2465200-4d8a-11ea-8bed-bffec4118b73.png)

**Comment by joelverhagen** [comment]
There new message looks like this:

![image](https://user-images.githubusercontent.com/94054/74886496-31103180-532d-11ea-8aaf-e41d8b33c70f.png)

**Comment by smatsson** [comment]
Thanks for fixing this!
