### ISSUE TITLE
Can't publish symbols because name collision on nuget.org

### ISSUE THREAD

**Issue by heaths** [NuGet/NuGetGallery#7848]
### Describe the bug
I can no longer publish symbols on nuget.smbsrc.net because someone published (and later delisted) a package with the same name.

### To Reproduce
1. Download MSI nupkg from https://dev.azure.com/heaths/public/_build/results?buildId=210&view=artifacts&type=publishedArtifacts
2. Regenerate my key (it had expired), copy it, and try to publish to wither www.nuget.org (either package or symbol package) or nuget.smbsrc.net (symbol package).

### Expected behavior
I can publish the symbol package.

### Actual behavior
I get an HTTP 403 error. Seems someone published https://www.nuget.org/packages/msi, which is the name of my package for powershellgallery.com. I've been publishing symbols this way for a while, but no longer can because of a name collision on nuget.org. There was never a need to publish the package to nuget.org (it's a PowerShell module). Seems authentication and authorization shouldn't necessarily be tied together. Is there some other way?

I can't seem to log into www.symbolsource.org anymore either. I can't remember account information (it's been a long time since I logged in), but http://www.symbolsource.org/Public/Account/SendPasswordMail says it requires a secure connection, but www.symbolsource.org doesn't respond via HTTPS.

### Additional context

Link to MSI package on PowerShell Gallery: https://www.powershellgallery.com/packages/MSI

**Comment by loic-sharma** [comment]
Hi, the NuGet team doesn't run Symbol Source so we can't help. We're not sure who the best contact is for these kinds of problem, so I'd try reaching out to the .NET Foundation (possibly on [Twitter](https://twitter.com/dotnetfdn)).

I'll close this off for now since we can't take any further action, but feel free to comment if you have any additional questions!
