### ISSUE TITLE
Add fuget.org link to package details page

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#7850]
This is the issue tracking the community PR: https://github.com/NuGet/NuGetGallery/pull/7832 as it needs some UX and messaging work before going live.

Rationale for the feature: 
fuget.org shows API level data for the packages and lets you compare the APIs across versions. This has been super useful for developers and they have already been using this. It would make sense for developers to directly explore their package on fuget.org from nuget.org's package details page.

**Comment by anangaur** [comment]
We would need to add a couple of icons and messaging to tell users that fuget.org is a third-party site not owned by Microsoft. Working on a proposal...

**Comment by anangaur** [comment]
Here is the proposal (undergoing UX review):

![image](https://user-images.githubusercontent.com/14800916/75476419-68936500-594f-11ea-81ee-a8cd78cc9279.png)

Text for tooltip: **TBD**
Accessibility review: **TBD**

**Comment by praeclarum** [comment]
Hello, I'm very excited for this feature!

**Comment by chgill-MSFT** [comment]
Plans as of now:

**Icon (this is for show, svg will be used):** <img src="https://user-images.githubusercontent.com/15097183/84452554-f64b4580-ac0a-11ea-9f7c-7c0330d85766.png" alt="Image" height="30">

**Link tooltip:** “Explore additional package info on fuget.org”
**Info (i) icon tooltip:** “fuget.org is a 3rd party website, not controlled by Microsoft. This link is made available to you per the NuGet Terms of Use.”

**Link accessibility:** "Link, open in fuget.org explorer"
**Info (i) icon accessibility:** “fuget.org is a 3rd party website, not controlled by Microsoft. This link is made available to you per the NuGet Terms of Use.”
