### ISSUE TITLE
Download count isn't updated when self-hosting in IIS

### ISSUE THREAD

**Issue by jslootweg** [NuGet/NuGetGallery#7861]
I have configured a instance of NuGet Gallery running under IIS using SQL Server as the database.  The download count doesn't appear to updating regardless of whether the download is via NuGet Install-Package or through the package download link on the website.

**Comment by joelverhagen** [comment]
Hey @jslootweg, have you enabled the following setting in your web.config?

```xml
<add key="Feature.TrackPackageDownloadCountInLocalDatabase" value="true"/>
```

By default it is disabled. I just tried it locally and it seems to work okay.

**Comment by jslootweg** [comment]
Ah, that was it.  Thanks!
