### ISSUE TITLE
NuGet.org package statistics not updating for over a week

### ISSUE THREAD

**Issue by j82w** [NuGet/NuGetGallery#7869]
### Bug description
Several packages have been updated in the last 7 days, and the statistics are showing 0 downloads. The packages have been downloaded several times by multiple users.

### Impacted packages

https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Swagger/

**Comment by tidyui** [comment]
I have the same issues with all of our packages for Piranha CMS.

https://www.nuget.org/packages/Piranha/

First the numbers didn't changed and the update date stayed the same, now the `last updated` date is changing but the numbers are not changing. This is, given many years of statistics **highly** unlikely.

**Comment by j82w** [comment]
It seems like the statistics got fixed.
