### ISSUE TITLE
Deprecating TLS 1.0 and 1.1 on NuGet.org - Stage 2

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7875]
As announced in the blog post [here](https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/), it's time to permanently remove support for TLS 1.0, 1.1.
Exact date in April is TBD and will be announced several weeks in advance.

**Comment by agr** [comment]
Resources by environment:

# DEV
- [ ] Gallery
   - [ ] Cloud service
   - [ ] App service
- [ ] Search
- [ ] APIM
- [ ] CDN
  - [ ] apidev.nugettest.org
  - [ ] globalcdn.dev.nugettest.org
- [ ] Symbol server
- [ ] Licenses app service
- [ ] Status app service

# INT
- [ ] Gallery
   - [ ] Cloud service
   - [ ] App service
- [ ] Search
- [ ] APIM
- [ ] CDN
  - [ ] apiint.nugettest.org
  - [ ] globalcdn.int.nugettest.org
- [ ] Symbol server
- [ ] Licenses app service
- [ ] Status app service

# PROD
- [ ] Gallery
   - [ ] Cloud service
   - [ ] App service
- [ ] Search
- [ ] APIM
- [ ] CDN
  - [ ] api.nuget.org
  - [ ] globalcdn.nuget.org
- [ ] Symbol server
- [ ] Licenses app service
- [ ] Status app service

**Comment by jorismathijssen** [comment]
Has the support for TLS 1.0, 1.1 been removed today? 

Maybe this is unrelated but since this morning we have troubles with Install-PackageProvider nuget. The changes as described in the post seems to work.

**Comment by agr** [comment]
Production environment support was not removed. Qualys' SSL test still reports it as enabled: [`www.nuget.org`](https://www.ssllabs.com/ssltest/analyze.html?d=www.nuget.org), [`api.nuget.org`](https://www.ssllabs.com/ssltest/analyze.html?d=api.nuget.org).
DEV and INT environments however are in progress of disabling TSL 1.0 and 1.1 currently. Are you using those by any chance?

**Comment by jorismathijssen** [comment]
> Production environment support was not removed. Qualys' SSL test still reports it as enabled: [`www.nuget.org`](https://www.ssllabs.com/ssltest/analyze.html?d=www.nuget.org), [`api.nuget.org`](https://www.ssllabs.com/ssltest/analyze.html?d=api.nuget.org).
> DEV and INT environments however are in progress of disabling TSL 1.0 and 1.1 currently. Are you using those by any chance?
> What exactly you were trying to do and what errors did you get?

How can i check if im using the DEV or INT environments. I guess i'm not but i want to be sure.

I try to run the powershell command `Install-PackageProvider -Name NuGet` but i receive this warning: `Unable to download the list of available providers. ` The command was working before friday.

Just like this thread: https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/trying-to-install-program-using-powershell-and/4c3ac2b2-ebd4-4b2a-a673-e283827da143

**Comment by skofman1** [comment]
@jorismathijssen , from the thread here https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/trying-to-install-program-using-powershell-and/4c3ac2b2-ebd4-4b2a-a673-e283827da143 I see that the error you are getting is from https://onegetcdn.azureedge.net/. This domain doesn't belong to nuget.org. TLS 1.0 must have been deprecated by them as well.

**Comment by jorismathijssen** [comment]
> @jorismathijssen , from the thread here https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/trying-to-install-program-using-powershell-and/4c3ac2b2-ebd4-4b2a-a673-e283827da143 I see that the error you are getting is from https://onegetcdn.azureedge.net/. This domain doesn't belong to nuget.org. TLS 1.0 must have been deprecated by them as well.


Ow I feel a little bit stupid. You are definitely right. Thank you for the information. It’s good to know that the upgrade works perfect. 

Thank you!
