### ISSUE TITLE
Can't upload package, says Package name reserved.

### ISSUE THREAD

**Issue by dariogriffo** [NuGet/NuGetGallery#7930]
Hi,
i'm trying to upload package using "Upload" button at https://www.nuget.org/packages/upload, but i'm receiving "The package ID 'NetCore.DependencyInjection.Modules' is not available.". I checked that package name - it not used at nuget gallery.

Can you help me with this?

**Comment by loic-sharma** [comment]
The prefix “NetCore.” is owned by the Microsoft account. You cannot create new packages that start with “NetCore.”, you will need to rename your package before uploading it.

**Comment by dariogriffo** [comment]
Renamed the package. Thanks a lot
