### ISSUE TITLE
Incorrect syntax near the keyword 'IF'. returned while running 201904292139301_RemoveVulnerabilityDataFromPackageDeprecationModel.cs migration

### ISSUE THREAD

**Issue by mihailmacarie** [NuGet/NuGetGallery#7931]
I took the latest version master branch builded the solution configured the connection strings and ran: 

`Update-Database -ConfigurationTypeName MigrationsConfiguration`

in Package Manager Console on NuGetGallery project.

While running 201904292139301_RemoveVulnerabilityDataFromPackageDeprecationModel.cs migration the Incorrect syntax near the keyword 'IF'. 

The fix this I had to replace :

`Sql("ALTER TABLE [dbo].[PackageDeprecations] DROP CONSTRAINT IF EXISTS [dbo.PackageDeprecations_CVSSRating];");`
 
with

`Sql("IF EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo.PackageDeprecations_CVSSRating]') AND parent_object_id = OBJECT_ID(N'[dbo].[PackageDeprecations]')) ALTER TABLE dbo.PackageDeprecations DROP CONSTRAINT [dbo.PackageDeprecations_CVSSRating];");`

**Comment by joelverhagen** [comment]
It looks like the `IF EXISTS` syntax in `ALTER TABLE` [was added in SQL Server 2016](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql). What version of SQL Server are you running?

> IF EXISTS
> **Applies to:** SQL Server ( SQL Server 2016 (13.x) and later) and Azure SQL Database.
> 
> Conditionally drops the column or constraint only if it already exists.

**Comment by mihailmacarie** [comment]
I'm using SQL Server 2012 which explains the issue.

**Comment by joelverhagen** [comment]
I see. We use Azure SQL Server for our production environments and LocalDB for local development so for us `IF EXISTS` is support everywhere. Apologies for the inconvenience.

We note the SQL Server 2016 requirement in the [README.md](https://github.com/NuGet/NuGetGallery/blob/master/README.md) but I am glad you were able to work around it.
