### ISSUE TITLE
An administrator needs to claim ownership of the company by DNS validation of X before the application NuGet.Org can be provisioned

### ISSUE THREAD

**Issue by markpiller** [NuGet/NuGetGallery#7932]
Trying to sign to my Nuget account and am getting this message:

```
AADSTS650051: Using application 'NuGet.Org' is currently not supported for your organization
 XXXX because it is in an unmanaged state. An administrator needs to claim ownership of the
 company by DNS validation of XXXX before the application NuGet.Org can be provisioned. 

Trace ID: 00a6abd7-0032-4e98-b22f-94d4026f4700 
Correlation ID: 3cda5e25-0c27-4c15-93df-166d1bfd9fe4 
Timestamp: 2020-04-06 16:19:09Z
```
I was able to sign to this very account just last week. How do I go about claiming the ownership?

**Comment by joelverhagen** [comment]
I would recommend taking a look at the nuget.org FAQ, especially the "account management" section. There is an entry about this specific case.
https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-login-issues-for-aad-accounts-with-unmanaged-tenant

If you have further problems, please reach out to support@nuget.org so we can work through your specific account.
