### ISSUE TITLE
Download page showing incorrect latest version

### ISSUE THREAD

**Issue by bbodenmiller** [NuGet/NuGetGallery#7933]
### Describe the bug
https://www.nuget.org/downloads is showing 5.4 at top as latest when it is not the latest version 5.5.1 is

### To Reproduce
1. https://www.nuget.org/downloads

### Expected behavior
Show correct latest version at top

### Screenshots
![image](https://user-images.githubusercontent.com/1192780/78588963-503b2380-77f4-11ea-8224-bfe142915b73.png)

**Comment by joelverhagen** [comment]
Thanks for bringing this to our attention. A nuget.exe version goes through several stages after it is first released. One of the last stages for a stable version is for it to become the "recommended latest". The 5.5.1 release has not reached this point yet. Personally I am not crystal clear on the time or other checks that need to occur to promote a version from simply "released" to being the "recommended latest". Perhaps @aortiz-msft or @rrelyea can chime in here with additional information.

**Comment by rrelyea** [comment]
We don't recommend it as soon as it becomes available, because many people auto-update to the latest recommended.

We wrote up some about the process here: 
https://github.com/NuGet/Home/issues/4851

**Comment by joelverhagen** [comment]
Great, thanks Rob. @bbodenmiller, it looks like this is expected and this point on https://github.com/NuGet/Home/issues/4851 speaks directly to what you are noticing:

> after a number of weeks (usually 2-6), we will call it good and publish to two other places:

**Comment by bbodenmiller** [comment]
Recommended latest is confusing. Why not just recommended version?
