### ISSUE TITLE
Improve ToU readability

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7934]
“You acknowledge that code (object or source) and related technology available via the Services (collectively, “Code”) may be subject to export control and economic sanctions laws, regulations, or orders of the United States or any other applicable jurisdiction (collectively, “Export Laws”). In using the Services, you agree to comply with all applicable Export Laws **, including end-user, end use, and destination restrictions imposed by such Export Laws.** ”

Remove the **bold** text.

**Comment by shishirx34** [comment]
modified the ToU. I see it reflected in Cloud service. App service will reload the content in one day.

![image](https://user-images.githubusercontent.com/1646506/79398245-06111b00-7f35-11ea-91a0-da465378fea7.png)
