### ISSUE TITLE
Waiting for validation. 2 days have passed.

### ISSUE THREAD

**Issue by erfg12** [NuGet/NuGetGallery#7946]
### Describe the bug
Waiting for validation. 2 days have passed.

### Expected behavior
Typically after submitting a new version it's approved within several minutes, not days.

### Additional context
https://www.nuget.org/packages/Memory.dll/

**Comment by joelverhagen** [comment]
Hello @erfg12, our internal partner which handles virus scanning has marked this package for review. The package is pending analysis. Apologies for the delay but nuget.org waits on a conclusive result from virus scanning before the package becomes available.

I have reached out to our internal partner for any update on the status of this package. I'll update this issue when I know more.

**Comment by erfg12** [comment]
ok, I got an email back that now says "failed for unknown reason". Not sure how I'm supposed to remedy this issue.

**Comment by joelverhagen** [comment]
Your package should now be available. Please feel free to reach out to support@nuget.org for further questions.
