### ISSUE TITLE
[Search] Opt-out of Azure Search's relevancy changes

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7947]
⚠️ This will block search index rebuilds after July 15, 2020!

From Azure Search's documentation: https://docs.microsoft.com/en-us/azure/search/index-ranking-similarity

> Starting July 15, 2020, newly created search services will use the BM25 ranking function, which has proven in most cases to provide search rankings that align better with user expectations than the current default ranking. ... With this change, you will most likely see slight changes in the ordering of your search results. 
>
> For services created before July 15, 2020: If the similarity is omitted or set to null, the index will use the old classic similarity algorithm.
> 
> For services created after July 15, 2020: If the similarity is omitted or set to null, the index will use the new BM25 similarity algorithm.
> 
> You can also explicitly set the similarity value to be one of the following two values: "#Microsoft.Azure.Search.ClassicSimilarity" or "#Microsoft.Azure.Search.BM25Similarity".

We should opt-out of `BM25Similarity` until we have validated that these change improve relevancy for NuGet's search.

**Comment by joelverhagen** [comment]
The improvement is minor:
```
Curated Search Queries
======================
Control:   0.745082727845896
Treatment: 0.746670341247443

Client Curated Search Queries
=============================
Control:   0.676177468352019
Treatment: 0.679542389231266
```

We can stick with it while we move to the new Azure SDK.

FYI this only applies when using the new Azure SDK. It appears our current legacy SDK safely keeps the classic similarity during index rebuilds.
