### ISSUE TITLE
curl no longer works with nuget.org

### ISSUE THREAD

**Issue by lilith** [NuGet/NuGetGallery#7951]
Previously, the following curl command would permit a package to be uploaded:

`curl -L "https://www.nuget.org/api/v2/package" -H "X-NuGet-ApiKey: [redacted] -H "X-NuGet-Client-Version: 4.1.0" -A "NuGet Command Line/3.4.4.1321 (Unix 4.4.0.92)" --upload-file Imageflow.NativeRuntime.ubuntu_18_04-x86_64.1.2.0-rc25.nupkg`

Now, it produces this (incorrect) error: 
`The specified API key is invalid, has expired, or does not have permission to access the specified package.The specified API key is invalid, has expired, or does not have permission to access the specified package.`

The API key is for *, is 1 day old, and 3 different api keys have to tried to reduce the possibility of human error. 

Given the state of nuget on linux, curl support is very important. Please help!

**Comment by joelverhagen** [comment]
cURL, with the headers you've provided, should work. I verified a push just a moment ago using the command you provided.

Could you verify that the API you created is associated with the organization that owns the package? I noticed that the [Imageflow.NativeRuntime.ubuntu_18_04-x86_64](https://www.nuget.org/packages/Imageflow.NativeRuntime.ubuntu_18_04-x86_64) package is owned by imazen, which is an organization. By default API keys are made for your individual account, not an organization.

![image](https://user-images.githubusercontent.com/94054/79501367-c4d74480-7fe2-11ea-9be7-32bfcdde00bc.png)

**Comment by lilith** [comment]
Thanks, I generated a new API key with imazen as the owner but I'm still getting the same message as before.
