### ISSUE TITLE
NUGET.SERVER - server packages from local

### ISSUE THREAD

**Issue by SeshagiriSriram** [NuGet/NuGetGallery#7957]
I have set up a local server with nuget.server. I can push packages to the repos. When I try to do install like so: 
nuget install <package>
Unable to load the service index for source '<mylocalrepos>' 
The content at '<mylocalrepos>' is not a valid JSON object
Am i missing something here? The source is defined in Nuget.Config as http://myserver/nuget

**Comment by joelverhagen** [comment]
Could you paste your entire nuget.config? Feel free to obfuscate secret values but try to leave as much as possible so I can spot any issues.

Also, could you try a nuget.exe command with the package source specified as a command line parameter, `-source`.
