### ISSUE TITLE
Windows Hello Identity error

### ISSUE THREAD

**Issue by CyberMonster** [NuGet/NuGetGallery#7969]
### Component:
Windows Hello Identity.
### Description:
When I try login to the gallery using windows hello feature, have an error.
### Error message:
Request Id: f79fa9c6-7ee3-458a-9b0c-3e52aadc2b00
Correlation Id: 9cfccb0f-99d1-468a-8ea0-01fe7720975a
Timestamp: 2020-04-27T10:48:31Z
Message: AADSTS135021: Invalid UserHandle prefix.

**Comment by joelverhagen** [comment]
Hey @CyberMonster, for account management issues, I'd recommend reaching out to support@nuget.org.

**Comment by shishirx34** [comment]
@CyberMonster - were you able to resolve this issue? do you still need help here? Please reach out to us with the issue details and screenshot of the error at support@nuget.org. Please feel free to include my github handle @shishirx34 in the mail so that the request gets routed to me correctly.
