### ISSUE TITLE
Embedded licenses files in MD are not encoded as HTML for display.

### ISSUE THREAD

**Issue by JimBobSquarePants** [NuGet/NuGetGallery#7975]
### Describe the bug

According to the specification embedded license files are accepted in either TXT or MD format.
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#license

However, MD files are not converted to HTML for display on the site and are rendered as raw Markdown.

### To Reproduce
1. On this URL 'https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.0-rc0001/License'

### Expected behavior

I would expect the markdown to be encoded as HTML.

**Comment by rocklan** [comment]
@skofman1 I have created a pull request for this. I'm sure it will take a while for it to be tested properly. It works on my machine :)

**Comment by skofman1** [comment]
Thanks for the contribution @rocklan ! Very cool! 
@zhhyu will work with you next week on reviewing and testing the PR and eventually merging it in. Can't wait to see it live!

**Comment by rocklan** [comment]
thanks and appreciate your enthusiam @skofman1 :)

**Comment by zhhyu** [comment]
Hi, all! We will enable this feature after finish following issues: 1. https://github.com/NuGet/NuGetGallery/issues/8277; 2. https://github.com/NuGet/NuGetGallery/issues/8278 Thanks! :relaxed:
