### ISSUE TITLE
Download count decreased for the VaultSharp package

### ISSUE THREAD

**Issue by rajanadar** [NuGet/NuGetGallery#7986]
### Bug Description
The download count for the VaultSharp package decreased in the last week, from 821,000 odd to 789,000 odd.

### To Reproduce
1. On this URL https://www.nuget.org/packages/VaultSharp/ see the download count. 

### Expected behavior
Download count should be around 821,000 odd. I don't have a screenshot for it, but that was the count 2 days ago. The download count it shows is 789,000 odd. 

### Additional context
It seems like the count got reset to a value that belonged to last week. The reduced number seems very familiar.

**Comment by skofman1** [comment]
Hi @rajanadar , apologies for the slow response and the inconvenience. Our statistics service has been malfunctioning lately and we are working on rebuilding it. I see download counts for VaultSharp are now 943K, so closing this issue.
