### ISSUE TITLE
Contact support out-of-service

### ISSUE THREAD

**Issue by agoling** [NuGet/NuGetGallery#8014]
### Describe the bug
“Contact support” out-of-service，Wrong report from https://www.nuget.org/ ，Please see the picture
![image](https://user-images.githubusercontent.com/37896493/83095304-98c8dc00-a0d5-11ea-892a-415ec8ee667c.png)

**Comment by agoling** [comment]
Unable to submit data

**Comment by joelverhagen** [comment]
Thanks for taking the time to report this. I tried the same flow on one of my own packages and didn't run into any problem. 

From the error it looks like the reCAPTCHA script (an external script from Google) is failing to load.

Could provide the following information?

1. Do you have any script blocking or ad blocking software installed on your computer or as a browser extension? If so, could you temporarily disable it so see if that's the problem?
2. Does any other package you own have a working Contact support form? Or does this Contact support form not work on any of your packages?
3. Could you capture a HAR file of loading that page and attempting to click submit on the form? This can be done in Chrome web tools Networking tab (close to the tab you have open there). Please send the HAR file to support@nuget.org.
4. Could you try the same form on another web browser on the same computer?
5. Could you try the same form on another computer or perhaps your smartphone?

**Comment by joelverhagen** [comment]
Please let us know if you are still encountering issues. I'm closing this issue since I have not heard back from you.
