### ISSUE TITLE
 NuGet.org package statistics not uploading

### ISSUE THREAD

**Issue by devlead** [NuGet/NuGetGallery#8020]
### Describe the bug

Packages download count is still 0 after 3 days.

### To Reproduce

1. On this URL
    * https://www.nuget.org/packages/Cake.Tool/
    * https://www.nuget.org/packages/Cake
    * https://www.nuget.org/packages/Cake.Common

2. Perform this operation 
    * Look at "Version history"

3. See error
   * 0.38.1 zero downloads
   * 0.38.0 zero downloads

### Expected behavior

We've confirmed several people are using the latest version, so we would expect download counts to increase a bit each day, at least be more than zero.

### Screenshots

![image](https://user-images.githubusercontent.com/1647294/83488376-09dd0a80-a4ad-11ea-8a4b-f1505ae78d57.png)
![image](https://user-images.githubusercontent.com/1647294/83488458-28db9c80-a4ad-11ea-8c6a-e08a286274c3.png)
![image](https://user-images.githubusercontent.com/1647294/83488562-59233b00-a4ad-11ea-84ba-ce3dcf874255.png)

**Comment by agr** [comment]
Hi, thanks for bringing it up, I see the download counts are non-zero now, but detailed data is not available for those versions yet, we are looking into it.

**Comment by agr** [comment]
The issues with statistics pipeline were mitigated. We are working on addressing the performance issues with statistics pipeline.
