### ISSUE TITLE
Stats figure trimming doesn't respect locale

### ISSUE THREAD

**Issue by drewgillies** [NuGet/NuGetGallery#8032]
On statistics page, this change (https://github.com/NuGet/NuGetGallery/pull/7990) has unit tests which fail in non-decimal-point locales. So does the actual trimming logic for the number. 
Examples:
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3797637&view=results
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3794657&view=results
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3790561&view=results

**Comment by agr** [comment]
The fix could use `UseInvariantCulture` attribute introduced in https://github.com/NuGet/NuGetGallery/pull/8021
