### ISSUE TITLE
Search: Extend search based on package type and package content

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#804]
We had this discussion during our stand-up and during "package explorer" functionality. Logging it for future tracking.
1. It would be good to be able to search packages based on their technology - like .Net. Javacscript and Native (as we are going to support native).
   2  It would be nice to be able to search for packages based on their content.

**Comment by skofman1** [comment]
Similar suggestion is tracked here: https://github.com/NuGet/NuGetGallery/issues/3098
