### ISSUE TITLE
Increase package size limit/and or support LZMA

### ISSUE THREAD

**Issue by lostmsu** [NuGet/NuGetGallery#8042]
### Is your feature request related to a problem? Please describe.
I am trying to package TensorFlow binaries, but the uncompressed size of a single 2.x GPU binary is 1.3GB. ZIP+Deflate-compressed is ~400MB. XZ+LZMA2-compressed is ~100MB, but NuGet does not support LZMA2 compression, meaning unpacking needs installation scripts, which are no longer supported.

### Describe the solution you'd like
Overall, I think supporting LZMA2 or even just ZIP+LZMA would be the best solution, but the client team already closed that issue for whatever reason https://github.com/NuGet/Home/issues/890 . So as an alternative for my scenario it would be sufficient to up the limit to 500MB, or better 750MB to be future-proof.

### Additional context
N/A

**Comment by skofman1** [comment]
@lostmsu , nuget.org's upper bound for package size is 250MB. Both server and clients are built with this in mind so increasing the size substantially may lead to unexpected results and impact user experience.
Our recommendation for users who need to upload a large package is to split it to several packages and have a "metapackage" that depends on the smaller ones.

**Comment by lostmsu** [comment]
@skofman1 any suggestions on how to split a single file?

Also not sure what is the problem with increasing package size on both client and the server. If older clients won't be able to download the package - it is not a problem - they would only be unable to download the new package version, which does not yet exist.

**Comment by walbourn** [comment]
ADO has a 512 MB limit, so it seems odd to not match that.
