### ISSUE TITLE
Published package with wrong name.

### ISSUE THREAD

**Issue by AndreVianna** [NuGet/NuGetGallery#8069]
I have published the package TheToolBox.Data.Contracts v1.0.0 with the wrong name.
It should be TheToolbox.Data.Contracts (with lower case "b").

I contacted the support to remove the package but nothing happened.
I've tried to upload a new version (1.0.1) with the new name (after unlisting the old one) but it is still shown the old name.

Please help!!!!!

**Comment by zhhyu** [comment]
The packages have been hard deleted, and you should be able to publish the package with the correct name again.

**Comment by AndreVianna** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
