### ISSUE TITLE
Allow package metadata to be editable

### ISSUE THREAD

**Issue by FransBouma** [NuGet/NuGetGallery#807]
Whenever I change an item in the package meta-data which is displayed on e.g. the nuget website, like the project url, I have to bump the version of the package. This is a problem, because the actual code didn't change, no version bump occurred there. People using my assembly through nuget now see an updated version, but there's no changelog, no change at all, just an URL changed in the meta-data of the package. 

It should be possible to re-upload nuget packages to the nuget repository if the meta-data changed but the actual dll didn't. I at least should get the choice to overwrite the package with the new one, if it's the same version. It's my responsibility after all whether that's the wisest choice to do.

I ran into this because I moved some projects from codeplex to github and wanted to change the project url in the package from the codeplex site to the github project site. This required a version bump, which I don't want to do. 

Some projects do bump the version of the package and awkwardly use another version number in the text to signal the real version of the code (e.g. log4net, which uses v2.0 on nuget, but the code is 1.2). This is confusing and awkward and as it's about meta-data around the code which is used/referenced by projects, it should not require one to bump the version number.

**Comment by opcodewriter** [comment]
I need to update one of the dependencies of a local nupkg installed from NuGet.
How can I do this?
