### ISSUE TITLE
Unable to publish packages to nuget with "Kubernetes" anywhere in package name

### ISSUE THREAD

**Issue by jkonicki** [NuGet/NuGetGallery#8110]
### Describe the bug
When trying to publish, with nuget cli, a new package under our reserved prefix `Steeltoe` we are getting a message that "This package ID has been reserved." message.  

This appears to only happen to our package with the word `Kubernetes` in the package name.  
```
“Steeltoe.Common.Kubernetes.3.0.0-m3.nupkg' already exists at feed 'https://www.nuget.org/api/v2/package'.
2020-07-14T19:16:15.4087082Z This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.”
```

I excluded this specific package and all other packages published without a problem, until it got to another package with the work `Kubernetes` in it. The same "This package ID has been reserved" message came up.   
```
2020-07-14T20:00:22.2858563Z Package 'D:\a\r1\a\_SteeltoeOSS.steeltoe\Packages\Steeltoe.Extensions.Configuration.KubernetesBase.3.0.0-m3.nupkg' already exists at feed 'https://www.nuget.org/api/v2/package'.
2020-07-14T20:00:22.2867646Z This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.
2020-07-14T20:00:22.2957046Z Pushing Steeltoe.Extensions.Configuration.KubernetesBase.3.0.0-m3.snupkg to 'https://www.nuget.org/api/v2/symbolpackage'...
2020-07-14T20:00:22.2958465Z   PUT https://www.nuget.org/api/v2/symbolpackage/
2020-07-14T20:00:22.3862872Z   NotFound https://www.nuget.org/api/v2/symbolpackage/ 90ms
2020-07-14T20:00:22.6729059Z nuget : Response status code does not indicate success: 404 (Not Found).
2020-07-14T20:00:22.6730012Z At D:\a\_temp\94375afb-439d-46a9-bff8-2ce95a337705.ps1:7 char:6
2020-07-14T20:00:22.6731312Z +      nuget push $_ *** -So ...
2020-07-14T20:00:22.6732742Z +      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-07-14T20:00:22.6824420Z     + CategoryInfo          : NotSpecified: (Response status...04 (Not Found).:String) [], RemoteException
2020-07-14T20:00:22.6828244Z     + FullyQualifiedErrorId : NativeCommandError
```
When I excluded all Kubernetes named packages, publishing completed, but obviously without all the packages I need. 

**>>> Is there some sort of reserved term for `*Kubernetes*` for NuGet?  If yes, why? and how do I get approval?  Or is there some other issue we are not seeing?**

Thanks.

### To Reproduce
1. nuget push D:\a\r1\a\_SteeltoeOSS.steeltoe\Packages\Steeltoe.Extensions.Configuration.KubernetesBase.3.0.0-m3.nupkg $(NuGetApiKey) -Source https://api.nuget.org/v3/index.json -SkipDuplicate -Verbosity detailed

### Expected behavior
The Package should publish if it is using my prefix no matter what follows.

**Comment by agr** [comment]
Could you please verify that you use an API key that can push to Steeltoe.* namespace for those packages that failed?
Did you try uploading the package manually through the web site?

**Comment by jkonicki** [comment]
Hello, 
I used a key with Glob Pattern: * 

It is a new package, so I assume a key with that pattern would cover that as it has in the past. 

Just tried the manual upload from website and it appears to have worked.  

Not sure why they nuget push would fail (noted above would fail).  It is running 5.6.0 of nuget.  The odd part is the message "This package ID has been reserved."

**Comment by agr** [comment]
Which account was used to generate the API key that was used for publishing? I see Steeltoe.* packages have multiple owners, but only one of those accounts is the owner of Steeltoe.* namespace.
I think the issue is not with the package ID, but with the fact that those were new package IDs and the API key was created by the account that does not have ownership for the namespace (pushing existing packages skips the namespace check).

**Comment by jkonicki** [comment]
First I tried with the key that publishes as `SteeltoeOSS` org (the `steeltoe` user is in the org),  this is the key we used for our last release. Then I created and tried with a new key that published with the `steeltoe` user, not the org.  They both had the same issues. 

Both have the same `Glob Pattern: *`

**Comment by agr** [comment]
We can try adding `SteeltoeOSS` organization as an owner for `Steeltoe.*` prefix to see if it helps with publishing. Would you be OK with that?

**Comment by jkonicki** [comment]
Yeah, lets try that.

**Comment by agr** [comment]
Ownership was updated, please, let us know if you see any changes.

**Comment by jkonicki** [comment]
Hi @agr,
I do think we should add SteeltoeOSS org to the Steeltoe.* prefix, because I would like to publish from the org not individual user.  Also note I have also tried publishing with "steeltoe" user which already has permission for that prefix and that didn't work from nuget cli. So, I am not sure it will change anything.  

The more I think about it and from what I have tried so far, it appears that the creation of new packages from APIKey is not working.      
Question:  When a nuget api key is created and I set `Glob Pattern: *` it gives a check mark to all existing packages.  In theory (and previously this worked), it would create a new package when publishing.  But maybe that is not happening for some reason.   When the key is created, is the api key assign the list of packages or just a wildcard?    Maybe the nuget cli is for some reason not allowing new creation of packages, because it is not in that list?  

Also, ever since I uploaded one of the packages manually via the Web UI, it is no longer complaining (until it gets to the next new package).  So, I can get around this issue by doing this with each package, but there is a real issues if the nuget cli will not allow this.  

Thoughts on how to proceed?

**Comment by agr** [comment]
When you create an API key there is a choice of allowed operations:
![image](https://user-images.githubusercontent.com/102933/87979390-d5d29e80-ca86-11ea-8b49-654c1f67ea33.png)

The ability to create new package IDs is covered by that setting (i.e. if you pick "Push only new package versions" you won't be able to do that). But, you'd get a different 403 response if that was the case:
> 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)

Now that the org was added as a namespace owner, please try publishing the other new packages through your pipeline.

**Comment by jkonicki** [comment]
@agr Great news, the push worked with the org added to that prefix.  I am starting to think that the secret key being passed in on Azure DevOps does not update on a "redeploy" even if you change it for that release, difficult to tell when it hides the key value with ***. 

It looks like we should be good now.  Thank you for the help diagnosing and fix.
