### ISSUE TITLE
References deprecated Nuget.Core package

### ISSUE THREAD

**Issue by rpetz** [NuGet/NuGetGallery#8127]
### Describe the bug
The current latest release on Nuget.org references Nuget.Core v2 which is deprecated.

### To Reproduce
Install the latest Nuget.Server package

### Expected behavior
No errors should appear in the package manager stating you are referencing a deprecated package
![Annotation 2020-07-26 094228](https://user-images.githubusercontent.com/4307189/88484568-56c8e480-cf24-11ea-8cfe-432a57a39a34.png)

**Comment by joelverhagen** [comment]
Hello, thanks for taking the time to report this. We are already tracking this migration in issue https://github.com/NuGet/NuGetGallery/issues/3123. Note that this is a rather time intensive project and the priority is relative low compared to the team's backlog. That being said, I'd be happy to provide guidance to any member of the community that wants to work on this.

The alternative package would be NuGet.Packaging, but the APIs look pretty different so it would take some methodical work.
