### ISSUE TITLE
NuGet Package Manager Browse tab search results are unordered and too broad

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/NuGetGallery#8131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1100552/nuget-package-manager-browse-tab-search-results-ar.html)._

---
In ther latest versions of Visual Studio (e.g., 16.6.1), searching for a package on the Browse tab of the NuGet Package Manager seems to be doing a full-text search and returning the thousands of results in a random order.  

For example, when I search for the Newtonsoft.Json package, the results that come back seem to contain either Newtonsoft or Json somewhere in the name, description, or dependencies(?).  There seems to be no ordering for quality of match with the package name or anything that would make it reasonable to find the package to install it in my current project.  For my example search, the Newtonsoft.Json package I was searching for was result number 656 in the list returned.  This makes the tool virtually unusable and I have resorted to using nuget.org to find the packages/versions and manually editing the csproj files rather than wasting my time trying to find them in this tool.

---
#### Feedback Bot on 7/2/2020, 07:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/28/2020, 05:10 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 7/28/2020, 05:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by joelverhagen** [comment]
Hello, thanks for taking the time to report this issue. We have moved it to NuGetGallery because this is where we track issues related to nuget.org's search.

When I search for "Newtonsoft.Json" just on nuget.org, Newtonsoft.Json is the first result.
https://www.nuget.org/packages?q=Newtonsoft.Json

Could you share a screenshot of your Visual Studio window where Newtonsoft.Json is not at the top? It's possible there are multiple package feeds configured in your Visual Studio leading to this undesirable result. If you could share your list of feeds, that would be helpful too!

Thanks!
