### ISSUE TITLE
Windows Authentication does not work with NuGet.Server

### ISSUE THREAD

**Issue by Kingofjoy** [NuGet/NuGetGallery#8133]
I have attempted to host my packages through my private intranet NuGet.Server for my firends. Yet, it worked well.
But, when i added a layer of security Windows Authentication, it stopped working!

` <authentication mode="Windows"/>
    <authorization>
      <deny users="?"/>
    </authorization>`

While i searched first with visual studio it asked for credentials, but then it does not show any results. In console it found below.

[MyNuget] The V2 feed at 'http://localhost/MyNuget/nuget/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net471'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.

then i opened browser to check it said similar

Error message 401.2.: Unauthorized: Logon failed due to server configuration.

- Config file is untouched, i just just added these authentication lines
- .Net Framework 4.6 and 4.7.1 both didnt work
- I am running VS, Browser both inside domain
- IIS Express also failed

Please help to make this work...

[Web.config.txt](https://github.com/NuGet/NuGetGallery/files/5006235/Web.config.txt)

**Comment by zhhyu** [comment]
Thank you for reporting this issue to us! We will take the investigation and let you know the next step soon.

**Comment by loic-sharma** [comment]
It appears you may need to permit specific users to have access. For example:

```
<configuration>
  <system.web>
    <authorization>
      <allow users="domainname\user1,domainname\user2,domainname\user3" />
      <deny users="*" />
    </authorization>
  </system.web>
</configuration>
```

Please refer to this documentation for more information: https://support.microsoft.com/en-us/help/323176/how-to-implement-windows-authentication-and-authorization-in-asp-net
