### ISSUE TITLE
Marketplace data improvement for publishers

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/NuGetGallery#8135]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/566663/marketplace-data-improvement-for-publishers.html)._

---
<p>Hello </p> <p>Is it possible to get historical data displayed for publishers - from the time the extension was published. Currently it is limited to past 180 days window, which is very limiting. Can you expand that to as much as possible. </p><p></p><p>I am primarily interested in two improvements</p><p>  
</p><p>1. Extending the current report window (180 days). Idealy this window would be 1 year +... if not, since the very first day extension was introduced on the marketplace.</p> <p>  
</p><p>2. Ability to filter by geography - per country and continent... when this info is known. I am OK with having a pool of people who are also 'unknown' if geo info is not available. </p><p>Thanks</p>

---
#### Jane Wu [MSFT] on 5/14/2019, 01:52 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Mads Kristensen [MSFT] on 6/10/2019, 11:20 AM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### Stefan Stefanov on 7/2/2019, 10:50 AM: 

<p>I also believe this would be very beneficial, as the current date is not enough to make any conclusions.</p>

#### Gabriel Torok on 12/2/2019, 06:10 AM: 

<p>Likewise, this would be helpful for us as well.</p>

#### Katie DeSantis on 12/2/2019, 06:32 AM: 

<p>We too would benefit from this information</p>

#### Dan Wright on 12/2/2019, 08:44 AM: 

<p>This would be really beneficial for us too. </p><p>Thanks. </p>

#### andre rolle on 12/2/2019, 03:35 PM: 

<p>Yes we definitely need this information to help improve our capabilities in improving how we create and published our application in visual studios marketplace.</p>

#### andre rolle on 12/2/2019, 03:49 PM: 

<p>The management of Microsoft would change there mind in extending the 90 days to at least 1 year if possible. We as developers and others who interact with creating and publishing an application or software to visual studios marketplace. Really need this information to improve everything we do to make our app 100% functional an smooth going.</p>

**Comment by sasakrsmanovic** [comment]
Hello. I'm just checking in on this item. I didn't realize it was moved here from https://developercommunity.visualstudio.com/t/Marketplace-data-improvement-for-publish/566663?space=8&entry=suggestion

I ask as I have submitted an alternative as well - asking to open up marketplace API to consume our own data through Power BI.  I will post the ticket to this thread once I receive it , for some reason I don't see it on developer community portal yet.

**Comment by skofman1** [comment]
@sasakrsmanovic , I'm so sorry for the confusion, we thought this issue was about NuGet.org statistics, but it's about VS Marketplace. I transferred the issue to the correct repo and it's now tracked here: https://github.com/microsoft/vsmarketplace/issues/14

We have received similar requests (to enhance statistics) from other publishers as well. While we are looking into this, given our backlog we don't expect to be able to deliver in CY 2021.
