### ISSUE TITLE
Breadcrumb link to package details from Report Abuse page doesn't for packages with additional build metadata in version string

### ISSUE THREAD

**Issue by chgill-MSFT** [NuGet/NuGetGallery#8136]
### Describe the bug
**Applies to packages with additional metadata in their version string.**

After clicking on "Report" link on package details page, breadcrumb to get back to the package details page doesn't work if the package version string has additional build metadata. This is likely because the additional build metadata is appended to the URL when it shouldn't be.

Example of version string with additional build metadata:
![image](https://user-images.githubusercontent.com/15097183/89084748-dcde9400-d345-11ea-9f24-fb3e1dad28e2.png)

### To Reproduce
1. Go to https://www.nuget.org/packages/NuGet.Packaging/5.6.0/ReportAbuse
2. Click breadcrumb back to the package details page in the top left corner
![image](https://user-images.githubusercontent.com/15097183/89083260-4f9b3f80-d345-11ea-8a96-95bb030f8667.png)

3. Get Error 404
4. See that it works if you remove the additional build metadata from the URL

URL with metadata (wrong): https://www.nuget.org/packages/NuGet.Packaging/5.6.0%2b636570e68732c1f718ede9ca07802d7b1cc69aa0

Correct URL: https://www.nuget.org/packages/NuGet.Packaging/5.6.0

### Expected behavior
Breadcrumb link back to package details page should work.

### GIF of bug repro with NuGet.Packaging
![Link back from Report page doesn't work with package versions with build metadata](https://user-images.githubusercontent.com/15097183/89083178-fe8b4b80-d344-11ea-9390-c97dedb8883a.gif)

### Additional context
Additional examples for repro:
- https://www.nuget.org/packages/Lib.Build/5.0.0-preview.2.1%2b5cb4e1e
- https://www.nuget.org/packages/ConfigHandler/1.2.1%2b42c1ae0

**Comment by rocklan** [comment]
@chgill-MSFT I have submitted #8157 pull request to fix this issue.

**Comment by joelverhagen** [comment]
This change is deployed to nuget.org. Thanks again for your contribution!
