### ISSUE TITLE
nuget server packagesPath using a URL

### ISSUE THREAD

**Issue by nbelley** [NuGet/NuGetGallery#8142]
I would love to be able to give my local nuget server an url for its packages source, could it be possible? My packages would be hosted on a s3 bucket.

**Comment by skofman1** [comment]
@nbelley , thanks for reaching out! NuGet.Server only works with packages hosted on the local file system.

**Comment by loic-sharma** [comment]
I would consider using a [third-party NuGet server](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview) that supports AWS, like [BaGet](https://github.com/loic-sharma/BaGet) or [Sleet](https://github.com/emgarten/sleet).
