### ISSUE TITLE
Symbol server when hosted on prem?

### ISSUE THREAD

**Issue by rocklan** [NuGet/NuGetGallery#8154]
Is there some documentation for enabling the symbols server functionality when hosted on prem? Or is this not possible?

**Comment by joelverhagen** [comment]
nuget.org's symbol server implementation has a closed source component that actually pushes the PDBs in the .snupkg to a symbol server that Visual Studio debugger and to.  Therefore cannot easily be adopted externally/on-prem. Consider alternatives such as [BaGet](https://loic-sharma.github.io/BaGet/) (cc @loic-sharma) for on-prem or perhaps [Sleet](https://github.com/emgarten/Sleet) for serverless (cloud-based).

**Comment by yishaigalatzer** [comment]
Why is that part closed source? Is it just about creds to pushing it up?

**Comment by joelverhagen** [comment]
@cristinamanum, could you provide context on the possibilities of running nuget.org's symbol server on-prem?

**Comment by yishaigalatzer** [comment]
I think the ask here is to enable a) symbol server capabilities from nuget.org be replicated on-prem (where for example network access is not available. b) Additional symbols published with internal packages.

**Comment by rocklan** [comment]
> I think the ask here is to enable a) symbol server capabilities from nuget.org be replicated on-prem (where for example network access is not available. b) Additional symbols published with internal packages.

No, it's for running nuget gallery code on local, on-prem server.

**Comment by loic-sharma** [comment]
> No, it's for running nuget gallery code on local, on-prem server.
> a) symbol server capabilities from nuget.org be replicated on-prem (where for example network access is not available.

The nuget.org symbol server is actually a mixture of [Azure Artifacts' symbol server](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops) and Microsoft's MSDL symbol server. Neither of these symbol servers are open-source.

> Why is that part closed source? Is it just about creds to pushing it up?

We use Azure Artifacts to ingest symbols. The only public way to upload symbols to Azure Artifacts is using the [`Index Sources & Publish Symbols`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops) task in your Azure Pipeline. This build task doesn't fit our needs, so instead, we use a closed-source Azure Artifacts SDK to ingest symbols.

> b) Additional symbols published with internal packages.

I'm not sure I understand this ask. Could you explain a little bit more?
