### ISSUE TITLE
Upload error: This package ID has been reserved...

### ISSUE THREAD

**Issue by sunny868** [NuGet/NuGetGallery#8162]
### Describe the bug
Upload package fail :
 runtime.linux-mips64.Microsoft.NETCore.DotNetAppHost.3.1.7.nupkg

error info is :
 This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.

### Expected behavior
upload sucess

**Comment by joelverhagen** [comment]
The package ID prefix `runtime.*` has been reserved by another package owner (the Microsoft organization). In this particular case you'll need to pick a different package ID that does not start with a reserved prefix.

For more information about ID prefix reservation, see https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation.

**Comment by sunny868** [comment]
Thank you very much.  Now I want to build nuget server on Linux platform. Do you have any documents for me?

**Comment by joelverhagen** [comment]
The NuGet.Server and NuGetGallery projects are both only supported on Windows.

**Comment by joelverhagen** [comment]
Please let me know if you have any further questions about ID prefix reservation. If not, we'll leave this one closed. If you have questions about another subject, please open another issue specific to that subject and we can continue the conversation there.

**Comment by loic-sharma** [comment]
You can find a list of NuGet server implementations here: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

A few of these options support Linux.
