### ISSUE TITLE
Test packages are visible on search results when filtering by last uploaded

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#8172]
### Describe the bug
See twitter thread: https://twitter.com/buhakmeh/status/1299115494973341696

### To Reproduce
1. Run Functional tests / E2E tests
2. Sort search results by "Recently updated"

### Expected behavior
User packages only are shown

### Screenshots
![image](https://user-images.githubusercontent.com/16807822/91502274-839e4d80-e87c-11ea-9953-8a7d873d0a2f.png)

### Additional context
We need to unlist/delete those packages after test completion

**Comment by joelverhagen** [comment]
Previously tracked by https://github.com/NuGet/Engineering/issues/497.
