### ISSUE TITLE
[A11y][Reflow]Some of the information is missed when reflow is applied

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#8191]
Copied from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1188115
## Browser Details:
Firefox Version: 79.0 (64 bit)

## OS Details

Microsoft Windows 10 Enterprise  ​

Version 2004 (OS Build 19041.450) 

## Note: 
Under 'Members' Administrator dropdown is not visible clearly after applying reflow
## Repro Steps:

    Change the Display resolution to 1280*1024 in System display settings
    Hit the URL and login with appropriate credentials
    Tab till "Open Profile drop down" and press enter
    Tab till "Manage organizations" and Press enter
    Tab till "Edit " present in any record the table and press enter
    Tab till Certificates and expand it 
    Apply reflow and Check whether data is missing or not  

## Actual Results:

Some of the data is missing when reflow is applied under the Certificates
## Expected Results:
User should be able to view the data without missing and all the information should be visible clearly with one scrollbar after applying reflow
## User Impact:
Users will not be able to see the information if it gets overlapped in reflow

## Notes
This is referencing the information on the Manage Organization page after setting minimum required CSS width (320 pixel). 
![image](https://user-images.githubusercontent.com/11051729/92166001-bdc39e00-edec-11ea-8679-fef816b3a1a3.png)
The information on this page entirely is difficult to see at the minimum width.

**Comment by joelverhagen** [comment]
Linked issue is closed.
