### ISSUE TITLE
Fix flaky db2catalog unit test

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8217]
The test [`RunInternal_WithMultipleDeletedPackagesWithSamePackageIdentity_PutsEachPackageInSeparateCommit`](https://github.com/NuGet/NuGet.Jobs/blob/dd26676619c5901c9924fc9b3286ba263c41a446/tests/NgTests/Db2CatalogTests.cs#L533) is flaky.

Example builds that have failed:

* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4090330
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4090974

Example builds that have passed (notice there are no changes between failed and passed builds):

* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4090487

**Comment by joelverhagen** [comment]
Fixed as part of https://github.com/NuGet/NuGet.Jobs/pull/1145
