### ISSUE TITLE
Update licenses.nuget.org

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8230]
The list of available licenses on licenses.nuget.org should match the licenses accepted by NuGet client. We should update licenses.nuget.org as the licenses accepted by NuGet client changed between v5.0.0 and v5.8.0 (see [this](https://github.com/NuGet/NuGetGallery/pull/8229/files#diff-7c18c2a160029a7f91c7a8e1044492b6R614)).

/cc @agr

**Comment by agr** [comment]
Need also to make sure that the recent client change is in: https://github.com/NuGet/NuGet.Client/pull/3720
