### ISSUE TITLE
.NET 5.0 not .NETFramework 5.0

### ISSUE THREAD

**Issue by f2calv** [NuGet/NuGetGallery#8235]
### Describe the bug
When viewing dependencies on the web site for a package that targets .NET 5.0 the UI reads '.NETFramework 5.0' which I believe is incorrect.

### To Reproduce
Publish a package that targets .NET 5.0

### Expected behavior
Should display ".NET 5.0" instead of ".NETFramework 5.0"

### Screenshots
![image](https://user-images.githubusercontent.com/16097639/95006735-9f2d0e80-0607-11eb-8b15-d3be2f25a535.png)

**Comment by joelverhagen** [comment]
Great catch, @f2calv! Essentially the problem here is that NuGet.org is using an older version of the framework definitions prior to the introduction of .NET 5.0.

We'll need to update the newest version of these definitions and reprocess packages that have .NET 5.0 dependencies.

/cc @zkat @nkolev92, is there a version of NuGet.Frameworks that we should be using for stable .NET 5.0 framework parsing?

Note to the server team: I think feed2catalog and perhaps even catalog2registration need to upgrade as well because they interact with dependency group metadata as well.

/cc @loic-sharma, who recently updated the package versions used on the server side. We may already have the version we need and just need to deploy it then reflow the packages.

My guess is other package feeds will run into similar problems. It may be worth an announcement about the introduction of the TFM and how it interacts with NuGet client and server implementations.

**Comment by nkolev92** [comment]
@joelverhagen 
5.8 early previews have *all* the changes necessary.

Anything above 5.8.0 P2 should work, but prefer the latest.

**Comment by zivkan** [comment]
Note to server team/whoever makes the fix:

`NuGetFramwork.DotNetFrameworkName` is designed explicitly to be compatible with `System.Runtime.Versioning.FrameworkName`. As per the [.NET 5 TFM spec](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md), this is not the recommended string for display.  Please use `NuGetFramework.ToString()` to get the recommended display name.

**Comment by joelverhagen** [comment]
Here are several variants and how they behave on nuget.org today.

### `net5.0`

Example package with `net5.0` in the dependency group:
https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/5.0.0-rc.1.20451.17
```xml
      <group targetFramework="net5.0">
        <dependency id="Microsoft.AspNetCore.Metadata" version="5.0.0-rc.1.20451.17" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Logging.Abstractions" version="5.0.0-rc.1.20451.14" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Options" version="5.0.0-rc.1.20451.14" exclude="Build,Analyzers" />
      </group>
```
Currently shows as:
![image](https://user-images.githubusercontent.com/94054/95136616-4fd80280-071b-11eb-8417-f3b17459afd8.png)

### `.NETCoreApp5.0`

Example package with `.NETCoreApp5.0` in the dependency group:
https://www.nuget.org/packages/Microsoft.Extensions.Options/5.0.0-rc.1.20451.14
```xml
      <group targetFramework=".NETCoreApp5.0">
        <dependency id="Microsoft.Extensions.DependencyInjection" version="5.0.0-rc.1.20451.14" />
        <dependency id="Microsoft.Extensions.DependencyInjection.Abstractions" version="5.0.0-rc.1.20451.14" />
        <dependency id="Microsoft.Extensions.Logging.Abstractions" version="5.0.0-rc.1.20451.14" />
        <dependency id="Microsoft.Extensions.Options" version="5.0.0-rc.1.20451.14" />
      </group>
```
Currently shows as:
![image](https://user-images.githubusercontent.com/94054/95136639-5bc3c480-071b-11eb-86b0-2cfb0d41195a.png)

### `net5.0-windows7.0`

Example package with `net5.0-windows7.0` in the dependency group:
https://www.nuget.org/packages/ReaLTaiizor/3.7.8
```
      <group targetFramework="net5.0-windows7.0">
        <dependency id="System.Configuration.ConfigurationManager" version="5.0.0-rc.1.20451.14" exclude="Build,Analyzers" />
        <dependency id="System.Drawing.Common" version="5.0.0-rc.1.20451.14" exclude="Build,Analyzers" />
        <dependency id="System.Resources.Extensions" version="5.0.0-rc.1.20451.14" exclude="Build,Analyzers" />
      </group>
```
Currently shows as:
![image](https://user-images.githubusercontent.com/94054/95136858-beb55b80-071b-11eb-990f-bd78877a2e5c.png)


I will loop with PMs to find the desired behavior (especially in light of platform)

**Comment by zivkan** [comment]
Note, those same packages as displayed by the VS PM UI:

https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/5.0.0-rc.1.20451.17
![image](https://user-images.githubusercontent.com/5030577/95147809-a56dd880-0736-11eb-9c17-dc1f6d0d2b63.png)

https://www.nuget.org/packages/Microsoft.Extensions.Options/5.0.0-rc.1.20451.14
![image](https://user-images.githubusercontent.com/5030577/95147838-bae30280-0736-11eb-83de-9f227ba0fe0f.png)

https://www.nuget.org/packages/ReaLTaiizor/3.7.8
![image](https://user-images.githubusercontent.com/5030577/95147872-d77f3a80-0736-11eb-8e08-c948ea5da795.png)


See also: [TFMs in the UI](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#tfms-in-the-ui) from the .NET 5 TFM spec. It's aimed at VS, but if gallery wants a similar experience to VS, it might be relevant.

**Comment by clairernovotny** [comment]
Related: https://github.com/NuGet/NuGetGallery/issues/8268

**Comment by joelverhagen** [comment]
After the latest deployment of NuGetGallery where we updated our version of NuGet.Frameworks, all .NET 5.0 frameworks are showing as ".NETCoreApp 5.0". The platform information is completely invisible, per https://github.com/NuGet/NuGetGallery/issues/8268. We are waiting on word from PM on what the desired UI should be.

**Comment by joelverhagen** [comment]
The fix is now in PROD. Thanks for reporting this, @f2calv, and for the details everyone!
