### ISSUE TITLE
Dependencies not showing platform component of .NET 5 TFM

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/NuGetGallery#8268]
The gallery is only showing `NetCoreApp 5.0` under the dependencies node and not `net5.0-windows10.19041`. 

I have a package that multi-targets both `net5.0` and `net5.0-windows10.19041`. I'd expect both to show up on the website; they are distinct dependency groups in the NuSpec:

![image](https://user-images.githubusercontent.com/1427284/96260782-7acd1c80-0f8d-11eb-8394-678d2728b471.png)

**Comment by joelverhagen** [comment]
The fix is now in PROD. Thanks for bringing this to our attention, @clairernovotny!

https://www.nuget.org/packages/System.Reactive/5.0.0-preview.220
![image](https://user-images.githubusercontent.com/94054/97733625-585ef700-1a95-11eb-98a0-e7c8219dafc2.png)
