### ISSUE TITLE
Nuget.org complains about license MIT-0 as unsupported

### ISSUE THREAD

**Issue by Doraku** [NuGet/NuGetGallery#8280]
### Describe the bug
Some months ago I switched my open source projects to the MIT No Attribution as I didn't like the part of MIT forcing the user to provide a copy of said license where it is used. Nuget.org didn't complained then and even showed the license correctly for my packages (see [here](https://www.nuget.org/packages/DefaultDocumentation/)).
Now wanting to release a new version Nuget.org complains that
> License expression must only contain licenses that are approved by Open Source Initiative or Free Software Foundation. Unsupported licenses: MIT-0.

which as far as I can [see](https://opensource.org/licenses/MIT-0) is not true?

### To Reproduce
Create a package from a csharp project with the `<PackageLicenseExpression>MIT-0</PackageLicenseExpression>` and try to upload it on Nuget.org

### Expected behavior
The package can be uploaded.

### Screenshots
![image](https://user-images.githubusercontent.com/27510075/96367671-86684100-114f-11eb-9a1b-f866a57a82c0.png)

**Comment by joelverhagen** [comment]
Hello, @Doraku. The reason this license is not allow is because it is not OSI approved or FSF free/libre. This can be seen here:
https://spdx.org/licenses/
![image](https://user-images.githubusercontent.com/94054/96487885-14950380-11f2-11eb-9f4d-105887365785.png)

Perhaps @agr, @chgill-MSFT, or @jcjiang could explain exactly why we limit the SPDX monikers on nuget.org to these two classifications (OSI approved or FSF free/libre).

**Comment by Doraku** [comment]
Then I guess this website is not up to date? The `MIT-0` can be seen [here](https://opensource.org/licenses/alphabetical) approved by the OSI.
Also did that requirement changed recently? As I was able to push successfully packages with this license a month ago.

**Comment by agr** [comment]
It was [recently](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-August/004917.html) approved and we didn't sync with SPDX database for a while. I'll check what need to be done to sync.

**Comment by agr** [comment]
As for why we don't support non-OSI/FSF approved licenses: as far as I remember the reasoning was that those seem to get much less attention in SPDX database and can contain explicit company/personal names in their texts, which obviously have nothing to do with the package owners on nuget.org.

**Comment by Doraku** [comment]
> As for why we don't support non-OSI/FSF approved licenses: as far as I remember the reasoning was that those seem to get much less attention in SPDX database and can contain explicit company/personal names in their texts, which obviously have nothing to do with the package owners on nuget.org.

Oh I definitely understand why you would put such a limit on usable licenses, the succession of events just led me to believe that the check was already there on nuget.org when I pushed my packages before and then stopped working for some reason since I could see the `MIT-0` was approved. Didn't see that it was this recent! Good to know that this will be sorted then :)

**Comment by donnie-msft** [comment]
https://github.com/NuGet/NuGet.Client/pull/3720 portion is merging to main (5.9.x)

**Comment by Doraku** [comment]
Hey, just found out that I could finally upload MIT-0 licensed package to nuget.org :) wondering if I could close this issue or if you want to keep it open still because of some work remaining?

**Comment by agr** [comment]
We had it updated recently, I was about to close it. Thanks for checking!
