### ISSUE TITLE
powershellgallery not responding and fails when attempting install-module

### ISSUE THREAD

**Issue by paul-rich** [NuGet/NuGetGallery#8304]
Received 500 error when attempting to open PowerShellGallery.com (specifically https://www.powershellgallery.com/package/AzureAD) to obtain package. This has been reproducing for about 12 hours at this point. The entire site is almost entirely unresponsive.  Checking the status page at https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md#powershell-gallery-status shows "The PowerShell Gallery is currently: Experiencing an outage" but the most current/recent entry with details about an outage is from October 15th.

**Comment by paul-rich** [comment]
Selecting Packages from Home page the site responds "There are 0 packages"

**Comment by paul-rich** [comment]
attempting in PowerShell:
PS C:\WINDOWS\system32> Install-Module AzureAD
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.

**Comment by hoffe86** [comment]
same issue on my side

**Comment by skofman1** [comment]
@paul-rich , @hoffe86 , PowerShell Gallery issues are tracked here: https://github.com/PowerShell/PowerShellGallery/issues
