### ISSUE TITLE
[A11y] [WCAG2.1] Two scroll bars shown on status page, when zooming in.

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#8313]
See this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1221931/

**Comment by agr** [comment]
Work with @chgill-MSFT and UI folks to determine expexted behavior for narrow screen layouts.

**Comment by lyndaidaii** [comment]
We will continue to reach out to UX experts to find out if there is a better fix
