### ISSUE TITLE
Dotnet Tools don't show Framework Dependencies

### ISSUE THREAD

**Issue by RickStrahl** [NuGet/NuGetGallery#8323]
### Dotnet Tools don't show Framework Dependencies
Dotnet tools published to the NuGet site do not show a framework dependency in the online listing. 

This is a problem if a package fails to install due a missing framework and the user needs to find a version that works - there's no way to find a version that might have a lower framework dependency.

Example:

![image](https://user-images.githubusercontent.com/1374013/98994268-9f0c1280-24d3-11eb-9336-067bdae9a5eb.png)

If I get an error message upon install like this:

![image](https://user-images.githubusercontent.com/1374013/98994299-acc19800-24d3-11eb-87b8-f8d69c7ccab4.png)

I can't even look for an older version (in this case the previous version) that runs on an older framework (3.1 in 0.2.16) because that info isn't displayed.

### Solution
Show the .NET Core Target Framework dependency. It's odd that this isn't shown since non-tool packages shows the framework target information.

**Comment by joelverhagen** [comment]
In general showing package compatibility is a weak spot for NuGet.org and NuGet tooling in general. The dependencies section for non-tool packages has served as an _approximation_ for compatibility for quite some time.

In general the dependency groups of a package and the frameworks it supports overlap so it's not a bad approximation. There are gaps however such as packages that don't have dependencies or packages that are packed using non-traditional means (causing dependency groups to not align with compatibility for whatever reason).

For the case with .NET tools, dependencies are not reported in the package .nuspec therefore this metadata does not appear on the nuget.org page. In fact, the dependencies are bundled into the package in a format that is not currently understood by nuget.org.

That being said, I totally agree that this is a bad experience and we should consider it for our future efforts in making package compatibility more visible to our users (/cc @JonDouglas).

**Comment by RickStrahl** [comment]
I'm confused... Isn't all that information available in the NuGet package:

![image](https://user-images.githubusercontent.com/1374013/99315363-a2bad480-2806-11eb-864f-de1880acc4e9.png)

Why should this be any different than a non-tool package? I'm not even asking for a full dependency graph, but the top level runtime dependency in this case is useful. Non-tool packages display that just fine:

![image](https://user-images.githubusercontent.com/1374013/99315540-e0b7f880-2806-11eb-87a2-155a692d8d05.png)

For the runtime at least there would not appear to be any ambiguities unless I'm missing something here...

**Comment by joelverhagen** [comment]
The **Dependencies** section on nuget.org is populated by the `<dependencies>` section in the .nuspec. For .NET tool packages, this section is does not exist. The reason for this is specific to how .NET tool packages are packages and deployed, but suffice it to say that the shape of the package and contained metadata is significantly different than normal dependency packages.

Compare in .nuspec or NuGet Package Explore view for these two packages:

### LiveReloadServer

![image](https://user-images.githubusercontent.com/94054/99316250-e1f22100-2818-11eb-83ca-44d1094680cf.png)

(no `<dependencies>` section in the .nuspec)

### Westwind.AspnetCore.LiveReload

![image](https://user-images.githubusercontent.com/94054/99316275-eddde300-2818-11eb-9dd9-d8e052a18c57.png)

There are dependencies in the .nuspec:

```xml
    <dependencies>
      <group targetFramework=".NETCoreApp3.1" />
      <group targetFramework="net5.0" />
    </dependencies>
```

Now, it's definitely not true that we _can't_ surface the information. You've screenshotted it and it exists 👍. It's just that we aren't doing it today. I'm trying to describe the current state. Sorry if I was confusing.

There is work in progress to improve how package compatibility information is surfaced. Jon Douglas, mentioned before, is working on the design of that effort.

This issue brings up a very good point though. We need to consider compatibility for both traditional dependency packages as well as .NET tool packages.

**Comment by joelverhagen** [comment]
This is resolved now with the `Frameworks` tab.
![image](https://github.com/NuGet/NuGetGallery/assets/94054/b108fe8a-54f6-46c2-a570-6e58fcd1fb4b)

The dependencies still do not show but this is tracked by a different item.
https://github.com/NuGet/NuGetGallery/issues/10020
