### ISSUE TITLE
Remove Usabilia Button on nuget.org

### ISSUE THREAD

**Issue by jcjiang** [NuGet/NuGetGallery#8326]
### Is your feature request related to a problem? Please describe.
Usabilia is no longer part of NuGet.org telemetry.

### Describe the solution you'd like
The Usabilia button should be removed from the page

**Comment by anangaur** [comment]
Whats the alternative, if any?

**Comment by jcjiang** [comment]
@anangaur To clarify, an alternative to Usabilia generally?

**Comment by zhhyu** [comment]
Should I proceed to remove Usabilia from Gallery?

**Comment by zhhyu** [comment]
Usabilia has been removed from nuget.org
