### ISSUE TITLE
Set security headers on responses

### ISSUE THREAD

**Issue by analogrelay** [NuGet/NuGetGallery#833]
"X-Frame-Options: deny" should be set on our responses, to disallow framing, which could be used in clickjacking. Modern browsers will honor this.

Test Notes: Try creating an HTML page like this: (https://gist.github.com/anurse/5208395). Modern browsers should show a blank frame. (verified with Chrome)

"X-XSS-Protection: 1; mode=block" should be set to enable the XSS filters in modern browsers and tell them to block our site if they detect an XSS (http://blogs.msdn.com/b/ieinternals/archive/2011/01/31/controlling-the-internet-explorer-xss-filter-with-the-x-xss-protection-http-header.aspx).

"Strict-Transport-Security: maxage=31536000; includeSubDomains" should be set to indicate to modern browsers that our site should be used with SSL only. This shouldn't affect users who have to use HTTP, but if you use HTTPS once, this will force the browser to continue using HTTPS each time (even if you get an HTTP link).

"X-Content-Type-Options: nosniff" should be set to disable browser sniffing of Content-Types.

**Comment by hickford** [comment]
Consider Strict-Transport-Security (HSTS) for https://api.nuget.org/ too
