### ISSUE TITLE
The number of Downloads for my lib stays at zero whereas we have downloaded it tens of times

### ISSUE THREAD

**Issue by tpierrain** [NuGet/NuGetGallery#8334]
### Bug Description
The number of __Downloads for my lib stays at zero__ whereas we have downloaded it tens of times at work or from home. This is not a good incentive to « sell » the lib ;-)

### To Reproduce
1. Open https://www.nuget.org/packages/Diverse/ and see 0 as downloads for the component
2. Download the components (either via nuget package manager in visual studio or through the download package link on nuget.org
3. Wait a while, refresh the page https://www.nuget.org/packages/Diverse/ : the downloads count remains zero...

### Expected behavior
I’m expecting the nuget.org gallery to display the relevant number of downloads for my package. At least not zero (which is not a good selling argument ;-)

### Screenshots

![6D14A75F-E5A4-44D3-8C5D-1C1FFA25BF1C](https://user-images.githubusercontent.com/2824069/100060150-761d4300-2e2c-11eb-9dcc-a5b444c717a3.png)

**Comment by zhhyu** [comment]
Hello, @tpierrain. Thank you for reporting this issue!
The statistics of package downloads are not updated in a real-time manner. So please wait for a while and the number will be refreshed.
We are improving the statistics pipeline, which will provide a higher refreshing frequency.

**Comment by tpierrain** [comment]
Thank you very much for your answer. I just saw that the counter started for the lib so, cool. 
Have a nice day
