### ISSUE TITLE
Cannot convert account to organization

### ISSUE THREAD

**Issue by losolio** [NuGet/NuGetGallery#8344]
### Describe the bug
Error when converting account to organization

### To Reproduce
1. Log with my account `losol`, go to this URL 'https://www.nuget.org/account/transform.', add losolio as new admin
1. Log in as losolio, go to `https://www.nuget.org/account/Organizations`
2. Perform this operation: accept joining organization by clicking the V
3. See error: Oops! Error 500 - Internal Server Error. An error occurred while processing your request. We really messed up this time...

### Expected behavior
Joining losol organization

**Comment by joelverhagen** [comment]
Hey @losolio and @waltiam (from https://github.com/NuGet/NuGetGallery/issues/8349), this is a legitimate bug on nuget.org right now. Thanks for bringing this to our attention. We are working quickly to get a fix out to unblock your experience.

**Comment by waltiam** [comment]
As a work around ... individual packages can be reassigned successfully.

**Comment by joelverhagen** [comment]
@losolio and @waltiam, a fix has been shipped to nuget.org with a fix. You should be able to convert your account into an organization now.

Please go ahead and give it a try again and let me know if you're still blocked.

**Comment by losolio** [comment]
Thanks, @joelverhagen. Confirming that this bug is fixed, and that the organization conversion succeeded. cc @waltiam
