### ISSUE TITLE
Having an issue uploading to Nuget.org

### ISSUE THREAD

**Issue by osaghaso** [NuGet/NuGetGallery#8347]
Hi,
I'm trying to upload package using "Upload" button at https://www.nuget.org/packages/upload, but i'm receiving " This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID".
Can you help me with this?.

**Comment by skofman1** [comment]
@osaghaso , I saw that you also sent us a mail. Closing this issue.
