### ISSUE TITLE
server error while transform a user into an organization

### ISSUE THREAD

**Issue by waltiam** [NuGet/NuGetGallery#8349]
### Describe the bug
I have a user account which has four packages.  I want to convert this user to an organization (let's call it 'A') and assign it to another user account that I control (let's call it 'B').  

### To Reproduce
There is a button for this ...

I add the I add the user 'B' to the test box and and click ok and then dismiss the alert with another affirmative.

I log in as the admin of the new organization owner and check the organizations view.  The transferred account appears there with an accept (check) and decline (exe).  If I decline everything returns to the previous state (not the desired end state).

If I accept control of the new organization - ka-boom  500 server error

### Expected behavior
The new administrator should have another organization.

### Screenshots

![There a button for this](https://user-images.githubusercontent.com/2963975/101568808-5136dd00-39a1-11eb-9131-18822fb09615.png)

![the view from the new admin](https://user-images.githubusercontent.com/2963975/101568976-9b1fc300-39a1-11eb-9526-40b86acb9012.png)

**Comment by skofman1** [comment]
@waltiam , thanks for reaching out!

Please e-mail support@nuget.org and provide all the details so we can investigate further and unblock you.

**Comment by skofman1** [comment]
Seems like we have a bug: https://github.com/NuGet/NuGetGallery/issues/8344 
Investigating.
