### ISSUE TITLE
"Unable to load the service index for source https://api.nuget.org/v3/index.json" in unbuntu

### ISSUE THREAD

**Issue by hieunm22** [NuGet/NuGetGallery#8351]
I'm using **ubuntu 18.04 LTS** and going to build my application using dotnet build
but it pops an error that tells _Unable to load the service index for source https://api.nuget.org/v3/index.json._
I tried to search the same issue and I found this [thread](https://github.com/NuGet/NuGetGallery/issues/7705). but all comments in this thread show how to fix in windows, not in ubuntu.
could some one tell me the solution in my case? 
thanks

**Comment by agr** [comment]
Apologies for the delayed response.

Could you please share a full build log with detailed verbosity (`dotnet build --verbosity detailed`)? Feel free to send it to support@nuget.org if you don't want to put it here.

**Comment by hieunm22** [comment]
Thanks for your response althought late
Here's the full log with the command you provided above
https://controlc.com/1e820605

The URL `www.nuget.org` can be accessed normally in browser, and so can the `curl https://api.nuget.org/v3/index.json`

An additional information in my case:
I created a new project with type = "mvc", type = "console" and the command `dotnet build` runs successfully
but some types such as "react", "classlib" doesn't

**Comment by agr** [comment]
Which SDK version are you using? Tried updating to the latest one?
I tried setting up an Ubuntu 18.04 VM to try to reproduce the issue and with the latest SDK it worked fine.

I am looking at the log, and I see that it fails but with a different error:

> /usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure.

You mentioned that it complained about "Unable to load the service index for source https://api.nuget.org/v3/index.json." before. Do you get consistent error messages?

Please, send us the output of `echo | openssl s_client -servername api.nuget.org -connect api.nuget.org:443 2>/dev/null`
The issue might be related to the version of OpenSSL on your system, please try updating to the latest one.

**Comment by hieunm22** [comment]
all dotnet components are up to date to version 3.1 LTS
what's your latest version? latest version is currently 5.0
 
this is the outout for the command above

`https://controlc.com/299441b0`

about the openssl, i updated it to latest version. is it the latest one: 1.1.1g  21 Apr 2020

**Comment by agr** [comment]
Yes, I was using 5.0

**Comment by agr** [comment]
Issue moved to [NuGet/Home #10414](https://github.com/NuGet/Home/issues/10414) via [**ZenHub**](https://www.zenhub.com/)
