### ISSUE TITLE
Nuget.Server Routes are not working with IIS Express in 2021

### ISSUE THREAD

**Issue by omatrot** [NuGet/NuGetGallery#8366]
### Describe the bug

Routes are not working

  - https://localhost:44380/nuget/Packages
  - https://localhost:44380/nuget/clear-cache

=> HTTP Error 404.0 - Not Found
The site seems to be looking for static files instead of being redirected to the corresponding conrollers.

### To Reproduce

  - Follow the procedure [here](https://docs.microsoft.com/fr-fr/nuget/hosting-packages/nuget-server).
  - Run the site and try to browse your packages or clear the cache.

### Expected behavior
I should be able to see my packages.

**Comment by skofman1** [comment]
@omatrot , thanks for reporting and sorry for the slow response. NuGet.Server is in maintenance mode, and as such we fix only critical bugs. If you managed to fix the problem, please consider sending us a PR.
