### ISSUE TITLE
Getting messages as package id is reserved contact the owner when uploading new packages

### ISSUE THREAD

**Issue by hosathota** [NuGet/NuGetGallery#8378]
Hi,
 I am trying to upload a new package which starts with IBM.Data.Db2.NET5 but keep getting messages something like 
" This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID."
We are the owners of these namespace (IBM.Data.DB2  series) and its not sure who could reserve these names and how to get them back. 
The other variants of the above name also did not succeed.

Thanks and regards
Vishwa

**Comment by skofman1** [comment]
@hosathota , sorry for the slow response. Please reach out to support at nuget.org and we will investigate.
