### ISSUE TITLE
Download package in china the url change.

### ISSUE THREAD

**Issue by here101** [NuGet/NuGetGallery#8383]
Download package very slow in china #6872
Please tell me which URL is url = "https://www.nuget.org/api/v2/package/$PackageName/$Version" if you change it to China, I tried to chang it to url = "https://www.api.nuget.org/v3/ package/$PackageName/$Version", but it failed.Thanks for your answers.

**Comment by here101** [comment]
Oh @joelverhagen, Thank you for your answer. I am trying to configure the dependencies of a project from a script file, the bat file to download the packages from Nuget, and one line in that script file is
 $url = "https://www.nuget.org/api/v2/package/$PackageName/$Version"

I have tried changing it to
 $url = "https://www.api.nuget.org/v3/index.json/package/$PackageName/$Version", but running this script gives me an error: The remote name could not be resolved: ' www.api.nuget.org

Looking forward to your reply, I've been stuck here for almost a week now.

**Comment by joelverhagen** [comment]
I would recommend using a command like `nuget.exe install {ID} -Source https://api.nuget.org/v3/index.json` for such a purpose. This will download the packages without having to understand .nupkg URLs.

Would that work for you?

**Comment by here101** [comment]
Well,thanks.Maybe I can try it.
