### ISSUE TITLE
Cannot connect account with work Microsoft account

### ISSUE THREAD

**Issue by prstrnn** [NuGet/NuGetGallery#8394]
Hi Nuget team!

Can you please assist me with my problem? I'm trying to create an account in Nuget.org and link it with work Microsoft account
Somehow I have created login+password account and now I'm getting this window:
![image](https://user-images.githubusercontent.com/30490978/105715159-4e328480-5f2e-11eb-98bb-aa1a7a80e3d1.png)

I\m understand that is correct behaviour of the site, because login+pass Auth has beem discontinued. When I am trying to log in with Mircosoft after choosing my accnount I'm getting this: 
![image](https://user-images.githubusercontent.com/30490978/105715347-8a65e500-5f2e-11eb-914f-811f0ceb242f.png)

I am expected to be logged in Nuget.org site, but got Need admin approval error. First, I tried to find person in company that related to creating Nuget accounts but no one knows about it inside company. 

I hope that you can help with this problem, 
Thanks
Andrey

**Comment by skofman1** [comment]
@prstrnn , sorry for the slow response. When it comes to account issues, please send an e-mail to support at nuget.org 
and we will help you resolve the issues.
