### ISSUE TITLE
get download statistic for my organization packages with API

### ISSUE THREAD

**Issue by nikkidreamt** [NuGet/NuGetGallery#8396]
Hi!
Marketing team in my organization is wondering if there is a way to get download statistic automatically?
We push packages to nuget.org using your API, do you have any method to get package info, including download statistic?
For package we need:
1. Total downloads
2. Unique IP Address Downloads

**Comment by loic-sharma** [comment]
You can use the search API to get a package's downloads. The nuget.org search service lets you filter to just a single package by writing a query like [`packageid:Newtonsoft.Json`](https://www.nuget.org/packages?q=packageid%3Anewtonsoft.json).

Here are some resources that may be helpful:

* Search API documentation: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result
* Example search API request to get just Newtonsoft.Json's metadata: https://azuresearch-usnc.nuget.org/query?q=packageid:newtonsoft.json&prerelease=true&semVerLevel=2.0.0&take=1
* C# SDK to search for NuGet packages: https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#search-packages

Sadly, we don't have a way to determine how many unique IP addresses have downloaded a package. Please let us know if you have any additional questions!
