### ISSUE TITLE
Reserved namespace error should mention a link to docs (aka.ms?)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8397]
### Describe the bug

When a user pushes a new package to NuGet.org and the ID is under  a reserved namespace, we show this error:
![image](https://user-images.githubusercontent.com/94054/105903905-572a6100-5fd5-11eb-8102-761e5ee19100.png)

This should mention a link to docs:
https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

Requested by @anangaur

**Comment by jcjiang** [comment]
For the text that shows in the banner -

This package ID has been reserved, per https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation. Please request access to upload from the prefix owner, or re-upload the package under a different prefix.

@skofman1 Let me know if there is anything else I can help with! :)
