### ISSUE TITLE
Build issue in TFS 2017 - NuGetGallery-2019.01.14 release code.

### ISSUE THREAD

**Issue by mcpdeveloper443** [NuGet/NuGetGallery#8400]
I am trying to download NuGetGallery-2019.01.14 release version and opened in visual studio 2017 .

Trying to build NugetGallery.sln.....a lot errors.....

![image](https://user-images.githubusercontent.com/72257289/105972004-2b7ca900-60b1-11eb-9ce8-987b2c3c63ad.png)

**Comment by skofman1** [comment]
@mcpdeveloper443 , Visual Studio 2019 is on of the pre-requisites for building the Gallery:
![image](https://user-images.githubusercontent.com/16807822/106508608-761b6e00-6481-11eb-846a-5d1ce834d08c.png)

If you don't have access to VS 2019, consider cloning an order version of the code (from around Sep 2020).
