### ISSUE TITLE
Cannot access to the account in any way

### ISSUE THREAD

**Issue by matteomigliore** [NuGet/NuGetGallery#8408]
### I lost the access to the main account on Nuget

I no longer have access to the email address associated with the account they used to publish the packages.

The domain has expired.

Please, can you help me to recover it?

Thank you.

**Comment by skofman1** [comment]
@matteomigliore , please send us an e-mail to 'support at nuget.org' with details about the name of your account and we will help you recover it!

**Comment by matteomigliore** [comment]
@skofman1 yes, you are tight, but No one has answered for 10 days!

**Comment by skofman1** [comment]
@matteomigliore , I see that we responded to your e-mail on Jan 28th. Please check your inbox for e-mails from admin at nuget.org.

**Comment by matteomigliore** [comment]
Hi Svetlana,

I cannot access to the emails linked to the domani because has not been
renewed.

Is there another way to solve?
Thank you.
Matteo Migliore

CEO - LEGALDESK
Cellulare 327 311 37 91

Il ven 5 feb 2021, 19:37 Svetlana Kofman <notifications@github.com> ha
scritto:

**Comment by ryuyu** [comment]
@matteomigliore We have started the process to hand the account over to you.
If we have not received a reply from the email on the account in a few more days, we will help fix the email address on the account.

Sorry that this has taken so long.
We appreciate your patience.

**Comment by matteomigliore** [comment]
Hi @ryuyu, it's been 5 days, do I have any hope of recovering my account? In total I have been waiting for 20 days.

Thank you.

**Comment by ryuyu** [comment]
@matteomigliore We are now ready to help you claim the account.
However, we have received no reply on any of the mails we have sent to you.
Could you send an email to support@nuget.org from the email that you would like to claim the account to?

Please include my name in either the subject or the body of the mail.
We will need this to continue to process.

Thanks again for bearing with us while we work through this.

**Comment by matteomigliore** [comment]
Hi @ryuyu ok, I send you the email. Thank you.

**Comment by ryuyu** [comment]
@matteomigliore I have update the account to the email address you provided.
You should be able to use the Reset Password procedure (https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#how-to-recover-nugetorg-password-login) to complete the reclaim of the account.

Please let me know if you continue to have difficulty.

Thanks for the your patience!

**Comment by matteomigliore** [comment]
Hi, I don't see the packages from none of my accounts.

Thank you.

**Comment by matteomigliore** [comment]
Thank you guys.

Now all is fixed. Good job.
