### ISSUE TITLE
Add link to Package Authoring best practices to Package Upload page

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#8411]
### Is your feature request related to a problem? Please describe.
It will make the page more discoverable to package authors.

### Describe the solution you'd like
Add a link to this page: https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices

//cc @jcjiang

**Comment by jcjiang** [comment]
![image](https://user-images.githubusercontent.com/23298667/107704096-8eee0580-6c71-11eb-9bf3-365df1754be6.png)
Looking at the existing functionality, I feel the warning that pops up when a package does not have sufficient information is a good place to put the link. Maybe it can replace the existing link. I am wary of putting the link at the very top because it is less discoverable. What do people think?

**Comment by skofman1** [comment]
I thinking changing the 'read more' link is a good idea, but the thing is, that the logic that pops-up this warning doesn't verify all the best practices in the doc.
What do you think about change the 'Read More' but also updating the text in the tab. We can add something like: "To learn how to author great packages read here".

![image](https://user-images.githubusercontent.com/16807822/107809641-45a8bf00-6d20-11eb-904a-17862a658a71.png)

**Comment by jcjiang** [comment]
Great point. I think linking in both places is a great idea! So something
like:

# Tab:

Your package file will be uploaded and hosted...

For resources on how to author great packages, read here.

# Read More

We recommend that you fix these issues and upload a new package. For more
resources, read here.

**Comment by loic-sharma** [comment]
Here are some links to the relevant code:

https://github.com/NuGet/NuGetGallery/blob/c71e12429b108c4d87e2da41790b164149a43389/src/NuGetGallery/Views/Packages/UploadPackage.cshtml#L20

And:

https://github.com/NuGet/NuGetGallery/blob/db62de43e24b704e9ab16d8abc39bdfa3e73260b/src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml#L77-L78
