### ISSUE TITLE
Launch NuGet Package Explorer from NuGet.org

### ISSUE THREAD

**Issue by Giorgi** [NuGet/NuGetGallery#8428]
It would be very useful if there was a link which uses custom scheme to launch [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) with the current package to load.

**Comment by skofman1** [comment]
@clairernovotny , what do you think?

**Comment by clairernovotny** [comment]
We have something special coming soon. Will email offline.

**Comment by clairernovotny** [comment]
It's live!

https://twitter.com/UnoPlatform/status/1407379209467617280
https://platform.uno/blog/nuget-package-explorer-is-now-a-web-app-powered-by-uno-platform/

Check out NuGet.info. You can also go to any NuGet.org package and change the .org to .info and it'll load up!

**Comment by loic-sharma** [comment]
FYI we do have a link to NuGet Package Explorer already, but it is only shown on Internet Explorer:

https://github.com/NuGet/NuGetGallery/blob/908da7fb5c1ae6768fd04e5ee093bab6ef5c1dba/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L1002-L1005

Replacing that link with nuget.info would be great! @jcjiang and @anangaur what are your thoughts? :)

**Comment by anangaur** [comment]
>FYI we do have a link to NuGet Package Explorer already, but it is only shown on Internet Explorer

Thats a revelation to me. Never seen it (no surprise here) 😄 . Replacing it makes sense to me as we enable for all browsers.

Pasting the current IE screenshot for others:
![image](https://user-images.githubusercontent.com/14800916/123006640-dba6c300-d36c-11eb-9497-b9298b83933d.png)

**Comment by jcjiang** [comment]
Love the idea of replacing that link with nuget.info!

I think we should change 'Package Explorer' to 'NuGet Package Explorer' for clarity, but the icon and general placement of the IE link looks good.

**Comment by anangaur** [comment]
I would rather call it nuget.info. Something like: `<icon> Explore package at nuget.info`. WYSIWYG

**Comment by loic-sharma** [comment]
Or: `<icon> Open in nuget.info`

**Comment by clairernovotny** [comment]
I don't like nuget.info. That's not the brand. Sorry.

**Comment by loic-sharma** [comment]
@clairernovotny What would you prefer instead? `Open in NuGet Package Explorer`, `Open in Package Explorer`, or something else?

**Comment by clairernovotny** [comment]
Open in NuGet Package Explorer is good.

**Comment by joelverhagen** [comment]
Okay, so it sounds like we landed on `Open in NuGet Package Explorer`. 

For the icon, what do you think about this one?

- `FabricFolderSearch`
  ![image](https://user-images.githubusercontent.com/94054/123156935-c68a6c80-d41e-11eb-9145-007233ec3c03.png)

vs.

- Current, IE-only icon: `OpenInNewWindow`
   ![image](https://user-images.githubusercontent.com/94054/123156982-d609b580-d41e-11eb-88b2-4ace174d58c3.png)

We can use most of the icons available here: https://uifabricicons.azurewebsites.net/
(most because we don't have the latest Office UI Fabric icon pack)

Thoughts, @jcjiang?

**Comment by clairernovotny** [comment]
> Okay, so it sounds like we landed on `Open in NuGet Package Explorer`.
> 
> For the icon, what do you think about this one?
> 
> * `FabricFolderSearch`
>   ![image](https://user-images.githubusercontent.com/94054/123156935-c68a6c80-d41e-11eb-9145-007233ec3c03.png)
> 
 
LGTM

**Comment by jcjiang** [comment]
Design looks great. Let's ship it!

**Comment by agr** [comment]
Similar to FuGet link, please make sure the link is optional and is off by default.

**Comment by clairernovotny** [comment]
@agr 
> Similar to FuGet link, please make sure the link is optional and is off by default.

Can you please clarify?

**Comment by dannyjdev** [comment]
> @agr
> 
> > Similar to FuGet link, please make sure the link is optional and is off by default.
> 
> Can you please clarify?

What @agr said is related to have this link hidden in a "feature flag" that we can turn on/off in our admin panel. We did this also for the FuGet link.
