### ISSUE TITLE
NuGet.config proxy is not working 

### ISSUE THREAD

**Issue by diybl** [NuGet/NuGetGallery#8437]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://nuget.cdn.azure.cn/v3/index.json" protocolVersion="3" />
    <config>
        <add key="http_proxy" value="http://192.168.43.129:1081" />
        <add key="no_proxy" value="192.168.43.129,localhost,127.0.0.1,*.azure.cn" />
    </config>
  </packageSources>
</configuration>

the ide is rider
the proxy is ok,but the nuget is not working

the error is:
00:52:08| Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.

**Comment by agr** [comment]
The index.json file you referenced is a [service index](https://docs.microsoft.com/en-us/nuget/api/service-index) file that contains links to actual resources that client uses. If you look at its contents, it still uses `api.nuget.org` in most of the links.

**Comment by diybl** [comment]
no this is not solved....
you give me the api.nuget.org domain in the https://nuget.cdn.azure.cn/v3/index.json file
also in the https://nuget.cdn.azure.cn/v3-index/repository-signatures/5.0.0/index.json
it give me the api.nuget.org domain

**Comment by diybl** [comment]
> The index.json file you referenced is a [service index](https://docs.microsoft.com/en-us/nuget/api/service-index) file that contains links to actual resources that client uses. If you look at its contents, it still uses `api.nuget.org` in most of the links.
> You probably would want `*.nuget.org` in the `no_proxy` list as well.
no this is not solved....
you give me the api.nuget.org domain in the https://nuget.cdn.azure.cn/v3/index.json file
also in the https://nuget.cdn.azure.cn/v3-index/repository-signatures/5.0.0/index.json
it give me the api.nuget.org domain

**Comment by skofman1** [comment]
@diybl, when making requests to domain api.nuget.org in mainland China, the requests get redirected to nuget.cdn.azure.cn.
So the links you are seeing are expected. 
In your nuget.config file, the package source should be https://api.nuget.org/v3/index.json

`<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />`
