### ISSUE TITLE
[Feature Request] Private feeds on nuget.org locked by an ApiKey

### ISSUE THREAD

**Issue by PureKrome** [NuGet/NuGetGallery#8455]
Current NuGet gallery is for public consumption - it's like a single, PUBLIC feed. 

Would love to have a the ability to create private feeds, locked by api keys (which already exist).

Currently we could:
- Use one of the -other- nuget server implementations that exist but this means we need to manage them (which most people don't need to want to manage anything, these days)
- Use a commercial product. This is good for businesses that making a profit/want extra security+complience/advanced features/etc ... but there's still a section of the community that don't need all of that and/or don't make money (but still would like private feeds).

So it would be really awesome if this could be a feature that could be considered.

(This idea was raised in #8314 )

**Comment by skofman1** [comment]
@PureKrome , thanks for the suggestion, however nuget.org is a public feed, and we have made the decision to stay public only. As you mentioned, there are many offerings out there of private feeds.
Based on the scenario of each user, they can decide with private feed to use. Here's a list of offerings in our docs: https://docs.microsoft.com/en-gb/nuget/hosting-packages/overview
