### ISSUE TITLE
[Readme] UTF8 characters broken in preview but work in expanded mode

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8457]
### Describe the bug
UTF8 characters do not render properly in the README preview.

### To Reproduce

1. Go to: https://dev.nugettest.org/packages/Loshar.Readme/2.0.0#
1. Look at the Documentation (notice the ?):

![image](https://user-images.githubusercontent.com/737941/111708733-a2a60200-8803-11eb-8f53-0bb94d04f4d8.png)

1. Now press `+ Show more` (notice the emojis):

![image](https://user-images.githubusercontent.com/737941/111708768-afc2f100-8803-11eb-8a12-5dcb69b2a733.png)

### Expected behavior
UTF8 emojis should work in the preview mode.

**Comment by lyndaidaii** [comment]
was not able to reproduce?
