### ISSUE TITLE
[README] Show more +/- is shown even if there is no additional content

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8458]
### Describe the bug

When the README is short (like 1-3 lines) the "Show more" / "Show less" links are shown but if you click on them they don't do anything.

### To Reproduce

1. Go to this package: https://dev.nugettest.org/packages/ICanHazReadme/1.0.0
2. Click "Show more" and "Show less"

### Expected behavior

The link should not appear for short READMEs.

### Screenshots

![image](https://user-images.githubusercontent.com/94054/111710428-ea7a5880-8806-11eb-94b3-ef11fe2a20b1.png)

**Comment by anangaur** [comment]
Can we increase the number of lines to show to may be 50, before we show the "Show more" link?
