### ISSUE TITLE
[README] Empty embedded readme breaks the manage package > documentation section

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8460]
### Describe the bug

I created a package with an empty README file. It seems to confuse the upload UI and the manage package Documentation section. It sort of looks like some of the code thinks it's a legacy readme package and other code thinks its an embedded readme.

### To Reproduce

Go here: https://dev.nugettest.org/packages/ICanHazReadme/1.0.2/Manage

Or

1. Create a nupkg with an embedded readme and make the readme empty (0 bytes)
2. Upload to Gallery
3. Notice the README preview on the upload package
4. After the package is uploaded, go to the Manage Package page and expand the Documentation section

### Expected behavior

Either the package should be rejected or the package should be considered to have an embedded readme and no Preview button should appear.

### Screenshots

No submit button:
![image](https://user-images.githubusercontent.com/94054/111712721-71c9cb00-880b-11eb-8ed0-5522618fd639.png)

**Comment by lyndaidaii** [comment]
reject empty readme file to aglin with client pack validation behavior
