### ISSUE TITLE
[README] Show more link jumps to the top of the page

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8461]
### Describe the bug

Clicking the Show More link clears the URL fragment and goes to the top of the page.

### To Reproduce

1. Go to https://dev.nugettest.org/packages/ICanHazReadme/1.0.1#show-readme-container
2. Click Show More
3. Wait a second

### Expected behavior

The README should expand but the viewport should stay where it is.

Actual: it jumps up.

### Screenshots

![repro](https://user-images.githubusercontent.com/94054/111713555-21536d00-880d-11eb-91f1-90fa6225b28b.gif)

**Comment by agr** [comment]
Package details page redesign should address it or make it unapplicable.
