### ISSUE TITLE
Do not redirect `https://api.nuget.org/v3/index.json` to `https://nuget.cdn.azure.cn/v3/index.json`

### ISSUE THREAD

**Issue by BlueD** [NuGet/NuGetGallery#8468]
### Describe the bug
Cannot access `https://api.nuget.org/v3/index.json`, because you automatically redirect it to `https://nuget.cdn.azure.cn/v3/index.json`.

And `https://nuget.cdn.azure.cn` has been down for a while.

### To Reproduce
```
C:\Users\blued> aria2c  https://api.nuget.org/v3/index.json

03/27 10:29:19 [NOTICE] Downloading 1 item(s)

03/27 10:29:20 [NOTICE] CUID#7 - Redirecting to https://nuget.cdn.azure.cn/v3/index.json
[#47c20f 0B/0B CN:1 DL:0B]
03/27 10:29:41 [NOTICE] CUID#7 - Redirecting to https://nuget.cdn.azure.cn/v3/index.json
[#47c20f 0B/0B CN:1 DL:0B]
03/27 10:30:03 [NOTICE] CUID#7 - Redirecting to https://nuget.cdn.azure.cn/v3/index.json
[#47c20f 0B/0B CN:1 DL:0B]
03/27 10:30:10 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

03/27 10:30:10 [NOTICE] Download GID#47c20fcf7b87320b not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
47c20f|INPR|       0B/s|https://api.nuget.org/v3/index.json

Status Legend:
(INPR):download in-progress.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
C:\Users\blued>
```

### Expected behavior
Do not redirect `https://api.nuget.org/v3/index.json` to `https://nuget.cdn.azure.cn/v3/index.json`.
Or fix `nuget.cdn.azure.cn`.

### Screenshots

https://www.isitdownrightnow.com/nuget.cdn.azure.cn.html

![火狐截图_2021-03-27T02-40-31 709Z](https://user-images.githubusercontent.com/398352/112707799-f0e49080-8ee8-11eb-984b-b7ad0d3339ae.png)

**Comment by loic-sharma** [comment]
Hello,

Thank you for creating an issue. Our monitoring does not indicate any outages. Please email support@nuget.org the following information:

* The geographical area of the affected machine
* Whether the affected machine is behind a proxy or firewall
* MTR or Fiddler traces

To capture MTR, please refer this guide: https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible

Best regards,
NuGet Team
