### ISSUE TITLE
Microsoft.Kepler is not available on nuget.org

### ISSUE THREAD

**Issue by pavanramineni** [NuGet/NuGetGallery#8475]
Unable to find Microsoft.Kepler package in nuget.org . But at the same time, I'm able to download this package from Visual Studio and other problem that I have noticed is KeplerClient.dll is coming as unsigned dll. 

![image](https://user-images.githubusercontent.com/48666994/113125851-a6d71400-9234-11eb-966b-a05daee95970.png)

**Comment by pavanramineni** [comment]
![image](https://user-images.githubusercontent.com/48666994/113125791-9a52bb80-9234-11eb-8b8e-3b85beeec119.png)

**Comment by joelverhagen** [comment]
Hello, there is no record of this package existing on NuGet.org. This is why you are seeing a 404 Not Found at the web page in your screenshot.

My guess here is that your NuGet package source configuration (via `NuGet.Config`) includes an additional feed which has this package. Could you look at the configuration on your local environment to verify this?

You can also restore your project from the command line at `nornmal` verbosity or higher (default is `minimal`) and see which package returned an HTTP 200 for a URL containing this package ID.
