### ISSUE TITLE
Clarify that the the statistics page only shows recent downloads

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8479]
### Describe the bug

It's not clear that the table in the package downloads page shows downloads for the last 6 weeks:

![image](https://user-images.githubusercontent.com/737941/113358201-3266a880-92fa-11eb-90e2-2e23a73235fd.png)

We should update the table's heading to `Downloads (last 6 weeks)`

Reported by: https://twitter.com/Tyrrrz/status/1377717292176445455?s=20

**Comment by loic-sharma** [comment]
Go for it! Let us know if you need any help 😀

**Comment by toseni** [comment]
While looking into this I noticed that `StatisticsController.PackageDownloadsByVersion` calls `GetPackageDownloadsByVersionReport` but result is unused. Data for page is returned from different endpoint `StatisticsController.PackageDownloadsByVersionReport`.
Is there some secret reason for `GetPackageDownloadsByVersionReport` method call inside `StatisticsController.PackageDownloadsByVersion` or that method call is redundant?
