### ISSUE TITLE
[README] "Blockquotes" is using a larger font size, and the distance between rows is too large

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#8505]
Repro:

Test package: https://int.nugettest.org/packages/license-expression-test2

Add this blockquotes into a readme file:

```
line 1
line 2
line 3
> quote1
>> quote 2
>>> quote 3

> quote 4

line 4
line 5
```
The package detail page shows:
<img src="https://user-images.githubusercontent.com/41028779/113785882-daaab180-96ec-11eb-9d9a-84250275e1c7.png" width="180">

Could the rendering be better?

**Comment by skofman1** [comment]
@zhhyu , what is your recommedation?
@lyndaidaii , FYI

**Comment by zhhyu** [comment]
CSS needs to be polished. The parser just translates the markdown into HTML if I understand correctly.

**Comment by lyndaidaii** [comment]
I don't think this is necessary, but this is nice improvement for display. 
Also this is example how github render this would look like: 
![github](https://user-images.githubusercontent.com/64443925/116332330-6660ac80-a786-11eb-90f3-745ef40430e3.PNG)

**Comment by jamesfancy** [comment]
`blockquote` font is too large (20px), I think it should not larger then font size of content (16px).

**Comment by lyndaidaii** [comment]
@jamesfancy Thank you for providing your feedback. We will reprioritize this issue.

**Comment by Tyrrrz** [comment]
I use blockquotes to highlight notes and warnings, but the larger text makes it look really weird. Compare the same readme below on GitHub vs NuGet gallery:

![image](https://user-images.githubusercontent.com/1935960/135525090-8df4debd-ea6e-420c-8df2-4bd523cd7173.png)
![image](https://user-images.githubusercontent.com/1935960/135525040-637f9480-4ef9-41a8-b6ab-345c6ca366bc.png)
