### ISSUE TITLE
[Readme] A marker is added in front of each item in a task list

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#8506]
Repro:

Test package: https://int.nugettest.org/packages/license-expression-test4

Add this task list into a readme file:

```
line 1
line 2

- [x] Completed task
- [ ] Incomplete task
  - [ ] task 1
  - [ ] task 2
  - [ ] task 3

line 3
line 4
```
The package detail page shows:
<img src="https://user-images.githubusercontent.com/41028779/113786969-09c22280-96ef-11eb-90d4-88aa5f63876f.png" width="180">

Should the marker be added in front of each item? I don't see this at either GitHub or ADO.

**Comment by lyndaidaii** [comment]
Not sure if this is markdig has option to render html differently, need dig into the markdig extension.
