### ISSUE TITLE
In search of a guide for upgrading self-hosted NuGet Gallery server

### ISSUE THREAD

**Issue by tbeavers** [NuGet/NuGetGallery#8509]
First, please forgive my newbiness when it comes to installing, configuring and upgrading a self-hosted NuGet Gallery server.

With that said, we have a NuGet Gallery server currently running version 1.0.0-master that was initially setup and configured a few years back by someone who is no longer with our company.  We want to upgrade to the latest and greatest release version, but cannot seem to find any documentation or "how to" guide on performing the upgrade. We are hosting on a Windows 2016 server with IIS and found a couple of links on initial setup, including the "[Hosting the NuGet Gallery Locally in IIS](https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS)" wiki page, but don't see anything related to upgrading an existing instance, so any help or direction would be gratefully appreciated.

Thanks in advance for your support.

**Comment by agr** [comment]
I don't think we have any upgrade instructions. The guide you mentioned is mostly applicable for the upgrade as well, the difference would be that you have an existing DB and a configured web service, so you'd need to update the DB and merge the configuration changes.

Hope it goes without saying, but backup everything first. The DB, the packages, the binaries you are currently running in IIS.
I personally would set up separate DB copy for experiments.

If your existing service uses SQL LocalDb (you have `Data Source=(localdb)\mssqllocaldb` in your connection string), you'd need to run the migration on the machine running the service, if you are using full blown SQL instance accessible over the network, you should be able to run migrations from any computer.

To migrate the DB you need get the source code you want to have running, open it in VS and make sure it builds, update the web.config's connection strings to point to the DB you want upgraded (it should be in web.config of the service you run already):
https://github.com/NuGet/NuGetGallery/blob/be38792c3d3d327765113a32d82cd5b9b68cd1b0/src/NuGetGallery/Web.config#L209-L213

(You should be fine just specifying the `Gallery.SqlServer` value)
Then in VS open the Package manager console, make sure the default project is specified as `1. Frontend\NuGetGallery` and run the following command (you should have made backups, this is the point of no return):

```
Update-Database -ConfigurationTypeName MigrationsConfiguration
```

This should update your DB to what the service expects it to be. It will likely make the DB incompatible with whatever old version of Gallery you are running, so please try it on a copy before that. If you get errors, post them.

Next thing is to merge the configurations. Not sure what would be the right way to do it, but I'd load your existing configuration and web.config from GitHub into some kind of diff tool and then apply the options specific to your installation to the new configuration. Alternatively, in your cloned git repository you can overwrite the `src\NuGetGallery\web.config` file with your and then run `git diff` to see what was removed and restore any new lines, or if you have it open in VS2019, you can also see diffs there in the `Git changes` panel.

Once you have Gallery built, DB updated and configuration merged, you should be able to replace your old code in IIS with the new one and see if it works.

**Comment by tbeavers** [comment]
Thank you @agr for the quick and detailed response!
