### ISSUE TITLE
Add hint text to support request edit dialog for tracking DMCA takedowns

### ISSUE THREAD

**Issue by drewgillies** [NuGet/NuGetGallery#8535]
For example: 

If resolving a DMCA request add offender account names (in single quotes, comma-delimited), offending package id, and resolution (no action, withdrawn, upheld). Example: accounts:'foo1','foo2' id:BarPkg resolution: upheld)

This will make the text more searchable, and will assist us in identifying repeat offenders in the DMCA space.

**Comment by drewgillies** [comment]
@jcjiang let's sync about this.

**Comment by skofman1** [comment]
@drewgillies , this is probably already deployed
