### ISSUE TITLE
Include jsdelivr CDN in the trusted image domains list

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/NuGetGallery#8541]
https://www.jsdelivr.com is well-known CDN for serving static files, and it's great to serve images (and other files) from GitHub repositories. All you have to do is use a format like this:

```
https://cdn.jsdelivr.net/gh/github-username/repository-name/path/to/the/image.png
```

e.g.
https://github.com/NuGet/NuGetGallery/src/NuGetGallery/Content/Logos/nugetlogo.png :arrow_right: https://cdn.jsdelivr.net/gh/NuGet/NuGetGallery/src/NuGetGallery/Content/Logos/nugetlogo.png

![nuget logo](https://cdn.jsdelivr.net/gh/NuGet/NuGetGallery/src/NuGetGallery/Content/Logos/nugetlogo.png)

Now that NuGet packages can include a README file, it would be nice to have jsdelivr as an [allowed domain for images and badges](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org)

### Describe the solution you'd like

Add `cdn.jsdelivr.net` to the trusted image domain list.

### Additional context

I'm happy to send a PR, if the above makes sense

**Comment by skofman1** [comment]
@chgill-MSFT , @lyndaidaii  can you evaluate if https://www.jsdelivr.com meets our security and privacy requirements?

**Comment by lyndaidaii** [comment]
@augustoproiete, thank you for your patience. We evaluated cdn.jsdelivr.net.  
This domain looks good in terms of privacy concern. 
But for security concern, we have a little concern that jsdelivr hosts not only images, but also javascript file, which might have malicious script. Some of browsers don't block script. It might put our customers into not secure environment if they use bowsers don't support disable script.
However, we support github images. 
Here is a list of github domain we support: 
        "raw.github.com",
        "raw.githubusercontent.com",
        "user-images.githubusercontent.com",
        "camo.githubusercontent.com"
         github.com/.../workflows/.../badge.svg
We also do additional path check for image start with github.com to address security issues that was exposed to github.com.
Unfortunately, we will not include `cdn.jsdelivr.net` into our allowlist with all consideration mainly because of security concern. 
Please let me know if you have a further question.

**Comment by augustoproiete** [comment]
Thanks for reviewing @lyndaidaii !

I understand the security concern, but I'm not sure I fully I understand the difference between `cdn.jsdelivr.net` and all the other domains currently included in the allowlist today.

Are you saying that it's **not** possible to host a javascript file and serve through any of the [existing domains allowed](https://github.com/NuGet/NuGetGallery/blob/v2021.04.08/src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json) which includes domains such as `ci.appveyor.com`, `circleci.com`, `isitmaintained.com`, etc.? :thinking:

Is there anything unique / special about `cdn.jsdelivr.net` compared to the other domains?

**Comment by lyndaidaii** [comment]
@augustoproiete,  there are possibility that domain from ci.appveyor.com, circleci.com, isitmaintained.com render JavaScript. when we render as img tag, javascript will be blocked. Sorry to my misleading. 
The main concern about `cdn.jsdelivr.net`,  we actually have more constraints for images from github. like this `github.com/.../workflows/.../badge.svg`, we will check the specific path for github image, `cdn.jsdelivr.net` serve images (and other files) from GitHub repositories, it kind of bypass our constraints, which might potential expose a way for attacker. That's our main concern. Also we support images from GitHub repositories like domain `raw.github.com`, `raw.githubusercontent.com`. Customer could directly include their GitHub images in readme without using `cdn.jsdelivr.net`. Hope my explanation is clear now, let me know if you have more questions.

**Comment by augustoproiete** [comment]
Thanks @lyndaidaii. If I understand correctly you're referring to [ImageDomainValidator](https://github.com/NuGet/NuGetGallery/blob/v2021.04.08/src/NuGetGallery/Services/ImageDomainValidator.cs) where there are some checks to allow some images to be served from the github.com domain without having to add github.com in the trusted domain list, and the concern is that `jsdelivr` could bypass these checks.

I can confirm that **`cdn.jsdelivr.net` can only access existing files of a specific repository,** and doesn't expose access to other resources such as workflows or actions.

For instance, if you browse what they can see on this very repository, you'll see that only raw files are available https://cdn.jsdelivr.net/gh/NuGet/NuGetGallery/ which would be the same files available via `raw.github.com`.

A simple test shows that `cdn.jsdelivr.net` doesn't break the constraints:

The following GitHub Actions badge is correctly displayed via github.com:
- `https://github.com/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop`
- ![GH badge](https://github.com/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop)

Whilst the same GitHub Actions badge is not retrieved, because it's not a valid file in the repo:
- `https://cdn.jsdelivr.net/gh/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop`
- ![GH badge attempt via jsdelivr doesn't work](https://cdn.jsdelivr.net/gh/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop)

---

Whilst using `raw.github.com` is an option, the whole point of using `jsdelivr` is to leverage [their global CDN](https://www.jsdelivr.com/network) to serve images much faster which would lead to a better experience for the end-users of the NuGet Gallery.

[![jsdelivr](https://user-images.githubusercontent.com/177608/127368465-ce001db2-b291-4e2b-ae41-7581414fe0d5.png)](https://www.jsdelivr.com/network)

**Comment by lyndaidaii** [comment]
> A simple test shows that `cdn.jsdelivr.net` doesn't break the constraints:



> Thanks @lyndaidaii. If I understand correctly you're referring to [ImageDomainValidator](https://github.com/NuGet/NuGetGallery/blob/v2021.04.08/src/NuGetGallery/Services/ImageDomainValidator.cs) where there are some checks to allow some images to be served from the github.com domain without having to add github.com in the trusted domain list, and the concern is that `jsdelivr` could bypass these checks.
> 
> I can confirm that **`cdn.jsdelivr.net` can only access existing files of a specific repository,** and doesn't expose access to other resources such as workflows or actions.
> 
> For instance, if you browse what they can see on this very repository, you'll see that only raw files are available https://cdn.jsdelivr.net/gh/NuGet/NuGetGallery/ which would be the same files available via `raw.github.com`.
> 
> A simple test shows that `cdn.jsdelivr.net` doesn't break the constraints:
> 
> The following GitHub Actions badge is correctly displayed via github.com:
> 
> * `https://github.com/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop`
> * ![GH badge](https://github.com/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop)
> 
> Whilst the same GitHub Actions badge is not retrieved, because it's not a valid file in the repo:
> 
> * `https://cdn.jsdelivr.net/gh/nils-org/JavaVersionSwitcher/actions/workflows/build.yaml/badge.svg?branch=develop`
> * ![GH badge attempt via jsdelivr doesn't work](https://camo.githubusercontent.com/cb3c5498b6e3ca1efd753b28dc5f6342de02829affcb8fc3099a8577f593ab07/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6e696c732d6f72672f4a61766156657273696f6e53776974636865722f616374696f6e732f776f726b666c6f77732f6275696c642e79616d6c2f62616467652e7376673f6272616e63683d646576656c6f70)
> 
> Whilst using `raw.github.com` is an option, the whole point of using `jsdelivr` is to leverage [their global CDN](https://www.jsdelivr.com/network) to serve images much faster which would lead to a better experience for the end-users of the NuGet Gallery.
> 
> [![jsdelivr](https://user-images.githubusercontent.com/177608/127368465-ce001db2-b291-4e2b-ae41-7581414fe0d5.png)](https://www.jsdelivr.com/network)
Thank you for provding more details. Since it won't retrieve the GitHub Actions badge, I think it will meet our criteria to inlcude it to our allowlist.
