### ISSUE TITLE
Readmes on NuGet.org don't properly handle large images

### ISSUE THREAD

**Issue by chgill-MSFT** [NuGet/NuGetGallery#8545]
### Describe the bug
Readmes on NuGet.org, both through the legacy and embedded workflow, can have images extend past the readme space if they are too large.

Example:
https://www.nuget.org/packages/Ben.Demystifier/0.4.1#
![image](https://user-images.githubusercontent.com/15097183/115898679-d2ac7a80-a42b-11eb-9209-fb71fed94b2c.png)

### To Reproduce
1. Add a link to the following image in a markdown file ![image](https://user-images.githubusercontent.com/15097183/115899032-43539700-a42c-11eb-9022-8bde733ac471.png)
2. Add the markdown as a package readme on NuGet.org by including it in a package or using the legacy workflow.
3. It will look like this: 
![image](https://user-images.githubusercontent.com/15097183/115899534-d7256300-a42c-11eb-8295-47308d7e856e.png)

### Expected behavior
The image should auto-scale to fit the readme space on NuGet.org, like it does in GitHub issues 😊

**Comment by skofman1** [comment]
This is a duplicate: https://github.com/NuGet/NuGetGallery/issues/8502
