### ISSUE TITLE
Set Canonical Meta tag on pages

### ISSUE THREAD

**Issue by MatthewSteeples** [NuGet/NuGetGallery#8559]
### Is your feature request related to a problem? Please describe.
Bing has decided that it's going to index the different versions of NuGet that are out there. As an example: my search for `signalr 2.4.2` resulted in links pointing me to `nugetprodusnc-northcentralus-01.regional.azure-api.net`, `nugetprodusnc.azure-api.net` and `www-1.nuget.org` (which I'm assuming are infrastructure related) as well as `packages.nuget.org` and `www.nuget.org`.

### Describe the solution you'd like
Setting the [Canonical meta tag](https://en.wikipedia.org/wiki/Canonical_link_element) should be a quick fix and ensure that Bing (and other search engines) only forward users to the proper URL

**Comment by skofman1** [comment]
Agree. That's a great idea. @MatthewSteeples thanks for letting us know.
We will get to it ASAP. If you would like to contribute a PR, we will grateful and help you make it live!

**Comment by MatthewSteeples** [comment]
More than happy to put a PR together, but I might need a few pointers on where to begin: The code that emails absolute links (that @joelverhagen suggested) seems to do it based on the URL of the request that came in (as all the emails that I can find are sent out in by controllers rather than as part of any background process).

My recommendation at this point (as an outsider) would be to have a config value set up (`Gallery.CanonicalUri`) and render that on all of the pages if set using something like [this](https://stackoverflow.com/questions/5396724/generating-an-canonical-automatically-for-mvc3-webapplication). Shouldn't be a big job so if there are no objections I'll put that in a PR

**Comment by joelverhagen** [comment]
@MatthewSteeples, we should be able to leverage the [`SiteRoot`](https://github.com/NuGet/NuGetGallery/blob/f248171208356b66499810ddd502276784157422/src/NuGetGallery.Services/Configuration/AppConfiguration.cs#L205-L208) configuration value which contains the "canonical root". The primary place this config is used is for the [`ConfigurationService.GetSiteRoot`](https://github.com/NuGet/NuGetGallery/blob/f248171208356b66499810ddd502276784157422/src/NuGetGallery.Services/Configuration/ConfigurationService.cs#L89-L92) method which plumbs in to [`UrlHelperExtensions`](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/UrlHelperExtensions.cs). Our main PROD deployment has this config:
```json
{
  ...
  "Gallery.SiteRoot": "https://www.nuget.org",
  ...
}
```

For an example of how this is used with email, here's a place we build a URL that a user can click on to reject or approve an organization membership request:
https://github.com/NuGet/NuGetGallery/blob/f248171208356b66499810ddd502276784157422/src/NuGetGallery/Controllers/OrganizationsController.cs#L148-L157

Of hand, I'm not sure of the best way to plumb this config value into a `CanonicalUrl` extension method but perhaps you've already connected the dots with your `Gallery.CanonicalUri` suggestion 😄.

Let me know if you need any other pointers!

**Comment by MatthewSteeples** [comment]
PR created. Let me know if it doesn't fit the style or if you'd rather it was done differently. I've not managed to test it properly yet as I'm still getting my local set-up working, but the code runs without throwing an exception!

**Comment by joelverhagen** [comment]
This is deployed to PROD. I'll wait a couple of weeks and check Google/Bing search results for improvement.

**Comment by MatthewSteeples** [comment]
Thanks for your assistance @joelverhagen 
Next on my list is to try and convince the VS Developer community site to do the same thing - https://vsf-prod.westus.cloudapp.azure.com/content/problem/1499167/download-error-when-installing-visual-studio-2022.html

**Comment by MatthewSteeples** [comment]
Just a note on this one. I think it's a configuration issue rather than code: www-1 seems to be set up with itself as a canonical host (rather than just www)

Example: https://www-1.nuget.org/profiles/WindowsSDK
