### ISSUE TITLE
[2021-05-03] Deployment

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#8566]
# dist.nuget.org

Instructions: https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28On-call.one%7CFFA95A40-BC9F-4CE4-A7D2-3ED62759712D%2F%29

* @skofman1 - Remove "Nightly Builds" from Downloads Page (#8522). Commit: https://github.com/NuGet/NuGet.Services.Index/commit/d4c749e53c191f120b932354c5a21f416f35ea77

**Comment by loic-sharma** [comment]
Merged this into the existing deployment work item here: https://github.com/NuGet/NuGetGallery/issues/8552
