### ISSUE TITLE
[Redesign display package page] Telemetry 

### ISSUE THREAD

**Issue by sophiamfavro** [NuGet/NuGetGallery#8613]
Add new telemetry based on the changes to the display package page. For more information look at the display package page redesign engineering spec as we plan to include telemetry discussed there and possibly more.

**Comment by loic-sharma** [comment]
@dannyjdev You can verify this by on the target environment on Gallery's application insights:

1. There should be a `ShowDisplayPackageTab` custom metric for each time you change the tab (`README`, `Dependencies`, etc..)
2. There should be a `ShowInstallCommand` custom metric for each time you change the install command (`.NET CLI`, `Package Manager`, etc..)
3. There should be a `CopyInstallCommand` custom metric each time you press the copy button
