### ISSUE TITLE
Add support for `<!-- -->` comments in README.mds

### ISSUE THREAD

**Issue by pakrym** [NuGet/NuGetGallery#8627]
In Azure SDKs are trying to start embedding README.md. One issue we've hit is that HTML-style comments that github supports (e.g. `<!-- This is a comment -->`) are rendered directly and not committed.

It would be great if support for stripping comments was added to nuget.org gallery

**Comment by skofman1** [comment]
@pakrym , thanks for the suggestion! If you are interested in contributing a PR we will gladly work with you to merge and ship the change.
