### ISSUE TITLE
Nuget.org search results page and API stats are not updating for about 6 days.

### ISSUE THREAD

**Issue by AnthonyLloyd** [NuGet/NuGetGallery#8634]
This happened before and you reset something after I notified you on twitter. Tried this time but no reply.

Its for everything but as an example currently:

https://www.nuget.org/packages/FsCheck gives 2,937,052 total downloads
https://www.nuget.org/packages?q=FsCheck gives 2,925,061 total downloads

same for the API.

**Comment by agr** [comment]
Generally, the download counts displayed on the search page and the package details page might not align as they come from two different sources (compare https://azuresearch-usnc.nuget.org/query?q=packageid:FsCheck and https://www.nuget.org/packages?q=packageid%3Afscheck) and the cadence of updates does not always match, this is a known issue and we'll look into it while working on the statistics pipeline updates.
In this case though, the search service is not having its version of download counts updated. We are looking into it.

**Comment by AnthonyLloyd** [comment]
Seems to be working again now. Thanks.
