### ISSUE TITLE
Support for publisher filter along the keyword search

### ISSUE THREAD

**Issue by egvijayanand** [NuGet/NuGetGallery#8641]
### Is your feature request related to a problem? Please describe.
For example, if the user want to search for the Maui packages published by Microsoft, there is no provision to do that. 

As of now, user has to search with Maui (relevant) keyword or visit Microsoft (publisher) profile page and look manually by traversing multiple pages.

### Describe the solution you'd like
Either enable the search option in the publisher profile page or add publisher filter in global search page.

### Additional context
I hope the description is self explanatory.

**Comment by skofman1** [comment]
@egvijayanand , thanks for the proposal!

As a stop gap, to filter by package owner you can use the following query pattern:
![image](https://user-images.githubusercontent.com/16807822/122814746-79c15d00-d289-11eb-9784-c7955439762d.png)

**Comment by egvijayanand** [comment]
Hi @skofman1, thanks for the feedback.

Yes, combining the search query term and the owner: pattern does produce the intended result.

Is there any area in documentation where I can such hidden power filters like these. If so, please share the link.

**Comment by skofman1** [comment]
Here it is: https://docs.microsoft.com/en-gb/nuget/consume-packages/finding-and-choosing-packages#search-syntax

**Comment by egvijayanand** [comment]
Hi @skofman1, thanks for the link.

**Comment by joelverhagen** [comment]
Closing since it appears the question has been answered.
