### ISSUE TITLE
GitHub badge regex is wrong

### ISSUE THREAD

**Issue by nils-a** [NuGet/NuGetGallery#8645]
### Describe the bug
According to https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org, github badges should show in embedded readme files.

However, mine does not.

### To Reproduce
1. Upload a readme, containing a badge to a GitHub action.
2. The image will appear "broken" 

### Expected behavior
Badges from GitHub should be rendered.

### Screenshots
![image](https://user-images.githubusercontent.com/349188/122641755-78682700-d107-11eb-9477-3c577f5733f0.png)

### Additional context
The expression to validate the badge is `^(https|http):\/\/github\.com\/[^/]+\/[^/]+\/workflows\/.*badge\.svg`, as given in [`ImageDomainValidator.cs`](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Services/ImageDomainValidator.cs#L16).

However I feel the expression should be `^(https|http):\/\/github\.com\/[^/]+\/[^/]+\/actions\/workflows\/.*badge\.svg`. (Notice `.../actions/workflows/...` instead of `.../workflows/...`)

All my badges contain the `/actions/` in the url, none work if `/actions/` is omitted.

**Comment by nils-a** [comment]
I have checked the two samples given in [ImageDomainValidatorFacts.cs](https://github.com/NuGet/NuGetGallery/blob/main/tests/NuGetGallery.Facts/Services/ImageDomainValidatorFacts.cs#L33) - none of them produce a valid badge. 

If I add `actions` to the URL, they do. (Well, sort of: One URL is broken anyway because of the inserted `/something/`-part, the other points to a non-existing branch..)

**Comment by nils-a** [comment]
@skofman1 Is something wrong with #8646 , or why did you add the up-for-grabs label?

**Comment by lyndaidaii** [comment]
@nils-a, thanks for your great propose. The reason why we add restriction to the github badge because of security concern. I am going to work with you about this effort. I will consult with our security expert to verify if this is secure to change regex to include /actions/, thank your for your patience. I will get back to you once we have result. Thanks!

**Comment by nils-a** [comment]
@lyndaidaii If you point me to a working example for a GitHub badge that matches regex I'd be happy to modify my readme to match the requirements.

**Comment by skofman1** [comment]
@nils-a , added 'up for grabs' retroactively. As @lyndaidaii mentioned, we will work with you on your PR! Thanks for the contribution! 🥇
