### ISSUE TITLE
[nuget.org] The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by MuSHaKS** [NuGet/NuGetGallery#8649]
I can not use the NuGet with Visual studio 2019 professional 16.6.0.
After that i try update it from 16.6.0 to 16.10.2, and try some solution and it is not work.
I try use it with C# .Net framework 4+ projects.

Note/ before a time ago it was working, then suddenly this problem appeared

The below NuGet error :

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

NuGet information:
Name             : Package Manager Host
Version          : 5.10.0.7240
InstanceId       : 0998e14d-2d16-48d4-adc1-1bc589af5580
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by zhhyu** [comment]
Hello, @MuSHaKS ! Sorry for the inconvenience!
We need to collect more information to diagnose this problem. Could you please follow the document here: https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-download-packages-from-or-upload-packages-to-nuget-org
and contact our support about this issue? We will help you there.
Thanks!

**Comment by zhhyu** [comment]
Hello, @MuSHaKS. We will close this issue now. If it still exists for you, feel free to contact the support, and we will help you there.
