### ISSUE TITLE
[Readme] remove space in readme container when preview

### ISSUE THREAD

**Issue by lyndaidaii** [NuGet/NuGetGallery#8651]
![image](https://user-images.githubusercontent.com/94054/120022021-acd14300-bfa0-11eb-89f6-8102320cfb0a.png)

The space here actually is div for edit markdown
https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml#L96
When we preview readme content, we remove hidden class
https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Scripts/gallery/page-edit-readme.js#L332

remove space when there is embeded reamde

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGetGallery/pull/8609.
