### ISSUE TITLE
Auth issue / throttling on search?

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/NuGetGallery#8653]
I see a couple of exceptions in telemetry with the following data. A copy/paste of the URL loads for me; not sure if there might be some other throttle/thing that would be returning a 307?

**Operation Name:** <undefined>

**Timestamp:** 2021-06-22T15:24:07.5360000Z

**Problem Id:** System.Net.Http.HttpRequestException

**Assembly:** NuGet.Protocol, Version=6.0.0.117, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Exception Type:** System.Net.Http.HttpRequestException

**Method:** NuGet.Protocol.HttpSource+<>c__DisplayClass18_0`1+<<ProcessStreamAsync>b__0>d.MoveNext

**Outer Exception Type:** NuGet.Protocol.Core.Types.FatalProtocolException

**Outer Exception Message:** Failed to retrieve metadata from source 'https://azuresearch-ussc.nuget.org/query?q=&skip=0&take=15&prerelease=true&semVerLevel=2.0.0'.

**Outer Exception Assembly:** NuGet.Protocol, Version=6.0.0.117, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Outer Exception Method:** NuGet.Protocol.RawSearchResourceV3+<SearchPage>d__3.MoveNext

**Innermost Exception Type:** System.Net.Http.HttpRequestException

**Innermost Exception Message:** Response status code does not indicate success: 307 (Authentication Required).

**Country or region:** United States

**State or province:** Alabama

**City:** Montgomery

**Link:** https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22:%22997e7c30-fd83-4b3d-bcf5-492e194f9b98%22,%22ResourceGroup%22:%22NuGetPackageExplorer%22,%22Name%22:%22NuGetPackageExplorer%22%7D/DataModel/%7B%22eventId%22:%2203e4fa2b-d36e-11eb-b561-a085fc878f01%22,%22timestamp%22:%222021-06-22T15:24:07.536Z%22%7D

**Comment by joelverhagen** [comment]
There's no telemetry on our side for this request. I looked for queries in a 10 minute range around this request. Nothing hitting "azuresearch-ussc.nuget.org" with that shape of query parameters in that window at all (success or failure).

Do you have a repro? Also, where's the source code for the client (whatever is using NuGet.Protocol)?

**Comment by joelverhagen** [comment]
Also, do you have the response body? That might help us understand what component returned the 307.

**Comment by clairernovotny** [comment]
I wonder if there was some transparent proxy? we don't have the response body, it's just app insights capturing exceptions.

**Comment by clairernovotny** [comment]
The code call is here:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/PackageViewModel/PackageChooser/ShowLatestVersionQueryContext.cs#L117

And it is using `6.0.0-preview.1.117` of the NuGet packages off of the CI feed.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/Directory.Build.props#L44

**Comment by joelverhagen** [comment]
There is an App Service hosting layer. IIS logs from that layer don't show any 307 either. At this point I don't have enough information to diagnose the issue. Could you add a try/catch to capture response body on non-HTTP 200 responses?

The number of layers here is quite high. 
nuget.info -> NPE -> XHR -> NuGet SDK -> USNC and then USSC search -> App Service -> our code 😓

Do you have a % of users/requests impacted by this?

Might be worth adding more instrumentation to the client code so that we can dig deeper. Response body and headers on the error response will help the most I think.

**Comment by clairernovotny** [comment]
This one was from the desktop client, so one layer removed :)

Where would you suggest adding more diagnostics?

`EnsureSuccessStatusCode` is being called within the NuGet client code, so it throws here -- if I put a try/catch around this, what should I report?

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/PackageViewModel/PackageChooser/ShowLatestVersionQueryContext.cs#L117

**Comment by clairernovotny** [comment]
I see it happened twice for this one user...it doesn't look like an ongoing thing as far as I can tell:

![image](https://user-images.githubusercontent.com/1427284/123139981-cab98880-d424-11eb-862c-bca229499f0b.png)

**Comment by clairernovotny** [comment]
Seems rare -- last 30 days it happened 7 times to four different users

![image](https://user-images.githubusercontent.com/1427284/123140540-66e38f80-d425-11eb-82b5-69d60a8f8a48.png)

**Comment by joelverhagen** [comment]
Does this particular user have successful hits also? One theory I have is that their corporate proxy has an "allow list" on azuresearch-**usnc** but not **ussc**. Client code tries USNC first (it's the first entry in the service index) and only fails over to USSC if USNC fails. Perhaps a transient availability issue in USNC causes a rare USSC failure. A corporate proxy could inject a 307 for sites not in the allow list, for example.

Regarding logging response body, I think your best bet would be to enhance the `HttpClient` pipeline by adding a `DelegatingHandler` that captures and logs this case. IIRC this can be done by implementing your own `HttpHandlerResource` somewhat like the default [`HttpHandlerResourceV3`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpHandlerResourceV3.cs).

**Comment by clairernovotny** [comment]
A few more -- I forgot I switched AI resources, so that doesn't go back 30 days. But it's still not high:

![image](https://user-images.githubusercontent.com/1427284/123141035-f0935d00-d425-11eb-9660-d06b59d8e414.png)

**Comment by joelverhagen** [comment]
I see URLs unrelated to azuresearch-*.nuget.org in your screenshots, indicating other package feeds are similarly affected. 

Since we don't have telemetry on our side correlating this problem, I think we will have a hard time digging deeper. I recommend enhancements to client side instrumentation.

**Comment by joelverhagen** [comment]
Closing this issue for now. Once we have more data/instrumentation or additional user reports, we can re-visit.

Currently, this appears to be a client connection issue and we need more information.

**Comment by kartheekp-ms** [comment]
Similar issue is reported via [Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-error:-nugetorg-Fa/10807477).
