### ISSUE TITLE
Replace DMCA reason with link to official Microsoft DMCA portal on 'Report Abuse' page

### ISSUE THREAD

**Issue by jcjiang** [NuGet/NuGetGallery#8654]
### Is your feature request related to a problem? Please describe.
Right now, the 'Report Abuse' page shows the following when users choose to report a DMCA violation. 
![image](https://user-images.githubusercontent.com/23298667/123144183-4230ed00-d410-11eb-821f-7eb714350151.png)

There are several issues with this form:
- No information about the six elements of a DMCA report needed to act, resulting in additional communication between the user and our team to act
- Single text box for input, resulting in difficult to parse information
- Reports come to our team in email, which can be lost in inboxes
- Users must submit a separate form for each package being reported
- There is a separate, Microsoft-wide DMCA portal that accepts DMCA violations related to NuGet. As a result, the team is receiving DMCA requests from two different sources, leading to confusion

### Describe the solution you'd like
After conversation with CELA and DMCA agent, we got permission to link to the [Microsoft DMCA portal](https://msrc.microsoft.com/report/infringement) from NuGet.org. In other words, users will be redirected to the overall Microsoft DMCA portal to submit their report.

![image](https://user-images.githubusercontent.com/23298667/123150737-8ecbf680-d417-11eb-89a7-0a0386734580.png)

Upon clicking on the hyperlink, the user is taken to 
![image](https://user-images.githubusercontent.com/23298667/123150797-9e4b3f80-d417-11eb-887b-718313c1144a.png)

Note the detailed information fields below.

![image](https://user-images.githubusercontent.com/23298667/123150854-b02ce280-d417-11eb-8792-b1f47a69575a.png)

There are several benefits to this:
- All DMCA reports will go through the Microsoft portal, instead of some through the portal and some through email
- Users have more guidance on what information they need to provide within the report, resulting in comprehensive reports that do not require follow-up communications from our team to get needed details
- The official Microsoft DMCA form has a better schema for the report data coming in because it has individual fields for each element of a DMCA complaint. This allows us to better query the data if needed (i.e. checking if a package author has been reported many times for violating DMCA.) 
- DMCA reports that go through the Microsoft portal are stored in ServiceNow, which our team can connect to in order to track the status of reports and ensure none are overlooked

### Additional context
Related to https://github.com/NuGet/NuGetGallery/issues/6364

Note that the official Microsoft DMCA portal actually starts here: ![image](https://user-images.githubusercontent.com/23298667/123145534-c8016800-d411-11eb-9848-f6a38979566f.png)
To get to the form linked above, users have to click on 'Services' and again afterwards to reach the actual form. To reduce friction for users, we will link to the actual form directly.

**Comment by joelverhagen** [comment]
Based on most recent experience with DMCA Agent escalations, we don't believe a tighter integration won't save us much work for the support DRI.
