### ISSUE TITLE
Codacy should be included in trusted badges domains.

### ISSUE THREAD

**Issue by developer-ken** [NuGet/NuGetGallery#8662]
[![Codacy Badge](https://app.codacy.com/project/badge/Grade/98c45dd9417943b0892e7d2f5bed4023)](https://www.codacy.com/gh/developer-ken/ProcedureOrientedSessionFramework/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=developer-ken/ProcedureOrientedSessionFramework&amp;utm_campaign=Badge_Grade)

I want to add this badage and found a warning that it is not in the list of trusted domains.  
Maybe this site can be trusted.

**Comment by joelverhagen** [comment]
Thanks @developer-ken for taking the time to open this issue. Our team will evaluate this host against our security and privacy requirements.

**Comment by lyndaidaii** [comment]
@developer-ken, we actually support api.codacy.com(https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges)
I checked the codacy how they generate the badges. They also support app.codacy.com for bages.

This domain is satisfy our privacy and security requirement. 
Would you like to open a PR to include app.coday.com? 

Here is file we added new domain into list
https://github.com/NuGet/NuGetGallery/blob/db62de43e24b704e9ab16d8abc39bdfa3e73260b/src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

**Comment by developer-ken** [comment]
I was busy with my school project and didnt keep track of this issue for some time. By reading comments above I guess the issue is solved by PR #8687. Maybe I close this issue?
