### ISSUE TITLE
Not able to upload any packages

### ISSUE THREAD

**Issue by vadi2** [NuGet/NuGetGallery#8674]
### Describe the bug
Not able to upload any packages on nuget.org - nothing happens.

### To Reproduce
1. Go to https://www.nuget.org/packages/manage/upload
2. Upload package
3. Observe 404's in the console

### Screenshots
![Screenshot 2021-07-10 10 27 40 AM](https://user-images.githubusercontent.com/110988/125157469-74aa4c00-e16b-11eb-9b09-db8e027948fd.png)

**Comment by loic-sharma** [comment]
Hello, is your package particularly large? Could you try publishing it using the command line: https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package#command-line

**Comment by vadi2** [comment]
It is indeed pretty big; `dotnet pack` is multiplying my asset files a few times over for some reason and that's blowing up the size to about 300mb. Even the CLI upload is failing:

```
--timeout 900000
Pushing Hammer.0.0.2.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/

An error was encountered when fetching 'PUT https://www.nuget.org/api/v2/package/'. The request will now be retried.
Error while copying content to a stream.
  Unable to write data to the transport connection: Connection reset by peer.
  Connection reset by peer
  PUT https://www.nuget.org/api/v2/package/
```

**Comment by loic-sharma** [comment]
The maximum package size is 250mb on nuget.org, so you won't be able to upload your 300mb package. For more information, see: https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#what-is-the-maximum-size-of-packages-i-can-upload-to-nuget-org

> NuGet.org allows packages up to 250MB, but we recommend keeping packages under 1MB if possible and using dependencies to link packages together. ... NuGet uses HTTP to download packages, so larger packages have a higher likelihood of failed installs than smaller ones.

Large packages are not all that well supported by NuGet. I recommend analyzing your package to see what's taking up so much space, and reducing its size if possible. If necessary, you can split your package into smaller packages that are linked together using dependencies.

Here are some suggestions if you still run into upload timeouts after reducing your package's size:

1. Use an internet connection with high upload speeds
2. If possible, try to upload your package from a machine in North America as this is physically closer to our servers that accept package uploads. You can do this using continuous integration providers, like GitHub Actions: https://docs.github.com/en/actions

**Comment by vadi2** [comment]
I've been working through this, going with the split packages approach as it's not been possible to size the package down (nuget duplicating symlinked content is a [blocker](https://github.com/dotnet/sdk/issues/19451)).

How can my application get a path to a dependant package in order to load the content? I understand for assemblies and native libraries nuget has magic that makes them visible, but in my case I my native code needs an actual path to load content from - and I'm not sure how to do that cross-package.

**Comment by joelverhagen** [comment]
Hello @vadi2, I think the best path forward here is to take a look at this document which focuses on creating native packages:
https://docs.microsoft.com/en-us/nuget/guides/native-packages

In the document, there is a link to an example native package. Perhaps that can get you started in the right direction. This repository is more for the nuget.org website so we're not best equipped to answer specific packaging questions like this.

If you're still blocked by native packaging or referencing assemblies in dependencies, could you ask the question at https://github.com/NuGet/Home/issues?

Thanks!
