### ISSUE TITLE
Unable to upload a package with specific prefix

### ISSUE THREAD

**Issue by aviadmini** [NuGet/NuGetGallery#8678]
### Describe the bug
Unable to upload a package. Getting error: `The package ID is reserved. You can upload your package with a different package ID. Reach out to support@nuget.org if you have questions.`. I haven't found a reservation for this prefix, so I sent an email describing the issue on June 1st and got no response.

### To Reproduce
1. Upload package with prefix `Avi.`
2. Getting error: `The package ID is reserved. You can upload your package with a different package ID. Reach out to support@nuget.org if you have questions.`

### Expected behavior
Package gets uploaded

**Comment by joelverhagen** [comment]
Hey @aviadmini, apologies on the delay. I've pulled in the right folks over email to look in to the situation. We'll be reaching out via your original message. Thanks for bringing this to our attention!

**Comment by joelverhagen** [comment]
It looks like your request has been fulfilled. Please feel free to respond to the email thread if you have any other questions. Thanks!
