### ISSUE TITLE
Cannot Access api.nuget.org from a specific IP Address

### ISSUE THREAD

**Issue by janecek1980** [NuGet/NuGetGallery#8679]
We cannot access https://api.nuget.org/v3/index.json. 
When opened in a browser, it just times out. However I can ping it. It seems to be the same issue as: https://github.com/NuGet/NuGetGallery/issues/3971
Strangely enough, it stopped working last Thursday, worked again (by itself) on Friday, and does not work again today.
I have send an email to support@nuget.org with more info.

Thank you, JC

**Comment by loic-sharma** [comment]
Hello,

We have received reports that customers are able to connect to nuget.org again. If you are still experiencing issues, please provide the following information:

* A browser trace reproducing this issue. See: https://docs.microsoft.com/en-us/azure/azure-portal/capture-browser-trace.
* Your geographical area
* Whether your machine is behind a proxy or firewall?
* Is your machine located on a cloud providers' data center (Azure, AWS etc)? If yes, please provide the name of the provider and the region.
 
Also, please run the following commands and provide the output. This will help us understand your specific timeout or connectivity issues.
 
On Windows PowerShell:
 
```ps1
ping api.nuget.org -n 5
(Invoke-WebRequest https://api.nuget.org/v3/index.json -Headers @{ "X-EC-Debug" = "x-ec-cache,x-ec-check-cacheable,x-ec-cache-key,x-ec-cache-state" }).RawContent
```

On macOS or Linux:

```cl1 
curl https://api.nuget.org/v3/index.json -vvv -H "X-EC-Debug: x-ec-cache,x-ec-check-cacheable,x-ec-cache-key,x-ec-cache-state"
```

These commands will provide us with which data center your request is routed to and diagnostic information about the content being returned (if any).

Thank you, and we apologize for the inconvenience. Keep an eye on our status page (https://status.nuget.org) for the latest information.

**Comment by janecek1980** [comment]
Hello,

it seems to be working now. Thanks.
May I ask - what the problem was?

JC

**Comment by loic-sharma** [comment]
We’re glad to hear the problem is resolved! We are still working root causing this incident, but it appears our CDN provider had an outage in certain European areas. Please don’t hesitate to reach out again if you run into additional problems.

**Comment by prenaissance** [comment]
I seem to have the same problem, except that on windows i can access the url from my browser, but in WSL I get the following output when curl-ing index.json:
```
*   Trying 13.107.246.44:443...
*   Trying 2620:1ec:bdf::44:443...
* Immediate connect fail for 2620:1ec:bdf::44: Network is unreachable
```
(My dev environment is in WSL)

Pinging from windows:
```
ping api.nuget.org -n 5                                                                               
Pinging s-part-0017.t-0009.t-msedge.net [13.107.246.45] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```
And running a request from powershell I get the correct result.

**Comment by joelverhagen** [comment]
If you are having connectivity issues with api.nuget.org, please open a support request. Steps:

1. Sign in to NuGet.org
2. Go to https://www.nuget.org/policies/Contact
3. Fill out the support request form, including the details mentioned in the bullet list here: https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org

**Comment by prenaissance** [comment]
> If you are having connectivity issues with api.nuget.org, please open a support request. Steps:
> 
>     1. Sign in to NuGet.org
> 
>     2. Go to https://www.nuget.org/policies/Contact
> 
>     3. Fill out the support request form, including the details mentioned in the bullet list here: https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org

It was a problem with WSL networking. I disabled ipv6 and changed the DNS server and after applying these and a restart I could make requests to nuget. Sorry for the rubber duck debugging and I hope that this is gonna help someone reading in the future.
