### ISSUE TITLE
Add imgur in trusted domains

### ISSUE THREAD

**Issue by Tagliatti** [NuGet/NuGetGallery#8693]
Hi, I would like imgur.com to be included in trusted domains if possible. It is widely used in the README of various projects and is one of the top free image hosts.
Thanks.

**Comment by Tagliatti** [comment]
PR #8694

**Comment by lyndaidaii** [comment]
@Tagliatti, I will work with you to evaluate this domain. We will evaluate this domain from privacy and security perspective. 
I will let you know once we have a conclusion about this domain. thank you!

**Comment by loic-sharma** [comment]
FYI the following popular .NET projects on GitHub use imgur as their image host:

GitHub project | Stars
-- | --
[Wox-launcher/Wox](https://www.github.com/Wox-launcher/Wox#readme) | 20493
[xupefei/Locale-Emulator](https://www.github.com/xupefei/Locale-Emulator#readme) | 6194
[HearthSim/Hearthstone-Deck-Tracker](https://www.github.com/HearthSim/Hearthstone-Deck-Tracker#readme) | 4411
[marian42/wavefunctioncollapse](https://www.github.com/marian42/wavefunctioncollapse#readme) | 3101
[MediaBrowser/Emby](https://www.github.com/MediaBrowser/Emby#readme) | 2882
[Ombi-app/Ombi](https://www.github.com/Ombi-app/Ombi#readme) | 2565
[keijiro/Skinner](https://www.github.com/keijiro/Skinner#readme) | 2474
[IgnaceMaes/MaterialSkin](https://www.github.com/IgnaceMaes/MaterialSkin#readme) | 2303
[sqlkata/querybuilder](https://www.github.com/sqlkata/querybuilder#readme) | 1964
[Codeusa/SteamCleaner](https://www.github.com/Codeusa/SteamCleaner#readme) | 1679
[mellinoe/veldrid](https://www.github.com/mellinoe/veldrid#readme) | 1644
[antonpup/Aurora](https://www.github.com/antonpup/Aurora#readme) | 1598
[kwsch/PKHeX](https://www.github.com/kwsch/PKHeX#readme) | 1593
[keijiro/Klak](https://www.github.com/keijiro/Klak#readme) | 1399
[BeardedManStudios/ForgeNetworkingRemastered](https://www.github.com/BeardedManStudios/ForgeNetworkingRemastered#readme) | 1387
[Unity-Technologies/VolumetricLighting](https://www.github.com/Unity-Technologies/VolumetricLighting#readme) | 1348
[Belphemur/SoundSwitch](https://www.github.com/Belphemur/SoundSwitch#readme) | 1323
[Monnoroch/ColorHighlighter](https://www.github.com/Monnoroch/ColorHighlighter#readme) | 1309
[amaneureka/AtomOS](https://www.github.com/amaneureka/AtomOS#readme) | 1241
[hallatore/Netling](https://www.github.com/hallatore/Netling#readme) | 1212
[keijiro/Voxelman](https://www.github.com/keijiro/Voxelman#readme) | 1156
[keijiro/Kino](https://www.github.com/keijiro/Kino#readme) | 1141
[Unity-Technologies/com.unity.multiplayer.mlapi](https://www.github.com/Unity-Technologies/com.unity.multiplayer.mlapi#readme) | 1093
[SebLague/Path-Creator](https://www.github.com/SebLague/Path-Creator#readme) | 1080
[qmk/qmk_toolbox](https://www.github.com/qmk/qmk_toolbox#readme) | 1056
[natemcmaster/LettuceEncrypt](https://www.github.com/natemcmaster/LettuceEncrypt#readme) | 1024

**Comment by lyndaidaii** [comment]
Evalute this domain. Here is major criteria it meets: 
- It won't drops any cookies
- It support https
- It have decent privacy policy
We will allow to be added in the list.
