### ISSUE TITLE
[Vulnerabilities]: order by severity on the display package page 

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8703]
### Related Problem

The display package page does not order packages' vulnerabilities by their severity. Notice how the most important vulnerability is last here:

![image](https://user-images.githubusercontent.com/737941/127034602-ac0b6873-f428-4247-94cf-ba74316a65d9.png)

### The Elevator Pitch

Some packages have *many* vulnerabilities ([example](https://www.nuget.org/packages/Microsoft.ChakraCore/1.4.2)). Sorting the vulnerabilities by their severity would help customers prioritize their security review.

**Comment by loic-sharma** [comment]
Yup feel free to take it! Please let us know if you run into any problems :)

**Comment by sipmann** [comment]
I tracked down till the `PackageVulnerabilitiesCacheService` source. Unfortunately, I'm not able to set the order through the SQL query. The only way I was able to order, was by setting the order at line 89. But I'm concerned with a possible performance issue. Any tips?

```c#
kv => kv.OrderByDescending(x => x.Severity).ToList().AsReadOnly() as IReadOnlyList<PackageVulnerability>));
```

**Comment by loic-sharma** [comment]
@sipmann Your change has been deployed to nuget.org! Thanks for your contribution 🥳
