### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by donet5** [NuGet/NuGetGallery#8704]
### NuGet Product(s) Involved

Visual Studio Package Management UI

 
I want sqlsugarCore and SqlSugar to come first when searching FOR SqlSugar, currently sqlsugarCore is nowhere to be found 
 
These are all my libraries.  The ranking is not what I want

**Comment by chgill-MSFT** [comment]
Hi!

Those packages are among the top search results when searching for "SqlSugar" in Visual Studio and on NuGet.org (which share the same search API).

![image](https://user-images.githubusercontent.com/15097183/135679112-708bad71-59d7-44f1-a598-26244f36e17a.png)
