### ISSUE TITLE
[Redesign]: large size  Image render problem on details page

### ISSUE THREAD

**Issue by lyndaidaii** [NuGet/NuGetGallery#8719]
### Impact

Other

### Describe the bug

When we display large image in the readme, image was out of bound. 
old page: 
![readmeimage](https://user-images.githubusercontent.com/64443925/127562776-748550b8-6816-4fa8-9055-ce1688a2f72b.PNG)

redesign page:
![reamdecontainer2](https://user-images.githubusercontent.com/64443925/127562536-d593b647-59ff-45f3-a551-66e20ee6722a.PNG)

### Repro Steps

see page here: https://dev.nugettest.org/packages/BaseTestPackage.ReadmeAllowlist/1.0.0?preview=1

### Expected Behavior

images should stay in side of readme container

**Comment by loic-sharma** [comment]
@dannyjdev You can verify this by uploading this package to the target environment and checking the images in the README look OK: https://dev.nugettest.org/packages/BaseTestPackage.ReadmeAllowlist/1.0.0?preview=1
