### ISSUE TITLE
[Redesign]: Font doesn't load correctly on Safari browser.

### ISSUE THREAD

**Issue by dannyjdev** [NuGet/NuGetGallery#8722]
The text bellow the installation instructions is not loading correctly on the new design.

**Previous Design**
![Previous page.jpeg](https://images.zenhubusercontent.com/5cd21722a70bea5d9ac12498/03a1ef7c-90d9-4f8c-9ff5-eae8dece2434)

**New Design**
![New V2 page.jpeg](https://images.zenhubusercontent.com/5cd21722a70bea5d9ac12498/ba97a5fe-1839-4f29-90ef-8ea468ed038b)

This was tested on Safari Version 14.1.1.

**Comment by loic-sharma** [comment]
@dannyjdev You can verify this on Safari on macOS by selecting the `PackageReference` installation instruction and making sure the warning below the instructions has the correct font.
