### ISSUE TITLE
[Feature]: Allow badges from FOSSA and GitHub Socialify

### ISSUE THREAD

**Issue by fgreinacher** [NuGet/NuGetGallery#8757]
### The Elevator Pitch

According to the [documentation for readme files in NuGet packages](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges) it is currently not possible to include badges for [FOSSA](https://fossa.com) or [GitHub Socialify](https://socialify.git.ci).

As both services seem to be pretty common and trustworthy I'd kindly ask you to consider adding the following patterns to the allow-list:

- `https://socialify.git.ci/.../.../image`
- `https://app.fossa.com/api/projects`

**Comment by fgreinacher** [comment]
Thanks @lyndaidaii, sounds good to me!

Regarding Socialify maybe @wei you might want to tackle this 😀

**Comment by CryogenicPlanet** [comment]
One of the other maintainers of Socialify here, just wanted to reply to clarify and ask exactly what you would want us to add.

 This is an OSS project (https://github.com/wei/socialify) and we literally collect nothing, no cookies, no emails, nothing. 
 
We do use Google Analytics (as mentioned here https://github.com/wei/socialify/issues/66). We added this to the readme https://github.com/wei/socialify#privacy and can link it on the site if needed

Not super familiar with legal stuff especially around OSS so we can try to generate a privacy policy, but most generators expect us to collect something, and we really don't collect anything.

**Comment by lyndaidaii** [comment]
@fgreinacher, We will proceed including `https://app.fossa.com/api/projects` in allowlist first, in terms of `https://socialify.git.ci/.../.../image`, we will investigate further related to legal stuff. For now, suggest to use alternative image host [image domain allowlist for readme in NuGet packages](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges)

**Comment by fgreinacher** [comment]
@lyndaidaii Can you share an update regarding the legal clarifications around `https://socialify.git.ci/.../.../image`?
