### ISSUE TITLE
[NuGet.org Bug]: Add cdn.syncfusion.com domain to trusted allowed list domain for nuget readme image

### ISSUE THREAD

**Issue by AbishakeD** [NuGet/NuGetGallery#8768]
### Impact

Other

### Describe the bug

We need to add readme with images for our syncfusion nuget packages. But images are allowed only [trusted domain](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges) in nuget readme file.

We need to use our domain as cdn.syncfusion.com in our syncfusion nuget readme file. So, could you please check our syncfusion domain cdn.syncfusion.com and include the domain into the trusted domain allow-lists for images in nuget readme?

### Repro Steps

1. Create a readme file for the nuget package with referring images by cdn.syncfusion.com link.
2. While we push created nuget, a warning occurs like images are allowed only trusted domain in readme preview.

### Expected Behavior

We need to use the cdn.syncfusion.com domain in nuget readme for images.

**Comment by joelverhagen** [comment]
Thanks for taking the time to reach out @AbishakeD. @lyndaidaii will check on this request and get back to you.

**Comment by AbishakeD** [comment]
Hi team,

Could you please update on this query?

Thanks,
Abishake

**Comment by AbishakeD** [comment]
Hi team,

Could you please update the status of this query? We need to complete this from our side.

Regards,
Abishake

**Comment by joelverhagen** [comment]
Hello! We are planning to investigate this issue during the month of September. We must evaluate whether the image host meets our privacy and security requirements.

In the meantime, you can consider using one of our allowed image hosts: https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges

**Comment by lyndaidaii** [comment]
@AbishakeD, Thank you for your patience. We are evalutating `cdn.syncfusion.com ` domain as you requested. Would you help provide example of image with host `cdn.syncfusion.com` to help us with evaluation. Thank you.
