### ISSUE TITLE
[NuGet.org Bug]: Error message shown in README preview from manage packages

### ISSUE THREAD

**Issue by AbishakeD** [NuGet/NuGetGallery#8771]
### Impact

Other

### Describe the bug

Navigate the manage packages section for our nuget packages in nuget.org and go to the Readme section below error is occurred

![image](https://user-images.githubusercontent.com/89626070/131291836-ed937a49-1560-4404-88a8-42c08c71a6f0.png)

This error occurred either readme file with or without HTML content. But, it's not affected while publishing process, if readme file more than 8kb

### Repro Steps

1. Navigate to Manage packages-> Readme in a published nuget package.
2. Below error message is shown 

      **Error Message:**  Conversion of Markdown to HTML failed with 'The Markdown Documentation file must be less than 8000 bytes

### Expected Behavior

Navigate to Manage packages-> Readme in a published nuget package not shown any error message

**Comment by joelverhagen** [comment]
What is the size of the README that you are uploading? I believe we picked this number conservatively based on existing README files. I believe we may have some wiggle room to increase this number depending on your requirement.

@lyndaidaii, what are your thoughts here?

**Comment by lyndaidaii** [comment]
@joelverhagen, currently the max size of readme file allowed is 1MB when customer upload package via gallery UI. However, in client side, there is no file limitation when publish package via nuget.exe/nuget cli. There is expected inconsistency from Client and Server. 
https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Services/PackageMetadataValidationService.cs#L61
https://github.com/NuGet/NuGetGallery/blob/db62de43e24b704e9ab16d8abc39bdfa3e73260b/src/NuGetGallery/Services/ReadMeService.cs#L238

**Comment by lyndaidaii** [comment]
@AbishakeD We were able to reproduce this issue. There is bug that inconsistency of readme file size check when display and upload package with readme. We will fix this bug. Thanks for reporting it. 

For embedded readme,  we don't support edit. What you could do is upload new version of package with new embedded readme file. 
Also you could preview readme file during upload. Here is upload link in nuget.org(https://dev.nugettest.org/packages/manage/upload).
For instance, you could preview your readme during upload: 
![UPLOAD](https://user-images.githubusercontent.com/64443925/131404715-4b4779eb-49ec-415a-94da-4f0b9802b0d8.PNG)
You could make sure what readme file look like when you publish package. 
Here is link about supported Markdown features for readme(https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org).
We would suggest to upload new version of package with embedded readme and make sure readme display as you want during upload. 
At meanwhile we are investigating and will fix this bug. Please let me know if you have any questions.
