### ISSUE TITLE
Missing nuget package 

### ISSUE THREAD

**Issue by deya-rawr** [NuGet/NuGetGallery#8784]
I couldnt find the nuget package Azure.Messaging.EventHubs.Producer

Can someone make sure I'm looking at the right place?

**Comment by joelverhagen** [comment]
Hello @deya-rawr. No package with that ID has existed on NuGet.org. However, I did some web searches and found that `Azure.Messaging.EventHubs.Producer` is one of the .NET namespaces in the [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs/):

https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer?view=azure-dotnet

Could the Azure.Messaging.EventHubs package be what you're looking for?

**Comment by joelverhagen** [comment]
Closing due to no response. Please feel free to open a new issue if you are still blocked.
