### ISSUE TITLE
[NuGet.org Bug]: Markdown table format is not shown properly

### ISSUE THREAD

**Issue by AbishakeD** [NuGet/NuGetGallery#8788]
### Impact

Other

### Describe the bug

I published package contains a readme file with markdown table format. But content is not visible properly with table format vertical line is missing

https://www.nuget.org/packages/CommonNuget/2.0.0

![image](https://user-images.githubusercontent.com/89626070/132215186-a0ad953a-9141-4ac7-af08-94454f4cf3bd.png)

### Repro Steps

1. Create a nuget package with a readme file contains markdown table format.
2. Publish it into nuget.org.
3. Check published package table format is not correctly formatted.

### Expected Behavior

We will expect table content is shown like below in the readme

ColumnName | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11
--- | --- | --- | --- |--- |--- |--- |--- |--- |--- |--- |---
Row1 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 7 | 9 | 6 | 7
Row2 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 6 | 5
Row3 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 6 | 4
Row4 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 6 | 5
Row5 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 6 | 5

**Comment by loic-sharma** [comment]
Hello, thanks for reporting this. We are tracking this improvement in this issue: https://github.com/NuGet/NuGetGallery/issues/8503

I'll close this one off for now, but let us know if you have any additional suggestions or questions!
