### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by ShadowDancer** [NuGet/NuGetGallery#8789]
### Impact

It bothers me. A fix would be nice

### Describe the bug

When cancelling upload to nuget gallery package ID is reserved, and it's not linked to account of person using it.
Because of this you cannot anymore upload package with this ID, because gallery errors with message:
`The package ID 'package-name' is not available.`.

Packages is not linked to your account, so there is no recovery, you need to change package ID.

### Repro Steps

1. create new nuget package with available ID.
2. Go to https://www.nuget.org/packages/manage/upload select browse and select your package
3. Read the notification about forgotten license link
4. Press cancel
5. Update package with license link
6. Try again
7. `The package ID 'package-name' is not available.`.

### Expected Behavior

I should be able to try again if I decided to cancel process.

**Comment by loic-sharma** [comment]
Hello, the package ID you are uploading is likely already reserved. Please contact support@nuget.org with the package ID you are uploading and we should be able to help you out.

Just to be sure, I tried your repro steps on nuget.org using a new package that that isn't reserved, and this worked as expected.
