### ISSUE TITLE
[Feature]: Add instructions to install MSBuildSdk packages

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/NuGetGallery#8800]
### Related Problem

Packages of type `MSBuildSdk` such as [`Microsoft.DotNet.PackageValidation`](https://devblogs.microsoft.com/dotnet/package-validation/#how-to-add-package-validation-to-your-projects) are meant to be consumed using the `<Sdk ... />` element.

However, the NuGet Gallery displays the installation instructions equivalent of `Dependency` type package:

![image](https://user-images.githubusercontent.com/177608/132955645-277a007d-2d3d-4885-954e-12e5927860d9.png)

### The Elevator Pitch

Add specific instructions for installing packages of type `MSBuildSdk` that the user can copy/paste on their project:

![image](https://user-images.githubusercontent.com/177608/132955565-6118354c-380f-4e3f-a0a6-0626e77d5e92.png)

**Comment by loic-sharma** [comment]
Good idea! If anyone is interested in implementing this, this is where you'll want to add this:

https://github.com/NuGet/NuGetGallery/blob/f08f9af86f14034516aa78ab25ca990b9cc23629/src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml#L27-L137

And:

https://github.com/NuGet/NuGetGallery/blob/1433c8197fadf16848de2b64a6c256112f2f2ec6/src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs#L105-L106
