### ISSUE TITLE
[Bug]: Image from camo.githubusercontent.com not displayed in NuGet Gallery

### ISSUE THREAD

**Issue by rdeago** [NuGet/NuGetGallery#8801]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The README for my package [Buildvana.Sdk](https://www.nuget.org/packages/Buildvana.Sdk) contains a badge hosted on `camo.githubusercontent.com`. The image is not displayed, despite `camo.githubusercontent.com` being [listed as a trusted domain](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges).

The complete URL for the image is https://camo.githubusercontent.com/4033ac1880ed401cc95b630c4994c1f2381101063742dfb4b7bd136966889fc5/68747470733a2f2f7777772e636f6465666163746f722e696f2f7265706f7369746f72792f6769746875622f6275696c6476616e612f6275696c6476616e612e73646b2f6261646765

### Repro Steps

1. Open https://www.nuget.org/packages/Buildvana.Sdk
2. Observe that the "Readme" section contains the warning "Some images are not displayed as they are not from trusted domains."
3. Click on the "Show more..." link under the warning.
4. Observe that the leftmost badge in the second row of badges is missing.
5. Verify that the badge appears correctly when looking at the [README on GitHub](https://github.com/Buildvana/Buildvana.Sdk/blob/main/README.md).

### Expected Behavior

The badge should be displayed, as it comes from a trusted domain.

### Screenshots

This is the relevant part of the NuGet Galòlery page for Buildvana SDK:
![NuGet-gallery](https://user-images.githubusercontent.com/139223/133036058-643880bf-c5d3-4a87-9f24-b439cc09687b.png)

This is how the badge appears on GitHub:
![GitHub](https://user-images.githubusercontent.com/139223/133036266-cdb743c9-ee2c-4ebe-b646-4085340a9ed8.png)

### Additional Context and logs

The source for the badge in the README file is as follows:

```Markdown
[![CodeFactor](https://www.codefactor.io/repository/github/buildvana/buildvana.sdk/badge)](https://www.codefactor.io/repository/github/buildvana/buildvana.sdk)
```

As you can see, the badge URL points to `codefactor.io`, which is not in the list of trusted domains; from there it gets redirected to `camo.githubusercontent.com`. This is the most probable cause of the problem: the NuGet Gallery checks URLs in the README source, finds an untrusted domain, and strips the image URL from the displayed README.

A generic solution for _all_ redirected image URLs would entail trying to load every image seemingly coming from an untrusted domain on the NuGet Gallery server, every time a README has to be rendered. I don't know if this means when displaying a package's page (i.e. Markdown is rendered at display time), or at upload time (i.e. Markdown is rendered once and cached). If the last redirection results in an actual image, coming from a trusted domain, the actual image URL should replace the source URL in the rendered README.

Of course, just adding `codefactor.io` to the list of trusted domains would solve the present issue as well.

**Comment by lyndaidaii** [comment]
@rdeago, thank you for your feedback, we are going to take a look at this issue. However, the workaround you could try is edit your readme badge with `https://camo.githubusercontent.com/4033ac1880ed401cc95b630c4994c1f2381101063742dfb4b7bd136966889fc5/68747470733a2f2f7777772e636f6465666163746f722e696f2f7265706f7369746f72792f6769746875622f6275696c6476616e612f6275696c6476616e612e73646b2f6261646765`, meanwhile we are going to evaluate domain `codefactor.io` from security and privacy aspects.
