### ISSUE TITLE
Package readme render for tables is not very legible

### ISSUE THREAD

**Issue by kzu** [NuGet/NuGetGallery#8807]
### Impact

It bothers me. A fix would be nice

### Describe the bug

See the table in the readme for this package: https://www.nuget.org/packages/YamlPeek. Compare with the GitHub readme rendering at https://github.com/devlooped/yaml, as well as the jekyll one at https://clarius.org/yaml.

Would be nice if the nuget.org gallery rendering for table had some borders around table/cells, and supported hard line breaks within the table since that's the only way to improve the readability inside cells.

### Repro Steps

Check the readme source at https://github.com/devlooped/yaml/blob/main/readme.md and compare it with the published package.

### Expected Behavior

Table has border, header with darker background and `br` line breaks are properly rendered as line breaks.

### Screenshots

Screenshots for reference:
1. [nuget.org](https://www.nuget.org/packages/YamlPeek): 
![image](https://user-images.githubusercontent.com/169707/133520032-8c193e5f-23ba-43e0-84b7-ed374c44dbcf.png)

2. [github.com](https://github.com/devlooped/yaml): 
![image](https://user-images.githubusercontent.com/169707/133520065-31f56ca3-7ad1-4b75-b849-2a94670c8398.png)

3. [jekyll site](https://clarius.org/yaml): 
![image](https://user-images.githubusercontent.com/169707/133520099-206abd10-aa76-4a8d-8ffb-c0c7c8994900.png)

**Comment by loic-sharma** [comment]
Hi, thanks for opening this. We're tracking table rendering with this work item: https://github.com/NuGet/NuGetGallery/issues/8503

I'll close this one for now, but let us know if you have additional feedback!
