### ISSUE TITLE
[NuGet.org Bug]: Search endpoint returns old versions

### ISSUE THREAD

**Issue by filipnavara** [NuGet/NuGetGallery#8813]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Search endpoint fail to return newest versions of the Xamarin.Forms package. This breaks dependency updates through GitHub Dependabot.

### Repro Steps

Hit any of the search endpoints with the following query:

- https://api-v2v3search-0.nuget.org/query?q=xamarin.forms
- https://azuresearch-usnc.nuget.org/query?q=xamarin.forms

Notice that the latest returned package versions are 4.3.

When looking at https://www.nuget.org/packages/Xamarin.Forms/ you can see the latest version is 5.0.0.2125.

### Expected Behavior

Version 5.0.xxxx should be returned.

**Comment by loic-sharma** [comment]
Hello, Xamarin.Forms's version includes build metadata (the stuff after the `+` in its version string) and is only supported by clients that support [SemVer 2.0.0](https://semver.org/). We exclude these packages from search results unless the client explicitly declares its support for SemVer 2.0.0 by providing the `semVerLevel=2.0.0` query parameter. For example: [`https://azuresearch-usnc.nuget.org/query?q=xamarin.forms&semverlevel=2.0.0&debug=true`](https://azuresearch-usnc.nuget.org/query?q=xamarin.forms&semverlevel=2.0.0&debug=true)

I know this behavior is quite confusing, and many folks have run into this. We have a work item to update the search behavior to include semver 2 results by default here: https://github.com/NuGet/NuGetGallery/issues/8814

There's a few gotchas with the NuGet protocol. I would highly recommend using NuGet's SDKs if possible: https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#search-packages

If you cannot use NuGet's SDKs, please read the NuGet protocol's docs thoroughly:

* https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-for-packages
* https://docs.microsoft.com/en-us/nuget/api/service-index

By the way, please don't use the `api-v2v3search-0.nuget.org` domain. This endpoint is deprecated. Please make sure to discover the latest search endpoint using the [service index](https://docs.microsoft.com/en-us/nuget/api/service-index). Using the NuGet SDK will do this automatically for you.

I'll close this off for now, but please let us know if you have additional questions or feedback!

**Comment by filipnavara** [comment]
Thanks for the detailed reply. I forwarded link to it to the support ticket for GitHub Dependabot.
