### ISSUE TITLE
[Display package page]: Make body tabs linkable 

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8822]
### Related Problem

The redesigned [display package page](https://www.nuget.org/packages/Newtonsoft.Json/) has body tabs: 
![image](https://user-images.githubusercontent.com/737941/134721623-a723525c-4a57-4943-ba69-d7341253e2ea.png)

### The Elevator Pitch

Suggestion from @NickCraver:

> I can't seem to link someone to a tab. If we're putting the information behind more clicks, at the least we should be able to link them directly there. IMO, something like #versions on the URL using HTML5 push history would do well here. It should automatically update as you navigate tabs, so that you're linking someone to what you're looking at when copying the current URL.
>
> If doing this, please replace history, not add to it - users almost certainly wouldn't want to navigate back through every ta when hitting the back button.

### Additional Context and Details

Kudos to @NickCraver for the suggestion here: https://github.com/NuGet/Home/pull/10867#issuecomment-926585829

**Comment by GKotfis** [comment]
@loic-sharma  I'd like to take this one as a part of my hacktoberfest contributions

**Comment by zhhyu** [comment]
It has been deployed and verified on PROD.
