### ISSUE TITLE
[Question]: Does the Gallery have API for fetching packages by user?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [NuGet/NuGetGallery#8825]
Hello. I'm sorry if it's a wrong place to ask these questions, so feel free to redirect me where needed.

My question is - is it possible to get a list of packages by user via nuget.org's API? In short, I want to make a badge which would show the number of downloads per user/org.

Thanks in advance.

**Comment by loic-sharma** [comment]
Hello, you should be able to use the [search API](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#search-packages) with [nuget.org's search syntax](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax) to do this:

```cs
ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
PackageSearchResource resource = await repository.GetResourceAsync<PackageSearchResource>();
SearchFilter searchFilter = new SearchFilter(includePrerelease: true);

IEnumerable<IPackageSearchMetadata> results = await resource.SearchAsync(
    "owner:microsoft",
    searchFilter,
    skip: 0,
    take: 20,
    logger,
    cancellationToken);

foreach (IPackageSearchMetadata result in results)
{
    Console.WriteLine($"Found package {result.Identity.Id} {result.Identity.Version}");
}
```

Some notes:
1. The search syntax is nuget.org specific. This may not work on other package sources
1. The nuget.org search API has limits on how many results it will return. You may not be able to fetch all data for accounts with thousands of packages

**Comment by WhiteBlackGoose** [comment]
Oh, awesome, thanks
