### ISSUE TITLE
[NuGet.org Bug]: The README Markdown parser does not render HTML that is mixed with Markdown

### ISSUE THREAD

**Issue by JimBobSquarePants** [NuGet/NuGetGallery#8828]
### Impact

It's more difficult to complete my work

### Describe the bug

The README Markdown parser does not render HTML that is mixed with Markdown. This will break the display for many users.

### Repro Steps

Add the following readme file to a package. HTML will not be rendered.
https://raw.githubusercontent.com/SixLabors/ImageSharp/master/README.md

### Expected Behavior

I expect the readme to be rendered in the same manner as GitHub is capable.

### Screenshots

![Screenshot 2021-09-28 142012](https://user-images.githubusercontent.com/385879/135024211-60b860d7-543f-43fe-b631-3b1bce9c8954.jpg)

![image](https://user-images.githubusercontent.com/385879/135024368-0e21a984-91ea-4b32-8e2a-f7d9e61e9ef9.png)

**Comment by lyndaidaii** [comment]
@JimBobSquarePants, thank you for providing feedback and suggestion. We noticed that there are some gaps on NuGet.org, comparing to GitHub markdown flavor. We are having a plan to provide customers with better markdown rendering experience aligning with GitHub markdown. More feedback and suggestions are really helpful for us.

**Comment by loic-sharma** [comment]
Thanks for opening this! We're tracking this work with https://github.com/NuGet/NuGetGallery/issues/8644. I'll close this off for now, but please let us know if you have additional suggestions or questions!
