### ISSUE TITLE
[README]: Add section link support for READMEs

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/NuGetGallery#8833]
### Impact

It bothers me. A fix would be nice

### Describe the bug

Section links in READMEs don't work on NuGet.org.

For longer READMEs, it is pretty common to have a table of contents or similar with links to the various sections like in the "Examples" section for https://www.nuget.org/packages/Azure.Monitor.Query.

![image](https://user-images.githubusercontent.com/15097183/135529614-1b1820ae-3e31-4f37-ace7-74181e74b0bf.png)

### Repro Steps

1. Take the README Azure/azure-sdk-for-net/sdk/monitor/Azure.Monitor.Query/README.md
2. Add to your package and upload to NuGet.org
3. Notice that section links now just link back to the package details page (https://www.nuget.org/packages/Azure.Monitor.Query) rather than bringing you to the expected section.
4. 

### Expected Behavior

Clicking on a section link like `[logs query](#logs-query)` should bring you to the section of the README labeled "logs query". This is the standard behavior on GitHub.

### Screenshots

When I inspect element, this is what the section links look like on GitHub:

![image](https://user-images.githubusercontent.com/15097183/135530909-a2b6520c-c537-43bd-bf1e-c0301fd2d079.png)

This is what the section links look like on NuGet.org:

![image](https://user-images.githubusercontent.com/15097183/135530975-68f6f2c5-beaa-4bea-9fd1-28366eb82bfe.png)

### Additional Context and logs

This issue might be a result of README sections on NuGet.org not being linkable.

**Comment by baronfel** [comment]
This has a builtin handler in Markdig: The [`AutoIdentifier`](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/AutoIdentifierSpecs.md) extension (extension method [here](https://github.com/xoofx/markdig/blob/203cfd6508d4f8fca510edd2f66f229ada2c25ad/src/Markdig/MarkdownExtensions.cs#L230-L237)).  I've used it in past jobs/tasks with great success.

**Comment by clairernovotny** [comment]
I currently consider this a blocker towards using ReadMe's with several of my packages that have long readmes (Humanizer and Refit come to mind).

**Comment by camigthompson** [comment]
Branch merged into dev.

**Comment by camigthompson** [comment]
Verified in PROD.

**Comment by camigthompson** [comment]
Hotfix for 500 error has been verified in PROD.

**Comment by NUBIAARCHANJO93** [comment]
vcs podem me ajudar o cara que moro achou meus vídeos
