### ISSUE TITLE
[Feature]: Support <br/> tags in README markdown

### ISSUE THREAD

**Issue by wiz0u** [NuGet/NuGetGallery#8836]
### Related Problem

In markdown, writing a \<br/> tag after a numbered list entry allows the following line of text to be aligned to the numbered caption

It is accepted by CommonMarks:
https://spec.commonmark.org/dingus/?text=1.%20item%20one%0A%3Cbr%2F%3Etext%20aligned%20with%20%22item%20one%22%0A%20%20%20-%20sublist%0A%20%20%20-%20sublist%0A2.%20item%20two%0A%0A

But NuGet.org shows the \<br/> instead. Live example here:
https://www.nuget.org/packages/WTelegramClient/

### The Elevator Pitch

With issue NuGet/Home#10791 finally solved, we will see an increase in provided Readmes, so I think Markdown support should be more thorough

**Comment by loic-sharma** [comment]
Hello, thank you for opening this! I agree this would be really useful. We're tracking the work of supporting additional HTML elements in markdown here: https://github.com/NuGet/NuGetGallery/issues/8644

I'll close this off for now as a duplicate, but please let us know if you have additional comments or questions!

**Comment by wiz0u** [comment]
Workaround: I discovered that adding two extra spaces at the end of a line is equivalent to <br/> and is supported by Nuget.org
