### ISSUE TITLE
[NuGet.org Bug]: index file contains wrong license URI

### ISSUE THREAD

**Issue by xriser** [NuGet/NuGetGallery#8847]
### Impact

I'm unable to use NuGet.org

### Describe the bug

There are a few old versions of the StyleCopAnalyzers package on nuget.org. 
The issue in the API V3 there are few errors in the index file index.json file, which consists of information about all versions of the NuGet package.
https://api.nuget.org/v3/registration5-gz-semver2/stylecop.analyzers/index.json
There is placeholder ${version} instead of the real package version
"licenseUrl": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/${version}/LICENSE",

It is impacts software that tries to parse package version and in order license URL and fails.

### Repro Steps

1. On this URL
https://www.nuget.org/packages/StyleCop.Analyzers/1.0.0-alpha004
https://www.nuget.org/packages/StyleCop.Analyzers/1.0.0-alpha003
https://www.nuget.org/packages/StyleCop.Analyzers/1.0.0-alpha002
https://www.nuget.org/packages/StyleCop.Analyzers/1.0.0-alpha001
2. Navigate to License Info and try to open the url
3. See url like  https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/$%7Bversion%7D/LICENSE  
which doesn't work.

### Expected Behavior

URL should be with the correct version  
https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/1.0.0-alpha004/LICENSE  

### Screenshots

![image](https://user-images.githubusercontent.com/21225105/137160564-5aa1898c-9af2-43ed-a65d-8f4fca6b373b.png)

**Comment by agr** [comment]
This doesn't seem to be an issue with nuget.org: we merely take what is specified in .nuspec and display that to a user or store to be presented through API. If you download the package, unpack it and look inside .nuspec file you'd see that that's the URL specified by the package author.

![image](https://user-images.githubusercontent.com/102933/140236995-54f99a9c-c39d-4f2d-9fa3-69ee272a271d.png)

This is a packaging issue.

Besides that, license URLs are free form, there are no requirements for them to adhere to any schema. There is also no requirement from NuGet services for this URL to point a valid resource.
