### ISSUE TITLE
[Gallery] Determine whether more work is needed for optimizing secret refresh

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8859]
# Background

When the Gallery reads a secret, it will reload it if the current value is expired:

https://github.com/NuGet/ServerCommon/blob/92d2a66ef95a1772e748872d77f34a6e951ffdc8/src/NuGet.Services.KeyVault/CachingSecretReader.cs#L55-L64

This approach has a few problems:

1. It requires an asynchronous context to read secrets, even if secrets aren't expired. We have [synchronous hot paths that read secrets](https://github.com/NuGet/NuGetGallery/issues/8858).
2. Concurrent accesses to the same secret results in the same secret being refreshed multiple times. This causes the thundering herd problem.

# Solution

The Gallery should reload secrets in the background and allow secrets to be read synchronously if possible. See:

* https://github.com/NuGet/ServerCommon/pull/363
* https://github.com/NuGet/ServerCommon/pull/363#issuecomment-807769173

**Comment by agr** [comment]
Push out #8858 and reassess if it urgent to fix.

**Comment by agr** [comment]
Close if #8858 helps.

**Comment by agr** [comment]
In the past month there are less than 100 sync attempts to create DB context per hour on average (vs ~millions per hour for async variant), each lasting less than 3 seconds. I think we are OK to stop investing any more time into it.
