### ISSUE TITLE
NuGet.org allows all images, including badges, from the following trusted domains to be rendered (but doesn't)

### ISSUE THREAD

**Issue by nullfx** [NuGet/NuGetGallery#8868]
[this page](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges) indicates that the following domains are allowed including travis-ci, except the travis-ci domain listed on that pages is `api.travis-ci.<org/com>` but the images used for the build status badges are not `api.travis-ci.com` but simply `travis-ci.com` which means nuget blocks the badge on any documentation package readme's (including mine as shown below).

Image from github readme.md
![image](https://user-images.githubusercontent.com/324971/140440425-761402ae-9643-4bd5-80a0-d5d5ad1940b9.png)

image on nuget which should be pulling from github readme.md but has travis-ci build image blocked
![image](https://user-images.githubusercontent.com/324971/140440750-72f1bfbf-dad0-440e-b886-56820e5e58bb.png)

**Comment by lyndaidaii** [comment]
@nullfx Thank you for providing more information. api.travis-ci.<org/com> are supported early with badge.
Example: ![api.travis-ci.org](https://api.travis-ci.org/messagemedia/lookups-csharp-sdk.svg?branch=master)
Thanks for pointing out that they also support travis-ci.com.  We will update to travis-ci.org/com to support more scenarios.

**Comment by nullfx** [comment]
has this been pushed to production yet? guessing not since nuget.org still not showing the build status for `travis-ci.org` while trying to update documentation pointing to readme with https://travis-ci.org as the badge source for "build status" which also doesn't show up on the main website:

![image](https://user-images.githubusercontent.com/324971/157476375-28e9b34f-8db6-44b4-a266-92b000e606cc.png)

**Comment by lyndaidaii** [comment]
![Screenshot 2022-03-09 095024](https://user-images.githubusercontent.com/64443925/157501171-cd94fb2a-b5af-4e2d-a8c0-731d38a4af67.png)
It would work. please let me know if you have further questions.

**Comment by nullfx** [comment]
brilliant. it wasn't showing up earlier. that was when i went to try and update the documentation (and saw what I just posted) but its showing now. thanks.
