### ISSUE TITLE
[NuGet.org Bug]: Failed to download package. Response status code does not indicate success: 301 (Moved Permanently)

### ISSUE THREAD

**Issue by NN-BT** [NuGet/NuGetGallery#8871]
### Impact

I'm unable to use NuGet.org

### Describe the bug

The issue started Friday (11-05-2021 PM PST) when running `dotnet restore` on a project failed with the following errors

```
/usr/share/dotnet/sdk/5.0.401/NuGet.targets(131,5): error : Failed to retrieve information about 'Microsoft.Extensions.DependencyInjection.Abstractions' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json'. [**.csproj]
/usr/share/dotnet/sdk/5.0.401/NuGet.targets(131,5): error :   Response status code does not indicate success: 301 (Moved Permanently). [**.csproj]
  Failed to download package 'System.Xml.XDocument.4.0.11' from 'https://api.nuget.org/v3-flatcontainer/system.xml.xdocument/4.0.11/system.xml.xdocument.4.0.11.nupkg'.
  Response status code does not indicate success: 301 (Moved Permanently).
  Failed to download package 'System.Text.Encoding.Extensions.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.3.0/system.text.encoding.extensions.4.3.0.nupkg'.
  Response status code does not indicate success: 301 (Moved Permanently).
```

Entering the URL, e.g. `https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json`  into a browser tab with Network inspection on showed that there is a redirect loop going on

![image](https://user-images.githubusercontent.com/26933358/140829177-4f68ccdc-eae5-4b1a-996f-d3763f28d46c.png)

This happens at random because it depends on the DNS resolution of api.nuget.org. If I'm lucky and the requests get directed to a good server, I could restore the package, but at times I got the above error.

### Repro Steps

1. Update **hosts** file to point api.nuget.org to a problematic server. E.g. `13.107.246.18 api.nuget.org`.
2. Go to the nuget URL either with a browser or curl, e.g. `https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json`
3. See the redirect loop

### Expected Behavior

Response 200 OK with the expected content.

### Additional Context and logs

Running PowerShell

```
resolve-dnsname api.nuget.org

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
api.nuget.org                  CNAME  0     Answer     nugetapiprod.trafficmanager.net
nugetapiprod.trafficmanager.ne CNAME  0     Answer     apiprod-mscdn.azureedge.net
t
apiprod-mscdn.azureedge.net    CNAME  0     Answer     apiprod-mscdn.afd.azureedge.net
apiprod-mscdn.afd.azureedge.ne CNAME  0     Answer     star-azureedge-prod.trafficmanager.net
t
star-azureedge-prod.trafficman CNAME  0     Answer     dual.part-0042.t-0009.t-msedge.net
ager.net
dual.part-0042.t-0009.t-msedge CNAME  0     Answer     part-0042.t-0009.t-msedge.net
.net

Name       : part-0042.t-0009.t-msedge.net
QueryType  : AAAA
TTL        : 101
Section    : Answer
IP6Address : 2620:1ec:bdf::70


Name       : part-0042.t-0009.t-msedge.net
QueryType  : AAAA
TTL        : 101
Section    : Answer
IP6Address : 2620:1ec:46::70


Name       : part-0042.t-0009.t-msedge.net
QueryType  : A
TTL        : 32
Section    : Answer
IP4Address : 13.107.213.70


Name       : part-0042.t-0009.t-msedge.net
QueryType  : A
TTL        : 32
Section    : Answer
IP4Address : 13.107.246.70

t-msedge.net                   NS     93697 Authority  ns1.t-mSEdgE.NEt
t-msedge.net                   NS     93697 Authority  ns2.t-mSEdgE.NEt

Name       : ns1.t-msedge.net
QueryType  : A
TTL        : 93697
Section    : Additional
IP4Address : 13.107.246.1


Name       : ns2.t-msedge.net
QueryType  : A
TTL        : 93697
Section    : Additional
IP4Address : 13.107.246.2
```

**Comment by lyndaidaii** [comment]
@NN-BT, thanks for reporting it. We have applied a mitigation early afternoon, please let us know if you still experience 301

**Comment by hank-weber** [comment]
> @NN-BT, thanks for reporting it. We have applied a mitigation early afternoon, please let us know if you still experience 301

I've been getting similar errors (301) with this message:
![image](https://user-images.githubusercontent.com/38435776/140970684-58670ff8-375b-4974-bc60-b8bfb1f0fbde.png)

Will the mitigation apply for this error as well?

**Comment by lyndaidaii** [comment]
@hank-weber, yes, mitigation will also apply to this. You might need to flush DNS cache for it to work(ipconfig/flushdns),
Please let us know if you still see it.

**Comment by NN-BT** [comment]
thanks for the mitigation. It has been working again so far.

**Comment by marksvc** [comment]
I've been having a similar problem, but with error 404. It can be reproduced by doing the following:

- Modify /etc/hosts to use line `13.107.227.38 api.nuget.org`
- Run `wget 'https://api.nuget.org/v3-flatcontainer/Geckofx45.64.Linux/45.0.21/Geckofx45.64.Linux.45.0.21.nupkg'`
  This produces error:
  > Connecting to api.nuget.org (api.nuget.org)|13.107.227.38|:443... connected.
  > HTTP request sent, awaiting response... 404 Not Found
  > 2022-04-19 12:05:13 ERROR 404: Not Found.

- Modify /etc/hosts to use line `152.199.4.184 api.nuget.org`
- Run `wget 'https://api.nuget.org/v3-flatcontainer/Geckofx45.64.Linux/45.0.21/Geckofx45.64.Linux.45.0.21.nupkg'`
  Success.

Github Actions often end up resolving api.nuget.org to an IP that gives the 404 error, failing my build, and I need to either try again and hope I get a different DNS response, or modify /etc/hosts.

**Comment by agr** [comment]
This is unrelated issue. All `api.nuget.org` urls are [expected](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource) to use all-lowercase package IDs and versions in URLs. Whatever generates those URLs for you is not following the spec.

**Comment by marksvc** [comment]
Thank you so much, @agr . When using lowercase, the error does not occur. 
Thanks for the link; I will look at how I am gathering the URLs.
