### ISSUE TITLE
[NuGet.org Bug]: Allow the user to select precisely the code they want

### ISSUE THREAD

**Issue by MangelMaxime** [NuGet/NuGetGallery#8886]
### Impact

It bothers me. A fix would be nice

### Describe the bug

Hello,

You can't select precisely the text you want in the "command" box.

https://user-images.githubusercontent.com/4760796/142740240-77277e23-4a71-4002-88cf-bd5800e82fd0.mp4

This is annoying when you already have the manifest set up in your repo and just want to copy the second line.

Fix: 

On the CSS class `install-command-row`, remove all the rules about `user-select: all;`

If the user, wants to copy the whole snippet he can use the Copy button on the right.

### Repro Steps

1. Open https://www.nuget.org/packages/fantomas-tool/4.6.0-alpha-008
2. Click on .NET CLI (local)
3. Try to select only the second line

### Expected Behavior

You should be able to select only the second line if you want

**Comment by loic-sharma** [comment]
Thanks for opening this - that video is super crisp! This suggestion seems good to me. @jcjiang or @chgill-MSFT do y'all have thoughts?

**Comment by chgill-MSFT** [comment]
I agree with it 💪

If you want to copy the whole thing you can just select the copy button.

**Comment by kolpav** [comment]
Funny, I was just about to create issue for this as it was something that annoyed me for a long time.

**Comment by loic-sharma** [comment]
Hello, this feature is now available on nuget.org. Please let us know if you have any additional feedback!
