### ISSUE TITLE
[Feature]:  Syntax Highlighting for code example in Readme.md

### ISSUE THREAD

**Issue by nfMalde** [NuGet/NuGetGallery#8894]
### Related Problem

The code examples on .nuget have no syntax highlighting. In some case this might be confusing for users.

### The Elevator Pitch

Add Syntax Highlighting for code examples at readme.md. (Like the one here on github)

### Additional Context and Details

Example:

 C# Code:
```C#
public class Foo {
  public string GetBar() => "bar";
}

```

**Comment by loic-sharma** [comment]
Hello thanks for opening this. We're tracking this ask here: https://github.com/NuGet/NuGetGallery/issues/8632

Please upvote that issue, it will help us prioritize. Thanks!
