### ISSUE TITLE
Total downloads bug

### ISSUE THREAD

**Issue by UkrGuru** [NuGet/NuGetGallery#8895]
Total downloads still view incorrect value in next page https://www.nuget.org/packages?q=ukrguru
and Ctrl+F5 not helped. see more  in screenshots. thanks,

![image](https://user-images.githubusercontent.com/53341568/142729236-1afc603c-9cc6-4c5e-93e5-1ad4ca9f7fa4.png)
![image](https://user-images.githubusercontent.com/53341568/142729273-97fc741e-29b5-4fcd-ac4e-bf0f9a8a96d4.png)

**Comment by anangaur** [comment]
Seems like a product issue than a docs one.

**Comment by joelverhagen** [comment]
If you continue to face an issue, please feel free to open a new issue. Thanks!
