### ISSUE TITLE
[NuGet.org Bug]: Unable to load the service index for source https://api.nuget.org/v3/index.json.

### ISSUE THREAD

**Issue by charlesx163** [NuGet/NuGetGallery#8903]
### Impact

I'm unable to use NuGet.org

### Describe the bug

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.
Unable to load the service index for source https://api.nuget.org/v3/index.json.

### Repro Steps

1 use the VS2019(Microsoft Visual Studio Enterprise 2019 Version 16.11.7) and VS2022 create a Console App
2 manage Nuget Packages and Click the Browse tab
3 the Error occurred

### Expected Behavior

can load the service index for source https://api.nuget.org/v3/index.json. And can install the common nuget package

### Screenshots

![image](https://user-images.githubusercontent.com/20280108/144606316-079232ed-9ad2-4943-b4da-35acde6fe912.png)

**Comment by zhhyu** [comment]
Hi, @charlesx163! My apologies for this inconvenience!

Does that work for you when you reach out to "https://api.nuget.org/v3/index.json" in browsers?
Could you please send us an email to "support@nuget.org" with the following information?
- Your location
- DNS record: (on Windows) “Resolve-DnsName api.nuget.org” or “nslookup api.nuget.org”

Thanks!

**Comment by charlesx163** [comment]
> Hi, @charlesx163! My apologies for this inconvenience!
> 
> Does that work for you when you reach out to "https://api.nuget.org/v3/index.json" in browsers? Could you please send us an email to "[support@nuget.org](mailto:support@nuget.org)" with the following information?
> 
> * Your location
> * DNS record: (on Windows) “Resolve-DnsName api.nuget.org” or “nslookup api.nuget.org”
> 
> Thanks!

Yeah, It works when I open "https://api.nuget.org/v3/index.json" in browsers.
Email has been sent.

**Comment by joelverhagen** [comment]
I am closing this issue because there has been no response back. If you continue to face an issue, please feel free to open a new issue. Thanks!
