### ISSUE TITLE
t[NuGet.org Bug]: Intel corp. cannot upload packages since Dec,9 to nuget.org with API

### ISSUE THREAD

**Issue by nikkidreamt** [NuGet/NuGetGallery#8908]
### Impact

It's more difficult to complete my work

### Describe the bug

We use a command:
for f in $(find <path> -name "*.nupkg" ); do echo $f; curl -H 'X-NuGet-ApiKey:<apikey>' -H 'X-NuGet-Protocol-Version: 4.1.0' -f -S --fail https://www.nuget.org/api/v2/package -X PUT -F "data=@$f" --ciphers AES256-SHA

The response is:
[12:37] Perestoronin, Andrey
* Trying 52.240.159.111...
* TCP_NODELAY set
* Connected to www.nuget.org (52.240.159.111) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: AES256-SHA
* successfully set certificate verify locations:
* CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
* subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=*.nuget.org
* start date: Oct 28 04:20:43 2021 GMT
* expire date: Oct 23 04:20:43 2022 GMT
* subjectAltName: host "www.nuget.org" matched cert's "*.nuget.org"
* issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 02
* SSL certificate verify ok.
> PUT /api/v2/package HTTP/1.1
> Host: www.nuget.org
> User-Agent: curl/7.58.0
> Accept: */*
> X-NuGet-ApiKey:
> X-NuGet-Protocol-Version: 4.1.0
> Content-Length: 16320443
> Content-Type: multipart/form-data; boundary=------------------------d0cc924f276fc3fd
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
**< HTTP/1.1 201 Created**
< Cache-Control: private, s-maxage=0
< Transfer-Encoding: chunked
< Request-Context: appId=cid-v1:338f6804-b1a9-4fe3-bba7-c93064e7ae7b
< Access-Control-Expose-Headers: Request-Context
< Content-Security-Policy: frame-ancestors 'none'
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Set-Cookie: ARRAffinity=a772f7d26114a351ca4c91c481fd64df4c1b791d3577c9c23a1751ba712cdd47;Path=/;HttpOnly;Secure;Domain=nuget-prod-v2gallery-appservice.trafficmanager.net
< Set-Cookie: ARRAffinitySameSite=a772f7d26114a351ca4c91c481fd64df4c1b791d3577c9c23a1751ba712cdd47;Path=/;HttpOnly;SameSite=None;Secure;Domain=nuget-prod-v2gallery-appservice.trafficmanager.net
< Date: Mon, 13 Dec 2021 09:36:35 GMT
<
* Connection #0 to host www.nuget.org left intact

But we don't see the packages on nuget.org yet.
The list pf packages we tried to upload:

onevpl.devel.win-x64.2022.0.0.59.nupkg
onevpl.runtime.win-x64.2022.0.0.59.nupkg
intelipp_crypto.devel.linux-x64.2021.5.0.445.nupkg
intelipp_crypto.devel.linux-x86.2021.5.0.445.nupkg
intelipp_crypto.nonpic.linux-x64.2021.5.0.445.nupkg
intelipp_crypto.nonpic.linux-x86.2021.5.0.445.nupkg
intelipp_crypto.static.linux-x64.2021.5.0.445.nupkg
intelipp_crypto.static.linux-x86.2021.5.0.445.nupkg
intelmpi.devel.win-x64.2021.5.0.474.nupkg
intelmpi.redist.win-x64.2021.5.0.474.nupkg
inteltbb.devel.linux.2021.5.0.707.nupkg
intelmpi.devel.linux-x64.2021.5.0.495.nupkg
intelopenmp.devel.linux.2022.0.0.3623.nupkg
intelopenmp.static.linux.2022.0.0.3623.nupkg
intelopenmp.devel.win.2022.0.0.3663.nupkg
intelopenmp.redist.win.2022.0.0.3663.nupkg
intelipp.devel.win-x64.2021.5.0.528.nupkg
intelipp.devel.win-x86.2021.5.0.528.nupkg
intelipp.redist.win-x64.2021.5.0.528.nupkg
intelipp.redist.win-x86.2021.5.0.528.nupkg
intelipp.static.win-x64.2021.5.0.528.nupkg
intelipp.static.win-x86.2021.5.0.528.nupkg
intelmkl.devel.cluster.win-x64.2022.0.0.115.nupkg
intelmkl.devel.win-x64.2022.0.0.115.nupkg
intelmkl.devel.win-x86.2022.0.0.115.nupkg
intelmkl.redist.cluster.win-x64.2022.0.0.115.nupkg
intelmkl.redist.win-x64.2022.0.0.115.nupkg
intelmkl.redist.win-x86.2022.0.0.115.nupkg
intelmkl.static.cluster.win-x64.2022.0.0.115.nupkg
intelmkl.static.win-x64.2022.0.0.115.nupkg
intelmkl.static.win-x86.2022.0.0.115.nupkg
onednn.cpu_iomp.devel.win-x64.2022.0.0.19.nupkg
onednn.cpu_iomp.redist.win-x64.2022.0.0.19.nupkg
onednn.cpu_tbb.devel.win-x64.2022.0.0.19.nupkg
onednn.cpu_tbb.redist.win-x64.2022.0.0.19.nupkg
onednn.cpu_vcomp.devel.win-x64.2022.0.0.19.nupkg
onednn.cpu_vcomp.redist.win-x64.2022.0.0.19.nupkg
inteldaal.devel.win-x64.2021.5.0.796.nupkg
inteldaal.redist.win-x64.2021.5.0.796.nupkg
inteldaal.static.win-x64.2021.5.0.796.nupkg
inteldal.devel.win-x64.2021.5.0.796.nupkg
inteldal.redist.win-x64.2021.5.0.796.nupkg
inteldal.static.win-x64.2021.5.0.796.nupkg
inteltbb.devel.win.2021.5.0.714.nupkg
inteltbb.redist.win.2021.5.0.714.nupkg

Intel Corp.

### Repro Steps

- Call https://www.nuget.org/api/v2/package api
- expect to see packages on https://www.nuget.org/

### Expected Behavior

to see packages on https://www.nuget.org/

**Comment by joelverhagen** [comment]
Hello @nikkidreamt, I've investigated this situation and it appears that at least the first and last package in the list have been pushed. Could you verify if any packages are missing?

Also, I had to revoke your API key since it was included in one of the traces above, in clear text. You'll need to generate a new one.

**Comment by joelverhagen** [comment]
Closing. @nikkidreamt, please let us know if you are still blocked.
