### ISSUE TITLE
[Feature]: How csproj to custom vaild signatures time?

### ISSUE THREAD

**Issue by shps951023** [NuGet/NuGetGallery#8918]
### Related Problem

https://github.com/andersnm/ExcelNumberFormat/issues/34

Hi @andersnm ,
For all clients, and I downloaded from NuGet official website and tested yesterday, you can use below CLI to test
```
dotnet nuget verify  "C:\Users\Wei\Downloads\excelnumberformat.1.1.0.nupkg"
```

![image](https://user-images.githubusercontent.com/12729184/147842468-6584fa92-90a8-4227-a508-a8b7651354de.png)

Default clients will not use `nuget verify -signatures`, so system will ignore this error. But high level security company like government level they will use it, and it will upgrade to build error.

---

How csproj to custom vaild signatures time?
It looks like 2 years vaild time default, we would like to extend to 4 years.

### The Elevator Pitch

```
PS C:\Users\Wei> dotnet nuget
NuGet Command Line 6.0.0.280
```

**Comment by joelverhagen** [comment]
Hey @shps951023, glad to hear about your focus on package signing details! I look at this issue, the package in question, and your thread with the package owner over on https://github.com/andersnm/ExcelNumberFormat/issues/34.

This package is certainly still in good standing (verifiable, secure) and there are many packages on NuGet.org (perhaps the majority, at this point?) that are in a similar situation where the repository signature's code signing certificate is expired. At first glance this may be shocking but the critical detail here is that the package signatures also include a **trusted timestamp**. Essentially the trusted timestamp captures the fact that the package was code signed at a time that the certificate was not yet expired and this timestamp itself is signed by a trusted timestamping service. This general approach is used in many code signing scenarios to allow the code to be run well beyond the code signing certificate's validity period.

We have several NuGet docs on the subject but perhaps this section provides the most specific point:
https://github.com/NuGet/Home/wiki/Package-Signatures-Technical-Details#-timestamps

> Signatures and countersignatures SHOULD include the `signature-time-stamp` attribute [[RFC 5126](https://tools.ietf.org/html/rfc5126#section-6.1.1)] to provide long-term validity even after the signing certificate's validity period has expired.

In short, it's expected for older packages to eventually have expired code signing certificates but this is mitigated by trusted timestamps.

NuGet client software falls back to the trusted timestamp verification in the event that a code signing certificate. So this is why this package is restoring successfully on your machine. 

Note that you can see the timestamp information:

<pre>
PS C:\Users\jver\Downloads> dotnet nuget verify .\excelnumberformat.1.1.0.nupkg --verbosity detailed

Verifying ExcelNumberFormat.1.1.0
C:\Users\jver\Downloads\.\excelnumberformat.1.1.0.nupkg
Signature Hash Algorithm: SHA256

Signature type: Repository
Service index: https://api.nuget.org/v3/index.json
Owners: andersnm
Verifying the repository primary signature with certificate:
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
  SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 4/9/2018 5:00:00 PM to 4/14/2021 5:00:00 AM
trace:       Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
trace:       SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
trace:       Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       Valid from: 10/22/2013 5:00:00 AM to 10/22/2028 5:00:00 AM
trace:             Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
trace:             SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
trace:             Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             Valid from: 11/9/2006 4:00:00 PM to 11/9/2031 4:00:00 PM
Timestamp: 10/2/2020 5:09:17 AM
<b>Verifying repository primary signature's timestamp with timestamping service certificate:</b>
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 4:00:00 PM to 3/22/2029 4:59:59 PM
trace:       Subject Name: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
trace:       SHA1 hash: 6FC9EDB5E00AB64151C1CDFCAC74AD2C7B7E3BE4
trace:       SHA256 hash: F3516DDCC8AFC808788BD8B0E840BDA2B5E23C6244252CA3000BB6C87170402A
trace:       Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:       Valid from: 1/11/2016 4:00:00 PM to 1/11/2031 3:59:59 PM
trace:             Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
trace:             SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
trace:             Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             Valid from: 4/1/2008 5:00:00 PM to 12/1/2037 3:59:59 PM

Successfully verified package 'ExcelNumberFormat.1.1.0'.
</pre>

I hope this makes sense.

**Comment by shps951023** [comment]
Hi @joelverhagen ,
Thank you for your kind response.
