### ISSUE TITLE
[NuGet.org Bug]: A11y_NuGet Service_Existing User_API Keys_Reflow : On Zooming the screen to 400% two scroll bar are appearing.

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8919]
### Impact

It's more difficult to complete my work

### Describe the bug

From https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1439351

### Repro Steps

1. Hit the https://www.nuget.org/
2. Tab navigate to "Sign in" control and hit enter.
3. Tab navigate to "Sign in with Microsoft" control and hit enter.
4.  Select “API Keys” from the Profile Dropdown and hit enter.
5.  "API Keys" screen gets opened.
6. Zoom the screen to 400% observe that two scroll are appearing.

When we zoom the screen to 400% two scroll bars are appearing.

### Expected Behavior

Only one scroll bar should appear when we zoom the screen to 400% as its not a complex grid.

**Comment by ryuyu** [comment]
This appears to be due to the table showing sample blob patterns not responding correctly to the resize. Investigating options now.
