### ISSUE TITLE
[NuGetGallery repository Bug]: 

### ISSUE THREAD

**Issue by Piedone** [NuGet/NuGetGallery#8944]
### Impact

It bothers me. A fix would be nice

### Describe the bug

When opening a NuGet.org bug, the "this guide" links are broken: 
![image](https://user-images.githubusercontent.com/1976647/150043139-2ac6b714-2031-4a48-9535-a5e209e4b46e.png)

### Repro Steps

Open https://github.com/NuGet/NuGetGallery/issues/new?assignees=&labels=Type%3ABug&template=NUGETORG_ISSUE.yml&title=%5BNuGet.org+Bug%5D%3A+

### Expected Behavior

The links point to somewhere concise. They both just open https://docs.microsoft.com/en-us/nuget/resources/nuget-faq though since apparently the linked questions were removed.

**Comment by joelverhagen** [comment]
Thanks for pointing this out! Looks like our FAQ moved around a bit.
