### ISSUE TITLE
[NuGet.org Bug]: A lot of SPAM - PHISHING websites into NUGET!

### ISSUE THREAD

**Issue by repelentosa** [NuGet/NuGetGallery#8959]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Hello DEVs.

I am user of NUGET since 5 months, but i found a LOT OF SPAMMY/PISHING WEBSITES!
How it is possible?
Part of links:
https://www.nuget.org/packages/Unused-Free-PSN-Codes-Generator-App-2022-XtC/
https://www.nuget.org/packages/Hack-Among.Us.Hack.Unlimited.2022/3.0.2
https://www.nuget.org/packages/BUXFLY-ROBUX-HACK-2022-JANUARY-28-2022/

and more more.

HOW TO FIX IT?

Thanks for review, best regards.

https://www.myget.org/feed/verified/package/nuget/Free-PSN-Codes-List-2022-Unused-Codes-For-Playstation-Plus-PS4-Sh9d

### Repro Steps

spammy links

### Expected Behavior

spammy links

**Comment by shishirx34** [comment]
@repelentosa - thank you for reporting these issues. We will take a look at these packages and investigate.

**Comment by repelentosa** [comment]
Ok.
My team found following links again.

Can you help me with contact with myget.org?
I did notice about spammy but no answer.
https://www.nuget.org/packages/Earn-Free-iTunes-Gift-Cards-in-2022/
https://www.nuget.org/packages/Free-Itunes-Gift-Card-Generator-2022/
https://www.nuget.org/packages/Imvu-Credits-Free/5.6.1



https://www.myget.org/feed/free-code/package/nuget/PS-Plus-Codes-Free-PSN-Cards-Online-PS4-Giftcards-PSN-Cards-Me
BEST REGARDS, TEAM
