### ISSUE TITLE
Incorrect link on NuGet TOU page

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/NuGetGallery#8963]
On the NuGet TOU page (https://www.nuget.org/policies/Terms), the link in the “Your Privacy” section to the "Microsoft Privacy Statement" is wrong. The current link (https://go.microsoft.com/fwlink/?linkid=2180118) points to the “Reporting Infringement” page. It should it point to the Privacy Policy page (https://go.microsoft.com/fwlink/?LinkId=521839) that’s in the footer instead. Confirmed with CELA.

**Comment by zhhyu** [comment]
The link has been updated.
