### ISSUE TITLE
[Feature]: Validation failures for snupkg should specify which pdb(s) were problematic

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/NuGetGallery#8970]
### Related Problem

From Twitter: https://twitter.com/punker76/status/1487421607303946243

If a snupkg contains both portable and Windows PDBs, validation will fail as expected. However the message doesn't say which file was the problem and it's hard for the user to know.

### The Elevator Pitch

The validation messages should specify which files within a snupkg had issues.

**Comment by loic-sharma** [comment]
Merging this one with https://github.com/NuGet/NuGetGallery/issues/8968
