### ISSUE TITLE
[NuGet.org Bug]: Downloads for Latest Version of Package Incorrectly Shows as 0

### ISSUE THREAD

**Issue by chlafreniere** [NuGet/NuGetGallery#8971]
### Impact

It's more difficult to complete my work

### Describe the bug

My team owns https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Sql/ and recently pushed a new version of this package to NuGet.org.

Since then, download numbers on NuGet have stayed at 0 on this latest version (0.1.207-preview), but we know that customers are using this, as we have signals from elsewhere (even including GitHub issues) that show folks are trying this out.

This makes it harder for us to assess usage for this package, and we like to report on package download numbers.

### Repro Steps

1. On https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Sql/
2. Downloads show as 0 for 0.1.207-preview

### Expected Behavior

Downloads do not show as 0.

### Screenshots

![image](https://user-images.githubusercontent.com/40371649/151888859-c8fa89df-33a2-47e9-9b1f-3a937b1d7cad.png)

**Comment by joelverhagen** [comment]
Hello @chlafreniere, apologies on the inconvenience. We have an ongoing issue with delayed package statistics. We have a notice on our [status page](https://status.nuget.org/).

> Package downloads are delayed since January 25th, 2022. Download count statistics are currently being ingested at a reduced rate. This is resulting in download counts on packages not reflecting their latest status. We apologize for the inconvenience and are actively working on a solution.

**Comment by chlafreniere** [comment]
Oh jeez, we totally missed that. Thank you so much, @joelverhagen! Will close this issue then.

Thanks so much for the quick reply!
