### ISSUE TITLE
[NuGet.org Bug]: Why have download counts not updated?

### ISSUE THREAD

**Issue by Jack005566** [NuGet/NuGetGallery#8983]
### Impact

It bothers me. A fix would be nice

### Describe the bug

![image](https://user-images.githubusercontent.com/68726706/152710149-915b98a4-58c0-4bfa-aca8-aa2d1c82e724.png)
EPPlus 4 days without download data

### Repro Steps

https://www.nuget.org/packages/EPPlus/

### Expected Behavior

nodejs.org every day update data, but nuget org looks like not

**Comment by joelverhagen** [comment]
Hello @Jack005566, apologies on the inconvenience. We have an ongoing issue with delayed package statistics. We have a notice on our [status page](https://status.nuget.org/).

We're in the process of ingesting old logs to catch up. Hopefully in next week or so, all of the downloads since the package was published will be reflected on nuget.org.

> Package downloads are delayed since January 25th, 2022. Download count statistics are currently being ingested at a reduced rate. This is resulting in download counts on packages not reflecting their latest status. We apologize for the inconvenience and are actively working on a solution.

**Comment by Jack005566** [comment]
@joelverhagen really appreciate Nuget team's efforts

**Comment by Jack005566** [comment]
@joelverhagen 
Excuse me, extra question, is this using queue technology?

**Comment by joelverhagen** [comment]
We do have a queue of access log files that we are slowly processing through which account for package downloads. These access logs are persisted in Azure Blob  Storage while they wait to be processed.

**Comment by Jack005566** [comment]
@joelverhagen really appreciate your reply

**Comment by Jack005566** [comment]
@joelverhagen 
It's 21 days, is it too many queue items > process speed?
really appreciate your effort

**Comment by joelverhagen** [comment]
Yes that's pretty much the gist of it. Our path forward is to stabilize our new stats system which has no ingestion speed issues. We hope to have this stable and live for NuGet.org download count numbers in the next week or two. Our first priority as a team is availability of package download (e.g. NuGet restore) but we're also focused on this issue in parallel. Apologies for the delay.

**Comment by joelverhagen** [comment]
In order to simplify our issue tracking, I have pinned an explanation of the stats delay in this NuGet/NuGetGallery issues. I'll close this issue in lieu of that: https://github.com/NuGet/NuGetGallery/issues/9018. Please feel free to ask any follow-up questions on that issue.
