### ISSUE TITLE
Plan for NuGet in 2022

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/NuGetGallery#8984]
Today we are excited to share with you the plan for NuGet and NuGet.org. This issue contains summary of the plan for the year and acts as a place for you to leave feedback.

This plan is a collection of input from many stakeholders and outlines where we intend to invest our time in NuGet and NuGet.org.

> **IMPORTANT**
> This plan is not a commitment; it will evolve as we continue to learn throughout the release. Some things that are not currently planned for NuGet may get pulled in. Some things currently planned may even be pushed out.

# General information

NuGet has a major release following [NuGet 6.0](https://docs.microsoft.com/nuget/release-notes/nuget-6.0) and is currently scheduled for release in November 2022 at the same time as .NET 7.

NuGet will align with the [.NET support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) and will therefore **not** be a long-term support (LTS) release.

NuGet.org does not currently follow any specific schedule and releases features & bug fixes regularly throughout the year.

### Breaking changes

NuGet may contain a small number of breaking changes as we continue to evolve NuGet with the .NET platform. Our goal is to minimize breaking changes as much as possible to keep you productive when upgrading.

## Themes

The large investments in NuGet are the following themes:

### Highly Requested Features

As always, a major input into our planning process comes from [votes (👍) for features on GitHub](https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#before-submitting-an-issue).

These features are areas we are actively engaged in with regards to designing, implementing, and polishing the respective experiences for.

#### NuGet Tooling

- https://github.com/NuGet/Home/issues/6764
- https://github.com/NuGet/Home/issues/11752
- https://github.com/NuGet/Home/issues/10730
- https://github.com/NuGet/Home/issues/7752
- https://github.com/NuGet/Home/issues/4103
- https://github.com/NuGet/Home/issues/8087
- https://github.com/NuGet/Home/issues/5887
- https://github.com/NuGet/Home/issues/1851
- https://github.com/NuGet/Home/issues/11262

#### NuGet Gallery

- https://github.com/NuGet/NuGetGallery/issues/3098
- https://github.com/NuGet/NuGetGallery/issues/4843
- https://github.com/NuGet/NuGetGallery/issues/8964

### .NET Platforms and Ecosystem

Much of the work planned for NuGet involves improving the package management experience for .NET across different platforms and ecosystem. This involves work in NuGet to ensure a great experience across .NET technologies.

- https://github.com/NuGet/Home/issues/5926
- https://github.com/NuGet/Home/issues/9667
- https://github.com/NuGet/Home/issues/10800
- https://github.com/NuGet/Home/issues/10430
- https://github.com/NuGet/Home/issues/10872

### Migrating to .NET

NuGet has always [supported many scenarios for package management](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference). In our continued efforts to help you migrate to the latest version of .NET, we will be working on improvements to the [Upgrade Assistant](https://github.com/dotnet/upgrade-assistant) and core package management experiences to help you migrate your project to use the latest version of NuGet.

## Performance

With each [new release of NuGet & Visual Studio comes a plethora of performance improvements](https://devblogs.microsoft.com/visualstudio/performance-improvements-in-nuget/) when restoring NuGet packages, managing project dependencies, and browsing for the next great package to include in your solution. We will continue to invest time to improve your experiences every .NET & Visual Studio release.

# Feedback

Your feedback is important to us. The best way to indicate the importance of an issue is to vote (👍) for that [issue on GitHub](https://github.com/NuGet/Home/issues) and [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We use this data to help us with our regular planning so we can work on the things that matter most to you.

Please **comment on this issue** if you believe we are missing something that is critical for NuGet, or are focusing on the wrong areas. Give us a little bit of context as to why you believe so and feel free to upvote each other's comments to help us make changes to our future plans.

Huge thanks to @ajcvickers and the Entity Framework Core team for a wonderful format and forum to discuss product plans in OSS. 🎉

**Comment by tonyqus** [comment]
Are you planning for 2023? If I need some advanced statistics feature of nuget package data, which place should I input this?

**Comment by JonDouglas** [comment]
Closing in preparation for 2023 to be released as another issue. Thank you all for the great 2022!

**Comment by JonDouglas** [comment]
@tonyqus Please provide that feedback on the 2023 plan to get conversations going :)

**Comment by tonyqus** [comment]
Where is the issue of 2025 plan? I'd like to input something
