### ISSUE TITLE
[Deployment] 2022.02.09

### ISSUE THREAD

**Issue by drewgillies** [NuGet/NuGetGallery#8999]
# Gallery

## Changes
FI `main` to `dev`:
* https://github.com/NuGet/NuGetGallery/pull/8966 (tracked by https://github.com/NuGet/Engineering/issues/4226)
* https://github.com/NuGet/NuGetGallery/pull/8967 (tracked by https://github.com/NuGet/Engineering/issues/4226)
* https://github.com/NuGet/NuGetGallery/pull/8973 (no tracking issue)
* https://github.com/NuGet/NuGetGallery/pull/8978 (tracked by https://github.com/NuGet/Engineering/issues/4226)

RI `dev` to `main`:
* https://github.com/NuGet/NuGetGallery/pull/8914 (tracked by https://github.com/NuGet/NuGetGallery/issues/8503)
* https://github.com/NuGet/NuGetGallery/pull/8960 (tracked by https://github.com/NuGet/NuGetGallery/issues/8961)
* https://github.com/NuGet/NuGetGallery/pull/8972 (tracked by https://github.com/NuGet/NuGetGallery/issues/8920)
* https://github.com/NuGet/NuGetGallery/pull/8974 (tracked by https://github.com/NuGet/NuGetGallery/issues/8919)
* [community <3] https://github.com/NuGet/NuGetGallery/pull/8892 (tracked by https://github.com/NuGet/NuGetGallery/issues/8886)
* https://github.com/NuGet/NuGetGallery/pull/8976 (no tracking issue)
* https://github.com/NuGet/NuGetGallery/pull/8874 (tracked by https://github.com/NuGet/NuGetGallery/issues/8868 and https://github.com/NuGet/NuGetGallery/issues/8801)
* https://github.com/NuGet/NuGetGallery/pull/8977 (tracked by https://github.com/NuGet/NuGetGallery/issues/8975)
* https://github.com/NuGet/NuGetGallery/pull/8947 (tracked by https://github.com/NuGet/Engineering/issues/4179)
* https://github.com/NuGet/NuGetGallery/pull/8981 (no tracking issue)
* https://github.com/NuGet/NuGetGallery/pull/8992 (tracked by https://github.com/NuGet/Engineering/issues/4231 and https://github.com/NuGet/Engineering/issues/4225)
* https://github.com/NuGet/NuGetGallery/pull/8985 (tracked by https://github.com/NuGet/Engineering/issues/4229)
* https://github.com/NuGet/NuGetGallery/pull/8993 (no tracking issue)
* https://github.com/NuGet/NuGetGallery/pull/8995 (tracked by https://github.com/NuGet/Engineering/issues/4220)
* https://github.com/NuGet/NuGetGallery/pull/8996 (tracked by https://github.com/NuGet/Engineering/issues/4219)

## Progress
* [x] Merge FI PR: https://github.com/NuGet/NuGetGallery/pull/8997
* [x] Merge RI PR: https://github.com/NuGet/NuGetGallery/pull/8998
* [x] Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5739295
* [x] Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1262852
* [x] DEV Artifacts build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5700986&view=results
* [x] DEV DB Migration - Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1255940
* [x] DEV
* [x] INT/PROD Artifacts build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5739290
* [x] INT DB Migration - Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1262800
* [x] INT
* [x] PROD DB Migration
* [x] PROD

**Comment by joelverhagen** [comment]
This changeset has a DB migration. Make sure to run this before deployment. @advay26 is the owner.
