### ISSUE TITLE
[NuGet.org Bug]: Using nuget.core 2.14.0 with https://www.nuget.org/api/v2 no longer allows finding packages.

### ISSUE THREAD

**Issue by nickeeex** [NuGet/NuGetGallery#9000]
### Impact

I'm unable to use NuGet.org

### Describe the bug

We are using NuGet.Core 2.14.0 with https://www.nuget.org/api/v2 and yesterday we started experiencing an error blocking finding packages.

We are getting the following exception on almost all packages we try to find using FindPackages(...)
System.InvalidOperationException: Response version '3.0' is not supported. The only supported versions are: '1.0', '2.0'.

This happens both in Azure and locally.

We are in the process of updating to a newer version of nuget but it would be nice to get this fixed.

### Repro Steps

You can also reporduce this manually by for example doing doing a manual request in browser:

1. https://packages.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'&version='4.1.1'
2. Check Response Headers.
3. DataServiceVersion: 3.0 is returned.

### Expected Behavior

Expected behaviour would be to return a version of DataServices that still works with NuGet.Core 2 when using v2 feed.

### Screenshots

Problem when using NuGet.Core
![image](https://user-images.githubusercontent.com/6636662/153552470-e9d14f01-efdd-4a9c-a17a-4d3ef2f38424.png)

Manual repro:
![image](https://user-images.githubusercontent.com/6636662/153591105-e3b0ba64-20cd-4ee2-b972-8a9dd49e32bf.png)

**Comment by joelverhagen** [comment]
Hey @nickeeex, I'm not able to repro the exception you've encountered. I tried to guess the code you're using and came up with this, which appears to work just fine.

```csharp
var repository = PackageRepositoryFactory.Default.CreateRepository("https://www.nuget.org/api/v2");
var packageId = "System.Runtime.Serialization.Primitives";
var version = new SemanticVersion("4.1.1");
var package = repository.FindPackage(packageId, version, allowPrereleaseVersions: false, allowUnlisted: false);
```

Also, I highly recommend trying out the NuGet.Protocol package which is much more performant and has the capability to interact with the V3 NuGet feed. Here are some great samples to get you started if you want to try the V3 feed instead:
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

Could you include a full Fiddler trace as well so I can see exactly what HTTP requests your application is doing?

**Comment by joelverhagen** [comment]
Another weird thing to note is that the `FindPackagesById()` endpoint does not support a `version` query, like in your example URL:
https://packages.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'&version='4.1.1'

Aside from several OData query parameters (e.g. `$orderby`), on `id` and `semVerLevel` are supported on this endpoint:
https://github.com/NuGet/NuGetGallery/blob/00c59a923f36b9f6a8edb5caa3971e4bd23a395f/src/NuGetGallery/Controllers/ODataV2FeedController.cs#L224-L227

**Comment by nickeeex** [comment]
The manual example was a bit hastely cobbled togeather, sorry for that.

So here is an example code that fails for us, but not always, it seems to be random? some packages fail for a couple of hours and then another one. 
```c#
	var repo = NuGet.PackageRepositoryFactory.Default.CreateRepository("https://www.nuget.org/api/v2");
	var packageId = "System.Runtime.Serialization.Primitives";

	var packageVersion = new VersionSpec()
	{
		MinVersion = new SemanticVersion("4.1.1"),
		IsMinInclusive = true,
		MaxVersion = null,
		IsMaxInclusive = false
	};

	var packages = repo.FindPackages(packageId, packageVersion,
			allowPrereleaseVersions: true, allowUnlisted: true);
```
This code will create a request like:  https://packages.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'

This code has been untouched for many years and worked well untill yesterday. 

Here is a example fiddler trace for one import. Here the last request suddently returned DataServiceVersion: 3.0
[FindPackagesById.txt](https://github.com/NuGet/NuGetGallery/files/8051354/FindPackagesById.txt)

We are in the process of updating to newer nuget libraries, we just currently have our own implementation for IPackage and IPackageLookup to use azure blobs as our package store and have not had time find an alternative solution. IIRC there was not a similar way to do it with newer libraries but we have not looked at that too throughly as it's worked for us with the older version of nuget libraries.

**Comment by joelverhagen** [comment]
I see a null reference exception when running your sample, as well as in your LINQPad screenshot. Is this a different situation that the exception mentioned in your original post, regarding a `InvalidOperationException`?

**Comment by nickeeex** [comment]
It's the same issue, the real exception seems to be swallowed by NuGet.Core   
at NuGet.DataServiceQueryWrapper`1.ExtractMessageFromClientException(Exception exception)
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)

**Comment by joelverhagen** [comment]
Got it, thanks! I'll investigate this issue.

**Comment by joelverhagen** [comment]
Hey @nickeeex, we've identified an issue in a recent caching change where these OData request headers were not contributing to a cache variant. We have added `MaxDataServiceVersion` to the cache variant configuration.

Could you let me know if you are still having issues?

**Comment by nickeeex** [comment]
The issue seems to be resolved. Thank you very much for the help. 

We'll start working on extending NuGet.Protocol to support using Azure Blob Container as the NuGet Repository to get rid of the deprected NuGet.Core

**Comment by joelverhagen** [comment]
Thanks for the confirmation!
