### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by hardik-2** [NuGet/NuGetGallery#9004]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Not able to connect to the project website https://webgrease.codeplex.com/. It is showing the site is unreachable. Our Governance Team need to explore the project site before consuming it NuGet .

### Repro Steps

1.Go to URL  https://webgrease.codeplex.com/
2.Check for its availability

### Expected Behavior

Site should be reachable

### Screenshots

![image](https://user-images.githubusercontent.com/99735590/154067205-2e6e0f03-4c56-429a-a7a9-b4206b3a308a.png)

**Comment by joelverhagen** [comment]
Hello @hardik-2. This GitHub repository is for the NuGet.org project itself. Our team does not support individual packages. Consider using the "Contact owners" link available on the package details page on NuGet.org. This will allow you to send a message to the package owners.
