### ISSUE TITLE
[Bug]: SearchQueryService doesnt find System.CommandLine

### ISSUE THREAD

**Issue by no1melman** [NuGet/NuGetGallery#9007]
### NuGet Product Used

Other/NA

### Product Version

https://azuresearch-usnc.nuget.org

### Impact

I'm unable to use this version

### Repro Steps & Context

```
https://azuresearch-usnc.nuget.org/query?q=system.commandline
```

neither

```
nuget search System.CommandLine
```

if you do

```
nuget search System.CommandLine -PreRelease
```
that works,

but

```
https://azuresearch-usnc.nuget.org/query?q=system.commandline&prerelease=true
```

still doesn't show anything

-- compare to --

nuget.org and search for System.CommandLine which actually shows the package

why can't these be found

**Comment by joelverhagen** [comment]
Hey @no1melman, I have not heard back from you in a week so I will close this issue. Please feel free to open a new issue if you are having further problems with the Search API.

**Comment by no1melman** [comment]
Yeaah the semver thing fixed it....
