### ISSUE TITLE
[NuGet.org ]:  Why is the download number Always 0

### ISSUE THREAD

**Issue by xuzhg** [NuGet/NuGetGallery#9012]
### Impact

Other

### Describe the bug

The download of our latest version 8.0.7 is 0 as:

![image](https://user-images.githubusercontent.com/9426627/154775237-89ea667d-cf09-4944-9f69-110c0d54a8d8.png)

What's wrong with this version? because all other versions have a download number.

### Repro Steps

Go to nuget.org, search for microsoft.aspnetcore.odata

### Expected Behavior

Should have the download number.

**Comment by joelverhagen** [comment]
Hello @Jack005566, apologies on the inconvenience. We have an ongoing issue with delayed package statistics. We have a notice on our [status page](https://status.nuget.org/).

We're in the process of ingesting old logs to catch up. Our old statistics system has reached a breaking point for log ingestion and we are in the process of moving to a new system.

> Package downloads are delayed since January 25th, 2022. Download count statistics are currently being ingested at a reduced rate. This is resulting in download counts on packages not reflecting their latest status. We apologize for the inconvenience and are actively working on a solution.

**Comment by xuzhg** [comment]
@joelverhagen Thanks for your information. 
by the way, I think you @xuzhg , not @Jack005566. :)

**Comment by joelverhagen** [comment]
Right you are! Oops!

**Comment by joelverhagen** [comment]
In order to simplify our issue tracking, I have pinned an explanation of the stats delay in this NuGet/NuGetGallery issues. I'll close this issue in lieu of that: https://github.com/NuGet/NuGetGallery/issues/9018. Please feel free to ask any follow-up questions on that issue.

**Comment by xuzhg** [comment]
@joelverhagen Thanks for the context.
