### ISSUE TITLE
[NuGet.org Bug]: Intermittent 500: https://api-v2v3search-0.nuget.org/query?

### ISSUE THREAD

**Issue by ppittle** [NuGet/NuGetGallery#9014]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Using a browser, or other http client, navigate to **https://api-v2v3search-0.nuget.org/query?q=PackageId:AWSSDK.AWSSupport&prerelease=true**

Reload the page several times.

On at least one reload, observe error message:

```
HTTP Error 500.30 - ANCM In-Process Start Failure
```

### Repro Steps

Steps to reproduce this behavior

1. Navigate to https://api-v2v3search-0.nuget.org/query?q=PackageId:AWSSDK.AWSSupport&prerelease=true
2. Refresh page several times
3. Observe page intermittently returns 500 error.

### Expected Behavior

Navigating to https://api-v2v3search-0.nuget.org/query?q=PackageId:AWSSDK.AWSSupport&prerelease=true should never return a 500 error.

### Screenshots

![image](https://user-images.githubusercontent.com/1190907/155009635-3ca8bd6c-4803-47b2-a12c-b0d625c1e537.png)

### Additional Context and logs

We have automated monitoring of our packages in NuGet that verify available version history once every 30 minutes.

We first observed a degraded experience on Feb 21st 2022 at approximately 16:10 UTC

**Comment by joelverhagen** [comment]
Hello @ppittle, thanks for taking the time to report this. Our telemetry is showing that this issue is resolved. The last failure from our monitoring was at Feb 21st 2022 at 20:06 UTC. Please let us know if you are encountering any additional problem with this endpoint.

**Comment by ppittle** [comment]
@joelverhagen thanks for the response!  Confirm service looks healthy and I'm no longer getting 500 responses to https://api-v2v3search-0.nuget.org/query?q=PackageId:AWSSDK.AWSSupport&prerelease=true.
