### ISSUE TITLE
[Service degradation] Package download counts are delayed

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#9018]
As mentioned in NuGet.org's [status page](https://status.nuget.org/):

> **Package download statistics are delayed. Download logs have been processed up to February 11th, 2022.** Download count statistics are currently being ingested at a reduced rate. This is resulting in download counts on packages not reflecting their latest status. We apologize for the inconvenience and are actively working on a solution.
>
> Our current plan forward is to accelerate our migration to a new statistics pipeline which will help us overcome the scaling issues that we have encountered.

To provide a bit more context: our team has been using a SQL-based statistics data warehouse solution which has had more and more scaling issues over the years. We have been working for several months on a new solution based on [Azure Synapse Analytics](https://azure.microsoft.com/en-us/services/synapse-analytics/) which will help us overcome the growing volume of download logs that we process.

The download logs are processed in order for use to generate various statistics reports (most notably the total download counts showing in many UI experiences). This new Synapse-based infrastructure will also allow us to more easily add new reports and statistics features in the future as well as keep up with the wonderful growth of the .NET ecosystem.

The old pipeline began to fall behind on log ingestion in mid-January before our planned migration to the new pipeline had completed. This was a surprise to us. Fortunately, our new pipeline is not far off from being ready for production usage. There were some remaining steps of hardening the monitoring as well and log reflow edge cases that we wanted complete prior turning off the old pipeline and activating the new one. To avoid investing engineering effort into the older stats pipeline (essentially throwaway work), we chose to focus our efforts on the migration to the new pipeline.

We anticipate during the next week or two (week of February 28th or March 6th) to have these final stabilization steps for the new pipeline completed and the reports produced by the new pipeline (i.e. parity with existing behavior on the old pipeline) to be activated on NuGet.org.

In the interim, you will continue to see delayed download counts as the old pipeline stoically churns to through a big pile of log files. No download counts have been lost and we anticipate the new pipeline to quickly churn through the backlog of logs at a satisfactory rate.

When the issue is resolved, we will clear the status page and close this issue.

**Comment by bgrainger** [comment]
The status page has been cleared: https://status.nuget.org/

Is this issue now resolved?

**Comment by joelverhagen** [comment]
This issue is now resolved. If you're download counts aren't behaving as expected, please feel free to open a new issue and we will investigate is separately.

Sorry for the confusion, I forgot to close this issue after clearing the status page.
