### ISSUE TITLE
[Self-hosted Bug]: Not able to get feed from server and pakage display as xml file

### ISSUE THREAD

**Issue by cpatel22** [NuGet/NuGetGallery#9034]
### Impact

I'm unable to use this version

### Describe the bug

1) not able to get feed

2) No UI display for packages list
![image](https://user-images.githubusercontent.com/7018966/156672352-ed8297b5-d522-41e4-8075-591b54dacaa0.png)

but UI display for NuGet server home page.
![image](https://user-images.githubusercontent.com/7018966/156672502-07925416-ec02-4468-a6fc-1e833d30db67.png)

### Expected Behavior

It's should be working fine and able to get my feed

**Comment by loic-sharma** [comment]
NuGet.Server does not display packages in a UI. I recommend either using a client to browser your server (like Visual Studio or [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer)), or, using a different NuGet server that does has a UI (see this list of [NuGet server implementations](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview)).

**Comment by cpatel22** [comment]
Still not able to get my feed in visual studio.

**Comment by loic-sharma** [comment]
What problems are you running into?

**Comment by joelverhagen** [comment]
Closing this issue since we don't have the information needed to diagnose the issue. @cpatel22, feel free to open a new bug with clear repro steps if you are still having trouble.
