### ISSUE TITLE
[Upload UI]: Improve experience when package has no license 

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#9037]
### Related Problem

The web UI shows a warning if you upload a package without a license:

![image](https://user-images.githubusercontent.com/737941/157503952-c57bf021-8f57-44c0-ab07-68c1d5ddd7f6.png)

Today the `Learn more` links to: https://aka.ms/deprecateLicenseUrl

This doc is for packages that provide the legacy URL but isn't ideal for brand new packages.

### The Elevator Pitch

Link to the licensing best practices instead! https://aka.ms/nuget/authoring-best-practices#licensing

**Comment by advay26** [comment]
@loic-sharma This change is now in PROD :)
