### ISSUE TITLE
[Self-hosted Bug]: NuGet.Server can not receive microsoft.xmlserializer.generator.6.0.0.nupkg

### ISSUE THREAD

**Issue by TiltonJH** [NuGet/NuGetGallery#9054]
### Impact

I'm unable to use this version

### Describe the bug

Hi,

we internally use a [NuGet.Server 3.4.1](https://github.com/NuGet/NuGet.Server) for our own as well as all third party nugets.

We can not push or otherwise publish `microsoft.xmlserializer.generator.6.0.0.nupkg` downloaded from [nuget.org](https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/) to our NuGet.Server.

On pushing we get a `System.Net.Http.HttpRequestException: Response status code does not indicate success: 406 (Not Acceptable).` error message.

If I put in the directory of the NuGet.Server I get `Part URI cannot start with two forward slashes.`.

So I took a look inside to figure out from where this might come from and found the `[Content_Types].xml` contains this line `<Override PartName="//prefercliruntime" ContentType="application/octet" />`. Removing one of the `/` at the beginning of `PartName` fixed my publish problem.

However now the package signature doesn't match anymore.

So my first question is: Who is to blame? Is NuGet.Server faulty or not tolerant enough? Or is nuget.org not strict enough?
Which leads to the second question: Is the package actually faulty? I mean, clearly something is odd here.

BTW: The 5.0.0 package does not have that issue. It only uses one `/`.

See also [microsoft.xmlserializer.generator.6.0.0.nupkg fails to upload to nuget.server · Issue #66584 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/issues/66584)

### Repro Steps

Try pushing `microsoft.xmlserializer.generator.6.0.0.nupkg` downloaded from [nuget.org](https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/) to a NuGet.Server.

### Expected Behavior

The push succeeds.

**Comment by joelverhagen** [comment]
I think at this point NuGet.Server is being stricter than it needs to be. I don't have the data, but I wager than many dozens of packages have this problem on NuGet.org therefore the "ship has sailed" on whether clients and server need to be tolerant of this. Therefore, the path forward would be to fix NuGet.Server to be more tolerant of this problem. More generally, the OPC files (of which `[Content_Types].xml` are not validated by newer versions of NuGet client (3.x and beyond I think) so there is a whole category of problems related to corrupt OPC where I think NuGet.Server would fall over.

If this is a fix you're interested in resolving, consider opening a PR against the [NuGet/NuGet.Server](https://github.com/NuGet/NuGet.Server) repo.

Alternatively, you can try a different package feed implementation:
https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

**Comment by TiltonJH** [comment]
Thank you for pointing to the alternatives. I will take a look at those. Maybe even change to a .NET Core/5/6 based server while I am at it. :)

I will also consider fixing the NuGet.Server. I am wondering, has the NuGet.Server been abandoned? It seems to be awfully quiet around it for a while now. If so, is there en official successor in the works?

What I still don't quite get, is how the package did get that corrupt `[Content_Types].xml` file in the first place. I assume no one builds those by "hand", but all get generated somehow. This package is so far the only one with that kind of issue we came across. For the same reasoning, I don't get why there would be any corrupt OPC files within a generated `.nupkg` as you pointed out. Seems to me like I am missing something. Perhaps I need to open a bug with dotnet, msbuild or nuget.exe.

**Comment by TiltonJH** [comment]
> NuGet.Server is not abandoned, per se. Security issues would be considered and we still accept PRs. In general, new changes are not made to regularly it for two reasons:

So mainly maintenance work, good to know. Would be nice if the `[README.md](https://github.com/NuGet/NuGet.Server#readme)` or some other project page would reflect that.

> 1. It implements the NuGet V2 protocol. New features are not added to V2 because we have a V3 protocol which we encourage all package consumers to use.

So NuGet.Server nor NuGet/NuGetGallery uses V3? I would have thought that those would be the first adopters. Well, in that case, I will most likely take a look at the other OOS offerings.

> From my many years of experience on NuGet team, I can tell you confidently that there is a lot of "hand crafted" NuGet packages, i.e. folks that either create the package without any official tooling at all, or use unofficial tooling, or even post-process packages with ZIP and XML APIs. I can't guess how this particular problem happened.

Turns out that was the case here as well. However, the handcrafted one got replaced by the built in nuget pack task.  (https://github.com/dotnet/runtime/issues/66584)

Luckily, there seems to be a workaround in the works, as well a bug tracking issue (https://github.com/NuGet/Home/issues/9097).

So will go ahead and consider this issue closed.
