### ISSUE TITLE
[Feature]:  Query sorting problem

### ISSUE THREAD

**Issue by donet5** [NuGet/NuGetGallery#9057]
### Related Problem

Such as
https://www.nuget.org/packages?q=sqlsugar  

Hopefully, that's what the search will bring up
SqlSugar
SqlSugarCore

But SQLSugarcore won't be on the first page at all

### The Elevator Pitch

Such as
https://www.nuget.org/packages?q=sqlsugar  

Hopefully, that's what the search will bring up
SqlSugar
SqlSugarCore

But SQLSugarcore won't be on the first page at all

### Additional Context and Details

Such as
https://www.nuget.org/packages?q=sqlsugar  

Hopefully, that's what the search will bring up
SqlSugar
SqlSugarCore

But SQLSugarcore won't be on the first page at all

**Comment by loic-sharma** [comment]
Hello, thank you for opening this issue. For now, I recommend you either keep your package's name as `SqlSugarCore`, or, add tags to your package like `sqlsugar`.

It looks like you're running into two problems:

* Search does not tokenize initialisms like `SQLSugar` into `SQL` and `sugar` yet. This work is tracked by https://github.com/NuGet/NuGetGallery/issues/6964
* Search does tokenize things like `Sugarcore` into `sugar` and `core`. This can be improved by shingling: https://github.com/NuGet/NuGetGallery/issues/7390

Please consider upvoting the linked issues to help prioritize improvements!

**Comment by donet5** [comment]
Where do I add tags?



This is how I pack
<?xml version="1.0"?>
<package >
  <metadata>
    <id>SqlSugarCore</id>
    <version>5.0.5.9</version>
    <authors>sunkaixuan</authors>
    <owners>Landa</owners>
    <licenseUrl>http://www.apache.org/licenses/LICENSE-2.0.html</licenseUrl>
    <projectUrl>https://github.com/sunkaixuan/SqlSugar</projectUrl>
    <iconUrl>https://secure.gravatar.com/avatar/a82c03402497b2e58fd65038a3699b30</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>5.0.3.5-Max 最低要求.Net Core 3.0+   ，5.0.0-5.0.3.4 最低要求 .Net Core 2.0+  SqlSugar ORM ,High-performance, lightweight </description>
    <copyright>Copyright 2016</copyright>
    <tags>Asp.net core orm</tags>
    <dependencies>
      <group targetFramework=".NETStandard2.1">
        <dependency id="System.Data.Common" version="4.3.0" />
        <dependency id="Microsoft.Data.SqlClient" version="2.1.1" />
        <dependency id="Newtonsoft.Json" version="10.0.3" />
        <dependency id="Microsoft.Data.Sqlite" version="5.0.5" />
        <dependency id="System.Reflection.Emit.Lightweight" version="4.3.0" />
        <dependency id="MySql.Data" version="8.0.21" />
        <dependency id="Oracle.ManagedDataAccess.Core" version="3.21.1" />
        <dependency id="Npgsql" version="5.0.7" />
	    <dependency id="SqlSugarCore.Dm" version="1.0.0" />
	    <dependency id="SqlSugarCore.Kdbndp" version="1.0.0" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="C:\NugetCore\SqlSugar.dll" target="lib\netstandard2.1"></file>
  </files>
</package>

**Comment by donet5** [comment]
There's a tag like this in description but it doesn't work

**Comment by donet5** [comment]
That's fine. Thank you.
