### ISSUE TITLE
[NuGet.org Bug]: The border can be thinner when clicking a link

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#9072]
### Impact

It bothers me. A fix would be nice

### Describe the bug

When clicking the link in nuget.org, it shows a wide border and sometimes covers the link text.
Will it be better to make the border thinner?

### Repro Steps

1. Go to nuget.org;
2. Click any link and you will see a wide border.

### Expected Behavior

 A thinner border will be better.

### Screenshots

![image](https://user-images.githubusercontent.com/41028779/159977880-dde1ca6c-0b84-43ce-9986-c704211bd00f.png)

**Comment by MRmlik12** [comment]
I can handle with this pr

**Comment by MRmlik12** [comment]
On Firefox the border doesn't appear. Should I remove bordering for chrome or add support for Firefox?
![image](https://user-images.githubusercontent.com/44818681/194377396-ce9edc8c-6e2e-4bb6-a8d1-8fb1be340694.png)

**Comment by zhhyu** [comment]
@advay26 Could you help us and support @MRmlik12 on this issue? Thanks!

**Comment by advay26** [comment]
@MRmlik12 I think we should add boxes to the Firefox experience too. If you try navigating the different elements on that page on Firefox by clicking 'Tab', these elements (Package ID, owners, tags) do have boxes around them in that case, it's just when we click on the links that they don't show the boxes.
![image](https://user-images.githubusercontent.com/82980589/194425279-a2c6f4bd-0518-4355-ba68-090fd361ea4d.png)
![image](https://user-images.githubusercontent.com/82980589/194425313-028d1479-6bca-4399-93e9-7ff38a2018d5.png)

I think we could try fixing this by:
1. Using thinner lines for the boxes (the line thickness on Firefox looks good to me, but Edge needs fixing)
2. Making the boxes slightly larger (especially around the Package ID, owners and tags) so they don't cover the text
3. Making sure the behavior is similar across different browsers (Edge, Firefox, Safari)
4. Running Accessibility FastPass to identify any common accessibility problems that come up https://accessibilityinsights.io/docs/web/getstarted/fastpass/

Let me know if you have any questions or need any help! You can also take a look at [CONTRIBUTING.md](https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md) for help on contributing to NuGetGallery.

**Comment by MRmlik12** [comment]
![packages](https://user-images.githubusercontent.com/44818681/194706009-e0fb15af-b1b6-44a6-9b1e-46a5d0bdf986.png)
![package-info](https://user-images.githubusercontent.com/44818681/194706036-edc75bb6-213a-4f5b-ab70-f79cc5c3a01f.png)

It's be ok?

**Comment by advay26** [comment]
@MRmlik12 Yes, this looks great!

You can follow the instructions here to create a PR with your changes: https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md#getting-started.
