### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by ShreeShivaTejaJuluri** [NuGet/NuGetGallery#9084]
### Impact

It bothers me. A fix would be nice

### Describe the bug

When trying to convert CloudStorageAccount from Microsoft.Azure.Storage.CloudStorageAccount to Microsoft.WindowsAzure.Storage.CloudStorageAccount based on storage credentials for emulator based accounts, we are seeing the following error when trying to access it _The remote server returned an error: (403) Forbidden._ 

### Repro Steps

Let Microsoft.Azure.Storage.CloudStorageAccount acc be an emulator based cloudstorageaccount. 

using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
StorageCredentials cred =
new StorageCredentials(acc.Credentials.AccountName, acc.Credentials.ExportKey());
CloudStorageAccount storageAccount = new CloudStorageAccount(cred, true);
var blobClient = storageAccount.CreateCloudBlobClient();
var v = blobClient.ListContainers();
var t = storageAccount.CreateCloudTableClient().ListTables();

The variable 't' is giving 403 exception when trying to access it.

### Expected Behavior

For non-emulator accounts, the cloudstorageaccount conversion is fine and we are able to access the cloudstorageaccount. We expect the same behaviour for emulator based accounts also without any 403 exceptions.

**Comment by joelverhagen** [comment]
Hello, this looks like a question about a specific package on NuGet.org. This GitHub repository is about www.nuget.org itself. This team does not provide support for individual packages. Please consider reaching out to the package owner about this problem.
