### ISSUE TITLE
[Bug]: Many SPDX license Expressions not resolved by https://licenses.nuget.org/ instead "We have no information regarding the 'Xyz' license."

### ISSUE THREAD

**Issue by SpocWeb** [NuGet/NuGetGallery#9097]
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI

### Product Version

dotnet 

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. create a Visual Studio Project Nuget Package with an SPDX Expression e.g. <PackageLicenseExpression>Hippocratic-2.1</PackageLicenseExpression>
2. build, pack and push the Package using an Azure pipeline 
3. Visit the Package Feed / Artifact Page in Azure 
4. Search for the new Package 
5. Click the Project License Link in the bottom right Corner which links to https://licenses.nuget.org/Hippocratic-2.1 
6. Get an Error Message: We have no information regarding the 'Hippocratic-2.1' license. 

The https://spdx.org/licenses/ Page lists many licenses, 
but it seems only a few work, e.g. MIT, MIT-0, LGPL-2.0-only and MPL-1.0 

Many Licenses listed on https://spdx.org/licenses/  don't work and the link https://licenses.nuget.org/Hippocratic-2.1 displays a page with an error message reading "We have no information regarding the 'Hippocratic-2.1' license."

I understand that maintaining the full List is a lot of work, but it would be good to at least 
* include a Link to the SPDX License https://spdx.org/licenses/Hippocratic-2.1.html 
* or a Link the List https://spdx.org/licenses/ 
in the Message when it cannot be found on https://licenses.nuget.org  

Best Regards...

### Verbose Logs

```shell
https://licenses.nuget.org/Hippocratic-2.1 does not link to or mirror 
https://spdx.org/licenses/Hippocratic-2.1
```

**Comment by SpocWeb** [comment]
I'll start right away. Luckily it's in C#

**Comment by agr** [comment]
All deployments are finished, and the update is fully rolled out. https://licenses.nuget.org/Hippocratic-2.1 now produces updated response.

Thank you for your contribution!
