### ISSUE TITLE
[NuGet.org Bug]: Missing Laserfiche 10.0.0 package

### ISSUE THREAD

**Issue by aptivadave** [NuGet/NuGetGallery#9100]
### Impact

It's more difficult to complete my work

### Describe the bug

We're getting build errors that point to the LaserFiche 10.0.0 package missing from nuget.org.  This package was active on Monday, April 18th at 8:39 AM CST, which was the last time a successful build for our project ran in Azure DevOps.  Can we get this package restored so that we can finish our build for this legacy application until we have a chance to upgrade the functionality that depends on this package?

### Repro Steps

Search for package named "LaserFiche 10.0.0" and view that no results come back.

### Expected Behavior

Package should be available

### Screenshots

![image](https://user-images.githubusercontent.com/15343115/164252515-630262ea-2e11-4366-9f0c-883d931d8b43.png)

**Comment by joelverhagen** [comment]
Hello, this package was deleted due to a policy violation. We contacted the package owner as part of our standard process and the package is no longer available on NuGet.org.

If you are the owner of the package and have further questions, please reach out to our support team using this form:
https://www.nuget.org/policies/Contact (sign in to access the contact form)

**Comment by aptivadave** [comment]
Is there an ETA as to when the package owner will have the issue resolve?

Yakoke,
David Coxsey | Choctaw Nation of Oklahoma<http://www.choctawnation.com/> | Yvnnvsh (Bison) Team Lead | Information Technology
***@***.******@***.***> | Phone: (800) 522-6170 | Fax: (580) 924-2165
[Faith, Family Culture]

**Comment by joelverhagen** [comment]
There is no ETA for restoring the package. It was deleted for policy violations. Consider seeking out an alternative package or reaching out to Laserfiche for recommendations on how to interact with their API.
