### ISSUE TITLE
[NuGet.org Bug]: flatcontainer api always returns BlobNotFound despite package name used to get the list of all versions listed being on nuget.org.

### ISSUE THREAD

**Issue by AraHaan** [NuGet/NuGetGallery#9105]
### Impact

It's more difficult to complete my work

### Describe the bug

Let's say for example you use this to query the API's manually using HttpClient: ``https://api.nuget.org/v3-flatcontainer/{packageName}/index.json``

Try with the following values: ``Elskom.SDK``, ``Elskom.Sdk.App``, and ``Elskom.Sdk.App.Ref``.

### Repro Steps

Steps to reproduce:
1. I also verified on my code that ``packageName`` never ends with an ``.``.
2. Attempt to try the above values directly in browser.
3. Notice that all 3 packages returns 404 or ``BlobNotFound``. Also when you visit ``https://api.nuget.org/v3-flatcontainer/`` it also returns ``BlobNotFound``.
4. Type in the package names into nuget.org and notice that they are found, but not with api.nuger.org's flatcontainer.

### Expected Behavior

For it to always return the json response which contains all of the versions of the packages that are listed on nuget.org.

### Screenshots

![image](https://user-images.githubusercontent.com/15173749/164376687-ee9ccbf1-dbce-44c4-bf08-26745ea3b5d8.png)
![image](https://user-images.githubusercontent.com/15173749/164376729-0361413d-f825-434c-9bd7-da0900261e19.png)
![image](https://user-images.githubusercontent.com/15173749/164376760-15a2452c-bfda-4028-a0e0-cccd15e6f7d4.png)
![image](https://user-images.githubusercontent.com/15173749/164376877-0e565ea6-ec66-4ada-8551-3a3d6adbc471.png)
![image](https://user-images.githubusercontent.com/15173749/164376920-cfa5d01d-156d-4797-9949-61d9b556b342.png)
![image](https://user-images.githubusercontent.com/15173749/164376939-8fb88c93-5abf-4003-a285-0a680e6d581c.png)

**Comment by kant2002** [comment]
You should lower case package name in the URL

**Comment by joelverhagen** [comment]
Precisely correct @kant2002! Please take a look at the API documentation for the endpoint:
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource

The ID component must be lowercase and any version component (e.g. for the .nupkg) must be lowercased and normalized using standard NuGet version normalization rules.

If you are downloading or listing packages in a custom way, consider using the NuGet client SDK:
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

If you need to write the HTTP requests yourself, please consider using a descriptive user agent!
