### ISSUE TITLE
[WIKI TYPO] Typo in "Branding the NuGet Gallery"

### ISSUE THREAD

**Issue by mickgarland** [NuGet/NuGetGallery#9113]
Hi,

There is a typo in the "Branding the NuGet Gallery" wiki.

In the [Clone The Gallery](https://github.com/NuGet/NuGetGallery/wiki/Branding-the-NuGet-Gallery#clone-the-gallery) section in point 3 you are missing a "h" in the URL, the URL is https://gitub.com/NuGet/NuGetGallery.git but should be https://github.com/NuGet/NuGetGallery.git

Cheers

**Comment by joelverhagen** [comment]
Fixed! Thank you!
