### ISSUE TITLE
Multiple certificates in your server nodes, one untrusted?

### ISSUE THREAD

**Issue by mattkosmach** [NuGet/NuGetGallery#9115]
Hello,

First of all, love nuget. 
Second, 

I'm having trouble accessing nuget via Visual Studio (and also via Chrome). 
Sometimes it works, sometimes it doesn't.
I'm accessing [v3/index.json](https://api.nuget.org/v3/index.json) to be precise.

Is it possible you have two (multiple) server nodes, where one is using server certificate which is created by untrusted signer?
Whenever I get response from server, where certificate path is "*.nuget.org -> Microsoft Azure TLS Issuing CA 05 -> DigiCert Global Root G2", everything is working just fine, but if I get response from other server, I get "Untrusted issuer error".

Seems like you've replaced certificates on 27.4.2022, maybe you forgot to do it for one of the nodes?

Or maybe there is problem with my organization's network or local machine ...

Best regards,
Matt

**Comment by joelverhagen** [comment]
Hello @mattkosmach, glad to hear you love NuGet. Me too :). It's encouraging to hear this from our users!

If you're comfortable with it, could you provide the country in which you are performing the NuGet operations? Currently this defines which CDN provider you interact with.

Also, could you run this command in PowerShell and provide the output? `Resolve-DnsName api.nuget.org`. For reference, my output looks like this:
<details>

    PS C:\z> Resolve-DnsName api.nuget.org

    Name                           Type   TTL   Section    NameHost
    ----                           ----   ---   -------    --------
    api.nuget.org                  CNAME  4     Answer     nugetapiprod.trafficmanager.net
    nugetapiprod.trafficmanager.ne CNAME  4     Answer     apiprod-mscdn.azureedge.net
    t
    apiprod-mscdn.azureedge.net    CNAME  4     Answer     apiprod-mscdn.afd.azureedge.net
    apiprod-mscdn.afd.azureedge.ne CNAME  4     Answer     star-azureedge-prod.trafficmanager.net
    t
    star-azureedge-prod.trafficman CNAME  4     Answer     dual.part-0041.t-0009.t-msedge.net
    ager.net
    dual.part-0041.t-0009.t-msedge CNAME  4     Answer     part-0041.t-0009.t-msedge.net
    .net

    Name       : part-0041.t-0009.t-msedge.net
    QueryType  : AAAA
    TTL        : 222
    Section    : Answer
    IP6Address : 2620:1ec:46::69


    Name       : part-0041.t-0009.t-msedge.net
    QueryType  : AAAA
    TTL        : 222
    Section    : Answer
    IP6Address : 2620:1ec:bdf::69


    Name       : part-0041.t-0009.t-msedge.net
    QueryType  : A
    TTL        : 211
    Section    : Answer
    IP4Address : 13.107.246.69


    Name       : part-0041.t-0009.t-msedge.net
    QueryType  : A
    TTL        : 211
    Section    : Answer
    IP4Address : 13.107.213.69

</details>

It's not expected to have any "Untrusted issuer" error. In fact, the root CA and intermediate CA for our SSL certificate was the same for both before and after the certificate rotation that performed around April 27th.

If you have Git Bash installed or some other distribution of `openssl`, could you also run this command and provide the output?

`"" | openssl s_client -showcerts -servername api.nuget.org -connect api.nuget.org:443`

(note that the `"" |` part of the command is needed on my machine to make the command terminate. I think my build is expecting something from stdin. You may not need it.)

For reference, my output looks like this:
<details>

    bash: : command not found
    CONNECTED(00000194)
    ---
    Certificate chain
    0 s:C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
    i:C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
    -----BEGIN CERTIFICATE-----
    MIIIVTCCBj2gAwIBAgITMwA5aK1RzdXyPE86jQAAADlorTANBgkqhkiG9w0BAQwF
    ADBZMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
    MSowKAYDVQQDEyFNaWNyb3NvZnQgQXp1cmUgVExTIElzc3VpbmcgQ0EgMDUwHhcN
    MjIwNDI3MDExNzIyWhcNMjMwNDIyMDExNzIyWjBiMQswCQYDVQQGEwJVUzELMAkG
    A1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
    b3Jwb3JhdGlvbjEUMBIGA1UEAwwLKi5udWdldC5vcmcwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCzabzPMveLdXN6u3QiaAEAgrwJ/9PPzyhvZhUEVw3u
    HkghnnD+3qtsShII+9qdW5WQVAbTudpbU7BelUH/EGNwJuDPsBt3pZMprr3k4JPz
    opXZlJGPkQ9aaMcyoTTo2MGbZAknsk3ywqxdZASuKiw2eUNhBO3cco21DfFpAcIf
    x2xr7FiEHQa040DVY0C3twMJsl0c5ff07J9BjfrNRWRF358VmAA0fTJyh9e7Qphh
    TtHqQlKvnRT23yaijBFiOBJ7jz3xBC1eSo8XTWmsEO0+NnUVuVO578GsW+JoX27Q
    4cRk3/ImKGrLAa0u3mhHDhOgO1fcnatCz4DnamtSq6XZAgMBAAGjggQLMIIEBzCC
    AX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHUArfe++nz/EMiLnT2cHj4YarRnKV3P
    sQwkyoWGNOvcgooAAAGAaKFO+QAABAMARjBEAiA/MRCjIbRRCKpsAuGW9dRq++FD
    KzzW/hjiy58lPpACwAIgLLs4tJLaFFhx+7kPH6Ng90ns1EbAykUM1ndZSQDlcBcA
    dgCzc3cH4YRQ+GOG1gWp3BEJSnktsWcMC4fc8AMOeTalmgAAAYBooU9wAAAEAwBH
    MEUCIQCD7usie1Xlcx0KKTEsNZ6vdnUlFV6YtM3ThgcIkz4ybQIgbCfwU+z4mC5M
    3xpFOaHXXoRh33oYq6d74bqcp4Xve5YAdgB6MoxU2LcttiDqOOBSHumEFnAyE4VN
    O9IrwTpXo1LrUgAAAYBooU9FAAAEAwBHMEUCIEeHTDww6Zbv/ZAGIHP5fgljrMB+
    AAukWjH0EU3cIRdwAiEA+/dWk0zCkwLLOIVNzT8h9p3RdHuVLHabdMuCOduSWrUw
    JwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDATA8BgkrBgEE
    AYI3FQcELzAtBiUrBgEEAYI3FQiHvdcbgefrRoKBnS6O0AyH8NodXYKE5WmC86c+
    AgFkAgElMIGuBggrBgEFBQcBAQSBoTCBnjBtBggrBgEFBQcwAoZhaHR0cDovL3d3
    dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBBenVyZSUy
    MFRMUyUyMElzc3VpbmclMjBDQSUyMDA1JTIwLSUyMHhzaWduLmNydDAtBggrBgEF
    BQcwAYYhaHR0cDovL29uZW9jc3AubWljcm9zb2Z0LmNvbS9vY3NwMB0GA1UdDgQW
    BBTubgFf7UnUg1fKfyLxgtglfZPmXTAOBgNVHQ8BAf8EBAMCBLAwIQYDVR0RBBow
    GIILKi5udWdldC5vcmeCCW51Z2V0Lm9yZzAMBgNVHRMBAf8EAjAAMGQGA1UdHwRd
    MFswWaBXoFWGU2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01p
    Y3Jvc29mdCUyMEF6dXJlJTIwVExTJTIwSXNzdWluZyUyMENBJTIwMDUuY3JsMGYG
    A1UdIARfMF0wUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93
    d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTAIBgZn
    gQwBAgIwHwYDVR0jBBgwFoAUx7KcfxzjuFrv6WgaqF2UwSZSamgwHQYDVR0lBBYw
    FAYIKwYBBQUHAwIGCCsGAQUFBwMBMA0GCSqGSIb3DQEBDAUAA4ICAQA1bHvTBkWx
    VGkPTCqL5FXNGUCkKaSEy3Mlv9lcRzuqVcHy8bDsIIDHOIjgyuhTUS4aDrC+Urnv
    wx+NY8lmAL5+JARC5BN6b9clLVQINH7Gzob/9PqwHzkY6p4r2aSrRfbE8XjSP0o4
    EPkTTCE++VBtNGeCCcsjgfuYXSMWwgg0+4apcO2UZI0KQut96CC+T+vElPIo49gn
    +uUAAMWuxE9K75AJ5kJ/ZzZs1SfATPMBQYHnl8feU8XwEMimm43Fm6Hja5KXrkJI
    owfJyTk656Zc1VPFI0avsiBYUQVZwgWQOso6nyRwlRnHdUUTeMetWMU+VvzoXucw
    lxq1IUeFMTcTg+6NsWaBTbdu8sMUErGnJPk2OY/4AeRG2mU7r1QkSraFEdVJiGtY
    Rt8ObyBI5sfwTOo+rRuDHQHJcCD1i5/Qx8AyEDKqmyg/9ReJwBh5fueiSNzMe+OS
    Sdtnfxde/AUMzBGgFfRVnBHUwghB7fPQMVOiY2zsBOcqQvRac9qud2ErL//k0D64
    7pTqWiF8O0wdw/Eekd2QEXiWds6Uy8iCJuPFWbSGQazcyAQRQcQpLroSO0ahqbe3
    n1du9gLF9SZuSX0VStEPqNTuo+tIW4viOh+N6APlSycm9UuTZkhDktJfn2i3whi1
    vO1LsZyKl5cpLv/jUajWTYrVMXUbLG3HmQ==
    -----END CERTIFICATE-----
    1 s:C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
    i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
    -----BEGIN CERTIFICATE-----
    MIIF8zCCBNugAwIBAgIQDXvt6X2CCZZ6UmMbi90YvTANBgkqhkiG9w0BAQwFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
    MjAeFw0yMDA3MjkxMjMwMDBaFw0yNDA2MjcyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
    MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKjAoBgNVBAMTIU1pY3Jv
    c29mdCBBenVyZSBUTFMgSXNzdWluZyBDQSAwNTCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAKplDTmQ9afwVPQelDuu+NkxNJ084CNKnrZ21ABewE+UU4GK
    DnwygZdK6agNSMs5UochUEDzz9CpdV5tdPzL14O/GeE2gO5/aUFTUMG9c6neyxk5
    tq1WdKsPkitPws6V8MWa5d1L/y4RFhZHUsgxxUySlYlGpNcHhhsyr7EvFecZGA1M
    fsitAWVp6hiWANkWKINfRcdt3Z2A23hmMH9MRSGBccHiPuzwrVsSmLwvt3WlRDgO
    bJkE40tFYvJ6GXAQiaGHCIWSVObgO3zj6xkdbEFMmJ/zr2Wet5KEcUDtUBhA4dUU
    oaPVz69u46V56Vscy3lXu1Ylsk84j5lUPLdsAxtultP4OPQoOTpnY8kxWkH6kgO5
    gTKE3HRvoVIjU4xJ0JQ746zy/8GdQA36SaNiz4U3u10zFZg2Rkv2dL1Lv58EXL02
    r5q5B/nhVH/M1joTvpRvaeEpAJhkIA9NkpvbGEpSdcA0OrtOOeGtrsiOyMBYkjpB
    5nw0cJY1QHOr3nIvJ2OnY+OKJbDSrhFqWsk8/1q6Z1WNvONz7te1pAtHerdPi5pC
    HeiXCNpv+fadwP0k8czaf2Vs19nYsgWn5uIyLQL8EehdBzCbOKJy9sl86S4Fqe4H
    GyAtmqGlaWOsq2A6O/paMi3BSmWTDbgPLCPBbPte/bsuAEF4ajkPEES3GHP9AgMB
    AAGjggGtMIIBqTAdBgNVHQ4EFgQUx7KcfxzjuFrv6WgaqF2UwSZSamgwHwYDVR0j
    BBgwFoAUTiJUIBiV5uNu5g/6+rkS7QYXjzkwDgYDVR0PAQH/BAQDAgGGMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMHYG
    CCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQu
    Y29tMEAGCCsGAQUFBzAChjRodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGln
    aUNlcnRHbG9iYWxSb290RzIuY3J0MHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6Ly9j
    cmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RHMi5jcmwwN6A1oDOG
    MWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RHMi5j
    cmwwHQYDVR0gBBYwFDAIBgZngQwBAgEwCAYGZ4EMAQICMBAGCSsGAQQBgjcVAQQD
    AgEAMA0GCSqGSIb3DQEBDAUAA4IBAQAe+G+G2RFdWtYxLIKMR5H/aVNFjNP7Jdeu
    +oZaKaIu7U3NidykFr994jSxMBMV768ukJ5/hLSKsuj/SLjmAfwRAZ+w0RGqi/kO
    vPYUlBr/sKOwr3tVkg9ccZBebnBVG+DLKTp2Ox0+jYBCPxla5FO252qpk7/6wt8S
    Zk3diSU12Jm7if/jjkhkGB/e8UdfrKoLytDvqVeiwPA5FPzqKoSqN75byLjsIKJE
    dNi07SY45hN/RUnsmIoAf93qlaHR/SJWVRhrWt3JmeoBJ2RDK492zF6TGu1moh4a
    E6e00YkwTPWreuwvaLB220vWmtgZPs+DSIb2d9hPBdCJgvcho1c7
    -----END CERTIFICATE-----
    ---
    Server certificate
    subject=C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org

    issuer=C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05

    ---
    No client certificate CA names sent
    Peer signing digest: SHA256
    Peer signature type: RSA-PSS
    Server Temp Key: ECDH, P-384, 384 bits
    ---
    SSL handshake has read 4486 bytes and written 473 bytes
    Verification: OK
    ---
    New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384
        Session-ID: 653AA1AD1F86F2B20A60823D3207E6F316C4900FDEB1099C6E7A5DC8F2138073
        Session-ID-ctx:
        Master-Key: D6D5066BD8A74FAE467DF979AF12D92DB61447823D4F6153BA59582E31AA6FD4D7162E03C29FDB04E51064ACD187BF9A
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        TLS session ticket lifetime hint: 36000 (seconds)
        TLS session ticket:
        0000 - 00 00 00 00 1c 8c 78 1b-01 7b d9 46 94 d5 f3 f3   ......x..{.F....
        0010 - 07 99 c5 51 f2 0d f1 06-c5 c7 86 96 69 80 46 92   ...Q........i.F.
        0020 - 4c 86 61 95 27 da 30 ed-21 42 bf ce 38 45 46 fc   L.a.'.0.!B..8EF.
        0030 - 31 d7 bd c2 d3 4e 5f 9d-8b 99 c9 18 0c 0d fc 2c   1....N_........,
        0040 - 45 5f 1e c2 87 7f 49 01-71 94 9a 6c 7a 26 fd 9b   E_....I.q..lz&..
        0050 - 9b 8c b8 48 2e f6 e6 68-35 f9 89 d1 cc 08 72 30   ...H...h5.....r0
        0060 - 2b 76 a2 e8 83 c4 a1 de-63 5e f8 18 ee 83 c5 2d   +v......c^.....-
        0070 - 65 5e 06 13 86 d1 76 dd-b7 4d 1b 2c 8a c9 59 22   e^....v..M.,..Y"
        0080 - 11 06 9a d3 87 b9 52 66-1c 9b bc 3a 30 d7 c2 4f   ......Rf...:0..O
        0090 - ad 24 89 09 38 91 4f 06-45 3a a1 dd 65 61 b1 f0   .$..8.O.E:..ea..
        00a0 - 61 ed 33 76 70 b6 d2 ee-95 86 7b dd dc 81 b2 f0   a.3vp.....{.....
        00b0 - 14 03 ce db a9 7e 7f fb-22 1f ac c1 4d 48 04 8d   .....~.."...MH..
        00c0 - 4b 0a c5 23 b6 eb df 54-f3 77 7a 51 f0 d4 0d f2   K..#...T.wzQ....
        00d0 - 82 19 d1 92 12 10 cd 4f-fc 9e 43 eb 98 b5 31 a8   .......O..C...1.
        00e0 - ca fc 22 33 ff ce 2e ef-3d 1e 13 1d 54 92 bd 11   .."3....=...T...
        00f0 - b9 4b c9 cb c8 08 28 50-96 f0 a8 3a b4 ed 91 25   .K....(P...:...%
        0100 - 5b 04 e2 51 7b 3d b8 e9-da 59 81 fe a9 08 52 b7   [..Q{=...Y....R.
        0110 - 30 e8 80 79                                       0..y

        Start Time: 1652291346
        Timeout   : 7200 (sec)
        Verify return code: 0 (ok)
        Extended master secret: yes
    ---
    depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
    verify return:1
    depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
    verify return:1
    depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
    verify return:1
    DONE
</details>

**Comment by mattkosmach** [comment]
Thank you for quick response. Below is the output.

**ping api.nuget.org**
Pinging part-0032.t-0009.fbs1-t-msedge.net [13.107.219.60] with 32 bytes of data:
Reply from 13.107.219.60: bytes=32 time=20ms TTL=112

**"" | openssl s_client -showcerts -servername api.nuget.org -connect api.nuget.org:443**
bash: : command not found
CONNECTED(0000036C)
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
verify return:1
---
Certificate chain
 0 s:C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org
   i:CN = Untrusted
-----BEGIN CERTIFICATE-----
MIIClzCCAYGgAwIBAgIUHbrViT08wvZhSFlaGogvSRVheewwCwYJKoZIhvcNAQEM
MBQxEjAQBgNVBAMTCVVudHJ1c3RlZDAeFw0yMjA0MjcwMTE3MjJaFw0yMzA0MjIw
MTE3MjJaMGIxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHUmVk
bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRQwEgYDVQQDDAsq
Lm51Z2V0Lm9yZzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMoAd5foOBmZRDnZ
ECW0NGIiGFOgUgTUH1iqONh6FUJwG03ziOh8NkIIZnZQpAWn1p3xeqa+U1EX/mxK
JKS+jO+jYjBgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAhBgNVHREE
GjAYggsqLm51Z2V0Lm9yZ4IJbnVnZXQub3JnMA4GA1UdDwEB/wQEAwIFoDAMBgNV
HRMBAf8EAjAAMAsGCSqGSIb3DQEBDAOCAQEAPhcdDUvgrUX6MQrMsWROVzM7ecGF
jQIs6VHUtkqdNOGxGxv+isKEhANkpBnpMLYlfZ7jC8Dtwxc3FSiAMt1DSXdHSdE4
EDXQwNnAquA9PYFLA28pqjPdH0RGfIxcJgCv21IRCSJ+PC32uz2iczryBxtbmaBZ
SYzjJFTXHvbtaCUrWHXc1+TvVin++MaXENQCOmTdJiqORq10ky2jDMOZ+J6ub+cp
NS/I1/INjUlI5qTs0krBsSK1A8gcGcNJsTaqAxFHh7eXe9/n9mE3g/e2TQ0zcOVw
h7FQ6O+T4Drr4vRebn50d3QmDS9dDL4pXf2dk/9oGEMDA7t8GcDdv4IbyQ==
-----END CERTIFICATE-----
---
Server certificate
subject=C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.nuget.org

issuer=CN = Untrusted

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 971 bytes and written 441 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES128-GCM-SHA256
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES128-GCM-SHA256
    Session-ID: BD3529A0032779FD34A6A3152307BD466B59400FD4CA65E469B3E09A7F2AF2EB
    Session-ID-ctx:
    Master-Key: 2D47D3DE5ED31001AA20C28CEDDB260ED81F5B1919592319DDE8D666216A6B1111D9BE40D75E1F1E53EE0029
71AE6300
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1652360846
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
---
DONE

**Comment by joelverhagen** [comment]
Based on this line:
```
issuer=CN = Untrusted
```
This is very strange. It looks like issuer name is actually the string `CN = Untrusted`.

I decoded the ASN.1 ([example](https://lapo.it/asn1js/#MIIClzCCAYGgAwIBAgIUHbrViT08wvZhSFlaGogvSRVheewwCwYJKoZIhvcNAQEMMBQxEjAQBgNVBAMTCVVudHJ1c3RlZDAeFw0yMjA0MjcwMTE3MjJaFw0yMzA0MjIwMTE3MjJaMGIxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRQwEgYDVQQDDAsqLm51Z2V0Lm9yZzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMoAd5foOBmZRDnZECW0NGIiGFOgUgTUH1iqONh6FUJwG03ziOh8NkIIZnZQpAWn1p3xeqa-U1EX_mxKJKS-jO-jYjBgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAhBgNVHREEGjAYggsqLm51Z2V0Lm9yZ4IJbnVnZXQub3JnMA4GA1UdDwEB_wQEAwIFoDAMBgNVHRMBAf8EAjAAMAsGCSqGSIb3DQEBDAOCAQEAPhcdDUvgrUX6MQrMsWROVzM7ecGFjQIs6VHUtkqdNOGxGxv-isKEhANkpBnpMLYlfZ7jC8Dtwxc3FSiAMt1DSXdHSdE4EDXQwNnAquA9PYFLA28pqjPdH0RGfIxcJgCv21IRCSJ-PC32uz2iczryBxtbmaBZSYzjJFTXHvbtaCUrWHXc1-TvVin--MaXENQCOmTdJiqORq10ky2jDMOZ-J6ub-cpNS_I1_INjUlI5qTs0krBsSK1A8gcGcNJsTaqAxFHh7eXe9_n9mE3g_e2TQ0zcOVwh7FQ6O-T4Drr4vRebn50d3QmDS9dDL4pXf2dk_9oGEMDA7t8GcDdv4IbyQ)) of the certificate you provided and it shows this:
![image](https://user-images.githubusercontent.com/94054/168121717-66bb6baa-a9c4-4060-a09e-08c48f6482ff.png)

The fingerprint of this certificate is: `5003370a4f07fb16955e5620e0b18d69e5e5a637`. I found it using this tool: https://ssltools.godaddy.com/views/certDecoder.

This does not match the new or old certificate fingerprint we are using on api.nuget.org:
Expires 7/29/2022 - fingerprint `0cea5ff77bd49c482f09772e7ba748076feaa854`
Expires 4/21/2023 - fingerprint `aff8e461e4b34dd2269ec0f1f70e1b14d7a8d1ba`

The only explanation that makes sense to me is that your network or local machine has a proxy enabled which is blocking some SSL connections by swapping out the returned SSL certificate chain (during TLS negotiation) for this "Untrusted" one. If you are in a corporate environment, could you reach out to your IT department to ask if anything like this is happening for `api.nuget.org`?

**Comment by joelverhagen** [comment]
Hello, I have not heard back from you about this issue. I will close it now. If you are still facing a problem related to NuGet.org, please feel free to open a new issue and reference this closed one. Thanks!
