### ISSUE TITLE
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.

### ISSUE THREAD

**Issue by LoxleyColourDev** [NuGet/NuGetGallery#9117]
### Impact

I'm unable to use NuGet.org

### Describe the bug

In Visual Studio 2022

Manage NuGet packages for solution.

Browse gives the following error:

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host

### Repro Steps

See above.
I also wrote a console app:
var response = await client.GetAsync("https://api.nuget.org/v3/index.json");
Same error.

### Expected Behavior

This should return without errror.

### Screenshots

![image](https://user-images.githubusercontent.com/7057224/168332965-56b1e7a1-4250-4bc2-8c8b-dafc9081b71c.png)

### Additional Context and logs

Microsoft Visual Studio Professional 2022
Version 17.1.6
VisualStudio.17.Release/17.1.6+32421.90
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Windows 10
Location: Edinburgh, Scotland
No firewall or proxy.
Home broadband.

**Comment by zhhyu** [comment]
@LoxleyColourDev Thank you for reaching out to us! 

Could you please let us know whether it's an intermittent issue or an always failure? We may need to reach out to our CDN provider for the further investigation.

**Comment by LoxleyColourDev** [comment]
Permanent failure now but it use to connect without any problems.

**Comment by alcoheca** [comment]
Similar issue for me when connecting from my office. Confirmed there is no firewall or proxy interfering. Permanent failure, I noticed it first on Tuesday 10th May.

Browsing the feed url via chrome DOES work, which I find confusing.

I've tried to make a request with all available SslProtocols.

```
Microsoft Visual Studio Professional 2019
Version 16.11.14
VisualStudio.16.Release/16.11.14+32428.217
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.106.23128
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Node.js Tools   1.5.30526.3 Commit Hash:c09c81113bcbc86d57943fcdd67e82434263d61d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62201.17150
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

```
-------------------------- None --------------------------------------
An error occurred while sending the request.
         --> The underlying connection was closed: An unexpected error occurred on a send.
         --> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
         --> An existing connection was forcibly closed by the remote host

None failed
-------------------------- Ssl2 --------------------------------------
The requested security protocol is not supported.

Ssl2 failed
-------------------------- Ssl3 --------------------------------------
The requested security protocol is not supported.

Ssl3 failed
-------------------------- Tls --------------------------------------
An error occurred while sending the request.
         --> The underlying connection was closed: An unexpected error occurred on a send.
         --> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
         --> An existing connection was forcibly closed by the remote host

Tls failed
-------------------------- Default --------------------------------------
The requested security protocol is not supported.

Default failed
-------------------------- Tls11 --------------------------------------
An error occurred while sending the request.
         --> The underlying connection was closed: An unexpected error occurred on a send.
         --> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
         --> An existing connection was forcibly closed by the remote host

Tls11 failed
-------------------------- Tls12 --------------------------------------
An error occurred while sending the request.
         --> The underlying connection was closed: An unexpected error occurred on a send.
         --> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
         --> An existing connection was forcibly closed by the remote host

Tls12 failed
-------------------------- Tls13 --------------------------------------
An error occurred while sending the request.
         --> The underlying connection was closed: An unexpected error occurred on a receive.
         --> The client and server cannot communicate, because they do not possess a common algorithm

Tls13 failed
```

**Comment by zhhyu** [comment]
Hi! My apologies for this inconvenience. NuGet.org has moved to a new multi-CDN infrastructure: https://github.com/NuGet/Announcements/issues/60. Some older TLS cipher suites are deprecated from the new CDN service.

Please ensure that TLS 1.2 and any of the following cipher suites have been enabled on your machine:

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by LoxleyColourDev** [comment]
I read the annoucement and enabled the ciphers on my machine previously.  It didn't helped.  It still fails to connect to NuGet.org.  Maybe I need to disable a few or rearrange the order?

![image](https://user-images.githubusercontent.com/7057224/168654841-f2ae0e4d-e6e6-463f-97f5-99c640855d3a.png)

![image](https://user-images.githubusercontent.com/7057224/168655048-688625f8-cd86-449f-89f4-c7d5b5a6e8c3.png)

**Comment by alcoheca** [comment]
@LoxleyColourDev sorry for hijacking your issue - I've resolved my issue by clicking the `Best Practices` button on IIS Crypto and rebooting my PC. Looking at your screenshot you still have TLS 1.0 and 1.1 enabled, perhaps that is the issue.

Thanks for the pointer nonetheless..

**Comment by LoxleyColourDev** [comment]
@alcoheca - Please do hijack - especially when it helps.  Ok.  Got it back working so thanks for the input.  Wasn't quite as simple as just using the Best Practices for me.  I then had to disable the Triple DES 168 cipher, just leaving me with AES 128/128 & AES 256/256.  I then had to disable TLS 1.0 & TLS 1.1 and enable SSL 3.0.  That got the connection to api.nuget.org back working within VS.  Screen prints of what Best Practises left me and then what actually got it working are below.

![image](https://user-images.githubusercontent.com/7057224/168682937-fd120564-0f9e-4cd2-ad29-b1d03279e0af.png)

![image](https://user-images.githubusercontent.com/7057224/168682880-93bb67ef-f728-4a90-b613-f7b5d2705ca5.png)
