### ISSUE TITLE
Tabs navigation permalinks

### ISSUE THREAD

**Issue by am11** [NuGet/NuGetGallery#9118]
Steps:
* Open https://www.nuget.org/packages/Microsoft.NET.Test.Sdk
* Click `Dependencies`

Expected: the URL in browser address bar is updated with permalink to Dependencies tab, ideally: https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/Dependencies /Framewroks /Versions etc. should be hooked to page load handler.

Actual: the URL is not updated, tab navigation permalinks are not supported on page loads. Sharing nuget.org URL in discussions, when the intended content is not visible to the audience, entails further explanation.

Moreover, the "last tab" info is currently cached locally, so the user who is sharing the link will still land on `Dependencies` after the refresh or open the link in new tab, unless it is opened in private browsing mode or a different browser. This causes more confusion when sharing nuget.org links in discussions.

note: there is a (less nicer) link https://www.nuget.org/packages/Microsoft.NET.Test.Sdk#dependencies-tab which shows up when we hover over the tab. In theory it should take us to Dependencies tab on page load, but it does not work.

**Comment by loic-sharma** [comment]
Hello, thanks for the suggestion! This seems like a duplicate of https://github.com/NuGet/NuGetGallery/issues/8822

**Comment by am11** [comment]
Thanks. Indeed, they are the same. Closing as dupe.
