### ISSUE TITLE
[NuGet.org Bug]: Details about Problem When uploading a package to nuget.org manually via the website, I can set a documentation URL that points to a readme file on github, as shown here: https://www.nuget.org/packages/blazor-server-githubactions-demo/  How do I this via a .csproject file, as I use CI / CD to publish my packages and so I don't want this to be a manual step. how publish readme file automatically along with pacakge.

### ISSUE THREAD

**Issue by mohanpaladugu** [NuGet/NuGetGallery#9124]
### Impact

It bothers me. A fix would be nice

### Describe the bug

[NuGet.org Bug]: Details about Problem When uploading a package to nuget.org manually via the website, I can set a documentation URL that points to a readme file on github,

 as shown here: https://www.nuget.org/packages/blazor-server-githubactions-demo/  

How do I this via a .csproject file, as I use CI / CD to publish my packages and so I don't want this to be a manual step. how publish readme file automatically along with pacakge.

### Repro Steps

https://www.nuget.org/packages/blazor-server-githubactions-demo/ 

### Expected Behavior

How do I this via a .csproject file, as I use CI / CD to publish my packages and so I don't want this to be a manual step. how publish readme file automatically along with pacakge.

**Comment by joelverhagen** [comment]
Hey @mohanpaladugu, it looks like you might be helped with the **embedded README** feature for NuGet packages.

Take a look at this blog post for how to use it:
https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/#add-a-readme-to-your-package

**Comment by joelverhagen** [comment]
I haven't heard back from you in the past couple of days. Take a look at the blog on how to embed a readme in your package. If you still have questions, please feel free to open a new issue. Thanks!

**Comment by mohanpaladugu** [comment]
Hi @joelverhagen thanks for responding.

Ya i implemented its working .
