### ISSUE TITLE
[Feature]: Add indexing status to the status page

### ISSUE THREAD

**Issue by jchristn** [NuGet/NuGetGallery#9125]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

Indexing has taken over an hour for a package I've published.  Please add indexing status to the status page on nuget.org

**Comment by jchristn** [comment]
I'm going to assume it was either [DatabaseWrapper](https://www.nuget.org/packages/DatabaseWrapper/) or [WatsonORM](https://www.nuget.org/packages/WatsonORM/) or one of their dependencies therein (for instance, ```DatabaseWrapper.Mysql```, there are about 5 of them, same with WatsonORM).

**Comment by joelverhagen** [comment]
We do retain this information for _validation_. I'm looking more at this situation and my initial theory has proven incorrect. I was assuming it was our validation pipeline (malware scanning, signing, etc) that had the delay. This was incorrect. What actually happened was that we had a massive wave of package deprecations which caused a delay in our pipeline.

Unfortunately, we do not retain _indexing_ telemetry on a per-package basis. However, at an aggregate level, our indexing delay reached a value of 3630 seconds (just over 1 hour) at 9:35 AM PDT on May 27th. This is very atypical.

This was the reason you experienced the indexing delay.

**Comment by jchristn** [comment]
Thanks for following up @joelverhagen - I appreciate it.
