### ISSUE TITLE
[NuGet.org Bug]: Sign in comes back with "Error 500 - Internal Server Error"

### ISSUE THREAD

**Issue by peterrexj** [NuGet/NuGetGallery#9126]
### Impact

I'm unable to use NuGet.org

### Describe the bug

After trying to sign in from the browser, the page goes to Error 500 - Internal Server Error
I have tried to 
- Clear cache
- Restart
- Try from another computer
- Try from a different browser

All of these attempts failed and navigates to Error 500 - Internal Server Error
I have confirmed that the user password is working as I tried with Microsoft Account and the same account is able to login other Microsoft services

### Repro Steps

Login to nuget.org

### Expected Behavior

Successfully able to log in and use the service

### Screenshots

![image](https://user-images.githubusercontent.com/10838987/170829497-dfecdaf3-b7c7-4122-bdd7-d284e967bc02.png)

### Additional Context and logs

With a full network log, I can share the username if required
![image](https://user-images.githubusercontent.com/10838987/170829560-2b6ee0ba-2bf2-4cdf-be0b-b993c786475d.png)

**Comment by koszeggy** [comment]
Same for me. A little addendum:

* I got the error in the OP after installing Microsoft Authenticator. I successfully confirmed the logon attempt before getting the error. I checked "Remember Me" so now I don't get any confirmation request just the internal error immediately whenever I select my account.
* I also tried to sign in with the "Windows Hello" option. I was prompted to use the fingerprint scanner of my laptop, and after the successful authentication I got the following error:

![image](https://user-images.githubusercontent.com/27336165/170830642-f58c55dc-2180-4d33-ad84-3f9ea4b9fd3e.png)

**Comment by mariuszgromada** [comment]
The same in my case
![image](https://user-images.githubusercontent.com/16277367/170830937-92a321e8-c195-4609-8d09-c842e2d9a277.png)

**Comment by tomahg** [comment]
Same for me.

**Comment by JPP01** [comment]
Same is happening to me. Also I cannot push new packet versions to nuget.org. The API endpoint (https://www.nuget.org/api/v2/package) responses the same 500 (Internal Server Error).

**Comment by porechajp** [comment]
Yes, I am getting the same issue while pushing a new version of Nuget package.

**Comment by peterrexj** [comment]
I can log in now successfully, am happy to close, or can wait for confirmation from others who have faced similar issues.
@koszeggy @mariuszgromada @tomahg @JPP01 @porechajp

**Comment by koszeggy** [comment]
@peterrexj: It's working now

**Comment by JPP01** [comment]
@peterrexj package update/upload via nuget push working also!

**Comment by peterrexj** [comment]
Thanks, @koszeggy @JPP01 for confirming, should work for all then, closing this issue
