### ISSUE TITLE
[A11y]API Keys button is rendered using the wrong HTML Element type.

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#9170]
Original: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1554272

Repro Steps:
 - Hit https://www.nuget.org and press Enter key.
 - Navigate to "Sign in" control and hit enter.
 - Navigate to "Sign in with Microsoft" control and hit enter.
 - Select “API Keys” from the Profile Dropdown and hit enter.
 - Navigate to "Create" button and hit enter.
 - Enter Values in "Key Name" and "Glob Pattern" field and hit enter on Create button.
 - Navigate to "Manage" control and hit enter.
 - Verify that whether the API keys are defined as button or heading.

Actual Result:
For 'API keys' button, it was defined as a H1 heading instead of button.

Expected result:
For API keys, it should be defined as button only.

User Impact:
Users might be able to get confused that the button is defined as heading.

Notes:
Updating this to a button and restyling to match should be sufficient.

**Comment by camigthompson** [comment]
Replied to the ADO bug and requested clarification as the specified headers appear in other pages and seem to just be needed as headers, not buttons.

**Comment by camigthompson** [comment]
ADO bug closed.
