### ISSUE TITLE
[NuGet.org Bug]: totalDownloads > 2.2b can crash clients assuming int32

### ISSUE THREAD

**Issue by apxltd** [NuGet/NuGetGallery#9196]
### Impact

I'm unable to use NuGet.org

### Describe the bug

A handful of "really popular" packages seem to have surpassed the 2.2b threshold:
* Microsoft.NETCore.Platforms
* Microsoft.Extensions.Primitives
* Microsoft.Extensions.DependencyInjection.Abstractions

As a result, clients that process results from the [Search resource](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource) will be unable to query NuGet.org if they assume that the documented `integer` that `totalDownloads` uses is a 32-bit integer.

Unfortunately, older versions of ProGet are one such client :(

This is causing a lot of ProGet users a lot of headaches / outages, especially since they can't quickly upgrade. It'd be really nice if this could be addressed on the back-end some how. Especially for users who can't easily upgrade.

Figure this is a long shot, but if it's relatively easy... my suggestion:
* `totalDownloads` is the total downloads, up to 2147483647 (`Int32.MaxValue`)
* `totalDownloadsLong` is the total downloads, up to `UInt64.MaxValue`

This would allow existing clients to work indefinitely while allowing the few packages that go past 2.2b to continue showing their stats.

### Repro Steps

Perform a search for any of the popular packages mentioned:
* Microsoft.NETCore.Platforms
* Microsoft.Extensions.Primitives
* Microsoft.Extensions.DependencyInjection.Abstractions

### Expected Behavior

`totalDownloads` returns 2147483647
`totalDownloadsLong` returns the downloads up to  `UInt64.MaxValue`

**Comment by shishirx34** [comment]
Hello @apxltd - this bug is addressed with a fix in this issue: https://github.com/NuGet/NuGetGallery/issues/9182. Let us know if you continue to see any issues here.
