### ISSUE TITLE
[Feature]: Allow README URLs from Free Software Foundation Europe, REUSE

### ISSUE THREAD

**Issue by dorssel** [NuGet/NuGetGallery#9200]
### Related Problem

Uploading my nuget README.md gives:

> Some images are not displayed as they are not from [trusted domains](https://aka.ms/nuget-org-readme#allowed-domains-for-images-and-badges).

The URL in question is: https://api.reuse.software/info/github.com/dorssel/dotnet-aes-extra
(and the associated badge.

### The Elevator Pitch

Considering that REUSE is a widely used tool to ensure proper (open-source) licensing, and that nuget has a strong open-source incentive, I think such URLs should be whitelisted (either just api.reuse.software, or perhaps even *.reuse.software).

**Comment by joelverhagen** [comment]
Hey @lyndaidaii, could you take a look at this image domain candidate?

**Comment by dorssel** [comment]
FYI, example nuget package here: https://www.nuget.org/packages/Dorssel.Security.Cryptography.AesExtra

**Comment by lyndaidaii** [comment]
@dorssel , thanks for idea. I am going to evaluate if this domain to secure to include in our image domain allowlist. I will let you know once I have result for evaluation,

**Comment by lyndaidaii** [comment]
@dorssel, thanks for your patience. After evaluation of this domain, we decided to add this new domain to our image domain allowlist.
