### ISSUE TITLE
[NuGet.org Bug]: Please fully qualify NuGet\Install-Package on the installer tab

### ISSUE THREAD

**Issue by potatoqualitee** [NuGet/NuGetGallery#9201]
### Impact

It's more difficult to complete my work

### Describe the bug

As a PowerShell Developer, I am excited to see a PowerShell install command on each package. 

![image](https://user-images.githubusercontent.com/8278033/185921310-15f20721-1336-4260-9378-82fd2b81c34d.png)

But it always fails because `-Version` does not exist in my `Install-Package` command. Only `-RequiredVersion` exists.

![image](https://user-images.githubusercontent.com/8278033/185921499-5c820107-ed23-485f-aba7-c602fb488a3c.png)

After talking to others who figured this out, I now understand that there are two distinct `Install-Package` commands with incompatible parameters.

### Repro Steps

1. Open up a Windows PowerShell console, not a VS Developer console. 
2. Run `Install-Package Microsoft.Playwright -Version 1.25.0`
3. This uses `Install-Package` from Microsoft's `PackageManagement` module
4. Fail

### Expected Behavior

Whatever is provided on NuGet.org should work.

Considering the naming convention is problematic, please fully qualify the command on the website so that end-users have a hint that there are two commands from Microsoft with the same name that are different.

```
NuGet\Install-Package Microsoft.Playwright -Version 1.25.0
```

Alternatively, please rename your command to `Install-NuGetPackage` for better alignment and clarity.

The "Package Manager Console" is also confusing to people who aren't intimately familiar with Visual Studio. Perhaps add a PowerShell tab with the proper syntax right after the Cake tab.

![image](https://user-images.githubusercontent.com/8278033/185923725-e2141b12-98dc-4e35-929e-0ea4fb58807f.png)

In that tab would be
```
PackageManagement\Install-Package Microsoft.Playwright -RequiredVersion 1.25.0
```

**Comment by joelverhagen** [comment]
This is an excellent suggestion. The confusion between the Package Manager Console's `Install-Package` (used historically within VS) and `Install-Package` in non-VS PowerShell (for PowerShell package management) is a great source of confusion.

Renaming the command is outside of the scope of NuGet.org. Furthermore, I think it would be a very tough request to fulfill since that's a breaking change and (IIRC) investments in the PMC are limited these days.

I think having some clarification around this tab (that it should be used within the VS PMC) would also help. Maybe some note like the `PackageReference` tab has that helps users understand where this command is used and why there is the `NuGet\` qualifier.

**Comment by joelverhagen** [comment]
@potatoqualitee, are you interested in opening a PR to add the `NuGet\` qualifier as well as adding note around where this command is used? Maybe linking to https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-powershell? This seems like a great "Up for grabs" issue that a community member can gets started on contributing with.

**Comment by potatoqualitee** [comment]
Thanks! I'll see what I can do.

**Comment by joelverhagen** [comment]
Thank you @potatoqualitee for your contribution! We'll work on getting this out to NuGet.org.

**Comment by potatoqualitee** [comment]
Thank you for the acceptance and assist!

**Comment by joelverhagen** [comment]
This is deployed on www.nuget.org. Thanks again for your contribution!

**Comment by potatoqualitee** [comment]
Looks so good, I told all my friends 😅 

![image](https://user-images.githubusercontent.com/8278033/188825645-fa81e6e0-93cd-4997-8853-fcd96fcb732f.png)

**Comment by potatoqualitee** [comment]
Thanks again for the assist 💯  100/100, would PR again.
