### ISSUE TITLE
[Mitigated incident] api.nuget.org is failing for some requests 

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#9218]
## Impact

It's more difficult to complete my work

## Problem description

While restoring packages from https://api.nuget.org/v3/index.json, you may encounter request timeouts or errors. This is an active incident that the NuGet.org team is investigating.

If you are facing an issue, please post a comment here with your approximate geographic location (country) and the specific error you are encountering.

## Timeline (UTC) - 2022-09-05

11:11 AM - first indication of failure from Application Insights availability web tests
11:47 AM - Severity 2 incident raised, on-call engineering called
12:08 PM - primary CDN in US and EU failed over to secondary CDN
12:09 PM - monitoring indicates that the mitigation is successful, expecting no more user impact
12:14 PM - status page manually updated: https://status.nuget.org/
12:18 PM - tweet sent out: https://twitter.com/nuget/status/1566762590335893505

## Timeline (UTC) - 2022-09-07

4:14 PM - first indication of failure from Application Insights availability web tests
4:19 PM - Severity 2 incident raised, on-call engineering called
4:28 PM - primary CDN in US and EU failed over to secondary CDN
4:32 PM - last indication of failure from monitoring

**Comment by hulken76** [comment]
Issue on own hosted devops build agent (Ubuntu 20.04), location Sweden
`"/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj" (Restore target) (1) ->
       (Restore target) -> 
         /azp/_work/_tool/dotnet/sdk/6.0.100/NuGet.targets(130,5): error : Failed to download package 'System.Linq.Expressions.4.1.0' from 'https://api.nuget.org/v3-flatcontainer/system.linq.expressions/4.1.0/system.linq.expressions.4.1.0.nupkg'. [/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj]
       /azp/_work/_tool/dotnet/sdk/6.0.100/NuGet.targets(130,5): error : The SSL connection could not be established, see inner exception. [/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj]
       /azp/_work/_tool/dotnet/sdk/6.0.100/NuGet.targets(130,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj]
         /azp/_work/_tool/dotnet/sdk/6.0.100/NuGet.targets(130,5): error : The feed 'NuGetOrg [https://api.nuget.org/v3/index.json]' lists package 'System.Linq.Expressions.4.1.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj]
       /azp/_work/_tool/dotnet/sdk/6.0.100/NuGet.targets(130,5): error :   Unable to find package 'System.Linq.Expressions.4.1.0'. [/azp/_work/1/s/src/AzureFunctions/DeviceEventHandler/DeviceEventHandler.csproj]
`

**Comment by Arnab-Developer** [comment]
GitHub action is failing at nuget restore step with below error message.

```
Failed to download package 'Dapper.2.0.123' from 'https://api.nuget.org/v3-flatcontainer/dapper/2.0.123/dapper.2.0.123.nupkg'.
  An error occurred while sending the request.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
```

**Comment by Arnab-Developer** [comment]
@joelverhagen GitHub action is working now. Thanks for the quick resolution. 👍🏼

**Comment by paulhickman-a365** [comment]
I'm getting intermittent failures on 7 Sep 2022 15:00 - 17:00 UTC trying to download packages from a Microsoft hosted DevOps agent in the UK South region using the image "windows-latest". e.g.

````
##[error]C:\hostedtoolcache\windows\dotnet\sdk\6.0.400\NuGet.targets(132,5): Error : Failed to download package 'Microsoft.AspNetCore.Cryptography.Internal.2.2.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/2.2.0/microsoft.aspnetcore.cryptography.internal.2.2.0.nupkg'.
The SSL connection could not be established, see inner exception.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
  An existing connection was forcibly closed by the remote host.
C:\hostedtoolcache\windows\dotnet\sdk\6.0.400\NuGet.targets(132,5): error : Failed to download package 'Microsoft.AspNetCore.Cryptography.Internal.2.2.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/2.2.0/microsoft.aspnetcore.cryptography.internal.2.2.0.nupkg'. [D:\a\1\s\App\<myprojecthere>]
C:\hostedtoolcache\windows\dotnet\sdk\6.0.400\NuGet.targets(132,5): error : The SSL connection could not be established, see inner exception. [D:\a\1\s\App\<myprojecthere>]
C:\hostedtoolcache\windows\dotnet\sdk\6.0.400\NuGet.targets(132,5): error :   Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. [D:\a\1\s\App\<myprojecthere>]
C:\hostedtoolcache\windows\dotnet\sdk\6.0.400\NuGet.targets(132,5): error :   An existing connection was forcibly closed by the remote host. [D:\a\1\s\App\<myprojecthere>]
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/index.json'.
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (api.nuget.org:443)
    A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
    An existing connection was forcibly closed by the remote host.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/index.json'.
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (api.nuget.org:443)
    A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/index.json'.
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (api.nuget.org:443)
    A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.cryptography.internal/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
    An existing connection was forcibly closed by the remote host.

````

In most cases an attempt is succeeding within the 5 retries it makes and the build still completes, but sometimes as per the log above, it fails all 5 attempts.

**Comment by joelverhagen** [comment]
This incident has was mitigated as of September 9th. If you are still facing additional problems, please don't hesitate to [contact us](https://www.nuget.org/policies/Contact) or by opening a new issue.
