### ISSUE TITLE
[NuGet.org Bug]: can't download "OrchardCore.Rules" Package in China

### ISSUE THREAD

**Issue by Gsonovb** [NuGet/NuGetGallery#9244]
### Impact

It's more difficult to complete my work

### Describe the bug

Hi,

I tried to create Orchard CMS project,
Adding ”OrchardCore.Application.Cms.Targets“  package, error "not found".
![image](https://user-images.githubusercontent.com/3164300/191384840-fb7a6169-b5d7-4acb-b5d2-eaa55aa78183.png)

Using Fiddler to view the request,

"GET, https://api.nuget.org/v3-flatcontainer/orchardcore.rules/index.json” return is 404.

Using Fiddler's AutoResponder, send the correct response

And then you see the request
“GET https://api.nuget.org/v3-flatcontainer/orchardcore.rules/1.4.0/orchardcore.rules.1.4.0.nupkg” return  404.

![image](https://user-images.githubusercontent.com/3164300/191384854-694004c1-1c70-44ea-a94c-786e9836123e.png)

![image](https://user-images.githubusercontent.com/3164300/191384862-86244abc-f4a2-47b1-849b-0b4f6bae9598.png)

https://github.com/OrchardCMS/OrchardCore/discussions/12455

### Repro Steps

1. dotnet new web 
2.  dotnet add package OrchardCore.Application.Cms.Targets

### Expected Behavior

Successfully adding "OrchardCore.Application.Cms.Targets“ and compile successfully

**Comment by dannyjdev** [comment]
@Gsonovb, thank you for rising this bug, we just deployed a fix, you should no longer have this issue.
