### ISSUE TITLE
[NuGet.org Bug]: Add caniuse images via bitsofco.de to trusted image domains

### ISSUE THREAD

**Issue by christianliebel** [NuGet/NuGetGallery#9252]
### Impact

It bothers me. A fix would be nice

### Describe the bug

We are offering Blazor wrapper packages for different web APIs. There is a great service called caniuse.com that shows the availability of a particular API on different platforms. Ire Aderinokun offers a service that shows the caniuse.com status data and MDN compat data in a (static) image, e.g.:

https://caniuse.bitsofco.de/image/async-clipboard.png → https://res.cloudinary.com/ireaderinokun/image/upload/v1663850793397/caniuse-embed/all/async-clipboard.png

![](https://caniuse.bitsofco.de/image/async-clipboard.png)

Thus, I'd like to suggest adding either `caniuse.bitsofco.de` or the resolved version `res.cloudinary.com/ireaderinokun/*/caniuse-embed/all/*.png` to the allowlist.

### Repro Steps

Status image is currently not shown:

- https://www.nuget.org/packages/Thinktecture.Blazor.AsyncClipboard
- https://www.nuget.org/packages/Thinktecture.Blazor.WebShare

### Expected Behavior

Status image is shown.

**Comment by christianliebel** [comment]
@ireade Could you maybe add a privacy policy to caniuse.bitsofco.de? Or is there any existing policy already?

**Comment by ireade** [comment]
Hey @christianliebel , I've tried to put a [privacy policy together](https://github.com/ireade/caniuse-embed/pull/37/files). I used a free online generator, but hopefully it's sufficient, let me know what you think. 

To summarise though, with the exception of google analytics on the main website (https://caniuse.bitsofco.de/), I don't collect or store any information. There isn't any analytics on the actual embed so I don't have any tracking on where it is used. I also don't have any tracking on the image URLs.

**Comment by lyndaidaii** [comment]
@ireade, let me know once you publish your privacy policy. I will continue to review again. thanks!

**Comment by christianliebel** [comment]
@ireade Looks good to me! Thank you!

**Comment by ireade** [comment]
@christianliebel great! this has now been published @lyndaidaii
