### ISSUE TITLE
[NuGet.org Bug]: SearchQueryService (primary) returns stale data

### ISSUE THREAD

**Issue by melanchall** [NuGet/NuGetGallery#9257]
### Impact

It's more difficult to complete my work

### Describe the bug

It looks like primary SearchQueryService returns stale data when package information queried. I observe the same stale total downloads count for my package for several days (see repro steps).

### Repro Steps

1. Execute https://api.nuget.org/v3/index.json.
2. Take primary SearchQueryService URL; at the moment it's https://azuresearch-usnc.nuget.org/query.
3. Execute https://azuresearch-usnc.nuget.org/query?q=PackageId:Melanchall.DryWetMidi.
4. Look into `totalDownloads` field, it's value is `36891` and this value is not changed from 21 Sept, although if you look into the package page (https://www.nuget.org/packages/Melanchall.DryWetMidi), you'll see that real total downloads count is `37.2K`. Also latest version downloads count is incorrect too.

But if you query information by secondary SearchQueryService (https://azuresearch-ussc.nuget.org/query?q=PackageId:Melanchall.DryWetMidi), you'll get more accurate value `37062` at the moment of this issue created (although the value is smaller than on nuget.org).

### Expected Behavior

Primary SearchQueryService returns correct downloads numbers. Right now secondary one returns more correct info, but I think _primary_ word means we should rely on it. Right now it seems you don't provide reliable way to get a package downloads statistics via API.

### Screenshots

![image](https://user-images.githubusercontent.com/26361185/192592218-014acd90-8e27-499e-86ee-7880ff02c781.png)

![image](https://user-images.githubusercontent.com/26361185/192592553-43f4abec-d8ce-42ca-b4a5-ac45a8573183.png)

**Comment by lyndaidaii** [comment]
@melanchall, thanks for reporting, azure search is working now. We reflowed packages Melanchall.DryWetMidi, it should bring all download counts to update. Please let us know if there is any other problem.

**Comment by melanchall** [comment]
@lyndaidaii It works, thanks!
