### ISSUE TITLE
[NuGet.org Bug]: The generated link for owner request is broken.

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#9258]
### Impact

It's more difficult to complete my work

### Describe the bug

The link in the email doesn't point to www.nuget.org.

### Repro Steps

Add a package owner and check the generated link in the email.

### Expected Behavior

The link should be workable. What about other scenarios?

**Comment by joelverhagen** [comment]
We may need an additional config used on the admin panel (in addition to the existing SiteUrl) used for email links.

**Comment by zhhyu** [comment]
The generated link used for API key revocation is also broken.
