### ISSUE TITLE
[NuGet.org Bug]: Prerelease sorting works in an unexpected way.

### ISSUE THREAD

**Issue by taori** [NuGet/NuGetGallery#9262]
### Impact

It's more difficult to complete my work

### Describe the bug

Imagine we have 2 packages 
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-alpha9
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-alpha11

9 is considered most recent 

I am willing to contribute a fix btw.

This also affects the integration within VS Nuget - providing the wrong packages.

### Repro Steps

See description

### Expected Behavior

with these urls:
https://www.nuget.org/packages/Amusoft.Toolkit.Http/
https://www.nuget.org/packages/Amusoft.Toolkit.Http/latest
https://www.nuget.org/packages/Amusoft.Toolkit.Http/latest/prerelease

i would expect alpha 11 to be the latest package (assuming there are no release packages) for all 3 of those urls.

Ideally each sequence of numerics, alphabet and non alphanumerics creates a pattern group resulting in a sorting schema of 

https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.1
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.1-beta4.1
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.1-beta1.5
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.1-alpha1.5
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-beta7.13
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-beta7.12
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-beta7.4
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-beta7
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-alpha11
https://www.nuget.org/packages/Amusoft.Toolkit.Http/1.0.0-alpha9

**Comment by joelverhagen** [comment]
Hey @taori! Yes, I agree this is an unintuitive part of SemVer. See https://semver.org/#spec-item-11:
> Identifiers with letters or hyphens are compared lexically in ASCII sort order.

However, fear not, there is a way to do what you want. If the dot-separated piece of the prerelease label (called an identifier in the spec) is only numeric, it will be sorted by numeric value. So if you put a dot between the numeric part and the "alpha"/"beta" part, it should work as expected.

So `1.0.0-alpha9` becomes `1.0.0-alpha.9`.

For example: see the fixed-up, sorted versions with my a little NuGet helper website I made: [example](https://nugettools.azurewebsites.net/6.0.0/sort-versions?versions=1.0.1%0D%0A1.0.1-beta.4.1%0D%0A1.0.1-beta.1.5%0D%0A1.0.1-alpha.1.5%0D%0A1.0.0%0D%0A1.0.0-beta.7.13%0D%0A1.0.0-beta.7.12%0D%0A1.0.0-beta.7.4%0D%0A1.0.0-beta.7%0D%0A1.0.0-alpha.11%0D%0A1.0.0-alpha.9).
