### ISSUE TITLE
[NuGet.org Bug]: URL to go to frameworks tab doesn't work

### ISSUE THREAD

**Issue by zivkan** [NuGet/NuGetGallery#9283]
### Impact

It bothers me. A fix would be nice

### Describe the bug

Go to any package on nuget.org. Right click the framework tab and select "open in new tab". The URL is something like: https://www.nuget.org/packages/NuGet.Frameworks#supportedframeworks-tab however it does not open directly to the frameworks tab (it seems to remember what the last tab I had open was, say the readme)

### Repro Steps

1. Go to any package on nuget.org and change your tab to readme
2. Open https://www.nuget.org/packages/NuGet.Frameworks#supportedframeworks-tab

### Expected Behavior

nuget.org should show the frameworks tab for the package

**Comment by joelverhagen** [comment]
Seems like the anchor baked into markup is `#supportedframeworks-body-tab` but the click event overrides the anchor to `#supportedframeworks-tab`. Not expected. Thanks for the report!

**Comment by Lanaparezanin** [comment]
There's more to this one than just the frameworks tab, none of the following ones can be properly opened in the new tab:

<img width="472" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/f4747802-e3cb-4228-a96a-d74ee5be3cdb">
<img width="356" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/6c33871a-ac01-47e9-b11d-946f01ea3b9b">
