### ISSUE TITLE
[Question] How to get repository commit property?

### ISSUE THREAD

**Issue by shps951023** [NuGet/NuGetGallery#9291]
My project MiniExcel on nuget will feedback missing repository commit information, link : https://nuget.info/packages/MiniExcel/1.28.2

![image](https://user-images.githubusercontent.com/12729184/198841871-ad5b1a8b-bcb3-4f95-8719-d05d1599dd5e.png)

but dapper nuget project can have it, why? really appreciate!

![image](https://user-images.githubusercontent.com/12729184/198841805-aa6dee35-0278-4e37-8b3a-b0325f502ae9.png)

**Comment by joelverhagen** [comment]
There are several ways to populate this information in your package. One of the most popular is using SourceLink.
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects

This is what Dapper appears to be source:
https://github.com/DapperLib/Dapper/blob/a31dfd3dd4d7f3f2580bd33c877199d7ef3e3ef9/Directory.Build.props#L39

I've used SourceLink and it's really easy. You get SourceLink enabled PDBs as well as this NuGet package metadata. Give it a try!

**Comment by loic-sharma** [comment]
I highly recommend the best practices guide: https://learn.microsoft.com/nuget/create-packages/package-authoring-best-practices#repository-type-and-url

**Comment by joelverhagen** [comment]
I'm going to close this issue since it appears your question is answered and we'll use the docs issue that Loic mentioned to track improving the visibility of this content.

**Comment by shps951023** [comment]
@loic-sharma @joelverhagen really appreciate!
