### ISSUE TITLE
[Question]. Are there plans for a .net core 6+ version of NuGet.Server?

### ISSUE THREAD

**Issue by erikbartlow** [NuGet/NuGetGallery#9292]
Since .NET 4.5.2 is soon to be out of support is there a plan to support .NET Core?

**Comment by joelverhagen** [comment]
Hey @erikbartlow, are you talking about running the NuGetGallery itself on the .NET (Core) runtime instead of .NET Framework? Or are you talking about package compatibility displays on NuGet.org?

**Comment by ArwynFr** [comment]
I would not talk on behalf of the OP, but I understand the question to be about nuget gallery itself. And I'm interested in the answer so I'll follow the conversation.

**Comment by joelverhagen** [comment]
Thanks for the input @ArwynFr. This is an undertaking we've talked about as a team but have not had the ability to prioritize a full-blown migration. That being said, there are some internal conversations on how to best approach this migration. There are some ideas on how we can do this in a safe, and incremental way. I can't provide a time estimate or delivery date, unfortunately.

cc @agr

**Comment by ArwynFr** [comment]
Thanks for the feedback ; sending you people strengh, as this is not an easy task.

**Comment by erikbartlow** [comment]
Thank you for the response.  It's the nuget server package.  Currently it
states it is only compatible up to .net framework.  I was hoping to run an
in house server, but don't want use a version of .net that is going out of
support soon.

Erik Bartlow

**Comment by joelverhagen** [comment]
Ah, understood. (@ArwynFr, he's referring to the [NuGet.Server package](https://www.nuget.org/packages/NuGet.Server) and associated [docs](https://learn.microsoft.com/en-us/nuget/hosting-packages/nuget-server)).

We do not have plans to move this package to .NET Core. Our team's main focus is on NuGet.org's server implementation and improving the features/security of that running web service. We will service NuGet.Server with security patches and accept pull requests, but it's not an effort we can prioritize.

@erikbartlow, if you're interested in a local NuGet feed that runs on .NET Core, consider one of the 3rd party or OSS implementations here: https://learn.microsoft.com/en-us/nuget/hosting-packages/overview. I know a lot of folks have great success with [BaGet](https://github.com/loic-sharma/BaGet), so maybe give that a try?

**Comment by joelverhagen** [comment]
I'll close this issue now since the question is answered.
