### ISSUE TITLE
[Question]: SemVer 2.0.0 packages filtered out of V2 endpoints by default

### ISSUE THREAD

**Issue by EkiH** [NuGet/NuGetGallery#9294]
### Impact

I'm unable to use NuGet.org

### Describe the bug

For some reason V2 feed does not return a result when searching for package SaxonCS 11.4.1, we couldn't reproduce this problem with any other package.

Link to the package in the Gallery: https://www.nuget.org/packages/SaxonCS/11.4.1

We're working on updating our client library, but for now we're stuck with the V2 feed.

### Repro Steps

LinqPad repro with Nuget.Core:
```
var repo = (IServiceBasedRepository)NuGet.PackageRepositoryFactory.Default.CreateRepository("https://www.nuget.org/api/v2");
repo.FindPackages("SaxonCS", new VersionSpec(new NuGet.SemanticVersion("11.4.1")), true, true).Dump();
```

Repro with direct http query:
`https://packages.nuget.org/api/v2/FindPackagesById()?id=%27SaxonCS%27`

### Expected Behavior

SaxonCS package would be found in the feed like any other package.

### Screenshots

![image](https://user-images.githubusercontent.com/6724459/199431332-737bc648-51e1-4b1c-90eb-32f8e3c6a67d.png)

![image](https://user-images.githubusercontent.com/6724459/199431187-5f4c6589-b7c3-40d3-8e55-0d19042fcbfa.png)

**Comment by joelverhagen** [comment]
[SaxonCS 11.4.1](https://www.nuget.org/packages/SaxonCS/11.4.1) is a SemVer 2.0.0 package, meaning it is filtered out of our API endpoints by default for legacy reasons. This URL will show the desired versions:
https://packages.nuget.org/api/v2/FindPackagesById()?id=%27SaxonCS%27&semVerLevel=2.0.0

I recommend switching to the NuGet.Protocol (NuGet 3.x+) package. NuGet.Core has been deprecated for quite a while.
https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

**Comment by EkiH** [comment]
Thank you for the reply!

I wasn't aware that SemVer 2.0.0 packages were filtered out. Is there a list of things that might cause a package to be filtered out somewhere?

We are aware that NuGet.Core is deprecated and we're working on moving to NuGet 3.x libraries and the v3 feed. It will just take some time as we had modifications, such as custom PackageRepository types, which we need to replace.

**Comment by joelverhagen** [comment]
I don't think we have a list in a document, just the way you're asking. In general V2 protocol is not documented.

Deleted packages are filtered out everywhere. Unlisted packages are filtered out of Search, but not that FindPackagesById endpoint. And SemVer 2.0.0 packages are filtered out of Search and FindPackagesById unless you pass the semVerLevel query parameter.

**Comment by joelverhagen** [comment]
I'll close this issue since the question is answered. Please feel free to open another issue if you're facing more problems!
