### ISSUE TITLE
[Feature]: Allow README URLs from flat.badgen.net

### ISSUE THREAD

**Issue by zabszk** [NuGet/NuGetGallery#9307]
### The Elevator Pitch

badgen.net is already on the list of allowed domains, however their subdomain flat.badgen.net (that provides a different badges style) is not.

Can we have flat.badgen.net subdomain added as well, so projects can use the flat style of badges as well?

**Comment by joelverhagen** [comment]
Thanks for the suggestion, @zabszk! There are several other image host requests in the queue. @lyndaidaii - could you look at this one at the same time as the others?

**Comment by lyndaidaii** [comment]
@zabszk, thanks for providing suggestions.  After security and privacy evaluation of this domain, we decided to include it into our image allowlist. Please let me know if you have any other suggestions/questions.

**Comment by zabszk** [comment]
> @zabszk, thanks for providing suggestions. After security and privacy evaluation of this domain, we decided to include it into our image allowlist. Please let me know if you have any other suggestions/questions.

Thanks a lot! For now I don't have any further suggestions or questions.
