### ISSUE TITLE
Support .NET Framework 4.8.1 in the compatible framework view

### ISSUE THREAD

**Issue by ww898** [NuGet/NuGetGallery#9321]
Hi there,

Could you please add .NET Framework 4.8.1 to the compatible framework view? See the example:
![image](https://user-images.githubusercontent.com/2767027/205999717-d7ab07b1-4ca8-46c6-8c1f-0b33dce396fc.png)

**Comment by joelverhagen** [comment]
Nice catch! We've recently shipped the `net7.0` frameworks but `net481` is indeed missing! We'll work on this soon.
