### ISSUE TITLE
[Self-hosted Bug]: The stream does not support concurrent IO read or write operations

### ISSUE THREAD

**Issue by WillMarcouiller** [NuGet/NuGetGallery#9322]
### Impact

I'm unable to use this version

### Describe the bug

looking to host a private nuget feed using nuget gallery, so trying to use it.  after having followed the step by step readme of the repo, the project comes up with the following error:

**The stream does not support concurrent IO read or write operations**

### Getting started
**First install prerequisites:**

1. Visual Studio 2019 - Install the following [Workloads](https://docs.microsoft.com/visualstudio/install/modify-visual-studio):
   - ASP.NET and web development
   - Azure development
2. PowerShell 4.0
3. SQL Server 2016 (with DB engine version 13.0 or greater)

**Now run the NuGet Gallery:**

1. Clone the repository with git clone https://github.com/NuGet/NuGetGallery.git
2. Navigate to .\NuGetGallery
3. Build with .\build.ps1
4. Create the database and enable HTTPS with .\tools\Setup-DevEnvironment.ps1
5. Open .\NuGetGallery.sln using Visual Studio
6. Ensure the NuGetGallery project is the StartUp Project and [press F5 to run the site](https://docs.microsoft.com/visualstudio/get-started/csharp/run-program)

### Expected Behavior

I expected the nuget gallery to run.

### Screenshots

after pressing **F5** to run the gallery and waiting for it to load...

![image](https://user-images.githubusercontent.com/6224870/206278724-db90dc04-d7b2-4845-bcef-8e1e9fab238e.png)

despite the existence of proper db.

![image](https://user-images.githubusercontent.com/6224870/206280352-1de7ffa0-3fad-4711-b9b6-47566abcde10.png)

**Comment by joelverhagen** [comment]
I'm not sure if this is related to the DB at all. Given the location of the exception being thrown, I'd actually expect this to be related to the static content or something related to the view later. Could you provide the full stack trace of the exception?

**Comment by joelverhagen** [comment]
I haven't heard back from you, so I'll go ahead and close this issue.
