### ISSUE TITLE
[Self-hosted Bug]: How to run NuGetGallery without Visual Studio?

### ISSUE THREAD

**Issue by xiaoxstz** [NuGet/NuGetGallery#9326]
### Impact

I'm unable to use this version

### Describe the bug

I can run the website with Visual Studio according to the contents in README

But, how can I run it without Visual Studio?

I have tried the command `dotnet  NuGetGallery.dll`, but it doesn't work.

### Repro Steps

Run the command below
`dotnet  NuGetGallery.dll`

### Expected Behavior

The website is started and we can use it then.

**Comment by joelverhagen** [comment]
There are many ways to run a ASP.NET MVC (.NET Framework) web application without Visual Studio. The way we do it on NuGet.org is to deploy the app to an Azure App Service. Generally speaking, you need a web server to run the application. You can configure the app in IIS if you have that running locally. I personally don't have much experience with these alternatives since the NuGet.org team, as quickly as possible, gets code changes into a test environment in Azure (so we can evaluate all sorts of Azure dependency interactions).

`dotnet NuGetGallery.dll` won't work because there is not built-in web server for the application. In other words, it's not as easy as ASP.NET Core applications where a lot of this stuff works well out of the box.

**Comment by xiaoxstz** [comment]
Common `ASP.NET` project can be run with the method below:
* Firstly, open the terminal tool and change to the folder where the project file (`.csproj`) is
* Secondly, run the command `dotnet run`

But it throws errors when running the command in the folder where  the project file (`NuGetGallery.csproj`) is

**Comment by xiaoxstz** [comment]
> This looks like a problem related to a missing workload. Maybe try ensuring the `ASP.NET and web development` workload is installed?

I have installed the workload with VS2022. So, I can build the project with Visual Studio.

I have also installed some .NET SDKs. The output of the command `dotnet --list-sdks` is below
```txt
3.0.100 [C:\Program Files\dotnet\sdk]
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.415 [C:\Program Files\dotnet\sdk]
5.0.402 [C:\Program Files\dotnet\sdk]
6.0.403 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
```

Visual Studio 2022 is installed in `C:\Program Files\Microsoft Visual Studio\2022\Preview`.

How should I run this project with command?

**Comment by xiaoxstz** [comment]
Maybe https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS can be the answer

**Comment by joelverhagen** [comment]
Yup, that looks like a good start. Apologies, I forgot about that document. In general, what you're asking for (a single CLI command to run the app) is not something we've investigated. If you discover the solution, please consider opening a PR enhancing our README document!

**Comment by xiaoxstz** [comment]
> Maybe https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS can be the answer

But the procedure is too complicated and vague. 

Instead, running the project locally with Visual Studio is so simple (We just need to press `F5`). But how can we run it at backend while using Visual Studio

**Comment by joelverhagen** [comment]
I believe our current best solution is the IIS link you've referenced above. If you'd like to investigate simplifying the procedure, we'd be happy to accept a pull request!

In the short term, we do not have plans to improve in this area. I'm happy to leave this issue open to gather upvotes so we can prioritize the work appropriately, with respect to our other work areas.

**Comment by xiaoxstz** [comment]
I found a much simpler solution.

The steps are shown below
1. Create a publish with Visual Studio. Set target as `Folder`
![image](https://user-images.githubusercontent.com/81862747/209054610-3ee579b8-bf14-46e1-8b52-0a3e9f24c6f9.png)

2. Copy the content to any folder you want. Assume the folder is `C:\GreenSoftware\NuGetGallery`

3. Run the command below (You have to use the absolute path)
```cmd
iisexpress /path:C:\GreenSoftware\NuGetGallery
```

Now, you can access the website with browsers. The URL is https://localhost

If you want to change the default port, see #9331

**Comment by xiaoxstz** [comment]
ok, I will write down the steps to readme and create a pull request later
