### ISSUE TITLE
[NuGet.org Bug]: Can't access old account without linked Microsoft Account

### ISSUE THREAD

**Issue by AlexZeitler** [NuGet/NuGetGallery#9329]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Turns my Microsoft Account linked to the Nuget.org Account to manage a particular Nuget package got deleted.

Now, when I'm using "Sign-in assistance" on the Nuget.org website, I get this email for the account:

> Hi there,
We heard you were looking for Microsoft logins associated with your account on NuGet Gallery.
No associated Microsoft logins were found.
Thanks,
The NuGet Gallery Team

What can I do to get access again?

### Repro Steps

1. visit https://www.nuget.org/users/account/LogOn
2. Click [Need assistance signing in?](https://www.nuget.org/users/account/LogOn?returnUrl=%2F#)
3. Enter the username
4. Wait for the email

### Expected Behavior

Get help to be able to login in

**Comment by joelverhagen** [comment]
Hey @AlexZeitler, please reach out to support@nuget.org for this issue. It involves personally identifiable information so we try to avoid GitHub (public issues) for that.

**Comment by AlexZeitler** [comment]
@joelverhagen thanks, will do.
