### ISSUE TITLE
Nuget Readme: whitelist avatars.githubusercontent.com

### ISSUE THREAD

**Issue by phnx47** [NuGet/NuGetGallery#9330]
### Related Problem

Please can we whitelist the domain `avatars.githubusercontent.com` for Nuget.org package readme’s.

### The Elevator Pitch

I have section Supporters with user avatars, I prefer use pictures from `avatars.githubusercontent.com`.

### Additional Context and Details

Example: https://github.com/prom-client-net/prom-client#supporters

**Comment by lyndaidaii** [comment]
@phnx47 Thanks for providing feedback. We are going to add this domain into our allowlist after reviewing it, thanks! Please let us know if you have any questions.

**Comment by phnx47** [comment]
Thanks!
