### ISSUE TITLE
[Self-hosted Bug]: change default https port

### ISSUE THREAD

**Issue by xiaoxstz** [NuGet/NuGetGallery#9331]
### Impact

I'm unable to use this version

### Describe the bug

When I change nothing, I can run the project with Sisual Studio. I can also access the website with my browser.

However, after I change the Project Url from `http://localhost:80` to  `http://localhost:8088` with Visual Studio, I cannot access the website with `http://localhost:8088`.

### Repro Steps

1. Using this git commit of NuGetGallery `f3d98cff86736ccceda547885d79bd458404eedd`
2. Open the solution with Visual Studio 2022.
3. Open the property window of the project `NuGetGallery`. Enter `Web` tab. Change the Project Url to  `http://localhost:8088` 
4. Run project `NuGetGallery` with Visual Studio

### Expected Behavior

I can access http://localhost:8088

### Screenshots

![image](https://user-images.githubusercontent.com/81862747/208923527-215efc55-4275-4f74-952a-73537334ea02.png)

**Comment by joelverhagen** [comment]
Currently, we only support running on the default port. Our `Setup-DevEnvironment.ps1` script assumes this: https://github.com/NuGet/NuGetGallery/blob/f3d98cff86736ccceda547885d79bd458404eedd/tools/Setup-DevEnvironment.ps1#L92

Did you read the getting started section?
https://github.com/NuGet/NuGetGallery#getting-started

You may be able to work around this in some way or modify the setup scripts, but this is not a supported scenario for our project.

**Comment by xiaoxstz** [comment]
Thank you! I succeed in changing the default ports.

The steps are shown below
* Firstly, change the port configuration in `.\tools\Setup-DevEnvironment.ps1`
  ```powershell
  function Get-SiteHttpHost() {return "$(Get-SiteFQDN):8088"}
  function Get-SiteHttpsHost() {return "$(Get-SiteFQDN):8089"}
  ```
* Secondly, run the script `.\tools\Setup-DevEnvironment.ps1` with powershell.
* Thirdly, change the port configuration in the property windows of the project `NuGetGallery` with Visual Studio
   ![](https://user-images.githubusercontent.com/81862747/208923527-215efc55-4275-4f74-952a-73537334ea02.png)
* Lastly, run the project `NuGetGallery` with `F5`
