### ISSUE TITLE
[NuGet.org Bug]: HTTP responses aren't reported to user

### ISSUE THREAD

**Issue by RussKie** [NuGet/NuGetGallery#9336]
### Impact

I'm unable to use NuGet.org

### Describe the bug

If a package author tries to upload
a) a signed package without a registered signing key, or
b) an unsigned package when a signing key is registered,
...the package will not be uploaded and no error message will be shown to the author.

The only way to find any kind of information is to open the DevTools and inspect the HTTP response. The HTTP response will look something like

![image](https://user-images.githubusercontent.com/4403806/209454605-bf34c11d-20f9-4ae3-b557-ced11ce2c24b.png)

### Repro Steps

See above

### Expected Behavior

The error message is shown to the user, and it clearly explains what the author must do in order to upload the package. The error message in the HTTP response **is not** be sufficient.
Links to documentation that articulates the necessity would also be helpful.

A slight necessary OT: our organisation maintains several packages some of which are signed and some of which aren't. We can't sign all of the packages (and it's besides the point). Up until recently we published all packages without issues, and now when I tried to upload a new version of the signed package I couldn't do it. After some head scratching and investigations, essentially I was forced to register the signing key. And after that I could no longer upload a new version of the unsigned package....
_If_ this is now "by design" this has to be explained, as well as steps to resolve such situations should be provided. "Sign all your packages" may not be an option.

**Comment by joelverhagen** [comment]
It turns out they are reported to the user, but they are hidden behind the newly collapsed "Upload" section heading:
![image](https://user-images.githubusercontent.com/94054/209880830-50d424ee-c08e-409f-a849-5071169bc25c.png)

I think the fix here is to move errors outside of the section. I'll work on that.

**Comment by joelverhagen** [comment]
This is fixed in PROD.
