### ISSUE TITLE
support for v3 (symbols) for NuGet/NuGet.Server

### ISSUE THREAD

**Issue by joer33304** [NuGet/NuGetGallery#9341]
### Related Problem

I am using https://github.com/NuGet/NuGet.Server to host some private packages. To be able to debug them I tried to push symbols (snupgk files) but had no success.  The Microsoft NuGet page mentions "Symbol package publishing is only supported by the NuGet V3 API"

I downloaded the /NuGet.Server sources and it looks like V3 is not supported there. I suggest to add it.

### The Elevator Pitch

Symbol support is critical to find bugs in packages

**Comment by joelverhagen** [comment]
We don't have any plans to add V3 or symbol support to NuGet.Server. The codebase is in maintenance mode (severe bug fixes and security patches only). I recommend taking a look at another package source implementation, such as [BaGet](https://github.com/loic-sharma/BaGet/) (for self-hosting) or [Sleet](https://github.com/emgarten/Sleet) (for serverless).

A bunch of other options are listed here: https://learn.microsoft.com/en-us/nuget/hosting-packages/overview
