### ISSUE TITLE
[NuGet.org Bug]: can't upload package with packed README: "The package contains one or more duplicated files in the same folder."

### ISSUE THREAD

**Issue by Sergio0694** [NuGet/NuGetGallery#9343]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I've added a readme file in my NuGet package following the advice from https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/, and I can't seem to be able to upload it to NuGet at all. I just get:

> "The package contains one or more duplicated files in the same folder."

The package contents seem just fine to me:

![](https://user-images.githubusercontent.com/10199417/211220604-66f514d2-f47d-4d58-ba2c-6ce953e86296.png)

PR with the readme changes: https://github.com/Sergio0694/PolySharp/pull/34

Does anyone know whether this is expected (?), or if it's an issue in the website? 😅

### Repro Steps

1. Grab the NuGet package from the artifacts for PolySharp 1.8.3 ([see here](https://github.com/Sergio0694/PolySharp/actions/runs/3869055352))
2. Try to upload it to NuGet.org

### Expected Behavior

It should just work as usual.

### Screenshots

![](https://user-images.githubusercontent.com/10199417/211220690-c17b9568-be2f-43a5-87ba-61b801198577.png)

**Comment by joelverhagen** [comment]
7-Zip shows two README.md files.
![image](https://user-images.githubusercontent.com/94054/211229672-fb3af01b-6e89-4c0e-8a6b-a01f46d9b608.png)

I haven't looked deeply at your .csproj or pack flow, but one good investigation step would be to run `dotnet pack /bl` (pack with the binlog option) and view the binlog using https://msbuildlog.com/. This might show you how the file is getting packed in twice. It's a bit odd that NuGet pack is even allowing a duplicate file to be added to the pack.

**Comment by Sergio0694** [comment]
Huh, that's very weird. Changing `PackFolder="\"` to use `PackagePath="README.md"` fixed it, though I'll admit I'm not entirely sure why that's the case. I might do more investigation and potentially open an issue about this in the NuGetizer repo.
Thank you @joelverhagen! 😄
