### ISSUE TITLE
[NuGet.org Bug]: Information on the `Script & Interactive` usage tab isn't quite accurate 

### ISSUE THREAD

**Issue by jonsequitur** [NuGet/NuGetGallery#9354]
### Impact

Other

### Describe the bug

The `Script & Interactive` tab shows informational text that could use an update. 

> #r directive can be used in F# Interactive, C# scripting and .NET Interactive. Copy this into the interactive tool or source code of the script to reference the package. 

I'd suggest two changes:

* The NuGet support for `#r` is not present in C# scripting. 
* The VS Code extension for .NET Interactive is now called [Polyglot Notebooks](https://devblogs.microsoft.com/dotnet/dotnet-interactive-notebooks-is-now-polyglot-notebooks/). (.NET Interactive is also available in other places, so this name change doesn't apply universally.) Mentioning .NET Interactive **_and_** Polyglot Notebooks might be helpful.

### Repro Steps

1. Open a package URL, e.g.  https://www.nuget.org/packages/Apache.Arrow/
2. Click the `Script & Interactive` tab

### Expected Behavior

The wording could be more accurate.

### Screenshots

![image](https://user-images.githubusercontent.com/547415/214192932-b1fa8a27-ce95-4d75-a11e-21e17274383c.png)

**Comment by KathleenDollard** [comment]
> #r directive can be used in F# Interactive and Polyglot Notebooks. Copy this into the interactive tool or source code of the script to reference the package.

**Comment by joelverhagen** [comment]
This is deployed to PROD on March 3rd. Thanks again for bringing this to our attention.
