### ISSUE TITLE
[NuGet.org Bug]: The rendering of code block in Readme shows the light grey shade. 

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#9355]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The rendering of code block in Readme shows the light grey shade at each line. This looks not pretty and doesn't align with official documents.

### Repro Steps

Open any package with the code block in Readme: https://www.nuget.org/packages/Newtonsoft.Json

There is the light grey shade at each line of the code block:
![image](https://user-images.githubusercontent.com/41028779/214198811-570ada55-fd22-41de-b921-29f6cd16920b.png)

Having the similar rendering of code block as official documents will look much better and support package authors to use this feature.

### Expected Behavior

No shade at each line of the code block in Readme.

**Comment by joelverhagen** [comment]
You have unbelievable vision @zhhyu 👀. This should be a simple CSS fix.

**Comment by joelverhagen** [comment]
@lyndaidaii, I've put this in February. The priority is low.

**Comment by joelverhagen** [comment]
Actually, I can do this one. I see at least one other small bug that I can pick up at the same time.

**Comment by joelverhagen** [comment]
This is fixed in PROD.
