### ISSUE TITLE
[Survey] Repo Contribution Experience Survey 2023

### ISSUE THREAD

**Issue by camigthompson** [NuGet/NuGetGallery#9384]
### **How are we doing? Let us know!**

We want to know how we're doing as maintainers. Fill out the survey in the link below and tell us what you think.

Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8KTX9VT?Source=NuGet/NuGetGallery

**Comment by loic-sharma** [comment]
Here are my recommendations (the survey's options aren't a good fit for ex-team members):

1. **Public by default**: As an outsider, it's hard to tell what the NuGet team is working on & how decisions are made. Too many conversations happen on private repos like http://github.com/NuGet/Engineering and http://github.com/NuGet/Client.Engineering. As much as possible, please include the community by having conversations on public repos like http://github.com/NuGet/Home and http://github.com/NuGet/NuGetGallery.
2. **Advocate the roadmap**: NuGet's roadmap https://github.com/NuGet/Home/issues/12407 is excellent but hard to find. I recommend advertising this roadmap further by pinning it to NuGet's issue trackers, linking to it from repo's README/CONTRIBUTING guides, putting it in issue templates, etc. 
3. **Update the roadmap**: I recommend keeping the roadmap updated with information on what's started, what's been cut, etc.. I'm a huge fan of [VS Code's roadmap](https://github.com/dotnet/efcore/issues/29853) and EF Core's [plan doc](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/plan) and [updates issue](https://github.com/dotnet/efcore/issues/29989). 
4. **Migrate to .NET 7**. The nuget.org codebase uses .NET Framework, which results in a frustrating development experience compared to .NET 7. I suspect this hampers contributions to the NuGetGallery. The team made excellent progress by migrating search to .NET Core, let's keep that momentum going!

**Comment by JonDouglas** [comment]
@loic-sharma Great feedback. Thanks for sharing it! 

I have nothing to add. We'll work to do better. You should see roadmaps for each major .NET repository in an upcoming .NET 8 Preview blog.

/cc @aortiz-msft @joelverhagen @skofman1

**Comment by JonDouglas** [comment]
@camigthompson @joelverhagen Can we pin an issue that links to the home roadmap given last year we made a copy and that led to some confusion?

**Comment by camigthompson** [comment]
@JonDouglas Pinned this issue: https://github.com/NuGet/NuGetGallery/issues/9386

**Comment by camigthompson** [comment]
@loic-sharma Thanks for the feedback!

**Comment by camigthompson** [comment]
The survey is now closed.
