### ISSUE TITLE
[NuGet.org Bug]: Filter for net7.0 does not include sub-TFM

### ISSUE THREAD

**Issue by michaelmairegger** [NuGet/NuGetGallery#9395]
### Impact

I'm unable to use NuGet.org

### Describe the bug

When filtering for net7.0 it should include all other TFM like -windows -android, ... too

### Repro Steps

- Search for e.g. Microsoft.Xaml.Behaviors.Wpf
- Set filter to net5.0
- Click apply
- No Results

Note: Setting the filter to .NET works

### Expected Behavior

Packages that match e.g. net7.0-windows should appear if filtering for net7.0.

**Comment by advay26** [comment]
Related to https://github.com/NuGet/NuGetGallery/issues/9372
