### ISSUE TITLE
[NuGet.org Bug]: Account linked to another email

### ISSUE THREAD

**Issue by dev-vinicius-andrade** [NuGet/NuGetGallery#9397]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Hello there, 

In the past I've created an organization in nuget called codescovery. 
Apparently it's linked to the email **REDACTED - PII**
I would like to link the account to **REDACTED - PII**

### Repro Steps

Trying to login into nuget.org using **REDACTED - PII**

### Expected Behavior

Manage Nuget Account using **REDACTED - PII**

### Screenshots

**REDACTED - PII**

**Comment by joelverhagen** [comment]
Hey @dev-vinicius-andrade, let's talk about this issue over email since it includes private information. Could you send an email to support@nuget.org with these details?

**Comment by dev-vinicius-andrade** [comment]
Sure
