### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by KondorosiAttila** [NuGet/NuGetGallery#9403]
### Impact

It's more difficult to complete my work

### Describe the bug

Hi Team,

I am trying to build our dotnet application with an automated Jenkins pipeline. The steps include: dotnet restore -> dotnet publish -> docker build. However, during the restore step when the process would download packages from https://api.nuget.org/v3/index.json, I get the errors which you can see below.

The occurrence of the errors and the number of affected packages is completely RANDOM. Sometimes they don't appear at all, sometimes I see these errors in the build log, but not breaking it, and sometimes the build breaks.
I've been getting these errors since a couple of days

### Repro Steps

Since these errors appear randomly, I am not sure there are exact steps to reproduce the issue. These are the steps used by me, that get the error:
- Jenkins job running a shell script
- Script executing dotnet restore, dotnet publish, docker build commands

This solution worked perfectly thus far

### Expected Behavior

Packages can be downloaded from https://api.nuget.org/v3/index.json during dotnet restore, consistently without errors

### Screenshots

![image](https://user-images.githubusercontent.com/61154662/221184392-9769f778-1cfc-4bd4-acc6-c15c1195cb4a.png)
![image](https://user-images.githubusercontent.com/61154662/221184112-15bdce2c-603e-4292-8d0e-2ae459728294.png)

**Comment by joelverhagen** [comment]
Hey @KondorosiAttila, do you happen to know if the Jenkins pipeline is running in AWS in the us-east-1 region on Alpine Linux? I know, very specific question 😄. But this looks like another issue over here: https://github.com/NuGet/NuGetGallery/issues/9396.

Could you run this command in your CI pipeline and provide the results? `dig +noedns +ignore api.nuget.org`

**Comment by KondorosiAttila** [comment]
Hey @joelverhagen it is exactly the case as you mentioned. Let me check the issue you linked

**Comment by joelverhagen** [comment]
Closing as a duplicate the. If you can, please provide the output of the `dig` command above, and for extra bonus points ✨ if you can provide a packet capture of a dig command reporting the truncated output, that would help our investigation a lot (as described in my latest comment: https://github.com/NuGet/NuGetGallery/issues/9396#issuecomment-1443767488)
