### ISSUE TITLE
[A11y]Focus order on Organization Management is not correct.

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#9420]
Url: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1744473

Environment Details:
App name: NuGet Service
#URL: [https://www.nuget.org](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.nuget.org%2f&data=05%7c01%7cv-nitipi%40microsoft.com%7c9a84307e7aa744a4b24208dafa5ca2fe%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638097573052590837%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=C8Eab3i6ixAmqsOjG4AxNT36z9WZQiXPbjDDkMcS5ME%3D&reserved=0)

OS and Browser Details:
Edition Windows 11 Enterprise
OS build 22621.1105.
Chrome version:  109.0.5414.120 (Official Build) (64-bit)

Repro Steps:
Hit the URL: https://www.nuget.org/
Navigate to "Sign in" control and hit enter.
Navigate to "Sign in with Microsoft" control and hit enter.
Select “Manage Organizations” from the Profile Dropdown and hit enter.
Navigate to "Add New" control and hit enter.
Enter values in "Organization Name" and "Organization Email Address" and hit enter on "Add" Control.
Again Select “Manage Organizations” from the Profile Dropdown and hit enter.
"Organizations" screen gets opened.
Navigate to Member and press enter.
Observe whether the focus order is incorrect after pressing "View Member Profile"

Actual Result:
The focus order is not in left to right order after expanding "View Member Profile"

Expected Result:
Keyboard focus order should move in logical order after pressing tab key "View member profile, Combo box and then Close button".

Notes:
This is probably due to the order of the elements in the DOM not matching the displayed order, as tab order is handled by browser (unless we explicitly override it)

**Comment by lyndaidaii** [comment]
This is duplicated of mine https://github.com/NuGet/NuGetGallery/issues/9450

**Comment by lyndaidaii** [comment]
close it as duplicate.
