### ISSUE TITLE
[NuGet.org Bug]: top 100 Community packages include MSFT packages

### ISSUE THREAD

**Issue by JanKrivanek** [NuGet/NuGetGallery#9427]
### Impact

I'm unable to use NuGet.org

### Describe the bug

some Microsoft packages (specifically Xamarin ones) showing up on the galley as community ones:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/3809076/223497680-553458e3-64f9-42ba-9dc9-280373df9a9c.png">
...
<img width="515" alt="image" src="https://user-images.githubusercontent.com/3809076/223497749-64c1eb84-bb70-4344-9aa7-630bd1bebcd7.png">

Those are not showing up when querying the `ddteldata` DS excluding the MSFT packages ([internal][query as link](https://dataexplorer.azure.com/clusters/ddteldata/databases/ClientToolsInsights?query=H4sIAAAAAAAAA23NMQvCQAyG4V3wP4TSoQURHRy7uQhaHdwl9tL22iOBXOAo+OOlUAXB9eN9+Gp/w2bEjo6SOAi6uF69wPlonhuDsyTSk9vAXQzDTzOIZ6g//JqYNIIw5IFa2y4Qqgpy9V3/XWaaelICFisW1mN8IE9FdvGNSpTWsrKcS1FHCs/pz7/hSLA/7N5FCuTRwgAAAA==)): 

```
NiPackageDownloads
| distinct LowerId, TotalDownloads
| join NiPackageOwners on $left.LowerId == $right.LowerId
| where not(Owners has_any("Microsoft"))
| order by TotalDownloads| take 150
```

### Repro Steps

1. Visit https://www.nuget.org/stats/packages
2. do not check 'Show all packages' checkbox
3. search for 'microsoft'

### Expected Behavior

Microsoft packages are not part of the community overview

**Comment by joelverhagen** [comment]
Thank you for bringing this to our attention, @JanKrivanek! Unfortunately the way this works today, we need to regularly update an "exclude list" of Microsoft packages to keep out of this list. It seems some new package IDs have crept in and gotten a lot of downloads.

We'll work to update the exclude list.

**Comment by agr** [comment]
I had the exclusion list updated, it should take effect tomorrow morning, I'll check back then.

**Comment by JanKrivanek** [comment]
Thank you for addressing this quickly!
