### ISSUE TITLE
[NuGet.org Bug]: Cannot sign-in

### ISSUE THREAD

**Issue by bwakabats** [NuGet/NuGetGallery#9431]
### Impact

I'm unable to use NuGet.org

### Describe the bug

My username is bwakabats

My email address is **REDACTED** (I do not have access to this email anymore but can sign-in to it using MS)

My new email address is **REDACTED**

I cannot sign-in to my **REDACTED** account

### Repro Steps

When I sign in as **REDACTED** (using MS) it says "The account with the email **REDACTED** is linked to another Microsoft account."

When I sign in to as **REDACTED** (using MS) I am told "Looks like we don't have an account with this email address (**REDACTED**) in our records." and asks me to sign-up, but I cant use the username "**REDACTED**" because its already taken.

When using the "Need assistance signing in" link, I enter the username "**REDACTED**" and the email address "**REDACTED**" and get an email saying "Our records indicate the associated Microsoft login(s): **REDACTED** **REDACTED**."

### Expected Behavior

I sign-in to my **REDACTED** account using one of the email addresses

**Comment by joelverhagen** [comment]
Hello, @bwakabats. Please contact support@nuget.org about this problem. We don't use the GitHub issue tracker for this type of problem since it contains personally identifiable information.
