### ISSUE TITLE
[NuGet.org Bug]: Prefix reservation C and c is not same.

### ISSUE THREAD

**Issue by chuongmep** [NuGet/NuGetGallery#9434]
### Impact

It bothers me. A fix would be nice

### Describe the bug

I have problem with publish package, I think in this case should be allow verify with user like : 

- Prefix  is `Chuongmep` also same with `chuongmep` because this username can't create by another account 
For instance, my package publish is Chuongmep.* but it can't because my user name is chuongmep.

### Repro Steps

Step to make this mistake; 
- Create a user name like : helloword
- Publish package with prefix is Helloword

### Expected Behavior

It should be accept for this case

### Screenshots

![image](https://user-images.githubusercontent.com/31106432/226303836-31737b41-1ad8-4759-b42f-a5e8cbd4c251.png)

### Additional Context and logs
https://www.nuget.org/packages/Chuongmep.Navis.Api.AdWindows

**Comment by joelverhagen** [comment]
> It should be accept for this case

Could you help me understand what specifically should be accepted? Are you asking for an automatic prefix reservation based on your username?

**Comment by chuongmep** [comment]
Hi @joelverhagen , my issue is look like that : 

Require of document to have a blue check is prefix name need same with username like : 
![image](https://user-images.githubusercontent.com/31106432/226358482-cf712725-4a65-4b68-86c0-25e3adec536b.png)
Now in my case is I had set my package with prefix name is `Chuongmep`, but my user name at the moment is `chuongmep`. with that problem, my package can't have tick blue, how to can have blue tick? 
https://www.nuget.org/packages/Chuongmep.Navis.Api.AdWindows

This post is say detail for that : https://devblogs.microsoft.com/nuget/package-identity-and-trust/

**Comment by joelverhagen** [comment]
This appears to be resolved. For future reference and for others, ID prefix reservation is not case sensitive, similar to how package IDs are not case sensitive.
