### ISSUE TITLE
[Feature]: Allow readme images from WakaTime

### ISSUE THREAD

**Issue by guibranco** [NuGet/NuGetGallery#9447]
### Related Problem

Allow `readme.md` files to reference images from [WakaTime](https://wakatime.com/).

WakaTime is an open source plugin for metrics about programming.
It tracks your time coding and display it's in a dashboard or via badges from https://wakatime.com domain

Sample markdown:

[![Time tracker](https://wakatime.com/badge/github/guibranco/CrispyWaffle.svg)](https://wakatime.com/badge/github/guibranco/CrispyWaffle)

### The Elevator Pitch

Add the domain wakatime.com to allowed images domains list in readme.md files

**Comment by guibranco** [comment]
Hi @lyndaidaii is this already in PROD ? I can't make it to work on NuGet page and also I can't find it on the [docs](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org). It was planned to 2023-04, but the PR was merged and then changed to 2023-05...The changes are already in main branch.

**Comment by lyndaidaii** [comment]
> Hi @lyndaidaii is this already in PROD ? I can't make it to work on NuGet page and also I can't find it on the [docs](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org). It was planned to 2023-04, but the PR was merged and then changed to 2023-05...The changes are already in main branch.
@guibranco, it's available in nuget.org now. Please let me know if you have any question.

**Comment by guibranco** [comment]
Hello @lyndaidaii, the documentation page at [Allowed domains for images and badges](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges) still not showing the `wakatime.com` domain
