### ISSUE TITLE
Ownership Invitation Email Additions

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#946]
This is what emails look like now for ownership invitations:

> **From:** <sourceuser> [sourceuser@redacted.com] 
> **To:** <targetuser> [targetuser@redacted.com]
> **Subject:** [NuGet Gallery] The user '<sourceuser>' wants to add you as an owner of the package '<packageid>'.
> 
> The user '<sourceuser>' wants to add you as an owner of the package '<packageid>'. If you do not want to be listed as an owner of this package, simply delete this email.
> To accept this request and become a listed owner of the package, click the following URL:
> <acceptanceurl>
> Thanks, The NuGet Gallery Team

When receiving these emails, here are the tasks I want to perform:
1. View the package page
2. View the source user's profile
3. Either accept or reject the invitation
4. When accepting, send a standard email to the source user
5. When rejecting, send an email to the source user with a message for why I rejected the invitation

To fulfill this workflow, I propose the email be changed to the following:

> **From:** <sourceuser> [sourceuser@redacted.com] 
> **To:** <targetuser> [targetuser@redacted.com]
> **Subject:** [NuGet Gallery] The user '<sourceuser>' wants to add you as an owner of the package '<packageid>'.
> 
> You have been invited to become a co-owner of a package on nuget.org.
> 
> **Package:**
> <packageid> - https://nuget.org/packages/<packageid>
> 
> **Current Owners:**
> <sourceuser> - https://nuget.org/profiles/<sourceuser>
> <otherowner1> - https://nuget.org/profiles/<otherowner1>
> <otherowner2> - https://nuget.org/profiles/<otherowner2>
> 
> To view this package and either accept or reject this invitation, log on to nuget.org and view the package page at https://nuget.org/packages/<packageid>.
> 
> Thanks,
> The NuGet Gallery Team

Then on the package details page, where the owners are displayed, when there's a pending invitation to become a co-owner of the package, two buttons should be shown for accepting or rejecting the invitation.

With either action, the user should be able to enter an optional message to send to the source user.  Whether a message is entered or not, a notification would go to the source user though.

Note that this approach not only caters to the actual workflow, but it also eliminates the need to save and send an ownership confirmation token.

_Note: the user of redacted.com is just for sake of illustrating that an email address would be shown_

**Comment by skofman1** [comment]
Many of those suggestions have been incorporated to the e-mail. No further work is needed in the area.
