### ISSUE TITLE
[Feature]: Simplify package lookup UI

### ISSUE THREAD

**Issue by mkArtakMSFT** [NuGet/NuGetGallery#9496]
### Related Problem

For many packages the NuGet UI has become very loaded and hard to read, given the number of packages on the list. It would be great to simplify it and I think it's possible.

For context, this is my second suggestion regarding making this UI simpler: https://github.com/NuGet/NuGetGallery/issues/9494

### The Elevator Pitch

Thanks for filing this, @JonDouglas.
Here are some more thoughts about this.
I think the goal of this page (for a given package) is to help the user to make a choice regarding which version of the package to take dependency on. As a framework and/or library author, I think it would make sense to (by default) show only the list of supported most recent packages from each major version and then provide options to see detailed list for all the minor versions too.
This can simplify the UI dramatically and result in shrinking the below view for [this package](https://www.nuget.org/packages/NuGet.Packaging) to the following table:
<img width="418" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/34246760/80076ff4-441b-4793-9f3b-415d6c4c2524">

| Version | Downloads | Last Updated |
| --- | --- | --- |
| 6.5.0 | 139,893 | 3 months ago |
| 5.11.3 | 214,167 | 7 months ago |
| 4.9.6 | 1,485 | 7 months ago |
| 3.5.0 | 477,579 | 12/14/2016 |

**Comment by agr** [comment]
https://github.com/NuGet/NuGetGallery/issues/9147 - duplicate?

**Comment by mkArtakMSFT** [comment]
Yes, thanks @agr !
