### ISSUE TITLE
[NuGet.org Bug]: Can't install package, but .net version is right.

### ISSUE THREAD

**Issue by AsakaJX** [NuGet/NuGetGallery#9497]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I want to install PowerShell package by Microsoft in VSCode, but I'm getting this weird error: 
```
error: NU1202: Package PowerShell 7.3.4 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package PowerShell 7.3.4 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
error: NU1212: Invalid project-package combination for PowerShell 7.3.4. DotnetToolReference project style can only contain references of the DotnetTool type 
error: Package 'PowerShell' is incompatible with 'all' frameworks in project 'd:/Projects/Eva/Source/Eva.csproj'.
```

### Repro Steps

Steps to reproduce:
1. Open Nuget Gallery
2. Search for PowerShell package.
3. Try to install package

### Expected Behavior

Package should install fine lol

**Comment by AsakaJX** [comment]
My .csproj:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Eva</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.33.0" />
    <PackageReference Include="TwitchLib" Version="3.5.3" />
    <PackageReference Include="TwitchLib.Api" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.Core" Version="3.9.0" />
    <PackageReference Include="TwitchLib.Api.V5" Version="3.3.0" />
  </ItemGroup>

</Project>
`

**Comment by joelverhagen** [comment]
The package appears to be a .NET tool, not a dependency package. Are you using one of the installation commands provided on the Gallery, for example:
```
dotnet tool install --global PowerShell --version 7.3.4
```

From your repro steps, it's not clear to me how you are actually performing the installation. You say in "VS Code", which tooling in particular? Could you provide a screenshot of the install button or command?

**Comment by AsakaJX** [comment]
I also tried to install using command that you provided and it installed fine I guess (?), but I can't figure out how to add it to my C# project.

**Comment by joelverhagen** [comment]
I haven't heard back from you, so I'll close this out.
