### ISSUE TITLE
[NuGet.org Bug]: FAQ goes to client FAQ, not server FAQ

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/NuGetGallery#9511]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The FAQ page on nuget.org redirects to https://learn.microsoft.com/en-us/nuget/resources/nuget-faq

There is however a better FAQ about NuGet.org that's located here: https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq

### Repro Steps

1. Open https://www.nuget.org/
2. Click on "FAQ" at the bottom
3. Directed to https://learn.microsoft.com/en-us/nuget/resources/nuget-faq

### Expected Behavior

1. Open https://www.nuget.org/
2. Click on "FAQ" at the bottom
3. Directed to https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq

**Comment by skofman1** [comment]
Fixed!
