### ISSUE TITLE
Unlisted packages show up in PowerShell AutoCompletion (Package-Ids API issue)

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#958]
_Ported from http://nuget.codeplex.com/workitem/2669_

**Repro Steps:**
1. Unlist a package from the gallery for eg. Portablelibtest
2. Open powershell and type install-package Portabl<tab>

**Actual:**
portablelibrarytest is listed 

https://nuget.org/api/v2/package-ids?partialId=Portabl 

["PortableArea","PortableClassLibrary1","Portablelibtest","PortableTPL"] 

**Expected:**
unlisted packages should not be returned by package-ids api

**Comment by robertmuehsig** [comment]
Isn't this tied to the "new" package catalog / search stuff with the v3 api or how could this issue be resolved?

**Comment by skofman1** [comment]
This behavior changed. Autocomplete doesn't show unlisted packages.
