### ISSUE TITLE
[NuGet.org Bug]: New package version stuck at validating

### ISSUE THREAD

**Issue by rvazarkar** [NuGet/NuGetGallery#9602]
### Impact

Other

### Describe the bug

A new version of the package was published yesterday and has been stuck in the validating state since then. This process usually takes minutes.

### Repro Steps

1. Upload a new package version

### Expected Behavior

Package validation should complete in a timely manner

### Screenshots

![image](https://github.com/NuGet/NuGetGallery/assets/5720446/2317c519-54cc-4160-a5d7-7a43c19cd58c)

### Additional Context and logs
Package is here:
https://www.nuget.org/packages/SharpHoundCommon

**Comment by rvazarkar** [comment]
Good afternoon,

Any updates on this?

Thanks,
Rohan

**Comment by joelverhagen** [comment]
We've identified the support request associated with this GitHub issue and will pursue the conversation over email.
