### ISSUE TITLE
[Feature]: expose repository information via v3 API

### ISSUE THREAD

**Issue by matt-phylum** [NuGet/NuGetGallery#9603]
### Related Problem

Most of the package metadata is exposed in the `PackageDetail` object. The [API documentation](https://learn.microsoft.com/en-us/nuget/api/catalog-resource#item-types) doesn't mention it, but the server is also returning a `repository` string, but it seems like it's always empty.

### The Elevator Pitch

The [`PackageDetail`](https://learn.microsoft.com/en-us/nuget/api/catalog-resource#item-types) object should contain the repository information as well so that it is available without having to download and parse the nuspec file inside the nupkg file. It already contains the license, project URL, description, etc.

### Additional Context and Details

In my case, I have the nuspec file, but it's inconsistent that I need to parse the repository URL out of the nuspec XML when the project URL and everything else is given to me in the API JSON.

This seems like it would be required for NuGet/Home#8584. The client can't cache all packages that the user might click on just to display the repository URL.

**Comment by joelverhagen** [comment]
Hey @matt-phylum, this is a reasonable request. We have it already tracked here: https://github.com/NuGet/NuGetGallery/issues/6262.

Closing as a duplicate.
