### ISSUE TITLE
[NuGet.org Bug]: The "install-tabs" no longer work

### ISSUE THREAD

**Issue by MarioZ** [NuGet/NuGetGallery#9637]
### Impact

It's more difficult to complete my work

### Describe the bug

Clicking between the installation tabs (e.g. ".NET CLI", "Package Manager", "PackageReference", "Paket CLI", "Script & Interactive", and "Cake") doesn't do anything anymore.
The displayed "tabpanel" remains being the ".NET CLI", it doesn't change.

### Repro Steps

1. You can use any package page, for example: https://www.nuget.org/packages/newtonsoft.json/
2. Click the "Package Manager" tab.
3. The tab panel remains being "> dotnet add package Newtonsoft.Json --version 13.0.3"

### Expected Behavior

The expected behavior is that the tab panel should display "NuGet\Install-Package Newtonsoft.Json -Version 13.0.3" when clicking the "Package Manager" tab.

### Screenshots

![issue](https://github.com/NuGet/NuGetGallery/assets/8082549/67e7a5df-e77f-4668-b17a-02b13849c587)

**Comment by Lanaparezanin** [comment]
Thank you for reporting this. We have rolled back the changes, it should work now. Our team is actively addressing the issue, we will keep you updated. Thanks again! Please let us know if there is any problem.
