### ISSUE TITLE
[Feature]: using custom PackageAuthenticationService class

### ISSUE THREAD

**Issue by Spork-Schivago** [NuGet/NuGetGallery#9667]
### Related Problem

NuGet.Server supports the use API keys, however, this support is very premative.    For example, NuGet.Server does not support retrieving api keys from secret managers like the Vault. 

### The Elevator Pitch

I would like to use my own custom PackageAuthenticationService that implements a more secure approach, such as using ephemeral API keys from the Vault.  I have modified the PackageAuthenticationService and added it to my ASP.NET Web Application (NET Framework) project but there doesn't seem to be any clear way to set NuGet.Server to use my custom class over it's built in one, maybe besides writing a custom resolver and setting NuGetODataConfig.cs to use my resolver instead.

Is there a way to accomplish what I want to accomplish, and if not, can it be implemented?   So NuGet.Server uses a custom PackageAuthenticationService?   Thanks.

**Comment by joelverhagen** [comment]
Hey @Spork-Schivago. NuGet.Server is in maintenance mode meaning our team will fix severe security issues (i.e. a security vulnerability) and severe bugs in existing behavior. This sounds like a new feature request for NuGet.Server which is something we won't be able to prioritize given our other commitments (e.g. maintaining and improving NuGet.org itself). I recommend forking the repository, cloning your fork, and giving it a try yourself if you need the functionality. 

It should be relatively straight forward to make a call out to Key Vault in an `IPackageAuthenticationService` implementation to determine if the given API key matches a value in Key Vault.

**Comment by Spork-Schivago** [comment]
Thank you for the response.    That is actually what I did, and yes, it was
pretty straight forward on my end.    I wish I could submit a merge
request, but I am not allowed to share the modifications.

Thank you again for the response.
