### ISSUE TITLE
[NuGet.org Bug]: api.nuget.org blocked by Checkpoint IPS

### ISSUE THREAD

**Issue by tcmailweb** [NuGet/NuGetGallery#9674]
### Impact

Other

### Describe the bug

We find that api.nuget.org is blocked by Checkpoint IPS, is this normal?

### Repro Steps

1. open terminal and run "curl -vk https://api.nuget.org/v3/index.json
2. get below result
3. * Establish HTTP proxy tunnel to api.nuget.org:443
> CONNECT api.nuget.org:443 HTTP/1.1
> Host: api.nuget.org:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 504 Gateway Timeout
< Pragma: no-cache
< Cache-Control: no-store
< Connection: keep-alive
< Proxy-Connection: keep-alive
< Content-Type: text/html
< Content-Length: 199
<
* Received HTTP code 504 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 504 from proxy after CONNECT

### Expected Behavior

1. open terminal and run "curl -vk https://api.nuget.org/v3/index.json
2. should be get the content in index.json

**Comment by zhhyu** [comment]
@tcmailweb My apologies for the inconvenience! Could you please follow this document: https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org and contact the support with more information? We will help you there. Thanks!

**Comment by zhhyu** [comment]
Hi, @tcmailweb! We will close this issue. If it is still ongoing, please reach out to support with more diagnose information. Thanks!
