### ISSUE TITLE
[NuGet.org Bug]: Unable to load the service index for source

### ISSUE THREAD

**Issue by MJEdwin** [NuGet/NuGetGallery#9699]
### Impact

I'm unable to use NuGet.org

### Describe the bug

error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.

### Repro Steps

1. Open the URL "https://api.nuget.org/v3/index.json"

### it show NET::ERR_CERT_DATE_INVALID on the edge.

Subject: nuget.cdn.azure.cn

Issuer: DigiCert Basic RSA CN CA G2

Expires on: 2023年10月8日

Current date: 2023年10月8日

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIGYTCCBUmgAwIBAgIQBbj9SpuvgrAgiMmGu61blzANBgkqhkiG9w0BAQsFADBK
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSQwIgYDVQQDExtE
aWdpQ2VydCBCYXNpYyBSU0EgQ04gQ0EgRzIwHhcNMjIxMDA3MDAwMDAwWhcNMjMx
MDA3MjM1OTU5WjBwMQswCQYDVQQGEwJDTjERMA8GA1UECBMIU2hhbmdoYWkxMTAv
BgNVBAoTKFNoYW5naGFpIEJsdWUgQ2xvdWQgVGVjaG5vbG9neSBDby4sIEx0ZC4x
GzAZBgNVBAMTEm51Z2V0LmNkbi5henVyZS5jbjCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAOdZYycmkw6LTTqjf5RWGBR5h13+VBao5TcHRmQ28H30ZpOq
w+xruD1VLkjnWjivgLkZ3AHFiDc/UOsX6WtRB5vXmqBVXtKXfs/Ppfg/PjDE9w3F
uvSYXU3QdfcwKMve1pUPSqatq6Qq2aBUuZZ57fjUA+cQD0emVdWFSyls2v8LkpJ0
3BLVJoezOJ5fbL9spf8hesuzcQ0KfO+VVjMCKmCAwFAZ6HRKrb0fiXAGUwjq4ixy
cWNSNifKH1hc6ni6I7Mp96CwCSkfxagMUg67TiwCoIB3JKPWLSTL1a6A+J2b34Uu
ditIV58qETlXqM42ygtcznCLAkkaJGLyClSQyskCAwEAAaOCAxswggMXMB8GA1Ud
IwQYMBaAFAa9pptgeVAxvtWpAkqg0JVTiy80MB0GA1UdDgQWBBRchlJUPZN6zRW3
qg3tYo/ZebgRGzAdBgNVHREEFjAUghJudWdldC5jZG4uYXp1cmUuY24wDgYDVR0P
AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBCBgNVHR8E
OzA5MDegNaAzhjFodHRwOi8vY3JsLmRpZ2ljZXJ0LmNuL0RpZ2lDZXJ0QmFzaWNS
U0FDTkNBRzIuY3JsMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkwJwYIKwYBBQUHAgEW
G2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzB2BggrBgEFBQcBAQRqMGgwIwYI
KwYBBQUHMAGGF2h0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNuMEEGCCsGAQUFBzAChjVo
dHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jbi9EaWdpQ2VydEJhc2ljUlNBQ05DQUcy
LmNydDAJBgNVHRMEAjAAMIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgAdgCt9776
fP8QyIudPZwePhhqtGcpXc+xDCTKhYY069yCigAAAYOv9Aq5AAAEAwBHMEUCIQC4
0diiEEjMsVH41oz86adzZhzADcfclMnGxcNJFhJkNQIgdRMYD7IqEYzM0plrAqh6
4zLcKaflBi1TkBsbT/36So0AdwCzc3cH4YRQ+GOG1gWp3BEJSnktsWcMC4fc8AMO
eTalmgAAAYOv9ArbAAAEAwBIMEYCIQCgzRZXle/hlsJ+wHxoQV6PNGn7pIZvTiDS
jIOj+sUpvAIhAP7D4IsKI310srZSXgBD49l+bZD+sG8ga9tRTx17m03EAHUAtz77
JN+cTbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkAAAGDr/QKsAAABAMARjBEAiAj
EfyD4U2K4Jv0qA4UrIu/9xd0IGCGEC4UaHEY+87RFgIga1KcSqUF48AGTOc9KTTS
4S3PZ5igIXPTCAwuhUa3XaQwDQYJKoZIhvcNAQELBQADggEBAHjDBPWj/8RJonlk
TsrNoW0uo1HF1sSSRAzQjFim7C7aBcdUVnI01cWEwr/fkPgNJ0TxO0EfdCO+64c2
104jiNa7/P67FEjhyaMotWH+eo4NiOwvcLi7AtB7q4JLzeeEVY/BMan7Xa237Ltk
1dhU1C9XJeJZcj0RCPz316GosR2pzKr1jbNlMEeyDXIPSGy5IL0UxrBSIw5RGMJE
YagvZH7sGT6XoV3nzuZLF1o0i9RFaO20OjHacukTNG1Qp9UFqvYWz0L04fooCJUg
bnjWtThYXWvd4VDka6azhMSE+k5/G21IpSmxXN5OYTkdqHhzNTpg4ecaYfsorXYt
J9aJ4HE=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFFTCCA/2gAwIBAgIQAvfh+YK60Amv9H3JV0Gy9jANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0yMDAzMDQxMjA0MDdaFw0zMDAzMDQxMjA0MDdaMEoxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJDAiBgNVBAMTG0RpZ2lDZXJ0IEJhc2lj
IFJTQSBDTiBDQSBHMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL49
9vplPYX4qjNjUI5QT6Ugcc8RjkWJFdcC2hMwvPbNQ6RLbjmvEBGHinnDlpBwb8FZ
kBGWVv+Djnfe9825hBwEH2iaI0D6QpjEd6Rb5EhHVGjIS4IcumpKkd3Q9tQaWPce
WB8TyC4H5XXPFRTR42t2K3qaZbdGPRp4PG3rsJLXgCG8M1cDVmi7cD9wMmji4kiy
0iL5/8VWajm09SHrHC0GFk5wwiGO7njyJqTU3afYaf5oXh1eBa1iK0FeHab7Cujx
E1afj/69v82GCigrUHyxNqnmypxpGz3vQ77HCY/jKvbYJKskqScBF/RGDE+SKuxz
w/+N2E42Iy//QT8bjLMCAwEAAaOCAd4wggHaMB0GA1UdDgQWBBQGvaabYHlQMb7V
qQJKoNCVU4svNDAfBgNVHSMEGDAWgBQD3lA1VtFMu2bwo+IbG8OXsj3RVTAOBgNV
HQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1Ud
EwEB/wQIMAYBAf8CAQAwMwYIKwYBBQUHAQEEJzAlMCMGCCsGAQUFBzABhhdodHRw
Oi8vb2NzcC5kaWdpY2VydC5jbjBABgNVHR8EOTA3MDWgM6Axhi9odHRwOi8vY3Js
LmRpZ2ljZXJ0LmNuL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNybDCB3QYDVR0gBIHV
MIHSMIHFBglghkgBhv1sAQEwgbcwKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRp
Z2ljZXJ0LmNvbS9DUFMwgYoGCCsGAQUFBwICMH4MfEFueSB1c2Ugb2YgdGhpcyBD
ZXJ0aWZpY2F0ZSBjb25zdGl0dXRlcyBhY2NlcHRhbmNlIG9mIHRoZSBSZWx5aW5n
IFBhcnR5IEFncmVlbWVudCBsb2NhdGVkIGF0IGh0dHBzOi8vd3d3LmRpZ2ljZXJ0
LmNvbS9ycGEtdWEwCAYGZ4EMAQICMA0GCSqGSIb3DQEBCwUAA4IBAQANZCJXBl6U
B2ISUsgfnEc7dgLQM5X8vAOq1xlO5p2d70I1TCdnGM/+RAsrlHvQH5hyHq+7yqJ4
YsnpvM8GHn+2WIXVgFzeUf9o0gcIN1h5SWDooMXGjdS42MUosuAsTH2reeBuNL4U
MDJoTw5mIwTRG2Qi3z74VVTJvXRPJYJL+SrY9HdRH382YEAXK5go4aRMaqvXY/Ob
TfGIL0tKLy1Mg5oaWa1SlNTgmar+gEsSGLuB8LY1yR7vIpLMCbJEF83TnCcqw8hA
NRJiGhVFyRB75UDuSHQi5rveZupfzfAf6OayAEk5NjemjOuD5AgeXvnyl83rPOJ3
wAx1cXMDxcLU
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
-----END CERTIFICATE-----

**Comment by zhhyu** [comment]
Hello! My apologies for this inconvenience. Please check the status page: https://status.nuget.org/. The mitigation is being rolled out.

**Comment by zhhyu** [comment]
Hello! The incident has been mitigated. We will close this issue. Feel free to reopen the issue if it is still ongoing. Thanks!

**Comment by seikosantana** [comment]
Hi, i am experiencing this issue only on my VPS again. It's the second time. Last time it fixes itself. Checked nuget service status and everything is operational.

Tried many things including
- Deleting nuget local caches
- Deleting nuget config
- Flushing DNS
- Updating the SDK
- Running restore with `--interactive`
- Running restore with `--disable-parallel`
- Running restore with `/p:EnableDefaultItems=false`

The only method that worked was to use v2 source `-s https://www.nuget.org/api/v2`, and now it restores successfully.

**Comment by zhhyu** [comment]
@seikosantana My apologies for this inconvenience! Could you please follow this document and reach out to support with more information? https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org 

NuGet.org depends on CDN to deliver packages in different regions, and one important piece of information is the geographical area of your failing machine. Thanks!

**Comment by seikosantana** [comment]
Hi @zhhyu 
According the the hosting client area, the Ubuntu VPS is located in Los Angeles.

I currently use a shell script to automate the builds in the VPS and for now i've made it default to v2 source and haven't tried the v3 again.
