### ISSUE TITLE
[NuGet.org Bug]: SSH.NET download count issue

### ISSUE THREAD

**Issue by WojciechNagorski** [NuGet/NuGetGallery#9708]
### Impact

Other

### Describe the bug

Two days ago I released a new version of SSH.NET, but the download counter still shows **0**:
https://www.nuget.org/packages/SSH.NET/2023.0.0
I have downloaded this package many times and updated it in other open source projects.

### Repro Steps

Open page https://www.nuget.org/packages/SSH.NET/2023.0.0

### Expected Behavior

The counter should be greater then 0.

### Screenshots

<img width="570" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/17333903/39373c55-a4c6-43ab-8e7c-f34e04960b55">

### Additional Context and logs

For instance I've updated this package in the following projects. 
https://github.com/testcontainers/testcontainers-dotnet/pull/1019
https://github.com/mRemoteNG/mRemoteNG/pull/2503
Both examples build in Github Actions.

**Comment by joelverhagen** [comment]
Hello, apologies for the delay in responded. We weren't able to track down a root cause for this 2 day delay but see now that your download counts are incrementing as you may expect. If this problem returns, please feel free to open a new issue.
