### ISSUE TITLE
[NuGet.org Bug]: Incorrect download number in Most Downloaded Packages page

### ISSUE THREAD

**Issue by tonyqus** [NuGet/NuGetGallery#9709]
### Impact

It's more difficult to complete my work

### Describe the bug

I'm checking the ranking of MimeKit in https://www.nuget.org/stats/packages page. But I notice a weird thing. The downloads in this page is different from the one on [MimeKit homepage]().

![image](https://github.com/NuGet/NuGetGallery/assets/772561/f89f87c5-477b-4148-8b0c-903226133eda)

This is the number on MimeKit homepage
![image](https://github.com/NuGet/NuGetGallery/assets/772561/cc0544a6-136e-4e99-b0dd-917e599fc5ec)

Can you double check your distinct logic? I'm afraid it's a bug.

### Repro Steps

1. Go to https://www.nuget.org/stats/packages
2. Pick any package and record the download number
3. Go inside to the package homepage and record the total download number

### Expected Behavior

The download number on stats/packages page should be same as the one on package homepage

**Comment by joelverhagen** [comment]
The number (5.1 million) on the /stats/packages page is the total _over the past 6 weeks_. The number on the package details page (106 million) is the total of all time.

They will always be different unless that package is first published (newly created package ID) in the past 6 weeks, in which case they will be the same or very close.

The MimeKit package was first published in 2016 so it has had a long time to accumulate downloads.

**Comment by joelverhagen** [comment]
On pages where the data is from the past 6 weeks, you'll see a notice like this on the page:
![image](https://github.com/NuGet/NuGetGallery/assets/94054/c82ba684-6fe6-49cc-aa75-04eb4023883f)
