### ISSUE TITLE
[NuGet.org Bug]: `net7.0-android` does not show as a computed compatible framework for a `net6.0-android` package

### ISSUE THREAD

**Issue by jpobst** [NuGet/NuGetGallery#9711]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The "Frameworks" tab for a `net6.0-android` NuGet package does not show `net7.0-android` as a computed compatible framework.  This leads users to believe that our packages our not usable by .NET 7 Android apps.

Example:
https://www.nuget.org/packages/Xamarin.AndroidX.Core#supportedframeworks-body-tab

Note it is likely caused by the additional Android version in the moniker.  For example, `net7.0-android` shows up as a computed framework for Json.NET:

https://www.nuget.org/packages/Newtonsoft.Json#supportedframeworks-body-tab

Also note we only specify `net6.0-android` in our `.csproj` file, the Android version is added automatically by `pack`:

https://github.com/xamarin/AndroidX/blob/main/Directory.Build.props#L9

### Repro Steps

Open URL: https://www.nuget.org/packages/Xamarin.AndroidX.Core#supportedframeworks-body-tab

### Expected Behavior

`net7.0-android` should be listed as an "Additional computed target framework(s)".

**Comment by jpobst** [comment]
As an additional note, though it becomes less important as time goes by, `monoandroidXX` packages are also considered compatible with `net6.0-android` and `net7.0-android`, so they should be listed as computed compatible frameworks here also:

https://www.nuget.org/packages/Xamarin.AndroidX.Migration

**Comment by IrinaPykhova** [comment]
the same about net8.0-android

**Comment by advay26** [comment]
We have a fix out for this bug: https://github.com/NuGet/NuGetGallery/pull/9741

A `net6.0-android31.0` package will now show something like this for its computed frameworks:
![image](https://github.com/NuGet/NuGetGallery/assets/82980589/769db831-b83d-447c-a58e-85bab98a522b)
See https://www.nuget.org/packages/Xamarin.AndroidX.Core/1.12.0#supportedframeworks-body-tab
