### ISSUE TITLE
[NuGet.org Bug]: net8.0-windows does not show as a computed compatible framework for a net6.0-windows and net7.0-windows packages

### ISSUE THREAD

**Issue by IrinaPykhova** [NuGet/NuGetGallery#9734]
### Impact

It's more difficult to complete my work

### Describe the bug

We are developing .Net controls for different platforms. This month we tested all our controls for compatibility with .Net 8. .Net 6 packages are fully compatible and can work under .Net 8, but Nuget.org doesn't show net8.0-windows in the list of computed frameworks for all the packages which target net6.0-windows.
The same happens with other platforms like Android or iOS: https://github.com/NuGet/NuGetGallery/issues/9711

Nuget.org only shows net8.0 for all platforms if original target is net6.0 without platform specifier. But it is not possible to use for WinForms or WPF packages.

### Repro Steps

Open this link: https://www.nuget.org/packages/C1.WPF.Core/7.0.20233.662#supportedframeworks-body-tab

### Expected Behavior

net8.0-windows should present in the list of additional computed target frameworks

### Screenshots

![image](https://github.com/NuGet/NuGetGallery/assets/19591075/e4005849-0a3b-4939-bfe6-bb08848be3fd)

**Comment by joelverhagen** [comment]
cc @advay26 and @dannyjdev who have worked on this area.

**Comment by Romfos** [comment]
Hi, any comments, updates on this?

**Comment by ShellBrowserWeber** [comment]
We have the same problem.
