### ISSUE TITLE
Broken doc link for 3 ways to mitigate risk when using private package

### ISSUE THREAD

**Issue by erdembayar** [NuGet/NuGetGallery#9762]
Below link is not working here: https://learn.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds
I believe it should point here: https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf
![image](https://github.com/NuGet/NuGetGallery/assets/8766776/49423b3c-acdd-44f0-9892-c031196aa7e6)

**Comment by erdembayar** [comment]
Refiled at https://github.com/NuGet/docs.microsoft.com-nuget/issues/3198

**Comment by sidoruk-sv** [comment]
@erdembayar looks like it is now reversed:

This link is only working: https://learn.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds
This link leads to nowhere: https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf

**Comment by erdembayar** [comment]
> @erdembayar looks like it is now reversed:
> 
> This link is only working: https://learn.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds This link leads to nowhere: https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf

I moved from that team.
cc @nkolev92 current member.

**Comment by medhatfawzy** [comment]
https://web.archive.org/web/20210210114409/https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf

You can use this link for now to access the PDF. I have also attached it
[3 Ways to Mitigate Risk When Using Private Package Feeds - v1.0.pdf](https://github.com/user-attachments/files/18218625/3.Ways.to.Mitigate.Risk.When.Using.Private.Package.Feeds.-.v1.0.pdf)
