### ISSUE TITLE
[NuGet.org Bug]: Unable to access api.nuget.org using the .NET SDK, but can access it using curl or Firefox.

### ISSUE THREAD

**Issue by gimbling-away** [NuGet/NuGetGallery#9769]
### Impact

I'm unable to use NuGet.org

### Describe the bug

When I do `dotnet restore`, it times out while fetching https://api.nuget.org/v3/index.json but I can access it using curl or open it in Firefox.

Note: I honestly have no idea whether this is a .NET SDK bug or a NuGet.org problem. The original issue at `dotnet/sdk` for this is https://github.com/dotnet/sdk/issues/37673. I did see similar issues regarding connectivity to the API in this repo, so felt this should be the place. I apologize if this is the wrong place. 😅

### Repro Steps

- Open any .NET project
- Run `dotnet restore`

### Expected Behavior

Not time out

### Screenshots

![image](https://github.com/NuGet/NuGetGallery/assets/93856041/e3249471-68e1-4a0a-9922-61feca67d1e4)

**Comment by gimbling-away** [comment]
Going through some older similar issues, `--disable-parallel` doesn't seem to help either

**Comment by gimbling-away** [comment]
Weird, I tried using a VPN and it *instantly* restores. That doesn't explain why I am able to access the API using curl or Firefox though *without* the VPN.

**Comment by zhhyu** [comment]
Hi! My apologies for this inconvenience! Some intermittent failures were detected in some regions and likely our CDN provider in your region had a regression at that time. If it is still happening, could you please follow this document (https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org) and send more diagnose information to the support mailbox? There are also some suggestions in the document that should help you enhance the resilience on the client side.

Feel free to reach out to the support mailbox or open an issue under this repo at any time when you meet failures!

**Comment by gimbling-away** [comment]
Hey \o

Can still reproduce it unfortunately :(
- FSharp.Core (Default F# project)
- `dotnet nuget --version`: `6.8.0.32767` `dotnet --version`: `8.0.100`
- [Log.txt](https://github.com/NuGet/NuGetGallery/files/13826676/Log.txt)
- MTR or a Fiddler traces (On Linux, sorry! No idea how to setup either)
- Geographical Area (India)
- No proxy or a firewall
- It is a local machine, no cloud service involved.

**Comment by Ben305** [comment]
Possibly related: https://github.com/NuGet/Home/issues/13148

**Comment by gimbling-away** [comment]
Can't reproduce anymore, seems fixed, cheers! 🥳
