### ISSUE TITLE
[NuGet.org Bug] Stats: Community Packages shows non-Community Packages #3

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#9772]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The Community Packages shows non-Community Packages. 

### Repro Steps

1. go to https://www.nuget.org/stats/packages

### Expected Behavior

Not showing Microsoft packages when "Show all packages" isn't checked. Currently multiple microsoft.* packages are shown

Related #8456, https://github.com/NuGet/NuGetGallery/issues/7314

**Comment by 304NotModified** [comment]
@shishirx34 could you please help in fixing this again? You've solved the previous (#8456) one nicely :)

**Comment by skofman1** [comment]
This is fixed now.
