### ISSUE TITLE
[NuGet.org Bug]: Unable to upload package

### ISSUE THREAD

**Issue by dbuenor** [NuGet/NuGetGallery#9777]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Hi, i'm trying to upload package using "Upload" button at https://www.nuget.org/packages/upload, but i'm receiving "The package ID 'PackageName' is not available.".
I checked package name and is "supposed" to be not registered previously but is not letting me register anyways. Is a modification/version for an existing library registered previously on NuGet, but prefix is not registered (it hasn't have blue check)

Can you help me to check if is registered or not?

My library name was: "EasyNetQ.Legacy.NetStandard"

and former/based library is "EasyNetQ" (https://www.nuget.org/packages/EasyNetQ/8.0.0-beta95)

### Repro Steps

Try to upload new package called "EasyNetQ.Legacy.NetStandard"

### Expected Behavior

I expect nuget to let me upload my new package because is supposed to be "free".

### Screenshots

![Capture](https://github.com/NuGet/NuGetGallery/assets/16104257/fd5176ba-2f08-4c3a-b19c-f09a3915712b)

**Comment by zhhyu** [comment]
Hi! Please reach out to the support mailbox. This is one issue that will be solved there. Thanks!
