### ISSUE TITLE
Given fuget is always down should it be removed as a link from the gallery?

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#9783]

**Comment by SimonCropp** [comment]
still down

**Comment by fowl2** [comment]
I think they disabled the link

**Comment by 304NotModified** [comment]
The link seems disabled indeed, but I can't find the commit for it.

FYI: fuget is still down

**Comment by joelverhagen** [comment]
@304NotModified, we have a feature flag (dynamic configuration) to disable/enable the FuGet link without making a code change, or even a deployment. It is currently in the disabled state because FuGet is down.

**Comment by SimonCropp** [comment]
@joelverhagen thanks
