### ISSUE TITLE
[Feature]: Adding https://raw.githubusercontent.com/ to Trusted Domain

### ISSUE THREAD

**Issue by d1820** [NuGet/NuGetGallery#9799]
### Related Problem

Images hosted in a repo that can be served up in the readme should be allowed to be trusted esp since github.com is already a trusted domain

### The Elevator Pitch

If github.com is already on the list adding the ability to serve raw image content from a subdomain of theirs should be allowed as well

### Additional Context and Details

Can view Example here: https://www.nuget.org/packages/DanTurco.GoogleMapExport2KML/

references images like 
https://raw.githubusercontent.com/d1820/GoogleMapExport2KML/ac9c689f9df0b1c023bd574eb1ac3d2677a4cb3b/GifInstructions/typical.gif

**Comment by erdembayar** [comment]
@d1820 
Could you please take a look at https://github.com/NuGet/NuGetGallery/pull/9857?  
The similar request was addressed in above PR. If it makes sense, could you please make a PR?

**Comment by d1820** [comment]
Issue resolved. raw.githubusercontent.com is already in the trusted domains file. Turns out there was a github redirect happening with my links, that i didnt notice until i saw the trusted domain file.
