### ISSUE TITLE
[NuGet.org Bug]: Package download numbers are not incrementing

### ISSUE THREAD

**Issue by bruno-garcia** [NuGet/NuGetGallery#9800]
### Impact

I'm unable to use NuGet.org

### Describe the bug

using `https://api.nuget.org/v3/index.json` and the search API, we've seen the same number return since January 20th.

```
 Sentry     | 2024-01-21 00:00:00 |       46888265
 Sentry     | 2024-01-20 00:00:00 |       46888265
 Sentry     | 2024-01-19 00:00:00 |       46804424
 Sentry     | 2024-01-18 00:00:00 |       46712023
```

Original NuGet Trends issue: 
* https://github.com/dotnet/nuget-trends/issues/258

### Repro Steps

Hit the NuGet API: https://azuresearch-usnc.nuget.org/query?q=Sentry

![image](https://github.com/NuGet/NuGetGallery/assets/1633368/6d59168e-7c70-418e-b4ed-4cca3d912580)

You can observe no change in days through NuGet Trends: https://nugettrends.com/packages?months=24&ids=Sentry

![image](https://github.com/NuGet/NuGetGallery/assets/1633368/30d33601-e63f-43ef-bbdd-2ad7ef43990a)

### Expected Behavior

Value to match NuGet Gallery
![image](https://github.com/NuGet/NuGetGallery/assets/1633368/ece4d15f-94c0-4d48-8e4f-c0a280de8853)

https://www.nuget.org/packages/Sentry

![image](https://github.com/NuGet/NuGetGallery/assets/1633368/0c81e9d5-4842-4615-ab84-318b90868137)

### Screenshots

above

### Additional Context and logs

its been raised here:

* https://github.com/NuGet/NuGetGallery/issues/9791#issuecomment-1937101754

**Comment by ivarconr** [comment]
Seems to be resolved now 👍🏼

**Comment by bruno-garcia** [comment]
woo! Thanks
