### ISSUE TITLE
Failing to upload nuget package on fresh install of NuGet Gallery

### ISSUE THREAD

**Issue by FraserElectronics** [NuGet/NuGetGallery#9802]
### Impact

I'm unable to use this version

### Describe the bug

I have built and installed NugGetGallery on my Azure account as per the instructions given in this repository.  I have created an account on my NuGetGallery site and then created an API key. When I try and push a nuget package from the Package Manager Console in Visual Studio 2022 I get:

```
dotnet nuget push .\MyNugetPackage.1.0.0.nupkg --api-key ********************************************** --source https://******.azurewebsites.net
Pushing MyNugetPackage.1.0.0.nupkg to 'https://******.azurewebsites.net'...
  PUT https://******.azurewebsites.net/api/v2/package/
  InternalServerError https://******.azurewebsites.net/api/v2/package/ 411ms
  PUT https://******.azurewebsites.net/api/v2/package/
  InternalServerError https://******.azurewebsites.net/api/v2/package/ 120ms
  PUT https://******.azurewebsites.net/api/v2/package/
  InternalServerError https://******.azurewebsites.net/api/v2/package/ 123ms
error: Response status code does not indicate success: 500 (The remote server returned an error: (409) Conflict.).
```

If I use the Upload option on the website and browse to my nupkg, it fills in all the fields correctly but when I click the Submit button, it shows:

![image](https://github.com/NuGet/NuGetGallery/assets/19693425/a37ea436-9673-4790-a704-2e017fe065a2)

I know there is not much information to go on but was wondering if anyone can point me in the direction of getting more diagnostic information as to why this fails.

Andy

### Repro Steps

Cloned NuGetGallery
Built and installed into Azure as documented.
Created a user account on the NuGetGallery website and generated an API key.
Tried to push a nuget package to the site using the generated API key.

### Expected Behavior

This is a very basic nuget package containing a simple .NET assembly. I would expect it to upload without problem.

**Comment by erdembayar** [comment]
Is this duplicate of https://github.com/NuGet/NuGetGallery/issues/9850?

**Comment by FraserElectronics** [comment]
@erdembayar Yes, I had forgotten that I had posted this as there was no response. I will close this issue and keep #9850 open.

Thanks.

Andy
