### ISSUE TITLE
[Self-hosted Bug]: Need guidance for mirroring

### ISSUE THREAD

**Issue by EdLichtman** [NuGet/NuGetGallery#9821]
### Impact

It's more difficult to complete my work

### Describe the bug

Every time a new package comes out I have to manually delete it. I've tried creating my own mirror, but it's not very resource effective, and not easy to use. So I'd like to use NuGetMirror. However, NuGetMirror only allows me to download the packages to a folder, it doesn't "relist" or "refresh the cache" of the package.

Do you have guidance on mirroring? and if it's not documented, could it be documented somewhere on the page that teaches you how to set up a NuGet Gallery yourself?

### Repro Steps

Kind of self-explanatory. Not a bug, but there wasn't really another option that I could choose.

### Expected Behavior

I expect to not have to download and list each package the moment they come out manually. Obviously that's not guaranteed with your software. but I would like guidance on how I can use this in a sane fashion without creating a brand new mirror myself.

**Comment by erdembayar** [comment]
@EdLichtman 
Thank you for filing this issue. Are you using https://github.com/emgarten/nuget.catalogreader for this? If yes, could you please create an issue in that repo? 

If not, could you please explain exactly what you're trying to accomplish? We couldn't understand why you want to delete the package if you want a mirror, I feel there are contradictory.
