### ISSUE TITLE
[NuGet.org Bug]: Markdown links not rendered correctly

### ISSUE THREAD

**Issue by gregsdennis** [NuGet/NuGetGallery#9823]
### Impact

It bothers me. A fix would be nice

### Describe the bug

It appears markdown links aren't being processed at all.

The text

```
This library conforms to the IETF JSON Path specification [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535.html).
```

should be rendered as it does on GitHub:

This library conforms to the IETF JSON Path specification [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535.html).

However, it appears to be unprocessed and the plain text is rendering.

### Repro Steps

Visible with the package: https://www.nuget.org/packages/JsonPath.Net/1.0.0#readme-body-tab

### Expected Behavior

I expect the markdown link to be processed.

### Screenshots

<img width="660" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/2676804/91466bc4-28a3-4b98-9b89-407fd052e530">

### Additional Context and logs

I'm setting this readme in the _.csproj_ file.  Maybe there's something going on with the XML translation and I'm just doing it wrong.

https://github.com/gregsdennis/json-everything/blob/106ff1dcf91ff8d79b61dbedc1d0e1704b3e714e/JsonPath/JsonPath.csproj#L10-L16

**Comment by erdembayar** [comment]
@gregsdennis 
Thank you for filing this issue. Unfortunately, below is not proper markdown, please don't put in csproj file.
https://github.com/gregsdennis/json-everything/blob/106ff1dcf91ff8d79b61dbedc1d0e1704b3e714e/JsonPath/JsonPath.csproj#L10-L16

Could you please take a look at this package where it done properly? https://www.nuget.org/packages/Newtonsoft.Json#readme-body-tab

You need to create actual Readme.md file and put it in there, please check for [Readme best practices](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/).

**Comment by gregsdennis** [comment]
Are you saying I need to create a separate readme for the nuget packages?  I have a readme for the entire project which is not suitable for packages as the project published multiple nuget packages.

**Comment by gregsdennis** [comment]
> below is not proper markdown

Pedantically, it _is_ proper markdown.  Are you saying that markdown just isn't supported when the text is defined directly in the csproj?  If so, I suppose that's what this issue is about.

Since Nuget READMEs permit markdown and the `<Description>` tag contents act as a README, it follows that markdown should be supported in the `<Description>` tag.

**Comment by erdembayar** [comment]
> > below is not proper markdown
> 
> Pedantically, it _is_ proper markdown. Are you saying that markdown just isn't supported when the text is defined directly in the csproj? If so, I suppose that's what this issue is about.
> 
> Since Nuget READMEs permit markdown and the `<Description>` tag contents act as a README, it follows that markdown should be supported in the `<Description>` tag.

Here is our doc description: https://learn.microsoft.com/en-us/nuget/reference/nuspec#description, either you use nuspec file or csproj file they're xml file.
