### ISSUE TITLE
NuGet package size limit

### ISSUE THREAD

**Issue by v-manil2** [NuGet/NuGetGallery#9848]
### Related Problem

Hello,  

Is there a way to increase the package size limit? 

We have a package including native libs and support for multiple platforms and archs, but we started getting over the 250MB limit for the next release we’re preparing and NuGet is rejecting the push. 

Is there a way to get an exception?

### The Elevator Pitch

It would be good if the package size limit is increased.

**Comment by erdembayar** [comment]
Dup of https://github.com/NuGet/NuGetGallery/issues/9473
Please go to that one upvote there. If you believe this issue is different than above, feel free to reopen this one.
cc @JonDouglas
