### ISSUE TITLE
[NuGet.org]: The uploaded symbols package contains one or more pdbs that are not portable

### ISSUE THREAD

**Issue by darrenge** [NuGet/NuGetGallery#9855]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I am trying to push a file to Nuget.org and I am getting this message during validation \ indexing:  The uploaded symbols package contains one or more pdbs that are not portable.

I found issue #7668 which is exactly my problem.  I went through and changed all the < DebugType > to portable and that didn't help. I went through and removed all < DebugType > and that didn't work. #7668 is almost 5 years old so maybe there is different guidance.

### Repro Steps

Trying to push to: https://www.nuget.org/packages/Microsoft.Garnet/
Unfortunately, our code isn't public ... yet, so can't point you to the GitHub repo
Uncheck the 'list in search result"

Strangely enough, we have another Nuget package https://www.nuget.org/packages/Microsoft.FASTER.Core and that has < DebugType > as full and that is pushed ok so I am thinking it is no longer < DebugType > and must be something else.

### Expected Behavior

Our nuget package gets uploaded \ verified \ indexed

**Comment by darrenge** [comment]
I think you guys understand this but want to make sure... the package file (nupkg) gets uploaded fine. It is the symbols file (snupkg) that fails validation.

**Comment by darrenge** [comment]
Our repo is public.  You can view it here: https://github.com/microsoft/Garnet  We put all the < DebugType > back but seems like there is another reason we can't get the symbols validated.

**Comment by darrenge** [comment]
Our github repo is now public.  You can check it out if you want and let me know what it would take to get the symbols in our Nuget packge.  https://github.com/microsoft/Garnet

**Comment by erdembayar** [comment]
Taking offline.

**Comment by darrenge** [comment]
To wrap this up ... We got help and found the one PDB that was problematic. It was a C++ native DLL / PDB.  We just removed it from the nuspec and the symbols passed validation.  We did NOT change the < DebugType > on any of the projects.
