### ISSUE TITLE
[Feature]: Support media.githubusercontent.com for images in README 

### ISSUE THREAD

**Issue by pascalberger** [NuGet/NuGetGallery#9856]
### Related Problem

LFS tracked images on GitHub are server on media.githubusercontent.com not raw.githubusercontent.com and therefore are not displayed in README files.

### The Elevator Pitch

Allow to show LFS tracked images from GitHub repositories in README files.

**Comment by erdembayar** [comment]
PR is already merged, feel free to re-open if we missed anything.
