### ISSUE TITLE
[NuGet.org Bug]: Can not use "https://int.nugettest.org/" as source to consume nuget pkg

### ISSUE THREAD

**Issue by zstdxxf** [NuGet/NuGetGallery#9874]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Can not use "https://int.nugettest.org/" as source to consume nuget pkg

### Repro Steps

1. Set "https://int.nugettest.org/" as source to consume nuget pkg in VS2019
![img_v3_0296_40808445-3d6f-4a07-be6c-6c626996738g](https://github.com/NuGet/NuGetGallery/assets/10097167/9909c0df-c0dd-4ec9-875b-6e376e06079e)

2. Try to get pkg to consume in VS 2019, but cannot get pkg to cosume and encounter some error
![image](https://github.com/NuGet/NuGetGallery/assets/10097167/7fa98be1-7f9f-4e96-b11b-e358ea2e8729)

### Expected Behavior

Expect can use "https://int.nugettest.org/" as source and search some nuget pkg and install to consume

**Comment by zhhyu** [comment]
Hi! This is not the correct URL to consume INT packages. Please try this one: https://apiint.nugettest.org/v3/index.json
