### ISSUE TITLE
[UI] Verify that new themes are compatible with old browsers

### ISSUE THREAD

**Issue by martinrrm** [NuGet/NuGetGallery#9875]
Had a talk with Joel about the support of CSS variables and how this could be a concern for old browsers, specially IE. For the moment we decided to continue using CSS variables since it make's the job easier, after merging into DEV we will verify that for IE, the page is usable.

**Comment by mariaghiondea** [comment]
@martinrrm is this one done?

**Comment by martinrrm** [comment]
@mariaghiondea Yes, I'm closing it, page has the same functionality as before. I tested using Internet Explorer, users can still navigate through the website but is not the best experience.
