### ISSUE TITLE
https://api.nuget.org/v3/index.json randomly return ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by tai-yi** [NuGet/NuGetGallery#9884]
### Impact

I'm unable to use NuGet.org

### Describe the bug

When access `https://api.nuget.org/v3/index.json ` randomly return ERR_EMPTY_RESPONSE

Seems some backend server or CDN down.

Region : China

### Repro Steps

Access https://api.nuget.org/v3/index.json multiple times

### Expected Behavior

return correct json

### Additional Context and logs

This page isn’t working
nuget.cdn.azure.cn didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by yangon99** [comment]
This happened on Feb 6 but was fixed a few days later.
It seems that nuget.cdn.azure.cn is to blame for this error. And we don't have a way to know where to report the network issue.

**Comment by tai-yi** [comment]
Now it works well, I find a e-mail link on nuget.org website.  
`support@nuget.org`
