### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by vivekpv1020** [NuGet/NuGetGallery#9898]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I am using Visual Studio 2022 for Devlopment.I am facing issue starting from 29th March 2024 that i can't restore Nuget packages.I tried all possible options and it is not working ..Can someone look on this issue

PM> dotnet restore
  Determining projects to restore...
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'.
  An error occurred while sending the request.
    The response ended prematurely. (ResponseEnded)
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  An error occurred while sending the request.
    The response ended prematurely. (ResponseEnded)
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error :   End of Central Directory record could not be found. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : Failed to download package 'Microsoft.Extensions.Logging.5.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg'. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/5.0.0/microsoft.extensions.logging.5.0.0.nupkg' is not valid. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error :   End of Central Directory record could not be found. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : An error occurred while sending the request. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error :   The response ended prematurely. (ResponseEnded) [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
  Failed to restore C:\CCSDXP\ccs-dxp\src\Dxa.Test\Dxa.Test.csproj (in 16.88 sec).
  Failed to restore C:\CCSDXP\ccs-dxp\src\dxa.web\Dxa.Web.csproj (in 14.39 sec).
PM> dotnet restore
  Determining projects to restore...
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid.
    End of Central Directory record could not be found.
  Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'.
  An error occurred while sending the request.
    The response ended prematurely. (ResponseEnded)
  Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'.
  The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : Failed to download package 'Microsoft.Extensions.WebEncoders.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg'. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : The nupkg at 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.webencoders/2.0.0/microsoft.extensions.webencoders.2.0.0.nupkg' is not valid. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error :   End of Central Directory record could not be found. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : Failed to download package 'System.Linq.Async.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg'. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error : The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
C:\Program Files\dotnet\sdk\8.0.202\NuGet.targets(169,5): error :   End of Central Directory record could not be found. [C:\CCSDXP\ccs-dxp\src\Dxa.sln]
  Failed to restore C:\CCSDXP\ccs-dxp\src\dxa.web\Dxa.Web.csproj (in 13.33 sec).
  Failed to restore C:\CCSDXP\ccs-dxp\src\Dxa.Test\Dxa.Test.csproj (in 13.33 sec).

### Repro Steps

Please try any issue on below one   The nupkg at 'https://api.nuget.org/v3-flatcontainer/system.linq.async/6.0.1/system.linq.async.6.0.1.nupkg' is not valid.
    End of Central Directory record could not be found.

### Expected Behavior

All the packages should be restored automatically

**Comment by erdembayar** [comment]
Thank you for filing the issue. It looks like a connectivity issue rather than a NuGetGallery bug. Please try with a different connection. If the problem still persists, then please file a support request through https://www.nuget.org/policies/Contact.
