### ISSUE TITLE
[NuGet.org Bug]: Cannot change organization email to email associated with Microsoft account

### ISSUE THREAD

**Issue by LL-SRN** [NuGet/NuGetGallery#9946]
### Impact

It's more difficult to complete my work

### Describe the bug

When changing the email address associated with an organization, if the new email address is associated with a microsoft account, the address change workflow fails because a nuget account is created for that email address so it can no longer be used as an organization email address.

### Repro Steps

Prerequisites:

- existing Nuget organization $ORGANIZATION
- email address $ADDRESS that is associated with a Microsoft account but not with a nuget account

1. Go to https://www.nuget.org/organization/$ORGANIZATION/ChangeEmail
2. insert $ADDRESS under "New Email Address" and press "save"
3. in mailbox for $ADDRESS, receive email with confirmation link
4. open confirmation link in browser
5. on opening link, receive request to select which Microsoft account you wish to associate with nuget
6. select $ADDRESS
7. Error message, approximately "cannot use account, already a nuget account"

### Expected Behavior

1. Go to https://www.nuget.org/organization/$ORGANIZATION/ChangeEmail
2. insert $ADDRESS under "New Email Address" and press "save"
3. in mailbox for $ADDRESS, receive email with confirmation link
4. open confirmation link in browser
5. $ADDRESS is now the email address associated with the nuget organization

### Additional Context and logs

Possibly associated with this issue: https://github.com/NuGet/NuGetGallery/issues/8616

**Comment by erdembayar** [comment]
Sign in from https://www.nuget.org/policies/Contact and send request from there, we need to see email in question, it's hard to reason for now.

**Comment by erdembayar** [comment]
We're closing this issue, please use above instruction to contact us
