### ISSUE TITLE
[Dark Theme Bug Bash] Dark them extra copy button creates extra `Copy` text

### ISSUE THREAD

**Issue by erdembayar** [NuGet/NuGetGallery#9956]
### Impact

It bothers me. A fix would be nice

### Describe the bug

Edge browser
1. Enable dark theme and go to package then press copy
![image](https://github.com/NuGet/NuGetGallery/assets/8766776/4effe44e-f53d-4940-9f4c-98d0a3ce2225)
2. Paste in Notepad, you'll see extra `Copy` text, but you wouldn't see it if you do it on nuget.org with the current theme.
![image](https://github.com/NuGet/NuGetGallery/assets/8766776/c5dafd10-a07e-4cf6-bfa2-e6acf74efcfc)
3. Same bug can repro for all other tabs such as `Package Manger`, `PackageReference` etc.

### Repro Steps

Edge browser with dark theme https://dev.nugettest.org/packages/e2e.semver2prerel.240506.234617.5383287/ or any other package

### Expected Behavior

No extra `Copy` text in new line besides `dotnet add package xxx`

**Comment by JonDouglas** [comment]
Can confirm. I get `dotnet add package Newtonsoft.Json --version 13.0.4                
                    
                        
                        Copy`
