### ISSUE TITLE
[NuGet.org Bug]: Dark mode contrast with dark images

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/NuGetGallery#9957]
### Impact

It bothers me. A fix would be nice

### Describe the bug

<img width="1465" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/1288848/045b30d8-d834-4f61-b4ae-ceba634662cb">

Some package icons and backgrounds are a bit hard to see in dark mode compared to light mode.

### Repro Steps

1. Open https://dev.nugettest.org/packages/Newtonsoft.Json

### Expected Behavior

NuGet.org sidebar should contrast well regardless of theme. Background on prefix reservation is just a nit in dark mode.

Package icons may encourage authors to update their icons to be light/dark theme compatible.

**Comment by martinrrm** [comment]
@JonDouglas This are the icons that have a problem: API Key icon, default package icon, and the Prefix Reserved icon.

Source repository icon is from git, they have a red one that I'll use for Dark mode.

![image](https://github.com/NuGet/NuGetGallery/assets/43253759/fb6351da-8c27-4d3e-91a0-68a9a1d8cbdf)
![image](https://github.com/NuGet/NuGetGallery/assets/43253759/3e74e21b-894e-4e83-8b98-47c742362787)
